### PR TITLE
fix: reset lockedQuote even when nothing will be auctioned

### LINKED ISSUE #8041: Vaults - lockedQuote not resetting when no vaults to auction
## Describe the bug
When there are no vaults to be put up for auction, the vault manager's `lockedQuote` will not be reset at the start of the auction.

## To Reproduce
1. Start a local chain (`cd packages/deployment/upgrade-test && make build run`)
2. Query the vault metrics (`agd query vstorage data published.vaultFactory.managers.manager0.metrics`)
3. Observe the `lockedQuote` is defined right after the start of the auction, through the start of the next auction

## Expected behavior
`lockedQuote` is undefined right after the start of the auction, until the next price lock period before the next auction.

## Additional context
This is likely because the contract [does an early return](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/src/vaultFactory/vaultManager.js#L1093-L1098) when there are no vaults to liquidate. It should publish the metrics with the undefined `lockedQuote` first instead.

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #8041

## Description

When there were no vaults to be liquidated, we exited early, and missed the step of reseting the locked quote. This fixes that oversight.

### Security Considerations

None

### Scaling Considerations

None

### Documentation Considerations

None

### Testing Considerations

Appropriate tests were sensitive to the change and had to be updated.

### CODE REVIEW

File: packages/inter-protocol/src/vaultFactory/vaultManager.js [hunk 1]
```diff
@@ -1094,6 +1094,7 @@ export const prepareVaultManagerKit = (
           state.lockedQuote = undefined;
 
           if (vaultData.getSize() === 0) {
+            void helper.writeMetrics();
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/vaultManager.js:1104]: on line 1160 it awaits before returning. Which is correct?

also that one superfluously references `facets`.

File: packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js [hunk 2]
```diff
@@ -939,8 +939,17 @@ test('liquidate two loans', async t => {
     manualTimer,
   );
 
-  totalDebt += 7n;
+  totalDebt += 6n;
   await aethVaultMetrics.assertChange({
+    lockedQuote: null,
```
Comment (turadg) [inline packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js:954]: 👍

File: packages/inter-protocol/src/vaultFactory/vaultManager.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/vaultManager.js:1104]: > on line 1160 it awaits before returning. Which is correct?

There were more calls that said `void` than `await`, so ...   No, that's not a good justification.

I don't see any reason that the calling environment wants to respond to the result or wait for it to finish, so I changed them all to `void`.

> also that one superfluously references facets.

fixed

**Review by turadg — APPROVED** [review]
