### PR TITLE
fix(bundle-source): fix comment misparse, make require optional

### LINKED ISSUE #362: Update moduleFormat so that `require` is not needed as an endowment
There is a suspicious `require` endowment needed in:

_Posted by @erights in https://github.com/Agoric/agoric-sdk/pull/355_
> `const zoe = makeZoe({ require });`

As @michaelfig says below, when we upgrade the moduleFormat, we should not need to pass `require` anymore.

### LINKED ISSUE #1281: bug: bundle-source generates invalid bundle
**Describe the bug**
`bundle-source` creates an invalid bundle when transforming the below text
```js
// below is the bad voodoo
//         */
// above is the bad voodoo
```
the javascript is transformed into the following invalid code with error
`SyntaxError: Unexpected token '*'`

```js
"(function getExport(require, exports) {   'use strict';   const module = { exports };     

'use strict'; /* below is the bad voodoo*/ /* */*/ /* above is the bad voodoo*/
  return module.exports;
})
//# sourceURL=/bundled-source/bug.js
```

this can be found in the `zlib` package of 
[rollup-plugin-node-builtins](https://github.com/calvinmetcalf/rollup-plugin-node-builtins), specifically [here](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/blob/63ab8aacd013767445ca299e468d9a60a95328d7/src/es6/zlib-lib/deflate.js#L353)

### PR DESCRIPTION
**Pull request by michaelfig**
Closes: #1281, closes: #362

Now, the `require` endowment is optional.

Also, bundling `// */ BAD CODE` no longer evaluates `BAD CODE`.

### CODE REVIEW

File: packages/bundle-source/src/index.js [hunk 1]
```diff
@@ -309,7 +311,8 @@ function getExportWithNestedEvaluate(filePrefix) {
   ${computeExports}
 
   // Evaluate the entrypoint recursively, seeding the exports.
-  return computeExports(entrypoint, { require }, {});
+  const systemRequire = typeof require === 'undefined' ? undefined : require;
```
Comment (warner) [inline packages/bundle-source/src/index.js:314]: Looks fine, but does this behave differently than just `const systemRequire = require;`? Is `typeof` exempt from some sort of referencing-missing-name warning or something?

File: packages/bundle-source/test/sanity.js [hunk 2]
```diff
@@ -105,7 +104,7 @@ test('getExport', async t => {
 
     const nestedEvaluate = src => {
       // console.log('========== evaluating', src, '\n=========');
-      return evaluate(src, { require, nestedEvaluate });
+      return evaluate(src, { nestedEvaluate });
```
Comment (warner) [inline packages/bundle-source/test/sanity.js:107]: If we *did* want to pass `require` in, is there still a test that exercises that? I'm probably ok if we remove that feature entirely, but we should do it consciously, and if it stays in, we should test it.

**Review by warner — APPROVED** [review]
looks good, but think about the questions briefly

File: packages/bundle-source/src/index.js [hunk 3]
```diff
@@ -122,7 +122,9 @@ export default async function bundleSource(
         .replace(HTML_COMMENT_START_RE, '<!X-')
         .replace(HTML_COMMENT_END_RE, '-X>')
         // ...replace import expressions with a defanged version to pass SES restrictions.
-        .replace(IMPORT_RE, 'X$1$2');
+        .replace(IMPORT_RE, 'X$1$2')
+        // ...replace end-of-comment markers
+        .replace(/\*\//g, '*X/');
```
[the remark this answers is not in the document]
Comment (michaelfig) [reply packages/bundle-source/src/index.js:127]: Yes, JS doesn't nest comments.  I'll add a test that demonstrates it.

File: packages/bundle-source/src/index.js (hunk 1 above)
Comment (michaelfig) [reply packages/bundle-source/src/index.js:314]: Yes, typeof is exempt from `ReferenceError`.

File: packages/bundle-source/test/sanity.js (hunk 2 above)
Comment (michaelfig) [reply packages/bundle-source/test/sanity.js:107]: We need the `require` feature for deploy scripts.  It is tested during integration.

**Review by FUDCo — APPROVED** [review]
Seems fine, though I instinctively distrust anything that uses regular expressions :-)

File: packages/bundle-source/src/index.js (hunk 1 above)
Comment (michaelfig) [reply packages/bundle-source/src/index.js:314]: Do note, though, that `ReferenceError` is not a "warning", it is a thrown exception.  `const systemRequire = require;` will throw `ReferenceError` if `require` is not declared.

You are not allowed to have undeclared variables in strict JS except in `typeof XXX`.  Sloppy mode allows you to assign to undeclared variables (which become globals), but IIUC that's the only exception (@erights will weigh in if I'm wrong).

Our SES `sloppyGlobals` mode gets this wrong because there's no way to completely emulate the sloppy behaviour using the 8 magic lines.

File: packages/bundle-source/test/sanity.js (hunk 2 above)
Comment (michaelfig) [reply packages/bundle-source/test/sanity.js:107]: I'll add a unit test for this, too.

File: packages/bundle-source/demo/trailing-comment.js [hunk 4]
```diff
@@ -12,3 +12,5 @@ export function buildRootObject() {
 }
 // comment
 // */ fooBarBaz!
+
+// /*
```
Comment (warner) [inline packages/bundle-source/demo/trailing-comment.js]: I'd be slightly more reassured if the comment-opener test were in a separate file, so it couldn't interact with the comment-closer test nearby.
