### PR TITLE
fix(inter-protocol): ensure PSM availability after staging failure

### LINKED ISSUE #6096: failed PSM trade prevents further service due to inconsistent seat staging
## Describe the bug

After accidentally trying to buy AUSD whent he PSM had none, attempts to trade 20 IST for USDC result in a refund rather than a trade.

## To Reproduce

In `agoricollinet-22`, check wallet balances and then attempt to trade 20 IST for USDC:

```
$ psm-tool --net ollinet --wallet $addr
{
  "balances": [
    [null,"zoe invite"],
    [1.99747,"AUSD"],
    [0,"BLD"],
    [46.800225,"IST"]
  ],
...
}

$ psm-tool --giveStable 20 --boardId $psmInstance --feePct 0.05 >,give20.json
$ agd --from=k1 tx swingset wallet-action --allow-spend "$(cat ,give20.json)"  --node https://ollinet.rpc.agoric.net:443 --chain-id agoricollinet-22 -y
code: 0
...
txhash: 07A7B0CCCD655F0EF2F8ED566380E23D23D6D665B0308671346A250880C6F3FF
```

Note that 20 IST is withdrawn for this trade:
```
$ psm-tool --net ollinet --wallet $addr
{
  "balances": [
    [null,"zoe invite"],
    [1.99747,"AUSD"],
    [0,"BLD"],
    [26.800225,"IST"]
  ],
  "offers": [
    ["2022-08-31T14:25:13.203Z","pending","psm","giveStable",{"give":{"In":[20,"IST"]},"want":{"Out":[19.990005,"AUSD"]}}]
  ]
}
```

But then it gets refunded:
```
$ psm-tool --net ollinet --wallet $addr
{
  "balances": [
    [null,"zoe invite"],
    [1.99747,"AUSD"],
    [0,"BLD"],
    [46.800225,"IST"]
  ],
  "offers": [
    ["2022-08-31T14:25:13.203Z","accept","psm","giveStable",{"give":{"In":[20,"IST"]},"want":{"Out":[19.990005,"AUSD"]}}]
  ]
}
```

Use metrics to check PSM pool balance:
```
$ agoric follow -B https://ollinet.agoric.net/network-config :published.psm.IST.AUSD.metrics
{
  anchorPoolBalance: {
    brand: slot(0,"Alleged: AUSD brand"),
    value: 23002530n,
  },
  feePoolBalance: {
    brand: slot(1,"Alleged: IST brand"),
    value: 2305n,
  },
  totalAnchorProvided: {
    brand: slot(0),
    value: 0n,
  },
  totalStableProvided: {
    brand: slot(1),
    value: 23002530n,
  },
}
```

## Expected behavior

Take my money! And give me USDC in return :)

## Platform Environment
ollinet, which is running [1af6550](https://github.com/Agoric/agoric-sdk/commit/1af6550688343129d5a458e7220898a86dd5503f)

cc @turadg @dtribble 

blocking #6064

### PR DESCRIPTION
**Pull request by dckc**
closes: #6096

## Description

When an attempt to trade IST for anchor/reference token fails due to lack of anchor funds in the PSM, seat stagings were left in an inconsistent state, preventing further service. This fix clears the seat stagings on failure.

@erights @Chris-Hibbert this also includes a couple zoe tweaks that @dtribble helped me with.

### Security Considerations

availability is good :)

### Testing Considerations

added a reasonably thorough unit test

### CODE REVIEW

File: packages/inter-protocol/src/psm/psm.js [hunk 1]
```diff
@@ -160,11 +160,24 @@ export const start = async (zcf, privateArgs, baggage) => {
...
+        { Anchor: maxAnchor },
+        { Out: maxAnchor },
+      );
+      zcf.reallocate(seat, anchorPool, stage, feePool);
+      stableMint.burnLosses({ Stable: afterFee }, stage);
+    } catch (e) {
+      stage.clear();
+      anchorPool.clear();
+      feePool.clear();
+      // NOTE someday, reallocate should guarantee that this case cannot happen
```
Comment (turadg) [inline packages/inter-protocol/src/psm/psm.js]: ticket? we probably will want to reference it often and it can serve to teach why and when to clear.

File: packages/inter-protocol/src/psm/psm.js [hunk 2]
```diff
@@ -183,12 +196,15 @@ export const start = async (zcf, privateArgs, baggage) => {
...
-    stageTransfer(stage, feePool, { Stable: fee });
     try {
+      stageTransfer(seat, anchorPool, { In: given }, { Anchor: given });
+      stageTransfer(stage, seat, { Stable: afterFee }, { Out: afterFee });
+      stageTransfer(stage, feePool, { Stable: fee });
       zcf.reallocate(seat, anchorPool, stage, feePool);
     } catch (e) {
+      stage.clear();
+      anchorPool.clear();
+      feePool.clear();
```
Comment (turadg) [inline packages/inter-protocol/src/psm/psm.js:206]: could we codify this pattern now with a contract helper? something like,
```js
atomicReallocate(zcf, [
  [seat, anchorPool, { In: given }, { Anchor: given }],
  [stage, seat, { Stable: afterFee }, { Out: afterFee }],
  [stage, feePool, { Stable: fee }],
]);
```

File: packages/inter-protocol/test/psm/test-psm.js [hunk 3]
```diff
@@ -209,29 +213,49 @@ async function makePsmDriver(t, customTerms) {
       return feePayoutAmount;
     },
 
-    /** @param {Amount<'nat'>} giveAnchor */
-    async swapAnchorForStable(giveAnchor) {
+    /**
+     * @param {Amount<'nat'>} giveAnchor
+     * @param {Amount<'nat'>} [wantStable]
+     * @param {*} [out]
```
Comment (turadg) [inline packages/inter-protocol/test/psm/test-psm.js]: yay for typing. this param would benefit from more docs:
```
```suggestion
     * @param {{seat: UserSeat, offerResult: *}} [out] will be filled
```

Comment (turadg) [reply packages/inter-protocol/test/psm/test-psm.js]: But I find the need for this suspicious. This function is returning payouts to abstract away seat and offerResult… but here we are needing to punch through. Will contract users need to also? If so we should just change the return type to hide less: `{seat, offerResult, payouts}`.

Or would it be sufficient to have `{numWantsSatisfied, payouts}`?

File: packages/inter-protocol/test/psm/test-psm.js [hunk 4]
```diff
@@ -305,6 +329,112 @@ test('limit', async t => {
...
+    const expectedAnchor = AmountMath.make(
+      anchor.brand,
+      minusStableFee(giveRun).value,
+    );
+    t.deepEqual(actualAnchor, expectedAnchor);
+  };
+
+  let ix = 0;
+  for (const [kind, give, want, result] of trades) {
+    switch (kind) {
```
Comment (turadg) [inline packages/inter-protocol/test/psm/test-psm.js]: this data driven test calls for [Ava macros](https://github.com/avajs/ava/blob/main/docs/01-writing-tests.md#reusing-test-logic-through-macros).  See https://github.com/Agoric/agoric-sdk/pull/5900

File: packages/zoe/src/contractFacet/zcfSeat.js [hunk 5]
```diff
@@ -335,7 +337,7 @@ export const createSeatManager = (
         );
         return amountKeywordRecord;
       },
-      clear: ignoreContext(clear),
+      clear: ({ self }) => clear(self),
```
Comment (turadg) [inline packages/zoe/src/contractFacet/zcfSeat.js]: just parroting the linter here: gotta remove the `ignoreContext` import

File: packages/zoe/src/contractFacet/zcfSeat.js [hunk 6]
```diff
@@ -114,7 +114,9 @@ export const createSeatManager = (
   };
 
   const clear = zcfSeat => {
-    zcfSeatToStagedAllocations.delete(zcfSeat);
+    if (zcfSeatToStagedAllocations.has(zcfSeat)) {
```
Comment (turadg) [inline packages/zoe/src/contractFacet/zcfSeat.js]: this is a change to the throw behavior of `clear`. was the earlier behavior documented or tested?

I'll go google it since [our API docs aren't on the APIs](https://github.com/Agoric/agoric-sdk/issues/4291) ;-) https://docs.agoric.com/zoe/api/zoe-contract-facet.html#zcfseat-clear Nope.

File: packages/inter-protocol/src/psm/psm.js (hunk 1 above)
Comment (dckc) [reply packages/inter-protocol/src/psm/psm.js]: Dunno. That comment pre-dates this PR.

Comment (turadg) [reply packages/inter-protocol/src/psm/psm.js]: Ok. Since it's written in this contract twice and relevant to other contracts, I'm requesting a ticket to document the footgun and that it be referenced from the places like this that say "someday…"

File: packages/inter-protocol/test/psm/test-psm.js (hunk 3 above)
Comment (dckc) [reply packages/inter-protocol/test/psm/test-psm.js]: Yes, I was too lazy to change the other call sites. Returning just the seat might be most straightforward.

File: packages/inter-protocol/test/psm/test-psm.js (hunk 4 above)
Comment (dckc) [reply packages/inter-protocol/test/psm/test-psm.js]: Note that the items have to be used within one test. The whole point is to *not* make a new PSM between them. Do macros work that way?

Comment (turadg) [reply packages/inter-protocol/test/psm/test-psm.js]: usually things that need be shared between tests are configured with `before` and `beforeEach`. but I won't block on this.

File: packages/zoe/src/contractFacet/zcfSeat.js (hunk 6 above)
Comment (Chris-Hibbert) [reply packages/zoe/src/contractFacet/zcfSeat.js]: Not only are there no tests for `clear`, there appear to be [no tests for zcfSeat](https://agoric-sdk-coverage.netlify.app/#file/desc/false/true/true/true/zoe%2Fsrc%2FcontractFacet/).  

[not suggesting this PR add anything.]

File: packages/inter-protocol/test/psm/test-psm.js [hunk 7]
```diff
@@ -305,6 +329,112 @@ test('limit', async t => {
   // t.throwsAsync(() => await E(seat1).getOfferResult());
 });
 
+/** @type {[kind: 'want' | 'give', give: number, want: number, result: number | false][]} */
+const trades = [
+  ['give', 200, 190, false],
+  ['want', 101, 100, 1],
+  ['give', 50, 50, false],
+  ['give', 51, 50, 1],
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/test/psm/test-psm.js]: Even though I've been working with JS for a  couple years now, seeing `false` and `1` as two possible values of a flag strikes me as wrong.

File: packages/inter-protocol/src/psm/psm.js [hunk 8]
```diff
@@ -160,11 +160,24 @@ export const start = async (zcf, privateArgs, baggage) => {
       AmountMath.isGTE(maxAnchor, wanted),
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/src/psm/psm.js:159]: Does the TODO on line 158 interact with the current problem at all? Can it be updated?

File: packages/inter-protocol/src/psm/psm.js (hunk 2 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/psm/psm.js:206]: I think it needs an `onFail:` clause to invoke `burnLosses`

File: packages/zoe/src/contractFacet/zcfSeat.js (hunk 5 above)
Comment (turadg) [reply packages/zoe/src/contractFacet/zcfSeat.js]: though, why delegate here at all? we can delete the `const clear` above.
```suggestion
      clear: ({ self }) => {
          if (zcfSeatToStagedAllocations.has(self)) {
            zcfSeatToStagedAllocations.delete(self);
          }
      };
```

File: packages/inter-protocol/src/psm/psm.js (hunk 1 above)
Comment (dtribble) [reply packages/inter-protocol/src/psm/psm.js]: note that only one of the comments is valid (the one before the mintGains). The assert got copied to provide a better diagnostic, but the comment needs to be deleted.

File: packages/zoe/src/contractFacet/zcfSeat.js (hunk 5 above)
Comment (Chris-Hibbert) [reply packages/zoe/src/contractFacet/zcfSeat.js]: I think MarkM hinted at the right choice here. Please inline the method, so it'll be more apparent that the parameter handling is parallel to the sibling methods.

**Review by Chris-Hibbert — CHANGES_REQUESTED** [review]
I think there's more discussion going on, so I'm going to submit my current comments and wait to see how it settles before reviewing again.

File: packages/inter-protocol/test/psm/test-psm.js (hunk 4 above)
Comment (dckc) [reply packages/inter-protocol/test/psm/test-psm.js]: it needs to be shared between these trades but no other tests

Comment (turadg) [reply packages/inter-protocol/test/psm/test-psm.js]: then another file would work well. this `test` function is doing a lot of work to replicate some of the `before` and `macro` semantics.

File: packages/inter-protocol/src/psm/psm.js (hunk 2 above)
Comment (dckc) [reply packages/inter-protocol/src/psm/psm.js:206]: postponed to #6116

File: packages/inter-protocol/src/psm/psm.js (hunk 8 above)
Comment (dckc) [reply packages/inter-protocol/src/psm/psm.js:159]: we certainly have relevant tests; I'm getting rid of that TODO in favor of #6116

File: packages/inter-protocol/src/psm/psm.js (hunk 1 above)
Comment (dckc) [reply packages/inter-protocol/src/psm/psm.js]: added #6116 and cited it. I don't understand that issue very well, so I'd appreciate it if someone else would clarify the title / description. @michaelfig helped me a little.

File: packages/inter-protocol/test/psm/test-psm.js (hunk 3 above)
Comment (dckc) [reply packages/inter-protocol/test/psm/test-psm.js]: I refactored the driver to have additional methods that expose the seat.

File: packages/inter-protocol/test/psm/test-psm.js (hunk 4 above)
Comment (dckc) [reply packages/inter-protocol/test/psm/test-psm.js]: Let's punt on this for today.

**Review by turadg — APPROVED** [review]
LGTM given https://github.com/Agoric/agoric-sdk/issues/6116 (which I've added to PSM audit release)

File: packages/inter-protocol/test/psm/test-psm.js [hunk 9]
```diff
@@ -179,6 +183,42 @@ async function makePsmDriver(t, customTerms) {
...
+  /**
+   * @param {Amount<'nat'>} giveAnchor
+   * @param {Amount<'nat'>} [wantStable]
+   */
+  const swapAnchorForStableSeat = async (giveAnchor, wantStable) => {
+    const seat = E(zoe).offer(
+      E(publicFacet).makeWantStableInvitation(),
+      harden({
+        give: { In: giveAnchor },
+        ...(wantStable ? { want: { Out: wantStable } } : {}),
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/test/psm/test-psm.js:195]: I like this.  It's a definite improvement on my approach of making the proposal, and then adding the want later.

File: packages/inter-protocol/test/psm/test-psm.js [hunk 10]
```diff
@@ -305,6 +340,108 @@ test('limit', async t => {
   // t.throwsAsync(() => await E(seat1).getOfferResult());
 });
 
+/** @type {[kind: 'want' | 'give', give: number, want: number, ok: boolean, wants?: number][]} */
+const trades = [
+  ['give', 200, 190, false],
+  ['want', 101, 100, true, 1],
+  ['give', 50, 50, false],
+  ['give', 51, 50, true, 1],
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/test/psm/test-psm.js:348]: I get what this is doing now, but only because of side conversations about ava macros. It would be nice if it said that the first line was intended to fail because the PSM doesn't have any anchor until after a `want` completes. Does the third fail because it doesn't include fees?

**Review by Chris-Hibbert — APPROVED** [review]

File: packages/inter-protocol/src/psm/psm.js (hunk 2 above)
Comment (erights) [reply packages/inter-protocol/src/psm/psm.js:206]: Progress on #6116 at #6577 , where `stageMgr.commit()` replaces `zcf.reallocate(...)` and does guarantee that all staging are cleared, whether the commit succeeded or failed.

@dtribble 's suggested `stageMgr.transfer` operation is much like @turadg 's rows of `atomicReallocate` above. The contrast between the list and the reified stageMgr is approx the contrast between https://github.com/Agoric/agoric-sdk/pull/6577 and https://github.com/Agoric/agoric-sdk/pull/4327
