### PR TITLE
fix: improve error messages for mintGains and burnLosses

### LINKED ISSUE #1708: ZCFMint.mintGains and ZCFMint.burnLosses should have better error messages
The error messages if no arguments are provided is currently:

```js
test(`zcf.makeZCFMint - mintGains`, async t => {
  const { zcf } = await setupZCFTest();
  const zcfMint = await zcf.makeZCFMint('A', MathKind.SET);
  // TODO: create seat if one is not provided
  // https://github.com/Agoric/agoric-sdk/issues/1696
  // @ts-ignore
  t.throws(() => zcfMint.mintGains(), {
    message: 'On demand seat creation not yet implemented',
  });
});

test(`zcf.makeZCFMint - burnLosses`, async t => {
  const { zcf } = await setupZCFTest();
  const zcfMint = await zcf.makeZCFMint('A', MathKind.SET);
  // @ts-ignore
  t.throws(() => zcfMint.burnLosses(), {
    message: "Cannot read property 'getCurrentAllocation' of undefined",
  });
});
```
We should improve these error messages.

### PR DESCRIPTION
**Pull request by katelynsills**
Improve the error messages for mintGains and burnLosses

Closes #1708

### CODE REVIEW

File: packages/zoe/src/contractFacet/contractFacet.js [hunk 1]
```diff
@@ -217,12 +217,21 @@ export function buildRootObject(_powers, _params, testJigSetter = undefined) {
           return mintyIssuerRecord;
         },
         mintGains: (gains, zcfSeat = undefined) => {
+          assert.typeof(
+            gains,
+            'object',
+            details`gains ${gains} must be an object`,
```
Comment (Chris-Hibbert) [inline packages/zoe/src/contractFacet/contractFacet.js]: while this is true, we can helpfully say more. 
```suggestion
            details`gains ${gains} must be an amountKeywordRecord`,
```

**Review by Chris-Hibbert — APPROVED** [review]
