### PR TITLE
fix: step towards stratifying customDetails

### LINKED ISSUE #5903: Invitation amounts should include terms
Background on invitation amount namespace collision:
   * An invitation amount is a record that combines properties according to zoe/zcf, with so-called customProperties that are according to the contract.
   * These two sources of properties share one namespace, with the bindings according to zoe/zcf silently taking precedence if they collide.
   * Thus, extending the properties provided by zoe/zcf may make previously correct contracts incorrect, by overwriting customProperties binding they had been legitimately using.

Background on terms and amount patterns:
   * Currently the `want` in a proposal must be an amount. However, we wish to upgrade it to eventually be an amount pattern. The covered call is a great motivating use case. Fred may simply want an instance of a given covered call installation with a certain parameterization. For the covered call specifically, this parameterization is included in the customProperties, but that is bespoke to a given contract.
   * In general, the terms are necessary to understand the meaning of a given contract instance.
   * The terms of a contract instance are publicly available to anyone who knows the instance.
   * Without knowing which instance he wants, Fred would be unable to express a `want` that constrains the values of an invitation's contract's terms.

To solve the second problem, we should add a `terms` property to the invitation amount properties that are according to zoe/zcf, and therefore reliable. These could be the terms snapshot as of the time the contract was created, or more plausibly snapshot at the time this invitation was created. (Frankly it is a bit weird that an instance's terms can change over time. This makes sense because the term namespace is similarly split, which a similar silent override on collision. We should revisit this too.)

But adding a `term` properties faces us with the first problem. It is early enough that we could add it anyway. But it would be better to take the opportunity to address the first problem as well, so that we don't face it again the next time we want to add a property to the terms. (Though *any* change to amount representations will present hard upgrade problems that might deter us from doing it post-deploy anyway.)

I propose we `terms` and `customProperties` as top level properties, where all the custom properties are properties of the record value of the `customProperties` field, without worry about collision. We cannot simply remove the flattening of the non-colliding customProperties via `...customProperties`. Nor can we `@deprecate` it because there's no specific flattened property names to deprecate. But we should explain and document it as deprecated, encouraging old code to switch to using the `customProperties` property explicitly.

Note that anything included in amounts must be a valid `Key`, which excludes promises, errors, and patterns. Also that they must pass `canBeDurable`, since ERTP stores amounts in durable storage. These two changes are synergistic, in that durability also requires us to omit promises, which is where we expect to pay all the transition costs. As part of making Zoe durable, we expect to require terms to be durable anyway, so this is an opportune time to do both.

### PR DESCRIPTION
**Pull request by erights**
The `customProperties` argument to `makeInvitation` has been renamed `customDetails`. This itself is not an API change, since, prior to this PR, the `customProperties` record, if any was spread out into the `invitationDetails`. But this spreading mixes the namespaces of names according to Zoe vs names according to the contract. It would prevent us from adding more names-according-to-Zoe to the invitation details over time.

This PR adds an explicit `customDetails` property to the `invitationDetails` record. But to avoid breaking things, it does yet remove the redundant spread form. The next PR #7067 does so, to be merged once all uses of the deprecated spread form are removed.

Would enable us to fix https://github.com/Agoric/agoric-sdk/issues/5903

### CODE REVIEW

File: packages/swingset-runner/demo/zoeTests/vat-dave.js [hunk 1]
```diff
@@ -85,21 +87,23 @@ const build = async (log, zoe, issuers, payments, installations, timer) => {
...
       // with the following rules:
-      keyEQ(invitationValue[0].asset, optionAmounts) ||
+      keyEQ(invitationValue[0].customDetails?.asset, optionAmounts) ||
         Fail`asset is the option`;
-      keyEQ(invitationValue[0].price, bucks(1n)) || Fail`price is 1 buck`;
+      keyEQ(invitationValue[0].customDetails?.price, bucks(1n)) ||
+        Fail`price is 1 buck`;
       const optionValue = optionAmounts.value;
+      const { customDetails } = optionValue[0];
+      assert(typeof customDetails === 'object');
```
Comment (Chris-Hibbert) [inline packages/swingset-runner/demo/zoeTests/vat-dave.js]: Why not move this above lines 90 and 92 and use this name there as well.

File: packages/zoe/src/zoeService/zoeStorageManager.js [hunk 2]
```diff
@@ -257,22 +259,31 @@ export const makeZoeStorageManager = (
...
+          const extraProperties =
+            typeof customDetails === 'object' &&
+            ownKeys(customDetails).length >= 1
+              ? harden({
+                  // @ts-expect-error of course it is an object here.
+                  ...customDetails, // At least deprecated. Use stratified
+                  customDetails,
+                })
+              : harden({});
+          // If the contract-provided `customDetails` include the properties
```
Comment (Chris-Hibbert) [inline packages/zoe/src/zoeService/zoeStorageManager.js:278]: After #7067, this paragraph will no longer be needed, right?

File: packages/zoe/src/zoeService/zoeStorageManager.js [hunk 3]
```diff
@@ -257,22 +259,31 @@ export const makeZoeStorageManager = (
...
           const { state } = this;
 
-          // If the contract-provided `customProps` include the properties
+          const extraProperties =
+            typeof customDetails === 'object' &&
+            ownKeys(customDetails).length >= 1
+              ? harden({
+                  // @ts-expect-error of course it is an object here.
+                  ...customDetails, // At least deprecated. Use stratified
+                  customDetails,
```
Comment (Chris-Hibbert) [inline packages/zoe/src/zoeService/zoeStorageManager.js:275]: If #7067 isn't expected to be merged immediately, there should be a TODO here referencing that change.

File: packages/zoe/test/unitTests/contracts/test-callSpread.js [hunk 4]
```diff
@@ -96,9 +96,12 @@ test('fundedCallSpread below Strike1', async t => {
     terms,
   );
 
-  const invitationDetail = await E(zoe).getInvitationDetails(creatorInvitation);
-  const longOptionAmount = invitationDetail.longAmount;
-  const shortOptionAmount = invitationDetail.shortAmount;
+  const { customDetails } = await E(zoe).getInvitationDetails(
+    creatorInvitation,
+  );
+  assert(typeof customDetails === 'object');
```
Comment (Chris-Hibbert) [inline packages/zoe/test/unitTests/contracts/test-callSpread.js:102]: Would it make sense for Zoe to export an `assertCustomDetails()` function to be used in all these places? For now, it could contain a `mustMatch()` clause that asserts it's an object, but if we nailed down the semantics of a particular keyword within `customDetails`, `assertCustomDetails()` could additionally enforce that.

... actually, can't `getInvitationDetails()` enforce that, so the clients don't have to check?

**Review by Chris-Hibbert — CHANGES_REQUESTED** [review]
Looks good. Some changes requested.

File: packages/swingset-runner/demo/zoeTests/vat-dave.js (hunk 1 above)
Comment (erights) [reply packages/swingset-runner/demo/zoeTests/vat-dave.js]: These are two different `customDetails`: this one is from `optionValue[0]` and the ones above from `invitationValue[0]`. But I took the suggestion anyway, making them stylistically consistent using distinct names.

Done.

File: packages/zoe/src/zoeService/zoeStorageManager.js (hunk 2 above)
Comment (erights) [reply packages/zoe/src/zoeService/zoeStorageManager.js:278]: Good catch! I just removed it from #7067 . Done there.

File: packages/zoe/src/zoeService/zoeStorageManager.js (hunk 3 above)
Comment (erights) [reply packages/zoe/src/zoeService/zoeStorageManager.js:275]: Done

File: packages/zoe/test/unitTests/contracts/test-callSpread.js (hunk 4 above)
Comment (erights) [reply packages/zoe/test/unitTests/contracts/test-callSpread.js:102]: I made the property optional, so only invitationDetails that have non-empty customDetails have the property at all. Then I had to type is as optional in InvitationDetails. What would `getInvitationDetails` do that would be helpful?

The `assert(typeof` is only to let the type checker know that I know it is an object.

**Comment by erights** [comment]
PTAL

File: packages/zoe/test/unitTests/contracts/test-callSpread.js (hunk 4 above)
Comment (Chris-Hibbert) [reply packages/zoe/test/unitTests/contracts/test-callSpread.js:102]: > The assert(typeof is only to let the type checker know that I know it is an object

Understood. too bad it looks like it's trying to do more than that. okay.

> What would getInvitationDetails do that would be helpful?

I think there's nothing else helpful it could do.

**Review by Chris-Hibbert — APPROVED** [review]
LGTM

File: packages/zoe/test/unitTests/contracts/test-callSpread.js (hunk 4 above)
Comment (erights) [reply packages/zoe/test/unitTests/contracts/test-callSpread.js:102]: Cool. Resolving.
