### PR TITLE
fix(centralSupply): shutdown after providing bootstrap payment

### LINKED ISSUE #4795: centralSupply contract vat continues to run after bootstrap is done with it
It has access to `feeMintAccess`, i.e. the right to print RUN.

### PR DESCRIPTION
**Pull request by dckc**
closes: #4795

### CODE REVIEW

**Comment by dckc** [comment]
@warner @Chris-Hibbert any idea why the shutdown promise doesn't resolve?

```
~/projects/agoric/agoric-sdk/packages/run-protocol
14:18 connolly@jambox$ yarn test test/vaultFactory/test-bootstrapPayment.js -m '*exits'
yarn run v1.22.17
$ ava test/vaultFactory/test-bootstrapPayment.js -m '*exits'

  bootstrap payment - contract exits

    ℹ start...
    ℹ get pmt ...
    ℹ {
        pmt: Object @Alleged: RUN payment {},
      }

  Error: Promise returned by test never resolved
    at process.emit (node:events:520:28)
```

**Comment by dckc** [comment]
@warner thanks for the clue about `fakeVatAdmin`. 00ce476 seems to address it; what do you think?

File: packages/run-protocol/src/centralSupply.js [hunk 1]
```diff
@@ -31,7 +31,10 @@ export const start = async (zcf, { feeMintAccess }) => {
 
   return {
     creatorFacet: Far('creator', {
-      getBootstrapPayment: () => bootstrapPayment,
+      getBootstrapPayment: () => {
+        zcf.shutdown('payment retrieved');
+        return bootstrapPayment;
```
Comment (Chris-Hibbert) [inline packages/run-protocol/src/centralSupply.js]: shutdown is synchronous and seems to kill the containing vat. Can the function return anything after that? Does this only work in tests?

It's also counter to our approach for contracts to return payments from API methods rather than as payouts. Why are we doing it this way?

**Review by Chris-Hibbert — CHANGES_REQUESTED** [review]

File: packages/run-protocol/src/centralSupply.js (hunk 1 above)
Comment (dckc) [reply packages/run-protocol/src/centralSupply.js]: > It's also counter to our approach for contracts to return payments from API methods rather than as payouts. Why are we doing it this way?

I don't know. It predates this PR.

> shutdown is synchronous and seems to kill the containing vat. Can the function return anything after that?

If not, our other contracts don't work either; for example, `atomicSwap.js`:

```js
    const matchingSeatOfferHandler = matchingSeat => {
      const swapResult = swap(zcf, firstSeat, matchingSeat);
      zcf.shutdown('Swap completed.');
      return swapResult;
    };
```

`sellItems.js`:
```js
    if (AmountMath.isEmpty(getAvailableItems())) {
      zcf.shutdown('All items sold.');
    }
    return defaultAcceptanceMsg;
```

**Comment by warner** [comment]
> @warner thanks for the clue about `fakeVatAdmin`. [00ce476](https://github.com/Agoric/agoric-sdk/commit/00ce476e922033cf11f1c7ae18cec8240115bb2f) seems to address it; what do you think?

That looks like a good implementation of `vatPowers.exitVat` and `adminNode.done`.

File: packages/run-protocol/src/centralSupply.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/run-protocol/src/centralSupply.js]: I'd be surprised if anyone is currently looking for those results. 

OTOH, someone certainly wants the bootstrapPayment. If that's accessible outside of tests, then it works.

Comment (dckc) [reply packages/run-protocol/src/centralSupply.js]: > Why are we doing it this way?

@dtribble reminds us: offer handling used to have fees etc. that complicate things, and the plan is that they will again in due course.

**Review by Chris-Hibbert — APPROVED** [review]
LGTM.

Thanks for answering my questions
