### PR TITLE
fix: without assertKeyPattern

### LINKED ISSUE #1489: `assertKeyPattern(M.kind("null"))` fails with "null keys are not supported")
I observed when exploring https://github.com/Agoric/agoric-sdk/pull/6903#discussion_r1099042215 that a `'null'` case appears to be missing from matchKindHelper's [`checkKeyPattern`](https://github.com/endojs/endo/blob/686ab61802c0e5206b14f4b91d499e3873555cd4/packages/patterns/src/patterns/patternMatchers.js#L887) (e.g., `matches(undefined, M.kind("undefined"))` and `matches(null, M.kind("null"))` are both true, but `assertKeyPattern(M.kind("undefined"))` passes while `assertKeyPattern(M.kind("null"))` fails with "_null keys are not supported_"), but then realized that `kind` has no documentation and its purpose isn't quite clear. Do we really want to be conflating passStyleOf results with tagged record tags, and if so then which of them count as "key" patterns and which do not?

### LINKED ISSUE #6953: Big Stores act as if they accept non-scalars as keys
All the current store making functions, including all the big store making functions are named `makeScalar*` to be explicit that they only accept scalars as keys. A scalar is a Passable primitive value or a Remotable. Everything else should be rejected. This is an implementation restriction under the theory that are current implementation is not able to handle non-scalar keys.

But from https://github.com/Agoric/agoric-sdk/pull/6903#discussion_r1098025959 it seems like some of our big stores do handle non-scalar keys. Do they do so correctly? Do they do this by accident? Which is the bug: That they handle non-scalar keys, or that they are specified as not doing so? Which should be fixed?

### PR DESCRIPTION
**Pull request by erights**
Fixes: https://github.com/Agoric/agoric-sdk/issues/6953
Fixes: https://github.com/endojs/endo/issues/1489
A step towards fixing https://github.com/Agoric/agoric-sdk/issues/5263
Replaces https://github.com/endojs/endo/pull/1498
Replaces https://github.com/Agoric/agoric-sdk/pull/7034

Problem correctly diagnosed at https://github.com/Agoric/agoric-sdk/pull/6903#discussion_r1099042215 

Not only was `assertKeyPattern` broken, it also wasn't needed. At best, it was an optimization to turn 
`M.and(M.scalar(), patt)` into `patt` in the case where `patt` implied `M.scalar()`, i.e., the case where every specimen that would satisfy `patt` would necessarily also satisfy `M.scalar()`. But correctness before optimization.

It turns out that the implementation of virtual and durable stores already ***correctly*** accepts non-scalar keys. So, inside `collectionManager.js` I privately renamed and fixed them to reflect that. However, to not create any deviation from ***intended*** behavior as of this PR, I wrap these with the scalar store makers and export only them. 

This sets us up to easily expose non-scalar virtual stores later. Since this PR is not actually exposing the non-scalar stores, it also doesn't test that they are correctly non-scalar stores. I only validated this by a bit of manual testing and watching what happens under a debugger. At such a time that we do wish to expose non-scalar stores, we'll also need to implement non-scalar versions of the heap stores. This would start with the same trick: using `encodePassable` to encode the key into a sort-order preserving string. But it would need different, and non-trivial, logic for the embedded remotables. So exposed non-scalar stores remain hidden as of this PR.

Once this PR settles down, I'll make a corresponding PR to make the applicable changes identically to `@endo/patterns`

### CODE REVIEW

File: packages/SwingSet/test/virtualObjects/test-representatives.js [hunk 1]
```diff
@@ -387,7 +387,7 @@ test('virtual object gc', async t => {
     [`${v}.vs.vc.4.|entryCount`]: '0',
     [`${v}.vs.vc.4.|label`]: 'watchedPromises',
     [`${v}.vs.vc.4.|nextOrdinal`]: '1',
-    [`${v}.vs.vc.4.|schemata`]: vstr([M.string()]),
+    [`${v}.vs.vc.4.|schemata`]: vstr([M.and(M.scalar(), M.string())]),
```
Comment (erights) [inline packages/SwingSet/test/virtualObjects/test-representatives.js:390]: @FUDCo I "fixed" this test so that it passes, without really understanding what's going on. Did I change the test correctly?

File: packages/swingset-liveslots/test/test-initial-vrefs.js [hunk 2]
```diff
@@ -91,7 +91,8 @@ test('initial vatstore contents', async t => {
   t.deepEqual(kunser(JSON.parse(get(`vc.2.|schemata`))), scalarSchema);
   t.deepEqual(kunser(JSON.parse(get(`vc.3.|schemata`))), scalarSchema);
   // watchedPromises uses vref (string) keys
-  t.deepEqual(kunser(JSON.parse(get(`vc.4.|schemata`))), stringSchema);
+  const scalarStringSchema = [M.and(M.scalar(), M.string())];
+  t.deepEqual(kunser(JSON.parse(get(`vc.4.|schemata`))), scalarStringSchema);
```
Comment (erights) [inline packages/swingset-liveslots/test/test-initial-vrefs.js:95]: @FUDCo I "fixed" this test so that it passes, without really understanding what's going on. Did I change the test correctly?

File: packages/swingset-liveslots/test/test-collections.js [hunk 3]
```diff
@@ -352,7 +352,15 @@ test('constrain set key shape', t => {
...
-test('bogus key shape', t => {
+// Prior to https://github.com/Agoric/agoric-sdk/pull/7035, virtual
+// stores did a sanity check on `keyShape` that it made sense for
+// scalar keys. However, that check was both broken and not otherwise
+// needed, so #7035 removed it. Instead, for scalar collections, the
+// key will *also* be checked for being a scalar. In cases like
+// `M.promise()`, without the error check, no possible key will pass
+// both conditions, and so such stores will always be empty. But
+// we don't need to treat this as an error.
+test.failing('bogus key shape', t => {
```
Comment (erights) [inline packages/swingset-liveslots/test/test-collections.js]: @FUDCo , is this loss of functionality ok with you? 

Note that the intended functionality never did work because of `assertKeyPattern` bugs, so this isn't loss of functionality that actually worked. For example, it would reject the `M.or(M.string(), M.promise())` below, but it would accept `M.any()` and `M.or(M.string(), M.any())`.

File: packages/SwingSet/test/virtualObjects/test-representatives.js (hunk 1 above)
Comment (FUDCo) [reply packages/SwingSet/test/virtualObjects/test-representatives.js:390]: This seems weird and wrong.  The table in question, created by a call to `makeScalarBigMapStore`,  has keys that are strictly strings and is declared as such in `swingset-liveslots/src/watchedPromises.js` (which is not one of the files changed in this PR).  I don't where the "AND scalar" part is creeping in, which suggests maybe something is broken here.

File: packages/swingset-liveslots/test/test-collections.js (hunk 3 above)
Comment (FUDCo) [reply packages/swingset-liveslots/test/test-collections.js]: This change seems fine, though I'll complain that you're violating a more general principle that it's unhelpful thus usually inappropriate for comments in code to remark upon the code's own history.  Nobody reading a piece of code cares what was there before.

File: packages/SwingSet/test/virtualObjects/test-representatives.js (hunk 1 above)
Comment (erights) [reply packages/SwingSet/test/virtualObjects/test-representatives.js:390]: Discussion with @FUDCo and @warner figured out the result above. The one with the `M.and(...)` is going through the normal scalarizing wrapper. The that just says `M.string()`  is using collectionManager's `provideBaggage` with bypasses the wrappers, since it is inside the module and already known that string implies scalar.

So resolving this conversation.

File: packages/swingset-liveslots/test/test-collections.js (hunk 3 above)
Comment (erights) [reply packages/swingset-liveslots/test/test-collections.js]: @FUDCo is certainly correct about the comment.

But in discussing this with @warner and @FUDCo , we do not have consensus on the new semantics that just intersects with `M.scalar()`. Neither do we have consensus on an error checking semantics. I believe we need a semantics more formalizable than either 
   * alert the user if it heuristically seems like they made a mistake
   * whatever the checking code actually happens to do is the semantics of the moment

Plus, I am still of the opinion that `assertKeyPattern` was not pulling its own weight. It was too much mechanism for too little benefit.

File: packages/swingset-liveslots/test/test-initial-vrefs.js (hunk 2 above)
Comment (FUDCo) [reply packages/swingset-liveslots/test/test-initial-vrefs.js:95]: Per our video conversation, yup.

Comment (erights) [reply packages/swingset-liveslots/test/test-initial-vrefs.js:95]: Thanks. Resolving.

**Comment by erights** [comment]
@FUDCo a failed test made it clear that our scalar big weak stores were not intended to exclude non-remotable, only non-scalars. So I changed it back to only and `M.scalar()` rather than `M.remotable(...)`.

**Comment by erights** [comment]
@warner added you to the reviewers, because you are.

File: packages/swingset-liveslots/src/collectionManager.js [hunk 4]
```diff
@@ -914,24 +909,88 @@ export function makeCollectionManager(
...
+  const narrowKeyShapeOption = (conjunct, options) => {
+    const { keyShape: baseKeyShape } = options;
+    // To prepare for pattern-based compression
+    // https://github.com/Agoric/agoric-sdk/pull/6432
+    // put the substantive pattern, if any, last in the `M.and` since
+    // an `M.and` pattern compresses only according to its last conjunct.
+    const keyShape =
+      baseKeyShape === undefined ? conjunct : M.and(conjunct, baseKeyShape);
+    return harden({ ...options, keyShape });
+  };
```
Comment (gibson042) [inline packages/swingset-liveslots/src/collectionManager.js]:
```suggestion
  /**
   * @param {Pattern} baseKeyShape
   * @param {StoreOptions} options
   * @returns {StoreOptions}
   */
  const narrowKeyShapeOption = (baseKeyShape, options) => {
    const { keyShape: keyShapeRestriction } = options;
    // To prepare for pattern-based compression
    // https://github.com/Agoric/agoric-sdk/pull/6432
    // put the substantive pattern, if any, last in the `M.and` since
    // an `M.and` pattern compresses only according to its last conjunct.
    const keyShape =
      keyShapeRestriction === undefined ? baseKeyShape : M.and(baseKeyShape, keyShapeRestriction);
    return harden({ ...options, keyShape });
  };
```

We might also consider a rename to `refineKeyShapeOption`, which has the (admittedly quite minor) benefit of not using a verb that can be confused for an adjective.

File: packages/store/src/types.js [hunk 5]
```diff
@@ -779,10 +770,4 @@
  * The left element must be before or the same rank as any possible
  * matching specimen. The right element must be after or the same
  * rank as any possible matching specimen.
- *
- * @property {(allegedPattern: Passable,
- *             check: Checker
- * ) => boolean} checkKeyPattern
- * Assumes this is the payload of a CopyTagged with the corresponding
- * matchTag. Is this a valid pattern for use as a query key or key shape?
```
Comment (gibson042) [inline packages/store/src/types.js:787]: Note that this part of agoric-sdk is still pending a resync with endo following https://github.com/endojs/endo/pull/1485 and https://github.com/endojs/endo/pull/1493 , which hasn't happened yet because I was planning to first address this same issue (albeit by means of replacing `checkKeyPattern` with a more general interface such as `isRefinementOf` rather than just dropping it... I like this approach better).

**Review by gibson042 — APPROVED** [review]
> Plus, I am still of the opinion that `assertKeyPattern` was not pulling its own weight. It was too much mechanism for too little benefit.

Agreed. I am very much in favor of removing it.

File: packages/store/src/types.js (hunk 5 above)
Comment (erights) [reply packages/store/src/types.js:787]: >  I like this approach better

You like which approach better? (Not clear which one "this" refers to)

File: packages/swingset-liveslots/src/collectionManager.js (hunk 4 above)
Comment (erights) [reply packages/swingset-liveslots/src/collectionManager.js]: Done.

I decided to keep "narrow" rather than "refine". The adjective reading leads in the same direction: it produces a narrower KeyShapeOption than it was given. To a formalist, the direction of "refine" is as clear. But to my non-formalist ears, the directionality of "narrow" is clearer.

File: packages/store/src/types.js (hunk 5 above)
Comment (gibson042) [reply packages/store/src/types.js:787]: I like the approach of this PR better, until/unless we need something more.

Comment (erights) [reply packages/store/src/types.js:787]: Thanks. Resolving.

**Comment by erights** [comment]
@FUDCo and @warner , I have approval from @gibson042 , as we both agree that `assertKeyPattern` was not pulling its weight. So if you want to block this from being merged in its current state without `assertKeyPattern`, please ***Request changes*** so we can keep track of what I need to do to satisfy your objections. I gotta do something, because this PR fixes bugs that need to be fixed.

If you don't want to block but "Approval" is too much, please just let me know and I'll proceed to merge based on @gibson042 's approval. Thanks.

**Comment by FUDCo** [comment]
I think there ought to be something doing `assertKeyPattern`'s job where we're using it, but it doesn't have to be this particular something and I don't think it's critical, so you can go ahead and merge as far as I'm concerned.

**Comment by erights** [comment]
@warner my memory is that @FUDCo 's opinion was strongly held, and your's was more weakly held. So with @FUDCo 's consent, I'm proceeding with this. Please let me know if I misread you.

File: packages/swingset-liveslots/test/test-collections.js (hunk 3 above)
Comment (erights) [reply packages/swingset-liveslots/test/test-collections.js]: With `assertKeyPattern` removed, this `test.failing` test case no longer made sense. Rather than fix the comment, I just deleted it.

Gone.
