### PR TITLE
Context building slog sender

### LINKED ISSUE #10269: context building slog sender
## What is the Problem Being Solved?

Our slog is a stream of structured events generated by the swingset kernel and the cosmic-swingset host. Most events actually come in pairs, with other events potentially temporally contained within them. These surrounding events create a context for the nested events, but for terseness and layering reasons, the data from this context is not always repeated within the nested events. When streaming slog entries as-is, this lack of context data on individual events makes it very difficult to query for related events.

Slog events are processed by "slog senders". The most basic one just writes the raw events to a jsonl file. We also have a `slog-to-otel` converter, but it attempts to create telemetry traces, which are great to represent the causality links in our execution model, but are too complex for simple querying of events. While the current implementation of that sender is due for a revamp (I have some local branches attempting this, and a short description of the design at https://github.com/Agoric/agoric-sdk/blob/mhofman/5724-otel-refactor/packages/telemetry/notes.txt), a more basic contextualizing log sender would enable more simple querying.

### Details of the slog entries

While slog events come mostly in pair, the context info we're interested in is not purely nested.

From the JS point of view, the execution is nested as follow:
- External event injected into swingset run queue (e.g. timer poll or cosmos message)
- Series of cranks, some resulting in deliveries to vats
- A delivery can contain a series of syscalls or console events

From the host point of view, we see the following events:
- kernel init (along with a bunch of nested events), one time, followed by a repeating series of block events:
- begin block (single event)
- end block, containing a series of run:
  - run 0 is always the continuation of any previous unfinished work
  - some runs for high priority messages
  - timer poll run
  - some runs for low priority messages
- commit block

A run contains a series of events described above detailing JS execution. If the cumulative amount of execution passes a threshold, the current run is suspended, and the end block completes. As such the events related to a JS execution to quiescence of swingset may be spread over multiple blocks. Also a cosmos message received in a given block may only execute in a later block.

We're interested in the ability to query events by both block and trigger events

## Description of the Design

A new slog sender building a context based on previously seen slog events, which streams these augmented events to a logging service which supports querying.

The context can be mostly ephemeral since a restart of the process will always start by processing a block from its beginning (after init). However the exception to this is the context of the trigger event, as the run 0 may continue execution that was started in a previous block. As such the latest trigger event context needs to be persisted (slog senders do not have access to the host DB, and need to arrange their own persistence).

We likely shouldn't tie the implementation to a specific log event receiver, and can likely leverage the otel logging libraries.

### Proposed details of slog event context builder

At any point there is a set of potential current **context** objects: **init**, **block**, **trigger**, **crank**, **replay**

These contexts merged together should be used as the base object for the attributes of the log record. Each slog events may have some fields extracted (removed) and instead included as extra log record attributes. The rest will be included as the body of the log record. Unless otherwise noted, the slog event is reported after and thus using the contexts that may have been updated using the event's data.

For all events, the `time` field is extracted from the slog event and used as timestamp of the log record. The `monotime` field is also extracted and used as a `process.uptime` attribute.

For the `kernel-init-start` event, build an **init context** with `init`: `true`, so that the nested events can easily be filtered out if necessary. Unset the **init context** after the `kernel-init-finish` event was reported.

For the `cosmic-swingset-begin-block` event, create a new **block context** formed as the following:
- `block.height`: `${blockHeight}`
- `block.time`: `${blockTime}`

Leave `blockHeight` and `blockTime` as body fields of the log record.

For the `cosmic-swingset-end-block-start` event, assert there is **block context**. Leave `blockHeight` and `blockTime` as body fields of the log record.
Restore any persisted **trigger context** immediately after reporting the end-block-start so it's available for run 0 events.

For the `cosmic-swingset-end-block-finish`, `cosmic-swingset-commit-start` and `cosmic-swingset-commit-finish` events, assert there is a **block context** and report normally.
For the `cosmic-swingset-after-commit-stats` event, report the event then unset the **block context**.

For the `cosmic-swingset-bootstrap-block-start` event, create a new **block context** formed as the following:
- `block.height`: `${blockHeight || 0}`
- `block.time`: `${blockTime}`

Create a **trigger context** formed as the following, but do not persist it:
- `run.id`: `bootstrap-${blockTime}`
- `run.trigger.type`: `bootstrap`
- `run.trigger.time`: `${blockTime}`

For the `cosmic-swingset-bootstrap-block-finish` event, report the event then unset the **block context** (the **trigger context** should already have been unset by the run-finish event).

For the `cosmic-swingset-bridge-inbound` or `cosmic-swingset-deliver-inbound` events, create and persist a **trigger context** formed as the following:
- `run.id`: `bridge-${inboundNum}` or `deliver-${inboundNum}`
- `run.trigger.type`: `bridge` or `deliver`
- `run.trigger.source`: `${source}` (for bridge)
- `run.trigger.sender`: `${sender}` (for deliver)
- `run.trigger.blockHeight`: `${inboundNum.split('-')[0]}`
- `run.trigger.txHash`: `${inboundNum.split('-')[1]}`
- `run.trigger.msgIdx`: `${inboundNum.split('-')[2]}`

For the `cosmic-swingset-run-start` event, if there is no **trigger context**, and the `runNum` field is not `0`, we assume the trigger is a timer poll. This is because there is no explicit slog event for the timer poll. There is unfortunately another trigger for a run without explicit slog event for the trigger: INSTALL_BUNDLE, but thankfully that event does not currently cause any activity during that run. Any duplication of trigger info would thus be benign (See #10332 to add explicit slog events of both timer poll and install bundle).
If there is no **trigger context**, and `runNum !== 0`, create and persist a **trigger context** formed as the following:
- `run.id`: `timer-${blockHeight}`
- `run.trigger.type`: `timer`
- `run.trigger.time`: `${blockTime}`

For every `cosmic-swingset-run-start` event, add the following field to an existing **trigger context**, or create (but do not persist) a **trigger context** with the following:
- `run.num`: `${runNum}`.

For the `cosmic-swingset-run-finish` event, report with the current contexts then unset the **trigger context**. Do not remove any persisted context.

For the `crank-start` event, create a **crank context** formed as the following:
- `crank.num`: `${crankNum}`
- `crank.type`: `${crankType}`

For the `crank-result` event, report with the current contexts then unset the **crank context**.

For the `clist` event, update the **crank context** with the following (assert the context exists):
- `crank.vatID`: `${vatID}`

For the `start-replay` event, create a **replay context** with `replay`: `true`. Unset the **replay context** after the `finish-replay` event was reported.

For the `deliver` event, update the **replay context** if it exists (assert that the slog event `replay` field is `true`), or the **crank context** otherwise, with the following:
- `crank.deliveryNum`: ${deliveryNum}`
- `crank.vatID`: `${vatID}`

Remove the `replay` and `deliveryNum` fields of the slog event and report.
For the `deliver-result` event, remove the `replay` and `deliveryNum` fields and report. There is no need to unset the deliveryNum from the context.

For the `syscall` and `syscall-result` events:
- remove the `replay` and `deliveryNum` fields
- extract (and remove) the `syscallNum` field into a `crank.syscallNum` attribute

For the `console` event:
- remove the `crankNum` and `deliveryNum` fields

## Security Considerations

None, this is log reporting

## Scaling Considerations

While better for consistency, it's not strictly necessary to flush the persisted **trigger context** to disk, as logging is not a critical operation. Furthermore when restoring the **trigger context** on end-block start, the implementation should avoid reading the persisted context from disk when it previously wrote it out.

## Test Plan

An integration test is likely sufficient. We possibly want to enable this reporting in a3p to verify that the context building logic does not fail or get out of sync. Like for `slog-to-otel`, consider enabling the env option to fail the chain if the slog sender errors out.

Verify in a test instagoric the shape and ability to query logs.

## Upgrade Considerations

The easiest is to deploy as a chain software update, but since slog senders are configurable, it could also be cherry-picked or even independently installed through a new NPM telemetry package, and configured on an existing deployment.

### PR DESCRIPTION
**Pull request by usmanmani1122**
closes: #10269

## Description
Adds a slog sender which will build various contexts along the way and report them along with the slogs for better logs querying and identification

### Security Considerations
None

### Scaling Considerations
This uses a json file storage

### Documentation Considerations
This is a new slogger which can be opted into

### Testing Considerations
This will be deployed on testnets (already deployed on one of the testnets and log link is added in a comment below)

### Upgrade Considerations
This can be configured on existing deployments by bumping the telemetry package

### CODE REVIEW

**Comment by usmanmani1122** [comment]
Grafana logs [link](https://monitor.agoric.net/explore?schemaVersion=1&panes=%7B%222zv%22:%7B%22datasource%22:%22P470A85C5170C7A1D%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22googlecloud-logging-datasource%22,%22uid%22:%22P470A85C5170C7A1D%22%7D,%22queryText%22:%22logName%3D%5C%22projects%2Fsimulationlab%2Flogs%2Fopentelemetry.io%252Fcollector-exported-log%5C%22%5Cnresource.labels.cluster_name%3D%5C%22puffynet%5C%22%5Cnresource.labels.namespace_name%3D%5C%22usman%5C%22%22,%22projectId%22:%22simulationlab%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)

File: packages/telemetry/src/context-aware-slog.js [hunk 1]
```diff
@@ -0,0 +1,475 @@
...
+  },
+  SYSCALL: 'syscall',
+  SYSCALL_RESULT: 'syscall-result',
+};
+
+const getDatabaseInstance = async () => {
+  if (!existsSync(DATABASE_FILE_PATH))
+    closeSync(openSync(DATABASE_FILE_PATH, 'w'));
+
+  const databaseInstance = sqlite(DATABASE_FILE_PATH, { fileMustExist: true });
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I was thinking we could use a simple file for this. Any reason to use an actual DB?

File: packages/telemetry/src/context-aware-slog.js [hunk 2]
```diff
@@ -0,0 +1,475 @@
...
+ * @typedef {{
+ *  'chain-id': string;
+ *  'crank.syscallNum'?: Slog['syscallNum'];
+ *  'process.uptime': Slog['monotime'];
+ *  timestamp: Slog['time'];
+ * } & Context} LogAttributes
+ */
+
+const DATABASE_FILE_PATH =
+  process.env.SLOG_CONTEXT_DATABASE_FILE_PATH || '/state/slog-db.sqlite3';
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Let's just use a file name, and build it from [`stateDir`](https://github.com/Agoric/agoric-sdk/blob/696d9370516dfe39e3f155d6aa4252d605dbaa6e/packages/telemetry/src/make-slog-sender.js#L132) that's already provided to all slog sender, possibly with an explicit override for this sender. See [flight-recorder for example](https://github.com/Agoric/agoric-sdk/blob/696d9370516dfe39e3f155d6aa4252d605dbaa6e/packages/telemetry/src/flight-recorder.js#L192C20-L192C43).

File: packages/telemetry/src/context-aware-slog.js [hunk 3]
```diff
@@ -0,0 +1,475 @@
...
+  REPLAY: {
+    FINISH: 'finish-replay',
+    START: 'start-replay',
+  },
+  // eslint-disable-next-line no-restricted-syntax
+  RUN: {
+    FINISH: 'cosmic-swingset-run-finish',
+    START: 'cosmic-swingset-run-start',
+  },
+  SWINGSET: {
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Nit these are cosmic-swingset slog entries. Swingset doesn't generate them

File: packages/telemetry/src/context-aware-slog.js [hunk 4]
```diff
@@ -0,0 +1,475 @@
...
+    },
+  },
+  REPLAY: {
+    FINISH: 'finish-replay',
+    START: 'start-replay',
+  },
+  // eslint-disable-next-line no-restricted-syntax
+  RUN: {
+    FINISH: 'cosmic-swingset-run-finish',
+    START: 'cosmic-swingset-run-start',
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Run entries are also generated by cosmic-swingset.

File: packages/telemetry/src/context-aware-slog.js [hunk 5]
```diff
@@ -0,0 +1,475 @@
...
+   * @param {Context} context
+   */
+  const persistContext = context => {
+    lastPersistedTriggerContext = context;
+    db.persistContext(context);
+  };
+
+  const restoreContext = () => {
+    if (lastPersistedTriggerContext) return lastPersistedTriggerContext;
+    return db.restoreContext();
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I think we can save the restored context into `lastPersistedTriggerContext`.

File: packages/telemetry/src/context-aware-slog.js [hunk 6]
```diff
@@ -0,0 +1,475 @@
...
+   * @param {Slog} slog
+   */
+  const slogSender = ({ monotime, time: timestamp, ...body }) => {
+    const finalBody = { ...body };
+
+    /** @type {LogAttributes} */
+    let logAttributes = {
+      'chain-id': String(CHAIN_ID),
+      'process.uptime': monotime,
+      timestamp,
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I believe the timestamp should be in the top level LogRecord, not in the attributes: https://opentelemetry.io/docs/specs/otel/logs/data-model/#log-and-event-record-definition

Apparently the JS SDK expects a nanosecond TimeInput value: https://open-telemetry.github.io/opentelemetry-js/interfaces/_opentelemetry_api_logs.LogRecord.html#timestamp

File: packages/telemetry/src/context-aware-slog.js [hunk 7]
```diff
@@ -0,0 +1,475 @@
...
+        logAttributes['crank.syscallNum'] = finalBody.syscallNum;
+
+        delete finalBody.deliveryNum;
+        delete finalBody.replay;
+        delete finalBody.syscallNum;
+
+        break;
+      }
+      default:
+        break;
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js:281]: Maybe add a comment that any other slog types are just logged as-is with the existing context.

File: packages/telemetry/src/context-aware-slog.js [hunk 8]
```diff
@@ -0,0 +1,475 @@
...
+      ...crankContext,
+      ...initContext,
+      ...logAttributes,
+      ...replayContext,
+      ...triggerContext,
+    };
+
+    logger.emit({
+      attributes: JSON.parse(stringify(logAttributes)),
+      body: JSON.parse(stringify(finalBody)),
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Any reason to clone these values?

File: packages/telemetry/src/context-aware-slog.js [hunk 9]
```diff
@@ -0,0 +1,475 @@
...
+          'run.trigger.source': finalBody.source,
+          'run.trigger.time': finalBody.blockTime,
+          'run.trigger.txHash': txHash,
+          'run.trigger.type': triggerType,
+        };
+        persistContext(triggerContext);
+        break;
+      }
+      case SLOG_TYPES.SWINGSET.COMMIT.FINISH:
+      case SLOG_TYPES.SWINGSET.COMMIT.START:
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I missed this in the issue, but `cosmic-swingset-after-commit-stats` should probably assert the block context exists as well here. Same for `cosmic-swingset-bootstrap-block-finish`

Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js]: I'm also wondering if we should assert that no trigger context exists at this point too.

File: packages/telemetry/src/context-aware-slog.js [hunk 10]
```diff
@@ -0,0 +1,475 @@
...
+          'run.trigger.type': 'bootstrap',
+        };
+        break;
+      }
+      case SLOG_TYPES.SWINGSET.BRIDGE_INBOUND:
+      case SLOG_TYPES.SWINGSET.DELIVER_INBOUND: {
+        const [blockHeight, txHash, msgIdx] = (
+          finalBody.inboundNum || ''
+        ).split('-');
+        const triggerType = body.type.split('-')[2];
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I'm not a fan of counting `-` here. I might prefer a pop in that case.
```suggestion
        const triggerType = body.type.split('-').pop();
```

File: packages/telemetry/src/context-aware-slog.js [hunk 11]
```diff
@@ -0,0 +1,475 @@
...
+
+        triggerContext = {
+          'run.id': `${triggerType}-${finalBody.inboundNum}`,
+          'run.trigger.blockHeight': Number(blockHeight),
+          'run.trigger.msgIdx': Number(msgIdx),
+          'run.trigger.sender': finalBody.sender,
+          'run.trigger.source': finalBody.source,
+          'run.trigger.time': finalBody.blockTime,
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: That is not correct. There should not be a `run.trigger.time` for these trigger types.
```suggestion
```

File: packages/telemetry/src/context-aware-slog.js [hunk 12]
```diff
@@ -0,0 +1,475 @@
...
+        break;
+      }
+      case SLOG_TYPES.SWINGSET.BRIDGE_INBOUND:
+      case SLOG_TYPES.SWINGSET.DELIVER_INBOUND: {
+        const [blockHeight, txHash, msgIdx] = (
+          finalBody.inboundNum || ''
+        ).split('-');
+        const triggerType = body.type.split('-')[2];
+
+        triggerContext = {
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Please sort these as they were described in the issue. If the otel collector and log UI is any good it'll keep the same order, allowing us to more quickly see together related attributes.

And let's start with a `run.num` placeholder so that when it gets added it appears first

```suggestion
        triggerContext = {
          'run.num': null,
```

File: packages/telemetry/src/context-aware-slog.js [hunk 13]
```diff
@@ -0,0 +1,475 @@
...
+      }
+      case SLOG_TYPES.SWINGSET.BOOTSTRAP_BLOCK.START: {
+        blockContext = {
+          'block.height': finalBody.blockHeight || 0,
+          'block.time': finalBody.blockTime,
+        };
+        triggerContext = {
+          'run.id': `bootstrap-${finalBody.blockTime}`,
+          'run.trigger.time': finalBody.blockTime,
+          'run.trigger.type': 'bootstrap',
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]:
```suggestion
          'run.trigger.type': 'bootstrap',
          'run.trigger.time': finalBody.blockTime,
```

File: packages/telemetry/src/context-aware-slog.js [hunk 14]
```diff
@@ -0,0 +1,475 @@
...
+      'chain-id': String(CHAIN_ID),
+      'process.uptime': monotime,
+      timestamp,
+    };
+
+    /**
+     * Add any before report operations here
+     * like setting context data
+     */
+    switch (body.type) {
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js:144]: As a matter of code organization, I would prefer to see the block and context building types handled first so that reading we can more clearly see each being built up as they would when processing the slog events. Here is seems they're somewhat lexicographically sorted, which doesn't really bring any value.

File: packages/telemetry/src/context-aware-slog.js [hunk 15]
```diff
@@ -0,0 +1,475 @@
...
+        initContext = { init: true };
+        break;
+      }
+      case SLOG_TYPES.REPLAY.START: {
+        replayContext = { replay: true };
+        break;
+      }
+      // eslint-disable-next-line no-restricted-syntax
+      case SLOG_TYPES.RUN.START: {
+        if (!(triggerContext || finalBody.runNum === 0)) {
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I find the negation confusing.

```suggestion
        if (!triggerContext && finalBody.runNum !== 0) {
```

File: packages/telemetry/src/context-aware-slog.js [hunk 16]
```diff
@@ -0,0 +1,475 @@
...
+          const blockTime = finalBody.blockTime || blockContext?.['block.time'];
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: My bad, I totally forgot that there was no `blockTime` on the run-start event.

Let's assert that `blockContext` exists and use that only.

```suggestion
          assert(blockContext);
          const blockTime = blockContext.['block.time'];
```

File: packages/telemetry/src/context-aware-slog.js [hunk 17]
```diff
@@ -0,0 +1,475 @@
...
+
+          assert(blockTime);
+          // TBD: add explicit slog events of both timer poll and install bundle
+          triggerContext = {
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Let's add a placeholder `run.num` here for consistent order purposes

```suggestion
          triggerContext = {
            'run.num': null,
```

File: packages/telemetry/src/context-aware-slog.js [hunk 18]
```diff
@@ -0,0 +1,475 @@
...
+            'run.id': `timer-${finalBody.blockHeight}`,
+            'run.trigger.time': blockTime,
+            'run.trigger.type': 'timer',
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]:
```suggestion
            'run.trigger.type': 'timer',
            'run.trigger.time': blockTime,
```

File: packages/telemetry/src/context-aware-slog.js [hunk 19]
```diff
@@ -0,0 +1,475 @@
...
+    }
+
+    /** @type {LogAttributes} */
+    logAttributes = {
+      ...blockContext,
+      ...crankContext,
+      ...initContext,
+      ...logAttributes,
+      ...replayContext,
+      ...triggerContext,
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Let's order this in order of relevance
```suggestion
      ...logAttributes, // Some static or general ordering info
      ...initContext, // Optional prelude
      ...blockContext, // Block is the first level of execution nesting
      ...triggerContext, // run and trigger info is nested next
      ...crankContext, // Finally cranks are the last level of nesting
      ...replayContext, // Replay is a substitute for crank context during vat page in
```

File: packages/telemetry/src/context-aware-slog.js [hunk 20]
```diff
@@ -0,0 +1,475 @@
...
+        assert(!!blockContext);
+        break;
+      }
+      case SLOG_TYPES.SWINGSET.END_BLOCK.START: {
+        assert(!!blockContext);
+        break;
+      }
+      case SLOG_TYPES.SYSCALL:
+      case SLOG_TYPES.SYSCALL_RESULT: {
+        logAttributes['crank.syscallNum'] = finalBody.syscallNum;
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Let's create an  `eventLogAttributes` for this that is last in the overall `logAttributes`

File: packages/telemetry/src/context-aware-slog.js [hunk 21]
```diff
@@ -0,0 +1,475 @@
...
+      case SLOG_TYPES.DELIVER: {
+        if (replayContext) {
+          assert(finalBody.replay);
+          replayContext = {
+            ...replayContext,
+            'crank.deliveryNum': finalBody.deliveryNum,
+            'crank.vatID': finalBody.vatID,
+          };
+        } else {
+          assert(!!crankContext);
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: We probably should also assert that the event is not replaying

```suggestion
          assert(!!crankContext);
          assert(!finalBody.replay);
```

File: packages/telemetry/src/context-aware-slog.js [hunk 22]
```diff
@@ -0,0 +1,475 @@
...
+      case SLOG_TYPES.SWINGSET.END_BLOCK.START: {
+        triggerContext = restoreContext();
+        break;
+      }
+      default:
+        break;
+    }
+  };
+
+  return slogSender;
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I believe the otel SDK does some caching. Let's try to flush things when possible. For example here is what the otel tracing sender does: https://github.com/Agoric/agoric-sdk/blob/696d9370516dfe39e3f155d6aa4252d605dbaa6e/packages/telemetry/src/otel-trace.js#L57-L70

**Review by mhofman — CHANGES_REQUESTED** [review]
This looks like a really good start!

Besides the specific comments there are 2 changes I'd like to see:
- I am really skeptical of using a SQLite DB for persisting a simple JSON object. Can we just sync write as a JSON serialized value to a file? No need to fsync eother, I don't care about failure recovery in this case.
- Can we extract the function that does transformation from a slog event into a log record into a separate module that doesn't depend on otel stuff? I believe @warner may be interested in using this context building logic on its own. I can be wrapped in a maker that takes the `db` object as power to persist / restore the trigger context. The rest is fully stateless.

**Comment by mhofman** [comment]
Oh yeah I'd also love to see this processing on an existing slog file from a mainnet follower! I have plenty around if needed.

File: packages/telemetry/src/context-aware-slog.js (hunk 1 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: Currently there is no need for a DB. I added DB in case we need to add more context or things in future. If we don't see this happening right now, we can move to a simple json file.

File: packages/telemetry/src/context-aware-slog.js (hunk 8 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: This is done for handling `bigint` serialization to number using the `stringify` function

File: packages/telemetry/src/context-aware-slog.js (hunk 11 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: My bad

File: packages/telemetry/src/context-aware-slog.js (hunk 12 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: Will do this. But I heavily doubt keys order will be honoured.

Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js]: At the very least they would be by a "slog transformer" that simply serializes back to a file

File: packages/telemetry/src/context-aware-slog.js (hunk 6 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: I think there could be problems with timezone if we tinker with timestamp field. I suggest letting the timestamp be populated automatically by the sink and use the `observedTimestamp` field

File: packages/telemetry/src/context-aware-slog.js (hunk 9 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: Should we add the assertion of trigger context?

File: packages/telemetry/src/context-aware-slog.js (hunk 8 above)
Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js]: I didn't realize we had any bigints in there

File: packages/telemetry/src/context-aware-slog.js (hunk 6 above)
Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js]: Observed timestamp should be filed automatically by the SDK, no?

What is the concern with tz? I believe the timestamp comes in as an iso string datetime.

File: packages/telemetry/src/context-aware-slog.js (hunk 14 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js:144]: Can you suggest a rough order? I am not sure which cases should be handled in what order for better understanding

Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js:144]: The order in the issue is roughly what I would expect. I'll double check that it fits

File: packages/telemetry/src/context-aware-slog.js [hunk 23]
```diff
@@ -122,88 +81,71 @@ const SLOG_TYPES = {
...
-        else
-          values.push(
-            DATABASE_SCHEMA[key].startsWith(DATABASE_TYPES.TEXT)
-              ? `'${value}'`
-              : value,
-          );
-      }
+    persistContext: context =>
+      new Promise(resolve =>
+        writeFile(filePath, JSON.stringify(context), FILE_ENCODING, err => {
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I am totally ok with using sync APIs here to avoid having to make the slog sender async

Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: Done

File: packages/telemetry/src/context-aware-slog.js (hunk 22 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: Added flush and shutdown functions

**Comment by usmanmani1122** [comment]
> * I am really skeptical of using a SQLite DB for persisting a simple JSON object. Can we just sync write as a JSON serialized value to a file? No need to fsync eother, I don't care about failure recovery in this case.

Done

> * Can we extract the function that does transformation from a slog event into a log record into a separate module that doesn't depend on otel stuff? I believe @warner may be interested in using this context building logic on its own. I can be wrapped in a maker that takes the `db` object as power to persist / restore the trigger context. The rest is fully stateless.

Done. Separated a function `logCreator` for this

File: packages/telemetry/src/context-aware-slog.js (hunk 6 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: The issue is with the sink (google cloud logging in this case). Due to timezone difference, the reported timestamp can be in future for the sink which causes failures. I think timestamp should be populated by the sink itself. For using our generated timestamp, it will be available in `labels` for anyone to use.

File: packages/telemetry/src/context-aware-slog.js (hunk 10 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: Regex it is 😈

File: packages/telemetry/src/context-aware-slog.js (hunk 6 above)
Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js]: That really doesn't make sense to me. Afaik the [slog event generator uses](https://github.com/Agoric/agoric-sdk/blob/df2faae7e5aa4bba657962f3b33aaeb7a3953c91/packages/SwingSet/src/controller/controller.js#L172-L173) the POSIX time for this value, and it does so on the same machine, so there is no reason that the timestamp generated by the otel SDK and the timestamp we generate would be having such a timezones difference. I would really like to be able to rely on our source of truth for time, so that we can keep our ability to backfill data by re-streaming captured slogs if necessary.

File: packages/telemetry/src/context-aware-slog.js [hunk 24]
```diff
@@ -0,0 +1,444 @@
...
+    }
+  };
+
+  return slogSender;
+};
+
+/**
+ * @param {Options} options
+ */
+export const makeSlogSender = options => {
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: The maker can and is expected to be async

File: packages/telemetry/src/context-aware-slog.js [hunk 25]
```diff
@@ -0,0 +1,444 @@
...
+  );
+
+  loggerProvider.addLogRecordProcessor(logRecordProcessor);
+
+  logs.setGlobalLoggerProvider(loggerProvider);
+  const logger = logs.getLogger('default');
+
+  const persistenceUtils = getContextFilePersistenceUtils(
+    process.env.SLOG_CONTEXT_FILE_PATH ||
+      `${options.stateDir || dirSync({ prefix: 'slog-context' }).name}/slog-context.json`,
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I am not sure that a dynamically generated "temp state dir" has any use since it wouldn't help with persistence between invocations in any way. We should either default to `TMPDIR` (like the flight recorder), or assert that stateDir is defined.

Also let's put the `slog-context.json` file name into a `DEFAULT_CONTEXT_FILE` const.

File: packages/telemetry/src/context-aware-slog.js [hunk 26]
```diff
@@ -0,0 +1,444 @@
...
+  );
+
+  const slogSender = logCreator(
+    logRecord => logger.emit(logRecord),
+    options,
+    persistenceUtils,
+  );
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I am conflicted about this. On the one hand, the callback approach allows flexibility in the future to "buffer" some events in order to "back contextualize" some of them with information from later slog events, on the other hand, I don't know if I want us to enable any more complex processing of slog events.

I think I would prefer a function that accepted a slog event, and synchronously returned a log record. That way it'd be clearer that the processing is meant to be immediate based on accumulated state so far.

File: packages/telemetry/src/context-aware-slog.js [hunk 27]
```diff
@@ -0,0 +1,444 @@
...
+  JSON.stringify(data, (_, value) =>
+    typeof value === 'bigint' ? Number(value) : value,
+  );
+
+/**
+ * @param {(log: import('@opentelemetry/api-logs').LogRecord) => void} emitLog
+ * @param {Options} options
+ * @param {Partial<{ persistContext: (context: Context) => void; restoreContext: () => Context | null; }>} persistenceUtils
+ */
+export const logCreator = (emitLog, options, persistenceUtils) => {
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Please extract this in a separate file so it can be used without the otel (or any) deps.

Let's also take the slogSender specific options out. I believe it's only needed for `CHAIN_ID` which really can be a `staticContext` provided as argument instead.

File: packages/telemetry/src/context-aware-slog.js [hunk 28]
```diff
@@ -0,0 +1,444 @@
...
+ * } Context
+ *
+ * @typedef {{
+ *  'chain-id': string;
+ *  'crank.syscallNum'?: Slog['syscallNum'];
+ *  'process.uptime': Slog['monotime'];
+ *  timestamp: Slog['time'];
+ * } & Context} LogAttributes
+ *
+ * @typedef {{env: typeof process.env; stateDir: string;}} Options
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I'm surprised we don't have this one specified anywhere else.

File: packages/telemetry/src/context-aware-slog.js [hunk 29]
```diff
@@ -0,0 +1,444 @@
...
+  },
+  SYSCALL: 'syscall',
+  SYSCALL_RESULT: 'syscall-result',
+};
+
+/**
+ * @param {string} filePath
+ */
+export const getContextFilePersistenceUtils = filePath => {
+  console.log(`Using file ${filePath} for slogger`);
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]:
```suggestion
  console.log(`Using file ${filePath} for slogger context`);
```

File: packages/telemetry/src/context-aware-slog.js [hunk 30]
```diff
@@ -0,0 +1,444 @@
...
+
+  return {
+    /**
+     * @param {Context} context
+     */
+    persistContext: context => {
+      try {
+        writeFileSync(filePath, JSON.stringify(context), FILE_ENCODING);
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Why not `stringify` aware of bigint here?
```suggestion
        writeFileSync(filePath, stringify(context), FILE_ENCODING);
```

File: packages/telemetry/src/context-aware-slog.js (hunk 8 above)
Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js]: Let's leave the bigint serialization concern to `emitLog`

File: packages/telemetry/src/context-aware-slog.js [hunk 31]
```diff
@@ -0,0 +1,444 @@
...
+
+const stringify = data =>
+  JSON.stringify(data, (_, value) =>
+    typeof value === 'bigint' ? Number(value) : value,
+  );
+
+/**
+ * @param {(log: import('@opentelemetry/api-logs').LogRecord) => void} emitLog
+ * @param {Options} options
+ * @param {Partial<{ persistContext: (context: Context) => void; restoreContext: () => Context | null; }>} persistenceUtils
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Let's make these optional.

File: packages/telemetry/src/context-aware-slog.js [hunk 32]
```diff
@@ -0,0 +1,444 @@
...
+      }
+      case SLOG_TYPES.COSMIC_SWINGSET.END_BLOCK.START: {
+        assert(!!blockContext);
+        break;
+      }
+      // eslint-disable-next-line no-restricted-syntax
+      case SLOG_TYPES.COSMIC_SWINGSET.RUN.START: {
+        if (!triggerContext && finalBody.runNum !== 0) {
+          assert(!!blockContext);
+          // TBD: add explicit slog events of both timer poll and install bundle
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: So apparently the install bundle does trigger some execution. We either need the info to be coming from the slog event, or for us to backfill the trigger context when we see the first delivery...

File: packages/telemetry/src/context-aware-slog.js (hunk 14 above)
Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js:144]: I checked and the order in the issue is what I would expect to see here.

**Review by mhofman — COMMENTED** [review]
Thanks for addressing the feedback so far. Some more refactoring suggestions. I also really want us to figure out this timestamp issue as I'd like to be able to upload old slogs to GCP with the original time the events were generated as the native timestamp of the event.

File: packages/telemetry/src/context-aware-slog.js (hunk 32 above)
Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js]: Filed https://github.com/Agoric/agoric-sdk/issues/10332.

FYI, here is what @warner 's classification tool does to look ahead (and add extra info on the nature of the bridge inbound): https://github.com/Agoric/agoric-sdk/pull/8680

File: packages/telemetry/src/context-aware-slog.js (hunk 6 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: I have tried it and google cloud sink gives error that the timestamp can’t be in future. But their limits page suggests that timestamp can be max 1 day in future so we might be able to fix it. Even if we could, the same page also suggest that maximum 30 days in the past are allowed so we won’t be able to report all the historic data using the timestamp field:
https://cloud.google.com/logging/quotas#log-limits
I would say we don’t use timestamp field and use either a label or a jsonPayload field for our time. We would still be able to use them to filter logs for a time range.

File: packages/telemetry/src/context-aware-slog.js (hunk 30 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: Good point

File: packages/telemetry/src/context-aware-slog.js [hunk 33]
```diff
@@ -0,0 +1,349 @@
...
+  SYSCALL: 'syscall',
+  SYSCALL_RESULT: 'syscall-result',
+};
+
+/**
+ * @param {(log: { attributes: LogAttributes, body: Partial<Slog> }) => void} emitLog
+ * @param {Partial<{ persistContext: (context: Context) => void; restoreContext: () => Context | null; }>?} persistenceUtils
+ */
+export const logCreator = (emitLog, persistenceUtils = {}) => {
+  const { CHAIN_ID } = process.env;
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I would rather this function not use `process` or any ambient power. Let's inject this through a `staticContext` arg.

File: packages/telemetry/src/context-aware-slog.js [hunk 34]
```diff
@@ -0,0 +1,349 @@
...
+        break;
+      }
+      case SLOG_TYPES.REPLAY.FINISH: {
+        replayContext = null;
+        break;
+      }
+      default:
+        break;
+    }
+  };
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js:342]: Let's return the logRecord here instead of emitting it. The attributes have been built from context already so it's safe to return after the context have been nulled out or restored.

```suggestion
    return { attributes: logAttributes, body: finalBody };
  };
```

File: packages/telemetry/src/context-aware-slog.js [hunk 35]
```diff
@@ -0,0 +1,349 @@
...
+  },
+  SYSCALL: 'syscall',
+  SYSCALL_RESULT: 'syscall-result',
+};
+
+/**
+ * @param {(log: { attributes: LogAttributes, body: Partial<Slog> }) => void} emitLog
+ * @param {Partial<{ persistContext: (context: Context) => void; restoreContext: () => Context | null; }>?} persistenceUtils
+ */
+export const logCreator = (emitLog, persistenceUtils = {}) => {
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: We usually name these functions returning a statefull function/object a maker. 

```suggestion
/**
 * @param {(log: { attributes: LogAttributes, body: Partial<Slog> }) => void} emitLog
 * @param {Partial<{ persistContext: (context: Context) => void; restoreContext: () => Context | null; }>} [persistenceUtils]
 */
export const makeContextualSlogProcessor = (emitLog, persistenceUtils = {}) => {
```

But given the other feedback, I expect to look more like:

```suggestion
/**
 * @template {Record<string, any>} [T={}]
 * @param {T} [staticContext]
 * @param {Partial<{ persistContext: (context: Context) => void; restoreContext: () => Context | null; }>} [persistenceUtils]
 * @returns {{ attributes: T & LogAttributes, body: Partial<Slog> }}
 */
export const makeContextualSlogProcessor = (staticContext = {}, persistenceUtils = {}) => {
```

File: packages/telemetry/src/context-aware-slog.js [hunk 36]
```diff
@@ -0,0 +1,349 @@
...
+        break;
+      }
+      case SLOG_TYPES.COSMIC_SWINGSET.END_BLOCK.FINISH:
+      case SLOG_TYPES.COSMIC_SWINGSET.COMMIT.START:
+      case SLOG_TYPES.COSMIC_SWINGSET.COMMIT.FINISH: {
+        assert(!!blockContext);
+        break;
+      }
+      case SLOG_TYPES.COSMIC_SWINGSET.AFTER_COMMIT_STATS: {
+        assert(!!blockContext && !triggerContext);
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I think all these can be merged together

```suggestion
      case SLOG_TYPES.COSMIC_SWINGSET.END_BLOCK.FINISH:
      case SLOG_TYPES.COSMIC_SWINGSET.BOOTSTRAP_BLOCK.FINISH:
      case SLOG_TYPES.COSMIC_SWINGSET.COMMIT.START:
      case SLOG_TYPES.COSMIC_SWINGSET.COMMIT.FINISH:
      case SLOG_TYPES.COSMIC_SWINGSET.AFTER_COMMIT_STATS: {
        assert(!!blockContext && !triggerContext);
```

File: packages/telemetry/src/context-aware-slog.js [hunk 37]
```diff
@@ -0,0 +1,349 @@
...
+        break;
+      }
+      case SLOG_TYPES.COSMIC_SWINGSET.BOOTSTRAP_BLOCK.START: {
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js:156]: Let's move this one between `begin-block` and `end-block-start`

File: packages/telemetry/src/context-aware-slog.js [hunk 38]
```diff
@@ -0,0 +1,349 @@
...
+      // eslint-disable-next-line no-restricted-syntax
+      case SLOG_TYPES.COSMIC_SWINGSET.RUN.START: {
+        if (!triggerContext && finalBody.runNum !== 0) {
+          assert(!!blockContext);
+          // TBD: add explicit slog events of both timer poll and install bundle
+          triggerContext = {
+            'run.num': null,
+            'run.id': `timer-${finalBody.blockHeight}`,
+            'run.trigger.type': 'timer',
+            'run.trigger.time': blockContext['block.time'],
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I'm thinking that since we can't be sure at this point what the trigger is, we need a sensible generic fallback:

```suggestion
            'run.id': `unknown-${finalBody.blockHeight}-${finalBody.runNum}`,
            'run.trigger.type': 'unknown',
            'run.trigger.time': blockContext['block.time'],
            'run.trigger.blockHeight': finalBody.blockHeight,
```

File: packages/telemetry/src/context-aware-slog.js [hunk 39]
```diff
@@ -0,0 +1,349 @@
...
+          'run.trigger.msgIdx': Number(msgIdx),
+        };
+        persistContext(triggerContext);
+        break;
+      }
+      // eslint-disable-next-line no-restricted-syntax
+      case SLOG_TYPES.COSMIC_SWINGSET.RUN.START: {
+        if (!triggerContext && finalBody.runNum !== 0) {
+          assert(!!blockContext);
+          // TBD: add explicit slog events of both timer poll and install bundle
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Let's add a link to the issue:

```suggestion
          // TODO: add explicit slog events of both timer poll and install bundle
          // https://github.com/Agoric/agoric-sdk/issues/10332
```

File: packages/telemetry/src/context-aware-slog.js [hunk 40]
```diff
@@ -0,0 +1,349 @@
...
+        replayContext = { replay: true };
+        break;
+      }
+      case SLOG_TYPES.DELIVER: {
+        if (replayContext) {
+          assert(finalBody.replay);
+          replayContext = {
+            ...replayContext,
+            'crank.deliveryNum': finalBody.deliveryNum,
+            'crank.vatID': finalBody.vatID,
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Nit

```suggestion
            'crank.vatID': finalBody.vatID,
            'crank.deliveryNum': finalBody.deliveryNum,
```

File: packages/telemetry/src/context-aware-slog.js [hunk 41]
```diff
@@ -0,0 +1,349 @@
...
+          };
+        } else {
+          assert(!!crankContext && !finalBody.replay);
+          crankContext = {
+            ...crankContext,
+            'crank.deliveryNum': finalBody.deliveryNum,
+            'crank.vatID': finalBody.vatID,
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Nit 

```suggestion
            'crank.vatID': finalBody.vatID,
            'crank.deliveryNum': finalBody.deliveryNum,
```

**Review by mhofman — COMMENTED** [review]
A few more refactoring nits. Let's continue the timestamp discussion offline.

File: packages/telemetry/src/context-aware-slog.js [hunk 42]
```diff
@@ -178,7 +165,15 @@ export const logCreator = (emitLog, persistenceUtils = {}) => {
         };
         break;
       }
-      case SLOG_TYPES.COSMIC_SWINGSET.BOOTSTRAP_BLOCK.FINISH: {
+      case SLOG_TYPES.COSMIC_SWINGSET.END_BLOCK.START: {
+        assert(!!blockContext);
+        break;
+      }
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: There should be no trigger context here either (since we're restoring it later)

```suggestion
      case SLOG_TYPES.COSMIC_SWINGSET.END_BLOCK.START:
```

File: packages/telemetry/src/context-aware-slog.js [hunk 43]
```diff
@@ -291,21 +288,17 @@ export const logCreator = (emitLog, persistenceUtils = {}) => {
...
-      'chain-id': String(CHAIN_ID),
       'process.uptime': monotime,
       ...initContext, // Optional prelude
       ...blockContext, // Block is the first level of execution nesting
       ...triggerContext, // run and trigger info is nested next
       ...crankContext, // Finally cranks are the last level of nesting
       ...replayContext, // Replay is a substitute for crank context during vat page in
       ...eventLogAttributes,
-      timestamp,
+      ...staticContext,
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Let's move `staticContext` to the begining.

File: packages/telemetry/src/context-aware-slog.js [hunk 44]
```diff
@@ -291,21 +288,17 @@ export const logCreator = (emitLog, persistenceUtils = {}) => {
         break;
     }
 
-    /** @type {LogAttributes} */
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Why not keep the type here?

```suggestion
    /** @type {T & LogAttributes} */
```

File: packages/telemetry/src/otel-context-aware-slog.js [hunk 45]
```diff
@@ -77,15 +77,31 @@ export const makeSlogSender = async options => {
...
+  /**
+   * @param {import('./context-aware-slog.js').Slog} slog
+   */
+  const slogSender = slog => {
+    const { timestamp, ...logRecord } = contextualSlogProcessor(slog);
+
+    const [secondsStr, fractionStr] = String(timestamp).split('.');
+    const seconds = parseInt(secondsStr, 10);
+    const nanoSeconds = parseInt(
+      (fractionStr || String(0)).padEnd(9, String(0)),
```
Comment (mhofman) [inline packages/telemetry/src/otel-context-aware-slog.js]: I don't trust numbers, and want to be resilient in case the `fractionStr` is more than 9 chars already.

In general I prefer string literals where possible

```suggestion
      (fractionStr.substr(0, 9) || '').padEnd(9, '0'),
```

**Review by mhofman — COMMENTED** [review]
This looks good, but holding my approval until I review the output of aa processed slog in case I missed anything. Is the grafana link up top still valid? I'll also look at the processed slog file you sent

File: packages/telemetry/src/context-aware-slog.js [hunk 46]
```diff
@@ -0,0 +1,348 @@
...
+      case SLOG_TYPES.COSMIC_SWINGSET.RUN.START: {
+        if (!triggerContext && finalBody.runNum !== 0) {
+          assert(!!blockContext);
+          // TODO: add explicit slog events of both timer poll and install bundle
+          // https://github.com/Agoric/agoric-sdk/issues/10332
+          triggerContext = {
+            'run.num': null,
+            'run.id': `unknown-${finalBody.blockHeight}-${finalBody.runNum}`,
+            'run.trigger.type': 'unknown',
+            'run.trigger.time': blockContext['block.time'],
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Let's remove the trigger time, it's confusing, and just duplicating the `block.time` anyway.

```suggestion
```

File: packages/telemetry/src/context-aware-slog.js [hunk 47]
```diff
@@ -0,0 +1,348 @@
...
+        blockContext = null;
+        break;
+      }
+      case SLOG_TYPES.COSMIC_SWINGSET.BOOTSTRAP_BLOCK.FINISH: {
+        blockContext = null;
+        break;
+      }
+      // eslint-disable-next-line no-restricted-syntax
+      case SLOG_TYPES.COSMIC_SWINGSET.RUN.FINISH: {
+        triggerContext = null;
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js:322]: I made a mistake on the logic of the trigger context persistence. We need to conditionally persist the context here:

```suggestion
        persistContext(finalBody.remainingBeans > 0 ? null : triggerContext);
        triggerContext = null;
```

Then we can simply restore the context on run start for `runNum === 0` I think.

File: packages/telemetry/src/context-aware-slog.js [hunk 48]
```diff
@@ -0,0 +1,348 @@
...
+     */
+    switch (body.type) {
+      case SLOG_TYPES.KERNEL.INIT.FINISH: {
+        initContext = null;
+        break;
+      }
+      case SLOG_TYPES.COSMIC_SWINGSET.END_BLOCK.START: {
+        triggerContext = restoreContext();
+        break;
+      }
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: We can restore the context in run start instead.

```suggestion
```

File: packages/telemetry/src/context-aware-slog.js [hunk 49]
```diff
@@ -0,0 +1,348 @@
...
+      case SLOG_TYPES.COSMIC_SWINGSET.AFTER_COMMIT_STATS: {
+        blockContext = null;
+        break;
+      }
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: We can consolidate here.

```suggestion
      case SLOG_TYPES.COSMIC_SWINGSET.AFTER_COMMIT_STATS:
```

File: packages/telemetry/src/context-aware-slog.js [hunk 50]
```diff
@@ -0,0 +1,348 @@
...
+          'run.trigger.blockHeight': Number(blockHeight),
+          'run.trigger.txHash': txHash,
+          'run.trigger.msgIdx': Number(msgIdx),
+        };
+        persistContext(triggerContext);
+        break;
+      }
+      // eslint-disable-next-line no-restricted-syntax
+      case SLOG_TYPES.COSMIC_SWINGSET.RUN.START: {
+        if (!triggerContext && finalBody.runNum !== 0) {
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Let's restore the trigger context here.

```suggestion
        if (finalBody.runNum === 0) {
          assert(!triggerContext);
          triggerContext = restoreContext(); // Restore persisted context if any
        } else if (!triggerContext) {
```

File: packages/telemetry/src/context-aware-slog.js [hunk 51]
```diff
@@ -0,0 +1,348 @@
...
+          'run.num': null,
+          'run.id': `${triggerType}-${finalBody.inboundNum}`,
+          'run.trigger.type': triggerType,
+          'run.trigger.source': finalBody.source,
+          'run.trigger.sender': finalBody.sender,
+          'run.trigger.blockHeight': Number(blockHeight),
+          'run.trigger.txHash': txHash,
+          'run.trigger.msgIdx': Number(msgIdx),
+        };
+        persistContext(triggerContext);
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]:
```suggestion
```

File: packages/telemetry/src/context-aware-slog.js [hunk 52]
```diff
@@ -0,0 +1,348 @@
...
+          // TODO: add explicit slog events of both timer poll and install bundle
+          // https://github.com/Agoric/agoric-sdk/issues/10332
+          triggerContext = {
+            'run.num': null,
+            'run.id': `unknown-${finalBody.blockHeight}-${finalBody.runNum}`,
+            'run.trigger.type': 'unknown',
+            'run.trigger.time': blockContext['block.time'],
+            'run.trigger.blockHeight': finalBody.blockHeight,
+          };
+          persistContext(triggerContext);
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]:
```suggestion
```

File: packages/telemetry/src/context-aware-slog.js [hunk 53]
```diff
@@ -0,0 +1,348 @@
...
+  const persistContext = context => {
+    lastPersistedTriggerContext = context;
+    return persistenceUtils?.persistContext?.(context);
+  };
+
+  const restoreContext = () => {
+    if (!lastPersistedTriggerContext)
+      lastPersistedTriggerContext =
+        persistenceUtils?.restoreContext?.() || null;
+    return lastPersistedTriggerContext;
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js:127]: ~Now that we're gonna persist `null` values as context, I think we should differentiate uninitialized (`undefined`) from `null` contexts (and of course let the initial value of the context be `undefined` above)~

```
    if (lastPersistedTriggerContext === undefined)
      lastPersistedTriggerContext =
        persistenceUtils?.restoreContext?.();
    return lastPersistedTriggerContext;
```

File: packages/telemetry/src/context-aware-slog.js [hunk 54]
```diff
@@ -0,0 +1,348 @@
...
+      case SLOG_TYPES.COSMIC_SWINGSET.BRIDGE_INBOUND:
+      case SLOG_TYPES.COSMIC_SWINGSET.DELIVER_INBOUND: {
+        const [blockHeight, txHash, msgIdx] = (
+          finalBody.inboundNum || ''
+        ).split('-');
+        const [, triggerType] =
+          /cosmic-swingset-([^-]+)-inbound/.exec(body.type) || [];
+
+        triggerContext = {
+          'run.num': null,
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I forgot that this would transiently show up in the output for this event. `undefined` will make it be skipped while still reserving the position.

```suggestion
          'run.num': undefined,
```

File: packages/telemetry/src/context-aware-slog.js [hunk 55]
```diff
@@ -0,0 +1,348 @@
...
+        blockContext = {
+          'block.height': finalBody.blockHeight || 0,
+          'block.time': finalBody.blockTime,
+        };
+        triggerContext = {
+          'run.num': null,
+          'run.id': `bootstrap-${finalBody.blockTime}`,
+          'run.trigger.type': 'bootstrap',
+          'run.trigger.time': finalBody.blockTime,
+        };
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Let's move this after reporting

```suggestion
```

File: packages/telemetry/src/context-aware-slog.js [hunk 56]
```diff
@@ -0,0 +1,348 @@
...
+
+    /**
+     * Add any after report operations here
+     * like resetting context data
+     */
+    switch (body.type) {
+      case SLOG_TYPES.KERNEL.INIT.FINISH: {
+        initContext = null;
+        break;
+      }
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js:303]: Let's set the bootstrap trigger context here.

```suggestion
      }
      case SLOG_TYPES.COSMIC_SWINGSET.BOOTSTRAP_BLOCK.START: {
        triggerContext = {
          'run.num': undefined,
          'run.id': `bootstrap-${finalBody.blockTime}`,
          'run.trigger.type': 'bootstrap',
          'run.trigger.time': finalBody.blockTime,
        };
      }
```

File: packages/telemetry/src/context-aware-slog.js [hunk 57]
```diff
@@ -0,0 +1,348 @@
...
+        };
+        break;
+      }
+      case SLOG_TYPES.CLIST: {
+        assert(!!crankContext);
+        crankContext['crank.vatID'] = finalBody.vatID;
+        break;
+      }
+      case SLOG_TYPES.REPLAY.START: {
+        replayContext = { replay: true };
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: I think we need to reset the context on finish for the reporting of the finish event, or it gets some leftover delivery details. Also let's include the vatID here.



```suggestion
      case SLOG_TYPES.REPLAY.START:
      case SLOG_TYPES.REPLAY.FINISH: {
        replayContext = { replay: true, 'crank.vatID': finalBody.vatID };
```

File: packages/telemetry/src/context-aware-slog.js [hunk 58]
```diff
@@ -0,0 +1,348 @@
...
+      START: 'cosmic-swingset-end-block-start',
+    },
+    // eslint-disable-next-line no-restricted-syntax
+    RUN: {
+      FINISH: 'cosmic-swingset-run-finish',
+      START: 'cosmic-swingset-run-start',
+    },
+  },
+  CRANK: {
+    RESULT: 'crank-result',
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog.js]: Oh I missed the typo here! Because of this we were not resetting the crank context.

```suggestion
    FINISH: 'crank-finish',
```

**Review by mhofman — COMMENTED** [review]
Well I knew I wouldn't get it right just by staring at the code generating slog events. After looking at the output, looks like we have some tweaks to make.

File: packages/telemetry/src/context-aware-slog.js (hunk 47 above)
Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js:322]: Actually I think we can persist an empty context instead (so you can keep `null` as missing).

```suggestion
        persistContext(finalBody.remainingBeans > 0 ? {} : triggerContext);
        triggerContext = null;
```

File: packages/telemetry/src/otel-context-aware-slog.js (hunk 45 above)
Comment (usmanmani1122) [reply packages/telemetry/src/otel-context-aware-slog.js]: According to [microtime.nowDouble](https://www.npmjs.com/package/microtime#microtimenowdouble) documentation, it returns microseconds precision so I don't think we should ever get 9 decimal places right?

File: packages/telemetry/src/context-aware-slog.js (hunk 47 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js:325]: I think we should also add an assertion here for `triggerContext` to exist here right?

Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js:322]: Since we have no assertion on `triggerContext` here, it could be `null` at this point. So I think we should either do
```
persistContext(finalBody.remainingBeans || !triggerContext ? {} : triggerContext);
```
Or have an assertion:
```
assert(!!triggerContext);
persistContext(finalBody.remainingBeans ? {} : triggerContext)
```

File: packages/telemetry/src/context-aware-slog.js (hunk 44 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js]: This raises a ts error. Though `LogAttributes` is assignable to the constraint of type `T`, ts cannot guarantee that the constructed object matches `T` as `T` is generic and could be any subtype of `Record<string, any>`  so I have moved this type assertion to the return to let ts now that we are guaranteeing the return type conforms to `T & LogAttributes`

File: packages/telemetry/src/context-aware-slog.js (hunk 47 above)
Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js:322]: There should be a trigger context by this point. Let's add an assertion

File: packages/telemetry/src/otel-context-aware-slog.js (hunk 45 above)
Comment (mhofman) [reply packages/telemetry/src/otel-context-aware-slog.js]: Precision of the source data doesn't mean anything for the representation as an IEEE 754 number. Those tend to do weird things often enough that I wouldn't bet on there being a max of 9 digits when stringified.

File: packages/telemetry/src/context-aware-slog.js (hunk 44 above)
Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js]: Oh yeah classic generic silliness

File: packages/telemetry/src/otel-context-aware-slog.js (hunk 45 above)
Comment (usmanmani1122) [reply packages/telemetry/src/otel-context-aware-slog.js]: Done

File: packages/telemetry/src/context-aware-slog.js (hunk 47 above)
Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js:322]: Done

File: packages/telemetry/src/otel-context-aware-slog.js [hunk 59]
```diff
@@ -91,7 +91,7 @@ export const makeSlogSender = async options => {
     const [secondsStr, fractionStr] = String(timestamp).split('.');
     const seconds = parseInt(secondsStr, 10);
     const nanoSeconds = parseInt(
-      (fractionStr || String(0)).padEnd(9, String(0)),
+      (fractionStr || String(0)).padEnd(9, String(0)).slice(0, 9),
```
Comment (mhofman) [inline packages/telemetry/src/otel-context-aware-slog.js:90]: The slicing should be done on `fractionStr`, not the result of the padding.

File: packages/telemetry/src/otel-context-aware-slog.js [hunk 60]
```diff
@@ -0,0 +1,110 @@
...
+  LoggerProvider,
+  SimpleLogRecordProcessor,
+} from '@opentelemetry/sdk-logs';
+import { readFileSync, writeFileSync } from 'fs';
+import { makeContextualSlogProcessor } from './context-aware-slog.js';
+import { getResourceAttributes } from './index.js';
+import { serializeSlogObj } from './serialize-slog-obj.js';
+
+/**
+ * @typedef {import('./index.js').MakeSlogSenderOptions} Options
```
Comment (mhofman) [inline packages/telemetry/src/otel-context-aware-slog.js]:
```suggestion
 * @import {MakeSlogSenderOptions as Options} from './index.js'
```

File: packages/telemetry/src/otel-context-aware-slog.js [hunk 61]
```diff
@@ -0,0 +1,110 @@
...
+ */
+
+const DEFAULT_CONTEXT_FILE = 'slog-context.json';
+const FILE_ENCODING = 'utf8';
+
+/**
+ * @param {string} filePath
+ */
+export const getContextFilePersistenceUtils = filePath => {
+  console.log(`Using file ${filePath} for slogger context`);
```
Comment (mhofman) [inline packages/telemetry/src/otel-context-aware-slog.js]: Let's avoid polluting stdout

```suggestion
  console.warn(`Using file ${filePath} for slogger context`);
```

File: packages/telemetry/src/otel-context-aware-slog.js [hunk 62]
```diff
@@ -0,0 +1,110 @@
...
+    },
+
+    /**
+     * @returns {import('./context-aware-slog.js').Context | null}
+     */
+    restoreContext: () => {
+      try {
+        return JSON.parse(readFileSync(filePath, FILE_ENCODING));
+      } catch (parseErr) {
+        console.warn('Error reading context from file: ', parseErr);
```
Comment (mhofman) [inline packages/telemetry/src/otel-context-aware-slog.js]: This is actually an error

```suggestion
        console.error('Error reading context from file: ', parseErr);
```

File: packages/telemetry/src/otel-context-aware-slog.js [hunk 63]
```diff
@@ -0,0 +1,110 @@
...
+  };
+};
+
+/**
+ * @param {Options} options
+ */
+export const makeSlogSender = async options => {
+  const { CHAIN_ID, OTEL_EXPORTER_OTLP_ENDPOINT } = options.env || {};
+  if (!(OTEL_EXPORTER_OTLP_ENDPOINT && options.stateDir))
+    return console.warn(
```
Comment (mhofman) [inline packages/telemetry/src/otel-context-aware-slog.js]: so is this
```suggestion
    return console.error(
```

**Review by mhofman — APPROVED** [review]
I have verified that the processor seem to generate coherent context data.

Once the slicing of timestamp fraction is fixed, feel free to merge.

Also consider adding a `context-aware-slog-file.js` (or better name) that simply writes the contextualized data to a file. Here is what I used (to experiment with `ingest-slog`), but feel free to adapt (or add support for persisting context, probably by extracting the tool from the otel file into a standalone module).

```js
import { makeFsStreamWriter } from '@agoric/internal/src/node/fs-stream.js';
import { makeContextualSlogProcessor } from './context-aware-slog.js';
import { serializeSlogObj } from './serialize-slog-obj.js';

/**
 * @import {MakeSlogSenderOptions as Options} from './index.js'
 */

/**
 * @param {Options} options
 */
export const makeSlogSender = async options => {
  const { CHAIN_ID, CONTEXTUAL_SLOGFILE } = options.env || {};
  if (!CONTEXTUAL_SLOGFILE)
    return console.warn(
      'Ignoring invocation of slogger "context-aware-slog-file" without the presence of "CONTEXTUAL_SLOGFILE"',
    );

  const stream = await makeFsStreamWriter(CONTEXTUAL_SLOGFILE);

  if (!stream) {
    return undefined;
  }

  const contextualSlogProcessor = makeContextualSlogProcessor({
    'chain-id': CHAIN_ID,
  });

  /**
   * @param {import('./context-aware-slog.js').Slog} slog
   */
  const slogSender = slog => {
    const contextualizedSlog = contextualSlogProcessor(slog);

    // eslint-disable-next-line prefer-template
    stream.write(serializeSlogObj(contextualizedSlog) + '\n').catch(() => {});
  };

  return Object.assign(slogSender, {
    forceFlush: () => stream.flush(),
    shutdown: () => stream.close(),
  });
};
```

File: packages/telemetry/src/otel-context-aware-slog.js (hunk 59 above)
Comment (usmanmani1122) [reply packages/telemetry/src/otel-context-aware-slog.js:90]: What difference would that make? Even if `fractionStr` returns a length greater than 9, padding would have no effect so wouldn't we will be slicing on `fractionStr` indirectly?
Additionally, looking at the [source code](https://github.com/wadey/node-microtime/blob/c0a0020fa6e03ece44377d04d10f43c7d8456df7/src/microtime.cc#L19-L31) of `gettimeofday` (used by `NowDouble` internally):
```
int gettimeofday(struct timeval *tv, struct timezone *tz) {
  FILETIME ft;
  (*getSystemTime)(&ft);
  unsigned long long t = ft.dwHighDateTime;
  t <<= 32;
  t |= ft.dwLowDateTime;
  t /= 10;
  t -= 11644473600000000ULL;
  tv->tv_sec = (long)(t / 1000000UL);
  tv->tv_usec = (long)(t % 1000000UL);

  return 0;
}

Napi::Value NowDouble(const Napi::CallbackInfo &info) {
  Napi::Env env = info.Env();
  timeval t;
  int r = gettimeofday(&t, NULL);
  if (r < 0) {
    ErrnoException(env, errno).ThrowAsJavaScriptException();
    return env.Null();
  }

  return Napi::Number::New(env, t.tv_sec + (t.tv_usec * 0.000001));
}
```
The microsecond part `tv_usec` should never be more then 6 digits as it is a mode of a number with `1000000` so I think we shouldn't need the slice. Thoughts?

Comment (mhofman) [reply packages/telemetry/src/otel-context-aware-slog.js:90]: > Even if `fractionStr` returns a length greater than 9, padding would have no effect so wouldn't we will be slicing on `fractionStr` indirectly?

Fair. For some reason it feels more confusing to me to slice after.

> The microsecond part `tv_usec` should never be more then 6 digits as it is a mode of a number with `1000000` so I think we shouldn't need the slice. Thoughts?

Right, a number of seconds since the UNIX epoch for our current dates should indeed have sufficient precision such that as represented by a IEEE 754 float, the fractional part would remain with less than 6 digits. It's just that if for some reason there is any arithmetic done anywhere in between, we risk triggering Number weirdness

```js
console.log(String(1.1 + 1.3)); // 2.4000000000000004
```

File: packages/telemetry/src/context-aware-slog-file.js [hunk 64]
```diff
@@ -0,0 +1,38 @@
...
+
+  const contextualSlogProcessor = makeContextualSlogProcessor({
+    'chain-id': CHAIN_ID,
+  });
+
+  /**
+   * @param {import('./context-aware-slog.js').Slog} slog
+   */
+  const slogSender = slog =>
+    stream.write(`${serializeSlogObj(contextualSlogProcessor(slog))}\n`);
```
Comment (mhofman) [inline packages/telemetry/src/context-aware-slog-file.js]: Please restore the `catch` and don't return the promise (`slogSender` is called without any await). I want to avoid unhandled rejections when `write` fails (since those are rolled into the `flush` report.

File: packages/telemetry/src/otel-context-aware-slog.js [hunk 65]
```diff
@@ -0,0 +1,106 @@
...
+    const { timestamp, ...logRecord } = contextualSlogProcessor(slog);
+
+    const [secondsStr, fractionStr] = String(timestamp).split('.');
+    const seconds = parseInt(secondsStr, 10);
+    const nanoSeconds = parseInt(
+      (fractionStr || String(0)).padEnd(9, String(0)).slice(0, 9),
+      10,
+    );
+
+    return logger.emit({
```
Comment (mhofman) [inline packages/telemetry/src/otel-context-aware-slog.js]: I just realized we shouldn't return the result of `logger.emit` because the `slogSender` result is not handled.

Do you know if any previous error is rolled into the processor's flush? If not we may need to accumulate the results in a `flushed` promise, and await that in `forceFlush` (and `shutdown`). See https://github.com/Agoric/agoric-sdk/pull/10343/commits/8431559fbfe8766dcfa14852dd54254634a999bb for a potentially reusable pattern.

**Review by mhofman — COMMENTED** [review]
I forgot about the return value of `slogSender`. Let's make sure we don't end up with unhandled rejections.

File: packages/telemetry/src/context-aware-slog-file.js (hunk 64 above)
Comment (mhofman) [reply packages/telemetry/src/context-aware-slog-file.js]: Also I had used string concatenation in this case because from recollection it's more performant, and this is a fairly hot path.

File: packages/telemetry/src/otel-context-aware-slog.js (hunk 59 above)
Comment (usmanmani1122) [reply packages/telemetry/src/otel-context-aware-slog.js:90]: I’ll keep the slice just to be safe 👍

File: packages/telemetry/src/otel-context-aware-slog.js (hunk 65 above)
Comment (usmanmani1122) [reply packages/telemetry/src/otel-context-aware-slog.js]: `emit` function queues a promise representing the log record. On [forceFlush](https://github.com/open-telemetry/opentelemetry-js/blob/eb3ca4fb07ee31c62093f5fcec56575573c902ce/experimental/packages/otlp-exporter-base/src/OTLPExporterBase.ts#L108-L112), all the pending promises are awaited:
```
forceFlush(): Promise<void> {
    return Promise.all(this._sendingPromises).then(() => {
      /** ignore resolved values */
    });
  }
```
Individual errors are not available though as `Promise.all` is used. I have added error handling on the returned error.

File: packages/telemetry/src/otel-context-aware-slog.js [hunk 66]
```diff
@@ -91,16 +91,28 @@ export const makeSlogSender = async options => {
...
+    logger.emit({
       ...JSON.parse(serializeSlogObj(logRecord)),
       severityNumber: SeverityNumber.INFO,
       timestamp: [seconds, nanoSeconds],
     });
   };
 
   return Object.assign(slogSender, {
-    forceFlush: () => logRecordProcessor.forceFlush(),
+    forceFlush: otelLogExporter.forceFlush,
```
Comment (mhofman) [inline packages/telemetry/src/otel-context-aware-slog.js]: It doesn't look like that method is bound. 

```suggestion
    forceFlush: () => otelLogExporter.forceFlush(),
```

File: packages/telemetry/src/otel-context-aware-slog.js [hunk 67]
```diff
@@ -0,0 +1,118 @@
...
+          otelLogExporter.forceFlush().then(
+            () => Promise.reject(shutdownError),
+            flushError =>
+              Promise.reject(AggregateError([shutdownError, flushError])),
+          ),
+        )
+        .then(
+          () => {},
+          flushError => Promise.reject(flushError),
+        ),
```
Comment (mhofman) [inline packages/telemetry/src/otel-context-aware-slog.js]: Let's avoid promise chaining. Also these methods of otel don't seem bound. There is probably a cleaner way, but the following should work:

```suggestion
    shutdown: async () => {
      const error = [];;
      try {
        await logRecordProcessor.shutdown();
      } catch (err) {
        errors.push(err);
      }
      
      try {
        await otelLogExporter.forceFlush();
      } catch (err) {
        errors.push(err);
      }
      
      switch (errors.length) {
        case 0:
          return;
        case 1:
          throw errors[0];
        default:
          throw AggregateError(errors);
      }
    },
```

File: packages/telemetry/src/otel-context-aware-slog.js (hunk 65 above)
Comment (mhofman) [reply packages/telemetry/src/otel-context-aware-slog.js]: Perfect, we can rely on their `forceFlush`. Well their `Promise.all` swallows multiple errors, but that's a common mistake people make, and it's good enough in this case.

**Review by mhofman — COMMENTED** [review]
Let's fix the usage of non bound methods.

File: packages/telemetry/src/otel-context-aware-slog.js (hunk 66 above)
Comment (usmanmani1122) [reply packages/telemetry/src/otel-context-aware-slog.js]: Good point

File: packages/telemetry/src/otel-context-aware-slog.js (hunk 67 above)
Comment (usmanmani1122) [reply packages/telemetry/src/otel-context-aware-slog.js]: Done

**Review by mhofman — APPROVED** [review]

File: packages/telemetry/src/context-aware-slog.js (hunk 47 above)
Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js:322]: I just realized that in the final version the `> 0` part of the check was dropped, which causes the persisted context to always be empty.

Comment (usmanmani1122) [reply packages/telemetry/src/context-aware-slog.js:322]: So we are missing the context in case of negative remaining beans right?

Comment (mhofman) [reply packages/telemetry/src/context-aware-slog.js:322]: We are missing the persisted context roughly always because the remaining beans is almost never 0.
