### PR TITLE
Mitigate more ag-solo robustness issues

### LINKED ISSUE #3289: CapTP Cannot read property 'res' of undefined
## Describe the bug
The load gen seem to sometimes cause a non-fatal error in CapTP when starting. It feels like a race where something is not yet initialized

## To Reproduce
1. Checkout https://github.com/Agoric/testnet-load-generator/ and follow setup instructions for chain and client
2. Run `yarn loadgen`
3. Observe error (or not)

## Expected behavior
No errors

## Platform Environment
 - **what OS are you using? what version of Node.js?** WSL2 (Ubuntu), node 14
 - **is there anything special/unusual about your platform?** 
 - **what version of the Agoric-SDK are you using? (run `git describe --tags --always`)** commit `fa7ff5e55e15e49d366852f5435b6dfa81396f73`

## Additional context
This was observed a few times as part of the automated load gen runner (not yet checked in), which performs the reproduction steps programmatically.

## Stacktrace
<details>

```
TypeError#1: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#2)
TypeError#2: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#3)
TypeError#3: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#4)
TypeError#4: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#5)
TypeError#5: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#6)
TypeError#6: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#7)
TypeError#7: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#8)
TypeError#8: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#9)
TypeError#9: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#10)
TypeError#10: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

CapTP bundle exception: (TypeError#11)
TypeError#11: Cannot read property 'res' of undefined
  at CTP_RETURN (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:332:12)
  at dispatch (/workspaces/agoric/agoric-sdk/packages/captp/lib/captp.js:389:9)
  at WebSocket.<anonymous> (/workspaces/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:110:13)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.EventEmitter.emit (domain.js:467:12)
  at Receiver.receiverOnMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.EventEmitter.emit (domain.js:467:12)
  at Receiver.dataMessage (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
  at Receiver.getData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
  at Receiver.startLoop (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
  at Receiver._write (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
  at writeOrBuffer (internal/streams/writable.js:358:12)
  at Receiver.Writable.write (internal/streams/writable.js:303:10)
  at Socket.socketOnData (/workspaces/agoric/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

</details>

### PR DESCRIPTION
**Pull request by michaelfig**
The three commits are mostly independent and can be read separately.

- use `epoch` to help prevent accidental CapTP crosstalk with multiple `agoric deploy` closes #3289
- make sure the wallet backend deployment is idempotent (only one active wallet backend)
- increase our default HTTP timeout to help prevent EOF error refs Agoric/testnet-notes#30

### CODE REVIEW

File: packages/agoric-cli/lib/deploy.js [hunk 1]
```diff
@@ -97,8 +97,15 @@ export default async function deployMain(progname, rawArgs, powers, opts) {
       connected = true;
       try {
         console.debug('Connected to CapTP!');
-        const { dispatch, getBootstrap } = makeCapTP('bundle', obj =>
-          sendJSON(ws, obj),
+        // Help disambiguate connections.
+        const epoch = Date.now();
```
Comment (dckc) [inline packages/agoric-cli/lib/deploy.js]: please pass `now` in via `powers`.

File: packages/solo/src/scratch.js [hunk 2]
```diff
@@ -2,25 +2,27 @@ import { Far } from '@agoric/marshal';
 
 export default function makeScratchPad() {
   const map = new Map();
-  async function get(idP) {
```
Comment (dckc) [inline packages/solo/src/scratch.js:5]: I don't see any substantive change here. Drive-by refactor? Leave a note in the commit comment in the future, please.

**Review by dckc — CHANGES_REQUESTED** [review]
grant access to the clock explicitly, please

File: packages/solo/src/scratch.js (hunk 2 above)
Comment (michaelfig) [reply packages/solo/src/scratch.js:5]: The substantive change was adding `init`.

Comment (michaelfig) [reply packages/solo/src/scratch.js:5]: I also added `keys` and `delete` for better Store-like compatibility.

Comment (dckc) [reply packages/solo/src/scratch.js:5]: ah. I somehow couldn't see it. thanks.

**Review by dckc — APPROVED** [review]
good stuff.
