### PR TITLE
7004 wallet errors

### LINKED ISSUE #7004: [requirement] any failure in smart-wallet observable in chain storage
## What is the Problem Being Solved?

There are some failures in the smart wallet contract (walletFactory.js) that throw or simply log to console. Because of the async nature of of the Cosmos bridge, that rejection don't get back to the initiator.

## Description of the Design

Ensure that every failure in the contract is observable, using chain storage.

For errors before the wallet is known, `published.wallet.lastError`: https://github.com/Agoric/agoric-sdk/blob/master/packages/smart-wallet/src/walletFactory.js#L152-L169

For errors on a wallet before an offer execution can handle it, `published.wallet.{addr}.lastError`: https://github.com/Agoric/agoric-sdk/blob/master/packages/smart-wallet/src/walletFactory.js#L152-L169

Anything that gets into an offer handler should write to the offerStatus when it fails.

### PR DESCRIPTION
**Pull request by turadg**
closes: #7004

## Description

Users need to be able find out about errors in their wallet actions. The offer handler already publishes errors to vstorage. This makes it so that errors that happen earlier, in reading the walletAction, also get published, under a new `updated: walletAction` status.

It leaves out publishing errors before that because there's no way yet to associate it with the account owner or transaction. And once there is, feeding it back will be done by the Cosmos bridge instead of the contract.

This also cleans up error handling within the offer executor. This required test changes, mostly simplifications to use `throwsAsync` instead of checking vstorage after. We have sufficient tests for offer failures writing to vstorage so we don't have to test it everywhere.

### Security Considerations

Error's `message` is logged to vstorage. The error construction should redact as needed.

### Scaling Considerations

Writes walletAction errors to vstorage.

### Documentation Considerations

--

### Testing Considerations

CI

### CODE REVIEW

File: packages/vats/test/bootstrapTests/test-vaults-integration.js [hunk 1]
```diff
@@ -182,15 +202,17 @@ test('close vault', async t => {
     {
       offerId: 'close-well',
       collateralBrandKey,
-      giveMinted: 5.0,
```
Comment (turadg) [inline packages/vats/test/bootstrapTests/test-vaults-integration.js:185]: this was a bug in the test. it wasn't detected because I had mistakenly thought `numWantsSatisified: 1` meant it succeeded. There were no wants so they were trivially satisfied.

That it _looked like_ it succeeded and it didn't underlines the value of the promise rejecting.

**Comment by dckc** [comment]
> feeding it back will be done by the Cosmos bridge instead of the contract

I hope we have an issue to represent that plan.

This PR would still be forward progress without it, though...

File: packages/smart-wallet/src/payments.js [hunk 2]
```diff
@@ -1,3 +1,4 @@
+import { Fail } from '@agoric/assert';
```
Comment (dckc) [inline packages/smart-wallet/src/payments.js:1]: Where did we get on that idiom? Ah yes... #5672 is still open.

**Comment by samsiegart** [comment]
Are there any UI changes that need to accompany this?

File: packages/inter-protocol/test/smartWallet/test-oracle-integration.js [hunk 3]
```diff
@@ -272,16 +272,14 @@ test.serial('errors', async t => {
...
       roundId: 1,
       unitPrice: 1,
     }),
     {
-      error:
-        'Error: In "pushPrice" method of (OracleKit oracle): arg 0: unitPrice: number 1 - Must be a bigint',
-      // trivially satisfied because the Want is empty
-      numWantsSatisfied: 1,
+      message:
+        'In "pushPrice" method of (OracleKit oracle): arg 0: unitPrice: number 1 - Must be a bigint',
```
Comment (dckc) [inline packages/inter-protocol/test/smartWallet/test-oracle-integration.js:282]: Does the wallet UI need a corresponding update to error handling?

That would make this a BREAKING CHANGE, yes?

File: packages/smart-wallet/src/smartWallet.js [hunk 4]
```diff
@@ -492,14 +493,28 @@ export const prepareSmartWallet = (baggage, shared) => {
...
+            err => {
+              const { address, updatePublishKit } = this.state;
+              console.error(
+                'wallet',
+                address,
+                'handleBridgeAction error:',
+                err,
+              );
+              updatePublishKit.publisher.publish({
+                updated: 'walletAction',
```
Comment (dckc) [inline packages/smart-wallet/src/smartWallet.js:510]: impacts wallet UI?

File: packages/smart-wallet/src/walletFactory.js [hunk 5]
```diff
@@ -153,8 +154,20 @@ export const prepare = async (zcf, privateArgs, baggage) => {
     }),
     {
       /**
+       * Designed to be called by the bridgeManager vat.
+       *
+       * If this errors before calling handleBridgeAction(), the failure will not be observable. The
+       * promise does rejects, but as of now bridge manager drops instead of handling it. Eventually
```
Comment (dckc) [inline packages/smart-wallet/src/walletFactory.js]:
```suggestion
       * promise does reject, but as of now bridge manager drops instead of handling it. Eventually
```

File: packages/smart-wallet/src/walletFactory.js [hunk 6]
```diff
@@ -153,8 +154,20 @@ export const prepare = async (zcf, privateArgs, baggage) => {
...
+       * we'll make the bridge able to give feedback about the requesting transaction. Meanwhile we
+       * could write the error to chainStorage but we don't have a guarantee of the wallet owner to
+       * associate it with. (We could have a shared `lastError` node but it would be so noisy as to
+       * not provide much info to the end user.
```
Comment (dckc) [inline packages/smart-wallet/src/walletFactory.js]:
```suggestion
       * associate it with. (We could have a shared `lastError` node but it would be so noisy as to
       * not provide much info to the end user.)
```

File: packages/vats/test/bootstrapTests/test-vaults-integration.js [hunk 7]
```diff
@@ -18,6 +18,19 @@ const test = anyTest;
 // presently all these tests use one collateral manager
 const collateralBrandKey = 'IbcATOM';
 
+const likePayouts = (collateral, minted) => ({
+  Collateral: {
+    value: {
+      digits: String(collateral * 1_000_000),
```
Comment (dckc) [inline packages/vats/test/bootstrapTests/test-vaults-integration.js:24]: I don't think this will survive the move to smallcaps (#6822).

Not critical. We'll notice when it's time.

**Review by dckc — COMMENTED** [review]
I need to understand the compatibility impact on the wallet UI better.

With this change, if the wallet UI doesn't change, will the wallet UI fail to notice some of the errors that it currently notices?

File: packages/inter-protocol/test/smartWallet/test-oracle-integration.js (hunk 3 above)
Comment (turadg) [reply packages/inter-protocol/test/smartWallet/test-oracle-integration.js:282]: That would be a breaking change, but the wallet UI isn't affected. The same errors are written to vstorage.

File: packages/smart-wallet/src/smartWallet.js (hunk 4 above)
Comment (turadg) [reply packages/smart-wallet/src/smartWallet.js:510]: Wallet UI can begin to observe these messages. It shouldn't break because it should never have assumed that new updates would never be added.

**Comment by turadg** [comment]
> With this change, if the wallet UI doesn't change, will the wallet UI fail to notice some of the errors that it currently notices?

No, this doesn't change any of the what has been published to vstorage. The only change to vstorage is that it adds a new update event for `walletAction` messages. The wallet UI can begin to read and display those. A good idea but not a breaking change.

The changes to the tests for existing messages is that now the function call carries the rejection message so tests running in JS (which can get the promise) don't need to resort to reading over RPC.

**Review by dckc — APPROVED** [review]
ok, not a breaking change then.

**Comment by turadg** [comment]
> > feeding it back will be done by the Cosmos bridge instead of the contract
> 
> I hope we have an issue to represent that plan.

https://github.com/Agoric/agoric-sdk/issues/7148
