### PR TITLE
fix liveslots double-free of virtual object/collection

### LINKED ISSUE #7353: liveslots double-free of virtual objects/collections when RAM and vdata pillars drop on same BOYD
## Describe the bug

While working on #7333, I found a bug in the way liveslots handles GC of virtual objects and collections. If we've got two things (each of which can either be a virtual object, or a virtual collection) A and B, such that A holds a vdata reference to B (either A has `state.foo = B`, or `collectionA.init('key', B)`), then we drop the in-RAM representatives for both A and B close enough in time that they get noticed in the same BOYD, *and* if the vref of A sorts lexicographically earlier than that of B, then:

* both A and B's vrefs are in `possiblyDeadSet`, placed there by the finalizer callbacks
* when BOYD runs:
  * `scanForDeadObjects()` promotes both to `deadSet`, since they both still lack RAM pillars
    * (note that in the old implementation, `deadSet` really means "things which definitely just lost their RAM pillar", and does not make any claim about possible vdata or export pillars)
  * vrefA is passed to `vrm.possibleVirtualObjectDeath()`, which checks the vdata and export pillars, and deletes the object if they are missing
    * deleting A causes vrefB to be sent to `addToPossiblyDeadSet`, because A might have been the only thing keeping the things it references alive
  * vrefB is passed to `vrm.possibleVirtualObjectDeath()`, which does the same, and deletes B
    * the vdata pillar check it does looks at references that were deleted a moment before, from A
    * so if B had been checked before A, then the vrefB vdata pillar check would have returned `true`, and B would *not* have been deleted (this is the source of the lexicographic-ordering dependency)
  * `scanForDeadObjects()` gets to the end of its loop, and notices that `possiblyDeadSet` is non-empty (it contains vrefB), so it loops again
    * it passes `vrefB` again to `vrm.possibleVirtualObjectDeath()`, which sees no vdata (A was deleted last time), and attempts to delete B again

The second deletion attempt fails. When B is a virtual object, it fails when `deleteStoredVO` needs to fetch the data first (to find references to decref), which fails after the backing vatstore key is gone. When B is a collection, it fails when `deleteCollection` attempts to fetch the metadata before walking the entries to decref. In the previous version, both attempts used to be ignored silently, which might be why we didn't notice this earlier.

The logic of the GC code needs to be changed to separate `vrm.possibleVirtualObjectDeath` into two pieces: `isVirtualObjectReachable()` (which does the two pillar checks), and `deleteVirtualObject()` (which does the actual deletion). We should filter the Representative vrefs in `possiblyDeadSet` through `isVirtualObjectReachable` to build `deadSet` (which now lives up to the name: vrefs that definitely lack all three pillars, and need to be deleted). Then, once `deadSet` is sorted, we pass its Representative vrefs to `deleteVirtualObject()`, which can delete the actual data.

In our example, the initial `possiblyDeadSet` contains vrefs for both A and B, because both just lost their RAM pillars. But only A will make it into `deadSet`, because B is kept alive by a vdata reference from A's state/entries. The first time through the loop, we only delete A, which adds B back to `possiblyDeadSet` as it drops the refcount to zero. Then, we'll make a *second* pass through the loop, and this time A *will* get promoted from `possiblyDeadSet` to (actually-)`deadSet`, and will get deleted.

Intuitively, we should expect one pass through this loop for every edge we must traverse from the newly-deleted RAM pillars through to reference graph to VOs that are no longer reachable by any pillars.

I've written up a test to exercise the full 2x2x2 matrix of:
* A (which holds B) is a virtual object, or a collection
* B (which holds nothing) is a virtual object, or a collection
* A's vref is lexicographically higher, or lower, than B's

### PR DESCRIPTION
**Pull request by warner**
fix liveslots double-free of virtual object/collection

When A and B are any combination of virtual objects or collections,
and A holds a reference to B, and no other vdata/export references
exist to either, and both A and B's Representatives are dropped, and
both drops are noticed in the same BOYD, and A's vref is
lexicographically earlier than B's, then liveslots would attempt to
free B twice.

The cause was using `vrm.possibleVirtualObjectDeath()`, which combines
a remaining-pillar check with the deletion code. Deleting a virtual
object or collection necessarily examines the contents (to decrement
their refcounts), and will add vrefs to possiblyDeadSet in the
process. For our example, deleting A caused B to get added back to
possiblyDeadSet, which caused a second deletion attempt as
scanForDeadObjects looped back around to pick up second-level dead
objects, even though B was deleted during the first pass, a moment
after A. If B's vref sorted earlier than A, possibleVirtualObjectDeath
would have not deleted B on the first pass, leaving it for the second,
and only trying to delete it once.

In earlier versions of the code, this double free was silently
ignored. But since the introduction of dataCache and schemaCache, this
causes an assertion to fail, causing a crash.

The fix is to filter possiblyDeadSet through a new
`vrm.isVirtualObjectReachable()` predicate to generate deadSet,
and *then* delete the objects with a new `vrm.deleteVirtualObject`.

closes #7353

### CODE REVIEW

File: packages/swingset-liveslots/src/liveslots.js [hunk 1]
```diff
@@ -257,18 +257,37 @@ function build(
       // eslint-disable-next-line no-await-in-loop, @jessie.js/no-nested-await
       await gcTools.gcAndFinalize();
 
-      // `deadSet` is the subset of those vrefs which lack an in-memory
-      // manifestation *right now* (i.e. the non-resurrected ones), for which
-      // we must check the remaining pillars.
+      // possiblyDeadSet contains a baseref for everything (Presences,
+      // Remotables, Representatives) that might have lost a
+      // pillar. The object might still be supported by other pillars,
+      // and the lost pillar might have been reinstanted by the time
```
Comment (FUDCo) [inline packages/swingset-liveslots/src/liveslots.js]: s/reinstanted/reinstantiated/

File: packages/swingset-liveslots/src/liveslots.js [hunk 2]
```diff
@@ -257,18 +257,37 @@ function build(
...
+      // we get here. The first step is to filter this down to a list
+      // of definitely dead baserefs.
```
Comment (FUDCo) [inline packages/swingset-liveslots/src/liveslots.js]: "definitely dead baserefs"
Somehow need to insert a Princess Bride quote from Miracle Max here.

File: packages/swingset-liveslots/src/liveslots.js [hunk 3]
```diff
@@ -257,18 +257,37 @@ function build(
...
+          // eslint-disable-next-line no-use-before-define
+          if (vrm.isVirtualObjectReachable(baseRef)) {
+            continue; // vdata or export pillar remains
+          }
+        }
+        deadSet.add(baseRef);
       }
       possiblyDeadSet.clear();
 
+      // deadBaserefs now contains objects which are certainly dead
```
Comment (FUDCo) [inline packages/swingset-liveslots/src/liveslots.js]: Comment says `deadBaseRefs` but code says `deadSet`

**Review by FUDCo — APPROVED** [review]
Good catch, and nice explanation.
A couple of minor documentation nits that you can fix at your leisure.
