### PR TITLE
fix: better error messages if a zoe invitation is required

### LINKED ISSUE #1767: Better error message than "payment not found" when Zoe invitation is missing
**What is the Problem Being Solved?**

A number of methods use Zoe invitations, but when the invitation is missing, the error message is the default one for ERTP: `payment not found for (a string)\nSee console for error data.`. This may be confusing because the user may not know that invitations are payments. We should make better error messages that mention invitations rather than payments.

To find such error messages, search for `payment not found for` in the packages/zoe/test directory.

### PR DESCRIPTION
**Pull request by katelynsills**
This PR improves the error messages if a Zoe invitation is required and is not provided. This PR does not use `getInterfaceOf`, since that would require an additional `await`/turn. Instead, the `onRejection` callback is used to provide a better error message.

Closes #1767

### CODE REVIEW

File: packages/zoe/src/zoeService/zoe.js [hunk 1]
```diff
@@ -71,18 +76,24 @@ function makeZoe(vatAdminSvc, zcfBundleName = undefined) {
...
-      E(invitationKit.issuer)
+    getInstance: async invitation => {
+      await assertInvitation(invitation);
+      return E(invitationKit.issuer)
         .getAmountOf(invitation)
-        .then(amount => amount.value[0].instance),
-    getInstallation: invitation =>
-      E(invitationKit.issuer)
+        .then(amount => amount.value[0].instance);
+    },
```
Comment (Chris-Hibbert) [inline packages/zoe/src/zoeService/zoe.js]: This is asking the issuer twice.  I think one round trip is enough
```js
    getInstance: async invitation => {
      return E(invitationKit.issuer)
        .getAmountOf(invitation)
        .then(
          amount => amount.value[0].instance,
          () =>
            assert(
              false,
              details`A Zoe invitation is required, not ${invitation}`,
            ),
        );
    },
```
The helper function I extracted looks like this. You may prefer something else.
```js
  async function getAmountOfInvitationThen(invitation, onFulfill) {
    return E(invitationKit.issuer)
      .getAmountOf(invitation)
      .then(onFulfill, () =>
        assert(false, details`A Zoe invitation is required, not ${invitation}`),
      );
  }
```
If you feel that the cost of two round trips isn't as important as simple code (your version is simpler to read), I'm okay with that.

File: packages/zoe/src/zoeService/zoe.js [hunk 2]
```diff
@@ -367,81 +378,82 @@ function makeZoe(vatAdminSvc, zcfBundleName = undefined) {
...
-          } else {
-            // payments outside the give: clause are ignored.
-            return getAmountMath(proposal.want[keyword].brand).getEmpty();
-          }
-        });
+      await assertInvitation(invitation);
 
-        return Promise.all(paymentDepositedPs).then(amountsArray => {
-          const initialAllocation = arrayToObj(amountsArray, proposalKeywords);
+      const invitationAmount = await invitationKit.issuer.burn(invitation);
```
Comment (Chris-Hibbert) [inline packages/zoe/src/zoeService/zoe.js]: I think the same approach works here, even though it can't use the same helper.

**Review by Chris-Hibbert — APPROVED** [review]
I have a suggestion about a more efficient way to make the check, but this is good regardless of whether you change the approach.

**Comment by katelynsills** [comment]
I'm going to try rewriting this to make use of getInterfaceOf

File: packages/zoe/src/zoeService/zoe.js (hunk 1 above)
Comment (katelynsills) [reply packages/zoe/src/zoeService/zoe.js]: It turns out this is better than the `getInterfaceOf` solution, since that requires an extra turn. I'll switch to this. Thanks for the code!

File: packages/zoe/src/zoeService/zoe.js [hunk 3]
```diff
@@ -62,6 +62,17 @@ function makeZoe(vatAdminSvc, zcfBundleName = undefined) {
     return installation;
   };
 
+  /**
+   * @type {GetAmountOfInvitationThen}
+   */
```
Comment (Chris-Hibbert) [inline packages/zoe/src/zoeService/zoe.js]: Is there a reason to prefer three line declarations? Line 76 uses one line for a similar declaration.  I admit that my prejudice is to get as much code on the screen at once as I can, and it doesn't seem that that's universal.

```suggestion
  /** @type {GetAmountOfInvitationThen} */
```

File: packages/zoe/src/zoeService/zoe.js [hunk 4]
```diff
@@ -62,6 +62,17 @@ function makeZoe(vatAdminSvc, zcfBundleName = undefined) {
...
+  const getAmountOfInvitationThen = async (invitationP, onFulfilled) => {
+    const onRejected = () =>
+      assert.fail(details`A Zoe invitation is required, not ${invitationP}`);
+    return E(invitationKit.issuer)
+      .getAmountOf(invitationP)
+      .then(onFulfilled, onRejected);
```
Comment (Chris-Hibbert) [inline packages/zoe/src/zoeService/zoe.js:71]: I like the way this pulls out `onRejected`. It's the same number of lines as I used, but it's much more readable.

**Review by Chris-Hibbert — APPROVED** [review]
lgtm

File: packages/zoe/src/zoeService/zoe.js (hunk 3 above)
Comment (katelynsills) [reply packages/zoe/src/zoeService/zoe.js]: Oh, no reason. I will change it

Comment (katelynsills) [reply packages/zoe/src/zoeService/zoe.js]: Done

**Comment by katelynsills** [comment]
Shoot, the underlying branch should have been master for this. Will redo the merge.
