### PR TITLE
More general mailbox state persistence

### LINKED ISSUE #1605: cosmic-swingset probably drops outbound mailbox messages during partial-commit interruption
**Describe the bug**

https://github.com/Agoric/agoric-sdk/pull/1604#pullrequestreview-473684144 describes a problem I studied while reviewing a change to the way cosmic-swingset manages our two commit points. When we receive END_BLOCK, swingset commits its own state first, then cosmos-sdk commits the rest of the cosmos state. The `block_manager.js` code in that PR correctly manages the three situations that might occur:

* swingset commits, cosmos commits, process survives to the next block
* swingset commits, cosmos commits, process dies. At restart, both resume where they left off.
* swingset commits, process dies. At restart, swingset is one block ahead of cosmos, and tolerates replay.

However I think the way we're managing the "mailbox state" leaves a gap in that last situation, and outgoing mailbox messages sent during that block will be dropped.

The mailbox state is kept in a simple `Map` that is modified by the mailbox device, and read by the host code during calls to `saveChainState()`. This function copies outbound messages (and the `ackNum` which indicates which inbound messages have been seen) into the cosmos state vector. The initial contents of this `Map` come from the cosmos state vector: they are copied from the cosmos Keeper into the `Map` each time the process starts up.

When we hit the third situation described above, there will be some block N whose inbound actions provoked a new outbound mailbox message. The `Map` will contain this outbound message, and we'll call `saveChainState()` to copy the N-message into the cosmos keeper, where it will sit until cosmos reaches its commit point (spoiler alert: it never does). Then swingset calls `saveOutsideState()` to commit the swingset N-state, as well as the list of actions which got us to state N. Then the process dies.

At startup, the cosmos state (including the mailbox contents) will be for block N-1, but the swingset state (and saved actions) will be for block N. Cosmos will restart from N-1 and replay all the transactions for block N. Swingset will notice that it's receiving a BEGIN_BLOCK/DELIVER_TX/END_BLOCK for N, and that these actions match the ones that were saved, so it will ignore them. After it finishes ignoring the END_BLOCK for N, it knows the current in-memory swingset state (unchanged since the replacement process launched and loaded it from disk) matches the old in-memory state that was present in the previous process just before cosmos managed to commit. At that point, swingset is up-to-date.

However, the mailbox Map came from the cosmos state, which was loaded from N-1. And because we skipped all the swingset transactions, we never re-invoke the mailbox device to regenerate those outbound messages.

So I think the consequence is that any outbound mailbox messages generated in a block for which swingset commits its state but cosmos does not, will be dropped and never recreated.

I suspect the fix will be to include a full copy of the mailbox Map in the mailbox-device state (which is stored in the swingset state vector), as well as in the cosmos state vector (where downstream followers can see it, which is how ag-solo currently receives messages from the chain). The mailbox device should copy this into the external (i.e. cosmos) table once at startup time, and then again after every time the device is invoked (for new messages). We should probably *not* copy the starting cosmos state into the mailbox state. Instead, the mailbox device should treat the cosmos-side table as a pure output.

We clearly need a good test of this, which will involve some means to manually interrupt the chain after swingset has committed but before cosmos gets to commit. Then we restart the process from those commit points and see if the new cosmos state knows about the outbound message.

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #1605

Remove a layer of caching so that we only load and save the mailboxes we actually change.

Implement SDK sent message storage in the kernel DB so that on restart we replay the same SDK calls, asserting we get the same results.  Use this mechanism to persist all our mailbox changes, as well as other SDK calls such as IBC.

Finally, have `agoric deploy --provide=...` properly exit early if the provided dependencies wouldn't change the ag-solo loading state (i.e. they're not something the ag-solo is currently blocked on).  This prevents the wallet from being reinstalled every time the ag-solo restarts.

### CODE REVIEW

File: packages/SwingSet/src/devices/mailbox.js [hunk 1]
```diff
@@ -72,12 +72,36 @@ import Nat from '@agoric/nat';
 // replace it with one that tracks which parts of the state have been
 // modified, to build more efficient Merkle proofs.
 
-export function buildMailboxStateMap() {
-  const state = harden(new Map());
+export function importMailbox(data, inout = {}) {
+  const outbox = new Map();
+  data.outbox.forEach(m => {
+    outbox.set(Nat(m[0]), m[1]);
```
Comment (warner) [inline packages/SwingSet/src/devices/mailbox.js:78]: Huh, this reminds me how challenging it will be to maintain determinism in the face of antagonistic code which is trying to examine every conceivable input for subtle variations in behavior, like the insertion order of maps. We're fine here (assuming `importMailbox` is fed the same data that came out of `exportMailbox`, it will always be sorted, so the new `outbox` will have a consistent insertion order), and for normal vats we're probably safe (the `args` they get are created by JSON.parse, which at least has one obvious order to pick). But we'll probably need to do a determinism audit to find places where, I dunno, maybe we provide an error object or the new `vatParameters` or something, and while the contents are always exactly the same, some incarnations of the process build the object differently, allowing sufficiently determined code to behave nondeterministically.

I think we need to guard access to objects that might have hidden nondeterminism, and only allow vetted code to examine them. But that sounds a lot more difficult to search for than our usual "objects with significant authority" criteria.

**Review by warner — APPROVED** [review]
looks pretty good
