### PR TITLE
fix: update types to specify ERef<Issuer> on addPool()

### LINKED ISSUE #4810: AMM.addPool should accept `ERef<Issuer>`
## Describe the bug
It seems like the implementation of `addPool` would accept a Promise for `issuer` but the types don't document it as such.

## To Reproduce
https://github.com/Agoric/agoric-sdk/blob/3f535921c7a51f07976d98e4cb915693a9a1698e/packages/zoe/src/contracts/vpool-xyk-amm/pool.js#L225-L233

https://github.com/Agoric/agoric-sdk/blob/6c823468e780b0945d237ac5706bc01ff9d570d0/packages/run-protocol/src/vpool-xyk-amm/types.js#L94

## Expected behavior
Ability to pass an ERef<Issuer> without typing complaints

## Platform Environment
 - what version of the Agoric-SDK are you using? `294a3a04603dbf335c3e427ca2b39ea1c2c8031c`

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #4810

## Description

Just changes to type declarations.  Includes a test.

### Security Considerations

None.

### Documentation Considerations

None.

### Testing Considerations

Added a test.

### CODE REVIEW

File: packages/run-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js [hunk 1]
```diff
@@ -1168,8 +1168,9 @@ test('amm adding liquidity', async t => {
   const timer = buildManualTimer(console.log, 30n);
 
   const { zoe, amm } = await setupAmmServices(electorateTerms, centralR, timer);
+  // verify that addPool works with ERef<Issuer>.
```
Comment (turadg) [inline packages/run-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js]: not worth another commit but this comment seems to be about 1173 not 1172

**Review by turadg — APPROVED** [review]

File: packages/run-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/run-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js]: There was an `expect-error` for this issue that I neglected to remove, so I had another chance to make a change.
