### PR TITLE
fix(swingset): fsync snapshots 

### LINKED ISSUE #5419: kernel: ##### KERNEL PANIC: unable to re-create vat v4 ##### (truncated .gz file)
On a test network, a few validator nodes dropped, and were unable to recover from a reboot with the following error.

```
{"level":"info","time":"2022-05-21T19:55:22Z","message":"starting ABCI with Tendermint"}
{"level":"info","args":["ag-chain-cosmos","--home","/root/.agoric","start","--home=/state/agoriloadtest-8","--log_format=json"],"time":"2022-05-21T19:55:22Z","message":"Start chain delegating to JS executable"}
{"level":"info","time":"2022-05-21T19:55:23Z","message":"starting ABCI with Tendermint"}
{"level":"info","module":"proxy","impl":"multiAppConn","time":"2022-05-21T19:55:24Z","message":"Starting multiAppConn service"}
{"level":"info","module":"proxy","connection":"query","module":"abci-client","impl":"committingClient","time":"2022-05-21T19:55:24Z","message":"Starting committingClient service"}
{"level":"info","module":"proxy","connection":"snapshot","module":"abci-client","impl":"committingClient","time":"2022-05-21T19:55:24Z","message":"Starting committingClient service"}
{"level":"info","module":"proxy","connection":"mempool","module":"abci-client","impl":"committingClient","time":"2022-05-21T19:55:24Z","message":"Starting committingClient service"}
{"level":"info","module":"proxy","connection":"consensus","module":"abci-client","impl":"committingClient","time":"2022-05-21T19:55:24Z","message":"Starting committingClient service"}
{"level":"info","module":"events","impl":"EventBus","time":"2022-05-21T19:55:24Z","message":"Starting EventBus service"}
{"level":"info","module":"events","module":"pubsub","impl":"PubSub","time":"2022-05-21T19:55:24Z","message":"Starting PubSub service"}
{"level":"info","module":"txindex","impl":"IndexerService","time":"2022-05-21T19:55:24Z","message":"Starting IndexerService service"}
{"level":"info","module":"consensus","hash":"\u000b&m\ufffd\ufffd\ufffd\ufffddOZ\ufffd~o\ufffd\u000fR7K\ufffd\ufffd\ufffd\ufffd\u0019\ufffd[\ufffdL\ufffd(Nq\ufffd","height":10889,"protocol-version":0,"software-version":"0.29.0","time":"2022-05-21T19:55:24Z","message":"ABCI Handshake App Info"}
{"level":"info","module":"consensus","appHeight":10889,"stateHeight":10893,"storeHeight":10893,"time":"2022-05-21T19:55:24Z","message":"ABCI Replay Blocks"}
{"level":"info","module":"consensus","height":10890,"time":"2022-05-21T19:55:24Z","message":"Applying block"}
Loading makeSlogSender from @agoric/telemetry/src/otel-trace.js
Prometheus scrape endpoint: http://0.0.0.0:26661/metrics
Enabling OTLP Traces Exporter to http://localhost:4318/v1/traces
2022-05-21T19:55:25.408Z launch-chain: Launching SwingSet kernel
2022-05-21T19:55:25.427Z launch-chain: buildSwingset
SwingSet xs-worker tracing: {
  XSNAP_TEST_RECORD: '/state/agoriloadtest-8/xs_test_record_1653162921'
}
2022-05-21T19:55:27.491Z SwingSet: ls: v1: Logging sent error stack (Error#1203)
2022-05-21T19:55:27.493Z SwingSet: ls: v1: Error#1203: cannot grab 1295000000urun coins: 154181338urun is smaller than 1295000000urun: insufficient funds [agoric-labs/cosmos-sdk@v0.45.1-alpha.agoric.4/x/bank/keeper/send.go:187]
2022-05-21T19:55:27.496Z SwingSet: ls: v1: Error: cannot grab 1295000000urun coins: 154181338urun is smaller than 1295000000urun: insufficient funds [agoric-labs/cosmos-sdk@v0.45.1-alpha.agoric.4/x/bank/keeper/send.go:187]
 at apply ()
 at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:5941)
 at callOutbound (.../vats/src/bridge.js:63)
 at apply ()
 at apply ()
 at dispatchToHandler (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8729)
 at (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8362)
 at win (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:9072)
 at ()

2022-05-21T19:55:27.497Z SwingSet: ls: v1: Error#1203 ERROR_NOTE: Thrown from: (Error#1204) : 8986 . 0
2022-05-21T19:55:27.498Z SwingSet: ls: v1: Error#1203 ERROR_NOTE: Sent as error:liveSlots:v1#70602
2022-05-21T19:55:27.500Z SwingSet: ls: v1: Error#1204: Event: 8985.1
2022-05-21T19:55:27.501Z SwingSet: ls: v1: Error: Event: 8985.1
 at construct ()
 at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:5943)
 at trackTurns (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8346)
 at handle (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:9063)
 at deliver (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15803)
 at dispatchToUserspace (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:16113)
 at runWithoutMetering (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:16566)
 at ()

2022-05-21T19:55:28.100Z SwingSet: ls: v1: Logging sent error stack (Error#1205)
2022-05-21T19:55:28.101Z SwingSet: ls: v1: Error#1205: cannot grab 1050000000urun coins: 153981338urun is smaller than 1050000000urun: insufficient funds [agoric-labs/cosmos-sdk@v0.45.1-alpha.agoric.4/x/bank/keeper/send.go:187]
2022-05-21T19:55:28.102Z SwingSet: ls: v1: Error: cannot grab 1050000000urun coins: 153981338urun is smaller than 1050000000urun: insufficient funds [agoric-labs/cosmos-sdk@v0.45.1-alpha.agoric.4/x/bank/keeper/send.go:187]
 at apply ()
 at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:5941)
 at callOutbound (.../vats/src/bridge.js:63)
 at apply ()
 at apply ()
 at dispatchToHandler (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8729)
 at (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8362)
 at win (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:9072)
 at ()

2022-05-21T19:55:28.104Z SwingSet: ls: v1: Error#1205 ERROR_NOTE: Thrown from: (Error#1206) : 8998 . 0
2022-05-21T19:55:28.105Z SwingSet: ls: v1: Error#1205 ERROR_NOTE: Sent as error:liveSlots:v1#70603
2022-05-21T19:55:28.106Z SwingSet: ls: v1: Error#1206: Event: 8997.1
2022-05-21T19:55:28.107Z SwingSet: ls: v1: Error: Event: 8997.1
 at construct ()
 at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:5943)
 at trackTurns (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8346)
 at handle (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:9063)
 at deliver (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15803)
 at dispatchToUserspace (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:16113)
 at runWithoutMetering (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:16566)
 at ()

2022-05-21T19:55:30.859Z SwingSet: kernel: ##### KERNEL PANIC: unable to re-create vat v4 #####
portHandler threw (Error#1)
Error#1: unexpected end of file

  at Zlib.zlibOnError [as onerror] (zlib.js:187:17)

Cannot initialize Controller Error: unexpected end of file
{"level":"info","time":"2022-05-21T19:55:37Z","message":"starting ABCI with Tendermint"}
```

I suspect either the process is not exiting cleanly when signaled

Here are the debug files from the a working node, and two misbehaving nodes: https://drive.google.com/drive/folders/1mzAelIl13RqzFGVbPj5CouBsByngTAqW?usp=sharing

Revision: 922d4c0bd566d8e8a3918fc9c6696031e130637e

### PR DESCRIPTION
**Pull request by mhofman**
closes: #5419

## Description

Explicitely open file handles for snapStore files, which allows us to fsync gzipped snapshots before closing and renaming them.

### Motivation

From: https://github.com/Agoric/agoric-sdk/issues/5419#issuecomment-1139867492:
> That said I've parsed through the node.js code and read about Unix fs syscalls, and I now understand that an fclose of a file does not guarantee that the OS will flush the data to the actual device, and Node does not implicitly call fsync anywhere. I'm ready to bet that both LMDB and SQLite both perform an fsync. What probably happen is that the write of the snapshots by the snapStore succeeded from the kernel process point of view, but wasn't synced to disk, unlike the writes for the swingStore and streamStore, which were explicitly synced.

### Security Considerations

This should make our precious data safer.

### Documentation Considerations

None

### Testing Considerations

Besides passing tests to ensure there is no regression, I have no idea how to test this besides trying to reproduce the original issue.

### CODE REVIEW

**Comment by mhofman** [comment]
cc @arirubinstein

File: packages/swing-store/src/snapStore.js [hunk 1]
```diff
@@ -121,12 +127,39 @@ export function makeSnapStore(
...
+      autoClose: false,
+    });
+    try {
+      await Promise.all([
+        fsStreamReady(sourceStream),
+        fsStreamReady(destinationStream),
+      ]);
+      await pipe(sourceStream, f, destinationStream);
+      if (flush) {
+        await destination.sync();
```
Comment (kriskowal) [inline packages/swing-store/src/snapStore.js:157]: Today I learned about `FD.sync`.

**Review by kriskowal — APPROVED** [review]
