### PR TITLE
fix(amm): Prevent creation of constant product AMM with non-fungible central token

### LINKED ISSUE #4047: Prevent creation of constant product AMM with non-fungible central token
## What is the Problem Being Solved?

The AMM would be completely unusable with a non-fungible asset as the central (or secondary) token. The code already insists that secondary assets be fungible in addPool().  

## Description of the Design

Verify that the central token is fungible when starting up the contract.

## Security Considerations

None. An AMM created with a non-fungible central token would be completely unusable. It wouldn't prevent creation of another market with a better choice.

## Test Plan

show that NFTs can't be used.

### PR DESCRIPTION
**Pull request by b4d2**
closes: #4047

## Description

Adds validation of AssetKind at AMM creation to ensure Central is of `AssetKind.NAT`

### Security Considerations

n/a

### Testing Considerations

Includes test that demonstrates failure to create an AMM with a AssetKind.SET

### CODE REVIEW

File: packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js [hunk 1]
```diff
@@ -115,6 +116,13 @@ const start = async (zcf, privateArgs) => {
   } = /** @type { Terms & AMMTerms } */ (zcf.getTerms());
   assertIssuerKeywords(zcf, ['Central']);
   assert(centralBrand !== undefined, X`centralBrand must be present`);
+
+  const centralDisplayInfo = await E(centralBrand).getDisplayInfo();
+  assert(
+    centralDisplayInfo.assetKind === AssetKind.NAT,
```
Comment (dckc) [inline packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js]:
```suggestion
  assert.equal(centralDisplayInfo.assetKind, AssetKind.NAT,
```

File: packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js [hunk 2]
```diff
@@ -115,6 +116,13 @@ const start = async (zcf, privateArgs) => {
...
+    X`Central must be of kind AssetKind.NAT`,
```
Comment (dckc) [inline packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js]:
```suggestion
    X`Central must be of kind ${q(AssetKind.NAT)}, not ${q(centralDisplayInfo.assetKind)}`,
```

File: packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js [hunk 3]
```diff
@@ -115,6 +116,13 @@ const start = async (zcf, privateArgs) => {
   } = /** @type { Terms & AMMTerms } */ (zcf.getTerms());
   assertIssuerKeywords(zcf, ['Central']);
   assert(centralBrand !== undefined, X`centralBrand must be present`);
+
+  const centralDisplayInfo = await E(centralBrand).getDisplayInfo();
```
Comment (dckc) [inline packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js]: This `await` adds a round-trip to contract startup. That could be avoided by combining it using `Promise.all` with `const paramManager = await makeParamManager(` below, at the cost of some code clarity.

@Chris-Hibbert I'm curious what you think.

Comment (dckc) [inline packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js]: There's a risk that `centralBrand` will tell us it's fungible here but then behave as non-fungible later. I suppose behaving as non-fungible later is already protected against, and the point of this check is to get a clear and relevant diagnostic rather than "array found where bigint expected" or some such later. So... never mind.

**Review by dckc — COMMENTED** [review]
I suggest using `assert.equal` and including both sides in the failure diagnostic.

I'd like to hear from @Chris-Hibbert on clear code that costs an `await` round trip vs. a `Promise.all` optimization.

File: packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js [hunk 4]
```diff
@@ -7,6 +7,7 @@ import { AssetKind, makeIssuerKit } from '@agoric/ertp';
 import { CONTRACT_ELECTORATE, handleParamGovernance } from '@agoric/governance';
 
 import { assertIssuerKeywords } from '@agoric/zoe/src/contractSupport/index.js';
+import { E } from '@agoric/eventual-send';
```
Comment (dckc) [inline packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js]: The new norm since #3833 is:

```suggestion
import { E } from '@agoric/far';
```

File: packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js (hunk 3 above)
Comment (Chris-Hibbert) [reply packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js]: My usual rule of thumb is to not worry about performance issues (particularly one-time start up costs) until measurement shows them to be a problem, but I think you've been actually measuring start up times, so anyway.

I don't have a problem with using `Promise.all()` to aggregate awaits even when they're working on different tasks. This test doesn't have to be the first thing done. It's entire purpose would be to prevent accidentally breaking the AMM, so it should never fail if the AMM would have been useful.

Comment (Chris-Hibbert) [reply packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js]: If it says it uses AssetKind.NAT`, then it's giving us permission to use the corresponding AmountMath. If it misbehaves after that, it's a broken issuer.

File: packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js [hunk 5]
```diff
@@ -115,6 +116,12 @@ const start = async (zcf, privateArgs) => {
   } = /** @type { Terms & AMMTerms } */ (zcf.getTerms());
   assertIssuerKeywords(zcf, ['Central']);
   assert(centralBrand !== undefined, X`centralBrand must be present`);
+
+  const centralDisplayInfo = await E(centralBrand).getDisplayInfo();
+  assert.equal(centralDisplayInfo.assetKind, AssetKind.NAT,
+    X`Central must be of kind ${q(AssetKind.NAT)}, not ${q(centralDisplayInfo.assetKind)}`,
```
Comment (Chris-Hibbert) [inline packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js]: It looks like the declaration of `q` and `X` is missing:

```
const { quote: q, details: X } = assert;
```

**Review by Chris-Hibbert — APPROVED** [review]

File: packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js (hunk 3 above)
Comment (dckc) [reply packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js]: Right... it's just that I'm new at evaluating the risks around broken issuers, so I was thinking out loud.

**Comment by dckc** [comment]
@Chris-Hibbert note that @b4d2 doesn't have merge rights. When this is ready, I guess it's up to you to merge it. (Let me know if you would rather I do it.)

@b4d2 we're used to having the author merges their own work, so this may have fallen between the cracks.

**Comment by Chris-Hibbert** [comment]
@dckc   do you have time to fix the conventional commit issues and submit this?  I'm happy with the current state.

**Comment by dckc** [comment]
squashing addressed the conventional-commits stuff.

(they don't block a merge in any case)

**Comment by dckc** [comment]
Thanks for the contribution, @b4d2!

**Comment by Chris-Hibbert** [comment]
> (they don't block a merge in any case)

Ah!  I thought they did.  Thanks!
