### PR TITLE
collectionManager: refcount remotables in keyShape/valueShape

### LINKED ISSUE #7321: collections permit Presences/vrefs in keyShape/valueShape, but doesn't refcount them
## Describe the bug

Our virtual/durable collections (i.e. `makeScalarBigMapStore`) accept optional `keyShape` and `valueShape` patterns, to restrict the kinds of keys and values that can be stored in each one. The patterns are defined with a constraint language, with terms both both categories of data (`M.number()` accepts any Number), and specific values (using `4` in a pattern will only accept the value `4`, no other number). There is an `M.remotable()`, which matches things like (imported) Presences and exported objects created with `Far`, or virtual/durable Representatives. And if you include a specific Remotable in the pattern, then (apparently) that will only match against the specific instance.

```js
import { matches, M } from '@agoric/store';
const thing1 = Far('thing', {});
const thing2 = Far('thing', {});
const pattern1 = M.remotable();
const pattern2 = thing1;
matches(thing1, pattern1); // true
matches(thing2, pattern1); // true
matches(thing1, thing1); // true
matches(thing1, thing2); // false
```

A specific Remotable could be used in a `keyShape` or `valueShape` too:

```js
const type1 = [thing1, M.number()];
const type2 = [thing2, M.string()];
const valueShape = M.or(type1, type2);
const store = makeScalarBigMapStore('map', { valueShape });
```

However, using a specific Remotable like that is going to be problematic. Both `keyShape` and `valueShape` are serialized and stored in a special per-collection `vatstore` key named `|schemata`, so that later vat incarnations (or later reanimations of the collection within the same vat incarnation) will be subject to the constraints as well. But if the shape had Remotables (Presences, Far()-generated ephemerals, or virtual/durable Representatives), the serialized form will have a vref, and we don't perform refcounting on those vrefs like we do for virtual-object `state` or collection entries.

Attempting to unserialize the schemata later might or might not find the corresponding object to be present in slotToVal. If the object was ephemeral, and it had been garbage-collected since the last usage, the `unserialize` will fail.

This was less obvious before, because the schemata was held in RAM for the lifetime of the incarnation, so it would only show up in a post-upgrade access to the Remotable-in-valueShape-using collection. We didn't really acknowlege the high cardinality of collections at first, and have places where we hold per-collection data in RAM when it really ought to live primarily in the DB. One consequence of this is a syscall sensitivity to GC of collections, which is being addressed in #6360. That will cause more frequent unserialization of `|schemata`, making this problem become visible within even the current vat incarnation.

## The Fix

`collectionManager.js` should assert that `serializedSchema.slots.length === 0` while creating the collection the first time.

As this means `serializedSchema.body` contains the complete description of the schema, I'm tempted to go further and only record `.body`, rather than our current `JSON.stringify(serializedSchema)` (including both `.body` and `.slots`). Then, on restore, do `unserialize({ body: vatstoreGet(`..|schemata`), slots: [] })`. That would make the saved data slightly smaller and simpler, but also completely excludes the possibility of unserializing vrefs in this context. Doing this would cause us backwards-compatibiltiy problems if we ever decided to find a way to lift this restriction, though.

### PR DESCRIPTION
**Pull request by warner**
collectionManager: refcount remotables in keyShape/valueShape

The collection schema (keyShape/valueShape) can refer to specific
Remotable instances (e.g. Presence, or a durable object), rather than
defining a constraint to be a whole category of objects. The
collection schema metadata is thus a form of write-once state storage,
like a tiny virtual object.

Previously, defineKind failed to increment the refcount on the
objects' vrefs, so when the collection falls out of memory, the object
might be deleted, and then we would be unable to revive the constraint
when loading the schema back in later.

This changes the code to increment the refcounts of the vrefs in
keyShape and valueShape when the collection is created, and decrement
them when the collection is deleted. It handles ephemeral Remotables,
as well as virtual/durable object Representatives. For durable
collections, it also enforces the same `isDurable` check on the schema
as it would on keys and values of the collection itself, so you cannot
use a `Far()` or a merely-virtual object in the valueShape of a
durable collection.

closes #7321

### CODE REVIEW

**Comment by warner** [comment]
Two of the new tests are disabled because I haven't been able to figure out how to avoid the "unhandled rejection" error from flunking the test. @gibson042 I could probably use your help figuring out that one.

**Comment by warner** [comment]
hrm, something is failing in a packages/vats upgrade test, feels like the refcounts are causing something to get deleted by mistake, will investigate tomorrow

File: packages/swingset-liveslots/src/collectionManager.js [hunk 1]
```diff
@@ -64,7 +64,7 @@ function prefixc(collectionID, dbEntryKey) {
 /*
  * Build a cache that holds the schema for each collection.
  *
- * The cache maps collectionID to { keyShape, valueShape, label,
+ * The cache maps colectionID to { keyShape, valueShape, label,
```
Comment (FUDCo) [inline packages/swingset-liveslots/src/collectionManager.js]: Typo: "colectionID".  Didn't we already see this?  And weird how it got made when the correct from was there previously.  Any way, typo.

**Review by FUDCo — APPROVED** [review]
Looks good.  Possibly also a new contender for largest ratio of test size to code change size .

File: packages/swingset-liveslots/src/collectionManager.js (hunk 1 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js]: huh, yeah, something went wrong with a rebase. I'll fix it.
