### PR TITLE
fix: return funds from liquidation via a seat payout

### LINKED ISSUE #3497: Treasury returns funds to borrower in offerResult
## Describe the bug

Treasury (`vault.js`) returns leftover RUN to the borrower after the loan is closed in a promise in the offerResult. Any RUN that needs to be returned should just  be in the payout.

## Expected behavior

test `price drop` in `test-stablecoin.js` [shows the issue](https://github.com/Agoric/agoric-sdk/blob/006d030974a4ce6475d2fe9f3b4406c66702d442/packages/treasury/test/test-stablecoin.js#L381). `liquidationPayout` shouldn't be necessary. Those funds should be included in the seat payout.

## Additional context

#3495

We should use a local `emptySeatKit` in `closeHook()` rather than using the shared `vaultSeat` for transferring the runDebt.

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
Reduce overuse of vaultSeat for transferring RUN

fixes: #3497

### CODE REVIEW

File: packages/treasury/src/vault.js [hunk 1]
```diff
@@ -167,20 +169,24 @@ export function makeVaultKit(
...
+    runMint.burnLosses({ RUN: runDebt }, burnSeat);
     seat.exit();
+    burnSeat.exit();
     active = false;
     updateUiState();
 
-    runMint.burnLosses({ RUN: runDebt }, vaultSeat);
     runDebt = AmountMath.makeEmpty(runBrand);
     assertVaultHoldsNoRun();
     vaultSeat.exit();
```
Comment (dtribble) [inline packages/treasury/src/vault.js:213]: This should have been exited when we liquidated the vault. Otherwise there's a race where more collateral could be added, for example.

**Review by dtribble — CHANGES_REQUESTED** [review]
There's a race in which more collateral could be added to the `vaultSeat` while liquidating. Because the `vaultSeat` is no longer used after that, the collateral would be lost. I think that the liqSeat should be the vaultSeat but this needs to be taken care of in any case.

File: packages/treasury/src/vault.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/treasury/src/vault.js:213]: We now exit when liquidation starts. It's also needed here in close.

**Review by Chris-Hibbert — COMMENTED** [review]
> There's a race in which more collateral could be added to the vaultSeat while liquidating. Because the vaultSeat is no longer used after that, the collateral would be lost. I think that the liqSeat should be the vaultSeat but this needs to be taken care of in any case.


Handing out the vaultSeat would be a mistake. We now disable the vault when liquidation starts.

File: packages/treasury/src/vault.js [hunk 2]
```diff
@@ -130,19 +143,31 @@ export function makeVaultKit(
...
+        break;
+      default:
+        throw Error(`unreachable vaultState: ${vaultState}`);
     }
   }
 
   function liquidated(newDebt) {
     runDebt = newDebt;
-    active = false;
+    vaultState = VaultState.CLOSED;
```
Comment (dtribble) [inline packages/treasury/src/vault.js:168]: for a future cleanup, perhaps a state argument should just be provided to `updateUiState` to coming the notification and update?

**Review by dtribble — APPROVED** [review]
