### PR TITLE
fix(telemetry): some otel housekeeping

### LINKED ISSUE #6469: Slog Error on 2c812d22161cd297587979b262eab6e2cc76e23d
Appears on 2c812d22161cd297587979b262eab6e2cc76e23d

```
Error tracing slog: {
  type: 'cosmic-swingset-begin-block',
  blockHeight: 1009,
  blockTime: 1666127156,
  queueAllowed: { inbound: 1000, inbound_mempool: 500 },
  time: 1666127162.345344,
  monotime: 239.6181161830006
} (Error#19)
Error#19: Check failed

  at Object.pop (packages/telemetry/src/slog-to-otel.js:348:11)
  at slogSender (packages/telemetry/src/slog-to-otel.js:812:17)
  at wrappedSlogSender (packages/telemetry/src/slog-to-otel.js:925:7)
  at slogSender (packages/telemetry/src/make-slog-sender.js:157:11)
  at process.<anonymous> (packages/telemetry/src/slog-sender-pipe-entrypoint.js:100:13)
  at process.emit (node:events:513:28)

WARNING: slog sender error (Error#19)
```

https://drive.google.com/drive/folders/1aZkPpiT-FM3RRR9DEbj4NzQjQ3zrrnd1?usp=sharing

### LINKED ISSUE #6513: otel collector no longer likes our traces
## Describe the bug

Our tracing exporter no longer works out of the box with the latest version of otelcol-contrib.  It does work with otelcol-contrib on version 0.50.0 however.

Testing otelcol-config:
```
receivers:
  otlp:
    protocols:
      http:
        endpoint:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: 
        - otlp
      exporters: 
        - logging
```

Config:
```
[Unit]
Description=Agoric Cosmos daemon
After=network-online.target

[Service]
User=ari
ExecStart=/home/ari/go/bin/agd start --log_level=warn
Restart=on-failure
RestartSec=3
LimitNOFILE=65536
Environment=OTEL_EXPORTER_PROMETHEUS_PORT=26661
Environment=SLOGFILE=/home/ari/.agoric/data/chain.slog
Environment=SLOGSENDER_AGENT=process
Environment=SLOGSENDER=@agoric/telemetry/src/otel-trace.js
Environment=OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318/v1/traces
[Install]
WantedBy=multi-user.target
```

Expected behavior: 
- Spans will print to console when using https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.63.0
(Spans do print when using https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.50.0)

Observed behavior:
- Spans do not print at all or make it past ingest

### PR DESCRIPTION
**Pull request by mhofman**
closes: #6469 
closes: #6513

refs: #6506 #6522

## Description

Rebases #6506 #6522 onto master. Those PRs were never merged into pismo and nevery cherry-picked in master. Still relevant

### 6506 Description

This PR fixes some otel converter processing issues which prevented it from making new spans once some edge cases were encountered. It also include more robust logic to hard reset the expected state of the otel tracing at block boundaries, to limit the blast radius of similar issues in the future.

This fixes an issue discovered when trying to get otel telemetry from the mainnet archival node, the previously reported https://github.com/Agoric/agoric-sdk/issues/6469, and a DB transaction issue discovered locally when working on other telemetry improvements.

### 6522 Description

The protobufs changed some time ago in the open telemetry collector, and newer versions are no longer compatible with the version of the JS SDK we're using.

This updates the OpenTelemetry JS SDK and deals with the fallout of the API changes.
In particular:
- Histogram metrics now need to have their custom aggregation configured explicitly when creating the metricsProvider. This causes quite a bit of change in the layering between kernel-stats and the telemetry package.
- Counters now require the observable part to be initialized separately.
- The exporter now needs to be added explicitly.

### Security Considerations

Always a supply chain risk when updating versions, but all the updated dependencies come reputable sources.

### Scaling Considerations

None

### Testing Considerations

Good question? @michaelfig I'm still not sure how to test this, especially the kernel-stats changes.

@arirubinstein I guess we'll get to test this in a testnet soon, right?

### CODE REVIEW

**Review by dckc — APPROVED** [review]
This is not an "I'm happy to maintain the result of this PR" approval. In particular, I don't see any test coverage at all.

But I don't see any problems and I gather it's somewhat urgent.

File: packages/cosmic-swingset/src/kernel-stats.js [hunk 1]
```diff
@@ -276,47 +316,38 @@ export function exportKernelStats({
...
+    const counter = metricMeter.createObservableUpDownCounter(name, options);
+    counter.addCallback(observableResult => {
+      observableResult.observe(getKernelStats()[key], attributes);
+    });
+    kernelStatsMetrics.set(key, counter);
   });
 
   if (inboundQueueMetrics) {
     for (const name of ['length', 'add', 'remove']) {
       const key = `cosmic_swingset_inbound_queue_${name}`;
```
Comment (michaelfig) [inline packages/cosmic-swingset/src/kernel-stats.js:340]:
```suggestion
      const key = `cosmic_swingset_inbound_queue_${name}`;
      expectedKernelStats.add(key);
```

**Review by michaelfig — APPROVED** [review]
I tested with `cd cosmic-swingset && make scenario2-setup scenario2-run-chain` and `curl http://localhost:9464/metrics`

Just one minor change, otherwise LGTM!
