### PR TITLE
8981 upgrade vaults

### LINKED ISSUE #7873: vaultFactory terms: auctioneerPublicFacet or auctioneer instance?
## What is the Problem Being Solved?

The vaultFactory's terms include `auctioneerPublicFacet`; a party who wants to audit/verify the auctioneer is likely to have the instance (for example from agoricNames.instance). This puts the burden on such parties to call `E(zoe).getPublicFacet(instance)` in order to verify.

## Description of the Design

Perhaps the vaultFactory should take the instance and do the call to `E(zoe).getPublicFacet(instance)`

### LINKED ISSUE #7954: make Vault Factory configurable with new Auctioneer contract
## What is the Problem Being Solved?

`auctioneer` returns non-durable facets so we’ll need to give `vaultFactory` the new publicFacet after upgrade. That means we have to upgrade vaultFactory too, giving it a way to receive an auctioneer other than in its terms (because terms are only for initial start of a contract).

## Description of the Design

The auctioneer is an implementation detail of the vaultFactory contract. Therefore it can go in `privateArgs`.

Move it from terms to privateArgs, so that it's set upon each start of the contract.

## Test Plan 
```[tasklist]
### Blocked by
- [ ] https://github.com/Agoric/agoric-sdk/issues/8079
```

### LINKED ISSUE #8079: vaultFactory contract not upgradable
## Describe the bug

The vaultFactory contract in master fails upgrading the vaultFactory contract deployed to mainnet (simulated in docker upgrade-test scripts). There are multiple hurdles. (TO INCLUDE)

## To Reproduce
1. check out 555b517 (from #8049)
3. in `packages/deployment/upgrade-tests`: `make build run`
2. bundle the vault factory outside the container: `bundle-source --cache-json /tmp packages/inter-protocol/src/vaultFactory/vaultFactory.js vaultFactory` and then `docker cp /tmp/bundle-vaultFactory.json $CONTAINERID:/tmp` where `$CONTAINERID` is from `docker ps`.
4. inside the container, use upgrade scripts from outside the container: `mv upgrade-test-scripts xx-scripts; ln -s /workspace/upgrade-test-scripts`
5. mint some IST to cover the cost of installing the bundles on chain: `. ./upgrade-test-scripts/agoric-upgrade-11/mint-ist.sh`
6. run the upgrade script from within docker at /usr/src/agoric-sdk: `./upgrade-test-scripts/agoric-upgrade-11/auctioneer-upgrade-driver.sh`
7. see various errors (details in comments below), though the kernel reports the contract vat _is_ upgraded and the core eval script _does_ report successful completion.

## Expected behavior
vault factory upgrade does not produce errors; contract works after upgrade

## Platform Environment
 - _what OS are you using?_ linux, macos. _what version of Node.js?_ whatever's in the `upgrade-test` docker stuff
 - _is there anything special/unusual about your platform?_ `upgrade-test` docker stuff
 - what version of the Agoric-SDK are you using? 555b517

## Additional context
work on upgrading vault factory to connect to a different auctioneer: #8049

## Screenshots
_We have a more complete log file internally._

### LINKED ISSUE #8726: vat-vaultFactory may believe governance is broken when vat-auctioneer is upgraded
As part of https://github.com/Agoric/agoric-sdk/pull/8499#issuecomment-1842457715 (look for `v45-auctioneer-v48-vaultfactory`), we observe that v48-vaultFactory follows (is a subscriber to) a governance-parameter notifier that lives in v45-auctioneer. The v45-auctioneer's `@agoric/governance` code is not durable, so when v45-auctioneer is upgraded, that notifier will be deleted/abandoned, and v48-vaultFactory may believe that governance has broken.

The subscriber code is probably set up here: https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/inter-protocol/src/vaultFactory/liquidation.js#L211 . It uses `observeIteration`, so if v45-auctioneer's governance objects were durable, this would be safe against v45-auctioneer being upgraded. And it looks like [this is called](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/inter-protocol/src/vaultFactory/vaultDirector.js#L516) from a `start` method that will be called on each upgrade of v48-vaultFactory, so it should be safe against v48-vaultFactory upgrades. 

To address this, I think the `subscribeEach` needs some sort of error-handling case, which can notice that the promise was disconnected (and perhaps check that the incarnation number is new), and react by requesting a new subscription from the (hopefully durable) `auctioneerPublicFacet`.

(#8079 might overlap with this, but is mainly about v48-vaultFactory not yet being upgradable, rather than what additional safeguards it needs against other vats being upgraded)

The tasks are:

* change `watchForGovernanceChange` in v48-vaultFactory to tolerate upgrades of the upstream v45-auctioneer
* demonstrate (via a3p?) upgrading v45-auctioneer, then making a governance change, then observing that v48-vaultFactory correctly notices the governance change

We must deploy the v48-vaultFactory fix before we can safely upgrade v45-auctioneer.

### LINKED ISSUE #8728: test that v48-vaultFactory re-subscribes to timer when v48-vaultFactory is upgraded
As part of https://github.com/Agoric/agoric-sdk/pull/8499#issuecomment-1842457715 (look for `v5-timer-v23-feedistributor-v48-vaultfactory`), we're investigating how v48-vaultFactory will react when it is upgraded, in particular whether it will re-follow the timer service notifiers it uses.

v48-vaultFactory [has code](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/inter-protocol/src/vaultFactory/vaultManager.js#L360-L368) which talks to the timer service and creates a notifier during `helper.start()`. The timer service provides durable notifiers, and this subscriber code correctly uses `observeNotifier` to react to vat-timer being upgraded (and the individual promises being disconnected). The remaining important property is that the subscribing code (in v48-vaultFactory) correctly handles itself being upgraded, by re-subscribing or restarting the timer notifier.

It looks like this is designed to happen correctly, by virtue of `helper.start` being [called by `provideAndStartVaultManagerKits`](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/inter-protocol/src/vaultFactory/vaultManager.js#L1213-L1215), in a loop which suggests that all existing kits will be restarted when v48-vaultFactory is upgraded. This is probably called from [`prepare`](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/inter-protocol/src/vaultFactory/vaultFactory.js#L70), which indicates the contract is designed for upgrade.

(I suspect this is all working, but if not, it would be a blocker to upgrading v5-timer. Someone who knows what is tested and what is not may be able to trivially close this ticket)

The task is to test this tolerance of upgrading v5-timer, probably through a3p:
* set up a vault factory, which will establish the timer loop
* upgrade the vault factory
* assert that the vault factory has re-subscribed to the timer service
  * perhaps by allowing time to advance and then observing the vault factory reacting to the passage of time correctly

### LINKED ISSUE #8735: inform VaultFactory about new Auctioneer
## What is the Problem Being Solved?

The Auction contract is not upgradeable; the plan has been to replace it rather than upgrading it.
The VaultFactory learns about the Auction in its `terms`, and has no mechanism to be informed about a replacement.

## Description of the Design

Figure out how to use upgrade vatParameters, or privateArgs, or add an creatorFacet or governed API to the VaultFactory in order to inform it of a new Auction it should use.

## Security Considerations

ensure no closely held authority is revealed.

## Scaling Considerations

N/A

## Test Plan

test in A3P.

## Upgrade Considerations

make it possible to upgrade vaultFactory and Auction.

### LINKED ISSUE #8740: Plan for replacing priceFeeds, redirecting oracles
## What is the Problem Being Solved?

#8400 explains that priceFeed vats are holding onto quote payments via recoverySets,  creating an uncollectible cycle. In order to stop adding to the growing amount of garbage, we need to make the Auction and VaultFactory rely on a different priceFeed. Once the clients are pointed to a different source, we can decide when to kill those vats to cause the garbage to be freed. 

## Description of the Design

In order to switch to new priceFeeds, we need a plan that describes what it takes to redirect the oracles so we can replace the priceFeeds in the priceAuthorityRegistry. 

Replacing the priceFeeds should be simple: the priceAuthorityRegistry has `registerPriceAuthority(pa, brandIn, brandOut, force)`. If `force = true`, the old one is dropped.

## Security Considerations

More robustness, rather than a security issue.

## Scaling Considerations

Garbage is accumulating.

## Test Plan

Test in a3p to ensure the new fluxAggregator is getting price data.

## Upgrade Considerations

Do we need new code anywhere in order to redirect oracles?

### LINKED ISSUE #8789: test that smartWallet offer notifications survive Zoe upgrade
## What is the Problem Being Solved?

#8773 is an upgrade to `walletFactory` that addresses #8286. During development we tested ([manually and in agoric-3-proposals](https://github.com/Agoric/agoric-3-proposals/pull/34)) that offers created before the upgrade would continue to be tracked even if Zoe was upgraded. Unfortunately, those tests no longer run once the code is upgraded on chain, so we have to add new tests in `a3p-integration`. In order to test it, we'll need a [hook to create an outstanding offer before performing the upgrade](https://github.com/Agoric/agoric-3-proposals/issues/74).

## Description of the Design

 * Create an offer (e.g. 'agops inter bid by-price --price 1 --give 1.0IST --from $GOV1ADDR --keyring-backend test --offer-id perpetual-open-bid-12')
 * upgrade walletFactory
 * upgrade Zoe
 * Verify that the offer exists and can be interacted with. ('agops inter bid cancel --id perpetual-open-bid-12 --from $GOV1ADDR')

## Security Considerations

None

## Scaling Considerations

None

## Test Plan

As above

## Upgrade Considerations

smart wallets should survive Zoe upgrade.

### LINKED ISSUE #8868: prepare updates for Upgrade 15
## What is the Problem Being Solved?

A plan for the userland updates for Upgrade 15

## Steps (in order)

1.  **Zoe**
  * [x] Make a branch with #8682, #8697, #8497, #8498
  * [x] write the core eval #8915
  * [x] test #8682 in A3P. [#9010)
  * [x] test #8807 in A3P [#8911]
2.  **Price Feeds**. (see #8740)
  * [x] Add #8497 to branch
  * [x] replace #8498 with something that doesn't clean incrementally (#9013)
  * [x] add upgrading price feeds to core eval, see #8740.  (see #9044)
  * [x] test price feeds in A3P
3. **Auction**
  * [x] add #8691, #8438, #8301 to the branch
  * [x] add starting a new auction to the core eval. (#8918)
4.  **Vaults**
  * [x] add #8696, #8049, #8757  to the branch
  * [x] add upgrading Vaults to the core eval
  * [x] verify that upgrade succeeds (#8079)
  * [x] test #8788, #8789, #8293 in A3P

We decided (2/12) to upgrade from master rather than a branch, so it's not necessary to make branches. We still need the coreEvals.

### LINKED ISSUE #8918: Write a coreEval to add a new Auction
## What is the Problem Being Solved?

In **Upgrade-15**, we plan to add a new Auction, and upgrade vaults to rely on it. In order to test this, we need a core-eval in a3p-integration. 

See #8740 for the overall plan for upgrading price feeds, of which this is a part.

## Description of the Design

The new auction should subscribe to the recently updated priceFeeds as the older ones will be discontinued. The existing Auction should be de-scheduled, but not until vaults upgrade and use the new Auction.

## Security Considerations

None.

## Scaling Considerations

It's all in service of resolving some sustainability challenges caused by the old price feeds

## Test Plan

Verify in a3p-integration that everything is happy afterwards.

## Upgrade Considerations

Yes.

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #8049
closes: #8740
closes: #8868
closes: #8918
closes: #8981
closes: #8079
refs: #8400
closes: #8735
closes: #7873
closes: #8726
closes: #7954
closes: #8757
closes: #8728 
closes: #8789

## Description

Upgrade **VaultFactory** in A3P, relying on the new PriceFeeds, and auctions. The actual upgrade waits for the priceFeeds to start supplying before doing the upgrade, so there won't be any gap in priceUpdates.

When the upgrade is finished, we also update the auctioneerKit and Auction instance in the bootstrap environment.

This PR demonstrates that VaultFactory can be upgraded even though governance is not persistent (#8123).

### Security Considerations

N/A

### Scaling Considerations

This is largely in service of #8400, which reports that priceFeed vats are accumulating garbage. This PR switches to new priceFeeds, which won't have that problem, though cleaning up the existing vats is a task for the future.

### Documentation Considerations

No changes to user-visible behavior.

### Testing Considerations

A3P tests that verify that vaultFactory has been upgraded, that a new Auctioneer is running and is receiving prices. Verify that when prices drop, assets are sold via the auction, the bidder gets the proceeds, and the vaults are liquidated or reconstituted appropriately.

### Upgrade Considerations

Upgrade all the vats!

### CODE REVIEW

File: a3p-integration/proposals/a:upgrade-next/agd-tools.js [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+  GOV3ADDR,
+  newOfferId,
+  CHAINID,
+} from '@agoric/synthetic-chain';
+
+const ORACLE_ADDRESSES = [GOV1ADDR, GOV2ADDR, GOV3ADDR];
+
+export const BID_OFFER_ID = 'bid-vaultUpgrade-test3';
+
+const agdQuery = path =>
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/agd-tools.js]: easy to confuse with existing `agd.query`. it's not exported so low risk but consider renaming. e.g. `queryVstorage`

File: a3p-integration/proposals/a:upgrade-next/agd-tools.js [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+  agd.query('vstorage', 'data', '--output', 'json', path);
+
+const getQuoteBody = async path => {
+  const queryout = await agdQuery(path);
+
+  const body = JSON.parse(JSON.parse(queryout.value).values[0]);
+  return JSON.parse(body.body.substring(1));
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/agd-tools.js]: don't we have real SmallCaps decoding now? consider importing from `@endo/marshal`

File: a3p-integration/proposals/a:upgrade-next/test.sh [hunk 3]
```diff
@@ -3,6 +3,7 @@
 # Place here any test that should be executed using the executed proposal.
 # The effects of this step are not persisted in further proposal layers.
 
-yarn ava post.test.js
 GLOBIGNORE=post.test.js
+
+yarn ava post.test.js
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/test.sh]: why move? I think this is less clear

File: a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+  BID_OFFER_ID,
+  checkForOracle,
+  createBid,
+  getLiveOffers,
+  getPriceQuote,
+  pushPrices,
+} from './agd-tools.js';
+import { getDetailsMatchingVats } from './vatDetails.js';
+
+test.serial('check all priceFeed vats updated', async t => {
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js]: Ava `serial` happens to run sequentially but is isn't guaranteed too. I think we should try to avoid using it whenever possible.

Consider putting the sequence into one `test` with `t.log` to provide the progress messages. And consider helper like `pushPrices(t)` to abstract the logic so it's easy to follow what the test is doing and checking.

File: a3p-integration/proposals/a:upgrade-next/vatDetails.js [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+      return dynamicIDs.filter(vatID =>
+        lookupVat(vatID).options().name.includes(vatName),
+      );
+    },
+    lookupVat,
+  });
+};
+
+/** @param {string} vatName */
+export const getDetailsMatchingVats = async vatName => {
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/vatDetails.js]: please comment on what we need `@agoric/synthetic-chain` before this module can be replaced by one of its exports. consider linking to an issue or PR once can reference to see whether the work is done

Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/vatDetails.js]: please comment on what we need `@agoric/synthetic-chain` before this module can be replaced by one of its exports. consider linking to an issue or PR once can reference to see whether the work is done

File: a3p-integration/scripts/generate-a3p-submissions.sh [hunk 6]
```diff
@@ -1,15 +1,19 @@
 #!/bin/bash
 set -ueo pipefail
 
-SCRIPT_DIR=$( cd ${0%/*} && pwd -P )
+## cd prints its target, so without the redirect, we get two copies
+#SCRIPT_DIR=$( cd ${0%/*} > /dev/null && pwd -P )
+SCRIPT_DIR=$( cd ${0%/*} > /dev/null && pwd -P )
```
Comment (turadg) [inline a3p-integration/scripts/generate-a3p-submissions.sh:5]: isn't this the same as what you commented out? please revert

File: a3p-integration/scripts/generate-a3p-submissions.sh [hunk 7]
```diff
@@ -1,15 +1,19 @@
...
 
 IFS=$'\n'
 
 for proposal in ./proposals/?:*; do
   cd $proposal
   while read -r line; do
     IFS=' ' parts=( $line )
+    echo "  about to GENERATE " $proposal
     $SCRIPT_DIR/generate-a3p-submission.sh $proposal ${parts[@]}
+    echo "  finished GENERATING" $proposal
```
Comment (turadg) [inline a3p-integration/scripts/generate-a3p-submissions.sh]: these seems more like the concern of the called script. consider putting the log output there

File: packages/builders/scripts/vats/upgradeVaults.js [hunk 8]
```diff
@@ -0,0 +1,23 @@
+import { makeHelpers } from '@agoric/deploy-script-support';
+
+/** @type {import('@agoric/deploy-script-support/src/externalTypes.js').ProposalBuilder} */
+export const defaultProposalBuilder = async ({ publishRef, install }) =>
+  harden({
+    sourceSpec: '@agoric/inter-protocol/src/proposals/upgrade-vaults.js',
```
Comment (turadg) [inline packages/builders/scripts/vats/upgradeVaults.js:6]: please make this filename match the casing, `upgrade-vaults`.

File: packages/governance/src/contractGovernance/paramManager.js [hunk 9]
```diff
@@ -224,10 +224,10 @@ const makeParamManagerBuilder = (publisherKit, zoe) => {
     if (!zoe) {
       throw Fail`zoe must be provided for governed Invitations ${zoe}`;
     }
-    const { instance, installation } = await E(zoe).getInvitationDetails(i);
 
-    // @ts-expect-error typedefs say they're guaranteed truthy but just to be safe
-    assert(instance && installation, 'must be an invitation');
+    // local check on isLive() gives better report than .getInvitationDetails()
```
Comment (turadg) [inline packages/governance/src/contractGovernance/paramManager.js:228]: thx for the comment

File: packages/inter-protocol/src/proposals/add-auction.js [hunk 10]
```diff
@@ -0,0 +1,177 @@
...
+  const paramValues = await E(legacyKit.publicFacet).getGovernedParams();
+  const params = harden({
+    StartFrequency: paramValues.StartFrequency.value,
+    ClockStep: paramValues.ClockStep.value,
+    StartingRate: paramValues.StartingRate.value,
+    LowestRate: paramValues.LowestRate.value,
+    DiscountStep: paramValues.DiscountStep.value,
+    AuctionStartDelay: paramValues.AuctionStartDelay.value,
+    PriceLockPeriod: paramValues.PriceLockPeriod.value,
+  });
```
Comment (turadg) [inline packages/inter-protocol/src/proposals/add-auction.js]: are the names important to see here? consider,
```suggestion
  const params = objectMap(paramValues p => p.value);
```

which could easily be inlined to avoid another binding in the scope

File: packages/inter-protocol/src/proposals/add-auction.js [hunk 11]
```diff
@@ -0,0 +1,177 @@
...
+        issuerKeywordRecord: { Bid: stableIssuer },
+        storageNode,
+        marshaller,
+        label: 'auctioneer',
+      },
+    }),
+  );
+
+  /** @type {GovernorStartedInstallationKit<typeof auctionInstallation>} */
+  const governorStartResult = await E(zoe).startInstance(
```
Comment (turadg) [inline packages/inter-protocol/src/proposals/add-auction.js]: any reason why not `startGovernedInstance`?

File: packages/inter-protocol/src/proposals/upgrade-vaults.js [hunk 12]
```diff
@@ -0,0 +1,202 @@
+import { E } from '@endo/far';
+import { makeNotifierFromAsyncIterable } from '@agoric/notifier';
+import { AmountMath } from '@agoric/ertp/src/index.js';
+import { makeTracer } from '@agoric/internal/src/index.js';
+
+const trace = makeTracer('upgrade Vaults proposal');
+
+// stand-in for Promise.any() which isn't available at this point.
+const any = promises =>
```
Comment (turadg) [inline packages/inter-protocol/src/proposals/upgrade-vaults.js:9]: I'm assuming this is correct

File: packages/inter-protocol/src/proposals/upgrade-vaults.js [hunk 13]
```diff
@@ -0,0 +1,202 @@
...
+      // @ts-expect-error It has a value until reset just below
+      auctioneerKitProducer.resolve(auctioneerKit);
+      auctioneerProducer.reset();
+      // @ts-expect-error It has a value until reset just below
+      auctioneerProducer.resolve(auctioneerKit.instance);
+      // We wanted it to be valid for only a short while.
+      tempAuctioneerKit.reset();
+      await E(E(agoricNamesAdmin).lookupAdmin('instance')).update(
+        'auctioneer',
+        // @ts-expect-error It has a value until reset just below
```
Comment (turadg) [inline packages/inter-protocol/src/proposals/upgrade-vaults.js]: reset ?

File: packages/inter-protocol/src/proposals/upgrade-vaults.js [hunk 14]
```diff
@@ -0,0 +1,202 @@
...
+        auctioneerKit.instance,
+      );
+    },
+  );
+
+  console.log(`upgradeVaults scheduled; waiting for priceFeeds`);
+};
+
+const t = 'upgradeVaults';
```
Comment (turadg) [inline packages/inter-protocol/src/proposals/upgrade-vaults.js]: `t` in proposals is conventionally `true`. What's the difference again in using a string?

please giving it a distinct name to avoid confusing with `true`:
```suggestion
const uV = 'upgradeVaults';
```

File: packages/inter-protocol/src/vaultFactory/params.js [hunk 15]
```diff
@@ -1,5 +1,3 @@
-// @jessie-check
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/params.js]: this code will run in a contract so should be Jessie-safe. what was failing?

File: packages/inter-protocol/src/vaultFactory/params.js [hunk 16]
```diff
@@ -166,6 +164,19 @@ export const makeGovernedTerms = ({
   });
 };
 harden(makeGovernedTerms);
+
+// XXX Better to declare this as VaultManagerParamValues + brand. How?
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/params.js]: Does this work?
```js
/** @typedef {VaultManagerParamValues & { brand: Brand }} VaultManagerParams */
```

but why does one type have `brand` and not the other? The similar names are confusing. A `typedef` will export the type name too, which will add it to what can be imported. 

please inline. I'll leave the suggestion below.

File: packages/inter-protocol/src/vaultFactory/params.js [hunk 17]
```diff
@@ -174,8 +185,14 @@ harden(makeGovernedTerms);
  *
  * @param {import('@agoric/vat-data').Baggage} baggage
  * @param {ERef<Marshaller>} marshaller
+ * @param {Record<string, VaultManagerParams>} managerParamValues - sets of
+ *   parameters (plus brand:) keyed by Keyword. override stored initial values
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/params.js]:
```suggestion
 * @param {Record<string, VaultManagerParamValues & { collateralBrand: Brand }>} managerParamOverrides
```

File: packages/inter-protocol/src/vaultFactory/params.js [hunk 18]
```diff
@@ -174,8 +185,14 @@ harden(makeGovernedTerms);
...
  */
-export const provideVaultParamManagers = (baggage, marshaller) => {
+export const provideVaultParamManagers = (
+  baggage,
+  marshaller,
+  managerParamValues,
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/params.js]:
```suggestion
  managerParamOverrides,
```

File: packages/inter-protocol/src/vaultFactory/params.js [hunk 19]
```diff
@@ -200,8 +217,24 @@ export const provideVaultParamManagers = (baggage, marshaller) => {
...
-  [...managerArgs.entries()].map(([brand, args]) => makeManager(brand, args));
+  // restore from baggage, unless `managerParamValues` overrides.
+  for (const [brand, args] of managerArgs.entries()) {
+    let values;
+    for (const key of Object.keys(managerParamValues)) {
+      if (managerParamValues[key]?.brand === brand) {
+        values = managerParamValues[key];
+        break;
+      }
+    }
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/params.js]:
```suggestion
    const newInitial = managerParamValues.find(v => v.brand === brand);
```

File: packages/inter-protocol/src/vaultFactory/vaultDirector.js [hunk 20]
```diff
@@ -437,6 +447,12 @@ const prepareVaultDirector = (
             allManagersDo(vm => vm.lockOraclePrices());
           });
         },
+        async updateShortfallReporter(newInvitation) {
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/vaultDirector.js]: `updateShortfallReporter` has another meaning in this same module. please rename. consider `setShortfallReporter`.

File: packages/inter-protocol/src/vaultFactory/vaultManager.js [hunk 21]
```diff
@@ -335,7 +334,7 @@ export const prepareVaultManagerKit = (
         getCollateralQuote: M.call().returns(PriceQuoteShape),
         getPublicFacet: M.call().returns(M.remotable('publicFacet')),
         lockOraclePrices: M.call().returns(PriceQuoteShape),
-        liquidateVaults: M.call(AuctionPFShape).returns(M.promise()),
+        liquidateVaults: M.call(M.promise()).returns(M.promise()),
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/vaultManager.js]:
```suggestion
        liquidateVaults: M.callWhen(AuctionPFShape).returns(M.undefined()),
```

**Review by turadg — CHANGES_REQUESTED** [review]

File: a3p-integration/proposals/a:upgrade-next/agd-tools.js (hunk 1 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/agd-tools.js]: done

File: a3p-integration/proposals/a:upgrade-next/test.sh (hunk 3 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/test.sh]: I went through intermediate stages where there were other elements in `GLOBIGNORE`, and I won't be surprised if we get there again.

In those cases, it was clear that it should be defined at the top before all the `yarn` commands, rather than just before one of the lines that uses globs.

File: a3p-integration/proposals/a:upgrade-next/vatDetails.js (hunk 5 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/vatDetails.js]: Hmm. This file was added in #9158. I must need to rebase.

But the request is good. I'll write up an issue.

File: a3p-integration/scripts/generate-a3p-submissions.sh (hunk 6 above)
Comment (Chris-Hibbert) [reply a3p-integration/scripts/generate-a3p-submissions.sh:5]: Yep. thanks.

File: a3p-integration/scripts/generate-a3p-submissions.sh (hunk 7 above)
Comment (Chris-Hibbert) [reply a3p-integration/scripts/generate-a3p-submissions.sh]: These were for debugging. I think it's stable now.

File: packages/builders/scripts/vats/upgradeVaults.js (hunk 8 above)
Comment (Chris-Hibbert) [reply packages/builders/scripts/vats/upgradeVaults.js:6]: It's annoying to have multiple files with the same name. At least minor variations make it possible to select one when a list doesn't include the paths. We used to have "proposal" or "script" in the file names, but now that's in the path, so it doesn't seem necessary in the filename. Some of the files are used in ways that prohibit mixed case, like "/proposals/", apparently. "/scripts/" doesn't require it. 

Why would it be an improvement to have multiple files in different places with the same name?

I'd prefer to give this a more different name, but that gets confusing as well. We now have scripts called "upgradeZcf", "upgradeZoe", and "replaceZoe", which are all doing similar things, and each is paired with a proposal.

File: packages/inter-protocol/src/proposals/upgrade-vaults.js (hunk 12 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/proposals/upgrade-vaults.js:9]: provided by @kriskowal, so I trust it.

File: a3p-integration/proposals/a:upgrade-next/agd-tools.js (hunk 2 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/agd-tools.js]: That didn't turn out to be straightforward. I left a `XXX` comment for later.

File: packages/inter-protocol/src/proposals/upgrade-vaults.js (hunk 14 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/proposals/upgrade-vaults.js]: I think when it's a string, it can be used for drawing dependency graphs.

I saw this done recently, and I liked the pun with `t` and `true`, but I'll switch it. Puns should be avoided when they're confusing.

File: packages/inter-protocol/src/vaultFactory/params.js (hunk 15 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/params.js]: It didn't like the conditional on line 225. Replacing that code with a `.find()` loop makes it possible to keep the `jessie-check`.

None of our other code asks for a `jessie-check`. Why is it needed here?

File: packages/inter-protocol/src/vaultFactory/params.js (hunk 16 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/params.js]: > but why does one type have brand and not the other?

The normal case doesn't include it, but it's needed for reconstituting param managers (see line 188 below). In the normal case, each VM has its own paramMgr, and already knows the brand. In order to store all the param settings so they can be separately created on restart in each VM, we need a key.

> A typedef will export the type name too, which will add it to what can be imported.

This type is referenced in vaultFactory.js, which calls `provideDirector`.

File: packages/inter-protocol/src/vaultFactory/params.js (hunk 17 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/params.js]: Oh, yes! that's better. Thanks.

File: packages/inter-protocol/src/vaultFactory/params.js (hunk 18 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/params.js]: done

File: packages/inter-protocol/src/vaultFactory/params.js (hunk 19 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/params.js]: That's close. this works:
```
const newInitial = Object.values(managerParamOverrides).find(
      e => e.brand === brand,
    )
```

File: packages/inter-protocol/src/vaultFactory/vaultDirector.js (hunk 20 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/vaultDirector.js]: good catch! done.

File: packages/inter-protocol/src/vaultFactory/vaultManager.js (hunk 21 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/vaultManager.js]: done

File: packages/inter-protocol/src/proposals/upgrade-vaults.js (hunk 13 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/proposals/upgrade-vaults.js]: I replaced all these with 
```
// @ts-expect-error auctioneerKit is non-null except between auctioneerKitProducer.reset() and auctioneerKitProducer.resolve()
```

File: a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js (hunk 4 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js]: I switched to a single test driver that invokes several functions, separated by `t.log()`. 

> And consider helper like pushPrices(t) to abstract the logic
I didn't understand this. There's already a `pushPrices()`, though it taked different params. Did you think there were other obvious helpers to extract?

File: a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js [hunk 22]
```diff
@@ -92,17 +92,38 @@ test.serial('open a marginal vault', async t => {
...
 
-test('new auction vat', async t => {
+const makeNewAuctionVat = async t => {
   const details = await getDetailsMatchingVats('auctioneer');
   // This query matches both the auction and its governor, so double the count
   t.true(Object.keys(details).length > 2);
+};
+
+// test.serial() isn't guaranteed to run tests in order, so we cobble together a driver
+test('driver', async t => {
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js]: this module has helpers functions, but not a "driver" object.

it's also not testing the driver.
```suggestion
test('auction after upgrade', async t => {
```

File: packages/builders/scripts/vats/upgradeVaults.js (hunk 8 above)
Comment (turadg) [reply packages/builders/scripts/vats/upgradeVaults.js:6]: > It's annoying to have multiple files with the same name.

Like `package.json`, `types.js` and `typeGuards.js`? :-P

I think it's more confusing that it's not clear which `proposal` maps to which `script`. Maybe we should move to having a single module that provides both aspects; they're rarely separate.

Regardless, we should avoid camelCase in filenames because of the problem for case insensitive file systems. But I won't block on it.

File: packages/inter-protocol/src/vaultFactory/params.js (hunk 15 above)
Comment (turadg) [reply packages/inter-protocol/src/vaultFactory/params.js]: My understanding from @erights is that for all code that runs in vats we should try to constrain to Jessie-safe

**Review by turadg — APPROVED** [review]

File: a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js (hunk 22 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js]: renamed

File: packages/builders/scripts/vats/upgradeVaults.js (hunk 8 above)
Comment (Chris-Hibbert) [reply packages/builders/scripts/vats/upgradeVaults.js:6]: > I think it's more confusing that it's not clear which proposal maps to which script. Maybe we should move to having a single module that provides both aspects; they're rarely separate.

I think that would be a big win. I have my own cheat sheets for keeping them correlated, and at least half that work would go away if they were in one file.

**Comment by Chris-Hibbert** [comment]
I'm still getting this in three tests.
```
 error TS9006: Declaration emit for this file requires using private name 'StartFunction' from module '"/home/runner/work/agoric-sdk/agoric-sdk/packages/zoe/src/zoeService/utils"'. An explicit type annotation may unblock declaration emit.
 ```
I'd appreciate help figuring out how to address this.

File: packages/inter-protocol/src/vaultFactory/params.js [hunk 23]
```diff
@@ -210,9 +210,9 @@ export const provideVaultParamManagers = (
 
   // restore from baggage, unless `managerParamOverrides` overrides.
   for (const [brand, args] of managerArgs.entries()) {
-    const newInitial = Object.values(managerParamOverrides).find(
-      e => e.brand === brand,
-    );
+    const newInitial = managerParamOverrides
+      ? Object.values(managerParamOverrides).find(e => e.brand === brand)
+      : undefined;
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/params.js:217]: isn't this what `find()` returns when nothing matches the predicate?

Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/params.js:217]: `Object.values()` is unhappy when `managerParamOverrides` is `undefined`.

Comment (turadg) [reply packages/inter-protocol/src/vaultFactory/params.js:217]: ah. I'm surprised it's ever undefined because the function signature says it's `Record<string, VaultManagerParamOverrides>`. If optional please give it a default of `{}` instead.
