### PR TITLE
fix(auction): assets added after auction start don't set IST limit

### LINKED ISSUE #7842: In Ollinet, auction continued selling past IST limit
## Describe the bug
Observed in Ollinet on 5/25
Auction continues selling ATOM past the IST raise target.  Extra IST raised not apparent in metrics.

Note: had not seen this behavior in previous testing.  Recent tests on master (from Turadg) did not show it either.  Have reproduced it twice in Ollinet, so filing.

Observed behavior
Ran HappyPath scenario from Liquidation Model
Auction fully filled all 3 bids instead of filling 2 and partially filling the last.  This resulted in selling too much ATOM (ended with 8.427481 ATOM instead of 9.659 ATOM) and raising 320 IST instead of 309.54
Correctly paid 0.30985 ATOM as penalty to reserve
Was left with 8.11xx ATOM to return to Vault holders

Vault holders received excess collateral correctly given those numbers.  However, it is not clear where the extra 10.46 IST raised ended up.  Did not observe it in Reserve or Vaults

## To Reproduce
In Ollinet
Set auction frequency, clock step, delay period, to reasonable settings for testing (10 minutes, 20 seconds)
Set oracle price to 12.34
Set up Vaults from Happy Path scenario - ensure no other vaults are present
Set up Bids from Happy Path scenario - ensure no other bids are present
Set oracle price to 9.99
Await liquidation auction to complete

## Expected behavior
Described above 

## Screenshots
See auction with too little collateral remaining

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #7842

## Description

If assets are added after the beginning of an auction, the auction might not track the required IST, and so might sell more than is desired.

This fixes that.

### Security Considerations

None

### Scaling Considerations

None

### Documentation Considerations

None

### Testing Considerations

There was a relevant test, but it was written before liquidating vaults specified the limit. I added that to the test, and with the fix, it showed that it was now capturing the limit.

### CODE REVIEW

File: packages/inter-protocol/src/auction/auctionBook.js [hunk 1]
```diff
@@ -514,7 +514,11 @@ export const prepareAuctionBook = (baggage, zcf, makeRecorderKit) => {
               calcTargetRatio(),
             );
 
-            if (state.remainingProceedsGoal !== null) {
+            if (
+              state.remainingProceedsGoal !== null ||
+              // XXX use this as an indication that the auction is active
```
Comment (turadg) [inline packages/inter-protocol/src/auction/auctionBook.js:519]: if we end up revving CI, please elaborate the comment. (auction has an active state but the book doesn't have access to it)

File: packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js [hunk 2]
```diff
@@ -3044,7 +3044,7 @@ test('Bug 7796 missing lockedPrice', async t => {
     shortfallBalance: run.makeEmpty(),
     allocations: {
       Aeth: aeth.make(310n),
-      Fee: run.make(10_460n),
+      Fee: run.makeEmpty(),
```
Comment (turadg) [inline packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js]: I want to understand this change before approving

**Review by turadg — APPROVED** [review]
thanks for the explanation offline
