### PR TITLE
Zoe Release Candidate

### LINKED ISSUE #782: "publicAPI" feels like a weird name
Specifically, the "API" part
Maybe `public` is enough?

The design of `{invite, publicAPI}` surprises me, but maybe that's for another time

### LINKED ISSUE #836: [Zoe] Add a contract shutdown method to the Zoe Contract Facet
A zcf method, maybe zcf.shutdown() that will instruct Zoe to not accept any further offers are accepted, no invites are redeemed, no publicAPI methods are callable, etc.

This could be like the EVM SUICIDE call - should we remove this instance entirely from the instanceRecord?

### LINKED ISSUE #1016: [Zoe] Consider uniformizing wording around "active" and "complete"
Zfc has a `.complete(offerHandles)` and `.getOfferStatuses` methods
Zoe service has a `.isOfferActive(offerHandle)`

And they refer to the same thing (whether an offerHandle still has an allocation associated with it with assets hold by Zoe), but the wording does not make it easy to understand

We've had a question about this during the hackathon

### LINKED ISSUE #1210: zoe could give fewer endowments to contracts
It should be straightforward to convert the rest to imports. Wanna create an issue and assign step one to me?

_Originally posted by @Chris-Hibbert in https://github.com/Agoric/agoric-sdk/pull/1201_

### LINKED ISSUE #1267: Bug in Autoswap - users can get endless liquidity and drain liquidity pool
**Describe the bug**
@dtribble found the bug and reports:

Basically the steps in `addLiquidity` are:
* compute how much liquidity to add based on the provided currencies
* mint the appropriate liquidity tokens
* asynchronously allocate it to incoming offer
* then reallocate to apply the supplied tokens to the respective pools

# Steal all the money

The most serious problem is that the liquidity tokens are allocated to the incoming offer 
in a separate reallocate from putting the tokens into the pools. If the later `reallocate` fails,
either due to offer safety or due to an `exit` getting executed in an intervening turn, the
liquidity tokens remain allocated to the incoming offer.

The easiest way to do force this is to demand an unrealistic number of liquidity tokens. ```js
{ give: { TokenA: x(100), TokenB: y(100) },
  want: { Liquidity: liqToken(10000000000) } }```
The first reallocate succeeds, to allocate e.g., `liqToken(100)` to the offer. But the `trade`
operation on line 133 fails because even though the offer has received some `liqToken`, it
has certainly not received 10M of then, so the reallocate is rejected as not offer safe.

The "steal" comes because I can mint as much liqToken as I want this way, and then redeem it, 
sucking the liquidity out. So since it's just fractional, I can't quite get *all* the money,
but I can get most of it :).

One way to think of this is that the pool actign as another party to the contract did not 
get offer safety because it wasn't outside the contract. It could have though

# First fix - confuse the curve

The simplest fix is to make sure there's only a single allocate. Might be better to just 
move the pool outside, but nonetheless:
* change the `escrowAndAllocateTo` to put the new liquidity in the pool's offer
* change the trade to include the liq transfer to the incoming offer.

That approximately what happens with the `removeLiquidity` operation. I'm unconvinced 
that this doesn't continually accumulate liq in the pool, thus screweing up redemption,
but that's an easy fix.

```js
       return escrowAndAllocateTo({
          amount: liquidityAmountOut,
          payment: liquidityPaymentP,
          keyword: 'Liquidity',
          recipientHandle: poolHandle,
        }).then(() => {
          liqTokenSupply += liquidityExtentOut;

          trade(
            {
              offerHandle: poolHandle,
              gains: {
                TokenA: userAllocation.TokenA,
                TokenB: userAllocation.TokenB,
              },B
            },
            // We've already given the user their liquidity using
            // escrowAndAllocateTo
            { offerHandle, 
              gains: { Liquidity: liquidityAmountOut },
            },
          );
```

I *think* that's not good enough though, since the price was determined before a 
turn boundary, and then sometime later, a transaction was made based on 
that price. The pool balances were not changed however, so the price might have 
changed in ways it shouldn't, viollating chain invariants.. Because `addLiquidity` 
doesn't change the price, the bug here would be subtle. But could result in mispricing
when someone is adding a lot of liquidity and the attacker changes the price in 
the middle.

# Some alternatives

Since the contract is already separately tracking the amount of active liquidity, it should
issue the liquidity tokens up front. Then it can assign them synchronously in `addLiquidity` 
(assuming it made enough), and that operations becomes a single-turn operation like 
`removeLiquidity`.

### LINKED ISSUE #1378: Zoe is gullible to issuer's allegation of brand
https://github.com/Agoric/agoric-sdk/blob/d9bc9ecc7fb2fe73c3fb08d978db5928e5663b5c/packages/zoe/src/state.js#L208
together with
https://github.com/Agoric/agoric-sdk/blob/d9bc9ecc7fb2fe73c3fb08d978db5928e5663b5c/packages/zoe/src/state.js#L229-L231
enters a binding from the brand that the issuer alleges to an issuer record which includes the issuer. But a malicious issuer could report someone else's brand, disrupting Zoe's possible later attempt to register the true issuer of that brand. We just need to also check `brand.isMyIssuer(issuer)` to ensure they are mutually acceptable to each other. The pair may still misbehave, but they can't interfere with a later attempt to register the true owner of that brand.

There may be similar vulnerabilities elsewhere we ask an issuer for its brand without asking the brand's opinion.

### LINKED ISSUE #1421: [Zoe] UserSeat.exit() and ZCFSeat.exit() should have same behavior?
**What is the Problem Being Solved?**

@erights had previously said that if `UserSeat.exit()` and `ZCFSeat.exit()` had the same name, they should have the same behavior. In other words, if `UserSeat.exit()` is present, the seat should be exited without condition, like `ZCFSeat.exit()`. At the time, we thought that feature testing `UserSeat.exit()` would work. But @dtribble pointed out that `UserSeat` will be a presence and feature testing doesn't work on presences. The current state of `zoe-release-branch` is that `UserSeat.exit` always exists but may or may not exit. 

We need to determine if this behavior is acceptable, or if there is a better solution.

### LINKED ISSUE #1442: [Zoe] Remove makeEmptyOffer in favor of makeEmptySeatKit
**What is the Problem Being Solved?**

makeEmptySeatKit is synchronous, which makes it preferable over makeEmptyOffer, and makeEmptyOffer can be removed.

**Description of the Design**

Remove makeEmptyOffer, replace any references with makeEmptySeatKit references.

**Security Considerations**

None with this removal specifically

**Test Plan**
Current tests

### LINKED ISSUE #1455: [Zoe] Add Issuers, Brands, Maths, to Terms. Keep `startInstance` the same
**What is the Problem Being Solved?**

We have two different mechanisms within contracts to get at the term-like information. The `terms` are now the second argument to `start` within contract code. However, to get the issuers and brands, a contract developer must call `zcf.getIssuers()` and `zcf.getBrands()`. 

**Description of the Design**

`issuers`, `brands`, and `maths` become part of the `terms` object that is passed in as the second argument to `start` in contract code. Any custom terms are in the same name space, but we will ensure that the custom properties cannot overwrite `issuers/brands/maths`.
```js
const start = (zcf, terms) => {
};

const {
   issuers: { Asset: moolaIssuer, Price: simoleanIssuer },
   brands: { Asset: moolaBrand, Price: simoleanBrand },
   maths: { Asset: moolaMath, Price: simoleanMath },
   numBids: 3,
} = terms;

```
Note that the above is a full destructuring and we would not expect it to be so verbose. Also, this destructuring can be done in the signature. 

The `startInstance` call remains the same:
```js
startInstance(installation, issuerKeywordRecord, customTerms)
```

**Security Considerations**

None

**Test Plan**

Current contract tests

### PR DESCRIPTION
**Pull request by katelynsills**
This PR captures the release candidate for Zoe. We expect all current tests to pass for this branch before merging into master, and once this branch is merged into master, a round of serious testing (in which tests are added and security claims are analyzed) will be done.

#dapp-encouragement-branch: new-zoe

Closes #836 
Closes #782 
Closes #1016 
Closes #1267 
Closes #1378
Closes #1210
Closes #1444 
Closes #1442
Closes #1451 
Closes #1452
Closes #1459
Closes #1455
Closes #1421

### CODE REVIEW

**Comment by erights** [comment]
Might as well keep track of it here. The files I'm signing up to review are those in
```
   ERTP/src/
   eventual-send/src/
   zoe/src/  ---  those directly in the zoe/src directory
   zoe/src/contractFacet/
   zoe/src/contractSuport/
   zoe/src/zoeService/
```

Of `zoe/src/`, what remains is `zoe/src/contracts/`, which I am *not* signing up to review in general. But I am signing up to review some specific contracts
```
   atomicSwap.js
   automaticRefund.js
   coveredCall.js
   mintPayment.js
```
If there are other specific contracts that you think I should review, let me know.

I am not signing up to review anything in `**/test/*`. Again, if there's something specific I should look at, let me know.

Is there any better way to keep track of who reviews which files?

**Comment by erights** [comment]
On `ERTP/src` and `eventual-send/src` I'll do differential reviews, which will be trivial.
Only on the `zoe/src/` stuff enumerated above will I do from-scratch reviews.

File: packages/dapp-svelte-wallet/api/src/lib-wallet.js [hunk 1]
```diff
@@ -896,119 +943,124 @@ export async function makeWallet({
...
     // We don't even create the record until we get an alleged brand.
     const brand = await E(payment).getAllegedBrand();
 
-    /** @type {Partial<PaymentRecord>} */
-    let paymentRecord = {
+    /** @type {PaymentRecord} */
+    let paymentRecord;
+
+    const depositedPK = makePromiseKit();
+    paymentRecord = {
```
Comment (michaelfig) [inline packages/dapp-svelte-wallet/api/src/lib-wallet.js]: Combine with the above `let paymentRecord` statement.

File: packages/dapp-svelte-wallet/api/src/lib-wallet.js [hunk 2]
```diff
@@ -14,9 +16,30 @@ import { makePromiseKit } from '@agoric/promise-kit';
 import makeObservablePurse from './observable';
 import { makeDehydrator } from './lib-dehydrate';
 
+import '@agoric/zoe/exported';
+import './types';
+
 // does nothing
 const noActionStateChangeHandler = _newState => {};
 
+const cmp = (a, b) => {
```
Comment (michaelfig) [inline packages/dapp-svelte-wallet/api/src/lib-wallet.js:25]: Validate that this behaves as expected (ascending sort of a list of integers).  We might need to reverse its sense, and instead use `-cmp(a, b)` where we currently have `cmp(a, b)`.

File: packages/dapp-svelte-wallet/api/test/test-lib-wallet.js [hunk 3]
```diff
@@ -262,22 +268,23 @@ test('lib-wallet dapp suggests issuer, instance, installation petnames', async t
...
-    const { publicAPI } = await E(zoe).getInstanceRecord(instanceHandle);
-    const invite2 = await E(publicAPI).makeInvite();
+    /** @type {{ makeInvitation(): Invitation }} */
+    const publicAPI = await E(zoe).getPublicFacet(instance);
+    const invite2 = await E(publicAPI).makeInvitation();
     const {
       value: [{ handle: inviteHandle2 }],
     } = await E(inviteIssuer).getAmountOf(invite2);
-    await wallet.deposit('Default Zoe invite purse', invite2);
+    wallet.deposit('Default Zoe invite purse', invite2);
```
Comment (michaelfig) [inline packages/dapp-svelte-wallet/api/test/test-lib-wallet.js]:
```suggestion
    await wallet.deposit('Default Zoe invite purse', invite2);
```

**Review by michaelfig — DISMISSED** [review]
Reviewed `cosmic-swingset` and `dapp-svelte-wallet`.  I found a few minor nits that I will address in a new PR.

File: packages/dapp-svelte-wallet/api/test/test-lib-wallet.js (hunk 3 above)
Comment (michaelfig) [reply packages/dapp-svelte-wallet/api/test/test-lib-wallet.js]: Turns out wallet.deposit should be an async method.  Will address in a coming PR.

**Review by michaelfig — COMMENTED** [review]
I won't approve, just so that we wait for all the reviewers.

File: packages/cosmic-swingset/lib/ag-solo/vats/lib-board.js [hunk 4]
```diff
@@ -37,3 +37,5 @@ function makeBoard(seed = 0) {
 }
 
 export { makeBoard };
+
+/** @typedef {ReturnType<typeof makeBoard>} Board */
```
Comment (dtribble) [inline packages/cosmic-swingset/lib/ag-solo/vats/lib-board.js:41]: I have a more comprehensive type for Board. Should that go here?
```
 * @typedef {Object} Board
 * @property {(id: string) => any} getValue
 * @property {(value: any) => string} getId
 * @property {(value: any) => boolean} has
 * @property {() => [string]} ids```

Comment (katelynsills) [reply packages/cosmic-swingset/lib/ag-solo/vats/lib-board.js:41]: That sounds fine to me, although does cosmic-swingset have exported types?

File: packages/zoe/src/zoeService/zoeSeat.js [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+  /** @type {UserSeat} */
+  const userSeat = harden({
+    getCurrentAllocation: async () => zoeSeatAdmin.getCurrentAllocation(),
+    getProposal: async () => proposal,
+    getPayouts: async () => payoutPromiseKit.promise,
+    getPayout: async keyword =>
+      payoutPromiseKit.promise.then(payouts => payouts[keyword]),
+    getOfferResult: async () => offerResultPromiseKit.promise,
+    hasExited: async () => instanceAdmin.hasZoeSeatAdmin(zoeSeatAdmin),
+    exit: async () =>
```
Comment (katelynsills) [inline packages/zoe/src/zoeService/zoeSeat.js]: @erights, I think we are wondering if this matches the criteria stated earlier about .exit() having the same meaning. Captured here: https://github.com/Agoric/agoric-sdk/issues/1421

**Comment by erights** [comment]
Re https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469552959

I answered at https://github.com/Agoric/agoric-sdk/issues/1421#issuecomment-673118267 . We still need two different names. The meaning is completely different. Note that one or both of them might be `<adjective>Exit` because they are related enough for that.

File: packages/zoe/src/zoeService/zoe.js [hunk 6]
```diff
@@ -0,0 +1,357 @@
...
+        getTerms: () => instanceRecord.terms,
+        getIssuers: () => instanceRecord.issuerKeywordRecord,
+        getBrands: () => instanceRecord.brandKeywordRecord,
+        getInstance: () => instance,
+      };
+
+      instanceToInstanceAdmin.init(instance, instanceAdmin);
+
+      /** @type {ZoeInstanceAdmin} */
+      const zoeInstanceAdminForZcf = {
```
Comment (erights) [inline packages/zoe/src/zoeService/zoe.js:243]: There's an interesting failure property that we're not setup to handle well. Generally, if our caller gives us bad arguments, we're doing our job if we detect these bad argument during input validation, perform no side effects, and throw an error or reject a promise. However, if our zcf client gives us something bad, that's a "should never happen", and zoe should treat this as an immediately fatal error of that zcf. We should terminate it or treat it as terminated, rather than just reporting an error to it.

I'm not sure how to factor this out so we get this effect without repeated boilerplate and maintenance headache.

File: packages/zoe/src/contractFacet/contractFacet.js [hunk 7]
```diff
@@ -0,0 +1,348 @@
...
+        assert(
+          areRightsConserved(getAmountMath, previousAmounts, newAmounts),
+          details`Rights are not conserved in the proposed reallocation`,
+        );
+
+        // Commit the staged allocations and inform Zoe of the
+        // newAllocation.
+        seatStagings.forEach(seatStaging =>
+          seatToZCFSeatAdmin.get(seatStaging.getSeat()).commit(seatStaging),
+        );
```
[the remark this answers is not in the document]
Comment (erights) [reply packages/zoe/src/contractFacet/contractFacet.js]: This raises an issue we're not setup to handle well: We should somehow indicate when we have an atomic block of multiple effects, where once we're past the commit point, all effects must happen successfully. If an operation within such a commit block throws an error, that should probably be fatal for the vat incarnation --- potentially causing a rollback to prior consistent state. At a tc39 meeting, @waldemarhorwat suggested something like that (the fatal error, not the rollback) in response to our "OOM Must Fail Fast" proposal. We need something like that. This applies to the ERTP implementation as well.

File: packages/zoe/src/contractFacet/contractFacet.js [hunk 8]
```diff
@@ -0,0 +1,348 @@
...
+          invitationHandle,
+          description,
+          customProperties,
+        );
+        return invitationP;
+      },
+      // Shutdown the entire vat and give payouts
+      shutdown: () => E(zoeInstanceAdmin).shutdown(),
+
+      // The methods below are pure and have no side-effects //
```
Comment (erights) [inline packages/zoe/src/contractFacet/contractFacet.js]: OOPS! @Chris-Hibbert and I both broke this comment when we added `makeZCFMint` and `makeEmptySeatKit` methods to the block below this comment. The comment is good. Having such a split is good. Please reorder the methods. Also reorder the declaration in types.js so they continue to match. Please repeat this comment between the two groups of methods there.

File: packages/zoe/src/contracts/simpleExchange.js [hunk 9]
```diff
@@ -22,57 +27,39 @@ import '../../exported';
  * not partially fill orders.
  *
  * The invitation returned on installation of the contract is the same as what
- * is returned by calling `await E(publicAPI).makeInvite().
+ * is returned by calling `await E(publicAPI).makeInvitation().
```
Comment (erights) [inline packages/zoe/src/contracts/simpleExchange.js]: Installation of a contract does not return an invitation. What is the significance of the `await` above? An `await` is not something one calls.

File: packages/zoe/src/contracts/multipoolAutoswap/multipoolAutoswap.js [hunk 10]
```diff
@@ -0,0 +1,91 @@
...
+ * would first use the pool (X, C) then the pool (Y, C). There are no
+ * liquidity pools between two secondary tokens.
+ *
+ * There should only need to be one instance of this contract, so liquidity can
+ * be shared as much as possible.
+ *
+ * When the contract is instantiated, the central token is specified in the
+ * issuerKeywordRecord. The party that calls `E(zoe).startInstance` gets an invitation
+ * that can be used to request an invitation to add liquidity. The same
+ * invitation is available by calling `await E(publicAPI).getLiquidityIssuer(brand)`.
```
Comment (erights) [inline packages/zoe/src/contracts/multipoolAutoswap/multipoolAutoswap.js]: What is the significance of the `await` here? An `await` is not something one calls.

**Review by erights — CHANGES_REQUESTED** [review]
Review so far. Most of these can probably be triaged to post alpha.

File: packages/zoe/src/types.js [hunk 11]
```diff
@@ -8,17 +8,16 @@
...
  * actual value is just an empty object.
  */
 
 /**
  * @typedef {string} Keyword
- * @typedef {Handle<'InstallationHandle'>} InstallationHandle - an opaque handle for an bundle installation
- * @typedef {Handle<'InstanceHandle'>} InstanceHandle - an opaque handle for a contract instance
- * @typedef {Handle<'OfferHandle'>} OfferHandle - an opaque handle for an offer
- * @typedef {Handle<'InviteHandle'>} InviteHandle - an opaque handle for an invite
+ * @typedef {Handle<'InvitationHandle'>} InvitationHandle - an opaque handle for an invite
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/types.js]: Still opaque, has not changed

File: packages/zoe/src/types.js [hunk 12]
```diff
@@ -349,17 +347,86 @@
...
+ * @param {Object} terms
+ * @returns {ContractStartFnResult}
+ */
+
+/**
+ * @typedef {Payment} Invitation
+ */
+
+/**
+ * @typedef {Handle<'InstanceHandle'>} Instance
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/types.js:425]: Yes, still has no methods. I think it is clearer to not have the name `handle` in core Zoe concepts.

File: packages/zoe/src/types.js [hunk 13]
```diff
@@ -28,122 +27,128 @@
...
+ * creates the ERTP payments that represent the right to interact with
+ * a smart contract in particular ways.
+ *
+ * @property {Install} install
+ * @property {StartInstance} startInstance
+ * @property {Offer} offer
+ * @property {(instance: Instance) => Object} getPublicFacet
+ * @property {(instance: Instance) => IssuerKeywordRecord} getIssuers
+ * @property {(instance: Instance) => BrandKeywordRecord} getBrands
+ * @property {(instance: Instance) => Object} getTerms
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/types.js:58]: There is a plan to allow users to pass in an invitation to Zoe directly to get credible instance information and information about their invitation specifically, back. @Chris-Hibbert is executing. Starting issue here:  #1456

File: packages/zoe/src/types.js [hunk 14]
```diff
@@ -28,122 +27,128 @@
...
+ * omitting that argument or passing undefined, rather than passing an
+ * empty record.
+ *
+ * The proposal has three parts: `want` and `give` are used by Zoe to
+ * enforce offer safety, and `exit` is used to specify the particular
+ * payout-liveness policy that Zoe can guarantee. `want` and `give`
+ * are objects with keywords as keys and amounts as values.
+ * `paymentKeywordRecord` is a record with keywords as keys, and the
+ * values are the actual payments to be escrowed. A payment is
+ * expected for every rule under `give`.
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/types.js:120]: this is old language

File: packages/zoe/src/contractFacet/contractFacet.js [hunk 15]
```diff
@@ -0,0 +1,348 @@
...
+            allSeatStagings.has(seatStaging),
+            details`The seatStaging ${seatStaging} was not recognized`,
+          ),
+        );
+
+        // Ensure that rights are conserved overall. Offer safety was
+        // already checked when an allocation was staged for an individual seat.
+        const flattened = arr => [].concat(...arr);
+        const flattenAllocations = allocations =>
+          flattened(allocations.map(allocation => Object.values(allocation)));
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/contractFacet/contractFacet.js]: Huh, I had tried `prototype.flat` which did not work but will look into `flatMap` https://github.com/Agoric/agoric-sdk/issues/1157

File: packages/zoe/src/contractFacet/contractFacet.js [hunk 16]
```diff
@@ -0,0 +1,348 @@
...
+        );
+        const previousAmounts = flattenAllocations(previousAllocations);
+
+        const newAllocations = seatStagings.map(seatStaging =>
+          seatStaging.getStagedAllocation(),
+        );
+        const newAmounts = flattenAllocations(newAllocations);
+
+        assert(
+          areRightsConserved(getAmountMath, previousAmounts, newAmounts),
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/contractFacet/contractFacet.js]: No, I believe it is good for areRightsConserved to have a clean, independent interface focused on calculating rights conservation. We might want to have a function that serves as a kind of adapter between the two kinds of representing the data.

File: packages/zoe/src/contractFacet/contractFacet.js [hunk 17]
```diff
@@ -0,0 +1,348 @@
...
+          details`Rights are not conserved in the proposed reallocation`,
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/contractFacet/contractFacet.js]: Sure, I like that idea

File: packages/zoe/src/zoeService/zoe.js [hunk 18]
```diff
@@ -0,0 +1,357 @@
...
+      uncleanIssuerKeywordRecord = harden({}),
+      terms = harden({}),
+    ) => {
+      // Unpack the invitationKit.
+
+      const {
+        issuer: invitationIssuer,
+        mint: invitationMint,
+        amountMath: invitationAmountMath,
+      } = invitationKit;
```
Comment (Chris-Hibbert) [inline packages/zoe/src/zoeService/zoe.js]: None of this is used until line 220. Let's move it down much lower.   

after `instanceToInstanceAdmin.init(instance, instanceAdmin);` seems like a good place.

File: packages/zoe/src/zoeService/zoeSeat.js [hunk 19]
```diff
@@ -0,0 +1,74 @@
+// @ts-check
+
+import { makePromiseKit } from '@agoric/promise-kit';
+import { makeNotifierKit } from '@agoric/notifier';
+import { assert } from '@agoric/assert';
+import { E } from '@agoric/eventual-send';
+
+import '../types';
+import '../internal-types';
+
```
Comment (Chris-Hibbert) [inline packages/zoe/src/zoeService/zoeSeat.js:22]: I'd like to add
```suggestion
/**
 * makeZoeSeatAdminKit makes an object that manages the state of a seat
 * participating in a Zoe contract and return its two facets.
 *
 * The UserSeat
 * is suitable to be handed to an agent outside zoe and the contract and allows
 * them to query or monitor the current state, access the payouts and result,
 * and call exit() if that's allowed for this seat.
 *
 * The zoeSeatAdmin is passed by Zoe to the ContractFacet (zcf), to allow zcf to
 * query or update the allocation or exit the seat cleanly.
 */

```

File: packages/zoe/src/types.js [hunk 20]
```diff
@@ -310,35 +306,37 @@
...
+ * @property {AdminNode} adminNode
+ */
+
+/**
+ * @typedef {Object} VatAdminSvc
+ * @property {(bundle: SourceBundle) => RootAndAdminNode} createVat
+ */
+
+/**
+ * @typedef {Object} AdminNode
```
Comment (erights) [inline packages/zoe/src/types.js]: Can we move all these into internal-types.js?

File: packages/zoe/src/types.js [hunk 21]
```diff
@@ -349,17 +347,86 @@
...
- * @typedef {Object} InstallationRecord
- * @property {InstallationHandle} handle - opaque identifier for the installation
- * @property {SourceBundle} bundle - contract code
- *
- * @typedef {Object} OfferStatus
- * @property {OfferHandle[]} active
- * @property {OfferHandle[]} inactive
- *
- * @typedef {(offerHandle: OfferHandle) => void} OfferHook
+ * @typedef {Record<Keyword,Amount>} Allocation
```
Comment (erights) [inline packages/zoe/src/types.js:372]:
```suggestion
 * @typedef {AmountKeywordRecord} Allocation
```
makes is explicit that they are the same structural type, but `Allocation` names a more specific intention.

File: packages/zoe/src/types.js [hunk 22]
```diff
@@ -349,17 +347,86 @@
...
+ * @typedef {Record<Keyword,AmountMath>} AmountMathKeywordRecord
+ */
+
+/**
+ * @typedef {Object} ZCFSeat
+ * @property {() => void} exit
+ * @property {(msg?: string) => void} kickOut
```
Comment (erights) [inline packages/zoe/src/types.js:379]: The msg is actually a `Details` as defined in assert, rather than a string.

Do we have any candidates for a better name than `kickOut`?

File: packages/zoe/src/contractFacet/seat.js [hunk 23]
```diff
@@ -0,0 +1,107 @@
...
+    kickOut: (msg = 'Kicked out of seat') => {
+      assertExitedFalse();
+      zcfSeat.exit();
+      assert.fail(msg);
+    },
+    getNotifier: () => {
+      assertExitedFalse();
+      return notifier;
+    },
+    hasExited: () => exited,
```
Comment (erights) [inline packages/zoe/src/contractFacet/seat.js:62]: After the zcfSeat has exited, it is not completely inoperative --- its `hasExited` method still responds with an answer appropriate for the concept of an "exited seat". Some of these other methods could also give answers appropriate for an exited seat. `getNotifier` in particular could just return the notifier, which presumably is already set to report some terminated state (finished or failed).

There's no reason for `getProposal` to stop returning the `proposal` which is immutable anyway. It is still the proposal that this seat made. etc

`getAmountAllocated`, `getCurrentAmount`, and `stage` should still refuse. I'm on the fence about `isOfferSafe` but leaning towards having it continue to refuse.

File: packages/zoe/src/contractFacet/seat.js [hunk 24]
```diff
@@ -0,0 +1,107 @@
...
+    exit: () => {
+      assertExitedFalse();
+      zcfSeatAdmin.updateHasExited();
+      E(zoeSeatAdmin).exit();
+    },
+    kickOut: (msg = 'Kicked out of seat') => {
+      assertExitedFalse();
+      zcfSeat.exit();
+      assert.fail(msg);
+    },
```
Comment (erights) [inline packages/zoe/src/contractFacet/seat.js]: IIUC correctly the purpose of `exit` vs `kickOut`, then `exit` should terminate the notifier with `updater.finish` whereas `kickOut` should should terminate it with `updater.fail`.

File: packages/zoe/src/types.js [hunk 25]
```diff
@@ -28,122 +27,128 @@
...
+ * are objects with keywords as keys and amounts as values.
+ * `paymentKeywordRecord` is a record with keywords as keys, and the
+ * values are the actual payments to be escrowed. A payment is
+ * expected for every rule under `give`.
+ */
+
+/**
+ * @typedef {Object} StartInstanceResult
+ * @property {Record<string, Function>} creatorFacet
+ * @property {Record<string, Function>} publicFacet
```
Comment (erights) [inline packages/zoe/src/types.js]: Usually the public facet is typed `{Object}`. Here it is `{Record<String,Function>}`. One place it is `{PublicFacet}` where `PublicFacet` is not mentioned anywhere else.

File: packages/zoe/src/types.js [hunk 26]
```diff
@@ -349,17 +347,86 @@
...
+ * @typedef {Object} ContractStartFnResult
+ * @property {Object=} creatorFacet
+ * @property {Promise<Invitation>=} creatorInvitation
+ * @property {Object=} publicFacet
+ */
+
+/**
+ * @callback ContractStartFn
+ * @param {ContractFacet} zcf
+ * @param {Object} terms
```
Comment (erights) [inline packages/zoe/src/types.js]: This parameter goes away in the next reform?

File: packages/zoe/src/types.js [hunk 27]
```diff
@@ -349,17 +347,86 @@
...
+
+/**
+ * @template T
+ * @callback GetAmountMath
+ * @param {Brand} brand
+ * @returns {AmountMath}
+ */
+
+/**
+ * @callback Trade
```
Comment (erights) [inline packages/zoe/src/types.js:436]: AFAICT, this is the only zoeHelper whose type is in this file. Other than this, it's all been zoe itself.

**Review by erights — COMMENTED** [review]
Some of these review comments are about types. These should not actually be considered part of this review. After posting, I will link to them from separate issues and then resolve those conversations.

Typing comments from this batch are linked to from https://github.com/Agoric/agoric-sdk/issues/1465#issuecomment-673921394 and resolved here.

File: packages/zoe/src/types.js (hunk 26 above)
Comment (katelynsills) [reply packages/zoe/src/types.js]: Yes

File: packages/zoe/src/zoeService/zoeSeat.js [hunk 28]
```diff
@@ -0,0 +1,74 @@
...
+  const userSeat = harden({
+    getCurrentAllocation: async () => zoeSeatAdmin.getCurrentAllocation(),
+    getProposal: async () => proposal,
+    getPayouts: async () => payoutPromiseKit.promise,
+    getPayout: async keyword =>
+      payoutPromiseKit.promise.then(payouts => payouts[keyword]),
+    getOfferResult: async () => offerResultPromiseKit.promise,
+    hasExited: async () => instanceAdmin.hasZoeSeatAdmin(zoeSeatAdmin),
+    exit: async () =>
+      exitObjPromiseKit.promise.then(exitObj => E(exitObj).exit()),
```
Comment (erights) [inline packages/zoe/src/zoeService/zoeSeat.js]: This code can produce two unpleasant failure behaviors:

If this is an offerless seat, `makeZoeSeatAdminKit` is called with no `exitObj` named argument, resulting in `exitObjPromiseKit.promise` being a promise that never resolves. If one asks an offerless seat to `tryExit`, no response is ever received and no diagnostic is reported anywhere.

If this is a seat whose exit kind is anything other than `'onDemand'`, then `exitObjPromiseKit.promise` will be a promise for undefined. The promise returned above will eventually reject, but with a completely uninformative diagnostic that looks like an internal error rather than an inappropriate request.

To address the first problem, I suggest that the default exitObj here be one that complains that this is an offerless seat. And the default exitObj in exit.js be one that complains that this exit kind, which it shows, does not allow the user to exit the userSeat on demand.

File: packages/zoe/src/zoeService/zoeSeat.js [hunk 29]
```diff
@@ -0,0 +1,74 @@
...
+export const makeZoeSeatAdminKit = (
+  initialAllocation,
+  instanceAdmin,
+  proposal,
+  brandToPurse,
+  promises = {},
+) => {
+  const payoutPromiseKit = makePromiseKit();
+  const offerResultPromiseKit = promises.offerResult || makePromiseKit();
+  const exitObjPromiseKit = promises.exitObj || makePromiseKit();
```
Comment (erights) [inline packages/zoe/src/zoeService/zoeSeat.js]: There is no reason for these named parameters to be promiseKits. `makeZoeSeatAdminKit` only ever makes of the promises of those kits. Only the caller ever makes use of the resolvers.

File: packages/zoe/src/zoeService/zoeSeat.js (hunk 28 above)
Comment (erights) [reply packages/zoe/src/zoeService/zoeSeat.js]: Why force a round trip by
```js
exitObjPromiseKit.promise.then(exitObj => E(exitObj).exit())
```
? Better is simply
```js
E(exitObjPromiseKit.promise).exit()
```

**Review by erights — COMMENTED** [review]
Another batch

File: packages/zoe/src/zoeService/zoe.js [hunk 30]
```diff
@@ -0,0 +1,388 @@
...
+        },
+        // checks of keyword done on zcf side
+        saveIssuer: (issuerP, keyword) =>
+          issuerTable.getPromiseForIssuerRecord(issuerP).then(issuerRecord => {
+            registerIssuerByKeyword(keyword, issuerRecord);
+            const { issuer, brand } = issuerRecord;
+            if (!brandToPurse.has(brand)) {
+              brandToPurse.init(brand, E(issuer).makeEmptyPurse());
+            }
+          }),
```
Comment (erights) [inline packages/zoe/src/zoeService/zoe.js:266]: This `saveIssuer` method is correct but easy to misread as having a common bug. What's worse is that the type declared for this method
```js
  @property {(issuerP: ERef<Issuer>, keyword: Keyword) => void} saveIssuer
```
if accurate, would mean that the code actually does have the bug. The code actually returns a `Promise<undefined>` (or perhaps we say `Promise<void>`, I'm not sure). This method is remotely called as
```js
        return E(zoeInstanceAdmin)
          .saveIssuer(issuerP, keyword)
          .then(() => {
```
If `saveIssuer` was indeed void return, then the promise for the result of `E{...}.saveIssuer(...)` fulfilling, triggering the `.then` callbacks, would indicate *only* that the `saveIssuer` message had been delivered.

If the body of `saveIssuer` had been enclosed in curlies, the type would have been correct and the `.then` callback would be triggered too soon. The code is correct because the absence of these curlies causes it to return a promise for what it's internal `.then` callback returns. Deepening the illusion, this internal `.then` callback is a curly block with no `return`, which does return `undefined`. 

Terminating this internal block with an unnecessary `return undefined;` and fixing the type makes the correctness of the code easier to see.

```suggestion
        saveIssuer: (issuerP, keyword) =>
          issuerTable.getPromiseForIssuerRecord(issuerP).then(issuerRecord => {
            registerIssuerByKeyword(keyword, issuerRecord);
            const { issuer, brand } = issuerRecord;
            if (!brandToPurse.has(brand)) {
              brandToPurse.init(brand, E(issuer).makeEmptyPurse());
            }
            return undefined;
          }),
```
Also, a comment wouldn't hurt.

File: packages/zoe/src/contractFacet/seat.js [hunk 31]
```diff
@@ -0,0 +1,107 @@
...
+export const makeZcfSeatAdminKit = (
+  allSeatStagings,
+  zoeSeatAdmin,
+  seatData,
+  getAmountMath,
+) => {
+  // The proposal and notifier are not reassigned.
+  const { proposal, notifier } = seatData;
+
+  // The currentAllocation, exited, and stagedAllocation may be reassigned.
```
Comment (erights) [inline packages/zoe/src/contractFacet/seat.js]: Comment stale. There is no `stagedAllocation` variable.

File: packages/zoe/src/contractFacet/offerSafety.js [hunk 32]
```diff
@@ -1,12 +1,14 @@
+// @ts-check
+
 /**
  * Helper to perform satisfiesWant and satisfiesGive. Is
  * allocationAmount greater than or equal to requiredAmount for every
  * keyword of giveOrWant?
- * @param {(Brand) => AmountMath} getAmountMath
- * @param {Proposal["give"] | Proposal["want"]} giveOrWant
+ * @param {(brand: Brand) => AmountMath} getAmountMath
+ * @param {ProposalRecord["give"] | ProposalRecord["want"]} giveOrWant
```
Comment (erights) [inline packages/zoe/src/contractFacet/offerSafety.js:8]: (Typing only)

In a type declaration, what's the difference between
```js
ProposalRecord["give"]
```
vs
```js
ProposalRecord.give
```
? 
Why?

Would it make more sense to just declare
```js
@param {AmountKeywordRecord} giveOrWant
```
?
I would not have found it puzzling.

**Review by erights — COMMENTED** [review]
Tonight's batch. I did a from-scratch review of all the remaining files of the zoe core mechanism, as I hoped to do tonight, with one exception:

I did not give `cleanProposal.js` a from scratch review. Instead, almost nothing changed, so I ***only did a differential review*** of it, which was trivial. However, it is security critical, so it should get a deeper look sometime after merge.

**Review by dtribble — COMMENTED** [review]
Reviewed sellItems.js. Only minor comments. 

Naming concern about `assertProposalKeywords` is the last issue.

File: packages/zoe/src/contracts/mintAndSellNFT.js [hunk 33]
```diff
@@ -23,16 +23,14 @@ import '../../exported';
...
+ * @type {ContractStartFn}
  */
-const makeContract = zcf => {
-  const { terms } = zcf.getInstanceRecord();
-  const { tokenName = 'token' } = terms;
-
+const start = zcf => {
+  const { tokenName = 'token' } = zcf.getTerms();
   // Create the internal token mint
   const { issuer, mint, amountMath: tokenAmountMath } = makeIssuerKit(
```
Comment (dtribble) [inline packages/zoe/src/contracts/mintAndSellNFT.js:32]: rename `tokenAmountMath` to `tokenMath`

Comment (dtribble) [inline packages/zoe/src/contracts/mintAndSellNFT.js:32]: Should this have been turned into a synchronous mint?

**Review by dtribble — COMMENTED** [review]
Reviewed mintAndSellNFTs.  Only non-blocking questions.

File: packages/zoe/src/contractFacet/contractFacet.js (hunk 15 above)
[the remark this answers is not in the document]
Comment (dtribble) [reply packages/zoe/src/contractFacet/contractFacet.js]: also called "smoosh" :D

File: packages/zoe/src/contractFacet/exit.js [hunk 34]
```diff
@@ -0,0 +1,47 @@
...
+  let exitObj;
+
+  const exitFn = () => {
+    zcfSeatAdmin.updateHasExited();
+    return E(zoeSeatAdmin).exit();
+  };
+
+  if (exitKind === 'afterDeadline') {
+    // Automatically exit the seat after deadline.
+    E(proposal.exit.afterDeadline.timer).setWakeup(
```
Comment (dtribble) [inline packages/zoe/src/contractFacet/exit.js:29]: The promise result is not wired in anywhere so errors are silently lost. What happens if the setWakeup doesn't work? What is the time is already past?

the promise result should be tied into errors for this offer.

Comment (erights) [reply packages/zoe/src/contractFacet/exit.js:29]: That's a good point, but where would the errors be seen? For this case, there's no `tryExit()` request from the user whose result could carry the rejection.

File: packages/zoe/src/contractSupport/auctions.js [hunk 35]
```diff
@@ -1,64 +1,51 @@
-export const secondPriceLogic = (bidAmountMath, bidOfferHandles, bids) => {
+export const secondPriceLogic = (bidAmountMath, bidSeats) => {
   let highestBid = bidAmountMath.getEmpty();
   let secondHighestBid = bidAmountMath.getEmpty();
-  let highestBidOfferHandle;
-  // eslint-disable-next-line array-callback-return
-  bidOfferHandles.map((offerHandle, i) => {
-    const bid = bids[i];
+  let highestBidSeat;
+
```
Comment (dtribble) [inline packages/zoe/src/contractSupport/auctions.js:5]: Since the loop is for computing the value of `highestBidSeat`, this space shouldn't be here.

File: packages/zoe/src/contractSupport/auctions.js [hunk 36]
```diff
@@ -1,64 +1,51 @@
...
-  const bidAmountMath = zcf.getAmountMath(brandKeywordRecord.Ask);
-  const assetAmountMath = zcf.getAmountMath(brandKeywordRecord.Asset);
-
-  // Filter out any inactive bids
-  const { active: activeBidHandles } = zcf.getOfferStatuses(
-    harden(allBidHandles),
-  );
+export const closeAuction = (zcf, auctionLogicFn, sellSeat, bidSeats) => {
+  const {
+    want: { Ask: minBid },
```
Comment (dtribble) [inline packages/zoe/src/contractSupport/auctions.js:28]: FYI I filed #1482 for a more extensive cleanup of these auctions. This specific binding to a set of Keywords makes this seem like a private function for `publoicAuction` rather than a reusable public helper.

File: packages/zoe/src/contracts/publicAuction.js [hunk 37]
```diff
@@ -19,131 +21,106 @@ import '../../exported';
...
-  } = zcf.getInstanceRecord();
-  numBidsAllowed = Nat(numBidsAllowed !== undefined ? numBidsAllowed : 3);
-
-  let sellerOfferHandle;
+const start = zcf => {
+  const {
+    maths: { Asset: assetMath, Ask: bidMath },
+  } = zcf.getTerms();
+  let { numBidsAllowed = 3 } = zcf.getTerms();
+  numBidsAllowed = Nat(numBidsAllowed);
```
Comment (dtribble) [inline packages/zoe/src/contracts/publicAuction.js:41]: `Nat` is an assertion, so this doesn't need to reassign.

File: packages/zoe/src/contracts/publicAuction.js [hunk 38]
```diff
@@ -19,131 +21,106 @@ import '../../exported';
...
     // Check that the item is still up for auction
-    if (!zcf.isOfferActive(sellerOfferHandle)) {
+    if (sellSeat.hasExited()) {
       const rejectMsg = `The item up for auction is not available or the auction has completed`;
-      throw rejectOffer(offerHandle, rejectMsg);
+      throw bidSeat.kickOut(rejectMsg);
     }
-    if (allBidHandles.length >= numBidsAllowed) {
-      throw rejectOffer(offerHandle, `No further bids allowed.`);
+    if (bidSeats.length >= numBidsAllowed) {
```
Comment (dtribble) [inline packages/zoe/src/contracts/publicAuction.js:58]: These checks are redundant since the sellSeat will be exited synchronously when there are enough bids.

File: packages/zoe/src/contracts/publicAuction.js [hunk 39]
```diff
@@ -19,131 +21,106 @@ import '../../exported';
...
+      Asset: assetMath.getEmpty(),
     });
-    const bidderSatisfied = satisfies(offerHandle, {
-      Asset: zcf.getCurrentAllocation(sellerOfferHandle).Asset,
-      Bid: zcf.getAmountMath(minimumBid.brand).getEmpty(),
+    const bidderSatisfied = satisfies(zcf, bidSeat, {
+      Asset: sellSeat.getAmountAllocated('Asset', auctionedAssets.brand),
+      Bid: bidMath.getEmpty(),
     });
     if (!(sellerSatisfied && bidderSatisfied)) {
```
Comment (dtribble) [inline packages/zoe/src/contracts/publicAuction.js:69]: These checks should be independent asserts since they actually have different error reports.

File: packages/zoe/src/contracts/publicAuction.js [hunk 40]
```diff
@@ -19,131 +21,106 @@ import '../../exported';
...
-    allBidHandles.push(offerHandle);
-    if (allBidHandles.length >= numBidsAllowed) {
-      closeAuction(zcf, {
-        auctionLogicFn: secondPriceLogic,
-        sellerOfferHandle,
-        allBidHandles,
-      });
+    bidSeats.push(bidSeat);
+    if (bidSeats.length >= numBidsAllowed) {
+      closeAuction(zcf, secondPriceLogic, sellSeat, bidSeats);
```
Comment (dtribble) [inline packages/zoe/src/contracts/publicAuction.js:77]: needs a comment since this is a big step of the contract.

Comment (dtribble) [reply packages/zoe/src/contracts/publicAuction.js:77]: Also, I don' tthink all the exits and such should be in a helper. It's a pretty important thing andshould be real obvious

**Review by dtribble — COMMENTED** [review]
Reviewed auctions.js and publicAuction.js. Non-=blocking comments. Filed #1482 to cover more generally renovating these contracts.

File: packages/zoe/src/contracts/multipoolAutoswap/getCurrentPrice.js [hunk 41]
```diff
@@ -0,0 +1,47 @@
+/**
+ *
+ * @param {(brand: Brand) => boolean} isSecondary
+ * @param {(brand: Brand) => boolean} isCentral
+ * @param {(brand: Brand) => Pool} getPool
+ */
+
+import '../../../exported';
```
Comment (michaelfig) [inline packages/zoe/src/contracts/multipoolAutoswap/getCurrentPrice.js:8]: Move above the `@param` declarations, since they describe `makeGetCurrentPrice`.

File: packages/zoe/src/contracts/multipoolAutoswap/pool.js [hunk 42]
```diff
@@ -0,0 +1,175 @@
...
+    /** @type {Pool} */
+    const pool = {
+      getPoolSeat: () => poolSeat,
+      getAmountMath: () => zcf.getAmountMath(secondaryBrand),
+      getCentralAmountMath: () => zcf.getAmountMath(centralBrand),
+      getCentralAmount: () =>
+        poolSeat.getAmountAllocated('Central', centralBrand),
+      getSecondaryAmount: () =>
+        poolSeat.getAmountAllocated('Secondary', secondaryBrand),
+      getCurrentPrice: (centralToSecondary, inputValue) => {
```
Comment (michaelfig) [inline packages/zoe/src/contracts/multipoolAutoswap/pool.js:48]: I would something like an argument called `fromKeyword` with values `'Central'` or `'Secondary'`.  It would make callees easier to understand.

File: packages/zoe/src/contracts/multipoolAutoswap/pool.js [hunk 43]
```diff
@@ -0,0 +1,175 @@
...
+ * @param {(brand: Brand) => boolean} isSecondary
+ * @param {(brand: Brand, pool: Pool) => void} initPool
+ * @param {Brand} centralBrand
+ */
+export const makeAddPool = (zcf, isSecondary, initPool, centralBrand) => {
+  const makePool = (liquidityZcfMint, poolSeat, secondaryBrand) => {
+    let liqTokenSupply = 0;
+    const {
+      brand: liquidityBrand,
+      amountMath: liquidityAmountMath,
```
Comment (michaelfig) [inline packages/zoe/src/contracts/multipoolAutoswap/pool.js:25]:
```suggestion
      amountMath: liquidityMath,
```

for conciseness.

File: packages/zoe/src/contracts/multipoolAutoswap/pool.js [hunk 44]
```diff
@@ -0,0 +1,175 @@
...
+          {
+            seat: userSeat,
+            gains: {
+              Central: centralTokenAmountOut,
+              Secondary: tokenKeywordAmountOut,
+            },
+          },
+        );
+
+        userSeat.exit();
```
Comment (michaelfig) [inline packages/zoe/src/contracts/multipoolAutoswap/pool.js:135]: As above, what happens to the `liqTokenSupply` if the trade was not offer-safe?

File: packages/zoe/src/contracts/multipoolAutoswap/pool.js [hunk 45]
```diff
@@ -0,0 +1,175 @@
...
+          {
+            seat: poolSeat,
+            gains: userSeat.getCurrentAllocation(),
+          },
+          {
+            seat: userSeat,
+            gains: { Liquidity: liquidityAmountOut },
+          },
+        );
+        userSeat.exit();
```
Comment (michaelfig) [inline packages/zoe/src/contracts/multipoolAutoswap/pool.js:89]: What happens to the `liqTokenSupply` if the trade was not offer-safe?

File: packages/zoe/src/contracts/multipoolAutoswap/pool.js [hunk 46]
```diff
@@ -0,0 +1,175 @@
...
+
+  /**
+   * Allows users to add new liquidity pools. `secondaryIssuer` and
+   * its keyword must not have been already used
+   * @param {Issuer} secondaryIssuer
+   * @param {Keyword} keyword - will be used in the
+   * terms.issuers for the contract, but not used otherwise
+   */
+  const addPool = async (secondaryIssuer, keyword) => {
+    zcf.assertUniqueKeyword(keyword);
```
Comment (michaelfig) [inline packages/zoe/src/contracts/multipoolAutoswap/pool.js:150]: To avoid a game of "guess-the-unused-keyword", can we do something to manage its automatic generation  for the user from something like `Secondary${nonce}`?

File: packages/zoe/src/contracts/multipoolAutoswap/swap.js [hunk 47]
```diff
@@ -0,0 +1,136 @@
...
+      );
+
+      const seatStaging = seat.stage(
+        harden({
+          In: brandInPool.getAmountMath().getEmpty(),
+          Out: amountOut,
+        }),
+      );
+
+      const centralTokenAmountMath = brandInPool.getCentralAmountMath();
```
Comment (michaelfig) [inline packages/zoe/src/contracts/multipoolAutoswap/swap.js:95]: Instead of `*AmountMath`, can we use just simply `*Math`?

File: packages/zoe/src/contracts/multipoolAutoswap/swap.js [hunk 48]
```diff
@@ -0,0 +1,136 @@
...
+  const swap = seat => {
+    const {
+      give: { In: amountIn },
+      want: { Out: wantedAmountOut },
+    } = seat.getProposal();
+    const { brand: brandIn, value: inputValue } = amountIn;
+    const brandOut = wantedAmountOut.brand;
+
+    // we could be swapping (1) central to secondary, (2) secondary to
+    // central, or (3) secondary to secondary
```
Comment (michaelfig) [inline packages/zoe/src/contracts/multipoolAutoswap/swap.js:32]: This was mind-numbing to read.  It would be clearer to me (but YMMV) if we set up the variables, then did:
```js
if (secondaryIn) {
  trade secondaryIn to central;
}
if (secondaryOut) {
  trade central to secondaryOut;
}
seat.exit();
```

**Review by michaelfig — COMMENTED** [review]
Some comments, nothing blocking.

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 49]
```diff
@@ -3,438 +3,363 @@
...
+ *
+ * This ExpectedRecord is like a Proposal, but the amounts in 'want'
+ * and 'give' should be null; the exit clause should specify a rule with
+ * null contents. If the client submits an Offer which does not match
+ * these expectations, that offer will be rejected (and refunded).
+ *
+ * @param {OfferHandler} offerHandler
+ * @param {ExpectedRecord} expected
+ */
+export const assertProposalKeywords = (offerHandler, expected) =>
```
Comment (erights) [inline packages/zoe/src/contractSupport/zoeHelpers.js:281]: The expected record does not just check keywords. For example, `exit: { afterDeadline: ... }`. Neither is a keyword. How about `assertProposalShape`?

File: packages/zoe/src/contracts/mintPayments.js [hunk 50]
```diff
@@ -1,81 +1,63 @@
...
-    return makeInvite();
-  });
+const start = async zcf => {
+  // Create the internal token mint for a fungible digital asset. Note
+  // that 'Tokens' is both the keyword and the allegedName.
+  const zcfMint = await zcf.makeZCFMint('Tokens');
+  // AWAIT
+
+  // Now ZCF has saved the issuer, brand, and local amountMath so that they
+  // can be accessed synchronously.
```
Comment (erights) [inline packages/zoe/src/contracts/mintPayments.js:28]: Grammar.

```suggestion
  // Now ZCF has saved the issuer, brand, and local amountMath, they
  // can be accessed synchronously.
```

File: packages/zoe/src/contracts/mintPayments.js [hunk 51]
```diff
@@ -1,81 +1,63 @@
...
+  const { amountMath, issuer } = zcfMint.getIssuerRecord();
+
+  const mintPayment = (extent = 1000) => seat => {
```
Comment (erights) [inline packages/zoe/src/contracts/mintPayments.js:31]: Clearer to move the default value onto `creatorFacet.makeInvitation` below, and just have this appear as a mandatory parameter. After all `mintPayment` is only used in that one place.

As is, the parameter to `creatorFacet.makeInvitation` looks mandatory, which is misleading.

**Review by erights — COMMENTED** [review]
Reviews of my four contracts done.

I have yet to complete my review of zoeHealpers.js

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 52]
```diff
@@ -3,438 +3,363 @@
...
-      from: newFromAllocation,
-      to: newToAllocation,
-    });
+const mergeAllocations = (currentAllocation, allocation) => {
+  const newAllocation = {
+    ...currentAllocation,
+    ...allocation,
   };
+  return newAllocation;
+};
```
Comment (erights) [inline packages/zoe/src/contractSupport/zoeHelpers.js]: Please delete `mergeAllocations` and just open code the pattern inline at its one callsite. We use this pattern directly at plenty of other places. There's nothing about this abstraction that's specific to allocations. Reading the callsite, to know what it means, one needs to read the implementation anyway.

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 53]
```diff
@@ -3,438 +3,363 @@
...
+ * the 'to' allocation
+ * @param {AmountKeywordRecord} [fromLosses=toGains] - what should be lost in
+ * the 'from' allocation. If not defined, fromLosses is equal to
+ * toGains. Note that the total amounts should always be equal; it
+ * is the keywords that might be different.
+ * @returns {FromToAllocations} allocations - new allocations
+ *
+ * @typedef FromToAllocations
+ * @property {AmountKeywordRecord} from
+ * @property {AmountKeywordRecord} to
```
Comment (erights) [inline packages/zoe/src/contractSupport/zoeHelpers.js:45]: I like the intentional distinction between `Allocation` vs `AmountKeywordRecord`, where the latter may represent a change to an allocation, but a change to an allocation is not itself an `Allocation`. Using this consistently will make the code (and APIs and types and docs) easier to understand.

```suggestion
 * @property {Allocation} from
 * @property {Allocation} to
```

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 54]
```diff
@@ -3,438 +3,363 @@
...
-        keyword,
-        add(allocations.to[keyword], toGains[keyword]),
-      ]),
-    );
-
-    return harden({
-      from: newFromAllocation,
-      to: newToAllocation,
-    });
+const mergeAllocations = (currentAllocation, allocation) => {
```
Comment (erights) [inline packages/zoe/src/contractSupport/zoeHelpers.js:95]: The second `allocation` parameter of `mergeAllocations` is *not* an Allocation. It is an AmountKeywordRecord representing an update to an Allocation. `mergeAllocations` is confusingly named because it is not merging allocations. It is merging an allocation with an allocation update to produce a new allocation.

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 55]
```diff
@@ -3,438 +3,363 @@
...
+ * check; whether the allocation constitutes a refund is not
+ * checked. Allocation is merged with currentAllocation
+ * (allocations' values prevailing if the keywords are the same)
+ * to produce the newAllocation.
+ * @param {ContractFacet} zcf
+ * @param {ZCFSeat} seat
+ * @param {Allocation} allocation
+ * @returns {boolean}
+ */
+export const satisfies = (zcf, seat, allocation) => {
```
Comment (erights) [inline packages/zoe/src/contractSupport/zoeHelpers.js:145]: The `allocation` parameter to `satisfies` is not an Allocation. It is an AmountKeywordRecord representing an update to an allocation.

```suggestion
 * @param {AmountKeywordRecord} allocationUpdate
 * @returns {boolean}
 */
export const satisfies = (zcf, seat, allocationUpdate) => {
```

The comment also needs adjusting.

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 56]
```diff
@@ -3,438 +3,363 @@
...
+    console.log(`right want`, tryRight.seat.getProposal().want);
+
+    if (!offerSafeForLeft) {
+      console.log(`offer not safe for left`);
+    }
+    if (!offerSafeForRight) {
+      console.log(`offer not safe for right`);
+    }
+    return tryRight.seat.kickOut();
+  }
```
Comment (erights) [inline packages/zoe/src/contractSupport/zoeHelpers.js]: The `kickOut` call should have some informative error message. Given the wealth of diagnostics we're sending to the log for this case, the message should suggest checking the log.

Regarding the logging, what is our current practice re `console.log` calls in production code? I think it is a good idea, but I haven't seen much elsewhere. For zoe, all of then are in this vicinity. Since these are only about a detected mistake, should they be `console.warn`? We should revisit such questions during our upcoming logging summit.

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 57]
```diff
@@ -3,438 +3,363 @@
...
+ * TODO: If the try offer is no longer active, swap() should terminate with
+ * a useful error message, like defaultRejectMsg.
+ *
+ * If the swap fails, no assets are transferred, and the 'try' offer is rejected.
+ *
+ * @param {ZCFSeat} keepSeat
+ * @param {ZCFSeat} trySeat
+ * @param {String} [keepHandleInactiveMsg]
+ */
+export const swap = (
```
Comment (erights) [inline packages/zoe/src/contractSupport/zoeHelpers.js:234]: I wonder if we really need `trade` and `swap` as distinct abstractions. Swap begins by checking if keepSeat has exited. However, it should also error if trySeat has exited. `trade` should also error if either has exited, so both checks could be moved into `trade`.

Looking at the callers of `trade`, a major reason they can't use `swap` is that the `keepSeat` remains open. They all do exit the trySeat. 

Looking at the callers of `swap`, since `swap` throws on failure and only closes the `keepSeat` on success, it would not be an undue burden for swap's callers to exit the keepSeat after the call to swap. Since we did presciently call it the `keepSeat`, it would also not be surprising for `swap` itself not to close it.

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 58]
```diff
@@ -3,438 +3,363 @@
...
+ *
+ * @param {ContractFacet} zcf
+ * @param {ZCFSeat} recipientSeat
+ * @param {AmountKeywordRecord} giveAmountKeywordRecord - the keywords
+ * and amounts to give to recipient. Keywords must match the keywords
+ * for the payments.
+ * @param {PaymentKeywordRecord} paymentKeywordRecord
+ * @returns {Promise<void>}
+ */
+export const escrowAndAllocateTo = (
```
Comment (erights) [inline packages/zoe/src/contractSupport/zoeHelpers.js]: `escrowAndAllocateTo` is now unused! YAY! Please delete. Since I expect it will be deleted, I have not reviewed its contents at all. If for some reason we keep it, please let me know and I'll review.

**Review by erights — CHANGES_REQUESTED** [review]
I have finished my part of reviewing this PR.

File: packages/zoe/src/contracts/mintAndSellNFT.js (hunk 33 above)
Comment (katelynsills) [reply packages/zoe/src/contracts/mintAndSellNFT.js:32]: No, it is being sent to another contract, and there's no such thing as synchronous mint between contracts

File: packages/zoe/src/contracts/multipoolAutoswap/pool.js [hunk 59]
```diff
@@ -0,0 +1,175 @@
...
+      brandMatches,
+      `The provided issuer was using another issuer's brand`,
+    );
+    assert(
+      !isSecondary(secondaryBrand),
+      details`issuer ${secondaryIssuer} already has a pool`,
+    );
+
+    await zcf.saveIssuer(secondaryIssuer, keyword);
+    assertUsesNatMath(zcf, secondaryBrand);
```
Comment (Chris-Hibbert) [inline packages/zoe/src/contracts/multipoolAutoswap/pool.js:165]: check for validity before saving the issuer.

File: packages/zoe/src/contracts/multipoolAutoswap/pool.js (hunk 42 above)
Comment (Chris-Hibbert) [reply packages/zoe/src/contracts/multipoolAutoswap/pool.js:48]: Can this be renamed so it doesn't conflict with the top-level getCurrentPrice? Maybe this can be bundled with michaelfig's suggestion.

File: packages/zoe/src/contracts/multipoolAutoswap/swap.js [hunk 60]
```diff
@@ -0,0 +1,136 @@
...
+
+    if (isCentral(brandIn) && isSecondary(brandOut)) {
+      const pool = getPool(brandOut);
+      const amountOut = pool.getCurrentPrice(true, inputValue);
```
Comment (Chris-Hibbert) [inline packages/zoe/src/contracts/multipoolAutoswap/swap.js:36]: when `amountOut` is less than `wantedAmountOut`, should we `exit()` immediately rather than calling `trade()` when we know it should fail?

File: packages/zoe/src/contracts/multipoolAutoswap/swap.js (hunk 48 above)
Comment (Chris-Hibbert) [reply packages/zoe/src/contracts/multipoolAutoswap/swap.js:32]: with seat staging this might be possible now.  I think you're right that that would be shorter adn simpler to read.

**Review by Chris-Hibbert — CHANGES_REQUESTED** [review]

File: packages/zoe/src/contracts/multipoolAutoswap/pool.js (hunk 59 above)
Comment (katelynsills) [reply packages/zoe/src/contracts/multipoolAutoswap/pool.js:165]: What validity checks aren't being done?

File: packages/zoe/src/contracts/multipoolAutoswap/pool.js [hunk 61]
```diff
@@ -0,0 +1,175 @@
...
+              poolValue: pool.getCentralAmount().value,
+              liquidityValueIn,
+            }),
+          ),
+        );
+
+        const tokenKeywordAmountOut = pool.getAmountMath().make(
+          calcValueToRemove(
+            harden({
+              liqTokenSupply,
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/contracts/multipoolAutoswap/pool.js:111]: I think not, it's one action that we are calculating for, split between two currencies.

File: packages/zoe/src/table.js [hunk 62]
```diff
@@ -15,6 +18,7 @@ const DEFAULT_CUSTOM_METHODS = _ => ({});
  *
  * @template {string} H
  * @param {H} handleType the string literal type of the handle
+ * @returns {Handle<H>}
  */
 export const makeHandle = handleType => {
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/table.js:23]: I think we should move this into an issue to be dealt with after merge - to review and (probably) remove the table abstraction from zoe.

[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/table.js:23]: Issue here: https://github.com/Agoric/agoric-sdk/issues/1494

File: packages/zoe/src/table.js [hunk 63]
```diff
@@ -78,7 +84,7 @@ export const makeTable = (
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/table.js:84]: https://github.com/Agoric/agoric-sdk/issues/1496

File: packages/zoe/src/contractFacet/contractFacet.js [hunk 64]
```diff
@@ -0,0 +1,348 @@
...
+      ).getIssuerRecord();
+      // AWAIT
+      const mintyAmountMath = makeAmountMath(mintyBrand, mathHelperName);
+      const mintyIssuerRecord = harden({
+        brand: mintyBrand,
+        issuer: mintyIssuer,
+        amountMath: mintyAmountMath,
+      });
+      registerIssuerRecord(keyword, mintyIssuerRecord);
+      issuerTable.registerIssuerRecord(mintyIssuerRecord);
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/contractFacet/contractFacet.js]: Renamed. I put off the discussion of the logic being moved to issuerTable, since that may be changing drastically anyway

File: packages/zoe/src/objArrayConversion.js [hunk 65]
```diff
@@ -51,6 +60,7 @@ export const assertSubset = (whole, part) => {
  * @returns {Pick<T,U[number]>}
  */
 export const filterObj = (obj, subsetKeys) => {
+  /** @type {Partial<Pick<T,U[number]>>} */
   const newObj = {};
   subsetKeys.forEach(key => {
     assert(
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/objArrayConversion.js]: Removed function

File: packages/zoe/src/objArrayConversion.js [hunk 66]
```diff
@@ -59,7 +69,9 @@ export const filterObj = (obj, subsetKeys) => {
     );
     newObj[key] = obj[key];
   });
-  return newObj;
+
+  const picked = /** @type {Pick<T,U[number]>} */ (newObj);
+  return picked;
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/objArrayConversion.js]: removed function

File: packages/zoe/src/objArrayConversion.js [hunk 67]
```diff
@@ -81,3 +94,16 @@ export const filterFillAmounts = (allocation, amountMathKeywordRecord) => {
   });
   return filledAllocation;
 };
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/objArrayConversion.js]: removed function

File: packages/zoe/src/types.js [hunk 68]
```diff
@@ -28,122 +27,128 @@
 
 /**
  * @typedef {Object} ZoeService
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/types.js:29]: Making an issue for test week

[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/types.js:29]: https://github.com/Agoric/agoric-sdk/issues/1498

File: packages/zoe/src/zoeService/zoe.js (hunk 6 above)
Comment (katelynsills) [reply packages/zoe/src/zoeService/zoe.js:243]: https://github.com/Agoric/agoric-sdk/issues/1500

File: packages/zoe/src/contractFacet/contractFacet.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/contractFacet/contractFacet.js]: https://github.com/Agoric/agoric-sdk/issues/1501

File: packages/zoe/src/contractFacet/contractFacet.js [hunk 69]
```diff
@@ -0,0 +1,348 @@
...
+          details`Rights are not conserved in the proposed reallocation`,
+        );
+
+        // Commit the staged allocations and inform Zoe of the
+        // newAllocation.
+        seatStagings.forEach(seatStaging =>
+          seatToZCFSeatAdmin.get(seatStaging.getSeat()).commit(seatStaging),
+        );
+      },
+      assertUniqueKeyword: keyword => {
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/contractFacet/contractFacet.js:240]: Hmm, ok, I don't find it confusing, but let's tackle this in types

File: packages/zoe/src/contractFacet/contractFacet.js (hunk 8 above)
Comment (katelynsills) [reply packages/zoe/src/contractFacet/contractFacet.js]: Let's tackle the reordering in type.js later (I certainly was not doing any particular ordering there!)

File: packages/zoe/src/contractFacet/contractFacet.js [hunk 70]
```diff
@@ -0,0 +1,348 @@
...
+        assert(
+          !getKeywords(instanceRecord.issuerKeywordRecord).includes(keyword),
+          details`keyword ${keyword} must be unique`,
+        );
+      },
+      saveIssuer: (issuerP, keyword) => {
+        // TODO: The checks of the keyword for uniqueness are
+        // duplicated. Assess how waiting on promises to resolve might
+        // affect those checks and see if one can be removed.
+        zcf.assertUniqueKeyword(keyword);
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/contractFacet/contractFacet.js:251]: https://github.com/Agoric/agoric-sdk/issues/1502

File: packages/zoe/src/zoeService/zoeSeat.js [hunk 71]
```diff
@@ -0,0 +1,74 @@
...
+import '../types';
+import '../internal-types';
+
+/** @type {MakeZoeSeatAdminKit} */
+export const makeZoeSeatAdminKit = (
+  initialAllocation,
+  instanceAdmin,
+  proposal,
+  brandToPurse,
+  promises = {},
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/zoeService/zoeSeat.js:29]: Yeah, I didn't do this and I don't like it either. :)

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 72]
```diff
@@ -3,438 +3,363 @@
...
+import { satisfiesWant } from '../contractFacet/offerSafety';
 
 import '../../exported';
 
 export const defaultRejectMsg = `The offer was invalid. Please check your refund.`;
 export const defaultAcceptanceMsg = `The offer has been accepted. Once the contract has been completed, please check your payout`;
 
-const getKeys = obj => harden(Object.getOwnPropertyNames(obj || {}));
 const getKeysSorted = obj =>
   harden(Object.getOwnPropertyNames(obj || {}).sort());
```
[the remark this answers is not in the document]
Comment (erights) [reply packages/zoe/src/contractSupport/zoeHelpers.js:15]: See https://github.com/Agoric/agoric-sdk/pull/1499 . With that PR, for any x where `passStyleOf(x) === 'copyRecord'`, all own properties are enumerable string-named data properties, where these various forms give answers consistent with each other.

File: packages/zoe/src/zoeService/zoeSeat.js (hunk 28 above)
Comment (katelynsills) [reply packages/zoe/src/zoeService/zoeSeat.js]: I feel like offerless seats should be on demand by default. Hmm, I think that might require some redesign. Until then, I will throw an error message that says that offerless seats cannot be exited.

File: packages/zoe/src/contracts/multipoolAutoswap/pool.js (hunk 59 above)
Comment (Chris-Hibbert) [reply packages/zoe/src/contracts/multipoolAutoswap/pool.js:165]: I meant that `assertUsesNatMath()` is invoked after saving the issuer. It should come before.

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 73]
```diff
@@ -3,438 +3,363 @@
...
-    swap: (
-      keepHandle,
-      tryHandle,
-      keepHandleInactiveMsg = 'prior offer is unavailable',
-    ) => {
-      if (!zcf.isOfferActive(keepHandle)) {
-        throw helpers.rejectOffer(tryHandle, keepHandleInactiveMsg);
+  keepSeat.exit();
+  trySeat.exit();
+  return defaultAcceptanceMsg;
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/contractSupport/zoeHelpers.js:258]: Actually, I think we shouldn't do this. The error message and the return message are not symmetric. The error message is part of the thrown error so it must be a parameter if the code using this function wants to change it. The default acceptable message can be overridden in an offerHandler by just not returning the return value of swap. I think this should stay as is.

[the remark this answers is not in the document]
Comment (erights) [reply packages/zoe/src/contractSupport/zoeHelpers.js:258]: ok

File: packages/zoe/src/contracts/sellItems.js [hunk 74]
```diff
@@ -21,107 +27,100 @@ import '../../exported';
...
-
-    const { proposal } = zcf.getOffer(buyerOfferHandle);
-    const wantedItems = proposal.want.Items;
-    const numItemsWanted = wantedItems.value.length;
-    const totalCostValue = pricePerItem.value * numItemsWanted;
-    const moneyAmountMaths = zcf.getAmountMath(pricePerItem.brand);
-    const itemsAmountMath = zcf.getAmountMath(wantedItems.brand);
+  const buy = buyerSeat => {
+    const currentItemsForSale = sellerSeat.getAmountAllocated('Items');
+    const providedMoney = buyerSeat.getAmountAllocated('Money');
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/contracts/sellItems.js:51]: You could, but in the past, people haven't understood the difference between the proposal and the current allocation, so I think we should use `getAmountAllocated` if we are trying to get the current allocation to not teach people to use the proposal, since they will probably use it when we don't have those guarantees

File: packages/zoe/src/contracts/sellItems.js [hunk 75]
```diff
@@ -21,107 +27,100 @@ import '../../exported';
...
+
     // Check that the money provided to pay for the items is greater than the totalCost.
-    if (!moneyAmountMaths.isGTE(providedMoney, totalCost)) {
-      return rejectOffer(
-        buyerOfferHandle,
-        `More money (${totalCost}) is required to buy these items`,
-      );
+    if (!moneyMath.isGTE(providedMoney, totalCost)) {
+      const rejectMsg = `More money (${totalCost}) is required to buy these items`;
+      throw buyerSeat.kickOut(rejectMsg);
```
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/zoe/src/contracts/sellItems.js:70]: Good idea.

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 76]
```diff
@@ -3,438 +3,363 @@
...
+};
+
+/**
+ * @typedef ExpectedRecord
+ * @property {Record<keyof ProposalRecord['give'],null>} [want]
+ * @property {Record<keyof ProposalRecord['want'],null>} [give]
+ * @property {Partial<Record<keyof ProposalRecord['exit'],null>>} [exit]
+ */
```
[the remark this answers is not in the document]
Comment (michaelfig) [reply packages/zoe/src/contractSupport/zoeHelpers.js:266]: > I don't understand why some of these are partial and other not, even though all of them are optional.

`exit` is partial because not every kind of exit needs appear.  For example both `waived` and `onDemand` would otherwise be required, which causes a type failure if you didn't supply one of them:

```
src/contracts/auction/secondPriceAuction.js:87:7 - error TS2739: Type '{ waived: null; }' is missing the following properties from type 'Record<"waived" | "onDemand" | "afterDeadline", null>': onDemand, afterDeadline

87       exit: { waived: null },
         ~~~~

  src/contractSupport/zoeHelpers.js:219:4
    219  * @property {Record<keyof ProposalRecord['exit'], null>} [exit]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'exit' which is declared here on type 'ExpectedRecord'
```

> Is `keyof ProposalRecord['give']` the same thing as `Keyword`? If so, `Keyword` would be clearer.

Done.

File: packages/zoe/src/contractFacet/offerSafety.js (hunk 32 above)
Comment (michaelfig) [reply packages/zoe/src/contractFacet/offerSafety.js:8]: > (Typing only)
> 
> In a type declaration, what's the difference between
> 
> ```js
> ProposalRecord["give"]
> ```
> 
> vs
> 
> ```js
> ProposalRecord.give
> ```

```
Cannot access 'ProposalRecord.give' because 'ProposalRecord' is a type, but not a namespace. Did you mean to retrieve the type of the property 'give' in 'ProposalRecord' with 'ProposalRecord["give"]'?ts(2713)
```

> Would it make more sense to just declare
> 
> ```js
> @param {AmountKeywordRecord} giveOrWant
> ```

Done.

File: packages/zoe/src/types.js (hunk 27 above)
Comment (michaelfig) [reply packages/zoe/src/types.js:436]: This has been moved.

File: packages/zoe/src/types.js [hunk 77]
```diff
@@ -28,122 +27,128 @@
...
- */
-
-/**
- * @template OC - the offer outcome
- * @typedef {Object} MakeInstanceResult
- * @property {Invite<OC>} invite
- * @property {InstanceRecord} instanceRecord
  */
 
 /**
```
[the remark this answers is not in the document]
Comment (michaelfig) [reply packages/zoe/src/types.js:167]: Good catch!  That fixed another problem where I needed Partial in a bizarre place.

File: packages/zoe/src/objArrayConversion.js [hunk 78]
```diff
@@ -81,3 +94,16 @@ export const filterFillAmounts = (allocation, amountMathKeywordRecord) => {
...
+
+/**
+ * @template T, U
+ * @template {keyof T} K
```
[the remark this answers is not in the document]
Comment (michaelfig) [reply packages/zoe/src/objArrayConversion.js:39]: `keyof { a: string, b: number, 42: any }` is the specifiec union type `'a' | 'b' | 42`.

[the remark this answers is not in the document]
Comment (michaelfig) [reply packages/zoe/src/objArrayConversion.js:39]: https://www.typescriptlang.org/docs/handbook/2/types-from-extraction.html#the-keyof-type-operator

File: packages/cosmic-swingset/lib/ag-solo/vats/lib-board.js (hunk 4 above)
Comment (michaelfig) [reply packages/cosmic-swingset/lib/ag-solo/vats/lib-board.js:41]: Done.  We can add type exports to cosmic-swingset later.
