### PR TITLE
fix: clean up portfolio `parseInboundPacket` and noisy logged errors

### LINKED ISSUE #11570: prune obsolete `rebalanceFromTransfer` flow
# What

Introduce a new flow and wire it up to an address hook mapped to the porfolioKit's local chain account (LCA).

## Why

Portfolio owners (and generous donors) should be able to deposit funds to the contract for the portfolio to rebalance as configured by the owner.

## How

Provide a stubbed-out `rebalanceFromTransfer` flow and add it to the `tap.receiveUpcall` implementation on the portfolioKit.  Implement test mocks and write a test for the new functionality.

The test can fail until the core rebalance functionality can be separated from the Zoe offer interface to the portfolio.

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #11570

## Description

- Removes the unimplemented parts of `portfolio-contract`'s `rebalanceFromTransfer` flow, leaving behind a simple `parseInboundPacket` flow.
- Avoid creating promise rejections in `localchain-orchestration-account.js` to reduce blathering to the console.
- Finally, improve test fidelity in `vat/tools/fake-bridge.js` by not throwing exceptions, rather reifying them as `{ error?: string }` so that they become exceptions only when API infrastructure code wants them to be.

### Security Considerations

Simplification improves auditability.

### Scaling Considerations

Minor performance improvement, rather than logging rejection errors that were caught and handled.

### Documentation Considerations

Nothing user-facing.

### Testing Considerations

n/a

### Upgrade Considerations

Will be deployed as bundled library code during a new orchestration client contract instantiation, and also upon upgrade of existing contracts.

### CODE REVIEW

File: golang/cosmos/app/upgrade.go [hunk 1]
```diff
@@ -238,6 +238,19 @@ func makeUnreleasedUpgradeHandler(app *GaiaApp, targetUpgrade string) upgradetyp
 			}
 		}
 
+		// Upgrade vat-orchestration to avoid noisy rejections.
```
Comment (dckc) [inline golang/cosmos/app/upgrade.go]: isn't `local-orchestration-account.js` library code?

I don't see it in the `vat-orchestration` bundle:

```console
~/projects/agoric-sdk/packages/boot$ jq -r '.contents | .[] | .relativePath' bundles/bundle-vat-orchestration-js-meta.json|grep local-orch
```

I see various other stuff...

```console
~/projects/agoric-sdk/packages/boot$ jq -r '.contents | .[] | .relativePath' bundles/bundle-vat-orchestration-js-meta.json|head -4

../exos/cosmos-interchain-service.js
../../../../node_modules/@endo/far/src/index.js
../../../vow/vat.js
```

**Review by dckc — COMMENTED** [review]
are you sure this needs an upgrade to `vat-orchestration`?

File: golang/cosmos/app/upgrade.go (hunk 1 above)
Comment (dckc) [reply golang/cosmos/app/upgrade.go]: `local-orchestration-account.js` is, however, used to make the contract bundle:

```console
~/projects/agoric-sdk/packages/portfolio-deploy$ jq -r '.inputs | keys | .[]' dist/portfolio.contract.meta.json |grep local-orch
../orchestration/src/exos/local-orchestration-account.js
```

Comment (michaelfig) [reply golang/cosmos/app/upgrade.go]: I found that the change I introduced is present in a build of `agoric-sdk/packages/portfolio-deploy`:

```
cd agoric-sdk/packages/portfolio-deploy
yarn build
[...]
grep extractFirstQueryResult dist/portfolio.contract.bundle.js
```

No need for an `x/gov` chain software-upgrade!

File: packages/orchestration/src/exos/local-orchestration-account.js [hunk 2]
```diff
@@ -115,6 +137,7 @@ const PUBLIC_TOPICS = {
   account: ['Account holder status', M.any()],
 };
 
+const denomTraceNotFoundMessage = 'denomination trace not found';
```
Comment (dckc) [inline packages/orchestration/src/exos/local-orchestration-account.js]: I gather this message (pattern) comes from somewhere else; where?

I suggest we [cite the external constraint](https://github.com/Agoric/agoric-sdk/wiki/Cite-External-Constraints)

File: packages/orchestration/src/exos/local-orchestration-account.js [hunk 3]
```diff
@@ -516,12 +539,23 @@ export const prepareLocalOrchestrationAccountKit = (
       },
       parseInboundTransferWatcher: {
         /**
-         * @param {QueryDenomHashResponse} localDenomHash
+         * @param {{ error?: string; reply: TypedJson<string> }[]
+         *   | TypedJson<string>} result
```
Comment (dckc) [inline packages/orchestration/src/exos/local-orchestration-account.js:548]: the interface guard doesn't guarantee this static type; help me be sure that we don't expose this method outside the exo?

File: packages/orchestration/src/exos/local-orchestration-account.js [hunk 4]
```diff
@@ -836,11 +870,11 @@ export const prepareLocalOrchestrationAccountKit = (
 
             // Find the local denom hash for the transferDenom, if there is one.
             return watch(
-              E(localchain).query(
+              E(localchain).queryMany([
```
Comment (dckc) [inline packages/orchestration/src/exos/local-orchestration-account.js:878]: that makes my breaking-change spidey-sense tingle. Who are the possible callers here?

**Review by dckc — APPROVED** [review]
approved provided the questions don't cause you to reconsider

File: packages/orchestration/src/exos/local-orchestration-account.js (hunk 2 above)
Comment (michaelfig) [reply packages/orchestration/src/exos/local-orchestration-account.js]: Thanks for the suggestion.  I cited the constraint as `ErrTraceNotFound` from `cosmos-sdk/ibc-go`.

File: packages/orchestration/src/exos/local-orchestration-account.js (hunk 3 above)
Comment (michaelfig) [reply packages/orchestration/src/exos/local-orchestration-account.js:548]: The various layers of wrapping help ensure that `holder` is the only facet of `LocalOrchestrationAccountKit` that escapes to user code (not just used in tests).  And in practice, this facet is only used internally as a vow watcher by `holder.parseInboundTransfer`.

To help ease your concern, I put the `M.record()` argument pattern back in the `parseInboundTransferWatcher`.

File: packages/orchestration/src/exos/local-orchestration-account.js (hunk 4 above)
Comment (michaelfig) [reply packages/orchestration/src/exos/local-orchestration-account.js:878]: Regardless of possible callers (and there are many), this is not a breaking change.

Maybe a look at the [definition of `localchain.query`](https://github.com/Agoric/agoric-sdk/blob/94ab2a7e5df38ee704bd0315f1150a521ced6eea/packages/vats/src/localchain.js#L517) would help?

Following the code of the watcher shows it translates `[{error?: string, reply}]` to a `throw Error(error)` or a `return reply`.  `queryMany` is similar in spirit to `Promise.allSettled([requestP])`.

```typescript
        /**
         * Make a single query to the local chain. Will reject with an error if
         * the query fails. Otherwise, return the response as a JSON-compatible
         * object.
         *
         * @template {TypedJson} [T=TypedJson]
         * @param {T} request
         * @returns {PromiseVow<JsonSafe<ResponseTo<T>>>}
         */
        async query(request) {
          const requests = harden([request]);
          return watch(
            E(this.facets.public).queryMany(requests),
            this.facets.extractFirstQueryResultWatcher,
          );
        },
```
