### PR TITLE
fix(liveslots): collection deletion and retirement bugs

### LINKED ISSUE #8756: collection.clear() fails to decref objects used as keys, or delete the reverse-mapping vatstore entries
While working on rate-limited GC, I discovered that calling `.clear()` method on a ScalarBigMapStore or ScalarBigSetStore would fail to delete any vref-bearing objects used as keys of the collection.

## Background: How Virtual Collections work

Our `.clear()` method is fancy: it accepts a "key pattern" and "value pattern" to limit the scope of what gets cleared. When these are used, `clear()` must iterate through each entry, compare the key/value against the pattern, and only delete the ones that match.

When we omit those patterns, or when we're deleting the collection entirely (because nobody is referencing it anymore), we use a specialized function named [`clearInternalFull()`](https://github.com/Agoric/agoric-sdk/blob/6e90d9640a7129584540b2028198e92a7b6e32c4/packages/swingset-liveslots/src/collectionManager.js#L546), which avoids deserializing the keys/values first. This is faster: we need to know what the keys/values point to (so we can decrement their refcounts), but we don't need to construct any new Representatives.

Collections are encoded as one vatstore record per collection entry. The vatstore key is an encoded form of the collection key, and the vatstore value is the JSON-serialized marshalling of the collection value. We use the `encodePassable` from `@endo/marshal` to encode the collection key into a string, which can then be further encoded into a vatstore key.

The collection key might be an object, with a pass-by-reference identity. These objects all have vrefs: values like `o-12` for the Presence you get when importing an object from the kernel, `o+13` for the ephemeral Remotable you create with `Far()` and might export into the kernel, or `o+d14/2` for a Representative of one instance of a virtual/durable Kind that might also be exported into the kernel.

We need virtual collections to enumerate in a useful and stable order, and we use the vatstore ordering directly as the collection's ordering. We rely upon `encodePassable` to provide encoded keys that maintain this order. For example, all BigInts are encoded into a form that has a length prefix on the MSB side, so that `19` sorts later than `2`, and it uses a `n` or `p` prefix for negative and positive numbers to ensure `15` sorts later than `-15`.

When `encodePassable` is given a pass-by-reference object (with a vref), we cannot use the vref as the sort order. Vrefs are local to the vat, so different vats would observe different orderings. In addition, we keep vrefs private to prevent an information leak (you could learn how many objects have been allocated, which would enable both eavesdropping and a covert communication channel).

Instead, we assign each object-used-as-key an "ordinal" integer. This gives us insertion order, just like JavaScript's native Map and Set collections. For as long as the object is a key of that collection, it will retain the same ordinal. We use a second vatstore record to map from the vref to its ordinal (the key is prefixed with `|`, which is not used by `encodePassable`). And the main entry's key is a combination (safe concatenation) of the ordinal plus the vref, so we don't need a third entry to remember the ordinal->vref mapping.

Suppose `collection` is collection number 5 (whose data all uses a vatstore prefix of `vc.5.`), and userspace defines an `add` method like:
```js
Far('iface', {
  add: presence => collection.init(presence, 'data'),
})
```

If `add(p)` is invoked with a Presence whose vref is `o-12`:

* we'll assign ordinal `1` to `o-12` (if it is the first one added)
* `encodePassable` tells us to use an `encodedKey` of `r0000000001:o+v10/1`
  * that combines the `r` prefix (marking this key type as an object, rather than a string or Number or BigInt, etc), the fixed-length ordinal (providing insertion order), and the original vref (for recoverability during `.keys()` or `.entries()`)
* we build a `dbKey` of `vc.5.r0000000001:o+v10/1`
* we marshal `'data'` into something like `{ body: '"data"', slots: [] }`
* we do `vatstoreSet('vc.5.r0000000001:o+v10/1', data)`
* we also do `vatstoreSet('vc.5.|o+v10/1', '1')`, for the reverse record

## How clearInternalFull Works

Our [`clearInternalFull`](https://github.com/Agoric/agoric-sdk/blob/6e90d9640a7129584540b2028198e92a7b6e32c4/packages/swingset-liveslots/src/collectionManager.js#L553-L567) uses a loop like this:
```js
      for (const dbKey of enumerateKeysStartEnd(syscall, start, end)) {
        const value = JSON.parse(syscall.vatstoreGet(dbKey));
        doMoreGC =
          value.slots.map(vrm.removeReachableVref).some(b => b) || doMoreGC;
        syscall.vatstoreDelete(dbKey);
        if (isEncodedRemotable(dbKey)) {   ///// <--- BUG HERE
          const keyVref = vrefFromDBKey(dbKey); // <- 2nd bug
          if (hasWeakKeys) {
            vrm.removeRecognizableVref(keyVref, `${collectionID}`, true);
          } else {
            doMoreGC = vrm.removeReachableVref(keyVref) || doMoreGC;
          }
          syscall.vatstoreDelete(prefix(`|${keyVref}`));
        }
      }
```

We iterate through the DB with `enumerateKeysStartEnd` to find all the forward-mapping keys (like `vc.5.r0000000001:o+v10/1`). For each one, we fetch its value, and run all the value's slots through `vrm.removeReachableVref()`, to decrement refcounts on anything pointed to by the value. Then we delete the forward mapping with `vatstoreDelete`.

Then we use `isEncodedRemotable(dbKey)` to decide whether the *key* was a pass-by-reference value. If so, we use `vrefFromDBKey` to convert `vc.5.r0000000001:o+v10/1` into `o+v10/1`, and decrement either its reference count or its recognizability count (depending upon whether the collection was strong or weak). Finally, we delete the reverse mapping with another `vatstoreDelete`.

## The Bug

The problem is that `isEncodedRemotable(dbKey)` is being passed `vc.5.r0000000001:o+v10/1`, but is expecting `r0000000001`. This function is coming from the encode-passble library of `@endo/marshal`, and doesn't know anything about our database keys. It will always answer `false`, because liveslots is always using dbKeys that start with the virtual-collection prefix (`vc.` something), and the only encode-passable prefix that is used for "encoded remotables" is `r`.

As a result, `clearInternalFull()` will never perform the key-deletion code for passables used as keys, with two consequences:

* the key object will not have its refcount reduced, so it will stay around forever
* the reverse-mapping vatstore entry will not be removed, leaving DB space used forever

The vatstore entry will be removed if/when the collection is *deleted* (not merely cleared), because there is extra code there to delete all the `vc.5.|`-prefixed metadata keys, and that happens to include the reverse-mapping keys. But the only other way to delete that DB space (or to drop the refcounts of the key objects) is to delete the entire vat.

The `if` clause being skipped had a second bug: it calls `vrefFromDBKey(dbKey)` to get the vref to use, but that function is:
```js
    const vrefFromDBKey = dbKey => dbKey.substring(BIGINT_TAG_LEN + 2);
```

The `dbKey` actually starts with the collection prefix, like `vc.5.`, but this function is only given the job of stripping off the `r0000000001:` encode-passable tag. So it will return corrupted data.

The only other caller of `vrefFromDBKey` is in the very next function:

```js
    const decodeRemotable = encodedKey =>
      convertSlotToVal(vrefFromDBKey(encodedKey));
```

where it *does* get a prefix-stripped value. The core problem is naming: we need separate functions, with correct names and argument types:

```js
    const encodedKeyFromDBKey = dbKey => dbKey.substring(dbKeyPrefix.length);
    const vrefFromEncodedKey = encodedKey => encodedKey.substring(BIGINT_TAG_LEN + 2);
    const vrefFromDBKey = dbKey => vrefFromEncodedKey(encodedKeyFromDBKey(dbKey));
```

Incidentally, we already have an `encodedKeyFromDBKey`, it is named [`dbKeyToKey`](https://github.com/Agoric/agoric-sdk/blob/6e90d9640a7129584540b2028198e92a7b6e32c4/packages/swingset-liveslots/src/collectionManager.js#L341-L344):

```js
    function dbKeyToKey(dbKey) {
      const dbEntryKey = dbKey.substring(dbKeyPrefix.length);
      return decodeKey(dbEntryKey);
    }
```

## The Fix

* add `vrefFromEncodedKey` and fix `vrefFromDBKey`
* change `isEncodedRemotable(dbKey)` to be `isEncodedRemotable(dbKeyToKey(dbKey))`

To deploy the fix into any given vat, we must perform a liveslots-bumping vat upgrade.

## Remediation

Fortunately, our production code does not delete or clear entire collections very frequently.

Unfortunately, it is not easy to search the code for places that might delete a collection. We can grep for `clear()`, or calls to `clear(keyPatt, valuePatt)` (and filter on cases where both patterns are empty). But that won't reveal places where a collection is dropped and then gets deleted when liveslots notices all its pillars have fallen.

We can scan the slogfiles for places where two encoded-passable keys are deleted in quick succession: eyeballing the vatstore calls should make it pretty obvious if we're looking at a `clearInternalFull()`.

I think it's entirely possible that we haven't run into this problem in production yet, which would be lovely.

But if we do have lost keys, we'll need to come up with a remediation plan. Maybe we should change `deleteCollection` to look for the reverse-mapping keys as it does it's final metadata sweep, and instead of merely deleting the key, it should also decrement it's reachability/recognizability count. If the entry was deleted properly (by the non-`full` form of `clearInternal`), the refcount was changed, *and* the reverse-mapping key was deleted. So the only case where the key is still present should also mean the refcount was not changed.

Then the remediation process is to somehow get userspace to delete the affected collections.

We might also change `clear()` to scan for leftover reverse-mapping keys, after it's processed and deleted everything else, and convince userspace to merely `.clear()` the affected collections.

These would only work if the collection were still reachable by userspace. A coding pattern that re-uses the same collection but periodically clears it would probably fix itself the next time it gets cleared. But if the collection is deleted by GC, then we've lost the data that shows where refcounts came from, and remediation will have to wait for liveslots to acquire a full mark-and-sweep garbage collector (which would discover the discrepancy between the refcount and the set of references, and could correctly mark the object for deletion).

And of course, we must upgrade the vats in question to a new version of liveslots, before any of these remediations could be applied, just to get the new code into place.

## Deeper Fixes

Code-coverage would probably have spotted this: I don't think there's any way we could reach that `if` clause, and we certainly have tests that use objects as keys. So improving our coverage infrastructure would be a big help.

I'm writing more tests that examine the syscalls triggered by deletion, which is how I discovered this one. Maybe more tests of that flavor.

Stronger types might have also helped: the core confusions are that `isEncodedRemotable` takes an `encodedKey` but is given a `dbKey`, and that `vrefFromDBKey` is written to expect an `encodedKey` but its name and signature claim that it takes a `dbKey`. However, since these are all strings, I don't think the "structural types" that TypeScript offers would be sufficient to catch the bug; it would need "nominal types" to distinguish between the `dbKey` kind of string, the `encodedKey` kind of string, and the `vref` kind of string.

### PR DESCRIPTION
**Pull request by warner**
Liveslots was suffering from the following bugs:

* vrefs weren't properly encoded into DB keys and "encodePassable"
  keys when deleting collections (such that `isEncodedRemotable()`
  always answered false, which skipped the refcount processing of
  keys, and removal of the "ordinal-assignment" record)

* recognition records (vom.ir. keys) weren't created or removed for
  Remotable-style keys in weak collections

* Presence-style vrefs were not submitted for retirement processing
  when deleting a weak collection

As a result:

* `collection.clear()` left the "ordinal-assignment"` records in the
  vatstore, causing subsequent .has(oldkey) to incorrectly return
  true, and .init(oldkey, newvalue) to throw a "already registered"
  error, as well as consuming DB space longer than necessary.

* Invoking the `.clear()` method on a virtual/durable collection, or
  dereferencing the collection itself (and allowing it to be garbage
  collected), did not free any Remotables, virtual/durable
  objects (Representatives), or imported Presences used as keys. This
  could cause data in other weak collections (or other vats) to be
  retained longer than necessary.

* retiring (deleting) a Remotable used as a key in a weak
  virtual/durable collection did not free the corresponding value,
  causing data (in local and/or remote vats) to be retained longer
  than necessary

* Allowing a weak virtual/durable collection to be garbage collected
  did not inform the kernel that the vat can no longer recognize the
  Presence-style keys, consuming c-list entries longer than necessary.

This commit fixes those bugs, which fixes the immediate cause of
issues #8756 , #7355 , and #9956 . As a change to liveslots, full
deployment requires both restarting the kernel with this new
code, *and* triggering a vat upgrade of all vats. Once that is done,
no new collection entries will suffer the problems listed above.

However, this commit makes no attempt to remediate any existing data
corruption. See #8759 for plans to build a tool that can audit the
virtual-data reference graph and detect the consequences of these bugs
in pre-existing kernel databases, and see the issues listed above for
notes on efforts to build remediation tools.

### CODE REVIEW

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 1]
```diff
@@ -0,0 +1,438 @@
...
+    Imports are in one of 5 states: UNKNOWN, REACHABLE, UNREACHABLE,
+    COLLECTED, FINALIZED. Note that there's no actual state machine with those
+    values, and we can't observe all of the transitions from JavaScript, but
+    we can describe what operations could cause a transition, and what our
+    observations allow us to deduce about the state:
+
+    * UNKNOWN moves to REACHABLE when a crank introduces a new import
+    * userspace holds a reference only in REACHABLE
+    * REACHABLE moves to UNREACHABLE only during a userspace crank
+    * UNREACHABLE moves to COLLECTED when GC runs, which queues the finalizer
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]: Probing my knowledge:
```suggestion
    * UNREACHABLE moves to COLLECTED when engine GC runs, which queues the finalizer
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 2]
```diff
@@ -0,0 +1,438 @@
...
+    * COLLECTED moves to FINALIZED when a new turn runs the finalizer
+    * liveslots moves from FINALIZED to UNKNOWN by syscalling dropImports
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
    * FINALIZED moves to UNKNOWN when liveslots sends a dropImports syscall
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 3]
```diff
@@ -0,0 +1,438 @@
...
+    * UNKNOWN to REACHABLE by creating a new Presence
+    * UNREACHABLE to REACHABLE by re-using the old Presence that userspace
+      forgot about
+    * COLLECTED/FINALIZED to REACHABLE by creating a new Presence
+
+    Our tracking tables hold data that depends on the current state:
+
+    * slotToVal holds a WeakRef in [REACHABLE, UNREACHABLE, COLLECTED]
+    * that WeakRef .deref()s into something in [REACHABLE, UNREACHABLE]
+    * possiblyDeadSet holds the vref only in FINALIZED
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
    * in [REACHABLE, UNREACHABLE, COLLECTED], slotToVal holds a WeakRef
    * in [REACHABLE, UNREACHABLE], that WeakRef .deref()s into something
    * in FINALIZED, possiblyDeadSet holds the vref only
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 4]
```diff
@@ -0,0 +1,438 @@
...
+    * (TODO) re-introduction could remove the vref from possiblyDeadSet
+
+    Each state thus has a set of perhaps-measurable properties:
+
+    * UNKNOWN: slotToVal[baseRef] is missing, baseRef not in possiblyDeadSet
+    * REACHABLE: slotToVal has live weakref, userspace can reach
+    * UNREACHABLE: slotToVal has live weakref, userspace cannot reach
+    * COLLECTED: slotToVal[baseRef] has dead weakref
+    * FINALIZED: slotToVal[baseRef] is missing, baseRef is in possiblyDeadSet
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
    * UNKNOWN: slotToVal[baseRef] is missing, baseRef not in possiblyDeadSet
    * REACHABLE: slotToVal[baseRef] weakref is live, userspace can reach
    * UNREACHABLE: slotToVal[baseRef] weakref is live, userspace cannot reach
    * COLLECTED: slotToVal[baseRef] weakref is dead
    * FINALIZED: slotToVal[baseRef] is missing, baseRef is in possiblyDeadSet
```
Also, I observe a switch here to "baseRef" (from "vref" in preceding text). Can we consistently adopt a single term that covers both virtual/durable cohorts and import/export values? Is "baseRef" already that term? (_"For Presence- and Remotable- style objects, the vref and baseref are the same" below suggests yes_)

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 5]
```diff
@@ -0,0 +1,438 @@
...
+    finalizer callback queued. So the callback must deduce the current state
+    and only perform cleanup (i.e. delete the slotToVal entry and add the
+    baseRef to possiblyDeadSet) in the COLLECTED state.
+
+    Our general rule is "trust the finalizer". The GC code below
+    considers a Presence to be reachable (the vref's "RAM pillar"
+    remains "up") until it moves to the FINALIZED state. We do this to
+    avoid race conditions between some other pillar dropping (and a
+    BOYD sampling the WeakRef) while it is in the COLLECTED state. If
+    we treated COLLECTED as unreachable,, then the subsequent
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]: Typo fix:
```suggestion
    we treated COLLECTED as unreachable, then the subsequent
```
Also, what is intended by the lowercase "unreachable" here? Rather than talking about states, should this say something like "_If we examined the vref in COLLECTED", then…"_?

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 6]
```diff
@@ -0,0 +1,438 @@
...
+  possiblyRetiredSet if the vref was at least RECOGNIZABLE
+  beforehand. This helps us avoid a vat-fatal duplicate dropImports or
+  retireImports syscall.
+
+  For imports, the lifetime is controlled by the upstream vat: we
+  might drop REACHABLE today and maintain RECOGNIZABLE for days until
+  the object is finally retired. For exports *we* control the
+  lifetime, so when we determine an export is no longer REACHABLE, we
+  delete it and retire the vref immediately, and it does not
+  observably linger in the RECOGNIZABLE state. This simplifies our
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]: "RECOGNIZABLE" is not defined or used above. Should these instances instead be "UNREACHABLE"?

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 7]
```diff
@@ -0,0 +1,438 @@
...
+
+    Our finalizer callback is queued by the engine's transition from
+    UNREACHABLE to COLLECTED, but the baseRef might be re-introduced before the
+    callback has a chance to run. There might even be multiple copies of the
+    finalizer callback queued. So the callback must deduce the current state
+    and only perform cleanup (i.e. delete the slotToVal entry and add the
+    baseRef to possiblyDeadSet) in the COLLECTED state.
+
+    Our general rule is "trust the finalizer". The GC code below
+    considers a Presence to be reachable (the vref's "RAM pillar"
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
    considers a Presence to be reachable (the vref's "RAM pillar" [defined below]
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 8]
```diff
@@ -0,0 +1,438 @@
...
+  Remotables have only the RAM pillar. When a Remotable-style vref is
+  exported to the kernel, the Remotable is added to the
+  `exportedRemotables` set. And when it is stored in vdata, it appears
+  as a key of the `remotableRefCounts` map. That keeps the Remotable
+  itself alive until the other reachability pathways have gone
+  away. We don't do this for Representatives because it would violate
+  our "don't use RAM for inactive virtual objects" rule.
+
+  When an imported Presence becomes UNREACHABLE, it might still be
+  RECOGNIZABLE, by virtue of being the key of one or more weak
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
  recognizable, by virtue of being the key of one or more weak
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 9]
```diff
@@ -0,0 +1,438 @@
...
+  collections. If not, it might transit from REACHABLE directly to
+  NONE. The code that reacts to the UNREACHABLE transition must check
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
  collections. If not, it might transit from REACHABLE directly to
  COLLECTED. The code that reacts to the UNREACHABLE transition must check
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 10]
```diff
@@ -0,0 +1,438 @@
...
+     * sort possiblyDeadSet, examine each by type
+       * presence (vref):
+         * if unreachable:
+           * dropImports
+           * add to possiblyRetiredSet
+       * remotable (vref):
+         * if unreachable:
+           * retireExports if kernelRecognizableRemotables
+           * vrm.ceaseRecognition
+       * VOM (baseref)
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
       * VOM (baseRef)
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 11]
```diff
@@ -0,0 +1,438 @@
...
+  the "baseRef". For example, `o+d44/2` is a BaseRef for a cohort, the
+  second instance created of the `o+d44` Kind, whose individual facets
+  would have vrefs of `o+d44/2:0` and `o+d44/2:1`.
+
+  We use a WeakMap to ensure that holding any facet will keep all the
+  others alive, so the cohort lives and dies as a group. The GC
+  tracking code needs to track the whole cohort at once, not the
+  individual facets, and any data structure which refers to cohorts
+  will use the BaseRef instead of a single vref. So `slotToVal` is
+  keyed by a BaseRef, and its values are a cohort of facets. But
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
  the "baseRef". For example, `o+d44/2` is a baseRef for a cohort, the
  second instance created of the `o+d44` Kind, whose individual facets
  would have vrefs of `o+d44/2:0` and `o+d44/2:1`.

  We use a WeakMap to ensure that holding any facet will keep all the
  others alive, so the cohort lives and dies as a group. The GC
  tracking code needs to track the whole cohort at once, not the
  individual facets, and any data structure which refers to cohorts
  will use the baseRef instead of a single vref. So `slotToVal` is
  keyed by a baseRef, and its values are a cohort of facets. But
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 12]
```diff
@@ -0,0 +1,438 @@
...
+*/
+
+/*
+  BaseRef vs vref
+
+  For multi-facted virtual/durable objects (eg `defineKind()` with
+  facetd `behavior` argument), each time userspace create a new
+  instance, we create a full "cohort" of facets, passing a record of
+  Representative objects (one per facet) back to the caller. Each
+  facet gets is own vref, but they all share a common prefix, known as
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
  facet gets its own vref, but they all share a common prefix, known as
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 13]
```diff
@@ -0,0 +1,438 @@
...
+  exceptions are:
+  * slotToVal is keyed by baseRef
+  * possiblyDeadSet holds baseRefs, that's what our WeakRefs track
+  * vrm.isVirtualObjectReachable takes baseRef
+  * vrm.deleteVirtualObject takes baseRef, returns [bool, retireees=vrefs]
+  * vrm.ceaseRecognition takes either baseRef or vref
+    (if given a baseRef, it will process all the facets)
+
+  For Presence- and Remotable- style objects, the vref and baseref are
+  the same.
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion

  For Presence- and Remotable- style objects, the baseRef is just the vref
  (i.e., every baseRef is either a cohort-identifying prefix or an
  isolated-object vref, and every vref either has a baseRef prefix and
  identifies one facet of a cohort or has no such prefix and identifies an
  isolated object).

  Most GC-related APIs take vrefs but not cohort-identifying baseRefs, with the
  following exceptions:
  * slotToVal is keyed by baseRef
  * possiblyDeadSet holds baseRefs, that's what our WeakRefs track
  * vrm.isVirtualObjectReachable takes baseRef
  * vrm.deleteVirtualObject takes baseRef, returns [gcAgain, retirees]
  * vrm.ceaseRecognition takes baseRef (and if that baseRef identifies a cohort,
    all its facets will be processed)
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 14]
```diff
@@ -0,0 +1,438 @@
...
+  syscall,
+  possiblyDeadSet,
+  possiblyRetiredSet,
+}) => {
+  // Presence (o-NN) lifetimes are controlled by the upstream vat, or
+  // the kernel. If the vref was in possiblyDeadSet, then it *was*
+  // reachable before, so we can safely presume the kernel to think we
+  // can reach it.
+
+  const checkImportPresence = vref => {
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
  // Presence (o-NN) lifetimes are controlled by the upstream vat, or
  // the kernel. If the vref was in possiblyDeadSet, then it *was*
  // reachable before, so we can safely presume the kernel to think we
  // can reach it.
  const checkImportPresence = vref => {
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 15]
```diff
@@ -0,0 +1,438 @@
...
+    // RAM pillar || vdata pillar
+    const isReachable = slotToVal.has(vref) || vrm.isPresenceReachable(vref);
+    // use slotToVal.has, not getSlotForVal(), to avoid duplicate drop
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
    // RAM pillar || vdata pillar
    // use slotToVal.has, not getValForSlot(), to avoid duplicate drop
    const isReachable = slotToVal.has(vref) || vrm.isPresenceReachable(vref);
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 16]
```diff
@@ -0,0 +1,438 @@
...
+  // recognition records, and to inform the kernel with a
+  // retireExports if kernelRecognizableRemotables says that the
+  // kernel still cares.
+
+  // note: we track export status for remotables in the
+  // kernelRecognizableRemotables set, not vom.es.VREF records. We
+  // don't currently track recognition records with
+  // vom.ir.VREF|COLLECTION, but we should, see #9956
+
+  const checkExportRemotable = vref => {
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]: Visual grouping suggestion:
```suggestion
  // recognition records, and to inform the kernel with a
  // retireExports if kernelRecognizableRemotables says that the
  // kernel still cares.
  //
  // note: we track export status for remotables in the
  // kernelRecognizableRemotables set, not vom.es.VREF records. We
  // don't currently track recognition records with
  // vom.ir.VREF|COLLECTION, but we should, see #9956
  const checkExportRemotable = vref => {
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 17]
```diff
@@ -0,0 +1,438 @@
...
+  // Representative (o+dNN/II or o+vNN/II) lifetimes are also
+  // controlled by us. We allow the Representative object to go away
+  // without deleting the vref, so we must track all three pillars:
+  // Representative (RAM), export, and vdata. When we decide the vref
+  // is unreachable, we must delete the virtual object's state, as
+  // well as retiring the object (by telling the kernel it has been
+  // retired, if the kernel cares, and removing any local recognition
+  // records).
+
+  const checkExportRepresentative = baseRef => {
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
  // Representative (o+dNN/II or o+vNN/II) lifetimes are also
  // controlled by us. We allow the Representative object to go away
  // without deleting the vref, so we must track all three pillars:
  // Representative (RAM), export, and vdata. When we decide the vref
  // is unreachable, we must delete the object's state, as well as
  // retiring the object (by telling the kernel it has been retired,
  // if the kernel cares, and removing any local recognition records).
  const checkExportRepresentative = baseRef => {
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 18]
```diff
@@ -0,0 +1,438 @@
...
+           * add to possiblyRetiredSet
+       * remotable (vref):
+         * if unreachable:
+           * retireExports if kernelRecognizableRemotables
+           * vrm.ceaseRecognition
+       * VOM (baseref)
+         * if unreachable:
+           * deleteVirtualObject (and retireExports retirees)
+       * all: remove from possiblyDeadSet
+     * repeat loop if gcAgain or possiblyDeadSet.size > 0
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
   * outer loop
     * gcAndFinalize
     * sort possiblyDeadSet, examine each by type
       * all: remove from possiblyDeadSet
       * presence (vref):
         * if unreachable:
           * dropImports
           * add to possiblyRetiredSet
       * remotable (vref):
         * if unreachable:
           * retireExports if kernelRecognizableRemotables
           * vrm.ceaseRecognition
       * VOM (baseRef)
         * if unreachable:
           * deleteVirtualObject (and retireExports retirees)
     * repeat loop if gcAgain or possiblyDeadSet.size > 0
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 19]
```diff
@@ -0,0 +1,438 @@
...
+    let gcAgain = false;
+
+    do {
+      gcAgain = false;
+      await gcTools.gcAndFinalize();
+
+      // process a sorted list of vref/baseRefs we need to check for
+      // reachability, one at a time
+
+      for (const vrefOrBaseRef of [...possiblyDeadSet].sort()) {
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
      for (const baseRef of [...possiblyDeadSet].sort()) {
```
?

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 20]
```diff
@@ -0,0 +1,438 @@
...
+        // remove the vref now, but some deleteVirtualObject might
+        // shake it loose again for a future pass to investigate
+        possiblyDeadSet.delete(vrefOrBaseRef);
+
+        const parsed = parseVatSlot(vrefOrBaseRef);
+        assert.equal(parsed.type, 'object', vrefOrBaseRef);
+
+        let res = {};
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
        let result = {};
```
?

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 21]
```diff
@@ -0,0 +1,438 @@
...
+        if (parsed.virtual || parsed.durable) {
+          const baseRef = vrefOrBaseRef;
+          res = checkExportRepresentative(baseRef);
+        } else if (parsed.allocatedByVat) {
+          const vref = vrefOrBaseRef;
+          res = checkExportRemotable(vref);
+        } else {
+          const vref = vrefOrBaseRef;
+          res = checkImportPresence(vref);
+        }
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]: The commentary and function definitions above are ordered like (presence, remotable, representative), while this logic proceeds in the reverse order (logically so, given the nature of the tests). Should the commentary and function definitions follow suit, or are we fine with the discrepancy?

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 22]
```diff
@@ -0,0 +1,438 @@
...
+
+        // prepare our end-of-crank syscalls
+        if (res.dropImport) {
+          importsToDrop.add(res.dropImport);
+          possiblyRetiredSet.add(res.dropImport);
+        }
+        for (const facetVref of res.exportsToRetire || []) {
+          exportsToRetire.add(facetVref);
+        }
+        gcAgain ||= !!res.gcAgain;
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]: Can we get to a point where `res.gcAgain` is guaranteed to be boolean?
```suggestion
        gcAgain ||= res.gcAgain;
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 23]
```diff
@@ -0,0 +1,438 @@
...
+      }
+
+      // Deleting virtual object state, or freeing weak-keyed
+      // collection entries, might shake loose more
+      // objects. possiblyDeadSet and possiblyRetiredSet are added
+      // when vdata vrefs are decreffed to zero, and gcAgain means that
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
      // objects. possiblyDeadSet and possiblyRetiredSet are added to
      // when a vdata vref decrefs to zero, and gcAgain means that
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 24]
```diff
@@ -0,0 +1,438 @@
...
+          (slotToVal.has(vref) || vrm.isPresenceReachable(vref));
+        // note: the old version used getValForSlot, which treats
+        // COLLECTED as unreachable, which would allow a retirement at
+        // the wrong time (before the finalizer fires and does the
+        // dropImport)
+        const isRecognizable = isReachable || vrm.isVrefRecognizable(vref);
+        if (!isRecognizable) {
+          importsToRetire.add(vref);
+        }
+      }
```
Comment (gibson042) [inline packages/swingset-liveslots/src/boyd-gc.js]: Reducing indentation depth:
```suggestion
      if (parsed.allocatedByVat) continue;

      // If we're dropping the vref, checkImportPresence() already
      // did our isReachable check, so we can safely skip it (and
      // save a vatstore syscall).
      const isReachable =
        !importsToDrop.has(vref) &&
        // Use slotToVal.has, not getValForSlot(), to avoid retirement
        // before the finalizer fires and does dropImport.
        (slotToVal.has(vref) || vrm.isPresenceReachable(vref));
      const isRecognizable = isReachable || vrm.isVrefRecognizable(vref);
      if (!isRecognizable) {
        importsToRetire.add(vref);
      }
```

File: packages/swingset-liveslots/src/collectionManager.js [hunk 25]
```diff
@@ -293,6 +293,17 @@ export function makeCollectionManager(
       return `${dbKeyPrefix}${dbEntryKey}`;
     }
 
+    // a "vref" is a string like "o-4"
```
Comment (gibson042) [inline packages/swingset-liveslots/src/collectionManager.js]:
```suggestion
    // a "vref" is a string like "o-4" or "o+d44/2:0"
```

File: packages/swingset-liveslots/src/collectionManager.js [hunk 26]
```diff
@@ -293,6 +293,17 @@ export function makeCollectionManager(
...
+    // an "EncodedKey" is the output of encode-passable:
+    // * strings become `s${string}`, like "foo" -> "sfoo"
+    // * positive BigInts become `p${len}:${digits}`, 47n -> "p2:47"
```
Comment (gibson042) [inline packages/swingset-liveslots/src/collectionManager.js]: This isn't exactly right, as [documented in encodePassable.js](https://github.com/endojs/endo/blob/67141a177bef32e037f454a696a4532999560ff8/packages/marshal/src/encodePassable.js#L151-L162).
```suggestion
    // * small positive BigInts become `p${len}:${digits}`, like 47n -> "p2:47"
```

File: packages/swingset-liveslots/src/collectionManager.js [hunk 27]
```diff
@@ -293,6 +293,17 @@ export function makeCollectionManager(
...
+    // * refs are assigned an "ordinal" and encode as "r0000000001:o-4"
```
Comment (gibson042) [inline packages/swingset-liveslots/src/collectionManager.js]:
```suggestion
    // * refs are assigned an "ordinal" and become `r${fixedLengthOrdinal}:${vref}`, like vref(o-4) -> "r0000000001:o-4"
```

File: packages/swingset-liveslots/src/collectionManager.js [hunk 28]
```diff
@@ -293,6 +293,17 @@ export function makeCollectionManager(
...
+    // a "DBKey" is used to index the vatstore
+    // * DBKeys for collection entries join a collection prefix to an EncodedKey
+    // * "foo" -> "vc.5.sfoo"
+    // * 47n -> "vc.5.p2:47"
+    // * vref(o-4) -> "vc.5.r0000000001:o-4"
```
Comment (gibson042) [inline packages/swingset-liveslots/src/collectionManager.js]:
```suggestion
    // a "DBKey" is used to index the vatstore
    // DBKeys for collection entries join a collection prefix and an EncodedKey
    // Possible DBKeys for entries of the collection identified by prefix "vc.5":
    // * "foo" -> "vc.5.sfoo"
    // * 47n -> "vc.5.p2:47"
    // * vref(o-4) -> "vc.5.r0000000001:o-4"
```

File: packages/swingset-liveslots/src/collectionManager.js [hunk 29]
```diff
@@ -347,10 +359,16 @@ export function makeCollectionManager(
...
 
     function dbKeyToKey(dbKey) {
+      // convert e.g. vc.5.r0000000001:o+v10/1 to r0000000001:o+v10/1
       const dbEntryKey = dbKey.substring(dbKeyPrefix.length);
       return decodeKey(dbEntryKey);
     }
 
+    function dbKeyToEncodedKey(dbKey) {
+      assert(dbKey.startsWith(dbKeyPrefix), dbKey);
+      return dbKey.substring(dbKeyPrefix.length);
```
Comment (gibson042) [inline packages/swingset-liveslots/src/collectionManager.js:377]: This common use case could benefit from promoting [`stripPrefix`](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/src/kernel/state/kernelKeeper.js#L188-L191) to e.g. `@agoric/internal`.
```js
function dbKeyToEncodedKey(dbKey) {
  return stripPrefix(dbKeyPrefix, dbKey);
}
```

File: packages/swingset-liveslots/src/collectionManager.js [hunk 30]
```diff
@@ -563,8 +581,9 @@ export function makeCollectionManager(
         doMoreGC =
           value.slots.map(vrm.removeReachableVref).some(b => b) || doMoreGC;
         syscall.vatstoreDelete(dbKey);
-        if (isEncodedRemotable(dbKey)) {
-          const keyVref = vrefFromDBKey(dbKey);
+        const encodedKey = dbKeyToEncodedKey(dbKey);
+        if (isEncodedRemotable(encodedKey)) {
+          const keyVref = vrefFromEncodedKey(encodedKey);
```
Comment (gibson042) [inline packages/swingset-liveslots/src/collectionManager.js]: Suggestion for a single-pass loop:
```js
export const collectionMetaKeys =
  new Set(['|entryCount', '|nextOrdinal', '|schemata']);
```
```js
      // visit every DB entry associated with the collection, which due to
      // sorting will be collection entries first and then a mixture of ordinal
      // mappings and size-independent metadata (both of which start with "|").
      for (const dbKey of enumerateKeysWithPrefix(syscall, dbKeyPrefix)) {
        const encodedKey = dbKeyToEncodedKey(dbKey);

        // preserve general metadata ("|entryCount" is cleared by our caller)
        if (collectionMetaKeys.has(encodedKey)) continue;

        if (!encodedKey.startsWith('|')) {
          // an entry; decref slots from its value
          const value = JSON.parse(syscall.vatstoreGet(dbKey));
          doMoreGC =
            value.slots.map(vrm.removeReachableVref).some(b => b) || doMoreGC;
        } else {
          // must be an ordinal mapping; decref its vref
          const keyVref = encodedKey.substring(1);
          parseVatSlot(keyVref);
          if (hasWeakKeys) {
            vrm.removeRecognizableVref(keyVref, `${collectionID}`, true);
          } else {
            doMoreGC = vrm.removeReachableVref(keyVref) || doMoreGC;
          }
        }

        // in either case, delete the DB entry
        syscall.vatstoreDelete(dbKey);
      }
```
or if you find the `enumerateKeysStartEnd` to be more clear, then a post-loop assertion that the collection no longer has any DB entries relating to its own entries (i.e., no entry data and no ordinal mapping data).
```js
      for (const dbKey of enumerateKeysWithPrefix(syscall, dbKeyPrefix)) {
        const encodedKey = dbKeyToEncodedKey(dbKey);
        collectionMetaKeys.has(encodedKey) ||
          Fail`internal: unexpected collection DB key suffix ${encodedKey}`;
      }
```

**Review by gibson042 — APPROVED** [review]
Excellent test coverage, as usual.

@erights notes that all three styles are "Remotables", so this PR should probably adopt new vocabulary for classifying vrefs (e.g., "presence" vs. "representative" vs. ~~"remotable"~~ "ephemeral"/"heap").

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 3 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: hm, I like having the state names on the left, but your version inverts the A-implies-B relationship, and I realized I should be more precise about "X happens *only* in state Y"

I think I'll change it to:
    * slotToVal holds a WeakRef only in [REACHABLE, UNREACHABLE, COLLECTED]
    * that WeakRef .deref()s into something only in [REACHABLE, UNREACHABLE]
    * possiblyDeadSet holds the vref only in FINALIZED

I can't find a concise way to include the "only" with the state-names-on-the-left phrasing.

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 5 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: Lowercase because I got fuzzy with the states I'm trying to describe. The original GC terminology was established before we had virtual objects, so it was almost entirely talking about Presences. We have one set of states for the Presence object (where COLLECTED and FINALIZED are things), but we have a different set of states for the abstract vref-centric object thing. Within a vat, the vref thing might be reachable (by any one of the three pillars). From the kernel's point of view, the vat has a reachable or merely-recognizable or neither c-list import status.

Also, the phrase "if we treated COLLECTED as UNREACHABLE" seems non-sensical the previous several paragraphs describe these as mutually-exclusive states (along with REACHABLE and UNKNOWN and FINALIZED). What we're really saying is "if we treated the Presence `Object` having the engine-GC-category COLLECTED state as meaning the RAM pillar was *down* (and thus not contributing to the reachability of the vref-thing), then the subsequent finalizer ..".

I'll see if I can tweak it a bit without going that verbose. Some day we'll need a more precise writeup.

Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: Oh yeah I hint at that at the beginning of the paragraph:

> The GC code below considers a Presence to be reachable (the vref's "RAM pillar" remains "up") until it moves to the FINALIZED state.

Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: maybe:

> If we treated COLLECTED as unreachable (the RAM pillar being "down"), then the subsequent finalizer callback would..

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 4 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: Hm, good question, I don't have a satisfying answer. Yeah, `baseRef` is the superset, `vref` is one subtype, and we don't have a name for the other subtype.

| category | typical BaseRef | typical related vrefs |
| --- | --- | --- |
| Presence | o-1 | o-1 |
| Remotable / heap | o+1 | o+1 |
| Representative | o+d4/5 | o+d4/5:0 , o+d4/5:1 , o+d4/5:2 |

`slotToVal` is keyed by things in the second column, `valToSlot` has values from the third column. If you call `ceaseRecognition()` with something from the second column, it will act as if you'd called it multiple times with each of the things from the third column.

I think I'll file an issue to refactor our documentation and find a way to be clear about our types. It might take the form of phrases like "the one vref of this baseref (one, because the baseref is Presence- or Remotable- style)". #9991

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 6 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: No, the vref-thing state this section is describing is one of only three states, reachable, merely-recognizable, or unknown. Let me see if I can add a paragraph to establish the different between e.g. REACHABLE for a Presence and "reachable" for the vref it embeds.

Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: ok the "paragraph" came out to two pages, but now I've got terms like VREF-RECOGNIZABLE and EXPORT-REACHABLE and they're all distinct from the REACHABLE/COLLECTED/etc that Presences have.

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 9 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: nope, this part is talking about the logical objects, which have only (in the new text) VREF-REACHABLE, VREF-RECOGNIZABLE, and nothing. So this line is talking about transitioning directly from VREF-REACHABLE to nothing, perhaps triggered by the Presence `Object` reaching FINALIZED, or perhaps by the vdata pillar dropping.

hopefully the new text will make this more clear

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 16 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: I like the extra `//`, but removing the newline at the end makes the start of the function less obvious on my screen.. I'll apply half

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 17 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: same issue, maybe it's just my editor's font-coloring choices

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 19 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: eh, hrm, maybe.. I think that until we have three distinct names, it's safer to use `vrefOrBaseRef` to indicate what assumptions we aren't making yet

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 20 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: meh, I think `res` is sufficient, it's clearly a result of some sort, and there's nothing nearby to suggest that it might mean "resolution"

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 21 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: yeah, i'd be nice if they matched.. I wrote the functions and commentary first, and then found the conditionals were ugly unless I flipped them. I'll move the functions and their comments to match.

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 22 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: Only two of the three branches wants to control it (Representative and Remotable), so my options are:

* 1: have `checkImportPresence` add an extra `.. gcAgain: false }` in its return value
* 2: have the scanForDeadObjects clause do something like `res = { gcAgain: false, ...res }`
* 3: lean on the fact that `undefined` is falsy and use `gcAgain ||= res.gcAgain`
* 4: use the explicit `!!res.gcAgain` coercion

1 is a little verbose and a little out-of-place, 2 is ugly, 3 means I'll spend another half hour fighting the typechecker (maybe `/** @type { bool | undefined } */` before the `let gcAgain = false`? ugh), so 4 seemed like the least bad.

But, I could live with 1, if you thought it was better than 4.

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 24 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: am I allowed to omit braces on an `if`? I thought that would cause the world to end or something. :)

Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: I'm slightly weirded out by splitting an expression with a comment, but I'm living dangerously today, I'll give it a whirl

File: packages/swingset-liveslots/src/collectionManager.js (hunk 27 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js]: you're really trying to blow my 80-column budget, aren't you :)

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 5 above)
Comment (gibson042) [reply packages/swingset-liveslots/src/boyd-gc.js]: Yeah, that's good.

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 19 above)
Comment (gibson042) [reply packages/swingset-liveslots/src/boyd-gc.js]: Works for me.

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 22 above)
Comment (gibson042) [reply packages/swingset-liveslots/src/boyd-gc.js]: Nah, this is fine.

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 14 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: eh, I like the gap, same reasons as above

File: packages/swingset-liveslots/src/collectionManager.js (hunk 29 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js:377]: agreed, but lemme see if I can do that without increasing the dependency load, I'm nervous about commonly-used packages growing extra "useful" functionality that drags more code into the fairly isolated bundle.

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 7 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: with the new text, "pillars" are defined well before this point

File: packages/swingset-liveslots/src/collectionManager.js (hunk 29 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js:377]: Yeah, that's a good longer-term fix, but I don't want this PR to modify`@agoric/internal` this week. I'll make a note to look into that later.

For my future reference:
```
$ cd packages/swingset-xsnap-supervisor
$ yarn build
$ cat supervisor.bundle|jq -r .source |grep -e '\(node_modules\|packages/\)' |cut -d: -f1
```
will emit a list of the packages included in the supervisor bundle (which is how liveslots gets delivered to a worker). That currently includes:
* `packages/store`
* `packages/swingset-liveslots`
* `packages/swingset-xsnap-supervisor`
* `@endo/{base64,common,compartment-mapper,env-options,errors,eventual-send,exo,far,import-bundle,marshal,nat,pass-style,patterns,promise-kit,zip}`

At a quick glance, adding `@agoric/internal` might grow that with `@endo/{init,stream}`, `@agoric/base-zone`, `anylogger`, and `jessie.js`.

Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js:377]: filed #9996

File: packages/swingset-liveslots/src/collectionManager.js (hunk 30 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js]: yeah, ok, I've warmed to the single-pass loop, will apply

Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js]: I flipped the `if()` to make it simpler, please double-check my math

File: packages/swingset-liveslots/src/collectionManager.js [hunk 31]
```diff
@@ -553,26 +579,38 @@ export function makeCollectionManager(
...
+          const keyVref = encodedKey.substring(1);
+          parseVatSlot(keyVref);
           if (hasWeakKeys) {
             vrm.removeRecognizableVref(keyVref, `${collectionID}`, true);
           } else {
             doMoreGC = vrm.removeReachableVref(keyVref) || doMoreGC;
           }
-          syscall.vatstoreDelete(prefix(`|${keyVref}`));
+        } else {
+          // an entry; decref slots from its value
```
Comment (gibson042) [inline packages/swingset-liveslots/src/collectionManager.js]:
```suggestion
          // a collection entry; decref slots from its value
```

**Review by gibson042 — APPROVED** [review]

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 32]
```diff
@@ -1,65 +1,190 @@
...
+  For garbage-collection purposes, liveslots tracks the "reachable"
+  and "recognizable" status for these logical objects.  A logical
+  object is either VREF-REACHABLE, VREF-RECOGNIZABLE, or nothing. The
+  logical objects form a two-color directed graph, or you may think of
+  it as a graph and an overlaying subgraph. The first color contains
+  "weak" or "recognizable" edges: a weakly-keyed collection can
+  recognize its keys, but does not hold them strongly, so it does not
+  provide "reachable" access. The second/overlay color represents
+  "strong" or "reachable" edges, where access to the first object
+  enables strong access to the second.
```
Comment (mhofman) [inline packages/swingset-liveslots/src/boyd-gc.js]: It's not clear here whether objects on the value side of a WeakMap are recognizable or reachable colored, or something else. Currently we consider them reachable until the key is no longer recognized, but in fact they should be considered "conditionally reachable" once the key becomes recognizable only (an if no other reachable edge points at them).

I find it much easier to think of WeakMap as creating `AND` joins in the graph from the key and the WeakMap instance, to the value (where other reachability edges form a `OR` joins). At that point loose recognizable WeakMap keys are really just members of a "recognizable root set".

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 33]
```diff
@@ -1,65 +1,190 @@
...
+  preserve all reachable data, but it can delete data that can no
+  longer be reached. Liveslots also needs to coordinate status updates
+  with the kernel, to enable the kernel to do the same.
+
+  The logical object for an imported vref (known as a "Presence-style
+  vref", o-NN) can be kept alive by either the existence of an actual
+  Presence `Object`, or by a (strong) virtual/durable collection that
+  uses the vref as its key or inside its value, or by a (weak)
+  collection that uses the vref inside its value, or by a
+  virtual/duralbe object that uses the vref inside its `state`. We
```
Comment (mhofman) [inline packages/swingset-liveslots/src/boyd-gc.js]:
```suggestion
  virtual/durable object that uses the vref inside its `state`. We
```

File: packages/swingset-liveslots/src/boyd-gc.js [hunk 34]
```diff
@@ -1,65 +1,190 @@
...
+  Objects which are unreachable by our vat might still be reachable by
+  others, or by something in the exporting vat, so becoming
+  unreachable is not the end of the story. The logical object might
+  still be *recognizable* by our vat, as a key in one or more weak
+  collections. While in this VREF-RECOGNIZABLE state, three things
+  might happen:
+
+  * The owner, or someone who still has access, may send it to us in a
+    message. The vat code receives a newly-minted Presence object, and
+    now the logical object is VREF-REACHABLE once more.
```
Comment (mhofman) [inline packages/swingset-liveslots/src/boyd-gc.js]: This section seems centered on imported presences, without making that clear.

Technically a representative can also be unreachable locally (or merely recognizable locally): create a virtual/durable object, use it as key in a weak collection, export it, and drop the local representative without storing it in any other store. The exporting vat can no longer reach the logical object on its own.

File: packages/swingset-liveslots/src/collectionManager.js [hunk 35]
```diff
@@ -347,10 +367,16 @@ export function makeCollectionManager(
     }
 
     function dbKeyToKey(dbKey) {
+      // convert e.g. vc.5.r0000000001:o+v10/1 to r0000000001:o+v10/1
       const dbEntryKey = dbKey.substring(dbKeyPrefix.length);
       return decodeKey(dbEntryKey);
     }
 
+    function dbKeyToEncodedKey(dbKey) {
+      assert(dbKey.startsWith(dbKeyPrefix), dbKey);
```
Comment (mhofman) [inline packages/swingset-liveslots/src/collectionManager.js:376]: This might be a case where the `cond || Fail` style is meaningfully more efficient.

File: packages/swingset-liveslots/src/collectionManager.js [hunk 36]
```diff
@@ -553,26 +579,38 @@ export function makeCollectionManager(
...
-        const value = JSON.parse(syscall.vatstoreGet(dbKey));
-        doMoreGC =
-          value.slots.map(vrm.removeReachableVref).some(b => b) || doMoreGC;
-        syscall.vatstoreDelete(dbKey);
-        if (isEncodedRemotable(dbKey)) {
-          const keyVref = vrefFromDBKey(dbKey);
+
+      // visit every DB entry associated with the collection, which
+      // (due to sorting) will be collection entries first, and then a
+      // mixture of ordinal-assignment mappings and size-independent
```
Comment (mhofman) [inline packages/swingset-liveslots/src/collectionManager.js:585]: Oh I hadn't realized that ordinal mappings and metadata used the same "space". That's kinda unfortunate,

File: packages/swingset-liveslots/src/collectionManager.js [hunk 37]
```diff
@@ -553,26 +579,38 @@ export function makeCollectionManager(
...
+      // metadata (both of which start with "|").
+      for (const dbKey of enumerateKeysWithPrefix(syscall, dbKeyPrefix)) {
+        const encodedKey = dbKeyToEncodedKey(dbKey);
+
+        // preserve general metadata ("|entryCount" and friends are
+        // cleared by our caller)
```
Comment (mhofman) [inline packages/swingset-liveslots/src/collectionManager.js:591]: I actually just looked at `clearInternal`, and I don't understand why it forcibly sets the `entryCount` to `0` when we're clearing with a pattern. Is there a bug there too?

It's also a bit unfortunate that when a pattern is used, we need to potentially recreate a representative/presence just to clear the entry.

(I can't comment there because it's out of "scope" of the diff)

File: packages/swingset-liveslots/src/virtualReferences.js [hunk 38]
```diff
@@ -500,26 +500,52 @@ export function makeVirtualReferenceManager(
...
+   * the collection's internal (real) WeakMap under the Remotable
+   * object itself (because the engine handles the bookkeeping, and
+   * there is no virtual data in the value that we need to clean up at
+   * deletion time).
+   *
+   * It is critical that each collection have exactly one recognizer
+   * that is unique to that collection, because the recognizers
+   * themselves will be tracked by their object identities, but the
+   * recognizer cannot be the collection itself else it would prevent
+   * the collection from being garbage collected.
```
Comment (mhofman) [inline packages/swingset-liveslots/src/virtualReferences.js]: I don't quite understand this paragraph

**Review by mhofman — APPROVED** [review]
I am still reviewing the tests, but I expect I won't have any blocking feedback on them.

Consider addressing the 2 following items:
- avoid `assert()` style checks in potentially performance sensitive paths. There is a decent overhead compared to `|| Fail` style.
- Incidental: double check the entry count logic (and maybe add a test) for when the collection is cleared with a key pattern in `clearInternal`.

The rest is all docs nitpicks.

File: packages/swingset-liveslots/src/collectionManager.js (hunk 30 above)
Comment (mhofman) [reply packages/swingset-liveslots/src/collectionManager.js]: FWIW, I preferred the other direction for the `if` as it represented better the order of iteration.

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 34 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: Good point. I'll change the first clause to:
```
  * The owner, or someone who still has access, may send it to us in a
    message. The vat code receives a newly-minted Presence or
    Representative object, and now the logical object is
    VREF-REACHABLE once more.
```

File: packages/swingset-liveslots/src/boyd-gc.js (hunk 32 above)
Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]: Yeah, I guess if I'm going to try to interpret this as a multi-colored graph, I have to work out the details more completely. The weak-colored edge that a weak collection provides from key to value is itself held alive by the collection, which means there must be a strong-color edge from something in the REACHABLE set to the collection itself.

I think I'll remove the details and just say that there's a graph-based interpretation without actually trying to nail down what it is. I think the reader will understand the intent.

Comment (warner) [reply packages/swingset-liveslots/src/boyd-gc.js]:
```

  For garbage-collection purposes, liveslots tracks the "reachable"
  and "recognizable" status for these logical objects.  A logical
  object is either VREF-REACHABLE, VREF-RECOGNIZABLE, or
  nothing. Strong references from a VREF-REACHABLE object makes the
  target also VREF-REACHABLE. Weak references from a VREF-REACHABLE
  makes the target at least VREF-RECOGNIZABLE, although it might be
  VREF-REACHABLE if there is also a strong reference to it.

  Weak collections provide weak access to their keys, and strong
  access to their values. Strong collections provide strong access to
  both keys and values. Virtual/durable objects provide strong access
  to their `state`. The "reachable set" is the transitive closure of
  strong edges, given a set of anchors. There will also be a
  "recognizable set", with weak edges from some members of the
  reachable set.
```

File: packages/swingset-liveslots/src/virtualReferences.js (hunk 38 above)
Comment (warner) [reply packages/swingset-liveslots/src/virtualReferences.js]: Yeah, that's leftover from the original implementation, the idea is that each voAwareWeakSet needs a distinct `recognizer`, they can't e.g. share one among the whole class. And, the recognizer is not the same thing as the `voAwareWeakSet` itself, because the strong reference we keep to the recognizer would prevent the `voAwareWeakSet` from being freed. So it must be 1-to-1 but not identical.

Comment (warner) [reply packages/swingset-liveslots/src/virtualReferences.js]: replaced with:
```
   * Each voAwareWeakMap/Set must have a distinct recognizer, so we
   * can remove the key from the right ones. The recognizer is held
   * strongly by the recognition record, so it must not be the
   * voAwareWeakMap/Set itself (which would inhibit GC).
```

File: packages/swingset-liveslots/src/collectionManager.js (hunk 37 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js:591]: sigh, yes, I'll file a new bug. #10007

File: packages/swingset-liveslots/src/collectionManager.js (hunk 36 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js:585]: yep, it got the ordinal-assignment records safely out of the main data range, and only steals one character from the encode-passable protocol, but it does rely upon vrefs never colliding with the fixed set of metadata keys like `|entryCount`

File: packages/swingset-liveslots/src/collectionManager.js (hunk 37 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js:591]: I'll include a failing test and a note on `clearInternal()` where the bug needs to be fixed.

File: packages/swingset-liveslots/src/collectionManager.js (hunk 35 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js:376]: That saves one function call, right? Because we aren't doing any string interpolation in the message argument.

Comment (mhofman) [reply packages/swingset-liveslots/src/collectionManager.js:376]: ah yeah the most expensive part of `assert` was if there was no message argument provided. Anyway, saving a function call is good too, but maybe not as necessary.
