### PR TITLE
fix(swing-store): remove explicit wal_checkpoint

### LINKED ISSUE #7069: remove the explicit wal_checkpoint(FULL)
## What is the Problem Being Solved?

The current swingstore DB code uses WAL mode, with `synchronous=FULL`:

https://github.com/Agoric/agoric-sdk/blob/40dc2876ae171890ce1364d47668ca69a6206869/packages/swing-store/src/swingStore.js#L203-L204

and then during `commit()`, it does both a DB `COMMIT` and a `wal_checkpoint(FULL)`:

https://github.com/Agoric/agoric-sdk/blob/40dc2876ae171890ce1364d47668ca69a6206869/packages/swing-store/src/swingStore.js#L517-L529

When SQLite is in WAL mode, it records new changes in the separate `.wal` file, and then periodically does a "checkpoint" to merge these changes back into the main `.sqlite` file. Read performance is slightly degraded if the WAL file gets too large (readers must look in two places to make sure they're seeing all potential writes), and that only gets fixed by the checkpoint operation. By default, SQLite performs a checkpoint/merge when it reaches some size (1000 pages, probably 1 or 2 MB of data). There are some interlock considerations if there are other readers or writers, and you can choose a checkpoint mode to adjust the aggressiveness of the checkpoint operation. The default of `PASSIVE` basically does as much work as it can, but will give up on the merge if there are other readers or writers at work. That doesn't cause any immediate problems: eventually there won't be any contention, and the checkpoint can finish to completion.

I originally [recommended](https://github.com/Agoric/agoric-sdk/pull/6561#discussion_r1050213665) using the `wal_checkpoint(FULL)` as a way to get durability safety despite power loss. Upon closer reading of the [SQLite WAL-mode docs](https://sqlite.org/wal.html#performance_considerations), I [changed my mind](https://github.com/Agoric/agoric-sdk/pull/6561#issuecomment-1360418217), and figured that the `synchronous=FULL` was sufficient to get durability. But we didn't wind up removing the `FULL` from the checkpoint step.

@mhofman noticed that `wal_checkpoint(FULL)` causes a significant stall: it is [defined](https://sqlite.org/c3ref/wal_checkpoint_v2.html) to "until there is no database writer and all readers are reading from the most recent database snapshot". In practice, he found that it causes the process to busywait for 5 seconds, waiting for a timeout, if an export has aread transaction open in another connection. That's 5s during which nothing else happens in the host application, which is pretty painful.

## Description of the Design

The fix is to just remove the forced checkpoint. Our choice of `PRAGMA synchronous=full` gets us a proper flush/`fsync` after every COMMIT, which means we don't need or care about checkpoints doing their own flush. We can let SQLite perform best-effort checkpoints automatically, and eventually it will manage to clean everything up.

## Security Considerations

none

## Scaling Considerations

none

## Test Plan

none

### PR DESCRIPTION
**Pull request by warner**
We're using `synchronous=FULL`, so we don't need to perform an explicit `wal_checkpoint(FULL)` to obtain durability in the face of power loss. And the FULL-mode checkpoints cause a 5s busy-wait when we have an external reader connection (like the upcoming swing-store exporter, which runs in a thread or subprocess, with it's own DB connection).

This commit just removes the call to `PRAGMA wal_checkpoint(FULL)` entirely.

closes #7069

### CODE REVIEW

File: packages/swing-store/src/swingStore.js [hunk 1]
```diff
@@ -200,6 +200,15 @@ function makeSwingStore(dirPath, forceReset, options = {}) {
     // { verbose: console.log },
   );
```
Comment (mhofman) [inline packages/swing-store/src/swingStore.js:201]: Wondering if we shouldn't take the opportunity to set the timeout at 0 as well, to prevent any busy waits.

```suggestion
  {
    // verbose: console.log,
    timeout: 0,
  });
```

**Review by mhofman — APPROVED** [review]
LGTM, but consider also dropping the default timeout.

File: packages/swing-store/src/swingStore.js (hunk 1 above)
Comment (warner) [reply packages/swing-store/src/swingStore.js:201]: I disagree, in my experiments so far, that makes things pretty fragile. I'm ok with the application experiencing jank if we're doing some manual interaction with the DB (something like `sqlite3 swing-store.sqlite 'DELETE FROM historical_transcript_spans'` comes to mind), I'm not so ok with causing it to crash if that operation takes too long. 5s is a probalistic measure, to be sure, but kernel insta-death just feels really risky.
