### PR TITLE
change processUpgradeVat to delete c-list entries

### LINKED ISSUE #9039: vat upgrade leaves refcount=1 on disconnected/rejected promises
## Describe the bug

While looking at the results of the emerynet test of upgrade-14, we noticed an increase (by several hundred) in the number of resolved kernel promise table entries. Further investigation of the DB contents and slogfiles show that, while the kernel correctly disconnects/rejects all promises decided by the upgraded vat, it does not *delete* them as it is supposed to, because it fails to decrement the refcount on that promise.

The consequence is a storage leak, as we leave the kernel-promise table record around, even though nothing is still referring to it. For the promises leaked during this upgrade, record contains four keys:

* `kp1068808.data.body`: `#{"incarnationNumber":0,"name":"vatUpgraded","upgradeMessage":"vat upgraded"}`
* `kp1068808.data.slots`:
* `kp1068808.refCount`: `1`
* `kp1068808.state`: `rejected`

Normally, when a vat uses `syscall.resolve()` to fulfill or reject a promise, the vat's c-list entry for that promise is deleted during the [`translateResolve()`](https://github.com/Agoric/agoric-sdk/blob/c5284e4721ad2702c4551f216bb8eed7abe4d7cf/packages/SwingSet/src/kernel/vatTranslator.js#L532) translation step, by calling `vatKeeper.deleteCListEntriesForKernelSlots()` here:

https://github.com/Agoric/agoric-sdk/blob/c5284e4721ad2702c4551f216bb8eed7abe4d7cf/packages/SwingSet/src/kernel/vatTranslator.js#L564-L567

A standard side-effect of deleting a c-list entry is to decrement the kref's refcount, in e.g. `kp1068808.refCount`.

After translation from vat-refs to kernel-refs, the syscall is actually executed with a function named [`doResolve()`](https://github.com/Agoric/agoric-sdk/blob/c5284e4721ad2702c4551f216bb8eed7abe4d7cf/packages/SwingSet/src/kernel/kernelQueue.js#L37):

When the promise is resolved (rejected) during `processUpgradeVat()`, here:

https://github.com/Agoric/agoric-sdk/blob/c5284e4721ad2702c4551f216bb8eed7abe4d7cf/packages/SwingSet/src/kernel/kernel.js#L902-L905

it uses `resolveToError()`, which routes to the same `doResolve()` as a syscall. *But*, because the decref happens during translation, and we don't do any translation in the upgrade path, we're missing the decref. Thus, the `refCount` is left at `1`, and the table entry is never removed.

## Fix Ideas

The rough fix is to change `processUpgradeVat()` to decrement the refcount as the promises are resolved, or use `deleteCListEntriesForKernelSlots` and follow the `syscall.resolve()` path as much as possible. However, there are cases where the vat is subscribed to their own promise (eg if they used a durable `watchPromise()` against a locally-decided `Promise`), and we need to keep working in those.

Every promise in the vat's c-list is either vat-decided or kernel-decided (as determined by the `${kpid}.decider` kvStore entry). For vat-decided promises, the usual resolution path is a `syscall.resolve()`, which deletes the c-list entry (and decrement the refcount). For kernel-decided promises, the usual path is a `dispatch.notify()`, which does the same thing.

For upgrade, we identify all the vat-decided kpids and use `doResolve()` to reject them. This sets their state, and enqueues `notify()` for any vat that is subscribed (possibly including the upgraded vat, which handles the `watchPromise()` case). And we need the c-list entry to stick around until that time, because we'll be translating the kpid to a vpid to deliver a `dispatch.notify()` to the new incarnation. So in that case, we must retain the refcount until that time, and allow translation to handle the decref.

I'll need to think about what the right approach will be.

## Remediation

We're likely to deploy upgrade-14 without a fix for this problem, which means mainnet will wind up with about 730 promise records.

Later, we'll want to figure out a remediation path. This will need some sort of mark-and-sweep analysis of kernel promises, locating the reference sources for every kpid, counting them, comparing against the recorded `refCount`, adjusting the `refCount` when wrong, and deleting the entry when `refCount === 0`. The references can come from c-list entries (which are easy to find), but also from enqueued messages. So we'd have to scan the run-queue as well as every unresolved promise's `kp$NN.queue.$MM` entries.

We currently have about 800 promises on mainnet, none of which have any queued messages. Examining all promises requires enumerating all `kpNN*` keys in the kvStore, of which there about 4000. So remediation will requires 4000 kvStore reads, plus 800 c-list checks for each of our 94-ish vats, plus a run-queue scan (probably empty), making about 79k kvStore reads. I'm guessing that might take more than a second but less than a minute to run.

We could probably pull this off at the start of an upgrade, but I'm not sure we'd want to do it every time. So maybe we add a `controller.fixPromiseRefcounts()` call and invoke it once, in some upgrade event after we fix the main bug.

### PR DESCRIPTION
**Pull request by warner**
The kernel is responsible for "disconnecting" (rejecting) promises
decided by a vat being upgraded, because Promise settlement functions
(resolve/reject) are ephemeral, so they are lost during the upgrade, so
the new incarnation will have no way to ever settle them.

When the vat resolves a promise with syscall.resolve(), that vat's
c-list entry is removed by the syscall handler. But when the kernel did
the rejection, the c-list entry was left in place, causing the promise
to be pinned forever.

This changes the kernel to remove the c-list entry as well, except in
the case that the vat is also subscribed to its own promise (which
happens when a PromiseWatcher is used on a locally-decided promise:
unusual but we needed to tolerate that case). Self-subscribed promises
are left in the c-list, because the subsequent dispatch.notify() will
finish the job and remove the entry.

We also add remediation code, run during `upgradeSwingset`, and bump the
state version from 2 to 3. Remediation looks for all settled promises
that are still present in vat c-lists, and schedules dispatch.notify
deliveries to allow the usual cleanup code to remove the entries,
decrement the refcounts, and GC anything thus freed. This results in
harmless deliveries that will be ignored by the vat's new incarnation.

fixes #9039

### CODE REVIEW

File: packages/SwingSet/src/kernel/kernel.js [hunk 1]
```diff
@@ -597,7 +597,7 @@ export default function buildKernel(
     const p = kernelKeeper.getKernelPromise(kpid);
     kernelKeeper.incStat('dispatchNotify');
     const vatKeeper = kernelKeeper.provideVatKeeper(vatID);
-    p.state !== 'unresolved' || Fail`spurious notification ${kpid}`;
+    assert(p.state !== 'unresolved', `spurious notification ${kpid}`);
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js]: FYI, if this was in a hot path, this would be a perf regression. It's unfortunate that TS is not capable of doing flow analysis in this case. The faster but more verbose alternative is to do

```suggestion
    if (p.state !== 'unresolved') {
      throw Fail`spurious notification ${kpid}`;
    }
```

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 2]
```diff
@@ -791,45 +792,47 @@ export default function makeKernelKeeper(
...
   function getKernelPromise(kernelSlot) {
     insistKernelType('promise', kernelSlot);
-    const p = { state: getRequired(`${kernelSlot}.state`) };
-    switch (p.state) {
+    const state = getRequired(`${kernelSlot}.state`);
+    const refCount = Number(kvStore.get(`${kernelSlot}.refCount`));
+    switch (state) {
       case undefined: {
         throw Fail`unknown kernelPromise '${kernelSlot}'`;
       }
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: Out of curiosity, how can this be undefined with `getRequired` ? If you want a more explicit message, why not do 

```js
const state = kvStore.get(`${kernelSlot}.state`);
```

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 3]
```diff
@@ -791,45 +792,47 @@ export default function makeKernelKeeper(
...
       case 'unresolved': {
-        p.refCount = Number(kvStore.get(`${kernelSlot}.refCount`));
-        p.decider = kvStore.get(`${kernelSlot}.decider`);
-        if (p.decider === '') {
-          p.decider = undefined;
+        let decider = kvStore.get(`${kernelSlot}.decider`);
+        if (decider === '') {
+          decider = undefined;
         }
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]:
```suggestion
        const decider = kvStore.get(`${kernelSlot}.decider`) || undefined;
```

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 4]
```diff
@@ -791,45 +792,47 @@ export default function makeKernelKeeper(
...
-        p.policy = kvStore.get(`${kernelSlot}.policy`) || 'ignore';
-        // @ts-expect-error get() may fail
-        p.subscribers = commaSplit(kvStore.get(`${kernelSlot}.subscribers`));
-        p.queue = Array.from(
+        const policy = kvStore.get(`${kernelSlot}.policy`) || 'ignore';
+        const subscribers = commaSplit(
+          getRequired(`${kernelSlot}.subscribers`),
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: Is subscribers guaranteed to be defined? Any hurt to support it not being?

```suggestion
          kvStore.get(`${kernelSlot}.subscribers`) || '',
```

File: packages/SwingSet/src/kernel/kernel.js [hunk 5]
```diff
@@ -289,7 +289,10 @@ export default function buildKernel(
 
       // Reject all promises decided by the vat, making sure to capture the list
       // of kpids before that data is deleted.
-      const deadPromises = [...kernelKeeper.enumeratePromisesByDecider(vatID)];
+      const deadPromises = [];
+      for (const [kpid, _p] of kernelKeeper.enumeratePromisesByDecider(vatID)) {
+        deadPromises.push(kpid);
+      }
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js]: The new iterator helpers can't come soon enough. It'd be 

```js
      const deadPromises = kernelKeeper.enumeratePromisesByDecider(vatID).map(([kpid, _p]) => kpid).toArray()
```

But since you don't really need to iterate more than once, why not:

```suggestion
      const deadPromiseEntries = kernelKeeper.enumeratePromisesByDecider(vatID);
```

and later

```js
      for (const [kpid, _p] of deadPromiseEntries) {
```

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 6]
```diff
@@ -213,6 +213,77 @@ export const getAllDynamicVats = getRequired => {
...
+ * @param { import('@agoric/swing-store').SwingStoreKernelStorage.kvStore } kvStore
+ * @param {string} kref  The kernel slot whose refcount is to be incremented.
+ * @param {string?} tag  Debugging note with rough source of the reference.
+ * @param {{ isExport?: boolean, onlyRecognizable?: boolean }} options
+ * 'isExport' means the reference comes from a clist export, which counts
+ * for promises but not objects. 'onlyRecognizable' means the reference
+ * provides only recognition, not reachability
+ */
+export const incrementReferenceCount = (
+  getRequired,
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:262]: I'm tempted to say we should have a top level `const getRequired = (kvStore, key) => { ... }` instead.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 7]
```diff
@@ -213,6 +213,77 @@ export const getAllDynamicVats = getRequired => {
...
+
+/**
+ * Increment the reference count associated with some kernel object.
+ *
+ * We track references to promises and objects, but not devices. Promises
+ * have only a "reachable" count, whereas objects track both "reachable"
+ * and "recognizable" counts.
+ *
+ * @param { string => string} getRequired
+ * @param { import('@agoric/swing-store').SwingStoreKernelStorage.kvStore } kvStore
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: That type looks sketchy. Wouldn't it just be `import('@agoric/swing-store').KVStore` ?

And as you've seen in the next commit, we now prefer `@import` JSDoc at the top :)

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 8]
```diff
@@ -213,6 +213,77 @@ export const getAllDynamicVats = getRequired => {
...
+    // kdebug(`++ ${kref}  ${tag} ${reachable},${recognizable}`);
+    setObjectReferenceCount(kvStore, kref, { reachable, recognizable });
+  }
+};
+
+export const addToQueue = (queue, item, getRequired, kvStore, incStat) => {
+  const [head, tail] = JSON.parse(getRequired(`${queue}`));
+  kvStore.set(`${queue}.${tail}`, JSON.stringify(item));
+  kvStore.set(`${queue}`, JSON.stringify([head, tail + 1]));
+  incStat(`${queue}Length`);
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: ~I'm tempted to say the `incStat` call should stay in the `enqueue` wrapper?~

Looks like the actual usage did create a stats object. I'm not a fan of the boundary leak here.

File: packages/SwingSet/src/kernel/kernel.js [hunk 9]
```diff
@@ -1000,9 +1000,30 @@ export default function buildKernel(
...
+      const selfSubscribed =
+        p.state === 'unresolved' && p.subscribers.includes(vatID);
+      if (isEphemeral) {
+        resolveToError(kpid, disconnectionCapData, vatID);
+        if (!selfSubscribed) {
+          // If the vat was subscribed to its own promise, the
+          // resolveToError will enqueue a dispatch.notify, whose delivery
+          // will delete the c-list entry. If it is *not* subscribed, we
+          // should delete the c-list entry now, because nobody else will.
+          vatKeeper.deleteCListEntriesForKernelSlots([kpid]);
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js:1028]: Would it make sense to accumulate the list of kpid to delete, and do it in a single call after the iteration?

File: packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js [hunk 10]
```diff
@@ -78,8 +78,19 @@ export const buildRootObject = () => {
...
+      const p3 = E(ulrikRoot).getWatchedDecidedPromise();
+
+      // Create our own promises that capture the rejection data,
+      // because the originals will be GCed when the rejection
+      // notifications finish delivery. Promise.all() returns a new
+      // promise, which either fulfills to an array of fulfillment
+      // values, or rejects with the first rejection reason, so for
+      // p1/p2 (which are supposed to reject), it effectively wraps
+      // the promise in a new one that behaves the same way.
+      const p1w = Promise.all([p1]);
```
Comment (mhofman) [inline packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js]: The long `Promise.all` explaination makes me think there are better ways. Some that come to mind.

```js
      const p1w = new Promise(resolve => { resolve(p1); });
```

Or at the cost of an extra tick.
```js
      const p1w = Promise.resolve().then(() => p1);
```

File: packages/SwingSet/src/controller/upgradeSwingset.js [hunk 11]
```diff
@@ -204,6 +207,154 @@ export const upgradeSwingset = kernelStorage => {
...
+    for (let p = runHead; p < runTail; p += 1) {
+      const rq = JSON.parse(getRequired(`runQueue.${p}`));
+      if (rq.type === 'notify') {
+        const { vatID, kpid } = rq;
+        assert(vatID);
+        assert(kpid);
+        if (!notifies.has(kpid)) {
+          notifies.set(kpid, []);
+        }
+        notifies.get(kpid).push(vatID);
```
Comment (mhofman) [inline packages/SwingSet/src/controller/upgradeSwingset.js]: We can do this with only 1 lookups in `notifies`:

```suggestion
        let vats = notifies.get(kpid);
        if (!vats) {
          vats = [];
          notifies.set(kpid, vats);
        }
        vats.push(vatID);
```

File: packages/SwingSet/src/controller/upgradeSwingset.js [hunk 12]
```diff
@@ -204,6 +207,154 @@ export const upgradeSwingset = kernelStorage => {
...
+    const isSettled = kpid => {
+      if (settledKPIDs.has(kpid)) {
+        return true;
+      }
+      if (nonSettledKPIDs.has(kpid)) {
+        return false;
+      }
+      const state = kvStore.get(`${kpid}.state`);
+      // missing state means the kpid is deleted somehow, shouldn't happen
+      assert(state, `${kpid}.state is missing`);
```
Comment (mhofman) [inline packages/SwingSet/src/controller/upgradeSwingset.js]: This one is in a pretty hot path, let's write it as a `Fail`. Not like we have strong typing here anyway.

```suggestion
      state || Fail`${kpid}.state is missing`;
```

File: packages/SwingSet/src/controller/upgradeSwingset.js [hunk 13]
```diff
@@ -204,6 +207,154 @@ export const upgradeSwingset = kernelStorage => {
...
+    // have deleted the promise records (if nothing else was
+    // referencing the promise, like arguments in messages enqueued to
+    // unresolved promises, or something transient on the
+    // run-queue). Deleting those promise records might have decreffed
+    // krefs in the rejection data (although in general 9039 rejects
+    // those promises with non-slot-bearing DisconnectionObjects).
+    //
+    // To avoid duplicating a lot of kernel code inside this upgrade
+    // handler, we do the simplest possible thing: enqueue a notify to
+    // the upgraded vat for all these leftover promises. The new vat
```
Comment (mhofman) [inline packages/SwingSet/src/controller/upgradeSwingset.js:305]: I am not the biggest fan of the kernel adding things to the run queue arbitrarily like this.

At upgrade time we may actually be in the middle of a run, and the reactions to these notifies will become part of that run. I would much prefer if this became a separate "upgrade run". This case is actually a good candidate for it. We can run the remediation anytime (as long as the targeted vats have not terminated), as the list of kpid is not going to grow anymore.

Maybe `upgradeSwingset` can return a closure that performs either the walk + enqueuing, or just the enqueuing from a walk that was already done. Or an alternative would be to return a description of what should be done (the list of queue items to add), and require the host to call a controller function that understands what to do. We already have a `queueTo` functions on the controller, so it's not a stretch to add a `controller.queueUpgradeAction(actionReturnedByUpgrade)`.

In either case, the host would perform this action when the previous run has completed, and then perform a new run just for this. It doesn't even have to be a "must run this block" with an unlimited policy, although that may still be preferable.

I think this would allow us to limit the amount of boundary piercing we have to do (no need to get stats here, or any functions that mutate the state kept by the keeper). It also sets up a framework for injecting actions at upgrade time, which have possibly not been self discovered but instead required offline processing (collection of some virtual data cycles comes to mind)

**Review by mhofman — COMMENTED** [review]
I have not yet reviewed the test for the mitigation.

I am not a fan of the revert to using `assert`. The lack of control flow type inference from TS is unfortunate, but it's not always clear that the perf impact is benign.

Besides how the scheduling of the notify is done, it's pretty much all nits. I would like to discuss alternative integrations of the upgrade action.

Another nit not captured in code comments: `refactor:` is an accepted conventional commit prefix :)

File: packages/SwingSet/src/kernel/kernel.js (hunk 5 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js]: interesting.. I try to avoid keeping iterators around for very long, but that might be leftover scar tissue from when kernelKeeper's iterators mapped directly to LMDB or SQLite iterators, which didn't work well if you wanted to make other DB transactions while the iterator was held open. But `enumeratePromisesByDecider` uses `enumeratePrefixedKeys` which does a separate `kvStore.getNextKey()` for each loop, so there are no txns being held open.

The only reason I can think to not use your pattern is memory pressure: by dropping everything but the `kpid` early, we shrink the active memory footprint earlier (the peak is just as high, but it is narrower). If there is significant memory usage between the array-ification and the subsequent loop, then pruning early could help avoid extra allocation.

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 13 above)
Comment (warner) [reply packages/SwingSet/src/controller/upgradeSwingset.js:305]: @mhofman and I walked through the code. The benefits of his scheme is that the post-chain-halting-upgrade execution slogs will show three distinct phases: catch-up, then swingset upgrade actions (e.g. injected `dispatch.notify` from the promise remediations), then finally core-eval upgrade proposals (like installing bundles and upgrading vats). Without this scheme, the order would be: initial catch-up cranks (anything that was already in the run-queue when the chain halted), swingset-upgrade/remediation cranks, then later catch-up cranks (anything triggered by the initial catch-up cranks), then core-eval upgrade proposals.

The drawbacks of this scheme are the complexity of additional controller APIs, an extra operational burden on host-app authors (swingset no longer upgrades itself by default, it needs help from the caller), and changes to cosmic-swingset to drive it (which is our least-well tested package, so I try to minimize changes to it).

I agreed to pursue his approach. The details:

On the kernel side:

* `upgradeSwingset()` returns an "upgrade actions list", which is opaque (to the host app) and basically contains a list of run-queue event records
  * upgradeSwingset must increment the refcounts for any krefs in those records, just as it would if it pushed them onto the run-queue directly
* `controller.addEvents(upgradeActionsList)` will take that list and add it to the run-queue. It nominally increfs (as the items are pushed onto the run-queue) and decrefs (as the `upgradeActionsList` item is deleted), but it's a wash, so we won't actually modify refcounts in the function, we'll just have a comment explaining why we don't have to.
* The host app is now responsible for conveying the actions from `upgradeSwingset` to the controller. These actions must be injected during the first run after upgrade (i.e. the host app must not `hostStorage.commit()` before it calls `c.addEvents`). If they fail to do so, the kernel state will be corrupted. (I lament this additional burden)

On the cosmic-swingset side:

* we'll introduce a new `ActionType.INJECT_UPGRADE_ACTIONS`
* inside launch-chain.js `buildSwingset()`, the call to `upgradeSwingset` will grab the returned upgrade actions list and return it next to `coreProposals` and `controller`
* in `launch() > doBlockingSend() -> case ActionType.AG_COSMOS_INIT`, when we build `coreProposals`, we'll also look at the upgrade actions list, and if it is not empty, we'll build an `INJECT_UPGRADE_ACTIONS` around it and push that onto `runThisBlock`, before we call `doCoreProposals`
  * this induces a dependency: if SwingSet is upgraded (such that `upgradeSwingSet()` returns actions that need to be injected), but the golang side doesn't realize that we're performing a chain-halting upgrade (such that it fails to send an `AG_COSMOS_INIT`), then we'll get corrupted kernel state
  * it would be nice to catch this error case with an assertion, rather than allowing the kernel upgrade actions to be silently dropped, but I think that requires reacting to the *lack* of an `AG_COSMOS_INIT` event, which sounds difficult
  
Now, on normal reboots, `upgradeSwingset()` returns nothing (maybe `undefined`, maybe `[]`, we'd need to choose), and no `AG_COSMOS_INIT` is pushed, so the `runKernel()` code does it's normal budget-limited catchup and action-queue servicing.

But after a chain-halting upgrade, `upgradeSwingset()` might return a non-empty list (if the chain software upgrade included a kernel upgrade, and if that kernel upgrade included a state upgrade, and if that state upgrade produced events that needed injection). *And*, the golang side will emit an `AG_COSMOS_INIT` event at the beginning of the first post-upgrade block. If so, the `AG_COSMOS_INIT` handler will notice the non-empty swingset upgrade action list, and an `INJECT_UPGRADE_ACTIONS` event onto `runThisBlock` before it pushes anything else (like core-proposals) associated with the upgrade.

Then, when we reach `END_BLOCK`, the catch-up run will use `neverStop` (because `runThisBlock` is empty), and then it will service `runThisBlock`, which will start with the swingset injections. These will run to completion before processing any of the core-proposals, because they appear in a separate action than the `ActionType.CORE_EVAL` events that might follow.

The empty/non-empty state of `runThisBlock` (for each block) is a part of consensus, because it affects the runPolicy budget for the catchup run. So it is important that non-upgrade reboots do not spuriously populate it. This will be doubly ensured:
* only the `AG_COSMOS_INIT` handler can push onto `runThisBlock`
* normal reboots should not be changing kernel code, so even though `upgradeSwingset` is called on every reboot, normal reboots should not cause it to actually do an upgrade, so those calls will never return any actions to be injected.

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 12 above)
Comment (warner) [reply packages/SwingSet/src/controller/upgradeSwingset.js:272]:
```
node $ yarn lint:types
yarn run v1.22.19
$ tsc
src/controller/upgradeSwingset.js:272:16 - error TS2304: Cannot find name 'Fail'.

272       state || Fail`${kpid}.state is missing`;
                   ~~~~


Found 1 error in src/controller/upgradeSwingset.js:272
```

File: packages/SwingSet/src/kernel/kernel.js (hunk 1 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js]: It's `if (p.state === 'unresolved')`, but I'll do it.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 2 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: good point, if the promise were missing, we'd get a more-opaque error inside `getRequired`. I'm not sure why that's there, but I'll remove it.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 4 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: if `state` is `unresolved`, then `.subscribers` is supposed to be defined, and it would be some sort of bug if it were missing, but yeah in the spirit of being maximally tolerant (or enabling some future optimization where we omit the entry until there is at least one subscriber, which isn't a bad idea TBH) it'd be fine to do it that way.. I'll make the change

File: packages/SwingSet/src/kernel/kernel.js (hunk 5 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js]: actually yeah, I think I'll leave it as-is, both because of the nominal memory thing, and because in the long run I'd like to have a flavor of `enumeratePromisesByDecider` which only returns the kpids and doesn't spend any time (or DB reads) populating the rest of the data, and in that form, `deadPromises` will strictly be kpids.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 6 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:262]: yeah, I think I tried both factorings and landed on this one, neither was great, both helpers still need `kvStore` for the `set()` authority

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 7 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: I think that's an old commit, the current line is:
```js
 * @param { SwingStoreKernelStorage['kvStore'] } kvStore
```

which refers to an earlier:
```
 * @import {SwingStoreKernelStorage} from '@agoric/swing-store';
```

does that seem like the right approach?

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 8 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: Well, `incStat` closes over a stats object, and its contents need to be written back to the DB before upgrade is complete, so it's awkward either way. Given the original goal of not doing a DB read+write for every stats delta, I couldn't find a better approach.

File: packages/SwingSet/src/kernel/kernel.js (hunk 9 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js:1028]: I didn't want to risk building a huge list in RAM. The `deleteCListEntriesForKernelSlots()` API takes a list because `syscall.retireExports` is allowed to retire more than one vref at a time, but vat workers are expected (er, ought to be expected) to limit themselves to a reasonable number. The kernel-side vat data structures have no such limits, and we should be prepared for a million promises to get rejected or deleted here.

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 13 above)
Comment (mhofman) [reply packages/SwingSet/src/controller/upgradeSwingset.js:305]: > * it fails to send an `AG_COSMOS_INIT`), then we'll get corrupted kernel state

There is always an init event (it happens for every restart). The event has flags indicating whether it's a consensus restart (bootstrap & upgrade info).

Like for core proposals, you can assert that swingset upgrade actions are only allowed on consensus restarts.

File: packages/SwingSet/src/kernel/kernel.js (hunk 5 above)
Comment (mhofman) [reply packages/SwingSet/src/kernel/kernel.js]: There actually should a smaller memory pressure with the iterators, since only the current entry is ever allocated, where for the array we temporarily have to allocate all entries.

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 11 above)
Comment (warner) [reply packages/SwingSet/src/controller/upgradeSwingset.js]: alright, I was leaning towards readability, and Maps are cheap, but I'll do it

File: packages/SwingSet/src/kernel/kernel.js (hunk 5 above)
Comment (mhofman) [reply packages/SwingSet/src/kernel/kernel.js]: `enumeratePromisesByDecider` can be a generator function that iterates the entries and only yields the kpid. Or we can use iterator helpers' map when that is more broadly supported

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 7 above)
Comment (mhofman) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: It was an old commit but the idea still stands. We should use `KVStore` directly instead of `SwingStoreKernelStorage`

File: packages/SwingSet/src/kernel/kernel.js (hunk 5 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js]: > There actually should a smaller memory pressure with the iterators, since only the current entry is ever allocated, where for the array we temporarily have to allocate all entries.

Oh that is an excellent point. Ok I think I remember the reason for the original order: the `markVatAsTerminated()` call used to be `cleanupAfterTerminatedVat()`, which deleted all the kvStore records, so we needed the list of dead promise kpids *before* everything got deleted. Now that we're merely marking it as terminated and not (yet) actually deleting everything, we can afford to fetch/iterate through the list at the end of that clause.

I'll rearrange it.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 7 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: ok, I've changed it to ` * @param { import('@agoric/swing-store').KVStore } kvStore`

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 13 above)
Comment (gibson042) [reply packages/SwingSet/src/controller/upgradeSwingset.js:305]: I very much agree with the original comment, and support the proposed plan.

Comment (gibson042) [reply packages/SwingSet/src/controller/upgradeSwingset.js:305]: ...and further considering that we must not lose these remediation events, _even if there is enough leftover work to fill more than one block_, I prefer a strategy in which their presence is communicated to the controller so that it can insist that the very next `run()` sees them first and gets all the way through (i.e., hosts are free to control exactly how they are injected but are not free to ask for other work first—if they care about not interrupting leftover, then they must delay the upgrade until there isn't any).

This does raise the question of what to do with followup actions from the initial events, for which my preference would be to treat as normal, effectively being born as leftover work (while reserving the option for a future change that instead treats those as part of the queue-jumping remediation).

File: packages/SwingSet/src/controller/upgradeSwingset.js [hunk 14]
```diff
@@ -204,6 +208,156 @@ export const upgradeSwingset = kernelStorage => {
...
+      if (rq.type === 'notify') {
+        const { vatID, kpid } = rq;
+        assert(vatID);
+        assert(kpid);
+        if (!notifies.has(kpid)) {
+          notifies.set(kpid, []);
+        }
+        notifies.get(kpid).push(vatID);
+      }
+    }
```
Comment (gibson042) [inline packages/SwingSet/src/controller/upgradeSwingset.js]: Better: extract `queueLength`/`dumpQueue` from kernelKeeper.js like you are already doing with `enqueue` → `addToQueue`.
```suggestion
    for (const queueName of ['runQueue', 'acceptanceQueue']) {
      for (const { type, vatID, kpid } of dumpQueue(queueName)) {
        if (type === 'notify') {
          assert(vatID);
          assert(kpid);
          if (!notifies.has(kpid)) {
            notifies.set(kpid, []);
          }
          notifies.get(kpid).push(vatID);
        }
      }
    }
```

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 13 above)
Comment (mhofman) [reply packages/SwingSet/src/controller/upgradeSwingset.js:305]: In this case, the swing-store upgrade can be performed (gather the list of promises to notify rejections), then the controller built and the left over work executed, then the injected events from the upgrade can be run without comingling. This is possible in this case because the notify events remain valid (the state of the promise doesn't change further). Since we already do not remove events from the run queue when the vat terminates, even that edge case is handled by [simply dropping the notify if that happens](https://github.com/Agoric/agoric-sdk/blob/3007c001ee490c847987bc61d22acf9689611340/packages/SwingSet/src/kernel/kernel.js#L591-L594).

I think all this remains true in the general case of injected events. As long as injected events have a valid refcount keeping their slots alive, the deliveries they represent are akin to being held in a separate queue. I expect a similar pattern could be used to inject retire exports to trigger collection of cycles.

File: packages/SwingSet/src/controller/upgradeSwingset.js [hunk 15]
```diff
@@ -204,6 +208,156 @@ export const upgradeSwingset = kernelStorage => {
...
+      const state = kvStore.get(`${kpid}.state`);
+      // missing state means the kpid is deleted somehow, shouldn't happen
+      state || Fail`${kpid}.state is missing`;
+      if (state === 'unresolved') {
+        nonSettledKPIDs.add(kpid);
+        return false;
+      }
+      settledKPIDs.add(kpid);
+      return true;
+    };
```
Comment (gibson042) [inline packages/SwingSet/src/controller/upgradeSwingset.js]:
```suggestion
    const settlementStatuses = new Map();
    const isSettled = kpid => {
      if (settlementStatuses.has(kpid)) {
        return settlementStatuses.get(kpid);
      }
      const state = kvStore.get(`${kpid}.state`);
      // missing state means the kpid is deleted somehow, shouldn't happen
      state || Fail`${kpid}.state is missing`;
      const result = state !== 'unresolved';
      settlementStatuses.set(kpid, result);
      return result;
    };
```
or if you're willing to extend packages/internal,
```suggestion
    const isSettled = memoizeUnary(kpid => {
      const state = kvStore.get(`${kpid}.state`);
      // missing state means the kpid is deleted somehow, shouldn't happen
      state || Fail`${kpid}.state is missing`;
      return state !== 'unresolved';
    });
```

File: packages/SwingSet/src/controller/upgradeSwingset.js [hunk 16]
```diff
@@ -204,6 +208,156 @@ export const upgradeSwingset = kernelStorage => {
...
+        const kpid = key.slice(len);
+        if (isSettled(kpid)) {
+          const n = notifies.get(kpid);
+          if (!n || !n.includes(vatID)) {
+            // there is no pending notify
+            buggyKPIDs.push([kpid, vatID]);
+          }
+        }
+      }
+    }
```
Comment (gibson042) [inline packages/SwingSet/src/controller/upgradeSwingset.js:289]: echoing https://github.com/Agoric/agoric-sdk/pull/10268#discussion_r1816549957
```suggestion
    for (const vatID of allVatIDs) {
      const ckpPrefix = `${vatID}.c.kp`;
      for (const { suffix } of enumeratePrefixedKeys(kvStore, ckpPrefix)) {
        const kpid = `kp${suffix}`;
        if (isSettled(kpid)) {
          const vatsPendingNotify = notifies.get(kpid) || [];
          if (!vatsPendingNotify.includes(vatID)) {
            // there is no pending notify
            buggyKPIDs.push([kpid, vatID]);
          }
        }
      }
    }
```

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 17]
```diff
@@ -212,6 +217,77 @@ export const getAllDynamicVats = getRequired => {
...
+  kvStore,
+  kref,
+  tag,
+  options = {},
+) => {
+  const { isExport = false, onlyRecognizable = false } = options;
+  kref || Fail`incrementRefCount called with empty kref, tag=${tag}`;
+  const { type } = parseKernelSlot(kref);
+  if (type === 'promise') {
+    const refCount = Nat(BigInt(getRequired(`${kref}.refCount`))) + 1n;
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: All the other sites that read a refCount key parse as number without bounds checking; I don't think this one should be special.
```suggestion
    const refCount = Number(getRequired(`${kref}.refCount`)) + 1;
```

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 18]
```diff
@@ -791,45 +846,41 @@ export default function makeKernelKeeper(
...
       case 'fulfilled':
       case 'rejected': {
-        p.refCount = Number(kvStore.get(`${kernelSlot}.refCount`));
-        p.data = {
-          body: kvStore.get(`${kernelSlot}.data.body`),
-          // @ts-expect-error get() may fail
-          slots: commaSplit(kvStore.get(`${kernelSlot}.data.slots`)),
+        const data = {
+          body: getRequired(`${kernelSlot}.data.body`),
+          slots: commaSplit(getRequired(`${kernelSlot}.data.slots`)),
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:873]: Is the change from `get` to `getRequired` for these body and slots fetches intentional?

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 19]
```diff
@@ -838,7 +889,7 @@ export default function makeKernelKeeper(
       insistVatID(expectedDecider);
     }
     const p = getKernelPromise(kpid);
-    p.state === 'unresolved' || Fail`${kpid} was already resolved`;
+    assert.equal(p.state, 'unresolved', `${kpid} was already resolved`);
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: These changes in particular (```x === y || Fail`…`;``` → ```assert.equal(x, y, `…`);```) don't seem like improvements to me.

File: packages/SwingSet/src/kernel/vatTranslator.js [hunk 20]
```diff
@@ -59,7 +60,11 @@ function makeTranslateKernelDeliveryToVatDelivery(vatID, kernelKeeper) {
     if (msg.result) {
       insistKernelType('promise', msg.result);
       const p = kernelKeeper.getKernelPromise(msg.result);
-      p.state === 'unresolved' || Fail`result ${msg.result} already resolved`;
+      assert.equal(
+        p.state,
+        'unresolved',
+        `result ${msg.result} already resolved`,
+      );
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/vatTranslator.js]: Isn't `msg.result` potentially expensive to serialize? The code being replaced handles that better.
```suggestion
      p.state === 'unresolved' || Fail`result ${msg.result} already resolved`;
```

File: packages/SwingSet/src/kernel/vatTranslator.js [hunk 21]
```diff
@@ -318,8 +323,11 @@ function makeTranslateVatSyscallToKernelSyscall(vatID, kernelKeeper) {
       // In the case of non-pipelining vats these checks are redundant since
       // we're guaranteed to have a promise newly allocated by the vat.
       const p = kernelKeeper.getKernelPromise(result);
-      p.state === 'unresolved' ||
-        Fail`send() result ${result} is already resolved`;
+      assert.equal(
+        p.state,
+        'unresolved',
+        `send() result ${result} is already resolved`,
+      );
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/vatTranslator.js]: Likewise here.

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 15 above)
Comment (mhofman) [reply packages/SwingSet/src/controller/upgradeSwingset.js]: Oh I didn't know we had a memoize in internal now.

Comment (gibson042) [reply packages/SwingSet/src/controller/upgradeSwingset.js]: We don't, it would need to crib from either [notifier](https://github.com/Agoric/agoric-sdk/blob/3007c001ee490c847987bc61d22acf9689611340/packages/notifier/src/publish-kit.js#L66-L84) or [Endo](https://github.com/endojs/endo/blob/4ca4028bb67ba9198060f30a7e5bbff21e8fa27f/packages/memoize/src/memoize.js#L16) and then generalize to support non-weak keys (e.g., as either different function or by supporting an optional `makeCache` parameter in addition to the input function).

Comment (mhofman) [reply packages/SwingSet/src/controller/upgradeSwingset.js]: Well this is actually more of a "makeOnce" store/zone pattern than a memoization, where we can just throw away the store after usage.

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 13 above)
Comment (warner) [reply packages/SwingSet/src/controller/upgradeSwingset.js:305]: Ok https://github.com/Agoric/agoric-sdk/pull/10337 is a secondary PR to this branch to address this. `upgradeSwingset()` is changed to record an internal list of the messages (notifies) that need to be injected, the new `controller.injectQueuedUpgradeEvents()` will do that, without revealing the messages to the caller. The host-app is newly responsible for calling that function after `upgradeSwingset()` (at least if it returns `modified === true`), and ideally before the next `commit()` (to avoid risking forgetting to do it), and before a `run()` (to get the work done promptly instead of leaving it for a future block). The cosmic-swingset code is changed to call it after a full cleanup/leftover run, but before any coreProposals, by adding a new `ActionType.KERNEL_UPGRADE_EVENTS` to the `runThisBlock` queue, but only when cosmos tells us that we're resuming from a chain-halting software upgrade.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 18 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:873]: half was to remove the TSC override, half was because if we're in that clause, all those keys are supposed to be present

File: packages/SwingSet/src/kernel/vatTranslator.js (hunk 20 above)
Comment (warner) [reply packages/SwingSet/src/kernel/vatTranslator.js]: In theory, yes, but each time I try to use that pattern, I spend an hour fighting with TSC. In this case, it breaks the assertion on the very next line, that wants to look at `p.decider`, which only exists for unresolved promises:

```
$ tsc
src/kernel/vatTranslator.js:64:10 - error TS2339: Property 'decider' does not exist on type 'PromiseRecord'.
  Property 'decider' does not exist on type 'SettledPromiseRecord'.

64       !p.decider || Fail`result ${msg.result} already has decider ${p.decider}`;
            ~~~~~~~

src/kernel/vatTranslator.js:64:71 - error TS2339: Property 'decider' does not exist on type 'PromiseRecord'.
  Property 'decider' does not exist on type 'SettledPromiseRecord'.

64       !p.decider || Fail`result ${msg.result} already has decider ${p.decider}`;
                                                                         ~~~~~~~
```

I know this is probably TSC not being clever enough to realize that a previous ersatz assertion pattern imposes a constraint on the type, which should be enough to satisfy a following check. But *I'm* not clever enough to trick TSC into recognizing the right thing without using `assert()`, which is more readable anyways.

(this PR turns on types where there weren't any before, so we're monotonically improving the typèdness of this file, but that's not the reason for the PR, so I'm disinclined to spend a lot of time on it)

If you can show me the trick to make it happy, I'll apply it.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 18 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:873]: actually I think it was entirely to get TSC to stop complaining

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 15 above)
Comment (warner) [reply packages/SwingSet/src/controller/upgradeSwingset.js]: I like the Map-based cache, I'll do that. I don't want to modify other packages in this PR if I can avoid it.

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 16 above)
Comment (warner) [reply packages/SwingSet/src/controller/upgradeSwingset.js:289]: I'd like to leave that improvement for a later PR. I'll file an issue.

Comment (warner) [reply packages/SwingSet/src/controller/upgradeSwingset.js:289]: #10340

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 14 above)
Comment (warner) [reply packages/SwingSet/src/controller/upgradeSwingset.js]: done

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 19 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]:
```
    if (p.state !== 'unresolved') {
      throw Fail`${kpid} was already resolved`;
    }
```
worked, the `foo || Fail` form causes TSC complaints that I don't know how to work around.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 22]
```diff
@@ -212,6 +217,84 @@ export const getAllDynamicVats = getRequired => {
...
+    if (!onlyRecognizable) {
+      reachable += 1;
+    }
+    recognizable += 1;
+    // kdebug(`++ ${kref}  ${tag} ${reachable},${recognizable}`);
+    setObjectReferenceCount(kvStore, kref, { reachable, recognizable });
+  }
+};
+
+export const addToQueue = (queue, item, getRequired, kvStore, incStat) => {
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: Now that #10337 merged into this one, let's revert this `addToQueue` change. I really don't like the stats boundary piercing.

File: packages/SwingSet/src/kernel/vatTranslator.js (hunk 20 above)
Comment (warner) [reply packages/SwingSet/src/kernel/vatTranslator.js]:
```
      if (p.state !== 'unresolved') {
        throw Fail`result ${msg.result} already resolved`;
      }
```
seems to satisfy it.

File: packages/SwingSet/src/kernel/vatTranslator.js (hunk 21 above)
Comment (warner) [reply packages/SwingSet/src/kernel/vatTranslator.js]:
```
      if (p.state !== 'unresolved') {
        throw Fail`send() result ${result} is already resolved`;
      }
```
worked

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 6 above)
Comment (mhofman) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:262]: I'm confused, I'm suggesting only passing `kvStore` here, and refactoring `getRequired` to be pure and thus importable. Of course that's a fairly decent refactoring, so arguably out of scope at this point.

File: packages/SwingSet/test/upgrade-swingset.test.js [hunk 23]
```diff
@@ -62,6 +64,28 @@ test('kernel refuses to run with out-of-date DB - v1', async t => {
...
+  const { hostStorage, kernelStorage } = initSwingStore();
+  const { commit } = hostStorage;
+  const { kvStore } = kernelStorage;
+  const config = {};
+  await initializeSwingset(config, [], kernelStorage, t.context.data);
+  await commit();
+
+  // now doctor the initial state to make it look like the
+  // kernelkeeper v1 schema, by reducing the version key and removing
+  // vats.terminated
```
Comment (mhofman) [inline packages/SwingSet/test/upgrade-swingset.test.js]: This copy paste probably needs a tweak?

File: packages/SwingSet/test/upgrade-swingset.test.js [hunk 24]
```diff
@@ -229,3 +255,196 @@ test('upgrade non-reaping kernel state', async t => {
...
+
+  const data = { ...debug.dump().kvEntries };
+
+  // confirm that this state is too old for the kernel to use
+  await t.throwsAsync(() => makeSwingsetController(kernelStorage), {
+    message: /kernel DB is too old/,
+  });
+
+  // upgrade it
+  upgradeSwingset(kernelStorage);
```
Comment (mhofman) [inline packages/SwingSet/test/upgrade-swingset.test.js]: Check that `modified` is true ?

```suggestion
  const { modified } = upgradeSwingset(kernelStorage);
  t.true(modified);
```

File: packages/SwingSet/test/upgrade-swingset.test.js [hunk 25]
```diff
@@ -229,3 +255,196 @@ test('upgrade non-reaping kernel state', async t => {
...
+
+  // now we should be good to go
+  const controller = await makeSwingsetController(kernelStorage);
+  controller.injectQueuedUpgradeEvents();
```
Comment (mhofman) [inline packages/SwingSet/test/upgrade-swingset.test.js:415]: Should we check the intermediate state before events are injected?

**Review by mhofman — APPROVED** [review]
Overall LGTM. Feel free to merge once the revert of `addToQueue` and the test tweaks are done.

File: packages/SwingSet/test/upgrade-swingset.test.js (hunk 25 above)
Comment (warner) [reply packages/SwingSet/test/upgrade-swingset.test.js:415]: yep, I'll add that
