### PR TITLE
fix(swingset): fix transcript extract/replay tools

### LINKED ISSUE #5602: fix extract-transcript and replay-transcript tools
## What is the Problem Being Solved?

While investigating #5571 and #5587, I found that my tools for transcript extraction/replay had bitrotted. The task is to update them.

* transcript extraction needs to capture the whole syscall result, even for failed syscalls
* `gcEveryCrank` must be `true`, else GC is entirely disabled
* replay now uses the whole syscall result, even for failed syscalls
* the fake kernelKeeper needs `getEnableFakeDurable`
* the fake kernelSlog needs `delivery()` and `syscall()`
* we should track `deliveryNum` and try to align it with the original slog

## Security Considerations

None, this is for a diagnostic tool

## Test Plan

None, although if I'd put more energy into writing these tools in a form that could be tested, they probably wouldn't have bitrotted. I'm currently ok with that.

### PR DESCRIPTION
**Pull request by warner**
These had bitrotted:
* transcript now includes whole syscall result, even failures
* handle kerneldb bundleIDs
* new LMDB in swingstore
* gcEveryCrank=false else all GC is disabled (refs #5600)
* fake kernelKeeper/slogger needed new methods

The new code also attempts to track `deliveryNum`, to align it with
the original slog, but I'm not positive it is accurate.

closes #5602

### CODE REVIEW

File: packages/SwingSet/misc-tools/extract-transcript-from-kerneldb.js [hunk 1]
```diff
@@ -83,28 +99,43 @@ if (!vatName) {
...
+  // host application failed to commit the kvStore).
+  //
+  // The kvStore `${vatID}.t.startPosition` tells us the index of the
+  // first entry of the most recent version (the most recent
+  // `startVat`), while `${vatID}.t.endPosition` tells us the last
+  // committed entry.
+  //
+  // We ignore the heap snapshot ID, because we're deliberately
+  // replaying everything from `startVat`, and therefore we also
+  // ignore `snapshot.startPos` (the index of the first delivery
```
Comment (mhofman) [inline packages/SwingSet/misc-tools/extract-transcript-from-kerneldb.js:117]: These would be the ones stored in `local.v$NN.lastSnapshot`, right ?

**Review by mhofman — APPROVED** [review]
I'm not super familiar with the transcript logic yet, but this all looks fine to me.

File: packages/SwingSet/misc-tools/extract-transcript-from-kerneldb.js (hunk 1 above)
Comment (warner) [reply packages/SwingSet/misc-tools/extract-transcript-from-kerneldb.js:117]: yep
