### PR TITLE
test: add assertAmountsEqual() helper

### LINKED ISSUE #2442: add assertAmountsEqual() as a testHelper
## What is the Problem Being Solved?

`t.truthy(math.isEqual(amount1, amount2))` provides no helpful debugging info. The replacement I've been using: `t.deepEquals(amount1, amount2)` works for natMath amounts, but is a bad habit because it would fail for sets.

## Description of the Design

Add a helper (in zoeTestHelpers) that just compares the brands and values, and prints something helpful on failure.

Also, use the new helper in `assertPayoutAmount()`, etc., which currently use `t.deepEqual()`.

## Security Considerations

more reliable test results. 

## Test Plan

replace some uses in tests. Observe no change in test results.

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #2442

### CODE REVIEW

File: packages/zoe/test/unitTests/zcf/test-zcf.js [hunk 1]
```diff
@@ -302,7 +303,7 @@ test(`zcf.makeInvitation - no customProperties`, async t => {
   // https://github.com/Agoric/agoric-sdk/issues/1705
   // @ts-ignore
   const details = await E(zoe).getInvitationDetails(invitationP);
-  t.deepEqual(details, {
+  assertAmountsEqual(t, details, {
```
Comment (katelynsills) [inline packages/zoe/test/unitTests/zcf/test-zcf.js]: Oh no, this is passing but it shouldn't. This is a record, not an amount, so when `assertAmountsEqual` checks `.brand` and `.value` both are undefined, and undefined === undefined so this passes.

Comment (katelynsills) [reply packages/zoe/test/unitTests/zcf/test-zcf.js]: Also, even if these were amounts, we should ensure this fails because MathKind.SET wasn't passed in, so MathKind.NAT was used as the default, and that is wrong.

**Review by katelynsills — CHANGES_REQUESTED** [review]
Hmm, I think this effort might have to wait until after the amountMath refactoring. Here's why:

The function as written will pass even if the "amounts" aren't equal! See the `zcf.makeInvitation - no customProperties` test in `test-zcf.js` for an example of something passing when it shouldn't be. Even if we added more checks (such as `.brand !== undefined`) I think that would be the wrong solution. I think we actually want to use `amountMath.isEqual` to get the real, robust, and canonical answer on whether the two are equal. That will save us from any errors in trying to replicate it. (Of course, if we want to add other checks after it fails to provide a better error message we can. My worry is that we will have passes when we should have failures.)

But now, that means that we have to pass in an amountMath, which is difficult and annoying. I tried doing this, and I don't recommend it. However, after the amountMath refactoring, we won't need to. 

So, I think this PR is the best that we could do now, but I think it's risky and I would probably prefer to redo it after the amountMath refactoring.

File: packages/zoe/test/unitTests/zcf/test-zcf.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/zoe/test/unitTests/zcf/test-zcf.js]: I reverted this incorrect conversion fo `deepEqual()` to `assertAmountsEqual()`. I'll convert the PR to `draft` until we have a solution for AmountMaths.

blocked on: #2311

**Comment by katelynsills** [comment]
Hey @Chris-Hibbert, now that the new amountMath is in, we can revisit this!

File: packages/zoe/test/zoeTestHelpers.js [hunk 2]
```diff
@@ -3,6 +3,47 @@
...
+    case MathKind.STRING_SET:
+      valuesEqual = setMathHelpers.doIsEqual(amount.value, expected.value);
+      break;
+    case MathKind.SET:
+      valuesEqual = setMathHelpers.doIsEqual(amount.value, expected.value);
+      break;
+    default:
+      valuesEqual = false;
+  }
+
```
Comment (katelynsills) [inline packages/zoe/test/zoeTestHelpers.js]: Why are we doing this? `amountMath.isEqual(x, y)` will do everything we need to do.

**Review by katelynsills — CHANGES_REQUESTED** [review]
We should never have to pass a MathKind in to know whether two amounts are equal. We should change this API

File: packages/zoe/test/zoeTestHelpers.js (hunk 2 above)
Comment (Chris-Hibbert) [reply packages/zoe/test/zoeTestHelpers.js]: This gives more detailed error messages when there isn't a match. If that's not valuable, then we can switch all the tests to use `t.is(amountMath.isEqual(amount, expected, message))`.

Comment (Chris-Hibbert) [reply packages/zoe/test/zoeTestHelpers.js]: also, `amountMath.isEqual()` throws when the brands don't match, which is less helpful in a test.

Comment (katelynsills) [reply packages/zoe/test/zoeTestHelpers.js]: We can still have the detailed error messages without having to pass in the mathKind. Some options:

* Use `amountMath.isEqual(` directly. If we know the brands are the same and amountMath.isEqual is false, then we know the values are different and can use the appropriate error message.

* Use `getMathKind` to switch which helpers to use based on the value alone.

* Use `isSetValue` and `isNatValue` to switch which helpers to use based on the value alone.

Both of these don't need the mathKind to be passed in, so we should definitely remove that.

Comment (katelynsills) [reply packages/zoe/test/zoeTestHelpers.js]: > also, amountMath.isEqual() throws when the brands don't match, which is less helpful in a test.

An easy fix for this is only use `amountMath.isEqual` if you've already checked that the brands match

File: packages/zoe/test/zoeTestHelpers.js [hunk 3]
```diff
@@ -3,6 +3,47 @@
...
+import setMathHelpers from '@agoric/ertp/src/mathHelpers/setMathHelpers';
+import { MathKind, amountMath } from '@agoric/ertp';
+
+import { q } from '@agoric/assert';
+
+export const assertAmountsEqual = (
+  t,
+  amount,
+  expected,
+  mathKind = MathKind.NAT,
```
[the remark this answers is not in the document]
Comment (Chris-Hibbert) [reply packages/zoe/test/zoeTestHelpers.js]: done

File: packages/zoe/test/zoeTestHelpers.js (hunk 2 above)
Comment (Chris-Hibbert) [reply packages/zoe/test/zoeTestHelpers.js]: done.  Thanks.

**Review by katelynsills — APPROVED** [review]
Looks good, thanks
