### PR TITLE
`gen-upgrade-proposal.sh` chain software upgrade helper

### LINKED ISSUE #7356: Cannot find package '@endo/init' from agd build
## Describe the bug

While writing docs for getting started as a liquidation bidder (#7295) I tested `agd build` on a blank debian container. It failed with `Cannot find package '@endo/init'`

## To Reproduce
1. start a blank debian container: `docker run --rm -ti debian:stable-slim`
2. `git clone https://github.com/agoric/agoric-sdk` (have to `apt update && apt install git curl -y` 1st)
3. `cd agoric-sdk; SKIP_DOWNLOAD=false ./bin/agd build`
4. See error:

```
$ yarn build:bundles
$ node ./scripts/build-bundles.js
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@endo/init'
```

## Expected behavior

install Just Works

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
[If applicable, add screenshots to help explain your problem, especially for UI interactions.](https://gist.github.com/dckc/838a51eec7467cacfd577904681162f1)

### PR DESCRIPTION
**Pull request by michaelfig**
## Description

Include a script to be referenced in future release notes when describing how to submit an Agoric chain software upgrade governance proposal.  Notably, the `--upgrade-info` constructed by this script will result in a proposal compatible with Cosmovisor.

Also adds a bit of stdout/stderr management and shell script debugging features when running `bin/agd build` vs. `bin/agd something else`.  As a drive-by, while tweaking `bin/agd`, also closes: #7356.

### Security Considerations

Cosmovisor's automatic download feature should not be used in production, though it is handy for one-off testing.

### Scaling Considerations

n/a

### Documentation Considerations

Should be described in release notes.

### Testing Considerations

Tested manually.

### CODE REVIEW

File: scripts/gen-upgrade-proposal.sh [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+echo "Generating SHA-256 checksum..." 1>&2
+checksum=sha256:$(shasum -a 256 "$zipfile" | cut -d' ' -f1)
+
+info="{\"binaries\":{\"any\":\"$ZIPURL?checksum=$checksum\"}}"
+
+cat <<EOF 1>&2
+------------------------------------------------------------
+Here is the skeleton of the recomended upgrade proposal command.
+You'll need to fill in the details:
+  <UPGRADE-NAME> is the name of the upgrade built into the agd binary
```
Comment (JimLarson) [inline scripts/gen-upgrade-proposal.sh]: Note that this will be provided by the organization that authored the upgrade.

File: scripts/gen-upgrade-proposal.sh [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+  <HEIGHT> is the block height at which the upgrade will take effect
```
Comment (JimLarson) [inline scripts/gen-upgrade-proposal.sh]: Point to guidance on how to choose this.

File: scripts/gen-upgrade-proposal.sh [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+  <TITLE> is the title of the proposal
```
Comment (JimLarson) [inline scripts/gen-upgrade-proposal.sh]: Note to look at previous recent proposals and follow their conventions. Same for DESCRIPTION below.

**Review by JimLarson — APPROVED** [review]

File: scripts/gen-upgrade-proposal.sh (hunk 1 above)
Comment (michaelfig) [reply scripts/gen-upgrade-proposal.sh]: I decided to remove these specific details in favour of more generic guidance, to reinforce that software upgrades are a power tool.

File: scripts/gen-upgrade-proposal.sh (hunk 2 above)
Comment (michaelfig) [reply scripts/gen-upgrade-proposal.sh]: Ditto.

File: scripts/gen-upgrade-proposal.sh (hunk 3 above)
Comment (michaelfig) [reply scripts/gen-upgrade-proposal.sh]: Ditto.

**Comment by michaelfig** [comment]
@Mergifyio refresh
