### PR TITLE
Zoe/ERTP input limits

### LINKED ISSUE #4276: When deploying a malicious contract, it is possible to crash the Zoe vat
## Describe the bug

By creating a zcfMint with an extremely large token name, after installing the Dapp in the wallet, the zoe vat crashes

## To Reproduce
1. Create a new Dapp with a contract (see the getting starting guide)
2. Wait for setup to finish 
3. Modify the makeZCFMint with the following code
```js
const tokenName = 'A'.repeat(200000000);
const zcfMint = await zcf.makeZCFMint(tokenName, AssetKind.NAT, harden({ decimalPlaces: 3 }));
```
4. Deploy the contract code (`agoric deploy ./contract/deploy.js ./api/deploy.js`)
contract code will install on zoe, 

```
2022-01-11T19:27:52.916Z SwingSet: kernel: delivery problem, terminating vat v11 Allocate meter exceeded
```

Deploy Output
```
% agoric deploy ./contract/deploy.js ./api/deploy.js

Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /Users/b4d2/dapp/demo/contract/deploy.js
agoric: deploy: Deploy script will run with Node.js ESM
- SUCCESS! contract code installed on Zoe
-- Contract Name: fungibleFaucet
-- Installation Board Id: 1221243446
writing /Users/b4d2/dapp/demo/ui/public/conf/installationConstants.js
agoric: deploy: running /Users/b4d2/dapp/demo/api/deploy.js
agoric: deploy: Deploy script will run with Node.js ESM
CapTP bundle exception: (RemoteError(error:captp:unknown#20001)#1)
RemoteError(error:captp:unknown#20001)#1: vat terminated

  at fullRevive (packages/marshal/src/marshal.js:399:34)
  at unserialize (packages/marshal/src/marshal.js:482:19)
  at CTP_RETURN (packages/captp/src/captp.js:504:16)
  at dispatch (packages/captp/src/captp.js:568:9)
  at WebSocket.<anonymous> (packages/agoric-cli/src/deploy.js:117:13)
  at WebSocket.emit (node:events:390:28)
  at WebSocket.emit (node:domain:475:12)
  at Receiver.emit (node:events:390:28)
  at Receiver.emit (node:domain:475:12)
  at Socket.emit (node:events:390:28)
  at Socket.emit (node:domain:475:12)

RemoteError(error:captp:unknown#20001)#1 ERROR_NOTE: Rejection from: (Error#2) : 19 . 0
Nested error under RemoteError(error:captp:unknown#20001)#1
  Error#2: Event: 18.1
  
    at deployApi (file:///Users/b4d2/dapp/demo/api/deploy.js:88:64)
    at async WebSocket.<anonymous> (packages/agoric-cli/src/deploy.js:264:13)
  
agoric: (RemoteError(error:captp:unknown#20001)#1)
```
5. Attempt to send 1 RUN from "Zoe fees" to Transfer within wallet "Agoric RUN currency", and the transfer will fail since zoe is dead
Screen Shot 2022-01-11 at 11 31 12 AM

## Expected behavior
I should not be able to crash the zoe vat from a malicious Dapp

## Additional notes
This may result in a cascading failure as well, as the Token name is utilized by multiple services downstream from zoe

## Platform Environment
 - what OS are you using? what version of Node.js?
 macOS 12.1, node v16.13.1
 - is there anything special/unusual about your platform?
 I only have 16gb of ram
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
`72cc8d6bcf428596653593708959446fb0a29596`

ref #4264

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #4276
refs: #4272

## Description

Basic sanity checking for decimalPlaces and keyword length that aren't caught by the general SwingSet input validation in #5579.

### Security Considerations

Doesn't improve client security by itself, but does help prevent accidental footguns while using the official ERTP library.

### CODE REVIEW

File: packages/ERTP/src/displayInfo.js [hunk 1]
```diff
@@ -67,6 +70,19 @@ export const coerceDisplayInfo = (allegedDisplayInfo, assetKind) => {
   assertSubset(displayInfoKeys, Object.keys(displayInfo));
   if (displayInfo.decimalPlaces !== undefined) {
     assert.typeof(displayInfo.decimalPlaces, 'number');
+    assert(
+      Number.isSafeInteger(displayInfo.decimalPlaces),
+      X`decimalPlaces ${displayInfo.decimalPlaces} is not a safe integer`,
+    );
```
Comment (erights) [inline packages/ERTP/src/displayInfo.js]: I think the second assert subsumes the first, so the first can be deleted.
```suggestion
    assert(
      Number.isSafeInteger(displayInfo.decimalPlaces),
      X`decimalPlaces ${displayInfo.decimalPlaces} is not a safe integer`,
    );
```

File: packages/ERTP/src/displayInfo.js [hunk 2]
```diff
@@ -67,6 +70,19 @@ export const coerceDisplayInfo = (allegedDisplayInfo, assetKind) => {
...
+    assert(
+      displayInfo.decimalPlaces <= MAX_ABSOLUTE_DECIMAL_PLACES,
+      X`decimalPlaces ${displayInfo.decimalPlaces} exceeds ${MAX_ABSOLUTE_DECIMAL_PLACES}`,
+    );
+    assert(
+      displayInfo.decimalPlaces >= -MAX_ABSOLUTE_DECIMAL_PLACES,
```
Comment (erights) [inline packages/ERTP/src/displayInfo.js:81]: Huh. It never occurred to me that negative `decimalPlaces` are meaningful. Good to know.
(No change suggested)

**Review by erights — APPROVED** [review]
LGTM

Good to start getting these defenses in, thanks!
