### PR TITLE
Tolerate loose errors

### LINKED ISSUE #2271: Error handler throws when it detects Unexpected own properties in an Error object
## Describe the bug

Marshall throws an Error when it detects Unexpected own properties in an Error object:
```
UnhandledPromiseRejectionWarning: (TypeError#1)
Nested error
  TypeError#1: Unexpected own properties in error: pos,loc,code
     at isPassByCopyError (kernel/packages/marshal/src/marshal.js:156:11)
    at passStyleOf (kernel/packages/marshal/src/marshal.js:364:13)
    at encode (kernel/packages/marshal/src/marshal.js:577:25)
    at Object.serialize (kernel/packages/marshal/src/marshal.js:687:21)
    at eval (kernel/packages/SwingSet/src/kernel/liveSlots.js:492:21)
```

marshall.js has the following code
```
  if (restNames.length >= 1) {
    throw new TypeError(`Unexpected own properties in error: ${restNames}`);
  }
```

The issue is that an unlimited ability to attach properties to Error objects would allow code to violate encapsulation.

## To Reproduce

checkout the branch [ErrorProperties](https://github.com/Agoric/agoric-sdk/pull/2272)
cd to packages/zoe
run `yarn test test/swingsetTests/zoe/test-zoe.js    -m 'zoe - coveredCall - valid inputs'`

## Expected behavior

Marshall shouldn't suppress error reporting when the properties are recognized as the kind added by well-known libraries like Node and Babel. 

## Platform Environment
 - what OS are you using? what version of Node.js? 
    -  ** Running on MacOS, with node v14.8.0 **
 - is there anything special/unusual about your platform? **no**
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`) **unifi-dao-demo-13-jan-2021-28-gb01bf7c9**

 - upgrades SES to  `"ses": "^0.11.1"`

## Additional context

This happened while Michael and I were debugging changes to various parsers to add support for BigInt literals. 

@michaelfig  says the problem has been around for a while, but was masked by the fringeSet implementation of harden. This was also unusual in that we're causing syntax errors at runtime while investigating the parsing of BigInts.

### PR DESCRIPTION
**Pull request by erights**
I failed to rebase #2272  and still reproduce the error. But the old marshal.js is now so out of date that it's pointless to work there without rebasing. This is still draft because I don't have tests yet. Rather than try to get something like #2272 working (or rather, correctly not working), I'm just going to write some synthetic unit tests. Until I do this is draft but feel free to start reviewing. I think it is in good shape.

Fixes #2271 

Needs https://github.com/Agoric/SES-shim/issues/579 but is not blocked on it.

### CODE REVIEW

File: packages/marshal/src/marshal.js [hunk 1]
```diff
@@ -180,20 +187,23 @@ function isPassByCopyError(val) {
...
   }
+  if (mDesc) {
+    if (typeof mDesc.value !== 'string') {
+      assert.note(
+        val,
+        X`Error message property ${mDesc} must be a string-valued data property.`,
+      );
+    }
+    if (mDesc.enumerable) {
+      assert.note(val, X`Error message property ${mDesc} not be enumerable`);
```
Comment (Chris-Hibbert) [inline packages/marshal/src/marshal.js]: If I'm reading this right: 
```suggestion
      assert.note(val, X`Error message property ${mDesc} must not be enumerable`);
```

**Review by Chris-Hibbert — COMMENTED** [review]
The comment on `isPassByCopyError()` was very clarifying. I think this makes sense, but I'd like to see (and understand) some tests.

File: packages/marshal/src/marshal.js (hunk 1 above)
Comment (erights) [reply packages/marshal/src/marshal.js]: You read that right. Thanks!

**Comment by erights** [comment]
> The comment on `isPassByCopyError()` was very clarifying. I think this makes sense, but I'd like to see (and understand) some tests.

Done

**Comment by erights** [comment]
Tests added. Ready for review.

**Review by michaelfig — APPROVED** [review]
LGTM!

File: packages/marshal/src/marshal.js [hunk 2]
```diff
@@ -174,20 +181,26 @@ function isPassByCopyError(val) {
...
-      !mDesc.enumerable,
-      X`An error's .message must not be enumerable`,
-      TypeError,
+  if (ownKeys(restDescs).length >= 1) {
+    assert.note(
+      val,
+      X`Passed Error has extra unpassed properties ${restDescs}`,
     );
   }
+  if (mDesc) {
```
Comment (Chris-Hibbert) [inline packages/marshal/src/marshal.js:190]: I'm pretty sure I understand the debugging case. What's the argument that this doesn't form a side-channel in the normal case?

Comment (erights) [reply packages/marshal/src/marshal.js:190]: Hi @Chris-Hibbert , 
Sorry, this came in right after I merged. What side channel hazard are you concerned about?

Comment (Chris-Hibbert) [reply packages/marshal/src/marshal.js:190]: Does it  leak information that we want to protect? Can code outside the debugging path see data in an Error object passing through?

The old code had `assert`s that threw to prevent some info from escaping. Was that info benign all along?

Comment (erights) [reply packages/marshal/src/marshal.js:190]: We do want to protect the `assert.note` info. It must not leak to anyone/anything that is not authorized to see it. It has essentially the same status as the substitution values of the details object associated with the error itself as the detailed error message.

The `assert.note` info leaks to those who can see console output, which we consider to be at a level of privilege comparable to being able to observe a debugger eye's view of the computation. The `assert.note`s do not leak to anyone with access just to the error instance nor do they affect what gets serialized.

The extra properties that this PR tolerates are in a middle ground. They are accessible to anyone with just the original error instance, because that's where something outside of our control put it. However, these extra properties do not affect what gets serialized and so do not leak info inter-vat.

There is always the question of leakage over pervasive side channels like timing or weakrefs. Our general answer to these it not to make any strong claims that we've prevented anything private from leaking outward on these channels, to those that can listen to those channels. But rather, we can prevent much computation the ability to listen by denying it the powers needed to listen --- to measure duration or to create weakrefs. However, I see only the normal danger of that here. I don't see anything uniquely leaky about this code.
