### PR TITLE
fix(SwingSet): move promise rejection from stopVat to the kernel

### LINKED ISSUE #6694: have kernel reject unresolved vat-decided promises of an upgraded vat
## What is the Problem Being Solved?

As listed in #6650, when a vat is upgraded, it's `stopVat` is currently responsible for rejecting ("disconnecting") all of that vat's Promises (i.e. all the Promises for which the upgraded vat was the decider). We do this because we don't have durable pseudo-promises (#3787), so the V2 version of that vat cannot possibly have access to the `resolve()`/`reject()` facets on those promises, so there's no way for them to become resolved ever again. We reject these promises during upgrade, with a distinctive value (so clients can distinguish "owner upgraded" vs "owner deliberately rejected"), which allows clients of e.g. durable *Notifiers* in the upgraded vat to come back and ask for a new Promise from the new version.

As part of #6650, we're moving responsibility for this task from the old vat into the kernel. The kernel will reject these promises just after it shuts down the old worker, and just before it starts the new one.

## Description of the Design

The kernel will walk the vat's c-list to find all promises known to the vat. These should all be unresolved, because we retire vpid/vrefs and c-list entries immediately upon resolution. For each kpid in the c-list, the kernel it will examine the kernel promise table to find the subset that are decided by the vat being upgraded. (In the future, perhaps as part of #6677 , we might use a better index to find this set of kpids more efficiently). The code to do this is already part of `kernelKeeper.cleanupAfterTerminatedVat`, as called by kernel.js `terminateVat`.

The kernel will reject these promises, using the same `disconnectObject` that we currently pass as an argument into `stopVat` (the one that contains `upgradeMessage` and the old `incarnationNumber`).

Inside the vat, we'll modify the Durable Promise Watcher:
* when watching a promise, liveslots must `syscall.subscribe()` to the vpid, even if the promise is being exported at that time
  * the kernel must now allocate a kpid for the vpid in `syscall.subscribe()`, if we don't already have one. This might already work fine, but it's a new case that we need to check
  * we need this to ensure that the new vat version receives `dispatch.notify()` events for self-decided/exported promises from the old version. Previously these were tracked internally in the `deadPromises` vatstore key
* remove `prepareShutdownRejections` from `liveslots/watchedPromises.js`, alone with the `deadPromises` table, and `deadPromisesDO` for the disconnect object
* in `loadWatchedPromiseTable`, remove the reads of `deadPromises`/`deadPromiseDO`, and the code that handles promises which were in this table. Instead, *all* promises in the `watchedPromiseTable` will be revived, and then the kernel will deliver `dispatch.notify()` for the ones that were disconnected
* change `kernelQueue.js`'s `doResolve()` function to enqueue a `notify()` to *all* subscribers, not skipping the deciding vat: vats are allowed to subscribe to their own promises, and they'll be notified if/when those promises are resolved
  * liveslots already tolerates (ignores) a `dispatch.notify()` of a promise that's missing from the slotToVal table (which we added because a notify might be queued at the time of a vat upgrade, and the new version would not remember subscribing)
  * liveslots will not gratuitously subscribe to exported promises: it only subscribes when deserializing a new vpid (imported promise), or when an auxilliary vpid appears in a batched resolution, or (new) when a promise becomes Watched

## Compatibility Considerations

In this new approach, self-exported promises will deliver their rejections (within the new vat version) slightly later than before. Previously, `startVat` sent these rejections, so they'll all be executed during the `startVat` delivery (after module load, after `buildRootObject` is called again, but still in the same crank, and before any new messages can be delivered). After this change, the rejections will be pushed onto the run-queue during upgrade, so they won't be delivered until after everything else currently on the run-queue is delivered.

## Test Plan

Unit tests

### PR DESCRIPTION
**Pull request by gibson042**
closes: #6694

## Description

- [x] Reject orphaned promises in `terminateVat`
- [x] Reject orphaned promises in `processUpgradeVat`
- [x] Remove special-casing in durable promise watchers

### Security Considerations

This is an overall increase in robustness against problems with dying vats.

### Scaling Considerations

I don't believe there are any changes w.r.t. scaling.

### Documentation Considerations

All changes would be internal, but we should still do a scan before merging.

### Testing Considerations

No changes.

### CODE REVIEW

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 1]
```diff
@@ -928,6 +909,27 @@ export default function makeKernelKeeper(kernelStorage, kernelSlog) {
     kvStore.set(`${kpid}.decider`, '');
   }
 
+  function* enumeratePromisesByDecider(vatID) {
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:909]: @warner We talked about a convention for generators, and "enumerate…" has some preexisting examples so I'm running with it.

File: packages/swingset-liveslots/src/vpid-tracking.md [hunk 2]
```diff
@@ -2,85 +2,88 @@
...
+Instead, we care about which side holds the resolution authority for a promise (referred to as being its **decider**). This is not indicated by the VPID sign, and in fact is not necessarily static. Liveslots does not currently have any mechanism to allow one promise to be forwarded to another, but if it acquires this some day, then the decider of a promise could shift from kernel to vat to kernel again before it finally gets resolved. And there *are* sequences that allow a vat to receive a reference to a promise in method arguments before receiving a message for which that same VPID identifies the result promise (e.g., `pk = makePromiseKit(); p2 = E(pk.promise).push('queued'); await E(observer).push(p2); pk.resolve(observer)` with an observer whose `push` returns a prompt response). In such cases, the decider is initially the kernel but later becomes the receiving vat.
```
Comment (warner) [inline packages/swingset-liveslots/src/vpid-tracking.md]: I fully agree with updating the example to `E()` instead of tildot, and your rewording is a lot more clear. I'm not sure I understand the new example.

OTOH I'm not sure I understand my original either. Let's see:
* p2 is decided by the kernel
* p1 is also decided by the kernel, at least until p2 is resolved
* `x` is an object in some vat
* `bar` is sent into that vat, carrying `p1` as an argument, so the vat knows that `p1` will be decided by the kernel, later
* `p2` gets resolved to `x`, allowing the `foo()` to be unqueued and delivered to the vat that hosts x
* the `dispatch.deliver()` of `foo` causes its result promise (`p1`) to change decidership from the kernel to the vat that hosts x
* none of this requires pipelining or promise forwarding

Let's see, in your new example:
* `pk` and `p2` are local to the sending vat
* `E(observer).push(p2)` to a remote vat causes `p2` to be exported, so the kernel knows the sending vat is the decider of `p2`
* by "push returns a prompt response" I'm guessing there's a crank boundary between the push(p2) and the pk.resolve()?
* `pk.resolve(observer)` resolves the local promise to the remote Presence, allowing the push("queued") to be sent out into the kernel towards "observer"
* the remote vat receives push("queued")

I don't think I see which promise is changing decider from kernel to receiving vat.

File: packages/swingset-liveslots/src/vpid-tracking.md [hunk 3]
```diff
@@ -2,85 +2,88 @@
...
+A Promise may be associated with a VPID even though the kernel does not know about it (i.e. the VPID is not in the kernel's c-list for that vat). This can occur when a Promise is stored into virtual data without also being sent to (or received from) the kernel, although note that every Promise associated with a durable promise watcher _is_ sent to the kernel so it can be rejected during vat upgrade. A Promise can also be resolved but still referenced in vdata and forgotten by the kernel (the kernel's knowledge is temporary; it retires VPIDs from c-lists upon `syscall.resolve` or `dispatch.notify` as relevant). So a VPID might start out stored only in vdata, then get sent to the kernel, then get resolved, leaving it solely in vdata once more.
```
Comment (warner) [inline packages/swingset-liveslots/src/vpid-tracking.md]: nit, s/as relevant/as appropriate/ sounds better to my ears

File: packages/swingset-liveslots/src/vpid-tracking.md [hunk 4]
```diff
@@ -2,85 +2,88 @@
...
+Each unresolved VPID has a decider: either the kernel or a vat. It can remain unresolved for arbitrarily long, but becomes resolved by the first of the following events:
 
-* if/when userspace resolves the corresponding `Promise` and liveslots learns of the resolution, then liveslots will perform a `syscall.resolve()`
-* if/when the vat is upgraded, liveslots will perform a `syscall.resolve()` of all remaining VPIDs during the delivery of `dispatch.stopVat()` (after which all `Promise`s evaporate along with the rest of the JS heap)
-* if/when the vat is terminated, the kernel internally rejects all remaining vat-decided KPIDs, without involving the vat
-* otherwise, the VPID remains unresolved until the heat death of the universe
+* if userspace resolves the corresponding Promise and liveslots learns of the resolution, then liveslots will perform a `syscall.resolve()`
+* if the vat is upgraded, liveslots will perform a `syscall.resolve()` of all remaining VPIDs during the delivery of `dispatch.stopVat()` (after which all Promises evaporate along with the rest of the JS heap)
```
Comment (warner) [inline packages/swingset-liveslots/src/vpid-tracking.md]: this should be updated to mention the new kernel-initiated rejection

File: packages/swingset-liveslots/src/vpid-tracking.md [hunk 5]
```diff
@@ -2,85 +2,88 @@
...
 ## Promise/VPID Management Algorithm
 
-* When a `Promise` is first serialized (it appears in `convertValToSlot`), a VPID is assigned and the VPID/`Promise` mapping is registered in `valToSlot`/`slotToVal`
+* When a Promise is first serialized (it appears in `convertValToSlot`), a VPID is assigned and the VPID/Promise mapping is registered in `valToSlot`/`slotToVal`
   * at this point, there is not yet a strong reference to the Promise
 * When a VPID appears in the serialized arguments of `syscall.send` or `syscall.resolve`:
   * if the VPID already exists in `exportedVPIDs` or `importedVPIDs`: do nothing
-  * else: use `followForKernel` to add to `exportedVPIDs` and use `.then()` to attach a `handle` callback
-* When `followForKernel`'s `handle` callback is executed:
+  * else: use `followForKernel` to add the VPID to `exportedVPIDs` and attach settlement callbacks
```
Comment (warner) [inline packages/swingset-liveslots/src/vpid-tracking.md]: Is the term "settlement callback" well known to JS programmers? I think I heard about promises and `.then` before learning the word "settlement". It might be good to mention `.then` the first time we use this phrase, so folks can connect something they know to the more precise terminology.

File: packages/swingset-liveslots/src/vpid-tracking.md [hunk 6]
```diff
@@ -2,85 +2,88 @@
...
   * else: unregister from `valToSlot`/`slotToVal`
 * When a new VPID is deserialized (it appears in `convertSlotToVal`), this must be the arguments of a delivery (not vdata)
   * use `makePipelinablePromise` to create a HandledPromise for the VPID
-  * add the Promise and it's `resolve`/`reject` pair to `importedVPIDs`
-  * register the Promise in `valToSlot`/`slotToVal'`
+  * add the Promise and its `resolve`/`reject` pair to `importedVPIDs`
+  * register the Promise in `valToSlot`/`slotToVal`
   * use `syscall.subscribe` to request a `dispatch.notify` delivery when the kernel resolves this promise
-* When a VPID appears as the `.result` of an outbound `syscall.send`:
+* When a VPID appears as the `result` of an outbound `syscall.send`: (_note overlap with the preceding_)
```
Comment (warner) [inline packages/swingset-liveslots/src/vpid-tracking.md:75]: is this note for the reader?

There *is* considerable overlap between the actions taken among the various ways a VPID might appear, but this section should emphasize clarity over brevity, and factoring out the common pieces might be a detriment to clarity.

File: packages/swingset-liveslots/src/vpid-tracking.md [hunk 7]
```diff
@@ -2,85 +2,88 @@
...
-* When a VPID appears as the `.result` of an inbound `dispatch.deliver`:
-  * check to see if the VPID is present in `importedVPIDs`:
-    * if yes: extract `pRec`, use `pRec.resolve(res)` to forward the invocation result promise to the previously-imported promise, then remove the VPID from `importedVPIDs`
-    * if no: register `res` the invocation result promise under the VPID
-  * in either case, next we add the VPID to `exportedVPIDs`
-  * then we call `followForKernel` to attach a callback to the `res` promise
+* When a VPID appears as the `result` of an inbound `dispatch.deliver`:
+  * if the VPID is present in `importedVPIDs`: retrieve the `[resolve, reject]` pRec and use `resolve(res)` to forward the invocation result promise to the previously-imported promise, then remove the VPID from `importedVPIDs`
+  * else: register `res` the invocation result promise under the VPID
+  * in either case, use `followForKernel` to add the VPID to `exportedVPIDs` and attach settlement callbacks
```
Comment (warner) [inline packages/swingset-liveslots/src/vpid-tracking.md]: I vaguely remember thinking that it was important to explain that `followForKernel` is attaching a callback to `res` specifically, and to give names to the different kinds of promises mentioned here. So maybe use "attach settlement callbacks to `res`".

(there are at least two promises floating around here, and we've had bugs resulting from getting them mixed up in the implementation, so I needed to be extra precise in the docs)

File: packages/swingset-liveslots/src/liveslots.js [hunk 8]
```diff
@@ -1183,7 +1191,6 @@ function build(
     // upgrade, or if we acquire decider authority for a
     // previously-imported promise
     if (pRec) {
-      // TODO: insist that we do not have decider authority for promiseID
```
Comment (warner) [inline packages/swingset-liveslots/src/liveslots.js:1186]: hm, I'm not 100% sure this goes away.

Let's see, if we resolve a watched local promise, currently the kernel won't send the notify back into us, because our `syscall.resolve` will delete the vpid from our c-list, which means the kernel's `notify` event will find the c-list entry missing, so the kernel can't deliver a `dispatch.notify` (it has no vpid to translate it into). So we won't observe that case.

(I think we would tolerate it anyways, if liveslots receives a notify for a promise whose vpid it doesn't recognize, it will ignore it. But I also think that case won't happen, at least not for these cancelled-by-upgrade promises)

If we watch a remotely-decided promise, the `dispatch.notify` will tell us about a promise that we aren't the decider for, so the assertion implied by the comment would be satisfied.

If we're a new incarnation, and we just finished walking our saved `WatchedPromises` table, and regenerated new Promise objects for everything there, we can pretend that the kernel is the decider for all of them. Some of them were decided by our predecessor, but we don't know that, and the kernel effectively claimed decidership when it shut down our predecessor.

Maybe just change it to "it is unlikely that we have decider authority for these: do some case analysis, and then maybe add an assertion".

File: packages/swingset-liveslots/src/liveslots.js [hunk 9]
```diff
@@ -1424,7 +1431,7 @@ function build(
       Fail`buildRootObject() for vat ${forVatID} returned ${rootObject} with no interface`;
     // Need to load watched promises *after* buildRootObject() so that handler kindIDs
     // have a chance to be reassociated with their handlers.
-    watchedPromiseManager.loadWatchedPromiseTable();
+    watchedPromiseManager.loadWatchedPromiseTable(unmeteredRevivePromise);
```
Comment (warner) [inline packages/swingset-liveslots/src/liveslots.js:1434]: What's our rationale for using *unmetered* `revivePromise`? I'm sure there might be one, but each time this comes up I have to think carefully about what it might or might not be sensitive to, and I'd like to have a clear reason for each place where we disable metering. I think it's usually a question of whether the function's behavior might depend upon the WeakRefs in `slotToVal`. If `loadWatchedPromiseTable` is strictly always adding things to that table (there's no chance for a vpid to already exist there), then I suspect we don't need/want it to be unmetered.

File: packages/swingset-liveslots/package.json [hunk 10]
```diff
@@ -16,7 +16,9 @@
     "lint:types": "tsc -p jsconfig.json",
     "lint:eslint": "eslint ."
   },
-  "devDependencies": {},
+  "devDependencies": {
+    "@agoric/swingset-vat": "^0.30.2"
```
Comment (warner) [inline packages/swingset-liveslots/package.json]: This will be a problem: swingset-vat already depends on liveslots (possibly via some other packages), and I don't want to have a cycle, even in the `devDependencies`, because I think it's going to impact the stability of yarn's dependency-resolver solutions.

File: packages/swingset-liveslots/test/test-vat-upgrade.js [hunk 11]
```diff
@@ -0,0 +1,73 @@
+import '@agoric/swingset-vat/tools/prepare-test-env.js';
+import test from 'ava';
+import { buildVatController } from '@agoric/swingset-vat';
+import { kunser } from '@agoric/swingset-vat/src/lib/kmarshal.js';
```
Comment (warner) [inline packages/swingset-liveslots/test/test-vat-upgrade.js]: Hrm. If we're testing this functionality here, in swingset-liveslots, we need to be able to do it without a kernel, and without `buildVatController`. This file might want to live in `packages/SwingSet/` instead of swingset-liveslots.

The general approach I've taken is that swingset-liveslots does unit tests that only involve liveslots, and interact with a liveslots instance by doing `dispatch.deliver` and watching for `syscall.send` -type stuff. Look for examples in `test-liveslots.js`: you can write a `buildRootObject` and pass it into the `makeDispatch` helper tool, and then send it messages and examine the log of syscalls (even peek into a `fakestore` to see what it does with the swingstore). These tests can be pretty high-resolution, it's easy to look inside the box, and they're fast.

Then, for more integration -type stuff, I put those in `packages/SwingSet/`, which can build an actual kernel. I can't usually inspect the internals as well, and it runs a lot slower, but it will catch integration issues that I wouldn't see with the narrower non-kernel tests.

BTW `buildRootObject` gets a `vatPowers` argument, and `vatPowers.VatData.watchPromise` gets you access to the promise-watcher entry point, which is probably how you should write this kind of test in the "narrow" form. We'll watch the syscall log for the `subscribe` calls. Then, we can simulate an upgrade by cloning the `fakestore` into a new copy, then starting a new `buildRootObject`, then sending in the `dispatch.notify()` calls that we know the kernel will do, and watch for the second version to react to the promise rejections.

The nice thing about this form of test is that our `buildRootObject` runs in the start compartment, and it can close over variables, with which it can communicate to the test runner. So the "vat" code can tell us when a promise gets rejected directly.

**Review by warner — CHANGES_REQUESTED** [review]
Nice! We'll need to move that new test into swingset/, remove the new dependencies, and write some new narrow-style tests to live in liveslots/ . Grab me tomorrow and we can pair on those tests if you like.

File: packages/swingset-liveslots/src/vpid-tracking.md (hunk 2 above)
Comment (gibson042) [reply packages/swingset-liveslots/src/vpid-tracking.md]: Here's my understanding of how decidership of p2 changes; please let me know if I've got anything wrong.

**step1**: `pk = makePromiseKit();`
1. `pk.promise` is local to Alice

**step2**: `p2 = E(pk.promise).push('queued');`
1. `syscall.send(target=pk.promise, method='push', args=['queued'], result=p2)`
2. Kernel becomes the decider of `p2` and notes that Alice is the decider of `pk.promise`

**step3**: `await E(observer).push(p2);`
1. `syscall.send(target=observer, method='push', args=[p2], result=<anonymous>)`
2. Kernel becomes the decider of `<anonymous>` and notes subscription by Alice
3. Alice loses agency

**step3a**
1. Kernel handles the step2 `syscall.send` by pushing onto the queue for `pk.promise`

**step3b**
1. Kernel handles the step3 `syscall.send` by `deliver(type='send', target=observer, method='push', args=[p2], result=<anonymous>)` and making `observer`'s vat the decider of `<anonymous>`
2. observer does `syscall.resolve(subject=<anonymous>, resolution=…)`
3. observer loses agency

**step3c**
1. Kernel handles the `syscall.resolve`, which involves `notify(vatID=Alice, promise=<anonymous>)` to enqueue a message

**step3d**
1. Kernel handles the notify by `deliver(type='notify', subject=<anonymous>, resolution=…)`
2. Alice regains agency

**step4**: `pk.resolve(observer);`
1. `syscall.resolve(subject=pk.promise, resolution=observer)`
2. Alice loses agency

**step4a**
1. Kernel handles the step4 `syscall.resolve`, which involves noting resolution of `pk.promise` to `observer` and `requeueKernelPromise(pk.promise)` to requeue messages to it

**step4b**
1. Kernel handles the requeued step2 `syscall.send` by `deliver(type='send', target=observer, method='push', args=['queued'], result=p2)` and making `observer`'s vat the decider of `p2` (which it previously only knew from delivery arguments) and [hopefully!] also noting subscription by Alice to `p2`

File: packages/swingset-liveslots/src/liveslots.js (hunk 8 above)
Comment (gibson042) [reply packages/swingset-liveslots/src/liveslots.js:1186]: Does liveslots track decidership at all? It looks to me like this block handles a notify for any watched promise in the imported set regardless of how it got there, and that being in the imported set is a solid basis for proceeding.

File: packages/swingset-liveslots/src/liveslots.js (hunk 9 above)
Comment (gibson042) [reply packages/swingset-liveslots/src/liveslots.js:1434]: This preserves existing behavior, but I would like to leave enough breadcrumbs to avoid such doubt in the future.

The first line of `revivePromise` asserts absence of metering, and then the rest proceeds to call `pRec = makePipelinablePromise(vpid)`, store the vpid–pRec mapping in `importedVPIDs`, register the vpid–promise mapping for the marshaller with `registerValue`, and return the promise.
`revivePromise` is called only by `loadWatchedPromiseTable`, which initializes an entry for the vpid–promise pair in `promiseRegistrations` and invokes `pseudoThen` to register settlement callbacks.

What commentary would you like to see at this invocation of `loadWatchedPromiseTable`?

File: packages/swingset-liveslots/src/vpid-tracking.md (hunk 5 above)
Comment (gibson042) [reply packages/swingset-liveslots/src/vpid-tracking.md]: yeah, promise vocabulary is muddy in the JS ecosystem and in our codebase. The full taxonomy (representation courtesy @erights) is
* unresolved
* resolved
  * forwarded[^1]
  * settled
    * fulfilled
    * rejected

But it's unfortunately common to use "resolved" in place of "settled", making it unclear for any given use whether or not forwarded promises are included. It seems like liveslots documentation and code are concerned only with the exclusive sense (e.g., forwarding does not result in syscalls and in fact isn't even sensed), and I'm trying to use more accurate vocabulary without losing people in the process. Which is a long-winded way to say "suggestion accepted".

[^1]: However, I'm not a fan of "forwarded" as a term because `resolveP1(P2)` forwards settlement _capability_ from P1 to P2 by forwarding eventual settlement _results_ from P2 to P1.

File: packages/swingset-liveslots/src/vpid-tracking.md (hunk 6 above)
Comment (gibson042) [reply packages/swingset-liveslots/src/vpid-tracking.md:75]: > is this note for the reader?

Yes, and for the reasons you describe.

File: packages/swingset-liveslots/src/vpid-tracking.md (hunk 7 above)
Comment (gibson042) [reply packages/swingset-liveslots/src/vpid-tracking.md]: Clarified.

File: packages/swingset-liveslots/src/vpid-tracking.md (hunk 4 above)
Comment (gibson042) [reply packages/swingset-liveslots/src/vpid-tracking.md]: Done.

File: packages/swingset-liveslots/test/test-vat-upgrade.js (hunk 11 above)
Comment (gibson042) [reply packages/swingset-liveslots/test/test-vat-upgrade.js]: Done.

File: packages/swingset-liveslots/src/vpid-tracking.md (hunk 2 above)
Comment (warner) [reply packages/swingset-liveslots/src/vpid-tracking.md]: > step2: p2 = E(pk.promise).push('queued');
>    syscall.send(target=pk.promise, method='push', args=['queued'], result=p2)

Ah, ok since `pk.promise` is local, this E() is handled entirely by HandledPromise, and liveslots doesn't see it at all, until/unless `pk.promise` gets resolved to something that liveslots created.

(I'm betting that invalidates the rest of the sequence, so I didn't study it carefully yet, we can sync up on this in realtime and work out an example that demonstrates the problem, or maybe remove it from the docs.. I'm pretty sure I wrote the original to remind myself in the future, because it wasn't easy to reconstruct the problematic scenario, so it'd be nice to include at least a few hints)

File: packages/swingset-liveslots/src/vpid-tracking.md [hunk 12]
```diff
@@ -2,85 +2,90 @@
...
-  * check to see if the VPID is present in `importedVPIDs`:
-    * if yes: extract `pRec`, use `pRec.resolve(res)` to forward the invocation result promise to the previously-imported promise, then remove the VPID from `importedVPIDs`
-    * if no: register `res` the invocation result promise under the VPID
-  * in either case, next we add the VPID to `exportedVPIDs`
-  * then we call `followForKernel` to attach a callback to the `res` promise
+* When a VPID appears as the `result` of an inbound `dispatch.deliver`, the vat is responsible for deciding it:
+  * construct a promise `res` to capture the userspace-provided result
+  * if the VPID is present in `importedVPIDs`: retrieve the `[resolve, reject]` pRec and use `resolve(res)` to forward eventual settlement of `res` to settlement of the previously-imported promise, then remove the VPID from `importedVPIDs`
+  * else: register marshaller association between the VPID and `res`
+  * in either case, use `followForKernel` to add the VPID to `exportedVPIDs` and attach `.then(onFulfill, onReject)` callbacks that will map fulfillment/rejection to `syscall.resolve()
```
Comment (warner) [inline packages/swingset-liveslots/src/vpid-tracking.md]: there's a missing backquote at the end of this line

File: packages/vat-data/src/exo-utils.js
Comment (warner) [inline packages/vat-data/src/exo-utils.js:1]: I don't see any problems with this refactoring, but if you adopt my request to avoid a liveslots->vat-data dependency, maybe it could go into a separate PR?

File: packages/swingset-liveslots/test/test-handled-promises.js [hunk 13]
```diff
@@ -0,0 +1,294 @@
+/* eslint-disable no-await-in-loop, @jessie.js/no-nested-await */
+import test from 'ava';
+import '@endo/init/debug.js';
+
+import { Far } from '@endo/marshal';
+import { Fail } from '@agoric/assert';
+import { M } from '@agoric/store';
+import { makePromiseKit } from '@endo/promise-kit';
+// import { makeStoreUtils } from '../../vat-data/src/vat-data-bindings.js';
+import { makeExoUtils } from '../../vat-data/src/exo-utils.js';
```
Comment (warner) [inline packages/swingset-liveslots/test/test-handled-promises.js]: This import feels problematic. At the very least, let's change it to `@agoric/vat-data/src/exo-util.js` (using `../..` is kinda cheating / assuming the monorepo layout, and I'm likely to be moving swingset-liveslots out to a separate repository, which will break `../../`)

At a deeper level, Exos are not a liveslots concern. Liveslots provides Kinds, and userspace can use `@agoric/vat-data` to get Exos on top of that. We need to make sure that liveslot's `defineKind` works when used by `makeExo` stuff, but I think that should be the responsibility of `vat-data` rather than liveslots.

And I'm worried about the coupling this induces (especially because of my upcoming #6596 work): currently swingset-liveslots has a `devDependency` upon vat-data solely to get the types for `DefineKindOptions` and `DurableKindHandle`, and I think those types should be *exported* by liveslots rather than having liveslots *import* them from vat-data. With that change, we could shed the liveslots -> vat-data `devDependency` entirely, which is going to help with the #6596 packaging effort (the build process for `xsnap-supervisor`, which imports liveslots, can happen in a workspace/repo/`node_modules` that doesn't have swingset at all, which would prune a cycle).

Could you have this test work with a Kind instead of an Exo, and remove the dependency on `vat-data`?

**Review by warner — CHANGES_REQUESTED** [review]
mostly good, but let's see if we can remove that new vat-data dependency

File: packages/swingset-liveslots/test/test-handled-promises.js (hunk 13 above)
Comment (gibson042) [reply packages/swingset-liveslots/test/test-handled-promises.js]: Huh, I thought I had already done that. Fixed.

File: packages/swingset-liveslots/src/liveslots.js (hunk 9 above)
Comment (warner) [reply packages/swingset-liveslots/src/liveslots.js:1434]: Good point, and yeah we don't have the time to dive any deeper than what you've just mapped out. Maybe just add "TODO: why does this need to be unmetered?", and we'll eventually do another pass through and revisit those decisions.

File: packages/swingset-liveslots/src/liveslots.js (hunk 8 above)
Comment (warner) [reply packages/swingset-liveslots/src/liveslots.js:1186]: Yeah, you're probably right. Our comment near the `importedVPIDs` declaration claims that it only holds VPIDs for which the kernel is the decider.. if that's actually true, then this comment is stale (and a tautology).

I remember doing a lot of refactoring on this about a year ago, and maybe I introduced `importedVPIDs`/`exportedVPIDs` at that time, to clean up liveslot's approach to keeping track of decidership. I suspect it still isn't precisely correct (in the face of forwardings), but it's clearly trying to be.

So yeah, go ahead and delete that line. There's no better criteria for decidership than membership/not in `importedVPIDs`, so if there's any cleanup or other cases to inspect, it won't be in this function, it'll be in the `dispatch.deliver` that reacts to a previously-known `result=` VPID, or in the code that does `syscall.send`.

**Review by warner — APPROVED** [review]
Ok everything looks good except for the vpid-tracking.md line 5 "vpid forwarding" example. Maybe just leave that line the way it was (tildot and all), and we come back to it later for a more complete analysis? I'm pretty sure the original wording expressed whatever weird case it was that I thought of years ago (even if I don't remember how that case worked anymore), and I'm not convinced that the new wording accomplishes that, and I don't want to hold this up just for the sake of updating the example.
