### PR TITLE
fix(run-protocol): store Presences, not Promises, in VaultManager

### LINKED ISSUE #5121: change vaultFactory (and run-protocol?) to require settled `priceAuthority` and `timerService`, not promises
## What is the Problem Being Solved?

#5106 is a swingset bug that's triggered by userspace code storing Promises in virtual data (`state` properties of virtual objects, or virtual collections). I'm working on fixing swingset, but I don't know that I can finish it in time for next week's deadline.

Also, you can't store Promises in *durable* objects/collections, so any contract code doing that will probably need to change before it can be made upgradable.

The one case where we do this (vaultFactory) looks like it'll be pretty easy to convert now, which means I can deprioritize fixing the swingset bug, and also it brings us closer to durable-izing / upgrade-able-izing the contract.

## Description of the Design

The main thing is that the `state` of `makeVaultManagerKit` needs to have arguments which are `PriceAuthority` and `TimerService`, not `ERef<PriceAuthority>`/etc. I'm looking to see how far upstream that can/should be pushed. Something before the call to `makeVaultManager()` needs to `await`  both arguments, to turn them into a Presence rather than a Promise.

cc @dtribble @turadg

### PR DESCRIPTION
**Pull request by warner**
To avoid triggering a swingset bug (#5106), and to prepare for turning
our virtual Kinds into durable Kinds, we need to not store Promises in
virtualized data. In addition, storing a Presence instead of a Promise
can provide a small performance improvement.

Currently, the only case where we store Promises in vdata is in
VaultManager, which stores Promises for `priceAuthority` and
`timerService` in its `state` object.

This changes the setup code to `await` both objects before handing
them to `makeVaultManager`, to ensure that we store Presences, not
Promises.

closes #5121
refs #5106

### CODE REVIEW

File: packages/run-protocol/src/econ-behaviors.js [hunk 1]
```diff
@@ -281,18 +281,19 @@ export const startVaultFactory = async (
     ]);
   const ammPublicFacet = await E(zoe).getPublicFacet(ammInstance);
   const feeMintAccess = await feeMintAccessP;
-
+  const pa = await priceAuthority;
+  const timer = await chainTimerService;
```
Comment (turadg) [inline packages/run-protocol/src/econ-behaviors.js:287]: we could be awaiting all those in the `Promise.all` to start in parallel but that does obscure readability.

I figure this whole file will get some cleanup soon.

**Review by turadg — APPROVED** [review]
