### PR TITLE
liveslots: don't pin the interior queueMessage promise

### LINKED ISSUE #3482: pendingPromises retains interior result Promise by mistake
## Describe the bug

While investigating #3406, I found an object retention problem that affected both XS and V8.

The test case is described in https://github.com/Agoric/agoric-sdk/issues/3406#issuecomment-881615731

When I implemented GC in liveslots, as I replaced the strong references of `slotToVal` with WeakRefs, I wanted to avoid changing the behavior of Promises (since we don't do the same kind of GC tracking on promises). I added a `Set` named `pendingPromises`, and everywhere we added a promise to `slotToVal`, I also added it to the set. The set keeps a strong reference to the Promise until it gets resolved, at which point we remove it from the set.

However, I also added another Promise to this set, which was *not* being tracked in `slotToVal`. The `queueMessage` function is responsible for outbound messages: it serializes the arguments, allocates a result promise, performs the `syscall.send`, subscribes to the result promise, and arranges for the caller to be notified when the results come back. `queueMessage` is called from the `fulfilledHandler` of the `HandledPromise` created by `makeImportedPresence` (to handle `E(presence).foo()`), and also by the `unfulfilledHandler` of the HP created by `makeImportedPromise` (for `E(promise).foo()`.

In both cases, the handler is *not* called during the same turn as the user-level code that invoked `E()`, because that would be a synchrony/reentrancy hazard. So the caller gets one promise (named `returnedP`), and the handler returns its own promise (named `p`). The HandledPromise implementation basically does a `p.then(result => resolveReturnedP(result), err => rejectReturnedP(err))`, forwarding `returnedP` to `p`.

To make sure userspace can take `returnedP` and pass it through other messages (and that the promise's identity is tracked correctly), `queueMessage` registers `returnedP` in the slotToVal/valToSlot tables. The `vpid` used as the `result:` in the `syscall.send` maps to `returnedP`, not `p`. `queueMessage` does a `pendingPromises.add(returnedP)` just before it returns `p`.

The problem was that `makeImportedPromise` *also* did a `pendingPromises.add(p)`, right next to the call to `importedPromisesByPromiseID.set(vpid, pRec)`, which it uses to track the resolver and rejector. So for the case of `queueMessage`'s result promises, we were pinning both the `returnedP` (which gets dropped when `dispatch.notify` tells us about the resolution), *and* `p` (which never got dropped). By keeping `p` alive, we were also keeping all the resolution values alive (because Promises keep their resolutions alive, because someone might call `.then` on the Promise later). This was inhibiting most of the potential GC in our system.

The only objects we could drop would be ones that arrived as arguments, rather than arriving in a resolution.

For historical reasons, it seems that `makeImportedPromise` is serving two purposes, and we think it'd be more accurate to rename it to `makePipelinablePromise`.

One purpose is to build the `p` result promise inside `queueMessage`. For this case, the promise should *not* be added to `pendingPromises`, because we don't actually need to keep it alive. It only needs to last long enough for the HP fulfilled/unfulfilled handler to do a `.then` on it.

The second purpose is to build an imported promise, as when an inbound message argument (or promise resolution data) includes a Promise that is decided by some other vat. This promise *should* be kept alive in `pendingPromises`, and will be removed from there when it gets resolved via some subsequent `dispatch.notify`.

The reason we want to keep these alive is to prevent userspace sensitivity to GC. The scenario is:

* vat1 sends a message to vat2 whose arguments include a Promise
  * vat2 receives the imported promise as pA, uses a WeakRef to recognize it, then drops it
  * pA is garbage collected
* vat1 sends a new message to vat2, including the same Promise
  * vat2 receives a new pB, which maps to the same vpid as pA did
  * vat2 looks it up in the WeakMap, sees it isn't there, and can tell that GC happened

If vat2 uses `.then` on the Promise it received, that might or might not keep the Promise alive. Liveslots holds on to the resolver/rejector for the promise (to handle a `dispatch.notify` for that vpid), which might or might not keep the Promise alive (in practice I think it does). But I don't want to rely upon the latter, and we certainly can't rely upon the former. The possibility of attached callbacks means we can't re-create a Promise that is indistinguishable from the original. So the safest approach is to just make sure the Promise doesn't get collected, at least until it's resolved. Hence `pendingPromises.add`.

So our plan is:
* remove the `pendingPromises.add(p)` from inside `makeImportedPromise`
* rename `makeImportedPromise` to `makePipelinedPromise`
* change `convertSlotToVal` to add a `pendingPromises.add(val)` in the clause that handles `type === 'promise'`
* also fix #3240 by adding an extra `setImmediate`, otherwise V8 doesn't seem to run all the finalizers it should

It might be better to put the `pendingPromises.add` inside `registerValue` instead, since we do other GC tracking there (for objects). However `registerValue` is called for every value, not just newly allocated ones, and I'd need to be sure that we weren't adding *resolved* promises too. That would be bad, it would keep those promises around forever, not just until they were resolved.

There's an additional case I need to investigate: we drop the Promise when it becomes resolved, but if userspace retains the ability to recognize the original, it might still be able to sense GC after that point. We prevent this for Representatives and Presences by commandeering `WeakMap` and `WeakSet` when used with keys that have vrefs associated with them. Maybe the VOM needs to recognize when a Promise is used as a key, and keep it alive for longer than usual.

### PR DESCRIPTION
**Pull request by warner**
'makeImportedPromise' was originally just for imported promises, but was soon
recruited to supply the result promises that come back from E() eventual-send
operations too. During this transition, the responsibility for registering
and retaining the returned Promise got fuzzy. When slotToVal was changed to
use a WeakRef instead of a strong reference, the `pendingPromises` set was
[introduced](fe93b3dba3b023e0d8255584add3aabaf11dfea1) to keep these alive
until they got resolved.

During that process, I went too far and changed `queueMessage` to stash its
interior `p` Promise in `pendingPromises`. This is the HandledPromise that
enables messages to be pipelined to the future result of the `queueMessage`
invocation, but it is *not* the one provided to userspace (HP's handlers are
invoked a turn later, to prevent a reentrancy hazard, so the
userspace-visible Promise has come and gone by the time `queueMessage` runs).
That userspace promise is registered under the result vpid, and kept alive
with `pendingPromises`, and resolved when a `dispatch.notify` arrives, but
the interior `p` promise needs none of those things.

By adding `p` to `pendingPromises` but not registering it for processing
during `dispatch.notify`, it was kept alive forever, even after being
resolved. And a resolved Promise necessarily keeps its resolution value
alive. The consequence was that any Presence returned through the result of
off-vat E() call was kept alive forever, and never made available for garbage
collection.

The fix is to refactor the code slightly. We rename `makeImportedPromise` to
`makePipelinablePromise` to make it clear that the function is not only for
promise imports. We stop using `pendingPromises` to pin the return value of
`makePipelinablePromise`, and leave that up to the caller. When that caller
is `convertValToSlot` (the original imported promise case), we add a
`pendingPromises.add` to pin those promises. When the caller is
`queueMessage`, we continue to not pin the interior `p`.

This was a liveslots bug, and not specific to XS or V8.

fixes #3482

### CODE REVIEW

**Review by michaelfig — APPROVED** [review]
LGTM!  Glad you were able to sort this out.

File: packages/SwingSet/test/gc/test-gc-vat.js [hunk 1]
```diff
@@ -78,4 +92,64 @@ async function dropPresence(t, dropExport) {
...
+  // confirm that zoe is exporting it
+  t.is(findClist(c, zoeID, invitation), 'o+1');
+  t.true(dumpClist(c).includes(`${invitation}/${zoeID}/o+1`));
+  // confirm that vat-target has not seen it yet
+  t.is(findClist(c, targetID, invitation), undefined);
+
+  // console.log(c.dump().kernelTable);
+  console.log(`calling makeInvitation`);
+
+  // Then we ask bootstrap to ask vat-target to ask vat-fake-zoe for the
```
Comment (mhofman) [inline packages/SwingSet/test/gc/test-gc-vat.js:143]: Funny that this test is about making sure our game of telephone has expected "losses" ;)

**Review by mhofman — COMMENTED** [review]
I have to admit, I'm not yet familiar enough with how promise resolution is tracked in swingset to understand the full ramifications of the change, but thanks for the detailed explanation!
