### PR TITLE
fix: declare amountMathKind parameter to makeissuerkit optional

### LINKED ISSUE #1373: The mathHelperName parameter in the makeIssuerKit method should be declared optional.
The mathHelperName parameter in the makeIssuerKit method should be declared optional.

_Originally posted by @erights in https://github.com/Agoric/agoric-sdk/pull/1357_

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
The mathHelperName was changed to amountMathKind, and it's optional in
the code. This updates the type declaration to match.

fixes: #1373

### CODE REVIEW

File: packages/ERTP/src/types.js [hunk 1]
```diff
@@ -183,7 +183,7 @@
 /**
  * @callback MakeIssuerKit
  * @param {string} allegedName
- * @param {AmountMathKind} amountMathKind
+ * @param {AmountMathKind?} amountMathKind
```
Comment (katelynsills) [inline packages/ERTP/src/types.js]:
```suggestion
 * @param {AmountMathKind=} amountMathKind
```
? will allow null but I think we actually want undefined

**Review by katelynsills — CHANGES_REQUESTED** [review]

File: packages/ERTP/src/types.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/ERTP/src/types.js]: @katelynsills, It feels like I've gotten the opposite advice previously. Is there a doc I can refer to?

Comment (katelynsills) [reply packages/ERTP/src/types.js]: Hmm, I was able to mouse-over the definition and see that it allowed for null. If you change it to `=` it will show that it allows for undefined instead.

**Review by katelynsills — APPROVED** [review]
