### PR TITLE
fix(cli): handle not found error in vstorage requests

### LINKED ISSUE #8535: Error when trying to check bid list in CLI
## Describe the bug
As part of upgrade 12 testing, I noticed while using the CLI that I was unable to run the command to see my bids and received an error I had not previously received from testing in the past.

## To Reproduce
-  [ ] git clone https://github.com/Agoric/agoric-sdk
- [ ] cd agoric-sdk
- [ ] SKIP_DOWNLOAD=false ./bin/agd build
- [ ] export PATH=$PWD/bin:$PATH 
- [ ] alias inter="yarn run --silent agops inter"
- [ ] export AGORIC_NET=emerynet
- [ ]  agd keys add test-acct --keyring-backend=test         
override the existing name test-acct [y/N]: y
- [ ] inter bid list --from test-acct --keyring-backend=test

## Expected behavior
I should be able to see my bids (if any)

## Screenshots

brendanotoole@brendans-MacBook-Pro agoric-sdk % inter bid list --from test-acct --keyring-backend=test
(Error#1)
Error#1: error code 38 reading data of published.wallet.agoric10r0mrv6dyyq8hnn4ek77sc2yllc6fs9gper8gs: no data for vstorage path: not found

  at packages/agoric-cli/src/lib/rpc.js:82:17
  at async Object.readAt (packages/agoric-cli/src/lib/rpc.js:118:19)
  at async Object.readFully (packages/agoric-cli/src/lib/rpc.js:140:38)
  at async storedWalletState (packages/agoric-cli/src/lib/wallet.js:215:21)
  at async Promise.all (index 1)
  at async Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:571:34)

brendanotoole@brendans-MacBook-Pro agoric-sdk % inter bid list --all --from test-acct --keyring-backend=test
(Error#1)
Error#1: error code 38 reading data of published.wallet.agoric10r0mrv6dyyq8hnn4ek77sc2yllc6fs9gper8gs: no data for vstorage path: not found

  at packages/agoric-cli/src/lib/rpc.js:82:17
  at async Object.readAt (packages/agoric-cli/src/lib/rpc.js:118:19)
  at async Object.readFully (packages/agoric-cli/src/lib/rpc.js:140:38)
  at async storedWalletState (packages/agoric-cli/src/lib/wallet.js:215:21)
  at async Promise.all (index 1)
  at async Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:571:34)

### PR DESCRIPTION
**Pull request by mhofman**
closes: #8535
refs: #8348

## Description

#8348 changed the validation of vstorage paths, including the errors returned for invalid or not found paths.

Unfortunately some code had hardcoded part of the error message when iterating over values to break out of the iteration, resulting in the error terminating abruptly instead.

This change uses the more stable error code of the error returned by the RPC server.

### Security Considerations

None

### Scaling Considerations

None

### Documentation Considerations

None

### Testing Considerations

No integration test exists for this. I'm not sure where it could live.
Tested manually.

### Upgrade Considerations

Should be backported to the `release-mainnet1B` for consistency

### CODE REVIEW

File: packages/agoric-cli/src/lib/rpc.js [hunk 1]
```diff
@@ -143,7 +147,11 @@ export const makeVStorage = (powers, config = networkConfig) => {
           ));
           // console.debug('readAt returned', { blockHeight });
         } catch (err) {
-          if (err.message.match(/unknown request/)) {
+          if (
+            err.message.match(/unknown request/) ||
```
Comment (samsiegart) [inline packages/agoric-cli/src/lib/rpc.js]: Any reason to keep this check around or can we remove it?

**Review by samsiegart — APPROVED** [review]
Just one question but lgtm either way

File: packages/agoric-cli/src/lib/rpc.js (hunk 1 above)
Comment (mhofman) [reply packages/agoric-cli/src/lib/rpc.js]: to not break mainnet and devnet users, until each is respectively updated.

Comment (samsiegart) [reply packages/agoric-cli/src/lib/rpc.js]: Ah I just tested on devnet, I'm getting error code "6", so looks like the code changed and not just the message

Comment (mhofman) [reply packages/agoric-cli/src/lib/rpc.js]: Yup: https://github.com/Agoric/agoric-sdk/commit/dafc7c1708977aaa55e245dc09a73859cf1df192#diff-5ddf33f542fbc7bc5cec3cef81c28de46085850594ce2f5c324115b88cd8309aR59

File: packages/agoric-cli/src/lib/rpc.js [hunk 2]
```diff
@@ -143,7 +147,11 @@ export const makeVStorage = (powers, config = networkConfig) => {
...
+            // ErrNotFound CosmosSDK error
+            (err.code === 38 && err.codespace === 'sdk')
+          ) {
```
Comment (gibson042) [inline packages/agoric-cli/src/lib/rpc.js]: We should probably explain a little more here.
```suggestion
          if (
            // CosmosSDK ErrNotFound; there is no data at the path
            (err.codespace === 'sdk' && err.code === 38) ||
            // CosmosSDK ErrUnknownRequest; misrepresentation of the same until
            // https://github.com/Agoric/agoric-sdk/commit/dafc7c1708977aaa55e245dc09a73859cf1df192
            // TODO remove after upgrade-12
            err.message.match(/unknown request/)
          ) {
```

**Review by gibson042 — APPROVED** [review]

**Comment by mhofman** [comment]
@gibson042 I added a test suite to vstorage querier. PTAL

File: golang/cosmos/x/vstorage/keeper/querier_test.go [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+		}...)
+	}
+
+	// Test data endpoint with valid vstorage path
+	testCases = append(testCases, []testCase{
+		{label: "data: non-existent path",
+			path: []string{"data", "bar"},
+			// DO NOT CHANGE
+			// The UI and CLI check for the specific cosmos-sdk error code & codespace
+			err: sdkerrors.ErrNotFound,
```
Comment (gibson042) [inline golang/cosmos/x/vstorage/keeper/querier_test.go:65]: Would it be going too far to also assert somewhere that  `sdkerrors.ErrNotFound` itself corresponds with code 38 in codespace "sdk"? That would capture our requirement of stability in cosmos-sdk.

**Review by gibson042 — APPROVED** [review]
Nice!

**Review by dckc — COMMENTED** [review]
I defer to other reviewers.
_filing this review to get it off my queue_
