### PR TITLE
fix(deployment): default `faucet-helper.sh` to `show-rpcaddrs`

### LINKED ISSUE #5220: Failed `faucet-helper.sh` in `deployment-test`
## Describe the bug

Failure found at https://github.com/Agoric/agoric-sdk/runs/6165114255?check_suite_focus=true#step:10:2649

```
curl: (6) Could not resolve host: setup.agoric.net
```

This was introduced when changing the `faucet-helper.sh` script to use `https://$networkName.agoric.net/network-config`

## To Reproduce

Run the `deployment-test` CI check.

## Expected behavior
No error.

## Platform Environment
 - what OS are you using? what version of Node.js? CI runner
 - is there anything special/unusual about your platform? CI
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`) `@agoric/sdk@16-91-g2b2c9666f`

## Additional context
None.

## Screenshots
image

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #5220

## Description

Default to local configuration if remote `*.agoric.net` config is not available.

### CODE REVIEW

**Review by mhofman — APPROVED** [review]

**Review by arirubinstein — APPROVED** [review]

File: packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh [hunk 1]
```diff
@@ -29,9 +29,13 @@ show-faucet-address)
...
 
 networkName=$(basename "$thisdir")
-netconfig=$(curl "https://$networkName.agoric.net/network-config")
-chainName=$(echo "$netconfig" | jq -r .chainName)
-read -r -a origRpcAddrs <<<"$(echo "$netconfig" | jq -r .rpcAddrs[])"
+if netconfig=$(curl "https://$networkName.agoric.net/network-config"); then
+  chainName=$(echo "$netconfig" | jq -r .chainName)
+  read -r -a origRpcAddrs <<<"$(echo "$netconfig" | jq -r .rpcAddrs[])"
+else
+  chainName=$(cat "$thisdir/ag-chain-cosmos/chain-name.txt")
```
Comment (mhofman) [inline packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh:36]: I was considering doing `ag-setup-cosmos show-config` instead to keep the alternatives consistent, but this roughly does the same thing
