### PR TITLE
test(cosmic-swingset): Implement subprocess-based retries for metrics comparison

### LINKED ISSUE #11175: cosmic-swingset test flaking: Prometheus metric definitions
## Describe the bug

Today I began noticing spurious failures in the "Prometheus metric definitions" test.

[This PR](https://github.com/Agoric/agoric-sdk/pull/11166) just refactors tests, and while it fails on [test-cosmic-swingset (20.x)](https://github.com/Agoric/agoric-sdk/actions/runs/14112092780/job/39545160798#logs), it passes **test-cosmic-swingset (18.x)**. At first It thought it was some interaction with Node version, but the next one fails on 18.x and not 20.x.

[This PR](https://github.com/Agoric/agoric-sdk/pull/11170/files) does nothing with cosmic-swingset and [fails on it](https://github.com/Agoric/agoric-sdk/actions/runs/14116240596/job/39547188650?pr=11170):
```
not ok 5 - prometheus › Prometheus metric definitions %ava-dur=47414ms
#   compared 113 "#"-prefixed meta lines
#   compared 247 keys
#   compared 77 values
  ---
    name: AssertionError
    message: >-
      "heapStats_total_global_handles_size" values must match - direct 638[97](https://github.com/Agoric/agoric-sdk/actions/runs/14116240596/job/39547188650?pr=11170#step:6:98)6 vs.
      slog 630784
    assertion: is
    values:
      'Difference (- actual, + expected):': |-
        - 630784
        + 638976
    at: 'file://test/prometheus.test.js:174:9'
```

# Solution

I expect it's due to this PR that landed today,
- https://github.com/Agoric/agoric-sdk/pull/11132

### PR DESCRIPTION
**Pull request by gibson042**
`@opentelemetry/sdk-metrics` keeps too much internal state to support simple
retries, so instead we spawn a subprocess. Fortunately, this kludge will go
away when metrics collection is fully extracted from swingset and the
kernel: #11405

Fixes #11175
Ref #11392

## Description

The first commit extends shutdown logic for slog-sender-pipe and otel-metrics, which I hoped was the root cause of flakiness here [narrator: "it wasn't"].

The second commit updates packages/cosmic-swingset/test/prometheus.test.ts with a kludgy bit of code that uses the current test implementation for the first try, but then on any subsequent try it instead spawns a `yarn test $SELF` subprocess with an IS_SUBPROCESS_RETRY environment variable, echoes the combined stdout/stderr from that subprocess, and asserts a successful exit status. That subprocess does not perform any retries of its own, and furthermore expands comparison fuzziness for metrics that are particularly susceptible to divergence, especially under what seems to be increased load in the subprocess (_logging failure messages for those metrics rather than actually failing their assertions_).

Fortunately, the latter code should be short-lived (cf. #11405).

### Security Considerations
None known.

### Scaling Considerations
Shutdown may be slower, but that's better than misbehavior from impatience.

### Documentation Considerations
n/a

### Upgrade Considerations
Nothing special is needed, and CI fully covers the expected testing/validation.

### CODE REVIEW

File: packages/telemetry/src/slog-sender-pipe.js [hunk 1]
```diff
@@ -72,6 +73,16 @@ export const makeSlogSender = async options => {
     env,
   });
   // logger.log('done fork');
+
+  const exitKit = makePromiseKit();
+  cp.on('error', error => {
+    // An exit event *might* be coming, so wait a tick.
```
Comment (mhofman) [inline packages/telemetry/src/slog-sender-pipe.js:79]: Have we noticed error events coming before exit events? And we want to ignore them in that case?

File: packages/cosmic-swingset/test/prometheus.test.ts [hunk 2]
```diff
@@ -157,17 +196,19 @@ avaRetry(test, 'Prometheus metric definitions', async t => {
...
     );
     comparisonCount += 1;
-    const [fuzziness, unit] = (() => {
+    const [fuzziness, unit, ignorable] = (() => {
       if (fuzzinessOverrides.has(name)) return fuzzinessOverrides.get(name);
 
-      // Default to 100 milliseconds of wiggle room for timing data.
+      // Default to 100 milliseconds of wiggle room for timing data, but expand
+      // that to 500 under subprocess retry (where the greater load can widen
+      // discrepancies).
```
Comment (mhofman) [inline packages/cosmic-swingset/test/prometheus.test.ts:209]: Why is the load greater in a retry?

**Review by mhofman — APPROVED** [review]
So we're not just retrying the Prometheus test, but also adapting the checks in that retry?

File: packages/telemetry/src/slog-sender-pipe.js (hunk 1 above)
Comment (gibson042) [reply packages/telemetry/src/slog-sender-pipe.js:79]: I haven't observed them, but they're explicitly documented as possible: https://nodejs.org/docs/latest/api/child_process.html#event-error
<blockquote>
The <code>'exit'</code> event may or may not fire after an error has occurred. When
listening to both the <code>'exit'</code> and <code>'error'</code> events, guard
against accidentally invoking handler functions multiple times.
</blockquote>

And if both are coming, I prefer `exit` here because that has the status code (in a [more general implementation](https://github.com/endojs/endo/blob/d9703bea83d508c5e5e869042addef01110e7686/scripts/esbench.mjs#L235-L244), I propagate data from both).

File: packages/cosmic-swingset/test/prometheus.test.ts (hunk 2 above)
Comment (gibson042) [reply packages/cosmic-swingset/test/prometheus.test.ts:209]: I suspect it's because of AVA's heartbeat IPC.

File: packages/cosmic-swingset/test/prometheus.test.ts [hunk 3]
```diff
@@ -20,7 +22,42 @@ import { makeCosmicSwingsetTestKit } from '../tools/test-kit.js';
...
+        timeout: 2 * 60_000, // 2 minutes
+      })`yarn test ${self}`;
+      // Inspired by media type multipart/* common syntax:
+      // https://www.rfc-editor.org/rfc/rfc2046.html#section-5.1.1
+      console.log(`--subprocess ${child.pid}`);
+      await child;
+      childOk = true;
+    } catch (err) {}
+    if (child) console.log(`\n--subprocess ${child.pid}--\n`);
+    t.true(childOk, 'subprocess retry');
```
Comment (gibson042) [inline packages/cosmic-swingset/test/prometheus.test.ts]: @michaelfig IIRC you had a need for something like this.

**Review by michaelfig — APPROVED** [review]
LGTM!  Just some minor linting issues exposed by CI.

File: packages/cosmic-swingset/test/prometheus.test.ts (hunk 3 above)
Comment (michaelfig) [reply packages/cosmic-swingset/test/prometheus.test.ts]: Yeah, I did a simpler version that's used by `@agoric/internal/src/lib-nodejs/ava-unhandled-rejection.js`.
