### PR TITLE
fix: minor, from purple

### LINKED ISSUE #4312: Remote errors are not passable
## Describe the bug
A remote error, aka an Error unserialized by marshal, is not passable because the `unseriazlize` logic sets the name to `Remote${EC.name}(${errorId})`, which no longer matches the prototype's name check `passStyleOf` does for errors.

## To Reproduce
```js
serialize(unserialize(serialize(harden({ myError: new Error() })));
```

## Expected behavior
nested errors are round-trip-able through multiple serialize / unserialize. See https://github.com/Agoric/agoric-sdk/issues/4337

## Platform Environment
 - what version of the Agoric-SDK are you using? `72cc8d6bcf428596653593708959446fb0a29596`

## Additional context
Since a top level error is exempt from the passable check, a remote error rethrown will likely pass through, albeit noisily annotated.

### PR DESCRIPTION
**Pull request by erights**
Fixes #4312 
Have recognition of passable Error obtain `name` from prototype, skipping any own `name` property on the error instance.

Note several of the places we need to revisit when we admit `error.cause` and `error.errors`.

Inline TODOs reminding us to revisit issues identified by zestival

Rename `keySchema`,`valueSchema` to `keyPattern`,`valuePattern`. Attn @FUDCo 

Some internal clarifying renamings.

### CODE REVIEW

File: packages/marshal/src/helpers/error.js [hunk 1]
```diff
@@ -53,7 +53,7 @@ export const ErrorHelper = harden({
       return check(false, X`Error expected: ${candidate}`);
     }
     const proto = getPrototypeOf(candidate);
-    const { name } = candidate;
+    const { name } = proto;
```
Comment (mhofman) [inline packages/marshal/src/helpers/error.js:55]: Interesting, this is probably the right way to fix https://github.com/Agoric/agoric-sdk/issues/4312, right? Didn't realize this was a serialize / passStyle error instead of a unserialize error.

Comment (erights) [reply packages/marshal/src/helpers/error.js:55]: Yes

**Review by mhofman — APPROVED** [review]
