### PR TITLE
test(boot): Add entropy to Swingset config file names for uniqueness in concurrent testing

### LINKED ISSUE #10092: CI sometimes fails to read swingset config file
## Describe the bug
As seen at https://github.com/Agoric/agoric-sdk/actions/runs/10873209314/job/30169121954?pr=10091#step:5:1
```
Run cd packages/boot && yarn test | $TEST_COLLECT
  cd packages/boot && yarn test | $TEST_COLLECT
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    AGORIC_AVA_USE_TAP: true
    TEST_COLLECT: tee -a _testoutput.txt
    NODE_V8_COVERAGE: coverage
    GH_ENGINE: 18.x
    CI_NODE_INDEX: 1
    CI_NODE_TOTAL: 4
    ESM_DISABLE_CACHE: true
yarn run v1.22.22
$ ava
TAP version 13
failed to load bundles/decentral-itest-vaults-config.json
not ok 1 - net-ibc-upgrade › before hook %ava-dur=96ms
#   REJECTED from ava test.before(): (SyntaxError#1)
#   SyntaxError#1: Unexpected end of JSON input
#       at JSON.parse (<anonymous>)
#       at loadSwingsetConfigFile (/home/runner/work/agoric-sdk/agoric-sdk/packages/SwingSet/src/controller/initializeSwingset.js:239:25)
#       at async ensureSwingsetInitialized (file:///home/runner/work/agoric-sdk/agoric-sdk/packages/cosmic-swingset/src/launch-chain.js:146:18)
#       at async buildSwingset (file:///home/runner/work/agoric-sdk/agoric-sdk/packages/cosmic-swingset/src/launch-chain.js:218:32)
#       at makeSwingsetTestKit (/home/runner/work/agoric-sdk/agoric-sdk/packages/boot/tools/supports.ts:501:48)
#       at makeTestContext (/home/runner/work/agoric-sdk/agoric-sdk/packages/boot/test/bootstrapTests/net-ibc-upgrade.test.ts:37:27)
#       at <anonymous> (/home/runner/work/agoric-sdk/agoric-sdk/packages/boot/test/bootstrapTests/net-ibc-upgrade.test.ts:49:15)
```

~~I suspect this can be fixed by adding a `flush: true` option to the [`writeFile` call in packages/boot/tools/supports.ts](https://github.com/Agoric/agoric-sdk/blob/e67cd918f33dafb1708bd4341f2a737b79fa574f/packages/boot/tools/supports.ts#L133), but only after raising the Node.js version bar to at least [v20.10.0](https://nodejs.org/docs/latest/api/fs.html#fspromiseswritefilefile-data-options) (cf. https://github.com/nodejs/node/pull/50009 for background). And if so, then we may want to consider using it in even more `writeFile`s. A possible alternative would be reading back the expected size, but that seems too heavyweight.~~

Subsequent conversation on Slack identified a more likely culprit as concurrently running tests writing and reading against the same file name, a hypothesis which was locally reproducible:
<details>

```console
node --input-type=module -e '
import fs from "node:fs";
import fsp from "node:fs/promises";
const sink = () => {};
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const waitFor = thunk => new Promise(async (resolve, reject) => {
  try {
    while (!(await thunk())) await delay(100);
    resolve();
  } catch (err) { reject(err); }
});

const path = "./dummy";
const data = Object.fromEntries(
  Array.from({ length: 10000 },
  (_, i) => [`key${i.toString().padStart(6, "0")}`, i]),
);
const fn = async worker => {
  for (let i = 0; i < 1000; i++) {
    await fsp.unlink(path).then(sink, sink);
    await waitFor(() => fs.statSync(path, { throwIfNoEntry: false }) === undefined);
    await fsp.writeFile(path, JSON.stringify(data), "utf-8");
    try {
      JSON.parse(fs.readFileSync(path, "utf-8"));
    } catch (err) {
      if (err.code === "ENOENT") continue;
      throw Error(`worker ${worker} failed on attempt ${i}`, { cause: err });
    }
  }      
  return;                       
};
for (let i = 0; i < 2; i++) fn(i);
'
file:///tmp/[eval1]:27
      throw Error(`worker ${worker} failed on attempt ${i}`, { cause: err });
            ^

Error: worker 0 failed on attempt 43
    at fn (file:///tmp/[eval1]:27:13) {
  [cause]: SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at fn (file:///tmp/[eval1]:24:12)
}

Node.js v18.18.2
```

</details>

We should instead introduce a differentiating component in these Swingset config file names, e.g. random and/or otherwise unique per potentially-concurrent test.

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #10092

## Description
Rather than having concurrently-running tests fight over e.g. **bundles/decentral-itest-vaults-config.json**, add some entropy to the file name. In this PR, I've chosen **bundles/config.${optionalLabel}.${dateTime}.${randomDigits}.decentral-itest-vaults-config.json**, although no current test is taking advantage of the label option.

### Security Considerations
n/a

### Scaling Considerations
There's a chance that local `bundles` directories fill up with identical config files. They're easily cleaned up by hand, but if this becomes an actual problem then we can add package.json `clean` scripts for that, or even update `getNodeTestVaultsConfig` to check for and reuse such files.

### Documentation Considerations
n/a

### Testing Considerations
n/a

### Upgrade Considerations
n/a

### CODE REVIEW

**Comment by mhofman** [comment]
> or even update `getNodeTestVaultsConfig` to check for and reuse such files.

Oh I didn't think of that! Suffixing the file based on the content would fix this issue! As long as we write the file atomically of course.

File: packages/boot/tools/supports.ts [hunk 1]
```diff
@@ -129,7 +130,14 @@ export const getNodeTestVaultsConfig = async (
     );
   }
 
-  const testConfigPath = `${bundleDir}/${basename(specifier)}`;
+  const configFilenameParts = [
+    'config',
+    discriminator,
+    new Date().toISOString().replaceAll(/[^0-9TZ]/g, ''),
+    String(Math.random()).replace(/^[^.]*[.]/, ''),
```
Comment (siarhei-agoric) [inline packages/boot/tools/supports.ts]: I would prefer a fixed-width random component. If I understand correctly, this can produce quite a variable range of possible lengths of digits.

**Comment by siarhei-agoric** [comment]
> > or even update `getNodeTestVaultsConfig` to check for and reuse such files.
> 
> Oh I didn't think of that! Suffixing the file based on the content would fix this issue! As long as we write the file atomically of course.

Right, a content hash would be cool. Though keeping the file name reasonably short would also be nice, which unfortunately puts it at odds with strong hashing...

On a second thought, if we anticipate hundreds/thousands of slightly different config files then it is entirely possible that it would be faster to just create a new file every time as opposed to scanning the directory to find the one we need. Depending on how this gets implemented, I can see that a copy of desired config might have to be generated in-memory regardless even if just to get its hash. If that is the case, then we might as well just write it out into a file.

Further, if the config holding directory has any sort of extended persistence then we should implement at least a rudimentary self-clean-up capability right away.

File: packages/boot/tools/supports.ts (hunk 1 above)
Comment (gibson042) [reply packages/boot/tools/supports.ts]: Done; this part will be 8 decimal digits.

**Comment by gibson042** [comment]
> Further, if the config holding directory has any sort of extended persistence then we should implement at least a rudimentary self-clean-up capability right away.

Done; `yarn clean` now removes the files.

**Review by siarhei-agoric — APPROVED** [review]
Ship it!
