### PR TITLE
Swing-store export data outside of genesis file

### LINKED ISSUE #9567: Genesis import fails for large exports
## Describe the bug
Generating a new genesis through `agd export` results in a `genesis.json` that is too large to be imported. Besides the large amount of memory used, the cosmos sdk attempts to store the original genesis file as is in its golevelDB, which has a limit of 4GB per document.

## To Reproduce
`agd export` on mainnet or devnet, followed by `agd start` using the new genesis

## Expected behavior
While large genesis can result in a huge RAM consumption, it should at least be possible to import.

## Platform Environment
upgrade-15 and master on mainnet or devnet

## Screenshots
```
panic: snappy: decoded block is too large [recovered]
        panic: snappy: decoded block is too large [recovered]
        panic: snappy: decoded block is too large

goroutine 86 [running]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction.func1()
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:763 +0xc5
panic({0x7f9222a12620, 0xc0001edcc0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact.func1()
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:159 +0x9b
panic({0x7f9222a12620, 0xc0001edcc0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/golang/snappy.Encode({0xc0011fe118?, 0x12?, 0x0?}, {0xc002b00000?, 0x7f922299a500?, 0x7f92203e270a?})
        /go/pkg/mod/github.com/golang/snappy@v0.0.4/encode.go:22 +0x2d1
github.com/syndtr/goleveldb/leveldb/table.(*Writer).writeBlock(0xc000f36000, 0xc000f36060, 0xc000f36060?)
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table/writer.go:172 +0x139
github.com/syndtr/goleveldb/leveldb/table.(*Writer).finishBlock(0xc000f36000)
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table/writer.go:223 +0x46
github.com/syndtr/goleveldb/leveldb/table.(*Writer).Append(0xc000f36000, {0x1c563030000, 0x12, 0x194fec000}, {0x1c563030012, 0x194feb506, 0x194febfee})
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table/writer.go:256 +0x253
github.com/syndtr/goleveldb/leveldb.(*tWriter).append(0xc0005a4de0, {0x1c563030000, 0x12, 0x194fec000}, {0x1c563030012, 0x194feb506, 0x194febfee})
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table.go:558 +0x1e5
github.com/syndtr/goleveldb/leveldb.(*tOps).createFrom(0x7f92203ebdd3?, {0x7f9222d9ed40, 0xc001274080})
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/table.go:397 +0x16d
github.com/syndtr/goleveldb/leveldb.(*session).flushMemdb(0xc000defa40, 0xc0011fa3c0, 0xc0001917a0, 0xc001663b10?)
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session_compaction.go:35 +0x116
github.com/syndtr/goleveldb/leveldb.(*DB).memCompaction.func1(0xc0005a4401?)
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:305 +0xa5
github.com/syndtr/goleveldb/leveldb.(*compactionTransactFunc).run(0x0?, 0x0?)
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:242 +0x1f
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact(0xc00066afc0, {0x7f9221dc1dbb, 0xb}, {0x7f9222d76f48, 0xc001650030})
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:186 +0x217
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransactFunc(...)
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:253
github.com/syndtr/goleveldb/leveldb.(*DB).memCompaction(0xc00066afc0)
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:303 +0x3e8
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc00066afc0)
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:777 +0x93
created by github.com/syndtr/goleveldb/leveldb.openDB
        /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:156 +0x5d8
```

### PR DESCRIPTION
**Pull request by mhofman**
Closes #9567

## Description
Stores the swing-store export data outside of the genesis file, and only include a hash of it in genesis for validation.

This is the bulk of the data in the genesis file (on mainnet 6GB vs 300MB for the rest), and it serves little purpose to keep it in there. Furthermore golevelDB chokes when cosmos attempts to store the genesis file inside the DB (limit of 4GB documents)

### Security Considerations
None, the data remains validated

### Scaling Considerations
Reduces memory usage on genesis export / import. Furthermore we avoid iterating over the data twice on import, which is painfully slow for IAVL.

### Documentation Considerations
None

### Testing Considerations
Added a3p acceptance test

Manually tested as follow:
```
cd packages/cosmic-swingset
make scenario2-setup
make scenario2-run-chain
# wait until there are blocks, then kill
mkdir t1/n0/export
agd --home t1/n0 export --export-dir t1/n0/export
agd --home t1/n0 tendermint unsafe-reset-all
mv t1/n0/export/* t1/n0/config
make scenario2-run-chain
# verify blocks are being produced after genesis restart
```

### Upgrade Considerations
There is a compatibility mode to load genesis files with export data embedded.

### CODE REVIEW

**Comment by toliaqat** [comment]
@mhofman, This is a great direction and will help us faster imports and exports. Thanks for working on this.
Can you please add new tests covering new code paths?

**Comment by mhofman** [comment]
> Can you please add new tests covering new code paths?

There are not unit tests covering genesis import / export, so it'd be a significant effort to add those now. I'll try to revive the integration test that existed, but given this feature is not used for normal operations, I'd prefer to not block on tests.

**Comment by mhofman** [comment]
@toliaqat I added an integration test of mainfork. See https://github.com/Agoric/agoric-sdk/actions/runs/9621035132/job/26540251077?pr=9549#step:9:2017

PTAL

File: golang/cosmos/x/swingset/genesis.go [hunk 1]
```diff
@@ -46,15 +54,62 @@ func InitGenesis(ctx sdk.Context, k Keeper, swingStoreExportsHandler *SwingStore
...
+		}
+	} else {
+		hashParts := strings.SplitN(data.SwingStoreExportDataHash, ":", 2)
+		if len(hashParts) != 2 {
+			panic(fmt.Errorf("invalid swing-store export data hash %s", data.SwingStoreExportDataHash))
+		}
+		if hashParts[0] != "sha256" {
+			panic(fmt.Errorf("invalid swing-store export data hash algorithm %s, expected sha256", hashParts[0]))
+		}
+		sha256Hash, err := hex.DecodeString(hashParts[1])
```
Comment (warner) [inline golang/cosmos/x/swingset/genesis.go:77]: nit: I'd name this `expectedSHA256Hash` or `expectedHash`

File: golang/cosmos/x/swingset/genesis.go [hunk 2]
```diff
@@ -46,15 +54,62 @@ func InitGenesis(ctx sdk.Context, k Keeper, swingStoreExportsHandler *SwingStore
...
+			return agoric.NewKVHookingReader(kvReader, func(entry agoric.KVEntry) error {
+				key := []byte(entry.Key())
+
+				if !entry.HasValue() {
+					swingStore.Delete(key)
+				} else {
+					swingStore.Set(key, []byte(entry.StringValue()))
+				}
+
+				return encoder.Encode(entry)
```
Comment (warner) [inline golang/cosmos/x/swingset/genesis.go:104]: I don't know that I'm reading this correctly, but it looks like something else is reading and parsing an artifact to produce `entry.Key()` and maybe-nil values, then this function JSON-encodes the entry we got, and then we hash the resulting JSON-encoded bytes. Is that about right?

I'd prefer that we hash the original, and *then* do whatever parsing we need to use the data. This approach is vulnerable to disagreements between the first parser and the JSON encoder. I can't name any cases that would actually trigger it, but say `json.NewEncoder` does many-to-one Unicode normalization of some codepoint X into bytes Z1Z2, and also serializes codepoint Y into the same Z1Z2. Then this could be tricked into passing Y into the swingstore data when the creator meant (and hashed) X.

File: golang/cosmos/x/swingset/genesis.go [hunk 3]
```diff
@@ -131,7 +182,17 @@ func (eventHandler swingStoreGenesisEventHandler) OnExportRetrieved(provider kee
 
 	artifactsProvider := keeper.SwingStoreExportProvider{
 		GetExportDataReader: func() (agoric.KVEntryReader, error) {
-			return nil, nil
+			exportDataIterator := eventHandler.swingStore.Iterator(nil, nil)
+			kvReader := agoric.NewKVIteratorReader(exportDataIterator)
+			eventHandler.hasher.Reset()
```
Comment (warner) [inline golang/cosmos/x/swingset/genesis.go:187]: Why does the hasher need to be reset here? Is it used more than once? I want to make sure we don't have a bug where we only actually hash the last bit of the data, because we reset it on every loop or something.

File: golang/cosmos/x/swingset/genesis.go [hunk 4]
```diff
@@ -131,7 +182,17 @@ func (eventHandler swingStoreGenesisEventHandler) OnExportRetrieved(provider kee
...
+			encoder := json.NewEncoder(eventHandler.hasher)
+			encoder.SetEscapeHTML(false)
+
+			return agoric.NewKVHookingReader(kvReader, func(entry agoric.KVEntry) error {
+				return encoder.Encode(entry)
```
Comment (warner) [inline golang/cosmos/x/swingset/genesis.go:192]: Hm, I can see that the "what do we hash" question is tied into the "what does golang encode" question. Giving golang the responsibility for framing/unframing, and then JSON-encoding the key/value pairs for hashing, is safe against concatenation/framing-confusion attacks, even if it's vulnerable to some hypothetical non-injectiveness in JSON.

If we were to, e.g., skip JSON, and just feed the key into the hasher, then feed the value into the hasher, then repeat for each pair: that would be vulnerable to framing confusion (`{ ab: 'cd', ef: 'gh'}` would hash the same as `{a: 'b', c: 'de', fg: 'h'}`). Without some kind of encoding/escaping, there's no way to avoid that (simply using a newline as a framing separator could still be confused with newlines in the keys or values).

One option would be to JSON-encode the key/value pairs first, then have the golang codec (struct? proto?) encode the resulting strings (one string per entry, not one for the key and a second for the value). Then the hasher could be fed those `JSON.stringify([key,value])` strings, which would be safely escaped, and unambiguously framed. It would look weird, eschewing the built-in encoding support in favor of manual JSON, but it would meet my maxim of "hash (sign) what you say, only use what you hash (sign)". Down with "canonical encoding" in secure protocols!

**Review by warner — COMMENTED** [review]
I'm not qualified to review the implementation, but I've thrown in some thoughts on the protocol. I'm merely -0 on hashing a derivative of the data, not -1: if you can't find any other way to do it, and we believe this isn't too hard to change in the future (genesis export is only for debugging right now, we can revisit it before considering relying upon it for an agoric4 replacement chain), then I'm ok with this protocol being landed.

File: golang/cosmos/x/swingset/genesis.go (hunk 2 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/genesis.go:104]: I went back and forth on this until I realized that there is no canonical JSON encoding. As such, hashing the original file isn't quite right. Of course even with a specified JSON encoding of each entry, there is no canonical way in which the entries should appear. In theory we should use an IAVL tree of the data to have a canonical hash :)

Basing the hash on the re-encoding to JSON by the golang encoder is thus motivated both by practicality (it fit better in the abstraction already in place of "export data reader"), and slightly increases the canonical status of the hash.

That said I was also careful that the hash computed this way is exactly equal to `sha256sum` of the file created by golang serialization.

> many-to-one Unicode normalization of some codepoint X into bytes Z1Z2, and also serializes codepoint Y into the same Z1Z2. Then this could be tricked into passing Y into the swingstore data when the creator meant (and hashed) X.

As mentioned above, it's actually the opposite. There are multiple ways to escape the same string value in JSON encodings, and here we're settling on the one that golang implements

File: golang/cosmos/x/swingset/genesis.go (hunk 3 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/genesis.go:187]: Technically `GetExportDataReader` could be called more than once

File: golang/cosmos/x/swingset/genesis.go (hunk 4 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/genesis.go:192]: > Then the hasher could be fed those `JSON.stringify([key,value])` strings, which would be safely escaped, and unambiguously framed.

That's exactly what this does. Bonus is that the hash ends up strictly equal to hashing the resulting file, which is a concatenation of all the JSON stringified entries terminated by new lines

File: golang/cosmos/x/swingset/genesis.go (hunk 2 above)
Comment (warner) [reply golang/cosmos/x/swingset/genesis.go:104]: > there is no canonical JSON encoding
> there is no canonical way in which the entries should appear

Yeah, that's the clue that we can't/shouldn't rely upon "canonical" encoding at all. In general, the creator of the hashed/signed artifact can encode it any way they want: doesn't matter, nobody else will be attempting to encode it in the same way. What matters is that everybody's *decoder* will treat the hashed/signed bytes in the same way.

If we find ourselves wanting a canonical *encoder*, that might mean we're doing encoding on the decoding/verification side, and that's where vulnerabilities live.

File: golang/cosmos/x/swingset/genesis.go (hunk 4 above)
Comment (warner) [reply golang/cosmos/x/swingset/genesis.go:192]: Just to make sure I was clear, you wouldn't extract `key` and `value` from the golang-encoded data and then feed `JSON.stringify([key,value])` to the hasher: that's the vulnerable-to-JSON-weirdness order. Rather, you'd feed `JSON.stringify([key,value])` to the golang *encoder*, and have golang do whatever additional/native encoding it wants on that single-string-per-entry. Then, on the decoding side, you'd first hash that single-string-per-entry, then you do `JSON.parse` to get the key/value that you need to act upon. The rule could also be summarized as "no encoding during decode".

But I hear you, we're fighting against the golang codec pattern, which has already frustrated me in cosmos txn generation/signing. And we're dependent upon their codec being possible to use securely, which isn't a given (the confusion between `nil` and an empty list comes to mind).

File: golang/cosmos/x/swingset/genesis.go (hunk 3 above)
Comment (warner) [reply golang/cosmos/x/swingset/genesis.go:187]: oh, I had assumed that the hasher was being created one-per-export, but maybe the `eventHandler` that it lives in is allocated statically, one-per-process?

File: golang/cosmos/x/swingset/genesis.go (hunk 4 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/genesis.go:192]: The missing bit is that the incoming stream of key value pairs may not be JSON encoded in the first place. It happens that's how we currently feed golang when dealing with export/import, but that may not always be the case.

File: golang/cosmos/x/swingset/genesis.go (hunk 3 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/genesis.go:187]: the artifact provided is passed to `WriteSwingStoreExportToDirectory`. That function is well behaved and will only read the stream export data once, but technically it could do it multiple times.

I agree the layering is weird, and in a perfects world I'd decouple the generation of the hash from the consumer that writes the data to disk, however I wanted to avoid that inefficiency. I suppose I could break boundaries, grab the iterator once on the outer scope, assert we only wrap the iterator once, and at the end verify that the iterator has been fully consumed.

File: a3p-integration/proposals/z:acceptance/genesis-test.sh [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+    GENESIS_HEIGHT_ARG="--height $1"
+    shift
+  fi
+
+  agd export --export-dir "$GENESIS_EXPORT_DIR" $GENESIS_HEIGHT_ARG "$@"
+}
+
+killAgd
+FORK_TEST_DIR=$(mktemp -t -d fork-test-XXX)
+mkdir -p $FORK_TEST_DIR/config
```
Comment (ivanlei) [inline a3p-integration/proposals/z:acceptance/genesis-test.sh]: _fix_:

Reads of `$FORK_TEST_DIR` in this file should be double quoted.

Be sure to put the quotes completely around `"$FORK_TEST_DIR/config"`

File: golang/cosmos/x/swingset/genesis.go [hunk 6]
```diff
@@ -46,15 +54,62 @@ func InitGenesis(ctx sdk.Context, k Keeper, swingStoreExportsHandler *SwingStore
...
 	snapshotHeight := uint64(ctx.BlockHeight())
 
-	getExportDataReader := func() (agoric.KVEntryReader, error) {
-		exportDataIterator := swingStore.Iterator(nil, nil)
-		return agoric.NewKVIteratorReader(exportDataIterator), nil
+	var getExportDataReader func() (agoric.KVEntryReader, error)
+
+	if len(swingStoreExportData) > 0 {
+		for _, entry := range swingStoreExportData {
+			swingStore.Set([]byte(entry.Key), []byte(entry.Value))
```
Comment (ivanlei) [inline golang/cosmos/x/swingset/genesis.go:63]: _fix or not: perf concern_:

This is reallocating every one of the keys and values to convert from `string` to `[]byte`. Because genesis export/import is RAM intensive, this might be worth fixing with either `unsafe` or `sync.Pool`. I leave it to you to decide if this is worth it.

https://josestg.medium.com/140x-faster-string-to-byte-and-byte-to-string-conversions-with-zero-allocation-in-go-200b4d7105fc has an example with a 0-alloc conversion.
```golang
func StringToBytes(s string) []byte {
 p := unsafe.StringData(s)
 b := unsafe.Slice(p, len(s))
 return b
}
```

File: golang/cosmos/types/kv_entry_helpers.go [hunk 7]
```diff
@@ -232,3 +232,45 @@ func EncodeKVEntryReaderToJsonl(reader KVEntryReader, bytesWriter io.Writer) (er
...
+	return &kvHookingReader{
+		reader,
+		onRead,
+		onClose,
+	}
+}
+
+// Read yields the next KVEntry from the source reader
+// Implements KVEntryReader
+func (hr kvHookingReader) Read() (next KVEntry, err error) {
```
Comment (ivanlei) [inline golang/cosmos/types/kv_entry_helpers.go:257]: _fix or not_:

Consider using `err = fmt.Errorf("...%w...",err,...)` or `sdkioerrors.Wrapf` so the code can explicitly message that a hook failed while not losing info about the underlying error.

File: golang/cosmos/x/swingset/genesis.go [hunk 8]
```diff
@@ -46,15 +54,62 @@ func InitGenesis(ctx sdk.Context, k Keeper, swingStoreExportsHandler *SwingStore
...
+			if kvReader == nil {
+				return nil, fmt.Errorf("swing-store export has no export data")
+			}
+
+			hasher := sha256.New()
+			encoder := json.NewEncoder(hasher)
+			encoder.SetEscapeHTML(false)
+
+			return agoric.NewKVHookingReader(kvReader, func(entry agoric.KVEntry) error {
+				key := []byte(entry.Key())
```
Comment (ivanlei) [inline golang/cosmos/x/swingset/genesis.go:96]: _fix or not: perf concern_

Once again using `[]byte()` in 2 spots in this function which double the allocation.

File: golang/cosmos/types/kv_entry_helpers.go [hunk 9]
```diff
@@ -232,3 +232,45 @@ func EncodeKVEntryReaderToJsonl(reader KVEntryReader, bytesWriter io.Writer) (er
 		}
 	}
 }
+
+var _ KVEntryReader = &kvHookingReader{}
```
Comment (ivanlei) [inline golang/cosmos/types/kv_entry_helpers.go:236]: _fix_:

Remove this line. I can't see why this is necessary and compiling without it succeeds.

**Review by ivanlei — DISMISSED** [review]
Please address the `fix` comment.

Please choose to address the `fix or not` or comment and briefly say why it's not useful/necessary/a priority at this time.

File: golang/cosmos/types/kv_entry_helpers.go (hunk 9 above)
Comment (mhofman) [reply golang/cosmos/types/kv_entry_helpers.go:236]: This is an interface check, making sure `kvHookingReader` implements `KVEntryReader`. There's lots of those around, and I simply cargo culted, but open to alternatives.

File: golang/cosmos/types/kv_entry_helpers.go (hunk 7 above)
Comment (michaelfig) [reply golang/cosmos/types/kv_entry_helpers.go:257]: Our `agoric-sdk/.github/workflows/golangci-lint.yml` explicitly warns `Found %w in ./golang/cosmos; please use %s instead.` in order to discourage making validator-specific source file locations in stack traces part of consensus.

`Wrapf` without `%w` is safe because it doesn't actually stringify the stack trace of the error, but still exposes it if there's a panic, much like Hardened JS's disciplined stack trace handling for `Error` objects.

**Review by michaelfig — APPROVED** [review]
LGTM conditional on satisfactorily addressing other reviewers' comments.

File: golang/cosmos/types/kv_entry_helpers.go (hunk 9 above)
Comment (michaelfig) [reply golang/cosmos/types/kv_entry_helpers.go:236]: I prefer the more obviously useless:
```suggestion
var _ KVEntryReader = (*kvHookingReader)(nil)
```

File: golang/cosmos/types/kv_entry_helpers.go (hunk 7 above)
Comment (mhofman) [reply golang/cosmos/types/kv_entry_helpers.go:257]: I'm confused about this feedback. The hook is only called if there was no error in the first place, so there are no errors to wrap.

File: golang/cosmos/x/swingset/keeper/keeper.go [hunk 10]
```diff
@@ -138,7 +139,9 @@ func (k Keeper) pushAction(ctx sdk.Context, inboundQueuePath string, action vm.A
 		return err
 	}
 
-	return k.vstorageKeeper.PushQueueItem(ctx, inboundQueuePath, string(bz))
+	// The string will immediately be stored
```
Comment (michaelfig) [inline golang/cosmos/x/swingset/keeper/keeper.go]: Maybe remove this comment, as `bz`'s lifetime does not impact the proper usage of `conv.UnsafeBytesToStr` (at least according to its doc comment on lifetime).

**Review by michaelfig — APPROVED** [review]

File: golang/cosmos/types/kv_entry_helpers.go (hunk 9 above)
Comment (ivanlei) [reply golang/cosmos/types/kv_entry_helpers.go:236]: Oh gosh... I completely forgot the use of these in golang. Yeah, happy for this to stay.

File: golang/cosmos/x/swingset/genesis.go (hunk 6 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/genesis.go:63]: decided to leave as-is for now given the lack of positive impact in rudimentary perf tests

**Comment by mhofman** [comment]
I unlayered this from #9568 and will merge as-is given all other feedback has been addressed
