### PR TITLE
Supply returnedP argument to handler

### LINKED ISSUE #886: cannot reference the internal Promise made by eventual-send?
While trying to write the tests in #859, I came across an unexpected behavior in the way SwingSet uses eventual-send. I think it's behaving as designed, but it feels unfortunate, and I'm trying to see if I can work around it or if this is likely to cause problems in the future.

When code inside a vat sends a message to somebody, it uses something like this:

```js
const p1 = E(bob).foo(); // equivalent to p1 = bob~.foo()
```

`bob`, in this case, is a "Presence": an empty object which is internally associated with a particular `HandledPromise`, which has a particular handler. This handler knows about the `o-NN` reference that represents "bob" on some other vat, and it knows how to make a `syscall.send()` with the method name and serialized arguments. This handler is defined in liveslots (in `makeQueued(slot)`, called by `convertSlotToVal()` when dealing with object references), and is built something like this:

```js
const handler = {
  applyMethod(_0, prop, args) {
    const p0 = queueMessage(slot, prop, args); // do syscall.send
    return p0;
  },
};
let resolveWithPresence
const hp = new HandledPromise((_, _, resPres => { resolveWithPresence = resPres }),
                              handler);
const presence = resolveWithPresence(handler); // fulfilledHandler
// discard hp, return presence
```

`queueMessage` creates a new promise identifier (a `p+NN` string) and uses it as the `result=` argument of the `syscall.send`. This tells the kernel how to notify the sending vat about the result of the message send: at some point in the future, this vat will receive a `dispatch.notifyFullToPresence` of some sort which references the same `p+NN` string, and the liveslots layer will resolve `p0`.

We add `p0` into the `valToSlot`/`slotToVal` tables, so in the off chance that other vats talk back to this one about this result promise, those references will be deserialized back into the correct promise.

What I had previously believed was that `p1 === p0`. I'm now realizing that this couldn't be true, because the `HandledPromise` handler is not trusted with synchronous behavior, and `p1` has been long-since created and returned by the time the handler is invoked to create `p0`. My current (tenuous) belief is that `p1` is eventually resolved to `p0`, which gives `p1` the same handler as `p0`, allowing pipelined sends to work (`p1~.bar()`). But they are distinct Promises, and most importantly `p1` is not added to `valToSlot` or `slotToVal`.

The consequence for the tests I'm writing is that one of the cases simply cannot be reached by liveslots-based vats. I wanted to exercise a case where a vat sends a message, creating result promise p1, and then sends `p1` as an argument in a subsequent message. I was expecting that the kernel will see the same promise identifier for both the result and the subsequent argument, and I was looking to test how the kernel (and other liveslots instances) reacts to that promise being resolved. But what I'm seeing is the result promise is serialized as `p+5`, while the later argument gets `p+6`. Now I'm realizing that the handler's internal `p0` is being registered as `p+5` during `queueMessage`, but the application-level code receives a distinct `p1`, and when that meets the serializer, it is assigned a brand new number.

I don't think this is affecting the ability to pipeline messages (`p1~.bar()`) because the handler is forwarded. However I think it *is* introducing an additional turn of delay into the transmission, which could be an ordering issue.

But it means that liveslots-based vats cannot reference their own result promises without external help. I think this will introduce addtional cranks (and roundtrips between vats) when promises are passed as arguments. E.g.:

```js
Alice: p1 = bob~.foo(); carol~.bar(p1)
Bob: function foo() { return 'f'; }
Carol: function bar(p1) { p1.then(f => console.log('carol got f')) }
```

In that example, I'd really prefer carol to receive the same promise ID that Bob is going to resolve. If that happened, then when Bob finally resolves it, the kernel will notify everyone subscribed to hear about it (both Alice and Carol), and Carol is notified pretty directly.

But if Alice's `p1` is not the same as the `result=` that Bob gets, then we have two distinct Promises in play. The first is subscribed-to by Alice, and decided-by/resolved-by Bob. The second is subscribed-to by Carol, and decided-by/resolved-by Alice. The resolution has to go from Bob to Alice first, and then Alice reacts to it by resolving the promise that Carol is watching.

I need to run some more tests to see if this new understanding is accurate, but it would explain what I've seen so far. @FUDCo I think it would also explain the additional turns we were seeing in that test.

@erights @michaelfig does this sound accurate? Does it also seem like an unfortunate performance hit?

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #886

This PR adds `returnedP` (a reference to the HandledPromise that was created for this call) as the last argument to the handler methods (currently `applyMethod` or `get`), as explained in https://github.com/Agoric/agoric-sdk/issues/886#issuecomment-611090801

### CODE REVIEW

File: packages/eventual-send/src/index.js [hunk 1]
```diff
@@ -448,7 +449,7 @@ export function makeHandledPromise(Promise) {
         HandledPromise.resolve()
           .then(() =>
             // and resolve to the answer from the specific unfulfilled handler,
-            resolve(unfulfilledHandler[operation](p, ...args)),
+            resolve(unfulfilledHandler[operation](p, ...args, returnedP)),
```
Comment (warner) [inline packages/eventual-send/src/index.js]: That's a splat, right? So the handler's operation function will get anywhere from 2 to N+2 arguments, depending upon `args.length`?

I'm not sure where this particular `...args` comes from.. do we need to worry that the caller and the receiver might not agree on the number of arguments, and then `returnedP` winds up in the wrong place? Most of the time I see varargs, they strictly come at the end of the function to avoid such confusion. But if our own code is on both ends of this call, maybe we don't need to worry about it.

**Review by warner — APPROVED** [review]
Looks ok to me in general, I'll defer to @erights about whether this takes us closer or farther from the standards proposal we're aiming for.

File: packages/eventual-send/src/index.js (hunk 1 above)
Comment (FUDCo) [reply packages/eventual-send/src/index.js]: I second what Brian said.  That looks like an accident waiting to happen.

Comment (michaelfig) [reply packages/eventual-send/src/index.js]: Yes, our own code is at both ends.

Comment (erights) [reply packages/eventual-send/src/index.js]: I understand why it looks confusing but it is the best way to write this. However, the variable name `args` perhaps should be renamed `metaArgs` or something, to indicate that's it at a metalevel compared to the normal use of `args` for an array of arguments. For example, when the `operation` is `applyMethod`, the contents of, let's say, `metaArgs` is `[prop, args]`, where `prop` is the name of the remote method to be called and `args` are the arguments to be spread out and passed to it.

In explaining this, it occurs to me that `prop` vs `operation` has the same meta-level shift as `args` vs `metaArgs`.

File: packages/eventual-send/src/index.js [hunk 2]
```diff
@@ -473,7 +474,8 @@ export function makeHandledPromise(Promise) {
     // We return a handled promise with the default unfulfilled handler.
     // This prevents a race between the above Promise.resolves and
     // pipelining.
-    return new HandledPromise(executor);
+    returnedP = new HandledPromise(executor);
```
Comment (erights) [inline packages/eventual-send/src/index.js]: You should get rid of the `let` on line 442 and make this be
```js
const returnedP = ...
```
You'll also need to suppress the eslint use-before-define warning. This is the right thing all the way around.
   * Forcing outselves to insert a comment to suppress the warning flags that something unusual is going on.
   * The temporal dead zone of the `const` declaration is your friend. If the variable is read before its defined, that would be a serious bug. The early `let` and late initialization would mask the bug with an `undefined`. Better to get a noisy throw.

**Review by erights — APPROVED** [review]
LGTM. Now that I see it in code, it's not as awkward as I feared. It'll be interesting to fold this back into the proposal.

File: packages/eventual-send/src/index.js (hunk 1 above)
Comment (michaelfig) [reply packages/eventual-send/src/index.js]: I added a comment to this effect.

**Review by erights — APPROVED** [review]
LGTM even more. thanks.
