### PR TITLE
fix(notifier): Add a makeDurablePublishKit "onUpdate" option

### LINKED ISSUE #7303: Alternative to `pipeTopicToStorage`
## What is the Problem Being Solved?

https://github.com/Agoric/agoric-sdk/issues/7302 identifies a deficiency with `pipeTopicToStorage`, and suggests a way to fix it. However all usages of `pipeTopicToStorage` follow a similar pattern of replicating all published values.

An alternative would be to eschew the subscriber pull altogether for that use case, and simply provide an optional durable callback invoked with each published value.

## Description of the Design

An optional parameter to the durable publish kit maker that is stored in the state of the kit (and thus must be durable compatible), and invoked directly for every published value.

The contract can then have its own abstractions for creating a storage node writer that replicates published values, while avoiding having a dependency from publishers onto storage. One potential design is detailed at https://github.com/Agoric/agoric-sdk/issues/7300.

## Security Considerations

None

## Scaling Considerations

Must be fully virtual and not hold any values in heap.

## Test Plan

Verify as part of https://github.com/Agoric/agoric-sdk/issues/7297

### PR DESCRIPTION
**Pull request by gibson042**
closes: #7303

## Description

Adds a new "onAdvance" option to `makeDurablePublishKit` to provide a callback for direct invocation upon publication of any new value. This is equivalent in functionality to subscription, but allows for better RAM utilization since callbacks (particularly those for supporting writes to chain storage) can be durable and paged out.

### Security Considerations

n/a

### Scaling Considerations

We hope to see less consumption of RAM in contract vats.

### Documentation Considerations

n/a

### Testing Considerations

Nothing special.

### CODE REVIEW

File: packages/internal/test/test-callback.js [hunk 1]
```diff
@@ -137,3 +137,14 @@ test('far function callbacks', async t => {
...
+
+test('isCallback', async t => {
+  t.true(cb.isCallback(cb.makeFunctionCallback(async () => {})));
+  t.true(cb.isCallback(cb.makeMethodCallback({ m: async () => {} }, 'm')));
+  t.true(cb.isCallback(cb.makeSyncFunctionCallback(() => {})));
+  t.true(cb.isCallback(cb.makeSyncMethodCallback({ m: () => {} }, 'm')));
+  t.false(cb.isCallback(undefined));
+  t.false(cb.isCallback(null));
+  t.false(cb.isCallback('string'));
+  t.false(cb.isCallback({}));
```
Comment (turadg) [inline packages/internal/test/test-callback.js]: consider some pathological cases,
```js
t.true(cb.isCallback({ target: 'anytruthy', bound: [] }));
t.true(cb.isCallback({ target: 'anytruthy', methodName: undefined, bound: [] }));

t.false(cb.isCallback({ target: {}, bound: undefined }));
t.false(cb.isCallback({ target: {}, methodName: 'foo }));
```

File: packages/notifier/src/publish-kit.js [hunk 2]
```diff
@@ -178,14 +179,19 @@ harden(makePublishKit);
 /**
  * @param {object} [options]
  * @param {DurablePublishKitValueDurability & 'mandatory'} [options.valueDurability='mandatory']
+ * @param {import('@agoric/internal/src/callback.js').Callback<*>} [options.onAdvance] A direct callback
```
Comment (turadg) [inline packages/notifier/src/publish-kit.js]: "advance" makes sense internally to this function but is a new concept to the consumer. I would have expected `onPublish`, but I see that would omit `finish` and `fail`. One way through this is to have `publish` be the garden path "publish" and to consider `finish` and `fail` as also publishing values. Of course that would have its own confusion. 

Trying to think of a more obvious name for "any new value". Maybe `onChange`? `onNew`?

Comment (gibson042) [reply packages/notifier/src/publish-kit.js]: Yeah, I had similar thoughts. How would you feel about `onUpdate`?

File: packages/notifier/src/publish-kit.js [hunk 3]
```diff
@@ -298,6 +304,13 @@ const advanceDurablePublishKit = (context, value, targetStatus = 'live') => {
   }
   const { tailP: currentP, tailR: resolveCurrent } =
     provideDurablePublishKitEphemeralData(state, facets);
+  const commit = resolution => {
+    // Invoke a direct callback, but ignore the result.
+    if (onAdvance) {
+      callE(onAdvance, resolution).then(sink, sink);
```
Comment (mhofman) [inline packages/notifier/src/publish-kit.js]: should there be a `void` prefix here? I'm surprised tslint didn't complain

File: packages/internal/src/callback.js [hunk 4]
```diff
@@ -120,3 +120,20 @@ export const makeMethodCallback = (target, methodName, ...bound) => {
...
+ * @param {any} callback
+ * @returns {callback is Callback}
+ */
+export const isCallback = callback => {
+  if (!callback || typeof callback !== 'object') {
+    return false;
+  }
+  const { target, methodName, bound } = callback;
+  return (
+    !!target &&
```
Comment (mhofman) [inline packages/internal/src/callback.js]: Should target be validated to be `isObject`?

File: packages/notifier/src/publish-kit.js (hunk 2 above)
Comment (turadg) [reply packages/notifier/src/publish-kit.js]: perfect

Comment (mhofman) [reply packages/notifier/src/publish-kit.js]: `onChange` and `onUpdate` are both fine with me, but I'd be ok with `onPublish` too. From what I understand `fail` won't cause a published value, and completion could be considered a final publish.

**Review by mhofman — APPROVED** [review]
Looks good to me, approved based on renaming

File: packages/notifier/src/publish-kit.js (hunk 3 above)
Comment (turadg) [reply packages/notifier/src/publish-kit.js]: Types based linting isn't enabled in CI (was too slow)

File: packages/notifier/src/publish-kit.js (hunk 2 above)
Comment (turadg) [reply packages/notifier/src/publish-kit.js]: I slightly prefer onPublish because it's a term the user already knows and they *should* understand that `finish` publishes and `fail` doesn't.

The confusion I was trying to avoid with alternatives to onPublish is really about the method names. I'd sooner rename finish() to publishFinal()

Comment (gibson042) [reply packages/notifier/src/publish-kit.js]: `fail` _does_ advance the publish kit; it's an alternative termination to `finish`.

File: packages/notifier/src/publish-kit.js (hunk 3 above)
Comment (gibson042) [reply packages/notifier/src/publish-kit.js]: Ah, I was also wondering why that didn't prompt a complaint.

**Comment by gibson042** [comment]
@mhofman @turadg: I've renamed `onAdvance` to `onUpdate` and expanded testing, which pulled in some changes to callback.js. PTAL.

File: packages/notifier/src/publish-kit.js (hunk 2 above)
Comment (mhofman) [reply packages/notifier/src/publish-kit.js]: When consuming the values through a subscriber, `fail` would result in a rejection, so by that logic, it's not observable as a published value, where both the values provided to `publish` and `finish` are.

Comment (gibson042) [reply packages/notifier/src/publish-kit.js]: Right, but the new callback isn't a subscriber and will get called with an object encapsulating the terminal rejection.

File: packages/internal/src/callback.js [hunk 5]
```diff
@@ -115,6 +126,9 @@ harden(makeSyncMethodCallback);
  * @returns {Callback<I>}
  */
 export const makeMethodCallback = (target, methodName, ...bound) => {
+  isObject(target) || Fail`method callback target must be an object: ${target}`;
+  typeof methodName === 'string' ||
```
Comment (mhofman) [inline packages/internal/src/callback.js:131]: Actually thinking about this, I believe we should allow well-known symbols since they're allowed as method names in `E`. cc @michaelfig 

Edit: that's what I get for reviewing commit-by-commit...

File: packages/notifier/src/publish-kit.js (hunk 2 above)
Comment (mhofman) [reply packages/notifier/src/publish-kit.js]: Oh I had missed that. Looks like it's updated with a rejected promise. We should not call the callback with either a value or a promise. Either we skip the rejection, or we wrap in a object like `PromiseSettlement`

**Review by mhofman — CHANGES_REQUESTED** [review]
I don't think we should have a variant value type for the callback.

File: packages/notifier/src/publish-kit.js (hunk 2 above)
Comment (gibson042) [reply packages/notifier/src/publish-kit.js]: I'd prefer to keep the symmetry between `subscribeAfter` promise settlement and values sent to the callback. If we don't like that, my next higher preference would be not adding this functionality at all and instead handling it entirely by wrapping the `makeDurablePublishKit` calls such that values are sent to chain storage at the same place as they are sent to the publish kit.
```js
const makeDurablePublishKit = prepareDurablePublishKit(baggage, label);
const makeDurableChainStoragePublishKit = prepareDurableChainStoragePublishKit(
  baggage,
  makeDurablePublishKit,
  shared.publicMarshaller,
);
…
// methods of this `publisher` wrap those of a publisher returned from `makeDurablePublishKit`
// to write to `storageNode` *and* invoke the inner object method.
const { publisher, subscriber } = makeDurableChainStoragePublishKit(storageNode);
```

Comment (mhofman) [reply packages/notifier/src/publish-kit.js]: Currently the `pipeToStorage` mechanism ignores failures. I understand we want to potentially support other use cases that care about the failure case.

An alternative is to always wrap the value given to the callback in a promise. a `Promise.resolve(resolution)` would work for that. My concern is having an argument that is sometimes a value, and sometimes a (rejected) promise.

Comment (gibson042) [reply packages/notifier/src/publish-kit.js]: > An alternative is to always wrap the value given to the callback in a promise. a `Promise.resolve(resolution)` would work for that. My concern is having an argument that is sometimes a value, and sometimes a (rejected) promise.

Fair enough. Done.

File: packages/internal/src/callback.js [hunk 6]
```diff
@@ -73,6 +78,8 @@ harden(makeSyncFunctionCallback);
  * @returns {Callback<I>}
  */
 export const makeFunctionCallback = (target, ...bound) => {
+  isObject(target) ||
+    Fail`function callback target must be a function presence: ${target}`;
```
Comment (michaelfig) [inline packages/internal/src/callback.js:82]: If it's not done already, I'd prefer also allowing near functions (i.e. `typeof target === 'function'`), since `E` accepts them as a target.

File: packages/internal/src/callback.js [hunk 7]
```diff
@@ -94,6 +101,11 @@ harden(makeFunctionCallback);
  * @returns {SyncCallback<I>}
  */
 export const makeSyncMethodCallback = (target, methodName, ...bound) => {
+  isObject(target) ||
+    Fail`sync method callback target must be an object: ${target}`;
+  typeof methodName === 'string' ||
```
Comment (michaelfig) [inline packages/internal/src/callback.js:106]: Can we also allow `number` since that's a valid `PropertyKey`?

File: packages/internal/src/callback.js [hunk 8]
```diff
@@ -115,8 +127,31 @@ harden(makeSyncMethodCallback);
  * @returns {Callback<I>}
  */
 export const makeMethodCallback = (target, methodName, ...bound) => {
+  isObject(target) || Fail`method callback target must be an object: ${target}`;
+  typeof methodName === 'string' ||
```
Comment (michaelfig) [inline packages/internal/src/callback.js:131]: Ditto for `number`?

File: packages/internal/src/callback.js [hunk 9]
```diff
@@ -115,8 +127,31 @@ harden(makeSyncMethodCallback);
...
+ */
+export const isCallback = callback => {
+  if (!isObject(callback)) {
+    return false;
+  }
+  const { target, methodName, bound } = callback;
+  return (
+    isObject(target) &&
+    (methodName === undefined ||
+      typeof methodName === 'string' ||
```
Comment (michaelfig) [inline packages/internal/src/callback.js:152]: And `number`?

File: packages/internal/test/test-callback.js
Comment (michaelfig) [inline packages/internal/test/test-callback.js:1]: Thanks for the comprehensive tests!  Much appreciated.

File: packages/notifier/src/publish-kit.js [hunk 10]
```diff
@@ -298,6 +304,13 @@ const advanceDurablePublishKit = (context, value, targetStatus = 'live') => {
   }
   const { tailP: currentP, tailR: resolveCurrent } =
     provideDurablePublishKitEphemeralData(state, facets);
+  const commit = resolution => {
+    // Invoke a direct callback, but ignore the result.
+    if (onUpdate) {
+      void callE(onUpdate, Promise.resolve(resolution)).then(sink, sink);
```
Comment (michaelfig) [inline packages/notifier/src/publish-kit.js]: I'd prefer not sinking rejections here.  A `SES_UNHANDLED_REJECTION` is more helpful for diagnosing errors in the callback.
```suggestion
      void callE(onUpdate, Promise.resolve(resolution));
```

File: packages/notifier/src/types-ambient.js [hunk 11]
```diff
@@ -160,6 +160,8 @@
  *
  * @property {DurablePublishKitValueDurability} valueDurability
  *
+ * @property {import('@agoric/internal/src/callback.js').Callback<(publicationRecordP: Promise<PublicationRecord<*>>) => void>} [onUpdate]
```
Comment (michaelfig) [inline packages/notifier/src/types-ambient.js]: I like this type.  Since it's reused in this package, would it be worth a `@typedef {...} PublishKitOnUpdate` somewhere here?

File: packages/notifier/test/test-publish-kit.js [hunk 12]
```diff
@@ -38,6 +39,12 @@ const makers = {
   ),
 };
 
+// ava t.like does not support array shapes, but object analogs are fine
```
Comment (michaelfig) [inline packages/notifier/test/test-publish-kit.js:42]: Oh!  This is a good one.

File: packages/internal/src/callback.js (hunk 6 above)
Comment (mhofman) [reply packages/internal/src/callback.js:82]: `isObject(target) === true ` for `typeof target === 'function'`

File: packages/internal/src/callback.js (hunk 7 above)
Comment (mhofman) [reply packages/internal/src/callback.js:106]: That's just a typing allowance. Properties are either string or symbol.

Maybe the helper should convert number to string?

File: packages/internal/src/callback.js (hunk 6 above)
Comment (gibson042) [reply packages/internal/src/callback.js:82]: `isObject` returns true for function input, and that case is covered by the first assertion in `test('isCallback', …)`.

**Review by turadg — APPROVED** [review]
`onUpdate` lgtm.

I echo the request to not sink rejections but I trust that will get resolved

File: packages/internal/src/callback.js (hunk 7 above)
Comment (gibson042) [reply packages/internal/src/callback.js:106]: Hmm, I'd rather have callers convert to string in case of surprises from e.g. `({ [Number.MAX_SAFE_INTEGER + 1]: true })[Number.MAX_SAFE_INTEGER + 2]`.

File: packages/notifier/src/publish-kit.js [hunk 13]
```diff
@@ -298,6 +304,13 @@ const advanceDurablePublishKit = (context, value, targetStatus = 'live') => {
   }
   const { tailP: currentP, tailR: resolveCurrent } =
     provideDurablePublishKitEphemeralData(state, facets);
+  const commit = resolution => {
+    // Invoke a direct callback, but ignore the result.
+    if (onUpdate) {
+      void callE(onUpdate, Promise.resolve(resolution));
```
Comment (mhofman) [inline packages/notifier/src/publish-kit.js:313]: Thinking about this, we should comment on why `Promise.resolve()` is safe and required here: it's only used on values we created in this file, and we need to keep the rejection promise as is (through `Promise.resolve()`'s brand check) to avoid losing the quiet part of the rejection.

File: packages/notifier/test/test-publish-kit.js [hunk 14]
```diff
@@ -277,22 +284,75 @@ test('durable publish kit upgrade trauma (full-vat integration)', async t => {
...
     { name: 'pubsub', methodName: 'getSubscriber' },
   ]);
+  const spyName = 'receivePublicationRecord';
+  const directSubscriber = await run('makeRemotable', [
+    'directSubscriber',
+    { [spyName]: undefined },
+  ]);
+  const pub2Options = {
+    // onUpdate: makeMethodCallback(directSubscriber, spyName),
+    onUpdate: { target: directSubscriber, methodName: spyName, bound: [] },
```
Comment (mhofman) [inline packages/notifier/test/test-publish-kit.js:294]: What's the reason to not use the maker?

**Review by mhofman — APPROVED** [review]
If you feel like it, maybe add the comment regarding the safety of `Promise.resolve()`. Orselse LGTM.

File: packages/notifier/src/types-ambient.js (hunk 11 above)
Comment (gibson042) [reply packages/notifier/src/types-ambient.js]: Sure; done.

File: packages/notifier/test/test-publish-kit.js (hunk 14 above)
Comment (gibson042) [reply packages/notifier/test/test-publish-kit.js:294]: It doesn't work at the level outside the vats because `directSubscriber` isn't an object there.
