### PR TITLE
fix(oracle): default restartDelay parameter

### LINKED ISSUE #7192: failing to pushPrice past round 2: round not accepting submissions
## Describe the bug

I can pushPrice for `--roundId 1` and for `--roundId 2`, but when I try `--roundId 3`, I get `Error: round not accepting submissions`.

If I try round 4, I get `invalid round to report`. (which makes sense, since `latestRound` is 2).

## Expected behavior

rounds 3, 4, ... accept pushPrice

## Platform Environment
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

2023-03-20 15:15 90f9597a5 feat: place bids by discount, price in inter CLI

based on

2023-03-20 19:47 ab52304dc Merge pull request #7184 from Agoric/7181-durable-auctionee

## Additional context

using `packages/agoric-cli/test/agops-oracle-smoketest.sh`

## Screenshots
```
2023-03-20T21:19:02.358Z SwingSet: xsnap: v9: RemoteError(error:liveSlots:v25#70005)#5: invalid round to report
2023-03-20T21:19:02.358Z SwingSet: xsnap: v9: Error: invalid round to report
 at construct ()
 at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:56)
 at makeError (/bundled-source/.../node_modules/ses/src/error/assert.js:242)
 at decodeErrorCommon (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:281)
 at decodeFromSmallcaps (/bundled-source/.../node_modules/@endo/marshal/src/encodeToSmallcaps.js:451)
 at unserialize (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:351)
 at notifyOnePromise (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1201)
 at notify (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1225)
 at dispatchToUserspace (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1467)
 at runWithoutMetering (/bundled-source/.../packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:57)
 at ()


2023-03-20T21:52:26.652Z SwingSet: xsnap: v9: Error: round not accepting submissions
 at construct ()
 at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:56)
 at makeError (/bundled-source/.../node_modules/ses/src/error/assert.js:242)
 at decodeErrorCommon (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:281)
 at decodeFromSmallcaps (/bundled-source/.../node_modules/@endo/marshal/src/encodeToSmallcaps.js:451)
 at unserialize (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:351)
 at notifyOnePromise (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1201)
 at notify (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1225)
 at dispatchToUserspace (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1467)
 at runWithoutMetering (/bundled-source/.../packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:57)
 at ()
```

### PR DESCRIPTION
**Pull request by turadg**
closes: #7192

## Description

The problem in 7192 is because of how the fluxAggregator observes `restartDelay` (count of rounds) vs how the earlier price aggregator did (timer ticks).

This fixes that and has some other improvements that were apparent while debugging.

### Testing Considerations

`agops-oracle-smoketest.sh` run locally

### CODE REVIEW

**Comment by dckc** [comment]
Neither gov1 nor gov2 works in round 3:

```
2023-03-21T20:54:16.018Z SwingSet: ls: v37: Error#2: round 3 not accepting submissions from oracle agoric1ldmtatp24qlllgxmrsjzcpe20fvlkp448zcuce
2023-03-21T20:55:11.159Z SwingSet: ls: v37: Error#3: round 3 not accepting submissions from oracle agoric140dmkrz2e42ergjj7gyvejhzmjzurvqeq82ang
```

Do I/we have to use the 3rd oracle operator for round 3? No; this config has only 2:

```json
          "oracleAddresses": [
            "agoric1ldmtatp24qlllgxmrsjzcpe20fvlkp448zcuce",
            "agoric140dmkrz2e42ergjj7gyvejhzmjzurvqeq82ang"
          ],
```

File: packages/inter-protocol/test/smartWallet/test-oracle-integration.js [hunk 1]
```diff
@@ -129,6 +129,12 @@ const acceptInvitation = async (wallet, priceAggregator) => {
 };
 
 let pushPriceCounter = 0;
+/**
+ * @param {*} wallet
+ * @param {string} adminOfferId
+ * @param {import('@agoric/inter-protocol/src/price/roundsManager.js').PriceRound} priceRound
+ * @returns
```
Comment (dckc) [inline packages/inter-protocol/test/smartWallet/test-oracle-integration.js:136]: if you end up changing anything else, please take this out

File: packages/agoric-cli/src/commands/oracle.js [hunk 2]
```diff
@@ -120,19 +125,19 @@ export const makeOracleCommand = async logger => {
       'offer that had continuing invitation result',
       Number,
     )
-    .requiredOption('--price [number]', 'price (per unitAmount)', BigInt)
-    .requiredOption('--roundId [number]', 'round', Number)
+    .requiredOption('--price [number]', 'price', Number)
+    .option('--roundId [number]', 'round', Number)
     .action(async function (opts) {
+      const unitPrice = scaleDecimals(opts.price);
```
Comment (dckc) [inline packages/agoric-cli/src/commands/oracle.js:131]: :clap:

File: packages/agoric-cli/test/agops-oracle-smoketest.sh [hunk 3]
```diff
@@ -64,14 +64,32 @@ agd query vstorage keys published.priceFeed
...
 
 # Set it to $13 per ATOM
+# second round, second oracle has to be first this time (alternating start)
+PROPOSAL_OFFER=$(mktemp -t agops.XXX)
+bin/agops oracle pushPriceRound --price 14.0 --roundId 2 --oracleAdminAcceptOfferId "$ORACLE2_OFFER_ID" >|"$PROPOSAL_OFFER"
+agoric wallet send --offer "$PROPOSAL_OFFER" --from gov2 --keyring-backend="test"
 # second round, first oracle
 PROPOSAL_OFFER=$(mktemp -t agops.XXX)
-bin/agops oracle pushPriceRound --price 120000000 --roundId 2 --oracleAdminAcceptOfferId "$ORACLE_OFFER_ID" >|"$PROPOSAL_OFFER"
+bin/agops oracle pushPriceRound --price 12.0 --roundId 2 --oracleAdminAcceptOfferId "$ORACLE_OFFER_ID" >|"$PROPOSAL_OFFER"
```
Comment (dckc) [inline packages/agoric-cli/test/agops-oracle-smoketest.sh:73]: yay!

File: packages/agoric-cli/test/agops-oracle-smoketest.sh [hunk 4]
```diff
@@ -64,14 +64,32 @@ agd query vstorage keys published.priceFeed
...
+# Set it to $20 per ATOM
+PROPOSAL_OFFER=$(mktemp -t agops.XXX)
+bin/agops oracle pushPriceRound --price 15.0 --roundId 3 --oracleAdminAcceptOfferId "$ORACLE_OFFER_ID" >|"$PROPOSAL_OFFER"
+agoric wallet send --offer "$PROPOSAL_OFFER" --from gov1 --keyring-backend="test"
+# second oracle
+PROPOSAL_OFFER=$(mktemp -t agops.XXX)
+bin/agops oracle pushPriceRound --price 25.0 --roundId 3 --oracleAdminAcceptOfferId "$ORACLE2_OFFER_ID" >|"$PROPOSAL_OFFER"
+agoric wallet send --offer "$PROPOSAL_OFFER" --from gov2 --keyring-backend="test"
+
+# leave round unspecified for contract to suggest ($21.2)
```
Comment (dckc) [inline packages/agoric-cli/test/agops-oracle-smoketest.sh:88]: I'm struggling to find the mechanism that fills this in. hm. I saw a shape that made it look required.

File: packages/inter-protocol/src/price/fluxAggregator.js [hunk 5]
```diff
@@ -52,7 +52,7 @@ const priceDescriptionFromQuote = quote => quote.quoteAmount.value[0];
  * @typedef {object} ChainlinkConfig
  * @property {number} maxSubmissionCount
  * @property {number} minSubmissionCount
- * @property {RelativeTimeValue} restartDelay the number of rounds an Oracle has to wait before they can initiate a round
+ * @property {bigint} restartDelay the number of rounds an Oracle has to wait before they can initiate a round
```
Comment (dckc) [inline packages/inter-protocol/src/price/fluxAggregator.js:55]: ah. I get it.

File: packages/inter-protocol/src/price/priceOracleKit.js [hunk 6]
```diff
@@ -56,9 +56,12 @@ const AdminI = M.interface('OracleKitAdmin', {
 });
 
 const OracleI = M.interface('Oracle', {
-  pushPrice: M.call({ roundId: M.any(), unitPrice: M.bigint() }).returns(
-    M.promise(),
-  ),
+  pushPrice: M.call(
+    M.splitRecord(
+      { unitPrice: M.bigint() },
+      { roundId: M.or(M.bigint(), M.number()) },
```
Comment (dckc) [inline packages/inter-protocol/src/price/priceOracleKit.js:62]: ah. I missed the `splitRecord` on 1st reading

**Review by dckc — APPROVED** [review]
nice!
