### PR TITLE
Fix ag-solo kernel reentrancy and fake-chain non-determinism

### LINKED ISSUE #268: anacrophobia error in restart with wallet UI
As mentioned in Agoric/cosmic-swingset#124, we're seeing a replay failure when we bounce the scenario2 solo node after hitting it with the wallet UI.

STR:

* scenario2-setup
* scenario2-run-chain (remains running)
* scenario2-run-client
* start wallet-frontend, open web page, hit "Connect" (sends a few messages to the solo node)
* hit "Disconnect", close web page, stop wallet-frontend
* stop the scenario2-run-client
* restart the scenario2-run-client, get error during replay of vat-http:

```
Replaying transcript of vatID v3
subscribing to canvasStatePublisher
vat-http.inbound (from browser) 0 Object <[Object: null prototype] {}> { type: 'walletGetPurses' }
vat-http.inbound (from browser) 1 Object <[Object: null prototype] {}> { type: 'walletGetInbox' }
vat-http.inbound (from browser) 1 Object <[Object: null prototype] {}> { type: 'walletGetInbox' }
anachrophobia strikes vat v3
expected: {"0":"send","1":"o-67","2":"processInbound","3":{"body":"[{\"type\":\"walletGetInbox\"},{\"gallery\":{\"@qclass\":\"slot\",\"index\":0},\"purse\":{\"@qclass\":\"slot\",\"index\":1},\"canvasStatePublisher\":{\"@qclass\":\"slot\",\"index\":2},\"chainTimerService\":{\"@qclass\":\"slot\",\"index\":3},\"sharingService\":{\"@qclass\":\"slot\",\"index\":4},\"contractHost\":{\"@qclass\":\"slot\",\"index\":5},\"registrar\":{\"@qclass\":\"slot\",\"index\":6},\"zoe\":{\"@qclass\":\"slot\",\"index\":7},\"localTimerService\":{\"@qclass\":\"slot\",\"index\":8},\"uploads\":{\"@qclass\":\"slot\",\"index\":9},\"spawner\":{\"@qclass\":\"slot\",\"index\":10},\"wallet\":{\"@qclass\":\"slot\",\"index\":11},\"exchange\":{\"@qclass\":\"slot\",\"index\":12},\"http\":{\"@qclass\":\"slot\",\"index\":13}}]","slots":{"0":"o-52","1":"o-53","2":"o-54","3":"o-55","4":"o-56","5":"o-57","6":"o-58","7":"o-59","8":"o-60","9":"p-62","10":"p-63","11":"p-64","12":"o-61","13":"o-62","length":14}},"4":"p+9","length":5}
got     : {"0":"send","1":"o-67","2":"processInbound","3":{"body":"[{\"type\":\"walletGetInbox\"},{\"gallery\":{\"@qclass\":\"slot\",\"index\":0},\"purse\":{\"@qclass\":\"slot\",\"index\":1},\"canvasStatePublisher\":{\"@qclass\":\"slot\",\"index\":2},\"chainTimerService\":{\"@qclass\":\"slot\",\"index\":3},\"sharingService\":{\"@qclass\":\"slot\",\"index\":4},\"contractHost\":{\"@qclass\":\"slot\",\"index\":5},\"registrar\":{\"@qclass\":\"slot\",\"index\":6},\"zoe\":{\"@qclass\":\"slot\",\"index\":7},\"localTimerService\":{\"@qclass\":\"slot\",\"index\":8},\"uploads\":{\"@qclass\":\"slot\",\"index\":9},\"spawner\":{\"@qclass\":\"slot\",\"index\":10},\"wallet\":{\"@qclass\":\"slot\",\"index\":11},\"exchange\":{\"@qclass\":\"slot\",\"index\":12},\"http\":{\"@qclass\":\"slot\",\"index\":13}}]","slots":{"0":"o-52","1":"o-53","2":"o-54","3":"o-55","4":"o-56","5":"o-57","6":"o-58","7":"o-59","8":"o-60","9":"p-62","10":"p-63","11":"p-64","12":"o-61","13":"o-62","length":14}},"4":"p+10","length":5}
anachrophobia strikes vat v3
expected: {"0":"subscribe","1":"p+9","length":2}
got     : {"0":"callNow","1":"d-70","2":"sendResponse","3":{"body":"[1,true,{\"@qclass\":\"error\",\"name\":\"Error\",\"message\":\"historical inaccuracy in replay-send\"}]","slots":{"length":0}},"length":4}
doProcess: Replay failed: [deliver, o+0, inbound, {"body":"[1,{\"type\":\"walletGetInbox\"}]","slots":[]}]: Error: historical inaccuracy in replay-callNow Error <Object <[Object: null prototype] {}>>: historical inaccuracy in replay-callNow
    at replay (eval at <anonymous> (eval at createScopedEvaluatorFactory (/home/warner/bindmounts/trees/cosmic-swingset/node_modules/ses/dist/ses.cjs.js:1308:10)), <anonymous>:2138:15)
    at Object.callNow (eval at <anonymous> (eval at createScopedEvaluatorFactory (/home/warner/bindmounts/trees/cosmic-swingset/node_modules/ses/dist/ses.cjs.js:1308:10)), <anonymous>:2171:32)
    at Proxy.eval (eval at <anonymous> (eval at createScopedEvaluatorFactory (/home/warner/bindmounts/trees/cosmic-swingset/node_modules/ses/dist/ses.cjs.js:1308:10)), <anonymous>:1411:33)
    at Object.inbound (/home/warner/bindmounts/trees/cosmic-swingset/t1/8000/vats/vat-http.js:1840:28)
(node:5988) UnhandledPromiseRejectionWarning: historical inaccuracy in replay-send

```

### PR DESCRIPTION
**Pull request by michaelfig**
Fixes #268

This PR fixes a longstanding problem with anacrophobia in an `ag-solo` that had been subjected to HTTP calls and then restarted.  It also fixes some other sources of nondeterminism in the `ag-solo` replay mechanism due to problems in the timer device integration.

Propagate inboundHandler errors better.  Prevent asynchronous rejection errors.  Synchronise the inbound messages calls.

### CODE REVIEW

File: packages/SwingSet/test/test-devices.js [hunk 1]
```diff
@@ -434,7 +434,7 @@ async function testCommandDeliver(t, withSES) {
   t.end();
 }
 
-test('command deliver without SES', async t => {
+test.only('command deliver without SES', async t => {
```
Comment (warner) [inline packages/SwingSet/test/test-devices.js]: This `.only` needs to be removed, else none of the other swingset tests will run.

File: packages/cosmic-swingset/lib/ag-solo/start.js [hunk 2]
```diff
@@ -123,23 +123,42 @@ async function buildSwingset(
     }
   }
 
+  // This synchronises the processKernel calls between
+  // deliverInboundToMbx and deliverInboundCommand.
+  let lastProcessKernelP = Promise.resolve();
```
Comment (warner) [inline packages/cosmic-swingset/lib/ag-solo/start.js]: I can't visualize this control flow in my head.. does it preserve the ordering of inbound calls when there are two or more queued up?

**Review by warner — CHANGES_REQUESTED** [review]
Please remove the test.only and make sure CI still passes afterwards.

File: packages/cosmic-swingset/lib/ag-solo/start.js [hunk 3]
```diff
@@ -123,23 +123,42 @@ async function buildSwingset(
...
-    // processKernel() call in deliverInbound()
-    await processKernel();
+    p.catch(e => {
+      // Save the exception for us to reraise.
+      // We stuff it in an array in case of `throw undefined`.
+      boxedException = [e];
+    });
+    // Run our processKernel.
+    await processKernelP();
+    if (boxedException) {
```
Comment (FUDCo) [inline packages/cosmic-swingset/lib/ag-solo/start.js]: The interleaving here feels complicated and delicate.  In particular, there seems to be a presumption that if there's an exception in `cm.inboundCommand`, the `p.catch` closure will be run before the promise returned by `processKernelP` resolves.  I can well imagine that's true, but it's not _obviously_ true.  Contrariwise, if you're not expecting this then whether `boxedException` is undefined or not seems stochastic.  Or maybe I'm not understanding this at all.  Anyway, I think I'd like to see an explanatory comment.

**Review by FUDCo — APPROVED** [review]
I'd like to see some extra explanation per my comment, but it's not worth blocking you if that's an issue.

File: packages/SwingSet/test/test-devices.js (hunk 1 above)
Comment (michaelfig) [reply packages/SwingSet/test/test-devices.js]: Gotcha.  My bad.

File: packages/cosmic-swingset/lib/ag-solo/start.js (hunk 3 above)
Comment (michaelfig) [reply packages/cosmic-swingset/lib/ag-solo/start.js]: Good point.  I've simplified this and added some explanatory text.

File: packages/cosmic-swingset/lib/ag-solo/start.js (hunk 2 above)
Comment (michaelfig) [reply packages/cosmic-swingset/lib/ag-solo/start.js]: It was half-baked and wishful.  I've reverted to the prior implementation and TODO comment.

File: packages/cosmic-swingset/lib/ag-solo/start.js [hunk 4]
```diff
@@ -137,10 +137,19 @@ async function buildSwingset(
...
+    p.catch(_ => {});
+
     // TODO: synchronize this somehow, make sure it doesn't overlap with the
-    // processKernel() call in deliverInbound()
+    // processKernel() call in deliverInboundToMbx()
     await processKernel();
-    return p;
+
+    // Rethrow any exception so that our caller must handle it.
+    return p.catch(e => {
```
Comment (FUDCo) [inline packages/cosmic-swingset/lib/ag-solo/start.js:155]: Can you do `p.catch` on the same promise twice?

File: packages/cosmic-swingset/lib/ag-solo/start.js (hunk 2 above)
Comment (michaelfig) [reply packages/cosmic-swingset/lib/ag-solo/start.js]: Nope, I changed my mind and went for the fully-baked version.

File: packages/cosmic-swingset/lib/ag-solo/start.js (hunk 4 above)
Comment (michaelfig) [reply packages/cosmic-swingset/lib/ag-solo/start.js:155]: Yup.  You get the same result in each of the handlers.

**Review by FUDCo — APPROVED** [review]
Well OK then.
