### PR TITLE
Replace old `insist` with new `assert` package

### LINKED ISSUE #78: [ERTP] insist fails to throw exceptions if you don't include the tagged template literal
See: [pull request 522](https://github.com/Agoric/agoric-sdk/pull/522)

The template-based `insist` API can lead to silently ignoring an assertion. If the template literal is left off, no exception is thrown on a failed test. We will change the API to take the message as an optional argument; e.g.,
```
insist(sky.isBlue(), details`${sky.color} should be blue`);
```

The `details` helper will be available as a direct import and as `insist.details`. It returns an object that can print itself with the formatted message, or when `complain` is invoked, will report the real details to the console but include only the `typeof` information in the exception to prevent revealing secrets up the exception path.

Some simultaneous considerations:
- nodejs has an assert library, so our concern (from prior languages) about asserts not being run in production is largely address
- we want the operation to match the package name
- we want to minimize churn atm

so here's the plan
- [ ] name the base test `insist`
- [ ] use compatible signatures with the node `assert` module so we only need a rename later
- [ ] name the reporter `details`
- [ ] add a `toString` for the `details` so that it can be used with other exception mechanisms
- [ ] file a ticket for later to rename `insist` to `assert` and flesh out to match the node assert library

### PR DESCRIPTION
**Pull request by dtribble**
FIXES: [Issue 78](https://github.com/Agoric/agoric-sdk/issues/78)

STATUS: WIP for initial review only

Add an assertion API that that is more like the NodeJS assert library but
that still protects sensitive data from being disclosed through error
paths.

### CODE REVIEW

File: packages/pixel-demo/test/unitTests/pixels/types/test-pixel-list.js [hunk 1]
```diff
@@ -216,7 +216,7 @@ test('pixelList without', t => {
   ]);
   t.throws(
     () => extentOps.without(harden([]), harden([startPixel])),
-    /part is not in whole/,
+    /\(an object\) must be in \(an object\)/,
```
Comment (katelynsills) [inline packages/pixel-demo/test/unitTests/pixels/types/test-pixel-list.js]: This change seems to make our tests less intuitive and helpful. Can we add some context back in since the error message doesn't have the objects?

File: packages/cosmic-swingset/lib/ag-solo/main.js [hunk 2]
```diff
@@ -63,7 +63,7 @@ start
     const { webhost, egresses } = subOpts;
     const basedir = subArgs[0] || AG_SOLO_BASEDIR;
     const subdir = subArgs[1];
-    insist(basedir !== undefined, 'you must provide a BASEDIR');
+    assert(basedir !== undefined, 'you must provide a BASEDIR');
```
Comment (katelynsills) [inline packages/cosmic-swingset/lib/ag-solo/main.js:66]: Does this version, without `details` work?

File: packages/assert/package.json [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+    "lint-fix-jessie": "eslint -c '.eslintrc-jessie.js' --fix '**/*.js'",
+    "lint-check-jessie": "eslint -c '.eslintrc-jessie.js' '**/*.js'"
+  },
+  "repository": {
+    "type": "git",
+    "url": "git+https://github.com/Agoric/agoric-sdk.git"
+  },
+  "keywords": [
+    "assert",
+    "assert"
```
Comment (katelynsills) [inline packages/assert/package.json]: duplicate

File: packages/assert/README.md [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+
+The literal portions of the template are assumed non-sensitive, as
+are the `typeof` types of the substitution values. These are
+assembles into the thrown error message. The actual contents of the
+substitution values are assumed sensitive, to be revealed to the
+console only. We assume only the virtual platform's owner can read
+what is written to the console, where the owner is in a privileged
+position over computation running on that platform.
+
+The optional `details` can be a string for backwards compatibility
```
Comment (katelynsills) [inline packages/assert/README.md:22]: Ah, good to know!

**Review by katelynsills — COMMENTED** [review]
Looks good to me so far. Could we add tests? I'd love to see a test of the kind of usage that broke before. Plus, a comparison of the details`` style versus the node assertion style would be great.

File: packages/cosmic-swingset/lib/ag-solo/main.js (hunk 2 above)
Comment (dtribble) [reply packages/cosmic-swingset/lib/ag-solo/main.js:66]: It does. This was because of making it backwards compatible with the `assert` APIs. It probably means we will eventually want an eslint rule to just use the `details` version to protect any sensitive data.

File: packages/pixel-demo/test/unitTests/pixels/types/test-pixel-list.js (hunk 1 above)
Comment (dtribble) [reply packages/pixel-demo/test/unitTests/pixels/types/test-pixel-list.js]: added more useful text to the error message.

**Comment by katelynsills** [comment]
Still to be done:

- [ ] Add unit tests for `assert`
- [x] Fix uses of `assert` in `store` and `weakStore`. They both had special syntax (see below) to log the keyName rather than obscuring it. 

Example special syntax in store/weakStore. We need to know how to do this with `assert.details`:
```
 const assertKeyDoesNotExist = key =>
    assert(!store.has(key))([`${keyName} already registered`]);
  const assertKeyExists = key =>
    assert(store.has(key))([`${keyName} not found: `, ''], key);
```

File: packages/store/src/store.js [hunk 5]
```diff
@@ -12,26 +12,26 @@ import { insist } from '@agoric/insist';
  */
 function makeStore(keyName = 'key') {
   const store = new Map();
-  const insistKeyDoesNotExist = key =>
-    insist(!store.has(key))([`${keyName} already registered`]);
-  const insistKeyExists = key =>
-    insist(store.has(key))([`${keyName} not found: `, ''], key);
+  const assertKeyDoesNotExist = key =>
+    assert(!store.has(key))([`${keyName} already registered`]);
```
Comment (dtribble) [inline packages/store/src/store.js]: This seems like it cannot be right because assert does not return a function. What's going on here?

File: packages/weak-store/src/weakStore.js [hunk 6]
```diff
@@ -12,26 +12,26 @@ import { insist } from '@agoric/insist';
  */
 function makeStore(keyName = 'key') {
   const wm = new WeakMap();
-  const insistKeyDoesNotExist = key =>
-    insist(!wm.has(key))([`${keyName} already registered`]);
-  const insistKeyExists = key =>
-    insist(wm.has(key))([`${keyName} not found: `, ''], key);
+  const assertKeyDoesNotExist = key =>
+    assert(!wm.has(key))([`${keyName} already registered`]);
```
Comment (dtribble) [inline packages/weak-store/src/weakStore.js]: As above, I don't know how this could work.

Comment (katelynsills) [reply packages/weak-store/src/weakStore.js]: Yes, it doesn't yet work. Mark is working on what the solution might be. https://github.com/Agoric/agoric-sdk/pull/522#issuecomment-584346117

Comment (erights) [reply packages/weak-store/src/weakStore.js]: This pattern is from when `insist()` was returning a template literal tag. Now that `details` is the template literal tag, and the details object is an argument to `assert`, the pattern needs to be redone in terms of that.

File: packages/SwingSet/src/kernel/deviceManager.js [hunk 7]
```diff
@@ -78,7 +78,7 @@ export default function makeDeviceManager(
     insistVatType('object', targetSlot);
     insistCapData(args);
     const target = mapDeviceSlotToKernelSlot(targetSlot);
-    assert(target, `unable to find target`);
```
Comment (dtribble) [inline packages/SwingSet/src/kernel/deviceManager.js]: I thought we backed off on that rule. I was leaving backquotes so that folks could easily add actual data fields.

File: packages/SwingSet/src/kernel/deviceManager.js [hunk 8]
```diff
@@ -38,7 +38,11 @@ export default function makeDeviceManager(
    *    or is otherwise invalid.
    */
   function mapDeviceSlotToKernelSlot(devSlot) {
-    assert.equal(devSlot, `${devSlot}`, details`non-string devSlot: ${devSlot}`);
+    assert.equal(
```
Comment (dtribble) [inline packages/SwingSet/src/kernel/deviceManager.js:41]: this btw was an experiment:  ```assert.equal(actual, expected, details`...`)``` vs. ```assert(actual === expected, details`...`)```. I realized a little ways into rewriting asserts that we want to keep `typeof` comparison as a conditional because then linting rules will ensure we are only testing for valid typeof strings. We could add a `assert.type` assertion, but a) I don't think there's an equivaletn in nodeJS assert (a weak but still notable negative), and b) it loses the lint check.

Are there other expressions that would be best left as conditionals?  The `assert.equal` form is good if you aren't going to actaully provide a details message, because it provides a better default details.

File: packages/SwingSet/src/kernel/kernel.js [hunk 9]
```diff
@@ -245,7 +245,10 @@ export default function buildKernel(kernelEndowments) {
     method = `${method}`;
     // we can't use insistCapData() here: .slots are from the controller's
     // Realm, not the kernel Realm, so it's the wrong kind of Array
-    assert(args.slots !== undefined, details`args not capdata, no .slots: ${args}`);
+    assert(
+      args.slots !== undefined,
```
Comment (dtribble) [inline packages/SwingSet/src/kernel/kernel.js:249]: Similarly this could have been `assert.notEqual` but that didn't seem clearer.

File: packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js [hunk 10]
```diff
@@ -103,7 +103,10 @@ function makeAliceMaker(E, log, contractHost) {
 
           const bobsRawPixel = result.extent[0];
           // TODO this was previously unchecked
-          console.log(`UNCHECKED ASSERTION NOW CHECKED HERE: ${bobsRawPixel.x === rawPixel.x && bobsRawPixel.y === rawPixel.y}`);
```
Comment (dtribble) [inline packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js]: Note, that this assertion is like this because it actually fails. This was the only silently failing one that actually failed. As it turns out, the assertion appears wrong rather than the surrounding code..

**Comment by erights** [comment]
Re https://github.com/Agoric/agoric-sdk/pull/522#pullrequestreview-356319520

The trick in store and weakStore is fixed. The deal is `details` is a function written to be used as a template literal tag, where the template is literal. Here, we want to calculate the string it uses as its template, so we manually feed it the arguments that a template literal expansion would feed it.

**Comment by erights** [comment]
Re https://github.com/Agoric/agoric-sdk/pull/522#pullrequestreview-356384026

Where I found a message argument was a simple string but pointlessly using backquote notation, I changed it to use single quote notation. Otherwise I fear than someone might insert a substitution value but forget to add the `details` template literal tag.

**Comment by erights** [comment]
Re https://github.com/Agoric/agoric-sdk/pull/522#pullrequestreview-356385715

After seeing that there were a good number of tests that something was a string, and that they were mostly doing it by comparison to a coercion-to-string of the same value, I thought it may be worth it to add an `assert.typeof` after all. The coercion has potential side effects, plan interference effects, possible thrown error, etc. The `typeof` test does not.

These happened in https://github.com/Agoric/agoric-sdk/pull/522/commits/618b4a5f1b388197fd8ad99d750a775f8f5f8025 . Have a look. Do you agree?

**Review by erights — CHANGES_REQUESTED** [review]

File: packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js (hunk 10 above)
Comment (erights) [reply packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js]: Now that this is gone, I don't know what it is about. If irrelevant, please resolve.

**Comment by erights** [comment]
Everything already there works again.

Still have yet to write the new unit tests.

File: packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js (hunk 10 above)
Comment (erights) [reply packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js]: Nevermind. I was looking at the wrong vat-alice.js

File: packages/same-structure/src/sameStructure.js [hunk 11]
```diff
@@ -161,12 +165,13 @@ function pathStr(path) {
...
   function complain(problem) {
-    const template = harden([
-      `${message}: ${problem} at ${pathStr(path)}: (`,
-      ') vs (',
-      ')',
-    ]);
-    insist(false)(template, left, right);
+    assert.fail(
+      details(
+        [`${message}: ${problem} at ${pathStr(path)}: (`, ') vs (', ')'],
```
Comment (erights) [inline packages/same-structure/src/sameStructure.js]: This is the other place we're dynamically computing a normally static template, and then manually calling the `details` template tag as a function.

File: packages/zoe/src/contracts/helpers/bondingCurves.js [hunk 12]
```diff
@@ -24,7 +24,10 @@ export const makeConstProductBC = (zoe, assays) => {
      */
     getPrice: (poolUnitsArray, unitsIn, feeInTenthOfPercent = 3) => {
       Nat(feeInTenthOfPercent);
-      insist(feeInTenthOfPercent < 1000)`fee is not less than 1000`;
+      assert(
+        feeInTenthOfPercent < 1000,
+        details`fee ${feeInTenthOfPercent} is not less than 1000`,
```
Comment (erights) [inline packages/zoe/src/contracts/helpers/bondingCurves.js:29]: I added the failing fee here. One of my rare observable changes in this PR.

File: packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js [hunk 13]
```diff
@@ -102,7 +102,12 @@ function makeAliceMaker(E, log, contractHost) {
           showPaymentBalance('childPayment2', childPayment2);
 
           const bobsRawPixel = result.extent[0];
-          insist(
+          // TODO this was previously unchecked
```
[the remark this answers is not in the document]
Comment (dtribble) [reply packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js]: Before my change, it was in fact an assert. Kate changed it to a console log to see what was up. Up to you two whether there is an assertion there to be checked.

File: packages/assert/src/assert.js [hunk 14]
```diff
@@ -56,27 +64,28 @@ function fail(optDetails = details`Assert failed`) {
...
-// with nodejs assertion library.
+// The optional `optDetails` can be a string for backwards compatibility
+// with the nodejs assertion library.
 function assert(flag, optDetails = details`check failed`) {
   if (!flag) {
     console.log(`FAILED ASSERTION ${flag}`);
     fail(optDetails);
   }
 }
-assert.details = details;
```
Comment (dtribble) [inline packages/assert/src/assert.js]: the advantage of `assert.details` is that it's easier to pass the single `assert` as an endowment, and it does match a certain style of usage that I've seen with various libraries.  I understand not wanting to support more than one pattern, but the first argument might be compelling.

File: packages/SwingSet/src/vats/comms/parseRemoteSlot.js [hunk 15]
```diff
@@ -7,7 +7,7 @@ import { assert, details } from '@agoric/assert';
 // message, and "-" when allocated by the sender of the message.
 
 export function parseRemoteSlot(s) {
-  assert(s, `${s}`, details`${s} is not a string`);
+  assert.equal(s, `${s}`, details`${s} is not a string`);
```
Comment (dtribble) [inline packages/SwingSet/src/vats/comms/parseRemoteSlot.js]: This may now become `assert.typeof`... of course :)

File: packages/assert/src/assert.js (hunk 14 above)
Comment (erights) [reply packages/assert/src/assert.js]: Sure, I could see one or the other. But not both. Of the two, I prefer what we kept.

File: packages/default-evaluate-options/test/test.js [hunk 16]
```diff
@@ -5,7 +5,7 @@ import makeDefaultEvaluateOptions from '../src';
 test('sanity', async t => {
   try {
     const options = makeDefaultEvaluateOptions();
-    t.assert(Array.isArray(options.shims), `options.shims is an array`);
+    t.assert(Array.isArray(options.shims), 'options.shims is an array');
```
Comment (dtribble) [inline packages/default-evaluate-options/test/test.js:8]: I'm not sure whether you are making these changes because of a lint rule?  If so, I thought we had turned that one off. It's one of the objectionable ones from AirBNB.  If you actaully generally prefer that (but don't require that) then that's fine :)

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 17]
```diff
@@ -317,7 +317,7 @@ export default function makeKernelKeeper(storage) {
   }
 
   function getVatIDForName(name) {
-    assert(name === `${name}`, details`${name} is not a string`);
+    assert.equal(name, `${name}`, details`${name} is not a string`);
```
Comment (dtribble) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: another `assert.typeof` which might actaully have gotten changed in a later checking.

File: packages/store/src/store.js [hunk 18]
```diff
@@ -13,9 +13,12 @@ import { assert, details } from '@agoric/assert';
...
   const store = new Map();
   const assertKeyDoesNotExist = key =>
-    assert(!store.has(key))([`${keyName} already registered`]);
+    assert(
+      !store.has(key),
+      details([`${keyName} already registered: `, ''], key),
+    );
   const assertKeyExists = key =>
-    assert(store.has(key))([`${keyName} not found: `, ''], key);
+    assert(store.has(key), details([`${keyName} not found: `, ''], key));
```
Comment (dtribble) [inline packages/store/src/store.js]: this still seems way too clever. What would it be like using just normal assert usage?

File: packages/SwingSet/src/vats/comms/parseRemoteSlot.js (hunk 15 above)
Comment (erights) [reply packages/SwingSet/src/vats/comms/parseRemoteSlot.js]: Already done ;)

File: packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js (hunk 13 above)
[the remark this answers is not in the document]
Comment (erights) [reply packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js]: @katelynsills what is this for? What should we do with this?

File: packages/same-structure/src/sameStructure.js [hunk 19]
```diff
@@ -165,12 +165,13 @@ function pathStr(path) {
...
 function mustBeSameStructureInternal(left, right, message, path) {
   function complain(problem) {
-    const template = harden([
-      `${message}: ${problem} at ${pathStr(path)}: (`,
-      ') vs (',
-      ')',
-    ]);
-    insist(false)(template, left, right);
+    assert.fail(
+      details(
```
Comment (dtribble) [inline packages/same-structure/src/sameStructure.js]: Still too much magic for me. At least please put in a comment explaining the template magic. I couldn't maintain this code when I was changing the formats.

File: packages/assert/src/assert.js [hunk 20]
```diff
@@ -95,8 +95,19 @@ function equal(
 ) {
   assert(actual === expected, optDetails);
 }
+
+function assertTypeof(
+  specimen,
+  typename,
+  optDetails = details(['', ` must be ${an(typename)}`], specimen),
```
Comment (dtribble) [inline packages/assert/src/assert.js]: why can't this just be ```optDetails = details`${specimen} must be ${an(typename)}` ```?

File: packages/default-evaluate-options/test/test.js (hunk 16 above)
Comment (erights) [reply packages/default-evaluate-options/test/test.js:8]: Not a lint rule and not a general preference. I prefer it here because we'll normally write a `details` tagged template literal here. I didn't want to make it easy to insert a substitution value and miss the absence of the `details` tag. That would leak info in a way no one would catch until too late.

File: packages/assert/src/assert.js (hunk 20 above)
Comment (dtribble) [reply packages/assert/src/assert.js]: I'm trying to avoid demanding knowledge of the template API rather than the template usage.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 17 above)
Comment (erights) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: yup. already done.

File: packages/store/src/store.js (hunk 18 above)
Comment (erights) [reply packages/store/src/store.js]: What do you mean "normal". It is using the calculated `keyName` both on the console and the thrown error. It is passing the `key` value only to the console and throwing only the typeof the `key` value. How would you write it?

Actually, I agree about it being too clever though. Here, it's encapsulated within the `assertKey*Exists` abstractions. But it appears again in `sameStructure`. I don't have a good idea.

File: packages/assert/src/assert.js (hunk 20 above)
Comment (erights) [reply packages/assert/src/assert.js]: Because in the thrown error you wouldn't reveal the contents of `an(typename)` but rather its typeof, which would always be `(a string)` and therefore confusing.

File: packages/same-structure/src/sameStructure.js (hunk 19 above)
Comment (erights) [reply packages/same-structure/src/sameStructure.js]: I agree. I'll comment this in assert and put comment citations everywhere I do this.

But running out of steam tonight. Will resume tomorrow.

File: packages/store/src/store.js (hunk 18 above)
Comment (dtribble) [reply packages/store/src/store.js]: Among other things, this should not be constructing a template string dynamically in an assert. One of the typical goals of the assert logic (albeit minor for JS I know) is to minimize the allocations in the case where the assert passes. Thus, you create the details object but don't do any string mucking unless the assert is actually failed.

What's wrong with:
```assert(store.has(key), details`${keyName} ${key} not found`);```

File: packages/assert/src/assert.js (hunk 20 above)
Comment (dtribble) [reply packages/assert/src/assert.js]: That makes me want separate methods then, that could have the string allocated once. Having to concat together a string every time I think I'm just doing a constant compare is the kind of surprise that leads to performance death of a thousand cuts. Or rather, reluctance to use simple type assertions because somehow they are more expensive than less clear ones :)

Comment (erights) [reply packages/assert/src/assert.js]: That's a good point I wasn't thinking about. I'll try a different idea tomorrow.

Comment (erights) [reply packages/assert/src/assert.js]: @dtribble Take a look at the new `openDetail` declassifier and its uses.

File: packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js (hunk 13 above)
[the remark this answers is not in the document]
Comment (katelynsills) [reply packages/pixel-demo/test/swingsetTests/gallery/vat-alice.js]: I think we should drop the assertion rather than spend time on fixing the pixel demo. That makes me think we should move it to Agoric-labs so monorepo-wide changes don't require us to dig into the pixel demo...

**Comment by erights** [comment]
@dtribble because you are the supposed author, I couldn't add you as a reviewer. Please consider yourself a reviewer anyway.

File: packages/store/src/store.js (hunk 18 above)
Comment (erights) [reply packages/store/src/store.js]: > What's wrong with...

The message in the thrown error would be
`(a string) (an object) not found`
when we'd like something more informative like
`asset (an object) not found`.

In any case, now fixed via `openDetail`. Done.

File: packages/same-structure/src/sameStructure.js (hunk 19 above)
Comment (erights) [reply packages/same-structure/src/sameStructure.js]: Fixed via `openDetail`. Done.

**Review by erights — APPROVED** [review]
Since it thinks I'm the author requesting review, I'm just approving myself, which isn't real. Will wait for actual reviewers @katelynsills and (original author) @dtribble

**Review by katelynsills — APPROVED** [review]
Looks good to me! 

We should probably have documentation for this. I'll make an issue on the documentation site for adding docs on assert.

**Comment by erights** [comment]
@dtribble do you want me to wait for your review, or should I go ahead and merge?

**Comment by katelynsills** [comment]
> @dtribble do you want me to wait for your review, or should I go ahead and merge?

@erights I just added Dean in person and he says it's good to go.
