### PR TITLE
test(a3p): extend governance test coverage for acceptance proposal

### LINKED ISSUE #10708: z:acceptance governance fails/flakes: No quorum
I'm getting a ci failure in an unrelated PR:
https://github.com/Agoric/agoric-sdk/pull/10692#issuecomment-2547042803

This `readLatestHead` immediate assumes vstorage updates by the time the deadline is reached; I don't think that's necessarily the case:

https://github.com/Agoric/agoric-sdk/blob/3e27c74e5385180799f500232d795508e275c687/a3p-integration/proposals/z%3Aacceptance/governance.test.js#L100-L106

A `retryUntilCondition` seems in order.

I don't know whether it's a flake. It failed again.

https://github.com/Agoric/agoric-sdk/actions/runs/12345315961/job/34449230334?pr=10692#step:10:8388

cc @frazarshad @LuqiPan  @Chris-Hibbert

### PR DESCRIPTION
**Pull request by Jorge-Lopes**
closes: https://github.com/Agoric/BytePitchPartnerEng/issues/24
closes: https://github.com/Agoric/agoric-sdk/issues/10708

## Description

This PR has the objective of extending the a3p-integration acceptance proposal test coverage. More specifically, it intend to test that:
- Configured EC governed parameters are intact following the contract upgrade
- Governance proposals history is visible

The test plan to verify that the parameters governed by the economicCommittee are intact when the contract is upgraded is:
- Propose a parameter change
- Verify that the value was updated
- Execute a null upgrade to the respective contract
- Verify that the value kept the same

Although more contracts are governed by economicCommittee, the ones selected to be included in this test case were `vaultFactory` and `provisionPool`. A detailed discussion on the rationale behind this decision can be found at https://github.com/Agoric/BytePitchPartnerEng/issues/24

Note: The existing governance test and helper functions were refactored to allow the `makeGovernanceDriver` function to be contract agnostic, in order to be reused by vaultFactory, provisionPool and any other contract that is intend to be tested in the future.

The test plan is to verify that the vstorage node published.committees.Economic_Committee.latestQuestion displays the history of proposed Economic Committee parameter changes is:
- Use the readHistory method to fetch all parameter change proposals from latestQuestion node, starting from block height 0.
- Verify that returned value is not an empty list
- Construct a list of expected parameters changes proposed by the economic committee prior to the governance test.
- Compare the parameters keys of both lists match.

### Security Considerations

No security considerations.
### Scaling Considerations

The "Governance proposals history" test compares vstorage values against a hardcoded list, requiring manual updates to expectedParametersChanges for new proposals or tests that executes a EC governed param changes made prior to this test. 

To prevent the halting the test when the developer does not update the hardcoded list, this test is only asserting that the value returned from the published.committees.Economic_Committee.latestQuestion vstorage node is not empty.
Then it will compare both lists and if any mismatches is found, it will:
- print an error message notifying the mismatch. 
- print both current and expected changes proposals records

Note that this solution may risks oversight and could lead to latent issues, so I am open a implement a new design if desired.

### Documentation Considerations

We propose adding a table to the z:acceptance README file. This table will:
- List the parameters being modified during acceptance test execution.
- Identify where and why these changes occur, providing developers with a clear understanding of parameter dependencies.

An [issue](https://github.com/Agoric/BytePitchPartnerEng/issues/43) was created to address this task.

### Testing Considerations

The methods exported by `makeVstorageKit` at the `@agoric/client-utils` package, seems to display an unexpected behaviour, more specifically, when using the `readFully` method to query Vstorage node full history. 
As a workaround, I updated the `makeVStorage` function at `z:acceptance/test-lib/rpc.js` to follow the same implementation as the `multichain-testing/tools/batchQuery.js.`
The rational behind this decision is explained in detail on the issue #10574 

If desired, I can add these changes to `@client-utils/src/vstorage.js` in a future PR, contribute to the ongoing effort of reducing the dependency of the acceptance test-lib.

The order of execution of the acceptance tests had to be updated to make sure that the `governance.test.js` would run after the state-sync acceptance tests to prevent the behavior described here #10574 

### Upgrade Considerations

No upgrade considerations.

### CODE REVIEW

File: a3p-integration/proposals/z:acceptance/test-lib/utils.js [hunk 1]
```diff
@@ -93,3 +95,29 @@ export const makeTimerUtils = ({ setTimeout }) => {
...
+ * This function solves the limitation of getIncarnation when multiple Vats
+ * are returned for the provided vatName and does not return the incarnation
+ * of the desired Vat (e.g. zcf-mintHolder-USDC)
+ * @param {string} vatName
+ * @returns {Promise<number>}
+ */
+const getIncarnationFromDetails = async vatName => {
+  const matchingVats = await getDetailsMatchingVats(vatName);
+  const expectedVat = matchingVats.find(vat => vat.vatName === vatName);
+  console.log('Vat: ', expectedVat);
```
Comment (Chris-Hibbert) [inline a3p-integration/proposals/z:acceptance/test-lib/utils.js]: A library function should probably not log like this.

File: a3p-integration/proposals/z:acceptance/test-lib/utils.js [hunk 2]
```diff
@@ -93,3 +95,29 @@ export const makeTimerUtils = ({ setTimeout }) => {
...
+/**
+ * This function solves the limitation of getIncarnation when multiple Vats
+ * are returned for the provided vatName and does not return the incarnation
+ * of the desired Vat (e.g. zcf-mintHolder-USDC)
+ * @param {string} vatName
+ * @returns {Promise<number>}
+ */
+const getIncarnationFromDetails = async vatName => {
+  const matchingVats = await getDetailsMatchingVats(vatName);
+  const expectedVat = matchingVats.find(vat => vat.vatName === vatName);
```
Comment (Chris-Hibbert) [inline a3p-integration/proposals/z:acceptance/test-lib/utils.js:108]: should this fail if the name doesn't uniquely match a single vat?  It seems like that could lead to surprising errors.

File: packages/vats/src/proposals/upgrade-vaultFactory-proposal.js
Comment (Chris-Hibbert) [inline packages/vats/src/proposals/upgrade-vaultFactory-proposal.js:1]: Please add @file comments here and in `./upgrade-vaults.js` with mutual cross-references, and say that this one is intended to be generic and reusable, while the other does several things that are specific to upgrade-18.

File: a3p-integration/proposals/z:acceptance/governance.test.js [hunk 3]
```diff
@@ -87,22 +59,175 @@ test.serial(
...
+      provisionPoolParamsAfter.current.PerAccountInitialAmount,
+      provisionPoolParamsBefore.current.PerAccountInitialAmount,
+      'provisionPool governed parameters did not match',
+    );
+  },
+);
+
+test.serial('Governance proposals history is visible', async t => {
+  /*
+   * List ordered from most recent to latest of Economic Committee
```
Comment (Chris-Hibbert) [inline a3p-integration/proposals/z:acceptance/governance.test.js]:
```suggestion
   * List ordered from most recent to earliest of Economic Committee
```

File: a3p-integration/proposals/z:acceptance/test-lib/rpc.js [hunk 4]
```diff
@@ -0,0 +1,291 @@
+/** @file copied from packages/agoric-cli */
+// TODO DRY in https://github.com/Agoric/agoric-sdk/issues/9109
```
Comment (Chris-Hibbert) [inline a3p-integration/proposals/z:acceptance/test-lib/rpc.js]: I understand why we have to duplicate stuff from `synthetic-chain`. If we can import from `@agoric/internal`, why do we need to repeat code that's in `agoric-cli`?

I looked around and didn't find where these functions were copied from.  Are they in agoric-sdk?

**Review by Chris-Hibbert — COMMENTED** [review]
Nice cleanup/enhancement of the governance driver.

File: a3p-integration/proposals/z:acceptance/test-lib/utils.js (hunk 1 above)
Comment (Jorge-Lopes) [reply a3p-integration/proposals/z:acceptance/test-lib/utils.js]: Change request addressed

File: a3p-integration/proposals/z:acceptance/test-lib/utils.js (hunk 2 above)
Comment (Jorge-Lopes) [reply a3p-integration/proposals/z:acceptance/test-lib/utils.js:108]: Thank you for bringing this to my attention.
An assert call was included to verify that `expectedVat` is not undefined.

File: a3p-integration/proposals/z:acceptance/governance.test.js (hunk 3 above)
Comment (Jorge-Lopes) [reply a3p-integration/proposals/z:acceptance/governance.test.js]: Change request addressed

File: a3p-integration/proposals/z:acceptance/test-lib/rpc.js (hunk 4 above)
Comment (Jorge-Lopes) [reply a3p-integration/proposals/z:acceptance/test-lib/rpc.js]: That comment was kept from the original rpc.js file, which end up being deleted in a previous PR and reintroduced on this one.
I updated the description to reflect the current implementation of rpc.js.

File: packages/vats/src/proposals/upgrade-vaultFactory-proposal.js
Comment (Jorge-Lopes) [reply packages/vats/src/proposals/upgrade-vaultFactory-proposal.js:1]: Change request addressed

File: a3p-integration/proposals/z:acceptance/test-lib/utils.js (hunk 2 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/z:acceptance/test-lib/utils.js:108]: That checks the difference between 0 and at least 1. I was asking whether we need to worry about the difference between 1 and more than 1.  `find` will return the first instance. Do we need to worry about `getIncarnationFromDetails` returning a different vat than was intended because the `vatName` would have matched more than one vat?

File: packages/vats/src/proposals/upgrade-vaultFactory-proposal.js [hunk 5]
```diff
@@ -0,0 +1,124 @@
+/**
+ * @file this core-eval proposal is a generic and reusable script for executing
+ *   a Vault Factory null upgrade. In contrast, upgrade-vaults.js is a specific
```
Comment (Chris-Hibbert) [inline packages/vats/src/proposals/upgrade-vaultFactory-proposal.js]: a "null upgrade" is one where the contract code doesn't change. This one uses the bundleRef from the provided `contractRef`, so it will do an actual upgrade.
```suggestion
 * @file this core-eval proposal is a generic and reusable script for executing
 *   a Vault Factory upgrade. In contrast, upgrade-vaults.js is a specific
```

**Review by Chris-Hibbert — COMMENTED** [review]
One remaining substantive question

File: a3p-integration/proposals/z:acceptance/test-lib/utils.js (hunk 2 above)
Comment (Jorge-Lopes) [reply a3p-integration/proposals/z:acceptance/test-lib/utils.js:108]: I don't think that should be a concern.
Assuming that getDetailsMatchingVats will return all vats that can be related with the provided vat name, and that vat names are unique, we can be confident that the strict equality operator will will one be true for the single instance that we intend to get.

**Review by Chris-Hibbert — APPROVED** [review]

File: a3p-integration/proposals/z:acceptance/test-lib/governance.js [hunk 6]
```diff
@@ -144,12 +158,93 @@ export const makeGovernanceDriver = async (fetch, networkConfig) => {
...
+    assert(
+      committeeInvitationForVoter,
+      `${address} must have committee invitation`,
+    );
+
+    return committeeInvitationForVoter;
+  };
+
+  const getLatestQuestion = async () => {
+    const { latestOutcome, latestQuestion } = await await retryUntilCondition(
```
Comment (anilhelvaci) [inline a3p-integration/proposals/z:acceptance/test-lib/governance.js]: any reason for a double `await` here?

Comment (Jorge-Lopes) [reply a3p-integration/proposals/z:acceptance/test-lib/governance.js]: No, that was a mistake that skipped my attention.
Thank you for noticing.

**Comment by anilhelvaci** [comment]
@mergifyio requeue
