### PR TITLE
fix(smart-wallet): handle {} wallet update records in client utils

### LINKED ISSUE #7777: inter bid list errors with "unknown record updated undefined"
## Describe the bug
`agops inter bid list` returns:

```
(Error#1)
Error#1: unknown record updated undefined

  at Object.update (packages/smart-wallet/src/utils.js:73:15)
  at storedWalletState (packages/agoric-cli/src/lib/wallet.js:228:17)
  at async Promise.all (index 1)
  at async Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:573:34)
  at async packages/agoric-cli/src/bin-agops.js:78:3
```

## To Reproduce
1. `cd packages/deployment/upgrade-test && make build run`
2. place some bids
3. note bids are accepted and wallet UI shows bids as pending
4. `agops inter bid list --from $GOV1ADDR --keyring-backend=test --all`

2 and 3 are optional and I was able to reproduce with 1 and 4.

## Expected behavior

Current bids are listed, and empty if no bids.

## Platform Environment

* Via docker upgrade-test.
* Current HEAD: 8d17ccef5b83f5feff95318e234067d1866edd8d
* `git describe --tags --always`: agoric-upgrade-8-2726-g8d17ccef5

## Additional context

@otoole-brendan first observed this while placing bids.

## Screenshots
TODO: @otoole-brendan screenshots?

### PR DESCRIPTION
**Pull request by dckc**
closes: #7777

## Description

Handle the `{}` wallet update records introduced in #7763.

Also: suppress other diagnostics about wallet update records being not quite right. They're uninteresting in contexts such as `inter bid list`.

### Security Considerations

suppressing diagnostics could hide some problems. a `--verbose` flag could be a useful enhancement.

### Scaling Considerations

n/a

### Documentation Considerations

The possibility of a `{}` is documented in the return type of `makeWalletStateCoalescer`.

### Testing Considerations

ok to skip the unit test for this basically 1-line fix?

### CODE REVIEW

**Review by raphdev — COMMENTED** [review]
Can confirm this closes #7777  by running `cd packages/deployment/upgrade-test && make local_sdk build_test run`:

`agops inter bid list --from $GOV1ADDR` (with and without `-all`) return empty as expected with no bids.

Placing a sample bid, then querying it:

`agops inter bid by-price --give 2IST --price 8.55 --from $GOV1ADDR --keyring-backend=test`
```shell
# agops inter bid list --from $GOV1ADDR
{"id":"bid-1684359303459","price":"8.55 IST/ATOM","give":{"Bid":"2 IST"},"maxBuy":"1000000 ATOM","result":"Your bid has been accepted"}
```

File: packages/smart-wallet/src/utils.js [hunk 1]
```diff
@@ -1,10 +1,12 @@
 /* eslint-disable no-undef-init */
-import { deeplyFulfilledObject, objectMap } from '@agoric/internal';
+import { deeplyFulfilledObject, objectMap, makeTracer } from '@agoric/internal';
 import { observeIteration, subscribeEach } from '@agoric/notifier';
 import { E } from '@endo/far';
 
 export const NO_SMART_WALLET_ERROR = 'no smart wallet';
 
+const trace = makeTracer('WUTIL', false);
```
Comment (turadg) [inline packages/smart-wallet/src/utils.js:8]: the `warn` and `error` sent to STDERR but this will send to STDOUT. I suppose now that it's disabled by default whoever enables it will understand the this can mix with any JSON output. (I don't recall whether this command has any)

**Review by turadg — APPROVED** [review]
Thanks for the usage confirmation @raphdev !

File: packages/smart-wallet/src/utils.js [hunk 2]
```diff
@@ -19,16 +21,19 @@ export const makeWalletStateCoalescer = (invitationBrand = undefined) => {
    */
   const invitationsReceived = new Map();
 
-  /** @param {import('./smartWallet').UpdateRecord} updateRecord newer than previous */
+  /** @param {import('./smartWallet').UpdateRecord | {}} updateRecord newer than previous */
```
Comment (samsiegart) [inline packages/smart-wallet/src/utils.js:24]: I had better results doing `Partial<UpdateRecord>` rather than `UpdateRecord | {}` in `wallet-app` (where the source is `.ts`). Otherwise it would say `property "updated" doesn't exist on type {} blah blah blah` no matter what. If it works here that's cool though.

**Review by samsiegart — APPROVED** [review]
