### PR TITLE
fix: command injection

### LINKED ISSUE #6731: Command Injection in agoric cli
There are some areas where command injection is possible when using an argument of the agoric and agops commands.  

e.g.

```
./agoric-sdk/packages/agoric-cli/bin/agoric wallet provision --account agoric1z5ralnet3yy8ly0ezhmp5797m3g2k0cfdhh0pc --nickname '$(touch /tmp/execed)' --spend
```

Moving from a one-string `execSync` to `execFileSync` will parameterize the arguments correctly.

### PR DESCRIPTION
**Pull request by arirubinstein**
closes: #6731 

## Description

Attempts to migrate from `execSync` to `execFileSync`

### Security Considerations

less command injection!

### Testing Considerations

Manually tested with psmload flow

### CODE REVIEW

File: packages/agoric-cli/src/commands/perf.js [hunk 1]
```diff
@@ -86,12 +86,12 @@ export const makePerfCommand = async logger => {
       void watchForSatisfied();
 
       // now execute
-      let cmd = `wallet-action --allow-spend "$(cat ${opts.executeOffer})"`;
+      let cmd = ['wallet-action', '--allow-spend', payloadStr];
       if (opts.keyringBackend) {
-        cmd = cmd.concat(' --keyring-backend ', opts.keyringBackend);
+        cmd = cmd.concat([`--keyring-backend=${opts.keyringBackend}`]);
```
Comment (turadg) [inline packages/agoric-cli/src/commands/perf.js]: non-blocking request: make `const cmd` and  append each item:
```suggestion
        cmd.push(`--keyring-backend=${opts.keyringBackend}`);
```
now that it's an array, the symbol doesn't need to be rebound to amend it. it also makes it read more clearly.

**Review by turadg — APPROVED** [review]
LGTM, modulo one code quality suggestion

**Comment by arirubinstein** [comment]
> LGTM, modulo one code quality suggestion

TIL you can `.push` a `const []`
