### PR TITLE
fix(swingset): move upgrade() vatParameters into options bag

### LINKED ISSUE #5345: vat upgrade should put vatParameters in an option bag
## What is the Problem Being Solved?

Vats are created with `vatAdminService~.createVat(bundleCap, options)`, where `options` includes `{ vatParameters }` and others.

Vats are upgraded with `adminFacet~.upgrade(newBundleCap, newVatParameters)`.

We should change this to be `upgrade(newBundleCap, { vatParameters })`, for parallelism with the original creation API, and to start an options bag for later.

Note that we don't currently have any other options. Many of the options available during initial creation are not changable by upgrade (e.g. the `managerType` is fixed at creation time). I don't currently think any of those other options are worth changing during upgrade, or it would be difficult to allow them to be changed. But `vatParameters` is how we'll give a new contract bundlecap to ZCF, so it's important to be replaceable.

## Description of the Design

Change the function signature.

## Security Considerations

None

## Test Plan

Update the existing unit tests

### PR DESCRIPTION
**Pull request by warner**
Previously, the parent vat did `E(adminFacet).upgrade(vatParameters)`

Now it does `E(adminFacet).upgrade(bundleCap, { vatParameters })`

This matches the way `vatParameters` are passed to the original
`createVat()` call.

All other options are rejected.

This changes the `adminFacet` API, but internally continues to send
`vatParameters` in their own argument to the underlying device
nodes. If/when we send actual options, we'll need to decide whether to
change the shape of the device node API by converting `vatParameters`
into `options`, or just add additional arguments.

closes #5345

### CODE REVIEW

File: packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js [hunk 1]
```diff
@@ -98,7 +98,13 @@ export function buildRootObject(vatPowers) {
       done() {
         return doneP;
       },
-      upgrade(bundlecap, vatParameters) {
+      upgrade(bundlecap, options) {
```
Comment (FUDCo) [inline packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js]: `options` should default to `{}`, so existing code that isn't using it don't need to change.

**Review by FUDCo — CHANGES_REQUESTED** [review]
One minor thing I really think should be tweak, but other than that it looks good to me.

File: packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js (hunk 1 above)
Comment (FUDCo) [reply packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js]: Hmm.  On second thought I'm not sure how downstream code will handle a missing `vatParameters` parameter.  I had been thinking you could get away with leaving it off if you didn't have any parameters, and maybe you could have.  If so, you should still be able to do that.  If not, maybe you should.

Comment (warner) [reply packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js]: Good catch!

I guess omitting `vatParameters` in the upgrade should get you the same value as you'd get omitting it in the original `createVat`. That *ought* to be `undefined`, but now that I'm looking at the code, I'm not sure that's what happens. I'll add a test.

**Review by FUDCo — APPROVED** [review]
は、私にはよく見えますよ
