### PR TITLE
fix(SwingSet): Don't send stopVat during upgrade

### LINKED ISSUE #6650: remove stopVat(): allow vat upgrade without participation of old vat version
## What is the Problem Being Solved?

Our current mechanism for upgrading vats requires two steps:
* send a `stopVat()` to the old version, giving it a chance to clean up and shut down
* create a new worker (with the new version), send it a `startVat()` to launch/resume everything under the new code

The reasons we built upgrade with a `stopVat` include:
* currently, the vat knows more about what data can be deleted than the kernel, so it seemed easier to let the vat drive the GC-like reference chasing (e.g. when a durable object is only referenced by a merely-virtual object, so the durable one should be deleted across the upgrade)
  * although we decided to defer most of the data-deletion for a future version, to reduce the risk of things going wrong during `stopVat`, at the cost of leaking some DB space
    * OT3H we don't expect vats to use a lot of merely-virtual (non-durable) objects, so the leak that represents may be insignificant
      * OT4H MarkM doesn't necessarily agree with me on that expectation
* the vat's virtual object manager (VOM) has an LRU cache that needs to be flushed: it has unwritten changes to durable objects which must reach the DB before the old version is retired

But we've talked about getting rid of the `stopVat` step, because:
* it's awkward that we depend upon the old version to assist in its own cleanup
* if the old version is sufficiently broken (thus in need of upgrade), is it functional enough to complete the `stopVat` without error?
* we don't know how long the vat will take to do `stopVat`; no user-space code is run, but it still raises the question of whether we should be doing some sort of metering
* if something goes wrong during `stopVat`, the vat is now un-upgradeable, and we're kinda stuck

While we haven't really committed to removing it, we'd like to.

To do that, we need to have the kernel take over responsibility for everything we currently delegate to `stopVat()`.

The [`stopVat()`](https://github.com/Agoric/agoric-sdk/blob/162fdf2a51c54e2da89c8ed35f06cab09fb013d2/packages/SwingSet/src/liveslots/liveslots.js#L1508) call currently does:
* for all locally-decided ("exported") Promises that are being tracked by a durable promise watcher, remember that they are rejected, so the new `startVat()` can notify the follower callbacks: https://github.com/Agoric/agoric-sdk/blob/162fdf2a51c54e2da89c8ed35f06cab09fb013d2/packages/SwingSet/src/liveslots/liveslots.js#L1529-L1532
* reject all exported Promises with the kernel-supplied `disconnectObject`: https://github.com/Agoric/agoric-sdk/blob/162fdf2a51c54e2da89c8ed35f06cab09fb013d2/packages/SwingSet/src/liveslots/stop-vat.js#L307
* enumerate all the exported ephemeral objects (Remotables) and non-durable virtual objects (exported Representatives of non-durable Kinds), and call `syscall.abandonExport()` on their vrefs: https://github.com/Agoric/agoric-sdk/blob/162fdf2a51c54e2da89c8ed35f06cab09fb013d2/packages/SwingSet/src/liveslots/stop-vat.js#L315-L318
* flush the virtual-object-manager LRU cache (a side-effect of the BOYD call at https://github.com/Agoric/agoric-sdk/blob/162fdf2a51c54e2da89c8ed35f06cab09fb013d2/packages/SwingSet/src/liveslots/stop-vat.js#L348 , currently accidentally missing, see #6604)
* a lot of other data-deletion code is commented out (see above), because it's complex, risky, potentially slow, and was incomplete anyways

## Description of the Design

First, we need to decide what to do about the LRU cache. Either we make it a write-through cache (so it's never stale, and doesn't need flushing), remove it entirely, or require a BOYD delivery in place of the `stopVat` (to allow the cache to be flushed, and incidentally providing one last chance to decrement references, which may reduce the amount of durable data retained across the upgrade boundary). Requiring a BOYD has many of the same issues as requiring stopVat: if the vat is really confused, it might not work, and thus break the upgrade. OTOH, BOYD avoids userspace interaction just as much as stopVat does, so the confusion would have to be in liveslots or lower for it to cause a problem.

Doing a BOYD before upgrade *does* have the potential to reduce the amount of data being retained across the upgrade, which might make things faster (and/or leak less data, until we manage to implement a full mark/sweep of the vatstore). I'm undecided about how the simplicity of not doing it compares to the consequences.

Then, we need to reject all the vat's old Promises. We already have code to locate these, in `cleanupAfterTerminatedVat()`, in https://github.com/Agoric/agoric-sdk/blob/162fdf2a51c54e2da89c8ed35f06cab09fb013d2/packages/SwingSet/src/kernel/state/kernelKeeper.js#L855-L856 , which walks the vat's c-list for kpids and looks for the ones that are unresolved and decided by the terminated vat. We can factor out this code and use it to perform the same search for vat upgrade, not just vat termination. There are two additional considerations:
* We implemented "durable promise watchers", which allows a vat to subscribe a durable callback to an arbitrary promise (any promise with a vpid, so imported/exported/stored-in-virtual-data). If the vat uses this to subscribe to one of its own promises, then the upgrade will reject the promise (as usual), and the new version must receive the callback. We have code in `stopVat` to record the list of these rejected vpids (in the vatstore, inside a durable collection named `watchedPromises`), and code in `startVat` to invoke the registered callbacks. If the kernel does the rejection, we'll need some way to inform the `startVat` about the vpids and the rejection data.
  * one option is to have the kernel record the vpids, in the same place that `stopVat` used to
  * perhaps a better one would be for `startVat` to acquire an additional argument, with the list of vat-decided non-durable vpids that we rejected during upgrade, so it can walk the saved registration table and issue the callbacks
  * a third might be to deliver `dispatch.notify()` for all the rejected promises after the `startVat`
  * in any case, efficiency is a consideration: the vat might have a lot of outstanding promises, but only register a watcher on a tiny number of them
    * we might use `syscall.subscribe()` to inform the kernel about the own-promises too, and the kernel could limit the notifies/etc to the ones that were subscribed
* In the future, we may introduce "durable promises" (#3787, also see #4567). These should *not* be rejected during upgrade, because the new version of the vat will retain some way to resolve/reject them later. The kernel must be able to distinguish between the c-list vpids that are non-durable (and should be rejected by the kernel), and the durable ones (that should be left untouched)

Next, we need to abandon all the non-durable exported objects. Again, we have similar code already present in the vat-termination pathway, https://github.com/Agoric/agoric-sdk/blob/162fdf2a51c54e2da89c8ed35f06cab09fb013d2/packages/SwingSet/src/kernel/state/kernelKeeper.js#L830-L842 . The key difference is that vat-termination abandons *all* objects, whereas vat *upgrade* must not abandon the *durable* exports. So the kernel needs a way to categorize the exports (the *object* vrefs, which are technically called `void`s, just as promise vrefs are `vpid`s, but we don't use the term for obvious reasons) into "durable" and "non-durable".

We want to limit the coupling between liveslots and the kernel, to give them each freedom to manage their own data structures without flag days or challenging upgrade steps, so we don't really want the kernel to know too much about how vrefs are structured. But I'm thinking that this durable/non-durable distinction might be worth bringing into the API.

Vat-exported vrefs start with `o+` or `p+` or `d+` (for device nodes). Originally, the object vrefs were strictly `o+NN`, but with the introduction of virtual/durable data, that expanded into things like `o+${kindID}/${instanceID}:${facetID}` (e.g. `o+11/2:0` is the first facet of the second instance of Kind `o+11`). The current `void` format is described in [vatstore-usage.md](https://github.com/Agoric/agoric-sdk/blob/162fdf2a51c54e2da89c8ed35f06cab09fb013d2/packages/SwingSet/src/liveslots/vatstore-usage.md) . However the kernel doesn't know anything about the suffix: it will allocate krefs for any `o+*` that it sees, and the only special value is `o+0` (which is automatically allocated for the root object during vat creation).

I'm thinking that we could expand that slightly, and introduce `o+d*` to mean "durable exported object". The kernel could then tell which c-list entries are for durable objects, and which are not. The kernel could then abandon all non-durables (except the `o+0` root object) during upgrade, without needing to ask the vat about which ones are which.

(it might be cleaner to also introduce `o+e*` to mean "ephemeral exported object", and require all `void`s to start with either `o+e` or `o+d`, but I kind of like the pedagogical simplicity of talking about `o+12` and `o-34` without always needing to include additional characters)

This would allow the kernel to take responsibility for abandoning everything (promises and objects) that definitely goes away during the upgrade. It wouldn't immediately help with the GC-like release of durable objects which were only retained by now-deleted ephemeral/merely-virtual ones, but it would reveal more information to the kernel, that could help with some future process (e.g. if we also change `vatstore` to include kernel-visible slots, making the reference graph visible to a kernel-side mark/sweep operation).

If we did the same for Promise vrefs (`vpid`s), i.e. `p+dNN`, then we'd be prepared for durable promises, which the kernel would *not* reject during upgrade (because the vat retains some durable mechanism to resolve/reject them in the new version).

## Task List

* LRU cache: remove, write-through, resign ourselves to pre-upgrade BOYD:  #6693
* kernel-side rejection of unresolved vat-decided promises during upgrade: #6694
* `startVat` argument with rejected promises and rejection object capdata to support durable promise watchers looking at own promises
* annotate object vrefs (`void`s) with durable/non-durable status: #6695
* kernel-side abandonment of non-durable object exports during upgrade: #6696
* probably add a BOYD to the kernel-side `processVatUpgrade` sequence #7001
* remove liveslots `dispatch.stopVat`, the kernel's call to it, and the rest of `src/liveslots/stop-vat.js` (including the commented-out code that performs object-graph chasing, and maybe the test code in `test-upgrade.js` which attempted to verify it) (this ticket)

## Security Considerations

Doing less work during upgrade should reduce the risk of an upgrade going wrong, which improves security (or at least improves our ability to react to a security problem).

Removing `stopVat` reduces our reliance on vat code (liveslots, not userspace) slightly: a compromised liveslots could not longer avoid having non-durable promises be rejected during upgrade, nor could it prevent non-durable exports from being abandoned.

## Compatibility Considerations

Changes to the vref format (`o+d*`) require coordination between vat (liveslots) and kernel, as does changing or removing the `stopVat` portion of the upgrade protocol, and changing which side is responsible for promise rejection and object abandonment. If we choose to implement this, but aren't able to deploy it before the bulldozer upgrade, then we'd need some sort of per-vat flag to tell the kernel what to do during an upgrade ("v1 vats should get a `stopVat`, >=v2 vats should have their c-lists walked and things rejected/abandoned").

## Test Plan

Lots of unit tests.

cc @FUDCo @gibson042

### LINKED ISSUE #7001: add BOYD to upgradeVat sequence
## What is the Problem Being Solved?

As part of #6650, the vat upgrade sequence should perform a BOYD delivery to the old vat just before shutting it down. This will give it one last chance to clean up while it still remembers what needs to be cleaned up:
* recently GCed ephemeral objects can be dropped, which may free up other references
* that might allow some imports to be dropped, and maybe retired, and thus removed from the c-list
* it may drop some virtual objects, allowing their contents to be dropped
* that may drop some durable objects, allowing their durable data to be removed from the vatStore

Currently we do some portion of this cleanup from inside the `stopVat` message, but 1: not enough, and 2: we want to remove the requirement for `stopVat` (to better preserve our ability to upgrade vats that are so broken they can't execute `stopVat`).

## Description of the Design

In kernel.js `processUpgradeVat()`, just before we do the `stopVat` message, create and deliver a `bringOutYourDead` message. The overall process will look just like the way we do `stopVat`: we synthesize a KernelDeliveryObject, translate it into a VatDeliveryObject, submit it to `deliverAndLogToVat`, await completion, retrieve and parse the status. If either the `bringOutYourDead` or the `stopVat` fails, we roll back the upgrade.

The code should include a comment to remind us that the BOYD is optional: if a vat is *so* broken that even BOYD fails, then we could dig ourselves out of the hole by:
* modify the kernel to add a "don't do BOYD" option to `vatAdminFacet.upgrade()`
* in `processUpgradeVat()`, the option says to skip the BOYD delivery and proceed directly to replacing the worker (since we'll have removed stopVat by then)
* deploy a kernel upgrade to the chain
* perform a contract governance action to upgrade the troubled vat without the BOYD step

This would result in more garbage being left behind than usual, but that should only cost us DB space and lingering imports, which is a better state than having the vat remain broken.

## Security Considerations

none, we send BOYD to vats all the time

## Scaling Considerations

This will slow down the vat-upgrade sequence slightly, since we're doing more work. It will probably be comparable to how upgrades used to work, back when we had `stopVat` doing a lot of cleanup (which we disabled to minimize the risk of `stopVat` failing, at the cost of more lingering garbage).

## Test Plan

The tests in `packages/SwingSet/test/upgrade/` have a section which examines the set of imports/virtual/durable state before and after the upgrade, to assert that everything we expect to be cleaned up, has actually been cleaned up:

https://github.com/Agoric/agoric-sdk/blob/f6996583c94e4b1d61160a102f1e92f81cc27bb0/packages/SwingSet/test/upgrade/test-upgrade.js#L267

There is a diagram (https://github.com/Agoric/agoric-sdk/blob/f6996583c94e4b1d61160a102f1e92f81cc27bb0/packages/SwingSet/test/upgrade/object-graph.pdf) which shows the object graph constructed by this test, with annotations to show what must be retained, what can be cleaned up (but currently isn't), and what ought to be cleaned up.

Unfortunately we disabled this portion of the test, probably about the same time we changed `stopVat` to remove the extra cleanup it was doing. But the diagram still covers the space of possible retentions/releases, and the vat code which sets up the object graph is still there.

For this ticket, I think we should examine that diagram and figure out what retentions/releases we expect, and we should re-enable some portions of the test to assert as much as we can about the GC behavior we'll get from a single BOYD. That means an ephemeral object which holds onto an import (which, now that I look at it, might need to be added to the digram) should be collected during BOYD, and thus emit a `dropImports` and `retireImports` for the import. This could be added to the test as a separate object, without untangling the disabled portion of the test.

### PR DESCRIPTION
**Pull request by gibson042**
closes: #6650
closes: #7001

TODO:
- [x] Fix or abandon failing assertions relating to dropping imports

## Description

Replaces upgrade-time `stopVat` with `bringOutYourDead` and leaves explanatory comments for the removed functionality. Also includes simplification and expanded coverage of some SwingSet tests.

### Security and Scaling Considerations

We're knowingly accepting some storage leakage in exchange for not relying on correct behavior from potentially broken vats. The former issue will hopefully be cleaned up in the future as part of fixing issues like #7212.

### Documentation Considerations

None not already covered as part of this PR.

### Testing Considerations

I believe the tests in this PR are sufficient to cover the changes.

### CODE REVIEW

**Comment by gibson042** [comment]
@warner Turns out the unexpectedly-reachable import was being sent back in by the post-upgrade scripted interactions. I've added clarifying comments, and this is ready for full review!

File: packages/SwingSet/src/kernel/kernel.js [hunk 1]
```diff
@@ -856,41 +840,36 @@ export default function buildKernel(
...
+
+    // send BOYD so the terminating vat has one last chance to clean
+    // up, drop imports, and delete durable data.
+    // If a vat is so broken it can't do BOYD, we can make this optional.
+    /** @type { import('../types-external.js').KernelDeliveryBringOutYourDead } */
+    const boydKD = harden(['bringOutYourDead']);
+    const boydVD = vatWarehouse.kernelDeliveryToVatDelivery(vatID, boydKD);
+    const boydStatus = await deliverAndLogToVat(vatID, boydKD, boydVD);
+    const boydResults = deliveryCrankResults(vatID, boydStatus, false);
+    (!boydResults.abort && !boydResults.terminate) ||
```
Comment (warner) [inline packages/SwingSet/src/kernel/kernel.js]: style nit, please use `if (boydResults.abort || boydResults.terminate) { Fail`, it reads more like the english would, and my eyes don't have to apply DeMorgan's law to figure out why this works

I'm learning to be ok with one-line `!good || Fail`, but I think if the condition grows larger than a single expression, we should stick with old-fashioned `if` statements.

File: packages/SwingSet/src/kernel/kernel.js [hunk 2]
```diff
@@ -856,41 +840,36 @@ export default function buildKernel(
...
+      Fail`Unexpected abort/terminate result from upgrade-internal bringOutYourDead: ${boydResults}`;
```
Comment (warner) [inline packages/SwingSet/src/kernel/kernel.js]: Hm, in the old version, a hard-meter overrun or liveslots internal error during `stopVat` would have unwound the upgrade, leaving the vat in the pre-upgrade state (but also still receiving messages).

In this new version, the same happening during the final `bringOutYourDead` will panic the kernel, since errors thrown during this `processUpgradeVat` are in a different category than errors happening within the worker.

I'm trying to figure out how I feel about that. On one hand, kernel panics are bad. Userspace should never be able to prevent kernel progress. We tolerate slightly more from liveslots, to give it agency to perform end-of-crank work, but even then, a dropped promise or infinite loop in most of `liveslots.js` would either return an error or trip the hard meter (only `dispatch()` itself has the ability to stall the kernel forever), meaning the worst it can do is get itself terminated. This change grants an effective `syscall.panicKernel()` to liveslots by making an illegal syscall during the final BOYD.

On the second hand, this isn't directly extending that power to userspace. The worst case I can think of is if userspace managed to build up such a large collection of unreachable objects that the BOYD crank overran the hard-meter limit. Userspace could do that at any time, without this change, but previously that could only cause the vat to be terminated (and userspace can pull that off trivially with an infinite loop, or `vatPowers.terminate()`). With this change, there's a tiny window during upgrade when careful preparation could panic the kernel.

On the third hand, if something goes wrong during during upgrade, what can we do?
* 1: unwind the upgrade
* 2: terminate the vat
* 3: panic the kernel

A vat-fatal error during upgrade means the vat was already in trouble, especially now that we're only doing BOYD and no other unusual deliveries (imagine a bug in the now-removed `stopVat`, which *only* broke upgrade, that would have been super annoying). If this BOYD kills the vat, it would have died soon anyways.

Although, if the vat is marked as critical and it terminates during some delivery (not necessarily the upgrade BOYD, nor any BOYD, just a regular message), the kernel will panic (to prevent the termination from being committed), and we're talking about waking up in a state where we've upgraded the kernel code to do something different, like upgrade the vat before allowing any other messages through. In that case, if our emergency ahead-of-the-line upgrade fails, we probably *do* want to re-panic the kernel, rather than re-delivering the fatal message, under the "death before confusion" rule.

That suggests that `isCritical` should play a role, or at least that any "error during upgrade causes vat termination" case should be amended with ".. unless `isCritical`, in which case panic the kernel".

If the vat is *not* marked `isCritical`, and we aren't in some emergency manually-driven-recovery situation, then what's the best way to handle a problem during upgrade? I've assumed we should just unwind it, because that covers the "version 2 is busted" case (which feels like the most likely one). Terminating the vat feels harsh, and panicing the kernel is clearly too much.

If the vat is marked `isCritical` but we're in a normal userspace-driven upgrade, then unwinding the upgrade and letting them try again with a better version feels appropriate. There are regular messages (already queued up) that will get delivered to the old version: upgrade is async from the POV of the parent vat, so we aren't violating any rules by not doing the upgrade at all (equivalent to deferring the upgrade forever).

So that leaves the emergency-manual-upgrade case. We'll have this code running (in the bulldozer release), then we imagine a kernel-panicing critical vat failure. We'll have some late nights frantically figuring out what the problem is, and how to recover from it. We'll have an opportunity to change the kernel code (as well as the rest of the release), then we'll deploy that release, and the kernel will wake up, and some special new code (that *isn't* being written today) will run, which will probably perform an ahead-of-the-queue upgrade of the vat that's in trouble. If *that* upgrade fails, then immediately panicing the kernel is probably best: if we didn't catch it testing, at least the validators will report failure as they try to come back up, and we'll spend another couple of late nights trying to figure out what went wrong.

I think this means that the upgrade-fails-now-what response wants to be "unwind" in most cases, and only "panic" if we're doing this emergency manual thing, and we haven't written the emergency manual thing yet. And we probably don't know enough to define that case yet. So rather than adding a half-baked `isEmergencyUpgradeSoPanicIsBetter` flag, let's leave a comment reminding ourselves of this analysis, and pointing out that some emergency upgrade situations might warrant panic-on-error. *And then* change this code to unwind the upgrade in case of error-during-BOYD, to match the previous behavior of error-during-stopVat.

That means retaining the old `if (stopVatResults.terminate)` clause, but looking at `boydResults` instead.

File: packages/swingset-liveslots/src/liveslots.js [hunk 3]
```diff
@@ -1516,42 +1515,11 @@ function build(
...
-        collectionManager,
-        bringOutYourDead,
-        vreffedObjectRegistry,
-      });
-    } catch (e) {
-      console.warn(`-- error during stopVat()`, e);
-      throw e;
-    }
+  async function stopVat(_disconnectObjectCapData) {
+    Fail`stopVat is no longer supported as of #6650`;
```
Comment (warner) [inline packages/swingset-liveslots/src/liveslots.js]: Hm, I think we should either make it a NOP, or remove it entirely (which would mean changing `supervisor-helper.js`, all the delivery translators on the kernel side). I don't want to make such invasive changes, so I think I'd recommend the NOP. That would also allow us to send `stopVat` to various versions of liveslots (maybe some future version where we decided to bring it back) without needing a compatibility/version flag ("hey kernel, don't send `stopVat` to this vat because it'll freak out).

Maybe just replace it with a console.log that says stopVat is now a NOP

File: packages/SwingSet/test/upgrade/test-upgrade.js [hunk 4]
```diff
@@ -318,88 +485,37 @@ const testUpgrade = async (t, defaultManagerType, options = {}) => {
...
-
-  // check koNN.owner to confirm the exported virtuals (2/5/7) are abandoned
-  t.false(kvStore.has(`${vir2Kref}.owner`));
-  t.false(kvStore.has(`${vir5Kref}.owner`));
-  t.false(kvStore.has(`${vir7Kref}.owner`));
+  // verify export abandonment/garbage collection/etc.
+  // This used to be MUCH more extensive, but GC was cut to the bone
+  // in commits like 91480dee8e48ae26c39c420febf73b93deba6ea5
+  // basically reverting 1cfbeaa3c925d0f8502edfb313ecb12a1cab5eac
+  // (see also #5342 and #6650).
```
Comment (warner) [inline packages/SwingSet/test/upgrade/test-upgrade.js]: Thanks for adding those notes. It'd also be nice to have a pointer to the git commit-ID from shortly before this lands, so exclude the various test changes that have happened since those two commits. Either cite this PR number (from which we can figure it out via github history), or sample current trunk's commit-ID (`ec6a7f4eded916afb8c927638b4a699e2ffd99c9` as of this morning, which is close enough).

**Review by warner — CHANGES_REQUESTED** [review]
Behavior change to make if BOYD fails during upgrade, plus some minor nits. Nice job!

File: packages/SwingSet/src/kernel/kernel.js (hunk 2 above)
Comment (gibson042) [reply packages/SwingSet/src/kernel/kernel.js]: This reasoning makes sense to me, and I've done my best to condense it into the source code. Please re-review the latest changes to kernel.js.

**Review by warner — APPROVED** [review]
