### PR TITLE
fix(swingset): retain vatParameters for vat creation and upgrade

### LINKED ISSUE #8947: maybe have kernel retain vatParameters, to enable kernel-unilateral vat upgrade
## What is the Problem Being Solved?

One task [identified as a requirement](https://github.com/Agoric/agoric-sdk/issues/8405#issuecomment-1918065985) for a kernel-unilateral restart-all-vats feature is to have the kernel retain each vat's `vatParameters`.

`vatParameters` is a chunk of data (`passable` object graph, except Promises are forbidden) which is provided as the second argument to the vat's `buildRootObject()` function at vat startup time. It is meant to parameterize the vat bundle for some specific purpose (making it distinct from all other vats using the same bundle). By providing these parameters early, before any messages have arrived, the vat bundle can use them when (re-)defining its Kinds.

Currently, the kernel treats `vatParameters` more like a message. In particular, the kernel does not remember the data after vat startup. `vatParameters` are held in the run-queue `startVat` event record, which is dropped after the delivery is begun. Any any object krefs in the vP are held with a refcount until they leave the queue, after which (if nothing else is holding onto them) they may get garbage collected.

(The same is true of vat root objects: once the bootstrap message is delivered, the kernel does not retain a reference to them, and the objects may get collected if the bootstrap vat did not choose to hold onto them. The policy I chose was to have the kernel defer to userspace decisions about what is important to retain and what is important to collect).

However, we can't correctly restart a vat without its `vatParameters`, and if the kernel is going to unilaterally restart vats, we need to keep them around.

## Description of the Design

We'll put a copy of the `vatParameterCapData` (or "vpcd" for short) into the kvStore `vNN.options` record, or perhaps in a new `vNN.vatParameterCapData` record.

When userspace creates a vat (via vat-admin), the kernel will store a copy of the vpcd, and increment the refcounts on any objects. When userspace upgrades a vat (supplying new vatParameters), the kernel will retrieve the old data, store the new data, increment the refcounts on the new data, then decrement the refcounts on the old data. When the vat is terminated, the refcounts will be decremented.

We'll continue to put a copy of the `vatParameterCapData` in the `startVat` message, and increment the refcount when doing so, and decrement the refcount when delivering `startVat`, to avoid upgrade concerns about refcount skew. However the `startVat`-time decref will never allow an object to be freed, because all such objects will also have a refcount for the kvStore copy.

## Security Considerations

None I can think of. Userspace cannot use this feature to retain objects any longer than it could have without it.

## Scaling Considerations

This causes all `vatParameter` objects to be held uncollectable until userspace upgrades the vat with different objects, or the vat is terminated. This is unlikely to represent a significant memory "leak", both because of the low rate of upgrade, and because (at least traditionally) most objects passed to `vatParameters` are used and held by the userspace code for the entire incarnation.

## Test Plan

Unit tests on the kernel side, in the code that checks refcounts.

## Upgrade Considerations

Current vats do not have any retained vpcd, and cannot retrieve it from the kvStore contents. So we need code to recognize that a vat does not currently have this data, and make it ineligible for unilateral upgrade.

### PR DESCRIPTION
**Pull request by warner**
fix(swingset): retain vatParameters for vat creation and upgrade

All vats have `vatParameters`, a mostly-arbitrary data record,
delivered as the second argument to their `buildRootObject()`
function. Dynamic vats get their vatParameters from the options bag
given to `E(vatAdminSvc).createVat()`. Static vats get them from the
kernel config record. When a vat is upgraded, the new incarnation gets
new vatParameters; these come from the options bag on
`E(adminNode).upgrade()`.

When received via `createVat()` or `upgrade()`, the vatParameters
can contain object and device references. VatParameters cannot include
promises.

Previously, the kernel delivered vatParameters to the vat, but did not
keep a copy. With this commit, the kernel retains a copy of
vatParameters (including a refcount on any kernel objects
therein). Internally, `vatKeeper.getVatParameters()` can be used to
retrieve this copy.  Only vats created or upgraded after this commit
lands will get retained vatParameters: for older vats this will return
`undefined`.

Retained vat parameters should make it easier to implement "upgrade
all vats", where the kernel perform a unilateral `upgrade()` on all
vats without userspace asking for it. When this is implemented, the
new incarnations will receive the same vatParameters as their
predecessors.

fixes #8947

### CODE REVIEW

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 1]
```diff
@@ -173,6 +174,35 @@ export function makeVatKeeper(
...
 
+  /**
+   * @param {SwingSetCapData} newVPCD
+   */
+  function setVatParameters(newVPCD) {
+    insistCapData(newVPCD);
+    const key = `${vatID}.vatParameters`;
+    // increment-before-decrement to minimize spurious rc=0 checks
+    for (const kref of newVPCD.slots) {
+      incrementRefCount(kref, `${vatID}.vp`);
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/vatKeeper.js]: Nit, keep the tag fully descriptive?

```suggestion
      incrementRefCount(kref, `${vatID}.vatParameters`);
```

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 2]
```diff
@@ -173,6 +174,35 @@ export function makeVatKeeper(
...
+    }
+    const old = kvStore.get(key) || '{"slots":[]}';
+    for (const kref of JSON.parse(old).slots) {
+      decrementRefCount(kref, `${vatID}.vp`);
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/vatKeeper.js]:
```suggestion
      decrementRefCount(kref, `${vatID}.vatParameters`);
```

File: packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js [hunk 3]
```diff
@@ -282,5 +282,26 @@ export const buildRootObject = () => {
 
       return [paramA, paramB];
     },
+
+    buildV1WithVatParameters: async () => {
+      const bcap1 = await E(vatAdmin).getNamedBundleCap('ulrik1');
+      const vp1 = { number: 1, marker };
```
Comment (mhofman) [inline packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js:290]: Let's add a promise here to verify behavior with those too as that's supported.

File: packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js [hunk 4]
```diff
@@ -282,5 +282,26 @@ export const buildRootObject = () => {
...
+      const options1 = { vatParameters: vp1 };
+      const res = await E(vatAdmin).createVat(bcap1, options1);
+      ulrikAdmin = res.adminNode;
+      ulrikRoot = res.root;
+      const param1 = await E(ulrikRoot).getParameters();
+      return param1;
```
Comment (mhofman) [inline packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js:296]: Should this return the original `marker` that was used?

File: packages/SwingSet/test/upgrade/upgrade.test.js [hunk 5]
```diff
@@ -953,3 +953,40 @@ test('failed vatAdmin upgrade - bad replacement code', async t => {
...
+    },
+  });
+  const kft = await initKernelForTest(t, t.context.data, config);
+  const { messageToVat, kvStore } = kft;
+
+  // create initial version
+  const params1 = await messageToVat('bootstrap', 'buildV1WithVatParameters');
+  t.is(params1.number, 1);
+  const marker = params1.marker;
+  t.deepEqual(params1, { number: 1, marker });
```
Comment (mhofman) [inline packages/SwingSet/test/upgrade/upgrade.test.js:985]: This seems like asking someone if they're themselves?

That said with a promise (which I want added), we shouldn't rely on JS object identity. While we effectively reuse the same promise object today, I really don't want to tie us too much to that behavior as we officially don't guarantee it. I suppose that in tests with test marshaller on this side, we can make that assumption.

File: packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js [hunk 6]
```diff
@@ -282,5 +282,26 @@ export const buildRootObject = () => {
...
+    },
+
+    upgradeV2WithVatParameters: async () => {
+      const bcap2 = await E(vatAdmin).getNamedBundleCap('ulrik2');
+      const vp2 = { number: 2, marker };
```
Comment (mhofman) [inline packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js:301]: Should this test using a different marker?

File: packages/SwingSet/test/vat-admin/create-vat.test.js [hunk 7]
```diff
@@ -415,25 +424,27 @@ test('createVat holds refcount', async t => {
   t.deepEqual(c.dump().reapQueue, []);
   // console.log(`---`);
 
-  // At this point we expected to see 5,5: v2-bootstrap, kpResolution pin,
-  // vat-vat-admin (because of the non-dropping bug), device-vat-admin
```
Comment (mhofman) [inline packages/SwingSet/test/vat-admin/create-vat.test.js:419]: descriptions change that wasn't included in a previous fix?

File: packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js
Comment (mhofman) [inline packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js:1]: I wish a lot of these numbers were expressed as relative offsets to avoid requiring so made "by 1" adjustments.

**Review by mhofman — APPROVED** [review]
The core logic looks good. Since promises are in fact valid in vatParameters, I'd like to test them.

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 1 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/vatKeeper.js]: Yeah, ok, I did a quick scan of our other tags, and we're kinda 50/50 with short (`enq` for enqueue, `vk|clist` for vat-keeper -managed clists) and long (`create-vat-event`, `external`, etc). But given that there's only one of these per vat, and we don't actually record them anyways (unless maybe some debug flag is on), there's no need to be terse. Will do.

**Comment by warner** [comment]
Oh, so in fact Promises are *not* valid `vatParameters`, because they must pass through a device `invoke()` call, and the liveslots `D()` call [uses](https://github.com/Agoric/agoric-sdk/blob/9c73ae4bfa7d48114690e694b065ee0a1ce99e30/packages/swingset-liveslots/src/liveslots.js#L866) a [helper named `forbidPromises`](https://github.com/Agoric/agoric-sdk/blob/9c73ae4bfa7d48114690e694b065ee0a1ce99e30/packages/swingset-liveslots/src/liveslots.js#L846-L851) to refuse those. (I discovered this while trying to add promises to the test).

That blocks promises when vat-vat-admin tries to talk to device-vat-admin, which will reject back to the caller of `E(vatAdminSvc).createVat()`, or `E(adminNode).upgrade()`.

File: packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js (hunk 4 above)
Comment (warner) [reply packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js:296]: No, quite the opposite, it's checking that the created/upgraded vat received the correct parameters. If this bootstrap vat returned `marker` then we'd be bypassing the created/upgraded vat entirely.

The test is actually preparing to check an additional feature, not implemented in this PR, which is to change the `upgrade()` semantics from "no `vatParameters` means `{}`" to "no `vatParameters` means reuse the retained value". Since the immediate goal is *preservation* of the old vP, the subsequent goal will be to enable *unilateral* upgrade (where vat-admin isn't even involved, much less userspace calling `upgrade()`), neither required a change to the `upgrade()` API. I realized I could/should reduce the scope of this PR after writing the tests but before writing the implementation. So the test is all set up to check that an `upgrade()` without `options.vatParameters` will return the old marker, and applies the correct assertion, but still supplies the option to the `upgrade()` call.

File: packages/SwingSet/test/upgrade/upgrade.test.js (hunk 5 above)
Comment (warner) [reply packages/SwingSet/test/upgrade/upgrade.test.js:985]: This pattern is a bit weird, but it's mostly intentional. I want to use `deepEqual` to check that everything in the retrieved parameters is as expected, but `kser`/`kunser` doesn't use persistent object-side identity (doing `kunser()` twice on the same capdata will give you two different psuedo-Presences, but both `.getKref()`s will give you the same kref). So I can't know ahead of time what the pseudo-Presence will be. So I extract the marker, then use `deepEqual` to check that everything else is right (no extra parameters, at least). And I uses the marker (and `.getKref()`) to check the kvStore's recorded values.

I don't really need the `t.is(params1.number, 1)` there; the `t.deepEqual` covers that. But it was the most immediate/obvious check that the parameters have changed. The rest was mostly for completeness.

File: packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js (hunk 6 above)
Comment (warner) [reply packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js:301]: It could, but I was relying upon the number to distinguish the original vs the new. I wanted the marker there to test that 1: krefs work, 2: refcounts are managed correctly. But I'm not checking refcounts in this test.. I do some of that in `create-vat.test.js`, but maybe I should add some here too.

If I was actually implementing the "vP-lacking `upgrade()` re-uses the retained vP" feature here, then this test would need to be bigger: use three markers, m1+m2 in the original, upgrade from v1 to v2 with no `options.vatParameters`, then upgrade from v2 to v3 with (m1+m3) in the vP. And we'd check that the refcount remains the same across the first upgrade (still retained, still received by the vat), but the second upgrade drops m2 and holds a refcount on m3.

But for this "merely retain them" change, that isn't necessary.

File: packages/SwingSet/test/vat-admin/create-vat.test.js (hunk 7 above)
Comment (warner) [reply packages/SwingSet/test/vat-admin/create-vat.test.js:419]: yeah, I think that's right, I should have removed the bit about "non-dropping bug" in the previous PR that fixed that issue.

File: packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js (hunk 3 above)
Comment (warner) [reply packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js:290]: as discussed, we can't actually submit promises in `vatParameters` as we've believed elsewhere, so I think there's nothing to do here

File: packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js
Comment (warner) [reply packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js:1]: My intention was for the series of +1/-1 adjustments to mirror the refcount changes we expect the kernel to be making, and then the `t.deepEqual` confirms that the real kernel is still in sync with our expectations. I switched to that rather than `[4,4]`/etc because I had a sub-mode where the starting point was higher, so I had a bunch of `if (mode1) t.deepEqual([4,4]) else t.deepEqual([5,5])` and it was gross. But it looks like the test lost that sub-mode thing.

File: packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js (hunk 6 above)
Comment (warner) [reply packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js:301]: I added a clause to check the refcounts in this test. It's muddled, because I'm not forcing BOYD, and the `kpResolution()` calls add extra ones, and `device-vat-admin` doesn't do GC, so the count is 6 instead of 2, and the second call sees a count of 7 because of the extra `kpResolution()` pin. But I think it still does the job of making sure that the saved parameters get a refcount,

File: packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js (hunk 4 above)
Comment (mhofman) [reply packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js:296]: Sorry I meant should this "also" return the marker, so that the test file can compare the identities.

File: packages/SwingSet/test/upgrade/upgrade.test.js (hunk 5 above)
Comment (mhofman) [reply packages/SwingSet/test/upgrade/upgrade.test.js:985]: > doing `kunser()` twice on the same capdata will give you two different psuedo-Presences

Oh that's surprising for presences

File: packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js
Comment (mhofman) [reply packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js:1]: Of couse we should see a 1 adjustment, I just wish it was limited to a single "base" line, and every other line wouldn't require a change.

File: packages/SwingSet/test/upgrade/upgrade.test.js [hunk 8]
```diff
@@ -953,3 +953,69 @@ test('failed vatAdmin upgrade - bad replacement code', async t => {
...
+  const vatID = JSON.parse(kvStore.get('vat.dynamicIDs'))[0];
+  const vp1cd = kvStore.get(`${vatID}.vatParameters`);
+  const vp1 = kunser(JSON.parse(vp1cd));
+  t.is(vp1.number, 1);
+  t.is(vp1.marker.getKref(), kref);
+
+  // Ideally, the refcount should be 2: one for the importing vat's
+  // c-list, and a second for the retained vNN.vatParameters. But it
+  // will also get a refcount from device-vat-admin, as a conduit for
+  // the upgrade() call, because devices don't do GC.
```
Comment (mhofman) [inline packages/SwingSet/test/upgrade/upgrade.test.js:998]: Does that mean that anything ever provided to a device never gets collected?

Comment (warner) [reply packages/SwingSet/test/upgrade/upgrade.test.js:998]: correct, unfortunately

Comment (mhofman) [reply packages/SwingSet/test/upgrade/upgrade.test.js:998]: That is a pretty severe leak. Do we have an issue?

File: packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js
Comment (gibson042) [reply packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js:1]: I'm interested in knowing whether https://github.com/Agoric/agoric-sdk/pull/10165/files#diff-2034a7fd43725a4ff26853bb57f1dc406e0d278ac4c3ff4378d43751131f31cfR180-R197 follows your target pattern.
