### PR TITLE
fix(swingset-liveslots): Throw a "not found" error for store.set(missingRemotable, val)

### LINKED ISSUE #8098: Virtual collection `set(missingRemotable, val)` throws "no ordinal" rather than "not found"
The "no ordinal" message is confusing and should be replaced with something more meaningful to developers.

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #8098

## Description

Updates collection `set` to detect a missing remotable key and throw an appropriate error. Also includes moderate refactoring of collectionManager.js to DRY out code and ensure consistent error messages.

### Security Considerations

n/a

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

Updates tests accordingly.

### Upgrade Considerations

This changes error messages, but I don't think we guarantee that those are stable. As long as restart/upgrade of any particular vat is in consensus across validators, then they will all agree on whether its liveslots dependency includes or does not include this change.

### CODE REVIEW

File: packages/swingset-liveslots/src/collectionManager.js [hunk 1]
```diff
@@ -439,11 +443,10 @@ export function makeCollectionManager(
       const { keyShape, label } = getSchema();
       mustMatch(key, keyShape, makeInvalidKeyTypeMsg(label));
       if (passStyleOf(key) === 'remotable' && getOrdinal(key) === undefined) {
-        throw Fail`key ${key} not found in collection ${q(label)}`;
+        failNotFound(label, key);
```
Comment (warner) [inline packages/swingset-liveslots/src/collectionManager.js]: huh, I remember needing the `throw` before the `Fail` to convince tsc or eslint that control flow would not make it past this point, good to know there's a way to avoid it

File: packages/swingset-liveslots/src/collectionManager.js [hunk 2]
```diff
@@ -432,6 +432,9 @@ export function makeCollectionManager(
           }
         }
       }
+      if (passStyleOf(key) === 'remotable' && getOrdinal(key) === undefined) {
```
Comment (warner) [inline packages/swingset-liveslots/src/collectionManager.js]: Hm, this introduces an extra `syscall.vatstoreGet` for  each `store.set`: `getOrdinal` does one, and then `keyToDBKey` does it again (via `encodeKey` -> `makeEncodePassable` -> `encodeRemotable` -> `getOrdinal`).

I managed to make our `has` method avoid it:

```js
      if (passStyleOf(key) === 'remotable') {
        return getOrdinal(key) !== undefined;
      } else {
        return syscall.vatstoreGet(keyToDBKey(key)) !== undefined;
      }
```

but in `get`, the extra `getOrdinal()` we added (to get a unified error message) causes the same extra `vatstoreGet` syscall in the successful case:

```js
    function get(key) {
      const { keyShape, label } = getSchema();
      mustMatch(key, keyShape, makeInvalidKeyTypeMsg(label));
      if (passStyleOf(key) === 'remotable' && getOrdinal(key) === undefined) {
        throw Fail`key ${key} not found in collection ${q(label)}`;
      }
      const result = syscall.vatstoreGet(keyToDBKey(key));
      if (!result) {
        throw Fail`key ${key} not found in collection ${q(label)}`;
      }
      return unserializeValue(JSON.parse(result));
    }
```

So, the extra syscall is unfortunate, but no worse than what `get` is already doing, and `get` probably happens more frequently than `set`.

Let's keep the perf impact in the back of our mind, and see if we can find a sensible refactoring that will let us avoid it later. If this were Python, I'd have `encodeRemotable` throw a recognizable exception type, and have `get`/`set` catch it and re-throw the same `IndexError` it would throw when `result` is missing. But I know we don't use JS error values that way.

File: packages/swingset-liveslots/src/collectionManager.js [hunk 3]
```diff
@@ -354,14 +354,19 @@ export function makeCollectionManager(
...
 
+    function mustGet(key, label) {
+      if (passStyleOf(key) === 'remotable' && getOrdinal(key) === undefined) {
+        failNotFound(key, label);
+      }
+      const dbKey = keyToDBKey(key);
+      const result = syscall.vatstoreGet(dbKey) || failNotFound(key, label);
+      return { dbKey, result };
+    }
+
```
Comment (warner) [inline packages/swingset-liveslots/src/collectionManager.js:365]: this will be a good starting point for a future refactoring that avoids the duplicate vatstoreGet syscall

**Comment by warner** [comment]
> Upgrade Considerations
> This changes error messages, but I don't think we guarantee that those are stable. As long as restart/upgrade of any particular vat is in consensus across validators, then they will all agree on whether its liveslots dependency includes or does not include this change.

It looks like it also changes the syscall trace, because of the extra `vatstoreGet` performed for each `store.set`. But as you said, we retain the same liveslots until the vat is upgraded, so that's an acceptable change.

**Review by warner — APPROVED** [review]
Looks good. The story might be slightly more concise if the commit which introduces `failNotFound` were to use the ideal argument order from the very start, but it doesn't distract significantly from the readability to swap the arguments in the last commit.

**Comment by warner** [comment]
One other thought: this changes the error message avoid revealing the distracting term "ordinal", and provides a unified error message for all sorts of missing keys, but I wonder if it should also inform the caller about the difference between `store.set(missingKey, value)` and `store.init(missingKey, value)`. I think @dckc 's original error report indicated some time lost re-discovering that `set` refuses to accept new keys.

Should we change the unified error message from `key ${key} not found in collection` to `set(${key}) cannot be used to initialize new keys of collection ${collection}, please use .init instead` ?

That would require a different factoring of `failNotFound`, like a second function used specifically from `.set` with a different message. Or, maybe, an option, but for a one-line function I think it'd be better to make a second function.

File: packages/swingset-liveslots/src/collectionManager.js (hunk 3 above)
Comment (dckc) [reply packages/swingset-liveslots/src/collectionManager.js:365]: re duplicate vat store operations... I often wish our stores had `c.initOrSet(k, v)` and `c.getOrElse(k, defaultVal = undefined)`

We have a lot of this:

```js
  if (c.has(k)) {
    c.set(k, v)
  } else {
    c.init(k, v)
  }
```

and:

```js
  if (c.has(k)) {
    const happy = c.get(k)
  } else {
    // sad path
  }
```

**Comment by erights** [comment]
> One other thought: this changes the error message avoid revealing the distracting term "ordinal", and provides a unified error message for all sorts of missing keys, but I wonder if it should also inform the caller about the difference between `store.set(missingKey, value)` and `store.init(missingKey, value)`. I think @dckc 's original error report indicated some time lost re-discovering that `set` refuses to accept new keys.
> 
> Should we change the unified error message from `key ${key} not found in collection` to `set(${key}) cannot be used to initialize new keys of collection ${collection}, please use .init instead` ?
> 
> That would require a different factoring of `failNotFound`, like a second function used specifically from `.set` with a different message. Or, maybe, an option, but for a one-line function I think it'd be better to make a second function.

Would be good to also look at the error messages emitted for these case by the heap stores in `@agoric-sdk/store`. Would be nice to at least understand the differences. Better would be to minimize the differences by having both converge on decent error messages.

File: packages/swingset-liveslots/src/collectionManager.js (hunk 2 above)
Comment (gibson042) [reply packages/swingset-liveslots/src/collectionManager.js]: I guess the existing inefficiency is in `get` (`getOrdinal` → **vatstoreGet**, `keyToDBKey` → `encodeKey` → `encodeRemotable` → `getOrdinal` → **vatstoreGet**, **vatstoreGet**), which this PR moves into `mustGet` and thereby infects `set`. I agree with you about the Pythonic approach, and avoiding that here would incline me towards updating `keyToDBKey` to distinguish top-level remotables and eliminate the redundant `getOrdinal` calls:
```diff
+    const encodeOrdinal = (ordinal, remotable) =>
+      `r${zeroPad(ordinal, BIGINT_TAG_LEN)}:${convertValToSlot(remotable)}`;
+
     const encodeRemotable = remotable => {
       // eslint-disable-next-line no-use-before-define
       const ordinal = getOrdinal(remotable);
       ordinal !== undefined || Fail`no ordinal for ${remotable}`;
-      const ordinalTag = zeroPad(ordinal, BIGINT_TAG_LEN);
-      return `r${ordinalTag}:${convertValToSlot(remotable)}`;
+      return encodeOrdinal(ordinal, remotable);
     };
```
```diff
-    function keyToDBKey(key) {
-      const encodedKey = encodeKey(key);
+    function keyToDBKey(key, label = undefined) {
+      let encodedKey;
+      if (passStyleOf(key) === 'remotable') {
+        const ordinal = getOrdinal(key) || failNotFound(key, label);
+        encodedKey = encodeOrdinal(ordinal, key);
+      } else {
+        encodedKey = encodeKey(key);
+      }
       assert(encodedKey.length < MAX_DBKEY_LENGTH, 'key too large');
       return prefix(encodedKey);
     }
```
```diff
     function mustGet(key, label) {
-      if (passStyleOf(key) === 'remotable' && getOrdinal(key) === undefined) {
-        failNotFound(key, label);
-      }
-      const dbKey = keyToDBKey(key);
+      const dbKey = keyToDBKey(key, label);
       const result = syscall.vatstoreGet(dbKey) || failNotFound(key, label);
       return { dbKey, result };
     }
```
Should I expand this PR to include such changes?

Comment (dckc) [reply packages/swingset-liveslots/src/collectionManager.js]: > ... If this were Python, I'd have `encodeRemotable` throw a recognizable exception type, and have `get`/`set` catch it and re-throw the same `IndexError` it would throw when `result` is missing. But I know we don't use JS error values that way.

We seem to use JS non-error values that way:

> For non-local non-erroneous control flow, our recommended practice (which we've only recently decided on and started practicing) is that **normal non-erroneous control flow**, not indicating a problem that should be brought to human attention, **should happen by raising a non-error**. -- [Errors and Control Flow](https://github.com/Agoric/agoric-sdk/wiki/Errors-and-Control-Flow)

Comment (dckc) [reply packages/swingset-liveslots/src/collectionManager.js]: p.s. here's hoping for ejectors...

 - https://github.com/endojs/endo/issues/414

**Review by FUDCo — APPROVED** [review]
Very nice cleanups.  This entirely bypasses the worry that I had, so this is good to go as far as I'm concerned.

**Comment by warner** [comment]
@gibson042 hey, what's the current state of this?

**Comment by gibson042** [comment]
Hmm, I guess it got tabled for other more urgent work. But I just rebased, so if we're ready for it now then it can land.
