### PR TITLE
fix(liveslots): do not leak known resolved promises

### LINKED ISSUE #11118: liveslots leaks slotToVal entries for known settled promises
## Describe the bug

When sending a message or notifying of resolution with promises contained in argument / resolution value, liveslots optimizes the resolution notification of these promises for any promise it knows to be settled, and any transitive promise in those resolutions. It collects these resolutions and group notifies them immediately.

Since these promises are settled, they were no longer in the clist (neither imported nor exported). Using them as payload of a send does temporarily export them, then the notify drops them right away. The marshalling adds them to slotToVal / valToSlot, but the optimization does not use the regular path for handling resolutions, and the entries are never removed.

This results in a leak through `slotToVal` growing empty WeakRefs for these temporarily exported promises, causing symptoms similar to #10757. This leak is the major cause of the observed heap still growing in the smart wallet (#10794) after that issue was worked around.

## To Reproduce
See https://github.com/Agoric/agoric-sdk/pull/10931

## Expected behavior
No leak when sending known resolved promises, either as send arguments or resolution payload

## Platform Environment
`agoric-upgrade-18` and `dc-fu-impact`

### PR DESCRIPTION
**Pull request by mhofman**
closes: #11118
refs: #10794

best reviewed commit-by-commit

## Description
Remove unreferenced vpids from know resolutions

### Security Considerations
None

### Scaling Considerations
None

### Documentation Considerations
None

### Testing Considerations
Verified manually using [mhofman/fu-impact](https://github.com/Agoric/agoric-sdk/compare/dc-fu-impact...mhofman/fu-impact).

Adds failing unit tests for the leak then marks the test as non failing in the fix commit

Adds a failing test for a remaining leak from https://github.com/Agoric/agoric-sdk/issues/10756 not currently mitigated. It would likely be solved by https://github.com/Agoric/agoric-sdk/issues/10778

### Upgrade Considerations
This will require a vat upgrade of all vats potentially resolving with known settled promises. We know of at least the smart wallet doing this, but others may also be affected. Since we cannot unilaterally upgrade vats yet (#8405), we'll have to look at which vats are impacted and include an explicit upgrade.

### CODE REVIEW

File: packages/swingset-liveslots/src/liveslots.js [hunk 1]
```diff
@@ -797,6 +797,7 @@ function build(
       for (const resolution of resolutions) {
         const [xvpid] = resolution;
         maybeNewVPIDs.delete(xvpid);
+        unregisterUnreferencedVPID(xvpid);
```
Comment (gibson042) [inline packages/swingset-liveslots/src/liveslots.js:800]: Optimization opportunity: combine the first two passes over `resolutions` (here and in `followForKernel`, which honestly seems like it could benefit from some consolidation).
```js
    const maybeNewVPIDs = new Set(serMethargs.slots);
    const resolutions = resolutionCollector().forSlots(serMethargs.slots);
    if (resolutions.length > 0) {
      try {
        const resolutionCDs = [];
        for (const [_xvpid, _isReject, resolutionCD] of resolutions) {
          resolutionCDs.push(resolutionCD);
          for (const vref of resolutionCD.slots) {
            maybeNewVPIDs.add(vref);
          }
        );
        assertAcceptableSyscallCapdataSize(resolutionCDs);
      } catch (e) {
        syscall.exit(true, m.serialize(e));
        return null;
      }
      syscall.resolve(resolutions);
      for (const [xvpid, _isReject, _resolutionCD] of resolutions) {
        maybeNewVPIDs.delete(xvpid);
        unregisterUnreferencedVPID(xvpid);
      }
    }
    for (const newVPID of Array.from(maybeNewVPIDs).sort()) {
      maybeExportPromise(newVPID);
    }
```

**Review by gibson042 — APPROVED** [review]
Kudos on the test changes; that was a lot.

File: packages/swingset-liveslots/src/liveslots.js (hunk 1 above)
Comment (mhofman) [reply packages/swingset-liveslots/src/liveslots.js:800]: Yeah I saw that too, but I wanted to avoid changing the logic itself too much. Let's table this until we revisit promise handling.
