### PR TITLE
Fully support `agoric install <dist-tag>`

### LINKED ISSUE #3857: no supported workflow for installing from npm
## Describe the bug

We don't have a supported workflow of building dapps by installing packages such as `@agoric/zoe` from npm. Only building from source is adequately supported.

For example, the agoric cli is installed using `yarn link-cli`, unlike other npm tools that are installed using `npm install -g` or the like.

## To Reproduce

If you run `agoric install` from inside an `agoric-sdk`, you're in a world of hurt.

If you then make a new `agoric-sdk` clone, forgetting to `yarn link-cli` leads to difficult-to-diagnose version skew (this cost @dtribble a bunch of time today).

`npx agoric init demo` doesn't work:
```
$ npx agoric init demo
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/gitpod/.npm/_npx/1639/lib/node_modules/agoric/bin/agoric
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/gitpod/.npm/_npx/1639/lib/node_modules/agoric/bin/agoric'
```

running `agoric` with a pre-ESM version gives a pretty bad diagnostic:
```
$ agoric
/home/connolly/projects/agoric/agoric-sdk/packages/agoric-cli/lib/entrypoint.js:6
import 'esm';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
```

## Expected behavior

like other dev tools in the npm world

cc @mhofman @katelynsills @warner @michaelfig

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #3857

## Description

If a dist-tag is specified with `agoric install <dist-tag>`, ensure we refresh the dapp's `yarn.lock` dependencies.

This makes it possible to build and develop a published dapp without needing the `agoric install` command (just `yarn install` suffices).  Indeed, `npm install -g agoric` or `yarn global add agoric` should be able to produce a working `agoric` command that can do everything that `yarn link-cli ~/bin/agoric` does, once this PR's version of `agoric-cli` has been published to NPM.

### Documentation Considerations

`agoric install beta` will update the workspace's `yarn.lock` with the beta dependencies.  From that point on, installing the dapp only needs `yarn install` (though `agoric install` will work, too).

### Testing Considerations

Tested manually on `dapp-oracle`.

### CODE REVIEW

File: packages/agoric-cli/src/install.js [hunk 1]
```diff
@@ -40,7 +40,112 @@ export default async function installMain(progname, rawArgs, powers, opts) {
...
+  const linkFlags = [];
+  if (opts.sdk) {
+    linkFlags.push(`--link-folder=${linkFolder}`);
+  }
+
+  const doYarnInstalls = async (phase, ...flags) => {
+    for (const instdir of installDirs) {
+      log.info(`yarn install ${phase} in ${instdir}`);
+      // eslint-disable-next-line no-await-in-loop
+      const yarnInstall = await pspawn(
```
Comment (dckc) [inline packages/agoric-cli/src/install.js:56]: not worth doing concurrently?

File: scripts/dist-tag.sh [hunk 2]
```diff
@@ -0,0 +1,47 @@
+#! /bin/bash
+# dist-tag.sh - manage dist-tags for NPM registry packages
```
Comment (dckc) [inline scripts/dist-tag.sh]: elaborate a bit on "manage"?

I'm not really fluent in bash. I could use a comment for each clump of lines, actually.

File: packages/agoric-cli/src/install.js [hunk 3]
```diff
@@ -134,21 +136,72 @@ export default async function installMain(progname, rawArgs, powers, opts) {
...
           return;
         }
+        const obsolete = new Set();
         const pj = JSON.parse(packageJSON);
         for (const section of ['dependencies', 'devDependencies']) {
           const deps = pj[section];
           if (deps) {
             for (const pkg of Object.keys(deps)) {
               if (versions.has(pkg)) {
+                if (deps[pkg] === forceSdkVersion) {
```
Comment (dckc) [inline packages/agoric-cli/src/install.js]: I would have thought we need to "invalidate the cache" on a version _mismatch_.

I can't see where `deps` is initialized in this diff, and when I looked at the whole file, I got a little dizzy. (color me lazy)

**Review by dckc — COMMENTED** [review]
I would need to level up my npm / yarn game to feel confident about this.

Maybe @kriskowal could take a look?

**Comment by dckc** [comment]
Does this depend on #4120?

**Comment by michaelfig** [comment]
> Does this depend on #4120?

Actually, no.  It's still valuable even if someone has to manually publish packages and dist-tags all the time.

File: packages/agoric-cli/src/install.js (hunk 1 above)
Comment (michaelfig) [reply packages/agoric-cli/src/install.js:56]: I originally made it concurrent, but that just made the output extremely difficult to read.

File: packages/agoric-cli/src/install.js (hunk 3 above)
Comment (michaelfig) [reply packages/agoric-cli/src/install.js]: > I would have thought we need to "invalidate the cache" on a version mismatch.

Actually, `yarn` already updates packages that have changed.  It's the packages whose version specifier has *not* changed that we need to first prune the old one, install, add the new one, and install to get it to update correctly.

File: packages/agoric-cli/src/install.js [hunk 4]
```diff
@@ -40,7 +40,117 @@ export default async function installMain(progname, rawArgs, powers, opts) {
...
+        // Modify all the SDK package versions.
+        const pjson = `${subdir}/package.json`;
+        const packageJSON = await fs
+          .readFile(pjson, 'utf-8')
+          .catch(_ => undefined);
+        if (!packageJSON) {
+          return;
+        }
+        const pj = JSON.parse(packageJSON);
+        const prunedPj = { ...pj };
```
Comment (kriskowal) [inline packages/agoric-cli/src/install.js]: I struggle with naming variables that all refer to the same thing, but in different forms. My principle is that all the names should have some portion that is the same to reflect that they refer to something common, and a term that varies to indicate what’s different about them. So, for something like this, I’ve been using names like `packageDescriptorBytes`, `packageDescriptorText`, `packageDescriptor`, and `packageDescriptorPruned`. I think `Json` instead of `Descriptor` might be valid but not precise. I personally loathe the case convention conundrum raised by acronyms and initialisms, particularly when they run-on. And, I don’t mind some verbosity, even for local variables where the verbosity is unnecessary.

This is a recommendation.

File: packages/agoric-cli/src/install.js [hunk 5]
```diff
@@ -40,7 +40,117 @@ export default async function installMain(progname, rawArgs, powers, opts) {
...
+          // Don't update on exit anymore.
+          process.off('beforeExit', updatePackageJson);
+          log.info(`updating ${pjson}`);
+          await fs.writeFile(pjson, `${JSON.stringify(pj, null, 2)}\n`);
+        };
+        updatesTodo.push(updatePackageJson);
+        if (needsPruning) {
+          pruningTodo.push(async () => {
+            // Update on exit, in case we are interrupted.
+            process.on('beforeExit', updatePackageJson);
```
Comment (kriskowal) [inline packages/agoric-cli/src/install.js]: I presume you considered and decided against framing this in terms of a finally. I don’t think it would occur to me to use the beforeExit event under any circumstances.

`updatePackageJson` returns a promise that the EventEmitter will ignore. That would suggest that any error will be realized as an unhandled rejection warning. I’d consider reframing this to sink the promise.

File: packages/agoric-cli/src/install.js [hunk 6]
```diff
@@ -40,7 +40,117 @@ export default async function installMain(progname, rawArgs, powers, opts) {
...
+      // Run all the pruning tasks in parallel.
+      pruningP = Promise.allSettled(pruningTodo.map(async remove => remove()))
+        .then(results => {
+          // After all have settled, try throwing the first rejection.
+          const firstFailure = results.find(
+            ({ status }) => status !== 'fulfilled',
+          );
+          if (firstFailure) {
+            throw firstFailure.reason;
+          }
```
Comment (kriskowal) [inline packages/agoric-cli/src/install.js]: Perhaps consider using `AggregateError`. That will of course be impossible inside a Compartment for now, but I do not think this is inside a Compartment.

File: packages/agoric-cli/src/install.js [hunk 7]
```diff
@@ -120,93 +235,44 @@ export default async function installMain(progname, rawArgs, powers, opts) {
...
-    await Promise.all(
-      subdirs.map(subdir => {
-        const nm = `${subdir}/node_modules`;
-        log(chalk.bold.green(`removing ${nm}`));
-        return rimraf(nm);
-      }),
-    );
-  }
+      // This open-coding of the above yarn command is quiet and fast.
+      const linkName = `${linkFolder}/${pjName}`;
```
Comment (kriskowal) [inline packages/agoric-cli/src/install.js:298]: How do you feel about `path.join`? My current personal rule is not hard and fast either way.

File: scripts/npm-dist-tag.sh [hunk 8]
```diff
@@ -0,0 +1,67 @@
+#! /bin/bash
+# npm-dist-tag.sh - manage dist-tags for NPM registry packages 
+# Try: `npm-dist-tag.sh` for usage.
+
+# Exit on any errors.
+set -e
```
Comment (kriskowal) [inline scripts/npm-dist-tag.sh]: Please consider cargoing `set -ueo pipefail` as a matter of style.

File: scripts/npm-dist-tag.sh [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+  ;;
+esac
+
+# Find the package name and version from the package.json.
+pkg=$(jq -r .name package.json)
+version=$(jq -r .version package.json)
+# echo "$OP $pkg@$version"
+
+# Get the second argument, if any.
+TAG=$2
```
Comment (kriskowal) [inline scripts/npm-dist-tag.sh:41]: As a matter of style, do you prefer to always use TRAIN_CASE or snake_case for sh/env variables? Do you prefer to beg a distinction on whether they’re exported?

File: scripts/npm-dist-tag.sh [hunk 10]
```diff
@@ -0,0 +1,67 @@
+#! /bin/bash
+# npm-dist-tag.sh - manage dist-tags for NPM registry packages
```
Comment (kriskowal) [inline scripts/npm-dist-tag.sh]: Perhaps add/remove/list is more evocative than manage.

File: scripts/npm-dist-tag.sh [hunk 11]
```diff
@@ -0,0 +1,67 @@
...
+  exec npm run -- lerna exec --stream --no-bail "$thisdir/$thisprog" ${1+"$@"}
+  ;;
+esac
+
+# If the package.json says it's private, we don't have a published version whose
+# tags we can manipulate.
+priv=$(jq -r .private package.json)
+case "$priv" in
+true)
+  echo 1>&2 "Private package, skipping npm-dist-tag.sh"
```
Comment (kriskowal) [inline scripts/npm-dist-tag.sh:30]: Wherein the reviewer relearns that redirects can be interpolated anywhere in a command.

File: scripts/npm-dist-tag.sh [hunk 12]
```diff
@@ -0,0 +1,67 @@
...
+  # If <tag> is given, list only that tag.
+  if test -n "$TAG"; then
+    npm dist-tag ls "$pkg" | sed -ne "s/^$TAG: //p"
+  else
+    npm dist-tag ls "$pkg"
+  fi
+  ;;
+*)
+  # Usage instructions.
+  echo 1>&2 "Usage: $0 [lerna] <add|remove|list> [<tag>]"
```
Comment (kriskowal) [inline scripts/npm-dist-tag.sh:64]: Is the distinction that `lerna` means to apply in bulk to the workspaces? Would we ever *not* do that?

File: packages/agoric-cli/src/install.js [hunk 13]
```diff
@@ -120,93 +235,44 @@ export default async function installMain(progname, rawArgs, powers, opts) {
...
-          // This use of yarn is noisy and slow.
-          await pspawn('yarn', [...linkFlags, 'unlink', pjName]);
-          return pspawn('yarn', [...linkFlags, 'link'], {
-            stdio: 'inherit',
-            cwd: dir,
-          });
-        }
+  // Create symlinks to the SDK packages.
+  await Promise.all(
+    dirPackages.map(async ([dir, pjName]) => {
```
Comment (kriskowal) [inline packages/agoric-cli/src/install.js]: Is this not equivalent to packages.entries()? Can these be consolidated?

File: packages/agoric-cli/src/install.js [hunk 14]
```diff
@@ -40,7 +40,117 @@ export default async function installMain(progname, rawArgs, powers, opts) {
...
+    }
+
+    // Ensure we do all the package.json updates after any necessary pruning,
+    // even if there are failures.
+    await pruningP.finally(() =>
+      // Ensure the updated package.jsons are installed.
+      Promise.allSettled(updatesTodo.map(async update => update())),
+    );
+  };
+
```
Comment (kriskowal) [inline packages/agoric-cli/src/install.js:181]: There’s a hazard on line 157 where a parse error will cause a reference error on 158.

**Review by kriskowal — COMMENTED** [review]
Everything in here looks like it does what it says it’s supposed to, but after a couple passes, I’m still fuzzy on why it works. Is the notion that `install` does a number of shallow installs and revises the package.jsons for the installed packages in-place? Is this recursive?

Would the effect be comparable to amending the dapp package.json to include `resolutions` for all the agoric-sdk packages using a particular dist-tag?

File: scripts/npm-dist-tag.sh (hunk 12 above)
Comment (michaelfig) [reply scripts/npm-dist-tag.sh:64]: > Is the distinction that lerna means to apply in bulk to the workspaces? Would we ever not do that?

Yes and yes, if we want to add/remove/list the dist-tags for just the package in the cwd.

File: scripts/npm-dist-tag.sh (hunk 9 above)
Comment (michaelfig) [reply scripts/npm-dist-tag.sh:41]: I use `TRAIN_CASE` for environment variables and command-line arguments.

File: packages/agoric-cli/src/install.js (hunk 7 above)
Comment (michaelfig) [reply packages/agoric-cli/src/install.js:298]: Unless portability to older versions or Windows failures demand otherwise, I just use slashes and trust that Node.js's `fs` module figures out the rest.

File: packages/agoric-cli/src/install.js (hunk 6 above)
Comment (michaelfig) [reply packages/agoric-cli/src/install.js]: `AggregateError` is not available in Node v14.  Do you have a better suggestion?

File: packages/agoric-cli/src/install.js (hunk 5 above)
Comment (michaelfig) [reply packages/agoric-cli/src/install.js]: > I presume you considered and decided against framing this in terms of a finally. I don’t think it would occur to me to use the beforeExit event under any circumstances.

It *is* framed in terms of a `pruningP.finally(...)`.  It's quite important that these updates are done even if the process is interrupted.  Do you have a better mechanism at hand?

**Review by michaelfig — COMMENTED** [review]
Comments addressed to the best of my ability.

**Comment by michaelfig** [comment]
> Is the notion that `install` does a number of shallow installs

No, it handles the old-style dapp environment which is a top-level worktree and another worktree with its own `yarn.lock` in the `ui` directory.  Typically the `package.json` are updated and then there is only one `yarn install` per worktree.

This works fine if the `package.json` versions **don't already match**, but yarn really doesn't want to reinstall a package that already appears in `yarn.lock` if it's semver-compatible.

When a forced version (like `agoric install dev`) is supplied, and a given `package.json' already refers to it, the `package.json` updates and `yarn install` above are preceded by first removing the matching Agoric SDK packages from the `package.json`s, then run a pruning `yarn install` per worktree to clear out the old dependencies.

This is the fastest way to trim out the obsolete dependencies from both the workspaces' `node_modules` directories and the worktrees' `yarn.lock`s, at a cost of at most 1-2 `yarn install`s per worktree.  Other methods I investigated but threw out were:

- `yarn remove` the packages one-by-one, then update the `package.json` and `yarn install`
- prune the `yarn.lock`s with code written especially for `agoric install`
- Delete the `yarn.lock`s entirely, and run a `yarn install`

> Would the effect be comparable to amending the dapp package.json to include `resolutions` for all the agoric-sdk packages using a particular dist-tag?

I don't think so.  The idea is that `package.json`s and `yarn.lock`s should point to real packages all the time, and be reinstallable from scratch just with `yarn install`.  The "symlink-to-SDK" mode is an add-on, not a replacement.

File: packages/agoric-cli/src/install.js (hunk 6 above)
Comment (kriskowal) [reply packages/agoric-cli/src/install.js]: In the absence of AggregateError, I like to aggregate error messages, e.g.,

```js
new Error(`Cannot x for multiple causes (${causes.map(x => x.message).join('; '))`)
```

But I won’t press the issue. The first cause is certainly sufficient and indeed all you’d see in a serial causal graph.

File: packages/agoric-cli/src/install.js (hunk 5 above)
Comment (kriskowal) [reply packages/agoric-cli/src/install.js]: No, there’s nothing better in the face of uncaught exceptions.

**Review by kriskowal — APPROVED** [review]
I cannot profess to be able to maintain `agoric install` based on this review, but the code looks like it should do as advertised. Given that hopefully `agoric install` gives way to `yarn install` soonish, I’m okay with this.

File: packages/agoric-cli/src/install.js [hunk 15]
```diff
@@ -63,43 +212,39 @@ export default async function installMain(progname, rawArgs, powers, opts) {
...
 
-  const linkFolder = path.resolve(`_agstate/yarn-links`);
-  const linkFlags = [`--link-folder=${linkFolder}`];
-
+  /** @type {Map<string, string>} */
   const packages = new Map();
-  const versions = new Map();
-  const dirPackages = [];
+
+  const sdkRoot = path.resolve(dirname, `../../..`);
```
Comment (mhofman) [inline packages/agoric-cli/src/install.js:218]: Where is this coming from ?

**Comment by mhofman** [comment]
> `agoric install beta` will update the workspace's `yarn.lock` with the beta dependencies. From that point on, installing the dapp only needs `yarn install` (though `agoric install` will work, too).

This actually doesn't work for me. The `yarn.lock` file of my existing dapp doesn't seem to be updated. The `preinstall` script is also left in place, which means `yarn install` is not possible.
