### PR TITLE
fix vault manager totalDebt metric

### LINKED ISSUE #5550: vault manager totalDebt metric does not return to zero when all vaults are closed/liquidated
## Describe the bug

vault manager totalDebt metric does not always return to zero when all vaults are closed/liquidated.

## To Reproduce
1. Open new vaults in a manager
2. Accrue interest that results in a shortfall and triggers liquidation
4. see that totalDebt is not zero

## Expected behavior
totalDebt is a metric of the debts in the store. It should always be the sum of the held vaults' actual debts. It could be inferred from adding that for all the vaults but for performance we track it as a scalar that moves with operations that change the vaults.

### PR DESCRIPTION
**Pull request by turadg**
closes: #5550
stacks on: #5531

## Description

The `totalDebt` tracker wasn't accounting for shortfalls. While debugging I also encountered off-by-one rounding errors with apparently inconsistent of ceil/floor, so this also changes to use bankers' rounding in interest calculations.

### Security Considerations

No changes here but noted some opportunities to reduce powers of the `liquidate` module.

### Documentation Considerations

--

### Testing Considerations

The metrics tests would take less effort to read and maintain if they used a driver. Should that be done in this PR? (e.g. moving into a new file modeled after `test-liquidator.js`.

### CODE REVIEW

File: packages/run-protocol/test/vaultFactory/test-vaultFactory.js [hunk 1]
```diff
@@ -2507,26 +2505,27 @@ test('manager notifiers', async t => {
       Collateral: t.context.aeth.mint.mintPayment(aeth.make(AMPLE)),
     }),
   );
-  const { vault: vault1 } = await E(vaultSeat).getOfferResult();
+  let { vault } = await E(vaultSeat).getOfferResult();
```
Comment (Chris-Hibbert) [inline packages/run-protocol/test/vaultFactory/test-vaultFactory.js:2508]: I'm not a fan of re-using variables in this way, but if that's the way this test goes, please update vault2 (line 2726) to be part of it.

**Review by Chris-Hibbert — APPROVED** [review]

File: packages/run-protocol/test/vaultFactory/test-vaultFactory.js (hunk 1 above)
Comment (turadg) [reply packages/run-protocol/test/vaultFactory/test-vaultFactory.js:2508]: Not my favorite either. I think this would be better with a driver but that's more work that I can't justify. At one point I had them numbered, but that made it harder to move things around. 

(done as a fixup and rebase)
