### PR TITLE
fix(vow): handle resolution loops in vows

### LINKED ISSUE #9560: Self resolving vows cause infinite loop
## Describe the bug
Resolving a vow to itself, either directly or through intermediate promises and/or other vows, result in an infinite loop through shortening.

Unlike promise self resolution which at best result in a data lock when awaited, the consequence here is a full livelock (no other work ends up processed while in the infinite loop)

## To Reproduce

```js
test.failing('vow self resolution', async t => {
  const zone = makeHeapZone();
  const { watch, when, makeVowKit } = prepareVowTools(zone);

  // A direct self vow resolution
  const { vow: vow1, resolver: resolver1 } = makeVowKit();
  resolver1.resolve(vow1);

  // A self vow resolution through promise
  const { vow: vow2, resolver: resolver2 } = makeVowKit();
  const vow2P = Promise.resolve(vow2);
  resolver2.resolve(vow2P);

  // A 2 vow loop
  const { vow: vow3, resolver: resolver3 } = makeVowKit();
  const { vow: vow4, resolver: resolver4 } = makeVowKit();
  resolver3.resolve(vow4);
  resolver4.resolve(vow3);

  // A head pointing to a 2 vow loop (a lasso?)
  const { vow: vow5, resolver: resolver5 } = makeVowKit();
  resolver5.resolve(vow4);

  const turnTimeout = async n => {
    if (n > 0) {
      return Promise.resolve(n - 1).then(turnTimeout);
    }

    return 'timeout';
  };

  /**
   * @param {number} n
   * @param {Promise<any>} promise
   */
  const raceTurnTimeout = async (n, promise) =>
    Promise.race([promise, turnTimeout(n)]);

  await t.throwsAsync(raceTurnTimeout(20, when(watch(vow1))));

  await t.throwsAsync(raceTurnTimeout(20, when(watch(vow2))));

  await t.throwsAsync(raceTurnTimeout(20, when(watch(vow3))));

  await t.throwsAsync(raceTurnTimeout(20, when(watch(vow5))));
});
```

## Expected behavior
No infinite loop

### PR DESCRIPTION
**Pull request by mhofman**
closes: #9560

## Description
Add a weak set of previously seen vowV0 payloads when shortening during `watch` or `when`

### Security Considerations
None

### Scaling Considerations
Potential churn in storage just for shortening loop detection. Every `watch` will cause a new WeakSetStore to be allocated.

### Documentation Considerations
None

### Testing Considerations
New unit tests

### Upgrade Considerations
To avoid state migration concerns, this needs to be deployed before we start using `watch` more broadly.

### CODE REVIEW

File: packages/vow/src/watch.js [hunk 1]
```diff
@@ -81,6 +81,7 @@ const preparePromiseWatcher = (zone, isRetryableReason, watchNextStep) =>
       const state = {
         vow: /** @type {unknown} */ (undefined),
         priorRetryValue: /** @type {any} */ (undefined),
+        seenPayloads: zone.detached().weakSetStore('seenPayloads'),
```
Comment (mhofman) [inline packages/vow/src/watch.js]: Is this the right way? Is there some scaling considerations about creating a new short lived weak store for every `watch` operation?

Comment (warner) [reply packages/vow/src/watch.js]: I'm guessing this code is running in userspace, so the weakSetStore is backed by a "WeakSet" which is really a `VirtualObjectAwareWeakSet`. I *think* that's ok, there's some extra overhead for each one, but I think it's linear. 
These keys, are vows `passStyleOf` as Remotables?

Comment (warner) [reply packages/vow/src/watch.js]: Oh, wait, the zone is durable, so this is making a new durable WeakSetStore. Yeah, that's got some significant overhead, we allocate a new collection ID (eg a vref) for each one. When the Store is GCed, we'll delete all that, but we still have several DB reads+writes for each one. It would be a lot better to make a single WeakSetStore for the whole vat, and have all watch operations share it.

Comment (mhofman) [reply packages/vow/src/watch.js]: the set is specific to each watch, so I don't see how to avoid making a new set per watch...

Comment (mhofman) [reply packages/vow/src/watch.js]: The alternative is to keep the vows strongly and use a copy array.

**Comment by mhofman** [comment]
@michaelfig I'm getting some test failures I'm not sure why

File: packages/vow/src/when.js [hunk 2]
```diff
@@ -28,8 +28,14 @@ export const makeWhen = (
     let result = await specimenP;
     let payload = getVowPayload(result);
     let priorRetryValue;
+    const seenPayloads = new WeakSet();
     while (payload) {
-      result = await basicE(payload.vowV0)
+      const { vowV0 } = payload;
```
Comment (michaelfig) [inline packages/vow/src/when.js:35]: Leaving as a TODO for later, I don't want to impede the pragmatic goal of getting this PR merged.

TODO: encapsulate this extraction in `vow-utils.js` as a subfunction used by `toPassableCap`, but taking a payload instead of a possible Vow:

```js
/**
 * comments here...
 * @param {VowPayload}
 * @returns {PassableCap}
 */
export const vowPayloadToPassableCap = payload => payload.vowV0;
```

Doing this would require more thought to decide when we actually should depend on `vowV0` vs when we only want a passable cap that can serve as a store key.

**Review by michaelfig — APPROVED** [review]
LGTM.  I love the test!

**Comment by mhofman** [comment]
@michaelfig PTAL for the ephemeral set for watch

**Review by michaelfig — APPROVED** [review]
Looks great!  Thanks for taking this on.
