### PR TITLE
fix: include liquidationMargin in liquidation

### LINKED ISSUE #7191: liquidationMargin ignored when liquidating
## Describe the bug

Changing the price from 12.34 to 9.99 should liquidate a vault with 15 collateral and 100 debt at liquidationMargin of 150%.

. | t0 | t1
-- | -- | --
Collateral | 15 | 15
Debt | 100 | 100
Price | 12.34 | 9.99
Coll. ratio | 185.10% | 149.85%

If we reduce the price to 5, so that the liquidation ratio is under 100%, it does liquidate.

## To Reproduce

Use the numbers above in the `'price drop'` test in `packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js`.

## Expected behavior

The vault above should get liquidated.

VaultManager should pass `liquidationMargin` to `normalizedCollRatioKey()`.

## Platform Environment
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

2023-03-20 15:15 90f9597a5 feat: place bids by discount, price in inter CLI

based on

2023-03-20 19:47 ab52304dc Merge pull request #7184 from Agoric/7181-durable-auctioneer

## Additional context

cc @Chris-Hibbert

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #7191

## Description

The liquidation calculation ignored the liquidationMargin. This adds it.

### Security Considerations

Economic implications, but not strictly security.

### Scaling Considerations

No impact

### Documentation Considerations

No changes required.

### Testing Considerations

Corrects some existing tests and adds a test corresponding to  #7191.

### CODE REVIEW

File: packages/inter-protocol/src/vaultFactory/vaultManager.js [hunk 1]
```diff
@@ -813,11 +813,18 @@ export const prepareVaultManagerKit = (
             Fail`Must have locked a quote before liquidating vaults.`;
           assert(lockedQuote); // redundant with previous line
 
-          const crKey = normalizedCollRatioKey(lockedQuote, compoundedInterest);
+          const liqMargin = facets.self
+            .getGovernedParams()
+            .getLiquidationMargin();
+          const crKey = normalizedCollRatioKey(
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/vaultManager.js]: Investigating this change made me realize: vaultManager shouldn't be concerned with the encoding. Even liquidation.js shouldn't.

`vaultManager` is concerned with the parameters
`liquidation` turns those into a collateralization ratio threshold
`prioritizedVaults` takes that ratio and uses the encoding utils to query its store

**Review by turadg — COMMENTED** [review]
Changes look correct. Please include factoring improvements.

File: packages/inter-protocol/src/vaultFactory/storeUtils.js [hunk 2]
```diff
@@ -128,15 +128,22 @@ harden(fromVaultKey);
...
  */
-export const normalizedCollRatio = (quote, compoundedInterest) => {
+export const normalizedCollRatio = (quote, compoundedInterest, margin) => {
   const amountIn = getAmountIn(quote).value;
   const amountOut = getAmountOut(quote).value;
   const interestNumerator = compoundedInterest.numerator.value;
   const interestBase = compoundedInterest.denominator.value;
-  const numerator = multiply(amountIn, interestNumerator);
-  const denominator = multiply(amountOut, interestBase);
+  const numerator = multiply(
```
Comment (dtribble) [inline packages/inter-protocol/src/vaultFactory/storeUtils.js:144]: Can we use amount math instead? It's purpose is to keep the amount units all correct rather than open-coding with raw numbers. 

Otherwise, it seems that we need (in the future) some additional helpers for e.g., doing unitless operations on Amounts.

File: packages/inter-protocol/src/vaultFactory/storeUtils.js [hunk 3]
```diff
@@ -128,15 +128,22 @@ harden(fromVaultKey);
  *
  * @param {PriceQuote} quote
  * @param {Ratio} compoundedInterest
+ * @param {Ratio} margin
  * @returns {number}
  */
-export const normalizedCollRatio = (quote, compoundedInterest) => {
+export const normalizedCollRatio = (quote, compoundedInterest, margin) => {
```
Comment (dtribble) [inline packages/inter-protocol/src/vaultFactory/storeUtils.js:139]: I would like a comment that explains what this is supposed to do rather than who uses it.

File: packages/inter-protocol/src/vaultFactory/storeUtils.js (hunk 2 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/storeUtils.js:144]: AmountMath is the wrong tool for calculating `a/b * c/d * e/f`.  Even using  ratios fails on this, since it wants to do a floor or ceiling divide on every operation. The best way to get an answer without losing precision along the way is to turn that into `a*b*c / d*e*f`, and only do one divide at the end. 

And in this case, we want the result to be a float anyway, since we're using it as a key/discriminator for a store indexed by normalized collateralization ratio.

File: packages/inter-protocol/src/vaultFactory/storeUtils.js (hunk 3 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/storeUtils.js:139]: copied more detail from below.

File: packages/inter-protocol/src/vaultFactory/prioritizedVaults.js [hunk 4]
```diff
@@ -108,9 +115,16 @@ export const makePrioritizedVaults = store => {
...
-    // crKey represents a collateralizationRatio based on the locked price.
+  const removeVaultsBelow = ({ margin, quote, interest }) => {
+    // crKey represents a collateralizationRatio based on the locked price, the
+    // interest charged so far, and the liquidation margin.
     // We'll remove all vaults below that ratio, and return them.
+    const crKey = normalizedCollRatioKey(quote, interest, margin);
+
+    trace(
+      `Liquidating vaults worse than`,
+      normalizedCollRatio(quote, interest, margin),
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/prioritizedVaults.js:126]: this is calling `normalizedCollRatio` even when trace is off, duplicating the work in `normalizedCollRatioKey`.

File: packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js [hunk 5]
```diff
@@ -1524,3 +1523,107 @@ test('Auction sells all collateral w/shortfall', async t => {
   //  Bidder bought 800 Aeth
   await assertBidderPayout(t, bidderSeat, run, 115n, aeth, 700n);
 });
+
+// See #7191.  Changing the price from 12.34 to 9.99 should liquidate a vault
+// with 15 collateral and 100 debt at liquidationMargin of 150%. Interest won't
+// be charged over this period.
+test('liquidation Margin matters', async t => {
```
Comment (dckc) [inline packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js:1532]: :clap:

File: packages/inter-protocol/src/vaultFactory/prioritizedVaults.js (hunk 4 above)
Comment (turadg) [reply packages/inter-protocol/src/vaultFactory/prioritizedVaults.js:126]: on second thought, not a problem. I first thought you’d just calculate the float then use it in both places, but the `…Key` function does the calculating too. You could separate the encoding but that is complexity is not worth the savings in extra arithmetic.

**Review by turadg — APPROVED** [review]
