### PR TITLE
fix: if `makeEmptyPurse` fails, then `startInstance` and `saveIssuer` should fail

### LINKED ISSUE #4062: Improve Behavior When Creating a Purse Hangs or Fails
# Suggestion 2: Improve Behavior When Creating a Purse Hangs or Fails

## Location
https://github.com/Agoric/agoric-sdk/blob/f6a87bab45bb6ac611f91e20a3c93baf1b180294/packages/zoe/src/zoeService/escrowStorage.js#L23-L27

[Unit test of failure](https://github.com/LeastAuthority/Agoric-Systems-Zoe-ERTP/blob/makeEmptyPurse/packages/zoe/test/unitTests/test-zoe.js#L192-L204)

## Synopsis
`startInstance` and `saveIssuer` create an empty purse as part of their implementation. If the empty purse creation fails, then both of these functions should fail.
The `createPurse` function calls the issuer’s `makeEmptyPurse` method:
```js
  const createPurse = (issuer, brand) => {
    if (!brandToPurse.has(brand)) {
      brandToPurse.init(brand, E(issuer).makeEmptyPurse());
    }
};
```
If `makeEmptyPurse `fails, then a rejected promise will be stored in `brandToPurse` but the `createPurse` function will not fail. As a result, neither `startInstance` nor `saveIssuer` will fail as they should. We have created a [unit test](https://github.com/LeastAuthority/Agoric-Systems-Zoe-ERTP/blob/makeEmptyPurse/packages/zoe/test/unitTests/test-zoe.js#L192-L205) to demonstrate this problem.

## Mitigation
`createPurse` is a synchronous function therefore it cannot return a rejected promise without changing its signature. We recommend rearchitecting the function and its callers so that failures in `makeEmptyPurse` bubble up the call stack.

### PR DESCRIPTION
**Pull request by katelynsills**
closes: #4062 

## Description

This PR fixes a bug in Zoe. Previously, when `startInstance` or `saveIssuer` was called, Zoe would try to create a new empty escrow purse for any new issuer. Rather than `await` the promise for the purse, Zoe put the promise for the purse directly in a map. This created problems, because if the promise later rejected, the original call would have already succeeded, and moreover, any further use of the "purse" would fail because only a rejected promise was stored. The fix is to `await` the promise for the purse, and thus make sure that the calling function (`startInstance` or `saveIssuer`) throws if `makeEmptyPurse` throws. Only when `makeEmptyPurse` succeeds and resolves to a purse do we store the purse in the map. 

### Security Considerations

If `makeEmptyPurse` throws during `startInstance`, a contract instance is not created, which is a security improvement.

### Documentation Considerations

Probably nothing to add to documentation.

### Testing Considerations

I added tests to confirm that `startInstance` and `saveIssuer` throw appropriately.

### CODE REVIEW

File: packages/zoe/src/zoeService/escrowStorage.js [hunk 1]
```diff
@@ -20,9 +20,24 @@ export const makeEscrowStorage = () => {
...
+    let purseP;
+    try {
+      purseP = await E(issuer).makeEmptyPurse();
+    } catch (err) {
+      const cannotCreateError = Error(
+        // @ts-ignore Types should allow for a DetailsToken
+        X`A purse could not be created for brand ${brand}`,
+      );
+      assert.note(cannotCreateError, X`Caused by: ${err}`);
+      throw cannotCreateError;
```
Comment (erights) [inline packages/zoe/src/zoeService/escrowStorage.js]: Unfortunately, we're not in a position to modify the `Error` constructors to understand error details (`X`). In this case, the static type error indicated an actual problem! Instead, use `assert.error`

```suggestion
      const cannotCreateError = assert.error(
        X`A purse could not be created for brand ${brand}`,
      );
      assert.note(cannotCreateError, X`Caused by: ${err}`);
      throw cannotCreateError;
```
or, in this case, consider using `assert.fail` directly. I don't see any reason to hide the underlying `err` cause to unprivileged viewers of the outer error.
```suggestion
      assert.fail(
        X`A purse could not be created for brand ${brand} because: ${err}`,
      );
```

File: packages/zoe/src/zoeService/escrowStorage.js [hunk 2]
```diff
@@ -20,9 +20,24 @@ export const makeEscrowStorage = () => {
...
   /** @type {CreatePurse} */
-  const createPurse = (issuer, brand) => {
+  const createPurse = async (issuer, brand) => {
+    if (brandToPurse.has(brand)) {
+      return;
+    }
+    let purseP;
+    try {
+      purseP = await E(issuer).makeEmptyPurse();
+    } catch (err) {
```
Comment (erights) [inline packages/zoe/src/zoeService/escrowStorage.js]: The `try/await/catch` seems like a very heavy hammer to get the reason from a rejected promise. More straightforward would be something like

```suggestion
  const createPurse = (issuer, brand) => {
    if (brandToPurse.has(brand)) {
      return undefined; // or Promise.resolve(undefined) without CreatePurse reform below
    }
    return E.when(
      E(issuer).makeEmptyPurse(),
      purseP => {
        // Check again after the `await`
        if (!brandToPurse.has(brand)) {
          brandToPurse.init(brand, purseP);
        }
      },
      err =>
        // ...See below for more on the error case...
        assert.fail(
          X`A purse could not be created for brand ${brand} because: ${err}`,
        ),
    );
  };
```

File: packages/zoe/src/zoeService/internal-types.js [hunk 3]
```diff
@@ -6,7 +6,7 @@
  * @callback CreatePurse
  * @param {Issuer} issuer
  * @param {Brand} brand
- * @returns {void}
+ * @returns {Promise<void>}
```
Comment (erights) [inline packages/zoe/src/zoeService/internal-types.js]:
```suggestion
 * @returns {ERef<void>}
```
allows the `return undefined;` in suggested change to `createPurse` above.

File: packages/zoe/test/unitTests/test-zoe.js [hunk 4]
```diff
@@ -141,6 +141,28 @@ test(`E(zoe).startInstance - terms, issuerKeywordRecord switched`, async t => {
...
+    makeEmptyPurse: async () => {
+      throw Error('bad issuer');
+    },
+    getBrand: () => brand,
+  });
+  await t.throwsAsync(
+    // @ts-ignore deliberate invalid arguments for testing
+    () => E(zoe).startInstance(installation, { Money: badIssuer }),
+    {
+      message: 'A purse could not be created for brand "[Alleged: brand]"',
```
Comment (erights) [inline packages/zoe/test/unitTests/test-zoe.js]:
```suggestion
      message: 'A purse could not be created for brand "[Alleged: brand]" because: "[Error: bad issuer]"',
```

File: packages/zoe/test/unitTests/zcf/test-zcf.js [hunk 5]
```diff
@@ -199,6 +200,28 @@ test(`zcf.saveIssuer - bad issuer`, async t => {
...
+    makeEmptyPurse: async () => {
+      throw Error('bad issuer');
+    },
+    getBrand: () => brand,
+  });
+  await t.throwsAsync(
+    // @ts-ignore deliberate invalid arguments for testing
+    () => zcf.saveIssuer(badIssuer, 'A'),
+    {
+      message: 'A purse could not be created for brand "[Alleged: brand]"',
```
Comment (erights) [inline packages/zoe/test/unitTests/zcf/test-zcf.js]:
```suggestion
      message: 'A purse could not be created for brand "[Alleged: brand]" because: "[Error: bad issuer]"',
```

**Review by erights — APPROVED** [review]
LGTM

File: packages/zoe/src/zoeService/escrowStorage.js (hunk 2 above)
Comment (katelynsills) [reply packages/zoe/src/zoeService/escrowStorage.js]: This looks much better, thanks!
