### PR TITLE
fix(x/swingset): migration upgrade handler to fix state-sync

### LINKED ISSUE #8031: Migrate swing-store shadow copy to x/swingset cosmos store
## What is the Problem Being Solved?

#7225 introduced support for state-sync, leveraging the existing vstorage API to store a copy of the swing-store in the cosmos DB.

However the semantics of the vstorage API are not the best fit for large amount of data which are actually never consumed by off-chain clients. Amongst other things vstorage uses an encoding meant for direct children enumeration which makes it expensive to iterate over all entries as needed during state-sync operations.

## Description of the Design

- Introduce a new Prefixed KVStore in the `x/swingset` module used for holding the "export data" of the swingstore
- Register a port handler for the `x/swingset` module, and add a new bridge API for stream exporting swing-store data into this new cosmos store.
- Update the state-sync logic to use the new store when restoring
- Add migration logic to place existing swing-store data in the new cosmos store
- 
## Security Considerations

None. The new DB is part of the same overall cosmos multi-store, which is similarly hashed under consensus

## Scaling Considerations

This is a performance improvement, mostly when performing state-sync restore, but also when streaming swing-store data into the cosmos store.

## Test Plan

The existing integration test should cover the state-sync logic
The docker upgrade test should cover the migration
Add new unit tests for the new `x/swingset` prefixed store

### LINKED ISSUE #8081: state-sync is broken on mainnet: causes consensus failure an hour later
## Describe the bug

We learned recently that state-sync on mainnet is broken: any validator which is created from a state-sync export will experience a consensus failure error within an hour or so, and will halt.

We think we understand the problem: the state-sync import is getting bad data, and then a periodic transaction queries the broken data.

The next chain-software upgrade will include both #8031 and #8025, and the migration they perform ought to fix this as a side-effect.

### LINKED ISSUE #8128: Perform migration, add docker upgrade automated test: TBD
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by mhofman**
closes: #8081 
closes: #8031

## Description

This PR updated the swing-store export/import logic to support the new repair-metadata feature introduced by #8075 
 and changes the upgrade handler to perform the necessary migration to solve #8081, and completes the tasks of #8031 by adding an automated migration test.

It leverages the direct [swing-store export/import logic that was split from the state-sync snapshotter](https://github.com/Agoric/agoric-sdk/pull/8072), to repair and populate the "export data" shadow copy in the [new SwingSet prefix DB](https://github.com/Agoric/agoric-sdk/pull/8043).

This also changes which artifacts are included in a state-sync snapshot to ensure we stop discarding transcript spans of the current vat incarnations in order to be able to [perform xsnap upgrades](https://github.com/Agoric/agoric-sdk/issues/7855) in the future

### Security Considerations

Because of the switch to require "replay" artifacts, some validators that lack these artifacts will no longer be able to produce state-sync snapshots, however this does not affect consensus.

### Scaling Considerations

None

### Documentation Considerations

Release/upgrade notes should indicate that this will performs a partial migration of data in the cosmos DB, which may take some time.

We also need to communicate with validators that if they cannot produce state-sync snapshot, they will need to state-sync from a node that is able to produce those (one that hasn't state-synced yet).

### Testing Considerations

Adds an automated test of the migration leveraging the docker upgrade testing framework

### Upgrade Considerations

If the repair-metadata is not successfully processed on all nodes, the upgrade block may result in a divergence, and consensus failure due to AppHash mismatch

A power failure / OS crash happening during the separate swing-store / cosmos commit window of the upgrade block that would normally trigger hangover inconsistency logic will cause the node to become stuck in an inconsistent state. The only resolution is to restore from a backup (or wait for other nodes to start producing state-sync snapshots)

### CODE REVIEW

File: golang/cosmos/app/app.go [hunk 1]
```diff
@@ -803,14 +804,88 @@ func NewAgoricApp(
...
+
+func (eventHandler swingStoreMigrationEventHandler) OnExportStarted(height uint64, retrieveSwingStoreExport func() error) error {
+	return retrieveSwingStoreExport()
+}
+
+func (eventHandler swingStoreMigrationEventHandler) OnExportRetrieved(provider swingsetkeeper.SwingStoreExportProvider) (err error) {
+	defer helpers.RecoverToError(&err)
+
+	var exportDataIterator sdk.Iterator
+	exportDataIterator, err = provider.GetExportDataIterator()
```
Comment (gibson042) [inline golang/cosmos/app/app.go]: This use of `helpers.RecoverToError` probably warrants an explanatory comment, which would then remove the need to specifically declare `exportDataIterator`.
```suggestion
	// Work around sdk.Iterator abuse of `panic`.
	defer helpers.RecoverToError(&err)
	exportDataIterator, err := provider.GetExportDataIterator()
```

File: golang/cosmos/app/app.go [hunk 2]
```diff
@@ -803,14 +804,88 @@ func NewAgoricApp(
...
+		savedBlockHeight := uint64(ctx.BlockHeight() - 1)
+
+		// First, repair swing-store metadata in case this node was state-synced
+		// This is done without checks on the block height as it's idempotent,
+		// and only missing historical metadata is imported
+		getExportDataIterator := func() (iter sdk.Iterator, err error) {
+			defer helpers.RecoverToError(&err)
+
+			return swingsetkeeper.NewExportDataIterator(swingsetkeeper.NewVstorageDataEntriesReader(
+				app.VstorageKeeper.ExportStorageFromPrefix(ctx, swingsetkeeper.StoragePathSwingStore),
```
Comment (gibson042) [inline golang/cosmos/app/app.go:871]: This fundamentally requires having all such entries in memory, right? Is there a way around that worth pursuing?

File: golang/cosmos/app/app.go [hunk 3]
```diff
@@ -803,14 +804,88 @@ func NewAgoricApp(
...
+		readArtifact := func() (artifact swingsettypes.SwingStoreArtifact, err error) {
+			return artifact, io.EOF
+		}
+
+		err := app.SwingStoreExportsHandler.RestoreExport(
+			swingsetkeeper.SwingStoreExportProvider{
+				BlockHeight:           savedBlockHeight,
+				GetExportDataIterator: getExportDataIterator,
+				ReadArtifact:          readArtifact,
+			},
```
Comment (gibson042) [inline golang/cosmos/app/app.go]:
```suggestion
		readNoArtifact := func() (nilArtifact swingsettypes.SwingStoreArtifact, err error) {
			return nilArtifact, io.EOF
		}

		err := app.SwingStoreExportsHandler.RestoreExport(
			swingsetkeeper.SwingStoreExportProvider{
				BlockHeight:           savedBlockHeight,
				GetExportDataIterator: getExportDataIterator,
				ReadArtifact:          readNoArtifact,
			},
```
We should probably also rename SwingStoreExportProvider `ReadArtifact` to something like `ReadNextArtifact` or `NextArtifact`, because I was definitely thrown off by this code until digging in.

File: golang/cosmos/app/app.go [hunk 4]
```diff
@@ -803,14 +804,88 @@ func NewAgoricApp(
...
 		// Record the plan to send to SwingSet
 		app.upgradePlan = &plan
 
-		// TODO: Migrate x/vstorage swingStore to x/swingset SwingStore
+		savedBlockHeight := uint64(ctx.BlockHeight() - 1)
+
+		// First, repair swing-store metadata in case this node was state-synced
+		// This is done without checks on the block height as it's idempotent,
+		// and only missing historical metadata is imported
+		getExportDataIterator := func() (iter sdk.Iterator, err error) {
```
Comment (gibson042) [inline golang/cosmos/app/app.go]: Suggested clarifying rename:
```suggestion
		getSwingStoreDataFromVstorage := func() (iter sdk.Iterator, err error) {
```
(or some variation thereof)

File: golang/cosmos/app/app.go [hunk 5]
```diff
@@ -803,14 +804,88 @@ func NewAgoricApp(
...
+			swingsetkeeper.SwingStoreExportOptions{ArtifactLevel: "none", ExportDataMode: "all"},
+		)
+		if err != nil {
+			return nil, err
+		}
+
+		err = swingsetkeeper.WaitUntilSwingStoreExportDone()
+		if err != nil {
+			return nil, err
+		}
```
Comment (gibson042) [inline golang/cosmos/app/app.go]: This comment could use some elaboration, e.g.
```suggestion
		// Then migrate the swing-store shadow copy:
		// 1. Remove swingStore-shadowing entries from vstorage.
		// 2. Export swingStore data (as of the previous block) through a handler
		//    that writes the key-value pairs into the swingset module.
		app.VstorageKeeper.RemoveEntriesWithPrefix(ctx, swingsetkeeper.StoragePathSwingStore)
		err = app.SwingStoreExportsHandler.InitiateExport(
			savedBlockHeight,
			swingStoreMigrationEventHandler{swingStore: app.SwingSetKeeper.GetSwingStore(ctx)},
			swingsetkeeper.SwingStoreExportOptions{ArtifactLevel: "none", ExportDataMode: "all"},
		)
		if err == nil {
			err = swingsetkeeper.WaitUntilSwingStoreExportDone()
		}
		if err != nil {
			return nil, err
		}
```

File: golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go [hunk 6]
```diff
@@ -157,44 +157,76 @@ type swingStoreRestoreExportAction struct {
 	Args        [1]swingStoreImportOptions `json:"args"`
 }
 
-// SwingStoreExportModeCurrent represents the minimal set of artifacts needed
-// to operate a node.
-const SwingStoreExportModeCurrent = "current"
+// SwingStoreNoneArtifactLevel mean that no artifacts are part of the
```
Comment (gibson042) [inline golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go]:
```suggestion
// SwingStoreNoneArtifactLevel means that no artifacts are part of the
```
And a nit: I think we should probably give these constants left-to-right names for supporting purpose identification, e.g. SwingStore{None,Operational,Replay,Archival,Debug}ArtifactLevel → SwingStoreArtifactLevel{None,Operational,Replay,Archival,Debug} and SwingStore{Skip,RepairMetadata,All}ExportDataMode → SwingStoreExportDataMode{Skip,RepairMetadata,Full}, and also group them visually like
```go
const (
	…ArtifactLevel constants…
)

const (
	…ExportDataMode constants…
)
```

File: golang/cosmos/x/vstorage/keeper/keeper.go [hunk 7]
```diff
@@ -181,6 +181,49 @@ func (k Keeper) ImportStorage(ctx sdk.Context, entries []*types.DataEntry) {
...
+func (k Keeper) RemoveEntriesWithPrefix(ctx sdk.Context, pathPrefix string) {
+	store := ctx.KVStore(k.storeKey)
+
+	var descendantPrefix string
+	if len(pathPrefix) > 0 {
+		if err := types.ValidatePath(pathPrefix); err != nil {
+			panic(err)
+		}
+		descendantPrefix = pathPrefix + types.PathSeparator
+	}
```
Comment (gibson042) [inline golang/cosmos/x/vstorage/keeper/keeper.go]: We should probably just reject calls in which `pathPrefix` is empty; I don't think that's what this function is for and that power seems like unnecessary risk.

File: packages/cosmic-swingset/src/import-kernel-db.js [hunk 8]
```diff
@@ -141,13 +143,66 @@ export const performStateSyncImport = async (
...
+      throw Fail`State-sync manifest missing required artifacts`;
+    }
+
+    const exportMode = getExportModeFromArtifactLevel(artifactLevel);
+    const includeHistorical =
+      exportMode === 'archival' || exportMode === 'debug';
+
+    if (includeHistorical && manifest.mode === 'current') {
+      throw Fail`State-sync manifest missing historical artifacts`;
+    }
```
Comment (gibson042) [inline packages/cosmic-swingset/src/import-kernel-db.js]: This seems like a **lot** of real estate for input validation; I wonder if it can be made more concise?
```js
    typeof manifest.blockHeight === 'number' ||
      Fail`State-sync manifest missing valid block height`;

    manifest.data ||
      Fail`State-sync manifest missing export data`;

    manifest.artifacts?.length ||
      Fail`State-sync manifest missing required artifacts`;

    manifest.mode !== 'current' || !includeHistorical ||
      Fail`State-sync manifest missing historical artifacts`;

    artifactLevel !== 'none' ||
      Fail`Cannot import "export data" without at least "operational" artifacts`;
```

File: packages/cosmic-swingset/src/import-kernel-db.js [hunk 9]
```diff
@@ -141,13 +143,66 @@ export const performStateSyncImport = async (
...
+    if (blockHeight !== savedBlockHeight) {
+      throw Fail`block height doesn't match. requested=${q(
+        blockHeight,
+      )}, current=${q(savedBlockHeight)}`;
+    }
+
+    await repairDB(stateDir, exporter);
+  } else if (exportDataMode === 'skip') {
+    throw Fail`Repopulation of artifacts not yet supported`;
+  }
```
Comment (gibson042) [inline packages/cosmic-swingset/src/import-kernel-db.js]: Should this have a final clause for unknown `exportDataMode`?

File: golang/cosmos/app/app.go (hunk 2 above)
Comment (mhofman) [reply golang/cosmos/app/app.go:871]: There is, it might be possible to do now that have this shared reader interface. I didn't think it was worth it for a one time thing. FYI current state-sync restore already suffers from this (but works fine on that point), and new state-sync doesn't, so it's literally once more for this migration.

File: packages/cosmic-swingset/src/import-kernel-db.js (hunk 9 above)
Comment (mhofman) [reply packages/cosmic-swingset/src/import-kernel-db.js]: I assume correct / validated `exportDataMode`

File: golang/cosmos/app/app.go (hunk 3 above)
Comment (mhofman) [reply golang/cosmos/app/app.go]: That ship has somewhat sailed, let me see if I can add that change to #8043

File: packages/cosmic-swingset/src/import-kernel-db.js (hunk 8 above)
Comment (mhofman) [reply packages/cosmic-swingset/src/import-kernel-db.js]: If only Typescript was cooperating

File: golang/cosmos/app/app.go (hunk 1 above)
Comment (mhofman) [reply golang/cosmos/app/app.go]: Removed after switching to KVEntryReader

File: golang/cosmos/app/app.go (hunk 5 above)
Comment (mhofman) [reply golang/cosmos/app/app.go]: Let me know if the new comments are more clear

File: packages/cosmic-swingset/src/import-kernel-db.js (hunk 8 above)
Comment (mhofman) [reply packages/cosmic-swingset/src/import-kernel-db.js]: extracted in its own function

File: packages/cosmic-swingset/src/import-kernel-db.js (hunk 9 above)
Comment (mhofman) [reply packages/cosmic-swingset/src/import-kernel-db.js]: Added an `else`

File: golang/cosmos/app/app.go [hunk 10]
```diff
@@ -107,6 +107,7 @@ import (
 	gaiaappparams "github.com/Agoric/agoric-sdk/golang/cosmos/app/params"
 
 	appante "github.com/Agoric/agoric-sdk/golang/cosmos/ante"
+	agorictypes "github.com/Agoric/agoric-sdk/golang/cosmos/types"
```
Comment (gibson042) [inline golang/cosmos/app/app.go]: I think we conventionally name this import `agoric`.

File: golang/cosmos/app/app.go [hunk 11]
```diff
@@ -803,14 +804,106 @@ func NewAgoricApp(
...
 // upgrade11Handler performs standard upgrade actions plus custom actions for upgrade-11.
 func upgrade11Handler(app *GaiaApp, targetUpgrade string) func(sdk.Context, upgradetypes.Plan, module.VersionMap) (module.VersionMap, error) {
 	return func(ctx sdk.Context, plan upgradetypes.Plan, fromVm module.VersionMap) (module.VersionMap, error) {
 		app.CheckControllerInited(false)
 		// Record the plan to send to SwingSet
 		app.upgradePlan = &plan
 
-		// TODO: Migrate x/vstorage swingStore to x/swingset SwingStore
+		// Perform swing-store migrations. We do this in the app upgrade handler
+		// since it involved multile modules (x/vstorage and x/swingset) which
```
Comment (gibson042) [inline golang/cosmos/app/app.go]:
```suggestion
		// since it involves multiple modules (x/vstorage and x/swingset) which
```

File: golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go [hunk 12]
```diff
@@ -157,44 +157,80 @@ type swingStoreRestoreExportAction struct {
 	Args        [1]swingStoreImportOptions `json:"args"`
 }
 
-// SwingStoreExportModeCurrent represents the minimal set of artifacts needed
-// to operate a node.
-const SwingStoreExportModeCurrent = "current"
+const (
+	// SwingStoreArtifactModeNone mean that no artifacts are part of the
```
Comment (gibson042) [inline golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go]:
```suggestion
	// SwingStoreArtifactModeNone means that no artifacts are part of the
```

File: golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go [hunk 13]
```diff
@@ -157,44 +157,80 @@ type swingStoreRestoreExportAction struct {
...
+
+const (
+	// SwingStoreExportDataModeSkip indicates "export data" should be excluded from
+	// an export. ArtifactMode cannot be "none" in this case.
+	SwingStoreExportDataModeSkip = "skip"
+
+	// SwingStoreRepairMetadataExportDataMode indicates the "export data" should be
+	// used to repair the metadata of an existing swing-store for an import
+	// operation. ArtifactMode must be "none" in this case.
+	SwingStoreRepairMetadataExportDataMode = "repair-metadata"
```
Comment (gibson042) [inline golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go]:
```suggestion
	SwingStoreExportDataModeRepairMetadata = "repair-metadata"
```

File: golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go [hunk 14]
```diff
@@ -157,44 +157,80 @@ type swingStoreRestoreExportAction struct {
...
 }
 
 // SwingStoreRestoreOptions are configurable options provided to the JS swing-store import
 type SwingStoreRestoreOptions struct {
-	// A flag indicating whether the swing-store import should attempt to load
-	// all historical artifacts available from the export provider
-	IncludeHistorical bool `json:"includeHistorical,omitempty"`
+	// ArtifactMode can be "none", "operational", "replay", "archival" or "debug".
+	// It controls the set of artifacts that should be restored in swing-store.
+	// Use SwingStore*ArtifactMode const
```
Comment (gibson042) [inline golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go]:
```suggestion
	// Use SwingStoreArtifactMode* const
```

**Review by gibson042 — APPROVED** [review]

File: golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go (hunk 13 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go]: oops it feel through the cracks

File: golang/cosmos/app/app.go (hunk 10 above)
Comment (mhofman) [reply golang/cosmos/app/app.go]: Yeah but this file is top level already, so it didn't feel right, and all other ones have `types` suffix.

File: golang/cosmos/app/app.go [hunk 15]
```diff
@@ -810,14 +810,106 @@ func NewAgoricApp(
...
 // upgrade11Handler performs standard upgrade actions plus custom actions for upgrade-11.
 func upgrade11Handler(app *GaiaApp, targetUpgrade string) func(sdk.Context, upgradetypes.Plan, module.VersionMap) (module.VersionMap, error) {
 	return func(ctx sdk.Context, plan upgradetypes.Plan, fromVm module.VersionMap) (module.VersionMap, error) {
 		app.CheckControllerInited(false)
 		// Record the plan to send to SwingSet
 		app.upgradePlan = &plan
 
-		// TODO: Migrate x/vstorage swingStore to x/swingset SwingStore
+		// Perform swing-store migrations. We do this in the app upgrade handler
+		// since it involves multile modules (x/vstorage and x/swingset) which
```
Comment (warner) [inline golang/cosmos/app/app.go]: s/multile/multiple/

File: golang/cosmos/app/app.go [hunk 16]
```diff
@@ -810,14 +810,106 @@ func NewAgoricApp(
...
+		// don't strictly have a version change on their own.
+
+		// We are at the begining of the upgrade block, so all stores are commited
+		// as of the end of the previous block
+		savedBlockHeight := uint64(ctx.BlockHeight() - 1)
+
+		// First, repair swing-store metadata in case this node was state-synced
```
Comment (warner) [inline golang/cosmos/app/app.go]: s/was state-synced/initialized from an incomplete state-sync snapshot./

File: golang/cosmos/app/app.go [hunk 17]
```diff
@@ -810,14 +810,106 @@ func NewAgoricApp(
...
+		// This is done with a check on the block height to catch any hangover early
```
Comment (warner) [inline golang/cosmos/app/app.go]: s/hangover early/hangover mismatch early./

**Review by warner — APPROVED** [review]
seems right to me, minor typo fixes suggested

File: golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go [hunk 18]
```diff
@@ -157,44 +157,71 @@ type swingStoreRestoreExportAction struct {
...
-	// A flag indicating whether "export data" should be part of the swing-store export
-	// If false, the resulting SwingStoreExportProvider's GetExportDataReader
-	// will return nil
-	IncludeExportData bool `json:"includeExportData,omitempty"`
+	// ArtifactMode can be "none", "operational", "replay", "archival" or "debug".
+	// It controls the set of artifacts that should be included in the swing-store
+	// export. Use SwingStoreArtifactMode* const
+	// See packages/cosmic-swingset/src/export-kernel-db.js initiateSwingStoreExport
+	ArtifactMode string `json:"artifactMode,omitempty"`
+	// ExportDataMode can be "skip" or "all". It selects whether to include "export data"
```
Comment (JimLarson) [inline golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go]: Reference the constants rather than repeating their string values. (This is where I miss a real enum type.)

File: golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go [hunk 19]
```diff
@@ -157,44 +157,71 @@ type swingStoreRestoreExportAction struct {
...
 type SwingStoreExportOptions struct {
-	// The export mode can be "current", "archival" or "debug" (SwingStoreExportMode* const)
-	// See packages/cosmic-swingset/src/export-kernel-db.js initiateSwingStoreExport and
-	// packages/swing-store/src/swingStore.js makeSwingStoreExporter
-	ExportMode string `json:"exportMode,omitempty"`
-	// A flag indicating whether "export data" should be part of the swing-store export
-	// If false, the resulting SwingStoreExportProvider's GetExportDataReader
-	// will return nil
-	IncludeExportData bool `json:"includeExportData,omitempty"`
+	// ArtifactMode can be "none", "operational", "replay", "archival" or "debug".
```
Comment (JimLarson) [inline golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go]: Reference the constants (e.g. through a comment on the consts that groups them) rather than repeating their string values.

File: golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go [hunk 20]
```diff
@@ -157,44 +157,71 @@ type swingStoreRestoreExportAction struct {
...
+	// Use SwingStoreExportDataMode* const
+	ExportDataMode string `json:"exportDataMode,omitempty"`
 }
 
 // SwingStoreRestoreOptions are configurable options provided to the JS swing-store import
 type SwingStoreRestoreOptions struct {
-	// A flag indicating whether the swing-store import should attempt to load
-	// all historical artifacts available from the export provider
-	IncludeHistorical bool `json:"includeHistorical,omitempty"`
+	// ArtifactMode can be "none", "operational", "replay", "archival" or "debug".
```
Comment (JimLarson) [inline golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go]: Reference the constants.

File: golang/cosmos/x/vstorage/keeper/keeper.go [hunk 21]
```diff
@@ -181,6 +181,49 @@ func (k Keeper) ImportStorage(ctx sdk.Context, entries []*types.DataEntry) {
...
+	keys := make([][]byte, 0)
+	defer iterator.Close()
+	for ; iterator.Valid(); iterator.Next() {
+		key := iterator.Key()
+		path := types.EncodedKeyToPath(key)
+		if strings.HasPrefix(path, descendantPrefix) {
+			keys = append(keys, key)
+		}
+	}
+	iterator.Close()
```
Comment (JimLarson) [inline golang/cosmos/x/vstorage/keeper/keeper.go]: Add a comment that this assumes that it's okay to close the iterator again in the deferred statement.

Alternatively, refactor lines 206-217 into a helper method so that only closes via defer.

File: golang/cosmos/x/vstorage/keeper/keeper.go [hunk 22]
```diff
@@ -181,6 +181,49 @@ func (k Keeper) ImportStorage(ctx sdk.Context, entries []*types.DataEntry) {
 	}
 }
 
+// RemoveEntriesWithPrefix removes all storage entries starting with the
+// supplied pathPrefix, which may not be empty.
+// It has the same effect as listing children of the prefix and removing each
+// descendant recursively.
```
Comment (JimLarson) [inline golang/cosmos/x/vstorage/keeper/keeper.go:200]: Note that it also creates a no-value entry from the path prefix.

File: packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-11/env_setup.sh [hunk 23]
```diff
@@ -83,4 +83,65 @@ pushPriceOnce () {
...
+    echo "missing-untrusted-export-data"
+    return
+  fi
+  
+  diff <(cat "$EXPORT_DIR/$EXPORT_DATA_FILE" | sort) <(cat "$EXPORT_DIR/$EXPORT_DATA_UNTRUSTED_FILE" | sort) >&2 && {
+    echo "match"
+  } || {
+    echo "mismatch"
+  }
 }
```
Comment (JimLarson) [inline packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-11/env_setup.sh]: Nit: add newline at end of file.

**Review by JimLarson — APPROVED** [review]
Approving in advance of the requested changes.

File: golang/cosmos/x/vstorage/keeper/keeper.go (hunk 22 above)
Comment (mhofman) [reply golang/cosmos/x/vstorage/keeper/keeper.go:200]: It does not. It uses setStorage with a no value to **delete** the entry and any parents

File: golang/cosmos/app/app.go (hunk 16 above)
Comment (mhofman) [reply golang/cosmos/app/app.go]: Nit: the state-sync snapshot is always complete with regards to metadata, it's the restore process that was incomplete...

File: golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go (hunk 19 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go]: I already mention to use the `SwingStoreArtifactMode*` consts. I would prefer having a short list of values appear in the highlight of the field provided by the IDE since golang doesn't seem to have a way to express enum types.
