### PR TITLE
fix: make eslint shut up about unhandled promises

### LINKED ISSUE #5535: swingset unhandled promise lint fixes
I ran the new `scripts/lint-with-types.js` tool on swingset today, and here's a list of all the Promises that it thinks are not being fully handled:

```
node ➜ ~/agoric-sdk/packages/SwingSet $ ../../scripts/lint-with-types.sh
yarn run v1.22.17
$ yarn lint:types&&yarn lint:eslint
$ tsc --maxNodeModuleJsDepth 3 -p jsconfig.json
$ eslint .

/home/node/agoric-sdk/packages/SwingSet/misc-tools/measure-metering/measurement-target.js
  68:7  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/src/kernel/kernel.js
  266:7  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/src/kernel/vat-loader/manager-nodeworker.js
  67:7  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/src/liveslots/watchedPromises.js
   83:9   warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  117:11  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  173:5   warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/src/vats/network/network.js
  335:11  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  511:3   warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/src/vats/plugin-manager.js
  157:11  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  184:11  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  208:7   warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/src/vats/vattp/vat-vattp.js
  131:9  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/test/basedir-promises-2/bootstrap.js
  14:9  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  29:9  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/test/basedir-promises-3/vat-right.js
  12:7  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/test/basedir-promises/bootstrap.js
  13:9  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  14:9  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  40:9  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/test/device-plugin/test-device.js
  81:3  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  97:3  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/test/gc-device-transfer/bootstrap-gc.js
  19:7  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/test/test-liveslots.js
  222:9  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/test/test-network.js
   91:9  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  182:9  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/test/test-queue-priority.js
  10:5  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/test/workers/vat-target.js
  60:5  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

/home/node/agoric-sdk/packages/SwingSet/tools/vat.js
  54:7  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  58:7  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
  63:1  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

✖ 34 problems (0 errors, 34 warnings)
```

We should fix these.

### PR DESCRIPTION
**Pull request by FUDCo**
Fixes #5535

### CODE REVIEW

File: packages/SwingSet/src/kernel/kernel.js [hunk 1]
```diff
@@ -263,7 +263,7 @@ export default function buildKernel(
 
       // ISSUE: terminate stuff in its own crank like creation?
       // eslint-disable-next-line no-use-before-define
-      vatWarehouse.vatWasTerminated(vatID);
+      void vatWarehouse.vatWasTerminated(vatID);
```
Comment (warner) [inline packages/SwingSet/src/kernel/kernel.js:267]: that seems ok, the worker might still be running (we've started `manager.shutdown()` but haven't `await`ed it), but everything else about the worker is gone, so I don't think it will hurt to let that happen in the background

File: packages/SwingSet/src/kernel/vat-loader/manager-nodeworker.js [hunk 2]
```diff
@@ -64,7 +64,7 @@ export function makeNodeWorkerVatManagerFactory(tools) {
 
     function sendToWorker(msg) {
       assert(msg instanceof Array);
-      workerP.then(worker => worker.postMessage(msg));
+      void workerP.then(worker => worker.postMessage(msg));
```
Comment (warner) [inline packages/SwingSet/src/kernel/vat-loader/manager-nodeworker.js:67]: ok, I don't even know how that could fail, also we don't love `manager-nodeworker.js` anyways

File: packages/SwingSet/src/liveslots/watchedPromises.js [hunk 3]
```diff
@@ -80,7 +80,7 @@ export function makeWatchedPromiseManager(
       promiseRegistrations.delete(vpid);
       for (const watch of watches) {
         const [watcher, ...args] = watch;
-        Promise.resolve().then(() => {
+        void Promise.resolve().then(() => {
```
Comment (warner) [inline packages/SwingSet/src/liveslots/watchedPromises.js:83]: ah, right, if the user-supplied watcher object throws, we want the platform to catch it, and if we added a `.catch()` or something here to satisfy `eslint`, then we wouldn't get that behavior, so `void` is the only appropriate thing to do

File: packages/SwingSet/src/vats/network/network.js [hunk 4]
```diff
@@ -508,7 +508,7 @@ export function makeNetworkProtocol(protocolHandler) {
   });
 
   // Wire up the local protocol to the handler.
-  E(protocolHandler).onCreate(protocolImpl, protocolHandler);
+  void E(protocolHandler).onCreate(protocolImpl, protocolHandler);
```
Comment (warner) [inline packages/SwingSet/src/vats/network/network.js:511]: @michaelfig is this right? Do we need to be more careful with a rejection from `onCreate` ?

File: packages/SwingSet/src/vats/plugin-manager.js [hunk 5]
```diff
@@ -205,7 +205,7 @@ export function makePluginManager(pluginDevice, { D, ...vatPowers }) {
       });
 
       // Declare the first reset.
-      E(resetter).onReset(Promise.resolve(false));
+      void E(resetter).onReset(Promise.resolve(false));
```
Comment (warner) [inline packages/SwingSet/src/vats/plugin-manager.js:208]: @michaelfig same question here

File: packages/SwingSet/test/basedir-promises-2/bootstrap.js [hunk 6]
```diff
@@ -26,7 +26,7 @@ export function buildRootObject(vatPowers, vatParameters) {
         // const p4 = vats.left!checkHarden(p1);
         // log(`p4 frozen ${Object.isFrozen(p4)}`);
         // allP.push(p4);
-        Promise.all(allP).then(_ => {
+        return Promise.all(allP).then(_ => {
```
Comment (warner) [inline packages/SwingSet/test/basedir-promises-2/bootstrap.js:29]: yep, that's ok because test-promises.js isn't paying attention to the `bootstrap()` result promise, so it's ok if it resolves at a different crank than before

File: packages/SwingSet/test/basedir-promises-3/vat-right.js [hunk 7]
```diff
@@ -9,7 +9,7 @@ export function buildRootObject() {
       // arg should be a Promise that promptly resolves to 4
       const argP = Promise.resolve(arg);
       const wasP = argP === arg;
-      argP.then(newArg => pk4.resolve([wasP, newArg]));
+      return argP.then(newArg => pk4.resolve([wasP, newArg]));
```
Comment (warner) [inline packages/SwingSet/test/basedir-promises-3/vat-right.js:12]: ok, that's ok for similar reasons: bootstrap.js is not explicitly doing anything with the promise it gets back from `E(p2).four()`, so having the resolution timing change doesn't affect the thing being tested. Some of these tests are pretty subtle, which is why I'm looking at them so carefully.

**Review by warner — APPROVED** [review]
Looks good! Thanks for diving into this.

File: packages/SwingSet/src/vats/network/network.js (hunk 4 above)
Comment (michaelfig) [reply packages/SwingSet/src/vats/network/network.js:511]: No, making it an unhandled rejection is perfectly fine.

File: packages/SwingSet/src/vats/plugin-manager.js (hunk 5 above)
Comment (michaelfig) [reply packages/SwingSet/src/vats/plugin-manager.js:208]: Ditto.
