### PR TITLE
fix: Add a script for fetching and flattening published capdata

### LINKED ISSUE #5878: Translate capdata into flat JSON
## What is the Problem Being Solved?

External consumers should not be expected to work with complex structured data, especially when that structure is `@qclass`-heavy capdata.

## Description of the Design

Create a utility for converting capdata into flat JSON, e.g. from
```
{
  centralAmount: {
    brand: { '@qclass': 'slot', iface: 'Alleged: RUN brand', index: 0 },
    value: { '@qclass': 'bigint', digits: '1859152806' }
  },
  liquidityTokens: {
    brand: {
      '@qclass': 'slot',
      iface: 'Alleged: BLDPoolLiquidity brand',
      index: 1
    },
    value: { '@qclass': 'bigint', digits: '4455322155' }
  },
  secondaryAmount: {
    brand: { '@qclass': 'slot', iface: 'Alleged: BLD brand', index: 2 },
    value: { '@qclass': 'bigint', digits: '2159517880' }
  }
}
```
to
```json
{ "central": "1859152806", "centralBrandBoardId": "board0425", "centralBrandAllegedName": "RUN", "liquidity": "4455322155", "liquidityBrandBoardId": "board03125", "liquidityBrandAllegedName": "BLDPoolLiquidity", "secondary": "2159517880", "secondaryBrandBoardId": "board03523", "secondaryBrandAllegedName": "BLD" }
```

## Security Considerations

The utility should be written such that adopting it does not risk a significant increase to potentially vulnerable surface area (e.g. by installing a complex executable).

## Test Plan

TBD

### PR DESCRIPTION
**Pull request by gibson042**
...with minimal dependencies
Fixes #5878

## Description

By liberal use of `awk` (which is required in any POSIX implementation), dependencies have been reduced to hopefully-noncontroversial `curl` and `base64`.

```sh
$ scripts/get-flattened-publication.sh https://xnet.rpc.agoric.net/ published.amm.pool0.metrics | \
  jq .
{
  "blockHeight": "513450",
  "centralAmount-brand-id": "board0425",
  "centralAmount-brand-allegedName": "RUN",
  "centralAmount-value": "202019830953",
  "liquidityTokens-brand-id": "board0188",
  "liquidityTokens-brand-allegedName": "IbcATOMLiquidity",
  "liquidityTokens-value": "202503724998",
  "secondaryAmount-brand-id": "board0639",
  "secondaryAmount-brand-allegedName": "IbcATOM",
  "secondaryAmount-value": "101498052"
}
```

It's also possible to use with e.g. `agd`, at the cost of block height information.

```sh
$ agd --node=https://xnet.rpc.agoric.net:443 query vstorage data published.amm.pool0.metrics -o json | \
  scripts/flatten_json_sequence.awk -v unwrap=value -v capdata=true | \
  jq .
{
  "centralAmount-brand-id": "board0425",
  "centralAmount-brand-allegedName": "RUN",
  "centralAmount-value": "202019830953",
  "liquidityTokens-brand-id": "board0188",
  "liquidityTokens-brand-allegedName": "IbcATOMLiquidity",
  "liquidityTokens-value": "202503724998",
  "secondaryAmount-brand-id": "board0639",
  "secondaryAmount-brand-allegedName": "IbcATOM",
  "secondaryAmount-value": "101498052"
}
```

### Security Considerations

No one should object to _using_ the code, since it is so narrowly-scoped in both power and effects. However, _auditing_ it is likely more difficult than would be the case if it were written in a more common language such as JS or Go (which could be done).

I'm also not sure if this code belongs in [agoric-sdk](https://github.com/Agoric/agoric-sdk) or another repository such as [dckc/ag-admin](https://github.com/dckc/ag-admin).

### Documentation Considerations

I have tried to include sufficient examples in source code comments.

### Testing Considerations

The input data is by nature a moving target, so I think it makes sense to skip tests at least until we have adopted another publication approach (cf. #5681, #5508, #5366).

### CODE REVIEW

**Review by dckc — COMMENTED** [review]
> minimal dependencies

no kidding! An implementation of JSON in AWK. That's... hard core.

OTOH, as you say, reviewing it is kind of a pain. At least one of our customers is happy with python. I'd be OK reviewing python.

As is, I'll just say I have no objections but leave approval to @arirubinstein .

File: scripts/get-flattened-publication.sh [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+#         "key": null,
+#         "value": "<base64-encoded JSON text>",
+#         "proofOps": null,
+#         "height": "<decimal digits>",
+#         "codespace": ""
+#       }
+#     }
+#   }
+vars="$(
+  curl -sS "${URL_PREFIX%/}/abci_query?path=%22/custom/vstorage/data/$STORAGE_KEY%22" | \
```
Comment (gibson042) [inline scripts/get-flattened-publication.sh]: Incidentally, this is probably a bug somewhere in Cosmos/Tendermint. Their [documentation](https://docs.tendermint.com/master/rpc/#/ABCI/abci_query) gives example values of `path` like `/a/b/c`, but making a query with `?path=/a/b/c` yields a response like
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32602,
    "message": "Invalid params",
    "data": "error converting http params to arguments: invalid character '/' looking for beginning of value"
  }
}
```
Something is apparently JSON-decoding the parameter value rather than using it directly.

Comment (gibson042) [reply scripts/get-flattened-publication.sh]: Specifically https://github.com/tendermint/tendermint/blob/75d51e18f740c7cbfb7d8b4d49182ee6c7f41982/rpc/jsonrpc/server/http_uri_handler.go#L42-L51 , but I can't really get to the bottom of the reflection-heavy `nonJSONStringToArg` in `httpParamsToArgs`.

**Comment by turadg** [comment]
> By liberal use of awk (which is required in any POSIX implementation), dependencies have been reduced to hopefully-noncontroversial curl and base64.

Was the use of https://stedolan.github.io/jq/ controversial? 

I see the ticket requirement,
> The utility should be written such that adopting it does not risk a significant increase to potentially vulnerable surface area (e.g. by installing a complex executable).

I take that to mean that the executable we're giving them isn't complex. `jq` is included in most distributions so what we'd be providing would be much simpler using that than this awk script.

**Comment by gibson042** [comment]
I don't think `jq` was _inherently_ controversial, but there was definitely consternation about the complexity of requiring expressions like the following as seen on Slack from @dckc (and which would only get more complicated to incorporate block height and/or data from `slots`):
```
.value | fromjson | .body | fromjson | {
  centralAmount: .centralAmount | { brand: .brand.iface, value: .value.digits | tonumber | (. / 1000000 ) },
  secondaryAmount: .secondaryAmount | { brand: .brand.iface, value: .value.digits | tonumber | (. / 1000000 ) },
  liquidityTokens: .liquidityTokens | { brand: .brand.iface, value: .value.digits | tonumber | (. / 1000000 ) }
}
```

**Comment by turadg** [comment]
> complexity of requiring expressions like the following

Maybe we're talking about different complexity. If that jq syntax were put into a `flatten_json_sequence.jq` then the end user complexity would be the same (modulo having to perhaps `apt-get jq`).

The stark difference is within `flatten_json_sequence` file. The the AWK is _much_ harder to follow than any JQ and it could have errors in its JSON parsing.

File: scripts/get-flattened-publication.sh (hunk 1 above)
Comment (gibson042) [reply scripts/get-flattened-publication.sh]: Opened https://github.com/tendermint/tendermint/issues/9164

Comment (arirubinstein) [reply scripts/get-flattened-publication.sh]: urlencode?

Comment (gibson042) [reply scripts/get-flattened-publication.sh]: No, I get the same results with `%22` vs. `"`. I even replaced an `a` with `\u0061` (which is a JSON escape sequence) in the quote-wrapped version and it still worked.

File: scripts/get-flattened-publication.sh [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+      }
+    }
+  '
+)"
+eval "$vars"
+
+# Decode the value into flat JSON and insert a member for the block height.
+printf '%s' "${value_base64:-}" | \
+  base64 -d | \
+  awk -f "$FLATTENER" -v unwrap=value -v capdata=true | \
```
Comment (gibson042) [inline scripts/get-flattened-publication.sh]: For the record, if `jq` is acceptable then this most complex use of `awk` (unwrap, expand capdata, and then flatten) can be replaced with the following:
```suggestion
  jq '[
    # Decode JSON in `value`, capture `slots`, then decode JSON in `body`.
    .value | fromjson | .slots as $slots | .body | fromjson |
    walk(
      if type=="object" and .["@qclass"]=="bigint" then
        # Replace bigint capdata with the sequence of digits.
        .digits
      elif type=="object" and .["@qclass"]=="slot" then
        # Replace slot reference capdata with {
        #   id: <value from global `slots`>,
        #   allegedName: <extracted from local `iface`>,
        # }.
        {
          id: $slots[.index],
          allegedName: .iface | sub("^Alleged: (?<name>.*) brand$"; "\(.name)"; "m")
        }
      else
        .
      end
    ) |
    paths(scalars) as $path |
    # Join deep object member names with "-".
    { key: $path | join("-"), value: getpath($path) } 
  ] | from_entries'
```

Comment (turadg) [reply scripts/get-flattened-publication.sh]: I'd approve that ;-)

> if jq is acceptable

I believe it is but I defer to @arirubinstein who I think represents the customer of this script

File: scripts/get-flattened-publication.sh [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+    "params": { "path": "/custom/vstorage/data/%s" }
+  }' "$STORAGE_KEY"
+)" | \
+# Decode, simplify, flatten, and compact the output.
+jq -c '
+  # Capture block height.
+  .result.response.height? as $height |
+
+  # Decode `value` as base64, then decode that as JSON.
+  .result.response.value | @base64d | fromjson |
```
Comment (gibson042) [inline scripts/get-flattened-publication.sh:67]: Today I learned that `jq` can encode/decode base64: https://stedolan.github.io/jq/manual/#Formatstringsandescaping

**Review by gibson042 — COMMENTED** [review]
@arirubinstein @dckc @turadg Replaced the awk with jq. PTAAL.

File: scripts/get-flattened-publication.sh [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+       e.g. \"https://xnet.rpc.agoric.net/\".
+  STORAGE_KEY is a chain storage key name, e.g. \"published.amm.pool0.metrics\".
+";
+
+URL_PREFIX="${1:-}";
+STORAGE_KEY="${2:-}";
+
+if [ ":${1:-}" = '--help' -o ":$URL_PREFIX" = : -o ":$STORAGE_KEY" = : -o $# -gt 2 ]; then
+  printf '%s' "$USAGE"
+  exit 64
```
Comment (turadg) [inline scripts/get-flattened-publication.sh:17]: TIL!

File: scripts/get-flattened-publication.sh [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+fi
+
+# Verify jq version.
+jq --version | awk '
```
Comment (turadg) [inline scripts/get-flattened-publication.sh:21]: I'm more familiar with version checking by grep and having the condition in shell code. nbd.

File: scripts/get-flattened-publication.sh [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+  /^jq-1[.]([6-9]|[1-9][0-9])/ {
+    exit;
+  }
+  {
+    print "jq version out of range (must be >=1.6 <2.0): " $0 > "/dev/stderr";
```
Comment (turadg) [inline scripts/get-flattened-publication.sh]: just curious, what's required in 1.6?

File: scripts/get-flattened-publication.sh [hunk 7]
```diff
@@ -0,0 +1,92 @@
...
+#       "response": {
+#         "value": "<base64-encoded JSON text>",
+#         "height": "<decimal digits>",
+#         ...
+#       }
+#     }
+#   }
+
+# Avoid the GET interface in case interpretation of `path` as JSON is ever fixed.
+# https://github.com/tendermint/tendermint/issues/9164
```
Comment (turadg) [inline scripts/get-flattened-publication.sh:51]: helpful 👍

**Review by turadg — APPROVED** [review]
> The input data is by nature a moving target, so I think it makes sense to skip tests at least until we have adopted another publication approach

Fair. I trust you've tested it with the status quo and that you'll remember to retest when the source data changes.

> not sure if this code belongs in [agoric-sdk](https://github.com/Agoric/agoric-sdk) or another repository such as [dckc/ag-admin](https://github.com/dckc/ag-admin).

Good question. I think it's fine to include here in this misc script directory. It will also help keep the version in sync with producer logic.

**Review by arirubinstein — APPROVED** [review]

File: scripts/get-flattened-publication.sh (hunk 6 above)
Comment (gibson042) [reply scripts/get-flattened-publication.sh]: `@base64d`, `walk`, and `getpath`.
