### PR TITLE
8606 invite proposals

### LINKED ISSUE #8606: Zoe should have a test of proposalShape.
## What is the Problem Being Solved?

There's [no existing test](https://github.com/Agoric/agoric-sdk/pull/8597/files#r1413218121) of `proposalShape` in `makeInvitation`.

## Description of the Design

Write a test. Create a trivial test contract if there's no better place to put it.

## Security Considerations

API regression testing is relevant.

## Scaling Considerations

None.

## Test Plan

https://github.com/Agoric/agoric-sdk/pull/8597#discussion_r1414433566
> * `E(zoe).offer(invitation, badProposal, payments)` still creates a seat.
> * `getOfferResult()` on that seat throws an error complaining about the proposal.
> * The seat's payouts match its payments.

## Upgrade Considerations

None

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #8606
closes: #8597

## Description

#8597 suggested adding a test proposal guards in Zoe. This adds that test, and also cleans up a redundant check in coveredCall. The added test exposed a mistake in the Zoe doc, so [1258](https://github.com/Agoric/documentation/pull/1258) fixes that as well.

### Security Considerations

None

### Scaling Considerations

None.

### Documentation Considerations

Improved documentation.

### Testing Considerations

Added tests.

### Upgrade Considerations

These changes do not impact code on-chain. There's a correction to an example contract, an improvement in a TypeGuard, and a documentation update which will be separately release.

### CODE REVIEW

File: packages/zoe/src/typeGuards.js [hunk 1]
```diff
@@ -367,7 +367,7 @@ export const ZoeServiceI = M.interface('ZoeService', {
   }),
   getInvitationDetails: M.call(M.eref(InvitationShape)).returns(M.any()),
   getProposalShapeForInvitation: M.call(InvitationHandleShape).returns(
-    M.opt(ProposalShape),
+    M.opt(M.pattern()),
```
Comment (turadg) [inline packages/zoe/src/typeGuards.js:370]: why does `getProposalShapeForInvitation` return values other than a ProposalShape?

Is `ProposalShape` wrong?

I notice that `getProposalShapeForInvitation` typedef returns `Pattern | undefined` but some places then require that it be narrower than Pattern:
https://github.com/Agoric/agoric-sdk/blob/322023f3ee84793aa6886316d30d3ba098009dd9/packages/zoe/src/zoeService/offer/offer.js#L45-L50

Comment (Chris-Hibbert) [reply packages/zoe/src/typeGuards.js:370]: Different meta-levels: `proposalShape` is the type for something that is shaped like a proposal. `E(zoe).offer(invitation, proposal)` takes a proposal, and its guard requires that it match `proposalShape`.
```
  const proposal = harden({
    give: { B: moola(5n) },
    exit: { onDemand: null },
  });
  E(zoe).offer(invitation, proposal, { B: fiveMoola });
```

The object returned by `getProposalShapeForInvitation(invitationHandle)` _describes_ a proposal. It's a `pattern`.

```
  const proposalShape = M.splitRecord({
    give: { B: AmountShape },
    exit: { deadline: M.any() },
  });
  const invitation = await zcf.makeInvitation(
    boring,
    'seat1',
    {},
    proposalShape,
  );
  const { handle } = await E(zoe).getInvitationDetails(invitation);
  const shape = await E(zoe).getProposalShapeForInvitation(handle);
  t.deepEqual(shape, proposalShape);
```

It's arguable whether `getProposalShapeForInvitation` should return a `ProposalShapePattern`, but I don't think it's possible to customize `M.pattern()`.

Comment (turadg) [reply packages/zoe/src/typeGuards.js:370]: Thanks for explaining. I agree `Pattern` is the right type but I request that `getProposalShapeForInvitation` get a jsdoc explaining its return type. A good time also to inline `GetProposalShapeForInvitation`

Comment (Chris-Hibbert) [reply packages/zoe/src/typeGuards.js:370]: done

**Review by turadg — APPROVED** [review]
