### PR TITLE
retry install-bundle in multichain test

### LINKED ISSUE #9934: sequence mismatch flake in multichain-testing
## What is the Problem Being Solved?

```
  Error: rewards available on osmosis condition failed after 8 retries.
    at retryUntilCondition (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/tools/sleep.ts:28:11)
    at async file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/test/stake-ica.test.ts:99:23
```

instances
- https://github.com/Agoric/agoric-sdk/actions/runs/10482566227/job/29033890661?pr=9395
- https://github.com/Agoric/agoric-sdk/actions/runs/10533760653/job/29190278931?pr=9953

### PR DESCRIPTION
**Pull request by turadg**
closes: #9934

## Description

The **Fund Provision Pool** job is stable now, so the next one is flaking, **Override Chain Registry**.

```
----- Depl.5  5 installing bundles
----- Agd.3  2 $ agd tx swingset install-bundle @/tmp/contracts/b1-1fc262aefef4f13a10b2b116e07e4c8539619479f01fe6bd03fae243d2765c88b86054f15331c6d3c94c424d65a9fb0a3e8684d20ee4d31c6c9b705d6053e3c8.json --keyring-backend test --chain-id agoriclocal --from agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw --broadcast-mode block --gas auto --gas-adjustment 1.4 --yes --output json
deploy failed, trying again (Error#1)
Error#1: Command failed: kubectl exec -i agoriclocal-genesis-0 -c validator --tty=false -- agd tx swingset install-bundle @/tmp/contracts/b1-1fc262aefef4f13a10b2b116e07e4c8539619479f01fe6bd03fae243d2765c88b86054f15331c6d3c94c[42](https://github.com/Agoric/agoric-sdk/actions/runs/13998860883/job/39200487363#step:12:43)4d65a9fb0a3e8684d20ee4d31c6c9b705d6053e3c8.json --keyring-backend test --chain-id agoriclocal --from agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw --broadcast-mode block --gas auto --gas-adjustment 1.4 --yes --output json
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = account sequence mismatch, expected 24, got 23: incorrect account sequence [agoric-labs/cosmos-sdk@v0.46.16-alpha.agoric.2.5/x/auth/ante/sigverify.go:269] With gas wanted: '18446744073709551615' and gas used: '1840763' : unknown request
```
It had a retry but wasn't waiting a block. This makes it wait a block.

### Security Considerations
It uses a global `fetch`. This is running in a Node env and just test code so I think it's warranted.

### Scaling Considerations
none

### Documentation Considerations
none

### Testing Considerations
If it passes, land it and hope it fixes the flake.

### Upgrade Considerations
n/a

### CODE REVIEW

File: multichain-testing/tools/e2e-tools.js [hunk 1]
```diff
@@ -106,20 +105,34 @@ export const makeBlockTool = ({ rpc, delay }) => {
...
+      yes: true,
+    });
+  let tx;
+  try {
+    tx = await installBundle();
+  } catch (err) {
+    console.warn('WARN: retrying failed install-bundle', err);
+    // TODO make available from client-utils
+    const { waitForBlock } = makeBlockTool({
+      rpc: makeHttpClient(rpcUrl, global.fetch),
```
Comment (dckc) [inline multichain-testing/tools/e2e-tools.js:130]:
```suggestion
      rpc: makeHttpClient(rpcUrl, globalThis.fetch),
```

> Stability: 3 - Legacy. Use globalThis instead.
 -- https://nodejs.org/api/globals.html#global

Comment (dckc) [reply multichain-testing/tools/e2e-tools.js:130]: Given that several other IO capabilities are injected as `opts`, it seems inconsistent to use a global `fetch`.

But... anything that works is better than this flake.

**Review by dckc — APPROVED** [review]
worth a try

File: multichain-testing/tools/e2e-tools.js [hunk 2]
```diff
@@ -106,20 +105,34 @@ export const makeBlockTool = ({ rpc, delay }) => {
...
+  const installBundle = () =>
+    agd.tx(['swingset', 'install-bundle', `@${fullPath}`], {
+      from,
+      chainId,
+      yes: true,
+    });
+  let tx;
+  try {
+    tx = await installBundle();
+  } catch (err) {
```
Comment (0xpatrickdev) [inline multichain-testing/tools/e2e-tools.js:126]: Nice, did you consider implementing this logic in `agd.tx` instead? The immediate concern is that this change works, but then `runCoreEval` starts to flake.

We could specifically look for "incorrect account sequence", taking a page from the inter oracle and ocw implementation: https://github.com/SimplyStaking/agoric-ocw/blob/9b1937cea0e573c9488389d48738614419f5a148/src/submitter.ts#L108

Comment (turadg) [reply multichain-testing/tools/e2e-tools.js:126]: Good point. I didn't want to put retry logic that low but it didn't occur to me to simply bump the sequence number. I'll work on that now but put that idea into the ticket if this recurs.
