### PR TITLE
preparations for forward retry

### LINKED ISSUE #10449: `CosmosOrchestrationAccount`'s `amountToCoin` returns incorrect `denom` when presented a `Brand`
## Describe the bug

`CosmosOrchestrationAccount`'s `amountToCoin` / `coerceCoin` / `coerceDenom` helpers do not account for issuing/host chain logic. 

Example:
```js
// actual
helper.amountToCoin(ISTbrand) => ({ denom: 'uist', amount: 1n })

// expected
helper.amountToCoin(ISTbrand, holdingChain) => ({ denom: 'ibc/uisthash', amount: 1n })
```

Most tests use `DenomArg` instead of `AmountArg`, as we are waiting on #9752, #9966, #9967, so this path wasn't well trodden.

## To Reproduce

`/packages/orchestration/test/exos/cosmos-orchestration-account.test.ts` has a test that mentions this

## Expected behavior
The helper should return the denom from the perspective of the holding chain. IOW, the host chain for the ICA.

### PR DESCRIPTION
**Pull request by turadg**
refs: https://github.com/Agoric/agoric-private/issues/311

## Description

A bunch of commits from https://github.com/Agoric/agoric-sdk/pull/11302 that are ready to merge.

~Most are refactorings but one is impactful and claims to close https://github.com/Agoric/agoric-sdk/issues/10449~

Review by commit recommended

### Security Considerations

~Relies on ChainHub to resolve a non-forgeable Brand object into a DenomAmount.~

### Scaling Considerations
no changes

### Documentation Considerations
no impact

### Testing Considerations
CI

### Upgrade Considerations
no compatibility issues

### CODE REVIEW

File: packages/vats/src/vat-bank.js [hunk 1]
```diff
@@ -26,6 +26,7 @@ import {
  * @import {Guarded} from '@endo/exo';
  * @import {RemotableObject} from '@endo/pass-style';
  * @import {BridgeMessage, BridgeBigInt} from '@agoric/cosmic-swingset/src/types.js';
+ * @import {VirtualPurse} from './virtual-purse.js';
```
Comment (dckc) [inline packages/vats/src/vat-bank.js:29]: note: no runtime changes to vat-bank; no upgrade considerations

File: packages/orchestration/src/utils/chain-hub-helper.js [hunk 2]
```diff
@@ -13,14 +13,17 @@
  * @param {Record<string, Brand<'nat'>>} brands
  * @param {Record<string, ChainInfo> | undefined} chainInfo
  * @param {[Denom, DenomDetail & { brandKey?: string }][] | undefined} assetInfo
+ * @param {object} opts
+ * @param {Console['log']} [opts.log]
```
Comment (dckc) [inline packages/orchestration/src/utils/chain-hub-helper.js:17]: :clap:

File: packages/fast-usdc-contract/test/supports.ts [hunk 3]
```diff
@@ -183,28 +189,71 @@ export const commonSetup = async (t: ExecutionContext<any>) => {
...
+   * Tracks `sequence` locally in test context, so this helper must be used
+   * for all simulated VTransfer calls in a test run for sequence to be
+   * accurate.
+   *
+   * @example
+   * ```js
+   * // send ack
+   * await transmitVTransferEvent('acknowledgementPacket');
+   * // send ack error
+   * await transmitVTransferEvent('acknowledgementPacket', 'packet-forward-middleware error: giving up on packet on channel (channel-21) port (transfer) after max retries');
```
Comment (dckc) [inline packages/fast-usdc-contract/test/supports.ts:210]: good to note that errors can come in ack packets

File: packages/fast-usdc-contract/test/forwarding.test.ts [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+  t.is(forwardInfo.receiver, EUD, 'receiver is osmo10tt0');
+
+  // in lieu of transmitTransferAck so we can set a nonce that matches our initial Advance
+  await E(transferBridge).fromBridge(
+    buildVTransferEvent({
+      receiver: outgoingForwardMessage.receiver,
+      sender: outgoingForwardMessage.sender,
+      target: outgoingForwardMessage.sender,
+      sourceChannel: outgoingForwardMessage.sourceChannel,
+      sequence: BigInt(Number(evidence.txHash.slice(2))),
```
Comment (dckc) [inline packages/fast-usdc-contract/test/forwarding.test.ts:105]: how the sequence number got into `txHash` could be more clear.
not important

**Review by dckc — APPROVED** [review]
LGTM
