### PR TITLE
Move transcripts out of key-value store and into stream stores

### LINKED ISSUE #3065: store transcripts in linear auxillary file, not LMDB
## What is the Problem Being Solved?

Vat transcripts have a very different access pattern than normal kernelDB contents (like c-lists and object/promise tables). During normal runtime, the transcripts are append-only. We only read from then at startup, when the kernel needs to rebuild the vat (and/or, when #2277 is done, it may happen on-demand instead of strictly at kernel startup).

For everything else, the kernel reads and writes the data constantly, with basically random access patterns.

We're using LMDB for everything, and we map both kinds of data into the key-value store it provides. Transcripts are represented as keys like `v$VATID.t.$NN`, and the values are a JSON encoding of the transcript entry (`VatDeliveryObject` plus all the syscalls and their return values).

We might be able to make things more efficient by moving the transcript entries out to some other kind of storage. Simply appending lines of JSON to a file (one file per vat) might work.

The main constraint is that we must maintain the transactionality boundaries. If we add something to a file, but then crash (or abandon the crank) before we've decided to commit, we must make sure a restart does not execute the uncommitted transcript entry. The nice thing about using LMDB for everything is the single commit point for both the new transcript entry and all the other kernelDB changes that happen at the same time. If we split into separate files, we need a mechanism to correctly link/correlate/commit the multiple pieces.

Once approach might be to include the length of the transcript file as an LMDB key. When starting up, the kernel (or more precisely the swingstore implementation) would simply truncate the file to the committed length. When adding a transcript entry, the swingstore would append the line, measure the length (just `ftell()`), then update a kernelDB key with the new length. If we commit the crank, that key is commited, and if we crash, it does not. We might need more code to handle a non-crashing/exiting rollback: maybe each time we want to append an entry, we first read the kernelDB key and `fseek()` to that location.

The other thing to remember is the dual uses of the transcript. For the local purpose of restarting a vat (which might happen every few minutes, if the #2277 Vat Warehouse decides that's the most memory-vs-CPU efficient thing to do), we only need the transcript entries that follow the last heap snapshot. We're effectively truncating the transcript each time we make a snapshot. However, we don't expect to include snapshots (and therefore not truncation either) in the consensus. So for the purpose of hashing the vat state into the consensus, and also for migration or upgrade, we must retain the entire transcript.

Perhaps the best approach is:

* the SwingStore API is enhanced to provide separate per-vat transcript access: `add`, `truncate`, `iterAll`, `iterTruncated`
* `add` writes transcript entries to a file, using the `fseek`/`ftell` approach described above
* it maintains a separate key to remember the size of the file, and commits it as described above
* it uses a second key to remember the starting point: `truncate` increments this offset, `iterTruncated` does an `fseek()` to that point before parsing lines of JSON from the file
  * this key is *not* included in the consensus state, although it must still be committed locally along crank/block boundaries as usual
  * if/when we split LMDB into consensus-included and consensus-excluded portions, this goes into the excluded part
* `iterAll` starts from offset 0

Of course, we need to measure what the performance benefit of this would actually be. If LMDB is efficient enough, it's a lot simpler to just write everything into a single DB. But if we're concerned about preserving its access speed for data that is actually used all the time, it could make sense to move the always-growing never-read-at-runtime data elsewhere.

cc @FUDCo @dckc

### PR DESCRIPTION
**Pull request by FUDCo**
These changes actually realize the goal of ceasing to store vat transcripts in the kernel LMDB database, instead streaming them to files outside the database, all managed by the new SwingStore streamStore abstraction.

Closes #3065

### CODE REVIEW

File: packages/swingset-runner/.gitignore [hunk 1]
```diff
@@ -1,4 +1,5 @@
 # swingset persistence data
+swingset-kernel-state
```
Comment (warner) [inline packages/swingset-runner/.gitignore]: maybe remove this?

File: packages/SwingSet/test/test-transcript.js [hunk 2]
```diff
@@ -12,11 +12,11 @@ async function buildTrace(c, storage) {
   // XXX TODO also copy transcript
```
Comment (warner) [inline packages/SwingSet/test/test-transcript.js]: The new `getAllState` includes the full transcript, right? (In fact the old `getAllState` probably did too, just embedded in the kvStore rather than as a separate piece). If so, would it be safe to remove this TODO comment?

File: packages/SwingSet/test/test-transcript-light.js [hunk 3]
```diff
@@ -13,95 +13,91 @@ test('transcript-light load', async t => {
...
-  const state5 = getAllState(kvStore);
+  const state5 = getAllState(hostStorage);
 
   // build from loaded state
   // Step 0
 
   const cfg0 = await loadBasedir(path.resolve(__dirname, 'basedir-transcript'));
   const hostStorage0 = provideHostStorage();
-  const kvStore0 = hostStorage0.kvStore;
   // XXX TODO copy transcripts
```
Comment (warner) [inline packages/SwingSet/test/test-transcript-light.js]: same here

**Review by warner — APPROVED** [review]
wow, that was pretty straightforward. nice!

File: packages/SwingSet/bin/extract-transcript-from-kerneldb.js [hunk 4]
```diff
@@ -1,3 +1,5 @@
+// XXX this is wrong; it needs to use the swingstore instead of opening the LMDB
+// file directly, then use stream store reads to get the transcript entries.
```
[the remark this answers is not in the document]
Comment (warner) [reply packages/SwingSet/bin/extract-transcript-from-kerneldb.js:2]: ticket-to-self in #3206

[the remark this answers is not in the document]
Comment (FUDCo) [reply packages/SwingSet/bin/extract-transcript-from-kerneldb.js:2]: Anecdotally, I've got several other tools that need to run in the SES environment (usually because they use swingstore!) and debugging hasn't been particularly problematic (at least, no more so that it ever is).

File: packages/swingset-runner/.gitignore (hunk 1 above)
Comment (FUDCo) [reply packages/swingset-runner/.gitignore]: `.gitignore` already ignores `.mdb` files, but the presence of transcript files make git think the store directories need to be added.  I suppose we could add a filename extension to the transcript files (which, I suppose, you might make a case we should do anyway) and tell git to ignore **those**, but _something_ will have to go in `.gitignore` or I end up with an 50 extra lines of crap in the output every time I do a `git status`.

File: packages/SwingSet/test/test-transcript.js (hunk 2 above)
Comment (FUDCo) [reply packages/SwingSet/test/test-transcript.js]: Yup.  Will do.

File: packages/swingset-runner/.gitignore (hunk 1 above)
Comment (FUDCo) [reply packages/swingset-runner/.gitignore]: All the unit tests either use the in-memory version of the store or clean up after themselves, but swingset-runner demos leave their databases around for inspection or replay.  I think I'm leaning towards giving the stream files their own file name extension so they can be ignored specifically.  That way if any _other_ stuff gets put (perhaps inadvertently) in a `swingset-kernel-state` directory it will be flagged by `git status`.
