### PR TITLE
fix(swing-store): Update archiveTranscript to wait for write stream conclusion

### LINKED ISSUE #11293: Error in `execSlowTranscriptDeletion`
## Describe the bug
From CI: https://github.com/Agoric/agoric-sdk/actions/runs/14518731707/job/40734385433?pr=11289#step:16:26
```
Run cd packages/swing-store && yarn test | $TEST_COLLECT
yarn run v1.22.22
$ ava
TAP version 13
ok 1 - bundles › b0 format %ava-dur=37ms
ok 2 - bundles › unknown format %ava-dur=7ms
ok 3 - bundles › b0 import %ava-dur=20ms
ok 4 - bundles › b0 bad import %ava-dur=17ms
ok 5 - bundles › b0 export %ava-dur=36ms
ok 6 - deletion › delete transcripts with export callback %ava-dur=69ms
ok 7 - deletion › delete snapshots with export callback %ava-dur=104ms
ok 8 - deletion › slow deletion of snapshots %ava-dur=87ms
ok 9 - deletion › slow deletion without stopUsingLastSnapshot %ava-dur=92ms
ok 10 - deletion › full deletion without stopUsingLastSnapshot %ava-dur=90ms
ok [11](https://github.com/Agoric/agoric-sdk/actions/runs/14518731707/job/40734385433?pr=11289#step:16:12) - deletion › slow deletion without stopUsingTranscript %ava-dur=181ms
ok [12](https://github.com/Agoric/agoric-sdk/actions/runs/14518731707/job/40734385433?pr=11289#step:16:13) - deletion › full deletion without stopUsingTranscript %ava-dur=177ms
not ok [13](https://github.com/Agoric/agoric-sdk/actions/runs/14518731707/job/40734385433?pr=11289#step:16:14) - deletion › slow deletion of transcripts with retention %ava-dur=2[14](https://github.com/Agoric/agoric-sdk/actions/runs/14518731707/job/40734385433?pr=11289#step:16:15)ms
  ---
    name: AssertionError
    message: Rejected promise returned by test
    values:
      'Rejected promise returned by test. Reason:': |-
        Error ***
          code: 'Z_BUF_ERROR',
          errno: -5,
          message: 'unexpected end of file',
        ***
    at: 'execSlowTranscriptDeletion (file://test/deletion.test.js:332:27)'
```
The [failing line](https://github.com/Agoric/agoric-sdk/blob/84adeefc52a0cf475a0dae8723ddd7b4fe54d483/packages/swing-store/test/deletion.test.js#L332) is doing `zlib.gunzipSync(fs.readFileSync(filePath))`, in which `filePath` was created by [`archiveTranscript`](https://github.com/Agoric/agoric-sdk/blob/84adeefc52a0cf475a0dae8723ddd7b4fe54d483/packages/swing-store/src/archiver.js#L55).

### PR DESCRIPTION
**Pull request by gibson042**
closes: #11293

## Description
`archiveTranscript` creates a WriteStream `writer` and a gzip stream `gzip`, connects them by `gzip.pipe(writer)`, and then waits for `streamFinished(gzip)` before returning. But `writer` can still have pending activity even after `gzip` finished, which seems to be the root cause of #11293.

This PR updates `archiveTranscript` to instead wait for conclusion of _`writer`_, currently by ~~listening for error/finish/close events (but I'm open to alternatives that also accomplish the same goal)~~ <code>await <a href="https://nodejs.org/docs/latest/api/stream.html#streampipelinesource-transforms-destination-options">pipeline</a>(source, createGzip(), writer);</code>.

### Security Considerations
n/a

### Scaling Considerations
n/a

### Documentation Considerations
n/a

### Testing Considerations
This is fixing racy behavior, and thus impractical to test specifically. We'll instead rely on the existing coverage that alerted us to begin with.

### Upgrade Considerations
n/a

### CODE REVIEW

**Comment by mhofman** [comment]
> (but I'm open to alternatives that also accomplish the same goal).

I'm only aware of the [`pipeline`](https://nodejs.org/docs/latest/api/stream.html#streampipelinesource-transforms-destination-options) and [`finished`](https://nodejs.org/docs/latest/api/stream.html#streamfinishedstream-options) node streams helpers.

File: packages/swing-store/src/archiver.js [hunk 1]
```diff
@@ -67,13 +68,15 @@ export const makeArchiveTranscript = (dirPath, powers) => {
...
+      const { promise: doneP, resolve, reject } = makePromiseKit();
+      writer.on('error', reject).on('finish', resolve).on('close', resolve);
       const gzip = createGzip();
       gzip.pipe(writer);
       const reader = Readable.from(entries);
       const destroyReader = promisify(reader.destroy.bind(reader));
       addCleanup(() => destroyReader(null));
       reader.pipe(gzip);
-      await streamFinished(gzip);
+      await doneP;
```
Comment (mhofman) [inline packages/swing-store/src/archiver.js]: Why can't we do `streamFinished(writer)` ?

Comment (gibson042) [reply packages/swing-store/src/archiver.js]: I don't know. I tried that in a reduced test case and it threw "Premature close".

Comment (gibson042) [reply packages/swing-store/src/archiver.js]: But `await pipeline(reader, createGzip(), fs.createWriteStream(…));` seems to work. Should we switch to that?

Comment (mhofman) [reply packages/swing-store/src/archiver.js]: Yeah we probably should have done that from the beginning. I think in that case we don't need the destroy reader part, nor the explicit `Readable.from` since it takes an `Iterable` as source.

Comment (gibson042) [reply packages/swing-store/src/archiver.js]: Done.

File: packages/swing-store/package.json [hunk 2]
```diff
@@ -21,12 +21,13 @@
...
   },
   "dependencies": {
-    "@endo/errors": "^1.2.10",
     "@agoric/internal": "^0.3.2",
     "@endo/base64": "^1.0.9",
     "@endo/bundle-source": "^4.0.0",
     "@endo/check-bundle": "^1.0.14",
+    "@endo/errors": "^1.2.10",
     "@endo/nat": "^5.1.0",
+    "@endo/promise-kit": "^1.1.10",
```
Comment (mhofman) [inline packages/swing-store/package.json]: Not: dep no longer needed

**Review by mhofman — APPROVED** [review]
Yay for cleaner abstrations
