### PR TITLE
fix(xsnap): format objects nicely in console using SES assert.quote

### LINKED ISSUE #3844: [object Object] obscure form in xsnap console
## Describe the bug

In un-redacted console messages, our [xsnap console shim](https://github.com/Agoric/agoric-sdk/blob/master/packages/xsnap/lib/console-shim.js) prints `[object Object]` where we're used to more detail from the node.js console.

```
Error#4: Withdrawal of [object Object] failed because the purse only contained [object Object]
```

## To Reproduce

for example: https://github.com/Agoric/testnet-load-generator/issues/30

## Expected behavior

something more like [inspect](https://nodejs.org/api/util.html#util_util_inspect_object_options).

or perhaps `assert.quote` from SES?

## Platform Environment
 - what version of the Agoric-SDK are you using? d48e6a7

## Additional context

originally discussed in https://github.com/Agoric/testnet-load-generator/issues/30

cc @kriskowal @katelynsills @mhofman

### PR DESCRIPTION
**Pull request by dckc**
fixes #3844

A couple things are a little awkward but seem cost-effective:
 - This uses `setQuote()` to break the cycle where SES requires `console` and `console` is implemented using `assert.quote` from SES.
 - for testing I added a global to capture args from console methods via `print()`.

### CODE REVIEW

File: packages/xsnap/lib/console-shim.js [hunk 1]
```diff
@@ -1,16 +1,13 @@
 /* global globalThis */
+
+// We use setQuote() below to break the cycle
+// where SES requires console and console is
+// implemented using assert.quote from SES.
+let quote = v => (typeof v === 'string' ? v : '[?]');
```
Comment (kriskowal) [inline packages/xsnap/lib/console-shim.js]: With the guard below, this can probably reduce to `v => '[?]'`.

File: packages/xsnap/lib/console-shim.js [hunk 2]
```diff
@@ -1,16 +1,13 @@
...
-  } catch (err) {
-    // eslint-disable-next-line
-    print('cannot print:', err.message);
-    args.forEach((a, i) => {
-      // eslint-disable-next-line
-      print(` ${i}:`, a.toString ? a.toString() : '<no .toString>', typeof a);
-    });
-  }
+  // eslint-disable-next-line
+  print(...args.map(v => typeof v === 'string' ? v : quote(v)));
```
Comment (kriskowal) [inline packages/xsnap/lib/console-shim.js]: The Node.js console joins console arguments with a single space `' '`.

**Review by kriskowal — APPROVED** [review]
🙏

File: packages/xsnap/lib/console-shim.js (hunk 1 above)
Comment (dckc) [reply packages/xsnap/lib/console-shim.js]: That's the way it was originally, but during debugging everything was coming out as `[?]`, which was annoying.

I suppose now that those bugs are fixed, this can be simplified.

File: packages/xsnap/lib/console-shim.js (hunk 2 above)
Comment (dckc) [reply packages/xsnap/lib/console-shim.js]: so does XS print: ``await worker.evaluate(`print('sep?', 1, 2, 3);`);`` prints
```
sep? 1 2 3
```

File: packages/xsnap/lib/console-shim.js (hunk 1 above)
Comment (kriskowal) [reply packages/xsnap/lib/console-shim.js]: Don’t trouble for it! Debugging without a call to setQuote is a good reason to leave it as-is. I have been thinking a lot lately about how code lies on the spectrum from flexible to strong.

File: packages/xsnap/lib/console-shim.js (hunk 2 above)
Comment (kriskowal) [reply packages/xsnap/lib/console-shim.js]: Perfect.

File: packages/xsnap/lib/console-shim.js (hunk 1 above)
Comment (dckc) [reply packages/xsnap/lib/console-shim.js]: too late. :)

File: packages/xsnap/lib/console-shim.js [hunk 3]
```diff
@@ -1,16 +1,13 @@
...
-    print(...args.map(arg => typeof arg === 'symbol' ? arg.toString() : arg));
-  } catch (err) {
-    // eslint-disable-next-line
-    print('cannot print:', err.message);
-    args.forEach((a, i) => {
-      // eslint-disable-next-line
-      print(` ${i}:`, a.toString ? a.toString() : '<no .toString>', typeof a);
-    });
-  }
+  // eslint-disable-next-line
```
Comment (erights) [inline packages/xsnap/lib/console-shim.js]: What are you disabling here?

Comment (dckc) [reply packages/xsnap/lib/console-shim.js]: eslint doesn't know that xsnap has `globalThis.print`.

File: packages/xsnap/lib/console-shim.js [hunk 4]
```diff
@@ -1,16 +1,13 @@
 /* global globalThis */
+
+// We use setQuote() below to break the cycle
+// where SES requires console and console is
+// implemented using assert.quote from SES.
+let quote = _v => '[?]';
+
 function tryPrint(...args) {
```
Comment (erights) [inline packages/xsnap/lib/console-shim.js]: There's no longer a `try/catch` here, so another name would be better.
For newly written functions (or even mostly newly written), please don't use non-arrow functions unless there's a reason.

```suggestion
const printAll = (...args) =>
  print(...args.map(v => typeof v === 'string' ? v : quote(v)));
```

File: packages/xsnap/lib/console-shim.js (hunk 3 above)
Comment (dckc) [reply packages/xsnap/lib/console-shim.js]: `no-undef` was not enough somehow.

note the `eslint-disable-next-line` was there before this change. ~~twice~~ three times, in fact.

File: packages/xsnap/lib/console-shim.js [hunk 5]
```diff
@@ -52,4 +49,12 @@ const console = {
   timeStamp: noop,
 };
 
+let quoteSet = false;
```
Comment (erights) [inline packages/xsnap/lib/console-shim.js:53]: Thanks for the interlock!

File: packages/xsnap/lib/console-shim.js [hunk 6]
```diff
@@ -52,4 +49,12 @@ const console = {
...
+
+export function setQuote(f) {
+  if (quoteSet) throw TypeError('quote already set');
```
Comment (erights) [inline packages/xsnap/lib/console-shim.js]: Jessie does not include braceless control flow.
```suggestion
  if (quoteSet) {
    throw TypeError('quote already set');
  }
```

**Review by erights — APPROVED** [review]
LGTM!

File: packages/xsnap/lib/console-shim.js (hunk 3 above)
Comment (erights) [reply packages/xsnap/lib/console-shim.js]: Please add a comment explaining this, so it won't look so mysterious to the next reader.

**Review by erights — APPROVED** [review]

File: packages/xsnap/lib/console-shim.js (hunk 3 above)
Comment (kriskowal) [reply packages/xsnap/lib/console-shim.js]: `/* global print */` also works, and TSC interprets it as `print : any`.
