### PR TITLE
ci: properly handle subdependencies for Endo branch override

### LINKED ISSUE #7947: build-bundle does not work with "current" endo master
Using https://github.com/Agoric/agoric-sdk/pull/7937 to try out "current" agoric-sdk master against "current" endo master, I'm getting a bunch of CI failures in the same place:

At https://github.com/Agoric/agoric-sdk/actions/runs/5295500873/jobs/9585898031?pr=7937#step:3:2927
```
$ node scripts/build-bundle.js
Failed with (TypeError#1)
TypeError#1: consumer.destroy is not a function

  at async Promise.all (index 0)
  at async run (packages/swingset-xsnap-supervisor/scripts/build-bundle.js:21:18)
```

Not immediately urgent because agoric-sdk still only depends on an earlier endo without this problem.

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #7947

## Description

The old implementation of `#endo-branch: XXX` hacked and slashed Endo tarballs into the checked out Agoric SDK, and in doing so, was extremely sensitive to conflicts in dependency versions between the two branches.

This PR introduces a better way: use yarn `resolutions` to override the Endo versions directly with the tarballs, and let yarn sort out how the dependency version conflicts should be handled.

As an aside, don't fail the SwingSet golden xsnap hash test when using an explicit Endo branch.

### Security Considerations

n/a

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

Improves CI support.

### CODE REVIEW

File: packages/SwingSet/test/test-xsnap-store.js [hunk 1]
```diff
@@ -130,6 +130,14 @@ test('create SES worker, save, restore, resume', async t => {
  * They are also sensitive to the XS code itself.
  */
 test('XS + SES snapshots are long-term deterministic', async t => {
+  /* global globalThis */
```
Comment (erights) [inline packages/SwingSet/test/test-xsnap-store.js]: Huh. I did not know we could do this locally. Is it scoped to the block it appears in?

Comment (michaelfig) [reply packages/SwingSet/test/test-xsnap-store.js]: Unfortunately, not scoped.

Comment (erights) [reply packages/SwingSet/test/test-xsnap-store.js]: It that case, I'd prefer it at the top of the file, since that lack of scoping is surprising and this misunderstanding fails unsafe.

**Review by erights — COMMENTED** [review]
FWIW, everything I understand LGTM. But I do not understand enough to approve.

File: .github/actions/restore-node/action.yml [hunk 2]
```diff
@@ -122,7 +127,12 @@ runs:
     - name: git dirty check
       working-directory: ${{ inputs.path }}
       run: |-
-        if [ -n "$(git status --porcelain)" ];
+        if [ ${{ steps.endo-branch.outputs.result }} == NOPE ]; then
+          dirty=$(git status --porcelain)
+        else
+          dirty=$(git status --porcelain | egrep -ve '^ M (package\.json|yarn\.lock)$')
```
Comment (mhofman) [inline .github/actions/restore-node/action.yml]: Unfortunate, but acceptable.

File: packages/SwingSet/test/test-xsnap-store.js (hunk 1 above)
Comment (mhofman) [reply packages/SwingSet/test/test-xsnap-store.js]: Yes let's move to the top

File: packages/SwingSet/test/test-xsnap-store.js [hunk 3]
```diff
@@ -130,6 +130,14 @@ test('create SES worker, save, restore, resume', async t => {
...
+  const ENDO_BRANCH = globalThis.process?.env?.ENDO_BRANCH;
+  if (ENDO_BRANCH && ENDO_BRANCH !== 'NOPE') {
```
Comment (mhofman) [inline packages/SwingSet/test/test-xsnap-store.js:135]: Wondering if instead we shouldn't run a `yarn test --update-snapshots` (and ignore the clobbered snapshot artifacts in the porcelain check)

File: scripts/replace-packages.sh
Comment (mhofman) [inline scripts/replace-packages.sh:1]: Can we keep this file around? I have found it useful for local testing too, where I don't care about the dependency resolution issues.

File: scripts/copy-packages-tgz.sh [hunk 4]
```diff
@@ -0,0 +1,39 @@
+#! /bin/bash
+# Usage: copy-packages-tgz.sh <SRCDIR>
+#
+# This script copies package tarballs generated from the $SRCDIR workspace
```
Comment (mhofman) [inline scripts/copy-packages-tgz.sh]: Why do we need to copy the tarballs at all? Aka can't the resolutions target the original package files?

**Review by mhofman — COMMENTED** [review]
Preliminary review, but seems fine so far.

File: .github/actions/restore-node/action.yml (hunk 2 above)
Comment (michaelfig) [reply .github/actions/restore-node/action.yml]: I've been thinking this over.  I'd like to pivot, and instead `git restore package.json yarn.lock` after the custom Endo's `yarn install` is done so that I can remove this special case.

File: packages/SwingSet/test/test-xsnap-store.js (hunk 3 above)
Comment (michaelfig) [reply packages/SwingSet/test/test-xsnap-store.js:135]: I don't want to make an assumption that this is the only SwingSet test using `t.snapshot`.  This approach seems less brittle.

File: scripts/copy-packages-tgz.sh (hunk 4 above)
Comment (michaelfig) [reply scripts/copy-packages-tgz.sh]: Good point!  I'll make that change once I figure out what to name this script. :)

File: scripts/replace-packages.sh
Comment (michaelfig) [reply scripts/replace-packages.sh:1]: Sounds good.  (I forgot about Hyrum's Law.)

File: packages/SwingSet/test/test-xsnap-store.js (hunk 3 above)
Comment (mhofman) [reply packages/SwingSet/test/test-xsnap-store.js:135]: The way I see it, when we add a test that breaks under these endo changes, either we update the test, or we update the CI job to handle the test. The main problem is if there are golden test impacted by endo changes that do not use snapshots.

The CI config here could simply add `--update-snapshot` to all `yarn test` invocations if we're not worried about other snapshot based tests diverging in more significant ways.

File: scripts/resolve-versions.sh [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+
+DIR=$(dirname -- "${BASH_SOURCE[0]}")
+
+cd -- "$DIR/.."
+
+override=$(jq 'to_entries | map({ key: ("**/" + .key), value: .value }) | from_entries')
+
+PACKAGEJSONHASH=$(
+  jq --arg override "$override" '.resolutions *= ($override | fromjson)' package.json |
+  git hash-object -w --stdin
```
Comment (mhofman) [inline scripts/resolve-versions.sh:17]: Interesting hack

**Review by mhofman — APPROVED** [review]

File: scripts/resolve-versions.sh (hunk 5 above)
Comment (kriskowal) [reply scripts/resolve-versions.sh:17]: I love this hack. It’s the best hack ever.

**Review by kriskowal — APPROVED** [review]
Big fan of the Shell, JQ, and Git software development stack. Now we just need an acronym for it that’s as compelling as LAMP.

**Comment by michaelfig** [comment]
> Big fan of the Shell, JQ, and Git software development stack. Now we just need an acronym for it that’s as compelling as LAMP.

_SHJQIT_, perchance?

**Comment by kriskowal** [comment]
> > Big fan of the Shell, JQ, and Git software development stack. Now we just need an acronym for it that’s as compelling as LAMP.
> _SHJQIT_, perchance?

💩
