### PR TITLE
Display wallet fees

### LINKED ISSUE #3735: [wallet] invitationDetails for an offer is undefined
## Describe the bug
On `agorictest-17`, invitation details are "undefined" in the wallet display when you click on the <> for an offer in the inbox.

## To Reproduce
1. Go to the Treasury, try to open a vault.
2. In the wallet, look at the proposed offer from the Treasury UI.
3. Click the '<>' to see the details
4. The 'invitationDetails' property is "undefined"

## Expected behavior
We should be seeing things like "instance", "installation", "expiry" and "fee"

## Screenshots

invitationDetailsUndefined

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #3735

The new behaviour:

image

and:

image

Also fix some problems with URL handling in the ag-solo.

### CODE REVIEW

File: packages/dapp-svelte-wallet/api/src/lib-wallet.js [hunk 1]
```diff
@@ -331,6 +334,23 @@ export function makeWallet({
...
 
+  const expandInvitationBrands = async invitationDetails => {
+    // We currently only add the fee's brand.
+    const { fee } = invitationDetails;
+    if (!fee) {
+      return invitationDetails;
+    }
+
+    // Add display info for the fee.
+    const displayInfo = await E(E(zoe).getFeeIssuer()).getDisplayInfo();
```
Comment (katelynsills) [inline packages/dapp-svelte-wallet/api/src/lib-wallet.js:345]: Hmm, we should get the same answer every time, so we could cache this. Not urgent but maybe let's add a todo.

**Review by katelynsills — APPROVED** [review]
LGTM! I was not able to manually test this locally, though

**Comment by katelynsills** [comment]
Was able to manually test using https://treasury.agoric.app. Everything looks good!
