### PR TITLE
test: fast-usdc contract flow

### LINKED ISSUE #10577: settler should not forward unknown transactions
## Describe the bug

The fast-usdc settler forward unknown transactions. It should not.

## To Reproduce

In #10572:

```js
test.serial.failing(
  'Settlement for unknown transaction (operator down)',
```

## Expected behavior

Leave the funds in the settlement account. Log loudly.

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

### PR DESCRIPTION
**Pull request by dckc**
refs: #10388
closes: #10577

doesn't close until
 - exercise all the code in the contract (analytic; best effort)

## Description / Testing Considerations

 - [x] test all the sequences in the product spec
    - [x] enumerate all the sequences in the product spec
 - [x] fix advancer/settler amount agreement bug

postponed:
 - 
 - #10510
    - [todo] C12 - Contract MUST only pay back the Pool only if they started the advance before USDC is minted
 - #10554

some `test.todo()`s are out of scope of contract flow tests. Some are more feasible as exo tests:
  - [todo] C18 - forward - MUST log and alert these incidents
  - [skip] LP borrow - TODO: move to exo test
  - [skip] LP repay - TODO: move to exo test

an some are after M1:
  - [todo] PERF: Target: settlement completes in a few minutes (after USDC is minted)
  - [todo] fee levels MUST be visible to external parties - i.e., written to public storage
  - [todo] C21 - Contract MUST log / timestamp each step in the transaction flow

### Security / Scaling / Upgrade Considerations

n/a

### Documentation Considerations

Internal design docs are assumed background knowledge.

### CODE REVIEW

**Comment by dckc** [comment]
currently (e049c85681) passing tests:

```
$ yarn test test/fast-usdc.contract.test.ts >,out 2>&1
$ grep ✔ ,out
  ✔ OCW operators redeem invitations and start watching
  ✔ C25 - LPs can deposit USDC
  ✔ STORY01: advancing happy path for 100 USDC (112ms)
  ✔ STORY03: see accounting metrics
  ✔ STORY05: LP collects fees on 100 USDC
  ✔ With 250 available, 3 race to get ~100 (242ms)
  ✔ STORY05(cont): LPs withdraw all liquidity
  ✔ STORY09: insufficient liquidity: no FastUSDC option
  ✔ C20 - Contract MUST function with an empty pool
  ✔ [expected fail] Settlement for unknown transaction (operator down)
  ✔ baggage (855ms)
```

File: packages/fast-usdc/src/exos/settler.js [hunk 1]
```diff
@@ -262,10 +262,11 @@ export const prepareSettler = (
...
         },
         /**
-         * @param {unknown} _result
-         * @param {SettlerTransferCtx} _ctx
+         * @param {unknown} reason
+         * @param {SettlerTransferCtx} ctx
          */
-        onRejected(_result, _ctx) {
+        onRejected(reason, ctx) {
+          trace('transfer rejected!', reason, ctx);
```
Comment (0xpatrickdev) [inline packages/fast-usdc/src/exos/settler.js]: should this have a ⚠️ emoji?

**Comment by dckc** [comment]
@0xpatrickdev , @turadg , based on today's discussion of scope, I think this is ready for review.

File: packages/orchestration/src/exos/chain-hub.js [hunk 2]
```diff
@@ -98,7 +98,7 @@ export const connectionKey = (chainId1, chainId2) => {
  */
 const reverseConnInfo = connInfo => {
   const { transferChannel } = connInfo;
-  return {
+  return harden({
```
Comment (0xpatrickdev) [inline packages/orchestration/src/exos/chain-hub.js:101]: I hit this as well: https://github.com/Agoric/agoric-sdk/pull/10571/commits/33f26e9aa14bdfe365520f5c71f12a5084c01f7f

File: packages/orchestration/src/utils/chain-hub-helper.js [hunk 3]
```diff
@@ -32,16 +32,17 @@ export const registerChainsAndAssets = (
...
+      const pair = [pChainId, cChainId].sort().join('<->');
       if (!registeredPairs.has(pair)) {
         chainHub.registerConnection(pChainId, cChainId, connInfo);
         registeredPairs.add(pair);
       }
     }
   }
+  console.log('chainHub: registered connections', [...registeredPairs].sort());
 
+  console.log('chainHub: registering assets', Object.keys(assetInfo || {}));
```
Comment (0xpatrickdev) [inline packages/orchestration/src/utils/chain-hub-helper.js:44]: Nice additions

File: packages/fast-usdc/test/supports.ts [hunk 4]
```diff
@@ -157,6 +196,19 @@ export const commonSetup = async (t: ExecutionContext<any>) => {
...
 
+  const chainInfo = harden(() => {
+    const { agoric, osmosis, noble } = fetchedChainInfo;
+    return { agoric, osmosis, noble };
+  })();
+
+  const assetInfo = harden(
+    Object.fromEntries([
+      assetOn('uusdc', 'noble'),
+      [uusdcOnAgoric, agUSDCDetail],
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/supports.ts:206]: `assetOn` is nifty. Why not also use it here?

File: packages/fast-usdc/src/exos/settler.js [hunk 5]
```diff
@@ -264,13 +275,13 @@ export const prepareSettler = (
          * @param {SettlerTransferCtx} ctx
          *
          * @typedef {{
-         *   txHash: EvmHash;
+         *   txHash: EvmHash | undefined;
```
Comment (0xpatrickdev) [inline packages/fast-usdc/src/exos/settler.js]: When can this be `undefined`?

File: packages/fast-usdc/src/exos/settler.js [hunk 6]
```diff
@@ -179,37 +176,51 @@ export const prepareSettler = (
...
          * @param {EvmHash} txHash
          * @param {NobleAddress} sender
-         * @param {NatValue} amount
+         * @param {NatValue} fullValue
          */
-        async disburse(txHash, sender, amount) {
+        async disburse(txHash, sender, fullValue) {
           const { repayer, settlementAccount } = this.state;
-          const received = AmountMath.make(USDC, amount);
+          const received = AmountMath.make(USDC, fullValue);
```
Comment (0xpatrickdev) [inline packages/fast-usdc/src/exos/settler.js:225]: In the advancer this was called "requested". In this context, I think "fullValue" works. "withFees"
and "advanceWithFees" are two not so great ideas that popped into my head.

File: packages/fast-usdc/src/exos/advancer.js [hunk 7]
```diff
@@ -222,39 +216,30 @@ export const prepareAdvancerKit = (
...
-            amount.value,
-            destination.value,
-            true,
+            q({ advanceAmount, destination, result }).toString(),
           );
+          try {
+            notifyFacet.notifyAdvancingResult({ destination, ...detail }, true);
+          } catch (err) {
+            log('@@@ call to notifyAdvancingResult', err);
+          }
```
Comment (0xpatrickdev) [inline packages/fast-usdc/src/exos/advancer.js]: When would this throw? We have different catch behavior in the `onRejected` below

File: packages/fast-usdc/src/exos/advancer.js [hunk 8]
```diff
@@ -39,47 +40,40 @@ import { makeFeeTools } from '../utils/fees.js';
...
+const AdvancerVowCtxShape = M.splitRecord(
+  {
+    fullAmount: AnyNatAmountShape,
+    advanceAmount: AnyNatAmountShape,
+    destination: ChainAddressShape,
+    forwardingAddress: M.string(),
+    txHash: EvmHashShape,
+  },
+  { tmpSeat: M.remotable() },
+);
```
Comment (0xpatrickdev) [inline packages/fast-usdc/src/exos/advancer.js:53]: Nice refactor

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 9]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
+
+  const me = harden({
+    checkPoolAvailable: async (
+      t: ExecutionContext,
+      want: NatValue,
+      metricsSub: ERef<Subscriber<PoolMetrics>>,
+    ) => {
+      const { value: m } = await E(metricsSub).getUpdateSince();
+      const { numerator: poolBalance } = m.shareWorth; // XXX awkward API?
+      const enough = poolBalance.value > want;
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts:595]: I believe this also needs to check against `encumberedBalance` . 

> // XXX awkward API?

And +1. Also confusing since the above is not obvious.

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 10]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
+
+  const makeTx = (amount: bigint, EUD: string): CctpTxEvidence => {
+    const recipientAddress = `${settleAddr}?EUD=${EUD}`;
+    nonce += 1;
+    const { txHash } = template;
+    const suffix = Number(txHash.slice(-5)) + nonce * 7;
+
+    const tx: CctpTxEvidence = harden({
+      ...template,
+      txHash: `0x${txHash.slice(2, txHash.length - 5)}${suffix}`,
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts]: Explain the goal more here (+ suffix)? I assume one part is to guarantee uniqueness. If we are going for legibility, maybe something like:
```
0x00000...0000001
0x00000...0000002
...
0x00000...0000010
```

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 11]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
-  );
+    send: async (t: ExecutionContext, amount: bigint, EUD: string) => {
+      const tx = cctp.makeTx(amount, EUD);
+      t.log(who, 'signs CCTP for', amount, 'uusdc w/EUD:', EUD);
+      txPublisher.publish(tx);
+      sent.push(tx);
+      await eventLoopIteration();
+      return tx;
+    },
+    checkSent: (
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts:610]: maybe `request` and `checkRequests` are better verbs? Agree they are sending funds for mint. But they are more so requesting an advance.

_I was also have a little trouble distinguishing the oracle operator at first, since the customer is sending `CctpTxEvidence`_

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 12]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
+      t: ExecutionContext,
+      { bank = [] as any[], local = [] as any[] } = {},
+      forward?: unknown,
+    ) => {
+      const evidence = sent.shift();
+      if (!evidence) throw t.fail('nothing sent');
+
+      // C3 - Contract MUST calculate AdvanceAmount by ...
+      // Mostly, see unit tests for calculateAdvance, calculateSplit
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts:619]: +1 unit tests cover fee math well

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 13]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
+  const sent1 = await cust1.send(t, 108_000_000n, 'osmo1234advanceHappy');
+  await transmitTransferAck(); // ack IBC transfer for advance
+  // Nothing we can check here, unless we want to inspect calls to `trace`.
+  // `test/exos/advancer.test.ts` covers calls to `log: LogFn` with mocks.
+  // This is still helpful to call, so we can observe "Advance transfer
+  // fulfilled" in the test output.
 
-  // advance sent from PoolSeat to PoolAccount
+  const { calculateAdvance, calculateSplit } = makeFeeTools(feeConfig);
+  const advance = calculateAdvance(usdc.make(sent1.tx.amount));
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts]: nit: maybe call this `expectedAdvance`

**Comment by dckc** [comment]
Why is this [inter protocol test failing???](https://github.com/Agoric/agoric-sdk/actions/runs/12039010307/job/33566059644?pr=10572)
```
not ok 274 - swingsetTests › reserve › assetReserve-upgrade › assetReserve service upgrade %ava-dur=22237ms
#   buildVatController
#   REJECTED from ava test("assetReserve service upgrade"): (Error#1)
#   Error#1: config.vats.bootstrap: Failed to load module "./test/swingsetTests/reserve/bootstrap-assetReserve-upgrade.js" in package "file:///home/runner/work/agoric-sdk/agoric-sdk/packages/inter-protocol/" (1 underlying failures: Cannot find external module "module" in package file:///home/runner/work/agoric-sdk/agoric-sdk/node_modules/@endo/compartment-mapper/
```

strangely, it reproduces locally.

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 14]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
+    },
+    'metrics while advancing',
   );
 
+  await mint(sent1);
+
+  // C8 - "Contract MUST be able to initialize settlement process when Noble mints USDC."
+  // The metrics are a useful proxy, but the contract could lie.
+  // The real test of whether the contract turns minted funds into liquidity is
+  // the ability to advance the funds (in later tests).
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts:794]: Which later test are you referring to? Should we check the outgoing `localchainBridge` messages in this test and confirm the advance was sent?

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 15]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
+        numerator: add(par250.numerator, split.PoolFee),
+      },
+      totalBorrows: { value: 105839999n },
+      totalContractFees: { value: 432000n },
+      totalPoolFees: { value: 1728001n },
+      totalRepays: { value: 105839999n },
+    },
+    'metrics after advancing',
+  );
+});
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts:813]: Worth a todo for checking `evmHash: status.ADVANCING` in vstorage?

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 16]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
+
+test.todo(
+  'PERF: Target: settlement completes in a few minutes (after USDC is minted)',
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts]: I don't think this will be the right place for this, since much of the latency is dependent on blocks and bridges, so maybe we should omit this todo. Would we do this in `multichain-testing`? a testnet?

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 17]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
+  cust.racer2.checkSent(t, since(bridgePos));
+  // TODO/WIP: cust.racer3.checkSent(t, since(bridgePos), 'forward - LP depleted');
   await transmitTransferAck();
-  // Nothing we can check here, unless we want to inspect calls to `trace`.
-  // `test/exos/advancer.test.ts` covers calls to `log: LogFn` with mocks.
-  // This is still helpful to call, so we can observe "Advance transfer
-  // fulfilled" in the test output.
+  await transmitTransferAck();
+  await transmitTransferAck();
+  await Promise.all([mint(sent1), mint(sent2), mint(sent3)]);
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts:886]: This is cool, but I'm struggling to understand how we plan to check the results of the Promise.all. I don't think we'll have any bridge messages that indicate insufficient funds (advancer's `log` would know though.) Will we wait for txs to be posted to vstorage?

Regardless, consider specifying in the TODO/WIP

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 18]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
+    bridges: { snapshot, since },
+    mint,
+  } = t.context;
+  const custEmpty = makeCustomer('Earl', cctp, txPub.publisher, feeConfig);
+  const bridgePos = snapshot();
+  const sent = await custEmpty.send(t, 150_000_000n, 'osmo123');
+  const bridgeTraffic = since(bridgePos);
+  await mint(sent);
+  custEmpty.checkSent(t, bridgeTraffic, 'forward');
+  t.log('No advancement, just settlement');
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts:941]: Consider a TODO somewhere here to ensure `Observed` and/or `Forwarded` statuses are recorded in vstorage

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 19]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
+  await transmitTransferAck(); // ack IBC transfer for forward
 });
+
+// advancedEarly stuff
+test.todo(
+  'C12 - Contract MUST only pay back the Pool only if they started the advance before USDC is minted',
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts:947]: This is advance early, but also could be the same scenario about. We could inspect the outgoing LCA bridge messages to confirm they sent the requested amount and not the net of fees amount

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 20]
```diff
@@ -510,115 +542,460 @@ test('LP repay', async t => {
...
+);
+
+test.todo('C18 - forward - MUST log and alert these incidents');
+
+test.serial.failing(
```
Comment (0xpatrickdev) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts]: Why is this failing?

**Review by 0xpatrickdev — APPROVED** [review]
LGTM. Only have one comment that really needs addressing.

I am not the craziest about the single shared test context and test.serials. It makes it so that we can't do `yarn test ... -m 'STORY01:*'` to debug or work on an individual test. Speaking offline it seemed more cost effective to structure this way, so I won't block on this.

File: packages/fast-usdc/test/supports.ts (hunk 4 above)
Comment (dckc) [reply packages/fast-usdc/test/supports.ts:206]: It was used to define these 2.
uusdOnAgoric is exported for use elsewhere.

File: packages/fast-usdc/src/exos/advancer.js (hunk 7 above)
Comment (dckc) [reply packages/fast-usdc/src/exos/advancer.js]: Oops. @@@ means I wasn't finished with this.  Good catch. Will give it another think.

File: packages/fast-usdc/src/exos/settler.js (hunk 5 above)
Comment (dckc) [reply packages/fast-usdc/src/exos/settler.js]: Only in the case that we're not handling correctly (#10577). I might as well fix it now.

File: packages/fast-usdc/src/exos/advancer.js (hunk 7 above)
Comment (dckc) [reply packages/fast-usdc/src/exos/advancer.js]: It was due to a bug; I saw:

```
Error#2: no advancing tx with {
  sender: 'noble1x0ydg69dh6fqvr27xjvp6maqmrldam6yfelqkd',
  amount: 105839999n
}
```

The thing is: if something throws in `onFulfilled`, the exception gets swallowed up. So I wonder if _all_ of our `onFulfilled` (and `onRejected`) methods need a try/catch.

Comment (dckc) [reply packages/fast-usdc/src/exos/advancer.js]: There's a new issue about this:
 - #10576

File: packages/fast-usdc/test/fast-usdc.contract.test.ts (hunk 10 above)
Comment (dckc) [reply packages/fast-usdc/test/fast-usdc.contract.test.ts]: OK... changing to...

```js
      txHash: `0x00000${nonce}`,
```

File: packages/fast-usdc/test/fast-usdc.contract.test.ts (hunk 11 above)
Comment (dckc) [reply packages/fast-usdc/test/fast-usdc.contract.test.ts:610]: > better verbs?

I'm trying out `sendFast`.

> ... the customer is sending `CctpTxEvidence`

Yeah; I'm adding some notes about that KLUDGE.

File: packages/fast-usdc/test/fast-usdc.contract.test.ts (hunk 14 above)
Comment (dckc) [reply packages/fast-usdc/test/fast-usdc.contract.test.ts:794]: > Which later test are you referring to?

The racer test, for example.

> Should we check the outgoing localchainBridge messages in this test and confirm the advance was sent?

We did `checkSent()` for the STORY01 advance.

What this comment is saying (or: trying to say) is: after STORY01 completes, the contract _says_ (via metrics) that it still has ~250USDC available. But it could say that it has a zillion USDC available. The proof that it actually has funds available is when it actually transfers them in a future advance.

File: packages/fast-usdc/test/fast-usdc.contract.test.ts (hunk 15 above)
Comment (dckc) [reply packages/fast-usdc/test/fast-usdc.contract.test.ts:813]: It's no longer ADVANCING at this particular point.

I'm not trying to be exhaustive about vstorage TODOs. The scope of this PR is M1. vstorage stuff is in M2.

File: packages/fast-usdc/test/fast-usdc.contract.test.ts (hunk 16 above)
Comment (dckc) [reply packages/fast-usdc/test/fast-usdc.contract.test.ts]: > I don't think this will be the right place for this,

I agree, but this is where I was taking notes on product requirements. I'll take this one out, but note that there are also TODOs here that should be satisfied by exo tests. When the TODOs get done, we can prune these notes.

> since much of the latency is dependent on blocks and bridges, so maybe we should omit this todo. Would we do this in multichain-testing? a testnet?

We have plans for bootstrap tests to measure computrons as well as multichain-testing and testnets.

File: packages/fast-usdc/test/fast-usdc.contract.test.ts (hunk 17 above)
Comment (dckc) [reply packages/fast-usdc/test/fast-usdc.contract.test.ts:886]: Yes, as I was working on this test, I realized that our mock bridge stuff only works one tx at a time. I'm not inclined to go on at any length about what's TODO/WIP here just now.

File: packages/fast-usdc/test/fast-usdc.contract.test.ts (hunk 18 above)
Comment (dckc) [reply packages/fast-usdc/test/fast-usdc.contract.test.ts:941]: M2

File: packages/fast-usdc/test/fast-usdc.contract.test.ts (hunk 19 above)
Comment (dckc) [reply packages/fast-usdc/test/fast-usdc.contract.test.ts:947]: > We could inspect the outgoing LCA bridge messages to confirm they sent the requested amount and not the net of fees amount

`checkSent` with `'forward'` does check that.

But we didn't test the `advancedEarly` case, i.e. the case where the mint comes in between ADVANCING and ADVANCED.

File: packages/fast-usdc/test/fast-usdc.contract.test.ts (hunk 20 above)
Comment (dckc) [reply packages/fast-usdc/test/fast-usdc.contract.test.ts]: - #10577

As I say, might as well fix it now.
