### PR TITLE
fix(casting): dont crash on bad capdata

### LINKED ISSUE #8579: Casting follower crashes on invalid capdata
## Describe the bug
We noticed the dapps weren't getting wallet updates in https://github.com/Agoric/ui-kit/issues/57. More details in the issue comments, but it turns out when an offer to close a vault fails (e.g. due to insufficient IST in one's purse), the vstorage update in `published.wallet.agoric1[useraddress]` contains an error object that cannot be parsed as valid capdata by `@endo/marshal`. This was causing the follower in casting to crash silently and stop yielding updates for offer statuses. This would also cause the next offer status update to fail, because when you load the dapp, it would hit this error, and the follower would crash.

## To Reproduce
1. Open a vault on app.inter.trade
2. Try to close the vault with insufficient IST in your purse
3. Notice that you never see the offer status update in the toast

## Expected behavior
The status update is able to be unserialized as valid capdata and the casting follower doesn't break

### PR DESCRIPTION
**Pull request by samsiegart**
refs https://github.com/Agoric/ui-kit/issues/57
refs https://github.com/Agoric/agoric-sdk/issues/8579

Explanation in the comment thread of the issue. TL;DR - The follower was crashing silently after hitting bad capdata. This change makes it so that instead it surfaces an `error` instead of a `value` in that case, and keeps yielding more values.

Added a unit test to ensure that it properly surfaces the error and can keep yielding more values afterwards.

### CODE REVIEW

File: packages/casting/src/types.js [hunk 1]
```diff
@@ -40,14 +40,18 @@ export {};
  */
 
 /**
- * @see {ChangeFollower}
  * @template T
```
Comment (michaelfig) [inline packages/casting/src/types.js]: The base no longer needs to be a template.
```suggestion
```

File: packages/casting/src/types.js [hunk 2]
```diff
@@ -40,14 +40,18 @@ export {};
...
- * @property {T} value
+ * @typedef {object} ValueFollowerBase
  * @property {number} blockHeight
  * @property {number} currentBlockHeight
  */
 
+/**
+ * @see {ChangeFollower}
+ * @template T
+ * @typedef {ValueFollowerBase<T> & ({ value: T } | { value: undefined, error: any })} ValueFollowerElement
```
Comment (michaelfig) [inline packages/casting/src/types.js]:
```suggestion
 * @typedef {ValueFollowerBase & ({ value: T } | { value: undefined, error: any })} ValueFollowerElement
```

**Review by michaelfig — APPROVED** [review]
I like how self-contained it is.  LGTM!

Please consider un-templatizing the ValueFollowerBase, but whether you choose to is not a blocker.

File: packages/casting/src/types.js (hunk 1 above)
Comment (samsiegart) [reply packages/casting/src/types.js]: Ah good catch, removed
