### PR TITLE
Operational swing-store artifact level

### LINKED ISSUE #9388: Switch state-sync artifact level to operational
## What is the Problem Being Solved?

To support #9174, we need to stop requiring older transcript artifacts in state-sync snapshot. #9386 would cause most validators to no longer keep historical swing-store, which would cause a "replay" level snapshot to fail creation.

## Description of the Design

In golang state-sync logic, change snapshot creation and restoration to use `operational` level instead of `replay`.

## Security Considerations

None

## Scaling Considerations

Smaller state-sync snapshots!

## Test Plan

Manually?
Existing loadgen integration tests does exercise that state-sync works

## Upgrade Considerations

Chain software upgrade.

### PR DESCRIPTION
**Pull request by mhofman**
closes: #9388

## Description

Switch from `replay` to `operational` for state-sync export/restore, genesis export/import, and as the default for cosmic-swingset's export/import of kernel DB command line tool.

Drive by change of the default chain home directory for the import/export tool (this location was effectively changed a couple year ago but not consistently in the rest of the SDK).

### Security Considerations

If all nodes prune historical "replay" artifacts, we lose the ability to perform replay based upgrades in the future. We expect archive nodes to not manually prune their DB in this way.

### Scaling Considerations

This should have no impact on performance right now. In the future, when exporting the IAVL data is not as slow, this would reduce the time it takes for state-sync snapshots to be created.

### Documentation Considerations

Should communicate this change with validators

### Testing Considerations

Covered by existing integration tests.

### Upgrade Considerations

Chain software change

### CODE REVIEW

File: golang/cosmos/x/swingset/genesis.go [hunk 1]
```diff
@@ -98,9 +98,8 @@ func ExportGenesis(ctx sdk.Context, k Keeper, swingStoreExportsHandler *SwingSto
 		// The export will fail if the export of a historical height was requested
 		snapshotHeight,
 		swingStoreGenesisEventHandler{exportDir: swingStoreExportDir, snapshotHeight: snapshotHeight},
-		// The export will fail if the swing-store does not contain all replay artifacts
 		keeper.SwingStoreExportOptions{
-			ArtifactMode:   keeper.SwingStoreArtifactModeReplay,
+			ArtifactMode:   keeper.SwingStoreArtifactModeOperational,
 			ExportDataMode: keeper.SwingStoreExportDataModeSkip,
```
Comment (gibson042) [inline golang/cosmos/x/swingset/genesis.go:103]: Hmm, shouldn't a genesis export require replay-level data?

**Review by gibson042 — APPROVED** [review]
Looks good, but I wonder about genesis export because an XS version change may be more likely in that scenario. Not an objection, though, just food for thought.

File: golang/cosmos/x/swingset/genesis.go (hunk 1 above)
Comment (warner) [reply golang/cosmos/x/swingset/genesis.go:103]: I don't think so, "operational" includes both XS heap snapshots and the subset (suffix) of transcript entries since the snapshot point.

I think a "genesis export" is meant to immediately reconstruct the chain state vector as of a given block height without retrieving or re-applying any cosmos txns. It could be used as the genesis of a new chain, with a different identity, whose initial state is equal to the most-recent state of the parent. And for that, you only need the current state of the vat workers, which is "operational" in our world.

In particular, it is *not* trying to start from the genesis state of the parent chain.

Now, the debugging/diagnostic replay-everything-with-a-different-xsnap things we might find ourselves needing to do *will* require replay-level data, and I suppose the question is whether we intend `agd genesis-export` to be the tool to fetch the data for that purpose, or if there's a different subcommand (or a `--replay` flag) that we'd use for that purpose.

File: packages/cosmic-swingset/src/export-kernel-db.js [hunk 2]
```diff
@@ -293,10 +293,7 @@ export const main = async (
   const stateDir =
     processValue.getFlag('state-dir') ||
     // We try to find the actual cosmos state directory (default=~/.ag-chain-cosmos)
-    `${processValue.getFlag(
-      'home',
-      `${homedir}/.ag-chain-cosmos`,
-    )}/data/agoric`;
+    `${processValue.getFlag('home', `${homedir}/.agoric`)}/data/agoric`;
```
Comment (warner) [inline packages/cosmic-swingset/src/export-kernel-db.js:300]: I think the comment on the previous line need to be updated to match

File: packages/cosmic-swingset/src/import-kernel-db.js [hunk 3]
```diff
@@ -248,10 +248,7 @@ export const main = async (
   const stateDir =
     processValue.getFlag('state-dir') ||
     // We try to find the actual cosmos state directory (default=~/.ag-chain-cosmos)
-    `${processValue.getFlag(
-      'home',
-      `${homedir}/.ag-chain-cosmos`,
-    )}/data/agoric`;
+    `${processValue.getFlag('home', `${homedir}/.agoric`)}/data/agoric`;
```
Comment (warner) [inline packages/cosmic-swingset/src/import-kernel-db.js:251]: same

File: packages/cosmic-swingset/src/export-kernel-db.js [hunk 4]
```diff
@@ -41,10 +41,10 @@ export const ExportManifestFileName = 'export-manifest.json';
  */
 export const getEffectiveArtifactMode = artifactMode => {
   switch (artifactMode) {
+    case undefined:
```
Comment (warner) [inline packages/cosmic-swingset/src/export-kernel-db.js:45]: .. and this might be the flag that one would provide to get a replay-everything -type bundle out of an archival node, to address @gibson042 's comment

**Review by warner — APPROVED** [review]
LGTM, assuming I'm understanding the how-do-we-get-full-data thing properly

File: golang/cosmos/x/swingset/genesis.go (hunk 1 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/genesis.go:103]: Right, at the end of the day, we can always devise a mechanism to re-import missing artifacts, as long as the hashes are correct in the export data. Genesis export does not change that. What may happen is that in a genesis export we'd need to edit artifacts in some fashion, which would require editing the hashes in the genesis file, but at this point I'm skeptical we'll ever be able to or need to do that.
