### PR TITLE
fix(tame-metering): be tolerant to Node.js 14.15.2

### LINKED ISSUE #2097: Tests with nodejs v14.15.2 fail on `master`
**WORKAROUND**
Run with `node v14.15.1` or lower.

**Describe the bug**
Creating a new build environment from scratch against nodejs version `v14.15.2` or later fails.  `yarn test` fails in `tame-metering`, as does any attempt to `agoric start` in dapps.

```
> @agoric/tame-metering
$ ava

  istamed › isTamed

  Error thrown in test:

  TypeError {
    messageundefined'Cannot redefine property: constructor',
  }
```

**To Reproduce**
1. sync master
2. `yarn; yarn build`
3. `yarn test`

**Expected behavior**
Tests pass

**Platform Environment**
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

**Additional context**
The full context:

```
> @agoric/tame-metering
$ ava

  ✖ No tests found in test/test-sanity.js

  ─

  istamed › isTamed

  Error thrown in test:

  TypeError {
    messageundefined'Cannot redefine property: constructor',
  }

  › defineProperty (<anonymous>)
  › assignToTarget (src/tame.js:243:11)
  › src/tame.js:256:7
  › Array.forEach (<anonymous>)
  › Array.forEach (src/tame.js:172:20)
  › wrap (src/tame.js:255:40)
  › wrap (src/tame.js:226:7)
  › wrapDescriptor (src/tame.js:67:20)
  › assignToTarget (src/tame.js:239:19)
  › src/tame.js:256:7

  Uncaught exception in test/test-sanity.js

  TypeError: Cannot redefine property: constructor

  › TypeError: Cannot redefine property: constructor
  › defineProperty (<anonymous>)
  › assignToTarget (src/tame.js:243:11)
  › src/tame.js:256:7
  › Array.forEach (<anonymous>)
  › Array.forEach (src/tame.js:172:20)
  › wrap (src/tame.js:255:40)
  › wrap (src/tame.js:226:7)
  › wrapDescriptor (src/tame.js:67:20)
  › assignToTarget (src/tame.js:239:19)
  › src/tame.js:256:7

  ─

  1 test failed
  1 uncaught exception
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.`
```

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #2097

With Node.js making some properties non-configurable, we found:

```
> @agoric/tame-metering
$ ava

  ✖ No tests found in test/test-sanity.js

  ─

  istamed › isTamed

  Error thrown in test:

  TypeError {
    messageundefined'Cannot redefine property: constructor',
  }

  › defineProperty (<anonymous>)
  › assignToTarget (src/tame.js:243:11)
  › src/tame.js:256:7
  › Array.forEach (<anonymous>)
  › Array.forEach (src/tame.js:172:20)
  › wrap (src/tame.js:255:40)
  › wrap (src/tame.js:226:7)
  › wrapDescriptor (src/tame.js:67:20)
  › assignToTarget (src/tame.js:239:19)
  › src/tame.js:256:7
```

With the change in this PR, the meter taming doesn't throw.  Do note that our metering has never been bulletproof, more just advisory until we get to XS.

### CODE REVIEW

File: packages/tame-metering/src/tame.js [hunk 1]
```diff
@@ -242,10 +242,7 @@ export function tameMetering() {
         try {
           defineProperty(o, p, newDesc);
         } catch (e) {
-          // Ignore: TypeError: Cannot redefine property: Symbol(Symbol.hasInstance)
-          if (typeof p !== 'symbol' || !(e instanceof TypeError)) {
-            throw e;
-          }
+          // Ignore: TypeError: Cannot redefine property: ...
```
Comment (dtribble) [inline packages/tame-metering/src/tame.js]: Should this log the failure?

**Comment by dtribble** [comment]
Also, are the now-non-configurable properties standard properties that were specified as non-configurable?  Or is this also a bug that should be file on node/v8?

**Review by erights — CHANGES_REQUESTED** [review]
Why is this safe?

**Comment by michaelfig** [comment]
> Why is this safe?

My point is that it is no less safe than the current metering implementation, and has the added benefit of not crashing during initialisation.

File: packages/tame-metering/src/tame.js (hunk 1 above)
Comment (michaelfig) [reply packages/tame-metering/src/tame.js]: This is best-effort code only, and logging would be annoying for no real gain.

**Comment by michaelfig** [comment]
> Also, are the now-non-configurable properties standard properties that were specified as non-configurable? Or is this also a bug that should be file on node/v8?

It's the brittleness of the current approach to blanket metering.  In all circumstances, this approach needs to evolve to a bulletproof one, and I think we're banking on XS for that.

File: packages/tame-metering/src/tame.js (hunk 1 above)
Comment (michaelfig) [reply packages/tame-metering/src/tame.js]: As requested, I've added logging.

**Review by erights — APPROVED** [review]
LGTM

Please also file an issue labeled "security" that this metering by rewrite should be considered insecure.

**Comment by michaelfig** [comment]
> Please also file an issue labeled "security" that this metering by rewrite should be considered insecure.

I've done so in #2105
