### PR TITLE
fixes to chainConnection key and vstorage

### LINKED ISSUE #8879: vat-orchestration expose client (chain) connection info
## What is the Problem Being Solved?
As a part of building the vat orchestration for the orchestration api, we need to allow a method to expose the client (chain) connection info

- ⚠️ `@agoric/orchestration`, `vat-orchestration` (done through agoricNames instead)
- ✅ Expose client (chain) connection info 
- ✅ Lookup (connection-0) by chainId
- ❌ Display current capabilities (host_enabled, allow_messages, allow_queries) [no use cases yet require]
- ❌ Alert when status changed (closed, expired)  [no use cases yet require]

### PR DESCRIPTION
**Pull request by turadg**
refs: #9063
closes: #8879

## Description

Fast follow on https://github.com/Agoric/agoric-sdk/pull/9376

Tests that uncovered that the JSON.stringify encoding is not a valid vstorage key. There's one character that can be used as a separator `_`, the only vstorage valid char that's not a chain-id valid char. (vstorage chars are superset of chain id chars)

Also fixes the chain_id half of the connection key, which had been chain name.

Also adds a cache to chain info writer so it doesn't write entries that exist and haven't changed.

Some misc test supports as well.

### Security Considerations

none

### Scaling Considerations

none

### Documentation Considerations

Eventually we'll document these new vstorage nodes, but probably by just pointing to some snapshots.

### Testing Considerations

The A3P test checks that it works through agd CLI.

### Upgrade Considerations

not yet released

### CODE REVIEW

File: packages/orchestration/src/utils/chainHub.js [hunk 1]
```diff
@@ -16,6 +16,20 @@ export const CHAIN_KEY = 'chain';
...
+ * Character used in a connection tuple key to separate the two chain ids. Valid
+ * because a chainId can contain only alphanumerics and dash.
+ *
+ * It was chosen to be:
+ *
+ * - easy to read
+ * - common for expressing a tuple
+ * - meaningless on the command line
+ *
+ * @see {@link https://github.com/ChainAgnostic/CAIPs/blob/main/CAIPs/caip-2.md}
```
Comment (dckc) [inline packages/orchestration/src/utils/chainHub.js:28]: :1st_place_medal: 
thanks for the research and for citing external constraints in a doc comment

File: packages/orchestration/src/utils/chainHub.js [hunk 2]
```diff
@@ -25,7 +39,7 @@ export const CONNECTIONS_KEY = 'chainConnection';
  * @param {string} chainId2
  */
 export const connectionKey = (chainId1, chainId2) =>
-  JSON.stringify([chainId1, chainId2].sort());
+  [chainId1, chainId2].sort().join(CHAIN_ID_SEPARATOR);
```
Comment (dckc) [inline packages/orchestration/src/utils/chainHub.js]: I think we should assert that neither id contains `CHAIN_ID_SEPARATOR`

Seems like there's a confusion attack risk otherwise.

**Review by dckc — APPROVED** [review]

File: packages/internal/src/storage-test-utils.js [hunk 3]
```diff
@@ -254,3 +255,43 @@ export const makeMockChainStorageRoot = () => {
...
   });
 };
+
+/**
+ * @param {import('ava').ExecutionContext<unknown>} t
+ * @param {MockChainStorageRoot | FakeStorageKit} storage
+ * @param {({ note: string } | { node: string; owner: string }) &
+ *   ({ pattern: string; replacement: string } | {})} opts
+ */
+export const documentStorageSchema = async (t, storage, opts) => {
```
Comment (dckc) [inline packages/internal/src/storage-test-utils.js:265]: internal... hm... we do want it exported from the SDK. I guess governance can continue to play that role.

**Review by dckc — APPROVED** [review]
