### PR TITLE
fix(addAssetToVault): support issuerName separate from keyword

### LINKED ISSUE #8235: addAssetToVault does not support initial lower-case asset names
## Describe the bug

Community testing of adding stATOM ran into the "must begin with an upper case letter" constraint on [Zoe keywords](https://docs.agoric.com/reference/zoe-api/zoe-data-types.html#keyword) due to conflating asset names (which should have no such constraints) with keywords.

 - https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/issues/16

## To Reproduce

As documented in https://github.com/0xpatrickdev/agoric-vault-collateral-proposal :

1. adapt the STARS proposal to stATOM
2. deploy bundles; make a governance proposal; vote
3. `Error: keyword "stATOM" must be an ascii identifier starting with upper case` shows in chain logs

We tried #8229, which cleans up some of the conflation in the short-lived proposal bundle code, but then we ran into another case in a long-running contract (the provision pool).

https://github.com/Agoric/agoric-sdk/blob/mainnet1B/packages/vats/src/provisionPoolKit.js#L347

## Expected behavior

The community should be able to choose asset names starting with lower-case.

## Platform Environment

devnet. mainnet1B code

also on a local chain using #8229

## Additional context

 - https://github.com/0xpatrickdev/agoric-vault-collateral-proposal

### PR DESCRIPTION
**Pull request by dckc**
fixes: #8235
refs: #8176, #8177

## Description

In `addAssetToVault`, we conflated `keyword` (needed for registration with the reserve and auction) with `issuerName` (for use in `agoricNames`). This adds to `InterchainAssetOptions` an `issuerName` property that defaults to the value of `keyword`.

### Security, Documentation Considerations

Allows higher fidelity between `agoricNames` and well-known names of assets.

### Scaling Considerations

n/a/

### Testing Considerations

Manual testing with `issuerName: 'atom'` and `issuerName: 'stars'` succeeded. We could keep the `issuerName: 'stars'` tweak. But first, I'd like to see what ci thinks of this.

### Upgrade Considerations

doesn't affect existing vats.

### CODE REVIEW

File: packages/inter-protocol/src/proposals/addAssetToVault.js [hunk 1]
```diff
@@ -16,8 +16,9 @@ export * from './startPSM.js';
  * @property {string} [issuerBoardId]
  * @property {string} [denom]
  * @property {number} [decimalPlaces]
- * @property {string} [proposedName]
+ * @property {string} proposedName
  * @property {string} keyword
+ * @property {string} [issuerName]
  * @property {string} oracleBrand
```
Comment (turadg) [inline packages/inter-protocol/src/proposals/addAssetToVault.js]: why allow oracleBrand to be different than issuerName?

Comment (dckc) [reply packages/inter-protocol/src/proposals/addAssetToVault.js]: I don't recall. Perhaps no reason. I suppose the thought at the time of writing was: why constrain them to be the same?

@michaelfig ? maybe you have a more clear idea of the constraints?

Comment (dckc) [reply packages/inter-protocol/src/proposals/addAssetToVault.js]: oh... are you suggesting that `oracleBrand` suffices instead of adding an `issuerName` property? I suppose that could work, though it seems like a stretch.

Comment (turadg) [reply packages/inter-protocol/src/proposals/addAssetToVault.js]: if they don't truly need to be different my suggestion would be to rename the `oracleBrand` property to `issuerName`.

Whether they need to be different… they are different brands but I think it's a source of unnecessary confusion to have different strings, since their different namespaces suffice.

Comment (0xpatrickdev) [reply packages/inter-protocol/src/proposals/addAssetToVault.js]: My 2c - in the event there were ever multiple oracle options for a single asset (say, redemption rate, twap, etc), provided as separate PriceAuthorities, it seems like it'd be beneficial to have `issuerName` and `oracleBrand` decoupled

**Comment by 0xpatrickdev** [comment]
Do we also need to update `/scripts/add-collateral-core.js`?  If I specify an `issuerName` in `interchainAssetOptions` in `/scripts/add-STARS.js`, it is not propagated through to the `getManifestCall` object in the generated script

**Comment by dckc** [comment]
@0xPatrickdev did [some testing and found a problem](https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/issues/16#issuecomment-1688522839)

```
2023-08-22T15:54:16.291Z SwingSet: xsnap: v29: Error: keyword "stATOM" must be an ascii identifier starting with upper case.
 at construct ()
...
 at In "assertUniqueKeyword" method of (InstanceRecord) (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:42)
 at saveIssuer (.../zoe/src/contractFacet/zcfZygote.js:261)
 at saveIssuer (.../zoe/src/contractFacet/zcfZygote.js:257)
 at updateState (.../vats/src/provisionPoolKit.js:344)
 at updateState (.../vats/src/provisionPoolKit.js:342)
```


Looks like we have more keyword/issuerName conflation in provisionPool. :-/

https://github.com/Agoric/agoric-sdk/blob/mainnet1B/packages/vats/src/provisionPoolKit.js#L347

_p.s. for follow-up, see #8238_

File: packages/inter-protocol/src/proposals/addAssetToVault.js [hunk 2]
```diff
@@ -18,7 +18,8 @@ export * from './startPSM.js';
  * @property {number} [decimalPlaces]
  * @property {string} [proposedName]
  * @property {string} keyword
- * @property {string} oracleBrand
+ * @property {string} [issuerName]
+ * @property {string} [oracleBrand]
```
Comment (0xpatrickdev) [inline packages/inter-protocol/src/proposals/addAssetToVault.js]: The new changes since last testing period look good to me (note: just from reading the code, i have yet to try a deployment).  I might suggest adding these comments, or something along these lines, to add more clarity around the parameters:

```suggestion
 * @property {string} keyword - the issuer keyword record for the contract instance
 * @property {string} [issuerName] - defaults to `keyword` if not provided
 * @property {string} [proposedName] - defaults to `issuerName` if not provided
 * @property {string} [oracleBrand] - defaults to `issuerName` if not provided
 ```
 
 (keyword took me a minute to grok, but it's seemingly just for the use case i described)

File: packages/vats/src/mintHolder.js [hunk 3]
```diff
@@ -10,6 +10,8 @@ import {
 /** @typedef {import('@agoric/vat-data').Baggage} Baggage */
 
 /**
+ * NOTE: "keyword" connotes initial caps constraint, which doesn't apply here.
```
Comment (turadg) [inline packages/vats/src/mintHolder.js:13]: consider explaining why the imperfect name remains

File: packages/inter-protocol/src/proposals/addAssetToVault.js [hunk 4]
```diff
@@ -118,11 +128,12 @@ export const registerScaledPriceAuthority = async (
   { options: { interchainAssetOptions } },
 ) => {
   const {
-    keyword,
-    oracleBrand,
+    keyword: kwd,
+    issuerName = kwd,
+    oracleBrand = issuerName,
```
Comment (turadg) [inline packages/inter-protocol/src/proposals/addAssetToVault.js]: You have a nice and clear progressive override below. Why not use it here?

```suggestion
    keyword,
    issuerName = keyword,
    oracleBrand = issuerName,
```

File: packages/inter-protocol/src/proposals/addAssetToVault.js [hunk 5]
```diff
@@ -62,18 +67,23 @@ export const publishInterchainAssetFromBank = async (
...
+  } = interchainAssetOptions;
 
   // Incompatible with issuerBoardId.
   assert.equal(interchainAssetOptions.issuerBoardId, undefined);
   assert.typeof(denom, 'string');
-  assert.typeof(keyword, 'string');
-  assert.typeof(decimalPlaces, 'number');
+  assert.typeof(issuerName, 'string');
   assert.typeof(proposedName, 'string');
+  assert.typeof(decimalPlaces, 'number');
```
Comment (turadg) [inline packages/inter-protocol/src/proposals/addAssetToVault.js]: moving this line looks superfluous to me. If you are going to move it, consider some rational ordering like alphabetical (as you have in the destructuring for this fn

**Review by turadg — APPROVED** [review]
No blockers but please consider the suggestions before merging.

File: packages/vats/src/mintHolder.js (hunk 3 above)
Comment (dckc) [reply packages/vats/src/mintHolder.js:13]: Hm. I considered it, but I don't see a concise explanation.

Changing the name wouldn't require upgrading the existing contract vats. It would just require remembering that the old ones use a different name. It might even be possible to support a new `name` property and deprecate the `keyword` property.

I suppose the real reason the `keyword` name remains is: changing it isn't necessary to address #8235.

Comment (turadg) [reply packages/vats/src/mintHolder.js:13]: > require remembering that the old ones use a different name
That seems reason enough to me. 

> the keyword name remains is: changing it isn't necessary

Fair. Though with this PR that imperfect name is tech debt. We should at least document the rationale to take on the debt.

**Comment by mhofman** [comment]
@mergifyio refresh
