### PR TITLE
swingset: remove no-ses mode

### LINKED ISSUE #721: swingset: remove --no-ses mode
The first step of #477 will be to remove SwingSet's "no-SES" mode. I originally added this mode because SES basically removed the stack tracebacks from Errors, making debugging really painful. But the architectural hijinks needed to support both modes were pretty gross, and now they're really getting in the way. New SES has a `noTameError` flag which addresses most of the debugging information, and the `nestedEvaluate` loader helps to get the filenames right. The debugging experience won't be quite as good as non-SES for a while yet, but I think this is the right point to make the transition.

I've already removed the `useSES=false` tests from other packages (which acquired them via cut-and-paste from swingset tests). So the remaining steps are to remove the non-SES tests from SwingSet itself, disable the flag, and then rip out the non-SES support code. This will pave the way towards the simpler+safer new-SES setup process that #477 addresses.

### PR DESCRIPTION
**Pull request by warner**
This disables SwingSet's "no-SES" mode: it removes all no-ses tests, enforces the `createVatController()` `withSES` flag to be `true`, and removes the now-unused support code.

closes #721

### CODE REVIEW

File: packages/SwingSet/src/controller.js [hunk 1]
```diff
@@ -226,16 +225,10 @@ function buildSESKernel(sesEvaluator, endowments) {
...
-  // Evaluate shims to produce desired globals.
-  const evaluateOptions = makeDefaultEvaluateOptions();
-  // eslint-disable-next-line no-eval
-  (evaluateOptions.shims || []).forEach(shim => (1, eval)(shim));
-
-  return buildKernelNonSES(endowments);
-}
-
 export async function buildVatController(config, withSES = true, argv = []) {
+  if (!withSES) {
```
Comment (FUDCo) [inline packages/SwingSet/src/controller.js:229]: Having a parameter in the middle of the list that's a mandatory `true` seems kinda icky.  Is it too late to fix the API to just get rid of it?

**Review by FUDCo — APPROVED** [review]
Looks fine, aside from the ugly API wart on `buildVatController` that it leaves behind (which is not urgent).  I will change swingset runner to get rid of the `--no-ses` option.

File: packages/SwingSet/src/controller.js (hunk 1 above)
Comment (warner) [reply packages/SwingSet/src/controller.js:229]: Actually I'd say it's too early :). Once this is all done, I'm planning to go through the whole monorepo and find all the calls to `buildVatController` and remove that parameter from all of them (probably turning it into an options bag, or merging it all into the config object). For now, I wanted to minimize changes to downstream users.

Comment (FUDCo) [reply packages/SwingSet/src/controller.js:229]: Yah, I figured as much.  BTW, outside `SwingSet/test` I count 9 calls to `buildVatController`, so we're not looking at a big job.  (And only 3 that aren't _other_ test code.
