### PR TITLE
8445 add promiseWatcher to smartWallet

### LINKED ISSUE #8445: vat-walletFactory upgrade would cause wallet to stop tracking existing offers
## Describe the bug

#8286 describes some problems that vat-walletFactory will have upon upgrade, but merges two separate problems. I'm leaving #8286 to capture what happens to vat-walletFactory when *vat-zoe* is upgraded, and this new ticket captures what happens to vat-walletFactory when vat-walletFactory itself is upgraded:

> Similarly, if the walletFactory is upgraded, the code processing the offer will not resume automatically.

The code in vat-walletFactory which subscribes to `numWantsSatisfied()` and `getPayouts()` and `getOfferResult()` (https://github.com/Agoric/agoric-sdk/blob/d4b32f129868ed2faa32f1bcad51b5d2248d4c14/packages/smart-wallet/src/offers.js) is run in a wallet function named `makeOfferExecutor`, and used by the `executeOffer()` [method](https://github.com/Agoric/agoric-sdk/blob/d4b32f129868ed2faa32f1bcad51b5d2248d4c14/packages/smart-wallet/src/smartWallet.js#L642). As best I can tell, this is the only time these three subscriptions occurs.

So if an offer is opened in vat-walletFactory incarnation-1, then vat-walletFactory is upgraded to incarnation-2, the new incarnation will not be following any of those promises. The seat might still be active, or it might exit some time after the upgrade, but I don't see any code in vat-walletFactory that would notice.

To resolve this, the wallet needs to either:
* 1: after upgrade, in the new incarnation, iterate through all durably-saved seats and re-establish those subscriptions
* 2: establish those subscriptions with a DurablePromiseWatcher in the first place

Fix 1 will require O(N) time spent shortly after upgrade, as it needs to iterate through *all* open seats. Fix 2 avoids O(N) work.

To remediate the problem for existing open seats, we need 1. To avoid making the problem worse, we need 2 as well.

# Deployment Considerations

We need this fix to be included in the next mainnet vat-walletFactory deployment: we cannot safely upgrade vat-walletFactory without it.

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #8445

## Description

Use watchedPromises to monitor expected payouts. This made it necessary to be able to call several functions from more than one location, so a lot of state and behavior that was ephemeral was made durable. I think the code is simpler now.

along the way `payments.tryReclaimingWithdrawnPayments()` went away. I'm pretty sure it was redundant with ERTP recoverySets. If there was other functionality that we should keep, please let me know.

### Security Considerations

offer security, not operational security. Without this fix, wallets wouldn't be able to pay out if the Zoe vat upgraded.

### Scaling Considerations

Repairs all the outstanding seats for each smartWallet on upgrade.

### Documentation Considerations

not applicable

### Testing Considerations

TBD.  Not done yet.

### Upgrade Considerations

It's all about upgrade.

### CODE REVIEW

File: packages/inter-protocol/test/smartWallet/test-psm-integration.js [hunk 1]
```diff
@@ -193,11 +193,6 @@ test('want stable (insufficient funds)', async t => {
     'Withdrawal of {"brand":"[Alleged: AUSD brand]","value":"[20000n]"} failed because the purse only contained {"brand":"[Alleged: AUSD brand]","value":"[10000n]"}';
   const status = computedState.offerStatuses.get('insufficientFunds');
   t.is(status?.error, `Error: ${msg}`);
-  /** @type {[PromiseRejectedResult]} */
-  // @ts-expect-error cast
-  const result = status.result;
-  t.is(result[0].status, 'rejected');
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/test/smartWallet/test-psm-integration.js:198]: The previous code just happened to call `updateStatus` on a `Promise.all()` that covered this case. We get the same results without the `Promise.all()`, so there's nothing to log at that point. The 'rejected' status is redundant with the error detected just above.

File: packages/zoe/src/zoeService/zoeSeat.js [hunk 2]
```diff
@@ -154,12 +153,12 @@ export const makeZoeSeatAdminFactory = baggage => {
...
           // If that happens, we shouldn't re-do any of the work.
           if (state.exiting) {
-            return;
+            return Promise.resolve();
           }
           assertHasNotExited(this, 'Cannot exit seat. Seat has already exited');
 
           state.exiting = true;
-          E.when(
+          return E.when(
```
Comment (dckc) [inline packages/zoe/src/zoeService/zoeSeat.js]: This conflicts with the interface pattern `.returns()`

Comment (Chris-Hibbert) [reply packages/zoe/src/zoeService/zoeSeat.js]: That was temporary debugging state. I did have to fix it, but it's been reverted.

File: packages/inter-protocol/test/smartWallet/test-psm-integration.js (hunk 1 above)
Comment (turadg) [reply packages/inter-protocol/test/smartWallet/test-psm-integration.js:198]: This is a breaking change and why `test-oracle-integration` is failing. When this code handles a rejection: https://github.com/Agoric/agoric-sdk/blob/daf4294bfa2ac36b1f6993bd0dc808bd27393fcf/packages/smart-wallet/src/offerWatcher.js#L182 it's not making it to this error handler: https://github.com/Agoric/agoric-sdk/blob/0e25d18804ffc064554d8ff6a813b70246ce7b1d/packages/smart-wallet/src/smartWallet.js#L843-L844

And so it's not getting thrown https://github.com/Agoric/agoric-sdk/blob/0e25d18804ffc064554d8ff6a813b70246ce7b1d/packages/smart-wallet/src/smartWallet.js#L874 to the `executeOffer` caller. 

It's a smell that there are two error handlers which both do `updateStatus({ error: err.toString() });`. Let's see if we can refactor this to have one error handler that throws and `executeOffer()` waits for the offer to complete.

File: packages/agoric-cli/src/commands/auction.js [hunk 3]
```diff
@@ -150,7 +150,7 @@ export const makeAuctionCommand = (
           path: { paramPath: { key: 'governedParams' } },
         };
 
-        /** @type {import('@agoric/smart-wallet/src/offers.js').OfferSpec} */
+        /** @type {import('@agoric/smart-wallet/src/smartWallet.js').OfferSpec} */
```
Comment (turadg) [inline packages/agoric-cli/src/commands/auction.js]: if we're going to touch all these lines, maybe it's best to move the type into a `types.js` where it can stay. This is part of the external API of the package.

File: packages/boot/test/bootstrapTests/liquidation.ts [hunk 4]
```diff
@@ -63,8 +63,7 @@ export const likePayouts = ({ Bid, Collateral }) => ({
   },
 });
 
-export const makeLiquidationTestContext = async t => {
-  console.time('DefaultTestContext');
+export const makeWalletFactoryContext = async t => {
```
Comment (turadg) [inline packages/boot/test/bootstrapTests/liquidation.ts]: this shouldn't be in `liquidation.ts`. consider a new file, `walletFactory.ts`

File: packages/boot/test/bootstrapTests/test-vaults-integration.ts [hunk 5]
```diff
@@ -136,6 +137,8 @@ test('adjust balances', async t => {
   });
 });
 
+// This test isn't marked .serial, but it depends on previous tests.
```
Comment (turadg) [inline packages/boot/test/bootstrapTests/test-vaults-integration.ts:140]: how can it pass reliably running in parallel with the test it depends on?

File: packages/boot/test/bootstrapTests/test-vaults-integration.ts [hunk 6]
```diff
@@ -171,20 +175,18 @@ test('close vault', async t => {
...
-      Offers.vaults.CloseVault,
-      {
-        offerId: 'close-insufficient',
-        collateralBrandKey,
-        giveMinted: 0.000_001,
-      },
-      'open-vault',
-    ),
+
+  // does not throw, because it's in the result, but it will show up in errors
```
Comment (turadg) [inline packages/boot/test/bootstrapTests/test-vaults-integration.ts]: this is a breaking change to the API. I don't think it's necessary. Let's discuss.

File: packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts [hunk 7]
```diff
@@ -1,53 +1,32 @@
...
-  likePayouts,
   makeLiquidationTestContext,
-  scale6,
   LiquidationSetup,
 } from './liquidation.ts';
 
 const test = anyTest as TestFn<LiquidationTestContext>;
 
-//#region Product spec
 const setup: LiquidationSetup = {
```
Comment (turadg) [inline packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts:17]: why is LiquidationSetup in a test about walletSurvivesZoeRestart?

File: packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts [hunk 8]
```diff
@@ -172,164 +95,38 @@ const checkFlow1 = async (
...
+    updated: 'offerStatus',
+    status: { id: 'open1', numWantsSatisfied: 1 },
+  });
 };
 
-test.serial.failing(
+test.serial(
   'wallet survives zoe null upgrade',
-  checkFlow1,
+  checkFlow,
```
Comment (turadg) [inline packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts]: no point having an Ava macro when there's only one test using it

File: packages/boot/tools/drivers.ts [hunk 9]
```diff
@@ -17,9 +17,9 @@ import type {
   CurrentWalletRecord,
   SmartWallet,
   UpdateRecord,
+  OfferSpec,
 } from '@agoric/smart-wallet/src/smartWallet.js';
 import type { WalletFactoryStartResult } from '@agoric/vats/src/core/startWalletFactory.js';
-import type { OfferSpec } from '@agoric/smart-wallet/src/offers.js';
```
Comment (turadg) [inline packages/boot/tools/drivers.ts]: consider leaving the type where it was, even if the logic had to move

File: packages/builders/scripts/smart-wallet/build-walletFactory-upgrade.js [hunk 10]
```diff
@@ -6,7 +6,7 @@
  */
 
 import { makeHelpers } from '@agoric/deploy-script-support';
-import { getManifestForUpgrade } from '@agoric/smart-wallet/src/proposals/upgrade-walletFactory-proposal.js';
+import { getManifestForUpgrade } from '@agoric/vats/src/proposals/upgrade-wallet-factory-proposal.js';
```
Comment (turadg) [inline packages/builders/scripts/smart-wallet/build-walletFactory-upgrade.js]: why move this?

File: packages/inter-protocol/test/smartWallet/test-oracle-integration.js [hunk 11]
```diff
@@ -575,4 +570,18 @@ test.serial('govern oracles list', async t => {
     }),
     { message: 'pushPrice for disabled oracle' },
   );
+
+  // XXX It looks like the error is being thrown, but it's not getting back here
```
Comment (turadg) [inline packages/inter-protocol/test/smartWallet/test-oracle-integration.js]: it's not being thrown from `executeOffer` as it used to

File: packages/smart-wallet/src/offerWatcher.js [hunk 12]
```diff
@@ -0,0 +1,227 @@
...
+ * error?: string,
+ * numWantsSatisfied?: number
+ * result?: unknown | typeof UNPUBLISHED_RESULT,
+ * payouts?: AmountKeywordRecord,
+ * }} OfferStatus
+ */
+
+const watchForOfferResult = (watcher, seat) => {
+  const rWatcher = watcher.resultWatcher;
+  globalThis.VatData.watchPromise(E(seat).getOfferResult(), rWatcher, seat);
```
Comment (turadg) [inline packages/smart-wallet/src/offerWatcher.js]:
```js
import { watchPromise } from '@agoric/vat-data';
```

File: packages/smart-wallet/src/offerWatcher.js [hunk 13]
```diff
@@ -0,0 +1,227 @@
...
+
+const watchForPayout = (watcher, seat) => {
+  const pWatcher = watcher.paymentWatcher;
+  globalThis.VatData.watchPromise(E(seat).getPayouts(), pWatcher, seat);
+};
+
+export const watchOfferOutcomes = (watcher, seat) => {
+  watchForPayout(watcher, seat);
+  watchForNumWants(watcher, seat);
+  watchForOfferResult(watcher, seat);
```
Comment (turadg) [inline packages/smart-wallet/src/offerWatcher.js]: the helper methods maybe obscure more than clarify. consider inlining

```suggestion
export const watchOfferOutcomes = (watcher, seat) => {
  watchPromise(E(seat).getOfferResult(), watcher.resultWatcher, seat);
  watchPromise(E(seat).numWantsSatisfied(), watcher.numWantsWatcher, seat);
  watchPromise(E(seat).getPayouts(), watcher.paymentWatcher, seat);
};
```

Comment (turadg) [reply packages/smart-wallet/src/offerWatcher.js]: also please annotate the params

File: packages/smart-wallet/src/smartWallet.js [hunk 14]
```diff
@@ -433,7 +488,9 @@ export const prepareSmartWallet = (baggage, shared) => {
               helper.updateBalance(purse, balance);
             },
             fail(reason) {
-              console.error(address, `failed updateState observer`, reason);
+              console.error(
+                `*** ${address} failed updateState observer, ${reason} ***`,
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: why the stars?

File: packages/smart-wallet/src/smartWallet.js [hunk 15]
```diff
@@ -725,7 +954,10 @@ export const prepareSmartWallet = (baggage, shared) => {
           return this.state.updateRecorderKit.subscriber;
         },
         getPublicTopics() {
-          const { currentRecorderKit, updateRecorderKit } = this.state;
+          const {
+            state: { currentRecorderKit, updateRecorderKit },
+          } = this;
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: this is a change in style. what motivates it? do you think it should be used generally?

File: packages/store/package.json [hunk 16]
```diff
@@ -31,6 +31,7 @@
   "homepage": "https://github.com/Agoric/agoric-sdk#readme",
   "dependencies": {
     "@agoric/assert": "^0.6.0",
+    "@agoric/time": "^0.3.2",
```
Comment (turadg) [inline packages/store/package.json]: why?

File: packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js
Comment (turadg) [inline packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js:1]: these changes are out of scope of the PR. I imagine they were helpful for debugging but do they need to be included? They need different reviewers so I suggest pulling them out into a different PR

File: packages/wallet/api/src/lib-wallet.js [hunk 17]
```diff
@@ -838,7 +838,7 @@ export function makeWalletRoot({
         );
       },
       fail(reason) {
-        console.error(`failed updateState observer`, reason);
+        console.error(`+++failed updateState observer ${reason}+++`);
```
Comment (turadg) [inline packages/wallet/api/src/lib-wallet.js]: why?

File: packages/agoric-cli/src/commands/auction.js (hunk 3 above)
Comment (Chris-Hibbert) [reply packages/agoric-cli/src/commands/auction.js]: Can we have both types.js and types.d.ts in the same directory, or should they go into types.d.ts?

File: packages/smart-wallet/src/offerWatcher.js (hunk 13 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/offerWatcher.js]: The helper methods area also called in the watchers on disconnections.

Comment (Chris-Hibbert) [reply packages/smart-wallet/src/offerWatcher.js]: I tried declaring `watcher` to be ` {ReturnType<MakeOfferWatcher>}`, but tsc says 
```
src/offerWatcher.js:195:28 - error TS2345: Argument of type '{ helper: { updateStatus(offerStatusUpdates: any): void; onNewContinuingOffer(offerId: any, invitationAmount: any, invitationMakers: any, publicSubscribers: any): void; publishResult(result: any): void; exitOpenSeat(reason: any): never; }; paymentWatcher: { ...; }; resultWatcher: { ...; }; numWantsWatcher: { ...; }; }' is not assignable to parameter of type '{ helper: { updateStatus(offerStatusUpdates: any): void; onNewContinuingOffer(offerId: any, invitationAmount: any, invitationMakers: any, publicSubscribers: any): void; publishResult(result: any): void; exitOpenSeat(reason: any): never; }; paymentWatcher: { ...; }; resultWatcher: { ...; }; numWantsWatcher: { ...; };...'.
  Type '{ helper: { updateStatus(offerStatusUpdates: any): void; onNewContinuingOffer(offerId: any, invitationAmount: any, invitationMakers: any, publicSubscribers: any): void; publishResult(result: any): void; exitOpenSeat(reason: any): never; }; paymentWatcher: { ...; }; resultWatcher: { ...; }; numWantsWatcher: { ...; }; }' is missing the following properties from type 'RemotableBrand<{}, { helper: { updateStatus(offerStatusUpdates: any): void; onNewContinuingOffer(offerId: any, invitationAmount: any, invitationMakers: any, publicSubscribers: any): void; publishResult(result: any): void; exitOpenSeat(reason: any): never; }; paymentWatcher: { ...; }; resultWatcher: { ...; }; numWant...': L, R
```
which I don't understand.

File: packages/boot/test/bootstrapTests/test-vaults-integration.ts (hunk 5 above)
Comment (Chris-Hibbert) [reply packages/boot/test/bootstrapTests/test-vaults-integration.ts:140]: I don't understand why. I blame ava for enforcing more dependency between tests than it should. 
I added this comment because some combinations of `test.only()` don't work.  `test.serial()` doesn't seem to be necessary, but I'll add it if you prefer that to the comment.

File: packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts (hunk 7 above)
Comment (Chris-Hibbert) [reply packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts:17]: in order to test that the wallets survive, it's using a vaultLiquidation scenario to exercise the vaults.

File: packages/boot/tools/drivers.ts (hunk 9 above)
Comment (Chris-Hibbert) [reply packages/boot/tools/drivers.ts]: done

File: packages/builders/scripts/smart-wallet/build-walletFactory-upgrade.js (hunk 10 above)
Comment (Chris-Hibbert) [reply packages/builders/scripts/smart-wallet/build-walletFactory-upgrade.js]: I'm probably confused about something, but there wasn't a copy of the relevant file in `smart-wallet/src/proposals`,  but there was in `vats/src/proposals/`.

File: packages/smart-wallet/src/offerWatcher.js (hunk 12 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/offerWatcher.js]: done

File: packages/smart-wallet/src/smartWallet.js (hunk 14 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: I think I was making it more visible. I'll replace it with '🚨'.

File: packages/smart-wallet/src/smartWallet.js (hunk 15 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: I think we do this occasionally. I did it here because those names were used a few times each.  I'll revert rather than figure out whether it's common.

File: packages/store/package.json (hunk 16 above)
Comment (Chris-Hibbert) [reply packages/store/package.json]: No longer needed.

File: packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js
Comment (Chris-Hibbert) [reply packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js:1]: AIR, they were necessary to allow tests to pass. The fakeVirtual tooling wasn't prepared for WatchedPromises. This code came via @warner, so hopefully he can approve relatively quickly.  I'll add him to the review.

File: packages/wallet/api/src/lib-wallet.js (hunk 17 above)
Comment (Chris-Hibbert) [reply packages/wallet/api/src/lib-wallet.js]: dunno. I'll revert.

File: packages/boot/test/bootstrapTests/liquidation.ts (hunk 4 above)
Comment (Chris-Hibbert) [reply packages/boot/test/bootstrapTests/liquidation.ts]: done

File: packages/store/package.json (hunk 16 above)
Comment (Chris-Hibbert) [reply packages/store/package.json]: I undid my reversion. Without it (notice that it's also present in `devDependencies`) tests don't build.

Comment (turadg) [reply packages/store/package.json]: oh that's because of another problem: this has @agoric/smart-wallet depending on the 'tests' dir of @agoric/store. That's an encapsulation violation.

instead, `@agoric/store` should be left alone and this line,
```js
import { AmountShape } from '@agoric/store/test/borrow-guards.js';
```
should be,
```js
import { AmountShape } from '@agoric/ertp/src/typeGuards.js';
```

File: packages/builders/scripts/smart-wallet/build-walletFactory-upgrade.js (hunk 10 above)
Comment (turadg) [reply packages/builders/scripts/smart-wallet/build-walletFactory-upgrade.js]: In master I see the file `packages/smart-wallet/src/proposals/upgrade-walletFactory-proposal.js` and when I run `agoric run scripts/smart-wallet/build-walletFactory-upgrade.js` it works.

Please revert moving the file. The proposal is about wallet-factory so belongs in smart-wallet.

File: packages/inter-protocol/test/smartWallet/test-oracle-integration.js [hunk 18]
```diff
@@ -154,7 +154,7 @@ const acceptInvitation = async (wallet, priceAggregator) => {
 
 let pushPriceCounter = 0;
 /**
- * @param {any} wallet
+ * @param {import('@agoric/smart-wallet/src/smartWallet.js').SmartWallet} wallet
```
Comment (turadg) [inline packages/inter-protocol/test/smartWallet/test-oracle-integration.js:157]: love to see it

File: packages/smart-wallet/src/invitations.js [hunk 19]
```diff
@@ -166,3 +166,5 @@ export const makeInvitationsHelper = (
   return invitationFromSpec;
 };
 harden(makeInvitationsHelper);
+
+/** @typedef {ReturnType<makeInvitationsHelper>} InvitationFromSpec */
```
Comment (turadg) [inline packages/smart-wallet/src/invitations.js]: this type is just `ERef<Invitation>`. it shouldn't matter where an invitation comes from.
```suggestion
```

File: packages/smart-wallet/test/test-addAsset.js [hunk 20]
```diff
@@ -376,8 +376,10 @@ test.serial('trading in non-vbank asset: game real-estate NFTs', async t => {
     );
     const wallet = simpleProvideWallet(addr);
     t.log('deposit', istQty, 'IST into wallet of', addr);
-    await E(E(wallet).getDepositFacet()).receive(spendingPmt);
+
+    // order of updates changed so offerStatus might not be last
```
Comment (turadg) [inline packages/smart-wallet/test/test-addAsset.js]: did the order of updates need to change?

File: packages/smart-wallet/test/test-addAsset.js [hunk 21]
```diff
@@ -418,10 +420,21 @@ test.serial('trading in non-vbank asset: game real-estate NFTs', async t => {
...
+    // status update used to be last, but now we have to look for the right one
+    let record = await E(updates).subscribeAfter();
+    while (
+      record.head.value.updated !== 'offerStatus' ||
+      !record.head.value.status.numWantsSatisfied ||
+      !record.head.value.status.payouts?.Places
+    ) {
+      record = await E(updates).subscribeAfter(record.publishCount);
+    }
+    const update = record.head.value;
```
Comment (turadg) [inline packages/smart-wallet/test/test-addAsset.js]: please pull this out into a helper function

File: packages/smart-wallet/test/test-addAsset.js [hunk 22]
```diff
@@ -495,13 +507,15 @@ test.serial('non-vbank asset: give before deposit', async t => {
       proposal: { give, want },
     });
     t.log('goofy client: propose to give', choices.join(', '));
-    await E(walletBridge).proposeOffer(ctx.fromBoard.toCapData(offer1));
+    await t.throwsAsync(
+      () => E(walletBridge).proposeOffer(ctx.fromBoard.toCapData(offer1)),
+      { message: /Withdrawal of .* failed because the purse only contained/ },
```
Comment (turadg) [inline packages/smart-wallet/test/test-addAsset.js]: why did this change? I suspect it's not necessary

File: packages/swingset-liveslots/tools/fakeVirtualSupport.js [hunk 23]
```diff
@@ -2,8 +2,9 @@
 /* eslint-disable max-classes-per-file */
 import { makeMarshal } from '@endo/marshal';
 import { assert } from '@agoric/assert';
-import { parseVatSlot } from '../src/parseVatSlots.js';
+import { isPromise } from '@endo/promise-kit';
 
+import { makeVatSlot, parseVatSlot } from '../src/parseVatSlots.js';
```
Comment (turadg) [inline packages/swingset-liveslots/tools/fakeVirtualSupport.js]: lint

File: packages/swingset-liveslots/tools/fakeVirtualSupport.js
Comment (turadg) [inline packages/swingset-liveslots/tools/fakeVirtualSupport.js:1]: consider landing the liveslots changes in different PR, with a review by @FUDCo

File: packages/vats/src/proposals/upgrade-wallet-factory-proposal.js [hunk 24]
```diff
@@ -0,0 +1,58 @@
+// @ts-check
```
Comment (turadg) [inline packages/vats/src/proposals/upgrade-wallet-factory-proposal.js]: this is redundant since a couple days ago when this package started linting all JS
```suggestion
```

File: packages/boot/test/bootstrapTests/test-vaults-integration.ts (hunk 5 above)
Comment (turadg) [reply packages/boot/test/bootstrapTests/test-vaults-integration.ts:140]: I think this is brittle but solving it is out of scope. Filed as https://github.com/Agoric/agoric-sdk/issues/8613

File: packages/boot/test/bootstrapTests/test-vaults-integration.ts [hunk 25]
```diff
@@ -171,20 +175,21 @@ test('close vault', async t => {
...
-        offerId: 'close-insufficient',
-        collateralBrandKey,
-        giveMinted: 0.000_001,
-      },
-      'open-vault',
-    ),
-    {
-      message,
-    },
+    () =>
```
Comment (turadg) [inline packages/boot/test/bootstrapTests/test-vaults-integration.ts]: why is this now necessary?

File: packages/boot/test/bootstrapTests/test-vaults-integration.ts [hunk 26]
```diff
@@ -226,14 +234,19 @@ test('open vault with insufficient funds gives helpful error', async t => {
...
+      wd.executeOfferMaker(Offers.vaults.OpenVault, {
+        offerId: 'open-vault',
+        collateralBrandKey,
+        giveCollateral,
+        wantMinted,
+      }),
+    {
+      message:
+        'Proposed debt {"brand":"[Alleged: IST brand]","value":"[904500000n]"} exceeds max {"brand":"[Alleged: IST brand]","value":"[63462857n]"} for {"brand":"[Alleged: ATOM brand]","value":"[9000000n]"} collateral',
+    },
```
Comment (turadg) [inline packages/boot/test/bootstrapTests/test-vaults-integration.ts]: `const message` is defined above. If you want to inline this please remove that declaration

File: packages/smart-wallet/src/offerWatcher.js [hunk 27]
```diff
@@ -0,0 +1,267 @@
...
+    onFulfilled: M.call(M.any(), SeatShape).returns(),
+    onRejected: M.call(M.any(), SeatShape).returns(),
+  }),
+  numWantsWatcher: M.interface('numWantsWatcher', {
+    onFulfilled: M.call(M.number(), SeatShape).returns(),
+    onRejected: M.call(M.any(), SeatShape).returns(),
+  }),
+});
+
+export const makeOfferWatcherMaker = baggage => {
```
Comment (turadg) [inline packages/smart-wallet/src/offerWatcher.js]: this is our convention:
```suggestion
export const prepareOfferWatcher = baggage => {
```

File: packages/smart-wallet/src/offerWatcher.js [hunk 28]
```diff
@@ -0,0 +1,267 @@
...
+         */
+        onRejected(err, seat) {
+          const { facets } = this;
+
+          if (isUpgradeDisconnection(err)) {
+            void watchForPayout(facets, seat);
+          } else {
+            facets.helper.updateStatus({ error: err.toString() });
+            facets.helper.exitOpenSeat();
+          }
```
Comment (turadg) [inline packages/smart-wallet/src/offerWatcher.js]: these three rejection handlers have the same logic save for the callback. please DRY.

e.g.
```suggestion
          facets.helper.handleError(err, seat, watchForPayout);
```

File: packages/smart-wallet/src/smartWallet.js [hunk 29]
```diff
@@ -315,10 +351,27 @@ export const prepareSmartWallet = (baggage, shared) => {
         .returns(M.promise()),
       publishCurrentState: M.call().returns(),
       watchPurse: M.call(M.eref(PurseShape)).returns(M.promise()),
+      repairUnwatchedSeats: M.call().returns(),
+      updateStatus: M.call(M.any(), M.string()).returns(),
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: this would take UpdateStatusShape if there was one. since this is a helper method I think this is okay

File: packages/smart-wallet/src/smartWallet.js [hunk 30]
```diff
@@ -494,6 +551,112 @@ export const prepareSmartWallet = (baggage, shared) => {
...
+          const { state, facets } = this;
+          const { address, invitationPurse } = state;
+          const { liveOffers, liveOfferSeats } = state;
+          const { zoe, agoricNames } = shared;
+          const { invitationBrand, invitationIssuer } = shared;
+
+          if (baggage.has(REPAIRED_UNWATCHED_SEATS)) {
+            return;
+          }
+          baggage.init(REPAIRED_UNWATCHED_SEATS, true);
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: A boolean makes it looks like it could be false. Since the value is never read, use a sentinel like 'present'.

Or confirm the value is true.

File: packages/smart-wallet/src/smartWallet.js [hunk 31]
```diff
@@ -494,6 +551,112 @@ export const prepareSmartWallet = (baggage, shared) => {
...
+              offerSpec,
+              address,
+              E(invitationIssuer).getAmountOf(invitation),
+              seat,
+            );
+
+            void watchOfferOutcomes(watcher, seat);
+          }
+        },
+        updateStatus(offerStatus, address) {
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: please annotate param types

File: packages/smart-wallet/src/smartWallet.js [hunk 32]
```diff
@@ -537,118 +704,182 @@ export const prepareSmartWallet = (baggage, shared) => {
...
+          const { address, invitationPurse } = state;
+          const { zoe, agoricNames } = shared;
+          const { invitationBrand, invitationIssuer } = shared;
 
           facets.helper.assertUniqueOfferId(String(offerSpec.id));
 
-          const logger = {
-            info: (...args) => console.info('wallet', address, ...args),
-            error: (...args) => console.error('wallet', address, ...args),
-          };
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js:566]: please restore the logger so that error output includes the wallet addr.

these no longer do:
```
console.error('OFFER ERROR:', err);
console.error('recovery failed reclaiming payments', e),
```

Consider changing the name so the point of the logger object is more apparent

File: packages/smart-wallet/src/offerWatcher.js (hunk 28 above)
Comment (turadg) [reply packages/smart-wallet/src/offerWatcher.js]: also, isn't the `updateStatus` redundant with the one in `smartWallet.js`? Please confirm whether these are necessary here.

I'm pretty sure both the logging and the seat exiting are handled in smartWallet's error handler. If so, then this is just,
```suggestion
          if (isUpgradeDisconnection(err)) {
            void watchForPayout(facets, seat);
          }
```
In which case it's better not to make a helper. It's pretty DRY as is.

**Review by turadg — CHANGES_REQUESTED** [review]

File: packages/boot/test/bootstrapTests/test-vaults-integration.ts (hunk 25 above)
Comment (Chris-Hibbert) [reply packages/boot/test/bootstrapTests/test-vaults-integration.ts]: Apparently it isn't, so I've reverted the change.

I don't understand why it's not necessary. My understanding of `throwsAsync()` is that it takes a thunk as its first argument, and `wd.executeOfferMaker()` doesn't look like it returns a thunk. What am I missing?

File: packages/boot/test/bootstrapTests/test-vaults-integration.ts (hunk 26 above)
Comment (Chris-Hibbert) [reply packages/boot/test/bootstrapTests/test-vaults-integration.ts]: reverted

File: packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts (hunk 8 above)
Comment (Chris-Hibbert) [reply packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts]: done

File: packages/vats/src/proposals/upgrade-wallet-factory-proposal.js (hunk 24 above)
Comment (Chris-Hibbert) [reply packages/vats/src/proposals/upgrade-wallet-factory-proposal.js]: done

File: packages/builders/scripts/smart-wallet/build-walletFactory-upgrade.js (hunk 10 above)
Comment (Chris-Hibbert) [reply packages/builders/scripts/smart-wallet/build-walletFactory-upgrade.js]: I think I see the problem.  I wanted a new file `upgrade-wallet-factory.js`, but it has the same name as a generated file. I didn't understand what the `upgrade-walletFactory-proposal.js` in `.../smart-wallet` was doing, and why it wasn't redundant with the new one I wanted.  

I now see that that one was for the earlier smart-wallet upgrade (which I was unaware of). I've renamed the new one (and added it to the PR) as `upgrade-wallet-factory2.js` and `upgrade-walletFactory2-proposal.js`.

Should those be in `../smart-wallet` rather than `../vats` and `../builders` ?

File: packages/inter-protocol/test/smartWallet/test-psm-integration.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/test/smartWallet/test-psm-integration.js:198]: this 'rejected' status came from `tryReclaimingWithdrawnPayments()`, which failed because the error happened before there was a seat. insufficientFunds was detected while attempting to create the payment to send to Zoe, so Zoe was never called.

The new approach doesn't attempt to collect those payments, so the `rejected` status is never set, which I think is fine. `status.error` tells all that needs to be understood.

`test-oracle-integration` now passes because of your fixes that pass the error through `executeOffer`.

File: packages/smart-wallet/src/invitations.js (hunk 19 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/invitations.js]: dropped

File: packages/smart-wallet/src/offerWatcher.js (hunk 27 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/offerWatcher.js]: fixed

File: packages/smart-wallet/src/offerWatcher.js (hunk 28 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/offerWatcher.js]: correct on all counts.

File: packages/smart-wallet/src/smartWallet.js (hunk 30 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: done

File: packages/smart-wallet/src/smartWallet.js (hunk 31 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: done

File: packages/smart-wallet/src/smartWallet.js (hunk 32 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js:566]: Done.  (There's no need to pass it around, so it's now just a pair of functions in `helper`.

File: packages/smart-wallet/test/test-addAsset.js (hunk 22 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/test/test-addAsset.js]: I don't understand why the behavior changed significantly. The description of the scenario says that it's trying to give an amount that's not in the purse, and it correctly fails to do so. Previously it correctly failed to do so, but discovered it later.  

I'm doing things slightly differently in `withdrawGive()`, since `paymentToPurse` had to be replaced with a store, but I don't see how the caller of `withdrawGive()` has any different error timing than before.

File: packages/swingset-liveslots/tools/fakeVirtualSupport.js (hunk 23 above)
Comment (Chris-Hibbert) [reply packages/swingset-liveslots/tools/fakeVirtualSupport.js]: done

File: packages/swingset-liveslots/tools/fakeVirtualSupport.js
Comment (Chris-Hibbert) [reply packages/swingset-liveslots/tools/fakeVirtualSupport.js:1]: Good idea: #8618

File: packages/smart-wallet/test/test-addAsset.js (hunk 21 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/test/test-addAsset.js]: no longer needed.

File: packages/smart-wallet/test/test-addAsset.js (hunk 20 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/test/test-addAsset.js]: No, I was able to revert these changes.

File: packages/agoric-cli/src/commands/auction.js (hunk 3 above)
Comment (turadg) [reply packages/agoric-cli/src/commands/auction.js]: `foo.d.ts` defines the types of a `foo.js`. the importer doesn't know what the syntax is; it always imports the `.js` extension.

so by `into a `types.js`" I meant into whatever file is expressing the types for `types.js`

File: packages/swingset-liveslots/tools/fakeVirtualSupport.js
Comment (turadg) [reply packages/swingset-liveslots/tools/fakeVirtualSupport.js:1]: I see 8618 landed. This still has changes to swingset-liveslots butI suppose those will go away when this is updated with master

File: packages/boot/test/bootstrapTests/test-vaults-integration.ts (hunk 25 above)
Comment (turadg) [reply packages/boot/test/bootstrapTests/test-vaults-integration.ts]: `throws` takes a thunk.
`throwsAsync` takes a promise. 

Think of the latter as "rejects". There's no throwing in this scope so no need to thunk it.

File: packages/builders/scripts/vats/upgrade-wallet-factory2.js
Comment (turadg) [inline packages/builders/scripts/vats/upgrade-wallet-factory2.js:1]: this and its script belong in `smart-wallet` like the other `upgrade-wallet-factory`

File: packages/smart-wallet/src/smartWallet.js [hunk 33]
```diff
@@ -422,7 +479,7 @@ export const prepareSmartWallet = (baggage, shared) => {
             E(purse).getCurrentAmount(),
             balance => helper.updateBalance(purse, balance),
             err =>
-              console.error(
+              facets.helper.consoleError(
                 address,
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: provided by consoleError
```suggestion
```

File: packages/smart-wallet/src/smartWallet.js [hunk 34]
```diff
@@ -433,7 +490,9 @@ export const prepareSmartWallet = (baggage, shared) => {
               helper.updateBalance(purse, balance);
             },
             fail(reason) {
-              console.error(address, `failed updateState observer`, reason);
+              facets.helper.consoleError(
+                `⚠️ ${address} failed updateState observer, ${reason}`,
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: address provided by consoleError
```suggestion
                '⚠️ failed updateState observer', reason,
```

File: packages/smart-wallet/src/smartWallet.js [hunk 35]
```diff
@@ -494,6 +553,121 @@ export const prepareSmartWallet = (baggage, shared) => {
...
+          const purse = await facets.helper.getPurseIfKnownBrand(
+            brand,
+            shared.agoricNames,
+          );
+          if (purse) {
+            return purse;
+          }
+          throw Fail`cannot find/make purse for ${brand}`;
+        },
+        consoleInfo(...args) {
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: consider something that indicates why to use this. e.g. `logWalletInfo` / `logWalletError`

File: packages/smart-wallet/src/smartWallet.js [hunk 36]
```diff
@@ -666,14 +907,19 @@ export const prepareSmartWallet = (baggage, shared) => {
...
           /** @param {Error} err */
           const recordError = err => {
             const { address, updateRecorderKit } = this.state;
-            console.error('wallet', address, 'handleBridgeAction error:', err);
+            facets.helper.consoleError(
+              'wallet',
+              address,
+              'handleBridgeAction error:',
+              err,
+            );
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]:
```suggestion
            facets.helper.consoleError(
              'handleBridgeAction error:',
              err,
            );
```

File: packages/smart-wallet/src/smartWallet.js [hunk 37]
```diff
@@ -725,17 +971,18 @@ export const prepareSmartWallet = (baggage, shared) => {
...
-              storagePath: currentRecorderKit.recorder.getStoragePath(),
+              subscriber: state.currentRecorderKit.subscriber,
+              storagePath: state.currentRecorderKit.recorder.getStoragePath(),
             },
             updates: {
               description: 'Changes to wallet',
-              subscriber: updateRecorderKit.subscriber,
-              storagePath: updateRecorderKit.recorder.getStoragePath(),
+              subscriber: state.updateRecorderKit.subscriber,
+              storagePath: state.updateRecorderKit.recorder.getStoragePath(),
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: unnecessary change. please revert

File: packages/smart-wallet/src/smartWallet.js [hunk 38]
```diff
@@ -747,6 +994,7 @@ export const prepareSmartWallet = (baggage, shared) => {
         const { helper } = facets;
 
         void helper.watchPurse(invitationPurse);
+        helper.repairUnwatchedSeats();
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: please explain why this is called when a smart wallet is created. The timing of this is unclear to me. The sentinel in the contract's own baggage so it'll only ever be performed once per contract vat. But it doesn't happen until a new wallet is made. ???

**Review by turadg — CHANGES_REQUESTED** [review]
I'll review again when it's rebased onto master. Feel free to squash the fixups into earlier commits.

File: packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js
Comment (Chris-Hibbert) [reply packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js:1]: #8618 has been merged to master.

File: packages/builders/scripts/vats/upgrade-wallet-factory2.js
Comment (Chris-Hibbert) [reply packages/builders/scripts/vats/upgrade-wallet-factory2.js:1]: done

File: packages/smart-wallet/src/smartWallet.js (hunk 33 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: fixed

File: packages/smart-wallet/src/smartWallet.js (hunk 34 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: fixed

File: packages/smart-wallet/src/smartWallet.js (hunk 35 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: done

File: packages/smart-wallet/src/smartWallet.js (hunk 36 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: done

File: packages/smart-wallet/src/smartWallet.js (hunk 37 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: I don't see it. These are no longer lexical, and have to be retrieved from state. The only bare `currentRecorderKit` or `updateRecorderKit` are in `init`.

File: packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts [hunk 39]
```diff
@@ -65,96 +44,30 @@ const setup: LiquidationSetup = {
...
-    placeBids,
-    controller,
-    buildProposal,
-  } = t.context;
   const { EV } = t.context.runUtils;
 
-  const buildAndExecuteProposal = async packageSpec => {
+  const buyer = await walletFactoryDriver.provideSmartWallet('agoric1buyer');
+
+  const buildAndExecuteProposal = async (packageSpec: string) => {
```
Comment (turadg) [inline packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts:70]: Out of scope but we should move this to SwingsetTestKit

File: packages/smart-wallet/package.json [hunk 40]
```diff
@@ -27,6 +27,7 @@
   "dependencies": {
     "@agoric/assert": "^0.6.0",
     "@agoric/casting": "^0.4.2",
+    "@agoric/deploy-script-support": "^0.10.3",
```
Comment (turadg) [inline packages/smart-wallet/package.json]: this is only here for `upgrade-wallet-factory2.js` in smart-wallet/proposals. But it's not a proposal; it's a builder. Please move to `packages/builders/scripts/smart-wallet`
```suggestion
```

File: packages/smart-wallet/src/proposals/upgrade-wallet-factory2.js [hunk 41]
```diff
@@ -0,0 +1,29 @@
+import { makeHelpers } from '@agoric/deploy-script-support';
+
+/**
+ * @file
+ *   `agoric run scripts/vats/upgrade-wallet-factory2.js | tee run-report.txt`
```
Comment (turadg) [inline packages/smart-wallet/src/proposals/upgrade-wallet-factory2.js]: please remove the `tee` since nothing here depend on it

File: packages/smart-wallet/src/smartWallet.js [hunk 42]
```diff
@@ -218,6 +249,12 @@ export const prepareSmartWallet = (baggage, shared) => {
       invitationDisplayInfo: DisplayInfoShape,
       publicMarshaller: M.remotable('Marshaller'),
       zoe: M.eref(M.remotable('ZoeService')),
+
+      // known only to smartWallets and walletFactory, this allows the
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js:253]: clever

File: packages/smart-wallet/src/smartWallet.js [hunk 43]
```diff
@@ -315,10 +356,30 @@ export const prepareSmartWallet = (baggage, shared) => {
...
+      addContinuingOffer: M.call(
+        M.or(M.number(), M.string()),
+        AmountShape,
+        M.remotable('InvitationMaker'),
+        M.or(M.record(), M.undefined()),
+      ).returns(M.promise()),
+      purseForBrand: M.call(BrandShape).returns(M.promise()),
+      logWalletInfo: M.call(M.any()).returns(),
+      logWalletError: M.call(M.any()).returns(),
+      // XXX is there a better guard for a bigMapStore?
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]:
```suggestion
      // XXX is there a tighter shape for a bigMapStore than M.any()?
```

fwiw I don't think so

File: packages/smart-wallet/src/smartWallet.js (hunk 37 above)
Comment (turadg) [reply packages/smart-wallet/src/smartWallet.js]: Agree they have to come out of state. I think this will read more clearly but not a blocker
```js
          const { state } = this;
          const { currentRecorderKit, updateRecorderKIt } = state;
```

File: packages/smart-wallet/src/smartWallet.js [hunk 44]
```diff
@@ -494,6 +560,152 @@ export const prepareSmartWallet = (baggage, shared) => {
           void helper.watchPurse(purse);
           return purse;
         },
+
+        // see https://github.com/Agoric/agoric-sdk/issues/8445 and
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: please use jsdoc so the comment appears in tooltips

File: packages/smart-wallet/src/smartWallet.js [hunk 45]
```diff
@@ -718,27 +999,41 @@ export const prepareSmartWallet = (baggage, shared) => {
...
             updates: {
               description: 'Changes to wallet',
-              subscriber: updateRecorderKit.subscriber,
-              storagePath: updateRecorderKit.recorder.getStoragePath(),
+              subscriber: state.updateRecorderKit.subscriber,
+              storagePath: state.updateRecorderKit.recorder.getStoragePath(),
             },
           });
         },
+        // one-time use function. Remove this and repairUnwatchedSeats once the
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: please use jsdoc so the comment appears in tooltips

File: packages/smart-wallet/src/walletFactory.js [hunk 46]
```diff
@@ -220,6 +223,13 @@ export const prepare = async (zcf, privateArgs, baggage) => {
 
   const registry = makeAssetRegistry(assetPublisher);
 
+  // An object known only to walletFactory and smartWallets. The WalletFactory
```
Comment (turadg) [inline packages/smart-wallet/src/walletFactory.js]: please use jsdoc so the comment appears in tooltips

File: packages/smart-wallet/src/walletFactory.js [hunk 47]
```diff
@@ -237,6 +248,19 @@ export const prepare = async (zcf, privateArgs, baggage) => {
...
   const makeSmartWallet = prepareSmartWallet(baggage, shared);
 
+  // One time repair for incarnation 2. We're adding WatchedPromises to allow
+  // wallets to durably monitor offer outcomes, but wallets that already exist
+  // need to be backfilled. This code needs to run once at the beginning of
+  // incarnation 2, and then shouldn't be needed again.
+  if (!baggage.has(UPGRADE_TO_INCARNATION_TWO)) {
+    trace('Wallet Factory upgrading to incarnation 2');
+
+    for (const wallet of walletsByAddress.values()) {
```
Comment (turadg) [inline packages/smart-wallet/src/walletFactory.js:266]: perhaps worth commenting that this can take a long while, and we expect it to run during an upgrade handler, between blocks

File: packages/smart-wallet/src/walletFactory.js [hunk 48]
```diff
@@ -237,6 +248,19 @@ export const prepare = async (zcf, privateArgs, baggage) => {
...
+      wallet.repairWalletForIncarnation2(upgradeToIncarnation2Key);
+    }
+    baggage.init(UPGRADE_TO_INCARNATION_TWO, 'done');
```
Comment (turadg) [inline packages/smart-wallet/src/walletFactory.js:269]: "done" sounds like it will be read but it's not an invariant. Perhaps we need a common value or pattern for keys for which the value is meaningless. Even `null` or `undefined` would work here.

```suggestion
    baggage.init(UPGRADE_TO_INCARNATION_TWO, 'keypresent');
```

File: packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/walletFactory-V2.js [hunk 49]
```diff
@@ -78,6 +78,13 @@ export const prepare = async (zcf, privateArgs, baggage) => {
 
   const registry = makeAssetRegistry(assetPublisher);
 
+  // An object known only to walletFactory and smartWallets. The WalletFactory
```
Comment (turadg) [inline packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/walletFactory-V2.js:81]: when updating the primary version, reminder to make this match

File: packages/smart-wallet/test/test-addAsset.js (hunk 22 above)
Comment (turadg) [reply packages/smart-wallet/test/test-addAsset.js]: Please revert the change error checking change. I confirmed it's not necessary using,
```
git checkout master test/test-addAsset.js
yarn test test/test-addAsset.js
```

**Review by turadg — COMMENTED** [review]
Please change the conventional commit tag from `refactor` to `feat`. It's new functionality. E.g.
```
feat: smartWallet v2 with watchedPromises
```

File: packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts (hunk 39 above)
Comment (dckc) [reply packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts:70]: take care to pass I/O access explicitly when doing so.

File: packages/smart-wallet/src/proposals/upgrade-wallet-factory2.js (hunk 41 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/proposals/upgrade-wallet-factory2.js]: done

File: packages/smart-wallet/src/smartWallet.js (hunk 44 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: done

File: packages/smart-wallet/src/smartWallet.js (hunk 37 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: Thanks.

File: packages/smart-wallet/src/smartWallet.js (hunk 45 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: done

File: packages/smart-wallet/src/walletFactory.js (hunk 46 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/walletFactory.js]: done

File: packages/smart-wallet/src/walletFactory.js (hunk 47 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/walletFactory.js:266]: done

File: packages/smart-wallet/src/walletFactory.js (hunk 48 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/walletFactory.js:269]: > Perhaps we need a common value or pattern for keys for which the value is meaningless.

Apparently. I think you've made the same comment before (for a similar use), but with a different suggested name. I don't favor `'keypresent'`, but would be happy with 'defined', 'present', or 'plugh'. I don't think it takes long to verify that the value doesn't matter.

File: packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/walletFactory-V2.js (hunk 49 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/walletFactory-V2.js:81]: done

File: packages/smart-wallet/test/test-addAsset.js (hunk 22 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/test/test-addAsset.js]: done

File: packages/smart-wallet/package.json (hunk 40 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/package.json]: done

**Comment by Chris-Hibbert** [comment]
@dckc, are you willing/able to approve this PR for merging. I believe I've addressed all the requested changes.

File: packages/vats/package.json [hunk 50]
```diff
@@ -23,6 +23,7 @@
   "license": "Apache-2.0",
   "dependencies": {
     "@agoric/assert": "^0.6.0",
+    "@agoric/deploy-script-support": "^0.10.3",
```
Comment (turadg) [inline packages/vats/package.json]: leftover
```suggestion
```

File: packages/smart-wallet/src/walletFactory.js (hunk 48 above)
Comment (turadg) [reply packages/smart-wallet/src/walletFactory.js:269]: >I don't think it takes long to verify that the value doesn't matter.

Not long, but not still cognitive load to search and remember.

not a big deal, resolving

File: packages/smart-wallet/src/smartWallet.js [hunk 51]
```diff
@@ -315,10 +356,33 @@ export const prepareSmartWallet = (baggage, shared) => {
...
+      addContinuingOffer: M.call(
+        M.or(M.number(), M.string()),
+        AmountShape,
+        M.remotable('InvitationMaker'),
+        M.or(M.record(), M.undefined()),
+      ).returns(M.promise()),
+      purseForBrand: M.call(BrandShape).returns(M.promise()),
+      logWalletInfo: M.call().rest(M.arrayOf(M.any())).returns(),
+      logWalletError: M.call().rest(M.arrayOf(M.any())).returns(),
+      // XXX is there a tighter guard for a bigMapStore than M.any()?
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: there isn't, but there could be a shape for it. consider,
```suggestion
      // TODO define a shape for bigMapStore 
```
even better, make an issue and mention it here

File: packages/smart-wallet/src/smartWallet.js [hunk 52]
```diff
@@ -494,6 +563,154 @@ export const prepareSmartWallet = (baggage, shared) => {
...
+         * we've addressed the problem for new offers. This function will
+         * backfill the solution for offers that were outstanding before the
+         * transition to incarnation 2 of the smartWallet.
+         */
+        async repairUnwatchedSeats() {
+          const { state, facets } = this;
+          const { address, invitationPurse } = state;
+          const { liveOffers, liveOfferSeats } = state;
+          const { zoe, agoricNames } = shared;
+          const { invitationBrand, invitationIssuer } = shared;
```
Comment (turadg) [inline packages/smart-wallet/src/smartWallet.js]: I can't tell whether it was intentional to separate them. Please make these two lines or explain why it's four.

**Review by turadg — APPROVED** [review]
I left some non-blocking feedback. Should be squashed into one `feat` commit

File: packages/smart-wallet/src/smartWallet.js (hunk 51 above)
Comment (dckc) [reply packages/smart-wallet/src/smartWallet.js]: `M.remotable()` seems like the right shape.
or with a label such as `M.remotable('mapStore')`.

https://github.com/Agoric/agoric-sdk/blob/5a06ded0d99e0e8ee3e78191ff4a538c091628ff/packages/swingset-liveslots/src/collectionManager.js#L843

Comment (turadg) [reply packages/smart-wallet/src/smartWallet.js]: I assumed we could do better by including the actual properties (methods) of a mapStore. M.remotable() is incrementally better than M.any() but then the shape can't change later to one that is a local object with methods.

Comment (dckc) [reply packages/smart-wallet/src/smartWallet.js]: Patterns only admit passables, such as a remotable or a copyRecord with properties (whose values are passable), but local objects with methods aren't passable, IIUC.

And even for a local `Far()` object, whether a pattern matches or not is pass-invariant, so you can't test its methods with patterns any more than you can for a remote presence.

Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: `M.remotable('mapStore')` is indeed better than `M.any()`. Thanks

File: packages/smart-wallet/src/smartWallet.js (hunk 52 above)
Comment (Chris-Hibbert) [reply packages/smart-wallet/src/smartWallet.js]: I hate prettier.

It used to turn 2 lines here or 4 lines into 10 lines. Now it's happy with two lines per declaration. Hurrah!
But with longer names or more names, it will jump from 2 lines to 6, and I'll go back to multiple declarations, or not declaring them all, or declaring some later.

File: packages/vats/package.json (hunk 50 above)
Comment (Chris-Hibbert) [reply packages/vats/package.json]: gone.

File: packages/smart-wallet/src/smartWallet.js (hunk 51 above)
Comment (turadg) [reply packages/smart-wallet/src/smartWallet.js]: Thanks @dckc and sorry for steering your wrong @Chris-Hibbert . I neglected to think through it, and was yet was hasty in my certainty. I plead guilty by reason of fever.
