### PR TITLE
ci: wait for 3 blocks before starting contract

### LINKED ISSUE #9325: Flake: Getting Started (registry/yarn)
## Describe the bug

The **Getting Started (registry/yarn)** is flakey

## To Reproduce

The test failed, as shown in
https://github.com/Agoric/agoric-sdk/actions/runs/8973265730/job/24643072843?pr=9283

```
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = account sequence mismatch, expected 60, got 59: incorrect account sequence [agoric-labs/cosmos-sdk@v0.46.16-alpha.agoric.2.1/x/auth/ante/sigverify.go:269] With gas wanted: '18446744073709551615' and gas used: '38588' : unknown request
```

hitting "Rerun failed tests" caused it to pass.

Other instances
- https://github.com/Agoric/agoric-sdk/actions/runs/9452805537/job/26036797179?pr=9477 `Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = account sequence mismatch, expected 63, got 62: incorrect account sequence [agoric-labs/cosmos-sdk@v0.46.16-alpha.agoric.2.4/x/auth/ante/sigverify.go:269] With gas wanted: '18446744073709551615' and gas used: '38588' : unknown request`
- https://github.com/Agoric/agoric-sdk/actions/runs/9482934359/job/26128895842?pr=9486
- https://github.com/Agoric/agoric-sdk/actions/runs/9485446800/job/26137411404?pr=9493
- https://github.com/Agoric/agoric-sdk/actions/runs/9575880016/job/26401438586?pr=9529
- https://github.com/Agoric/agoric-sdk/actions/runs/9585917138/job/26432853529?pr=9532
- https://github.com/Agoric/agoric-sdk/actions/runs/9585956607/job/26432968021?pr=9494
- https://github.com/Agoric/agoric-sdk/actions/runs/9587308469/job/26437076172?pr=9494
- https://github.com/Agoric/agoric-sdk/actions/runs/9604519081/job/26490178328?pr=9544
- https://github.com/Agoric/agoric-sdk/actions/runs/9604519081/job/26490177945?pr=9544

## Expected behavior

Tests  should not be flakey.

## Platform Environment

Running in CI.

### PR DESCRIPTION
**Pull request by rabi-siddique**
closes: https://github.com/Agoric/agoric-sdk/issues/9325

## Description

As per my inspection, the initial blocks often contain transactions from governance-related wallets when the chain starts. Starting the contract also involves these governance wallets. When these transactions overlap during the initial blocks, it can lead to an account sequence mismatch. Since we now wait for three blocks to be produced, this should be sufficient to surpass the phase where governance wallets are involved in transactions.

### CODE REVIEW

File: packages/agoric-cli/tools/getting-started.js [hunk 1]
```diff
@@ -172,7 +172,7 @@ export const gettingStartedWorkflowTest = async (t, options = {}) => {
 
     // ==============
     // wait for the chain to start
-    let lastKnownBlockHeight = 0n;
+    let lastKnownBlockHeight = 1000n;
```
Comment (mujahidkay) [inline packages/agoric-cli/tools/getting-started.js]:
```suggestion
    let lastKnownBlockHeight = 2n;
```

File: packages/agoric-cli/tools/getting-started.js [hunk 2]
```diff
@@ -181,8 +181,8 @@ export const gettingStartedWorkflowTest = async (t, options = {}) => {
         if (currentHeight > lastKnownBlockHeight) {
           const earlierHeight = lastKnownBlockHeight;
           lastKnownBlockHeight = currentHeight;
-          if (earlierHeight > 0n && currentHeight > earlierHeight) {
-            // We've had at least one block produced.
+          if (earlierHeight > 1000n && currentHeight > earlierHeight) {
+            // We've had at least 1000 blocks produced.
```
Comment (mujahidkay) [inline packages/agoric-cli/tools/getting-started.js]:
```suggestion
          if (earlierHeight > 2n && currentHeight > earlierHeight) {
            // We've had at least 2 blocks produced.
```

File: packages/agoric-cli/tools/getting-started.js [hunk 3]
```diff
@@ -181,8 +181,8 @@ export const gettingStartedWorkflowTest = async (t, options = {}) => {
         if (currentHeight > lastKnownBlockHeight) {
           const earlierHeight = lastKnownBlockHeight;
           lastKnownBlockHeight = currentHeight;
-          if (earlierHeight > 0n && currentHeight > earlierHeight) {
-            // We've had at least one block produced.
+          if (earlierHeight > 2n && currentHeight > earlierHeight) {
+            // We've had at least 3 blocks produced.
```
Comment (Muneeb147) [inline packages/agoric-cli/tools/getting-started.js:185]: How is waiting for three blocks fix the account seq mismatch issue? Isn't it due to parallel jobs doing tx with same account?

Comment (rabi-siddique) [reply packages/agoric-cli/tools/getting-started.js:185]: > How is waiting for three blocks fix the account seq mismatch issue?

As per my inspection, the initial blocks often contain transactions from governance-related wallets when the chain starts. Starting the contract also involves these governance wallets. When these transactions overlap during the initial blocks, it can lead to an account sequence mismatch. Since we now wait for three blocks to be produced, this should be sufficient to surpass the phase where governance wallets are involved in transactions. 

> Isn't it due to parallel jobs doing tx with same account?

No. Each `getting-started` job runs independently in its own runner. There's no shared state between workflows, as each one runs its own A3P chain in a separate space.

Comment (Muneeb147) [reply packages/agoric-cli/tools/getting-started.js:185]: Hmm right. So As far as I know, this tx sequence is linked with account/wallet as well. Our tests use user1 (install-bundles.sh), so about governance wallet transactions, their sequence number shouldn't disturb user1, right? Not sure just thnking out loud.

Comment (rabi-siddique) [reply packages/agoric-cli/tools/getting-started.js:185]: `user1` is involved in installing bundles. But for the contract core eval to be passed, I reckon governance wallets take part in it via voting on it. I think that phase leads to account sequence mismatch.

Comment (Muneeb147) [reply packages/agoric-cli/tools/getting-started.js:185]: Hmmm interesting.
So do we have successful re-runs as well?

Comment (rabi-siddique) [reply packages/agoric-cli/tools/getting-started.js:185]: Yes. Mujahid and I ran it several times. Did not encounter any flakes or failures.

Comment (rabi-siddique) [reply packages/agoric-cli/tools/getting-started.js:185]: https://github.com/Agoric/agoric-sdk/actions/workflows/integration.yml?query=branch%3Ars-fix-getting-started-flakes

**Review by Muneeb147 — APPROVED** [review]
Good possible detection.
Can you also update PR description with 
https://github.com/Agoric/agoric-sdk/pull/10295#discussion_r1806472664?

Also I see we did multiple runs with successful outcome 🤞❤️
