### PR TITLE
fix: limit number of kernel steps per block

### LINKED ISSUE #2290: Impose per-block crank limit

### LINKED ISSUE #2299: basic scheduler: limit number of cranks per block
## What is the Problem Being Solved?

Currently, the cosmic-swingset host application runs the kernel's run-queue to completion on each block, by calling `controller.run()` during the `endBlock` phase:

https://github.com/Agoric/agoric-sdk/blob/07e763d4749fcbc1252178a93f09a9e253632942/packages/cosmic-swingset/lib/launch-chain.js#L96-L99

If the run-queue is too deep (either because an inbound message added too much, the processing of one queue entry causes too many additional entries to be added, or because the queue was too deep to start with), the block proposer will take too long to generate the proposal, and the other validators will give up on it. Whatever time the block proposer takes to create the block will also be required in the validators to check it.

Currently, a simple infinite loop spread across two separate vats will cause an unending stream of events to be added to the run-queue, one at a time, and `controller.run()` will never finish.

Instead of an unbounded `controller.run()`, the host application needs to call `controller.step()` a finite number of times (and/or we should enhance swingset to offer `controller.run(maxCranks)` and cosmic-swingset should call it with a finite argument).

For now, we should pick any finite value (perhaps `1000`) for `maxCranks`: anything is better than allowing an infinite loop. If the number is too low, we may leave work on the queue and under-utilize the CPU. If the number is too high, we may exceed our block-processing (time) budget and validators may get slashed.

In the longer term, we need to find a way to make this adaptive. Ideally, we would compute a wallclock-time processing budget as `(INTER_BLOCK_TIME - MESSAGING_AND_VOTING_OVERHEAD) / 2 - SAFETY_MARGIN`, and have the block proposer execute as many cranks as it could within that budget. That would utilize as much of the CPU as possible without causing votes or blocks to be delayed (and achieving roughly 50% CPU utilization on each node).

The tricky thing is that we don't know ahead of time how long each crank will take. Our Metering story may provide some rough upper bounds, but it is still likely to be variable.

I'll file a separate ticket to brainstorm about how to make this adaptive. For now, the main task is to allow a finite number of cranks.

Note that anything other than "inifinity" creates the scarceness that makes Scheduling interesting. If all cranks are executed on every block, there's no value to prioritizing some messages over others. But if only a subset can be executed, then paying for priority gets you a clear benefit. So meaningful Scheduler/Escalator work is dependent upon this limitation being in place.

# Test Plan

We should have some unit tests in cosmic-swingset that can exercise smaller parts of the system.

In the longer run, we want a performance testnet with a client that creates periodic bursts of traffic (more than 1000 cranks), but whose overall rate is low enough to allow that traffic to drain. We should be able to observe the later messages in the burst taking more than one block time to get handled.

cc @michaelfig

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #2299

### CODE REVIEW

File: packages/cosmic-swingset/lib/launch-chain.js [hunk 1]
```diff
@@ -18,6 +18,10 @@ const log = anylogger('launch-chain');
 
 const SWING_STORE_META_KEY = 'cosmos/meta';
 
+// This is how many steps we run per block, as per #2299.
```
Comment (warner) [inline packages/cosmic-swingset/lib/launch-chain.js]: let's call them "cranks" instead of "steps", to match the kernel jargon

File: packages/cosmic-swingset/lib/launch-chain.js [hunk 2]
```diff
@@ -18,6 +18,10 @@ const log = anylogger('launch-chain');
...
+// TODO Make it dependent upon metering instead.
+const FIXME_STEPS_PER_BLOCK = 1000;
```
Comment (warner) [inline packages/cosmic-swingset/lib/launch-chain.js]: maybe `FIXME_MAX_CRANKS_PER_BLOCK`? most blocks will have far fewer

File: packages/cosmic-swingset/lib/launch-chain.js [hunk 3]
```diff
@@ -95,6 +99,13 @@ export async function launch(
   // ////////////////////////////
   // TODO: This is where we would add the scheduler.
   async function endBlock(_blockHeight, _blockTime) {
+    let stepsRemaining = FIXME_STEPS_PER_BLOCK;
+    let stepped = true;
+    while (stepped && stepsRemaining > 0) {
+      // eslint-disable-next-line no-await-in-loop
+      stepped = await controller.step();
+      stepsRemaining -= 1;
+    }
```
Comment (warner) [inline packages/cosmic-swingset/lib/launch-chain.js:108]: we need to remove the trailing `await controller.run()` for this to actually limit execution

**Comment by warner** [comment]
Eventually we'll need to impose a limit on ag-solo too (there's a `controller.run()` in `lib/ag-solo/start.js`), but the constraints are different, and I think we'll need some changes to the outer loop to make it meaningful. We don't have an N-second block budget limit, in some sense it'd be ok for the ag-solo to spend minutes or even hours processing before it surfaces enough to commit the state changes that result, or perform IO. But we should probably do work in smaller pieces, for several reasons:

* if we wait too long before committing the results, we increase the chance that we crash before reaching a commit point, and we'll make less progress than we could have
* some of the results might be messages that go to external systems: if we can emit those messages sooner, they can start their own work sooner, which increases parallelism and reduces latency
* if we only look at the timer device at the beginning of a "block", we won't give higher-priority timer-triggered events a chance to bid for execution time, and they'll run later than they should

The tradeoff is that smaller "block" times for the ag-solo will reduce efficiency somewhat, just like any context-switching overhead.

The advantage we have in an ag-solo is that we don't have to agree with any other nodes, or commit ahead of time to the number of cranks we're doing. So we could poll wallclock time after each `controller.step()` and stop once we've gone past our target. If the run-queue is not empty, we should give the timer a chance to inject work, and then run the process again. If not, we can wait until the next timer interrupt or inbound comms message.

I'll spin off a separate ticket for the ag-solo crank limiting.

File: packages/cosmic-swingset/lib/launch-chain.js (hunk 3 above)
Comment (michaelfig) [reply packages/cosmic-swingset/lib/launch-chain.js:108]: Oops.  Got it.

**Review by FUDCo — COMMENTED** [review]
Well OK then
