### PR TITLE
fix(swingset): delete unused snapshots

### LINKED ISSUE #3374: snapstore: unused snapshots are never deleted
## What is the Problem Being Solved?

We want to delete unused snapshots. The snapstore is somewhat disconnected from the set of vats which use their snapshots (e.g. the snapstore doesn't know which vats are using which snapshots). And multiple vats might be using a single snapshot, at least for a little while (if we don't write a new snapshot until 20 cranks have been delivered, then all young vats will be using the same starting snapshot).

So we need some sort of refcounts, and something to notice when a snapshot is unused, and to delete the file.

We should probably get this implemented before e.g. moving vat-tp back to `xsnap`, since it receives a lot of messages (probably more than any other vat in the system), which will produce a lot of snapshots. And making it stateless (#3305) is stalled on some deep science (reconstructing Remotables without replay). The vat-tp state is small and doesn't grow over time, so each snapshot should be minimal (I think we've seen 200-300kB?), but writing a new one every 20 deliveries would be a lot of space.

## Description of the Design

Not sure, maybe swingStore should be aware of which keys are being used to hold snapshot names, and could perform the refcounting internally. Or maybe something on the kernel side should track it.

### PR DESCRIPTION
**Pull request by dckc**
In addition to maintaining a mapping from vatID to snapshotID,
vatKeeper maintains a reverse mapping.

After `commitCrank()`, the kernel calls `vatWarehouse.pruneSnapshots()`,
which, if `snapshotPruneInterval` cranks have passed:
 1. calls `kernelKeeper.getUnusedSnapshots()`,
 2. tries to `snapStore.delete()` each of them, and
 3. reports the results using `kernelKeeper.forgetUnusedSnapshots()`.

fixes #3374

includes progress on #3431

### CODE REVIEW

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 1]
```diff
@@ -53,6 +53,7 @@ const enableKernelGC = true;
 // v$NN.t.endPosition = $NN
 // v$NN.vs.$key = string
 // v$NN.lastSnapshot = JSON({ snapshotID, startPos })
+// snapshot.$id = [vatID, ...]
```
Comment (warner) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:64]: let's add a note, `// exclude from consensus`, to both this and the `v$NN.lastSnapshot` keys: when #3442 lands we need to not hash these DB keys into the consensus state

File: packages/xsnap/src/snapStore.js [hunk 2]
```diff
@@ -130,5 +130,13 @@ export function makeSnapStore(
     }, `${hash}-load`);
   }
 
-  return freeze({ load, save });
+  /**
+   * @param {string} hash
+   * @throws { Error } if there is no such snapshot
+   */
+  function deleteSnapshot(hash) {
```
Comment (warner) [inline packages/xsnap/src/snapStore.js]: it might be nice to assert there are no `/` in the alleged `hash`, to limit the authority of this function to deleting things under `root`

File: packages/SwingSet/src/kernel/kernel.js [hunk 3]
```diff
@@ -705,6 +705,10 @@ export default function buildKernel(
       }
       commitCrank();
       kernelKeeper.incrementCrankNumber();
+      if (snapStore) {
+        // eslint-disable-next-line no-use-before-define
+        vatWarehouse.pruneSnapshots(snapStore, kernelKeeper.getCrankNumber());
+      }
```
Comment (warner) [inline packages/SwingSet/src/kernel/kernel.js]: unfortunately this is too early, because of the following scenario:

* host commits block 1
* host starts processing block 2
  * kernel writes snapshot4 for vatA, causing the previous snapshot3 to become unreferenced
  * 20 more cranks happen, enoguh to trip `snapshotPruneInterval`
  * crank 21 finishes, `commitCrank` writes it to the crank buffer
    * note that all 21 cranks are still sitting in the block buffer, since the host has not yet gotten control back to write out block 2
  * kernel calls `pruneSnapshots`, snapshot3 is deleted
  * host process dies
* host process restarts, tries to process block 2 again
  * DB shows vatA using snapshot3
  * vat-warehouse attempts to load vatA from snapshot3, fails because the file is deleted

We need to defer the deletion until after the host has committed the block buffer. We'll need to figure out the best place to do this.. it's not dissimilar to the problems the `streamStore` has/had w.r.t. external files. If we could store snapshots in the same DB (within the same atomicity domain) as the rest of the kernel state, that'd fix this problem, but 1: the snapshots are larger than we'd like to put there, and 2: they need to be available on disk for the `xsnap` process to see, so there's still a "when does it get added/removed in the DB" question to answer.

**Comment by warner** [comment]
Oh, we should make sure that terminated vats get removed from the users list.

File: packages/SwingSet/src/kernel/kernel.js (hunk 3 above)
Comment (FUDCo) [reply packages/SwingSet/src/kernel/kernel.js]: Storing the transcript in the stream store had something of the opposite problem, namely that it would write entries reflecting a future that didn't happen and needed to be rolled back, pruning the timeline at the front.  Since the last thing written to the DB is the endpoint, it was safe to leave the record of that future out there and just let the new timeline overwrite it.  Consequently I'm not sure the stream store experience has much to tell us.  This is more like pulling up the carpet behind you.

Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js]: @dckc: @FUDCo and I walked through this today, and figured that the best solution is something like:
* buffer the deletion inside the `snapstore`: when the kernel/vat-wardhouse checks the refcounts and sees that the snapshot is eligible for deletion, it calls `snapstore.delete()`, but that merely puts an entry in a `deletionSet` Set
* when creating a snapshot (just after we determine the name of the snapshot, by hashing its contents), check to see if it's already in `deletionSet`, and if so, remove it
* consolidate `snapstore` with the rest of `swingstore`
* when the swingstore's `commit()` is called (by the host app), swingstore leans over to snapstore and says "hey, now would be a safe time to delete things"
* snapstore then walks through the `deletionSet` and deletes the files therein

This protects against the case where the kernel decides to delete a snapshot, but is then interrupted before the kvstore updates which stop using it are committed. The delete always happens after that kvstore commit, during the "safe deletion window" that begins after the kvstore commit and ends when a new snapshot is created and committed to the kvstore.

This does leave a small window for leaks: if the process is interrupted after the kvstore commit, but before the file deletion: the kernel will have removed the 0 refcount kvstore entry at the same time as it enqueues the deletion, and that kvstore removal has been committed, but the deletion didn't actually happen, and when the process is restarted, the kernel will no longer remember what needs to be deleted. The core problem is that we have two atomicity domains.

This relates to the #3431 refactoring we were talking about. It might possible to reduce the size of the change by doing something like `makeLMDBSwingStore(basedir, snapstore)`, so one can call the `commit` of the other at the right time. Or by adding a `commit` to the snapstore, and then changing the host applications to commit both (always kvstore first, then snapstore), but it's probably better to give applications fewer opportunities to get it wrong.

Comment (dckc) [reply packages/SwingSet/src/kernel/kernel.js]: > @dckc: @FUDCo and I walked through this today, and figured that the best solution is something like:

Yes, this was pretty straightforward...

> * buffer the deletion inside the `snapstore`: ... `snapstore.delete()`

I called it `prepareToDelete`

> * consolidate `snapstore` with the rest of `swingstore`

This involved some coin-tosses. LMK if looks OK.

> This relates to the #3431 refactoring we were talking about. It might possible to reduce the size of the change by doing something like `makeLMDBSwingStore(basedir, snapstore)` ...

Since `makeLMDBSwingStore` already creates the `streamStore`, I figured it might as well create the `snapStore` too.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 4]
```diff
@@ -570,7 +579,7 @@ export default function makeKernelKeeper(
       assert(k.startsWith(importPrefix), k);
       // abandoned imports: delete the clist entry as if the vat did a
       // drop+retire
-      const kref = kvStore.get(k);
+      const kref = kvStore.get(k) || assert.fail('getKeys ensures get');
```
Comment (warner) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:582]: would `getRequired()` help here and the other places that needed `assert.fail`?

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 5]
```diff
@@ -452,6 +464,50 @@ export function makeVatKeeper(
...
   }
 
+  /**
+   * Add vatID to consumers of a snapshot.
+   *
+   * @param {string} snapshotID
+   */
+  function addToSnapshot(snapshotID) {
+    const key = `snapshot.${snapshotID}`;
+    const consumersJSON = kvStore.get(key);
```
Comment (warner) [inline packages/SwingSet/src/kernel/state/vatKeeper.js]: I wouldn't mind `kvStore.get(key) || '[]'` here..

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 6]
```diff
@@ -506,7 +569,8 @@ export function makeVatKeeper(
         const slot = k.slice(prefix.length);
         if (!slot.startsWith('k')) {
           const vatSlot = slot;
-          const kernelSlot = kvStore.get(k);
+          const kernelSlot =
+            kvStore.get(k) || assert.fail('getKeys ensures get');
```
Comment (warner) [inline packages/SwingSet/src/kernel/state/vatKeeper.js:571]: this can be a `getRequired`, yeah?

File: packages/swing-store-lmdb/src/snapStore.js [hunk 7]
```diff
@@ -119,6 +125,8 @@ export function makeSnapStore(
    * @template T
    */
   async function load(hash, loadRaw) {
+    assert(!hash.includes('/'));
```
Comment (warner) [inline packages/swing-store-lmdb/src/snapStore.js]: maybe also `assert.typeof(hash, 'string')`, since if I was attacking this I'd fake both `.includes` and `.toString`

File: packages/swing-store-lmdb/src/snapStore.js [hunk 8]
```diff
@@ -130,5 +138,22 @@ export function makeSnapStore(
...
+   */
+  function prepareToDelete(hash) {
+    toDelete.add(hash);
+  }
+
+  /**
+   * @throws { Error } if any call to unlink() fails
+   */
+  function commitDeletes() {
+    for (const hash of toDelete) {
```
Comment (warner) [inline packages/swing-store-lmdb/src/snapStore.js:161]: We need to clear `toDelete`, yeah? And maybe have a test that calls `commitDeletes` twice to provde it?

File: packages/swing-store-lmdb/src/lmdbSwingStore.js [hunk 9]
```diff
@@ -176,6 +195,7 @@ function makeLMDBSwingStore(dirPath, forceReset, options) {
       txn.commit();
       txn = null;
     }
+    snapStore.commitDeletes();
```
Comment (warner) [inline packages/swing-store-lmdb/src/lmdbSwingStore.js:205]: Let's add a comment here to remind our future selves of the important sequencing requirement: the kvstore (which used to contain `vatA -> snapshot1`, and is being replaced with `vatA -> snapshot2`) must be committed before we delete `snapshot1`. Otherwise, on restart, we'll consult the kvstore and see `snapshot1`, but we'll fail to load it because it's been deleted already.

File: packages/swing-store-lmdb/package.json [hunk 10]
```diff
@@ -22,11 +22,13 @@
...
     "@agoric/assert": "^0.3.6",
     "better-sqlite3": "^7.4.1",
-    "node-lmdb": "^0.9.4"
+    "node-lmdb": "^0.9.4",
+    "tmp": "^0.2.1"
   },
   "devDependencies": {
     "@agoric/install-ses": "^0.5.20",
     "@agoric/swing-store-simple": "^0.4.6",
+    "@agoric/xsnap": "^0.6.9",
```
Comment (warner) [inline packages/swing-store-lmdb/package.json]: I'm a bit weirded out by this dependency, but I can see why it's expedient. I wouldn't mind seeing a `swing-store-lmdb/test/test-snapstore.js` which only talked to the store, and exercised all of load/save/delete/commit, without using xsnap.

Then the existing test becomes more of an integration test that confirms we can use it in the right way (which of course must use both snapstore and xsnap, and thus wants to live either here or in `xsnap/`, and thus induces the slightly-weird dependency in either one direction or the other). I guess I'm marginally in favor of it living in `xsnap/` (the swingstore feels "lower level" than xsnap), but it's a toss-up.

File: packages/swing-store-lmdb/src/snapStore.js (hunk 8 above)
Comment (dckc) [reply packages/swing-store-lmdb/src/snapStore.js:161]: oh my. that was sloppy.

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 6 above)
Comment (dckc) [reply packages/SwingSet/src/kernel/state/vatKeeper.js:571]: `getRequired` felt like a bit of a performance hit. I was trying to just satisfy the typechecker.

I suppose the `||` is a runtime check too, though. Hm.

File: packages/swing-store-lmdb/package.json (hunk 10 above)
Comment (dckc) [reply packages/swing-store-lmdb/package.json]: I expect `xsnap` to migrate to endo, so I don't want any dependencies on `swing-store-lmdb`. hm.

Comment (dckc) [reply packages/swing-store-lmdb/package.json]: Would it make sense to move this integration test to `cosmic-swingset` or `solo`?

Comment (FUDCo) [reply packages/swing-store-lmdb/package.json]: This dependency makes me really uncomfortable, because it means all the supposedly standalone tools that use the LMDB swingstore would then be dependent on xsnap.

Comment (dckc) [reply packages/swing-store-lmdb/package.json]: I moved it to `solo`, which already depends on `@agoric/xsnap`.

_I tried to move it to `cosmic-swingset` but `yarn test` started compiling a bunch of go code, and I didn't want to go there._

Comment (dckc) [reply packages/swing-store-lmdb/package.json]: @michaelfig I moved some snapstore tests to `solo/test` in c6e76e0; ok with you?

Comment (michaelfig) [reply packages/swing-store-lmdb/package.json]: > ok with you?

Totally fine if you want an integration test that isn't chain-specific.

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 6 above)
Comment (dckc) [reply packages/SwingSet/src/kernel/state/vatKeeper.js:571]: The thought was: `getRequired()` is used where the "schema" says the key can't be missing, but it's not statically evident from the code.

Where it's statically evident that `.get(k)` won't return `undefined` because we got `k` from `getKeys` or just checked it with `has`, the `|| assert.fail()` idiom tells the typechecker.

I'm not a fan of the `has()` followed by `get()` idiom. Feels fragile and requires 2 round trips to the DB.

And I'd like to see `getEntries()` replace `getKeys()` followed by `get()`. But that felt out of scope.

Comment (warner) [reply packages/SwingSet/src/kernel/state/vatKeeper.js:571]: Ok, I just figured that since the implementation of `getRequired` is identical to `get || assert`, then using `getRequired` would make the code shorter and easier to read. My habit has been that `get` means I'm prepared to tolerate it being missing, and `getRequired` means I'm not (DB state is confused and it's best to halt right away). But I'm happy to see it written either way.

File: packages/swing-store-lmdb/package.json (hunk 10 above)
Comment (warner) [reply packages/swing-store-lmdb/package.json]: Having the xsnap+swingstore integration test live in `packages/swingset/` could work too: swingset uses both, and expects them to work together.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 11]
```diff
@@ -803,7 +812,7 @@ export default function makeKernelKeeper(
     assert.typeof(name, 'string');
     const k = `vat.name.${name}`;
     assert(kvStore.has(k), X`vat name ${name} must exist, but doesn't`);
-    return kvStore.get(k);
+    return kvStore.get(k) || assert.fail('.has() ensures .get()');
```
Comment (warner) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:815]: ok yeah I guess I wasn't being consistent here.. this has+get pair could be replaced by a single `getRequired`

(I think we didn't have `getRequired` when that was first written)

File: packages/swing-store-lmdb/test/test-snapstore.js [hunk 12]
```diff
@@ -0,0 +1,84 @@
...
+    );
+    hashes.push(h);
+  }
+  t.is(fs.readdirSync(pool.name).length, 5);
+
+  t.notThrows(() => store.commitDeletes());
+
+  // @ts-ignore
+  t.throws(() => store.prepareToDelete(1));
+  t.throws(() => store.prepareToDelete('../../../etc/passwd'));
```
Comment (warner) [inline packages/swing-store-lmdb/test/test-snapstore.js:67]: What does `prepareToDelete('/etc/passwd')` do? I think it'll create a path like `/path/to/store//etc/passwd`, and I don't really know if that will collapse the `//` into a single `/` (and thus be safe), or if syscalls are in the habit of restarting the directory traversal at the root when they see `//`.

File: packages/swing-store-lmdb/test/test-snapstore.js [hunk 13]
```diff
@@ -0,0 +1,84 @@
...
+
+  store.prepareToDelete(hashes[2]);
```
Comment (warner) [inline packages/swing-store-lmdb/test/test-snapstore.js:70]: Please add one more check here: do a `prepareToDelete(hashes[3])` followed by a `store.save` that replaces it. I saw you have code in `save` that removes things from the pending-deletion list (awesome), we should have a check for it to make sure it doesn't get lost in the future.

File: packages/swing-store-lmdb/test/test-snapstore.js (hunk 12 above)
Comment (warner) [reply packages/swing-store-lmdb/test/test-snapstore.js:67]: Oh, nevermind, I see that `hashpath()` prohibits all slashes, not just `..` .. that's perfect.

**Review by warner — APPROVED** [review]
One additional check in the unit test recommended, rest looks good.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 11 above)
Comment (dckc) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:815]: I think I tried using `getRequired` here but it changes the error message and there's a test for the error message.

File: packages/swing-store-lmdb/test/test-snapstore.js (hunk 12 above)
Comment (dckc) [reply packages/swing-store-lmdb/test/test-snapstore.js:67]: > What does `prepareToDelete('/etc/passwd')` do?

It trips over the same `assert(!hash.includes('/'));`

File: packages/swing-store-lmdb/test/test-snapstore.js (hunk 13 above)
Comment (dckc) [reply packages/swing-store-lmdb/test/test-snapstore.js:70]: right; done.
