### PR TITLE
fix(swingset): use dynamic vat options.name for the xsnap no-op argument

### LINKED ISSUE #5516: `E(vatAdmin).createVatByName` doesn't set the resulting vat's name
## Describe the bug

`E(vatAdmin).createVatByName('foo')` should result in a vat with name `'foo'`, but currently it has name `'undefined'`.

I think this will be really easy to fix, but I don't know where in the layering to plumb it in.

## To Reproduce
1. Start an Agoric chain with `agoric start local-chain`, and wait for it to boot.
2. Note the process list:
```
$ ps -ef | grep xsnap
  502 11615 11587   0 12:04PM ttys004    0:00.92 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v1:bootstrap -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/f5af99219d5bda038a8b4d709a9d593db8081c67ea52e4e3b8e60be79f86e8a8-load-bewiRa.xss
  502 11616 11587   0 12:04PM ttys004    0:00.05 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v5:timer -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/478d1cfbef22449330301e2bac505bb0ef2e43766418a6cc95c1db4b5c0d32f3-load-Qrgwn0.xss
  502 11617 11587   0 12:04PM ttys004    0:00.03 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v2:vatAdmin -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/eee73f5641494e8e4a062cc1af30f529d14b6b47f7a44f4fe833cdb523ac1c60-load-Zz8PZm.xss
  502 11618 11587   0 12:04PM ttys004    0:00.01 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v4:vattp -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/b6cb1c4900d18692214b58e3b285e1829883ab07c40bb99a429b1d3a7b9a0a5b-load-yEXq78.xss
  502 11623 11587   0 12:04PM ttys004    0:00.03 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v6:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/7ac7d8a4e7b3206c75249b0011a9fc459d0033a7a4611b21f73dc52f30859627-load-2970L5.xss
  502 11624 11587   0 12:04PM ttys004    0:00.32 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v7:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-stat
  502 11625 11587   0 12:04PM ttys004    0:00.03 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v8:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/ff1f5fba02e1b79fcbc51a9a85cd066f502417dae7a0277d00929b3bcab35dc7-load-PHFYyL.xss
  502 11626 11587   0 12:04PM ttys004    0:00.01 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v9:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/bddcc2a0d69671b47aa1286a8132969de85f47eac37f8f1f7ddea11152c0012c-load-yVngnY.xss
  502 11627 11587   0 12:04PM ttys004    0:00.04 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v10:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/e965bd831496bfa18b35b11c8a3c949fddb43d800afac698c6c0afc3e6f2750d-load-4oL1Iv.xss
  502 11628 11587   0 12:04PM ttys004    0:00.03 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v11:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/7f5182cbbfe4e06da25ab2b78bac4a75c8a651810d7a24f104900359eab49bb8-load-7u9InQ.xss
  502 11629 11587   0 12:04PM ttys004    0:00.02 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v12:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/aa544966cc30f7a1296503fd34004b0c628a8cf7cabdc7a42100077b2aa7a8a0-load-1eJ1BT.xss
  502 11630 11587   0 12:04PM ttys004    0:00.22 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v14:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/b60adce626b40c8d9c16a29ec0a23f0d22ed29a5ef9e3380db782b5bdda33313-load-7IG00O.xss
  502 11633 11587   0 12:04PM ttys004    0:00.07 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v15:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/5dc402482415f21844f7986aa2d614782c38610edffe04c59121178af0c67c14-load-BSktFb.xss
  502 11634 11587   0 12:04PM ttys004    0:00.44 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v16:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/4b7c871d9d8bba24025dd50f99a941b9e054f0ff5748115fa960f9bbbec18d17-load-o99VDD.xss
  502 11635 11587   0 12:04PM ttys004    0:00.15 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v17:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/afcb218f436d37307c22bbc68e7df8273e47c2c2bac3db5b808696ef254a2b07-load-Jf3Tzq.xss
  502 11642 11587   0 12:04PM ttys004    0:00.32 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v18:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/ce35c0f8c5f78482dfd09ae768cdbd91361d50db400883dd248ae75095aab74c-load-7Bt8Q2.xss
  502 11648 11587   0 12:04PM ttys004    0:00.27 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v19:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/8612f1b5b81ab7b12d0ac83f54b2dc19cb98cfafadb8363f07dd0d7df72cfe64-load-k8hPoI.xss
  502 11649 11587   0 12:04PM ttys004    0:00.29 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v20:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/6d9ab76bde8de5d33634a66e5a3bf335a914d486bb67443049b8af120a87853e-load-Wsz5hT.xss
  502 11650 11587   0 12:04PM ttys004    0:00.22 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v21:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/3c2d3bbe6106c1bdeac75d3b25731ba682ccf0f0e2092f2cf9f83e4309b9193b-load-yyB00I.xss
  502 11651 11587   0 12:04PM ttys004    0:00.38 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v22:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/259a0d76b4185e929c2b66e79d5d04b1c3034502c03c3dbeb7d52b360857f394-load-0OaMxw.xss
  502 11652 11587   0 12:04PM ttys004    0:00.29 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v23:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/a6a07c951849d9fc8a5a00f5def4beaae98b27b5196bcc358c8ab5bb646d7358-load-wBMOzW.xss
  502 11653 11587   0 12:04PM ttys004    0:00.28 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v24:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/19ada13d2d9bbd8ea21efbf0c4a700a309cb82fd2f61aec96312a81883ee5675-load-jnaVHV.xss
  502 11654 11587   0 12:04PM ttys004    0:00.31 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v25:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/2daec6a87566361b2b025c3626e8268cae81d91a58d7462c69e9f957c12c0f71-load-aYnQot.xss
  502 11657 11587   0 12:04PM ttys004    0:00.86 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v26:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/2ccad366c3e770f5a0538850c8989d161bd618fbdb3b11d0203f64999c7b0c55-load-YWfoRg.xss
  502 11660 11587   0 12:04PM ttys004    0:00.40 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v27:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/c9e85a97d5b5ef5f64ff3d09544bb7a1d89ca64a3ace3d595af405d4c74042bc-load-Gf1WR2.xss
  502 11661 11587   0 12:04PM ttys004    0:00.07 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v28:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/91be593a3a9e146c3c81315db172b4c8de4cc262b407333ef1c205d02db7cac8-load-NykbH5.xss
  502 11662 11587   0 12:04PM ttys004    0:00.30 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v29:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/e1d8b7178b26d2c5cfea153ae900d54c9463c501c30ae01743a568821337d3e8-load-4ntstV.xss
  502 11663 11587   0 12:04PM ttys004    0:00.47 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v30:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/87861c625e95a2d3af30ccfbb2748412dcfe803d88983bf8fd1b88cb8899b031-load-Bb4Bj2.xss
  502 11672 11587   0 12:04PM ttys004    0:00.29 /Users/michael/agoric/agoric-sdk/packages/xsnap/xsnap-native/xsnap/build/bin/mac/release/xsnap-worker v31:undefined -r /Users/michael/agoric/agoric-sdk/packages/cosmic-swingset/t1/n0/data/ag-cosmos-chain-state/xs-snapshots/6bd72ddb2e2de2be9aa8b5f7ad0dde9262cc619f8feb0f145043f85e2168c63d-load-mu1Zma.xss
```
3. See that only the static vats have a name other than `v${vatID}:undefined`.

## Expected behavior
Dynamic vats launched by bootstrap should have names.

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

### PR DESCRIPTION
**Pull request by warner**
fix(swingset): use dynamic vat options.name for the xsnap no-op argument

Previously, static vats would glean a "name" value from the config
structure, and dynamic vats would not get a name. Both kinds of vats
would glean a "description" that combined this name, a `description`
argument provided to `createVat()`, and information about the source
bundle used to create the vat. If `name` was available, it would be
used as an extra no-op argument to `xsnap`, so by looking at `ps`, you
could tell which `xsnap` worker process was hosting which vat.

As we move to bundlecaps (especially as the chain bootstrap code moves
to bundlecaps), we've lost the `name` field in `ps` for most initial
vats.

This change allows the creator of a dynamic vat to provide a `name`
field, just like the config structure can provide then for static
vats. This `name` is now uniformly used in the `ps` arguments.

The `description` option has been removed. Slogfiles still include a
description, and it incorporates the assigned name and source bundle
information, but userspace can no longer provide
`E(vatAdminSvc).createVat(bcap, { description })` in the options.

The `name` field is arbitrarily limited to 200 characters, to avoid
running into OS limitations when `xsnap` includes in in `argv`.

fixes #5516

### CODE REVIEW

**Review by FUDCo — APPROVED** [review]
C'est bon.

**Comment by warner** [comment]
Oops, missed a test that needed updating, that push ought to fix it.

**Comment by michaelfig** [comment]
There was a dependency on the old `${vatID}:undefined` behaviour (and looks like the only one I can find).

https://github.com/Agoric/agoric-sdk/runs/6766086772?check_suite_focus=true#step:5:1379

I've pushed a fix, but not set automerge.  Feel free to season to taste.

File: packages/xsnap/src/xsnap.js [hunk 1]
```diff
@@ -89,6 +89,8 @@ export function xsnap(options) {
   /** @type {Deferred<void>} */
   const vatExit = defer();
 
+  assert(!/^-/.test(name), `name '${name}' cannot start with hyphen`);
```
Comment (michaelfig) [inline packages/xsnap/src/xsnap.js:92]: Since this is an assertion that could fail at runtime, do you want to tailor the regexp used by `vat-admin/vat-vat-admin.js` to also insist on an initial non-hyphen character?

**Review by michaelfig — APPROVED** [review]
Looks great!  Just one question around the name validation....

File: packages/xsnap/src/xsnap.js (hunk 1 above)
Comment (warner) [reply packages/xsnap/src/xsnap.js:92]: I thought about that, but the unavoidable-by-userspace `${vatID}` prefix means that `createVat(bcap, { name: '--sneaky' })` will result in xsnap.js getting `name: 'v123:--sneaky'`, which seems fine.

Comment (michaelfig) [reply packages/xsnap/src/xsnap.js:92]: In that case, could you call this variable something different than `name`, if it really is `${vatID}:${name}`?

**Comment by michaelfig** [comment]
https://github.com/Agoric/agoric-sdk/runs/6766958464?check_suite_focus=true#step:10:5452 would not have occurred if an undefined name resulted in `${vatID}:` instead of just `vatID`.

**Comment by warner** [comment]
> https://github.com/Agoric/agoric-sdk/runs/6766958464?check_suite_focus=true#step:10:5452 would not have occurred if an undefined name resulted in `${vatID}:` instead of just `vatID`.

Oh, ok, something is looking for `/v\d+:/`, ok, I'll bring it back

File: packages/xsnap/src/xsnap.js (hunk 1 above)
Comment (warner) [reply packages/xsnap/src/xsnap.js:92]: Hm, that would be a breaking change to the `xsnap` API (because `name` appears in an options bag, not as a positional argument), and in theory we might have non-swingset users of `@agoric/xsnap`. These two uses of `name` appear in different packages.

Would it look better if `manager-subprocess-xsnap.js` did:
```js
const {
  ..
  name: vatName,
} = managerOptions;
..
const argName = `${vatID}:${vatName !== undefined ? vatName}`;
```
instead?

Comment (michaelfig) [reply packages/xsnap/src/xsnap.js:92]: Yes, that would be great.  I was just misled by the reuse of the identifier `name` when it had different contents.
