### PR TITLE
fix: add shutdown() to atomicSwap, coveredCall, and sellItems.

### LINKED ISSUE #1606: add shutdown() calls to contracts
**What is the Problem Being Solved?**

Zoe/Zcf have a method `shutdown()` that exits all the seats and then calls `adminNode.terminate()`. The `terminate()` method used to be a no-op, but now it's wired up. No contracts call it, even though it would make sense for some to.

**Description of the Design**

Add shutdown in atomicSwap and coveredCall, and any other contracts for which it makes sense.

**Security Considerations**

OfferSafety and other guarantees Zoe makes should continue to be enforced.

**Test Plan**

This will allow @FUDCo to validate the functioning of the `terminate()` call.

Either add tests for added functionality, or add issues recording tests to be added.

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
atomicSwap already had obvious places to say they were finished. 

sellItems had to check that the items were all sold.

fixes #1606

### CODE REVIEW

File: packages/zoe/src/contractFacet/seat.js [hunk 1]
```diff
@@ -22,7 +22,8 @@ export const makeZcfSeatAdminKit = (
   let currentAllocation = harden(seatData.initialAllocation);
   let exited = false; // seat is "active"
 
-  const assertExitedFalse = () => assert(!exited, `seat has been exited`);
+  const assertExitedFalse = () =>
+    assert(!exited, details`seat has been exited`);
```
Comment (katelynsills) [inline packages/zoe/src/contractFacet/seat.js:26]: why use details?

File: packages/zoe/src/contracts/atomicSwap.js [hunk 2]
```diff
@@ -28,8 +28,11 @@ const start = zcf => {
     const { want, give } = firstSeat.getProposal();
 
     /** @type {OfferHandler} */
-    const matchingSeatOfferHandler = matchingSeat =>
-      swap(zcf, firstSeat, matchingSeat);
+    const matchingSeatOfferHandler = matchingSeat => {
+      const swapResult = swap(zcf, firstSeat, matchingSeat);
+      zcf.shutdown();
+      return swapResult;
```
Comment (katelynsills) [inline packages/zoe/src/contracts/atomicSwap.js:34]: can you return things after calling shutdown?

File: packages/zoe/src/contracts/sellItems.js [hunk 3]
```diff
@@ -83,16 +97,11 @@ const start = zcf => {
...
-  };
 
-  /** @type {SellItemsPublicFacet} */
-  const publicFacet = {
-    getAvailableItems: () => {
-      assert(sellerSeat && !sellerSeat.hasExited(), `no items are for sale`);
-      return sellerSeat.getAmountAllocated('Items');
-    },
-    getItemsIssuer: () => issuers.Items,
+    if (publicFacet.getAvailableItems().value.length === 0) {
```
Comment (katelynsills) [inline packages/zoe/src/contracts/sellItems.js]: we really should be using `math.isEmpty()` here. Hardcoding this sounds like a bad thing to teach people.

File: packages/zoe/src/zoeService/zoe.js [hunk 4]
```diff
@@ -291,7 +291,7 @@ function makeZoe(vatAdminSvc, zcfBundleName = undefined) {
         },
         shutdown: () => {
           exitAllSeats();
-          adminNode.terminate();
+          E(adminNode).terminate();
```
Comment (katelynsills) [inline packages/zoe/src/zoeService/zoe.js:294]: good catch!

File: packages/zoe/test/unitTests/contracts/test-sellTickets.js [hunk 5]
```diff
@@ -507,8 +507,6 @@ test(`mint and sell opera tickets`, async t => {
 
     const operaPurse = moolaIssuer.makeEmptyPurse();
 
-    await E(sellItemsCreatorSeat).tryExit();
```
Comment (katelynsills) [inline packages/zoe/test/unitTests/contracts/test-sellTickets.js:510]: huh, is this removed to test the functionality? can we add a comment as such?

File: packages/zoe/src/contracts/atomicSwap.js (hunk 2 above)
Comment (katelynsills) [reply packages/zoe/src/contracts/atomicSwap.js:34]: What kind of activities can happen after calling zcf.shutdown, since it is synchronously called?

**Review by katelynsills — APPROVED** [review]
Just some small changes

File: packages/zoe/src/contractFacet/seat.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/zoe/src/contractFacet/seat.js:26]: Without it I got a complaint about optDetails not being a function.  Don't our `assert`s take a details object, in general?

File: packages/zoe/test/unitTests/contracts/test-sellTickets.js (hunk 5 above)
Comment (Chris-Hibbert) [reply packages/zoe/test/unitTests/contracts/test-sellTickets.js:510]: I removed it because the seat has been exited by this time, so it's not needed, and causes an extraneous error.

File: packages/zoe/src/contracts/atomicSwap.js (hunk 2 above)
Comment (Chris-Hibbert) [reply packages/zoe/src/contracts/atomicSwap.js:34]: I'll admit this surprised me too, but I surmise that no more messages can be sent to objects in the vat. But this function is already executing, and has to return somehow. Returning a constant should be trivial. Returning a value that was previously computed and is in a variable should work. I dunno what else we could get away with.

@FUDCo ?  What should we expect here?

File: packages/zoe/src/zoeService/zoe.js (hunk 4 above)
Comment (Chris-Hibbert) [reply packages/zoe/src/zoeService/zoe.js:294]: Don't give me too much credit. A test failed since adminNode is a presence and doesn't have a terminate() method of its own.

File: packages/zoe/src/contracts/sellItems.js (hunk 3 above)
Comment (Chris-Hibbert) [reply packages/zoe/src/contracts/sellItems.js]: done.

File: packages/zoe/src/contracts/atomicSwap.js (hunk 2 above)
Comment (FUDCo) [reply packages/zoe/src/contracts/atomicSwap.js:34]: Well, you can _send_ messages to objects in a terminated vat, but any messages that hit the vat after it has been terminated will bounce off with an error (i.e., the result will be rejected).  Terminating a vat will also have the effect of rejecting any previously existing promises the vat was the decider for.  Any messages sent _by_ the vat prior to its termination will be delivered.

If any information needs to get out of zcf before shutdown, you need to arrange for that to happen.  For example, you could give zcf the ability to terminate itself (maybe it already does) and have take care of any unfinished business and then pull the trigger on itself by sending a message to vatAdmin.  However, what you are doing here seems completely legit.

**Review by FUDCo — APPROVED** [review]
This all seems swell to me.

File: packages/zoe/src/contracts/atomicSwap.js (hunk 2 above)
Comment (Chris-Hibbert) [reply packages/zoe/src/contracts/atomicSwap.js:34]: > am I correct in my understanding that the contract is running inside the zcf vat? 

Yep.

> which will have the effect of cutting the vat being terminated off from the world. Vat termination does not abort any execution in progress. Anything done in the same crank as your issuance of the terminate message to the vatAdmin will happen (such as sending messages, resolving promises, etc.). In addition, any messages addressed to the vat that were in the kernel run queue prior to termination will be processed since the termination message will be placed into the run queue behind those.

I think that's what I'm counting on. Calls out to Zoe will be delivered. Calls within ZCF are mostly  synchronous, so they'll have completed by the time the shutdown takes effect.

There are some calls back-and-forth between zoe and zcf to manage seats. @katelynsills we should think about whether those could leave any incomplete state that would be cut off by a termination. My instinct is that Everything that would affect payouts and results will already have taken place. But I suspect I'm not thinking about all possible invocations by a contract. Do we need to add some explicit guidance for contract writers about which invocations need to have been finalized before it's safe to call shutdown?

File: packages/zoe/test/unitTests/contracts/test-sellTickets.js (hunk 5 above)
Comment (katelynsills) [reply packages/zoe/test/unitTests/contracts/test-sellTickets.js:510]: Ok sounds good

File: packages/zoe/src/contracts/atomicSwap.js (hunk 2 above)
Comment (katelynsills) [reply packages/zoe/src/contracts/atomicSwap.js:34]: I think that makes sense. Can we create a separate issue to think this through and analyze it?

File: packages/zoe/src/contractFacet/seat.js (hunk 1 above)
Comment (katelynsills) [reply packages/zoe/src/contractFacet/seat.js:26]: huh, I think you're right, thanks for catching
