### PR TITLE
7850 gracefully handle failures of distributeProceeds

### LINKED ISSUE #7850: Vaults stuck in liquidating state
@otoole-brendan commented on [Fri May 26 2023](https://github.com/Agoric/dapp-inter/issues/132)

## Describe the bug

After testing reconstitution scenario on Emerynet (which was successful) - the two reconstituted vaults were liquidated again in the next auction (expected). While in a state of 'liquidating' - I changed the price to 12.34 (previously 9.99). Even thought the auction finishes, the vaults never leave the liquidating state (i.e. they are not reconstituted, at least per the UI). 
I'm unable to take action/click etc.

Looks like this 

## To Reproduce

1. Test Reconstitution liquidation scenario (or I suspect happy path)
2. When vault is in a state of 'liquidating' - change the price to something higher than liquidation price i.e. 12.34
3. Oberve when auction finishes if vaults complete liquidation/are reconstituted

## Expected behavior

Changing price during liquidation should not break/hang the state of the vaults in the UI

## Platform Environment

- what OS are you using? what version of Node.js?
- is there anything special/unusual about your platform?
- what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots

If applicable, add screenshots to help explain your problem, especially for UI interactions.

---

@rowgraus commented on [Fri May 26 2023](https://github.com/Agoric/dapp-inter/issues/132#issuecomment-1564821074)

Metrics show that the vaults have correctly reconstituted.  However, the status is stuck as Liquidating, which prevents the user from adjusting their vault in the UI
image

### PR DESCRIPTION
**Pull request by turadg**
closes: #7850 

## Description

We had a [bug in distributeProceeds](https://github.com/Agoric/agoric-sdk/issues/7851). It's since been fixed, but it revealed that an error in that function would [leave vaults in a "liquidating" state forever](https://github.com/Agoric/agoric-sdk/issues/7850).

This moves the state transition out of `distributeProceeds` so that it always executes. It also cleans up some redundant state tracking, `vaultsToLiquidate`, which is simply the values in `liquidatingVaults` that haven't been deleted during the distribution/reconstitution.

### Security Considerations

no change

### Scaling Considerations

no change

### Documentation Considerations

--

### Testing Considerations

It would be good to have a test of this error handling but we don't have a way to induce the failure. It's not _expected_ to fail. This is a precaution in case it does anyway.

### CODE REVIEW

**Review by dckc — COMMENTED** [review]
I don't see anything wrong, but I'm not up to speed on how the state is maintained here.

**Review by Chris-Hibbert — CHANGES_REQUESTED** [review]
As we discussed, I think this can leave things in an inconsistent state because some metrics have been updated. 

It also liquidates all vaults, even those we've decided to reinstate if we haven't yet called `reinstateAll()`.

File: packages/inter-protocol/test/supports.js [hunk 1]
```diff
@@ -145,10 +145,13 @@ export const produceInstallations = (space, installations) => {
   }
 };
 
+export const scale6 = x => BigInt(Math.round(x * 1_000_000));
+
 /**
  * @param {Pick<IssuerKit<'nat'>, 'brand' | 'issuer' | 'mint'>} kit
  */
 export const withAmountUtils = kit => {
+  const decimalPlaces = kit.issuer.getDisplayInfo?.()?.decimalPlaces ?? 6;
```
Comment (dckc) [inline packages/inter-protocol/test/supports.js:154]: is `getDisplayInfo` also available on the issuer? I'm used to getting it from the brand.

Comment (Chris-Hibbert) [reply packages/inter-protocol/test/supports.js:154]: Yes, it's also on the Issuer.  I added an issue [to update the doc site](https://github.com/Agoric/documentation/issues/808).

File: packages/inter-protocol/src/contractSupport.js [hunk 2]
```diff
@@ -29,6 +30,17 @@ export const ratioPattern = harden({
 export const addSubtract = (base, gain, loss) =>
   AmountMath.subtract(AmountMath.add(base, gain), loss);
 
+/**
+ * @template {Amount} T
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/src/contractSupport.js:32]: Please add a comment saying what it does: Subtract right from left, but if right is bigger, returns empty.  Should this be in AmountMath?

File: packages/inter-protocol/src/contractSupport.js [hunk 3]
```diff
@@ -128,3 +140,7 @@ harden(makeMetricsPublishKit);
  */
 export const makeNatAmountShape = (brand, min) =>
   harden({ brand, value: min ? M.gte(min) : M.nat() });
+
+/** @param {Pick<PriceDescription, 'amountIn' | 'amountOut'>} quoteAmount */
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/src/contractSupport.js:99]: This belongs with Oracle stuff. `zoe/src/contracts/priceAggregator.js` or in `inter-protocol/src/price/`.

File: packages/inter-protocol/src/vaultFactory/vaultManager.js [hunk 4]
```diff
@@ -660,312 +641,113 @@ export const prepareVaultManagerKit = (
...
-              }
-              vaultsToLiquidate.push(vault);
-            }
+            atomicRearrange(zcf, harden(transfers));
+          }
 
-            if (transfers.length > 0) {
-              atomicRearrange(zcf, harden(transfers));
-            }
+          // was reinstateAll
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/src/vaultFactory/vaultManager.js]: Please drop comment

File: packages/inter-protocol/src/vaultFactory/proceeds.js [hunk 5]
```diff
@@ -0,0 +1,273 @@
...
+
+    let leftToStage = distributableCollateral;
+
+    // iterate from best to worst, returning collateral until it has
+    // been exhausted. Vaults after that get nothing.
+    for (const [vaultIndex, balances] of vaultsBalances.entries()) {
+      const { collateral: vCollat, presaleDebt } = balances;
+      updatePhantomDebt(balances);
+
+      const price = makeRatioFromAmounts(mintedProceeds, collateralSold);
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/src/vaultFactory/proceeds.js]: This can be outside the loop. It can't be outside the flow because collateralSold is only known to be non-zero inside this flow.

File: packages/inter-protocol/src/vaultFactory/proceeds.js [hunk 6]
```diff
@@ -0,0 +1,273 @@
...
+
+    const hasCollateralToDistribute = !AmountMath.isEmpty(
+      distributableCollateral,
+    );
+    plan.collateralForReserve = hasCollateralToDistribute
+      ? AmountMath.add(leftToStage, totalPenalty)
+      : collateralProceeds;
+  };
+
+  const runFlow2a = () => {
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/src/vaultFactory/proceeds.js:158]: Please add comment
```
// Flow 2a: all collateral was sold but debt was not covered
```
perhaps before the flow so it doesn't get merged with the following comment, which only applies to the few lines that follow it?

File: packages/inter-protocol/src/vaultFactory/proceeds.js [hunk 7]
```diff
@@ -0,0 +1,273 @@
...
+    const vaultPortion = makeRatioFromAmounts(distributable, totalCollateral);
+
+    // iterate from best to worst returning remaining funds to vaults
+    for (const [vaultIndex, balances] of vaultsBalances.entries()) {
+      // from best to worst, return minted above penalty if any remains
+      const vaultShare = floorMultiplyBy(balances.collateral, vaultPortion);
+      updatePhantomDebt(balances);
+
+      if (!AmountMath.isEmpty(mintedRemaining)) {
+        const mintedToReturn = AmountMath.isGTE(mintedRemaining, vaultShare)
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/src/vaultFactory/proceeds.js]: use `AmountMath.min`

File: packages/inter-protocol/src/vaultFactory/proceeds.js [hunk 8]
```diff
@@ -0,0 +1,273 @@
...
+          ? vaultShare
+          : mintedRemaining;
+        mintedRemaining = AmountMath.subtract(mintedRemaining, mintedToReturn);
+        plan.transfersToVault.push([vaultIndex, { Minted: mintedToReturn }]);
+      }
+    }
+  };
+
+  const runFlow2b = () => {
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/src/vaultFactory/proceeds.js:188]: add a comment:
```
// Flow 2b: collateral remains but debt was not covered
```

File: packages/inter-protocol/src/vaultFactory/proceeds.js [hunk 9]
```diff
@@ -0,0 +1,273 @@
...
+        amount,
+      ));
+
+    // iterate from best to worst attempting to reconstitute, by
+    // returning remaining funds to vaults
+    for (const [vaultIndex, balances] of vaultsBalances.entries()) {
+      const { collateral: vCollat, presaleDebt } = balances;
+
+      // according to #7123, Collateral for penalty =
+      //    vault debt / total debt * total liquidation penalty
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/src/vaultFactory/proceeds.js]: When I'm working through the math, this is immensely easier to read.  Ratio math requires that the numerator be a different brand from the denominator, so we calculate with vault debt * (total liquidation penalty / total debt).
```suggestion
      //    total liquidation penalty * vault debt / total debt
```

File: packages/inter-protocol/src/vaultFactory/proceeds.js [hunk 10]
```diff
@@ -0,0 +1,273 @@
...
+        AmountMath.isGTE(plan.collatRemaining, collatPostPenalty) &&
+        AmountMath.isGTE(totalDebt, presaleDebt);
+
+      if (reconstituteVaults) {
+        plan.collatRemaining = AmountMath.subtract(
+          plan.collatRemaining,
+          collatPostPenalty,
+        );
+        shortfallToReserve = subtractToEmpty(shortfallToReserve, presaleDebt);
+        // must reinstate after atomicRearrange(), so we record them.
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/src/vaultFactory/proceeds.js:234]: drop the comment. With the advent of plans, this is no longer just a local consideration here.

File: packages/inter-protocol/src/vaultFactory/proceeds.js [hunk 11]
```diff
@@ -0,0 +1,273 @@
...
+        reduceCollateral(vCollat);
+      }
+    }
+
+    plan.collateralForReserve = AmountMath.add(
+      plan.collatRemaining,
+      totalPenalty,
+    );
+
+    plan.accounting.shortfall = shortfallToReserve;
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/src/vaultFactory/proceeds.js]: We should not be updating accounting!  `accounting` should be immutable.  If we need to record a decision here, we need another entry in `plan`.

File: packages/inter-protocol/test/swingsetTests/psmUpgrade/bootstrap-psm-upgrade.js [hunk 12]
```diff
@@ -13,18 +13,16 @@ import buildManualTimer from '@agoric/zoe/tools/manualTimer.js';
 import { E } from '@endo/eventual-send';
 import { Far } from '@endo/marshal';
 import { makePromiseKit } from '@endo/promise-kit';
-import { withAmountUtils } from '../../supports.js';
+import { scale6, withAmountUtils } from '../../supports.js';
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/test/swingsetTests/psmUpgrade/bootstrap-psm-upgrade.js:16]: Just a comment: if you have `.units`, do you ever want to use `scale6()`?

File: packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js [hunk 13]
```diff
@@ -2743,7 +2728,7 @@ test('refund to one of two loans', async t => {
   await m.assertLike({
     allocations: {
       Aeth: aeth.make(9n),
-      Fee: run.makeEmpty(),
+      Fee: undefined,
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js:2731]: Would it be better to drop `Fee: undefined`, rather than have it present? I think both mean the same thing to this test.

File: packages/inter-protocol/test/vaultFactory/test-liquidation-plans.js [hunk 14]
```diff
@@ -0,0 +1,99 @@
...
+} from './driver.js';
+
+/**
+ * @typedef {import('./driver.js').DriverContext & {
+ * }} Context
+ */
+/** @type {import('ava').TestFn<Context>} */
+const test = unknownTest;
+
+const trace = makeTracer('TestLP');
```
Comment (Chris-Hibbert) [inline packages/inter-protocol/test/vaultFactory/test-liquidation-plans.js]:
```suggestion
const trace = makeTracer('TestLP', false);
```

Even if we want to turn on trace in many parts of the production code, I think there's no benefit to leaving it on in tests.

**Review by Chris-Hibbert — CHANGES_REQUESTED** [review]
These are nearly all very local cleanups or requests for more comments. The one that seems important is that plan.accounting should be immutable.

**Comment by dckc** [comment]
https://github.com/Agoric/agoric-sdk/blob/21380352224b341532665c218931751dd47a5e54/packages/inter-protocol/src/vaultFactory/Liquidation.md?plain=1#L12-L16

In 2a, all the collateral is sold, so how could there be excess collateral?

**Comment by dckc** [comment]
https://github.com/Agoric/agoric-sdk/blob/21380352224b341532665c218931751dd47a5e54/packages/inter-protocol/src/vaultFactory/vaultFactory.js#L14-L16

each Vault Manager, yes?

File: packages/inter-protocol/test/swingsetTests/psmUpgrade/bootstrap-psm-upgrade.js (hunk 12 above)
Comment (turadg) [reply packages/inter-protocol/test/swingsetTests/psmUpgrade/bootstrap-psm-upgrade.js:16]: the one place I think we'll still need it: `assertChange`, because the brand doesn't change.

there are some other test utils that take bigints for amounts, like `mintRunPayment`. now that we have a more convenient way to make amounts we could change those to take branded amounts.

File: packages/inter-protocol/src/contractSupport.js (hunk 2 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/contractSupport.js:32]: I moved it.

File: packages/inter-protocol/src/contractSupport.js (hunk 3 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/contractSupport.js:99]: I left it here because there wasn't a good  place in `/price/`, and this is pretty close.

File: packages/inter-protocol/src/vaultFactory/proceeds.js (hunk 8 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/proceeds.js:188]: done

File: packages/inter-protocol/src/vaultFactory/proceeds.js (hunk 7 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/proceeds.js]: done

File: packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js (hunk 13 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js:2731]: I was wrong. In an *assertLike*, `Fee: undefined` verifies that it's absent.

File: packages/inter-protocol/src/vaultFactory/proceeds.js (hunk 5 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/proceeds.js]: done

File: packages/inter-protocol/src/vaultFactory/proceeds.js (hunk 6 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/proceeds.js:158]: done

File: packages/inter-protocol/src/vaultFactory/proceeds.js (hunk 9 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/proceeds.js]: done

File: packages/inter-protocol/src/vaultFactory/proceeds.js (hunk 10 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/proceeds.js:234]: done

File: packages/inter-protocol/src/vaultFactory/proceeds.js (hunk 11 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/proceeds.js]: refactored

File: packages/inter-protocol/src/vaultFactory/vaultManager.js (hunk 4 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/vaultFactory/vaultManager.js]: done

File: packages/inter-protocol/test/vaultFactory/test-liquidation-plans.js (hunk 14 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/test/vaultFactory/test-liquidation-plans.js]: done

**Review by Chris-Hibbert — COMMENTED** [review]
These are nearly all very local cleanups or requests for more comments. The one that seems important is that plan.accounting should be immutable.

**Comment by Chris-Hibbert** [comment]
> each VaultManager, yes?

Correct. Fixed

**Comment by Chris-Hibbert** [comment]
> In 2a, all the collateral is sold, so how could there be excess collateral?

You are correct. We take the 2a branch when collateral is empty, so there can't be any to return. The code doesn't attempt to do anything with the collateral. I'll clean up the description.

**Review by dckc — APPROVED** [review]
This is pretty clearly a robust fix for the bug where subtraction overflow left vaults in a liquidating state (#7850).

Factoring out `calculateDistributionPlan` improves clarity substantially.

I didn't know the contract well before this PR, so I started reading it from scratch. I didn't get all the way through, so I'm not confident I could jump in right away to address maintenance going forward, but I'm definitely more familiar.

I don't see any regressions. I'm not as confident as I'd like to be that there are none, but I think relying on @turadg and @Chris-Hibbert there is a good plan.

**Comment by Chris-Hibbert** [comment]
@dckc, I accidentally erased your approval while I was attempting to re-request my review. I swear the button jumped while I was reaching for it.

**Review by Chris-Hibbert — APPROVED** [review]

**Review by dckc — APPROVED** [review]
> I swear the button jumped while I was reaching for it.

one of the great evils of our time
