### PR TITLE
fix: Remove superfluous -S for env in shebangs

### LINKED ISSUE #3709: docs say Ubuntu 18.04 but ci runs on 20.04
## Describe the bug

Trying to run the `agoric` cli on Ubuntu 18.04 results in `/usr/bin/env: invalid option --'S'`

## To Reproduce
1. Run Ubuntu 18.04.5
2. Follow the directions in https://agoric.com/documentation/getting-started/before-using-agoric.html

```
 user|project_dir $ agoric 
   /usr/bin/env: invalid option --'S'
```

## Platform Environment
 - what OS are you using? what version of Node.js? Ubuntu 18.04.5 , Node: 14.17.5
 - is there anything special/unusual about your platform? It's a little old.
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`) agoricstage-7-24-g29b9c5282

## Additional context

Looks like the `-S` is new a week or so ago:
https://github.com/Agoric/agoric-sdk/blame/master/packages/agoric-cli/lib/entrypoint.js#L1
https://github.com/Agoric/agoric-sdk/commit/d9a40194ad5bd0d05bcc8ef2a7de57b9d651e5be

And we don't test Ubuntu 18.04:
> Operating System: Ubuntu 20.04.2
-- https://github.com/Agoric/agoric-sdk/runs/3345379077?check_suite_focus=t

This is a reasonably well known portability issue.

[/usr/bin/env: invalid option \-\- 'S' \- Environments / Linux \- Travis CI Community](https://travis-ci.community/t/usr-bin-env-invalid-option-s/7121).

https://en.wikipedia.org/wiki/Shebang_(Unix)#Character_interpretation

cc @kriskowal @warner @katelynsills

### PR DESCRIPTION
**Pull request by kriskowal**
## Description

The `-S` flag on `/usr/bin/env` in `#!` lines is necessary when using extra command line flags like `-r esm` or `--inspect-brk`, but not portable to Linux. This change does not completely remove these lines but does remove all of the flags that are not necessary, and probably are vestiges of former use of `-r esm`.

### CODE REVIEW

File: packages/xsnap/src/replay.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 /**
  * Replay usage:
- *   node -r esm replay.js <folder>...
```
Comment (dckc) [inline packages/xsnap/src/replay.js]: I think that breaks usage of this module as a CLI script, powered by `if (require.main === module) { ... }` at the bottom.

NESM doesn't have an "if I have been invoked as a CLI script ..." idiom, does it?

**Review by dckc — CHANGES_REQUESTED** [review]
Maybe leave the `-r esm` vestiges for a separate PR?

Using `relay.js` as a cli script is important to not break; it's instrumental in our collaboration with Moddable.

File: packages/xsnap/src/replay.js (hunk 1 above)
Comment (kriskowal) [reply packages/xsnap/src/replay.js]: Evidently `new URL(import.meta.url).pathname === process.argv[1]` is the new idiom, or near to it as I could find.

**Comment by kriskowal** [comment]
I’ve moved the second commit to #3710

**Review by dckc — APPROVED** [review]
Thanks

File: packages/xsnap/src/replay.js (hunk 1 above)
Comment (mhofman) [reply packages/xsnap/src/replay.js]: Yeah I almost went down that rabbit hole, and apparently there is a package that wrap that logic (with some extra extension handling): https://www.npmjs.com/package/es-main
