### PR TITLE
fix dynamic vat replay

### LINKED ISSUE #1480: dynamic vats aren't replayed when kernel is restarted
**Describe the bug**

@FUDCo discovered that our dynamic vat support is incomplete. We're saving the transcripts and c-lists of dynamic vats into the kernel state DB, but not their code. At startup, the kernel does not regenerate the dynamic vats, so other vats which interact with them will fail.

This wouldn't be noticable if a contract vat completes its business before the host is shut down (i.e. a validator node reboots), but any contract that is still operating at that time would be non-functional when the node starts back up again.

To fix this, we'll need to save the dynamic vat's code (and/or the `bundleName` used to create it) in the DB. And we'll need to change the kernel startup code to look for dynamic vats and regenerate them, including replaying their transcripts.

### PR DESCRIPTION
**Pull request by warner**
Dynamic vats aren't getting reloaded properly: we aren't saving the source
bundle used to create them, nor are we loading them at startup time.

This adds test to exercise the problem, which fail ("unknown vatID") when we
start a new swingset from the old state vector. We'll fix the problem in the
next commit.

refs #1480

### CODE REVIEW

File: packages/SwingSet/src/kernel/dynamicVat.js [hunk 1]
```diff
@@ -13,34 +14,56 @@ export function makeDynamicVatCreator(stuff) {
...
+
+  function recreateVatDynamically(vatID, source, dynamicOptions) {
+    // eslint-disable-next-line no-use-before-define
+    return create(vatID, source, dynamicOptions, false);
+  }
+
+  function create(vatID, source, dynamicOptions, notifyNewVat) {
+    const vatSourceBundle = source.bundle || getBundle(source.bundleName);
+    if (!vatSourceBundle) {
+      throw Error(`Bundle ${source.bundleName} not found`);
```
Comment (FUDCo) [inline packages/SwingSet/src/kernel/dynamicVat.js:65]: This will be ugly if `source` has neither `bundle` nor `bundleName`.  Should either validate the `source` parameter or switch back to the 2-method API.

File: packages/SwingSet/src/kernel/dynamicVat.js [hunk 2]
```diff
@@ -104,13 +127,21 @@ export function makeDynamicVatCreator(stuff) {
     }
 
     function makeErrorResponse(error) {
+      if (!notifyNewVat) {
```
Comment (FUDCo) [inline packages/SwingSet/src/kernel/dynamicVat.js]: If the consequence of this flag being `false` here is a kernel panic, I think probably the flag should have a different name.

File: packages/SwingSet/src/kernel/dynamicVat.js [hunk 3]
```diff
@@ -13,34 +14,56 @@ export function makeDynamicVatCreator(stuff) {
...
-   * defines the vat. This should be generated by calling bundle-source on a
-   * module whose default export is makeRootObject(), which takes E as a
-   * parameter and returns a root object.
-   * @param options an options bundle. The only option defined so far is
-   * 'metered', which defaults to 'true'. If 'true', the new dynamic vat is
-   * subject to a meter that limits the amount of computation and allocation
-   * that can occur during any given crank. Stack frames are limited as well.
-   * The meter is refilled between cranks, but if the meter ever underflows,
-   * the vat is terminated. If 'false', the vat is unmetered.
+   * @param source an object which either has a `bundle` (JSON-serializable
```
Comment (FUDCo) [inline packages/SwingSet/src/kernel/dynamicVat.js:28]: _Really_ not a fan of switching from two methods with simple APIs to one method with a complicated API.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 4]
```diff
@@ -31,12 +31,17 @@ const enableKernelPromiseGC = true;
...
 // vat.names = JSON([names..])
+// vat.dynamicIDs = JSON([vatIDs..])
 // vat.name.$NAME = $vatID = v$NN
 // vat.nextID = $NN
 // device.names = JSON([names..])
 // device.name.$NAME = $deviceID = d$NN
 // device.nextID = $NN
 
+// dynamic vats have these too:
+// v$NN.source = JSON({ bundle }) or JSON({ bundleName })
```
Comment (FUDCo) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:42]: I suspect overloading this is the tail that wagged to dog w.r.t the API complexity I complained about above.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 5]
```diff
@@ -498,6 +504,18 @@ export default function makeKernelKeeper(storage) {
     return storage.get(k);
   }
 
+  function addDynamicVatID(vatID) {
```
Comment (FUDCo) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:507]: I'm presuming that the plan is (eventually) for dead vats to be removed from `vat.dynamicIDs`?  Also, might it make sense to put them in a separate identifier namespace (e.g., `vd$NN`) and allocate them here, instead of passing the ID in, as that might reduce the chances of a coordination failure between allocation and use?

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 6]
```diff
@@ -31,12 +31,17 @@ const enableKernelPromiseGC = true;
 // The schema is:
 //
 // vat.names = JSON([names..])
+// vat.dynamicIDs = JSON([vatIDs..])
```
Comment (FUDCo) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:34]: Let me know when you think the schema changes have stabilized, as I (or somebody, but probably me) will need to update the `kerneldump` utility to match.

**Review by FUDCo — APPROVED** [review]
Looks good aside from my issues below w.r.t the complexification of the API.  I don't think those concerns are major enough to stop the train (hence I'm approving) but I'm a wee bit cranky about them.  Also one or two of other totally non-blocking minor nits to address at your leisure.

**Review by michaelfig — COMMENTED** [review]
Would it make sense to add the genesis vats to the kernelDB as well, and treat their sources the same as the dynamic vats?  I would like this, so that it's a little harder to accidentally modify the genesis vat source code without resetting state from scratch, and also so that exporting the kernel state is just a matter of doing a direct dump of the kernelDB and not having to rebundle sources at export time (which is sensitive to the bundler we use, and any changes to the sources).  It would also mean we don't need to copy the vat directory to every created basedir.

If not now, but you think this is a good idea, I can create an issue for it.

**Comment by warner** [comment]
> Would it make sense to add the genesis vats to the kernelDB as well, and treat their sources the same as the dynamic vats? I would like this, so that it's a little harder to accidentally modify the genesis vat source code without resetting state from scratch, and also so that exporting the kernel state is just a matter of doing a direct dump of the kernelDB and not having to rebundle sources at export time (which is sensitive to the bundler we use, and any changes to the sources). It would also mean we don't need to copy the vat directory to every created basedir.
> 
> If not now, but you think this is a good idea, I can create an issue for it.

Yes, absolutely. I think we'll wind up going farther than that: the "payload"/deployment level of the stack will be defined by a set of additions to the "blob pool" (where bundles get stored), and an initial series of messages to the singular initial vat, which creates dynamic vats for zoe and whatever else the system should have from T=2 (where T=1 has the initial vat but nothing else). Genesis vats should be replaced by messages. I'm not sure how long the medium-term (genesis vat source code goes into the DB) will last, so I'm kinda deferring it a bit in the hopes we can jump directly to the messages form, but if we haven't made any progress on the latter within, say, a month, let's go ahead and do the genesis-code-in-DB thing.

File: packages/SwingSet/src/kernel/dynamicVat.js (hunk 2 above)
Comment (warner) [reply packages/SwingSet/src/kernel/dynamicVat.js]: fair point, I think I have a way to rewrite that flow: instead of conditionals in the callbacks, I'll do something like this at the bottom of the file:

```js
    const p = Promise.resolve().then(build);
    if (notifyNewVat) {
      p.then(makeSuccessResponse, makeErrorResponse)
        .then(sendResponse)
        .catch(err => console.error(`error in createVatDynamically`, err));
    } else {
      p.catch(errorDuringReplay);
    }
```

File: packages/SwingSet/src/kernel/dynamicVat.js (hunk 3 above)
Comment (warner) [reply packages/SwingSet/src/kernel/dynamicVat.js:28]: I hear you, but we can't simplify it to the point that `dynamicVat.js` only hears about full bundle objects, as it did before. If we did that, the create-from-name case would throw away the name before `dynamicVat.js` heard about it, which means it would have to store the full (unnamed) bundle into the DB for both cases, not just create-from-bundle. By retaining the name (when one is available), we can store just the name in the DB. And that feels like it's going to be important for storage-performance pretty quickly.

The fully-denormalized(?) alternative would probably be for `vatKeeper` to have two separate methods (one that returns a source bundle or `undefined`, a second which returns a source bundleName or undefined). The kernel would call both in succession to see which one has a value. Then `dynamicVat.js` must expose *four* methods (first-time-vs-replay times name-vs-bundle). That felt like a net complexity increase over the polymorphic `source` argument. We could have it expose two methods (name-vs-bundle) and make both take an optional `vatID` to select between first-time-vs-replay, but I was more uncomfortable using polymorphism over `vatID` than I was over `source`.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 4 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:42]: It did make it make the other pieces fall into that shape, yeah. My first pass had separate `v$NN.sourceBundle` and `v$NN.sourceBundleName`, with a comment that there should only ever be one, which is a sort of fussy invariant that I always want to avoid (better to have the rule be present-or-not than one-of-two).

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 5 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:507]: Yeah, we'll remove them from that list when they're really dead. For our intermediate step, the dead vats will be remembered by a `vat.dynamicIDs` entry and a `v$NN.dead` flag (and no other `v$NN.*` keys), which will tell our startup code to create a dead-vat no-manager no-vatKeeper `ephemeral.vats` entry for it. The step after that, when we remove them completely (no object-table/etc references), will delete the two remaining DB keys, and the only trace that they ever existed will be the suspiciously-elevated `nextVatID` counter. And of course the vat will live on in the memories (messages/transcripts) of all those (surviving vats) who loved it.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 6 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:34]: It's probably stable enough now. Unless it breaks something (which, if there were unit tests for `kernelDump`, I would have noticed :wink:), I think we can ignore the new keys until your dead-vat changes land, and update `kernelDump` for both at the same time.

Comment (FUDCo) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:34]: Adding to the database schema doesn't break `kernelDump` but if it knows about the new items it can display them more usefully.
