### PR TITLE
fix(zcf): mint kind during reincarnation

### LINKED ISSUE #7502: ZCF registerFeeMint fails reincarnation
## Describe the bug

If a contract calls `registerFeeMint` then in its reincarnation (`restartContract`) it will fail with the following error,
```
Error#1: no kind info for 21 ( o+d21/1 ); check deserialize preceeding kind definitions
```

## To Reproduce

```sh
git checkout 7466-psm-upgrade
cd packages/inter-protocol
yarn test test/swingsetTests/psmUpgrade/
```

It works before restart,
```
About to registerFeeMint {
  feeMintAccess: Object [Alleged: FeeMint feeMintAccess] {},
  initialPoserInvitation: Object [Alleged: Zoe Invitation payment] {},
  marshaller: Object [Alleged: Board readonlyMarshaller] {},
  storageNode: Object [Alleged: ChainStorageNode] {}
}
----- BootPSMUpg.3  5 BOOT buildV1 started instance
----- BootPSMUpg.3  6 testFunctionality1
```

but fails in restart,
```
----- BootPSMUpg.3  7 BOOT nullUpgradeV1 start
----- BootPSMUpg.3  8 BOOT nullUpgradeV1 upgradeContract
UnhandledPromiseRejectionWarning: (Error#1)
Nested error under Error#1
Error#1: no kind info for 21 ( o+d21/1 ); check deserialize preceeding kind definitions
…
  at makeZCFMintFactory (.../zoe/src/contractFacet/zcfMint.js:167:11)
  at initSeatMgrAndMintFactory (.../zoe/src/contractFacet/zcfZygote.js:335:22)
  at Object.restartContract (.../zoe/src/contractFacet/zcfZygote.js:420:7)
```

Note the ZCF fix that makes this problem detected sooner: https://github.com/Agoric/agoric-sdk/commit/7e3986a5b4a36028610d1a4e42c340884f059012

## Expected behavior

Contracts using registerFeeMint are restartable

### PR DESCRIPTION
**Pull request by turadg**
closes: #7502 

## Description

ZCF mint types were failing to restore during reincarnation. @warner traced this down to a faulty argument to `zcfMintBaggage.add()`. That should have been caught by TypeScript but wasn't due to https://github.com/Agoric/agoric-sdk/issues/7507

There was an additional bug in awaiting a remote call (zoe vat from zcf vat) during reincarnation. This precludes the call during reincarnation by keeping the result in baggage. This changed allowed for less async handling so this also cleans up some related paths.

### Security Considerations

issuer record in baggage

### Scaling Considerations

--

### Documentation Considerations

--

### Testing Considerations

Existing tests pass. No unit tests for regression because it will be stressed by contract upgrade tests such as for https://github.com/Agoric/agoric-sdk/issues/7466 in which this problem was discovered.

### CODE REVIEW

File: packages/zoe/src/contractFacet/zcfMint.js [hunk 1]
```diff
@@ -18,14 +18,14 @@ import './types.js';
...
-  recordIssuer,
-  getAssetKindByBrand,
-  makeEmptySeatKit,
-  reallocator,
+export const makeZCFMintFactory = (
+  /** @type {import('@agoric/vat-data').Baggage} */ zcfBaggage,
+  /** @type {{ (keyword: string, issuerRecord: IssuerRecord): void }} */ recordIssuer,
+  /** @type {GetAssetKindByBrand} */ getAssetKindByBrand,
+  /** @type { (exit?: undefined) => { zcfSeat: any; userSeat: Promise<UserSeat> }} */ makeEmptySeatKit,
+  /** @type {ZcfMintReallocator} */ reallocator,
```
Comment (erights) [inline packages/zoe/src/contractFacet/zcfMint.js:26]: This seems like a radical shift in style from `@param`. Why? At least at first, I do not find it more readable.

File: packages/zoe/src/contractFacet/zcfZygote.js [hunk 2]
```diff
@@ -90,7 +90,10 @@ export const makeZCFZygote = async (
   // Make the instanceRecord
   const makeInstanceRecord = makeInstanceRecordStorage(zcfBaggage);
 
-  const recordIssuer = (keyword, issuerRecord) => {
+  const recordIssuer = (
+    /** @type {string} */ keyword,
+    /** @type {IssuerRecord} */ issuerRecord,
```
Comment (erights) [inline packages/zoe/src/contractFacet/zcfZygote.js:95]: ditto

**Review by erights — APPROVED** [review]
LGTM. Question about formatting, but don't let it slow things down.

File: packages/zoe/src/contractFacet/zcfMint.js [hunk 3]
```diff
@@ -18,14 +18,14 @@ import './types.js';
...
 ) => {
-  /** @type {SetStore<ZCFMint>} The set of baggages for zcfMints */
+  /** @type {SetStore<import('@agoric/vat-data').Baggage>} The set of baggages for zcfMints */
```
Comment (warner) [inline packages/zoe/src/contractFacet/zcfMint.js:28]: Is there any way to make this type more specific, to declare that it holds a set of `zcfMintBaggage` (which has a particular set of keys), rather than a set of generic Baggage (which itself is just a MapStore)?

File: packages/zoe/src/contractFacet/zcfMint.js [hunk 4]
```diff
@@ -150,21 +143,24 @@ export const makeZCFMintFactory = async (
...
         });
-        const zcfMint = await makeDurableZcfMint(
-          keyword,
-          zoeMint,
-          zcfMintBaggage,
-        );
-        zcfMintBaggageSet.add(zcfMint);
-        return zcfMint;
+
+        zcfMintBaggage.init('issuerRecord', issuerRecord);
```
Comment (warner) [inline packages/zoe/src/contractFacet/zcfMint.js:152]: This works, but it now looks awfully like per-`zcfMint` state, and I wouldn't mind a cleanup pass that replaced the `prepareSingleton` (one Kind per mint) with a `prepare` something else that shared a single Kind among all mints, with `state.keyword`, `state.zoeMint`, and `state.issuerRecord`. That would make startup faster, remove the extra Kinds, reduce memory use a little bit, and be generally simpler.

But, probably out of scope for this PR.

**Review by warner — APPROVED** [review]
I share MarkM's questions, but LGTM, even without the proposed simplification.

File: packages/zoe/src/contractFacet/zcfMint.js (hunk 1 above)
Comment (turadg) [reply packages/zoe/src/contractFacet/zcfMint.js:26]: It's the style that "infer params from usage" automates. I think it's worth allowing because it removes the need to repeat the parameter name.

File: packages/zoe/src/contractFacet/zcfMint.js (hunk 3 above)
Comment (turadg) [reply packages/zoe/src/contractFacet/zcfMint.js:28]: It would be pretty awkward since a MapStore allows any keys. We could have a subtype that maintains a list of keyname to type mappings and conditions `get`/`init`/`set` accordingly but I'm not sure it's a good idea and it's definitely out of scope :)

File: packages/zoe/src/contractFacet/zcfMint.js (hunk 4 above)
Comment (turadg) [reply packages/zoe/src/contractFacet/zcfMint.js:152]: Good idea. I'll follow up with that.
