### PR TITLE
restore types linting

### LINKED ISSUE #4620: Type checker in IDE and CLI/CI sometimes disagree
## Describe the bug

Presently, successful type checking depends on a `--maxNodeModulesJsDepth` flag which IDE use doesn't support. In some cases, `@ts-expect-error` can't be used because the IDE and CLI/CI disagree about the set of errors.

## Expected behavior
Set of errors reported by type checker is consistent no matter where it's run.

## Additional context

https://github.com/Agoric/agoric-sdk/issues/4560 will fix that but that's a work item and this ticket is the bug itself. Easier to find by title search and more clear when linked to from code as to why. When that's resolved it would be good to find the `ts-ignore` we resorted to and replace them with `ts-expect-error` where possible. I'm assigning this to myself to take care of that.

### LINKED ISSUE #5788: linting types disabled (too slow)
## What is the Problem Being Solved?

The lint test sometimes fails even though there are no errors. The output shows no lint errors and running lint locally passes, but the exit code is 1.

```
✖ 54 problems (0 errors, 54 warnings)
lerna success - @agoric/ui-components
lerna success - @agoric/vat-data
lerna success - @agoric/wallet-connection
lerna success - @agoric/web-components
lerna success - @agoric/xsnap
lerna success - @agoric/wallet-backend
lerna success - @agoric/wallet-ui
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

Some instances:
https://github.com/Agoric/agoric-sdk/runs/7430249641?check_suite_focus=true

They're all in `lint-rest` which has grown from 9m when typed linting was enabled to 30min in a recent run. `@agoric/wallet-backend` alone took 20min. I did some investigation but after a while gave up as it's not a priority. It was only producing warnings and we've resolved many of them. The rest will probably take a ticket to resolve and in that one we can enable the flag locally to get all the warnings.

So for now it's disabled. https://github.com/Agoric/agoric-sdk/pull/5780/commits/4a84690f226c2e20bce25629757de4113f79d931

## Description of the Design

No diagnosis yet.

### PR DESCRIPTION
**Pull request by turadg**
closes: #5788
refs: #7888

## Description

Types linting got very slow so we had to disable it.

https://github.com/typescript-eslint/typescript-eslint/pull/6754 solved a problem in linting plugin whereby it was repeating work.

It worked by operating more like the IDE so I thought it would also help with #4620 , but when I tested in VS Code the ESLint plugin failed. I bet it will get worked out eventually. Meanwhile we can still use this new option for CI runs, restoring our floating-promise warnings and opening the door to error on them. 

### Documentation Considerations

Reviewers, it is recommended to review by commit.

### Testing Considerations

CI

The two lint jobs each take 5min. (Only 30s of that is setup overhead so they could be combined into one job that takes ~10min, which is still faster than most of the jobs. It might be even faster that than since this new option re-uses projects. But I'll leave that consolidation to another PR since it affects the GH repo "required checks" rules.)

### CODE REVIEW

File: packages/SwingSet/misc-tools/db-delete.js [hunk 1]
```diff
@@ -1,4 +1,5 @@
 #!/usr/bin/env node
+// @ts-nocheck
```
Comment (kriskowal) [inline packages/SwingSet/misc-tools/db-delete.js:2]: I was dismayed by all these `@ts-nocheck` until I realized that they weren’t previously checked and that you’ve just moved the exclusion from `jsconfig.json` to individual files, presumably so we can reveal them to the checker individually. Carry on.

File: .eslintrc.cjs [hunk 2]
```diff
@@ -36,6 +36,8 @@ module.exports = {
   parser: '@typescript-eslint/parser',
   parserOptions: lintTypes
     ? {
+        // this is not yet compatible with eslint lsp so it's conditioned on AGORIC_ESLINT_TYPES
```
Comment (kriskowal) [inline .eslintrc.cjs:39]: Recommend “gated”, “contingent on”, or “predicated”.

**Review by kriskowal — APPROVED** [review]

File: packages/SwingSet/misc-tools/db-delete.js (hunk 1 above)
Comment (turadg) [reply packages/SwingSet/misc-tools/db-delete.js:2]: bingo. glad that was apparent enough since I was too lazy to leave a comment explaining

File: .eslintrc.cjs (hunk 2 above)
Comment (turadg) [reply .eslintrc.cjs:39]: all better, though imo not different enough to suffer through the _Chain deployment test_ again.
