### PR TITLE
fix(telemetry): handle smallcaps and msg formatting

### LINKED ISSUE #6991: slog sender error: spanKey not found
## Describe the bug

I get this weird error in my node log.

## To Reproduce
_IOU_

## Expected behavior
...

## Platform Environment
 - what OS are you using? what version of Node.js?

linux
v16.19.0

 - is there anything special/unusual about your platform?

 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

6673db
20230209023556-6673db-linux_amd64

## Additional context
[Add any other context about the problem here.](https://github.com/Agoric/agoric-sdk/pull/6960)

## Screenshots

```
WARNING: slog sender error (Error#4056)
Error tracing slog: {
  type: 'deliver-result',
  crankNum: 901n,
  vatID: 'v2',
  deliveryNum: 33n,
  replay: false,
  dr: [
    'ok',
    null,
    {
      meterType: 'xs-meter-20',
      currentHeapCount: 89254,
      compute: 165310,
      allocate: 42074144,
      timestamps: [Array]
    }
  ],
  time: 1676309901.233356,
  monotime: 497.07128099900007
} (Error#4057)
Error#4057: spanKey not found: ["crank",901]

  at assertKeyExists (packages/store/src/legacy/legacyMap.js:39:23)
  at Object.get (packages/store/src/legacy/legacyMap.js:52:7)
  at Object.get (packages/telemetry/src/slog-to-otel.js:304:26)
  at slogSender (packages/telemetry/src/slog-to-otel.js:586:15)
  at wrappedSlogSender (packages/telemetry/src/slog-to-otel.js:924:7)
  at slogSender (packages/telemetry/src/make-slog-sender.js:156:11)
  at process.<anonymous> (packages/telemetry/src/slog-sender-pipe-entrypoint.js:99:13)
  at process.emit (node:events:513:28)

WARNING: slog sender error (Error#4057)
```

cc @mhofman

### PR DESCRIPTION
**Pull request by mhofman**
closes: #6991

Best reviewed commit-by-commit

## Description

Handles smallcaps in messages by relying on `@endo/marshal` instead of assuming and parsing JSON for the body.

I had written this a while ago as part of wider telemetry improvements, which I partially brought over here on the premise they're self contained and my previous smallcaps integration is easier with these changes.

Rewrote the error handling logic in the flows touching the slog sender to propagate errors into the flush operation, and added an option to fail when such errors occur. This should avoid the recurring regressions we have been experiencing.

### Security Considerations

None, telemetry only

### Scaling Considerations

None

### Documentation Considerations

None

### Testing Considerations

Tested in a local loadgen run with slog-to-otel sender enabled, and the new fail option, with and without the slog sender producing errors.

The whole telemetry package still lacks unit tests, and this does not change that. It does have slightly better typing, and new checks during the deployment integration test.

### CODE REVIEW

File: packages/telemetry/src/slog-to-otel.js [hunk 1]
```diff
@@ -128,16 +189,7 @@ export const makeSlogToOtelKit = (tracer, overrideAttrs = {}) => {
...
-        delete attrs.msg;
-        const { methargs, method = extractMethod(methargs) } = message.msg;
-        const slots =
-          message.msg.methargs?.slots ?? message.msg.args.slots ?? [];
-        attrs.details = `E(${message.target}).${method}`;
-        attrs['msg.target'] = message.target;
-        attrs['msg.method'] = method;
-        attrs['msg.slots'] = slots.join(',');
-        attrs['msg.result'] = message.msg.result;
+        assign(attrs, formatMsg(message.target, parseMsg(message.msg)));
```
Comment (dckc) [inline packages/telemetry/src/slog-to-otel.js:240]: this change from `{'msg.target': ...}` to `{msg: {target: ...}}` is intended, right?

File: packages/telemetry/src/slog-to-otel.js [hunk 2]
```diff
@@ -106,6 +110,57 @@ export const makeSlogToOtelKit = (tracer, overrideAttrs = {}) => {
   const dbTransactionManager = makeKVDatabaseTransactionManager(db);
   const kernelPromiseToSendingCause = makeKVStringStore('kernelPromise', db);
 
+  /** @type {WeakMap<Promise | object, {kref: string, iface: string | undefined}>} */
+  const presenceMap = new WeakMap();
+  /** @type {Map<string, Promise | object>} */
+  const valCache = new Map();
+
+  const slotToVal = (kref, iface) => {
```
Comment (dckc) [inline packages/telemetry/src/slog-to-otel.js:117]: why does handling smallcaps need the whole `slotToVal` machinery? How did we get by without it before?

Comment (dckc) [reply packages/telemetry/src/slog-to-otel.js:117]: is this just handling smallcaps in the way we did before? Or is it parsing the whole message in a more fine-grain way or something?

**Review by dckc — COMMENTED** [review]
I need to understand the smallcaps marshal stuff better

File: packages/telemetry/src/slog-to-otel.js (hunk 1 above)
Comment (mhofman) [reply packages/telemetry/src/slog-to-otel.js:240]: There is actually no change, the serializer this goes through results in the same output

File: packages/telemetry/src/slog-to-otel.js (hunk 2 above)
Comment (mhofman) [reply packages/telemetry/src/slog-to-otel.js:117]: It was not handling smallcaps at all before, just throwing because `body` started with a `#` which is invalid JSON. 

Before we were manually parsing `body` assuming it was a JSON serialized string, more precisely a qclass based caps encoding.

This is the same kind of change that the kernel went through in https://github.com/Agoric/agoric-sdk/pull/6450, and uses a dummy `slotToVal` converter.

File: packages/telemetry/src/slog-to-otel.js [hunk 3]
```diff
@@ -104,13 +110,124 @@ export const makeSlogToOtelKit = (tracer, overrideAttrs = {}) => {
...
+    kref[0] === 'k' || assert.fail(`Unexpected non-kernel ref ${kref}`);
+    val = harden(
+      kref.startsWith('kp')
+        ? new Promise(sink)
+        : Remotable(iface || 'Remotable'),
+    );
+    valCache.set(kref, val);
+    presenceMap.set(val, { kref, iface });
+
+    return val;
```
Comment (michaelfig) [inline packages/telemetry/src/slog-to-otel.js]: Why not just:

```suggestion
  if (!valCache.has(kref)) {
    valCache.set(kref, { kref, iface });
  }
  return valCache.get(kref);
```

File: packages/telemetry/src/slog-to-otel.js [hunk 4]
```diff
@@ -104,13 +110,124 @@ export const makeSlogToOtelKit = (tracer, overrideAttrs = {}) => {
...
+  };
+
+  const valToSlot = val => {
+    const { kref } = presenceMap.get(val) || {};
+    kref || assert.fail(`Unknown val ${val}`);
+    return kref;
+  };
+
+  const { unserialize: rawUnserialize } = makeMarshal(valToSlot, slotToVal, {
```
Comment (michaelfig) [inline packages/telemetry/src/slog-to-otel.js]: `valToSlot` is not needed if the only thing you're creating is `unserialize`.

```suggestion
  const { unserialize: rawUnserialize } = makeMarshal(undefined, slotToVal, {
```

**Review by michaelfig — COMMENTED** [review]
I pointed out a few places that can be simplified, and in doing so, drop some unnecessary bookkeeping.

**Review by michaelfig — APPROVED** [review]
@mhofman and I discussed where his change stack is going, and I'm alright with maintaining things after this PR lands, given that it is an incremental step towards the ideal.

**Comment by michaelfig** [comment]
Here's the type error that messes up `lint-rest`: https://github.com/Agoric/agoric-sdk/actions/runs/4189275332/jobs/7261459281#step:4:118

File: packages/telemetry/src/slog-to-otel.js (hunk 3 above)
Comment (mhofman) [reply packages/telemetry/src/slog-to-otel.js]: As discussed, marshal now enforces that a remotable / promise actually checks against `passStyleOf`, so `Remotable` / `Promise` is necessary.

The `presenceMap` however is a leftover from a large change where I used serialization. I can remove.

**Comment by mhofman** [comment]
@michaelfig could you please re-review? I ended up implementing the enforcement in the CI integration tests that the otel slog sender should not fail.

**Review by michaelfig — APPROVED** [review]
LGTM as the next step.
