### PR TITLE
fix(xsnap): take snapshot without impact on GC

### LINKED ISSUE #2469: review of Agoric additions to xsnap

### LINKED ISSUE #3139: XS instrumentation: upstream?
## What is the Problem Being Solved?

Integrating new XS code automatically (#2648) is infeasible since we switched over to our fork when we made some tweaks for instrumentation during testnet: https://github.com/agoric-labs/moddable/pull/5

## Description of the Design

Options include:
  - maintain the fork; manually integrate upstream changes as and when we notice them
  - upstream some of the changes; discard others as they become less necessary as more of our swingset GC works

cc @warner @kriskowal @dtribble @phoddie @michaelfig

### LINKED ISSUE #3577: XS GC timing changes after snapshot
## Description

Restoring from an XS snapshot results in a different heap organization, causing GC to happen at different times.

## To Reproduce

As in the `GC after snapshot vs restore` test c4f0cec https://github.com/Agoric/agoric-sdk/blob/snap-gc-sync/packages/xsnap/test/test-xsnap.js#L340-L373 :

1. Start an xsnap worker
2. Allocate a large array that causes garbage collection and then let it go out of scope.
3. Take a snapshot
4. Start a clone from the snapshot. (Its heap is cleaned up.)
5. Track GC in the worker and the clone; note that they happen at different times.

## Expected behavior

No observable differences between the worker and its clone.

## Additional context

Original diagnosis: https://github.com/Agoric/agoric-sdk/issues/3428#issuecomment-872024373

Moddable has a fix in https://github.com/agoric-labs/xsnap-pub/commit/94a7a88ad2301ccfa1390eaf34495af870bb8f0b :
> we reworked the chunk allocator to always use a single memory block for chunk storage.

But integrating it is non-trivial because
  1. We have not integrated the platform vs. application refactor https://github.com/agoric-labs/xsnap-pub/commit/c2cebe78c723ec4e7ebf452aac39e08aea889d3a
  2. The `xsnap-ava.c` code with our I/O loop has fallen behind.

cc @phoddie

### PR DESCRIPTION
**Pull request by dckc**
Moddable reworked the chunk allocator to always use a single memory block for chunk storage.

The change is implemented in `xsnapPlatform.c`. The implementation uses `mmap`/`mprotect` (`VirtualAlloc` on Windows) to reserve and to commit memory pages. 

To get this fix, we add an `xsnap-native` submodule that replaces `xsnap.c` and friends.
The submodule includes a few tweaks: https://github.com/agoric-labs/xsnap-pub/tree/endo-submodule

fixes #3577
fixes #3139 , bringing us back to stock XS.
fixes #2469 - Moddable reviewed the code well enough to substantially re-work it.

todo:
 - [x] reconcile `src/build.js` with `build:native`
 - [x] prune obsolete files: `xsnap.[ch]`, `makefiles`
   - [x] prune redundant docs
 - [x] add unit test

### CODE REVIEW

**Comment by dckc** [comment]
@michaelfig help me update `build.js`? Or tell me how to test that I broke it so I can try to fix it?

**Comment by michaelfig** [comment]
> @michaelfig help me update `build.js`? Or tell me how to test that I broke it so I can try to fix it?

The essential problem is that both the Docker build (ci and deployment/Makefile) and `build.js` assume only one submodule.  That needs to change.

Let's do a face-to-face to make sure we cover all the cases, whenever you're ready.

**Review by michaelfig — APPROVED** [review]
LGTM, just the little pasto in `packages/deployment/Makefile`.

**Comment by dckc** [comment]
With help from @kriskowal and @warner, I finally figured out a unit test that doesn't rely on `garbageCollectionCount`, using `WeakRef` instead.

@michaelfig helped me sort out the issues of building in the docker context. (Maybe I better double-check that it builds on a Mac...)

So I propose that this is ready to go. Please take a look.

File: packages/deployment/Makefile [hunk 1]
```diff
@@ -28,6 +28,8 @@ docker-build: docker-build-sdk docker-build-solo \
 docker-build-sdk:
 	docker build --build-arg=MODDABLE_COMMIT_HASH=$(MODDABLE_COMMIT_HASH) \
 		--build-arg=MODDABLE_URL=$(MODDABLE_URL) \
+		--build-arg=XSNAP_NATIVE_COMMIT_HASH=$(MODDABLE_COMMIT_HASH) \
+		--build-arg=XSNAP_NATIVE_URL=$(MODDABLE_URL) \
```
[the remark this answers is not in the document]
Comment (michaelfig) [reply packages/deployment/Makefile]: Not sure why this was resolved.  It looks like `$(XSNAP_NATIVE_URL)` and `$(XSNAP_NATIVE_COMMIT_HASH)` are unused.

**Review by michaelfig — CHANGES_REQUESTED** [review]

File: packages/deployment/Makefile (hunk 1 above)
[the remark this answers is not in the document]
Comment (dckc) [reply packages/deployment/Makefile]: oops. better now?

**Comment by dckc** [comment]
p.s. I _do_ propose to keep the commits separate, modulo fixups from review.

File: packages/xsnap/src/build.js [hunk 2]
```diff
@@ -1,70 +1,232 @@
+#!/usr/bin/env node
+/* eslint-disable no-await-in-loop */
```
Comment (kriskowal) [inline packages/xsnap/src/build.js]: I like to apply this on a case-by-case basis since sometimes it bullies me into using Promise.all when appropriate (parallel). The case in question is definitely serial.

File: packages/xsnap/src/build.js [hunk 3]
```diff
@@ -1,70 +1,232 @@
...
+ * Adapt spawn to Promises style.
+ *
+ * @param {string} command
+ * @param {{
+ *   spawn: typeof import('child_process').spawn,
+ * }} io
+ */
+function makeCLI(command, { spawn }) {
+  /** @param { import('child_process').ChildProcess } child */
+  const waiting = child =>
```
Comment (kriskowal) [inline packages/xsnap/src/build.js]: nit: suggest just `wait` for the verbly named function.

**Review by kriskowal — APPROVED** [review]

File: packages/xsnap/src/build.js (hunk 2 above)
Comment (dckc) [reply packages/xsnap/src/build.js]: indeed, this turned up a job for `Promise.all`

**Review by michaelfig — APPROVED** [review]
LGTM!

File: packages/xsnap/test/test-xs-perf.js [hunk 4]
```diff
@@ -55,18 +55,10 @@ test('meter details', async t => {
...
       compute: 'number',
       allocate: 'number',
-      allocateChunksCalls: 'number',
-      allocateSlotsCalls: 'number',
-      garbageCollectionCount: 'number',
-      mapSetAddCount: 'number',
-      mapSetRemoveCount: 'number',
-      maxBucketSize: 'number',
     },
     'auxiliary (non-consensus) meters are available',
```
Comment (warner) [inline packages/xsnap/test/test-xs-perf.js]: nit: this `'auxiliary (non-consensus) meters are available'` test description is no longer quite accurate

File: packages/xsnap/test/test-xsnap.js [hunk 5]
```diff
@@ -333,3 +335,83 @@ test('normal close of pathological script', async t => {
...
+  const optClone = { ...options(io), name: 'clone', snapshot };
+  const clone = xsnapr(optClone);
+  t.log('cloned', { snapshot });
+  t.teardown(clone.terminate);
+
+  let workerGC = beforeClone;
+  let cloneGC = workerGC;
+  let iters = 0;
+
+  while (workerGC === cloneGC && iters < 3) {
```
Comment (warner) [inline packages/xsnap/test/test-xsnap.js:408]: Looks like a good test.. it failed before the XS/xsnap change, right?

**Review by warner — APPROVED** [review]
Looks good!

File: packages/xsnap/test/test-xsnap.js (hunk 5 above)
Comment (dckc) [reply packages/xsnap/test/test-xsnap.js:408]: yes it failed before the change, as @kriskowal is my witness.

Comment (kriskowal) [reply packages/xsnap/test/test-xsnap.js:408]: I seen it 👀
