### PR TITLE
fix(notifier)!: Stop retaining durable publish kit values in RAM

### LINKED ISSUE #7298: Durable publish kits should not hold values in RAM
## What is the Problem Being Solved?
https://github.com/Agoric/agoric-sdk/pull/6502#pullrequestreview-1218750825
>  commit to doing more RAM-reducing perf work on it before it gets used in high-cardinality anger
> don't hold resolved Promises in RAM, instead keep the current value only in the DB

Basically, durable publish kits keep a `durablePublishKitEphemeralData` WeakMap in RAM where each key is a `publish` facet and the corresponding value is a record containing latest-result promise, next-result promise, and next-result resolve function, and the cache entry for a kit is populated by [`provideDurablePublishKitEphemeralData`](https://github.com/Agoric/agoric-sdk/blob/ed68edf80ceb09e619877e820cf57266948470a2/packages/notifier/src/publish-kit.js#L227) upon subscribing to it or publishing a new value, in both cases with the current-result promise settled to a record containing the current value when there is one (and therefore holding it in RAM).

## Description of the Design
The kits should instead let go of published values and recreate promises as needed by methods of its `subscriber` facet. It will still be necessary to hold on to non-durable published values when we support them, but they are currently forbidden by the [restriction of `valueDurability` to 'mandatory'](https://github.com/Agoric/agoric-sdk/blob/ed68edf80ceb09e619877e820cf57266948470a2/packages/notifier/src/publish-kit.js#L185).

## Security Considerations

The identity of promises from interactions with a durable publish kit will be observably different. However, promise identity is not preserved between vats and in general is not considered important even within the same vat.

## Scaling Considerations

This should significantly reduce durable representative count and therefore RAM consumption in vats hosting instances of durable publish kits.

## Test Plan

This merits a distinct test that publishes a sequence of values and interrogates liveslots after each.

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #7298

## Description

Refactor ephemeral data to retain a promise resolved to the current value only when that value is ephemeral, which is currently prohibited by the [restriction of valueDurability to 'mandatory'](https://github.com/Agoric/agoric-sdk/blob/ed68edf80ceb09e619877e820cf57266948470a2/packages/notifier/src/publish-kit.js#L185).

### Security Considerations

n/a

### Scaling Considerations

This PR reduces RAM consumption by allowing durable promise kit resolution values to be paged out.

### Documentation Considerations

This change is breaking only because the identity of promises and `head` objects is no longer preserved, but I don't believe we ever promised such preservation and it isn't observable across vat boundaries anyway.

### Testing Considerations

I still want a test that verifies lack of retention, and am open to ideas regarding the best pattern for that.

### CODE REVIEW

**Review by FUDCo — COMMENTED** [review]
This all looks quite sensible to me, but it's far enough outside my wheelhouse that I'm not comfortable giving it a thumbs up (or down) just on my own.  So consider this a kinda-sorta approval conditional on someone whose promise-fu is greater than mine giving it their blessing.

File: packages/notifier/src/publish-kit.js [hunk 1]
```diff
@@ -216,75 +216,90 @@ const initDurablePublishKitState = (options = {}) => {
...
+  if (currentP) {
+    return currentP;
+  }
+
+  const { publishCount, status, hasValue, value } = state;
+  if (!hasValue) {
+    assert(status === 'live');
+    return tail;
+  }
+  if (status === 'live' || status === 'finished') {
```
Comment (michaelfig) [inline packages/notifier/src/publish-kit.js:255]: Maybe use `switch (status)` here?

File: packages/notifier/src/publish-kit.js [hunk 2]
```diff
@@ -216,75 +216,90 @@ const initDurablePublishKitState = (options = {}) => {
...
-      tailP,
-      tailR: undefined,
-    };
-  } else if (status === 'live') {
-    const { promise: tailP, resolve: tailR } = makePromiseKit();
+
+  const { status } = state;
+  let tailP;
+  let tailR;
+  if (status === 'live') {
```
Comment (michaelfig) [inline packages/notifier/src/publish-kit.js:292]: Again?

**Review by michaelfig — APPROVED** [review]
LGTM.  IIUC, avoiding keeping `currentP` around where possible and reconstituting it when necessary is what makes this change use less memory.

I'll defer to your preference on whether `if` or `switch` is better for dispatching `state.status`.

File: packages/notifier/src/publish-kit.js [hunk 3]
```diff
@@ -216,75 +216,90 @@ const initDurablePublishKitState = (options = {}) => {
  */
 const getEphemeralKey = facets => facets.publisher;
 
-/** @type {WeakMap<DurablePublishKitEphemeralKey, {currentP, tailP, tailR}>} */
+/**
+ * @typedef DurablePublishKitEphemeralData
+ * @property {Promise<*> | undefined} currentP The current-result promise
+ *   (undefined unless resolved with unrecoverable ephemeral data)
+ * @property {Promise<*>} tailP The next-result promise
+ * @property {import('@endo/promise-kit').PromiseKit<*>['resolve'] | undefined} tailR The next-result resolver
```
Comment (mhofman) [inline packages/notifier/src/publish-kit.js]: Why import the resolve definition? It's pretty standard:

```suggestion
 * @property {((value: *) => void) | undefined} tailR The next-result resolver
```

File: packages/notifier/src/publish-kit.js [hunk 4]
```diff
@@ -304,32 +319,30 @@ const advanceDurablePublishKit = (context, value, targetStatus = 'live') => {
...
   }
-  durablePublishKitEphemeralData.set(
-    getEphemeralKey(facets),
-    harden({ currentP, tailP, tailR }),
-  );
 
+  let currentP;
   if (targetStatus === 'failed') {
     state.hasValue = true;
     state.value = value;
```
Comment (mhofman) [inline packages/notifier/src/publish-kit.js:344]: Could this not throw if the fail `reason` is not durable? I think we would get into an inconsistent state then?

Same below for a final value (hidden because not changed)

File: packages/notifier/src/publish-kit.js [hunk 5]
```diff
@@ -216,75 +216,90 @@ const initDurablePublishKitState = (options = {}) => {
...
+  const ephemeralKey = getEphemeralKey(facets);
+  const foundData = durablePublishKitEphemeralData.get(ephemeralKey);
+  const currentP = foundData?.currentP;
+  if (currentP) {
+    return currentP;
+  }
+
+  const { publishCount, status, hasValue, value } = state;
+  if (!hasValue) {
+    assert(status === 'live');
```
Comment (mhofman) [inline packages/notifier/src/publish-kit.js:252]: What happens if a publisher is finished or failed with a non-durable value/reason? Should we have a more descriptive error message?

**Review by mhofman — COMMENTED** [review]
I admittedly do not grok enough the publisher/subscribers to consider my review authoritative, but I have concerns about the handling of non-durable finish values and fail reasons. Arguably this was a problem before, but I have a hard time figuring out the state in which it leaves the ephemeral data.

On the memory usage, an empirical test seem to indicate we no longer hold virtual objects through the ephemeral data, so that's good! Of course we do still have a bunch of heap promise per publisher, but not much to do about this until we implement pseudo-promises.

File: packages/notifier/src/publish-kit.js [hunk 6]
```diff
@@ -15,6 +15,8 @@ const makeQuietRejection = reason => {
   void E.when(rejection, sink, sink);
   return rejection;
 };
+const makeTooFarRejection = () =>
+  makeQuietRejection(new Error('Cannot read past end of iteration.'));
```
Comment (mhofman) [inline packages/notifier/src/publish-kit.js]: So I actually found one more leak, at least in v8. Apparently the `Error`s structured stack keeps references to each call site, including in this case the context object of the `finish` call. That object is the `{state, facets}` context of the notifier exo kit. While this is most likely not a problem in XS, and likely applies to other Exo class based patterns, I figured it'd be easy enough to fix in this case since I don't believe there is much value in capturing the stack of when the publisher was finished.

image


```suggestion
const tooFarRejection = harden(
  makeQuietRejection(new Error('Cannot read past end of iteration.')),
);
```

File: packages/notifier/src/publish-kit.js (hunk 1 above)
Comment (gibson042) [reply packages/notifier/src/publish-kit.js:255]: Considered, but rejected because I want `provideCurrentP` and `provideDurablePublishKitEphemeralData` to remain compact.

File: packages/notifier/src/publish-kit.js (hunk 4 above)
Comment (gibson042) [reply packages/notifier/src/publish-kit.js:344]: Terminal values (from `finish` or `fail`) are required to be durable, enforced near the top of the function.
> ```js
>   const done = targetStatus !== 'live';
>   if (done || valueDurability === 'mandatory') {
>     canBeDurable(value) || Fail`Cannot accept non-durable value: ${value}`;
>   }
> ```

File: packages/notifier/src/publish-kit.js (hunk 5 above)
Comment (gibson042) [reply packages/notifier/src/publish-kit.js:252]: This is a true assertion; if there's no value and status is not "live" then the implementation has a bug.

File: packages/notifier/src/publish-kit.js (hunk 4 above)
Comment (mhofman) [reply packages/notifier/src/publish-kit.js:344]: Oh I missed that!

File: packages/notifier/src/publish-kit.js (hunk 6 above)
Comment (gibson042) [reply packages/notifier/src/publish-kit.js]: Fixed.

File: packages/notifier/src/publish-kit.js (hunk 3 above)
Comment (gibson042) [reply packages/notifier/src/publish-kit.js]: Done.

File: packages/notifier/src/publish-kit.js (hunk 6 above)
Comment (mhofman) [reply packages/notifier/src/publish-kit.js]: So the reason I suggested to `harden` was because the rejection would be shared instead of built for each publisher when reaching a terminal state.

**Review by mhofman — APPROVED** [review]

File: packages/notifier/src/publish-kit.js (hunk 6 above)
Comment (gibson042) [reply packages/notifier/src/publish-kit.js]: Yep, makes sense. And `makeQuietRejection` already hardens the returned promise.
