### PR TITLE
10143 require extensions

### LINKED ISSUE #10143: .js extension missing in imports from orchestration types files
## Describe the bug

The `.js` extension is missing from a couple imports:

https://github.com/Agoric/agoric-sdk/blob/f46aec96c6aa69bab926c682dbdd37845b3a5618/packages/orchestration/src/exos/exo-interfaces.ts#L4-L5

## To Reproduce
1. `yarn set version berry`; `yarn add @agoric/orchestration` to get `0.2.0-u17.1`
2. set up typescript `yarn add --dev typescript`; copy `.yarnrc.yml` and `tsconfig.json` from dapp-orchestration-basics
3. put `import { withOrchestration } from '@agoric/orchestration/src/utils/start-helper.js';` in `src/x.js`
3. `yarn tsc`
4. blammo:

```
$ yarn tsc
node_modules/@agoric/orchestration/src/exos/exo-interfaces.ts:4:44 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean '../utils/address.js'?

4 import type { ICAChannelAddressOpts } from '../utils/address';
                                             ~~~~~~~~~~~~~~~~~~

node_modules/@agoric/orchestration/src/exos/exo-interfaces.ts:5:36 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './icq-connection-kit.js'?

5 import type { ICQConnection } from './icq-connection-kit';
                                     ~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@agoric/orchestration/src/exos/exo-interfaces.ts:4
```

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context

working on
 - https://github.com/Agoric/dapp-orchestration-basics/pull/49

### PR DESCRIPTION
**Pull request by turadg**
closes: #10143

## Description

The local tsconfig using `moduleResolution: bundler` doesn't require it but consumers of these packages can have other moduleResolution configs that do. For example, dapp-orchestration-basics in #10143.

### Security Considerations
n/a

### Scaling Considerations
n/a

### Documentation Considerations
nothing

### Testing Considerations
ran `lint-fix` locally to test that it works.

### Upgrade Considerations
none

### CODE REVIEW

File: packages/orchestration/src/exos/exo-interfaces.ts [hunk 1]
```diff
@@ -1,8 +1,8 @@
 import type { IBCConnectionID } from '@agoric/vats';
 import type { Vow } from '@agoric/vow';
 import type { IcaAccount } from '../cosmos-api.ts';
-import type { ICAChannelAddressOpts } from '../utils/address';
-import type { ICQConnection } from './icq-connection-kit';
+import type { ICAChannelAddressOpts } from '../utils/address.js';
+import type { ICQConnection } from './icq-connection-kit.js';
```
Comment (mhofman) [inline packages/orchestration/src/exos/exo-interfaces.ts]: FWIW, we should be consistent in the extension used. Above is using `.ts`, which I'm ok with since it's an `import type`, but I do believe it's a risk for all of them since runtime imports would require a `.js` extension.

Consider the following:
```suggestion
import type { IcaAccount } from '../cosmos-api.js';
import type { ICAChannelAddressOpts } from '../utils/address.js';
import type { ICQConnection } from './icq-connection-kit.js';
```

I am confused however why this didn't result in a check failure since from what I gather, the plugin requires `.js` extensions to be used.

File: package.json [hunk 2]
```diff
@@ -26,6 +26,7 @@
     "eslint-plugin-import": "^2.29.1",
     "eslint-plugin-jsdoc": "^48.5.2",
     "eslint-plugin-prettier": "^5.1.3",
+    "eslint-plugin-require-extensions": "^0.1.3",
```
Comment (dckc) [inline package.json:29]: I wish we had a clear process for adding to our software supply chain.

I did a tiny bit of due diligence...

67k downloads/week. Last published 2 years ago. By solana-labs

**Review by dckc — APPROVED** [review]
Seems to fit the bill

File: packages/orchestration/src/exos/exo-interfaces.ts (hunk 1 above)
Comment (turadg) [reply packages/orchestration/src/exos/exo-interfaces.ts]: I tried https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/file-extension-in-import.md and it has the same problem.

Maybe by the time the lint rule sees the AST it's `.js`? Dunno.

Btw I tried out using the `eslint-plugin-n` rule but it balks at valid subpath imports like,
```js
import { sha256 } from '@noble/hashes/sha256';
import { bytesToHex } from '@noble/hashes/utils';
```
