### PR TITLE
misc Fast USDC cleanup 

### LINKED ISSUE #9934: sequence mismatch flake in multichain-testing
## What is the Problem Being Solved?

```
  Error: rewards available on osmosis condition failed after 8 retries.
    at retryUntilCondition (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/tools/sleep.ts:28:11)
    at async file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/test/stake-ica.test.ts:99:23
```

instances
- https://github.com/Agoric/agoric-sdk/actions/runs/10482566227/job/29033890661?pr=9395
- https://github.com/Agoric/agoric-sdk/actions/runs/10533760653/job/29190278931?pr=9953

### PR DESCRIPTION
**Pull request by turadg**
closes: #9934

## Description
Increases the threshold for multichain that has been timing out (à la #9934)

Also includes a couple tiny improvements to docs and logging.

### CODE REVIEW

File: multichain-testing/tools/e2e-tools.js [hunk 1]
```diff
@@ -23,8 +23,8 @@ import { makeTracer } from '@agoric/internal';
 const trace = makeTracer('E2ET');
 
 // The default of 6 retries was failing.
-// XXX even 15 wasn't enough
-const SMART_WALLET_PROVISION_RETRIES = 30;
+// XXX also tried 15, 30. There's probably something deeper to fix.
+const SMART_WALLET_PROVISION_RETRIES = 100;
```
Comment (dckc) [inline multichain-testing/tools/e2e-tools.js:27]: has a higher retry count ever helped?

my intuition says that the thing gets into a state where just retrying won't help.

**Review by dckc — APPROVED** [review]
it's not clear to me that waiting longer helps, but I guess it doesn't hurt much

File: multichain-testing/tools/e2e-tools.js (hunk 1 above)
Comment (turadg) [reply multichain-testing/tools/e2e-tools.js:27]: I think so but since it's intermittent it's hard to know for sure. If 100 doesn't work then I'll take a different tack.
