### PR TITLE
fix: clean up E.when and E.resolve

### LINKED ISSUE #1364: Fix odd use of E.when
https://github.com/Agoric/agoric-sdk/blob/2c7ba13e2a40413959e4d1ebc76b56d978b09975/packages/notifier/src/asyncIterableAdaptor.js#L112

This is not how `E.when` is meant to be used. Either substitute `E.resolve` (which, btw, is currently absent from the type declarations. See #1361 ) or replace the following `).then(` with a comma, so that the first and second `.then` arguments become the second and third `E.when` arguments. (This doesn't yet work in the type system because #1362 )

### PR DESCRIPTION
**Pull request by erights**
Fixes #1364 

See also #1361

### CODE REVIEW

File: packages/notifier/test/test-notifier-adaptor.js [hunk 1]
```diff
@@ -42,7 +43,8 @@ const finiteStream = makeIterable(false);
 const explodingStream = makeIterable(true);
 
 const testEnding = (t, p, fails) => {
-  return Promise.resolve(p).then(
+  return E.when(
```
Comment (michaelfig) [inline packages/notifier/test/test-notifier-adaptor.js:46]: Something about this change is failing tests.  Can you inspect the `E.when` implementation?

**Review by michaelfig — APPROVED** [review]
LGTM, modulo test failures.

File: packages/notifier/test/test-notifier-adaptor.js (hunk 1 above)
Comment (erights) [reply packages/notifier/test/test-notifier-adaptor.js:46]: The `when` implementation is fine, as is the line above. Rather, the problem is that the old `when` followed by `then` was causing an extra turn, leading to incorrect "lossy" testing happening to succeed. With only one `when` the order changed, the notifier lossiness changed, exposing a pattern of bugs in my lossiness testing. Fixed.
