### PR TITLE
fix(xsnap)!: avoid O(n^2) Array, Map, Set growth

### LINKED ISSUE #3012: xs performance investigation (array, Map/Set optimizations)
We're looking at nonlinear performance characteristics of the core datatypes (specifically Array, Map, Set) in XS.

_We originally focused on WeakMap, but that part has been addressed._

When we run our load-generator test, we see the zoe vat taking longer and longer with each load cycle. Our current implementation has the following properties:

* zoe has a [number](https://github.com/Agoric/agoric-sdk/blob/9746ae1a9d2d90310f75400527cf3dd947dda4a8/packages/zoe/docs/zoe-catalog-of-storage.md) of WeakMaps used to keep track of seats, invitations, etc
  * zoe was written with the assumption that the weakness of WeakMap is sufficient to remove the entries when they are no longer active, so there are no explicit `wm.delete()` calls
* swingset does not yet provide GC (#2615), so when liveslots creates a Presence and gives it to zoe, or when zoe creates a Remotable and sends it off-vat, that object will be kept alive by liveslots forever
* as a result, zoe's WeakMaps grow larger and larger over time, filled with a small number of actively-used items and a much larger number of items which would be garbage collected if only liveslots could drop them
* on each cycle of the load generator, zoe will add a few items to the WeakMap, and retrieve those same items
  * these items will always be the most recently added ones
* moreover (and probably more significant), our SES shim uses a single shared WeakMap to implement `harden` (specifically to track which objects have already been frozen or not). Since our programming/safety style is to `harden()` everything, this WeakMap will include everything that Zoe puts in the WeakMaps listed above, plus far more. Many of these objects will go away (they are not held by liveslots), but everything that liveslots is holding will probably be included in the harden WeakMap.

We don't specifically know that WeakMap is involved, but given how Zoe works, it's a reasonable hypothesis for something that might grow over time.

Our current working hypotheses are:

* the XS WeakMap implementation appears to use a simple linked list, which means read time for the first-added entry will be constant, while read time for the most-recently-added entry will be O(num_entries)
  *  zoe only interacts with the most-recently added entries, making this worst-case
* when adding a WeakMap entry, XS must get a new "slot" structure with `fxNewSlot`
  * if there is free space available (`the->freeHeap` holds a linked-list of free slots), no allocations are necessary
  * if not, `fxNewSlot` might trigger GC (`fxCollect`) to make some available, and/or it might call `fxGrowSlots` to allocate more by calling `malloc()`
  * because we aren't deleting items, we call `fxNewSlot` a lot
  * because the total number of objects in the heap is large, GC takes a long time, O(num_objects)

Together, this would explain a linear slowdown in the time each load-generator cycle takes. It would not explain the superlinear slowdown that we've measured.

### PR DESCRIPTION
**Pull request by dckc**
TODO:
 - [x] tests to verify performance improvements

*BREAKING CHANGE:* xs-meter-9 represents XS Map/Set optimizations

see also https://github.com/agoric-labs/moddable/tree/ag-testnet-5 ; this time, I merged Moddable's `public` branch into our "vendor branch" rather than rebasing.

commit 437261727 is work that we would have gotten for free if we had integrated Moddable's refactor of `xsnap.c` into platform and application. https://github.com/endojs/endo/issues/681

fixes #3012

### CODE REVIEW

File: packages/xsnap/src/xsnap.c [hunk 1]
```diff
@@ -213,7 +213,7 @@ typedef enum {
 	E_TOO_MUCH_COMPUTATION = 17,
 } ExitCode;
 
-ExitCode main(int argc, char* argv[])
+int main(int argc, char* argv[])
```
Comment (warner) [inline packages/xsnap/src/xsnap.c:216]: Any particular reason this was downgraded to `int`?

Comment (dckc) [reply packages/xsnap/src/xsnap.c:216]: yes; @jessysaurusrex discovered that it generates a warning:

```
../../src/xsnap.c:216:1: warning: return type of 'main' is not 'int' [-Wmain-return-type]
ExitCode main(int argc, char* argv[])
```

ref https://gist.github.com/jessysaurusrex/e28c5ec0230c50c8af3adce8dee26fa5#file-gistfile1-txt-L1
https://github.com/Agoric/agoric-sdk/issues/2469#issuecomment-889429425

I tried to be clear about this in the 490cdba6de81 commit message.

**Comment by kriskowal** [comment]
For release management, the `*BREAKING CHANGE:*` line must appear in one of the commit messages, possibly the merge commit, with the asterisks, for Lerna to pick it up and recommend a version appropriately.

File: packages/xsnap/src/xsnap.c [hunk 2]
```diff
@@ -827,14 +827,10 @@ void fxFreezeBuiltIns(txMachine* the)
...
-	mxFreezeBuiltInCall; mxPush(mxMapEntriesIteratorPrototype); mxFreezeBuiltInRun;
-	mxFreezeBuiltInCall; mxPush(mxMapKeysIteratorPrototype); mxFreezeBuiltInRun;
-	mxFreezeBuiltInCall; mxPush(mxMapValuesIteratorPrototype); mxFreezeBuiltInRun;
+	mxFreezeBuiltInCall; mxPush(mxMapIteratorPrototype); mxFreezeBuiltInRun;
 	mxFreezeBuiltInCall; mxPush(mxModulePrototype); mxFreezeBuiltInRun;
 	mxFreezeBuiltInCall; mxPush(mxRegExpStringIteratorPrototype); mxFreezeBuiltInRun;
-	mxFreezeBuiltInCall; mxPush(mxSetEntriesIteratorPrototype); mxFreezeBuiltInRun;
-	mxFreezeBuiltInCall; mxPush(mxSetKeysIteratorPrototype); mxFreezeBuiltInRun;
-	mxFreezeBuiltInCall; mxPush(mxSetValuesIteratorPrototype); mxFreezeBuiltInRun;
+	mxFreezeBuiltInCall; mxPush(mxSetIteratorPrototype); mxFreezeBuiltInRun;
```
Comment (kriskowal) [inline packages/xsnap/src/xsnap.c:833]: Story checks out:

```
$ node
> new Map().keys().__proto__ === new Map().entries().__proto__
true
```

File: packages/xsnap/test/test-xs-perf.js [hunk 3]
```diff
@@ -138,7 +139,9 @@ test('metering can be switched off / on at run-time', async t => {
   const opts = options(io);
   const vat = xsnap(opts);
   t.teardown(() => vat.terminate());
-  const { meterUsage: { compute: noUnMeteredCompute } } = await vat.evaluate(`
+  const {
+    meterUsage: { compute: noUnMeteredCompute },
```
Comment (kriskowal) [inline packages/xsnap/test/test-xs-perf.js:143]: nit: Maybe `fullyMeteredCompute` to cancel the negatives. I want to love giving `Un` its own camel hump, and also `MoDem`, `TeleType`, and `TransCoder`.

File: packages/xsnap/test/test-xs-perf.js [hunk 4]
```diff
@@ -179,3 +184,62 @@ test('metering switch - start compartment only', async t => {
...
+    t.log({ compute, r });
+    return { compute, r };
+  };
+
+  const { r: r1 } = await run(8);
+  const { r: r2 } = await run(10);
+  const { r: r3 } = await run(12);
+  t.log({ r2_1: r2.rate / r1.rate, r3_2: r3.rate / r2.rate });
+  t.true(r2.rate / r1.rate >= 1);
+  t.true(r3.rate / r2.rate >= 1);
```
Comment (kriskowal) [inline packages/xsnap/test/test-xs-perf.js:244]: What do these assertions verify?

**Review by kriskowal — APPROVED** [review]
Neat, thanks.

File: packages/xsnap/test/test-xs-perf.js (hunk 4 above)
Comment (dckc) [reply packages/xsnap/test/test-xs-perf.js:244]: that the data structure manipulation rate (computed above as `n * logn / delta_t`) stays comparable as the (binary) order of magnitude grows.

It used to be `>= 0.85`. Now that it's `>= 1`, it could just be `r2.rate >= r1.rate`, I suppose.
