### PR TITLE
fix(vow): watcher args instead of context

### LINKED ISSUE #9555: inconsistent `watch` handling of arguments for watcher
## Describe the bug

Currently watch accepts a single optional argument in 3rd position to bind an argument for the watcher. If that argument is not provided, the watcher is still called with an `undefined` argument, which can trip up interface guards that do not expect it.

Furthermore `watchPromise` which is the ancestor of `watch` accepted multiple positional arguments after the watcher, creating a migration footgun.

## Expected behavior
Accept multiple positional arguments and respect arity.

## Platform Environment
master

### PR DESCRIPTION
**Pull request by mhofman**
closes: #9555

## Description

This PR updates the internal watcher exo to handle an args list, and updates the `watch` tool to check the arity and realize if a 3rd argument has been provided or not. It does not currently accept a regular rest argument like `watchPromise` does.

### Security Considerations
None

### Scaling Considerations
None

### Documentation Considerations
Updated type definition

### Testing Considerations

I didn't find any unit test coverage for this but some integration tests have shape on the watcher checking the arity.

### Upgrade Considerations
Need to settle the internal handling of arguments before we commit to them in state.

### CODE REVIEW

**Comment by mhofman** [comment]
@michaelfig this is now ready for review!

File: packages/vow/src/watch-utils.js [hunk 1]
```diff
@@ -111,7 +111,7 @@ export const prepareWatchUtils = (zone, watch, makeVowKit) => {
           }
           resolver.resolve(harden(results));
         },
-        onRejected(value, { id }) {
+        onRejected(value, { id, index: _index }) {
```
Comment (turadg) [inline packages/vow/src/watch-utils.js:114]: stray?

Comment (mhofman) [reply packages/vow/src/watch-utils.js:114]: Nope it's there to satisfy typescript, in particular https://github.com/Agoric/agoric-sdk/blob/6b62e09cfe8fc348e571c86cf17a96c0bfccf133/packages/vow/src/watch-utils.js#L65

Now that this PR correctly [plumbs the args in the rejection handler in the type definitions](https://github.com/Agoric/agoric-sdk/blob/6b62e09cfe8fc348e571c86cf17a96c0bfccf133/packages/vow/src/types.js#L84-L87), the extra property check of TS kicked in with the type of the args which were inferred to the narrower / common part of the fulfillment and rejection handler. Maybe there is a better way to type `watch` to avoid this gotcha?

**Review by michaelfig — APPROVED** [review]
LGTM.

My only minor nitpick is with the type parameter which was named `<C>` because of `watcherContext` becoming less appropriate when `watcherContext` became `watcherArgs`.

Not a blocker, though!  :shipit:
