### PR TITLE
Tame metering direct eval

### LINKED ISSUE #1179: tame-metering plus new-ses breaks endowments
I've run into some kind of conflict between the agoric-sdk `tame-metering` package, and new SES (0.8.0). The symptom is that endowments aren't visible to the evaluated code.

Using the `@agoric/tame-metering` in the current trunk, I set up two files. The first injects metering code into all the global objects (so confined code cannot use built-ins to provoke very large memory usage or runtime). To avoid upsetting SES, it must also add a property to one of the objects it replaced.

```js
// install-global-metering.js
import { tameMetering } from '@agoric/tame-metering';
tameMetering();

Object.defineProperties(RegExp, {
  [Symbol.species]: {
    get() { return RegExp; },
  },
});
```

The second imports the first (first, before importing anything else, which is important, because the first file modifies built-in objects like `Object`, and we need the other imports to use those modified objects):

```js
import './install-global-metering.js';
import 'ses';
lockdown();
const c = new Compartment({ foo: 0 });
const namespace = c.evaluate('foo');
```

(I'll attach a draft PR with this test, for ease of reproduction).

The symptom is that the `c.evaluate('foo')` fails with `ReferenceError: foo is not defined`.

I've instrumented `Compartment`, specifically `performEval`, and I can see that `scopeHandler.get(whatever, 'foo')` succeeds. If I harden `c.globalThis` then I also see `foo` in the `getScopeConstants` array (among lots of other object names). But when it finally calls `apply(evaluate, globalObject, [source])`, it fails with the ReferenceError.

If I comment out the `tameMetering()` call, it all works.

The use case that provoked this was using the metering transform, which injects code that includes calls to `getMeter()`. I'm supposed to be able to use the transform in conjunction with a `getMeter` endowment, but the transformed code could not be evaluated, with the same kind of ReferenceError.

I'm guessing that something `tameMetering` does to some globals is causing problems in our magic lines. Maybe the built-in `eval` is modified, and stops working for our "magic lines of code"?

Cc @michaelfig who wrote tame-metering, and @kriskowal who knows SES the best, and @erights because I'm desperate :).

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #1180, closes #1179

Ensure that we preserve the `eval` identity so that direct eval continues to work, even in the face of `-r esm`.

### CODE REVIEW

File: packages/tame-metering/src/tame.js [hunk 1]
```diff
@@ -142,6 +146,9 @@ export function tameMetering() {
       ({ [name]: wrapper } = {
         [name](...args) {
           // Fast path:
+          if (name === 'eval') {
+            console.log('eval escaped', target);
+          }
```
Comment (kriskowal) [inline packages/tame-metering/src/tame.js]: Is this debug cruft?

File: packages/tame-metering/src/tame.js [hunk 2]
```diff
@@ -76,7 +79,8 @@ export function tameMetering() {
     if (
       typeof target !== 'function' ||
       target === FunctionPrototype ||
-      target === SES1ErrorConstructor
+      target === SES1ErrorConstructor ||
+      target === globalEval
```
Comment (kriskowal) [inline packages/tame-metering/src/tame.js:98]: Maybe clarify in the comment above why this “hack” does not breach containment (I’m not sure whether this is the case). Would be good to clarify too that SES-1.0 is actually SES before 0.8.0, and if/why it’s not necessary later. Sounds like it’s still necessary after 0.8.0.

File: packages/tame-metering/test/test-sanity.js [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+import test from 'tape-promise/tape';
+
+test('symbol properties', t => {
+  t.assert(RegExp[Symbol.species], 'RegExp[Symbol.species] is kept');
+  t.end();
+});
+
+function foo(_bar) {
+  // eslint-disable-next-line no-eval
+  return eval('_bar');
```
Comment (kriskowal) [inline packages/tame-metering/test/test-sanity.js:11]: Very illustrative test case. Since this is just one sane expectation, should the test file should be named `direct-eval.test.js`?

Comment (michaelfig) [reply packages/tame-metering/test/test-sanity.js:11]: The symbol properties test is also in this file.

File: packages/tame-metering/src/tame.js (hunk 1 above)
Comment (michaelfig) [reply packages/tame-metering/src/tame.js]: Ahh, yes.  Removing it.

File: packages/tame-metering/src/tame.js (hunk 2 above)
Comment (michaelfig) [reply packages/tame-metering/src/tame.js:98]: Not necessary after 0.8.0.  I've clarified.

File: packages/tame-metering/src/tame.js [hunk 4]
```diff
@@ -71,12 +74,19 @@ export function tameMetering() {
...
 
-    // Without this hack, SES-1.0 fails with:
+    // Without this ErrorConstructor hack, SES pre-0.8 fails with:
     // TypeError: prototype function Error() { [native code] } of unknown.global.EvalError is not already in the fringeSet
+    // This is due to an ordering constraint between when SES-pre-0.8 captures the intrinsics versus when it runs the shims.
+    //
+    // SES 0.8 and later do not have this constraint, since the vetted shims are installed before SES is even imported.
+    //
+    // Not wrapping the Error constructor doesn't cause much of an exposure, although it can be used to allocate large
+    // strings without counting towards the allocation meter.  That's not a problem we're trying to solve yet.
```
Comment (kriskowal) [inline packages/tame-metering/src/tame.js]: And if the target is `globalEval`, I presume this doesn’t violate containment because that eval is in turn a wrapper that will rewrite the given program to incorporate the meter. Is that correct?

**Review by kriskowal — APPROVED** [review]

File: packages/tame-metering/src/tame.js (hunk 4 above)
Comment (michaelfig) [reply packages/tame-metering/src/tame.js]: Yes, it is only used internally by SES, and otherwise is replaced with the wrapper.

**Comment by erights** [comment]
@michaelfig I am confused about this from the title, but haven't yet read the rest.

It is impossible to support direct eval in the SES-shim, or any shim based on the eight magic lines. What is the purpose of this PR? What effect does it actually have when run under the SES-shim?

**Comment by michaelfig** [comment]
> It is impossible to support direct eval in the SES-shim, or any shim based on the eight magic lines. What is the purpose of this PR? What effect does it actually have when run under the SES-shim?

This meter taming runs before SES-shim is loaded, adding metering support to all the globals.  It is not "run under the SES-shim", it is a "vetted shim".

Before this PR, this process would not preserve the `eval` identity, so when SES-shim would run the eight magic lines, it would always get an indirect `eval` and thereby fail to support proper confinement or endowments.

**Comment by warner** [comment]
@erights take a look at #1179 , which was the problem I ran into that prompted this fix. The symptom was that the SES `c.evaluate` was not seeing its endowments in an environment where the `tame-metering` vetted shim was installed before `lockdown()` (and of course it cannot be installed *after* `lockdown()`).

I don't understand it completely, but my take is that the eight magic lines depend upon being able to do a *direct* eval. And `tame-metering`, which replaces all the builtins with versions that perform metering, replaced `eval` too, making it no longer direct. When the SES evaluator tried to run the magic lines with an *indirect* eval, it wasn't using the scope proxy any more.

Hm, in fact, if it wasn't using that proxy, could it have been pulling names off the real global, thus bypassing some of the SES protections? The constants array probably satisfied most (all?) of those, so maybe it wasn't producing a real break. But maybe it'd be a good idea to add a check to SES that the `eval` it has is actually a direct eval, and bail if not, to detect security-threatening changes in the vetted environment.

**Comment by erights** [comment]
That all makes perfect sense. Now that you point it out, it couldn't be any other way. Thanks!
