### PR TITLE
fix(fast-usdc): .exit() all internal temporary seats

### LINKED ISSUE #10890: Fast USDC load test
## What is the Problem Being Solved?

Our tests to date tear down the world after a handful of operations. We don't know the impact on the chain under sustained load.

## Description of the Design

Goal: a load test to verify that some metrics don't grow over time: pending kernel promises, number of kernel objects, clist.

cc @mhofman 

## Scaling Considerations

kinda the whole point

## Test Plan

TBD

### PR DESCRIPTION
**Pull request by dckc**
closes #10890

refs:
  - #10931

## Description

mainly:

 - fix: .exit() all internal temporary seats

Also, to exercise pruning vstorage:

 - feat: core eval script to deleteCompletedTxs
    - expose deleteCompletedTx via creatorFacet

To speed up testing and match it with expected deployment:

 - chore: don't write-chain-info when testing Fast USDC

Plus a misc type refinement:
 
 - chore: refine return type of Offers.deposit

### Security / Scaling Considerations

Reducing leaks improves scalability which improves availability.

### Documentation Considerations

I don't think so.

### Testing Considerations

Tests are in #10931 ; they're somewhat rough and not included in this PR.

### Upgrade Considerations

Some undiagnosed heap growth remains. A fix for that might go out in a future upgrade.

### CODE REVIEW

File: packages/fast-usdc/src/delete-completed-txs.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+  trace('pruneFastUsdcStorage');
+  const { fastUsdcKit } = powers.consume;
+  const { creatorFacet } = await fastUsdcKit;
+  trace(creatorFacet);
+  await E(creatorFacet).deleteCompletedTxs();
+  trace('done');
+};
+
+trace('script finishing');
+pruneFastUsdcStorage;
```
Comment (turadg) [inline packages/fast-usdc/src/delete-completed-txs.js]: We don't have an extension for scripts that run in CoreEval. `.core.js` is for scripts that are _built_ by a `.build.js` into a script that runs.

So I think this filename is fine for now, but it shouldn't be part of `src` because it's not a package export. How about in `scripts`?

File: packages/fast-usdc/src/exos/advancer.js [hunk 2]
```diff
@@ -223,7 +223,8 @@ export const prepareAdvancerKit = (
         onFulfilled(result, ctx) {
           const { poolAccount, intermediateRecipient, settlementAddress } =
             this.state;
-          const { destination, advanceAmount, tmpSeat: _, ...detail } = ctx;
+          const { destination, advanceAmount, tmpSeat, ...detail } = ctx;
+          tmpSeat.exit();
```
Comment (0xpatrickdev) [inline packages/fast-usdc/src/exos/advancer.js:227]: 👍

**Review by turadg — APPROVED** [review]
Nice

**Comment by dckc** [comment]
Even after 3 tries, I'm blocked by a ci flake

 - https://github.com/Agoric/agoric-sdk/issues/9934#issuecomment-2641518556
