### PR TITLE
Update go version and fix govulncheck warnings

### LINKED ISSUE #6638: Agoric Clients - golang: `govulncheck` for all agoric release repos and agoric dependency repos
Before the release is ready to be cut, *all* known security issues raised by `govulncheck` must be resolved unless otherwise exempted.  This does not include devDependencies issues unless there is a likely path to exploitation, determined by the Security team.

By default, this includes Critical, High, Medium issues.  Select low issues may be raised by the Security team

### PR DESCRIPTION
**Pull request by JimLarson**
closes: #6638

## Description

Updating to Go 1.20.

### Security Considerations

Fixes govulncheck warnings.

### Scaling Considerations

N/A

### Documentation Considerations

Need to update our public build instructions.

### Testing Considerations

N/A

### CODE REVIEW

File: bin/agd [hunk 1]
```diff
@@ -167,6 +172,11 @@ fi
         }
         ;;
       esac
+      # Ensure minimum patch versions of Go environment
+      goversion=$(go version 2>/dev/null)
+      goregexp='go version go([0-9]+).([0-9]+).([0-9]+) '
+      [[ "$goversion" =~ $goregexp ]] || fatal "illegible go version"
```
Comment (michaelfig) [inline bin/agd]:
```suggestion
      [[ "$goversion" =~ $goregexp ]] || fatal "illegible go version \`$goversion'"
```

File: repoconfig.sh [hunk 2]
```diff
@@ -1,6 +1,15 @@
...
 GOLANG_DIR=golang/cosmos
 GOLANG_DAEMON=$GOLANG_DIR/build/agd
+
+# Args are major, minor and patch version numbers
+function golang_version_check() {
+  # Want 1.20.2+, 1.21+, or 2+
+  [ $1 -eq 1 ] && {
+    [ $2 -lt 20 ] && echo "need go version 1.20 or higher" 1>&2 && return 1
+    [ $2 -eq 20 ] && [ $3 -lt 2 ] && echo "need go version 1.20.2 or higher" 1>&2 && return 1
+  } || true
```
Comment (michaelfig) [inline repoconfig.sh]: We can make the shell more like a Go switch:

```suggestion
  if [ $1 -ne 1 ]; then :
  elif [ $2 -lt 20 ]; then :
  elif [ $2 -eq 20 ] && [ $3 -lt 2 ]; then : 
  else
    return 0
  fi
  echo "need go version 1.20.2 or higher" 1>&2
  return 1
```

File: bin/agd [hunk 3]
```diff
@@ -14,6 +14,11 @@
 # the SDK.
 set -ueo pipefail
 
+function fatal() {
+  echo $1 1>&2
```
Comment (michaelfig) [inline bin/agd]: Quoting.
```suggestion
  echo "$1" 1>&2
```

**Review by michaelfig — APPROVED** [review]
A few little changes to consider.

File: bin/agd (hunk 3 above)
Comment (JimLarson) [reply bin/agd]: The `echo` command is happy to echo multiple arguments, though if you omit the double quotes it might normalize whitespace and interpret a leading `"-n "`, though I'd argue that the latter is a feature. Nevertheless I'll make the change because of my philosophy which departs from Emerson: "A foolish consistency is the hobgoblin of good programming."

File: repoconfig.sh (hunk 2 above)
Comment (JimLarson) [reply repoconfig.sh]: Imagine we were still allowing 1.19.7+, or adding a constraint of 1.21.1+ - the logic here would get pretty janky.

I've flattened it to make it as simple and clear as I can think of without getting too repetitious.

File: bin/agd (hunk 3 above)
Comment (michaelfig) [reply bin/agd]: BTW, if you want the `fatal()` function to be variadic and treat arguments exactly as `echo` does, may I suggest:

```sh
  echo ${1+"$@"} 1>&2
```

Comment (JimLarson) [reply bin/agd]: Done.

**Comment by JimLarson** [comment]
@mergifyio refresh
