### PR TITLE
Expose metrics via slogger

### LINKED ISSUE #2617: add performance/metering callbacks to swingset API
## What is the Problem Being Solved?

We're looking for a clean way to let a host application learn time-based performance data from internal SwingSet events.

In particular, when swingset starts up, it will spend some amount of time replaying vat transcripts to get all vats ready for messages. In our current code, where everything runs under Node.js, startup involves reloading each vat, one at a time, replaying the full transcript for each before moving on to the next, and all non-terminated vats are loaded before `makeSwingsetController`'s return Promise is fired. The total replay time this takes is interesting to measure (and report on a dashboard), as it represents the (probable) majority of the time that restart consumes, and total restart time is downtime for a validator.

As our system gets more sophisticated, we'll reduce this downtime. First, we'll move vats to XS, and we'll get snapshots working, so reloading a single vat will really mean loading a snapshot and then replaying a truncated transcript instead of the full one, which should go a lot faster. Then, we'll avoid reloading *all* vats at startup, instead we'll only reload some of them (the most popular, the largest, some heuristic), and leave the others to be loaded on-demand as messages arrive. In this state, each individual crank may spend some amount of time waiting for the target vat to be loaded. This will appear as latency: block processing time that was lost because the kernel did not have the resources in place by the time they were needed. We want to measure this and look for ways to reduce it. This time is like the `iowait` time in a Unix-like kernel: time that userspace spends blocking, waiting for the kernel.

One way we'll reduce it is to preemptively load more vats. With an XS worker process, we can do this in the background. Swingset startup will load the most critical vats, then announce itself open for business (`makeSwingsetController`'s return promise fires), then continue loading some additional number of vats in the background. If we have the RAM, we could load all of them. If we don't, we'll load some middle tier and leave the outliers for demand loading. With luck, by the time messages arrive, the target vat will be loaded, but misses will still result in some downtime, which we'll want to measure.

As a block is processed, we'll spend some amount of time running cranks, some time doing non-swingset cosmos-sdk operations (like balance transfers), then some time performing consensus operations, and finally some amount of idle time while we're waiting for the block proposer to announce the next block. We'd like to know the ratio of these periods. If we spend a lot of time idle, but the swingset run-queue is not empty, that suggests we should spend more time processing cranks, and we should adjust our scheduler/metering limits to achieve that. If we spend no time idle, and the inter-block time grows above our target rate (e.g. once per 6 seconds), that implies we might be spending *too much* time doing cranks, and should reduce a limit somewhere.

We want a clean way to get this data out of swingset, without having swingset itself know about wallclock time (to preserve the hygiene of swingset being generally deterministic and lacking IO).

## Description of the Design

We're thinking that `makeSwingsetController()`'s `runtimeOptions` parameter should get a set of callbacks. Swingset will then invoke these callbacks as it runs, allowing the host application to use its private clock access to measure the durations of interest. We can also add callbacks into the `controller.step()/run()` arguments, for data that is scoped to a single crank.

One pair of callbacks would be `beginVatLoad(vatID)` and `finishVatLoad(vatID)` (perhaps reporting a number of transcript entries processed as an extra argument to `finishVatLoad`). This would give the host the ability to measure the "iowait" time, either during startup (in `makeSwingsetController`), or during a crank.

We could have a coarser-granularity pair of callbacks to be invoked during startup, to indicate when the first vat is beginning to be reloaded, and when the last vat is finished. This will become less useful when we start loading vats in parallel, or on-demand, but might be more convenient in the current phase.

## Delivering Metering Data via Callback, not Return Value

@michaelfig suggested that we should also use this to report metering data. Currently we've been planning to have `controller.step()` return a "meter consumed" number in the resolution of its return promise, so that the host can do a limited amount of work (per block) like:

```
let used = 0;
while (used < limit) {
  used += await controller.step();
}
```

Instead, we might provide a callback to which the usage data would be reported:

```
let used = 0;
function use(amount) {
  used += amount;
}
while (used < limit) {
  await controller.step({ callbacks: { meteringUsed: use } });
}
```

If we use this approach, the rules would be:

* the callbacks are observe-only
  * swingset would protect itself against exceptions thrown by the callback
  * the kernel input queue (#720) would protect against the callback attempting to call back into swingset
  * we'd normally prefer to use a Promise here, to avoid all the reentrancy hazards that inspired Promises in the first place, but for the callbacks who want to measure the elapsed time of something, running them at the end of a promise queue might impact the accuracy of their results
* the `meteringUsed` callback might be called once, many times, or none at all

One argument in favor of this approach is that the kernel has roughly five code paths that can result from a `controller.step` (depending upon whether the top-most run-queue item is a delivery or a notification, and whether the delivery is to an object or a promise in one of the various fulfillment states). It seems slightly easier to pass a callback into each of these paths than to ensure that all of the paths have the same return signature. Another argument is that we might add a new kind of metering unit, and a host which does not know how to deal won't be exposed to it unless they registered a new kind of callback.

(I'm not entirely convinced by these arguments, but I'd like to explore them further).

We'll be changing the way we measure CPU usage over time. It will certainly be helpful to report new kinds of metering measurements (to dashboards and the like) well before we change the code to act upon their values. For example, in an early phase, we might continue to execute at most 1000 cranks per block, but could report bytecode instructions executed as well. We can analyze the additional metrics offline to try and model the relationship between bytecode-instructions and wallclock time, to come up with the initial bytecode-instructions-per-block limit that we should switch to.

## Security Considerations

I'm slightly concerned about the opportunity for reentrancy hazards or general authority escalation inherent in giving functions into swingset, rather than having swingset return data back out. If we don't actually need the host to measure wallclock time of events, it may be better to report those events through a less scheduling-hazard-prone pathway.

## Test Plan

not sure, probably unit tests to make sure the callbacks get executed when we expect, but their values are by nature nondeterministic for many of them

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #2617

This PR takes the low road to exposing more SwingSet details via Prometheus metrics.  We add a `sloggerCallbacks` kernel option that contains methods that should be wrapped around the corresponding method on the SwingSet slogger.  This makes it possible to intercept interesting slog actions and have them trigger the metrics.

Additionally, we have the local and xsnap vat managers return a meter usage object at the end of the deliveryResults array.  This result is available to slog, and thus can be smuggled back to the host from the `sloggerCallbacks.deliver.finish` function, where with cosmic-swingset it is available to Prometheus.

I find this integration to be pleasing, as it doesn't introduce another code path for metrics, but continues to leverage the existing SwingSet kernelStats and slogger mechanisms.  I tried to make minimal changes.  When we have more work on the vatManagers and complete metering under XS we will probably find abstractions to clean up any untidy code.

<details><summary>Example of new metrics exposed on http://localhost:9461/metrics (please excuse the extra `le="+Inf"` data points.  I hope to expand them (probably too much load on Prometheus) or remove them (takes some https://opentelemetry.io work) sometime.</summary>

```
# HELP swingset_vat_startup Vat startup time (ms)
# TYPE swingset_vat_startup histogram
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v1"} 1 1616222257396
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v1"} 16 1616222257396
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v1",le="+Inf"} 1 1616222257396
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v11"} 1 1616222257413
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v11"} 14 1616222257413
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v11",le="+Inf"} 1 1616222257413
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v13"} 1 1616222257421
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v13"} 7 1616222257421
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v13",le="+Inf"} 1 1616222257421
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v2"} 1 1616222257443
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v2"} 20 1616222257443
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v2",le="+Inf"} 1 1616222257443
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v3"} 1 1616222257457
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v3"} 12 1616222257457
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v3",le="+Inf"} 1 1616222257457
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v4"} 1 1616222257475
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v4"} 17 1616222257475
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v4",le="+Inf"} 1 1616222257475
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v5"} 1 1616222257487
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v5"} 10 1616222257487
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v5",le="+Inf"} 1 1616222257487
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v6"} 1 1616222257508
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v6"} 19 1616222257508
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v6",le="+Inf"} 1 1616222257508
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v7"} 1 1616222257514
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v7"} 5 1616222257514
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v7",le="+Inf"} 1 1616222257514
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v8"} 1 1616222257521
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v8"} 6 1616222257521
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v8",le="+Inf"} 1 1616222257521
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v9"} 1 1616222257527
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v9"} 5 1616222257527
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v9",le="+Inf"} 1 1616222257527
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v15"} 1 1616222257538
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v15"} 10 1616222257538
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v15",le="+Inf"} 1 1616222257538
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v12"} 1 1616222257545
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v12"} 6 1616222257545
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v12",le="+Inf"} 1 1616222257545
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v14"} 1 1616222257553
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v14"} 6 1616222257553
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v14",le="+Inf"} 1 1616222257553
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v10"} 1 1616222257584
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v10"} 26 1616222257584
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v10",le="+Inf"} 1 1616222257584
swingset_vat_startup_count{app="ag-chain-cosmos",vatID="v16"} 1 1616222296474
swingset_vat_startup_sum{app="ag-chain-cosmos",vatID="v16"} 10665 1616222296474
swingset_vat_startup_bucket{app="ag-chain-cosmos",vatID="v16",le="+Inf"} 1 1616222296474
# HELP swingset_vat_delivery Vat delivery time (ms)
# TYPE swingset_vat_delivery histogram
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v11"} 72 1616222265842
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v11"} 119 1616222265842
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v11",le="+Inf"} 72 1616222265842
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v14"} 156 1616222300291
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v14"} 593 1616222300291
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v14",le="+Inf"} 156 1616222300291
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v12"} 4 1616222296513
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v12"} 10687 1616222296513
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v12",le="+Inf"} 4 1616222296513
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v9"} 1 1616222257638
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v9"} 1 1616222257638
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v9",le="+Inf"} 1 1616222257638
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v8"} 1 1616222257640
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v8"} 1 1616222257640
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v8",le="+Inf"} 1 1616222257640
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v1"} 30 1616222285605
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v1"} 32 1616222285605
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v1",le="+Inf"} 30 1616222285605
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v15"} 19 1616222258055
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v15"} 40 1616222258055
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v15",le="+Inf"} 19 1616222258055
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v10"} 27 1616222300266
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v10"} 57 1616222300266
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v10",le="+Inf"} 27 1616222300266
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v2"} 1 1616222257651
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v2"} 3 1616222257651
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v2",le="+Inf"} 1 1616222257651
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v6"} 118 1616222284954
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v6"} 199 1616222284954
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v6",le="+Inf"} 118 1616222284954
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v4"} 134 1616222296570
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v4"} 213 1616222296570
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v4",le="+Inf"} 134 1616222296570
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v7"} 1 1616222258137
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v7"} 1 1616222258137
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v7",le="+Inf"} 1 1616222258137
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v5"} 18 1616222258420
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v5"} 42 1616222258420
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v5",le="+Inf"} 18 1616222258420
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v3"} 14 1616222258418
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v3"} 21 1616222258418
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v3",le="+Inf"} 14 1616222258418
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v13"} 218 1616222300288
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v13"} 289 1616222300288
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v13",le="+Inf"} 218 1616222300288
swingset_vat_delivery_count{app="ag-chain-cosmos",vatID="v16"} 8 1616222300270
swingset_vat_delivery_sum{app="ag-chain-cosmos",vatID="v16"} 3694 1616222300270
swingset_vat_delivery_bucket{app="ag-chain-cosmos",vatID="v16",le="+Inf"} 8 1616222300270
...
# HELP swingset_meter_usage Vat meter usage
# TYPE swingset_meter_usage histogram
swingset_meter_usage_count{app="ag-chain-cosmos",vatID="v16",meterType="tame-metering-1",stat="allocate"} 8 1616222300270
swingset_meter_usage_sum{app="ag-chain-cosmos",vatID="v16",meterType="tame-metering-1",stat="allocate"} 19318758 1616222300270
swingset_meter_usage_bucket{app="ag-chain-cosmos",vatID="v16",meterType="tame-metering-1",stat="allocate",le="+Inf"} 8 1616222300270
swingset_meter_usage_count{app="ag-chain-cosmos",vatID="v16",meterType="tame-metering-1",stat="compute"} 8 1616222300285
swingset_meter_usage_sum{app="ag-chain-cosmos",vatID="v16",meterType="tame-metering-1",stat="compute"} 16681529 1616222300285
swingset_meter_usage_bucket{app="ag-chain-cosmos",vatID="v16",meterType="tame-metering-1",stat="compute",le="+Inf"} 8 1616222300285
```
</details>

I can't wait to slice and dice this data from testing!

### CODE REVIEW

File: packages/SwingSet/src/kernel/vatManager/deliver.js [hunk 1]
```diff
@@ -51,16 +52,16 @@ export function makeDeliver(tools, dispatch) {
     await runAndWait(() => dispatch[dispatchOp](...dispatchArgs), errmsg);
     stopGlobalMeter();
 
-    let status = ['ok'];
+    let status = ['ok', null, null];
     // refill this vat's meter, if any, accumulating its usage for stats
     if (meterRecord) {
       // note that refill() won't actually refill an exhausted meter
-      const used = meterRecord.refill();
+      status[2] = { ...meterRecord.refill(), meterType: METER_TYPE };
```
Comment (warner) [inline packages/SwingSet/src/kernel/vatManager/deliver.js]: let's keep that `const used=`, it's an extra line that's technically redundant, but it serves to document the fact that we expect `meterRecord.refill()` to return the previous usage, which is not otherwise obvious:

```js
const used = meterRecord.refill();
status[2] = { ...used, meterType: METER_TYPE };
```

(also I'd be tempted to skip the magic-constant name `METER_TYPE`, I guess I usually read those as suggesting that you could just change the constant in one place and everything would be ok, but in fact the two things that must change at the same time are the `meterRecord.refill()` call and the `'tame-metering-1'` value, and having those two things on different lines makes it more likely we'll mess up and change one without the other)

File: packages/cosmic-swingset/lib/kernel-stats.js [hunk 2]
```diff
@@ -1,11 +1,147 @@
...
+import makeStore from '@agoric/store';
+
 import {
   KERNEL_STATS_SUM_METRICS,
   KERNEL_STATS_UPDOWN_METRICS,
 } from '@agoric/swingset-vat/src/kernel/metrics';
 
+export const DEFAULT_METER_PROVIDER = new MeterProvider();
+
+export const HISTOGRAM_SECONDS_LATENCY_BOUNDARIES = [
```
Comment (warner) [inline packages/cosmic-swingset/lib/kernel-stats.js:13]: For the record (no pun intended! ok maybe a little intended) I'll mention that I still find it really weird that we have to pre-bin the values we record and send to Prometheus. I really wish we had a service that just let us send raw how-long-did-X-take numbers and let the backend figure out the statistics. I expect the graphs we get out of this to be difficult to read without a lot of mental prep work.

**Review by warner — APPROVED** [review]
Minor change suggested, but overall looks good. I'm slightly weirded out by the responsibility being delegated to the metric callbacks, but I appreciate the care you put into protecting against failure in them. It looks like the only bad things they might do are to go into an infinite loop (which we can't do anything about), or re-enter into the kernel somehow (and we can't use eventual-sends to prevent that without sacrificing the synchronous timeliness that the measurement functions want to measure), so that sounds good.

File: packages/SwingSet/src/kernel/vatManager/deliver.js (hunk 1 above)
Comment (michaelfig) [reply packages/SwingSet/src/kernel/vatManager/deliver.js]: I've now inlined the `meterType: 'whatever'` code where the meterUsage structure is actually constructed, along with a `TODO` there to update it if the structure changes.

File: packages/cosmic-swingset/lib/kernel-stats.js (hunk 2 above)
Comment (michaelfig) [reply packages/cosmic-swingset/lib/kernel-stats.js:13]: Yeah.  This is one of the reasons I chose to use OpenTelemetry and not Prometheus directly.  We will be able to gain this feature when OTEL figures out how to implement it (and it is already on their TODO list), and possibly switch to a different metrics backend.

**Comment by michaelfig** [comment]
You're right, infinite loops in the host can't be defended against unless we somehow meter the kernel itself (and the code it calls).

> re-enter into the kernel somehow

We'll protect against this with #720.
