### PR TITLE
fix(vaults): when reconstituting vaults, report correct shortfall

### LINKED ISSUE #7474: Vault reconstitution: vault manager appears to incorrectly assign remaining IST to shortfall in addition to reconstituted vaults
## What is the Problem Being Solved?
Ran through a reconstitute auction scenario where two vaults should have been reconstituted (issues there filed separately)

From the spreadsheet we were using to track results, we saw the following:
Auction completed with 234.54 IST remaining to fill
Vault manager reconstituted two vaults, one with 100.5 debt and another with 103.515 debt
Shortfall amount should have been 30.525 (234.54 minus the 204.015 debt given to vaults)

However, we saw the reserve shortfall increase by 234.54, suggesting it double counted that debt.  

The liquidation penalty also appears unaccounted for.  The expected amount of excess collateral (i.e., not reconstituted into a vault) was transferred to the reserve, but the total collateral (reconstituted in vault + transferred + sold) sums to less than what the auction started with.  The delta is what was expected for the penalty.

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
fixes: #7474

## Description

We weren't reducing the reported shortfall by the amount of debt being restored to some vaults.

### Security Considerations

None.

### Scaling Considerations

Not an issue.

### Documentation Considerations

N/A

### Testing Considerations

Corrected a test.

### CODE REVIEW

File: packages/inter-protocol/src/vaultFactory/vaultManager.js [hunk 1]
```diff
@@ -869,13 +875,13 @@ export const prepareVaultManagerKit = (
               transfers.length,
             );
 
-            facets.helper.markRestoreDebt(
-              AmountMath.subtract(totalDebt, debtRemaining),
-            );
             facets.helper.sendToReserve(collatRemaining, liqSeat);
             facets.helper.markDoneLiquidating(totalDebt, totalCollateral);
+            facets.helper.recordShortfallAndProceeds({
+              overage: accounting.overage,
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/vaultManager.js]: without knowing the types, reviewing in web UI it looks like this could be missing some properties.
```suggestion
              ...accounting,
```

**Review by turadg — APPROVED** [review]
Fix LGTM. There's a lint error I made a commit for. Also I was thinking about how to have prevented this and noticed that `recordShortfallAndProceeds` is supposed to be called whenever it's done liquidating, so I moved the work into `markDoneLiquidating`. 

I pushed for expediency. It has a fixup commit so still requires a rebase to merge.
