### PR TITLE
fix: Preserve smart wallets through bulldozer upgrade

### LINKED ISSUE #7537: smart wallets for those who paid 10 BLD should be preserved
## Describe the bug

Much like #6645, this precious state from the previous VM should be preserved.

## To Reproduce
_IOU_

## Expected behavior
if I paid 10BLD for a wallet in pismo, I should be able to use it in vaults

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context
https://github.com/Agoric/agoric-sdk/issues/6644#issuecomment-1404138609

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #7537

## Description

Propagate chain storage data in which keys represent addresses into provisionPool, which exports a reviver facet for the wallet factory (that itself *uses* the wallet factory when called).

This is somewhat convoluted, but avoids making more Far objects in the bootstrap vat.

### Security Considerations

I believe all new interfaces (and in particular the one for indicating an address as revivable) are closely held in the bootstrap vat.

### Scaling Considerations

Revivable address are stored in a virtual collection, and I don't foresee any other scaling risks.

### Documentation Considerations

This is a specific interpretation of exported chain storage data (every path is assumed to be a wallet address), but I don't know how to document it.

### Testing Considerations

This is unit tested, but should also be extended to cover upgrade as realistically as possible. Is there a good starting point?

### CODE REVIEW

File: packages/vats/src/core/startWalletFactory.js [hunk 1]
```diff
@@ -238,18 +217,45 @@ export const startWalletFactory = async (
...
-    namesByAddressAdmin,
-    walletFactory: wfFacets.creatorFacet,
-  });
+  await Promise.all([
+    E(ppFacets.creatorFacet).addRevivableAddresses(oldAddresses),
+    E(ppFacets.creatorFacet).setReferences({
+      bankManager,
+      namesByAddressAdmin,
+      walletFactory: wfFacets.creatorFacet,
+    }),
```
Comment (gibson042) [inline packages/vats/src/core/startWalletFactory.js]: Are these uses of `ppFacets` (along with `walletReviver: ppFacets.walletReviver` above) correct? The tests had to use `E(facets.creatorFacet).getLimitedCreatorFacet()`, but after starting in a different way (`const facets = await E(zoe).startInstance(…)` rather than `const ppFacets = await startGovernedInstance(…)` as is the case here).

File: golang/cosmos/x/vstorage/vstorage.go [hunk 2]
```diff
@@ -197,7 +197,11 @@ func (sh vstorageHandler) Receive(cctx *vm.ControllerContext, str string) (ret s
 		entries := make([][]interface{}, len(children.Children))
 		for i, child := range children.Children {
 			entry := keeper.GetEntry(cctx.Context, fmt.Sprintf("%s.%s", path, child))
-			entries[i] = []interface{}{child, entry.Value()}
+			if !entry.HasData() {
```
Comment (dckc) [inline golang/cosmos/x/vstorage/vstorage.go:200]: Why start with the negative case? (maybe it's idiomatic go? I don't have a lot of go experience)

File: golang/cosmos/x/vstorage/vstorage_test.go [hunk 3]
```diff
@@ -274,13 +274,13 @@ func TestEntries(t *testing.T) {
 		want string
 	}
 	cases := []testCase{
-		{path: "key1", want: `[["child1",null]]`},
+		{path: "key1", want: `[["child1"]]`},
```
Comment (dckc) [inline golang/cosmos/x/vstorage/vstorage_test.go:277]: Why this change? does `null` act too much like an empty string at some FFI boundary?

File: packages/vats/src/core/startWalletFactory.js [hunk 4]
```diff
@@ -238,18 +217,45 @@ export const startWalletFactory = async (
...
+  );
+  /** @type {WalletFactoryStartResult} */
+  const wfFacets = await E(zoe).startInstance(
+    walletFactory,
+    { Fee: feeIssuer },
+    terms,
+    {
+      storageNode: walletStorageNode,
+      walletBridgeManager,
+      walletReviver: ppFacets.walletReviver,
```
Comment (dckc) [inline packages/vats/src/core/startWalletFactory.js]: I think `ppFacets` doesn't have `walletReviver` at this point.

The facets returned from `E(zoe).startInstance()` are just `publicFacet` and `creatorFacet`. `startGovernedInstance` adds a few more, but I don't see how it could access exo facets such as `walletReviver`.

I think we need a `E(creatorFacet).getWalletReviver()` to make up the gap.

I wonder whether a bootstrap test for this is cost-effective.

**Review by dckc — CHANGES_REQUESTED** [review]
mostly looks good, but I don't think the result of `startGovernedInstance` will have a `.walletReviver`

File: packages/vats/src/provisionPoolKit.js [hunk 5]
```diff
@@ -95,13 +100,23 @@ export const prepareProvisionPoolKit = (
...
+        addRevivableAddresses: M.call(M.arrayOf(M.string())).returns(),
+        getWalletReviver: M.call().returns(
+          M.remotable('ProvisionPoolKit wallet reviver'),
+        ),
+        setReferences: M.call({
           bankManager: M.any(),
           namesByAddressAdmin: M.any(),
           walletFactory: M.any(),
-        }).returns(M.remotable('BridgeHandler')),
+        }).returns(),
```
Comment (dckc) [inline packages/vats/src/provisionPoolKit.js]: ci shows:
```
2023-05-04T01:49:50.431Z SwingSet: ls: v31: Error#1: value for bankManager is not durable: slot 0 of { body: '#"&0"', slots: [ 'p-72' ] }
...
at setReferences (.../vats/src/provisionPoolKit.js:181)
```

I think the '&' sigil on `&0` means there's a promise there. Perhaps the exo method guard for `setReferences` should use `M.callWhen()` and `M.await()`.

File: packages/vats/src/core/startWalletFactory.js [hunk 6]
```diff
@@ -128,6 +128,7 @@ const startGovernedInstance = async (
  */
 export const startWalletFactory = async (
   {
+    vatParameters: { chainStorageEntries = [] },
```
Comment (dckc) [inline packages/vats/src/core/startWalletFactory.js:47]: Please add `exportStorageSubtrees` to swingset config files such as `decentral-devnet-config.json` to cause this to get populated.

I neglected to do that for PSM too. Would you please cherry-pick this one?

1fd3bc9fce435b3e5f0c09a1de5541778eec49a7

File: golang/cosmos/x/vstorage/vstorage.go (hunk 2 above)
Comment (gibson042) [reply golang/cosmos/x/vstorage/vstorage.go:200]: No reason for this method in particular, but it's consistent with the rest of the file because `!entry.HasData()` is often the condition for early exit.

File: golang/cosmos/x/vstorage/vstorage_test.go (hunk 3 above)
Comment (gibson042) [reply golang/cosmos/x/vstorage/vstorage_test.go:277]: It was requested in https://github.com/Agoric/agoric-sdk/pull/7489#discussion_r1175603227 , and I went with `null` at the time but reconsidered when I got to this PR because it was unnecessary overhead.

File: packages/vats/src/core/startWalletFactory.js (hunk 4 above)
Comment (gibson042) [reply packages/vats/src/core/startWalletFactory.js]: > I wonder whether a bootstrap test for this is cost-effective.

Yes, definitely! Is there a good example to base it on?

File: packages/vats/src/provisionPoolKit.js (hunk 5 above)
Comment (gibson042) [reply packages/vats/src/provisionPoolKit.js]: `m.await()` is only an option for top-level arguments, but the principle still applies. Now using `deeplyFulfilled` in the function body.

File: packages/vats/src/core/startWalletFactory.js (hunk 4 above)
Comment (dckc) [reply packages/vats/src/core/startWalletFactory.js]: How about refining `test-vaults-integration.js`?

Tweak the start-up to pass in some addresses and add another test.serial to consume them.

File: packages/vats/src/core/startWalletFactory.js [hunk 7]
```diff
@@ -237,7 +237,7 @@ export const startWalletFactory = async (
     {
       storageNode: walletStorageNode,
       walletBridgeManager,
-      walletReviver: ppFacets.walletReviver,
+      walletReviver: E(ppFacets.creatorFacet).getWalletReviver(),
```
Comment (dckc) [inline packages/vats/src/core/startWalletFactory.js]: nit: seems like more of a fixup than a fix; that is: this doesn't address a defect in master.

File: packages/vats/src/core/startWalletFactory.js [hunk 8]
```diff
@@ -9,6 +9,7 @@ import {
 import { AmountMath } from '@agoric/ertp';
 import { CONTRACT_ELECTORATE, ParamTypes } from '@agoric/governance';
 import { makeStorageNodeChild } from '@agoric/internal/src/lib-chainStorage.js';
+import { makeHistoryReviver } from '../../tools/board-utils.js';
```
Comment (dckc) [inline packages/vats/src/core/startWalletFactory.js]: This will work, but since we only need the keys, it's overkill.

Comment (dckc) [reply packages/vats/src/core/startWalletFactory.js]: ah... the `.children()` feature is relevant. I get it.

File: packages/vats/src/core/startWalletFactory.js [hunk 9]
```diff
@@ -191,7 +192,11 @@ export const startWalletFactory = async (
     feeIssuerP,
   ]);
 
-  const oldAddresses = harden(chainStorageEntries.map(entry => entry[0]));
+  // Carry forward wallets with an address already in chain storage.
+  const dataReviver = makeHistoryReviver(chainStorageEntries);
+  const walletStoragePath = await E(walletStorageNode).getPath();
+  const oldAddresses = harden(dataReviver.children(`${walletStoragePath}.`));
```
Comment (dckc) [inline packages/vats/src/core/startWalletFactory.js]: `harden()` should be done inside `.children()`.

File: packages/vats/src/core/startWalletFactory.js [hunk 10]
```diff
@@ -191,7 +192,11 @@ export const startWalletFactory = async (
     feeIssuerP,
   ]);
 
-  const oldAddresses = harden(chainStorageEntries.map(entry => entry[0]));
+  // Carry forward wallets with an address already in chain storage.
+  const dataReviver = makeHistoryReviver(chainStorageEntries);
+  const walletStoragePath = await E(walletStorageNode).getPath();
```
Comment (dckc) [inline packages/vats/src/core/startWalletFactory.js:114]: If someone chose to deploy the new contract with a different storage path, that won't change where the old data is. Hard-coding the `published.wallet` path seems appropriate.

Comment (gibson042) [reply packages/vats/src/core/startWalletFactory.js:114]: Even though nothing else in this file has awareness of the "published" prefix? I was thinking that if the storage path ever changed, we'd introduce a vat parameter to communicate the old path.

Comment (dckc) [reply packages/vats/src/core/startWalletFactory.js:114]: In practice I suppose it doesn't matter.

File: packages/vats/test/test-provisionPool.js [hunk 11]
```diff
@@ -350,8 +371,124 @@ test('makeBridgeProvisionTool handles duplicate requests', async t => {
...
+  const newPurse = /** @type {Purse} */ (purses.get(newAddr));
+  const poolBank = await E(bankManager).getBankForAddress('pool');
+  const poolPurse = E(poolBank).getPurse(fees.brand);
+  await E(poolPurse).deposit(
+    await E(fees.mint).mintPayment(fees.make(scale6(100))),
+  );
+
+  // start a provisionPool contract with mock governance terms
+  const starterAmount = fees.make(250n);
+  const initialPoserInvitation = await E(committeeCreator).getPoserInvitation();
```
Comment (dckc) [inline packages/vats/test/test-provisionPool.js:435]: After writing this boilerplate for starting a governed contract 1 too many times, we came up with a puppet governance test tool that might be handy here.

https://github.com/Agoric/agoric-sdk/blob/master/packages/governance/tools/puppetGovernance.js#L1

Comment (gibson042) [reply packages/vats/test/test-provisionPool.js:435]: I'm working with existing test context here and am not confident I understand enough to adopt that utility (but we could pair on that if you think it's worthwhile).

**Comment by gibson042** [comment]
@dckc This should be ready for final review!

File: packages/internal/src/storage-test-utils.js [hunk 12]
```diff
@@ -6,6 +6,18 @@ import { bindAllMethods } from './method-tools.js';
...
+ * A map corresponding with a total function such that `get(key)`
+ * is assumed to always succeed.
+ *
+ * @template K, V
+ * @typedef {{[k in Exclude<keyof Map<K, V>, 'get'>]: Map<K, V>[k]} & {get: (key: K) => V}} TotalMap
+ */
+/**
+ * @template T
+ * @typedef {T extends Map<infer K, infer V> ? TotalMap<K, V> : never} TotalMapFrom
+ */
```
Comment (gibson042) [inline packages/internal/src/storage-test-utils.js:23]: I wrote these because I got sick of TypeScript complaining that the result of `map.get(key)` can be undefined in circumstances where we know it won't. They should probably migrate to internal or endo at some point.

Comment (dckc) [reply packages/internal/src/storage-test-utils.js:23]: :clap:

File: packages/vats/src/provisionPoolKit.js [hunk 13]
```diff
@@ -95,7 +95,7 @@ export const prepareProvisionPoolKit = (
     'ProvisionPoolKit',
     {
       machine: M.interface('ProvisionPoolKit machine', {
-        makeHandler: M.call({
+        makeBridgeHandler: M.call({
```
Comment (dckc) [inline packages/vats/src/provisionPoolKit.js]: This is a breaking contract API change. It needs a suitable conventional commit message.

File: packages/vats/src/provisionPoolKit.js [hunk 14]
```diff
@@ -163,6 +207,28 @@ export const prepareProvisionPoolKit = (
...
         },
       },
+      walletReviver: {
+        async reviveWallet(address) {
+          const {
+            revivableAddresses,
+            bankManager,
+            namesByAddressAdmin,
+            walletFactory,
+          } = /** @type {Record<string, any>} */ (this.state);
```
Comment (dckc) [inline packages/vats/src/provisionPoolKit.js]: why does this need a cast? The init function should provide the type, I think.

Let's avoid `any`. Or clearly document why we're using it.

File: packages/vats/test/test-provisionPool.js (hunk 11 above)
Comment (dckc) [reply packages/vats/test/test-provisionPool.js:435]: ok.

File: packages/vats/src/provisionPoolKit.js [hunk 15]
```diff
@@ -210,15 +216,17 @@ export const prepareProvisionPoolKit = (
...
       },
       walletReviver: {
+        /** @param {string} address */
         async reviveWallet(address) {
           const {
             revivableAddresses,
             bankManager,
             namesByAddressAdmin,
             walletFactory,
-          } = /** @type {Record<string, any>} */ (this.state);
```
Comment (dckc) [inline packages/vats/src/provisionPoolKit.js]: ah. I was reviewing by commit. nvm

File: packages/vats/src/provisionPoolKit.js [hunk 16]
```diff
@@ -224,7 +226,7 @@ export const prepareProvisionPoolKit = (
             namesByAddressAdmin,
             walletFactory,
           } = this.state;
-          if (!(bankManager && namesByAddressAdmin && walletFactory)) {
+          if (!bankManager || !namesByAddressAdmin || !walletFactory) {
```
Comment (dckc) [inline packages/vats/src/provisionPoolKit.js]: consider [assertAllDefined](https://github.com/Agoric/agoric-sdk/blob/d2164c968cda56e110dd3b9e98a32be61a72281c/packages/internal/src/utils.js#L279-L280)

Hm... it doesn't have a place to put "must do X before Y"

**Review by dckc — CHANGES_REQUESTED** [review]
the re-bootstrap test looks nifty. Here's hoping I can study it some more.

Meanwhile... the contract API change needs a BREAKING CHANGE indicator

File: packages/vats/src/provisionPoolKit.js (hunk 13 above)
Comment (ivanlei) [reply packages/vats/src/provisionPoolKit.js]: I think at this point in the release, a breaking change isn't warranted. Please use the existing name and we can choose to change the name in a future issue.

Comment (gibson042) [reply packages/vats/src/provisionPoolKit.js]: Reverted.

File: packages/vats/src/provisionPoolKit.js [hunk 17]
```diff
@@ -132,31 +166,54 @@ export const prepareProvisionPoolKit = (
...
-         *   walletFactory: *,
-         * }} opts
+         * @param {string[]} oldAddresses
          */
-        makeHandler(opts) {
-          const {
-            facets: { helper },
-          } = this;
+        addRevivableAddresses(oldAddresses) {
+          this.state.revivableAddresses.addAll(oldAddresses);
```
Comment (dckc) [inline packages/vats/src/provisionPoolKit.js]: let's log `oldAddresses.length` here, please

**Review by dckc — APPROVED** [review]
good stuff!

good to go once the ci checks pass

File: packages/vats/src/provisionPoolKit.js (hunk 17 above)
Comment (gibson042) [reply packages/vats/src/provisionPoolKit.js]: Just `console.log('revivableAddresses count', oldAddresses.length)`?

File: packages/inter-protocol/src/proposals/startPSM.js [hunk 18]
```diff
@@ -351,6 +368,8 @@ export const makeAnchorAsset = async (
     // eslint-disable-next-line @jessie.js/no-nested-await
     const anchorPaymentMap = await anchorBalancePayments;
 
+    // TODO: validate that `metrics.anchorPoolBalance.value` is
+    // pass-by-copy PureData (e.g., contains no remotables).
```
Comment (dckc) [inline packages/inter-protocol/src/proposals/startPSM.js:372]: you can use `Nat` or `M.nat()`. PSM brands have to be fungible.
