### PR TITLE
fix: filter proposal give and want by sparseKeywords in zcf.reallocate

### LINKED ISSUE #1075: [Zoe] Reallocate only for Keyword not in user's `give` or `want`
The scenario:

Alice specifies their proposal:

```
 const aliceProposal = harden({
    give: { Asset: moola(3) },
    want: { Price: simoleans(7) },
    exit: { onDemand: null },
  });
```

We want to give Alice an unrelated token (`Freebie`) that she doesn't previously know about (and importantly, does not mention in her proposal.)

We use the helper `escrowAndAllocateTo`. Within this helper, we call `reallocate` which only reallocates for the particular `keyword` by using the third parameter to filter:

```
          zcf.reallocate(
            harden([tempHandle, recipientHandle]),
            harden([tempAlloc, recipientAlloc]),
            harden([keyword]),
          );
```
In the `reallocate` call, `isOfferSafeForOffer` for offer is called. For the reallocation to be offer safe, either the user must be given what they gave (a refund) or what they want (winnings). When we introduced sparse keywords, we filtered and filled the current allocations by keyword and asserted that all the sparse keywords were present in the `newAllocations`, but we didn't filter the `give` or `want`. 

Because we didn't filter the proposal by the keyword, we are left in the situation of comparing Alice's `give: Asset: moola(3)` and `want: { Price: simoleans(7) }` with the allocation of `Freebie: freebie(100)`. This obviously turns out to not be offer safe. We should be filtering the proposal keywords too, so that we are actually comparing a proposal of `{ want: {}, give: {} }` (Alice had no rule for Freebie) with an allocation of `Freebie: freebie(100)`, which should be offer safe. 

## Actual

After `reallocate` is called with third parameter `sparseKeywords = ['Freebie']`, `isOfferSafeForOffer` is comparing the full original proposal `give` and `want`:

```
    give: { Asset: moola(3) },
    want: { Price: simoleans(7) },
```
with the allocation: `{ Freebie: freebie(1000) }`

Offer safety fails, because we have given neither what the user wanted or gave.

## Expected

Instead, what should happen is:

After `reallocate` is called with third parameter `sparseKeywords = ['Freebie']`, `isOfferSafeForOffer` is comparing  the proposal `give` and `want` filtered by `sparseKeywords`:

```
    give: { },
    want: { },
```
with the allocation: `{ Freebie: freebie(1000) }`

Offer safety succeeds trivially, because the user did not specify Freebie in their `give` or their `want`.

### PR DESCRIPTION
**Pull request by katelynsills**
This PR fixes a bug (#1075) in `zcf.reallocate` in which we were filtering and filling the current allocation by `sparseKeywords` and asserting that the `newAllocation` is filled for `sparseKeywords` but we were not filtering the `proposal.want` or `proposal.give`, leading to valid partial reallocations being rejected for not meeting offer safety. See issue for more details. 

Adds two tests. One test ensures that an allocation of something that is not specified in the proposal is offer safe. Another test ensures that the `mintPayments.js` contract works even if the user has `proposal.want` and `proposal.give` using different keywords. The user gets a refund and the newly minted assets.

Edit (5/8/2020, 4:55pm): Updated information about how we handle sparse keywords for the current allocation and the `newAllocation`. We do not fill the `newAllocation`, we only assert that all the sparseKeywords exist. 

Closes #1075

### CODE REVIEW

File: packages/zoe/src/objArrayConversion.js [hunk 1]
```diff
@@ -70,6 +70,21 @@ export const filterObj = /** @type {function<T>(T, string[]): T} */ (
   return newObj;
 };
 
+// return a new object with only the keys in subsetKeywords. `obj`
+// may *not* have all the `subsetKeywords`.
```
Comment (Chris-Hibbert) [inline packages/zoe/src/objArrayConversion.js]: Sorry, I read "may *not* have all" as "is not allowed to have all", while I think it should say "is allowed to not include some".  "might *not* have all" is also unambiguous.

File: packages/zoe/test/unitTests/contracts/test-mintPayments.js [hunk 2]
```diff
@@ -50,3 +52,72 @@ test('zoe - mint payments', async t => {
...
+    const instanceHandle = await getInstanceHandle(adminInvite);
+
+    // Bob wants to get 1000 tokens so he gets an invite and makes an
+    // offer
+    const { publicAPI } = await E(zoe).getInstanceRecord(instanceHandle);
+    const invite = await E(publicAPI).makeInvite();
+    t.ok(await E(inviteIssuer).isLive(invite), `valid invite`);
+    const proposal = harden({
+      give: { Asset: moolaBundle.amountMath.make(10) },
+      want: { Price: simoleanBundle.amountMath.make(100) },
```
Comment (Chris-Hibbert) [inline packages/zoe/test/unitTests/contracts/test-mintPayments.js:87]: Bob's `want` was simoleans. Did he get any simoleans? 

I think this is being processed as a refund rather than a successful transaction where they got what they wanted. This shows that `reallocate()` worked. I'd also like to see that `complete()` works when there has been a trade.

**Review by Chris-Hibbert — CHANGES_REQUESTED** [review]

File: packages/zoe/src/objArrayConversion.js (hunk 1 above)
Comment (katelynsills) [reply packages/zoe/src/objArrayConversion.js]: Sure, that sounds good

File: packages/zoe/test/unitTests/contracts/test-mintPayments.js (hunk 2 above)
Comment (katelynsills) [reply packages/zoe/test/unitTests/contracts/test-mintPayments.js:87]: Yes, this is a refund because it is the makePayment contract, which doesn't do any swapping. Bob didn't get any simoleans.

Whether complete works when there is a trade is out of scope for this test, but it is tested by the atomicSwap test.

**Review by erights — CHANGES_REQUESTED** [review]
If we have the bug I think we do, I don't understand why this seems to work at all.

At https://github.com/Agoric/agoric-sdk/blob/32a23e6766bf3e07e688df80cba0f41469edc46c/packages/zoe/src/offerSafety.js#L40 you check offer safety by enumerating `[keyword, amount]` pairs of `proposal.give`, checking that the new allocation `isGTE` the allocation proposed to give. However, with this PR the new allocation may omit a keyword, in which case 
https://github.com/Agoric/agoric-sdk/blob/32a23e6766bf3e07e688df80cba0f41469edc46c/packages/zoe/src/offerSafety.js#L32
will be `undefined`.

Likewise for `proposal.want`. Once I understand what's going on here, I'll take a good look at rightsConservation.js.

**Comment by Chris-Hibbert** [comment]
> with this PR the new allocation may omit a keyword

I  think offer safety is only supposed to check that want and give are satisfied. There is a separate check that currency is conserved.  Anything outside those limits is up to the contract. The point of this bug fix is that if the contract decides to provide something that's not specified by anyone's proposals, it can add it and move it around as much as is useful without any offer having anything to say about it.

**Review by erights — APPROVED** [review]
@katelynsills clarified. the `newAllocations` must still be as populated as before, so the danger I worried about is invalid.

LGTM

**Comment by erights** [comment]
@Chris-Hibbert I misunderstood the PR as allowing more keyword positions to be absent, such as in the `newAllocations`. @katelynsills explained and we verified that the only new absences allowed are in the proposals. So my concern was invalid.

**Comment by katelynsills** [comment]
Added an edit clarifying what happens with the current allocation and the `newAllocation` within `reallocate`.
