### PR TITLE
fix(swingset): use "dirt" to schedule vat reap/bringOutYourDead

### LINKED ISSUE #8980: dirty-vat -driven BOYD scheduler
## What is the Problem Being Solved?

Vats accumulate "garbage" over time: JS objects (Presences, Remotables, Representaives) which have been collected but not processed, as well as imported/exported refcounts that have reached zero but not yet processed. We defer this processing until a special `dispatch.bringOutYourDead` delivery, which performs an engine-level forced GC pass, examines all the finalizers that have run since the last BOYD, and checks current refcounts on every vref/baseref that might now be unreachable or unrecognizable.

We defer BOYD until specific calls, to reduce the sensitivity of normal execution (especially metering and the syscall transcript) to the details of the garbage collector. We definitely need to prevent userspace from sensing GC activity, but if we can also maintain the transcript's insensitivty, then we have more flexibility to change the engine in the future (upgrading XS or xsnap without requiring a complete vat upgrade).

We also do a BOYD just before we write out an XS heap snapshot, because the heap-writing process does a forced GC anyways, and we want to minimize the size of the snapshot (i.e. "empty your trash cans before you put them in the moving van").

However, this raised the question of how frequently we should make these BOYD calls. Too frequently, and we're spending a lot of time forcing unnecessary GC mark-and-sweep operations. Too infrequently, and a single BOYD might need to examine a large number of vrefs, which requires refcount syscalls (`vatstoreGet`), and which might create `syscall.dropImports/retireImports` calls with a large number of vrefs (which creates spikes in kernel activity that may cause problems).

The current kernel scheduler triggers a BOYD after every 2000 deliveries ("`reapInterval`", recorded separately for each vat in `vatKeeper.updateReapInterval()`, read from a kernel-wide configurable default that is set with `changeKernelOptions({defaultReapInterval: NN})`). However it also triggers a heap snapshot (and thus a BOYD) on a different schedule: 3 deliveries after the start of the incarnation, and then every 200 deliveries (`snapshotInitial` and `snapshotInterval`, configurable on the kernel as a whole with `changeKernelOptions({snapshotInterval: NN})`). The host application can also invoke `controller.reapAllVats()` to trigger a BOYD on all vats, although this does not update the counters (#8665), so the usual BOYDs will still happen at their usual time.

The worst case, and the motivation for this ticket, is when a large vat is terminated, or deletes a large collection, and drops a lot of references into some other vat. The #8928 strategy limits the rate at which we send `dispatch.dropExports/retireExports` into the upstream vat, but if we don't also do BOYD frequently enough, we'll still be stuck with problematically-large BOYD deliveries. The largest expansion factor I've seen so far is when a terminated contract's ExitObject or SeatHandle is dropped, because these are engaged in reference cycles through v9-zoe. Each dropped object triggers about 50 syscalls in v9-zoe (to unwind the zoe-side portion of the cycle).

I want to limit each BOYD to maybe 500 syscalls, to minimize the CPU time and kvStore churn (which causes IAVL churn, which adds to the cosmos-sdk state pruning work that happens sooner or later). Based on my studies so far, 500 syscalls of work can be done in about half a second, which seems safe to do in nearly every block (as a "background" task, only done when no other work was done in that block).

So I want the scheduler to trigger a BOYD after 10 krefs have been dropped and retired.

## Description of the Design

We'd replace the current `vNN.reapCountdown` vatKeeper key with one named `vNN.dirty`. The value is a JSON-serialized record with `{ deliveries, gcKrefs, computrons }`. Each non-BOYD delivery (and its `deliveryResults`) gets sent to a new function, maybe named `measureDirt`, which:
* deserializes the old record
* increments `deliveries`
* uses the result computrons (if any) to increment `computrons`
* examines the delivery to see if it's a `dispatch.dropImports` or other GC delivery, counts the krefs inside, and maybe increments `gcKrefs`
* serializes and writes the record back to kvStore
* finally, compare the values against the vat's trigger thresholds (`vNN.reapInterval`, and some new kernel-wide `gcKrefsLimit`)
  * if exceeded, add the vatID to kernelKeeper's `reapQueue` with `scheduleReap(vatID)`

Then, the next time `kernel.step()` happens, it might see a vatID in the reapQueue, and process it:
* remove the vatID from `reapQueue`
* perform the BOYD delivery
* zero out the `vNN.dirty` counters

In addition, the BOYD we do as part of writing heap snapshots should zero out the counters and remove it from `reapQueue`. That would fix the #8665 problem, as well as deferring BOYDs to the next correct time (avoiding rapid BOYDs when the `snapshotInterval` counter phases in and out of sync with the `reapInterval` counter).

We'll need to make the thresholds configurable. We already have `changeKernelOptions({defaultReapInterval})`, but it only sets the default (which gets sampled when a vat is created), and doesn't provide a way to modify a single vat's interval later. And we certainly need a new control on the GC kref threshold, so maybe we add `changeKernelOptions({gcKrefReapThreshold})` (but I don't love the spelling of that).

This `vNN.dirty` record could also be used to schedule heap snapshots some day (#6786). Some thoughts:

* burning computrons should definitely accelerate the heap-snapshot schedule, since they represent work that must be done on the next replay, creating surprising delays during reboot or paging-in an offline vat worker
* but we don't record computrons for first-turn liveslots work, which includes all of the GC and BOYD deliveries
  * a large BOYD could do thousands of syscalls, but not appear to consume significant computrons
  * so we might want to add a syscall counter to `dirty`, and also trigger snapshots after a lot of them
  * and eventually we should start metering the GC/BOYD work, not to charge against the vat's Meter, but certainly to share with the `runPolicy`, and probably also to trigger snapshots
* I'm not currently convinced that computron-counting is useful for scheduling BOYDs
  * I have a theory which could be proved/disproved by scanning the slogfiles and computing some statistics:
    * in general, most `dispatch.deliver` *increase* the number of vrefs being tracked (especially if they include vrefs as arguments)
    * in general, most `dispatch.notify` (promise resolutions) *decrease* the number of vrefs, increasing garbage
    * GC deliveries almost always decrease the number of vrefs
    * so it might be an interesting heuristic might be to count `.slots.length` and delivery-type, and use them to compute a score, which might ignore `dispatch.deliver` but would trigger GC sooner if a lot of `dispatch.notify` or `dispatch.dropImports/etc` deliveries were made
* but `vNN.dirty` is a decent place to track them, or to add new things to be tracked

## Security Considerations

None, userspace code cannot observe GC or BOYD. The most significant concern is what kind of userspace behavior could provoke excessive BOYDs (either too frequently, or individual ones that are too large). E.g. creating a large collection and then dereferencing it, so it gets collected in a future BOYD, which then gets too big (would be addressed/prevented by #8417). Changing the scheduler might change the tactics an attacker might take to provoke this, but I think a dirt-driven scheduler should generally work better than our current `reapInterval` approach.

## Scaling Considerations

The main purpose of this scheduler is to improve the scaling behavior, by doing BOYD more frequently when there is more garbage to be collected, and avoiding infrequent-but-large BOYDs (which trigger bad kernel behavior, #8402).

## Test Plan

Swingset unit tests which use fake vats (returning fake metering data), to measure exactly when BOYD happens.

## Upgrade Considerations

Transitioning from `vNN.reapCountdown` to `vNN.dirty` is a schema upgrade that can be done lazily. We'll delete `countdownToReap()` and replace it with `addDirt()` (etc), and the new function needs to accommodate a missing `vNN.dirty` key by initializing it to a new zero record, looking for a legacy `vNN.reapCountdown` (and the still-useful `vNN.reapInterval`), and subtracting them to deduce the new `.deliveries`. We didn't have a `gcKrefs` or computron-counter before, so we don't need to initialize them with anything but zero.

This is a one-way upgrade, of course, since we delete `vNN.reapCountdown`.

### PR DESCRIPTION
**Pull request by warner**
fix(swingset): use "dirt" to schedule vat reap/bringOutYourDead

NOTE: deployed kernels require a new `upgradeSwingset()` call upon
(at least) first boot after upgrading to this version of the kernel
code.

`dispatch.bringOutYourDead()`, aka "reap", triggers garbage collection
inside a vat, and gives it a chance to drop imported c-list vrefs that
are no longer referenced by anything inside the vat.

Previously, each vat has a configurable parameter named
`reapInterval`, which defaults to a kernel-wide
`defaultReapInterval` (but can be set separately for each vat). This
defaults to 1, mainly for unit testing, but real applications set it
to something like 1000.

This caused BOYD to happen once every 1000 deliveries, plus an extra
BOYD just before we save an XS heap-state snapshot.

This commit switches to a "dirt"-based BOYD scheduler, wherein we
consider the vat to get more and more dirty as it does work, and
eventually it reaches a `reapDirtThreshold` that triggers the
BOYD (which resets the dirt counter).

We continue to track `dirt.deliveries` as before, with the same
defaults. But we add a new `dirt.gcKrefs` counter, which is
incremented by the krefs we submit to the vat in GC deliveries. For
example, calling `dispatch.dropImports([kref1, kref2])` would increase
`dirt.gcKrefs` by two.

The `reapDirtThreshold.gcKrefs` limit defaults to 20. For normal use
patterns, this will trigger a BOYD after ten krefs have been dropped
and retired. We choose this value to allow the #8928 slow vat
termination process to trigger BOYD frequently enough to keep the BOYD
cranks small: since these will be happening constantly (in the
"background"), we don't want them to take more than 500ms or so. Given
the current size of the large vats that #8928 seeks to terminate, 10
krefs seems like a reasonable limit. And of course we don't want to
perform too many BOYDs, so `gcKrefs: 20` is about the smallest
threshold we'd want to use.

External APIs continue to accept `reapInterval`, and now also accept
`reapGCKrefs`, and `neverReap` (a boolean which inhibits all BOYD,
even new forms of dirt added in the future).

* kernel config record
  * takes `config.defaultReapInterval` and `defaultReapGCKrefs`
  * takes `vat.NAME.creationOptions.reapInterval` and `.reapGCKrefs`
    and `.neverReap`
* `controller.changeKernelOptions()` still takes `defaultReapInterval`
   but now also accepts `defaultReapGCKrefs`

The APIs available to userspace code (through `vatAdminSvc`) are
unchanged (partially due to upgrade/backwards-compatibility
limitations), and continue to only support setting `reapInterval`.
Internally, this just modifies `reapDirtThreshold.deliveries`.

* `E(vatAdminSvc).createVat(bcap, { reapInterval })`
* `E(adminNode).upgrade(bcap, { reapInterval })`
* `E(adminNode).changeOptions({ reapInterval })`

Internally, the kernel-wide state records `defaultReapDirtThreshold`
instead of `defaultReapInterval`, and each vat records
`.reapDirtThreshold` in their `vNN.options` key instead of
`vNN.reapInterval`. The vat-level records override the kernel-wide
values. The current dirt level is recorded in `vNN.reapDirt`.

NOTE: deployed kernels require explicit state upgrade, with:

```js
import { upgradeSwingset } from '@agoric/swingset-vat';
..
upgradeSwingset(kernelStorage);
```

This must be called after upgrading to the new kernel code/release,
and before calling `buildVatController()`. It is safe to call on every
reboot (it will only modify the swingstore when the kernel version has
changed). If changes are made, the host application is responsible for
commiting them, as well as recording any export-data updates (if the
host configured the swingstore with an export-data callback).

During this upgrade, the old `reapCountdown` value is used to
initialize the vat's `reapDirt.deliveries` counter, so the upgrade
shouldn't disrupt the existing schedule. Vats which used `reapInterval
= 'never'` (eg comms) will get a `reapDirtThreshold.never = true`, so
they continue to inhibit BOYD. Any per-vat settings that match the
kernel-wide settings are removed, allowing the kernel values to take
precedence (as well as changes to the kernel-wide values; i.e. the
per-vat settings are not sticky).

We do not track dirt when the corresponding threshold is 'never', or
if `neverReap` is true, to avoid incrementing the comms dirt counters
forever.

This design leaves room for adding `.computrons` to the dirt record,
as well as tracking a separate `snapshotDirt` counter (to trigger XS
heap snapshots, ala #6786). We add `reapDirtThreshold.computrons`, but
do not yet expose an API to set it.

Future work includes:
* upgrade vat-vat-admin to let userspace set `reapDirtThreshold`

New tests were added to exercise the upgrade process, and other tests
were updated to match the new internal initialization pattern.

We now reset the dirt counter upon any BOYD, so this also happens to
help with #8665 (doing a `reapAllVats()` resets the delivery counters,
so future BOYDs will be delayed, which is what we want). But we should
still change `controller.reapAllVats()` to avoid BOYDs on vats which
haven't received any deliveries.

closes #8980

### CODE REVIEW

**Comment by mhofman** [comment]
> We choose this value to allow the #8928 slow vat
> termination process to trigger BOYD frequently enough to keep the BOYD
> cranks small: since these will be happening constantly (in the
> "background"), we don't want them to take more than 500ms or so. Given
> the current size of the large vats that #8928 seeks to terminate, 10
> krefs seems like a reasonable limit. And of course we don't want to
> perform too many BOYDs, so `gcKrefs: 20` is about the smallest
> threshold we'd want to use.

I am somewhat concerned that the cost of engine gc might mean 20 is too low. How do we validate we won't spend too much time in BOYD? Do we have an idea of what portion of the time spent in BOYD is related to the engine doing a gc mark and sweep, and how much of it is liveslots reacting to the found garbage? I assume liveslots usually has vatStore calls to make when garbage was found?


> External APIs continue to accept `reapInterval`, and now also accept `reapGCKrefs`.
> 
> * kernel config record
>   
>   * takes `config.defaultReapInterval` and `defaultReapGCKrefs`
>   * takes `vat.NAME.creationOptions.reapInterval` and `.reapGCKrefs`
> * `controller.changeKernelOptions()` still takes `defaultReapInterval`
>   but now also accepts `defaultReapGCKrefs`

This does not sound scalable for adding new dirt thresholds. Why not add a `reapDirtThresholds` record in configs / options?

> The kernel will automatically upgrade both the kernel-wide and the
> per-vat state upon the first reboot with the new kernel code. 

I'll need to look at this. It sounds like a sort of schema migration.

> as well as tracking a separate `snapshotDirt` counter (to trigger XS
> heap snapshots, ala #6786).

~I'm not sure I understand this. Is the idea to trigger snapshots every `n` BOYD? Snapshots should already force BYOD before snapshotting. The snapshotting process reveals gc to liveslots, which may have bugs revealing this out (#6784), so the idea has been to force a BOYD before each snapshot (#7504) but we expect BOYD to be more frequent than snapshots.~

Edit: I totally misunderstood `snapshortDirt`: it's not meant to trigger reap, or be related to `reapDirt`, just will likely use a similar accounting mechanism, with likely similar dirt input.

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 1]
```diff
@@ -39,11 +39,30 @@ const FIRST_DEVICE_ID = 70n;
...
+  kvStore,
+  transcriptStore,
+  vatID,
+  source,
+  options,
+) {
+  assert(options.workerOptions, `vat ${vatID} options missing workerOptions`);
+  assert(source);
+  assert('bundle' in source || 'bundleName' in source || 'bundleID' in source);
+  assert.typeof(options, 'object');
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/vatKeeper.js]: This should check that `options` is a non-`null` object before checking that `optons.workerOptions` exists, but this seems to be a problem with the original `setSourceAndOptions` too.

Which brings me to the second issue: I'm not a major fan of duplicating the logic between there and here. Any way to refactor to use the same underlying implementation for both the checks and saving the values to the kvStore?

File: packages/SwingSet/src/controller/initializeKernel.js [hunk 2]
```diff
@@ -9,14 +9,32 @@ import { insistVatID } from '../lib/id.js';
...
+} from '../kernel/state/kernelKeeper.js';
 import { exportRootObject } from '../kernel/kernel.js';
 import { makeKernelQueueHandler } from '../kernel/kernelQueue.js';
 
+/**
+ * @typedef { import('../types-external.js').SwingSetKernelConfig } SwingSetKernelConfig
+ * @typedef { import('../types-external.js').SwingStoreKernelStorage } SwingStoreKernelStorage
+ * @typedef { import('../types-internal.js').InternalKernelOptions } InternalKernelOptions
+ * @typedef { import('../types-internal.js').ReapDirtThreshold } ReapDirtThreshold
+ */
```
Comment (mhofman) [inline packages/SwingSet/src/controller/initializeKernel.js:24]: We switched to TS 5.5 so we can now use `@import` ! See #9149

That said, there are a lot of other places in kernel code where we should switch, so I'm ok punting for now.

File: packages/SwingSet/src/kernel/kernel.js [hunk 3]
```diff
@@ -379,7 +380,7 @@ export default function buildKernel(
    *    didDelivery?: VatID, // we made a delivery to a vat, for run policy and save-snapshot
    *    computrons?: BigInt, // computron count for run policy
    *    meterID?: string, // deduct those computrons from a meter
-   *    decrementReapCount?: { vatID: VatID }, // the reap counter should decrement
+   *    measureDirt?: [ VatID, Dirt ], // the dirt counter should increment
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js]: Any reason to switch to a tuple instead of a record here for the return value?

File: packages/SwingSet/src/kernel/kernel.js [hunk 4]
```diff
@@ -601,6 +607,8 @@ export default function buildKernel(
     if (!vatWarehouse.lookup(vatID)) {
       return NO_DELIVERY_CRANK_RESULTS; // can't collect from the dead
     }
+    const vatKeeper = kernelKeeper.provideVatKeeper(vatID);
+    vatKeeper.addDirt({ gcKrefs: krefs.length });
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/kernel.js]: Why not plumb this into `deliveryCrankResults` and rely the handling of crank results to add dirt?

Let's assume we started counting the number of refs introduced in every delivery as a dirt counter (the more you have, the more likely you are to have some that are now garbage). That number is also derived from the message. In that case, does it make sense to increment here or in the results? I suppose the handling of abort/terminate may have an influence on this?

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 5]
```diff
@@ -327,6 +374,55 @@ export default function makeKernelKeeper(kernelStorage, kernelSlog) {
     initializeStats();
   }
 
+  // maybeUpgradeKernelState() can be called multiple times; this flag
+  // helps avoid extra "are we upgraded" DB queries
+  let upgraded = false;
+
+  // the caller is responsible for ensuring that any changes made here
+  // get committed at a useful point
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: Some worry that a rollback could revert the kernel state but would leave the `upgraded` flag in place, but it looks like this is always called outside savepoints. Why not run this at the beginning of every `startCrank()`?

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 6]
```diff
@@ -327,6 +374,55 @@ export default function makeKernelKeeper(kernelStorage, kernelSlog) {
...
+      // along. By upgrading the kernel's recorded default here, the
+      // subsequent maybeUpgradeVatState() calls will upgrade each vat
+      // to this new value. If we waited for the host app to call
+      // controller.setKernelOptions(), the vats would be upgraded
+      // without a "gcKrefs", and would not trigger BOYDs the way we
+      // want.
+      /** @type ReapDirtThreshold */
+      const threshold = {
+        deliveries: 'never',
+        gcKrefs: DEFAULT_GC_KREFS_PER_BOYD,
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: I would imagine that if the old reap interval was never, we want a `gcKrefs` value of `'never'` in the new kernel options, no ?

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 7]
```diff
@@ -68,7 +74,8 @@ const enableKernelGC = true;
 // bundle.$BUNDLEID = JSON(bundle)
 //
 // kernel.defaultManagerType = managerType
-// kernel.defaultReapInterval = $NN
+// (old) kernel.defaultReapInterval = $NN
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:89]: should we have a "formal" schema v0 designation. At some point I assume we'll have multiple "old"

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 8]
```diff
@@ -148,33 +228,70 @@ export function makeVatKeeper(
...
+    if (reap) {
+      scheduleReap(vatID);
+    }
+  }
+
+  function getReapDirt() {
+    return reapDirt;
+  }
+
+  function clearReapDirt() {
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/vatKeeper.js:224]: We need to also call this when injecting the BOYD message in `maybeSaveSnapshot`

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 9]
```diff
@@ -163,6 +188,21 @@ const FIRST_PROMISE_ID = 40n;
 const FIRST_CRANK_NUMBER = 0n;
 const FIRST_METER_ID = 1n;
 
+// this default "reap interval" is low for the benefit of tests:
+// applications should set it to something higher (perhaps 200) based
+// on their expected usage
+
+export const DEFAULT_DELIVERIES_PER_BOYD = 1;
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:226]: I am somewhat concerned with a default value that is not "production ready", but this seems to be the existing behavior already, so out of scope. Is the builder for a test kernel the same as the production one?

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 10]
```diff
@@ -119,6 +193,12 @@ export function makeVatKeeper(
     return value;
   }
 
+  // We keep the vat's reap-dirt state (and threshold) in a
+  // write-through cache, and populate the cache at vatKeeper startup.
+  const reapDirtKey = `${vatID}.reapDirt`;
+  let reapDirt = JSON.parse(getRequired(reapDirtKey));
+  let reapDirtThreshold = getOptions().reapDirtThreshold;
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/vatKeeper.js]: I'm having funny feelings about ad-hoc caching, in particular because I don't fully understand the impact of savepoints and crank rollbacks.

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 11]
```diff
@@ -148,33 +228,70 @@ export function makeVatKeeper(
...
+      const threshold = reapDirtThreshold[key];
+      // Don't accumulate dirt if it can't eventually trigger a
+      // BOYD. This is mainly to keep comms from counting upwards
+      // forever. TODO revisit this when we add heapSnapshotDirt,
+      // maybe check both thresholds and accumulate the dirt if either
+      // one is non-'never'.
+      if (threshold && threshold !== 'never') {
+        const oldDirt = reapDirt[key] || 0;
+        // The 'moreDirt' value might be Number or BigInt (eg
+        // .computrons). We coerce to Number so we can JSON-stringify.
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/state/vatKeeper.js:204]: I thought we converted the `computrons` to Number before putting the value in the dirt record?

**Review by mhofman — COMMENTED** [review]
This is mostly looking good.

I think we're missing a `clearReapDirt` for the BOYD injected when creating a snapshot.

Wondering if the schema migration should be handled more explicitly when starting the kernel instead of optimistically running it before each crank.

I'll need to do another pass and review the tests.

File: packages/SwingSet/src/controller/initializeKernel.js (hunk 2 above)
Comment (warner) [reply packages/SwingSet/src/controller/initializeKernel.js:24]: yeah I'd like to do that cleanup in a separate PR, and I'm concerned about how it will interact with our current branch policy (cherry-picking changes to a release branch)

Comment (mhofman) [reply packages/SwingSet/src/controller/initializeKernel.js:24]: good call

File: packages/SwingSet/src/kernel/kernel.js (hunk 3 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js]: No good ones, I think I ran into a name collision during development, but I can't find evidence of it now, so I'll switch to a record.

File: packages/SwingSet/src/kernel/kernel.js (hunk 4 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js]: I think that would work. It would look like
```js
function deliveryCrankResults(vatID, status, measureDirt, meterID, gcKrefs) {
  ...
  if (measureDirt && ..) {
    if (gcKrefs) {
      dirt.gcKrefs = gcKrefs;
    }
 ..
}

...

  deliveryCrankResults(vatID, status, true, undefined, krefs.length);
```

IIRC I balked at adding another positional argument to `deliveryCrankResults()` which would only be used by `processGCMessage()` but would need to be provided by all callers, especially since we've already got the optional `meterID` posarg, and stopped short of converting the posargs to an options bag.

I think the abort/terminate shouldn't be a big influence.. I don't know exactly whether we should increment the dirt counter if the delivery caused a vat-fatal error or not, but I think either way would be ok.

I'll look to see if there's a decent way to refactor it as you suggest.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 7 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:89]: Yeah, we're still in that fuzzy ad-hoc stage of this table's maturity curve, but I'll improve the comments and write down the definitions of v0/v1/whatever even though we don't have a single key that says what version the kvStore is at. For swingstore I'm working on making it precise (and doing a full+atomic migration from vN to vN+1), but for this table, the weird thing was that vatKeepers have an "upgrade your keys" function, which the kernel calls at startup (sometimes), so there's a brief window during this call where vat4 has migrated but vat5 has not, and that didn't lend itself to declaring the entire kvStore as at "version 2", and I didn't want to introduce per-vat version keys either.

File: packages/SwingSet/src/kernel/kernel.js (hunk 4 above)
Comment (mhofman) [reply packages/SwingSet/src/kernel/kernel.js]: Oh yeah definitely should avoid more positional args. That's what named args (destructured records are for).

Btw, the above was a light suggestion, I'm really not sure if it makes sense. I just had some trouble following the flow of where dirt gets changed.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 9 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:226]: The (weak) philosophy here was that we don't know what a good value would be, so make the default a predictable and hyper-safe one, at the cost of performance. Making it convenient for tests is another consideration, although of course it's always a lazy and inadvisable choice to prioritize tests over reality.

We might even make a hand-wavy argument that this matches XS: minimizing RAM usage (ie GCing frequently) at the cost of performance.

> Is the builder for a test kernel the same as the production one?

Not sure what you mean, our most important host application (cosmic-swingset) overrides this value, and in general we expect all host applictions to do so.

Comment (mhofman) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:226]: I was remembering that all tests used a single function to build the kernel, in which case we could have a value more appropriate for production as a default here. Anyway, as stated this not really in scope for this PR.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 5 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: Yeah, there's one `upgraded` flag per `KernelKeeper` object, and each kernel has exactly one `KernelKeeper` (created at the start of `buildKernel()`), but we also create a `KernelKeeper` when we initialize/populate the DB, and we should *not* be doing an upgrade at that time, which is why `maybeUpgradeKernelState()` is a method and not an automatic consequence of `makeKernelKeeper()`.

It's currently called just before each call to `startCrank()`.. I wanted to make it more explicit, because (as you noted) it's important to call it from outside a savepoint. I was worried that adding it to `startCrank()` would obscure the upgrade point and make it fragile under maintenance.

But.. in looking more carefully at how/when `startCrank` is called (it also show up in `changeKernelOptions` and `installBundle`, to which I did *not* add a `maybeUpgrade` call), I think my PR would have a small bug. `kernelKeeper.startCrank()` calls `kernelStorage.startCrank()` in swing-store, which sets an `inCrank = true` flag, and calls `resetCrankHash()`. By not calling `startCrank` *before* `maybeUpgrade` (or not calling it at all, if we start with `changeKernelOptions` or `installBundle`, which sounds pretty plausible TBH), we don't include any upgrade-related kvStore changes in the crankhash. That's not the intent: upgrades are in-consensus, all nodes of a consensus kernel should upgrade at the same time, and their changes should be included in the crankhash.

So I think I need to change this as you suggest: call `maybeUpgradeKernelState()` from inside `kernelKeeper.startCrank()`, but do it specifically *after* that function calls `kernelStorage.startCrank()`. I'm not excited to conceal the fact that upgrades are happening from call sites like `step()` and `run()`, but it's more important to have these upgrade changes be captured in the hash reliably.

Comment (mhofman) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: > we also create a `KernelKeeper` when we initialize/populate the DB, and we should _not_ be doing an upgrade at that time, which is why `maybeUpgradeKernelState()` is a method and not an automatic consequence of `makeKernelKeeper()`.

That had totally skipped my mind. Can we document somewhere these constraints?

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 6 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: Yeah, that's probably a good idea. I considered it, but it felt weird to have one category (`gcKrefs`) be influenced by an unrelated one (`deliveries`).  But yeah, it probably captures the old config's intention better to set everything to `never` in that case. I'll make the change.

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 1 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/vatKeeper.js]: aye, I'll change the order of the asserts

I guess I could factor out a two-line function (plus some asserts), and call it from both places, but it didn't seem worth it at the time, and I didn't think of a good name for it. `doSetSourceAndOptions(kvStore, source, options)` ?

It's important that `initializeVatState()` remain a standalone function, not a method on `vatKeeper`, because it must be called before creating a `vatKeeper()` (which asserts the presence of `.options`, to populate the `reapDirtThreshold` RAM cache).

I'll see what I can do.

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 10 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/vatKeeper.js]: I probably haven't considered it thoroughly enough, but my basic idea was that crank rollbacks still happen in consensus, and still take time, so some of our reactions to their costs should still happen even if the crank gets rolled back. Like, the runPolicy should be told about computrons spent inside rolled-back cranks (we don't get more time for a block just because the vat did something weird and needs to forget the delivery).

Obviously that doesn't apply to the amount of dirt inside a vat: abandoning the external consequences of the delivery will also abandon the vat-internal changes, like an increase in the amount of dirt. So I agree it would be appropriate to *not* increment `reapDirt` in the case of an abandoned crank.

I wanted to avoid too much extra DB activity for every crank. We definitely need to write out the new dirt value, so it's persistent (and this triggers an `export-data` IAVL change, sigh). We almost certainly shouldn't *read* the dirt threshold each time, since it rarely changes (and only by `setSourceAndOptions`, which happens in its own non-delivery crank, which isn't subject to rollback since there's no vat).

I currently call `addDirt()` from two places (the generic one in `processDeliveryMessage`, and the `gcKrefs` -only one in `processGCMessage`), so if I remove the `reapDirt` cache and do a full DB read+increment+write cycle each time, I'm paying 2 or 4 DB queries per crank. If I can implement your other suggestion to pass `gcKrefs` into `deliveryCrankResults()`, then that is reduced to 2 per crank.

So I think I'll:
* merge gcKrefs into `deliveryCrankResults()`
* remove the RAM cache of `reapDirt`, doing 2 DB actions instead of 1 each delivery
* leave the `reapDirtThreshold` RAM cache

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 11 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/vatKeeper.js:204]: There's a duplicate coercion, yeah, I figured that was harmless.

This one was annoying, I first tried to make `gcKrefs` be a BigInt, to match how we handle computrons, but then I can't use simple JSON to store `reapDirt` or `reapDirtThreshold`, and holding it in RAM as a BigInt but converting back/forth to Number in the save/load functions was messy and distracting. Also, my choice to use `key is missing` as "no dirt of that category" made things slightly harder (the `|| 0` is to ignore `gcKrefs: undefined` -like cases).

And I didn't want to go back and change `computrons` to be Number everything, that was too much churn. I decided that I'd treat computrons as potentially large, and gcKrefs as always pretty small, and use that to justify leaving computrons as BigInts in the existing code. But then I ignore that argument in `addDirt` and do not tolerate large computron sizes. Sigh.

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 8 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/vatKeeper.js:224]: Agreed, I'll see if there's a way to factor out BOYD delivery to have just one place to call it from (we actually have three code paths: `processBringOutYourDead`, `processUpgradeVat` as the last thing sent to the old incarnation, and `maybeSaveSnapshot`). Ideally all three would call `processBringOutYourDead` but that wasn't trivial. I'll see what I can do, worst case I'll just add another `clearReapDirt()` call like you suggested.

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 11 above)
Comment (mhofman) [reply packages/SwingSet/src/kernel/state/vatKeeper.js:204]: Oh yeah `Number` is totally fine here for dirt computrons. Even if we go over the MAX_SAFE_INTEGER value, the loss of precision is deterministic and doesn't impact the threshold logic.

**Comment by warner** [comment]
> > We choose this value to allow the #8928 slow vat
> > termination process to trigger BOYD frequently enough to keep the BOYD
> > cranks small: since these will be happening constantly (in the
> > "background"), we don't want them to take more than 500ms or so. Given
> > the current size of the large vats that #8928 seeks to terminate, 10
> > krefs seems like a reasonable limit. And of course we don't want to
> > perform too many BOYDs, so `gcKrefs: 20` is about the smallest
> > threshold we'd want to use.
> 
> I am somewhat concerned that the cost of engine gc might mean 20 is too low. How do we validate we won't spend too much time in BOYD? Do we have an idea of what portion of the time spent in BOYD is related to the engine doing a gc mark and sweep, and how much of it is liveslots reacting to the found garbage? I assume liveslots usually has vatStore calls to make when garbage was found?

We certainly need to experiment on real data and tune this. The "`reapDirtThresholds.gcKrefs` -> work-per-BOYD" ratio is worst-case determined by how many objects/krefs are entrained by each #8401 Zoe/ExitObject cycle, and how much work (in particular how many syscalls) Zoe does in the resulting BOYD.

My notes/predictions are in https://github.com/Agoric/agoric-sdk/issues/8928#issuecomment-1962192341 . `gcKrefs: 20` and a cleanup budget of "5" ought to trigger one zoe BOYD every other empty block, which will do 500 syscalls, free 10 cycles, and take 500ms. It will take about a week to get through the cycle-breaking c-list deletions.

This might actually be too aggressive, but if so we can reduce the cleanup rate instead of reducing the `gcKrefs` threshold.

My worry about increasing `reapDirtThresholds.gcKrefs` is that it would make the BOYDs bigger (albeit less frequent). We're going to be triggering BOYDs constantly, every N blocks, and I'm worried that the slower validators/followers will fall behind. You're absolutely right that smaller+faster BOYD vs larger+slower is influenced by the non-kref-handling code, and so the "percentage of total time spent in a BOYD" equation is not independent of `gcKrefs`. My hunch is that it's dominated by the syscalls, rather than the engine GC, but I'll see if I can measure that.

Also, your question means I should measure the rate of non-cleanup-related `gcKrefs` going into a vat like zoe, and estimate what kind of BOYD rate we expect this to provoke, just in normal operation. Our baseline is one BOYD per 200 deliveries (triggered by heap snapshots), so if `reapDirtThresholds.gcKrefs` doesn't trigger BOYDs faster than that, we should be ok (since we'll make snapshot-triggered BOYDs reset the dirt counters, so they'll replace instead of adding).

> > External APIs continue to accept `reapInterval`, and now also accept `reapGCKrefs`.
> > 
> > * kernel config record
> >   
> >   * takes `config.defaultReapInterval` and `defaultReapGCKrefs`
> >   * takes `vat.NAME.creationOptions.reapInterval` and `.reapGCKrefs`
> > * `controller.changeKernelOptions()` still takes `defaultReapInterval`
> >   but now also accepts `defaultReapGCKrefs`
> 
> This does not sound scalable for adding new dirt thresholds. Why not add a `reapDirtThresholds` record in configs / options?

I started out doing it that way, but it triggered a lot of test churn, and made it hard to distinguish between "I'm setting a threshold and I don't care about property X, use your default", vs "I'm setting a threshold and I want property X to never trigger BOYD", mostly because I stuck with a type of `Number | undefined`, and could only get one meaning for the `undefined` case. In the future, when we add a new threshold type/property, we want to be backwards-compatible with the intentions of the old config, so missing properties need to mean "use your default", and I found it hard to do that when the thresholds were all glued together into a single argument record.

I'll take another look and see if there's a way to get a cleaner API, but I have to admit it's not my highest priority.

> > The kernel will automatically upgrade both the kernel-wide and the
> > per-vat state upon the first reboot with the new kernel code.
> 
> I'll need to look at this. It sounds like a sort of schema migration.

It is, for sure. I thought briefly about adding a `controller.upgradeKernelState()`, but I didn't like the DX of that:

* existing host apps which don't get the memo, and fail to add the upgrade call, would break
* to make them break cleanly, I'd need `buildKernel()` to check the kvStore for evidence of being out-of-date, and bail early if so (with an error pointing them at `upgradeKernelState`), so we don't charge ahead with bogus state
* creating the controller also starts the kernel, and a lot of schema upgrades we can imagine (for the future) will need to be done by that point, so it's kinda too late, which means it really wants a standalone function, kind of like `initializeSwingset()` (which takes a `kernelStorage` but doesn't use/create a controller or kernel), which would make the host app responsibility be like:

```js
import { makeSwingsetController, maybeUpgradeKernelState } from '@agoric/swingset-vat';
const { kernelStorage, hostStorage } = openSwingStore(..);
maybeUpgradeKernelState(kernelStorage);
hostStorage.commit();
const controller = makeSwingsetController(kernelStorage, ..);
..
```

We've had similar discussions in #8089, and I think you convinced me to make it explicit, where the host app must call a function (at the right time), and *not* have the library perform an automatic upgrade, but then export-data considerations [led us both](https://github.com/Agoric/agoric-sdk/issues/8089#issuecomment-1747776532) to give up on using an explicit call, and instead having upgrade be implicit during the `openSwingStore()` call.

I think we've got similar issues here: the reapDirt upgrades will cause kvStore changes, and export-data/IAVL changes, that need to be committed. The situation is better, though, because we already have the `kernelStorage` object, so we've got somewhere to hold the pending changes.

I'll try to think about how we could make this an explicit call.

> > as well as tracking a separate `snapshotDirt` counter (to trigger XS
> > heap snapshots, ala #6786).
> 
> ~I'm not sure I understand this. Is the idea to trigger snapshots every `n` BOYD? Snapshots should already force BYOD before snapshotting. The snapshotting process reveals gc to liveslots, which may have bugs revealing this out (#6784), so the idea has been to force a BOYD before each snapshot (#7504) but we expect BOYD to be more frequent than snapshots.~
> 
> Edit: I totally misunderstood `snapshortDirt`: it's not meant to trigger reap, or be related to `reapDirt`, just will likely use a similar accounting mechanism, with likely similar dirt input.

Right, we'd have `reapDirt` and `snapshotDirt` counters, compared against `reapDirtThreshold` and `snapshotDirtThreshold` respectively. We'd want snapshots to be driven mostly by `computrons` and partially by deliveries, and whereas we'd want BOYD to be mostly driven by memory/vref things rather than CPU-usage things, but both could use the same structure, just with different thresholds.

**Comment by warner** [comment]
I went to move the upgrade code into `startCrank` as suggested, and to write a test that the crankhash is updated to include the upgrade changes, and realized that this branch wouldn't work at all, because the kernelKeeper requires an up-to-date kvStore as soon as it is created, but the normal `kernel.start()` process creates the kernelKeeper before doing any cranks. My original unit test created a kernel in isolation, and the new test I was writing used `controller` instead, and it couldn't get past creating the kernel before it asserted.

I thought about our plans for swing-store schema migration (concluding by [this comment](https://github.com/Agoric/agoric-sdk/issues/8089#issuecomment-1747776532)), and the constraints therein, and how it applies to this upgrade step. We don't have the same "where do the export-data changes show up?" problem, since `makeSwingsetController()` *accepts* a swing-store (vs #8089 where `openSwingStore()` must *return* one). We still have the ergonomics question of "when does the DB get mutated?" and the corresponding host-app obligation to commit those changes (with `swingStore.hostStorage.commit()`) at an appropriate time.

Each kernel reboot uses some particular version of the `@agoric/swingset-vat` package (and likewise of the swing-store package). Each kernel "run" (the committed results of a `controller.run()`, plus whatever IO/device inputs arrived first) uses some version, and one of the host-app responsibilities is that this version never regresses: every run must use the a version that is the same or newer than the version used on the previous run. That means you can upgrade your kernel between reboots, and you are not allowed to revert it to an earlier version.

In a consensus system, each "block" (or whatever they call the coordinated units of work) is executed with some particular version of the kernel/swingstore. The host-app's responsbility is to ensure that each block is executed with the same version, across all workers. You must upgrade your kernel at the same time as everybody else, even though you're allowed to make non-upgrading reboots more frequently than that.

So, I think I see three options:

* A: add a standalone `upgradeSwingset(kernelStorage)` function, which looks for an explicit kvStore `version` key, makes upgrading changes if necessary, and always leaves it at `version = CURRENT` ("1" in our case). Then kernelKeeper can assert that `version` is as expected. In this option, `makeSwingsetController()` does not mutate the DB.
* B: add an `{ upgrade: true }` option to `makeSwingsetController()`, which tells it to perform an upgrade when it starts, and then have kernelKeeper assert the version as above. Then `makeSwingsetController()` *might* mutate, but only if you approve it.
* C: have `makeSwingsetController()` automatically upgrade, without an extra approval flag

I prefer being very explicit about when DB changes might happen, so I don't like C. And it feels odd to have `makeSwingsetController()` be a source of mutation: I expect `controller.run()` to mutate, and of course `initializeSwingset`, but not a function that claims to be merely creating a control surface. B would be a compromise, to make it very clear to the caller that they must commit any changes made by `makeSwingsetController()`, but it sticks out like a sore thumb.

So I'm going to pick A, where we have a separate `upgradeSwingset()` function that must be called before `makeSwingsetController()`. The simplest host-app behavior would be to call it every time, in every reboot, and rely upon the fact that it won't mutate anything if we're already up-to-date. Technically, if you knew exactly which reboots might have upgraded the kernel, you could refrain from calling it most of the time, but I don't think that would make anything simpler. Just in case, I'll have `upgradeSwingset()` return a boolean that says whether it actually changed anything, so host-apps could include an assertion like "hey, I wasn't following an upgrade plan, nothing should have changed, bail before I commit anything".

I'm also going to move to the explicit kvStore key that says what version the schema is, and graduate from [our "ad-hoc" phase](https://github.com/Agoric/agoric-sdk/pull/9169#discussion_r1592864450) . I need something for `makeSwingsetController()` (really `makeKernelKeeper()`) to assert against. The rule will be that (only) `upgradeSwingset()` is allowed to change this, and consistency between the `version` key and the rest of the data is both a pre-condition and a post-condition around that call, but we're allowed to have inconsistent data while in the middle of the call (i.e. just what you'd expect). I'll need to look at `initializeSwingset` and decide whether to create a v0 DB and immediately upgrade it (as is my plan with #8089), or to create a v1 DB right off the bat. It might be easier to write unit tests if there's a `createV0` function available.

And then I'll need to look at how cosmic-swingset calls this and make sure I'm not creating any problems. We'll already need to handle mutation (and thus export-data callbacks being invoked) with the #8089 changes, because the constraints *there* obligate us to perform upgrades as part of `openSwingStore()`, rather than using a separate upgrade function. But since #8089 isn't done yet, the cosmic-swingset code might not be ready for it. I *think* it won't require anything special, I'll add the call to `upgradeSwingset()` just before wherever we call `makeSwingsetController()`, with a note that this changes the DB, and that both the export-data callbacks (headed into IAVL) and the actual state changes will get committed as part of the first block after reboot. This should only actually change anything in the first block after a chain upgrade, which will be in-consensus.

Note that this means the upgrade changes won't be included in any crank, and they won't be included in a crankhash. (To be precise, they'll get hashed into the `crankhasher` created by `swingStore.js` when the swing-store is built, but they'll get cleared by the `startCrank()` that the kernel calls at the top of the first real crank, so they're effectively ignored). I think that's fine, we weren't expecting that #8089 swing-store upgrade changes (which might cause an IAVL change, even if just for the `version` key) would be included in a crank. We still get export-data/IAVL shadows of everything, so a buggy validator which upgrades at the wrong time will fall out of consensus right away, we just won't have a slogfile crank-hash value that explains why.

**Comment by mhofman** [comment]
> I _think_ it won't require anything special, I'll add the call to `upgradeSwingset()` just before wherever we call `makeSwingsetController()`

That sounds right. cosmic-swingset only builds the kernel as part of an init message, which is always done while processing a block at the cosmos level, so calls to the bridge are safe during that time.

> the upgrade changes won't be included in any crank, and they won't be included in a crankhash

This part is a little unfortunate, but I guess acceptable. If we ever change how we export the swing-store kv data, we'll likely still have data to validate it in IAVL. The unfortunate part is that right now we would have no way to detect this difference using the slog only, and exporting and comparing swing-store and iavl trees is difficult compared to comparing slog entries (e.g. from a flight recorder). Can we maybe add a new slog entry for upgrades, which maybe captures the crankHasher state at the end even if it doesn't end up chained like a normal crank?

**Comment by mhofman** [comment]
> > I _think_ it won't require anything special, I'll add the call to `upgradeSwingset()` just before wherever we call `makeSwingsetController()`
> 
> That sounds right. cosmic-swingset only builds the kernel as part of an init message, which is always done while processing a block at the cosmos level, so calls to the bridge are safe during that time.
> 
> > the upgrade changes won't be included in any crank, and they won't be included in a crankhash
> 
> This part is a little unfortunate, but I guess acceptable. If we ever change how we export the swing-store kv data, we'll likely still have data to validate it in IAVL. The unfortunate part is that right now we would have no way to detect this difference using the slog only, and exporting and comparing swing-store and iavl trees is difficult compared to comparing slog entries (e.g. from a flight recorder). Can we maybe add a new slog entry for upgrades, which maybe captures the crankHasher state at the end even if it doesn't end up chained like a normal crank?

**Comment by warner** [comment]
> Can we maybe add a new slog entry for upgrades, which maybe captures the crankHasher state at the end even if it doesn't end up chained like a normal crank?

Let's see, if I call `emitCrankHashes()` at the end of `upgradeSwingset()`, it will return the accumulated `crankhash`, which we could write to the slog. But it will also update `activityhash`, which will affect all subsequent activityhashes.

On one hand, that's good, it's a more explicit way for consensus to fail if one node diverges from the rest during `upgradeSwingset()`: the small changes they make to kvStore will get mirrored into IAVL and cause a divergence, but they'll also be captured by the activityhash (which itself is mirrored into IAVL, and will cause divergence), in addition to the non-IAVL-stored crankhash appearing in the slog.

On the other hand, it makes the act of calling `upgradeSwingset()` always mutating, even if the schema was up-to-date and no changes needed to be made. Which means we could not afford to call it on every reboot, because reboots are not supposed to be part of consensus. We'd need cosmic-swingset code to tell us whether we're running an upgrade plan (i.e. we're in the first reboot after a chain-halting upgrade event), and *only* call `upgradeSwingset()` on that one reboot-per-chain-upgrade.

I guess I could split `emitCrankHashes()` into two pieces. The first rotates and returns the crankhash, but doesn't mutate the DB. The second would accept a crankhash, and would update/store/return the activityhash. Normal cranks would call both, but `upgradeSwingset()` would only call the first.

I'm trying to think through how this interacts with the mutations caused by device inputs (eg pushing messages onto the run-queue). Those don't happen inside cranks, they happen before a `controller.run()`. They mutate the DB, which feeds the crankhasher, but the kernel calls `startCrank()` at the top of `run()`, which means their crankhash changes are thrown away before they can affect anything else, like the activityhash. I guess I'd assumed that pre-`run()` changes would get folded into the activityhash by the first crank, but I was wrong. Divergence would still be caught by the IAVL shadow, but we'd have the same "where did it diverge?" debugging problem that prompted @mhofman 's request (although, I think they *would* show up in the flight-recorder). I guess that's an argument for making "device input methods" more first-class (have device registration create functions that the host-app can safely call at arbitrary times, have the kernel schedule their actual invocation to avoid overlap with kernel execution), so we could wrap them in a `startCrank/`emitCrankHashes` pair and capture their mutations in an updated activityhash.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 7 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js:89]: Ok I overhauled the way upgrade happens, and now there *is* a `version` key that indicates how we're using the kvStore. There's an explicit `upgradeSwingset()` that must be called at least once per swingset-package-version -changing reboot (but is safe to call on every reboot), and it look for `version < 1` or a missing `version` to trigger the 0-to-1 upgrade.

Unlike my plans for swing-store SQL schemas, new kernels start out at version 1, partly because there are different kernel-wide options that influence the v1 behavior, which were missing at v0, so I'm not sure the final state would match what I want it to be.

I'll be pushing a new branch soon.

**Comment by warner** [comment]
I'm going to leave the crankhash/activityhash alone for now, I'm worried about accidentally introducing "how many times did we call `upgradeSwingset()`" non-determinism.

**Comment by warner** [comment]
One lingering concern I've got.. we have a kernel-wide default value, and vat-creation -time options that can override it, and we combine those two values at the moment we create the vat, and store the resulting per-vat threshold in `vNN.options`. This PR expands the nature of the value, but doesn't change that basic model. A consequence of the model is that changing multiple vats at the same time would require doing a `adminNode.changeVatOptions()` on every single vat. In particular I'm thinking about how tune `threshold.gcKrefs` after this gets deployed.

I'm wondering if there's a decent way to record "the creator of this vat didn't override anything" as a missing per-vat threshold property, and have the kernel merge in the kernel-wide default later, either as the `vatKeeper` is created (so basically once per worker page-in), or on every crank (safer but more expensive, although you're probably thinking it's a drop in the bucket compared to all the other DB reads we do on each crank and you're probably right).

That would change the upgrade process to look for *differences* between `vNN.reapInterval` and the kernel-wide `defaultReapInterval`, and only record `deliveries:` into `vNN.options` if they were different, otherwise omitting that property. For mainnet, every vat would have their `JSON.parse(`v${vatID}.options`).reapDirtThreshold` be `{}`, except for comms, which would get never/never/never.

Adding new kinds of dirt would only require a change to the kernel-wide `defaultReapDirtThreshold`, not something to walk all vats.

@mhofman thoughts?

**Comment by warner** [comment]
changed PR to draft for an hour while I try to implement that new thing

**Comment by warner** [comment]
@mhofman ok I updated the PR to minimize the per-vat recordkeeping: it only puts something in `vNN.options (.reapDirtThreshold)` if it needs to override the kernel-wide setttings. That mean that if we change the kernel-wide `gcKrefs` in the future, all vats will automatically start using the new value, which should help out a lot as we tune this thing.

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 10 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/vatKeeper.js]: Actually I removed all the caches. So on each crank, we do three reads: `vNN.reapDirt`, `kernel.reapDirtThreshold` (the kernel-wide defaults), and `vNN.options` (to get the per-vat overrides). Then we write the updated `vNN.reapDirt`, and occasionally do more if it's time to schedule a BOYD. I agree that this is safer, and the extra DB activity is probably minor compared to what it takes to actually perform the delivery.

**Comment by warner** [comment]
just updated it to slog the cleanup work (and when it's complete), and to rebase onto current trunk

**Comment by warner** [comment]
## Upgrade Considerations

NOTE: deployed kernels require explicit state upgrade, with:

```js
import { upgradeSwingset } from '@agoric/swingset-vat';
..
upgradeSwingset(kernelStorage);
```

This must be called after upgrading to the new kernel code/release,
and before calling buildVatController(). It is safe to call on every
reboot (it will only modify the swingstore when the kernel version has
changed). If changes are made, the host application is responsible for
commiting them, as well as recording any export-data updates (if the
host configured the swingstore with an export-data callback).

(we still need an integration PR which adds cosmic-swingset support; until that lands, pre-existing kernels, like mainnet, will crash at startup. I don't think we have any CI which exercises upgrade from old kernel state)

**Comment by warner** [comment]
I've updated the PR to include the necessary `upgradeSwingset()` call in cosmic-swingset (in its own commit). There's also a commit to make sure that we don't get export-data callbacks at a time that would cause problems (to guard against the problems we wrote up in #9655): @mhofman please take a look at those and confirm that I'm enabling/disabling the callback in all the right places, it passes the `cosmic-swingset` unit tests (and failed when I commented out the `enabled = true` lines), but I need extra eyes on it.

File: packages/SwingSet/src/controller/initializeKernel.js [hunk 12]
```diff
@@ -9,14 +9,32 @@ import { insistVatID } from '../lib/id.js';
...
 
+/*
+ * @param {SwingSetKernelConfig} config
+ * @param {SwingStoreKernelStorage} kernelStorage
+ * @param {*} [options]
+ * @returns {Promise<string | undefined>} KPID of the bootstrap message
+ *                                        result promise
+ */
+
 export async function initializeKernel(config, kernelStorage, options = {}) {
```
Comment (gibson042) [inline packages/SwingSet/src/controller/initializeKernel.js]: This isn't recognized as JSDoc unless it starts with `/**`.
```suggestion
/**
 * @param {SwingSetKernelConfig} config
 * @param {SwingStoreKernelStorage} kernelStorage
 * @param {object} [options]
 * @returns {Promise<string | undefined>} KPID of the bootstrap message result promise
 */
export async function initializeKernel(config, kernelStorage, options = {}) {
```

File: packages/SwingSet/src/controller/initializeKernel.js [hunk 13]
```diff
@@ -25,6 +43,9 @@ export async function initializeKernel(config, kernelStorage, options = {}) {
   const logStartup = verbose ? console.debug : () => 0;
   insistStorageAPI(kernelStorage.kvStore);
 
+  const CURRENT_VERSION = 1;
+  kernelStorage.kvStore.set('version', `${CURRENT_VERSION}`);
```
Comment (gibson042) [inline packages/SwingSet/src/controller/initializeKernel.js]: It feels wrong to modify kvStore contents before asserting that `kernelKeeper.getInitialized()` returns false, and for that matter it seems like there's some redundancy between "initialized" and "version" data. I can think of a few possible refactorings, but the one that appeals to me most is:
* Remove ```kernelStorage.kvStore.set('version', `${CURRENT_VERSION}`)``` here.
* Replace `kernelKeeper.setInitialized()` below with something like `kernelKeeper.setInitialized(CURRENT_VERSION)`.
* In kernel.js, update `setInitialized` accordingly (to take a version argument and write that to the kvStore, preferably at key "version" rather than "initialized").
  * If at key "version", then update `upgradeSwingset` accordingly (to migrate data from "initialized" to "version").
* Also in kernel.js, move the version check from `makeKernelKeeper` to `getInitialized`:
  ```js
  function getInitialized() {
    const version = kvStore.get('version');
    if (version !== `${EXPECTED_VERSION}`) {
      throw Error(
        `kernelStorage is too old (have version ${version}, need ${EXPECTED_VERSION}), please upgradeSwingset()`,
      );
    }
    return true;
  }
  ```
* Optionally, update kernel.js to check `getInitialized` right after `makeKernelKeeper(kernelStorage, kernelSlog)` (maintaining the early error introduced by the current state of this PR).
* Optionally, rename `setInitialized` to e.g. `setVersion` and/or `getInitialized` to e.g. `assertInitialized`.

File: packages/SwingSet/src/kernel/kernel.js [hunk 14]
```diff
@@ -264,6 +263,14 @@ export default function buildKernel(
     // check will report 'false'. That's fine, there's no state to
     // clean up.
     if (kernelKeeper.vatIsAlive(vatID)) {
+      // If there was no vat state, we can't make a vatKeeper to ask for
+      // options. For now, pretend the vat was non-critical. This will fail
+      // to panic the kernel for startVat failures in critical vats
+      // (#9157). The fix will add .critical to CrankResults, populated by a
+      // getOptions query in deliveryCrankResults() or copied from
+      // dynamicOptions in processCreateVat.
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/kernel.js:277]: This commentary seems like it would be more appropriate at the declaration of `critical` than at the point where we are looking up an accurate value.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 15]
```diff
@@ -1288,15 +1357,17 @@ export default function makeKernelKeeper(kernelStorage, kernelSlog) {
...
   function provideVatKeeper(vatID) {
     insistVatID(vatID);
     const found = ephemeral.vatKeepers.get(vatID);
     if (found !== undefined) {
       return found;
     }
-    if (!kvStore.has(`${vatID}.o.nextID`)) {
-      initializeVatState(kvStore, transcriptStore, vatID);
-    }
+    assert(kvStore.has(`${vatID}.o.nextID`), `${vatID} was not initialized`);
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:1389]: Style nit:
```suggestion
    kvStore.has(`${vatID}.o.nextID`) || Fail`${vatID} was not initialized`;
```

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 16]
```diff
@@ -32,18 +34,42 @@ const FIRST_OBJECT_ID = 50n;
...
 /**
  * Establish a vat's state.
  *
  * @param {*} kvStore  The key-value store in which the persistent state will be kept
  * @param {*} transcriptStore  Accompanying transcript store
  * @param {string} vatID The vat ID string of the vat in question
  * TODO: consider making this part of makeVatKeeper
+ * @param {SourceOfBundle} source
+ * @param {RecordedVatOptions} options
  */
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/vatKeeper.js]: This TODO doesn't belong in between parameter definitions, and should probably just be deleted—but if not, then moved up:
```suggestion
/**
 * Establish a vat's state.
 * TODO: consider making this part of makeVatKeeper
 *
 * @param {*} kvStore  The key-value store in which the persistent state will be kept
 * @param {*} transcriptStore  Accompanying transcript store
 * @param {string} vatID The vat ID string of the vat in question
 * @param {SourceOfBundle} source
 * @param {RecordedVatOptions} options
 */
```

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 17]
```diff
@@ -32,18 +34,42 @@ const FIRST_OBJECT_ID = 50n;
...
+  transcriptStore,
+  vatID,
+  source,
+  options,
+) {
+  assert(source);
+  assert('bundle' in source || 'bundleName' in source || 'bundleID' in source);
+  assert(options);
+  assert.typeof(options, 'object');
+  assert(options.workerOptions, `vat ${vatID} options missing workerOptions`);
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/vatKeeper.js]: Are `source` and `options` hardened, or can they be? If so, we can cover this with `@endo/patterns` and take advantage of upcoming improvements there.
```suggestion
  mustMatch(source, bundleSourceShape, assert.details`vat ${vatID} source`);
  mustMatch(options, vatOptionsShape, assert.details`vat ${vatID} options`);
```
with
```js
import { M, mustMatch } from '@endo/patterns';

const bigStringShape = M.string({ stringLengthLimit: Number.MAX_SAFE_INTEGER });

const bundleShape = M.or(
  {
    moduleFormat: 'endoZipBase64',
    endoZipBase64: bigStringShape,
    endoZipBase64Sha512: M.string(),
  },
  M.splitRecord(
    { moduleFormat: 'getExport', source: bigStringShape },
    { sourceMap: bigStringShape },
  ),
  M.splitRecord(
    { moduleFormat: 'nestedEvaluate', source: bigStringShape },
    { sourceMap: bigStringShape },
  ),
);
const bundleSourceShape = M.or(
  { bundleName: M.string() },
  { bundle: bundleShape },
  { bundleID: M.string() },
);

const vatOptionsShape = harden({
  name: M.string(),
  vatParameters: M.record(),
  enableSetup: M.boolean(),
  enablePipelining: M.boolean(),
  useTranscript: M.boolean(),
  reapDirtThreshold: M.splitRecord({}, {
    deliveries: M.or(M.number(), 'never'),
    gcKrefs: M.or(M.number(), 'never'),
    computrons: M.or(M.number(), 'never'),
    never: M.boolean(),
  }),
  critical: M.boolean(),
  meterID: M.or(M.string(), M.undefined()),
  workerOptions: M.or(
    { type: 'local' },
    { type: 'xsnap', bundleIDs: M.arrayOf(M.string()) },
    M.splitRecord({ type: 'node-subprocess' }, { nodeOptions: M.arrayOf(M.string()) }),
  ),
  enableDisavow: M.boolean(),
});
```

or failing that, still simplify and provide better error messages:
```suggestion
  isBundleSource(source) ||
    Fail`vat ${vatID} source ${source} does not have the right shape`;
  (isObject(options) && isObject(options.workerOptions)) ||
    Fail`vat ${vatID} options ${options} is missing workerOptions`;
```
with
```js
import { isObject } from '@endo/marshal';

const isBundleSource = source => {
  return (
    isObject(source) &&
    (isObject(source.bundle) ||
      typeof source.bundleName === 'string' ||
      typeof source.bundleID === 'string')
  );
};
```

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 18]
```diff
@@ -32,18 +34,42 @@ const FIRST_OBJECT_ID = 50n;
...
+
   kvStore.set(`${vatID}.o.nextID`, `${FIRST_OBJECT_ID}`);
   kvStore.set(`${vatID}.p.nextID`, `${FIRST_PROMISE_ID}`);
   kvStore.set(`${vatID}.d.nextID`, `${FIRST_DEVICE_ID}`);
+  kvStore.set(`${vatID}.reapDirt`, JSON.stringify({}));
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/vatKeeper.js:79]: The name of this key strikes me as less than clear. I think instead of "reapDirt", "dirtiness" or just "dirt" would read a bit better.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 19]
```diff
@@ -182,6 +241,16 @@ export default function makeKernelKeeper(kernelStorage, kernelSlog) {
...
 
+  if (
+    !kvStore.has('version') ||
+    Number(getRequired('version')) !== EXPECTED_VERSION
+  ) {
+    const have = kvStore.get('version') || 'undefined';
+    throw Error(
+      `kernelStorage is too old (have ${have}, need ${EXPECTED_VERSION}), please upgradeSwingset()`,
+    );
+  }
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: More robustly:
```suggestion
  const version = kvStore.get('version');
  if (version !== `${EXPECTED_VERSION}`) {
    throw Error(
      `kernelStorage is too old (have ${version}, need ${EXPECTED_VERSION}), please upgradeSwingset()`,
    );
  }
```

File: packages/SwingSet/src/types-internal.js [hunk 20]
```diff
@@ -35,11 +48,48 @@ export {};
...
+/**
+ * Each counter in Dirt matches a threshold in
+ * ReapDirtThreshold. Missing values are treated as zero, so vats
+ * start with {} and accumulate dirt as deliveries are made, until a
+ * BOYD clears them.
+ *
+ * @typedef { object } Dirt
+ * @property { number } [deliveries]
+ * @property { number } [gcKrefs]
+ * @property { number } [computrons]
```
Comment (gibson042) [inline packages/SwingSet/src/types-internal.js]: "gcKrefs" reads to me like a verb. Suggestion:
```suggestion
 * @typedef { object } Dirt
 * @property { number } [deliveries]
 * @property { number } [downgradedKrefs]
 * @property { number } [computrons]
```
(or similar)

Or perhaps better, identify all the properties as counts:
```suggestion
 * @typedef { object } Dirt
 * @property { number } [deliveryCount]
 * @property { number } [krefCount]
 * @property { number } [computronCount]
```

File: packages/SwingSet/src/controller/upgradeSwingset.js [hunk 21]
```diff
@@ -0,0 +1,193 @@
...
+  }
+  kvStore.delete(oldReapIntervalKey);
+  kvStore.delete(oldReapCountdownKey);
+  kvStore.set(reapDirtKey, JSON.stringify(reapDirt));
+
+  // remove .reapInterval from options, replace with .reapDirtThreshold
+  const options = JSON.parse(kvStore.get(vatOptionsKey));
+  delete options.reapInterval;
+  options.reapDirtThreshold = threshold;
+  kvStore.set(vatOptionsKey, JSON.stringify(options));
```
Comment (gibson042) [inline packages/SwingSet/src/controller/upgradeSwingset.js]: Suggested refactoring:
```suggestion
  const reapIntervalString = kvStore.get(oldReapIntervalKey);
  const reapCountdownString = kvStore.get(oldReapCountdownKey);
  const reapDirtString = kvStore.get(reapDirtKey);

  reapIntervalString !== undefined || assert.Fail`${oldReapIntervalKey} is undefined`;
  reapCountdownString !== undefined || assert.Fail`${oldReapCountdownKey} is undefined`;
  reapDirtString === undefined ||
    assert.Fail`${reapDirtKey}=${reapDirtString} should not be present already`;

  const intervalIsNever = reapIntervalString === 'never';
  const countdownIsNever = reapCountdownString === 'never';
  intervalIsNever === countdownIsNever ||
    assert.Fail`${vatID} reapInterval=${reapIntervalString} should match reapCountdown=${reapCountdownString}`;

  // Initialize or upgrade state.
  const reapDirt = {}; // all missing keys are treated as zero
  const threshold = {};

  if (intervalIsNever) {
    // Old vats that were never reaped (eg comms) used
    // reapInterval='never', so respect that and set the other
    // threshold values to 'never' as well.
    threshold.never = true;
  } else {
    // Deduce delivery count from old countdown values.
    const reapInterval = Number.parseInt(reapIntervalString, 10);
    const reapCountdown = Number.parseInt(reapCountdownString, 10);
    const deliveries = reapInterval - reapCountdown;
    deliveries >= 0 ||
      assert.Fail`${vatID} reapCountdown=${reapCountdown} should not exceed reapInterval=${reapInterval}`;
    reapDirt.deliveries = deliveries;
    if (reapInterval !== defaultReapDirtThreshold.deliveries) {
      threshold.deliveries = reapInterval;
    }
  }

  kvStore.delete(oldReapIntervalKey);
  kvStore.delete(oldReapCountdownKey);
  kvStore.set(reapDirtKey, JSON.stringify(reapDirt));

  // Update options to use the new schema.
  const options = JSON.parse(kvStore.get(vatOptionsKey));
  delete options.reapInterval;
  options.reapDirtThreshold = threshold;
  kvStore.set(vatOptionsKey, JSON.stringify(options));
```

File: packages/SwingSet/src/kernel/kernel.js [hunk 22]
```diff
@@ -375,7 +383,7 @@ export default function buildKernel(
    *    didDelivery?: VatID, // we made a delivery to a vat, for run policy and save-snapshot
    *    computrons?: BigInt, // computron count for run policy
    *    meterID?: string, // deduct those computrons from a meter
-   *    decrementReapCount?: { vatID: VatID }, // the reap counter should decrement
+   *    measureDirt?: { vatID: VatID, dirt: Dirt }, // the dirt counter should increment
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/kernel.js]:
```suggestion
   *    measureDirt?: { vatID: VatID, dirt: Dirt }, // dirt counter(s) should increment
```

File: packages/SwingSet/src/kernel/kernel.js [hunk 23]
```diff
@@ -1733,14 +1778,38 @@ export default function buildKernel(
...
       for (const option of Object.getOwnPropertyNames(options)) {
         const value = options[option];
         switch (option) {
           case 'defaultReapInterval': {
-            kernelKeeper.setDefaultReapInterval(value);
+            if (typeof value === 'number') {
+              assert(value > 0, `defaultReapInterval = ${value}`);
+            } else {
+              assert.equal(value, 'never', `defaultReapInterval = ${value}`);
+            }
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/kernel.js]:
```suggestion
            (typeof value === 'number' && value > 0) ||
              value === 'never' ||
              Fail`defaultReapInterval ${value} must be a positive number or "never"`;
```

File: packages/SwingSet/src/kernel/kernel.js [hunk 24]
```diff
@@ -1733,14 +1778,38 @@ export default function buildKernel(
...
+              deliveries: value,
+            });
+            break;
+          }
+          case 'defaultReapGCKrefs': {
+            if (typeof value === 'number') {
+              assert(value > 0, `defaultReapGCKrefs = ${value}`);
+            } else {
+              assert.equal(value, 'never', `defaultReapGCKrefs = ${value}`);
+            }
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/kernel.js]:
```suggestion
            (typeof value === 'number' && value > 0) ||
              value === 'never' ||
              Fail`defaultReapGCKrefs ${value} must be a positive number or "never"`;
```

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 25]
```diff
@@ -52,8 +60,9 @@ const enableKernelGC = true;
 // allowed to vary between instances in a consensus machine. Everything else
 // is required to be deterministic.
 //
-// The schema is:
+// The current ("v1") schema is:
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]:
```suggestion
// The schema is indicated by the value of the "version" key, which was added
// for version 1 (i.e., version 0 had no such key).
// Version 1 also added keys "kernel.defaultReapDirtThreshold" and
// "v$NN.reapDirt", dropped keys "kernel.defaultReapInterval",
// "v$NN.reapInterval",  and "v$NN.reapCountdown", and updated the schema for
// values of "v$NN.options" keys.

// As of version 1, known keys and values are:
```

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 26]
```diff
@@ -145,6 +173,20 @@ function insistMeterID(m) {
   Nat(BigInt(m.slice(1)));
 }
 
+export const getAllStaticVats = kvStore => {
+  const result = [];
+  for (const k of enumeratePrefixedKeys(kvStore, 'vat.name.')) {
+    const name = k.slice(9);
+    const vatID = kvStore.get(k) || Fail`getNextKey ensures get`;
+    result.push([name, vatID]);
+  }
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: Eliminating a magic number:
```suggestion
  const prefix = 'vat.name.';
  for (const k of enumeratePrefixedKeys(kvStore, prefix)) {
    const vatID = kvStore.get(k) || Fail`getNextKey ensures get`;
    const name = k.slice(prefix.length);
    result.push([name, vatID]);
  }
```

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 27]
```diff
@@ -352,21 +429,26 @@ export default function makeKernelKeeper(kernelStorage, kernelSlog) {
 
   /**
    *
-   * @returns {number | 'never'}
+   * @returns { ReapDirtThreshold }
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]: I hate that we're inconsistent about presence vs. absence of whitespace inside JSDoc braces, but we currently are so no further comment here.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 28]
```diff
@@ -352,21 +429,26 @@ export default function makeKernelKeeper(kernelStorage, kernelSlog) {
...
+   */
+  function setDefaultReapDirtThreshold(threshold) {
+    assert.typeof(threshold, 'object');
+    assert(threshold);
+    for (const [key, value] of Object.entries(threshold)) {
+      if (typeof value === 'number') {
+        assert(value > 0, `threshold[${key}] = ${value}`);
+      } else {
+        assert.equal(value, 'never', `threshold[${key}] = ${value}`);
+      }
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js]:
```suggestion
      (typeof value === 'number' && value > 0) ||
        value === 'never' ||
        Fail`threshold[${assert.quote(key)}] ${value} must be a positive number or "never"`;
```

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 29]
```diff
@@ -125,45 +160,80 @@ export function makeVatKeeper(
...
+   *
+   * @param {Dirt} moreDirt
+   */
+  function addDirt(moreDirt) {
+    const reapDirt = JSON.parse(getRequired(reapDirtKey));
+    const thresholds = {
+      ...JSON.parse(getRequired(DEFAULT_REAP_DIRT_THRESHOLD_KEY)),
+      ...JSON.parse(getRequired(`${vatID}.options`)).reapDirtThreshold,
+    };
+    assert.typeof(moreDirt, 'object');
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/vatKeeper.js]: Maybe validate the argument first?
```suggestion
    assert.typeof(moreDirt, 'object');
    const reapDirt = JSON.parse(getRequired(reapDirtKey));
    const thresholds = {
      ...JSON.parse(getRequired(DEFAULT_REAP_DIRT_THRESHOLD_KEY)),
      ...JSON.parse(getRequired(`${vatID}.options`)).reapDirtThreshold,
    };
```

**Review by gibson042 — APPROVED** [review]
I was going to ask about the interaction of various dirt-driven BOYDs, but I think this approach of allowing each metric to independently prompt them makes sense.

No blockers, but a large handful of æsthetic suggestions. Also, thanks for the thorough testing.

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 1 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/vatKeeper.js]: I changed the order of asserts, but didn't find a decent way to factor out the assertions. I'll leave that for a later cleanup.

File: packages/SwingSet/src/kernel/kernel.js (hunk 4 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js]: done

File: packages/SwingSet/src/controller/initializeKernel.js (hunk 12 above)
Comment (warner) [reply packages/SwingSet/src/controller/initializeKernel.js]: fixed, which of course brought a bunch of code under typechecks that had previously escaped it..

File: packages/SwingSet/src/controller/initializeKernel.js (hunk 13 above)
Comment (warner) [reply packages/SwingSet/src/controller/initializeKernel.js]: Yeah, that sounds like the best plan. I'm not jazzed about the idea of `makeKernelKeeper()` returning an API surface for the wrong data (e.g. if `kernel.js` forgot to make the `getInitialized`/`assertInitialized`/`assertVersion` check, and started using a non-upgraded DB), but the real problem is that that we need a kernelKeeper to populate the initial state, which of course happens before the DB initialized.

Hm, what about `makeKernelKeeper(expectedVersion)` ? We'd use `undefined` for the initial construction, then the normal `kernel.js` usage would pass in `CURRENT_VERSION` or whatever. Oh, and what if we used `'uninitialized'` instead of `undefined`? That would make it impossible to call `makeKernelKeeper()`, and you'd have to be explicit about whether you're making one for initialization purposes, or for actual use?

Hm, now *that* makes me wonder if `upgradeSwingset` could go back to being a method of `kernelKeeper`, as I first tried. If we went that way, `upgradeSwingset()` would be like `makeKernelKeeper(..).upgrade()` .. hm, no, we wouldn't know what version to expect (it could be either 0 or 1, but shouldn't be missing entirely / uninitialized).

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 18 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/vatKeeper.js:79]: I put `reap` in there to make room for a second set of counters to drive the creation of heap snapshots, where computrons would be the most important thing to track. So it's "the reap kind of dirt", vs "the snapshot kind of dirt". That said, any improved phrasing which still captures the two concepts is welcome.

File: packages/SwingSet/src/kernel/kernel.js (hunk 23 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js]: Sorry, that doesn't scan as well for me.. I've resisted our pattern of `goodthing || Fail` in favor of a more English-like `if (badthing) { Fail }` or better yet `assert(goodthing)`. It's harder when the conditional is more complex like this one. Here are several different options (wrapped to the original's column-offset, which imposes an additional brevity/legibility constraint):

```js
            if (
              (typeof value === 'number' && value <= 0) ||
              value !== 'never'
            ) {
              Fail`defaultReapInterval ${value} must be a positive number or "never"`;
            }
            
            if (
              !((typeof value === 'number' && value > 0) || value === 'never')
            ) {
              Fail`defaultReapInterval ${value} must be a positive number or "never"`;
            }
            
            (typeof value === 'number' && value > 0) ||
              value === 'never' ||
              Fail`defaultReapInterval ${value} must be a positive number or "never"`;
              
            if (typeof value === 'number') {
              assert(value > 0, `defaultReapInterval = ${value}`);
            } else {
              assert.equal(value, 'never', `defaultReapInterval = ${value}`);
            }
            
            assert(
              (typeof value === 'number' && value > 0) || value === 'never',
              `defaultReapInterval ${value} must be a positive number or "never"`,
            );
```

I'm not sure why I find it harder to read the `goodthing || Fail` pattern than everyone else here. I think maybe it's a garden-path thing, where I have to read all the way to the end of the sequence to discover the Fail that inverts the logic.. I start out reading `foo || bar && baz || Fail` as "if foo.. or bar, ok, and this baz thing, then we fail? no, wait, we fail if *not* foo, ok then how does baz affect that?" etc. I've got no problem with `assert(goodthing)`, the outcome I'm looking for is announced up front.

Of all those options, I think I'll go with the last one, the (goodthing) pattern reads well, it comes out one line shorter than the original (although one line longer than your suggestion), and it avoids duplicating the message.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 25 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: We've got the 0->1 delta information at the end of the table too.. which side do you think is better? We probably don't need to list it twice.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 19 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: rewrote this part differently, please take a look at the new version (once I push it up)

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 27 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: which do you prefer?

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 28 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: I'll follow the previous pattern

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 16 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/vatKeeper.js]: yeah, I'll delete it, I no longer think that would be a good idea anyways

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 17 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/vatKeeper.js]: Yeah.. that first option doesn't *look* like a simplification.. lotta lines there :). And that shape is already being expressed in typescript, I'm not sure I want to duplicate the form. The runtime check was mostly just to catch some API changes (adding a new argument) that tripped me up a  few years ago.

I'm happy to go with the second one, although with an assert instead of `goodthing || Fail`, for my idiosyncratic reasons listed above.

File: packages/SwingSet/src/types-internal.js (hunk 20 above)
Comment (warner) [reply packages/SwingSet/src/types-internal.js]: Hm, that *does* read better, although a bit more verbose. I do need to maintain the "GC" -ness of the count, though: a plain `krefCount` could mean how many krefs we send into a vat, which is an entirely different (and completely plausible) thing that we might want to trigger a BOYD.

I'll try `deliveryCount` / `gcKrefCount` / `computronCount` and see how it reads.

File: packages/SwingSet/src/controller/initializeKernel.js (hunk 13 above)
Comment (warner) [reply packages/SwingSet/src/controller/initializeKernel.js]: Ok I went with `makeKernelKeeper(expectedVersion)`, and I like how it flows. `kernelKeeper.js` exports the current version, so the kernel demands it, and won't get back an API that's using wrong-version data. And there's a way for `initializeKernel` to demand an uninitialized one. The host app doesn't create the kernelKeeper, so it doesn't need to know anything about versions, it just calls `upgradeSwingset` (either every boot, or every boot after the operator/host-app-author knows they've changed the kernel code).

File: packages/SwingSet/src/controller/upgradeSwingset.js (hunk 21 above)
Comment (warner) [reply packages/SwingSet/src/controller/upgradeSwingset.js]: adopted a modified version, with more `assert` than `Fail`

File: packages/SwingSet/src/kernel/kernel.js (hunk 14 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js:277]: yeah, I guess, but that's only a few lines earlier, so anyone looking there will also see the comment here.. I'm going to leave it as is for now

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 25 above)
Comment (warner) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: ok I'm going to stick with the deltas at the end, I like the format better.

**Comment by warner** [comment]
I've pushed the feedback changes. I'll squash these into better shape before landing. @mhofman if you get time to look, the first four commits are organized/review-separately, the remainder are haphazard and not worth looking at separately.

File: packages/SwingSet/src/kernel/state/kernelKeeper.js (hunk 27 above)
Comment (gibson042) [reply packages/SwingSet/src/kernel/state/kernelKeeper.js]: I don't have a strong opinion, but in terms of internal consistency it looks like "no spaces" wins by a lot so I guess that's the way to go:
```console
$ git grep '[*].*@[a-z].*[{].*[}]' packages/ \
  | grep -vE '@(import|see|link)' \
  | awk '{
    # Reduce $0 to `{…}`.
    gsub(/^[^*]*[*][^@]*@[a-z][^{]*|[^}]*$/, "");
    # Find the span [i, j) inside the wrapping braces and any adjacent spaces.
    i = match($0, /^[{] */) + RLENGTH;
    j = match($0, / *[}]$/);
    # 
    print substr($0, 1, i - 1) "..." substr($0, j, RLENGTH);
  }' \
  | sort \
  | uniq -c
    361 { ... }
     73 { ...}
     66 {... }
  10857 {...}
```

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 18 above)
Comment (gibson042) [reply packages/SwingSet/src/kernel/state/vatKeeper.js:79]: Hmm, maybe "reapDirtiness" or "gcDirtiness"?

File: packages/SwingSet/src/kernel/state/vatKeeper.js (hunk 17 above)
Comment (gibson042) [reply packages/SwingSet/src/kernel/state/vatKeeper.js]: > that first option doesn't _look_ like a simplification.. lotta lines there :)

Yes, but half of them belong in endo.

> that shape is already being expressed in typescript, I'm not sure I want to duplicate the form.

A very fair point... I think we're making progress on mechanical derivation, but AFAIK we aren't there yet.

> I'm happy to go with the second one, although with an assert instead of `goodthing || Fail`, for my idiosyncratic reasons listed above.

:+1:
