### PR TITLE
fix(vat-bank): getPurse race

### LINKED ISSUE #7844: Ollinet: Auction bidder did not receive ATOM; bid shows error in logs
## Describe the bug
Ran happy path scenario in Ollinet
The by-price bid was correctly picked up and handled by the auction, but did not transfer ATOM proceeds to the user

We also see an error associated with bids related to the one at issue when we examine bids from IAVL tree: 
string"Error: key (a string) already registered in collection "addressToUpdater""

## Additional Details
All three bids showed as well formed when listed prior to run.  All bids placed by a test account.
```
agoric-cli git:(dc-oracle-setPrice) bin/agops inter bid list --from test-acct
{"id":"bid-1685075828626","discount":10,"give":{"Bid":"80 IST"},"maxBuy":"1000000 ATOM","result":"Your bid has been accepted"}
{"id":"bid-1685075847435","price":"9 IST/ATOM","give":{"Bid":"90 IST"},"maxBuy":"1000000 ATOM","result":"Your bid has been accepted"}
{"id":"bid-1685075866382","discount":15,"give":{"Bid":"150 IST"},"maxBuy":"1000000 ATOM","result":"Your bid has been accepted"}
```

The expected ATOM filled to each bid should have been:
8.897786676 (Discount 10, IST 80)
10.01001001 (Price 9, IST 90)
16.43290349 (Discount 15, IST 150) (partial fill)

Bids 1 and 3 exited correctly for the user.  Bid 2 did not.

User purse balance for ATOM is 25.330689
It should be ~35.34
Delta is the expected ATOM from the errored bid.  10.01001001

The auction proceeded as if it had sold to all bids accurately.

## To Reproduce
Run Happy Path scenario in ollinet

## Platform Environment
Ollinet-81 
Hash: ea8c1c64911b4c58fb43635b25e17e3d50d0cf2a

### PR DESCRIPTION
**Pull request by turadg**
closes: #7844

## Description

The `getPurse` method in vat-bank had a race condition. This was observed in https://github.com/Agoric/agoric-sdk/pull/7804/ but first hypothesized as an artifact of testing. In further discussion with @michaelfig we determined this may be a real race handling error that hadn't yet been exercised in tests. (While the bank has coverage of multiple getPurse calls, none were with remote vats that had real latency).

Meanwhile, the same evening testing in Ollinet showed this race in a running chain,
- https://github.com/Agoric/agoric-sdk/issues/7844

This fixes the race condition by using the AtomicProvider. That utility assumes responsibility for the durable storage, and in this case the Exo is responsible for the durable storage. Since the provider has to be on the heap (in the prepare) this uses the provider to produce the value, and in the finish() it moves the value from the provider's store to the Exo's.

### Security Considerations

Reduces potential to exploit timing.

### Scaling Considerations

The pending purses require a new durable store that holds objects temporarily. To reduce IO, the store it uses could be an in-memory store or a new utility created that only manages the "pending" map and doesn't try to store durably. 

### Documentation Considerations

--

### Testing Considerations

In master we don't have test coverage for this race behavior. https://github.com/Agoric/agoric-sdk/pull/7804/ adds test-liquidation which fails before this change and passes after. I propose that we get this PR in first and once 7804 is landed it will serve as the regression test.

### CODE REVIEW

**Review by dckc — APPROVED** [review]
I think I get it.

ideally some of the explanation would be in code comments, but I don't think that would have substituted for discussion entirely

File: packages/vats/src/vat-bank.js [hunk 1]
```diff
@@ -451,54 +457,53 @@ const prepareBank = (
...
-          // Just emulate with a real purse.
-          return keepPurse(E(assetRecord.issuer).makeEmptyPurse());
-        }
-
-        const addressToUpdater = denomToAddressUpdater.get(assetRecord.denom);
-
-        /** @type {PublishKit<Amount>} */
-        const { publisher, subscriber } = makePublishKit();
-        const balanceUpdater = makeBalanceUpdater(brand, publisher);
+        const providerKey = `${address}:${assetRecord.denom}`;
```
Comment (michaelfig) [inline packages/vats/src/vat-bank.js]:
```suggestion
        // Create a composite key that doesn't rely on the contents of the address and denom strings.
        const providerKey = JSON.stringify([address, assetRecord.denom])`;
```

File: packages/vats/src/vat-bank.js [hunk 2]
```diff
@@ -404,6 +405,10 @@ const prepareBank = (
   const makeBalanceUpdater = prepareBalanceUpdater(zone);
   const makeBankPurseController = prepareBankPurseController(zone);
 
+  const addressDenomToPurse = zone.mapStore('addressDenomToPurse');
```
Comment (michaelfig) [inline packages/vats/src/vat-bank.js:412]:
```suggestion
  // Using a purseProvider singleton requires a single map with composite keys (which we emulate, since
  // we know both address and denom are JSONable).  If we decide to partition the provider and use
  // brandToVPurse directly, we'd need ephemera for each `makeBank` call.
  const addressDenomToPurse = zone.mapStore('addressDenomToPurse');
```

**Review by michaelfig — APPROVED** [review]
LGTM!  I'd just like to see the one weird JSON composite key trick also suggested by @dckc.
