### PR TITLE
fix(async-flow): panic if a guest fulfills during replay

### LINKED ISSUE #9465: replay of async flow doesn't panic on early completion
## Describe the bug

The replay of a suspended flow that completes early, aka for which the guest outcome promise settles (fulfilment or rejection) before reaching the end of the recorded replay log, results in a completion of the flow and transition into the done state. This is particularly bad for a guest which somehow errors on replay without panicking the flow first.

## To Reproduce
Add the following test to `async-flow.test.js` after `testFirstPlay`.

```js
/**
 * @param {any} t
 * @param {Zone} zone
 */
const testBadShortReplay = async (t, zone) => {
  t.log('badShortReplay started');
  const vowTools = prepareVowTools(zone);
  const { asyncFlow, adminAsyncFlow } = prepareAsyncFlowTools(zone, {
    vowTools,
  });
  prepareOrchestra(zone);
  const { when } = vowTools;

  // purposely violate rule that guestMethod is closed.
  const { promise: promiseStep, resolve: resolveStep } = makePromiseKit();

  const { guestMethod } = {
    async guestMethod(gOrch7, g1, _p3) {
      t.log('  badReplay return early');
      resolveStep(true);
      return 'bad';
    },
  };

  // `asyncFlow` can be used simply to re-prepare the guest function
  // by ignoring the returned wrapper function. If the wrapper function is
  // invoked, that would be a *new* activation with a new outcome and
  // flow, and would have nothing to do with the existing one.
  asyncFlow(zone, 'AsyncFlow1', guestMethod);

  const outcomeV = /** @type {Vow} */ (
    zone.makeOnce('outcomeV', () => Fail`need outcomeV`)
  );
  const flow = /** @type {AsyncFlow} */ (
    zone.makeOnce('flow', () => Fail`need flow`)
  );
  const flow1 = adminAsyncFlow.getFlowForOutcomeVow(outcomeV);
  t.is(flow, flow1);
  t.is(passStyleOf(flow), 'remotable');

  await promiseStep;

  const replayProblem = flow.getOptFatalProblem();
  t.log('  badShortReplay failures', replayProblem);
  t.true(replayProblem instanceof Error);

  const outcome = when(outcomeV);
  await eventLoopIteration();

  t.is(await Promise.race([outcome, Promise.resolve('good')]), 'good');

  t.deepEqual(
    adminAsyncFlow.getFailures(),
    makeCopyMap([[flow, replayProblem]]),
  );

  t.log('badShortReplay done');
};
```

## Expected behavior
Skipping the replay should result in a panic of the flow. When handling the settlement of the outcome vow, the handler should check if the flow is still replaying or not first before settling the outcome vow.

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

```
    ℹ badShortReplay started
    ℹ   badReplay return early
    ℹ   badShortReplay failures undefined
    ℹ badShortReplay done
```

### LINKED ISSUE #10148: async-flow transitioning to Failed should provide diagnostics
## What is the Problem Being Solved?

When an error happens on the guest side of the membrane, including failures of async-flow itself, but more commonly when the guest fails to replay, or passes an unexpected argument to a call, the flow panics and transitions into a Failed state. That state is often recoverable with an upgrade by changing the guest behavior to no longer trigger the fault. Because of that, the result vow is not rejected when a flow gets into a failed state.

While the panic throws the failure error into the guest to prevent its forward progress, the guest result handling logic will currently absorb that error because the bijection was reset, and the error will go unreported.

The host can use the async-flow admin facet to query failures (`getFailures()`), but that requires an explicit check.

We would like to instead report these errors to the console, or possibly handle them (e.g. in tests cause a failure of the test).

An example of a test that silently failed (for lack of progress) without any diagnostics: https://github.com/Agoric/agoric-sdk/actions/runs/11018434693/job/30598843847?pr=10140

## Description of the Design

A callback/handler provided when preparing async flow to either report panics directly, or errors reaching the guest result promise when the bijection is no longer valid. If not provided, the error would be reported as an unhandled rejection.

## Security Considerations

The handler should not be able to interfere with the flow's state. This would likely be a per flowTools power (see #9375)

## Scaling Considerations

None

## Test Plan

Replication of the test that silently failed above (guest tried to pass a non passable function through the membrane), with failure of test attributed to async-flow panic.

## Upgrade Considerations

Adding an optional API to the async-flow tool which is pulled by contracts using an NPM package.

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #9465
closes: #10148

## Description

This pull request introduces several changes to the `async-flow` package, focusing on enhancing error handling, updating documentation, and improving test robustness. Key changes include updating panicking if the guest function settles during replay (unexpected early completion), ***Failure*** state handling, adding a panic handler, and refactoring tests to utilize a new utility function.

### Security Considerations

Behaviour is more correct by guaranteeing the guest behaviour actually matches the recorded log.

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

Converted an existing `test.failing` to a passing test, with a minor change to use `eventLoopIteration` to paper over multiple turns needed for the async flow to register an early completion failure.

### Upgrade Considerations

n/a

### CODE REVIEW

**Comment by mhofman** [comment]
> fulfills

quick nit: settles. An early rejection is as incorrect and an early fulfillment, and actually more likely to occur.

File: packages/async-flow/src/async-flow.js [hunk 1]
```diff
@@ -247,6 +247,19 @@ export const prepareAsyncFlowTools = (outerZone, outerOptions = {}) => {
...
                 if (bijection.hasGuest(guestResultP)) {
+                  try {
+                    !log.isReplaying() ||
+                      admin.panic(
+                        makeError(
+                          X`guest fulfilled with ${gFulfillment} before finishing replay`,
+                        ),
+                      );
+                  } catch (hostPanic) {
+                    // Catch the hostPanic or else it becomes an unhandled rejection.
```
Comment (mhofman) [inline packages/async-flow/src/async-flow.js]: You may be interested in https://github.com/Agoric/agoric-sdk/issues/10148

File: packages/async-flow/src/async-flow.js [hunk 2]
```diff
@@ -247,6 +247,19 @@ export const prepareAsyncFlowTools = (outerZone, outerOptions = {}) => {
...
+                    // FIXME: Do we want to surface the panic in the outcome?
+                    // outcomeKit.resolver.reject(hostPanic);
```
Comment (mhofman) [inline packages/async-flow/src/async-flow.js]: We definitely do not want the outcome to be affected. We just need to Fail the flow so it can be resumed with fixed logic in the next incarnation.

**Review by mhofman — CHANGES_REQUESTED** [review]
We need to handle the rejection case too :)

File: packages/async-flow/docs/async-flow-states.png
Comment (mhofman) [inline packages/async-flow/docs/async-flow-states.png:1]: Technically the flow can also go from running to failed if the guest does something illegal like passing a non passable to a guest wrapper. It's not just for internal failures.

File: packages/async-flow/test/_utils.js [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+ * @import {PreparationOptions} from '../src/types.js';
+ */
+
+/**
+ * @param {*} t
+ * @param {Zone} zone
+ * @param {PreparationOptions} [opts]
+ */
+export const prepareTestAsyncFlowTools = (t, zone, opts) => {
+  const { panicHandler = e => t.log('Handled panic', e) } = opts || {};
```
Comment (mhofman) [inline packages/async-flow/test/_utils.js]: Shouldn't the default behavior be to `t.fail` the test? I know that's what the unhandled rejection handler ava sets up would do, but I think that's the correct default behavior, and here it'd just be more explicit.

File: packages/async-flow/test/async-flow-early-completion.test.js [hunk 4]
```diff
@@ -149,8 +150,12 @@ const testBadShortReplay = async (t, zone) => {
 
   const { guestMethod } = {
     async guestMethod(_gOrch7, _g1, _p3) {
-      t.log('  badReplay return early');
-      resolveStep(true);
+      t.log('  badShortReplay return early');
```
Comment (mhofman) [inline packages/async-flow/test/async-flow-early-completion.test.js]: Let's move this log line before the `return` ?

File: packages/async-flow/docs/async-flow-states.md [hunk 5]
```diff
@@ -10,6 +10,7 @@
...
+- ***Failed***. If during the ***Replaying*** state the guest activation fails to exactly reproduce its previously logged behavior, it goes into the inactive ***Failed*** state, with a diagnostic explaining how the replay failed, so it can be repaired by another future upgrade. As of the next reincarnation, the failure status is cleared and it starts ***Replaying*** again, hoping not to fail this time. If replay failed because the guest async function did not reproduce its previous behavior, then the upgrade needs to replace the function with one which does. If a ***Replaying*** or ***Running*** guest failed because of a failure of the `asyncFlow` mechanism, whether a bug or merely hitting a case that is not yet implemented, then an upgrade needs to replace the relevant part of the `asyncFlow`'s mechanism.
```
Comment (mhofman) [inline packages/async-flow/docs/async-flow-states.md]: I think we also need to mention that a Running guest can go into failed state if it interacts with a host wrapper in an unsupported way (e.g. uses non passable or otherwise non recognized values as arguments)

**Review by mhofman — APPROVED** [review]
Looks good, feel free to merge once the following is addressed:

- Small documentation update to reflect in which case the flow goes from running to failed.
- I am uncomfortable defaulting the test async flow panic handler to just log, and I think it's safe to make it fail the test. Please let m know if I'm misunderstanding something.

**Comment by mhofman** [comment]
> closes: https://github.com/Agoric/agoric-sdk/issues/10148

I just realized, can we add an explicit test of the new panic handler? I'm thinking something like a guest that passes a locally defined function as argument, and verify that trips up the panic handler.

File: packages/async-flow/docs/async-flow-states.md (hunk 5 above)
Comment (michaelfig) [reply packages/async-flow/docs/async-flow-states.md]: Does "a case that is not yet implemented" cover that?

File: packages/async-flow/test/_utils.js (hunk 3 above)
Comment (michaelfig) [reply packages/async-flow/test/_utils.js]: Okay, so you're talking about the default `panicHandler`.  I presume you mean that the tests that had unhandled rejections, but expected them, would override the `panicHandler` option?

File: packages/async-flow/docs/async-flow-states.md (hunk 5 above)
Comment (michaelfig) [reply packages/async-flow/docs/async-flow-states.md]: I reworded this bullet to be more explicit.

File: packages/async-flow/docs/async-flow-states.png
Comment (michaelfig) [reply packages/async-flow/docs/async-flow-states.png:1]: Updated the diagram.

File: packages/async-flow/docs/async-flow-states.md (hunk 5 above)
Comment (mhofman) [reply packages/async-flow/docs/async-flow-states.md]: Some things may be not yet implemented. But others may just be intrinsic limitations of async-flow or of our object model. Passing a non-passable value as argument is one of those purely guest error that async-flow isn't responsible for.

**Comment by michaelfig** [comment]
> I just realized, can we add an explicit test of the new panic handler? I'm thinking something like a guest that passes a locally defined function as argument, and verify that trips up the panic handler.

A guest that passes a locally defined function doesn't cause a panic, it just shows up as a `'doThrow'` in the log.  Do you have another way to test what you have in mind?

**Comment by mhofman** [comment]
> A guest that passes a locally defined function doesn't cause a panic, it just shows up as a `'doThrow'` in the log

That is surprising, and not what I expected at all.

File: packages/async-flow/test/bad-host.test.js [hunk 6]
```diff
@@ -103,6 +111,8 @@ const testBadHostFirstPlay = async (t, zone) => {
     // Notice that the bad call was not recorded in the log
   ]);
   t.log('badHost firstPlay done');
+  // Allow panicHandler to be called.
+  await null;
```
Comment (mhofman) [inline packages/async-flow/test/bad-host.test.js]: I'm tempted to say we should `await eventLoopIteration()` (aka `await nextCrank()`) here

**Review by mhofman — APPROVED** [review]
LGTM

Small nit, as relying on precise turn counts is likely not reliable long term. That said, we likely need to update all tests to be more resilient to that, so feel free to ignore for now.

I'm satisfied that the new panic handler is exercised in some of these tests already, It would be nice to also cover the case of guest misbehavior in playing state, but that's something we can add as part of #9933
