### PR TITLE
6880 bootstrap integration test of vaultFactory with smart wallet

### LINKED ISSUE #6880: integration tests of walletFactory and vaultFactory
## What is the Problem Being Solved?

We lack test coverage of the integration between vaultFactory and walletFactory contracts.

## Description of the Design

https://github.com/Agoric/agoric-sdk/tree/master/packages/inter-protocol/test/smartWallet has integration tests between other Inter contracts and walletFactory (smart wallet).

We need a similar one for vaultFactory. The challenge is that the existing ones use `boot-psm` and vaultFactory has many more boot requirements. E.g. the AMM and reserve. Since those are to support liquidation, which is about to be replaced, we could start booting with some inert liquidation contract that doesn't need them.

## Test Plan

Includes a regression test for the looping condition @samsiegart ran into https://gist.github.com/samsiegart/f74a97206d43cdb7c5095714f84136fc . (Though that might already be fixed by https://github.com/Agoric/agoric-sdk/pull/6804 )

### PR DESCRIPTION
**Pull request by turadg**
closes: #6880

## Description

Tests Vault Factory integration with Smart Wallet, using a new kind of Swingset test.

vs contract tests:
- integrates the full bootstrap so there's no config maintenance
- runs on top of the same `decentral-test-vaults-config.json` as testnet
- takes ~1m to run

vs chain tests:
- fakes the Cosmos bridge
- uses `local` instead of `xs-worker` so it's faster (e.g. xs about 50% slower than Node in local dev) and enables use of the Node debugger
- can use Ava test runner and assertions

### CODE REVIEW

File: packages/SwingSet/tools/bundleTool.js [hunk 1]
```diff
@@ -172,10 +172,11 @@ export const makeBundleCache = (wr, cwd, readPowers, opts) => {
   const loaded = new Map();
   /**
    * @param {string} rootPath
-   * @param {string} targetName
+   * @param {string} [targetName]
    * @param {(message: *) => void} [log]
    */
   const load = async (rootPath, targetName, log = console.debug) => {
+    targetName ||= pathAmbient.basename(rootPath, '.js');
```
Comment (turadg) [inline packages/SwingSet/tools/bundleTool.js]: the `||=` is why this PR is stacked on https://github.com/Agoric/agoric-sdk/pull/7073

@dckc I know you'll have thoughts about `pathAmbient`. It was a hassle to wire it through the functions and they don't have types so that would be lost. I figure the module is like a closure in which an authority is available so this is not a violation of ocap.

I figure at some point we'll have things like Node's `path` not importable. Until then this feels pragmatic.

Comment (dckc) [reply packages/SwingSet/tools/bundleTool.js]: > It was a hassle to wire it through the functions ...

Adding `basename` to `readPowers` isn't straightforward?

> I figure the module is like a closure in which an authority is available so this is not a violation of ocap.

Hm. Exporting functions that close over ambient authority such as `path.basename` is one of the few crisp prohibitions we have managed to articulate (or... I thought we had managed...):

> No modules should export powerful objects (for example, objects that close over `fs` or `process.env`).
 -- [OCap Discipline](https://github.com/Agoric/agoric-sdk/wiki/OCap-Discipline)

File: packages/SwingSet/tools/bundleTool.js [hunk 2]
```diff
@@ -30,7 +31,7 @@ export const makeFileWriter = (fileName, { fs, path }) => {
   });
 };
 
-export const makeBundleCache = (wr, cwd, readPowers, opts) => {
+export const makeBundleCache = (wr, options, cwd, readPowers, opts) => {
```
Comment (dckc) [inline packages/SwingSet/tools/bundleTool.js]: `options` _and_ `opts`? Any particular reason not to combine them?

File: packages/SwingSet/src/controller/initializeSwingset.js [hunk 3]
```diff
@@ -414,16 +419,26 @@ export async function initializeSwingset(
...
     if (mode === 'bundle') {
       return desc.bundle;
     } else if (mode === 'bundleSpec') {
       return JSON.parse(fs.readFileSync(desc.bundleSpec).toString());
     } else if (mode === 'sourceSpec') {
-      return bundleSource(desc.sourceSpec, {
-        dev: config.includeDevDependencies,
-        format: config.bundleFormat,
-      });
+      return bundleCache.load(desc.sourceSpec);
```
Comment (dckc) [inline packages/SwingSet/src/controller/initializeSwingset.js]: @warner this is the bit we were talking about earlier today.

File: packages/SwingSet/tools/bundleTool.js (hunk 1 above)
Comment (turadg) [reply packages/SwingSet/tools/bundleTool.js]: > Adding basename to readPowers isn't straightforward?

Adding it to `makeReadPowers` isn't because that's in Endo. This works,
```js
  const readPowers = {
    ...makeReadPowers({ fs, url, crypto }),
    basename: fs.basename,
  };
```
But it's confusing the `makeReadPowers` doesn't make `readPowers`. And the type information is lost. The net cost of repeating every `fs` function that we need strikes me as greater than its benefit.

> No modules should export powerful objects (for example, objects that close over fs or process.env).

I don't think we fully follow that edict. A search of `process.env` shows 77 results in 40 files. Not all are functions closing over it but I see 10-20 that are.

I'll remove pathAmbient to get this PR in but I think the ocap coding guidelines could use some refinement.

File: packages/SwingSet/tools/bundleTool.js (hunk 2 above)
Comment (turadg) [reply packages/SwingSet/tools/bundleTool.js]: they're different bags. the first one is for bundleSource. but the latter isn't ever used so I'll remove it.

File: packages/SwingSet/tools/bundleTool.js (hunk 1 above)
Comment (dckc) [reply packages/SwingSet/tools/bundleTool.js]: > > No modules should export powerful objects (for example, objects that close over fs or process.env).
> 
> I don't think we fully follow that edict.

Indeed;  #2160 represents the technical-debt to clean that up.

> And the type information is lost.

That seems straightforward to address.

> The net cost of repeating every `fs` function that we need strikes me as greater than its benefit.

It is unfortunate that node's `fs` API is awkward w.r.t. the principle of least authority. I hope we can use something shaped like this more widely...

https://github.com/Agoric/agoric-sdk/blob/010105a0e4471a81a97d567bf04cb48753e0ec37/packages/SwingSet/tools/bundleTool.js#L9-L31

Comment (dckc) [reply packages/SwingSet/tools/bundleTool.js]: > Adding it to `makeReadPowers` isn't because that's in Endo.

Ah... I missed that point earlier. Now I appreciate why it's awkward.

Here's hoping I can sync up with endo on POLA-shaped IO soonish. Thanks for ef90a4f meanwhile.

File: packages/SwingSet/src/controller/initializeSwingset.js (hunk 3 above)
Comment (dckc) [reply packages/SwingSet/src/controller/initializeSwingset.js]: The original description of #3609 by @warner has a bunch of considerations for reliable bundle caching. Before closing that one, I reduced the scope to "prototype". Using it for a dev tool has served us reasonably well, but this is a proposal to put it into production runtime, so it's worth some thought.

Comment (turadg) [reply packages/SwingSet/src/controller/initializeSwingset.js]: It's a perf optimization so we could land this PR without it and solve the bundle caching separately.

One way would be to have the bootstrap config indicate whether to bundle cache. The test could add it to the modifications it does before passing on the config.

Another option might be to define another bundle source specifying the built bundle. Then the config would be modified to point to pre-bundled sources.

**Comment by turadg** [comment]
Since these integrate bootstrap I'm wondering if the tests should be in 'packages/vats' instead. At least the supports module.

In some way "vats" is the product and these are functional tests of user flows so it makes sense for them to be there.

File: packages/SwingSet/src/controller/initializeSwingset.js [hunk 4]
```diff
@@ -459,6 +477,15 @@ export async function initializeSwingset(
     return getBundle(desc, mode, nameToBundle)
       .then(addBundleID)
       .then(bundleWithID => {
+        const emptyBundleSize = 11320;
```
Comment (ivanlei) [inline packages/SwingSet/src/controller/initializeSwingset.js]: What is the signifance of `11320`? It has a "magic number" vibe.

Comment (turadg) [reply packages/SwingSet/src/controller/initializeSwingset.js]: @warner reports that it's the size of an empty bundle. 

Yeah I'll find a better place this constant

File: packages/SwingSet/src/controller/initializeSwingset.js (hunk 3 above)
Comment (dckc) [reply packages/SwingSet/src/controller/initializeSwingset.js]: > One way would be to have the bootstrap config indicate whether to bundle cache. The test could add it to the modifications it does before passing on the config.

I like that idea.

File: packages/SwingSet/src/controller/initializeSwingset.js (hunk 4 above)
Comment (turadg) [reply packages/SwingSet/src/controller/initializeSwingset.js]: Second thought, this was for debugging and is obsolete with https://github.com/Agoric/agoric-sdk/pull/7076. It's also a little squishy relying on this empirical value and it's an odd place for this check.

Conferred with @dckc to take it out instead.

File: packages/SwingSet/src/controller/initializeSwingset.js [hunk 5]
```diff
@@ -401,42 +406,72 @@ export async function initializeSwingset(
...
-  // E(vatAdminService).createVatByName(bundleName)
-
-  // The 'kconfig' we pass through to initializeKernel has
-  // kconfig.[vats|devices].NAME.bundleID and
-  // kconfig.namedBundleIDs.BUNDLENAME=bundleID , which both point into
-  // kconfig.idToBundle.BUNDLEID=bundle
-
-  async function getBundle(desc, mode, nameToBundle) {
-    if (mode === 'bundle') {
+  const bundleCache = await (config.bundleCachePath
```
Comment (dckc) [inline packages/SwingSet/src/controller/initializeSwingset.js:409]: :+1:

File: packages/SwingSet/src/controller/initializeSwingset.js [hunk 6]
```diff
@@ -466,7 +512,12 @@ export async function initializeSwingset(
       });
   }
 
+  /**
+   * @param {string} groupName
+   * @param {Record<string, EndoZipBase64Bundle>} [nameToBundle]
+   */
   async function processGroup(groupName, nameToBundle) {
+    console.time(`processGroup ${groupName}`);
```
Comment (dckc) [inline packages/SwingSet/src/controller/initializeSwingset.js]: was this for debugging? worth keeping?

File: packages/SwingSet/src/devices/mailbox/mailbox.js [hunk 7]
```diff
@@ -94,6 +94,10 @@ export function exportMailbox(inout) {
   };
 }
 
+/**
+ *
+ * @param {Map<*, *>} state
+ */
```
Comment (dckc) [inline packages/SwingSet/src/devices/mailbox/mailbox.js]:
```suggestion
/** @param {Map<*, *>} state */
```

is that type not inferred?

File: packages/SwingSet/src/lib/kmarshal.js [hunk 8]
```diff
@@ -71,6 +86,10 @@ const kmarshal = makeMarshal(krefOf, kslot, {
 
 export const kser = value => kmarshal.serialize(harden(value));
 
+/**
+ * @param {import('@endo/marshal').CapData<any>} serializedValue
```
Comment (dckc) [inline packages/SwingSet/src/lib/kmarshal.js]: I think kernel slots are strings...

```suggestion
 * @param {import('@endo/marshal').CapData<string>} serializedValue
```

File: packages/SwingSet/test/bootstrap-relay.js [hunk 9]
```diff
@@ -1,87 +1,18 @@
-import { E } from '@endo/eventual-send';
-import { Far, isObject, makeMarshal } from '@endo/marshal';
 import { assert } from '@agoric/assert';
 import { objectMap } from '@agoric/internal';
+import { E } from '@endo/eventual-send';
+import { Far } from '@endo/marshal';
 import { buildManualTimer } from '../tools/manual-timer.js';
+import { makePassableEncoding } from '../tools/passableEncoding.js';
```
Comment (dckc) [inline packages/SwingSet/test/bootstrap-relay.js:6]: something to consider for this file: https://github.com/Agoric/agoric-sdk/blob/c0af2a6dc163b6f454f72c1b31a1d60912e1a605/packages/vats/test/upgrading/test-upgrade-vats.js#L66-L94

File: packages/agoric-cli/src/lib/vaults.js [hunk 10]
```diff
@@ -50,6 +50,7 @@ const makeProposal = (brands, opts) => {
   return harden(proposal);
 };
 
+// TODO factor out BridgeAction, same across all
```
Comment (dckc) [inline packages/agoric-cli/src/lib/vaults.js]: Elaborate just a bit?

File: packages/cosmic-swingset/src/launch-chain.js [hunk 11]
```diff
@@ -61,6 +71,7 @@ async function buildSwingset(
   env.ROLE = argv.ROLE;
 
   const debugPrefix = debugName === undefined ? '' : `${debugName}:`;
+  /** @type {import('@agoric/swingset-vat').SwingSetConfig & { pinBootstrapRoot?: boolean } | null} */
```
Comment (dckc) [inline packages/cosmic-swingset/src/launch-chain.js]: move `pinBootstrapRoot` into `SwingSetConfig` type?

File: packages/cosmic-swingset/src/launch-chain.js [hunk 12]
```diff
@@ -359,6 +373,7 @@ export async function launch({
       inboundNum,
       source,
     });
+    if (!bridgeInbound) throw Fail`bridgeInboard undefined`;
```
Comment (dckc) [inline packages/cosmic-swingset/src/launch-chain.js]:
```suggestion
    if (!bridgeInbound) throw Fail`bridgeInbound undefined`;
```

File: packages/vats/test/bootstrapTests/supports.js [hunk 13]
```diff
@@ -0,0 +1,242 @@
...
+ */
+export const makeSwingsetTestKit = async t => {
+  console.time('makeSwingsetTestKit');
+  const configPath = await getNodeTestVaultsConfig();
+  const { kernelStorage } = initSwingStore();
+
+  const storage = makeFakeStorageKit('bootstrapTests');
+
+  /**
+   *
```
Comment (dckc) [inline packages/vats/test/bootstrapTests/supports.js:209]: make a note about fragility under maintenance?

File: packages/vats/test/bootstrapTests/supports.js [hunk 14]
```diff
@@ -0,0 +1,242 @@
...
+    v => v !== '@agoric/pegasus/scripts/init-core.js',
+  );
+
+  // XXX assumes the test is being run from the package root and that bundles/ exists
+  const testConfigPath = 'bundles/local-decentral-test-vaults-config.json';
+  await fs.writeFile(testConfigPath, JSON.stringify(config), 'utf-8');
+  return testConfigPath;
+};
+
+/**
```
Comment (dckc) [inline packages/vats/test/bootstrapTests/supports.js:191]: make a note about taking care with a shared swingset across tests?

File: packages/vats/test/bootstrapTests/test-vaults-integration.js [hunk 15]
```diff
@@ -0,0 +1,326 @@
...
+  console.time('open vault');
+  const { runUtils, storage } = t.context;
+
+  const factoryDriver = await makeWalletFactoryDriver(runUtils, storage);
+  console.timeLog('open vault', 'made walletDriver');
+
+  const wd = await factoryDriver.provideSmartWallet('agoric1open');
+
+  const { agoricNamesRemotes } = t.context;
+  await wd.executeOffer({
```
Comment (dckc) [inline packages/vats/test/bootstrapTests/test-vaults-integration.js:73]: static typechecking this big offer expression would be nifty

File: packages/vats/test/bootstrapTests/test-vaults-integration.js [hunk 16]
```diff
@@ -0,0 +1,326 @@
...
+      invitationMakerName: 'AdjustBalances',
+    },
+    proposal: {
+      give: {
+        // @ts-expect-error XXX remote in OfferSpec
+        Minted: { brand: agoricNamesRemotes.brand.IST, value: 500n },
+      },
+    },
+  });
+  console.log(wd.getLatestUpdateRecord());
```
Comment (dckc) [inline packages/vats/test/bootstrapTests/test-vaults-integration.js]: use `t.log`? or did you mean to prune it as debugging code?

File: packages/vats/test/bootstrapTests/test-vaults-integration.js [hunk 17]
```diff
@@ -0,0 +1,326 @@
...
+        Minted: { brand: agoricNamesRemotes.brand.IST, value: 5000000n },
+      },
+    },
+  });
+  t.like(wd.getLatestUpdateRecord(), {
+    updated: 'offerStatus',
+    status: { id: 'open-vault', numWantsSatisfied: 1 },
+  });
+
+  // try giving more than is available in the purse/vbank
```
Comment (dckc) [inline packages/vats/test/bootstrapTests/test-vaults-integration.js]: :clap:

File: packages/vats/test/snapshots/test-board-utils.js.md [hunk 18]
```diff
@@ -0,0 +1,152 @@
+# Snapshot report for `test/test-board-utils.js`
+
+The actual snapshot is saved in `test-board-utils.js.snap`.
+
+Generated by [AVA](https://avajs.dev).
+
+## makeAgoricNamesRemotesFromFakeStorage
```
Comment (dckc) [inline packages/vats/test/snapshots/test-board-utils.js.md:7]: It would be great to promote this to https://docs.agoric.com/

**Review by dckc — APPROVED** [review]
very nice!

some stuff to consider, but nothing critical

File: packages/SwingSet/src/controller/initializeSwingset.js (hunk 6 above)
Comment (turadg) [reply packages/SwingSet/src/controller/initializeSwingset.js]: removed

File: packages/SwingSet/src/devices/mailbox/mailbox.js (hunk 7 above)
Comment (turadg) [reply packages/SwingSet/src/devices/mailbox/mailbox.js]: good point, this doesn't add anything. removed.

File: packages/vats/test/bootstrapTests/test-vaults-integration.js (hunk 15 above)
Comment (turadg) [reply packages/vats/test/bootstrapTests/test-vaults-integration.js:73]: it checks the types of the properties, but for some reason it doesn't check the top level properties. gonna punt on that.

File: packages/SwingSet/test/bootstrap-relay.js (hunk 9 above)
Comment (turadg) [reply packages/SwingSet/test/bootstrap-relay.js:6]: nifty! TALA [38cd282](https://github.com/Agoric/agoric-sdk/pull/7021/commits/38cd282a0566cb04a8f29f19ca08b3082ac847cd)

Comment (dckc) [reply packages/SwingSet/test/bootstrap-relay.js:6]: @gibson042 check this out ^

File: packages/cosmic-swingset/src/launch-chain.js [hunk 19]
```diff
@@ -47,7 +48,16 @@ const blockManagerConsole = anylogger('block-manager');
...
+/**
+ * @param {Map<*, *>} mailboxStorage
+ * @param {*} bridgeOutbound
+ * @param {SwingStoreKernelStorage} kernelStorage
+ * @param {string} vatconfig absolute path
+ * @param {Record<string, any>} argv XXX argv should be an array but it's being called with object
+ * @param {{ ROLE: string }} env
+ * @param {*} options
+ */
+export async function buildSwingset(
```
Comment (mhofman) [inline packages/cosmic-swingset/src/launch-chain.js:60]: I really wasn't expecting this to be exported, and to stay an internal concern.

**Comment by mhofman** [comment]
> * fakes the Cosmos bridge

I hope this will be compatible with the bridge changes in #6741 

Edit: confirmed to be compatible!

File: packages/cosmic-swingset/src/launch-chain.js (hunk 19 above)
Comment (turadg) [reply packages/cosmic-swingset/src/launch-chain.js:60]: I'm not clear on what the intent of this comment is. Do you want it to be factored differently? If so, how?

Comment (mhofman) [reply packages/cosmic-swingset/src/launch-chain.js:60]: I just have 3 pending PRs that are now failing/conflicting because of this change. I'm not sure if there is a better way to factor this, haven't looked closely yet. It's more of a process question, I wish I had known about this change coming.
