### PR TITLE
fix(swingset): clean up promise c-list entries during vat deletion

### LINKED ISSUE #10261: vat termination leaks promises
## Describe the bug

While writing tests for remediation of #9039 , I noticed a second problem. When a vat is terminated, and the kernel rejects its remaining outstanding (vat-decided) promises, we delete the late vat's c-list entry without decrementing the corresponding refcount. That means these promises will be left with a final refcount of 1, not 0, causing the promise (and it's rejected value, e.g. the DisconnectionObject) to be retained forever.

## To Reproduce

I'm modifying `SwingSet/test/vat-admin/terminate/terminate.test.js` to demonstrate the problem, by gleaning the kpid of a dead-vat -decided promise, and then examining the kvStore afterwards to see whether or not the kernel promise table entry is still present.

## Impact

On chain, we've only ever deleted one vat (a provisioning vat, during the initial bootstrap run at chain launch, back in 2023). So the impact is minimal so far. But we're intending to terminate some large vats in the near future, so we should get this fixed before we perform those terminations.

## Cause

When the kernel terminates a vat, we run a function named `terminateVat()` in kernel.js . Originally, before we landed slow-termination, this built a list of `deadPromises` by scanning for all promises decided by the vatID, then used `kernelKeeper.cleanupAfterTerminatedVat()` to delete all c-list entries (and vatstore), then submit each dead kpid to `resolveToError()`. This `resolveToError` calls `doResolve` with a rejection value, which is the same function that is used by `syscall.resolve`.

The critical difference is that when a vat does `syscall.resolve()`, the vatTranslator (which converts the VatSyscallObject to a KernelSyscallObject, translating vrefs to krefs) would also retire the c-list entries immediately after translation, using `vatKeeper.deleteCListEntriesForKernelSlots()`. This function decrements the entry's refcount just before deleting the kvStore keys, allowing the usual `maybeFreeKrefs` processing to clean things up.

But `terminateVat` goes directly to `resolveToError`/`doResolve` without going through a vref/kref translator, so nothing ever calls `deleteCListEntriesForKernelSlots`. It calls `cleanupAfterTerminatedVat`, and that function *does* decrement refcounts for kernel *objects*, but it does not do anything special for kernel *promises*, it merely deletes the forward (`vNN.c.kpNN`) and reverse kvStore entries without touching refcounts.

When we landed slow termination, we retained this pattern. All the dead vat's promises are rejected immediately, inside `terminateVat()`, but we leave c-list handling to the slow/background `kernelKeeper.cleanupAfterTerminatedVat()`, which behaves just like the old version, and doesn't perform refcount handling on promise c-list entries.

## Likely Fix

One path would be to properly retire the promise c-list entries during `terminateVat()`. We would change it to use `vatKeeper.deleteCListEntriesForKernelSlots(deadPromises)`. I'd have to think about the right ordering: should be retire those entries before or after doing `resolveToError` on all of them? The vat might have been self-subscribed to some of those promises, so `resolveToError` will enqueue notifications to the dead vat. I'm pretty sure those will be safely ignored when they reach the front of the run-queue, but we'd need to test it.

A second path would be to change `cleanupAfterTerminatedVat()` to have a `'promise'` phase, probably just after the `'import'` and `'export'` phases, but before the `'kv'` phase. Currently, the `vNN.c.kpNN` promise c-list entries are bulk-deleted during the `kv` phase, because I didn't think those deletions had side-effects (I thought the refcounts were decremented immediately, during `terminateVat()`, so it's safe to delete them at a faster rate. This would be in keeping with our slow-deletion patterns: all userspace-visible consequences of the termination happen immediately, during `terminateVat()`, but non-userspace-visible consequences (GC drops/retires) are allowed to happen slowly, afterwards.

I'm inclined to take the second path, although it probably means more work: adding a new phase involves cosmic-swingset code to make that limit be configurable.

### PR DESCRIPTION
**Pull request by warner**
Previously, when a vat was terminated, and we delete the promise
c-list entries from its old state, the cleanup code was failing to
decrement the kpid's refcount properly. This resulted in a leak: those
promises could never be retired.

This commit updates the vat cleanup code to add a new phase, named
`promises`. This executes after `exports` and `imports`, but before
`kv`, and is responsible for both deleting the c-list entries and also
decrementing the refcounts of the corresponding promises. We do this
slowly, like we do exports and imports, because we don't know how many
there might be, and because those promise records might hold
references to other objects (in the resolution data), which could
trigger additional work. However, this work is unlikely to be
significant: the run-queue is usually empty, so these outstanding
promises are probably unresolved, and thus cannot beholding resolution
data.

All promises *decided* by the dead vat are rejected by the kernel
immediately during vat termination, because those rejections are
visible to userspace in other vats. In contrast, freeing the promise
records is *not* visible to userspace, just like how freeing imports
or exports are not visible to userspace, so this cleanup is safe to do
at a leisurely pace, rate-limited by `runPolicy.allowCleanup`.

The docs are updated to reflect the new `runPolicy` API:

* `budget.promises` is new, and respected by slow cleanup
* `work.promises` is reported to `runPolicy.didCleanup()`

I don't intend to add any remediation code: it requires a full
refcount audit to find such promises, and the mainnet kernel has only
ever terminated one vat so far, so I believe there cannot be very many
leaked promises, if any. Once this fix is applied, no new leaks will
occur.

fixes #10261

### CODE REVIEW

File: packages/SwingSet/src/kernel/state/kernelKeeper.js [hunk 1]
```diff
@@ -1043,8 +1045,22 @@ export default function makeKernelKeeper(
...
+    for (const k of enumeratePrefixedKeys(kvStore, promisePrefix)) {
+      const kref = kvStore.get(k) || Fail`getNextKey ensures get`;
+      const vref = stripPrefix(clistPrefix, k);
+      vatKeeper.deleteCListEntry(kref, vref);
+      // that will also delete both db keys
+      work.promises += 1;
+      remaining -= 1;
+      if (remaining <= 0) {
+        return { done: false, work };
+      }
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/kernelKeeper.js:1116]: This `cleanupAfterTerminatedVat` function is getting a bit unwieldy... I wonder if things would be better or worse if we abstracted some boilerplate?

No suggestion at this point, though.

File: packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js [hunk 2]
```diff
@@ -182,7 +202,7 @@ async function doSlowTerminate(t, mode) {
   t.true(JSON.parse(kvStore.get('vats.terminated')).includes(vatID));
   // no cleanups were allowed, so nothing should be removed yet
   t.truthy(kernelStorage.kvStore.get(`${vatID}.options`));
-  t.is(remainingKV().length, 129);
+  t.is(remainingKV().length, 169);
```
Comment (gibson042) [inline packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js]: We should avoid repeating this magic number, especially since it may need occasional updating.
```suggestion
  t.is(remainingKV().length, initialKVCount);
```

Comment (gibson042) [reply packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js]: This test tells a great story, but may be overly fine-tuned. No suggestions at the moment, though.

File: packages/SwingSet/test/vat-admin/terminate/terminate.test.js [hunk 3]
```diff
@@ -471,6 +471,23 @@ test.serial('dead vat state removed', async t => {
...
+      const refCount = Number(kvStore.get(`${kpid}.refCount`));
+      const decider = kvStore.get(`${kpid}.decider`);
+      if (decider === 'v6') {
+        decidedKPID = kpid;
+      } else {
+        subscribedKPID = kpid;
+      }
+      t.is(refCount, 2, `${kpid}.refCount=${refCount}, not 2`);
+    }
+  }
```
Comment (gibson042) [inline packages/SwingSet/test/vat-admin/terminate/terminate.test.js:490]: I noticed in the other file that we pretty much always need to strip off the prefix for each key returned from `enumeratePrefixedKeys` (which makes sense). If we refactored it to produce `{ key, suffix }` records (where suffix has had the prefix stripped), then we'd end up here with something like
```suggestion
  for (const { suffix } of enumeratePrefixedKeys(kvStore, 'v6.c.kp')) {
    const kpid = `kp${suffix}`;
    const refCount = Number(kvStore.get(`${kpid}.refCount`));
    const decider = kvStore.get(`${kpid}.decider`);
    if (decider === 'v6') {
      decidedKPID = kpid;
    } else {
      subscribedKPID = kpid;
    }
    t.is(refCount, 2, `${kpid}.refCount=${refCount}, not 2`);
  }
```

**Review by gibson042 — APPROVED** [review]
I must have leveled up, because following these changes was not too bad.

File: packages/SwingSet/test/vat-admin/terminate/terminate.test.js (hunk 3 above)
Comment (warner) [reply packages/SwingSet/test/vat-admin/terminate/terminate.test.js:490]: filed #10340 to remember to do this refactoring later

File: packages/SwingSet/test/vat-admin/slow-termination/bootstrap-slow-terminate.js [hunk 4]
```diff
@@ -21,11 +22,22 @@ export function buildRootObject(_vatPowers) {
...
 
       // set up 20 "dude exports, bootstrap imports" c-list entries
-
       for (let i = 0; i < 20; i += 1) {
         myImports.push(await E(root).sendExport());
       }
 
+      // also 10 imported promises
+      for (let i = 0; i < 10; i += 1) {
+        await E(root).acceptImports(makePromiseKit().promise);
```
Comment (mhofman) [inline packages/SwingSet/test/vat-admin/slow-termination/bootstrap-slow-terminate.js:31]: To be clear, these eventual sends also result in imported / externally decided promises but since they're immediately settled, they do not participate in any cleanup?

**Review by mhofman — APPROVED** [review]
This looks fairly straightforward. The tests do seem very descriptive, which I'm worried will complicate maintenance, but that's out of scope for this change.

File: packages/SwingSet/test/vat-admin/slow-termination/bootstrap-slow-terminate.js (hunk 4 above)
Comment (warner) [reply packages/SwingSet/test/vat-admin/slow-termination/bootstrap-slow-terminate.js:31]: Right, the `acceptImports` result promises are settled (and the notifies delivered) during the bootstrap run, driven by the `await controller.run()` on line 110 of `slow-termination.test.js`. The `makePromiseKit().promise` *payload* of those messages are never resolved (they remain decided by vat-bootstrap, but we've thrown away the settlement functions), so they'll still be in the c-list when the vat is terminated. The exports will be rejected when the target vat is terminated, and removed from the c-list by the `run()` on line 191. But the imports will still be sitting there when the slow deletion happens.
