### PR TITLE
chore: update moddable to get snapshot fixes

### LINKED ISSUE #2322: metering support in vat workers (XS regex, ...)
## What is the Problem Being Solved?

As discussed in #2319, to figure out when we should end a block (ideally just before we reach the wallclock time budget), we need our vat workers to provide two facilities to the kernel:

* when the kernel instructs a worker to execute a crank, the kernel will provide a limit (a number)
  * as soon as the worker sees that the computation has exceeded this limit, the vat should be killed
  * the worker should return a VatDeliveryResults object that indicates the vat died due to a meter overrun
  * the kernel might later rebuild this vat from an earlier state (to resubmit the crank), or it might just be dead forever
  * the kernel will generally provide a fairly generous limit: we really want to avoid retries, because they're expensive
* when the worker finishes executing a crank, it will return the actual amount consumed (as a number)
  * the VatDeliveryResults will include this number

The kernel will be able to add this number to the usage of all other cranks it has executed, and compare the result against a per-block limit.

We're hoping that this number will be roughly proportional to wallclock time. It is, of course, influenced by all sorts of other factors (CPU speed, complexity of the code being run, overhead, interference by other processes on that system, etc). We don't require the relationship to be deterministic, however the more stable/consistent it is, the higher we can raise the limit (improving utilization) while still avoiding occasional block timeouts on most validators.

We do require that the limits and amount-consumed results are deterministic. All workers (on all nodes) must yield the same values for a vat in the same state, processing the same crank. Any overhead that is not part of the deterministic input to the vat behavior must be excluded from the usage numbers.

## Design

The VatDeliveryObject should be expanded to include a meter limit. The VatDeliveryResults should be expanded to include a consumption amount.

For now, the kernel should choose a hard-coded meter limit based upon the worker type. Workers that do not enforce metering (which is all of them right now) should ignore it. Workers which do not measure usage should return a `consumption` of `undefined`.

We'll need to think about the relationship between the kernel-process -side VatManager and whatever worker it manages, to figure out the right place to decide/deduct the usage numbers. This will eventually expand to involve Meters, stacked/backup meters, etc, all of which happens much closer to the kernel than to the worker.

## Worker Types

Our main target is XS, where we expect the JS engine to support this feature. The `xsnap` supervisor will need to be told what the limit is, configure it into the engine somehow, run the crank to completion (or early termination), determine which case actually happened, retrieve the consumed (or remaining) value from the engine, and report the results back to the kernel.

For a local (Node.js in the kernel process) worker, we might adapt the existing Metering Transform to give us a similar number, and augment the local worker code to have a similar API. The actual units would be drastically different, of course (the same vat running in a local worker will consume different "gas" than if it were running on XS), but the basic principle would be the same. Or we might decide that it isn't worth the effort to try and limit local workers and put our energy solely into XS.

## Security Considerations

If the metering is non-deterministic (slightly different versions of XS, perhaps), one validator might decide that it is done with a block earlier than others. This might be deterministically different: they get the same answer each time, just not an answer that matches the other validators. I'm not sure how Tendermint would react to this, but I think it could be bad: the minority faction could never replicate the proposed block, and would remain disjoint forever. They would eventually get slashed for not contributing, and the total validator set would grow smaller.

If the metering is random (e.g. it winds up depending upon uninitialized memory, or filesystem responses, or some platform-level thing that changes from one run to the next), it's probably worse: a validator that re-runs the disputed block could produce a different vote than before, which is equivocation and subject to more serious slashing. Validators who find themselves disagreeing with the proposed block because of a metering difference might wish to refrain from voting, and instead try restarting the process, to re-run the block from a different platform state, in the hopes of achieving a match (i.e. compare the number of cranks performed locally against something in the block, before deciding to vote no).

Small differences in the measured meter value might not cause the number of executed cranks to change: the probability depends upon the average crank size vs the amount of variation. The statistics would be similar to what you get by rounding a slightly random number and comparing the integer result across trials. This might reduce the effect of nondeterministic metering. If validators had a way to survive a low rate of disagreement (perhaps by taking a performance hit as they re-run the process and rebuild all their vats), this might still work.

Hmm, if we had such a technique to survive disagreement, we might want to *intentionally* introduce a bit of randomness, to avoid getting stuck in a "no matter how many times I retry, I keep getting the same (minority) result" hole. Curious.

## Test Plan

We need test cases that populate a medium-sized vat, send it instructions to run a bunch of cranks, and then compare how many computrons each one used against a golden master. (We have no theory as to how to predict this value; we must simply run it once to find out the number, and then assert that all subsequent trials yield the same result).

cc @michaelfig @dckc @erights

### LINKED ISSUE #3350: xsnap crashes (SIGSEGV) in GC after snapshot; error stack bug; missing callback
## Description

The `v11:bootstrap` vat runs for a while until it calls `gc()` inside `gcAndFinalize()`, at which point it crashes with a SIGSEGV.

The following is an excerpt of a stack trace from https://github.com/Agoric/agoric-sdk/issues/2273#issuecomment-862433436

```
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:301
#1  0x000055cddbe73e0e in fxSweep (the=0x55cddc49e4e0)
    at /home/connolly/projects/agoric/agoric-sdk/packages/xsnap/makefiles/lin/../../moddable/xs/sources/xsMemory.c:1534
#2  0x000055cddbe70fdb in fxCollect (the=0x55cddc49e4e0, theFlag=1)
    at /home/connolly/projects/agoric/agoric-sdk/packages/xsnap/makefiles/lin/../../moddable/xs/sources/xsMemory.c:251
#3  0x000055cddbdfb538 in fxCollectGarbage (the=0x55cddc49e4e0)
    at /home/connolly/projects/agoric/agoric-sdk/packages/xsnap/makefiles/lin/../../moddable/xs/sources/xsAPI.c:1717
#4  0x000055cddbeff618 in fx_gc (the=0x55cddc49e4e0) at ../../src/xsnap.c:912
#5  0x000055cddbea336e in fxRunID (the=0x55cddc49e4e0, generator=0x7f23807663d0, count=0)
    at /home/connolly/projects/agoric/agoric-sdk/packages/xsnap/makefiles/lin/../../moddable/xs/sources/xsRun.c:835
```

As it turns out, the snapshots are not essential to the problem, but I originally discovered it a la...

```
$ agoric start --reset -v
...
SwingSet: kernel: delivery problem, terminating vat v11 v11:bootstrap exited due to signal SIGSEGV
```

vat `v1:bank` starts by loading the SES shim and supervisor and taking a snapshot; vat `v11:bootstrap` starts from that snapshot and runs for a while until it calls `gc()` inside `gcAndFinalize()`, at which point it crashes with a SIGSEGV.

## To Reproduce: replay xsnap recording

You will need node 14 plus:

 1. the recording: [xsnap-tests.zip](https://github.com/Agoric/agoric-sdk/files/6671728/xsnap-tests.zip)
     - unzip in `/tmp/`
 2. the replay tool: [xs-replay.zip](https://github.com/Agoric/agoric-sdk/files/6672934/xs-replay.zip)
     - unzip somewhere; you'll get an `xs-replay` directory.
 3. an `xsnap` binary:
     - `git clone https://github.com/Agoric/agoric-sdk/; cd agoric-sdk; yarn; yarn build`
     - `export AGORIC_SDK=${PWD}`

Then:

```
$ cd xs-replay
$ make SDK=${AGORIC_SDK}
node --version | grep 14.
v14.16.0
mkdir -p build/bin/lin/debug
cp -rp /.../agoric-sdk/packages/xsnap/build/bin/lin/debug/xsnap build/bin/lin/debug/xsnap
mkdir -p build/bin/lin/release
cp -rp /.../agoric-sdk/packages/xsnap/build/bin/lin/release/xsnap build/bin/lin/release/xsnap
node replay-bin.cjs /tmp/xsnap-tests/1/ /tmp/xsnap-tests/3/
/tmp/xsnap-tests/1/ 00000-options.json : { os: 'Linux', name: 'v1:bank', debug: true, meteringLimit: 0 }
/tmp/xsnap-tests/1/ 1 evaluate
/tmp/xsnap-tests/1/ 2 evaluate
/tmp/xsnap-tests/1/ 3 snapshot
/tmp/xsnap-tests/1/ 00003-snapshot.dat ignoring remaining steps from /tmp/xsnap-tests/1/
/tmp/xsnap-tests/3/ 00000-options.json already spawned; ignoring: {
  os: 'Linux',
  name: 'v11:bootstrap',
  debug: true,
  snapshot: '/home/connolly/projects/agoric/dapp-2865/_agstate/agoric-servers/dev/fake-chain-sim-chain-state/xs-snapshots/c5d82df2198c546034d7df17565503156f6e8684be1eb243c507550b3c06c770-load-aNDEbV.xss',
  meteringLimit: 10000000
}
/tmp/xsnap-tests/3/ 1 evaluate
/tmp/xsnap-tests/3/ 2 issueCommand
/tmp/xsnap-tests/3/ 3 reply
/tmp/xsnap-tests/3/ 4 issueCommand
/tmp/xsnap-tests/3/ 5 reply
/tmp/xsnap-tests/3/ 6 reply
/tmp/xsnap-tests/3/ 7 reply
/tmp/xsnap-tests/3/ 8 issueCommand
/tmp/xsnap-tests/3/ 9 reply
/tmp/xsnap-tests/3/ 10 reply
/tmp/xsnap-tests/3/ 11 issueCommand
/tmp/xsnap-tests/3/ 12 reply
/tmp/xsnap-tests/3/ 13 reply
/tmp/xsnap-tests/3/ 14 reply
/tmp/xsnap-tests/3/ 15 reply
/tmp/xsnap-tests/3/ 16 reply
/tmp/xsnap-tests/3/ 17 reply
/tmp/xsnap-tests/3/ 18 reply
/tmp/xsnap-tests/3/ 19 reply
/tmp/xsnap-tests/3/ 20 reply
/tmp/xsnap-tests/3/ 21 reply
/tmp/xsnap-tests/3/ 22 reply
/tmp/xsnap-tests/3/ 23 reply
/tmp/xsnap-tests/3/ 24 reply
/tmp/xsnap-tests/3/ 25 issueCommand
/tmp/xsnap-tests/3/ 26 issueCommand
/tmp/xsnap-tests/3/ 27 issueCommand
/tmp/xsnap-tests/3/ 28 issueCommand
/tmp/xsnap-tests/3/ 29 issueCommand
/tmp/xsnap-tests/3/ 30 issueCommand
/tmp/xsnap-tests/3/ 31 reply
/tmp/xsnap-tests/3/ 32 reply
/tmp/xsnap-tests/3/ 33 reply
/tmp/xsnap-tests/3/ 34 reply
/tmp/xsnap-tests/3/ 35 reply
/tmp/xsnap-tests/3/ 36 reply
/tmp/xsnap-tests/3/ 37 reply
/tmp/xsnap-tests/3/ 38 reply
/tmp/xsnap-tests/3/ 39 issueCommand
/tmp/xsnap-tests/3/ 40 issueCommand
/tmp/xsnap-tests/3/ 41 issueCommand
/tmp/xsnap-tests/3/ 42 reply
/tmp/xsnap-tests/3/ 43 reply
/tmp/xsnap-tests/3/ 44 issueCommand
/tmp/xsnap-tests/3/ 45 reply
/tmp/xsnap-tests/3/ 46 reply
/tmp/xsnap-tests/3/ 47 issueCommand
/tmp/xsnap-tests/3/ 48 reply
/tmp/xsnap-tests/3/ 49 reply
/tmp/xsnap-tests/3/ 50 issueCommand
/tmp/xsnap-tests/3/ 51 issueCommand
/tmp/xsnap-tests/3/ 52 reply
/tmp/xsnap-tests/3/ 53 reply
/tmp/xsnap-tests/3/ 54 reply
/tmp/xsnap-tests/3/ 55 reply
/tmp/xsnap-tests/3/ 56 reply
/tmp/xsnap-tests/3/ 57 reply
/tmp/xsnap-tests/3/ 58 issueCommand
/tmp/xsnap-tests/3/ 59 issueCommand
/tmp/xsnap-tests/3/ 60 issueCommand
/tmp/xsnap-tests/3/ 61 reply
/tmp/xsnap-tests/3/ 62 reply
/tmp/xsnap-tests/3/ 63 reply
/tmp/xsnap-tests/3/ 64 reply
/tmp/xsnap-tests/3/ 65 reply
/tmp/xsnap-tests/3/ 66 reply
/tmp/xsnap-tests/3/ 67 reply
/tmp/xsnap-tests/3/ 68 reply
/tmp/xsnap-tests/3/ 69 reply
/tmp/xsnap-tests/3/ 70 reply
/tmp/xsnap-tests/3/ 71 reply
/tmp/xsnap-tests/3/ 72 reply
/tmp/xsnap-tests/3/ 73 reply
/tmp/xsnap-tests/3/ 74 reply
/tmp/xsnap-tests/3/ 75 reply
/tmp/xsnap-tests/3/ 76 reply
/tmp/xsnap-tests/3/ 77 issueCommand
/tmp/xsnap-tests/3/ 78 reply
/tmp/xsnap-tests/3/ 79 reply
/tmp/xsnap-tests/3/ 80 snapshot
/tmp/xsnap-tests/3/ 81 issueCommand
(node:28438) UnhandledPromiseRejectionWarning: ExitSignal: v1:bank exited due to signal SIGSEGV
    at ChildProcess.<anonymous> ...
```

## Platform Environment

 - _what OS are you using?_ linux
   - the problem has been reproduced on a mac
 - _is there anything special/unusual about your platform?_ 2273-snapstore branch
 - _what version of the Agoric-SDK are you using?_ `git describe --tags --always` says `@agoric/access-token@0.4.1-36-g36c6a80ef`

cc @phoddie @warner @dtribble @kriskowal @FUDCo @michaelfig @rowgraus

### PR DESCRIPTION
**Pull request by dckc**
fixes #3350
fixes #2322
ref https://github.com/agoric-labs/moddable/tree/ag-testnet-4

We were previously at a97e1fb60dde. Moddable released the fixes re #3350 as well as metering for bigint, regex for #2322. Here we add test and bump the metering version. In the moddable repo, the top two commits (20ec3085, 29b71e09) are our metering tweaks, rebased. 2602c98c is the latest change from moddable that affects XS.

```
moddable/xs$ git log --graph --pretty=format:'%ad %h %s' --abbrev-commit --date=short a97e1.. .
* 2021-05-02 29b71e09 feat(xsnap): count additions and removals from maps, sets
* 2021-05-01 20ec3085 feat: maintain garbageCollectionCount for xsnap
* 2021-06-20 2602c98c quick change to preflight keys needed by mod
* 2021-06-19 71b46945 XS: too many mod keys will abort later
* 2021-06-19 2572a7bc XS snapshot missing bound functions callback
* 2021-06-18 fd6dcf52 XS: safer capture error stack
* 2021-06-17 028fcd45 XS snapshot: cleanup chunks after wrtiting
* 2021-06-15 969ba224 XS metering string from/to number conversions
* 2021-06-14 274c545f XS: metering bigint
* 2021-06-14 a14a5c03 XS: metering regexp
* 2021-06-14 b594c62a XS: metering changes
* 2021-06-09 b99a8268 add ArrayBuffer.fromBigInt

moddable/xs$ git diff -w --stat a97e1fb60dde.. .
 xs/includes/xs.d.ts       |  1 +
 xs/platforms/esp/xsHost.c |  8 ++++++++
 xs/sources/xsAPI.c        | 35 +++++++++++++++++++++++++++++++++--
 xs/sources/xsAll.h        |  3 +--
 xs/sources/xsBigInt.c     | 65 ++++++++++++++++++++++++++++++++++++++++++++++-------------------
 xs/sources/xsError.c      |  8 ++++++--
 xs/sources/xsFunction.c   | 35 -----------------------------------
 xs/sources/xsRun.c        | 20 +++++++++++++++-----
 xs/sources/xsSnapshot.c   | 21 ++++++++++++++++++++-
 xs/sources/xsre.c         | 19 +++++++++++++++++--
 10 files changed, 147 insertions(+), 68 deletions(-)

```

### CODE REVIEW

**Review by warner — APPROVED** [review]
Looks good, as far as I can tell. Agreed that we should wait (at least a little bit) for upstream to get the fixes, so we can remain as close the official sources as we can.

**Comment by dckc** [comment]
Moddable released their stuff as well as some metering stuff. PTAL.

File: packages/xsnap/src/xsnap.c [hunk 1]
```diff
@@ -84,7 +86,8 @@ static char* fxWriteNetStringError(int code);
 #define mxSnapshotCallbackCount 6
 txCallback gxSnapshotCallbacks[mxSnapshotCallbackCount] = {
 	fx_issueCommand, // 0
-	fx_Array_prototype_meter, // 1
+	// fx_Array_prototype_meter, // 1
+	NULL, // 1
```
Comment (warner) [inline packages/xsnap/src/xsnap.c]: Does this mean that we cannot load any snapshots that happened to include a reference to this function? Or, we can load them, but if they subsequently actually try to call it, we'll get a crash?

I'm wondering if it would be better to remove the callback slot entirely, rather than replacing it with a NULL, if we aren't really preserving snapshot compatibility across this change.

**Comment by warner** [comment]
Huh, in `xs/sources/xsRun.c`, on the new line 313, I see a `%%ld` in an `sprintf` string.. is that right? Won't that print a literal `%ld` and then ignore the arguments?

https://github.com/agoric-labs/moddable/compare/a97e1fb60ddea76566eab32609ebad2eccb0d36f...29b71e093f83a19695314713aad87b131cbfe0e4#diff-ae25655a5f4a58dd1f12052e9954cd9f499d9916057191ea0ac918835796792aR313-R317

File: packages/xsnap/src/xsnap.c (hunk 1 above)
Comment (dckc) [reply packages/xsnap/src/xsnap.c]: Right; the NULL isn't worth the risk.

fixed in f337f8a

**Comment by warner** [comment]
Other than `xsRun.c` and the `xsnap.c` question, the rest of the delta looks good.

**Comment by dckc** [comment]
> Huh, in `xs/sources/xsRun.c`, on the new line 313, I see a `%%ld` in an `sprintf` string.. is that right?

That _does_ look goofy. I don't think it affects us: It's in the `#else` part of an `#ifdef mxMetering`, and we have `mxMetering` turned on.

But I guess we owe a heads-up to moddable. (_p.s. done._)

**Comment by warner** [comment]
That test failure suggests that our default CPU meter allowance might be too low.

File: packages/xsnap/test/test-xs-perf.js [hunk 2]
```diff
@@ -56,7 +63,23 @@ test('meter details', async t => {
...
+
+test('metering regex - REDOS', async t => {
+  const opts = options(io);
+  const vat = xsnap(opts);
+  t.teardown(() => vat.terminate());
+  // Java Classname Evil Regex
+  // https://en.wikipedia.org/wiki/ReDoS
+  // http://www.owasp.org/index.php/OWASP_Validation_Regex_Repository
+  const result = await vat.evaluate(`
+  'aaaaaaaaa!'.match(/^(([a-z])+.)+/)
```
Comment (kriskowal) [inline packages/xsnap/test/test-xs-perf.js:79]: ❤️

File: packages/xsnap/test/test-xs-perf.js [hunk 3]
```diff
@@ -56,7 +63,23 @@ test('meter details', async t => {
     },
     'auxiliary (non-consensus) meters are available',
   );
-  t.is(meterType, 'xs-meter-7');
+  // @ts-ignore extra meters not declared on RunResult (yet?)
```
Comment (kriskowal) [inline packages/xsnap/test/test-xs-perf.js]: Might be worth tracking this.

File: packages/xsnap/src/xsnap.c [hunk 4]
```diff
@@ -859,11 +860,13 @@ void fxFreezeBuiltIns(txMachine* the)
 	mxPop();
 }
 
+#if 0
```
Comment (kriskowal) [inline packages/xsnap/src/xsnap.c]: Is this permanently dead code? How do we decide whether to remove the pragma fence or remove the code?

**Review by kriskowal — APPROVED** [review]

File: packages/xsnap/src/xsnap.c [hunk 5]
```diff
@@ -81,14 +83,13 @@ static char* fxWriteNetStringError(int code);
...
-	fx_Array_prototype_meter, // 1
-	fx_print, // 2
-	fx_setImmediate, // 3
-	fx_gc, // 4
-	fx_performance_now, // 5
+	fx_print, // 1
+	fx_setImmediate, // 2
+	fx_gc, // 3
+	fx_performance_now, // 4
 	// fx_evalScript,
```
[the remark this answers is not in the document]
Comment (dckc) [reply packages/xsnap/src/xsnap.c:89]: `NULL` was my hand-wave at a tombstone. Both you and @warner called my bluff, in different directions (which is good!).

The moddable folks added `fx_Function_prototype_bound` to the middle rather than the end of the array in `xsSnapshot.c`; so unless we want to push back on that, we're already not in a good position to preserve snapshot compatibility across this change.

> Are there any snapshots in databases that we care about continuing to be able to restore?

I think not, and @warner 's comment suggests likewise.

File: packages/xsnap/test/test-xs-perf.js (hunk 3 above)
Comment (dckc) [reply packages/xsnap/test/test-xs-perf.js]: I'm mentally tracking it as #3139 . I guess since I have to re-spin ci anyway, I'll note it in the comment.

File: packages/xsnap/src/xsnap.c (hunk 4 above)
Comment (dckc) [reply packages/xsnap/src/xsnap.c]: Again, it's good that you call my bluff here.

This is the [how to organize xsnap?](https://github.com/endojs/endo/issues/681) issue, to my mind. I lean toward a separate xsnap-native submodule.

I guess I might as well delete this code rather than `#if 0` it, but I wanted to prompt some discussion first.

File: packages/xsnap/test/test-xs-perf.js (hunk 3 above)
Comment (dckc) [reply packages/xsnap/test/test-xs-perf.js]: fixed in 5fd6c6f

File: packages/xsnap/src/xsnap.c (hunk 4 above)
Comment (dckc) [reply packages/xsnap/src/xsnap.c]: fixed in e432531

File: packages/xsnap/src/xsnap.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (warner) [reply packages/xsnap/src/xsnap.c:89]: agreed, not yet

We'll need some sort of versioning marker sooner or later. I suspect we're going to need `@agoric/xsnap` to keep multiple binaries around, since all of (snapshot binary format, the `callbacks` table, metering behavior) will be highly dependent upon the binary. So once a vat starts executing with a given version of the `xsnap` binary, both its snapshots and it's future execution are forever bound to that one version (modulo whole-transcript replay to switch to a different version, which might work with consensus but we can figure out the details later).
