### PR TITLE
fix(vaults): reset lockedQuote at start of auction

### LINKED ISSUE #7670: VaultManager does not consider price update and allow vault creation
## Describe the bug

Getting below error in Wallet UI upon attempting to approve vault creation transaction (following txn signing in Keplr):

## To Reproduce

1. Go to Vaults UI
2. Submit create vault offer
3. Approve in Wallet UI
4. Sign Keplr transaction
5. Get error

## Expected behavior

Vault should be created

## Platform Environment

- what OS are you using? what version of Node.js?
- is there anything special/unusual about your platform?
- what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots

If applicable, add screenshots to help explain your problem, especially for UI interactions.

Additional comment from Sam on original ticket
More context: The UI displays a price of 14.5, with 175% MCR. The numbers in the screenshot above appear to be enforcing a price of 0.151, which was the result of a previous price round. However, the price was since updated to 14.5, which the UI sees, but the contract doesn't seem to be enforcing.

@turadg @dckc I'm soliciting some input here, I'm thinking either the UI or the contract is reading the price from the wrong source. The UI is watching manager0.quotes, is that correct? How can we make sure the contract and UI are in sync?

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #7670

## Description

The lockedQuote wasn't getting reset at the start of the auction, so the previous locked price was being enforced when users attempted to open new vaults.

### Security Considerations

nothing

### Scaling Considerations

Not relevent.

### Documentation Considerations

bug fix: no doc changes needed.

### Testing Considerations

There was a test that showed that the restriction on opening out-of-the-money vaults enforcement included the lock price after starting the auction. I changed the timing to show that it was enforced before the start, and not after the start.

### CODE REVIEW

File: packages/inter-protocol/src/vaultFactory/vaultManager.js [hunk 1]
```diff
@@ -1191,6 +1191,8 @@ export const prepareVaultManagerKit = (
               debtBrand,
               collateralBrand,
             );
+          state.lockedQuote = undefined;
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/vaultManager.js:1195]: consider a comment explaining why this is necessary, and why here. 

EDIT: after reading the test I see it documents this case pretty well

File: packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js [hunk 2]
```diff
@@ -1917,14 +1917,15 @@ test('auction locks low price', async t => {
...
-  trace('auction started, binding lockedQuote in the vault manager state');
 
-  // Bump back up to a high price
-  // @ts-expect-error it's a mock
-  priceAuthority.setPrice(
-    makeRatio(100n * wanted, run.brand, baseCollateral, aeth.brand),
-  );
+  const schedule = await E(auctioneerKit.creatorFacet).getSchedule();
+  const priceDelay = await E(auctioneerKit.publicFacet).getPriceLockPeriod();
+  // @ts-expect-error known to be good.
```
Comment (turadg) [inline packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js]: I forget what the error is but if it's about undefined values, better to assert so they're narrowed and we'll detect unexpected changes

**Review by turadg — APPROVED** [review]

File: packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js (hunk 2 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js]: I tried applying `/** @type {import('../../src/auction/scheduler.js').Schedule} */` to `schedule.nextAuctionSchedule` to say that it was non-null, but the ts-error didn't go away.

```
  const { startTime, startDelay } = (/** @type {import('../../src/auction/scheduler.js').Schedule} */ schedule.nextAuctionSchedule);
```

Is there a better way to convince it?

Comment (turadg) [reply packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js]:
```js
  const { startTime, startDelay } = NonNullish(schedule.nextAuctionSchedule);
```

**Review by turadg — APPROVED** [review]
