### PR TITLE
zoe(fix): canTradeWith should use currentAllocations, not give

### LINKED ISSUE #1145: [Zoe] zoeHelper.canTradeWith should be based on current allocations, not what was given
Currently, `canTradeWith` compares the `gives` and `wants` of two offers. This worked ok in our simplest cases. However, if the `currentAllocation` is ever different than the `give`, this is the wrong way to do it, because `give` won't accurately represent whether a trade is possible. 

We need to make the following changes:

Screen Shot 2020-05-29 at 3 40 28 PM

### PR DESCRIPTION
**Pull request by katelynsills**
Closes #1145

### CODE REVIEW

**Comment by katelynsills** [comment]
Whoops, I forgot to request your review @Chris-Hibbert

File: packages/zoe/src/contractSupport/zoeHelpers.js [hunk 1]
```diff
@@ -99,20 +101,18 @@ export const makeZoeHelpers = (zcf) => {
...
-          if (want[keyword]) {
-            return amountMaths[keyword].isGTE(give[keyword], want[keyword]);
-          }
-          return true;
+      const leftAllocation = zcf.getCurrentAllocation(leftOfferHandle);
+      const rightAllocation = zcf.getCurrentAllocation(rightOfferHandle);
+      const satisfied = (want, availableForTrade) =>
+        getKeywords(want).every(keyword => {
+          const amountMath = helpers.getAmountMath(keyword);
+          return amountMath.isGTE(availableForTrade[keyword], want[keyword]);
```
Comment (Chris-Hibbert) [inline packages/zoe/src/contractSupport/zoeHelpers.js:111]: I don't see any tests that show that this change made a difference in behavior. I'd expect to see a test where the return value from canTradeWith changes when the currentAllocation changes. It might even be good to have one where it changes from true to false, and another for which it changes from false to true.

**Review by Chris-Hibbert — CHANGES_REQUESTED** [review]

File: packages/zoe/src/contractSupport/zoeHelpers.js (hunk 1 above)
Comment (katelynsills) [reply packages/zoe/src/contractSupport/zoeHelpers.js:111]: Sure, sounds good. I can add those.

**Review by Chris-Hibbert — APPROVED** [review]
