### PR TITLE
fix: contractGovernor can change params after contract is upgraded

### LINKED ISSUE #9982: contractGovernor holds contract's paramManager; on upgrade, reference is broken
## Describe the bug

The otherwise reachably durable contract governor holds onto the governed contract's ephemeral paramManager. If the governed contract upgrades, the ephemeral  object turns into a pumpkin.

## To Reproduce

This bit the auctions and vaults coreEval in RC2, necessitating [RC3](https://github.com/Agoric/agoric-sdk/pull/9953).

## Expected behavior

Upgrading the contract shouldn't break its governor.

## Additional context

In [`contractGovernorKit.js`](https://github.com/Agoric/agoric-sdk/blob/d9700fb6ea0e450087bb070ffd90c2f5657a4ffa/packages/governance/src/contractGovernorKit.js#L158C4-L171C3), we check to see if we have a saved version of the paramManager, and use it if we do. If the contract has been upgraded, sending a message to this object will fail. We can catch that error, and call `provideParamGovernance()` again when that happens.
```
        provideParamGovernance() {
          if (!paramGovernance) {
            const { timer } = powers;
            const { creatorFacet, instance } = this.state;
            paramGovernance = setupParamGovernance(
              E(creatorFacet).getParamMgrRetriever(),
              instance,
              timer,
              () => this.facets.helper.getUpdatedPoserFacet(),
            );
          }
          return paramGovernance;
        },
```

### LINKED ISSUE #10172: handle replacing installations in writeCoreEval
## What is the Problem Being Solved?

The ` myContractRef: publishRef(install(...))` idiom works fine for initial deployment of installations. You might think it would work to replace installations. But in [recent experience](https://github.com/Agoric/dapp-orchestration-basics/pull/61), it does not, and lack of `.reset()` in the code below strongly suggests why the limitation.

https://github.com/Agoric/agoric-sdk/blob/442f07c8f0af03281b52b90e90c27131eef6f331/packages/deploy-script-support/src/coreProposalBehavior.js#L168-L170

## Description of the Design

Add `.reset()`.

## Security Considerations

Should improve security by matching behavior better with developer expectations.

Could be a risk if any code is currently relying on the `.resolve()` being a no-op.

## Scaling Considerations

N/A

## Test Plan

A bootstrap test should suffice:
1. boot as usual
2. save the installation
3. run a core proposal to replace it
4. test that the new one is in place

cc @Chris-Hibbert 

## Upgrade Considerations

The `coreProposalBehavior.js` code is _copied_ into each deployment, so there's no need to upgrade previous deployments.

Could be a risk if any code is currently relying on the `.resolve()` being a no-op.

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #9982
closes: #10172

## Description

When a governed contract is upgraded, its paramManager (which was ephemeral) is replaced, and the contractGovernor needs to get a fresh copy.

### Security Considerations

This bug caused us to need to cut RC2 when preparing the vaultFactory release. That time, the fix was to upgrade the contractGovernor when upgrading a governed contract.  

### Scaling Considerations

No scaling impacts.

### Testing Considerations

added a new test, which fails without the fix.

### Upgrade Considerations

This is staged on top of #10074, and the goal is to include it with the priceFeed coreEval. Recent commits have updated the coreEval to include upgrading and installing the contractGovernor code.

### CODE REVIEW

**Comment by dckc** [comment]
What's the upgrade / deployment story?

**Comment by Chris-Hibbert** [comment]
> What's the upgrade / deployment story?

My hope is that we can approve it before the priceFeed coreEval goes out, so the change will be included in any contractGovernors that get upgraded or replaced.

Hmm. that means I'll need a follow-on PR to add installing the code to the priceFeed coreEval. Thanks for asking.

**Comment by dckc** [comment]
> Hmm. that means I'll need a follow-on PR to add ...

does that mean "closes: #9982" should be changed to "refs"?

**Comment by Chris-Hibbert** [comment]
> does that mean "closes: https://github.com/Agoric/agoric-sdk/issues/9982" should be changed to "refs"?

I don't think so. AIUI, we close bug reports when the code that fixes the issue is merged, not when it gets to the chain.

**Comment by dckc** [comment]
My understanding is that merging to master is supposed to include whatever code / tests are necessary to get it on chain.

**Comment by Chris-Hibbert** [comment]
> merging to master is supposed to include whatever code / tests are necessary to get it on chain.

added.

File: packages/builders/scripts/vats/upgradeVaults.js [hunk 1]
```diff
@@ -13,6 +13,12 @@ export const defaultProposalBuilder = async ({ publishRef, install }) =>
             '../bundles/bundle-vaultFactory.js',
           ),
         ),
+        governorRef: publishRef(
+          install(
+            '@agoric/governance/src/contractGovernor.js',
+            '../bundles/bundle-contractGovernor.js',
```
Comment (dckc) [inline packages/builders/scripts/vats/upgradeVaults.js]: Please add a test that this works.

I just ran into at least one case where it does not while working on dapp-orchestration-basics deployment testing. And now I see why. Note the lack of `.reset()` in...

https://github.com/Agoric/agoric-sdk/blob/442f07c8f0af03281b52b90e90c27131eef6f331/packages/deploy-script-support/src/coreProposalBehavior.js#L168-L170

Perhaps an easy 1-line fix. ~~IOU~~ I just made issue. Fixing it in this same PR seems fine.

 - https://github.com/Agoric/agoric-sdk/issues/10172

**Review by dckc — CHANGES_REQUESTED** [review]
Please add a test, if not a fix, for deploying the installation, since it's already `.resolve()`d in `bootstrapPowers.installation.produce`.

**Comment by dckc** [comment]
Also, please include an Upgrade Considerations section in the PR description that goes into the merge commit. @ivanlei recently asked for a list of all the vats that we're upgrading in u17. When u18 or whatever comes around, I want to be able to show that we thought about that list ahead of time. Thanks for adding the **contract-upgrade** label; that will make this easier to find.

File: packages/builders/scripts/vats/upgradeVaults.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/builders/scripts/vats/upgradeVaults.js]: > Please add a test that this works.

Ah, now that I understand #10172, I get that by "works", you mean that it saves the installation to promise space. That had never been part of my mental model of what `publishRef(install()` did, and so most of the time, I manually populated `produce.instance.contract`. 
Now that I get what it's supposed to be doing, I'll ensure that the key matches the one used for the governance installation.

Comment (Chris-Hibbert) [reply packages/builders/scripts/vats/upgradeVaults.js]: commit [7b9e75f](https://github.com/Agoric/agoric-sdk/pull/10163/commits/7b9e75f6b1bb3bcd271ab8c78786a03786748fd6) uses `restoreRef()` to replace a bunch of manual fiddling with bundles and `install()` calls. The line in `coreProposalBehavior.js` is part of the solution.

File: packages/builders/scripts/vats/upgradeVaults.js [hunk 2]
```diff
@@ -7,12 +7,18 @@ export const defaultProposalBuilder = async ({ publishRef, install }) =>
...
             '@agoric/inter-protocol/src/vaultFactory/vaultFactory.js',
             '../bundles/bundle-vaultFactory.js',
           ),
         ),
+        contractGovernorRef: publishRef(
+          install(
+            '@agoric/governance/src/contractGovernor.js',
+            '../bundles/bundle-contractGovernor.js',
+          ),
+        ),
```
Comment (dckc) [inline packages/builders/scripts/vats/upgradeVaults.js:21]: Looks like we're installing the governor from two places. So we'll get 2 installation handles.

Does it matter whether the governor for VaultFactory has an identical installation handle to the one from the auctioneer instance? Does it matter that only one of them can be checked against `agoricNames.installation` to see whether it's the "right" one?

File: packages/inter-protocol/src/proposals/upgrade-vaults.js [hunk 3]
```diff
@@ -149,7 +139,7 @@ export const upgradeVaults = async (
     });
 
     const upgradeResult = await E(kit.adminFacet).upgradeContract(
-      bundleID,
+      VaultFactoryBundle.bundleID,
```
Comment (dckc) [inline packages/inter-protocol/src/proposals/upgrade-vaults.js]: that name is kinda misleading.

I went "whoa! we're putting the whole text of the vault factory contract in there??!?" but then I realized no, it's just a small data structure with a `.bundleID`. The relevant type is `ManifestBundleRef`. A name based on that might be nice: `vaultsBundleRef`.

**Review by dckc — COMMENTED** [review]
I'd like to discuss installation handle identities briefly.

File: packages/builders/scripts/vats/upgradeVaults.js (hunk 2 above)
Comment (dckc) [reply packages/builders/scripts/vats/upgradeVaults.js:21]: We discussed the possibility of only using this mechanism in 1 place and waiting for it in the other. (take care to not just wait for `consume.installation.contractGovernor`, since that's already resolved)

It doesn't seem that either option is catastrophic, so I'll leave it at your discretion.

**Review by dckc — APPROVED** [review]
yay for progress on bug fixes...

File: packages/builders/scripts/vats/upgradeVaults.js (hunk 2 above)
Comment (Chris-Hibbert) [reply packages/builders/scripts/vats/upgradeVaults.js:21]: I made a separate issue: #10248. I'd like to fix it before this gets to the chain, but I think it's second priority, and there's other work to get done.

File: packages/inter-protocol/src/proposals/upgrade-vaults.js (hunk 3 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/proposals/upgrade-vaults.js]: done
