### PR TITLE
fix(vstorage)!: Enforce path validation

### LINKED ISSUE #8337: vstorage module path validation regular expression is incorrect
## Describe the bug
[`pathPattern`](https://github.com/Agoric/agoric-sdk/blob/97cb7158f1176d14b9a8d775328aa826458282ea/golang/cosmos/x/vstorage/types/path_keys.go#L45) is intended to check that a provided path consists _exclusively_ of letters, numbers, underscores, ASCII dashes, and separating periods, but because it lacks anchoring, it actually matches any provided path.

## To Reproduce
This cannot be reproduced from the JS side, because vat-bridge chainStorageNodes have [their own validation](https://github.com/Agoric/agoric-sdk/blob/97cb7158f1176d14b9a8d775328aa826458282ea/packages/internal/src/lib-chainStorage.js#L98-L104).

## Expected behavior
The vstorage module should clearly document constraints on paths, and reject any attempt to use a path that does not conform with them.

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #8337

## Description

Improves the cross-referenced Go and JS documentation of vstorage path structure, and updates the Go code to correctly enforce it.

### Security Considerations

This change means that vat storage keys are no longer generally valid in vstorage paths, but that is acceptable because they are now stored in the swingset module rather than in vstorage.

### Scaling Considerations

There should be a small but largely irrelevant improvement in the performance of validating paths, which are now scanned only once if valid.

### Documentation Considerations

n/a

### Testing Considerations

Nothing should be needed beyond the included unit tests.

### Upgrade Considerations

Existing tests should validate the assumption that vat storage keys are not used in vstorage paths.

### CODE REVIEW

File: golang/cosmos/x/vstorage/types/path_keys.go [hunk 1]
```diff
@@ -42,22 +50,26 @@ func EncodedKeyToPath(key []byte) string {
 	return string(pathBytes)
 }
 
-var pathPattern = regexp.MustCompile(`[-a-zA-Z0-9_` + PathSeparator + `]*`)
+var pathSegmentPattern = `[a-zA-Z0-9_-]+`
+var pathSeparatorPattern = `\` + PathSeparator
+var pathPattern = fmt.Sprintf(`^$|^%[1]s(%[2]s%[1]s)*$`, pathSegmentPattern, pathSeparatorPattern)
+var pathMatcher = regexp.MustCompile(pathPattern)
```
Comment (mhofman) [inline golang/cosmos/x/vstorage/types/path_keys.go:56]: Have we considered instead of building this complex RegExp to split the `path` and validate each segment with an anchored `pathSegmentPattern` ? I'm not sure how efficient golang is at creating string slices.

File: golang/cosmos/x/vstorage/keeper/querier.go [hunk 2]
```diff
@@ -18,14 +16,32 @@ const (
...
+	return requestPathSegments[0], nil
+}
+
+// NewQuerier returns the function for handling queries routed to this module.
+// It performs its own routing based on the first URL slash-separated path segment.
 func NewQuerier(keeper Keeper, legacyQuerierCdc *codec.LegacyAmino) sdk.Querier {
-	return func(ctx sdk.Context, path []string, req abci.RequestQuery) (res []byte, err error) {
-		switch path[0] {
+	return func(ctx sdk.Context, pathSegments []string, req abci.RequestQuery) (res []byte, err error) {
+		switch pathSegments[0] {
```
Comment (mhofman) [inline golang/cosmos/x/vstorage/keeper/querier.go]: Ok this is confusing. I see `pathSegment` is a `/` delimited part of the URL's path. At first I thought it was a `.` delimited vstorage path segment.

I'm not sure how to make this more clear, but right now it isn't sufficiently different. At the very least maybe we should use the "component" nomenclature for vstorage paths? But maybe we could prefix the variables with `route`/`storage` as appropriate here ?

File: golang/cosmos/x/vstorage/types/path_keys.go (hunk 1 above)
Comment (gibson042) [reply golang/cosmos/x/vstorage/types/path_keys.go:56]: It's not bad, but I prefer this single-pass approach.

File: golang/cosmos/x/vstorage/keeper/querier.go (hunk 2 above)
Comment (gibson042) [reply golang/cosmos/x/vstorage/keeper/querier.go]: I've clarified by renaming to better distinguish URL path vs. vstorage entry path.

**Review by mhofman — APPROVED** [review]
Thanks for making these clarifications
