### PR TITLE
test coverage over bundles

### LINKED ISSUE #1817: coverage analysis of bundled code
**Describe the bug**

The coverage tool NYC `yarn test:nyc` produces output that doesn't comport with reality.

**To Reproduce**

checkout on master, running in packages/zoe: 

` yarn test:nyc`
produces 
nyc-zoe

**Expected behavior**

I was a little suspicious of the last line, on `zoeSeat.js`. I set breakpoints on every basic block, and a few other lines, then ran under the debugger (in WebStorm, but your results should be consistent in any debugger.) I ran the tests `test-zoeHelpersWZcf.js`, and `test-zcf.js`, and hit every single breakpoint I had set.

Also notice that the line numbers given as "uncovered" in zoe.js mostly don't correspond to actual code.

### PR DESCRIPTION
**Pull request by turadg**
closes: #1817

## Description
Code coverage for bundles in unit tests!

### Security Considerations
none

### Scaling Considerations
none

### Documentation Considerations
none

### Testing Considerations
per se

### Upgrade Considerations
none

### CODE REVIEW

File: packages/zoe/tools/setup-zoe.js [hunk 1]
```diff
@@ -61,12 +61,31 @@ export const setUpZoeForTest = async ({
...
+  const bundleAndInstall = async pathOrExports => {
+    await null;
+    let id;
+    let bundle;
+    if (typeof pathOrExports === 'string') {
+      const path = pathOrExports;
+      bundle = await bundleSource(path);
+      id = `b1-${path}`;
+    }
+    {
```
Comment (Chris-Hibbert) [inline packages/zoe/tools/setup-zoe.js]: Is this supposed to be an `else`?

File: packages/zoe/tools/setup-zoe.js [hunk 2]
```diff
@@ -61,12 +61,31 @@ export const setUpZoeForTest = async ({
...
+      assert.equal(
+        Object.prototype.toString.call(pathOrExports),
+        '[object Module]',
+      );
```
Comment (mhofman) [inline packages/zoe/tools/setup-zoe.js]: An equivalent would be to `getOwnPropertyDescriptor(pathOrExports, Symbol.toStringTag)` and verify its value is `Module`

File: packages/zoe/tools/setup-zoe.js [hunk 3]
```diff
@@ -61,12 +61,31 @@ export const setUpZoeForTest = async ({
...
+      // Copy all the properties so this object can be hardened.
+      const exports = { ...pathOrExports };
+      bundle = harden({
+        moduleFormat: 'test',
+        [Symbol.for('exports')]: exports,
+      });
```
Comment (mhofman) [inline packages/zoe/tools/setup-zoe.js]: Why not use [`bundleTestExports`](https://github.com/endojs/endo/pull/2735/files#diff-b93764e4d9804500e1cd218013ddf54177d51099601d766a974c5a11151c13fdR182-R190) ?

File: packages/zoe/tools/setup-zoe.js [hunk 4]
```diff
@@ -61,12 +61,31 @@ export const setUpZoeForTest = async ({
...
+      id = `b1-test-exports-${Math.random()}`;
```
Comment (mhofman) [inline packages/zoe/tools/setup-zoe.js]: Interesting, this will also ensure that `bundleAndInstall` is only used from the privileged start compartment.

File: packages/zoe/tools/setup-zoe.js (hunk 1 above)
Comment (turadg) [reply packages/zoe/tools/setup-zoe.js]: indeed

**Comment by mhofman** [comment]
> Draft until this doesn't have to patch Endo (next Endo rev )

I'd like to emphasize this one. The next Endo version introduces a revamped bundler, and maintaining coverage through the endo sync will be invaluable for @kriskowal

File: packages/zoe/tools/setup-zoe.js [hunk 5]
```diff
@@ -61,13 +63,40 @@ export const setUpZoeForTest = async ({
...
+      return bundleSource(path);
+    } else {
+      assert.equal(
+        Object.getOwnPropertyDescriptor(pathOrExports, Symbol.toStringTag)
+          ?.value,
+        'Module',
+      );
+      // Copy all the properties so this object can be hardened.
+      const exports = { ...pathOrExports };
+      return bundleTestExports(exports);
```
Comment (mhofman) [inline packages/zoe/tools/setup-zoe.js:81]: Does anyone harden the returned bundle?

File: patches/@endo+import-bundle+1.3.3.patch
Comment (mhofman) [inline patches/@endo+import-bundle+1.3.3.patch:1]: FYI the version that ended up landing is quite a bit different.

**Review by kriskowal — COMMENTED** [review]
@turadg It’s *fantastic* we can get coverage analysis for contracts this way. Do you feel that, after this change, we still have an adequate canary for changes the contract that will only be evident if it’s bundled, like runtime censorship errors?

I’ve filed a work item for Endo, to make the bundler do a SES censorship simulation after transforms, such that the act of bundling in CI would detect that failure mode without having to execute the bundle.
https://github.com/endojs/endo/issues/2756

That might be enough.

**Comment by turadg** [comment]
> Do you feel that, after this change, we still have an adequate canary for changes the contract that will only be evident if it’s bundled, like runtime censorship errors?

Yes, this is just letting us integrate with a fake Zoe and we have a more integration levels above this.

1. Boostrap/RunUtils with a testing SwingSet, but all the vats and real bundles
2. a3p-integration with a real agoric chain

File: packages/zoe/tools/setup-zoe.js (hunk 5 above)
Comment (turadg) [reply packages/zoe/tools/setup-zoe.js:81]: not presently.

https://github.com/endojs/endo/blob/84716b7fb874f790000b96953ef6fe194c4a2f85/packages/import-bundle/src/index.js#L213-L223

If you think that's necessary I'd request that it be done in ^ so the current example code suffices:
https://github.com/endojs/endo/blob/84716b7fb874f790000b96953ef6fe194c4a2f85/packages/import-bundle/README.md?plain=1#L81-L82

**Comment by mhofman** [comment]
> > Do you feel that, after this change, we still have an adequate canary for changes the contract that will only be evident if it’s bundled, like runtime censorship errors?
> 
> Yes, this is just letting us integrate with a fake Zoe and we have a more integration levels above this.

Catching early would still be better, so https://github.com/endojs/endo/issues/2756 would be a nice to have

File: packages/swing-store/src/bundleStore.js [hunk 6]
```diff
@@ -9,11 +9,9 @@ import { Nat } from '@endo/nat';
 import { createSHA256 } from './hasher.js';
 
 /**
- * @typedef { { moduleFormat: 'getExport', source: string, sourceMap?: string } } GetExportBundle
- * @typedef { { moduleFormat: 'nestedEvaluate', source: string, sourceMap?: string } } NestedEvaluateBundle
- * @typedef { { moduleFormat: 'endoZipBase64', endoZipBase64: string, endoZipBase64Sha512: string } } EndoZipBase64Bundle
- * @typedef { EndoZipBase64Bundle | GetExportBundle | NestedEvaluateBundle } Bundle
+ * @import {Bundle, EndoZipBase64Bundle} from '@agoric/swingset-vat/src/types-external.js';
```
Comment (mhofman) [inline packages/swing-store/src/bundleStore.js]: I know this is types only, but I'd prefer if swing-store kept no dependency on SwingSet. Can we import from `@endo` instead ?

File: packages/swing-store/test/bundles.test.js [hunk 7]
```diff
@@ -9,6 +9,10 @@ import { makeSwingStoreExporter } from '../src/exporter.js';
 import { importSwingStore } from '../src/importer.js';
 import { buffer } from '../src/util.js';
 
+/**
+ * @import {Bundle} from '@agoric/swingset-vat/src/types-external.js';
```
Comment (mhofman) [inline packages/swing-store/test/bundles.test.js]: Slightly less qualms with tests, but would prefer a dependency on endo instead.

File: packages/swing-store/test/bundles.test.js [hunk 8]
```diff
@@ -19,7 +23,7 @@ test('b0 format', t => {
   const { kernelStorage } = initSwingStore();
   const { bundleStore } = kernelStorage;
 
-  /** @type {import('../src/bundleStore.js').Bundle} */
+  /** @type {any} */
```
Comment (mhofman) [inline packages/swing-store/test/bundles.test.js]: Why do those require switching to any?

File: packages/zoe/tools/fakeVatAdmin.js [hunk 9]
```diff
@@ -139,17 +139,28 @@ function makeFakeVatAdmin(testContextSetter = undefined, makeRemote = x => x) {
...
       if (idToBundleCap.has(id)) {
-        assert.equal(
-          bundle.endoZipBase64,
-          bundleCapToBundle.get(idToBundleCap.get(id)).endoZipBase64,
-        );
+        const extant = bundleCapToBundle.get(idToBundleCap.get(id));
+        assert(extant);
+        assert.equal(bundle.moduleFormat, extant.moduleFormat);
+        if (
+          // TS doesn't infer that the equal above implies one of these is redundant
```
Comment (mhofman) [inline packages/zoe/tools/fakeVatAdmin.js]: That would be a really smart inference if it could do that!

File: packages/zoe/tools/setup-zoe.js (hunk 5 above)
Comment (mhofman) [reply packages/zoe/tools/setup-zoe.js:81]: I think my question is can we get away with dropping the spread if no code would harden the bundle.

If there is such code, then my question for @kriskowal is whether `bundleTestExports` should create a getter for the `Symbol.for('exports')` property instead of a data property so that it's compatible with hardening? That should be a compatible change. It will not make the bundle passable but that is just not possible with this design.

File: packages/swing-store/test/bundles.test.js (hunk 8 above)
Comment (turadg) [reply packages/swing-store/test/bundles.test.js]: because they weren't handling all the kinds of `Bundle`. it's a test so the typecheck wasn't adding detection

File: packages/zoe/tools/fakeVatAdmin.js (hunk 9 above)
Comment (turadg) [reply packages/zoe/tools/fakeVatAdmin.js:152]: [close](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABAQwM6oKYCcoFECOIyANgDwCCAfABTIBci5ANIgEYPgDWYcA7mAEoGaTDlRtEMceUQBvAFCJJwRLUQBCALya2AuYqWIoACyx9EYDL0S4sZrNQAG5dNlgJEwZDGIYAJgwAJLLIAL4a2ojBrKGOAgDcBqHyyRAIqFCIxjCIOgDk2XmJaWAZiKhwALYYJjBgAOYcYNx8SPmFifIA9F2IAAJQqAC0GAAeAA4Y0CN2cFjyFdW1DQB0vg0mnSJuBETE1NksizXZDQnyC1UndfVrGBvGiUA)

File: packages/swing-store/src/bundleStore.js (hunk 6 above)
Comment (turadg) [reply packages/swing-store/src/bundleStore.js]: I did a time boxed improvement. If this isn't acceptable I'll omit the commit from this PR.

Comment (turadg) [reply packages/swing-store/src/bundleStore.js]: I've omitted it since it's not necessary for the issue. I kept the commit if you want to land it separately

File: packages/zoe/tools/fakeVatAdmin.js (hunk 9 above)
Comment (turadg) [reply packages/zoe/tools/fakeVatAdmin.js]: just needed a small tweek

File: packages/swing-store/src/bundleStore.js (hunk 6 above)
Comment (mhofman) [reply packages/swing-store/src/bundleStore.js]: Why not duplicate the definitions from `@agoric/swingset-vat` instead of importing them?

Comment (turadg) [reply packages/swing-store/src/bundleStore.js]: Because duplicates can get out of sync with each other, misleading the developer and causing surprise type errors

File: packages/zoe/tools/setup-zoe.js (hunk 5 above)
Comment (mhofman) [reply packages/zoe/tools/setup-zoe.js:81]: Given that this doesn't hurt, and is probably helpful (no-one should expect a live binding here), I'm ok with keeping the spread here.

**Review by mhofman — APPROVED** [review]
Thanks for getting us this coverage!

File: packages/orchestration/test/examples/stake-ica.contract.test.ts [hunk 10]
```diff
@@ -13,11 +13,9 @@ import { maxClockSkew } from '../../src/utils/cosmos.js';
 import { UNBOND_PERIOD_SECONDS } from '../ibc-mocks.js';
 import { commonSetup } from '../supports.js';
 
-const dirname = path.dirname(new URL(import.meta.url).pathname);
+import * as contractExports from '../../src/examples/stake-ica.contract.js';
```
Comment (Chris-Hibbert) [inline packages/orchestration/test/examples/stake-ica.contract.test.ts:16]: Why doesn't `import path from 'path';` get dropped here and in most, if not all of these files?

**Review by Chris-Hibbert — APPROVED** [review]

File: packages/orchestration/test/examples/stake-ica.contract.test.ts (hunk 10 above)
Comment (turadg) [reply packages/orchestration/test/examples/stake-ica.contract.test.ts:16]: Because unused imports aren't automatically cleaned up. It's passing CI because there's no lint rule for it.

I would expect `no-unused-vars` to but it's not. `typescript-eslint/no-unused-vars` works but isn't worth the effort to adopt rn, imo. Maybe updating eslint will fix the built in one.

`noUsedLocals` in tsconfig would catch it but make it harder to work with jsdoc `@import`.
