### PR TITLE
fix(auction): handle auction waking a little bit late gracefully

### LINKED ISSUE #7677: Bug: Liquidation auction fails to run
## Describe the bug
Have observed this bug twice now.  

Set up Vaults to liquidate based on a decline in price
At liquidation time, UI shows vaults entering liquidating state.  Dashboard shows correct amount of collateral available for auction
However, no updates are available about the current auction price from the CLI or in the dashboard
Bids that should have been picked up weren't

Seems like some issue in handoff between vault manager and auction but not clear.

Both times, vaults successfully liquidated (and auction ran) at the next scheduled time.

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
fixes: #7677 

## Description

When the auction's timer wakes it a little bit late (which has happened multiple times while testing), the auctioneer should handle it cleanly. If it's less than 5 minutes late, continue with the auction, possibly missing some descending steps. If it's more than 5 minutes late, call it a loss and skip to the next one.

### Security Considerations

None

### Scaling Considerations

None

### Documentation Considerations

If the chain is under heavy load, the auction will try to recover gracefully, but individual auctions can be interrupted or skipped.

### Testing Considerations

Added a new test that drives the scheduler to these obscure cases.

### CODE REVIEW

**Comment by Chris-Hibbert** [comment]
Sorry, @warner. I accidentally clicked your name, and then github didn't let me deselect you as a reviewer until I made the PR. No need for your review here.

File: packages/inter-protocol/src/auction/scheduler.js [hunk 1]
```diff
@@ -218,28 +221,37 @@ export const makeScheduler = async (
...
-      console.warn(
-        `Auction time jumped to ${q(now)} before next scheduled start ${q(
-          nextSchedule.startTime,
-        )}. Skipping that round.`,
-      );
-      nextSchedule = computeRoundTiming(params, now);
+      const late = TimeMath.subtractAbsAbs(now, nextSchedule.startTime);
+      const maxLate = relativeTime(MAX_LATE_TICK);
+
+      debugger;
```
Comment (turadg) [inline packages/inter-protocol/src/auction/scheduler.js]: remove debugger before merge

**Review by turadg — APPROVED** [review]
