### PR TITLE
fix: move the assertion that `allStagedSeatsUsed` into `reallocate`

### LINKED ISSUE #3613: Bug: `zcfMint.mintGains` wrongly errors if any seats have staged allocations
## Describe the bug
Working with @tgrecojs on #3226, we discovered that Zoe has a bug in which `zcfMint.mintGains` will error if any seat has any staged allocations. This is because `mintGains` calls `reallocateInternal` to add the newly minted amount to a seat. However, we should really only be checking that all staged allocations are included when `zcf.reallocate(...` is called. We do not intend for `mintGains` to be reallocating over multiple seats, and in fact there's no way to do so. 

## To Reproduce
1. Write a contract with an offerHandler with a seat with a stagedAllocation
2. Create a `zcfMint` 
3. Call `zcfMint.mintGains`
4. The offerHandler will error with the message `At least one seat has a staged allocation but was not included in the call to reallocate` in line 147 of zcfSeat.js.

## Expected behavior
`zcfMint.mintGains` should *not* check that `allStagedSeatsUsed`. This means that `reallocateInternal` should not check `allStagedSeatsUsed`, and this should be moved to `reallocate` before it calls `reallocateInternal`.

### PR DESCRIPTION
**Pull request by katelynsills**
This PR fixes a bug (#3613) in Zoe. The assertion `allStagedSeatsUsed` needs to be in `reallocate` rather than `reallocateInternal`, because `zcfMint.mintGains` calls `reallocateInternal`, and we should not assert that all staged seats are being used when `mintGains` is called.

Closes #3613

### CODE REVIEW

File: packages/zoe/src/contractFacet/zcfSeat.js [hunk 1]
```diff
@@ -124,7 +124,7 @@ export const createSeatManager = (
     seats.forEach(assertStagedAllocation);
 
     // Keep track of seats used so far in this call, to prevent aliasing.
-    const zcfSeatsSoFar = new WeakSet();
+    const zcfSeatsSoFar = new Set();
```
Comment (erights) [inline packages/zoe/src/contractFacet/zcfSeat.js:127]: Good. (Somehow I thought this had already been fixed. Was there a similar fix elsewhere?)

**Review by erights — APPROVED** [review]
LGTM

File: packages/zoe/src/contractFacet/zcfSeat.js (hunk 1 above)
Comment (katelynsills) [reply packages/zoe/src/contractFacet/zcfSeat.js:127]: I think ERTP is now using a set for anti-aliasing, whereas some months ago it wasn't
