### PR TITLE
cache the collection schema, only read from vatstore once per crank

### LINKED ISSUE #6360: syscall sensitivity to GC of virtual collection objects and timing of organic GC
While we're pretty sure that userspace code cannot sense GC activity, we were also trying to make sure that the syscalls a vat worker emits were not sensitive to GC (to preserve our ability to have different GC timing among different validators, or different heap snapshot schedules, or upgrades, or something).

I noticed a few weeks ago that one such sensitivity has snuck in. If a virtual collection Representative (e.g. the object returned by `makeScalarBigMapStore()`) is both held in RAM and stored as the property of a virtual object, it will have a vref, and `slotToVal.get(vref)` will be a populated ("full") `WeakRef` that points to the Represenative. We call this state "REACHABLE" in our GC design documentation. If that RAM reference is dropped (moving the Representative to the "UNREACHABLE" state), the WeakRef is still populated until a GC event occurs. After the GC event, the Representative is "COLLECTED", and the WeakRef is empty (`slotToVal.get(vref).deref() === undefined`). (there is also a FinalizationRegistry watching the Represenative, and when that fires it would move to "FINALIZED", but we buffer the finalization results until a `dispatch.bringOutYourDead` delivery, so that's not the source of the sensitivity).

GC events happen spontaneously whenever the JS engine wants a new `struct slot` and can't find one in the free pool. We call this "organic GC", and the timing of it depends very closely upon the code that is running: every function call or temporary JS object needs a few slots, so simply inserting a `const ignored = 0;` in the code would temporarily allocate a few, making organic GC happen a little bit earlier than it would have otherwise. We force GC during `bringOutYourDead`, but that doesn't prevent organic GC from happening before that point (although it might defer the next one until later).

If some subsequent code then reaches into the virtual object and retrieves the collection from it, liveslots must provide a Representive for the caller. The deserialization code looks at `slotToVal` to see if we already have one in RAM. If so, it does `slotToVal.get(vref).deref()` to return the old one. If not, a "reanimation" function is called to make a new Representative. This is true for all virtual objects, even user-defined ones, not just collections.

But what's different about the collection's reanimation function is that it does a `vatstoreGet()` to fetch the `|schemata` and `|label` keys:

https://github.com/Agoric/agoric-sdk/blob/9f75b0e840c151c36b46150451e3c74860a90710/packages/SwingSet/src/liveslots/collectionManager.js#L951-L959

As a result, in a vat which has performed organic GC after the UNREACHABLE transition, we'll observe a pair of `syscallvatstoreGet`s that are missing from a vat that started out with the same userspace state but which hasn't done organic GC yet.

That sensitivity isn't a huge problem, and I'm not sure we can easily get rid of it, but it's something to keep in mind. We're no longer really convinced that we can tolerate variations in GC timing anyways, but we've avoided doing anything that obviously breaks that tolerance.

The code reads `|schemata` so it can unserialize the `keyShape` and `valueShape` patterns which enforce that keys/values match a particular schema. We need these before we can accept gets/sets on the collections. And it reads `|label` to get a string that can be added to the error messages when those shape enforcement checks fail.

At one point, I think I made the assumption that the number of collections in use would be small (they could hold an arbitrary number of entries, but in a small number of collections), and thus holding the schema in RAM would be ok, but I've realized that nobody else made this assumption: ERTP creates a new collection for every Purse, both of which are durable:

https://github.com/Agoric/agoric-sdk/blob/9f75b0e840c151c36b46150451e3c74860a90710/packages/ERTP/src/purse.js#L31-L41

and the virtual collection code correctly avoids consuming any RAM for collection Representatives that are not currently `REACHABLE` in RAM.

I can't think of any way to avoid doing those reads without changing the rules ("stop using lots of collections, because they're going to cost RAM even if they aren't currently `REACHABLE`"). But this ticket can serve as a place to collect ideas in case we think of something new in the future

### LINKED ISSUE #7142: GC syscall sensitivity through reanimate and reanimateDurableKindID
## Describe the bug

I think I found another two ways in which syscalls are sensitive to GC activity. I've got a fast (non-kernel-based) test for them as well.

The first arises when `reanimateDurableKindID` is used to regenerate a KindHandle (i.e. deserializing one while pulling it out of a virtual or durable MapStore). To build the Representative, we must read the `durableKindDescriptor` out of the vatstore. If the deserialization is able to re-use an existing Representative, the `syscall.vatstoreGet()` won't happen:

https://github.com/Agoric/agoric-sdk/blob/2e333069005f63468bfca25b8ee1281ce2aeabbe/packages/swingset-liveslots/src/virtualObjectManager.js#L927-L931

The second arises when `reanimate` is used to regenerate a normal Kind instance's Representative. Same issue, this time `reanimate` calls `makeRepresentative()`:

https://github.com/Agoric/agoric-sdk/blob/2e333069005f63468bfca25b8ee1281ce2aeabbe/packages/swingset-liveslots/src/virtualObjectManager.js#L795-L798

which calls `ensureState()`:

https://github.com/Agoric/agoric-sdk/blob/2e333069005f63468bfca25b8ee1281ce2aeabbe/packages/swingset-liveslots/src/virtualObjectManager.js#L712-L718

whose `cache.lookup(.., true)` will cause the LRU cache to do a `vatstoreGet` to read the state data if it isn't already in the cache.

The issue I'm looking at is that `makeRepresentative` is called only when GC has happened and deserialization fails to find a Representative in the `slotToVal` weakref. Imagine a virtual object that is created and stored in baggage during step 1, but is then dropped from userspace (it becomes UNREACHABLE). Then time passes, and we look at two cases. In case A, GC happens, moving it to COLLECTED and FINALIZED, removing it from `slotToVal`. In case B, GC does not happen, leaving it in UNREACHABLE. Then, in step 2, something reads the value out of baggage again.

In case A, the deserialization in step2 fails to find the vref, so `reanimate()` is called to build a replacement, which calls `makeRepresentative`. If the state had fallen out of the LRU cache, this will cause a `vatstoreGet` to fetch the state data. In case B, `renimate()` is *not* called, and no `vatstoreGet` will happen.

I think our testing might not have managed to evict the state data from the cache, so we missed this case. Also, we don't have a lot of mock-the-GC tests: `test-liveslots.js` has the necessary mocks for WeakRef and FinalizationRegistry, but they weren't exported or put in a shared library, so no other tests were using those tools.

Incidentally, the presence or absence of the state data in the cache is deterministic function of the sequence of calls to the LRU cache, like `lookup` and `refresh`, which are driven by (deterministic) calls to the `state` object's getters and setters, but also by calls to `makeRepresentative`. If `makeRepresentative` is called with GC sensitivity, then the LRU cache contents will be GC-sensitive, adding another variable to the "will vatstore reads happen or not" question. I think we convinced ourselves that the determinism of getters and setters made this safe, without realizing that `reanimate` itself could be a source of trouble.

I've written a new test to exercise this, on the [7142-gc-sensitivity branch](https://github.com/Agoric/agoric-sdk/tree/7142-gc-sensitivity), which compares the syscalls made by case A and case B, and asserts that they are equal. Those tests currently fail, with an extra `vatstoreGet` appearing in case A.

### PR DESCRIPTION
**Pull request by warner**
This changes the collectionManager to keep the per-collection
metadata (keyShape, valueShape, label) in a cache. Like the VOM's
dataCache, this `schemaCache` is populated at most once per crank, and
flushed at the end of every crank. This removes the GC-sensitive
syscalls that used to fetch the metadata when userspace caused a
collection to be reanimated. Instead, the cache is read when userspace
invokes a collection method that needs the data (most of them, to
validate keys or values), regardless of whether the collection
Representative remains in RAM or not.

It also removes the now-unused in-RAM list of all collections, which used to support `deleteAllVirtualCollections`, called from `stopVat`.

closes #6360 
refs #5058 
closes #7142

### CODE REVIEW

**Comment by warner** [comment]
@FUDCo the last commit changes the serialized `|schemata` value from `[keyShape, valueShape]` to `{ keyShape, valueShape }` (from array to object/record). I thought that make future extensions more straightforward, but I could be talked out of it, especially since it grows the stored size slightly (it's storing an explicit `undefined` for both, but maybe we should change that, by building up the serialized object one property at a time). I'm moderately sure that there's no functional difference between e.g. `{ keyShape, valueShape: undefined }` and just `{ keyShape }`.

So two questions for you to think about:
* avoid storing values of `undefined` in the record?
* record vs array?

A performance note: this approach does either zero or one reads of `|schemata` and `|label` per collection per crank, triggered by pretty much any collection method (since nearly all of them want to validate against `keyShape`). The schemata it reads is flushed at end-of-crank. This makes the syscall trace deterministic, but I'd respect an argument that once-per-crank is too frequent. The next most logical thing to do would be to hold them across multiple cranks, until a BOYD flushes the cache. That frequency felt too slow (i.e. too high RAM usage) for the VOM `dataCache`, but the virtual-collection `schemaCache` holds a lot less data, so we might choose a different tradeoff.

@mhofman this ought to remove the gc-sensitivity due to collections being collected and then reanimated. And #7138 removed another. I think there's one known source of sensitivity for me to try to fix, involving KindHandles being reanimated (the other part of #7142).

**Comment by warner** [comment]
oops, something is still broken, will re-submit when ready

**Comment by warner** [comment]
Ok I went ahead and changed the serialized schemata object to be empty if there were no keyShape/valueShape constraints given. In practice, there's always a keyShape, because the default is `M.scalar()`, but this still saves some space in the serialized form when `valueShape = undefined` (which is really common)

I'm storing `schemataCD` (capdata) in the cache. This isn't obviously useful for this PR, but there's another one stacked up on top of it (#7334, for #7321) that needs the `.slots` to do refcounting on.

**Comment by mhofman** [comment]
> I went ahead and changed the serialized schemata object to be empty if there were no keyShape/valueShape constraints given

Quick question: is there any reason not to merge the schemata and label vatStore entries into a single one? Especially now that we have a record for the schemata.

**Comment by warner** [comment]
> > I went ahead and changed the serialized schemata object to be empty if there were no keyShape/valueShape constraints given
> 
> Quick question: is there any reason not to merge the schemata and label vatStore entries into a single one? Especially now that we have a record for the schemata.

I think that'd be fine. We've got two mutable metadata keys (`|entryCount`, updated each time we add/remove something from a collection, and `|nextOrdinal`, incremented when we add a new vref-based key), and two immutable ones (`|label` and `|schemata`). We'll want to keep the mutable ones as they are, they have different "temperatures". But merging all the immutables ones makes sense, and then naming them something closer to `|info`.

 @FUDCo can you remember why they were split?

**Comment by FUDCo** [comment]
> @FUDCo can you remember why they were split?

I don't think there was a deep reason.  Mainly, I think, to avoid having to parse the value to separate two relatively unrelated pieces of information from each other.

**Comment by warner** [comment]
Cool, thanks. Ok, now that we're reading them both at the same time (schemata, to build the keyShape/valueShape checkers, and label, to build the error messages emitted if those checkers fail), it'll save a vatstore read to merge them together. I'll add a commit to do that.

File: packages/swingset-liveslots/src/collectionManager.js [hunk 1]
```diff
@@ -48,6 +49,58 @@ function throwNotDurable(value, slotIndex, serializedValue) {
...
+ * @property {Pattern} keyShape
+ * @property {Pattern} valueShape
+ * @property {string} label
+ * @property {object} schemataCD
+ */
+
+/*
+ * Build a cache that holds the schema for each collection.
+ *
+ * The cache maps colectionID to { keyShape, valueShape, label
```
Comment (FUDCo) [inline packages/swingset-liveslots/src/collectionManager.js]: Typo: "colection" -> "collection"

File: packages/swingset-liveslots/src/collectionManager.js [hunk 2]
```diff
@@ -48,6 +49,58 @@ function throwNotDurable(value, slotIndex, serializedValue) {
...
+ * inside two keys, one for the [keyShape, valueShape] schemata,
+ * another for the label.
+ */
+function makeSchemaCache(syscall, unserialize) {
+  /** @type {(collectionID: string) => SchemaCacheValue} */
+  const readBacking = collectionID => {
+    // this is only called once per crank
+    const schemataKey = prefixc(collectionID, '|schemata');
+    const schemataValue = syscall.vatstoreGet(schemataKey);
+    const schemataCD = JSON.parse(schemataValue);
```
Comment (FUDCo) [inline packages/swingset-liveslots/src/collectionManager.js]: I don't understand `CD` in the name.

File: packages/swingset-liveslots/src/collectionManager.js [hunk 3]
```diff
@@ -48,6 +49,58 @@ function throwNotDurable(value, slotIndex, serializedValue) {
...
+    const { keyShape, valueShape } = unserialize(schemataCD);
+    const labelKey = prefixc(collectionID, '|label');
+    const label = syscall.vatstoreGet(labelKey);
+    return harden({ keyShape, valueShape, label, schemataCD });
+  };
+  /** @type {(collectionID: string, value: SchemaCacheValue) => void } */
+  const writeBacking = (collectionID, value) => {
+    const { label, schemataCD } = value;
+    const schemataKey = prefixc(collectionID, '|schemata');
+    const schemataValue = JSON.stringify(schemataCD);
```
Comment (FUDCo) [inline packages/swingset-liveslots/src/collectionManager.js]: Why return `keyShape`, `valueShape`, AND `schemataCD` from the read but stringify `schemataCD` in the write?  If the consumer needs the shapes, having the `schemataCD` doesn't help, and when writing the producer (presumably) generates the `keyShape` and `valueShape` values and shouldn't concerned with how they're encoded.  Am I missing something here?

File: packages/swingset-liveslots/src/collectionManager.js [hunk 4]
```diff
@@ -647,48 +682,39 @@ export function makeCollectionManager(
...
 
     const doMoreGC = collection.clearInternal(true);
-    for (const dbKey of enumerateKeysWithPrefix(syscall, prefixc(subid, '|'))) {
+    for (const dbKey of enumerateKeysWithPrefix(
+      syscall,
+      prefixc(collectionID, '|'),
+    )) {
+      if (dbKey.endsWith('|schemata') || dbKey.endsWith('|label')) {
+        continue; // will be deleted when schemaCache is flushed
+      }
```
Comment (FUDCo) [inline packages/swingset-liveslots/src/collectionManager.js]: I think I understand why you're doing this, but it still seems kinda weird and off.

File: packages/swingset-liveslots/src/liveslots.js [hunk 5]
```diff
@@ -1499,7 +1499,8 @@ function build(
   async function bringOutYourDead() {
     await scanForDeadObjects();
     // now flush all the vatstore changes (deletions) we made
-    vom.flushStateCache();
+    // eslint-disable-next-line no-use-before-define
+    afterDispatchActions();
```
Comment (FUDCo) [inline packages/swingset-liveslots/src/liveslots.js:1543]: Won't the normal dispatch flow call `afterDispatchActions` also?

**Review by FUDCo — COMMENTED** [review]
I think this is OK, but there are a few points I'm unclear on that I'd like to be clear on before approving.

File: packages/swingset-liveslots/src/collectionManager.js (hunk 2 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js]: Short for capdata. I'll expand it to `schemataCapData`.

File: packages/swingset-liveslots/src/collectionManager.js (hunk 3 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js]: This is preparation for #7321  (PR #7334), which needs to know about any slots (vrefs) in the serialized keyShape/valueShape. When the collection is deleted, rather than re-serialize those values (to learn the vrefs, so we can feed them to `vrm.removeReachableVref`, to decrement their refcounts), we keep the original serialized forms around. The memory overhead of retaining the serialized capdata is pretty small, and it didn't occur to me to trust that serialization would return the same values as the original.. felt more appropriate to retain the original instead.

The only time we write to the `schemaCache` is when a collection is first created, and at that time we also have the serialized capdata available (again, as anticipation for #7334, which needs to *increment* refcounts for everything therein).

File: packages/swingset-liveslots/src/collectionManager.js (hunk 4 above)
Comment (warner) [reply packages/swingset-liveslots/src/collectionManager.js]: Yeah, true. The `schemaCache` owns those two keys, but there are others (`|nextOrdinal` and `|entryCount`), and they need to be deleted too.

I wanted to keep the PR minimal, but one option that might be cleaner would be to have `schemaCache` own *all* the metadata keys (and maybe call it something else, `collectionMetadataCache`?). We could put all the values in a single DB key, and have the cache read them all. In that approach, we'd write to the cache more often (any time `init` or `set` introduced a new ordinal/Remotable, or any time `init` or `delete` changed the `entryCount`), and at the end of each of those cranks, we'd write out all of them. But it seemed better to separate the "hot" keys (`|nextOrdinal` and `|entryCount`) from the "cold" / immutable-after-creation ones.

I'll add a bit more explanation to the comment.

File: packages/swingset-liveslots/src/liveslots.js (hunk 5 above)
Comment (warner) [reply packages/swingset-liveslots/src/liveslots.js:1543]: I thought so too, but our `dispatch` treats BOYD and `stopVat` specially, and doesn't route them through the same code path, so they don't get an `afterDispatchActions`:

```js
  async function dispatch(delivery) {
    if (delivery[0] === 'bringOutYourDead') {
      return meterControl.runWithoutMeteringAsync(bringOutYourDead);
    } else if (delivery[0] === 'stopVat') {
      return meterControl.runWithoutMeteringAsync(() => stopVat(delivery[1]));
    } else {
      let complete = false;
      const p = Promise.resolve(delivery).then(unmeteredDispatch);
      p.finally(() => (complete = true));
      return gcTools.waitUntilQuiescent().then(() => {
        afterDispatchActions();
        return complete ? p : Promise.reject('buildRootObject unresolved');
      });
    }
  }
```

The two code paths are sufficiently different that I don't see an obvious way to merge them.

I'll add a comment explaining why it's necessary.

**Review by FUDCo — APPROVED** [review]
Well OK then
