### PR TITLE
repair transfer timeout tests

### LINKED ISSUE #11026: Orchestration tests have unhandled vow rejections
## Describe the bug
While working on #10686 (convert unhandled vow rejections to unhandled promise rejections), we discovered that a few orchestration tests started to fail with unhandled promise rejections.

## To Reproduce
1. Search for the use of `expectUnhandled(` in test files of `agoric-sdk/packages/orchestration`.
2. You'll find it used in a few places:
```
$ cd agoric-sdk/packages/orchestration
$ rg 'expectUnhandled\('
test/exos/local-orchestration-account-kit.test.ts
118:test(expectUnhandled(1), 'transfer', async t => {

test/examples/staking-combinations.test.ts
35:test(expectUnhandled(1), 'start', async t => {

test/examples/send-anywhere.test.ts
260:test(expectUnhandled(1), 'failed ibc transfer returns give', async t => {
$
```
3. If you run those tests individually, unhandled promise rejections are reported by AVA.
4. The use of `expectUnhandled` allows the tests to return success, even though AVA would normally fail.

I would expect these calls to the `expectUnhandled(N)` macros to be unnecessary.

## Platform Environment
 - what OS are you using? what version of Node.js? Agoric CI
 - is there anything special/unusual about your platform? Yes, it's CI
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`) a version that has #10686 merged in it

### PR DESCRIPTION
**Pull request by 0xpatrickdev**
closes: #11026

## Description
The primary goal of this PR is to repair three tests that have unhandled vow rejections. To simulate a timeout, tests incorrectly relied on the `vlocalchain` to reject `MsgTransfer` requests for a certain amount (`504n`).  This pattern failed to simulate `vtransfer` side of things which is needed to settle the `.transfer()` vow from `LocalOrchestrationAccount`. These tests now inbound a `timeoutPacket` event for the corresponding outgoing `MsgTransfer` (denoted by `sequence`) to properly reject the vow.

Along the way, types in `ibc-packet.js` and `packet-tools.js`  were improved and a small fix was applied to how `PacketOptions` are passed through vow context. `ibcResultWatcher` was also fixed to not expect an `acknowledgement` string when a `timeoutPacket` is received. A default value of 'transfer' was also set for `opName` instead of 'unknown' since a default is not expressed anywhere.

### Security Considerations
None

### Scaling Considerations
None

### Documentation Considerations
Through tests, properly documents how to test timeouts and acknowledgement errors for `MsgTransfer` sent from `LocalOrchestrationAccount`s.

### Testing Considerations
Repairs tests that broke after #10686. Adds new testing patterns for `timeoutPacket`s and `acknowledgePacket`s with  acknowledgement errors.

### Upgrade Considerations
Changes library code in Orchestration SDK that will be pulled in during the next Orchestration application release (FastUSDC). Does not change `vat-orchestration` code.

### CODE REVIEW

File: packages/orchestration/tools/ibc-mocks.ts [hunk 1]
```diff
@@ -207,12 +209,19 @@ export const buildVTransferEvent = ({
...
   blockTime: 0,
   event,
-  acknowledgement: btoa(JSON.stringify({ result: 'AQ==' })),
+  acknowledgement: btoa(
+    JSON.stringify(
+      acknowledgementError
+        ? { error: acknowledgementError }
+        : { result: 'AQ==' },
+    ),
+  ),
```
Comment (0xpatrickdev) [inline packages/orchestration/tools/ibc-mocks.ts]: I owe a test for this - probably in `local-orchestration.account.test.ts`. Looking for an error from MN but i think it was longer than our log retention window

Comment (0xpatrickdev) [reply packages/orchestration/tools/ibc-mocks.ts]:
```
2025-03-13T06:19:55.427Z SwingSet: ls: v221 Error#3: ICS20-1 transfer error packet-forward-middleware error: giving up on packet on channel (channel-21) port (transfer) after max retries
```

Comment (0xpatrickdev) [reply packages/orchestration/tools/ibc-mocks.ts]: [9ef1747](https://github.com/Agoric/agoric-sdk/pull/11318/commits/9ef1747fc7adad06e1ac0ec99d51e58b2aaafc38)

File: packages/orchestration/src/exos/ibc-packet.js [hunk 2]
```diff
@@ -128,7 +133,7 @@ export const prepareIBCTransferSender = (zone, { watch, makeIBCReplyKit }) => {
           const { resultV: ackDataV, ...rest } = makeIBCReplyKit(
             replyPacketPattern,
             match,
-            ctx,
+            opts,
```
Comment (michaelfig) [inline packages/orchestration/src/exos/ibc-packet.js]: This is the right place to declare that the operation is a transfer, unless `opts` overrides it.

```suggestion
            { opName: 'transfer', ...opts },
```

**Review by michaelfig — DISMISSED** [review]

File: packages/orchestration/test/supports.ts [hunk 3]
```diff
@@ -144,9 +150,32 @@ export const commonSetup = async (t: ExecutionContext<any>) => {
...
   await registerKnownChains(agoricNamesAdmin, () => {});
 
+  /** proxy for current sequence of the IBC Channel */
   let ibcSequenceNonce = 0n;
-  /** simulate incoming message as if the transfer completed over IBC */
-  const transmitTransferAck = async () => {
+  /**
+   * Simulate an inbound message to the vtransfer bridge.
+   *
+   * Using the localchain bridge to lookup the last message and infer packet
```
Comment (0xpatrickdev) [inline packages/orchestration/test/supports.ts]: s/Using/Uses

File: packages/orchestration/src/exos/ibc-packet.js [hunk 4]
```diff
@@ -88,6 +89,10 @@ export const prepareIBCTransferSender = (zone, { watch, makeIBCReplyKit }) => {
     }),
     {
       public: {
+        /**
+         * @param {Vow<IBCEvent<'acknowledgementPacket' | 'timeoutPacket'>>} match
```
Comment (michaelfig) [inline packages/orchestration/src/exos/ibc-packet.js]: I think this needs to be:
```suggestion
         * @param {Vow<IBCEvent<'acknowledgementPacket'> | IBCEvent<'timeoutPacket'>>} match
```

File: packages/orchestration/src/exos/ibc-packet.js [hunk 5]
```diff
@@ -108,10 +113,13 @@ export const prepareIBCTransferSender = (zone, { watch, makeIBCReplyKit }) => {
          *     >
          *   >,
          * ]} response
-         * @param {Record<string, any>} ctx
+         * @param {{
+         *   opts: PacketOptions;
+         *   match: Vow<IBCEvent<'acknowledgementPacket' | 'timeoutPacket'>>;
```
Comment (michaelfig) [inline packages/orchestration/src/exos/ibc-packet.js]: Same as above.

File: packages/orchestration/src/exos/ibc-packet.js [hunk 6]
```diff
@@ -168,14 +182,26 @@ export const prepareIBCReplyKit = (zone, vowTools) => {
...
+      onFulfilled: M.call(
+        M.splitRecord({ event: M.string() }, { acknowledgement: M.string() }),
+        M.record(),
+      ).returns(Vow$(M.string())),
     }),
     {
-      onFulfilled({ event, acknowledgement }, { opName = 'unknown' }) {
-        assertAllDefined({ event, acknowledgement });
+      /**
+       * @param {IBCEvent<'acknowledgementPacket' | 'timeoutPacket'>} ibcEvent
```
Comment (michaelfig) [inline packages/orchestration/src/exos/ibc-packet.js]: Ditto.

File: packages/orchestration/src/exos/ibc-packet.js [hunk 7]
```diff
@@ -168,14 +182,26 @@ export const prepareIBCReplyKit = (zone, vowTools) => {
...
+       * @param {PacketOptions} ctx
+       */
+      onFulfilled(ibcEvent, { opName = 'unknown' }) {
+        const { event } = ibcEvent;
         switch (event) {
-          case 'acknowledgementPacket':
+          case 'acknowledgementPacket': {
+            const { acknowledgement } =
+              /** @type {IBCEvent<'acknowledgementPacket'>} */ (ibcEvent);
```
Comment (michaelfig) [inline packages/orchestration/src/exos/ibc-packet.js]: Shouldn't need a cast if `event` isn't destructured from `ibcEvent`:

```js
switch (ibcEvent.event) {
  case 'acknowledgementPacket': {
    const { acknowledgement } = ibcEvent;
    ...
```

File: packages/orchestration/src/exos/ibc-packet.js [hunk 8]
```diff
@@ -186,8 +212,9 @@ export const prepareIBCReplyKit = (zone, vowTools) => {
   );
 
   /**
+   * @template {'acknowledgementPacket' | 'timeoutPacket'} [E='acknowledgementPacket' | 'timeoutPacket']
    * @param {Pattern} replyPacketPattern
-   * @param {Vow<any>} matchV
+   * @param {Vow<IBCEvent<E>>} matchV
```
Comment (michaelfig) [inline packages/orchestration/src/exos/ibc-packet.js]:
```suggestion
   * @param {Vow<E>} matchV
```

File: packages/orchestration/src/exos/ibc-packet.js [hunk 9]
```diff
@@ -186,8 +212,9 @@ export const prepareIBCReplyKit = (zone, vowTools) => {
   );
 
   /**
+   * @template {'acknowledgementPacket' | 'timeoutPacket'} [E='acknowledgementPacket' | 'timeoutPacket']
```
Comment (michaelfig) [inline packages/orchestration/src/exos/ibc-packet.js]:
```suggestion
   * @template {IBCEvent<string>} [E=(IBCEvent<'acknowledgementPacket'> | IBCEvent<'timeoutPacket'>)]
```

File: packages/orchestration/src/exos/packet-tools.js [hunk 10]
```diff
@@ -241,6 +242,16 @@ export const preparePacketTools = (zone, vowTools) => {
         },
       },
       sendPacketWatcher: {
+        /**
+         * @param {[
+         *   {
+         *     resolver: VowResolver<any>;
+         *     match: Vow<IBCEvent<'acknowledgementPacket' | 'timeoutPacket'>>;
```
Comment (michaelfig) [inline packages/orchestration/src/exos/packet-tools.js]:
```suggestion
         *     match: Vow<IBCEvent<'acknowledgementPacket'> | IBCEvent<'timeoutPacket'>>;
```

File: packages/orchestration/src/exos/packet-tools.js [hunk 11]
```diff
@@ -33,6 +33,7 @@ const just = obj => {
 /**
  * @typedef {object} PacketSender
  * @property {(
+ *   match: Vow<IBCEvent<'acknowledgementPacket' | 'timeoutPacket'>>,
```
Comment (michaelfig) [inline packages/orchestration/src/exos/packet-tools.js]:
```suggestion
 *   match: Vow<IBCEvent<'acknowledgementPacket'> | IBCEvent<'timeoutPacket'>>,
```

**Review by michaelfig — APPROVED** [review]
LGTM!

My suggestions for this review are highly speculative... I don't know if the typing I suggest will work unmodified, or will just introduce other problems.  Feel free to ignore, if they are not desirable.

File: packages/orchestration/src/exos/ibc-packet.js (hunk 7 above)
Comment (0xpatrickdev) [reply packages/orchestration/src/exos/ibc-packet.js]: Yep this goes away once we use `IBCEvent<'acknowledgementPacket'> | IBCEvent<'timeoutPacket'>` instead of `IBCEvent<'acknowledgementPacket' | 'timeoutPacket'>`

File: packages/orchestration/src/exos/ibc-packet.js (hunk 4 above)
Comment (0xpatrickdev) [reply packages/orchestration/src/exos/ibc-packet.js]: Yes, thank you. `IBCEvent<'acknowledgementPacket' | 'timeoutPacket'>` is not equivalent to your suggestion - it seems to narrow to fields common to both 'acknowledgementPacket' and 'timeoutPacket'.
