### PR TITLE
fix: Make the auction schedule robust when adding collateral types

### LINKED ISSUE #8296: auctioneer doesn't recover when collateral is added without a price
## Describe the bug
While testing changing oracle prices for ATOM and stATOM with Simply Staking on Devnet in order to test liquidation - I noticed that when checking inter auction status that the auction hadn't ran since 8/23: 

```
% inter auction status --book 2
{
  "schedule": {
    "activeStartTime": "2023-08-23T17:00:02.000Z",
    "nextStartTime": "2023-08-23T18:00:02.000Z",
    "nextDescendingStepTime": "2023-08-23T17:12:02.000Z"
  },
  "book2": {
    "startCollateral": "0 stATOM",
    "collateralAvailable": "0 stATOM"
  },
  "params": {
    "DiscountStep": "5.00%",
    "ClockStep": "00:00:30",
    "LowestRate": "65.00%"
```

<details><summary>red herring from ollinet logs</summary>

Per Dan:
logs show
```
2023-09-01T03:10:06.502Z SwingSet: vat: v42: ----- SCHED.8  14414 nextRound { timerBrand: Object [Alleged: timerBrand] {}, absValue: 1_693_538_400n }
```
which translates to...
```
new Date(1000*1_693_538_400)
Thu Aug 31 2023 22:20:00 GMT-0500 (Central Daylight Time)
```
so it could be that under the covers, all is well, but vstorage isn't getting updated somehow.

</details> 

## To Reproduce
1. Go CLI, point to devnet
2. Check auction inter status
3. Also - check Vaults UI on Devnet - notice no next liquidation price (Based on auction)

## Expected behavior
Auction should continue to run

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #8296

This fixes two problems. 
 * If the auction tried to start before a price had been captured from the oracle, it would crash the schedule.
 * If a schedule existed, but it's nextStart was in the past, resetting the parameters didn't fix it. This checks to see if the existing schedule's start time has passed, and if so, restarts the schedule.

#8307 covers the additional issue of ensuring that all repeating timers in the auction should survive exceptions.

## Description

If a new collateral type is added to the auctioneer before its price is available from an oracle, it breaks the schedule of all auctions in a way that is irretrievable.

### Security Considerations

Auction shouldn't be this delicate.

### Scaling Considerations

None.

### Documentation Considerations

None.

### Testing Considerations

Adds a test.

### Upgrade Considerations

Has to wait for the ability to upgrade governed contracts.

### CODE REVIEW

File: packages/inter-protocol/src/auction/auctionBook.js [hunk 1]
```diff
@@ -555,9 +555,12 @@ export const prepareAuctionBook = (baggage, zcf, makeRecorderKit) => {
 
           trace(this.state.collateralBrand, 'settleAtNewRate', reduction);
           const { capturedPriceForRound, priceBook, scaledBidBook } = state;
-          capturedPriceForRound !== null ||
-            Fail`price must be captured before auction starts`;
-          assert(capturedPriceForRound);
+          if (!capturedPriceForRound) {
+            console.warn(
```
Comment (turadg) [inline packages/inter-protocol/src/auction/auctionBook.js]: from throw to warn… is it not an error to start the auction without a price feed? https://github.com/Agoric/agoric-sdk/blob/fb2e7f5dec80c6bf17a16483fb3b956fced41029/packages/inter-protocol/src/vaultFactory/vaultManager.js#L749-L751

maybe not. I suppose we have decided it is part of the spec that the auction skips if there's no feed.

File: packages/inter-protocol/src/auction/scheduler.js [hunk 2]
```diff
@@ -323,7 +323,12 @@ export const makeScheduler = async (
       async updateState(_newState) {
         trace('received param update', _newState);
         await null;
-        if (!nextSchedule) {
+
+        now = await E(timer).getCurrentTimestamp();
+        if (
+          !nextSchedule ||
+          TimeMath.compareAbs(nextSchedule.startTime, now) < 0
+        ) {
```
Comment (turadg) [inline packages/inter-protocol/src/auction/scheduler.js]: I think with the new await that the `await null` is redundant. But I'd propose instead only awaiting the timestamp if necessary.
```suggestion
        if (
          !nextSchedule ||
          TimeMath.compareAbs(nextSchedule.startTime, await E(timer).getCurrentTimestamp()) < 0
        ) {
```
or perhaps more readably,
```suggestion
        const validSchedule = nextSchedule && TimeMath.compareAbs(nextSchedule.startTime, await E(timer).getCurrentTimestamp()) < 0;
        if (!validSchedule) {
```

File: packages/inter-protocol/test/auction/test-auctionContract.js [hunk 3]
```diff
@@ -1408,3 +1423,78 @@ test.serial('time jumps forward', async t => {
   t.is(schedules.liveAuctionSchedule?.startTime.absValue, 1530n);
   t.is(schedules.liveAuctionSchedule?.endTime.absValue, 1550n);
 });
+
+// serial because dynamicConfig is shared across tests
+// This test reproduced bug #8296. Now its expectations don't match the behavior
```
Comment (turadg) [inline packages/inter-protocol/test/auction/test-auctionContract.js]: we need a regression test. so please change this test to ensure that a missing price feed does not throw.

**Review by turadg — CHANGES_REQUESTED** [review]

File: packages/inter-protocol/src/auction/auctionBook.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/auctionBook.js]: It's an error, but it should only affect the auction for that collateral. Throwing is an over-reaction.

File: packages/inter-protocol/test/auction/test-auctionContract.js (hunk 3 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/test/auction/test-auctionContract.js]: Good idea. I'll add a test for that case. I think this test also needs to be part of the PR, just to show the reproduction scenario in case anyone needs to work through that.

File: packages/inter-protocol/src/auction/scheduler.js (hunk 2 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/scheduler.js]: This doesn't save `now`, so I end up making the call to `getCurrentTimestamp` inside a conditional.
```
        let repairableSchedule;
        if (!nextSchedule) {
          repairableSchedule = true;
        } else {
          now = await E(timer).getCurrentTimestamp();
          repairableSchedule =
            TimeMath.compareAbs(nextSchedule.startTime, now) < 0;
        }

        if (repairableSchedule) {
```
The TimeMath comparison will only be called if we did need to update `now`, so it's relatively clean. I tried to use a ternary, but it wasn't pretty (since the else has to be two statements--it's possible with a comma expression, but not great.)

File: packages/inter-protocol/src/auction/auctionBook.js (hunk 1 above)
Comment (turadg) [reply packages/inter-protocol/src/auction/auctionBook.js]: Certainly throwing is an over-reaction. My question was about how to log.
> It's an error

Then should it be `console.error`? Consider also `⚠️` in the message to draw attention to it in log output. I think "🚨" would be too severe as this is a known possible state.

File: packages/inter-protocol/src/auction/scheduler.js (hunk 2 above)
Comment (turadg) [reply packages/inter-protocol/src/auction/scheduler.js]: Ah, I didn't realize `now` needs to be saved.

File: packages/inter-protocol/test/auction/test-auctionContract.js [hunk 4]
```diff
@@ -1408,3 +1423,153 @@ test.serial('time jumps forward', async t => {
...
+    t.false(await E(liqSeat).hasExited());
+    await E(liqSeat).tryExit();
+
+    await assertPayouts(t, liqSeat, bid, collateral, 0n, 0n);
+
+    await driver.advanceTo(210n, 'wait');
+    await driver.advanceTo(220n, 'wait');
+    await driver.advanceTo(250n, 'wait');
+
+    // before the fix for #8296 in scheduler, this didn't repair the problem.
```
Comment (turadg) [inline packages/inter-protocol/test/auction/test-auctionContract.js]: ACK

**Review by turadg — APPROVED** [review]
LG, contingent upon removing the skipped test. (Thanks for including it to facilitate review.)

File: packages/inter-protocol/src/auction/auctionBook.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/auctionBook.js]: I'm fine with error, though I haven't seen any evidence that it increases visibility.

I had intended to add a glyph, but forgot. Thanks for the reminder.
