### PR TITLE
fix(resolve): protect against reentrancy attack

### LINKED ISSUE #9: Promise.resolve(p).then(t => {...})` not actually safe from reentrancy attack.
```js
Promise.resolve(p).then(t => {...})
```
is not actually safe from reentrancy attack.

This vulnerability is suggested by https://github.com/Agoric/eventual-send/issues/32 but not actually stated there. We carefully designed the semantics of `Promise.resolve` so that it was safe from reentrancy attacks, even when its argument was a thenable that triggers absorption. We had in mind that patterns like that above would likewise be 
   * safe under SES because `Promise.prototype.then` would be frozen (good assumption) 
   * safe under SES because genuine promises would be born frozen (bad assumptiion)

The attacker could make a genuine promise with an own `then` property that executes immediately, attacking any reentrancy available to it. Thus, we must find some alternative to the above code pattern.

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #9

Note that the test for `isNormalPromiseThen` does not check that the `Promise.prototype` is frozen as this is always true under SES and too strict outside of SES (tries assimilating all Promises).  It also checks if `p` is frozen only when under SES, as it is too strict outside of SES (tries assimilating platform Promises).

Please review carefully.  There is no rush.

### CODE REVIEW

File: packages/eventual-send/src/index.js [hunk 1]
```diff
@@ -224,13 +236,24 @@ export function makeHandledPromise(Promise) {
     return handledP;
   }
 
-  HandledPromise.prototype = Promise.prototype;
+  HandledPromise.prototype = promiseProto;
 
   // Uncomment this line if needed for conformance to the proposal.
   // Currently the proposal does not specify this, but we might change
   // our mind.
   // Object.setPrototypeOf(HandledPromise, Promise);
```
Comment (erights) [inline packages/eventual-send/src/index.js]: We change our mind. We must have this. Otherwise, a promise is detectably different from a handled promise, which is not the intention.

We need to update the proposal to match.

File: packages/eventual-send/src/index.js [hunk 2]
```diff
@@ -224,13 +236,24 @@ export function makeHandledPromise(Promise) {
...
 
+  function isNormalPromiseThen(p) {
+    return (
+      (!isSES || isFrozen(p)) &&
+      // isFrozen(promiseProto) && // unnecessary under SES and too strict outside SES
+      getPrototypeOf(p) === promiseProto &&
+      promiseResolve(p) === p &&
+      gopd(p, 'then') === undefined &&
+      (isSES || gopd(promiseProto, 'then').value === originalThen) // unnecessary under SES
```
Comment (erights) [inline packages/eventual-send/src/index.js]: Outside of SES, if we're not checking `isFrozen(promiseProto)` and we are checking `gopd(promiseProto, 'then').value === originalThen`, we should also check that this data property is non-writable, non-configurable.

**Review by erights — CHANGES_REQUESTED** [review]

**Comment by Chris-Hibbert** [comment]
Sorry, but I'm not qualified to review this.

File: packages/eventual-send/src/index.js (hunk 2 above)
Comment (michaelfig) [reply packages/eventual-send/src/index.js]: I found that using `harden()` anywhere in `eventual-send` meant that we are taking a stand in hardening HandledPromises.  Going all the way, I instead harden things that are returned by  `HandledPromise.resolve` which simplifies the test and makes it behave more consistently inside and outside SES.  This helped ERTP pass all its unit tests again.

I hope I made an acceptable tradeoff.

If that's not acceptable, then we need a much more convincing story of what we should actually harden in `eventual-send`.

File: packages/eventual-send/src/index.js (hunk 1 above)
Comment (michaelfig) [reply packages/eventual-send/src/index.js]: I've resolved this and created [proposal issue #7](/tc39/proposal-eventual-send/issues/7).

**Comment by erights** [comment]
```js
Object.setPrototypeOf(HandledPromise, Promise);
```

My apologies! I saw the comment, and interpreted it as being about setting `HandledPromise.prototype` to be `Promise.prototype`, which we do in fact need. However, I see this was always true, now with the line

```js
HandledPromise.prototype = promiseProto;
```

which was never turned off. Regarding the line that I mistakenly asked you to change, I actually have no strong feeling one way or the other. I'm happy with what you changed it to, and with making the corresponding change to the spec. But I'd also be happy without it. Feel free to revert this portion of this PR before merging, or not, as you wish.

Sorry for the confusion!

**Comment by michaelfig** [comment]
After using https://github.com/dckc/tape-xs/pull/3 I discovered that the test suite under XS is hanging with the following output:

```
# E method calls
ok 1 return is a thenable
 lin_xs_cli: main() returned a promise; entering event loop
ok 2 method call works
# E shortcuts
ok 3 method call works
ok 4 anonymous method works
ok 5 property get
# chained properties
ok 6 should be equivalent
ok 7 should be equivalent
# E.resolve is always asynchronous
ok 8 should be identical
```

**Comment by michaelfig** [comment]
@dckc, the hanging test is at an [awaited promise](https://github.com/Agoric/agoric-sdk/pull/401/files#diff-ff0bf23100c5dafe0afa7b2985472ad4R16)

**Comment by michaelfig** [comment]
@dckc Aha!  I'm narrowing down on the problem, and it looks like a legit portability bug in this PR.

**Comment by michaelfig** [comment]
It's the override mistake.  Under XS, I cannot override the `.then` of a promise because `Promise.prototype.then` is frozen!

That's actually a good thing.  This prevents having to assimilate promises under XS.

I've updated the tests accordingly.  Will retry.

File: packages/eventual-send/src/index.js (hunk 2 above)
Comment (michaelfig) [reply packages/eventual-send/src/index.js]: @erights PTAL.

**Comment by erights** [comment]
> That's actually a good thing. This prevents having to assimilate promises under XS.

The override mistake only protects against override by assignment. It doesn't prevent override by `defineProperty`, and so does not provide any actual safety against intentional override.

**Comment by michaelfig** [comment]
> > That's actually a good thing. This prevents having to assimilate promises under XS.
> 
> The override mistake only protects against override by assignment. It doesn't prevent override by `defineProperty`, and so does not provide any actual safety against intentional override.

Oh, okay.  I'll rewrite the test accordingly.

**Comment by michaelfig** [comment]
Bingo!  The workaround of the override mistake using `Object.defineProperty` shows proper assimilation behaviour under both Node and XS.

Still, it was interesting to reveal https://github.com/Moddable-OpenSource/moddable/issues/322

**Review by erights — APPROVED** [review]
LGTM
