### PR TITLE
fix: provisionPool vstorage in exportStorageSubtrees

### LINKED ISSUE #7705: Provisionpool Metrics aren't retained across vaults upgrade
to reproduce

1. `git clone git@github.com:Agoric/agoric-sdk.git && cd agoric-sdk && checkout ari/vaultstest`
2. `cd packages/deployment/upgrade-test`
3. `TARGET=agoric-upgrade-8 make build run`
4. in container, `agoric follow :published.provisionPool.metrics`
see output:
```
{
  totalMintedConverted: {
    brand: slot(0,"Alleged: IST brand"),
    value: 20000000n,
  },
  totalMintedProvided: {
    brand: slot(0),
    value: 750000n,
  },
  walletsProvisioned: 2n,
}
```
5. `TARGET=agoric-upgrade-10 make build run`
6. in container, `agoric follow -F :published.provisionPool.metrics`
see output:
```
{
  totalMintedConverted: {
    brand: slotToVal("board0257","Alleged: IST brand"),
    value: 0n,
  },
  totalMintedProvided: {
    brand: slotToVal("board0257"),
    value: 0n,
  },
  walletsProvisioned: 0n,
}
```

### PR DESCRIPTION
**Pull request by turadg**
closes: #7705

## Description

`provisionPool` has data we want to carry through like `published.psm.IST`. We keep `metrics` but not `governance`, because the values have never been changed from defaults (for `PerAccountInitialAmount`) and the post-bulldoze will come with the same defaults.

Analogously to PSM, we consume exported `published.provisionPool.metrics` data, translate old brand boardID values into new ones, and plumb the result into the new provisionPool incarnation via privateArgs so it can pick up where its
predecessor left off.

### Security Considerations

provisionPool can now start from a nonempty state under the control of its creator, which gets that state from exported vstorage data. But if that can be tampered with, then we've got bigger problems.

### Scaling Considerations

At most, this slows down the time to execute re-bootstrap—which we don't care about (but realistically, I don't expect any significant impact even to that).

### Documentation Considerations

n/a

### Testing Considerations

There's not really a good way to cover this with our automated testing, since real wallets are provisioned by a bridge handler (which doesn't provide a response), while test-vaults-upgrade.js bypasses that—and therefore the `helper.onProvisioned()` call that publishes metrics to chain storage—to directly invoke the wallet factory's `provideSmartWallet` method (which provides a response that is depended upon by assertions etc.).

We can probably address that given more time, but for now I've just validated manually.

As for other published storage paths, @turadg examined them all and found no gaps other than `provisionPool`.

### CODE REVIEW

**Review by ivanlei — APPROVED** [review]
🚀

**Review by gibson042 — APPROVED** [review]
This will preserve the `published.provisionPool.metrics` data in vstorage and export entries to bootstrap, but IIUC bootstrap is expected to ignore them, right?

**EDIT**: Nope, we need metrics migration (mapping old brands to new ones) just like for PSM.

**Review by gibson042 — APPROVED** [review]
The tweaks LGTM!

File: packages/vats/src/provisionPool.js [hunk 1]
```diff
@@ -23,6 +23,8 @@ export const privateArgsShape = M.splitRecord(
   harden({
     // only necessary on first invocation, not subsequent
     initialPoserInvitation: InvitationShape,
+    // expected only in upgrade incarnations
+    metricsOverride: M.recordOf(M.string()),
```
Comment (dckc) [inline packages/vats/src/provisionPool.js:27]: That's a little misleading... "upgrade" in a contract usually means restarting a vat with a new implementation associated with durable state.

This `metricsOverride` is about restarting _the whole swingset VM_ with all new vats.

File: packages/vats/src/provisionPoolKit.js [hunk 2]
```diff
@@ -378,6 +382,24 @@ export const prepareProvisionPoolKit = (
               },
             },
           );
+
+          if (metrics) {
+            // Restore state, but don't publishMetrics()
+            // because that already happened in the last incarnation.
```
Comment (dckc) [inline packages/vats/src/provisionPoolKit.js:388]: Hm. now it's not just a misleading comment. It's incorrect. We're not doing a zoe contract upgrade between incarnations here. We're restarting the swingset VM. So the metrics should be published right away in the first incarnation.

It's not the end of the world, since the problem goes away the next time anyone provisions a smart wallet.

File: packages/vats/tools/board-utils.js [hunk 3]
```diff
@@ -116,7 +116,7 @@ export const makeHistoryReviver = (entries, slotToVal = undefined) => {
       ),
     ]);
   };
-  return harden({ getItem, children, has: k => vsMap.has(k) });
+  return harden({ getItem, children, has: k => vsMap.get(k) !== undefined });
```
Comment (dckc) [inline packages/vats/tools/board-utils.js:119]: would be good to have a unit test for this change
