### PR TITLE
fix(amm): update metrics whenever pool balances change, including init

### LINKED ISSUE #5442: AMM Pool Subscriptions showing 0 liquidity for non-zero pools
## Describe the bug
Title sums it up

## To Reproduce
1. Start a local sim-chain with `agoric start --reset`
2. Access a pool subscription with `E(ammAPI).getPoolMetrics(brand)`
3. Observe the first (non-final) value in the subscription shows 0 liquidity for the pool
4. Observe that you can still make a trade on the pool, so it's not actual 0

## Expected behavior
The first value of the subscription shows the real pool value

## Additional context
According to @Chris-Hibbert: We need to put an updateMetrics() call in addLiquidity

## Screenshots
image

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #5442

## Description

The AMM wasn't updating the pool balances to the metrics stream when pools were created with an initial balance. This fixes that.

### Security Considerations

None.

### Documentation Considerations

None

### Testing Considerations

Added tests that show the updates at initialization, when trades happen, and when liquidity changes.

### CODE REVIEW

File: packages/run-protocol/test/amm/vpool-xyk-amm/test-liquidity.js [hunk 1]
```diff
@@ -188,6 +189,20 @@ test('amm add and remove liquidity', async t => {
...
   );
 
+  const poolMetrics = await E(amm.ammPublicFacet).getPoolMetrics(moolaR.brand);
+  const tracker = await subscriptionTracker(t, poolMetrics);
+  await tracker.assertInitial({
+    centralAmount: central(0n),
+    liquidityTokens: 0n,
+    secondaryAmount: moola(0n),
+  });
+  const poolLiquidity = {
```
Comment (turadg) [inline packages/run-protocol/test/amm/vpool-xyk-amm/test-liquidity.js:199]: nice pattern

**Review by turadg — APPROVED** [review]
Discovered through working on other features?

**Comment by Chris-Hibbert** [comment]
> Discovered through working on other features?

Not really.  You had asked in another PR that the state changes be represented minimally so a reviewer can see what's different more easily, and this seemed the most straightforward way.
