### PR TITLE
fix wallet extract-id CLI

### LINKED ISSUE #10891: wallet extract-id CLI fails
## Describe the bug
`agoric wallet extract-id` causes this error when called:

```
agoric: (TypeError#1)
TypeError#1: Cannot read properties of undefined (reading 'fromCapData')
  at Command.<anonymous> (file:///usr/src/agoric-sdk/packages/agoric-cli/src/commands/wallet.js:132:37)
  at async Command.parseAsync (/usr/src/agoric-sdk/node_modules/commander/lib/command.js:1092:5)
  at async main (file:///usr/src/agoric-sdk/packages/agoric-cli/src/main.js:402:5)

```

## Additional context

It was caused by a refactoring, and the type checker didn't detect the implicit `any`.

There was _some_ test coverage in `f:fast-usdc` but that was pinned to an older release so not testing HEAD.

### PR DESCRIPTION
**Pull request by turadg**
closes: #10891

## Description

A recent refactor of agoric-cli introduced an error. It wasn't caught by typecheck because the callsite was `any`. 

### Security Considerations
none

### Scaling Considerations
none

### Documentation Considerations
none

### Testing Considerations
This PR doesn't have a runtime regression test because this is a very uncommon code path which does have _some_ CI coverage in a3p-integration (https://github.com/Agoric/agoric-sdk/pull/10839/commits/1d018800e573718ed3a7f45611671cdab4c210ec) 

### Upgrade Considerations
Not run on chain.

### CODE REVIEW

File: packages/agoric-cli/src/lib/chain.js [hunk 1]
```diff
@@ -132,6 +133,7 @@ harden(execSwingsetTransaction);
 /**
  *
  * @param {MinimalNetworkConfig} net
+ * @returns {ParamsSDKType}
```
Comment (dckc) [inline packages/agoric-cli/src/lib/chain.js:136]: I'm not sure JSON output from `agd` always directly corresponds with protobuf stuff. I wouldn't be surprised if it does in this case, but did you happen to verify experimentally? Or maybe there's a caller that clearly relies on it?

**Review by dckc — APPROVED** [review]
looks good

File: packages/agoric-cli/src/lib/chain.js (hunk 1 above)
Comment (turadg) [reply packages/agoric-cli/src/lib/chain.js:136]: Yeah there's a caller. 
Screenshot 2025-01-24 at 2 41 02 PM
