### PR TITLE
Fix IBC (`x/capability`) nondeterminism after node restart

### LINKED ISSUE #4159: Divergence between nodes after restart during IBC channel open
## Describe the bug
Nodes diverge from one another at a block that includes a new IBC channel attempt.

## To Reproduce
1. Start a multi-node chain
2. Add a peer which should halt soon (say, at block 20, with `ag-chain-cosmos start --log_level=warn --halt-height=20`)
2. After the halt node stops, start it running normally `ag-chain-cosmos start --log_level=warn`
3. Establish an IBC channel to the chain via a relayer (such as Hermes)
4. Note that the restarted node fails with an AppHash mismatch at the `/ibc.core.channel.v1.MsgChannelOpenTry` transaction message

## Expected behavior

No failure.

## Platform Environment
 - what OS are you using? Ubuntu what version of Node.js? 14.x
 - is there anything special/unusual about your platform? no
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`) agoricdev-6

## Additional context

```
> \x01=\x84\x80\xe2:\xcfq\x06\xdc\xc7p\xdb"9\x8d\xe4a\xa6\xc1\n \n /cosmos.auth.v1beta1.BaseAccount\x12{\n-agoric18kzgpc36eacsdhx8wrdjywvdu3s6dsg2ae3t54\x12F\n\x1f/cosmos.crypto.secp256k1.PubKey\x12#\n!\x02Ay\xb9\x1f\x83\xda\x17<\xf5\x17\xd7\xf9\x1f\x93\xf5\xdfT\xa9y\x8d\x8e\xb5\xa0\x19\xb7\xc8\xb6U1\xc47\xce\x18\x1b \x7f        {"blockHeight":52769,"txHash":"34EE87F4CF4A25AE30C1A4D1A7483160D8618BC579B1C9208CC6323AAFC4D053"}
60,62c61
< commitments/ports/transfer/channels/channel-2/sequences/1     "t^\xa4\xc5kN\t\x01\x0eei\r\xaf\xd5\xd7\xfe\rI\xcd0\xe2\xef*\xf0L\xef\x95#\xb0\x9b\xfc  {"blockHeight":52769,"txHash":"149D04DF120171DE7184E67BE2C8E3B978020A90F386FD5E5D42AC565B2DAFB4"}
< nextSequenceSend/ports/transfer/channels/channel-2    \0\0\0\0\0\0\0\x02      {"blockHeight":52769,"txHash":"149D04DF120171DE7184E67BE2C8E3B978020A90F386FD5E5D42AC565B2DAFB4"}
< swingset/data:activityhash    342391f0588659651666272a435e519853f077c260ddfc6fa231bae88898d071        {"blockHeight":52769,"txHash":"149D04DF120171DE7184E67BE2C8E3B978020A90F386FD5E5D42AC565B2DAFB4"}
---
> swingset/data:activityhash    355d62261417de3b1089c5e071f456d611d422cdd92aaab939661dcc90118c6d        {"blockHeight":52769,"txHash":"149D04DF120171DE7184E67BE2C8E3B978020A90F386FD5E5D42AC565B2DAFB4"}
```

After `unsafe-reset-all`, then starting, then after 400 blocks, restarting a node, we have a crash:

```
mos[27118]: 2021-12-07T16:42:45.657Z block-manager: block 8013 commit
mos[27118]: panic: Failed to process committed block (8014:F03EBBC2555EDEF88E0AA0908A9A39484249FE2049AF172AFDE7F7CF8555C8C4
```

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #4159

## Description

Fixes nondeterminism caused by missing `x/capability` in the Cosmos `SetOrderBeginBlockers` call (found by narrowing down to a `x/capability` problem, then studying occurrences of `capability` in Cosmos SDK v0.44.4 `cosmos-sdk/simapp/app.go`).

Simplifies the `golang/cosmos/app/app.go` to set less `genesis.json` overrides, instead doing it explicitly in `agoric set-defaults`.  This makes things a little less magical.

Also updates `packages/deployment` to work with newer Docker installations where the `/sys/fs/cgroup` must not be mounted.  I needed this to do local testing.

### Testing Considerations

We really need multinode IBC testing along with the other loadgen tests.  Maybe for the New Year?

### CODE REVIEW

**Comment by mhofman** [comment]
> We really need multinode IBC testing along with the other loadgen tests. Maybe for the New Year?

File a new issue? Is this something we can extend the loadgen to do?

File: packages/agoric-cli/src/chain-config.js [hunk 1]
```diff
@@ -5,6 +5,8 @@ export const CENTRAL_DENOM = 'urun';
 export const MINT_DENOM = 'ubld';
 export const STAKING_DENOM = 'ubld';
 export const STAKING_MAX_VALIDATORS = 150;
+export const COSMOS_TRANSFER_PORT_ID = 'cosmos-transfer';
```
Comment (dckc) [inline packages/agoric-cli/src/chain-config.js]: I'm still fuzzy on `transfer` vs. `cosmos-transfer`. Is it worth adding a comment about that here?

**Review by dckc — APPROVED** [review]
tmjson looks handy :)

**Review by JimLarson — APPROVED** [review]
