### PR TITLE
ci(getting-started): mitigate `registry/yarn` flake

### LINKED ISSUE #9325: Flake: Getting Started (registry/yarn)
## Describe the bug

The **Getting Started (registry/yarn)** is flakey

## To Reproduce

The test failed, as shown in
https://github.com/Agoric/agoric-sdk/actions/runs/8973265730/job/24643072843?pr=9283

```
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = account sequence mismatch, expected 60, got 59: incorrect account sequence [agoric-labs/cosmos-sdk@v0.46.16-alpha.agoric.2.1/x/auth/ante/sigverify.go:269] With gas wanted: '18446744073709551615' and gas used: '38588' : unknown request
```

hitting "Rerun failed tests" caused it to pass.

Other instances
- https://github.com/Agoric/agoric-sdk/actions/runs/9452805537/job/26036797179?pr=9477 `Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = account sequence mismatch, expected 63, got 62: incorrect account sequence [agoric-labs/cosmos-sdk@v0.46.16-alpha.agoric.2.4/x/auth/ante/sigverify.go:269] With gas wanted: '18446744073709551615' and gas used: '38588' : unknown request`
- https://github.com/Agoric/agoric-sdk/actions/runs/9482934359/job/26128895842?pr=9486
- https://github.com/Agoric/agoric-sdk/actions/runs/9485446800/job/26137411404?pr=9493
- https://github.com/Agoric/agoric-sdk/actions/runs/9575880016/job/26401438586?pr=9529
- https://github.com/Agoric/agoric-sdk/actions/runs/9585917138/job/26432853529?pr=9532
- https://github.com/Agoric/agoric-sdk/actions/runs/9585956607/job/26432968021?pr=9494
- https://github.com/Agoric/agoric-sdk/actions/runs/9587308469/job/26437076172?pr=9494
- https://github.com/Agoric/agoric-sdk/actions/runs/9604519081/job/26490178328?pr=9544
- https://github.com/Agoric/agoric-sdk/actions/runs/9604519081/job/26490177945?pr=9544

## Expected behavior

Tests  should not be flakey.

## Platform Environment

Running in CI.

### LINKED ISSUE #9710: Possible race in integration testing
## Describe the bug
#9688 encountered a surprising issue that caused the first attempt of **getting-started (link-cli/yarn)** to fail, followed by broken/cleanup-missing recovery logic: https://github.com/Agoric/agoric-sdk/actions/runs/9913890868/job/27391851751?pr=9688#check-step-7
```
ENV_SETUP starting
ENV_SETUP finished
start voteLatestProposalAndWait()
waiting for block...
1
block produced
done
Latest proposal: 14
waiting for block...
1
block produced
done
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = account sequence mismatch, expected 63, got 62: incorrect account sequence [agoric-labs/cosmos-sdk@v0.46.16-alpha.agoric.2.4/x/auth/ante/sigverify.go:269] With gas wanted: '18446744073709551615' and gas used: '38588' : unknown request
Usage:
  agd tx gov deposit [proposal-id] [deposit] [flags]

Flags:
  -a, --account-number uint      The account number of the signing account (offline mode only)
      --aux                      Generate aux signer data instead of sending a tx
  -b, --broadcast-mode string    Transaction broadcasting mode (sync|async|block) (default "sync")
      --dry-run                  ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it (when enabled, the local Keybase is not accessible)
      --fee-granter string       Fee granter grants fees for the transaction
      --fee-payer string         Fee payer pays fees for the transaction instead of deducting from the signer
      --fees string              Fees to pay along with transaction; eg: 10uatom
      --from string              Name or address of private key with which to sign
      --gas string               gas limit to set per-transaction; set to "auto" to calculate sufficient gas automatically. Note: "auto" option doesn't always report accurate results. Set a valid coin value to adjust the result. Can be used instead of "fees". (default 200000)
      --gas-adjustment float     adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored  (default 1)
      --gas-prices string        Gas prices in decimal format to determine the transaction fee (e.g. 0.1uatom)
      --generate-only            Build an unsigned transaction and write it to STDOUT (when enabled, the local Keybase only accessed when providing a key name)
  -h, --help                     help for deposit
      --keyring-backend string   Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
      --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
      --ledger                   Use a connected Ledger device
      --node string              <host>:<port> to tendermint rpc interface for this chain (default "tcp://localhost:26657")
      --note string              Note to add a description to the transaction (previously --memo)
      --offline                  Offline mode (does not allow any online functionality)
  -o, --output string            Output format (text|json) (default "json")
  -s, --sequence uint            The sequence number of the signing account (offline mode only)
      --sign-mode string         Choose sign mode (direct|amino-json|direct-aux), this is an advanced feature
      --timeout-height uint      Set a block timeout height to prevent the tx from being committed past a certain height
      --tip string               Tip is the amount that is going to be transferred to the fee payer on the target chain. This flag is only valid when used with --aux, and is ignored if the target chain didn't enable the TipDecorator
  -y, --yes                      Skip tx broadcasting prompt confirmation

Global Flags:
      --chain-id string     The network chain ID
      --home string         directory for config and data (default "/root/.agoric")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors

make: *** [Makefile:101: start-contract] Error 1
make: Leaving directory '/workspace/contract'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn start:ui
$ cd ui && yarn dev
$ vite

  VITE v4.5.0  ready in 213 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ✘ [fail]: workflow yarn start:contract works
  ─

  workflow

  yarn start:contract works

  Difference (- actual, + expected):

  - 2
  + 0

  › gettingStartedWorkflowTest (packages/agoric-cli/tools/getting-started.js:124:7)

  ─

  1 test failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Warning: Attempt 1 failed. Reason: Child_process exited with error code 1
yarn run v1.22.22
$ yarn run create-agoric-cli /home/runner/bin/agoric
$ node ./scripts/create-agoric-cli.cjs /home/runner/bin/agoric
Script directory /home/runner/bin does not appear in $PATH
(You may want to `export PATH=$PATH:/home/runner/bin' to add it to your PATH environment variable)
ensuring /home/runner/bin exists
creating /home/runner/bin/agoric
Error: /home/runner/bin/agoric must not already exist; you should use a fresh path.
    at Object.<anonymous> (/home/runner/work/agoric-sdk/agoric-sdk/scripts/create-agoric-cli.cjs:45:11)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Warning: Attempt 2 failed. Reason: Child_process exited with error code 1
yarn run v1.22.22
$ yarn run create-agoric-cli /home/runner/bin/agoric
$ node ./scripts/create-agoric-cli.cjs /home/runner/bin/agoric
Script directory /home/runner/bin does not appear in $PATH
(You may want to `export PATH=$PATH:/home/runner/bin' to add it to your PATH environment variable)
ensuring /home/runner/bin exists
creating /home/runner/bin/agoric
Error: /home/runner/bin/agoric must not already exist; you should use a fresh path.
    at Object.<anonymous> (/home/runner/work/agoric-sdk/agoric-sdk/scripts/create-agoric-cli.cjs:45:11)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Final attempt failed. Child_process exited with error code 1
```

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #9325, closes: #9710

## Description
This is a minor fix to make sure the `registry/yarn` getting-started CI test doesn't fail.  It embraces the current situation that `agoric install $DISTTAG` is not currently usable within the default [Agoric/dapp-offer-up](https://github.com/Agoric/dapp-offer-up) because of the long list of `packageJson.resolutions`  `dapp-offer-up` uses.

Thus, `getting-started.js` has `AGORIC_INSTALL_DISTTAG` set to `false`.  This ensures that `agoric install $DISTTAG` does not execute.  It is replaced by simply `yarn install`.

### CODE REVIEW

File: packages/agoric-cli/tools/getting-started.js [hunk 1]
```diff
@@ -23,6 +24,38 @@ const dirname = new URL('./', import.meta.url).pathname;
 // yarn start:contract
 // yarn start:ui
 
+/**
+ * @param {string} url
+ * @returns {Promise<bigint>}
+ */
+const getLatestBlockHeight = url =>
```
Comment (dckc) [inline packages/agoric-cli/tools/getting-started.js:37]: I wonder how many implementations we have of this by now :)

File: packages/agoric-cli/tools/getting-started.js [hunk 2]
```diff
@@ -14,13 +14,18 @@ import { makePspawn } from '../src/helpers.js';
 const RETRY_BLOCKHEIGHT_SECONDS = 3;
 const SOCKET_TIMEOUT_SECONDS = 2;
 
+// TODO: Set this to `true` when `agoric install $DISTTAG` properly updates the
+// getting-started workflow's dependencies to current `@endo/*` and Agoric SDK
+// from the local registry.
```
Comment (dckc) [inline packages/agoric-cli/tools/getting-started.js:19]: seems like this should reference an issue.

I don't see one that's quite on target; closest I find is #8621

**Review by dckc — COMMENTED** [review]
notes on current draft...

File: packages/agoric-cli/tools/getting-started.js (hunk 2 above)
Comment (michaelfig) [reply packages/agoric-cli/tools/getting-started.js:19]: I'll try to add to that issue or create a new one to include as a reference in the TODO.

File: packages/agoric-cli/tools/getting-started.js (hunk 1 above)
Comment (michaelfig) [reply packages/agoric-cli/tools/getting-started.js:37]: It occured to me: I should probably do a pure JS implementation available via the `agoric wait-for-block` command  to subsume the functionality of the `waitForBlock` shell function and the various polling loops we have in Makefiles, etc.

**Review by rabi-siddique — APPROVED** [review]

File: packages/agoric-cli/tools/getting-started.js (hunk 2 above)
Comment (mhofman) [reply packages/agoric-cli/tools/getting-started.js:19]: Probably #9615 ?
