### PR TITLE
6689 fix watchPurse race

### LINKED ISSUE #6689: race condition in smartWallet addBrand handling
## Describe the bug
In some versions of XS, the non-init `updateBalance` hits before the init one, causing an assert to fail when checking for the presence of the key in the collection.

In general while the purse is guaranteed to see the messages `getCurrentAmount` and `getCurrentAmountNotifier` in order, there is no guarantee those will be resolved in the same order. And even if they were, E.when and the observeNotifier may not make any guarantee about the number of turns or cranks that may occur.

https://github.com/Agoric/agoric-sdk/blob/c7d422343c9fdfd173b6e756ad2a02577d7c4574/packages/smart-wallet/src/smartWallet.js#L320-L334
## To Reproduce

Not practical to reproduce. Just fix through code analysis.

## Expected behavior

No assertion failure if promises resolve in another valid resolution order.

## Platform Environment
XS

## Additional context

https://github.com/Agoric/agoric-sdk/issues/6689#tasklist-block-1aacc3df-2305-4b3e-b890-26f1d3164b34

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

### PR DESCRIPTION
**Pull request by turadg**
closes: #6689

## Description

Fixes a race condition identified in #6689

Also bundles a [code refactoring suggestion](https://github.com/Agoric/agoric-sdk/pull/6862#discussion_r1088442990) from @gibson042 

### Security Considerations

--
### Scaling Considerations

--

### Testing Considerations

The race happened in XS only. We could have a regression test by slowing down the faster promise, but doesn't seem worth it.

### CODE REVIEW

File: packages/internal/src/lib-chainStorage.js [hunk 1]
```diff
@@ -153,18 +153,17 @@ export async function makeStorageNodeChild(storageNodeRef, childName) {
...
  */
-export const makeMarshallToStorage = (storageNode, marshaller) => {
-  return value =>
-    E(marshaller)
-      .serialize(value)
-      .then(serialized => {
-        const encoded = JSON.stringify(serialized);
-        return E(storageNode).setValue(encoded);
-      });
+export const makeSerializeToStorage = (storageNode, marshaller) => {
```
Comment (dckc) [inline packages/internal/src/lib-chainStorage.js:163]: reminds me of #6646 . hope to get back to that soonish...

File: packages/smart-wallet/src/smartWallet.js [hunk 2]
```diff
@@ -282,14 +282,13 @@ export const prepareSmartWallet = (baggage, shared) => {
...
-        updateBalance(purse, balance, init) {
+        updateBalance(purse, balance) {
           const { purseBalances, updatePublishKit } = this.state;
-          if (init) {
-            purseBalances.init(purse, balance);
-          } else {
+          if (purseBalances.has(purse)) {
             purseBalances.set(purse, balance);
+          } else {
+            purseBalances.init(purse, balance);
```
Comment (dckc) [inline packages/smart-wallet/src/smartWallet.js:291]: This looks like the gist of it. I'd appreciate a look by @mhofman and/or @gibson042 .

Did @gibson042 already look at this?

**Review by dckc — APPROVED** [review]
> We could have a regression test by slowing down the faster promise, but doesn't seem worth it.

I'm a bit reluctant to go without that test, but since the only purse watched by the smart wallet is now the zoe purse, the scope is much reduced, so I concur.

I would appreciate a look from @mhofman and/or @gibson042 .

@mhofman if you happen to have the hash of the relevant XS version, that would be nice. And/or an excerpt from logs of the run where we observed the problem.

**Comment by mhofman** [comment]
> @mhofman if you happen to have the hash of the relevant XS version, that would be nice. And/or an excerpt from logs of the run where we observed the problem.

The only happened because of a bug in XS, when replaying the mainnet transcripts. So per se there is not minimal reproduction, and I don't think even that repro is related. It's just that when I looked at this code, I realized it was subject to a theoretical race.

File: packages/smart-wallet/src/smartWallet.js (hunk 2 above)
Comment (mhofman) [reply packages/smart-wallet/src/smartWallet.js:291]: This looks fine. Unfortunate we don't have an `upsert` for these cases.

**Review by mhofman — APPROVED** [review]
