### PR TITLE
fix: correct accounting numbers in liquidation and auction

### LINKED ISSUE #7475: Some VaultFactory and Auction.Book liquidation/auction-specific names are confusing/unclear
## Description of the Design

vaultFactor.Manager
- [ ] 'liquidatingCollateral' looks to be total cumulative liquidated collateral for a given vault manager (please confirm @dckc and @Chris-Hibbert). If this is the case, the name is confusing and should be renamed to 'TotalCollateralLiquidated' 

- [ ] likewise for 'liquidatingDebt' -> renaming to 'TotalDebtLiquidated' seems to make more sense

auction.book0
- [ ] From watching a few auctions, 'collateralAvailable' seems to tick up as collateral is sold in the auction so it's not really tracking available collateral. It would make more sense to either change the calculation logic here such that it starts at total amount of liquidated collateral available that needs to be sold and counts downwards as the auction ticks forward.
Alternatively (but a second preference), it could be renamed to 'CollateralSold' if changing calculation logic is a harder lift.

## Security Considerations
Unknown
## Scaling Considerations
Unknown

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #7475

## Description

7475 reported some incorrect accounting numbers in liquidation and auctions. This fixes them.

liquidatingCollateral and liquidatingDebt weren't being reduced in flow 2b, so they were growing without bound and looked like accumulators rather than current values.

collateralAvailable was reporting collateralSold instead. In addition, the value was being reported before assets were added rather than after.

### Security Considerations

None.

### Scaling Considerations

None.

### Documentation Considerations

None

### Testing Considerations

Tests were helpful.

### CODE REVIEW

File: packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js [hunk 1]
```diff
@@ -1809,6 +1809,8 @@ test('reinstate vault', async t => {
 
   await aethVaultMetrics.assertChange({
     numActiveVaults: 1,
+    liquidatingDebt: { value: 0n },
```
Comment (turadg) [inline packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js:1840]: ah, I see now why the `TotalDebtLiquidated` rename was proposed and should be abandoned

**Review by turadg — APPROVED** [review]

File: packages/inter-protocol/test/auction/test-auctionContract.js [hunk 2]
```diff
@@ -919,16 +919,14 @@ test.serial('onDeadline exit, with chainStorage RPC snapshot', async t => {
...
-    collateralAvailable: { value: 0n },
-  });
+  await bookTracker.assertChange({});
 
   await driver.advanceTo(170n, 'wait');
   await scheduleTracker.assertChange({
     nextDescendingStepTime: { absValue: 175n },
   });
   await bookTracker.assertChange({
-    collateralAvailable: { value: 100n },
```
Comment (samsiegart) [inline packages/inter-protocol/test/auction/test-auctionContract.js:931]: It's not really clear from looking at this test that the problem is fixed. It might help to put comments at various points after `driver.advanceTo` to signify what point in the process the test is at.

In general though at previous orgs I've seen conventions of one unit test per behavior for this reason. Maybe that's unwieldy for these scenarios but reading the test name `onDeadline exit, with chainStorage RPC snapshot` doesn't tell me anything about the expected behavior.
