### PR TITLE
`agd export` option for diagnosis

### LINKED ISSUE #8420: `agd export` option for diagnosis
## What is the Problem Being Solved?

#8152 added support for `agd export` including SwingSet state, solving #6527. Another use case for `agd export` is to gather diagnostics is a chain node encounters an `AppHash` error. However if the node does not have full replay state, `agd export` will currently fail.

## Description of the Design

add a new option to `agd export` which makes a `debug` export of the swing store instead of a `replay` one, and which includes "export data" as an artifact as well to allow comparing consistency with the shadow version in the cosmos DB.

Potential names for the option
- `--debug`
- `--force`
- `--raw`
- `--for-diagnostics`

## Security Considerations

None

## Scaling Considerations

None

## Test Plan

Manual may be sufficient

## Upgrade Considerations

This is a change to cosmos code, and as such is better distributed along a chain software upgrade, even though it should not have any impact on consensus.

### PR DESCRIPTION
**Pull request by usmanmani1122**
closes: #8420
ref: #8152

## Description
This PR adds a new optional flag `--swing-store-export-mode` to the `agd export` command which can be used to specify the nature of swing-store export

### Security Considerations
None

### Scaling Considerations
None

### Documentation Considerations
An optional flag `--swing-store-export-mode` option is now supported for `agd export` to specify the kind of swing store export required:
- `operational` (default) option will retain the existing behavior and export the swing-store artifacts using the latest height
- `skip` option will not export any swing-store artifact
- `debug` option will export all swing-store artifacts, starting from height `0`

### Testing Considerations
Tested manually

### Upgrade Considerations
None

### CODE REVIEW

File: golang/cosmos/daemon/cmd/root.go [hunk 1]
```diff
@@ -453,7 +480,16 @@ func (ac appCreator) appExport(
...
+	swingStoreExportMode, ok := appOpts.Get(gaia.FlagSwingStoreExportMode).(string)
+	if !(ok && allowedSwingSetExportModes[swingStoreExportMode]) {
+		return servertypes.ExportedApp{}, fmt.Errorf(
+			"export mode '%s' is not supported",
+			swingStoreExportMode,
+		)
+	}
+
+	// We don't have to launch VM in case the swing store export is not required
+	if !(swingStoreExportMode == swingsetkeeper.SwingStoreArtifactModeSkip || OnExportHook == nil) {
```
Comment (usmanmani1122) [inline golang/cosmos/daemon/cmd/root.go]: @mhofman since `OnExportHook` currently points to `launchVM`, is it okay to bypass this hook in case swing-store export is not needed? Or do you see us adding cosmic side future hook changes?

File: golang/cosmos/x/swingset/genesis.go [hunk 2]
```diff
@@ -169,32 +190,73 @@ type swingStoreGenesisEventHandler struct {
...
+				artifact, err = provider.ReadNextArtifact()
+			} else {
+				return types.SwingStoreArtifact{}, io.EOF
+			}
+
+			if err == io.EOF {
+				artifactsEnded = true
+				if eventHandler.exportMode == keeper.SwingStoreArtifactModeDebug {
+					err = nil
+					exportDataReader, err := getExportDataReader()
```
Comment (Muneeb147) [inline golang/cosmos/x/swingset/genesis.go]: Do we need to close this reader in defer?
`defer exportDataReader.Close()`

File: golang/cosmos/x/swingset/genesis.go [hunk 3]
```diff
@@ -169,32 +190,73 @@ type swingStoreGenesisEventHandler struct {
...
+						)
+						if err == nil {
+							artifact = types.SwingStoreArtifact{
+								Data: encodedExportData.Bytes(),
+								Name: keeper.UntrustedExportDataArtifactName,
+							}
+						}
+					}
+				}
+			}
```
Comment (Muneeb147) [inline golang/cosmos/x/swingset/genesis.go]: So in-case exportMode is "debug", we are sending an extra artifact at the end which is a full export of swingStore (Kvstore)? Right? Assuming that caller iterates over `ReadNextArtifact` until gets io.EOF.

File: golang/cosmos/x/swingset/genesis.go (hunk 2 above)
Comment (usmanmani1122) [reply golang/cosmos/x/swingset/genesis.go]: I thought `EncodeKVEntryReaderToJsonl` function will close the reader passed to it at the end but it seems like it doesn't

File: golang/cosmos/app/app.go [hunk 4]
```diff
@@ -137,13 +137,16 @@ import (
...
-const FlagSwingStoreExportDir = "swing-store-export-dir"
+const (
+	// FlagSwingStoreExportDir defines the config flag used to specify where a
+	// genesis swing-store export is expected. For start from genesis, the default
+	// value is config/swing-store in the home directory. For genesis export, the
+	// value is always a "swing-store" directory sibling to the exported
+	// genesis.json file.
+	// TODO: document this flag in config, likely alongside the genesis path
+	FlagSwingStoreExportDir  = "swing-store-export-dir"
+	FlagSwingStoreExportMode = "swing-store-export-mode"
```
Comment (mhofman) [inline golang/cosmos/app/app.go:154]: Let's add a godoc comment for this flag

File: golang/cosmos/daemon/cmd/root.go [hunk 5]
```diff
@@ -386,6 +386,12 @@ const (
 	ExportedSwingStoreDirectoryName = "swing-store"
 )
 
+var allowedSwingSetExportModes = map[string]bool{
+	swingsetkeeper.SwingStoreArtifactModeDebug:       true,
+	swingsetkeeper.SwingStoreArtifactModeOperational: true,
+	swingsetkeeper.SwingStoreArtifactModeSkip:        true,
```
Comment (mhofman) [inline golang/cosmos/daemon/cmd/root.go]: This is a bit of a hacky reuse, especially because skip is not a current artifact mode. It would be clearer to define explicit constants for the swing-store genesis export mode, describing what each one does.

File: golang/cosmos/daemon/cmd/root.go (hunk 1 above)
Comment (mhofman) [reply golang/cosmos/daemon/cmd/root.go]: I think that's fine, but I'd like @michaelfig to confirm, especially with his upcoming changed for split brains. Basically export only needs to launch the VM if it will export the swing-store, which is decided by a command line config. Since `OnExportHook` is unconditionally set or not based on the entrypoint used, the only option we have is to ignore it here.

Comment (mhofman) [reply golang/cosmos/daemon/cmd/root.go]: Btw, my brain still struggles with distributing negations. 

```suggestion
	if swingStoreExportMode != swingsetkeeper.SwingStoreArtifactModeSkip && OnExportHook != nil {
```

File: golang/cosmos/x/swingset/genesis.go [hunk 6]
```diff
@@ -130,36 +130,57 @@ func InitGenesis(ctx sdk.Context, k Keeper, swingStoreExportsHandler *SwingStore
...
+			hasher:         sha256.New(),
+			exportMode:     swingStoreExportMode,
+		}
+
+		err := swingStoreExportsHandler.InitiateExport(
+			// The export will fail if the export of a historical height was requested outside of debug mode
+			snapshotHeight,
+			eventHandler,
+			keeper.SwingStoreExportOptions{
+				ArtifactMode:   swingStoreExportMode,
```
Comment (mhofman) [inline golang/cosmos/x/swingset/genesis.go]: I would prefer to set above a `artifactMode := swingStoreExportMode` and explain that the values for this option currently matches for non skip.

File: golang/cosmos/x/swingset/genesis.go [hunk 7]
```diff
@@ -130,36 +130,57 @@ func InitGenesis(ctx sdk.Context, k Keeper, swingStoreExportsHandler *SwingStore
...
+	swingStoreExportMode string,
+) *types.GenesisState {
 	gs := &types.GenesisState{
-		Params:               k.GetParams(ctx),
-		State:                k.GetState(ctx),
-		SwingStoreExportData: nil,
+		Params:                   k.GetParams(ctx),
+		State:                    k.GetState(ctx),
+		SwingStoreExportData:     nil,
+		SwingStoreExportDataHash: "",
```
Comment (mhofman) [inline golang/cosmos/x/swingset/genesis.go]: This should actually always be set, even in skip mode, to avoid triggering the ["bootstrap" logic from import genesis](https://github.com/Agoric/agoric-sdk/blob/4b1403aa06a6c08aae2d4cce0fd582480b7e3c7f/golang/cosmos/x/swingset/genesis.go#L44-L45).

Most likely we want to create the hasher in all cases (`hasher := sha256.New()`), and `gs.SwingStoreExportDataHash = fmt.Sprintf("sha256:%x", hasher.Sum(nil))` would be done even if we didn't call `InitiateExport`. The hasher will simply try to hash the empty string and return `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`.

Importing such a genesis [will cause a panic when trying to open the export directory](https://github.com/Agoric/agoric-sdk/blob/4b1403aa06a6c08aae2d4cce0fd582480b7e3c7f/golang/cosmos/x/swingset/genesis.go#L50-L53), which is what we want.

File: golang/cosmos/x/swingset/genesis.go [hunk 8]
```diff
@@ -169,32 +190,72 @@ type swingStoreGenesisEventHandler struct {
...
+			if !artifactsEnded {
+				artifact, err = provider.ReadNextArtifact()
+			} else {
+				return types.SwingStoreArtifact{}, io.EOF
+			}
+
+			if err == io.EOF {
+				artifactsEnded = true
+				if eventHandler.exportMode == keeper.SwingStoreArtifactModeDebug {
+					exportDataReader, _ := getExportDataReader()
```
Comment (mhofman) [inline golang/cosmos/x/swingset/genesis.go]: This should come from the swing-store export (aka `provider.GetExportDataReader()`).

File: golang/cosmos/x/swingset/genesis.go [hunk 9]
```diff
@@ -169,32 +190,72 @@ type swingStoreGenesisEventHandler struct {
...
+					err = agoric.EncodeKVEntryReaderToJsonl(
+						exportDataReader,
+						&encodedExportData,
+					)
+					if err == nil {
+						artifact = types.SwingStoreArtifact{
+							Data: encodedExportData.Bytes(),
+							Name: keeper.UntrustedExportDataArtifactName,
+						}
+					}
```
Comment (mhofman) [inline golang/cosmos/x/swingset/genesis.go:266]: It really is a bit unfortunate we have to read, decode, re-encode it all in memory before finally writing it out, but streamlining this is definitely out of scope.

File: golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go [hunk 10]
```diff
@@ -160,7 +160,7 @@ type swingStoreRestoreExportAction struct {
 const (
 	// SwingStoreArtifactModeNone means that no artifacts are part of the
 	// export / import.
-	SwingStoreArtifactModeNone = "none"
+	SwingStoreArtifactModeSkip = "skip"
```
Comment (mhofman) [inline golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go]: I very much would like to not change this as it matches [cosmic-swingset definitions](https://github.com/Agoric/agoric-sdk/blob/4b1403aa06a6c08aae2d4cce0fd582480b7e3c7f/packages/cosmic-swingset/src/export-kernel-db.js#L27)

File: golang/cosmos/x/swingset/genesis.go [hunk 11]
```diff
@@ -169,32 +190,72 @@ type swingStoreGenesisEventHandler struct {
...
+		encoder.SetEscapeHTML(false)
+
+		return agoric.NewKVHookingReader(kvReader, func(entry agoric.KVEntry) error {
+			return encoder.Encode(entry)
+		}, func() error {
+			return nil
+		}), nil
+	}
+
 	artifactsProvider := keeper.SwingStoreExportProvider{
```
Comment (mhofman) [inline golang/cosmos/x/swingset/genesis.go:223]: In the case of debug mode (and only in this case), the export artifact should capture the blockHeight of the swing-store, so we don't completely lose track of it (we unfortunately don't have a better place to stash it)

```go
if eventHandler.exportMode == keeper.SwingStoreArtifactModeDebug {
  artifactProvider.BlockHeight = provider.BlockHeight
}
```

File: golang/cosmos/x/swingset/genesis.go [hunk 12]
```diff
@@ -169,32 +190,72 @@ type swingStoreGenesisEventHandler struct {
...
 }
 
 func (eventHandler swingStoreGenesisEventHandler) OnExportStarted(height uint64, retrieveSwingStoreExport func() error) error {
 	return retrieveSwingStoreExport()
 }
 
 func (eventHandler swingStoreGenesisEventHandler) OnExportRetrieved(provider keeper.SwingStoreExportProvider) error {
-	if eventHandler.snapshotHeight != provider.BlockHeight {
+	if !((eventHandler.exportMode == keeper.SwingStoreArtifactModeDebug && eventHandler.snapshotHeight == 0) ||
+		eventHandler.snapshotHeight == provider.BlockHeight) {
```
Comment (mhofman) [inline golang/cosmos/x/swingset/genesis.go]: Part of this check is technically redundant 

```suggestion
	if eventHandler.exportMode != keeper.SwingStoreArtifactModeDebug &&
		eventHandler.snapshotHeight != provider.BlockHeight {
```

**Review by mhofman — CHANGES_REQUESTED** [review]
Thanks for digging through this. The main issue is that we don't currently write out the "export data" as "untrusted copy" in debug mode, but instead we-write the cosmos DB copy.

File: golang/cosmos/daemon/cmd/root.go (hunk 5 above)
Comment (usmanmani1122) [reply golang/cosmos/daemon/cmd/root.go]: You are right. `skip` is not a supported artifact mode. I will revert `SwingStoreArtifactModeSkip` to `SwingStoreArtifactModeNone`.
But I don't see `SwingStoreArtifactModeNone` and `SwingStoreArtifactModeDebug` used elsewhere and I think they were defined for controlling the artifact mode. So why not use them?

File: golang/cosmos/x/swingset/genesis.go (hunk 7 above)
Comment (usmanmani1122) [reply golang/cosmos/x/swingset/genesis.go]: I thought we wanted to trigger the bootstrap logic
And will the reason of the panic be the absence of directory pointed by `swingStoreExportDir`?

File: golang/cosmos/x/swingset/genesis.go (hunk 8 above)
Comment (usmanmani1122) [reply golang/cosmos/x/swingset/genesis.go]: Yes. My bad. Not sure why I changed it in [this](https://github.com/Agoric/agoric-sdk/pull/10344/commits/8811fc0c264775209999aef8dd1526db86e65293) commit 😄

File: golang/cosmos/daemon/cmd/root.go (hunk 5 above)
Comment (mhofman) [reply golang/cosmos/daemon/cmd/root.go]: It's more of a conceptual question. We're not just controlling the artifacts part of the swing-store export, but what kind of swing-store export we want to do. It happens that we're partially reusing the same words to describe the whole export, as the artifacts part if a bug component of it.

File: golang/cosmos/x/swingset/genesis.go (hunk 7 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/genesis.go]: We definitely don't want to trigger swingset bootstrap for any genesis export, at least not without a manual intervention on the genesis file. And yeah it'd be the missing directory as the genesis would be saying "hey look at the data alongside for swing set" and there is none.

File: golang/cosmos/daemon/cmd/root.go (hunk 5 above)
Comment (usmanmani1122) [reply golang/cosmos/daemon/cmd/root.go]: Done

File: golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go [hunk 13]
```diff
@@ -195,6 +195,20 @@ const (
...
+
+	// SwingStoreExportModeOperational (default) indicates export should
+	// have the minimal set of artifacts needed to operate a node.
+	SwingStoreExportModeOperational = "operational"
+
+	// SwingStoreExportModeDebug indicates export should have the maximal
+	// set of artifacts available in the JS swing-store.
+	SwingStoreExportModeDebug = "debug"
+)
+
```
Comment (mhofman) [inline golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go]: Let's move these to `genesis.go` as it's only applicable to that logic.

File: golang/cosmos/x/swingset/genesis.go (hunk 2 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/genesis.go]: Right, `EncodeKVEntryReaderToJsonl` doesn't close the reader. I think that was because I wanted the reader to be closed even if a read error occurred, and leave the caller in charge of handling potentially double errors. I'm not sure if that's the idiomatic golang thing to do, and would be open to reconsider if it's not.

**Review by mhofman — APPROVED** [review]
Assuming my final nit is addressed, feel free to merge this. Thanks for working on this.
