### PR TITLE
fix(cosmic-swingset): reduce unnecessary logs

### LINKED ISSUE #424: silence unnecessary logs
It's important not to print logs that are redundant, especially when they happen frequently.

Otherwise, it is easy to chew up log storage on hosted platforms that charge for usage.

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #424

### CODE REVIEW

File: packages/cosmic-swingset/x/swingset/handler.go [hunk 1]
```diff
@@ -147,13 +147,17 @@ func handleMsgBeginBlock(ctx sdk.Context, keeper Keeper) {
...
 
-	out, err := CallToNode(string(b))
-	fmt.Fprintln(os.Stderr, "Returned from SwingSet", out, err)
+	// fmt.Fprintln(os.Stderr, "Returned from SwingSet", out, err)
 	UnregisterPortHandler(newPort)
-	return
+	if err != nil {
+		return sdk.ErrInternal(err.Error()).Result()
+	}
+	return sdk.Result{} // return
```
Comment (Chris-Hibbert) [inline packages/cosmic-swingset/x/swingset/handler.go]: does "// return" add anything here?

File: packages/cosmic-swingset/x/swingset/handler.go [hunk 2]
```diff
@@ -119,18 +119,18 @@ func handleMsgDeliverInbound(ctx sdk.Context, keeper Keeper, msg MsgDeliverInbou
 	if err != nil {
 		return sdk.ErrInternal(err.Error()).Result()
 	}
-	fmt.Fprintln(os.Stderr, "About to call SwingSet")
+	// fmt.Fprintln(os.Stderr, "About to call SwingSet")
```
Comment (Chris-Hibbert) [inline packages/cosmic-swingset/x/swingset/handler.go]: I don't see much point in commenting out print statements like these. If there was more state being reported, and one might forget to include enough  if it, it would be more worthwhile. As it is, it would be fine to remove them entirely.

**Review by Chris-Hibbert — APPROVED** [review]

File: packages/cosmic-swingset/x/swingset/handler.go (hunk 1 above)
Comment (michaelfig) [reply packages/cosmic-swingset/x/swingset/handler.go]: Removed.

File: packages/cosmic-swingset/x/swingset/handler.go (hunk 2 above)
Comment (michaelfig) [reply packages/cosmic-swingset/x/swingset/handler.go]: Okay, removed.
