### PR TITLE
ag-solo plugin interface

### LINKED ISSUE #1719: Synthetic presences are not first-class
**Describe the bug**
Presences that are created within a SwingSet vat's user code do not have their handlers invoked by liveSlots.  Instead, messages arriving for them are reified as method calls on the presence itself.

**To Reproduce**
1. Create a presence with a fulfilledHandler within a Vat, and return it to a caller:
```js
xport function buildRootObject(vatPowers) {
  return harden({ getPresenceP() { 
    return new HandledPromise((_res, _rej, resolveWithPresence) => {
      resolveWithPresence({
        applyMethod(_p, name, args) {
          return `Hello there ${name}`;
        },
      });
    });
  } });
};
```
2. Fetch that vat's presence from the REPL:
```js
presence = E(myVat).getPresenceP()
```
3. The handler is not triggered when called:
```
E(presence).foo()
// Promise.reject("TypeError: target[foo] does not exist, has ")
```

**Expected behavior**
I expected messages inbound to the vat to be forwarded to the presence's handler, and to receive `"Hello there foo"`.

**Platform Environment**
 - MacOS, Node.js 12.16.1
 - what version of the Agoric-SDK are you using? `@agoric/sdk@2.7.2-72-g2be22e63`

**Additional context**
This is blocking the #1718 plugin interface design.

**Screenshots**
Screen Shot 2020-09-08 at 1 41 32 AM

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #1719 but currently, the `stall=0` Swingset tests are marked as known failures.

A plugin system for ag-solo.  This currently allows privileged modules to interact with the rest of SwingSet via a CapTP link and the SwingSet device model.

This is begging to be wrapped with LavaMoat, but for now, it is no worse than a dynamic `web.js` which can be installed via `agoric deploy`.

Given `lib/ag-solo/hello.js` of:

```js
import { promises as fs } from 'fs';

export const bootPlugin = ({ getState, setState }) => {
  let state = getState() || { count: 0 };
  const dataFile = `${__filename}.dat`;
  console.error('got initial state', dataFile, state);
  return harden({
    start(_opts) {
      return harden({
        hello(name) {
          state = { count: state.count + 1 };
          setState(state);
          await fs.writeFile(dataFile, `Said hello ${state.count} times`);
          return `Hello, ${name}`;
        },
      });
    },
  });
};
```

Implements:

```js
helloObj = E(local.plugin).load('./hello')
E(helloObj).hello('World') // Promise.resolve('Hello, World!')
```

and if you cat the data file, it should have the message written in it.

### CODE REVIEW

**Comment by michaelfig** [comment]
I've got this working, even across `ag-solo` restarts.  Next comes making the swingset tests pass, then running it past the crack kernel team (@warner, @FUDCo) and documenting it.

**Comment by michaelfig** [comment]
The failures all seem to be of this form: https://github.com/Agoric/agoric-sdk/pull/1718/checks?check_run_id=1088192711#step:7:966

Could either of you advise me if this is an overspecified test, or if I introduced something incorrect?

**Comment by warner** [comment]
> The failures all seem to be of this form: https://github.com/Agoric/agoric-sdk/pull/1718/checks?check_run_id=1088192711#step:7:966
> 
> Could either of you advise me if this is an overspecified test, or if I introduced something incorrect?

Thta doesn't quite feel like an overspecified test. It feels like an extra message is being sent, or a message is being omitted that ought to be present. I'll need to look at the full set of messages to learn more.

**Comment by michaelfig** [comment]
@warner, @FUDCo this is R4R now.  I'm using it with great success in Agoric/dapp-encouragement#62.

File: packages/eventual-send/src/index.js [hunk 1]
```diff
@@ -355,15 +357,36 @@ export function makeHandledPromise() {
...
+      }
+      if (!t) {
+        const ftype = typeof t;
+        throw new TypeError(
+          `target cannot contain [${q(method)}], typeof is ${ftype}`,
+        );
+      }
+      if (!(method in t)) {
+        const names = Object.getOwnPropertyNames(t).sort();
+        throw new TypeError(
```
Comment (warner) [inline packages/eventual-send/src/index.js]: I think I used `new Error` when I first started, but since then I've moved to just `Error`. Feel free to stick with your own pre-existing convention instead of copying my confused one :)

File: packages/agoric-cli/lib/main.js [hunk 2]
```diff
@@ -107,6 +107,11 @@ const main = async (progname, rawArgs, powers) => {
   program
     .command('deploy [script...]')
     .description('run a deployment script against the local Agoric VM')
+    .option(
+      '--allow-unsafe-plugins',
+      'CAREFUL: allow the deploy script full control over the Agoric VM',
```
Comment (warner) [inline packages/agoric-cli/lib/main.js]: it's not just the VM, right? it's the entire Unix user account.

File: packages/captp/test/test-disco.js [hunk 3]
```diff
@@ -1,5 +1,3 @@
-/* global harden */
-
 import '@agoric/install-ses';
```
Comment (warner) [inline packages/captp/test/test-disco.js:1]: oh, this tests disconnect? For some reason I thought "disco" was short for "discovery".

File: packages/cosmic-swingset/lib/ag-solo/vats/bootstrap.js [hunk 4]
```diff
@@ -242,6 +249,7 @@ export function buildRootObject(vatPowers, vatParameters) {
 
     return allComparable(
       harden({
+        ...(plugin ? { plugin } : {}),
```
Comment (warner) [inline packages/cosmic-swingset/lib/ag-solo/vats/bootstrap.js:250]: I'm anxious about exposing this to the `.local` object, but I think that's the only way to make your dynamic scheme work.

File: packages/cosmic-swingset/lib/ag-solo/vats/plugin.js [hunk 5]
```diff
@@ -0,0 +1,185 @@
...
+      E(resetter).onReset(false);
+
+      // Start the first connection.
+      connect();
+
+      // Give up our bootstrap object for the caller to use.
+      return harden({
+        // This is the public state, a promise that never resolves,
+        // but pipelines messages to the bootPK.promise.
+        bootstrap: actions.makeStableForwarder(),
```
Comment (warner) [inline packages/cosmic-swingset/lib/ag-solo/vats/plugin.js]: you might name this something other than `bootstrap` to avoid confusion with the first kernel message to the bootstrap vat. "start" or "init" or "prepare" or "setup", combined with "plugin" and/or "manager" or something.

File: packages/SwingSet/src/devices/plugin-src.js [hunk 6]
```diff
@@ -0,0 +1,134 @@
...
+          },
+          setState(state) {
+            return new HandledPromise(resolve => {
+              connectedState[index] = state;
+              endowments.queueThunkForKernel(() => {
+                // TODO: This is not a synchronous call.
+                // We need something akin to read-write separation
+                // to get the benefits of both sync and async.
+                saveState();
+                resolve();
```
Comment (warner) [inline packages/SwingSet/src/devices/plugin-src.js:76]: I think we'll end up needing a different coordination mechanism, so the caller can know they're if/when they're supposed to cycle the kernel after triggering a message.

**Review by warner — CHANGES_REQUESTED** [review]
Ok, I'm nervous about the implications, but I think we discussed the issues well enough, and I know you need this to progress.

Please see if you can write a unit test for the swingset-side device. We have plans to change the device API a lot, and I don't think I can keep it working under maintenance without tests.

File: packages/captp/test/test-disco.js (hunk 3 above)
Comment (michaelfig) [reply packages/captp/test/test-disco.js:1]: Remnants of my days in the telecom industry.

File: packages/cosmic-swingset/lib/ag-solo/vats/bootstrap.js (hunk 4 above)
Comment (michaelfig) [reply packages/cosmic-swingset/lib/ag-solo/vats/bootstrap.js:250]: Right.  Now, only agents with an access token can get to `.local`.

File: packages/SwingSet/src/devices/plugin-src.js (hunk 6 above)
Comment (michaelfig) [reply packages/SwingSet/src/devices/plugin-src.js:76]: Yes, absolutely.

**Comment by michaelfig** [comment]
> Please see if you can write a unit test for the swingset-side device. We have plans to change the device API a lot, and I don't think I can keep it working under maintenance without tests.

Will do!

File: packages/cosmic-swingset/lib/ag-solo/vats/plugin.js (hunk 5 above)
Comment (michaelfig) [reply packages/cosmic-swingset/lib/ag-solo/vats/plugin.js]: It's the CapTP bootstrap object.  I'll call it pluginRoot.

**Comment by michaelfig** [comment]
> Please see if you can write a unit test for the swingset-side device. We have plans to change the device API a lot, and I don't think I can keep it working under maintenance without tests.

@warner, I've added a relatively simple test.  R4R.

File: packages/agoric-cli/lib/main.js (hunk 2 above)
Comment (michaelfig) [reply packages/agoric-cli/lib/main.js]: So does `agoric deploy` as a whole (without the `--allow-unsafe-plugins` flag).  So I added a bigger top-level warning, too.

File: packages/SwingSet/test/device-plugin/test-device.js [hunk 7]
```diff
@@ -0,0 +1,109 @@
+/* global harden */
+import '@agoric/install-ses';
+import test from 'ava';
+import { buildVatController } from '../../src/index';
+import { buildBridge } from '../../src/devices/bridge';
+import { buildPlugin } from '../../src/devices/plugin';
+
+test.before('initialize hostStore', t => {
+  const m = new Map();
```
Comment (warner) [inline packages/SwingSet/test/device-plugin/test-device.js]: this works, but I'd bet `@agoric/swing-store-simple` has what you need

File: packages/SwingSet/src/devices/plugin-src.js [hunk 8]
```diff
@@ -0,0 +1,134 @@
...
+        // console.info('receiver', index, obj);
+
+        // We need to run the kernel after the send-only.
+        endowments.queueThunkForKernel(() =>
+          SO(registeredReceiver).dispatch(index, obj),
+        );
+      };
+      // Create a bootstrap reference from the module.
+      const bootstrap = modNS.bootPlugin(
+        harden({
```
Comment (warner) [inline packages/SwingSet/src/devices/plugin-src.js:64]: to test the transcript replay is working correctly, we should pass through `testLog` here, so the loaded module can write things where the unit test can see them

File: packages/SwingSet/test/device-plugin/pingpong.js [hunk 9]
```diff
@@ -0,0 +1,14 @@
+/* global harden */
+
+export function bootPlugin() {
+  return harden({
+    start(opts) {
+      const { prefix } = opts;
+      return harden({
+        ping(msg) {
```
Comment (warner) [inline packages/SwingSet/test/device-plugin/pingpong.js:8]: To test the transcript, this should pull `testLog` from the object passed as the first argument to `bootPlugin` (maybe call it `pluginPowers` to mimic `vatPowers`), and do `testLog('ping')` or something.

We're expecting `ping` to appear exactly once, even though the swingset has been reloaded from saved state. The bootstrap function is executed multiple times (once initially, then once per reload as the transcript is replayed), but the syscall it makes to talk to the device is simulated on the non-initial passes, so the device should only receive the initial call.

File: packages/SwingSet/test/device-plugin/test-device.js [hunk 10]
```diff
@@ -0,0 +1,109 @@
...
+    t,
+  );
+
+  queueThunkForKernel(() => bridge.deliverInbound('pingpong'));
+  await cycle();
+
+  t.deepEqual(dump().log, [
+    'starting plugin test',
+    'installing pingPongP',
+    'starting pingpong test',
```
Comment (warner) [inline packages/SwingSet/test/device-plugin/test-device.js:67]: when you add the `testLog` in the loaded module, we should see the `ping` here, after "starting pingpong test" and before "pingpong reply"

File: packages/SwingSet/test/device-plugin/test-device.js [hunk 11]
```diff
@@ -0,0 +1,109 @@
...
+    'pingpong reply = Whoopie Agoric!',
+    'starting pingpong test',
+    'pingpong reply = Whoopie Agoric!',
```
Comment (warner) [inline packages/SwingSet/test/device-plugin/test-device.js:91]: and we should specifically *not* see a second copy here

Note that the `testLog` is ephemeral: it is not recorded in the kernelDB. However when vats are replayed, they *do* write their messages to the `testLog`, even though their syscalls are being simulated/blocked. So it kinda *looks* like the testLog is persistent, but it's not, it's just being deterministically regenerated.

**Review by warner — APPROVED** [review]
Ok, that tests looks good, thanks.

Please open a ticket to improve the test after Alpha, to exercise the replay behavior as indicated.
