### PR TITLE
fix: Add consensus-independent vat snapshot/transcript archiving configuration

### LINKED ISSUE #10036: swingstore mode to move/archive historical transcript spans to separate files, outside the DB
## What is the Problem Being Solved?

As [discussed here](https://github.com/Agoric/agoric-sdk/issues/9389#issuecomment-2332868090), I kinda want a swing-store mode like `{ keepTranscripts: false, archiveTranscriptsInto: DIRNAME }`, which would instruct the `transcriptStore` to write a compressed span into a new file in DIRNAME, just before deleting the items of that span.

My goal is to enable an external script (some combination of `mv` and `scp` or `s3cmd`) to move the completed files out of the way, upload or transfer them to some cheaper location, and then delete the originals. I want to save space on my follower's SSD, but I still want to have those old transcripts around for analysis purposes.

In addition to the new swing-store option and implementation, it would also need some plumbing through the `app.toml` config file (similar to what #10032 is doing).

## Security Considerations

None, this is a write-only option for swing-store, to a directory specified by the host application (which also specifies the directory for the SQLite file).

## Scaling Considerations

This might improve performance of the SQLite `transcriptItems` table, in configurations where historical spans are not being retained, by drastically (90%) reducing the number of rows, and correspondingly reducing the size of the index. However I don't have any reason to believe this is currently consuming a significant amount of time in our system.

The stored files would be compressed, which would save about 90% of the disk space, compared to uncompressed items remaining in SQLite. However that's not a fair comparison, because either you're retaining historical transcripts (`keepTranscripts: true`) in which case they stay in SQLite and you're consuming a whole lot of disk, or you're allowing them to be pruned from the DB (`keepTranscripts: false`) in which case you're saving all of the space. This third option that I'm asking for will consume more overall space than plain `keepTranscripts: false`, but at least it will only be consuming about 10% of the disk space that the uncompressed `transcriptItems` items would have needed. Also note that #8318 would achieve the all-but-10% space savings (by virtue of compression) while still retaining all the historical spans.

## Test Plan

unit tests in `packages/swing-store`, plus something (not sure what) for the `app.toml` wiring

## Upgrade Considerations

None, when this feature is first enabled on a node, subsequent span rollovers will start populating the given directory. This is a local, not-in-consensus property, like `maxVatsOnine` or the option to retain historical spans at all.

To avoid losing data, a node which wishes to use this mode should change from `{ keepTranscripts: true }` to `{ keepTranscripts: false, archiveTranscriptsInto: DIRNAME }` in a single step, and never run the kernel with merely `{ keepTranscripts: false }`.

cc @gibson042  @mhofman

### LINKED ISSUE #10054: swing-store: stopUsingTranscript fails to delete transcript spans
## Describe the bug
Unlike [`rolloverIncarnation` and `rolloverSpan`](https://github.com/Agoric/agoric-sdk/blob/2e66067830c76bc9f1e0ab76c54f10aec1a19f1a/packages/swing-store/src/transcriptStore.js#L296-L320), [`stopUsingTranscript`](https://github.com/Agoric/agoric-sdk/blob/2e66067830c76bc9f1e0ab76c54f10aec1a19f1a/packages/swing-store/src/transcriptStore.js#L368) does not run `sqlDeleteOldItems` even when `keepTranscripts` is false and therefore leaves entries for the previously-current span.

## Additional context
This is implicitly fixed by reloading from an export that does not include the orphaned data, but we still shouldn't leave it hanging around.

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #10036

## Description
Adds consensus-independent `vat-{snapshot,transcript}-archive-dir` cosmos-sdk swingset configuration for propagation in AG_COSMOS_INIT. When set, gzip-compressed vat snapshot/transcript files are written to the respective directory (the former when created, the latter when finalized by rollover).

It also includes miscellaneous documentation and code improvements, most significantly a new helper for replacing `const cleanups = []; return aggregateTryFinally(async () => { … cleanups.push(…); … }, async () => { await PromiseAllOrErrors(cleanups.reverse().map(fn => Promise.resolve().then(() => fn()))); });` with `return withDeferredCleanup(async addCleanup => { … addCleanup(…); … });` (i.e., folding in the cleanup registration and ordering).

Best reviewed commit-by-commit.

### Security Considerations
This provides a new interface by which the Swingset kernel can write to its host filesystem, albeit indirectly via callback. But as such, it is a potential vector for filling up a disk or possibly overwriting files, although subject to an operator's own bad configuration and/or elevated permissions.

### Scaling Considerations
When one or both new settings are active and the disk is full or slow, performance may suffer. I considered performing these writes in the background, but decided that silent failures or slow writes would be worse than the new `await`s (and when active, the archive dir will likely be on the same filesystem as the database anyway).

### Documentation Considerations
I think I've covered what I need to, although there might be some other Markdown files worth updating.

### Testing Considerations
New features are covered by unit tests.

### Upgrade Considerations
This is all kernel code that can be used at any node restart (i.e., because the configuration is consensus-independent, it doesn't even need to wait for a chain software upgrade). But we should mention the new cosmos-sdk configuration in release notes, because it won't be added to existing app.toml files already in use.

### CODE REVIEW

File: packages/swing-store/src/transcriptStore.js [hunk 1]
```diff
@@ -257,18 +257,27 @@ export function makeTranscriptStore(
     WHERE vatID = ? AND position >= ? AND position < ?
   `);
 
-  function doSpanRollover(vatID, isNewIncarnation) {
+  function closeSpan(vatID, bounds) {
```
Comment (mhofman) [inline packages/swing-store/src/transcriptStore.js]: Let's add a comment that `closeSpan` does not note any changes to the `.current` export and that the caller is in charge of that. An alternative would be to always note a deletion of that export when closing, but that's unnecessary churn for the common case.

**Review by mhofman — COMMENTED** [review]
As a matter of process, could we split and merge the first part of this PR that addresses #10054? It seems like it can stand on its own and is sufficiently different than the archive change. I have reviewed that set of commit and would approve such a PR.

File: packages/internal/src/node/utils.js [hunk 2]
```diff
@@ -28,10 +28,10 @@ export const PromiseAllOrErrors = async items => {
...
 
 /**
- * @type {<T>(
- *   trier: () => Promise<T>,
- *   finalizer: (error?: unknown) => Promise<void>,
- * ) => Promise<T>}
+ * @template T
+ * @param {() => Promise<T>} trier
+ * @param {(error?: unknown) => Promise<unknown>} finalizer
+ * @returns {ReturnType<trier>}
```
Comment (mhofman) [inline packages/internal/src/node/utils.js]: Why use `ReturnType` here instead of `Promise<T>` ?

File: packages/internal/src/node/utils.js [hunk 3]
```diff
@@ -44,3 +44,31 @@ export const aggregateTryFinally = async (trier, finalizer) =>
         )
         .then(error => Promise.reject(error)),
   );
+
+/**
+ * Run a function with the ability to defer last-in-first-out cleanup callbacks.
+ *
+ * @template T
+ * @param {(
+ *   addCleanup: (fn: (err?: unknown) => Promise<void>) => void,
```
Comment (mhofman) [inline packages/internal/src/node/utils.js]: I think `addCleanup` should be allowed to accept a function that returns something else than a promise, but the problem is that `Promise<void> | void` [has undesirable behavior](https://github.com/microsoft/TypeScript/issues/43921). Maybe `Promise<any> | any`, just for documentation purposes?

File: packages/swing-store/test/deletion.test.js [hunk 4]
```diff
@@ -255,6 +260,17 @@ const execSlowTranscriptDeletion = async (t, { keepTranscripts }) => {
   );
   t.is(db.prepare('SELECT COUNT(*) FROM transcriptSpans').pluck().get(), 4);
 
+  // verify archived transcripts
+  t.deepEqual(
+    fs.readdirSync(archiveDir),
+    expectedArtifactNames.slice(0, -1).map(name => `${name}.gz`),
```
Comment (mhofman) [inline packages/swing-store/test/deletion.test.js:278]: I thought Brian wanted the incarnation number in the artifact name, but I can't find any mention of that anywhere now, and it'd be different enough from the swing-store export feature that it likely isn't warranted (as that's tightly coupled to the export kv entry's name)

File: packages/swing-store/src/transcriptStore.js
Comment (mhofman) [inline packages/swing-store/src/transcriptStore.js:1]: Consider extracting the asyncification in a standalone `refactor` commit.

File: packages/cosmic-swingset/src/chain-main.js [hunk 5]
```diff
@@ -1,14 +1,14 @@
...
 import process from 'node:process';
 import fs from 'node:fs';
 import fsPromises from 'node:fs/promises';
-import { performance } from 'perf_hooks';
-import { resolve as importMetaResolve } from 'import-meta-resolve';
-import tmpfs from 'tmp';
+import { performance } from 'node:perf_hooks';
 import { fork } from 'node:child_process';
+import { resolve as importMetaResolve } from 'import-meta-resolve';
+import tmp from 'tmp';
```
Comment (mhofman) [inline packages/cosmic-swingset/src/chain-main.js:11]: Consider extracting the rename of `path` and `tmp` in a standalone `refactor` commit.

File: packages/swing-store/test/deletion.test.js [hunk 6]
```diff
@@ -170,7 +172,18 @@ const setupTranscript = async (t, keepTranscripts) => {
...
+  t.teardown(cleanupArchives);
+  const archiveTranscript = makeArchiveTranscript(archiveDir, {
+    fs,
+    path,
+    tmp,
+  });
+  const store = initSwingStore(dbDir, {
+    exportCallback,
+    keepTranscripts,
+    archiveTranscript,
```
Comment (mhofman) [inline packages/swing-store/test/deletion.test.js:184]: Given that the swingStore does extra / different work when `archiveTranscript` is present, should this be a variation of the test?

Same for `archiveSnapshot`, especially if we end up teeing the compression stream.

File: packages/swing-store/src/archiver.js [hunk 7]
```diff
@@ -0,0 +1,44 @@
...
+  const { fs, path, tmp } = powers;
+  fs.mkdirSync(dirPath, { recursive: true });
+  const archiveTranscript = (spanName, entries) => {
+    const destPath = path.join(dirPath, `${spanName}.gz`);
+    return withDeferredCleanup(async addCleanup => {
+      const {
+        name: tmpName,
+        fd,
+        removeCallback,
+      } = tmp.fileSync({
```
Comment (mhofman) [inline packages/swing-store/src/archiver.js:61]: Why use the sync version if we're in an async function ?

File: packages/swing-store/src/archiver.js [hunk 8]
```diff
@@ -0,0 +1,44 @@
...
+        prefix: spanName,
+        postfix: '.gz',
+        detachDescriptor: true,
+      });
+      addCleanup(() => removeCallback());
+      const writer = fs.createWriteStream('', { fd, flush: true });
+      const gzip = createGzip();
+      gzip.pipe(writer);
+      const reader = Readable.from(entries);
```
Comment (mhofman) [inline packages/swing-store/src/archiver.js:70]: I am feeling conflicted about the async shape of this, and the impact it has on the rest of the swing-store. Brian seemed interested in keeping things sync.

Previous discussion on this topic at https://github.com/Agoric/agoric-sdk/pull/8693#discussion_r1442125026, captured as #8739. With the caveat that here we get to write out as a stream as well, so even the output doesn't need to be kept as a whole in memory.

File: packages/swing-store/src/archiver.js [hunk 9]
```diff
@@ -0,0 +1,44 @@
...
+    const destPath = path.join(dirPath, `${spanName}.gz`);
+    return withDeferredCleanup(async addCleanup => {
+      const {
+        name: tmpName,
+        fd,
+        removeCallback,
+      } = tmp.fileSync({
+        prefix: spanName,
+        postfix: '.gz',
+        detachDescriptor: true,
```
Comment (mhofman) [inline packages/swing-store/src/archiver.js:64]: why do we care about detaching the descriptor?

File: packages/swing-store/src/snapStore.js [hunk 10]
```diff
@@ -250,20 +255,28 @@ export function makeSnapStore(
...
         });
 
+        let archiveWriteSeconds;
+        if (archiveSnapshot) {
+          ({ duration: archiveWriteSeconds } = await measureSeconds(
+            async () => {
+              await archiveSnapshot(exportKey, compressedSnapshot);
+            },
+          ));
+        }
```
Comment (mhofman) [inline packages/swing-store/src/snapStore.js]: I was originally thinking we'd want to create a `PassThrough` stream, pipe the `gzip` stream above to it just before passing `gzip` to `buffer` (aka tee the gzip stream into the buffer and the archiver). That would avoid delaying the overall save operation with a sequential step.

**Review by mhofman — APPROVED** [review]
Overall this looks good, but please consider some of the suggested refactorings.

File: packages/swing-store/src/transcriptStore.js (hunk 1 above)
Comment (gibson042) [reply packages/swing-store/src/transcriptStore.js]: Done.

File: packages/internal/src/node/utils.js (hunk 2 above)
Comment (gibson042) [reply packages/internal/src/node/utils.js]: No strong reason, just a way to emphasize that the happy-path result is just decoration of the function.

File: packages/internal/src/node/utils.js (hunk 3 above)
Comment (gibson042) [reply packages/internal/src/node/utils.js]: I think it'd be easier to just wrap with `async () => { … }`, but we can cross that bridge if/when we get there. This is an internal async helper, and there's no current need for supporting non-async callbacks.

File: packages/swing-store/test/deletion.test.js (hunk 4 above)
Comment (gibson042) [reply packages/swing-store/test/deletion.test.js:278]: Using the export name is an obvious default, and we can make it configurable later if there's a need.

File: packages/swing-store/src/transcriptStore.js
Comment (gibson042) [reply packages/swing-store/src/transcriptStore.js:1]: It actually started that way, but it turned out that only two of the changes were non-fundamental.

File: packages/swing-store/test/deletion.test.js (hunk 6 above)
Comment (gibson042) [reply packages/swing-store/test/deletion.test.js:184]: The work is purely additive, so I figured it was fine to always check in these tests rather than multiply its configuration to the cross product of keepTranscripts={true,false} and archiveTranscript={undefined,fn}—plus there's lots of testing that covers `initSwingStore` with archiveTranscript=undefined, including in this file. Do you feel strongly about making this a test variation?

File: packages/swing-store/src/archiver.js (hunk 7 above)
Comment (gibson042) [reply packages/swing-store/src/archiver.js:61]: No strong reason; this step doesn't need to be async and honestly wouldn't benefit from it anyway.

File: packages/swing-store/src/archiver.js (hunk 9 above)
Comment (gibson042) [reply packages/swing-store/src/archiver.js:64]: The library complained without it; because of `streamFinished(writer)` IIRC.

File: packages/swing-store/src/snapStore.js (hunk 10 above)
Comment (gibson042) [reply packages/swing-store/src/snapStore.js]: I didn't want it to muddy our compressSeconds metric, which currently does not include any writes to disk. And we run sqlSaveSnapshot with the full compressed contents anyway, so it didn't seem worthwhile to optimize one half of the tee while leaving the other fundamentally non-optimized. But that intuition might be wrong, and I look forward to archiveWriteSeconds data upon which we can make a more informed decision.

**Comment by gibson042** [comment]
> As a matter of process, could we split and merge the first part of this PR that addresses #10054? It seems like it can stand on its own and is sufficiently different than the archive change. I have reviewed that set of commit and would approve such a PR.

#10060

File: packages/swing-store/src/archiver.js (hunk 8 above)
Comment (gibson042) [reply packages/swing-store/src/archiver.js:70]: I agree, but this function _really_ wants to be async, for both the deferred cleanups and for following the existing pattern established by export. The best alternative I can think of is having swing-store synchronously aggregate data into a Buffer and send that over, but on balance that seemed worse.

File: packages/swing-store/src/transcriptStore.js
Comment (mhofman) [reply packages/swing-store/src/transcriptStore.js:1]: What do you mean by "non-fundamental". I consider making a function and all its callers transitively async to be a pure refactor.

File: packages/swing-store/test/deletion.test.js (hunk 6 above)
Comment (mhofman) [reply packages/swing-store/test/deletion.test.js:184]: Not strongly no, but since we already have a macro, I thought it could be cheap enough. Not all permutations need to be tested (e.g. transcript options are fully independent of the snapshot option)

File: packages/swing-store/src/archiver.js (hunk 7 above)
Comment (mhofman) [reply packages/swing-store/src/archiver.js:61]: I'm just wondering because I believe it means the removeCallback is sync, which may be unexpected (according to types) for the cleanup. I do remember that `tmp` had some surprising changes in behavior between sync and async, but I'm not sure what those where now.

File: packages/swing-store/src/archiver.js (hunk 9 above)
Comment (mhofman) [reply packages/swing-store/src/archiver.js:64]: Oh right, stream will close the fd unless you tell it not to.

File: packages/swing-store/src/transcriptStore.js
Comment (gibson042) [reply packages/swing-store/src/transcriptStore.js:1]: Do you mean that you want to see a commit which is just marking functions as `async` and inserting `await` at their call sites, with no point-in-time motivation for such a refactor until the following commit adds internal `await`s, as opposed to a42c45f09e883643bc5156dc35e35d7076b753c3 including both? I don't think I would find that useful.

File: packages/SwingSet/src/kernel/kernel.js [hunk 11]
```diff
@@ -287,11 +288,12 @@ export default function buildKernel(
       // remove vatID from the list of live vats, and mark for deletion
       kernelKeeper.deleteVatID(vatID);
       kernelKeeper.markVatAsTerminated(vatID);
-      kernelKeeper.removeVatFromSwingStoreExports(vatID);
+      deferred.push(kernelKeeper.removeVatFromSwingStoreExports(vatID));
       for (const kpid of deadPromises) {
         resolveToError(kpid, makeError('vat terminated'), vatID);
       }
     }
+    await Promise.all(deferred);
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/kernel.js]: This is necessary to preserve the [log ordering in terminate.test.js](https://github.com/Agoric/agoric-sdk/blob/bf1e6453eee701f3e465120a03877cf44d458cc6/packages/SwingSet/test/vat-admin/terminate/terminate.test.js#L498-L504). Alternatively (or additionally), we could update [bootstrap-terminate-with-presence.js](https://github.com/Agoric/agoric-sdk/blob/bf1e6453eee701f3e465120a03877cf44d458cc6/packages/SwingSet/test/vat-admin/terminate/bootstrap-terminate-with-presence.js#L15-L32) to tolerate ordering variation.

File: packages/swing-store/src/transcriptStore.js
Comment (mhofman) [reply packages/swing-store/src/transcriptStore.js:1]: That would be my soft preference, yes. It's similar to moving some code around in a first commit in preparation for a subsequent commit which has a more minimal behavioral change.

File: packages/SwingSet/src/kernel/kernel.js (hunk 11 above)
Comment (mhofman) [reply packages/SwingSet/src/kernel/kernel.js]: I am confused about why the simple `await` was not working.

Comment (gibson042) [reply packages/SwingSet/src/kernel/kernel.js]: Figuring it out was an interesting dive... [vat-vat-admin.js `terminateWithFailure`](https://github.com/Agoric/agoric-sdk/blob/914bee2aa7472039ba230267d72027b940bf8a1c/packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js#L282) ends with a synchronous call to `D(vatAdminDev).terminateWithFailure`, which through further synchronous calls in [device-vat-admin.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/src/devices/vat-admin/device-vat-admin.js#L253) → [kernel/deviceManager.js](https://github.com/Agoric/agoric-sdk/blob/914bee2aa7472039ba230267d72027b940bf8a1c/packages/SwingSet/src/kernel/deviceManager.js#L56) → [kernel.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/src/kernel/kernel.js#L1760) → [kernelSyscall.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/src/kernel/kernelSyscall.js#L201) → [vat-admin-hooks.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/src/kernel/vat-admin-hooks.js#L97)
invokes `void terminateVat(vatID, true, marshalledReason)`, which means that only the synchronous prelude of `terminateVat` has an effect before the result promise of `E(vatAdminNode).terminateWithFailure(reason)` settles and enqueues notifies.

Before this PR, [`kernelKeeper.removeVatFromSwingStoreExports`](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/src/kernel/state/kernelKeeper.js#L933) was synchronous and therefore could not impede the [following step](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/src/kernel/kernel.js#L290-L293)'s rejection of promises yet to be decided by the terminating vat (which therefore preceded fulfillment of the `terminateWithFailure` result promise).

But now that this PR is making `removeVatFromSwingStoreExports` async, a naïve `await` thereof would end the synchronous prelude _before_ dead promise rejection, which is what caused the [assertion in terminate.test.js](https://github.com/Agoric/agoric-sdk/blob/914bee2aa7472039ba230267d72027b940bf8a1c/packages/SwingSet/test/vat-admin/terminate/terminate.test.js#L498-L504) to fail. Deferring the `await` restores the expected ordering, although we may want to move it even _further_ down to avoid bumping following logic out of the synchronous prelude, e.g.:
```js
    if (critical) {
      // The following error construction is a bit awkward, but (1) it saves us
      // from doing unmarshaling while in the kernel, while (2) it protects
      // against the info not actually encoding an error, but (3) it still
      // provides some diagnostic information back to the host, and (4) this
      // should happen rarely enough that if you have to do a little bit of
      // extra interpretive work on the receiving end to diagnose the problem,
      // it's going to be a small cost compared to the trouble you're probably
      // already in anyway if this happens.
      panic(`critical vat ${vatID} failed`, Error(info.body));
    } else if (vatAdminRootKref) {
      // static vat termination can happen before vat admin vat exists
      notifyTermination(
        vatID,
        vatAdminRootKref,
        shouldReject,
        info,
        queueToKref,
      );
    } else {
      console.log(
        `warning: vat ${vatID} terminated without a vatAdmin to report to`,
      );
    }

    // worker, if present, needs to be stopped (note that this only applies to ephemeral vats)
    deferred.push(() => vatWarehouse.stopWorker(vatID));

    await Promise.all(deferred);
```

Comment (mhofman) [reply packages/SwingSet/src/kernel/kernel.js]: I actually would want to go a step further and remove the async nature of this function, but still make it return a promise. However that would release zalgo somewhat, so we should not do that in a hurry now.

Please go ahead with the proposed change above, but use `PromiseAllOrErrors` to avoid swallowing multiple errors.

Comment (mhofman) [reply packages/SwingSet/src/kernel/kernel.js]: Filed https://github.com/Agoric/agoric-sdk/issues/10073 to track addressing this footgun

File: packages/swing-store/src/transcriptStore.js [hunk 12]
```diff
@@ -289,13 +392,13 @@ export function makeTranscriptStore(
     }
   }
 
-  function doSpanRollover(vatID, isNewIncarnation) {
+  async function doSpanRollover(vatID, isNewIncarnation) {
```
Comment (warner) [inline packages/swing-store/src/transcriptStore.js:395]: Oh, this makes me sad. Swingstore wants to be synchronous for all the "normal" day-to-day operations. I'm ok with async for `commit` and exports and things done by the host, but I'd really prefer that everything the kernel touches is synchronous.

I see that it happened to fit into the existing callers (they're already awaiting a snapshot write, or a vat eviction), so the contagion didn't have a big impact, but in general, any async operational API call raises concerns about what state the swingstore is in while that Promise is pending.

In this case, there's a period where the old span is closed, but the new span has not yet been created (we're sitting in the `await closeSpan()`, which is sitting in its `await archiveTranscript`). If someone calls into swingstore while that Promise is pending, we'll have no `isCurrent` spans, and doing something like `addItem` will throw (at best) or be very confused (at worst). With a synchronous interface, this invariant-violating state is not exposed.

As you know, I'm not a fan of async file IO, I'm not convinced that there's enough perf improvement (if any) to justify the complexity. But I do see that you didn't have a lot of choice.. the gzip streams used by `makeArchiveTranscript` would be a PITA to use synchronously (but that just makes me sad about the gzip APIs we have available).

So, ok, but let's make it a goal to keep the API synchronous, and only allow exceptions like this when really necessary.

(sorry I missed this when the review was pending, I was OOO).

Comment (gibson042) [reply packages/swing-store/src/transcriptStore.js:395]: No worries; after the fact reviews are still much appreciated! Should we open a new ticket about refactoring to isolate asynchronicity?
