### PR TITLE
fix: start swing-store export without blocking checks

### LINKED ISSUE #9418: Operational swing-store slow to open DB for export
## Describe the bug
With a devnet state (and likely on mainnet as well), the swing-store export logic seems to be really slow when opening the store. The time elapsed until the 'started' event is issued can go from 20-30 seconds on a fast SSD (my dev machine), up to 30 minutes on GKE (instagoric devnet validator), which seem to have somewhat low perf I/O. This seems irrespective of whether there is a concurrent writer connection open to the DB or not (but other I/O on the system may affect this time). A "vacuumed" swing-store DB (exported then reimported) takes slightly less time (roughly half on GKE).

## To Reproduce
Use `gs://agoric-chain-backups/agoricdev-23-data-agoric-block-3382307.tgz` and initiate an export using `export-kernel-db.js`, or `gs://agoric-chain-backups/agoricdev-23-swingstore-3382307.sqlite.gz` for the same, but vacuumed one.

Alternatively start a devnet follower with `gs://agoric-chain-backups/agoricdev-23-3406000.tar.gz`, a (fully pruned / vacuumed) cosmos data snapshot (tendermint state missing, need to bootstrap from light client), enable state-sync snapshot, and observe `cosmic-swingset-snapshot` slog timings (captured below)

## Expected behavior
Opening a new swing-store connection and starting the export transaction should take less than 6 seconds, aka the time of a new block to be produced) to not delay node operations

## Platform Environment
 - devnet-23 node (running agoric-upgrade-15) in GKE

## Screenshots
```
{"type":"cosmic-swingset-commit-block-finish","blockHeight":3448000,"blockTime":1716793106,"saveTime":0.007,"chainTime":0,"fullSaveTime":1.382,"time":1716793113.339064,"monotime":2767.921415152013}
{"type":"cosmic-swingset-after-commit-stats","blockHeight":3448000,"blockTime":1716793106,"memoryUsage":{"rss":1015324672,"heapTotal":46784512,"heapUsed":41045928,"external":9018711,"arrayBuffers":5823086},"heapStats":{"total_heap_size":46784512,"total_heap_s>
{"type":"cosmic-swingset-snapshot-start","blockHeight":3448000,"request":"initiate","args":[{"artifactMode":"replay","exportDataMode":"skip"}],"time":1716793113.379051,"monotime":2767.9614016709925}
{"type":"cosmic-swingset-begin-block","blockHeight":3448001,"blockTime":1716793111,"inboundQueueStats":{"cosmic_swingset_inbound_queue_length":0,"cosmic_swingset_inbound_queue_add":110,"cosmic_swingset_inbound_queue_remove":110},"time":1716793117.491427,"mono>
{"type":"cosmic-swingset-end-block-start","blockHeight":3448001,"blockTime":1716793111,"time":1716793117.496762,"monotime":2772.0791101230384}
--
{"type":"cosmic-swingset-run-finish","blockHeight":3448001,"runNum":2,"startBeans":0,"finishBeans":1658518800,"usedBeans":1658518800,"remainingBeans":4841481200,"time":1716793119.710186,"monotime":2774.2925318900348}
{"type":"cosmic-swingset-end-block-finish","blockHeight":3448001,"blockTime":1716793111,"inboundQueueStats":{"cosmic_swingset_inbound_queue_length":0,"cosmic_swingset_inbound_queue_add":111,"cosmic_swingset_inbound_queue_remove":111},"time":1716793119.711026,>
{"type":"cosmic-swingset-snapshot-finish","blockHeight":3448000,"request":"initiate","args":[{"artifactMode":"replay","exportDataMode":"skip"}],"time":1716793683.241991,"monotime":3337.824341889024}
{"type":"cosmic-swingset-commit-block-start","blockHeight":3448001,"blockTime":1716793111,"time":1716793683.243273,"monotime":3337.825620804012}
{"type":"cosmic-swingset-commit-block-finish","blockHeight":3448001,"blockTime":1716793111,"saveTime":0.11,"chainTime":0,"fullSaveTime":563.989,"time":1716793683.700302,"monotime":3338.2826520609856}
--
{"type":"cosmic-swingset-commit-block-finish","blockHeight":3451345,"blockTime":1716811956,"saveTime":0.005,"chainTime":0,"fullSaveTime":0.057,"time":1716811962.856074,"monotime":21617.438422158957}
{"type":"cosmic-swingset-after-commit-stats","blockHeight":3451345,"blockTime":1716811956,"memoryUsage":{"rss":1626034176,"heapTotal":60940288,"heapUsed":50556512,"external":9073834,"arrayBuffers":5878209},"heapStats":{"total_heap_size":60940288,"total_heap_s>
{"type":"cosmic-swingset-snapshot-start","request":"retrieve","time":1716811967.184669,"monotime":21621.76701863098}
{"type":"cosmic-swingset-snapshot-finish","request":"retrieve","result":"/state/tmp/agd-state-sync-3448000--94-LkARjtE1idt7","time":1716811967.184994,"monotime":21621.767341470957}
{"type":"cosmic-swingset-begin-block","blockHeight":3451346,"blockTime":1716811962,"inboundQueueStats":{"cosmic_swingset_inbound_queue_length":0,"cosmic_swingset_inbound_queue_add":905,"cosmic_swingset_inbound_queue_remove":905},"time":1716811968.261525,"mono>
{"type":"cosmic-swingset-end-block-start","blockHeight":3451346,"blockTime":1716811962,"time":1716811968.265865,"monotime":21622.848213718058}
```

### PR DESCRIPTION
**Pull request by mhofman**
closes: #9418

## Description

This moves the completeness check from being eager when creating the exporter to delayed when yielding the artifact names list.
It also updates the kernel export logic to yield to the event loop after triggering the started event and before initiating the actual export, so that any IPC messages have a chance to be sent.

### Security Considerations

None

### Scaling Considerations

The consumer will no longer get an early error if the DB is not suitable for export. In practice that doesn't change anything since the state-sync logic was already not in a position to handle such an early error.

However the state-sync export relied on the "started" event to have triggered by the time the next block commit was reached. The completeness check here was happening before that point, and could take a significant amount of time as described in #9418.

### Documentation Considerations

None

### Testing Considerations

Manually verified, and verifying with a patched upgrade-15 image on devnet instagoric.
Updated tests to reflect that making the exporter does not immediately fails if incomplete.

`export-kernel-db.js` is not sufficiently covered by test to automate testing of the `started` message.

### Upgrade Considerations

None

### CODE REVIEW

File: packages/swing-store/src/exporter.js [hunk 1]
```diff
@@ -170,14 +164,22 @@ export function makeSwingStoreExporter(dirPath, options = {}) {
...
+      const internal = { snapStore, bundleStore, transcriptStore };
+      assertComplete(internal, artifactMode);
+    }
+    // weird construct here is because we need to be able to throw before the generator starts
+    async function* exporter() {
+      yield* snapStore.getArtifactNames(artifactMode);
+      yield* transcriptStore.getArtifactNames(artifactMode);
+      yield* bundleStore.getArtifactNames();
+    }
+    harden(exporter);
```
Comment (warner) [inline packages/swing-store/src/exporter.js]: To match the protective behavior of the original version, we still need to `harden(getArtifactNames)`, otherwise two isolated importers of the module could use it to communicate.

I don't think `harden(exporter)` does anything useful: we don't return it, and the caller has no way to access it.

I don't know whether it would be useful to harden the *iterator* that is returned by this function.. the original did not do that, and I think it doesn't represent a communication channel (since each invocation of `getArtifactNames()` returns a different iterator).

File: packages/swing-store/test/exportImport.test.js [hunk 2]
```diff
@@ -220,15 +220,13 @@ async function testExportImport(
     await ssOut.hostStorage.commit();
   }
 
+  const exporter = makeSwingStoreExporter(dbDir, { artifactMode: exportMode });
```
Comment (warner) [inline packages/swing-store/test/exportImport.test.js:226]: maybe add a comment for the future here

```js
// this exporter is broken (the swingstore is incomplete), but that is signaled during `getArtifactNames()`, not during construction (which must finish quickly, without scanning the whole DB)
```

**Review by warner — APPROVED** [review]
Looks good, approved assuming you address the `harden()` comment.

File: packages/swing-store/src/exporter.js (hunk 1 above)
Comment (mhofman) [reply packages/swing-store/src/exporter.js]: That is not actually correct.
- `exporter` needs to be hardened because it's actually available through the iterator object. Generators are like defining a class.
- `getArtifactNames` as a generator was previously explicitly hardened for that reason. We don't have a lint rule about explicitly hardening generators, but we probably should, if we could. However it was always redundant since it was getting hardened as a method of the `Exporter` object returned by this maker. Because it's now a simple non-generator function, we can rely on that harden.

Comment (mhofman) [reply packages/swing-store/src/exporter.js]: I actually didn't need it to be in the closure, so extracted. It should be slightly less clunky

File: packages/cosmic-swingset/src/export-kernel-db.js [hunk 3]
```diff
@@ -192,6 +193,9 @@ export const initiateSwingStoreExport = (
     abortIfStopped();
     startedKit.resolve();
     log?.(`Starting DB export at block height ${savedBlockHeight}`);
+    // Let the `started` event be sent before proceeding with blocking processing:
+    // `getArtifactNames` may block the agent for a while.
+    await waitUntilQuiescent();
```
Comment (mhofman) [inline packages/cosmic-swingset/src/export-kernel-db.js:198]: When testing this in instagoric, I noticed that the previous change was not sufficient. I suspect an `await null` may be enough here, but turning the event loop is much more robust. This is a somewhat strange layering inversion that I don't see how to better handle.

File: packages/swing-store/src/exporter.js (hunk 1 above)
Comment (warner) [reply packages/swing-store/src/exporter.js]: ah, ok, I didn't realize they were reachable.. sounds good

File: packages/cosmic-swingset/src/export-kernel-db.js (hunk 3 above)
Comment (warner) [reply packages/cosmic-swingset/src/export-kernel-db.js:198]: this is to let the `log()` get delivered to the parent process? or at least to let it escape the current (child) process? yeah, the full `waitUntilQuiescent()` seems safe.

**Review by warner — APPROVED** [review]
ok sounds good

File: packages/cosmic-swingset/src/export-kernel-db.js (hunk 3 above)
Comment (mhofman) [reply packages/cosmic-swingset/src/export-kernel-db.js:198]: This is to let the `startedKit.promise` reactions run, which include sending a "started" message over to IPC if using `spawnSwingStoreExport`, which is what happens during state-sync.

It's just a bit weird that the export logic has to be conscious of its consumer, but besides having an active "ack" to proceed, I don't see how to better handle this case.
