### PR TITLE
Fix fullOrder leak. Semi-fungibles via CopyBags

### LINKED ISSUE #4261: setMathHelpers leaks history-dependent full ordering of remotables
POTENTIAL SECURITY BUG

Currently, because the `setMathHelpers` and the `amountMath` built on it are static, we have a dilemma leading to an information leak. The algorithms in https://github.com/Agoric/agoric-sdk/blob/master/packages/store/src/keys/merge-set-operators.js benefit tremendously by being able to fully order a set of elements, not just rank[1] sort them. However, remotables a) can be elements of sets, and b) cannot be objectively ordered. As an expedient temporary measure, at 

https://github.com/Agoric/agoric-sdk/blob/5ac65ecdfeed42be99f9316172b2799f70e37562/packages/ERTP/src/mathHelpers/setMathHelpers.js#L21-27

we capture a history-dependent full order into a top level variable, which is therefore mutable static state than can be used as a communications channel. Although the comparator itself is not exposed, the order of the resulting arrays is visible, which is equivalent in power.

The proper solution to this is a breaking change where the setMathHelper, and an amountMath using it are multiply instantiated, and each ERTP issuer locally makes its own instance. Note that there is no distributed coordination needed in any case, as the setMathHelper `coerce` function will always first reorder based on its own full comparator.

This communications channel is not an immediate concern, since we're currently running on a public chain that is fully transparent (no confidentiality, can keep no secrets) anyway. All the info that's leaked is already public info, and so no one can rely on it being secret anyway.

  - [1] A full order is one in which x <= y and y <= x iff x == y. A rank order is one in which x and y can be different but still be in the same equivalence class as far as the order is concerned. IOW, x and y are tied for the same rank (e.g., tied for second place). `Array.prototype.sort` is a *stable sort*, where the whole concept of a stable sort is only meaningful for a rank order. For a full order, there's no observable difference between a stable sort and a non-stable sort. The objective `compareRank` function defines only a rank order that does not leak information. But such orderings are too weak to enable the algorithms in merge-set-operators.js .

### PR DESCRIPTION
**Pull request by erights**
Fixes #4261

Fixes that many copySet functions, and functions over keys of a copySet, were not checking that their elements were indeed keys, rather than other kinds of passables. To do this well involved both renamings for clarity (elements vs keys) and moving the exported functions to where they could close the loop and certify sets as correct, including that they contain only keys.

### CODE REVIEW

File: packages/store/src/keys/merge-set-operators.js [hunk 1]
```diff
@@ -1,84 +1,145 @@
...
+              return harden({ done: false, value });
+            }
+            const similarRun = elements.slice(i, j);
+            i = j;
+            const resorted = sortByRank(similarRun, fullCompare);
+            // Providing the same `fullCompare` should cause a memo hit
+            // within `assertNoDuplicates` enabling it to avoid a
+            // redundant resorting.
+            assertNoDuplicates(resorted, fullCompare);
+            optInnerIterator = resorted[Symbol.iterator]();
```
Comment (gibson042) [inline packages/store/src/keys/merge-set-operators.js:70]: We could use a comment here explaining and allowing the unharded nature of values returned from `optInnerIterator`.

File: packages/store/src/keys/merge-set-operators.js [hunk 2]
```diff
@@ -1,84 +1,145 @@
...
+  const fullCompare = makeFullOrderComparatorKit().antiComparator;
+
+  const xs = windowResort(xelements, compareAntiRank, fullCompare);
+  const ys = windowResort(yelements, compareAntiRank, fullCompare);
   return harden({
     [Symbol.iterator]: () => {
       const xi = xs[Symbol.iterator]();
-      /** @type {Opt<T>} */
-      let x; // PUMPKIN when done
+      /** @type {T} */
```
Comment (gibson042) [inline packages/store/src/keys/merge-set-operators.js:105]: It would be nice to see an explanatory comment that we always have the next x/xDone and y/yDone, essentially buffering ahead one item.

File: packages/store/src/keys/merge-set-operators.js [hunk 3]
```diff
@@ -1,84 +1,145 @@
...
+            return optInnerIterator.next();
+          } else {
+            return harden({ done: true, value: null });
+          }
+        },
+      }),
+  });
+};
 
 /**
```
Comment (gibson042) [inline packages/store/src/keys/merge-set-operators.js:80]:
```suggestion
/**
 * Returns an iterable whose iteration results are [key, xCount, yCount] tuples.
```

File: packages/store/src/keys/merge-set-operators.js [hunk 4]
```diff
@@ -90,148 +151,125 @@ const merge = (xs, ys, fullCompare) => {
...
-    if (x !== PUMPKIN) {
-      result.push(x);
+  for (const [m, xc, yc] of xyi) {
+    assert(xc === 0n || yc === 0n, X`Sets must not have common elements: ${m}`);
+    if (xc >= 1n) {
+      result.push(m);
     } else {
-      assert(y !== PUMPKIN);
-      result.push(y);
+      assert(yc >= 1n);
```
Comment (gibson042) [inline packages/store/src/keys/merge-set-operators.js]:
```suggestion
      assert(yc >= 1n, X`Internal: …`);
```

**Review by gibson042 — APPROVED** [review]
