### PR TITLE
fix: fix bug which breaks rights conservation and offer safety guarantees

### LINKED ISSUE #3848: bug(Zoe): rights conservation and offer safety can be violated due to zcfMint interaction with staged allocations
## Describe the bug

The following code produces the error `'Reallocate failed because a seat had no staged allocation. Please add or subtract from the seat and then reallocate.'`

```js
/** @type {OfferHandler} */
const buyNFTs = (buyerSeat) => {
  sellerSeat.incrementBy(buyerSeat.decrementBy({ Money: pricePerNFT }));
  mint.mintGains({ NFTs: nftAmount }, buyerSeat);
  zcf.reallocate(buyerSeat, sellerSeat);
  buyerSeat.exit();
};
```

Here's what is happening:

1. `buyerSeat.decrementBy` creates a staged allocation for `buyerSeat`. 
2. `mintGains` under the hood does an `reallocateInternal` which allows for a reallocation just one seat, in this case, the `buyerSeat`. The intention based on a previous version of staging is that the reallocation is restricted to the assets minted in this line, and not anything else staged.  That intention is violated with this version of staging.
3. `zcf.reallocate` tries to look for `stagedAllocations` for the `buyerSeat` and the `sellerSeat`, but because the `buyerSeat` had a previous reallocation, there is no longer an active stagedAllocation for the `buyerSeat`. 

This presents an opportunity to bypass the rights conservation check, but not the offer safety check. [Edit: @erights points out that offer safety is of course violated for the other users whose assets are no longer in Zoe as a result of the rights conservation violation. It is only the offer safety in this particular transaction that is not violated. This could harm other users of the contract or users of other contracts.]

Here's an example that bypasses the rights conservation check:

```js
  /** @type {OfferHandler} */
  const buyNFTs = (buyerSeat) => {

    // Take more money than exists
    sellerSeat.incrementBy(buyerSeat.decrementBy({ Money: AmountMath.make(moneyBrand, 20n)}));

    mint.mintGains({ NFTs: emptyAmount }, buyerSeat);
    mint.mintGains({ NFTs: emptyAmount }, sellerSeat);

    buyerSeat.exit();
  };
```

In this particular case, it produces an error because the purse doesn't actually have enough to fulfill this, but we would not expect an early error to happen in production, where the same purses are being used to hold assets for multiple contracts. So in production it would be very likely that this would result in an attacker being able to extract assets from other contracts. 

Offer safety for this particular transaction is still enforced because `mintGains` and `burnLosses` each check offer safety for the seat themselves.

## To Reproduce
1. Write an offer handler that creates a staged allocation for a seat before mintGains reallocates for that seat under the hood.

## Expected behavior
MintGains probably shouldn't be doing any reallocate, and especially should not reallocate for staged allocations not involved in the minting request.

## Platform Environment
 - what version of the Agoric-SDK are you using? 
 1f3aa69

### PR DESCRIPTION
**Pull request by katelynsills**
This PR rewrites `zcfMint.mintGains` and `zcfMint.burnLosses` so that neither use staged allocations and neither use the typical `reallocate` path. Instead, the code is simplified such that the updated allocations are calculated, then a special reallocate only for zcfMint methods (`reallocateForZCFMint`) is called. `reallocateInternal` is deleted and its contents moved into `reallocate` proper.

Closes #3848

### CODE REVIEW

File: packages/zoe/src/contractFacet/zcfSeat.js [hunk 1]
```diff
@@ -113,50 +113,25 @@ export const createSeatManager = (
...
-      // Commit the staged allocations (currentAllocation is replaced
-      // for each of the seats) and inform Zoe of the
+      // Commit the newAllocation and inform Zoe of the
       // newAllocation.
 
-      seats.forEach(commitStagedAllocation);
+      activeZCFSeats.set(zcfSeat, newAllocation);
 
-      const seatHandleAllocations = seats.map(seat => {
+      const seatHandleAllocations = [zcfSeat].map(seat => {
```
Comment (erights) [inline packages/zoe/src/contractFacet/zcfSeat.js]: Since we're specializing anyway, the special case should avoid the complexity costs that came from generalizing.

```suggestion
      const seatHandleAllocations = [
        {
          seatHandle: zcfSeatToSeatHandle.get(zcfSeat),
          allocation: newAllocation,
        },
      ];
```

File: packages/zoe/src/contractFacet/zcfZygote.js [hunk 2]
```diff
@@ -152,31 +153,64 @@ export const makeZCFZygote = (
...
+        const allocationPlusGains = addToAllocation(
+          zcfSeat.getCurrentAllocation(),
+          gains,
+        );
+
+        // Increment the stagedAllocation if it exists so that the
+        // stagedAllocation is kept up to the currentAllocation
+        if (zcfSeat.hasStagedAllocation()) {
+          zcfSeat.incrementBy(gains);
+        }
```
Comment (erights) [inline packages/zoe/src/contractFacet/zcfZygote.js:169]: I see why this is necessary, but OMG what a mess. No change suggested.

File: packages/zoe/src/contractFacet/zcfZygote.js [hunk 3]
```diff
@@ -152,31 +153,64 @@ export const makeZCFZygote = (
...
         // verifies offer safety
-        assert(zcfSeat.isOfferSafe(zcfSeat.getStagedAllocation()));
-        // No effects above. The following two steps
-        // *should* be committed atomically, but it is not a
-        // disaster if they are not. If we minted only, no one would
-        // ever get those invisibly-minted assets.
+        assert(
+          zcfSeat.isOfferSafe(allocationPlusGains),
+          `The allocation after minting gains ${allocationPlusGains} for the zcfSeat was not offer safe`,
+        );
```
Comment (erights) [inline packages/zoe/src/contractFacet/zcfZygote.js]: Same question applies both before and after this PR: Aside from a bug in zoe we don't know about, is there any way for this to fail? Since the previous allocation was offer safe, adding gains to it should not be able to make it not be offer safe, yes?

If so, I am not suggesting removing the test. But perhaps rewording it to indicate an internal error in Zoe, rather than a mistake in the contract.

File: packages/zoe/src/contractFacet/zcfZygote.js [hunk 4]
```diff
@@ -152,31 +153,64 @@ export const makeZCFZygote = (
...
+        const allocationMinusLosses = subtractFromAllocation(
+          zcfSeat.getCurrentAllocation(),
+          losses,
+        );
+
+        // Decrement the stagedAllocation if it exists so that the
+        // stagedAllocation is kept up to the currentAllocation
+        if (zcfSeat.hasStagedAllocation()) {
+          zcfSeat.decrementBy(losses);
+        }
```
Comment (erights) [inline packages/zoe/src/contractFacet/zcfZygote.js:204]: This can fail! It is ok, it fails safe. But a failure here would be surprising, and would often be hard to understand. The contract was only burning seat allocations that it had. It is only a prior staging, which perhaps would not have been used anyway, that has been rendered invalid. One could argue that it is better for the burn to succeed, since it is locally correct, and for the staging to fail to be committed on a later reallocate. On balance I think that's worse, so I am not suggesting it. But it is interesting.

**Review by erights — APPROVED** [review]
LGTM!

File: packages/zoe/src/contractFacet/zcfSeat.js (hunk 1 above)
Comment (katelynsills) [reply packages/zoe/src/contractFacet/zcfSeat.js]: I like that

File: packages/zoe/src/contractFacet/zcfZygote.js (hunk 2 above)
Comment (katelynsills) [reply packages/zoe/src/contractFacet/zcfZygote.js:169]: Hah, my thoughts as well.

File: packages/zoe/src/contractFacet/zcfZygote.js (hunk 3 above)
Comment (katelynsills) [reply packages/zoe/src/contractFacet/zcfZygote.js]: There's no way for this to fail apart from a bug in Zoe, but I wanted to leave it in so it's easy to say that reallocations pass through an offer safety check. I'll add a comment about the unfeasibility of this failing unless something very wrong happens.

File: packages/zoe/src/contractFacet/zcfZygote.js (hunk 4 above)
Comment (katelynsills) [reply packages/zoe/src/contractFacet/zcfZygote.js:204]: Yeah, I agree that would be worse. If the burn succeeded but the staging later failed, it would be even more mysterious to the contract developer.

File: packages/zoe/src/contractFacet/zcfZygote.js (hunk 3 above)
Comment (katelynsills) [reply packages/zoe/src/contractFacet/zcfZygote.js]: Comment added
