### PR TITLE
fix(vat-bank): allow numeric or string nonces

### LINKED ISSUE #10928: `vat-bank.js` Exo `nonce` guards cause failures
## Describe the bug
When a `VBANK_BALANCE_UPDATE` is sent from `agd` to cause a vpurse balance update, it fails instead with a logged error.

## To Reproduce
1. Start an Agoric chain with at least SwingSet debug logs `DEBUG=SwingSet:vat`
2. Monitor log output
3. See error (I've attached details which are visible if you expand the triangle below)

<details><summary>v14: Error updating balance ...</summary>

```
2025-01-27T17:00:32.948Z SwingSet: vat: v14: Error updating balance { address: 'agoric13fymc0q63lwkpe3wjd4tmjm5vrp9zhvt8gkhly', amount: '1000500', denom: 'ibc/65D0BEC6DAD96C7F5043D1E54E54B6BB5D5B3AEC3FF6CEBB75B9E059F3580EA3' } (Error#58)
2025-01-27T17:00:32.948Z SwingSet: vat: v14: Error#58: In "update" method of (BalanceUpdater): arg 1?: number (a number) - Must be a string
2025-01-27T17:00:32.949Z SwingSet: vat: v14: Error: In "update" method of (BalanceUpdater): arg 1?: number (a number) - Must be a string
 at apply ()
 at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:60)
 at makeError (/bundled-source/.../node_modules/ses/src/error/assert.js:352)
 at throwLabeled (/bundled-source/.../node_modules/@endo/common/throw-labeled.js:26)
 at applyLabelingError (/bundled-source/.../node_modules/@endo/common/apply-labeling-error.js:43)
 at mustMatch (/bundled-source/.../node_modules/@endo/patterns/src/patterns/patternMatchers.js:591)
 at defendSyncArgs (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:82)
 at In "update" method of (BalanceUpdater) (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:170)
 at fromBridge (.../vats/src/vat-bank.js:208)
 at fromBridge (.../vats/src/vat-bank.js:190)
 at apply ()
 at In "fromBridge" method of (BankChannelHandler) (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:171)
 at apply ()
 at localApplyMethod (/bundled-source/.../node_modules/@endo/eventual-send/src/local.js:126)
 at apply ()
 at dispatchToHandler (/bundled-source/.../node_modules/@endo/eventual-send/src/handled-promise.js:159)
 at win (/bundled-source/.../node_modules/@endo/eventual-send/src/handled-promise.js:511)
 at ()

2025-01-27T17:00:32.949Z SwingSet: vat: v14: Error#58 ERROR_NOTE: Caused by (Error#59)
2025-01-27T17:00:32.949Z SwingSet: vat: v14: Error#59: arg 1?: number (a number) - Must be a string
2025-01-27T17:00:32.949Z SwingSet: vat: v14: Error: arg 1?: number (a number) - Must be a string
 at apply ()
 at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:60)
 at makeError (/bundled-source/.../node_modules/ses/src/error/assert.js:352)
 at throwLabeled (/bundled-source/.../node_modules/@endo/common/throw-labeled.js:26)
 at applyLabelingError (/bundled-source/.../node_modules/@endo/common/apply-labeling-error.js:43)
 at every ()
 at checkMatches (/bundled-source/.../node_modules/@endo/patterns/src/patterns/patternMatchers.js:1367)
 at applyLabelingError (/bundled-source/.../node_modules/@endo/common/apply-labeling-error.js:41)
 at mustMatch (/bundled-source/.../node_modules/@endo/patterns/src/patterns/patternMatchers.js:591)
 at defendSyncArgs (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:82)
 at In "update" method of (BalanceUpdater) (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:170)
 at fromBridge (.../vats/src/vat-bank.js:208)
 at fromBridge (.../vats/src/vat-bank.js:190)
 at apply ()
 at In "fromBridge" method of (BankChannelHandler) (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:171)
 at apply ()
 at localApplyMethod (/bundled-source/.../node_modules/@endo/eventual-send/src/local.js:126)
 at apply ()
 at dispatchToHandler (/bundled-source/.../node_modules/@endo/eventual-send/src/handled-promise.js:159)
 at win (/bundled-source/.../node_modules/@endo/eventual-send/src/handled-promise.js:511)
 at ()

2025-01-27T17:00:32.950Z SwingSet: vat: v14: Error#59 ERROR_NOTE: Caused by (Error#60)
2025-01-27T17:00:32.950Z SwingSet: vat: v14: Error#60: number 20 - Must be a string
2025-01-27T17:00:32.950Z SwingSet: vat: v14: Error: number (a number) - Must be a string
 at apply ()
 at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:60)
 at makeError (/bundled-source/.../node_modules/ses/src/error/assert.js:352)
 at fail (/bundled-source/.../node_modules/ses/src/error/assert.js:482)
 at baseAssert (/bundled-source/.../node_modules/ses/src/error/assert.js:504)
 at assertChecker (/bundled-source/.../node_modules/@endo/pass-style/src/passStyle-helpers.js:77)
 at checkKind (/bundled-source/.../node_modules/@endo/patterns/src/patterns/patternMatchers.js:287)
 at checkMatches (/bundled-source/.../node_modules/@endo/patterns/src/patterns/patternMatchers.js:959)
 at applyLabelingError (/bundled-source/.../node_modules/@endo/common/apply-labeling-error.js:41)
 at every ()
 at checkMatches (/bundled-source/.../node_modules/@endo/patterns/src/patterns/patternMatchers.js:1367)
 at applyLabelingError (/bundled-source/.../node_modules/@endo/common/apply-labeling-error.js:41)
 at mustMatch (/bundled-source/.../node_modules/@endo/patterns/src/patterns/patternMatchers.js:591)
 at defendSyncArgs (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:82)
 at In "update" method of (BalanceUpdater) (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:170)
 at fromBridge (.../vats/src/vat-bank.js:208)
 at fromBridge (.../vats/src/vat-bank.js:190)
 at apply ()
 at In "fromBridge" method of (BankChannelHandler) (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:171)
 at apply ()
 at localApplyMethod (/bundled-source/.../node_modules/@endo/eventual-send/src/local.js:126)
 at apply ()
 at dispatchToHandler (/bundled-source/.../node_modules/@endo/eventual-send/src/handled-promise.js:159)
 at win (/bundled-source/.../node_modules/@endo/eventual-send/src/handled-promise.js:511)
 at ()
```

</details>

## Expected behavior
No error.

## Platform Environment
 - what OS are you using? GitHub CI (ubuntu-latest CI worker)
 - what version of Node.js? v18 / CI version
 - is there anything special/unusual about your platform? CI
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`) agoric-upgrade-16av-1785-g3d64bee5b5

## Additional context
I traced the error to the `BalanceUpdaterI` interface guard in `vat-bank`.  The change in #8544 made the former `undefined` nonce (which had successfully passed the guard in the past) become a Golang int64 encoded as a JS `number` (which the guard was unprepared to accept).  Both values were correctly handled by the `updater.update` method, but the guard failed to accommodate `nonce: number` values.

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #10928 
refs: #8544

## Description

The change in #8544 unintentionally disabled `vat-bank`'s vpurse balance notification feature.

### Security Considerations

Since the `vat-bank.js` on mainnet has not been upgraded to the code in #8544, the #10928 issue only pertains to new or upgraded instances of `vat-bank.js`, such as in CI, local chains, and testnet chains.  There is absolutely no impact if this PR is landed before the next `vat-bank.js` upgrade to #8544 code.

### Scaling Considerations

None.

### Documentation Considerations

None.

### Testing Considerations

A unit test would be beneficial, but is not yet implemented.

### Upgrade Considerations

As above, production chains should not upgrade their `vat-bank.js` to the code in current master until this PR lands.

### CODE REVIEW

**Review by dckc — APPROVED** [review]

File: packages/vats/src/vat-bank.js [hunk 1]
```diff
@@ -42,12 +42,12 @@ const BridgeChannelI = M.interface('BridgeChannel', {
...
 /**
  * @typedef {Guarded<{
- *   update: (value: string, nonce?: string) => void;
+ *   update: (value: string, nonce?: string | number) => void;
  * }>} BalanceUpdater
  */
 
 const BalanceUpdaterI = M.interface('BalanceUpdater', {
-  update: M.call(M.string()).optional(M.string()).returns(),
+  update: M.call(M.string()).optional(M.or(M.number(), M.string())).returns(),
```
Comment (turadg) [inline packages/vats/src/vat-bank.js]: The issue this closes says,
> the guard failed to accommodate nonce: string values.

It did handle string, which as you explain is how a Golang `uint64` gets JSON-encoded.
```go
type VbankBalanceUpdate struct {
	*vm.ActionHeader `actionType:"VBANK_BALANCE_UPDATE"`
	Nonce            uint64                  `json:"nonce"`
	Updated          vbankManyBalanceUpdates `json:"updated"`
}
```

What produces `number` values?

If that is indeed valid then we need to update `VbankBalanceUpdateAction` too:
https://github.com/Agoric/agoric-sdk/blob/master/packages/cosmic-swingset/src/types.d.ts#L38-L44

**Review by turadg — CHANGES_REQUESTED** [review]
Please do include a regression test.

File: packages/vats/src/vat-bank.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/vats/src/vat-bank.js]: I haven't been able to trace it back to a source, but I suspect it's coming from the wallet. The test code isn't directly injecting the value. In `a3p-integration` tests, I definitely see that the nonce comes in as a number.

**Review by Chris-Hibbert — APPROVED** [review]
This looks right to me.

File: packages/vats/src/vat-bank.js (hunk 1 above)
Comment (michaelfig) [reply packages/vats/src/vat-bank.js]: The source is agd's `json.Marshal`, vis-a-vis https://github.com/Agoric/agoric-sdk/issues/10928#issuecomment-2629628340

**Comment by michaelfig** [comment]
> Please do include a regression test.

Done, PTAL.

File: packages/internal/src/typeGuards.js [hunk 2]
```diff
@@ -11,3 +11,14 @@ export const UnguardedHelperI = M.interface(
...
 );
+
+/**
+ * @typedef {number | `${number}`} BridgeBigInt Ensure that callees passed a
+ *   bridge message that was serialised from a Golang int64 or uint64 don't care
+ *   whether a value is a digit string or a plain number.
+ */
+
+/**
+ * Corresponding to the `BridgeBigInt` type.
```
Comment (turadg) [inline packages/internal/src/typeGuards.js]:
```suggestion
 * @type {TypedPattern<BridgeBigInt>}
```

**Review by turadg — APPROVED** [review]
Assuming you'll adopt the jsdoc change.

File: packages/internal/src/typeGuards.js (hunk 2 above)
Comment (michaelfig) [reply packages/internal/src/typeGuards.js]: Done!
