### PR TITLE
Close transcript span synchronously

### LINKED ISSUE #11642: kernel panic with transcript archive and vat termination
## Describe the bug
When archiving closed transcripts (`vat-transcript-archive-dir`), a vat termination causes a kernel panic. 

```
SwingSet: kernel: kernel terminating vat v111 (failure=true)
SwingSet: kernel: error during syscall translation: (TypeError#4)
TypeError#4: This database connection is busy executing a query

  at Object.set (packages/swing-store/src/kvStore.js:140:14)
  at Object.set (packages/swing-store/src/swingStore.js:356:15)
  at setReachableFlag (.../swingset-vat/src/kernel/state/vatKeeper.js:309:13)
  at mapKernelSlotToVatSlot (.../swingset-vat/src/kernel/state/vatKeeper.js:502:9)
  at Object.deleteCListEntriesForKernelSlots (.../swingset-vat/src/kernel/state/vatKeeper.js:568:23)
  at translateResolve (.../swingset-vat/src/kernel/vatTranslator.js:568:15)
  at Object.vatSyscallToKernelSyscall (.../swingset-vat/src/kernel/vatTranslator.js:596:16)
  at vatSyscallHandler (.../swingset-vat/src/kernel/kernel.js:1609:27)
  at syscallHandler (.../swingset-vat/src/kernel/vat-warehouse.js:42:18)
  at Object.syscallFromWorker (.../swingset-vat/src/kernel/vat-loader/manager-helper.js:164:17)
  at handleUpstream (.../swingset-vat/src/kernel/vat-loader/manager-subprocess-xsnap.js:107:21)
  at handleCommand (.../swingset-vat/src/kernel/vat-loader/manager-subprocess-xsnap.js:41:20)
  at runToIdle (packages/xsnap/src/xsnap.js:348:37)

SwingSet: xsnap: v2: UnhandledPromiseRejectionWarning: (Error#4)
SwingSet: xsnap: v2: Error#4: syscall.resolve failed: syscall translation error: prepare to die
```

## To Reproduce
1. Setup a new node using `agoric-upgrade-21`
2. Use cosmos state [agoric-20562999-pre-u21.tar.gz](https://storage.googleapis.com/agoric-snapshots-public/mainnet-cosmos-snapshots/agoric-20562999-pre-u21.tar.gz)
3. Configure `vat-transcript-archive-dir` in `config/app.toml`

## Expected behavior
Successfully executed block

## Additional context
Failure happens during the terminate syscall.

## Slogs
```
{"type":"deliver","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"replay":false,"dispatch":"message","kd":["message","ko4295551",{"methargs":{"body":"#[\"terminateWithFailure\",[{\"#error\":\"governed contract [\\\"board052184\\\",\\\"stkATOM-USD_price_feed\\\"] terminated by terminate-governed-instance\",\"errorId\":\"error:liveSlots:v9#77487\",\"name\":\"Error\"}]]","slots":[]},"result":"kp114774832"}],"vd":["message","o+d13/106",{"methargs":{"body":"#[\"terminateWithFailure\",[{\"#error\":\"governed contract [\\\"board052184\\\",\\\"stkATOM-USD_price_feed\\\"] terminated by terminate-governed-instance\",\"errorId\":\"error:liveSlots:v9#77487\",\"name\":\"Error\"}]]","slots":[]},"result":"p-1379"}],"time":1753176272.381982,"monotime":72.68224924600001}
{"type":"syscall","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"syscallNum":0,"replay":false,"syscall":"vatstoreGet","ksc":["vatstoreGet","v2","vom.o+d13/106"],"vsc":["vatstoreGet","vom.o+d13/106"],"time":1753176272.382672,"monotime":72.68294009499999}
{"type":"syscall-result","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"syscallNum":0,"replay":false,"syscall":"vatstoreGet","ksr":["ok","{\"vatID\":{\"body\":\"#\\\"v111\\\"\",\"slots\":[]}}"],"vsr":["ok","{\"vatID\":{\"body\":\"#\\\"v111\\\"\",\"slots\":[]}}"],"time":1753176272.382726,"monotime":72.68299312,"seconds":0.000035735999990720305}
{"type":"console","source":"liveslots","state":"delivery","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"level":"warn","args":["Logging sent error stack","(RemoteError(error:liveSlots:v9#77487)#3)"],"time":1753176272.383503,"monotime":72.683771134}
{"type":"console","source":"liveslots","state":"delivery","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"level":"warn","args":["RemoteError(error:liveSlots:v9#77487)#3:","governed contract [\"board052184\",\"stkATOM-USD_price_feed\"] terminated by terminate-governed-instance"],"time":1753176272.383792,"monotime":72.684059986}
{"type":"console","source":"liveslots","state":"delivery","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"level":"warn","args":["Error: governed contract [\"board052184\",\"stkATOM-USD_price_feed\"] terminated by terminate-governed-instance\n at construct ()\n at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:56)\n at makeError (/bundled-source/.../node_modules/ses/src/error/assert.js:243)\n at decodeErrorCommon (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:281)\n at decodeFromSmallcaps (/bundled-source/.../node_modules/@endo/marshal/src/encodeToSmallcaps.js:434)\n at map ()\n at map ()\n at fromCapData (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:356)\n at deliver (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1084)\n at dispatchToUserspace (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1509)\n at runWithoutMetering (/bundled-source/.../packages/swingset-xsnap-supervisor/lib/supervisor-subprocess-xsnap.js:60)\n at ()\n"],"time":1753176272.384009,"monotime":72.68427729300001}
{"type":"console","source":"liveslots","state":"delivery","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"level":"warn","args":["RemoteError(error:liveSlots:v9#77487)#3 ERROR_NOTE:","Sent as","error:liveSlots:v2#70003"],"time":1753176272.384175,"monotime":72.68444315}
{"type":"syscall","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"syscallNum":1,"replay":false,"syscall":"callNow","ksc":["invoke","kd33","terminateWithFailure",{"body":"#[\"v111\",{\"#error\":\"governed contract [\\\"board052184\\\",\\\"stkATOM-USD_price_feed\\\"] terminated by terminate-governed-instance\",\"errorId\":\"error:liveSlots:v2#70003\",\"name\":\"Error\"}]","slots":[]}],"vsc":["callNow","d-70","terminateWithFailure",{"body":"#[\"v111\",{\"#error\":\"governed contract [\\\"board052184\\\",\\\"stkATOM-USD_price_feed\\\"] terminated by terminate-governed-instance\",\"errorId\":\"error:liveSlots:v2#70003\",\"name\":\"Error\"}]","slots":[]}],"time":1753176272.38441,"monotime":72.684677746}
{"type":"console","source":"kernel","level":"log","args":["kernel terminating vat v111 (failure=true)"],"time":1753176272.385728,"monotime":72.685995933}
{"type":"syscall-result","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"syscallNum":1,"replay":false,"syscall":"callNow","ksr":["ok",{"body":"#\"#undefined\"","slots":[]}],"vsr":["ok",{"body":"#\"#undefined\"","slots":[]}],"time":1753176272.388727,"monotime":72.68899406,"seconds":0.004297876999989967}
{"type":"console","source":"kernel","level":"log","args":["error during syscall translation:",{"errorType":"TypeError","message":"This database connection is busy executing a query"}],"time":1753176272.39199,"monotime":72.69225774099999}
{"type":"syscall","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"syscallNum":2,"replay":false,"syscall":"resolve","vsc":["resolve",[["p-1379",false,{"body":"#\"#undefined\"","slots":[]}]]],"time":1753176272.392103,"monotime":72.692371064}
{"type":"syscall-result","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"syscallNum":2,"replay":false,"syscall":"resolve","ksr":["error","syscall translation error: prepare to die"],"vsr":["error","syscall translation error: prepare to die"],"time":1753176272.392123,"monotime":72.692390492,"seconds":0.000007763000001432373}
{"type":"console","source":"xsnap","state":"delivery","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"level":"error","args":["UnhandledPromiseRejectionWarning:","(Error#4)"],"time":1753176272.393065,"monotime":72.69333248500001}
{"type":"console","source":"xsnap","state":"delivery","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"level":"error","args":["Error#4:","syscall.resolve failed: syscall translation error: prepare to die"],"time":1753176272.393406,"monotime":72.69367443499999}
{"type":"console","source":"xsnap","state":"delivery","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"level":"error","args":["Error: syscall.resolve failed: syscall translation error: prepare to die\n at apply ()\n at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:54)\n at doSyscall (/bundled-source/.../packages/swingset-xsnap-supervisor/lib/supervisor-helper.js:86)\n at handle (/bundled-source/.../packages/swingset-liveslots/src/liveslots.js:1189)\n at ()\n"],"time":1753176272.393989,"monotime":72.6942576}
{"type":"deliver-result","crankNum":459025435,"vatID":"v2","deliveryNum":1342,"replay":false,"dispatch":"message","dr":["ok",null,{"meterType":"xs-meter-35","currentHeapCount":255046,"compute":31350,"allocate":42074144,"timestamps":[1753176272.382092,1753176272.382537,1753176272.382807,1753176272.383145,1753176272.38359,1753176272.383628,1753176272.38388,1753176272.383929,1753176272.384072,1753176272.384103,1753176272.384238,1753176272.384293,1753176272.389561,1753176272.389687,1753176272.392239,1753176272.392427,1753176272.393161,1753176272.3932,1753176272.393532,1753176272.39358,1753176272.394076,1753176272.394087]}],"time":1753176272.394226,"monotime":72.694493656,"seconds":0.01222685000000638}
{"type":"console","source":"kernel","level":"error","args":["error in kernel.deliver:",{"errorType":"TypeError","message":"This database connection is busy executing a query"}],"time":1753176272.395289,"monotime":72.695557226}
{"type":"console","source":"kernel","level":"error","args":["##### KERNEL PANIC: error during tryProcessMessage: TypeError: This database connection is busy executing a query #####"],"time":1753176272.395619,"monotime":72.69588689599999}
{"type":"console","source":"controller","level":"error","args":[{"errorType":"Error","message":"unfinished slog event cosmic-swingset-run-start {\"blockHeight\":20563000,\"phase\":\"forced\",\"remainingBeans\":\"[undefined]\",\"runNum\":5,\"startBeans\":\"[15167642400n]\"}","cause":{"errorType":"TypeError","message":"This database connection is busy executing a query"}}],"time":1753176272.397308,"monotime":72.69757600099999}
{"type":"console","source":"controller","level":"error","args":[{"errorType":"Error","message":"unfinished slog event cosmic-swingset-end-block-start {\"blockHeight\":20563000,\"blockTime\":1752506159}","cause":{"errorType":"TypeError","message":"This database connection is busy executing a query"}}],"time":1753176272.397873,"monotime":72.698141571}
```

### PR DESCRIPTION
**Pull request by mhofman**
closes: #11642

## Description
The vat termination triggered in u21 revealed a latent bug in the way transcript archiving integrates with span rollover.

This PR does the least intrusive change updating only the implementation of the transcript store to guarantee that all store operations are synchronous even for the methods that are async because of the archiver's integration.

### Security Considerations
We previously released Zalgo by assuming some async operation was mostly sync, and it worked fine because of the low number of ticks the callee took, except when the archiver was enabled. This is taming Zalgo a little bit. In a perfect world we would change the signature of these async transcript store APIs into sync functions returning a nested promise for the deferred part, making the sync part explicit, and legal to rely upon.

### Scaling Considerations
None

### Documentation Considerations
Comment added in JSDoc with sync guarantees

### Testing Considerations
Added test for the sync guarantees.

Reproduced the original issue in a manual test of the code before fix: with the addition of an `await new Promise(resolve => setImmediate(resolve));` between the call to the APIs triggering span close and the log check (simulating the numerous `await` in the callers), the test with archiver disabled passes, but fails with the archiver enabled.

### Upgrade Considerations
None, this is not consensus affecting (running this patch on my u21 archiving follower).

### CODE REVIEW

File: packages/cosmic-swingset/src/chain-main.js [hunk 1]
```diff
@@ -223,7 +223,7 @@ export const makeQueueStorage = (call, queuePath) => {
  * @param {typeof process.env} [options.env]
  * @param {Pick<import('fs'), 'createWriteStream' | 'mkdirSync' | 'renameSync'>} options.fs
  * @param {Pick<import('path'), 'join' | 'resolve'>} options.path
- * @param {import('tmp')} [options.tmp] required to support vatSnapshotArchiveDir/vatTranscriptArchiveDir
+ * @param {import('tmp')} options.tmp required to support vatSnapshotArchiveDir/vatTranscriptArchiveDir
```
Comment (gibson042) [inline packages/cosmic-swingset/src/chain-main.js:226]: I'd prefer this to remain optional; `makeLaunchChain` is at least in principle usable without it.

File: packages/cosmic-swingset/tools/test-kit.js [hunk 2]
```diff
@@ -253,6 +253,7 @@ export const makeCosmicSwingsetTestKit = async (
     env,
     fs,
     path: nativePath,
+    tmp,
```
Comment (gibson042) [inline packages/cosmic-swingset/tools/test-kit.js:256]: ...as demonstrated here.

File: packages/swing-store/src/archiver.js [hunk 3]
```diff
@@ -4,9 +4,13 @@ import { promisify } from 'node:util';
...
 import { withDeferredCleanup } from '@agoric/internal';
 
+/**
+ * @import {AnyIterable} from './exporter.js';
+ */
+
 const streamFinished = promisify(streamFinishedCallback);
 
-/*
+/**
```
Comment (gibson042) [inline packages/swing-store/src/archiver.js:13]: Whoops.

**Review by gibson042 — APPROVED** [review]
Approved, but please reconsider making `tmp` a required option for `makeLaunchChain`.

File: packages/cosmic-swingset/src/chain-main.js (hunk 1 above)
Comment (mhofman) [reply packages/cosmic-swingset/src/chain-main.js:226]: This was definitely the most expedient way of dealing with this. The problem is that `tmp` is only optional when not using transcript archival. I don't really want to change the param type definition to express this conditionality.
