### PR TITLE
fix(scripts): Update GitHub release template to document recursive `git clean`

### LINKED ISSUE #9633: Release template build instructions fail to `git clean` submodules
## Describe the bug
This was a contributing factor to #9614 (because `build` directories containing `xsnap-worker` executables were left in place), and has already been fixed in the [agoric-upgrade-16-rc0 release](https://github.com/Agoric/agoric-sdk/releases/tag/agoric-upgrade-16-rc0).

### PR DESCRIPTION
**Pull request by gibson042**
closes: #9633
refs: #9614

## Description
Adds `git submodule foreach --recursive git clean -xdf` to build instructions in the release template.

### Security Considerations
None.

### Scaling Considerations
n/a

### Documentation Considerations
This PR updates documentation intended for node operators.

### Testing Considerations
n/a

### Upgrade Considerations
n/a

### CODE REVIEW

File: scripts/gen-github-release.sh [hunk 1]
```diff
@@ -156,7 +156,7 @@ Install supported versions of Go, Node.js, and a compiler such as gcc or clang a
 cd agoric-sdk
 git fetch --all
 git checkout $TAG
-git clean -xdf
+git clean -xdf && git submodule foreach --recursive git clean -xdf
 yarn install
```
Comment (mhofman) [inline scripts/gen-github-release.sh]: We need to switch to `.bin/agd build` as well.

And there are other changes I had to make in the release notes, some regarding the upgrade handler name, and some due to state-sync changes.

**Review by mhofman — APPROVED** [review]
@gibson042 please review my changes and merge as you see fit.
