### PR TITLE
fix(swingset): xs-worker confused meter exhaustion with process fail

### LINKED ISSUE #3394: manager-subprocess-xsnap should distinguish metering faults from random process death
If a vat worker subprocess exits unexpectedly, our kernel does not know the state of the vat: the worker might have died because of something the vat did, or because of something outside swingset (maybe the host computer is being rebooted and all processes are being killed, in some random order). #2958 is about having a policy to react to an unexpected worker termination.

If we're in "consensus mode", we must crash the kernel: we do not know why the worker terminated, so we don't know that it's also being terminated on all other validators. In particular, metering faults are a distinct "known" form of worker termination. We need to be able to distinguish between a metering fault and some other random error.

`manager-subprocess-xsnap.js` has a `catch` inside `deliverToWorker` that conflates these cases:

```js
    async function deliverToWorker(delivery) {
      parentLog(vatID, `sending delivery`, delivery);
      let result;
      try {
        result = await issueTagged(['deliver', delivery]);
      } catch (err) {
        parentLog('issueTagged error:', err.code, err.message);
        let message;
        switch (err.code) {
          case ExitCode.E_TOO_MUCH_COMPUTATION:
            message = 'Compute meter exceeded';
            break;
          case ExitCode.E_STACK_OVERFLOW:
            message = 'Stack meter exceeded';
            break;
          case ExitCode.E_NOT_ENOUGH_MEMORY:
            message = 'Allocate meter exceeded';
            break;
          default:
            message = err.message;
        }
        return harden(['error', message, null]);
      }
```

I'm thinking that the non-meter-fault errors should propogate an Error upwards (i.e. don't `catch` the default case). We can use a non-rejecting `deliverToWorker` return promise with a value of `['error'..]` to mean "consensus metering fault", and a yes-rejecting return promise (which should then carry all the way back to `controller.run()`) to mean "unknown worker error, halting the kernel".

I think we can get away without fixing this for the stress-test phase this week, but the danger is that something which happens to kill a worker process might trick that one validator into thinking the vat has had a consensus metering fault, and once that validator commits the results, it won't be able to rejoin consensus. (I think. @michaelfig has investigated this more than me).

### PR DESCRIPTION
**Pull request by dckc**
fixes #3394

separate commits are not worth keeping after review; let's squash.

### CODE REVIEW

File: packages/SwingSet/test/test-xsnap-errors.js [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+
+  theProc.kill();
+
+  t.throwsAsync(p, {
+    instanceOf: Error,
+    code: 'SIGTERM',
+    message: 'v1:undefined exited due to signal SIGTERM',
+  });
+
+  await p.catch(() => {});
```
Comment (warner) [inline packages/SwingSet/test/test-xsnap-errors.js:94]: Huh, was this necessary to prevent some other unhandled rejection warning? I would have expected `t.throwsAsync` to do a `catch` or two-argument `then`.

**Review by warner — APPROVED** [review]
looks good

File: packages/SwingSet/test/test-xsnap-errors.js (hunk 1 above)
Comment (dckc) [reply packages/SwingSet/test/test-xsnap-errors.js:94]: yes, it's necessary:
  - without any `await` on `p`, ava complains that the test completed with assertions outstanding
  - `await p;` alone causes the test function to return a rejected promise, which ava counts as a failure

File: packages/SwingSet/src/kernel/vatManager/manager-helper.js [hunk 2]
```diff
@@ -139,16 +139,19 @@ function makeManagerKit(
   /**
    *
    * @param { VatDeliveryObject } delivery
-   * @returns { Promise<VatDeliveryResult> }
+   * @returns { Promise<VatDeliveryResult> } // or Error
```
Comment (mhofman) [inline packages/SwingSet/src/kernel/vatManager/manager-helper.js:142]: What does `or Error` mean? It can't throw or return any synchronous value since it's an `async function`?

File: packages/SwingSet/test/test-xsnap-errors.js (hunk 1 above)
Comment (mhofman) [reply packages/SwingSet/test/test-xsnap-errors.js:94]: I thought the way to do this was to `await t.throwsAsync(...)` ?

File: packages/SwingSet/test/test-xsnap-errors.js [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+import path from 'path';
+import { spawn } from 'child_process';
+import bundleSource from '@agoric/bundle-source';
+
+import { makeXsSubprocessFactory } from '../src/kernel/vatManager/manager-subprocess-xsnap.js';
+import { makeStartXSnap } from '../src/controller.js';
+import { capargs } from './util.js';
+
+function suppressUnhandled(t, message) {
+  process.on('unhandledRejection', (reason, promise) => {
```
Comment (mhofman) [inline packages/SwingSet/test/test-xsnap-errors.js:14]: I'm not super familiar with ava but my experience with other test frameworks is that this is leaky.

The test should as much as possible manually cleanup these global event handlers after the test has run so that events in future tests don't interact weirdly.

Comment (dckc) [reply packages/SwingSet/test/test-xsnap-errors.js:14]: I stipulate that it should, but in ava, each test script runs its own node process, so I don't think this is a correctness issue.

File: packages/SwingSet/src/kernel/vatManager/manager-helper.js (hunk 2 above)
Comment (dckc) [reply packages/SwingSet/src/kernel/vatManager/manager-helper.js:142]: I'm not sure; @warner added it... I squinted at it a little bit but then moved on.

File: packages/SwingSet/test/test-xsnap-errors.js (hunk 1 above)
Comment (dckc) [reply packages/SwingSet/test/test-xsnap-errors.js:94]: ah. yes, that works, @mhofman .
