### PR TITLE
fix(solo): properly expose `/wallet/bridge.html`

### LINKED ISSUE #8620: Solo wallet is broken in current NPM packages
## Describe the bug

#8533 solved this problem.

`ag-solo`'s builtin web server was incorrectly configured.  Dapps were trying to reach `http://localhost:8000/wallet/bridge.html` but no bridge connection would result.

## To Reproduce
1. `git clone https://github.com/Agoric/dapp-card-store -b mfig-hack-getting-started`
2. Follow the README.md
3. Note that the card store UI spins forever

## Expected behavior
Using the dapp would connect to the Solo and make progress in its UI.

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context
It looks like the Solo's wallet bridge connection is stuck.  Loading the `http//localhost:8000/wallet/bridge.html` page directly (as the network tab reveals the dapp is trying to do) doesn't show the "no user-servicable parts" bridge page, it shows the Solo wallet management UI.  It looks like the web server is configured for a Single Page App, when in reality it's a Dual Page App.

## Screenshots
I'm writing this from memory.

### PR DESCRIPTION
**Pull request by michaelfig**
## Description

Don't send `/wallet/index.html` when `/wallet/bridge.html` was requested.

Makes solo wallet compatible with `@agoric/web-components` again.

### Security Considerations

n/a

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

Tested manually with fungible faucet

### Upgrade Considerations

n/a

### CODE REVIEW

File: packages/solo/src/web.js [hunk 1]
```diff
@@ -148,21 +149,28 @@ export async function makeHTTPListener(
...
-      console.log('redirecting wallet bridge');
       app.get('/wallet-bridge.html', (req, res) =>
-        res.redirect('/wallet/bridge.html'),
+        res.redirect(
+          url.format({ pathname: '/wallet/bridge.html', query: req.query }),
+        ),
+      );
+    } else {
+      app.get('/wallet/bridge.html', (_, res) =>
+        res.sendFile(path.resolve(soloHtmlDir, 'wallet-bridge.html')),
```
Comment (mhofman) [inline packages/solo/src/web.js:167]: Why not redirect to `wallet-bridge.html` ?

**Review by mhofman — APPROVED** [review]

File: packages/solo/src/web.js (hunk 1 above)
Comment (michaelfig) [reply packages/solo/src/web.js:167]: No redirect because I want `/wallet/bridge.html` to be canonical.
