### PR TITLE
test: lint Ava tests

### LINKED ISSUE #4941: Lint for Ava tests
## What is the Problem Being Solved?

Things like `test.only` should fail CI (example https://github.com/Agoric/agoric-sdk/pull/4868#discussion_r836802722  )

## Description of the Design

Adopt https://github.com/avajs/eslint-plugin-ava

## Security Considerations
n/a

## Test Plan
n/a

### PR DESCRIPTION
**Pull request by turadg**
closes: #4941

## Description

Motivation in #4941.

- Adds https://github.com/avajs/eslint-plugin-ava
- Disabled [`use-test`](https://github.com/avajs/eslint-plugin-ava/blob/v13.2.0/docs/rules/use-test.md) due to https://github.com/avajs/eslint-plugin-ava/pull/294#issuecomment-1084648317 
- Selectively disabled [`no-lone-blocks`](https://eslint.org/docs/rules/no-lone-blocks) that started erroring, I suppose because a dep that was updated caught more cases. Alternately we could disable the rule.
- A test that imported from another test required refactoring

### Security Considerations

--
### Documentation Considerations

--

### Testing Considerations

--

### CODE REVIEW

**Comment by turadg** [comment]
Wrinkle with `https://github.com/eslint/eslint/issues/3458` because this makes packages that import `@agoric` eslint config now have to also import `eslint-plugin-ava`.

If we're going to have [an eslint config]((https://www.npmjs.com/package/@agoric/eslint-config)) that gets imported by packages outside this repo then I suppose it should be minimal and very general. Then more specific ones that can be opted into. For example, sdk and dapp. The ava linting would only be on the 'sdk' one. 

So I'll change this PR to
- define that "sdk" config
- use it in all the SDK packages
- make that config lint Ava

File: packages/cosmic-swingset/test/test-provision-smartwallet.js [hunk 1]
```diff
@@ -59,13 +59,7 @@ test.before(async t => {
   t.context = { scenario2, walletTool, pspawnAgd, bootstrapAddr, soloAddr };
 });
 
-// SKIP: struggling with timing issues resulting in one of...
-// Error: cannot grab 250000uist coins: 0uist is smaller than 250000uist: insufficient funds
-// error: code = NotFound desc = account agoric1mhu... not found
-// Sometimes I can get this test to work alone, but not
-// if run with the test above.
-// TODO: https://github.com/Agoric/agoric-sdk/issues/6766
```
Comment (Chris-Hibbert) [inline packages/cosmic-swingset/test/test-provision-smartwallet.js]: Should this PR 
```
closes: #6766
```
?

File: packages/solo/src/start.js [hunk 2]
```diff
@@ -1,4 +1,5 @@
 // @ts-check
+/* eslint-disable no-lone-blocks */
```
Comment (Chris-Hibbert) [inline packages/solo/src/start.js]: Is this required because of the switch/case? If so, I think the rule is being too aggressive. I wouldn't want to have to add this caveat every time I use swtch/case. Doesn't our style recommend using braces with switch/case?  (It should, IMHO.)

File: packages/swing-store/test/exports.js [hunk 3]
```diff
@@ -0,0 +1,99 @@
+import { Buffer } from 'buffer';
+import { makeB0ID } from './util.js';
```
Comment (Chris-Hibbert) [inline packages/swing-store/test/exports.js:2]: remark: Good extraction!

**Review by Chris-Hibbert — APPROVED** [review]
with caveats, as discussed.

File: packages/solo/src/start.js (hunk 2 above)
Comment (turadg) [reply packages/solo/src/start.js]: Remnant of an earlier revision. I'll remove

File: packages/cosmic-swingset/test/test-provision-smartwallet.js (hunk 1 above)
Comment (turadg) [reply packages/cosmic-swingset/test/test-provision-smartwallet.js]: sadly, no. It's still failing https://github.com/Agoric/agoric-sdk/actions/runs/5867547993/job/15908602617?pr=4981

I'll revert this change

**Comment by FUDCo** [comment]
I think `no-lone-blocks` is a dumb rule that serves no useful purpose that I can discern.  We should disable it universally.

**Review by FUDCo — APPROVED** [review]
This all looks quite reasonable to me.

**Comment by Chris-Hibbert** [comment]
> I think no-lone-blocks is a dumb rule that serves no useful purpose that I can discern. We should disable it universally.

I don't know why it's a good rule to enforce, but I've found that my tastes don't seem to prevail unless I can show why a proposed rule would get in the way. I asked enough questions to convince myself that it doesn't prevent anything that I'm aware of doing.   @FUDCo is there something that you occasionally do that this would grouse about?

**Comment by FUDCo** [comment]
I think the example you already cited of switch cases is compelling by itself, but also: sometimes lone blocks are useful for expository purposes to highlight functionally distinct parts of a function, much as blank lines are used.  Also, I've occasionally found them useful to control what gets captured by a closure -- sometimes optimizations inside the JS engine can result in more stuff getting captured by a closure than you want or than is lexically apparent from reading the code; arguably this latter case is more about working around JS engine issues, but real nonetheless.
