### PR TITLE
fix!: rights conservation should allow new brands or dropped brands if sum is empty

### LINKED ISSUE #3033: Zoe: reallocating empty amounts for seats that had no prior allocation for the brand
The following test fails:

```js
test(`zcfSeat.stage, zcf.reallocate with only empty amounts`, async t => {
  const { zcf } = await setupZCFTest();
  const { zcfSeat: zcfSeat1 } = zcf.makeEmptySeatKit();
  const { zcfSeat: zcfSeat2 } = zcf.makeEmptySeatKit();
  const zcfMint = await zcf.makeZCFMint('RUN');
  const { brand } = zcfMint.getIssuerRecord();

  // Get the amount allocated on zcfSeat1. It is empty for the RUN brand.
  const allocation = zcfSeat1.getAmountAllocated('RUN', brand);
  t.true(amountMath.isEmpty(allocation));

  // Stage zcfSeat2 with the allocation from zcfSeat1
  const zcfSeat2Staging = zcfSeat2.stage({ RUN: allocation });

  // Stage zcfSeat1 with empty
  const zcfSeat1Staging = zcfSeat1.stage({ RUN: amountMath.makeEmpty(brand) });

  zcf.reallocate(zcfSeat1Staging, zcfSeat2Staging);

  t.deepEqual(zcfSeat1.getCurrentAllocation(), {
    RUN: amountMath.make(0n, brand),
  });
  t.deepEqual(zcfSeat2.getCurrentAllocation(), {
    RUN: amountMath.make(0n, brand),
  });
});
```

It fails because reallocate checks that the number of brands before a reallocation and after a proposed reallocation are the same. This is meant to be a quick defense against a reallocation that allocates more tokens than existed previously, but it forgets about the possibility of empty amounts. We should allow for reallocations of empty amounts, even if the seats had no previous allocation for the brand.

### PR DESCRIPTION
**Pull request by katelynsills**
Closes #3033 

The rights conservation code previously checked that the brands before and after a proposed allocation were exactly the same. This assumption is wrong, because from a rights allocation perspective, it is ok to include a new brand or drop a brand, as long as the sum is empty. 

From the code comments:

```
  // We cannot assume that all of the brand keys present in
  // leftSumsByBrand are also present in rightSumsByBrand. A empty
  // amount could be introduced or dropped, and this should still be
  // deemed "equal" from the perspective of rights conservation.

  // Thus, we should allow for a brand to be missing from a map, but
  // only if the sum for the brand in the other map is empty.
```

### CODE REVIEW

File: packages/zoe/src/contractFacet/rightsConservation.js [hunk 1]
```diff
@@ -37,24 +37,43 @@ const sumByBrand = amounts => {
...
+   */
+  const getOrEmpty = (sumsByBrandMap, brand, amount) => {
+    if (!sumsByBrandMap.has(brand)) {
+      return amountMath.makeEmptyFromAmount(amount);
+    }
+    return sumsByBrandMap.get(brand);
+  };
+
+  const assertSumsEqualInMap = (mapToIterate, mapToCheck) => {
+    mapToIterate.keys().forEach(brand => {
```
Comment (erights) [inline packages/zoe/src/contractFacet/rightsConservation.js]: If you union the brands, you can do each comparison only once.
```suggestion
    const allBrands = new Set([...mapToIterate.keys(), ...mapToCheck.keys()]);
    allBrands.forEach(brand => {
```

Comment (katelynsills) [reply packages/zoe/src/contractFacet/rightsConservation.js]: Oo, nice!

Comment (katelynsills) [reply packages/zoe/src/contractFacet/rightsConservation.js]: huh, looking at this method in isolation though, we don't know if the brand is defined in the left or the right. And to make empty, we need an amount from the other map. The code gets messy because it doesn't have a place to stand. Let me see if I can improve this.

Comment (katelynsills) [reply packages/zoe/src/contractFacet/rightsConservation.js]: Ok, pushed up a version that uses allBrands, but is a little more verbose

File: packages/zoe/src/contractFacet/rightsConservation.js [hunk 2]
```diff
@@ -46,34 +46,43 @@ const assertEqualPerBrand = (leftSumsByBrand, rightSumsByBrand) => {
   // only if the sum for the brand in the other map is empty.
```
Comment (erights) [inline packages/zoe/src/contractFacet/rightsConservation.js:46]: Deleting like 37 above makes the comment clearer.

**Review by erights — APPROVED** [review]
LGTM

File: packages/zoe/src/contractFacet/rightsConservation.js (hunk 2 above)
Comment (katelynsills) [reply packages/zoe/src/contractFacet/rightsConservation.js:46]: @erights, sorry, I don't understand this comment

Comment (erights) [reply packages/zoe/src/contractFacet/rightsConservation.js:46]:
```js
/**
 * Assert that the left sums by brand equal the right sums by brand
 *
 * @param  {Store<Brand, Amount>} leftSumsByBrand - a map of brands to sums
 * @param  {Store<Brand, Amount>} rightSumsByBrand - a map of brands to sums
 * indexed by issuer
 */
```
Line 37 says "indexed by issuer", only as an extension of "a map of brands to sums" for `rightSumsByBrand`, not `leftSumsByBrand`. What does it mean?

Comment (katelynsills) [reply packages/zoe/src/contractFacet/rightsConservation.js:46]: oh, I see, you want to delete that line. That makes sense. I think its inclusion is a mistake from past implementations.

Comment (erights) [reply packages/zoe/src/contractFacet/rightsConservation.js:46]: yes
