### PR TITLE
Execute vat creation and root object initialization in a crank

### LINKED ISSUE #2910: tolerate vatstore syscalls during vat startup
## Describe the bug

I realized the other day that, with the introduction of virtual objects, vats might attempt to create some during their startup phase: at the top-level module context, or inside `buildRootObject()` but outside of any remote message handler (methods of that root object). This will cause `vatstoreSet()` syscalls to happen much earlier than before. Our vat managers aren't currently prepared to honor syscalls this early.

We need to fix that, since we want to encourage Issuers to use virtual objects, and it's entirely reasonable for contracts to create some sort of singleton infrastructural Purse during startup.

The state changes that result from these syscalls (the kerneldb vatstore writes) should be lumped into the same atomic transaction as the clist creation and scheduling of the resolution of the vatAdmin vat-creation promise (the one that introduces the caller to the new vat's root object).

### PR DESCRIPTION
**Pull request by FUDCo**
Run vat creation and initialization in a crank, so module initialization and `buildRootObject` have access to syscalls and have their actions logged in the vat transcript.

Closes #2910

### CODE REVIEW

File: packages/SwingSet/test/test-liveslots.js [hunk 1]
```diff
@@ -952,9 +952,13 @@ test('dropImports', async t => {
...
     gcTools,
+    undefined,
+    () => {
+      return { buildRootObject: build };
+    },
   );
-  const { setBuildRootObject, dispatch, possiblyDeadSet } = ls;
-  setBuildRootObject(build);
+  const { dispatch, startVat, possiblyDeadSet } = ls;
+  await startVat();
```
Comment (warner) [inline packages/SwingSet/test/test-liveslots.js:961]: Let's use this pattern to add one small test that asserts `makeLiveSlots()` does not call the provided `buildVatNamespace` until someone invokes `startVat`. Something like:

```js

test('buildVatNamespace not called until after startVat', async t => {
  const { syscall } = buildSyscall();
  const imports = [];
  const gcTools = makeMockGC();
  let buildCalled = false;

  function buildRootObject(_vatPowers) {
    buildCalled = true;
    return Far('root', {});
  }

  const ls = makeLiveSlots(
    syscall,
    'vatA',
    {},
    {},
    undefined,
    false,
    false,
    gcTools,
    () => ({ buildRootObject }),
  );
  assert.falsy(buildCalled);
  await ls.startVat();
  assert(buildCalled);
});
```

File: packages/SwingSet/src/kernel/vatManager/supervisor-subprocess-xsnap.js [hunk 2]
```diff
@@ -282,6 +282,28 @@ function makeWorker(port) {
...
+      TextDecoder,
+      Base64: globalThis.Base64, // Present only in XSnap
+    };
+
+    async function buildVatNamespace(
+      lsEndowments,
+      inescapableGlobalProperties,
+    ) {
+      const vatNS = await importBundle(bundle, {
+        endowments: { ...workerEndowments, ...lsEndowments },
```
Comment (warner) [inline packages/SwingSet/src/kernel/vatManager/supervisor-subprocess-xsnap.js:300]: this swaps the priority order (`lsEndowments` can override `workerEndowments`) vs the original, but I think I like it better this way, it gives liveslots slightly more control, and a hypothetical #4376 liveslots update pathway would be able to replace HandledPromise or `assert` or something

File: packages/SwingSet/src/kernel/vatManager/manager-local.js [hunk 3]
```diff
@@ -129,43 +151,26 @@ export function makeLocalVatManagerFactory(tools) {
...
-
-    let dispatch;
-    if (typeof vatNS.buildRootObject === 'function') {
-      const { buildRootObject } = vatNS;
-      ls.setBuildRootObject(buildRootObject);
-      dispatch = ls.dispatch;
-    } else if (enableSetup) {
+    if (enableSetup) {
+      const vatNS = await buildVatNamespace(
+        ls.vatGlobals,
```
Comment (warner) [inline packages/SwingSet/src/kernel/vatManager/manager-local.js]: Interesting.. if we decided that `setup`-based vats did not need these globals (and didn't need the `inescapableGlobalProperties` forced upon them), could we simplify liveslots to stop including them in the return value? That might be a nice (small) cleanup.

Previously, we didn't know ahead of time whether the bundle would provide `export default setup` or `export function buildRootObject`. But now (if I understand correctly), `enableSetup` means we're always using `setup` and vice versa. So in the `enableSetup` case, we don't need to be prepared to support `buildRootObject` -style vats.

`setup` is only used by comms and unit tests (and maybe vattp someday), so I guess the real question is whether comms needs any of the `vatGlobals`. (It doesn't really use WeakMaps or WeakSets, just one for a debug hook).

File: packages/SwingSet/src/kernel/vatManager/manager-local.js [hunk 4]
```diff
@@ -129,43 +151,26 @@ export function makeLocalVatManagerFactory(tools) {
...
       assert.typeof(setup, 'function');
       const helpers = harden({}); // DEPRECATED, todo remove from setup()
       const state = null; // TODO remove from setup()
-      dispatch = setup(syscall, state, helpers, vatPowers, vatParameters);
+      const dispatch = setup(syscall, state, helpers, vatPowers, vatParameters);
+      return finish(dispatch);
     } else {
-      assert.fail(X`vat source bundle lacks buildRootObject() function`);
+      assert(ls.dispatch);
+      const result = finish(ls.dispatch);
```
Comment (warner) [inline packages/SwingSet/src/kernel/vatManager/manager-local.js]: this could be collapsed, `return finish(dispatch)` after the close of the `else` branch

File: packages/SwingSet/src/kernel/kernel.js [hunk 5]
```diff
@@ -336,31 +336,32 @@ export default function buildKernel(
...
-      }
       // else... static... maybe panic???
 
       // ISSUE: terminate stuff in its own crank like creation?
       // eslint-disable-next-line no-use-before-define
       vatWarehouse.vatWasTerminated(vatID);
     }
+    if (vatAdminRootKref) {
+      // static vat termination can happen before vat admin vat exists
+      notifyTermination(
```
Comment (warner) [inline packages/SwingSet/src/kernel/kernel.js:254]: The `// else... static... maybe panic` comment above still seems relevant. This new version will call `notifyTermination` for static vats, whereas the previous version would not notify anybody. We need to be more deliberate if a static vat dies.. that probably represents something pretty serious, and I think a kernel panic may be appropriate. #4279 could overlap.

Let's update that `else... static...` comment to restore the context that was previously provided by the `if (isDynamic)` clause. Maybe "TODO: if a static vat terminates, panic the kernel?".

File: packages/SwingSet/src/kernel/kernel.js [hunk 6]
```diff
@@ -684,12 +686,40 @@ export default function buildKernel(
     return harden(policyInput);
   }
 
+  async function processStartVat(message) {
```
Comment (warner) [inline packages/SwingSet/src/kernel/kernel.js:610]: let's add a comment on this function to help orient us later, "The start-vat event is queued by `initializeKernel` for all static vats, so we can run their bundle import and buildRootObject in a transcript context. For dynamic vats, this happens during the create-vat event instead (which delegates part of the work to processStartVat)."

It might almost be worthwhile to factor this out more obviously. `processStartVat` to be invoked by a `start-vat` event, `processCreateVat` to be invoked by a `create-vat`, and both of them call a common `deliverStartVat` function. Of course then `processStartVat` is a one-liner.

File: packages/SwingSet/src/kernel/kernel.js [hunk 7]
```diff
@@ -684,12 +686,40 @@ export default function buildKernel(
...
+    postAbortActions.discardFailedDelivery = true;
+    const { type, vatID } = message;
+    // console.log(`-- processStartVat(${vatID})`);
+    insistVatID(vatID);
+    // eslint-disable-next-line no-use-before-define
+    if (!vatWarehouse.lookup(vatID)) {
+      // Note a bit of weirdness here: if a vat's module initialization or
+      // buildRootObject function throws an error, the crank in which it was
+      // executed will be aborted, which will leave the 'startVat' delivery on
```
Comment (warner) [inline packages/SwingSet/src/kernel/kernel.js]: Wait, is that comment still true? I thought `discardFailedDelivery = true` means that the `start-vat`will be discarded. Should the `vatWarehouse` check be converted into an `assert(vatWarehouse.lookup(vatID))` instead?

File: packages/SwingSet/src/kernel/kernel.js [hunk 8]
```diff
@@ -684,12 +686,40 @@ export default function buildKernel(
...
+      // the run queue (since the removal of the request from the run queue will
+      // have been rolled back by the abort).  This means it will be delivered
+      // *again* on the next crank; that, however, will lead us here: the vat
+      // won't exist (because it was terminated) and the nugatory redundant
+      // 'startVat' will safely render as a no-op and go away.
+      /** @type { PolicyInput } */
+      const policyInput = harden(['create-vat', {}]);
+      return harden(policyInput);
+    }
+    const kd = harden([type]); // TODO(4381) add vatParameters here
```
Comment (warner) [inline packages/SwingSet/src/kernel/kernel.js:617]: let's not have this depend on `type`, it makes it look like `processStartVat` is intended to handle a variety of types, whereas really it must only ever be `startVat`.

```js
const kd = harden(['startVat']); // TODO(4381) add vatParameters here
```

File: packages/SwingSet/src/kernel/kernel.js [hunk 9]
```diff
@@ -733,14 +764,22 @@ export default function buildKernel(
...
-      .then(sendResponse)
-      .catch(err => console.error(`error in vat creation`, err))
-      .then(() => policyInput);
+    return (
+      // eslint-disable-next-line no-use-before-define
+      vatWarehouse
+        .createDynamicVat(vatID)
+        // if createDynamicVat fails, go directly to makeErrorResponse
+        .then(_ =>
+          enableSetup ? null : processStartVat({ type: 'startVat', vatID }),
```
Comment (warner) [inline packages/SwingSet/src/kernel/kernel.js:684]: You know, it might make sense to send `dispatch.startVat` to `setup` based vats too, it would tell them when it's safe to make syscalls. I don't know how many unit tests would have to change, though, to add a no-op `startVat()` to their setup-based `dispatch` functions.

If we did that, this would become unconditional, and we wouldn't need to extract `enableSetup` first.

File: packages/SwingSet/src/kernel/kernel.js [hunk 10]
```diff
@@ -797,7 +842,10 @@ export default function buildKernel(
         kernelKeeper.decrementRefCount(message.kpid, `deq|notify`);
         policyInput = await processNotify(message);
       } else if (message.type === 'create-vat') {
+        // creating a new dynamic vat will immediately do start-vat
         policyInput = await processCreateVat(message);
+      } else if (message.type === 'startVat') {
```
Comment (warner) [inline packages/SwingSet/src/kernel/kernel.js:768]: I've got a slight preference for kebab-case in these run-queue events (`start-vat` not `startVat`), but it's not worth putting any significant time into changing. The delivery to the vat needs to be camel case, though, because it maps closely to a method name.

File: packages/SwingSet/src/kernel/liveSlots.js [hunk 11]
```diff
@@ -1103,9 +1100,22 @@ function build(
     assert(key.match(/^[-\w.+/]+$/), X`invalid vatstore key`);
   }
 
-  function setBuildRootObject(buildRootObject) {
-    assert(!didRoot);
-    didRoot = true;
+  async function startVat() {
+    assert(!didStartVat);
+    didStartVat = true;
+    // consume the first (unmetered) turn to ensure vat module code runs with metering
```
Comment (warner) [inline packages/SwingSet/src/kernel/liveSlots.js]: add to the comment "unlike dispatch.deliver or dispatch.notify, we don't need to unserialize any data here, so there's no opportunity for GC-based meter divergence. But when #4381 adds `vatParameters` to this event, perform that unserialization during the unmetered turn.

File: packages/SwingSet/src/kernel/liveSlots.js [hunk 12]
```diff
@@ -1103,9 +1100,22 @@ function build(
     assert(key.match(/^[-\w.+/]+$/), X`invalid vatstore key`);
   }
 
-  function setBuildRootObject(buildRootObject) {
-    assert(!didRoot);
-    didRoot = true;
+  async function startVat() {
```
Comment (warner) [inline packages/SwingSet/src/kernel/liveSlots.js:1101]: Let's rearrange this to build `vpow` at the beginning, while we're still in the unmetered turn, so all of our preparations are ready before we call `buildVatNamespace`. I'd like to have a comment that clearly marks the point at which user-provided code might cause us to crash or overrun a meter, and do as much as possible before that point.

File: packages/SwingSet/src/kernel/liveSlots.js [hunk 13]
```diff
@@ -1220,9 +1231,14 @@ function build(
...
         break;
       }
+      case 'startVat': {
+        result = startVat();
+        break;
+      }
       default:
         assert.fail(X`unknown delivery type ${type}`);
     }
+    return result;
```
Comment (warner) [inline packages/SwingSet/src/kernel/liveSlots.js:1252]: We need to update the type comment for `dispatchToUserspace`, I think this new case makes it `{ void | Promise<void> }`. We don't have `// @ts-check` turned on here yet, else I bet it would have complained.

File: packages/SwingSet/src/kernel/liveSlots.js [hunk 14]
```diff
@@ -1371,20 +1390,12 @@ export function makeLiveSlots(
...
   );
-  const {
-    vatGlobals,
-    inescapableGlobalProperties,
-    dispatch,
-    setBuildRootObject,
-    possiblyDeadSet,
-    testHooks,
-  } = r; // omit 'm'
+  const { dispatch, startVat, possiblyDeadSet, testHooks } = r; // omit 'm'
```
Comment (warner) [inline packages/SwingSet/src/kernel/liveSlots.js:1406]: oh, hey, we aren't returning `vatGlobals` or `inescapableGlobalProperties` anyways, so we should definitely make that change in `manager-local.js`, they'll always be empty

File: packages/SwingSet/src/kernel/kernel.js (hunk 9 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js:684]: We should document the conclusions we came to about the error handling of `processStartVat`. Something like:

If the new vat fails during module import or `buildRootObject`, the `startVat` delivery will signal a failure, and `deliverAndLogToVat` will `setTerminationTrigger`, which will unwind the crank after we return. `processStartVat` returns a PolicyInput rather than throwing, which means we'll call `makeSuccessResponse` (queueing a message to vatAdmin that the new vat was successfully created), but that message will be discarded when the crank is unwound.

File: packages/SwingSet/src/kernel/vatAdmin/vatAdminWrapper.js [hunk 15]
```diff
@@ -154,6 +154,9 @@ export function buildRootObject(vatPowers) {
 
   // the kernel sends this when the vat halts
   function vatTerminated(vatID, shouldReject, info) {
+    if (pending.has(vatID)) {
+      newVatCallback(vatID, { error: info });
```
Comment (warner) [inline packages/SwingSet/src/kernel/vatAdmin/vatAdminWrapper.js:166]: let's add a comment:

This happens when a dynamic vat survives `vatWarehouse.createDynamicVat()` but fails during the delivery of `startVat`. In that case, a successful `newVatCallback` was unwound by the failed delivery, but then it queues a `vatTerminated` for us. If this arrives before we see `newVatCallback`, that means the vat failed, and we should simulate the errorful `newVatCallback` so the caller will be notified about their misfortune.

File: packages/SwingSet/src/kernel/vatManager/manager-subprocess-xsnap.js [hunk 16]
```diff
@@ -75,7 +74,7 @@ export function makeXsSubprocessFactory({
       vatSyscallHandler,
       true,
       compareSyscalls,
-      useTranscript,
+      true,
```
Comment (warner) [inline packages/SwingSet/src/kernel/vatManager/manager-subprocess-xsnap.js]: Could we do an `assert(managerOptions.useTranscript)` instead of putting a literal `true` in this argument list? My concern is that from here it isn't obvious what the `true` is doing. I had to look up what the existing `true` is for (`workerCanBlock`). And if somebody thinks they can set `useTranscript: false`, I'd rather throw an error than silently do something surprising.

Maybe this just means `makeManagerKit` has too many parameters, and switching to a named-property bag of stuff would make the call site more legible. Probably a cleanup to do some other time.

File: packages/SwingSet/test/devices/test-devices.js [hunk 17]
```diff
@@ -64,7 +64,16 @@ test.serial('d0', async t => {
   const hostStorage = provideHostStorage();
   await initializeSwingset(config, [], hostStorage);
   const c = await makeSwingsetController(hostStorage, {});
+  for (let i = 0; i < 5; i += 1) {
```
Comment (warner) [inline packages/SwingSet/test/devices/test-devices.js]: wow these tests are fussy

I'm inclined to do `c.run()` in as many of them as possible, rather than carefully (and probably fragily) doling out a specific number of steps ahead of time. This test doesn't look like it does any additional steps, so I think it might work (and be cleaner) to `await c.run()` instead.

File: packages/SwingSet/test/devices/test-devices.js [hunk 18]
```diff
@@ -118,6 +127,10 @@ test.serial('d1', async t => {
   const hostStorage = provideHostStorage();
   await initializeSwingset(config, [], hostStorage, t.context.data);
   const c = await makeSwingsetController(hostStorage, deviceEndowments);
+  for (let i = 0; i < 5; i += 1) {
+    // eslint-disable-next-line no-await-in-loop
+    await c.step(); // vat start
+  }
```
Comment (warner) [inline packages/SwingSet/test/devices/test-devices.js]: this might also fall into the "`c.run()` first" category: do a `c.run` at startup, let all the startup-ish things finish, then do a single `c.step` after the `c.queueToVatRoot`

File: packages/SwingSet/test/devices/test-devices.js [hunk 19]
```diff
@@ -338,6 +354,12 @@ test.serial('liveslots throws when D() gets promise', async t => {
   const hostStorage = provideHostStorage();
   await initializeSwingset(config, ['promise1'], hostStorage, t.context.data);
   const c = await makeSwingsetController(hostStorage, {});
+  for (let i = 0; i < 4; i += 1) {
+    // eslint-disable-next-line no-await-in-loop
+    await c.step(); // vat start
+    // eslint-disable-next-line no-await-in-loop
+    await c.step(); // bring out your dead
+  }
```
Comment (warner) [inline packages/SwingSet/test/devices/test-devices.js:352]: ok this one really does need the careful pre-stepping

BTW feel free to hoist that `eslint-disable` to the top of this source file, that'd probably remove a lot of clutter

File: packages/SwingSet/test/run-policy/test-run-policy.js [hunk 20]
```diff
@@ -33,6 +33,10 @@ async function testCranks(t, mode) {
   const rightKref = c.pinVatRoot('right');
   const rightID = c.vatNameToID('right');
   t.teardown(c.shutdown);
+  for (let i = 0; i < 5; i += 1) {
+    // eslint-disable-next-line no-await-in-loop
+    await c.step(); // start vat
```
Comment (warner) [inline packages/SwingSet/test/run-policy/test-run-policy.js]: this can probably be a c.run

File: packages/SwingSet/test/test-controller.js [hunk 21]
```diff
@@ -113,6 +116,10 @@ test('bootstrap', async t => {
   // basedir-controller-2/bootstrap.js logs "bootstrap called" and queues a call to
   // left[0].bootstrap
   const c = await buildVatController(config);
+  for (let i = 0; i < 5; i += 1) {
+    // eslint-disable-next-line no-await-in-loop
+    await c.step(); // vat starts
```
Comment (warner) [inline packages/SwingSet/test/test-controller.js:121]: I bet this can be c.run

File: packages/SwingSet/test/test-controller.js [hunk 22]
```diff
@@ -123,6 +130,10 @@ test('XS bootstrap', async t => {
   config.defaultManagerType = 'xs-worker';
   const hostStorage = provideHostStorage();
   const c = await buildVatController(config, [], { hostStorage });
+  for (let i = 0; i < 5; i += 1) {
+    // eslint-disable-next-line no-await-in-loop
+    await c.step(); // vat starts
```
Comment (warner) [inline packages/SwingSet/test/test-controller.js:135]: this too

File: packages/SwingSet/test/test-controller.js [hunk 23]
```diff
@@ -156,6 +167,10 @@ test('static vats are unmetered on XS', async t => {
       },
     },
   );
+  for (let i = 0; i < 5; i += 1) {
+    // eslint-disable-next-line no-await-in-loop
+    await c.step(); // vat starts
```
Comment (warner) [inline packages/SwingSet/test/test-controller.js:172]: this too

File: packages/SwingSet/test/test-controller.js [hunk 24]
```diff
@@ -258,6 +279,10 @@ test.serial('bootstrap export', async t => {
   }
 
   t.deepEqual(c.dump().log, []);
+  for (let i = 0; i < 7; i += 1) {
+    // eslint-disable-next-line no-await-in-loop
+    await stepGC(); // vat starts
```
Comment (warner) [inline packages/SwingSet/test/test-controller.js:284]: but not this

huh, with only 6 non-`setup` vats, I'd expect the loop should need 6 iterations, not 7. And the deleted `stepGC` below (the `// dropExports`) one sort of correlates with that. But I'm guessing the test failed when you do 6 loops and retain the `// dropExports` one?

File: packages/SwingSet/test/test-promises.js [hunk 25]
```diff
@@ -19,6 +19,12 @@ test('flush', async t => {
   );
   const c = await buildVatController(config, ['flush'], t.context.data);
   // all promises should settle before c.step() fires
+  for (let i = 0; i < 6; i += 1) {
+    // eslint-disable-next-line no-await-in-loop
+    await c.step(); // vat start
```
Comment (warner) [inline packages/SwingSet/test/test-promises.js]: I bet this can be c.run

File: packages/SwingSet/test/test-vat-env.js [hunk 26]
```diff
@@ -69,6 +69,12 @@ async function testForExpectedGlobals(t, workerType) {
   const c = await buildVatController(config, [], {
     hostStorage,
   });
+  for (let i = 0; i < 4; i += 1) {
+    // eslint-disable-next-line no-await-in-loop
+    await c.step(); // vat start
```
Comment (warner) [inline packages/SwingSet/test/test-vat-env.js]: this too

**Review by warner — CHANGES_REQUESTED** [review]
nice work! pretty minor updates to make

File: packages/SwingSet/src/kernel/vatManager/manager-local.js (hunk 3 above)
Comment (FUDCo) [reply packages/SwingSet/src/kernel/vatManager/manager-local.js]: I do like the idea of having no entanglement whatsoever between setup vats and liveslots, and those two references to `ls` in the call to `buildVatNamespace` are the last vestige of that, but I'm not sure we're prepared to categorically declare that setup vats can't access stores or virtual objects.  On the other hand, the inner voodoo that makes stores and virtual objects actually work assumes a lot of the liveslots infrastructure, so now I'm thinking the "can't use virtuals from setup vats" ship has already sailed, and if a setup vat were to actually try to use any of the stuff that's currently passed into them as part of `vatGlobals` or `inescapableGlobalProperties` then Bad Things would happen.  So making this change would arguably be more than just a nice cleanup, but actually something necessary to protect correctness.

File: packages/SwingSet/src/kernel/vatManager/manager-local.js (hunk 4 above)
Comment (FUDCo) [reply packages/SwingSet/src/kernel/vatManager/manager-local.js]: Yeah, I thought about that.  I really wish the JS `const` declaration simply enforced single assignment semantics rather than requiring immediate initialization.  As it is, to do what you say we'd have to declare `dispatch` as a `let` variable outside the `if`, and I'm always nervous about that kind of thing, even though, in this case, it's probably not an issue since the value is going to immediately be returned.

File: packages/SwingSet/src/kernel/kernel.js (hunk 10 above)
Comment (FUDCo) [reply packages/SwingSet/src/kernel/kernel.js:768]: While I think I agree with your aesthetic instincts on this, we've already got a number of other run queue items that have already bought into camel case (I think, as you point out, to match the corresponding function name), so the only actual kebab-case one is `create-vat`.  If anything I would argue for changing _it_ just for the sake of consistency.  But I think for now this is one of those let sleeping dogs lie things.

File: packages/SwingSet/src/kernel/vatManager/manager-local.js (hunk 3 above)
Comment (FUDCo) [reply packages/SwingSet/src/kernel/vatManager/manager-local.js]: As an experiment I just tried changing the these endowments to empty objects here and ran the full test suite and everything worked fine, so I think I will make that change permanent, which will also let us move the `makeLiveSlots` call into the non-`enableSetup` branch and entirely remove liveslots from the setup vat universe.

File: packages/SwingSet/src/kernel/kernel.js (hunk 7 above)
Comment (FUDCo) [reply packages/SwingSet/src/kernel/kernel.js]: Yes, I think you're right.  I'll replace the comment with an assert of the contrary condition.

File: packages/SwingSet/src/kernel/kernel.js (hunk 8 above)
Comment (FUDCo) [reply packages/SwingSet/src/kernel/kernel.js:617]: I'm not sure I agree.  Doing it the way it's written (which a number of the other `processXXX` functions also do, BTW) insulates the code from having to be dependent on the name of the event it is processing; it just uses whatever name that happens to be.  So that if we were to, say, strictly hypothetically, change `'startVat'` to `'start-vat'`, this code would not have to be altered to match.

File: packages/SwingSet/src/kernel/kernel.js (hunk 9 above)
Comment (FUDCo) [reply packages/SwingSet/src/kernel/kernel.js:684]: I was actually handling `startVat` in setup vats in the prior, abandoned (`buildRootObject` only) PR.  A lot of them already had code to ignore `bringOutYourDead` deliveries so adding another case to ignore was no big deal.  However, I'm not sure what benefit would be provided, as there's really no useful "you can now use syscalls" signal, because `setup` is called outside the crank by definition.  In a setup vat, you can use syscalls from calls to `dispatch` and you can't use them during `setup` or during module initialization.

File: packages/SwingSet/src/kernel/vatManager/manager-subprocess-xsnap.js (hunk 16 above)
Comment (FUDCo) [reply packages/SwingSet/src/kernel/vatManager/manager-subprocess-xsnap.js]: OK.   All the non-local worker types now pass `useTranscript` but throw if it's not true.

File: packages/SwingSet/test/test-controller.js (hunk 21 above)
Comment (FUDCo) [reply packages/SwingSet/test/test-controller.js:121]: Nope.

File: packages/SwingSet/test/test-controller.js (hunk 22 above)
Comment (FUDCo) [reply packages/SwingSet/test/test-controller.js:135]: Not this one either.

File: packages/SwingSet/test/devices/test-devices.js (hunk 17 above)
Comment (FUDCo) [reply packages/SwingSet/test/devices/test-devices.js]: I went through all the tests and converted the ones that could succeed with `c.run()` to do so.  That was maybe half of them or a little more.  I'm not quite sure what the issues were in the places where it didn't work, but I don't think it's worth trying to figure that out just now.

File: packages/SwingSet/test/test-liveslots.js (hunk 1 above)
Comment (FUDCo) [reply packages/SwingSet/test/test-liveslots.js:961]: With minor tweaks to make it actually work, it works.

**Comment by FUDCo** [comment]
@warner ready for re-review.  I put all the changes in a separate commit for ease of reviewing.  I'll squash it out when landing, assuming everything is OK.

File: packages/SwingSet/test/test-controller.js (hunk 21 above)
Comment (warner) [reply packages/SwingSet/test/test-controller.js:121]: Huh, that test is really confused. I'll rewrite it after this lands. The 5 steps you've got here are enough to deliver `startVat` and `bringOutYourDead` to two other vats, and just `startVat` to a third (but not `bringOutYourDead`), leaving one vat half-finished, a second vat completely unfinished, and the bootstrap method doesn't even get delivered. Which is good, because the `bootstrap` vat it references emits `'bootstrap called'` when in fact only `buildRootObject` has been called, and it doesn't even define a `bootstrap()` method, so when `c.run()` gets all the way through, it crashes.

**Review by warner — APPROVED** [review]
changes look great, rebase+squash and land.

File: packages/SwingSet/test/test-controller.js (hunk 21 above)
Comment (warner) [reply packages/SwingSet/test/test-controller.js:121]: I added #4632 to fix this one.

File: packages/SwingSet/src/kernel/kernel.js (hunk 6 above)
Comment (warner) [reply packages/SwingSet/src/kernel/kernel.js:610]: #4636 to track this

File: packages/SwingSet/test/test-controller.js (hunk 24 above)
Comment (mhofman) [reply packages/SwingSet/test/test-controller.js:284]: I'm reopening this as I was just stung by this in my change to the run queue. Switching to `6` and restoring the second `stepGC` below fixed the issue (after a while of tracing the diff).
