### PR TITLE
[Zoe] throw if 0 or 1 offerHandles in reallocate

### LINKED ISSUE #1017: What should be happen when zfc.reallocate is called with 0 or 1 offerHandle?
During the hackathon, i've seen the following pattern:
```js
zcf.reallocate(
  [offerHandle],
  [zcf.getCurrentAllocation(offerHandle)],
);
```

Although it's not wrong to do that, it's a no-op (the assets allocated with an offerHandle are re-allocated... to the same offerHandle)
it feels like this snippet is a mistake made by the author

I think that calling `zfc.reallocate` with 0 or 1 offerHandle should probably be considered a mistake and result at least in a `console.warn` or maybe an error thrown

### PR DESCRIPTION
**Pull request by katelynsills**
Closes #1017

### CODE REVIEW

**Review by Chris-Hibbert — APPROVED** [review]

File: packages/zoe/src/zoe.js [hunk 1]
```diff
@@ -415,6 +415,10 @@ const makeZoe = (additionalEndowments = {}) => {
     const contractFacet = harden({
       reallocate: (offerHandles, newAllocations, sparseKeywords) => {
         assertOffersHaveInstanceHandle(offerHandles, instanceHandle);
+        assert(
```
Comment (erights) [inline packages/zoe/src/zoe.js:420]: Please insert a TODO comment pointing to our discussion about how this is a temporary kludge to be replaced by a static test.

**Review by erights — APPROVED** [review]
LGTM with the addition of the requested comment.

File: packages/zoe/src/zoe.js (hunk 1 above)
Comment (katelynsills) [reply packages/zoe/src/zoe.js:420]: Hmm, I'm happy to put a comment that we will revisit this to see if a static test might be sufficient, but I think I've shown that reallocating with zero or one offers is more like adding zero or one terms together (in other words, it's not merely a no-op, it does not make any conceptual sense, and there is no good reason to do it), than it is like adding the value 0. Saying that this is a temporary kludge seems to be ignoring this point.

Comment (erights) [reply packages/zoe/src/zoe.js:420]: I thought I had convinced you that this was a false analogy. Since I hadn't, it is still a live controversy what the right answer is. That much more reason to insert a link to the continuing discussion!

Comment (katelynsills) [reply packages/zoe/src/zoe.js:420]: Oh, no, I didn't see any reply to the analogy, only the question of why static testing isn't enough. Putting a link in to the discussion sounds like a very good idea!
