### PR TITLE
8722 provisionPool re-register notifiers

### LINKED ISSUE #8238: provisionPool Error: keyword ... must be an ascii identifier starting with upper case
## Describe the bug

_NOTE: This bug is only critical for assets where we're adding a PSM. Otherwise, the provisionPool can't use them anyway._

[Community testing with stATOM](https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/issues/16) showed that the provisionPool will fail to track its balance of any asset registered in the vbank with an issuerName that doesn't match the [Zoe keyword](https://docs.agoric.com/reference/zoe-api/zoe-data-types.html#keyword) constraints: ASCII identifier string that must begin with an upper case letter.

## To Reproduce
1. adapt the STARS proposal to stATOM
2. deploy bundles; make a governance proposal; vote
3. `Error: keyword "stATOM" must be an ascii identifier starting with upper case` shows in chain logs

The stack trace includes a call to `saveIssuer`.
https://github.com/Agoric/agoric-sdk/blob/mainnet1B/packages/vats/src/provisionPoolKit.js#L347

## Expected behavior

Assets known as `xyzABC` work fine for funding the provisionPool via a PSM.

## Platform Environment

`mainnet1B` code as well as a few other local chain configurations

## Additional context

[Community testing with stATOM](https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/issues/16) with @0xPatrickdev

## Logs / stacktrace

<details><summary>stack trace from a scenario2 local-chain log</summary>

```
2023-08-22T15:54:16.291Z SwingSet: xsnap: v29: Error: keyword "stATOM" must be an ascii identifier starting with upper case.
 at construct ()
 at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:56)
 at makeError (/bundled-source/.../node_modules/ses/src/error/assert.js:273)
 at fail (/bundled-source/.../node_modules/ses/src/error/assert.js:387)
 at assertKeywordName (.../zoe/src/cleanProposal.js:33)
 at assertUniqueKeyword (.../zoe/src/instanceRecordStorage.js:106)
 at apply ()
 at apply ()
 at In "assertUniqueKeyword" method of (InstanceRecord) (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:42)
 at saveIssuer (.../zoe/src/contractFacet/zcfZygote.js:261)
 at saveIssuer (.../zoe/src/contractFacet/zcfZygote.js:257)
 at updateState (.../vats/src/provisionPoolKit.js:344)
 at updateState (.../vats/src/provisionPoolKit.js:342)
 at (.../notifier/src/asyncIterableAdaptor.js:63)
 at ()
```
</details>

### LINKED ISSUE #8722: vat-provisionpool will not re-subscribe to vat-bank getCurrentAmountNotifier
As part of https://github.com/Agoric/agoric-sdk/pull/8499#issuecomment-1842457715 (look for `v14-bank-v28-provisionpool`), we identified a likely problem in the ProvisionPool vat. It has about a dozen promises that are subscribed to v14-bank, which will probably not re-subscribe when v14-bank is restarted/upgraded. As such, it represents an upgrade blocker: we must deploy a fix to v28-provisionpool before we can safely upgrade v14-bank.

v28-provisionpool uses `observeNotifier` [to subscribe to a notifier obtained with](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/vats/src/provisionPoolKit.js#L351) `E(exchangePurse).getCurrentAmountNotifier()`. The use of `observeNotifier` is great, it knows how to react to vat upgrades, however [the notifier it is pulling from](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/ERTP/src/purse.js#L81) (created by ERTP) [is not durable](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/ERTP/src/purse.js#L20). So `observeNotifier` will see an unrecoverable error, and will stop following.

We need the provisionpool code to react to this by calling `getCurrentAmountNotifier()` again (perhaps the `fail:` clause can inspect the `reason` and, if it is a new disconnection, try again).

## Upgrade Considerations

v28-provisionpool does not use durable followers, so if/when v28 is upgraded, all of the `observeNotifier` instances will go away. This presents a problem when upgrading v28. We need the provisionpool code to somehow re-acquire all the asset subscriptions at upgrade time. This needs to be present in the next deployment of v28, to avoid losing track of the amounts that it is supposed to be watching. This yields the following sequence of upgrade dependencies:

* fix provisionpool to re-establish its followers upon vat-provisionpool upgrade
* deploy this fix to v28
* fix provisionpool to re-establish followers upon vat-bank upgrade
* deploy this fix to v28
* now it is safe to upgrade/restart v14-bank

The first two v28 deployments can be merged.

### LINKED ISSUE #8724: test that restarting v28-provisionpool will re-subscribe to v14-bank asset subscriptions
As part of #8499 (look for `v14-bank-v28-provisionpool`, [the second section](https://github.com/Agoric/agoric-sdk/pull/8499#issuecomment-1842457715)), we investigate how v28-provisionpool will react when it is upgraded, specifically with respect to the promises that it follows from v14-bank. These promises appear on v28-provisionpool in [`start()`](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/vats/src/provisionPoolKit.js#L343) when it calls `E(poolBank).getAssetSubscription()`. This code uses `observeIteration` (which tolerates the *decider* getting upgraded/restarted), however it doesn't use a `DurablePromiseWatcher`, so our concern is what happens when the *subscriber* (v28-provisionpool) is upgraded/restarted.

This code is called from a `start` method, and [there is evidence](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/vats/src/provisionPool.js#L74-L85) that `start` will be called each time v28-provisionpool is restarted. If so, we're good. If not, the new version of the vat might not correctly follow new assets created after upgrade.

The task for this ticket is to test this case, ideally through a3p or some reproducible mechanism, and demonstrate that:
* 1: the new version of v28-provisionpool calls `getAssetSubscription()`
* 2: the upgraded provisionpool vat correctly reacts to new assets being announced by v14-bank

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
fixes: #8722
fixes: #8724
fixes: #8238

## Description

Upgrade provisionPool so its notifiers are robust to upgrades. 

### Security Considerations

This is about soundness of the chain and its services.

### Scaling Considerations

N/A

### Documentation Considerations

No change to functionality.

### Testing Considerations

Includes a test in `a3p-integration` that demonstrates that provisionPool will survive its own or vat-bank's upgrade.

### Upgrade Considerations

See above.

### CODE REVIEW

File: packages/inter-protocol/src/provisionPoolKit.js [hunk 1]
```diff
@@ -327,62 +341,96 @@ export const prepareProvisionPoolKit = (
...
+                    await zcf.saveIssuer(desc.issuer, desc.issuerName);
+
+                    // see https://github.com/Agoric/agoric-sdk/issues/8238
+                  } else if (desc.issuerName.match(FIRST_LOWER_ASCII)) {
+                    await saveIssuerWithLegalKeyword(desc, zcf);
+                  } else {
+                    console.error(
+                      `unable to save issuer with illegal keyword: ${desc.issuerName}`,
+                    );
+                  }
```
Comment (turadg) [inline packages/inter-protocol/src/provisionPoolKit.js]: both branch save with a legal keyword. This abstraction makes it look like this branch does something different. I think it would be more clear if you made a valid `desc` and then saved it consistently.

```suggestion
                  // let this handle the conditions and log about whether repair was necessary  
                  const goodDesc = repair(desc);
                  if (goodDesc) {
                    await zcf.saveIssuer(desc.issuer, desc.issuerName);
                  } else {
                    console.error(
                      `unable to save issuer with illegal keyword: ${desc.issuerName}`,
                    );
                  }
```

File: packages/vats/src/proposals/upgrade-provisionPool-proposal.js [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+
+  assert(provisionPoolRef.bundleID);
+  console.log(`PROVISION POOL BUNDLE ID: `, provisionPoolRef.bundleID);
+
+  const [provisionPoolStartResult, instancePrivateArgs] = await Promise.all([
+    provisionPoolStartResultP,
+    instancePrivateArgsP,
+  ]);
+  const { adminFacet, instance } = provisionPoolStartResult;
+  // const privateArgs = await deeplyFulfilled(instancePrivateArgs.get(instance));
```
Comment (turadg) [inline packages/vats/src/proposals/upgrade-provisionPool-proposal.js]: stray

File: a3p-integration/proposals/a:upgrade-next/agd-tools.js [hunk 3]
```diff
@@ -137,3 +137,8 @@ export const bankSend = (addr, wanted) => {
 
   return agd.tx('bank', 'send', VALIDATORADDR, addr, wanted, ...noise);
 };
+
+export const getProvisionPoolMetrics = async () => {
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/agd-tools.js:141]: not worth the abstraction imo

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+const ADD_STARS_DIR = 'add-STARS';
+const ADD_STARS2_DIR = 'add-STARS2';
+
+const USDC_DENOM =
+  'ibc/295548A78785A1007F232DE286149A6FF512F180AF5657780FC89C009E2C348F';
+const PROVISIONING_POOL_ADDR = 'agoric1megzytg65cyrgzs6fvzxgrcqvwwl7ugpt62346';
+
+/**
+ * @file
+ * The problems to be addressed are that provisionPool won't correctly handle
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/provisionPool.test.js]: minor: "won't correctly handle" is one problem

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+ * new asset kinds after vat-bank is upgraded.
+ *
+ * To test this, we will
+ *
+ * 1. See that we can add USDC.
+ *
+ * 2. Null upgrade vat-bank, and see that we can add a new collateal.
+ *
+ * 2a. if we had been able to null-upgrade provisionPool at this point, we
+ * wouldn't have been able to productively add USDC, but the null upgrade fails.
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/provisionPool.test.js]: IIUC, this would be more clear:
```suggestion
 * 2a. verify a provisionPool null upgrade fails (if it passed, we wouldn't have been able to productively add USDC)
```
Though I don't understand why

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js [hunk 6]
```diff
@@ -0,0 +1,101 @@
...
+ *
+ * 3. Do a full upgrade of provisionPool; then deposit USDC, and see IST
+ * incremented in totalMintedConverted.
+ *
+ * 4. Null upgrade vat-bank again, and then see (in logs) that adding a new
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/provisionPool.test.js:41]: why not make a deposit to verify that ability?

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js [hunk 7]
```diff
@@ -0,0 +1,101 @@
...
+
+  const metricsAfter = await getProvisionPoolMetrics();
+  console.log('PPT post', metricsAfter);
+  t.is(
+    metricsAfter.totalMintedConverted.brand,
+    metricsBefore.totalMintedConverted.brand,
+    'brands match',
+  );
+  if (expectedToGrow) {
+    // I couldn't import AmountMath. dunno why.
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/provisionPool.test.js:61]: you'd have to add `@agoric/ertp` as a dependency of this proposal package. Did you try that?

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+    );
+  } else {
+    t.equal(
+      metricsAfter.totalMintedConverted.value,
+      metricsBefore.totalMintedConverted.value,
+    );
+  }
+};
+
+test.serial('add assets before', async t => {
```
Comment (turadg) [inline a3p-integration/proposals/a:upgrade-next/provisionPool.test.js]: are these meant to run _in sequence_? `test.serial` just means not in parallel and the order is technically undefined.

if they're in sequence, just put them all into a single test. You can use `t.log` to show progress

File: packages/builders/scripts/vats/add-STARS.js [hunk 9]
```diff
@@ -0,0 +1,22 @@
...
+      keyword: 'STARS',
+      oracleBrand: 'STARS',
+      proposedName: 'STARS',
+    },
+  });
+};
+
+export default async (homeP, endowments) => {
+  const { writeCoreProposal } = await makeHelpers(homeP, endowments);
+  await writeCoreProposal('add-STARS-collateral', starsVaultProposalBuilder);
```
Comment (turadg) [inline packages/builders/scripts/vats/add-STARS.js]: doesn't this belong under `scripts/inter-protocol` like the other `add-STARS.js`?  Please distinguish between them by filename and perhaps a `@file` comment

File: packages/inter-protocol/src/provisionPoolKit.js [hunk 10]
```diff
@@ -327,62 +341,96 @@ export const prepareProvisionPoolKit = (
...
           const {
             state: { brandToPSM, poolBrand },
             facets: { helper },
           } = this;
 
-          // Must match. poolBrand is from durable state and the param is from
-          // the contract, so it technically can change between incarnations.
-          // That would be a severe bug.
-          AmountMath.coerce(poolBrand, params.getPerAccountInitialAmount());
+          void observeNotifier(E(exchangePurse).getCurrentAmountNotifier(), {
```
Comment (turadg) [inline packages/inter-protocol/src/provisionPoolKit.js:346]: this is part of a commit titled `refactor:` but it's changing behavior. It's adding a new feature for upgrade durability so it's a `feat:`. Though it would have made review easier if the refactor changes were separated.

File: a3p-integration/proposals/a:upgrade-next/agd-tools.js (hunk 3 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/agd-tools.js:141]: It hides two things: `getQuoteBody()` is not exported, and the callers would have to share a definition of the path. I'll make the change if you insist, but you'll have to ask a second time. :-)

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js (hunk 6 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/provisionPool.test.js:41]: We only have assets for currencies that provisionPool already knows about. We can add new currencies, but I haven't found a reasonable way to mint them to be able to deposit them.

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js (hunk 5 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/provisionPool.test.js]: I attempted to clarify.

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js (hunk 7 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/provisionPool.test.js:61]: I did try that. Lemme try again.

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js (hunk 8 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/provisionPool.test.js]: done

File: packages/builders/scripts/vats/add-STARS.js (hunk 9 above)
Comment (Chris-Hibbert) [reply packages/builders/scripts/vats/add-STARS.js]: Thinking about moving them there (good idea!) made it clearer that these two are for testing, and shouldn't be confused with the production scripts. Is it enough to put them under a testing directory and add a top-comment?
I also renamed them from STARS since the re-use of an actual currency name is of no value.

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js (hunk 7 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/provisionPool.test.js:61]: When I do, I get an error at runtime
```
  ReferenceError: assert is not defined

  › file://node_modules/@endo/eventual-send/src/E.js:3:40
```
without anything I can recognize as indicating where the problem manifested.

File: packages/inter-protocol/src/provisionPoolKit.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/provisionPoolKit.js]: Yes, that's better.

File: packages/inter-protocol/src/provisionPoolKit.js (hunk 10 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/provisionPoolKit.js:346]: fixed.   I'll try to make better separations.

File: a3p-integration/proposals/a:upgrade-next/agd-tools.js (hunk 3 above)
Comment (turadg) [reply a3p-integration/proposals/a:upgrade-next/agd-tools.js:141]: ah, I didn't notice the export privacy aspect

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js (hunk 6 above)
Comment (turadg) [reply a3p-integration/proposals/a:upgrade-next/provisionPool.test.js:41]: it is trickier since it's a synthetic-chain test. I think you could do it with core-eval that both adds a new currency and with the available powers mints then deposits. But this comment suffices.

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js (hunk 7 above)
Comment (turadg) [reply a3p-integration/proposals/a:upgrade-next/provisionPool.test.js:61]: oh yeah, that durn dependency on SES.

You'll also need `import "@endo/init/debug.js"` before that import.

File: packages/inter-protocol/src/provisionPoolKit.js (hunk 10 above)
Comment (turadg) [reply packages/inter-protocol/src/provisionPoolKit.js:346]: https://github.com/tummychow/git-absorb helps me. E.g. when you had the your review changes, if you ran `git add . && git absorb` it would make fixups on the previous. That way master doesn't have the iterations of code review.

File: packages/builders/scripts/testing/add-LEMONS.js [hunk 11]
```diff
@@ -0,0 +1,27 @@
+import { makeHelpers } from '@agoric/deploy-script-support';
+import { defaultProposalBuilder as vaultProposalBuilder } from '../inter-protocol/add-collateral-core.js';
+
+/**
+ * @file
+ *     *** TESTING ONLY   ***   NOT FOR PRODUCTION USE  ***
```
Comment (turadg) [inline packages/builders/scripts/testing/add-LEMONS.js]: +1 to `scripts/testing`. Perhaps even `scripts/a3p`. There might be some other scripts that belong here but nbd.

That said, I think this line is too scary. There's practically zero risk that somebody is going to find `scripts/testing/add-LEMON.js` and shepherd it into production.
```suggestion
```

File: packages/inter-protocol/src/provisionPoolKit.js [hunk 12]
```diff
@@ -21,9 +21,15 @@ import {
...
 import { E } from '@endo/far';
 import { Far } from '@endo/marshal';
+import { isUpgradeDisconnection } from '@agoric/internal/src/upgrade-api.js';
 
 const { details: X, quote: q, Fail } = assert;
 
+const trace = makeTracer('ProvPool');
+
+const FIRST_CAP_ASCII = /^[A-Z][a-zA-Z0-9_$]*$/;
+const FIRST_LOWER_ASCII = /^[a-z][a-zA-Z0-9_$]*$/;
```
Comment (turadg) [inline packages/inter-protocol/src/provisionPoolKit.js]: these are more restricted than ASCII. consider,
```suggestion
const FIRST_CAP_KEYWORD = /^[A-Z]/;
const FIRST_LOWER_KEYWORD = /^[a-z]/;
```

**Review by turadg — APPROVED** [review]

File: packages/builders/scripts/testing/add-LEMONS.js (hunk 11 above)
Comment (Chris-Hibbert) [reply packages/builders/scripts/testing/add-LEMONS.js]: Yeah, okay. I added the scary line before I renamed them. It's unneeded now.

File: a3p-integration/proposals/a:upgrade-next/provisionPool.test.js (hunk 7 above)
Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/provisionPool.test.js:61]: I'm not familiar with that one (or I've forgotten). Do you have a pointer to an issue or discussion?

Comment (Chris-Hibbert) [reply a3p-integration/proposals/a:upgrade-next/provisionPool.test.js:61]: Ah, it turns out that what we get from vstorage isn't actually an Amount. The brand field contains stringified captp representations. We can compare them for equality, but they're not the brands that AmountMath recognizes.

File: packages/inter-protocol/src/provisionPoolKit.js (hunk 12 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/provisionPoolKit.js]: I'm changing the names to `FIRST_UPPER_KEYWORD` and `FIRST_LOWER_NEAR_KEYWORD`, but keeping the patterns the same. If it's not a keyword pattern, I'd rather take the `else` fallback.

File: a3p-integration/proposals/a:upgrade-next/localchain.test.js
Comment (mhofman) [inline a3p-integration/proposals/a:upgrade-next/localchain.test.js:1]: Why is this test being removed?
