### PR TITLE
fix(vaults): Publish after collateral is returned

### LINKED ISSUE #7665: Vaults that receive collateral back after liquidation (reconstituted or excess collateral) do not reflect it in the UI or metrics query
## Describe the bug
Ran through "Reconstitute" scenario in liquidation testing, which should have resulted in a reconstituted vault with 14.899 collateral and 100.5 debt

Vault UI shows a vault with the correct amount of debt but no collateral

## To Reproduce
1. Run through liquidation in 'reconstitute' scenario
2. Validate that reconstituted vault shows no collateral in the UI

### PR DESCRIPTION
**Pull request by dtribble**
closes: #7665

## Description
The reallocate of collateral happened after looping through the restored vaults to signal that they were completed or restored.

- collect the vaults to be liquidated and do it at the end
- collect the vaults to be reinstated, and do it after reallocate
- add test for the reinstate case for correct balance

### CODE REVIEW

File: packages/inter-protocol/src/vaultFactory/vaultManager.js [hunk 1]
```diff
@@ -898,6 +904,7 @@ export const prepareVaultManagerKit = (
               shortfall: shortfallToReserve,
             });
           }
+          liquidateAll();
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/vaultManager.js:907]: If it doesn't break anything please move this next to `reinstateAll`.

**Review by turadg — APPROVED** [review]
Nice and clean. One suggestion and the commit message needs to be amend.

File: packages/inter-protocol/src/vaultFactory/vaultManager.js (hunk 1 above)
Comment (dtribble) [reply packages/inter-protocol/src/vaultFactory/vaultManager.js:907]: I had intended to do that. BUT `reinstateAll` is only used on one branch, whereas the `liquidateAll` is outside the big `if` and so applies to all branches.
