### PR TITLE
fix(agoric-cli): repair an observed type confusion

### LINKED ISSUE #7700: Error#1: Check failed when attempting to accept the ec committee invitation
4e5ca113512d831026c29a0c9d37703f93fef72b
```
root@0601fc45c85e:/usr/src/agoric-sdk# agops ec committee --send-from $GOV1ADDR
(Error#1)
Error#1: Check failed

  at findContinuingIds (packages/agoric-cli/src/lib/wallet.js:163:3)
  at toOffer (packages/agoric-cli/src/commands/ec.js:151:25)
  at processOffer (packages/agoric-cli/src/commands/ec.js:81:19)
  at async Command.<anonymous> (packages/agoric-cli/src/commands/ec.js:166:7)
  at async packages/agoric-cli/src/bin-agops.js:76:3
```

to reproduce:
```
1. `git clone git@github.com:Agoric/agoric-sdk.git && cd agoric-sdk && checkout ari/vaultstest`
2. `cd packages/deployment/upgrade-test`
3. `make local_sdk build` (once)
4. `make run`
5. run `agops ec committee --send-from $GOV1ADDR`
```

### LINKED ISSUE #7701: Error#1: Check failed unable to accept ec charter
4e5ca113512d831026c29a0c9d37703f93fef72b

```
# agops ec charter --send-from $GOV1ADDR 
(Error#1)
Error#1: Check failed

  at findContinuingIds (packages/agoric-cli/src/lib/wallet.js:163:3)
  at toOffer (packages/agoric-cli/src/commands/ec.js:188:25)
  at processOffer (packages/agoric-cli/src/commands/ec.js:81:19)
  at async Command.<anonymous> (packages/agoric-cli/src/commands/ec.js:203:7)
  at async packages/agoric-cli/src/bin-agops.js:76:3

root@7a7f0ec46caf:/usr/src/agoric-sdk# echo $GOV1ADDR
agoric18rl8v6kgf09fq0y3sutsc3alttrjky3nl2mdqy

```

to reproduce:
```
1. `git clone git@github.com:Agoric/agoric-sdk.git && cd agoric-sdk && checkout ari/vaultstest`
2. `cd packages/deployment/upgrade-test`
3. `make local_sdk build` (once)
4. `make run`
5. run `agops ec charter --send-from $GOV1ADDR`
```

### PR DESCRIPTION
**Pull request by erights**
Fixes #7700 
Fixes #7701 
See https://github.com/Agoric/agoric-sdk/pull/7139

The error reported by both of these seems to be a misunderstanding of what type is expected. `getCurrent` is supposed to return a `CurrentWalletRecord` whose type says that it has a property `offerToUsedInvitation` whose value is an array of pairs, as returned by `Object.entries` applied to an object. But it gets that alleged `current` record from
```js
await readLatestHead(`published.wallet.${addr}.current`)
```
that returns a similar record, but where the value of `offerToUsedInvitation` is an object with the expected property names and values, that needs to be turned into the expected list of pairs.

### CODE REVIEW

File: packages/agoric-cli/src/lib/wallet.js [hunk 1]
```diff
@@ -28,13 +29,28 @@ const emptyCurrentRecord = {
...
-  const current =
+  let current =
     /** @type {Partial<import('@agoric/smart-wallet/src/smartWallet').CurrentWalletRecord> | undefined} */ (
       await readLatestHead(`published.wallet.${addr}.current`)
     );
   if (current === undefined) {
     throw new Error(`undefined current node for ${addr}`);
   }
+
+  // Repair a type misunderstanding seen in the wild
```
Comment (samsiegart) [inline packages/agoric-cli/src/lib/wallet.js]: We can link to https://github.com/Agoric/agoric-sdk/pull/7139 to be more clear

Comment (erights) [reply packages/agoric-cli/src/lib/wallet.js]: Aha! Makes it more clear to me to.

Done, thanks.

**Review by turadg — APPROVED** [review]
🎯
