### PR TITLE
fix(vbank): ensure that multiple balance updates are sorted

### LINKED ISSUE #3425: Use `Fatalf` when Golang tests should abort
Make this `Fatalf` then - if we get here then `gotMsg` and `gotNonce` are likely garbage and we shouldn't compare further.

_Originally posted by @JimLarson in https://github.com/Agoric/agoric-sdk/pull/3423#discussion_r659394679_

### PR DESCRIPTION
**Pull request by michaelfig**
Fixes #3425

@mhofman identified another nondeterminism in `x/vbank`: balance update messages sent to JS that contained more than 1 update were giving an updates array whose order was determined by the Golang [iteration order randomizer](https://github.com/golang/go/issues/6719).

This change sorts the updates array and tests for regressions.

### CODE REVIEW

File: golang/cosmos/x/vbank/vbank_test.go [hunk 1]
```diff
@@ -99,6 +103,7 @@ func Test_marshalBalanceUpdate(t *testing.T) {
 		addressToBalance map[string]sdk.Coins
 		want             balances
 		wantErr          bool
+		encoded          []byte
```
Comment (JimLarson) [inline golang/cosmos/x/vbank/vbank_test.go]: This field seems to be unused.

File: golang/cosmos/x/vbank/vbank_test.go [hunk 2]
```diff
@@ -82,7 +82,11 @@ func decodeBalances(encoded []byte) (balances, uint64, error) {
 		return nil, 0, fmt.Errorf("bad balance update type: %s", balanceUpdate.Type)
 	}
 	b := newBalances()
-	for _, u := range balanceUpdate.Updated {
+	fmt.Printf("updated balances %v\n", balanceUpdate.Updated)
```
Comment (JimLarson) [inline golang/cosmos/x/vbank/vbank_test.go:98]: The non-determinism of update order is what led to the following commit in the PR that created these tests:  https://github.com/Agoric/agoric-sdk/pull/3210/commits/854fe21b192550642d1314698b9610980c593560

In the long run, that commit should be undone and this file should switch from `want` values in the the map-of-maps representation - elegant as it is - to the `vbankBalanceUpdate` structure, or perhaps the raw encoded JSON - depending on whether differences in encoded JSON, e.g. different whitespace, would trigger a nondeterminism failure.

That could possibly be delayed to a follow-on PR. If so, then for now please abstract this plus the Type field check above into a `balanceUpdateValid(vbu vbankBalanceUpdate) bool` utility function, and file an issue for going back to determinism-sensitive `want` values.

File: golang/cosmos/x/vbank/vbank_test.go [hunk 3]
```diff
@@ -495,7 +502,7 @@ func Test_EndBlock_Events(t *testing.T) {
 	}
 	gotMsg, gotNonce, err := decodeBalances([]byte(msgsSent[0]))
 	if err != nil {
-		t.Errorf("decode balances error = %v", err)
+		t.Fatalf("decode balances error = %v", err)
```
Comment (JimLarson) [inline golang/cosmos/x/vbank/vbank_test.go:514]: Cool! Please note that this PR fixes #3425.

**Review by JimLarson — APPROVED** [review]
Great! Just some cleanup stuff to do.

File: golang/cosmos/x/vbank/vbank_test.go (hunk 2 above)
Comment (michaelfig) [reply golang/cosmos/x/vbank/vbank_test.go:98]: I introduced `validateBalanceUpdate`, which returns an `error` if there's a problem, `nil` otherwise.

I'm not sure I want determinism-sensitive `want` values.  I like the fact that the test creates random private/pubkeys, and it would make the test less clear to write dynamic `want` values (since their update order depends on the lexicographic ordering of the pubkey addresses).
