### PR TITLE
5622 vaultManager ephemera

### LINKED ISSUE #5622: Ephemeral state in vaultManager is incorrectly module-scope
## Describe the bug
Introduced in https://github.com/Agoric/agoric-sdk/pull/5214

In [vaultmanager.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/run-protocol/src/vaultFactory/vaultManager.js#L132), the EPHEMERAL STATE is supposed to be per vault manager (embedded in the scope of a `makeVaultManagerfunction`), but instead it’s module scoped!

## To Reproduce
I think the consequences would be:
- with multiple collateral types
- there would only be a single liquidation process for the first collateral
- all other collaterals would update the quote for their own collateral type
- that would either fail or would confuse the quote)

## Expected behavior
Each vault manager has it's own ephemeral state.

## Additional context
The code is complicated by the durability work.

## Solutions
1. Refactor to use the "singleton durable object" pattern for vault managers, so that it is inside the `makeVaultManager` function. 
2. Use a module-level weak map for ephemeral state
3. Make it durable -- can't do this because it have promises and other non-durable objects

### PR DESCRIPTION
**Pull request by turadg**
closes: #5622

## Description

Vault Manager has some ephemeral state in module scope that is unique per VMgr instance. This makes a map that can hold such state, keyed by the VMgr instance. The singleton pattern was also sketched and [ruled out](https://github.com/Agoric/agoric-sdk/pull/5650#issuecomment-1180486256).

It also extracts `makeEphemeralProvider` to be used in other cases for state on durable kinds that need not (or cannot) be durable.

### Security Considerations

`vaultManager.js` continues to trust `contractSupport.js`.

### Documentation Considerations

This is a solution to a challenge common with durable kinds. It may be worth documenting more. At the point I think it's sufficient to have the example and shared utility function.

### Testing Considerations

Ideally we'd have add a regression test that breaks in master and go green now, but the only way I see to cover this case is have liquidations going on one brand while another one is starting and that requires setting up multiple concurrent priceAuthorities which we don't currently support in our test code.

### CODE REVIEW

File: packages/run-protocol/src/vaultFactory/vaultManager.js [hunk 1]
```diff
@@ -127,9 +131,15 @@ const trace = makeTracer('VM');
  * }>} MethodContext
  */
 
-// FIXME https://github.com/Agoric/agoric-sdk/issues/5622
-let liquidationQueueing = false;
-let outstandingQuote = null;
+/** @typedef {{
```
Comment (Chris-Hibbert) [inline packages/run-protocol/src/vaultFactory/vaultManager.js]: I think this is the right place for a comment saying that these values are ephemeral, and per-vaultManager, and why that's the case.

**Review by Chris-Hibbert — APPROVED** [review]
