### PR TITLE
fix(cosmos): share less state between Agoric Cosmos app instances

### LINKED ISSUE #9139: Remove shared mutable state from `App` instances
## Describe the bug

Some Agoric Cosmos modules (notably `golang/cosmos/vm/controller`) use package-level mutable state.  This can interfere with testing multiple App instances in the same process.

## To Reproduce
Instantiate more than one `golang/cosmos/app/app.go` in the same test, and note that they share the same `vm` state when they should not.

## Expected behavior
Isolation between different App instances.

## Platform Environment
 - what OS are you using? what version of Node.js? n/a
 - is there anything special/unusual about your platform? n/a
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #9139

## Description

Prevent the use of shared mutable state in the JS-to-Golang layer from interfering with test setups that instantiate more than one Agoric Cosmos App.

### Security Considerations

Better partitioning of responsibilities and adherence to ocap principles.

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

Tested with existing integration tests as well as some new end-to-end `vtransfer/ibc_middleware_test.go` tests.

### Upgrade Considerations

n/a

### CODE REVIEW

File: golang/cosmos/vm/server.go [hunk 1]
```diff
@@ -1,23 +1,93 @@
...
 	"fmt"
+	"sync"
+
+	sdk "github.com/cosmos/cosmos-sdk/types"
 )
 
-type AgdServer struct{}
+const VmPortMappingContextKey = sdk.ContextKey("vm-port-mapping")
+
+type AgdServer struct {
```
Comment (JimLarson) [inline golang/cosmos/vm/server.go:13]:
```suggestion
// AgdServer manages communication from the VM to the ABCI app.
// The structure is mutable and the mutex must be held to read or write any field.
type AgdServer struct {
```

File: golang/cosmos/vm/server.go [hunk 2]
```diff
@@ -1,23 +1,93 @@
...
+	portToHandler map[int]PortHandler
+	portToName    map[int]string
+	nameToPort    map[string]int
+}
+
+var wrappedEmptySDKContext = sdk.WrapSDKContext(
+	sdk.Context{}.WithContext(context.Background()),
+)
 
 func NewAgdServer() *AgdServer {
```
Comment (JimLarson) [inline golang/cosmos/vm/server.go:31]:
```suggestion
// NewAgdServer returns a pointer to a new AgdServer
// with empty context and port mappings.
func NewAgdServer() *AgdServer {
```

File: golang/cosmos/vm/server.go [hunk 3]
```diff
@@ -1,23 +1,93 @@
...
+	return &AgdServer{
+		currentCtx:    wrappedEmptySDKContext,
+		mtx:           sync.Mutex{},
+		portToHandler: make(map[int]PortHandler),
+		portToName:    make(map[int]string),
+		nameToPort:    make(map[string]int),
+	}
+}
+
+func (s *AgdServer) SetControllerContext(ctx sdk.Context) func() {
```
Comment (JimLarson) [inline golang/cosmos/vm/server.go:43]:
```suggestion
// SetControllerContext sets the context to the given argument and returns a function
// which will reset the context to an empty context (not the old context).
func (s *AgdServer) SetControllerContext(ctx sdk.Context) func() {
```

File: golang/cosmos/vm/server.go [hunk 4]
```diff
@@ -1,23 +1,93 @@
...
+	defer s.mtx.Unlock()
+	s.currentCtx = sdk.WrapSDKContext(ctx.WithGasMeter(sdk.NewInfiniteGasMeter()))
+	return func() {
+		s.mtx.Lock()
+		defer s.mtx.Unlock()
+		s.currentCtx = wrappedEmptySDKContext
+	}
+}
+
+func (s *AgdServer) getContextAndHandler(port int) (context.Context, PortHandler) {
```
Comment (JimLarson) [inline golang/cosmos/vm/server.go:58]:
```suggestion
// getContextAndHandler atomically gets the context and handler for the given port number.
func (s *AgdServer) getContextAndHandler(port int) (context.Context, PortHandler) {
```

File: golang/cosmos/vm/server.go [hunk 5]
```diff
@@ -1,23 +1,93 @@
...
 	if handler == nil {
 		return fmt.Errorf("unregistered port %d", msg.Port)
 	}
-	resp, err := handler.Receive(controllerContext, msg.Data)
+	resp, err := handler.Receive(ctx, msg.Data)
 	*reply = resp
 	return err
 }
+
+func (s *AgdServer) GetPort(name string) int {
```
Comment (JimLarson) [inline golang/cosmos/vm/server.go:80]:
```suggestion
// GetPort returns a port number by name, or 0 if the name is not registered.
func (s *AgdServer) GetPort(name string) int {
```

File: golang/cosmos/vm/server.go [hunk 6]
```diff
@@ -1,23 +1,93 @@
...
+	sdk "github.com/cosmos/cosmos-sdk/types"
 )
 
-type AgdServer struct{}
+const VmPortMappingContextKey = sdk.ContextKey("vm-port-mapping")
+
+type AgdServer struct {
+	currentCtx    context.Context
+	mtx           sync.Mutex
+	lastPort      int
```
Comment (JimLarson) [inline golang/cosmos/vm/server.go]:
```suggestion
	// zero is an out-of-band port number
	lastPort      int
```

File: golang/cosmos/vm/server.go [hunk 7]
```diff
@@ -1,23 +1,93 @@
...
 	return err
 }
+
+func (s *AgdServer) GetPort(name string) int {
+	s.mtx.Lock()
+	defer s.mtx.Unlock()
+	return s.nameToPort[name]
+}
+
+func (s *AgdServer) RegisterPortHandler(name string, portHandler PortHandler) int {
```
Comment (JimLarson) [inline golang/cosmos/vm/server.go]:
```suggestion
// RegisterPortHandler registers the handler to a new port number, then maps the name to it,
// returning the port number. If the name was previously in use, the old port number still maps
// to the old handler and name, but the name will only map to the new port number.
func (s *AgdServer) RegisterPortHandler(name string, portHandler PortHandler) int {
```

File: golang/cosmos/vm/server.go [hunk 8]
```diff
@@ -1,23 +1,93 @@
...
+	s.mtx.Lock()
+	defer s.mtx.Unlock()
+	s.lastPort++
+	s.portToHandler[s.lastPort] = NewProtectedPortHandler(portHandler)
+	s.portToName[s.lastPort] = name
+	s.nameToPort[name] = s.lastPort
+	return s.lastPort
+}
+
+func (s *AgdServer) UnregisterPortHandler(portNum int) error {
```
Comment (JimLarson) [inline golang/cosmos/vm/server.go:113]:
```suggestion
// UnregisterPortHandler unregisters the handler and name mappings for this port number,
// and the reverse mapping for its name, if any of these exist.
func (s *AgdServer) UnregisterPortHandler(portNum int) error {
```

File: golang/cosmos/vm/server.go [hunk 9]
```diff
@@ -1,23 +1,93 @@
...
+	s.mtx.Lock()
+	defer s.mtx.Unlock()
+	delete(s.portToHandler, portNum)
+	name := s.portToName[portNum]
+	delete(s.portToName, portNum)
+	delete(s.nameToPort, name)
+	return nil
```
Comment (JimLarson) [inline golang/cosmos/vm/server.go:123]: Since there's currently no error case, consider eliminating the return type? Or make unregistering an unused port an error.

File: golang/cosmos/vm/server.go [hunk 10]
```diff
@@ -1,23 +1,93 @@
...
+	return s.lastPort
+}
+
+func (s *AgdServer) UnregisterPortHandler(portNum int) error {
+	s.mtx.Lock()
+	defer s.mtx.Unlock()
+	delete(s.portToHandler, portNum)
+	name := s.portToName[portNum]
+	delete(s.portToName, portNum)
+	delete(s.nameToPort, name)
```
Comment (JimLarson) [inline golang/cosmos/vm/server.go:122]: Potential problem here if a second port handler is registered for the same name and you unregister the first one's port number - it still removes the name-to-new-port mapping. Consider either:

- making it an error to register a handler for an already-registered name;
- registering an already-registered name merely overwrites the handler and uses the old port number;
- registering an already-registered name completely unregisters the old one before registering the new one.

File: golang/cosmos/vm/server.go [hunk 11]
```diff
@@ -1,23 +1,93 @@
...
-type AgdServer struct{}
+const VmPortMappingContextKey = sdk.ContextKey("vm-port-mapping")
+
+type AgdServer struct {
+	currentCtx    context.Context
+	mtx           sync.Mutex
+	lastPort      int
+	portToHandler map[int]PortHandler
+	portToName    map[int]string
+	nameToPort    map[string]int
```
Comment (JimLarson) [inline golang/cosmos/vm/server.go]: Document the invariants - subject to how you solve the re-registration issue mentioned below. One option is:

```
// portToHandler[i] is nonzero iff portToName[i] is nonzero
// portToName[nameToPort[i]] == i && nameToPort[portToName[s]] == s for all i, s.
```

**Review by JimLarson — CHANGES_REQUESTED** [review]
Mostly comment suggestions but one potential corruption. Should either error on re-registering a port name or handle it in one of several ways.

File: golang/cosmos/vm/server.go (hunk 9 above)
Comment (ivanlei) [reply golang/cosmos/vm/server.go:123]: IMO: Returning an `error` from a function but not currently having any failure cases is reasonable defensive programming. It lets the function evolve and develop error cases without the callers needing modification.

File: golang/cosmos/vm/server.go (hunk 10 above)
Comment (michaelfig) [reply golang/cosmos/vm/server.go:122]: Thanks, I made it an error to register a handler for an already-registered name.

**Review by michaelfig — COMMENTED** [review]
Comments addressed.  PTA(nother)L, @JimLarson.

**Review by JimLarson — APPROVED** [review]
LGTM!
