### PR TITLE
fix(vats): `vats/init-core.js` relies on econCommittee

### LINKED ISSUE #11053: Devnet vm-config does not provision smart wallets
## Describe the bug
New chains initialized (not upgraded) from `@agoric/vm-config/decentral-devnet-config.json` cannot provision smart wallets.

## To Reproduce
1. `cd packages/cosmic-swingset`
2. `make scenario2-setup scenario2-run-chain`
3. Wait (a long time) for the chain to begin producing blocks, like `block 17 commit`
4. In another terminal, `make fund-provision-pool`
5. `make provision-acct ACCT_ADDR=$(cat t1/8000/ag-cosmos-helper-address)`
6. `agd query vstorage path published.wallet.`
7. See no wallet children entries:
```yaml
children: []
pagination: null
```

## Expected behavior

`agd query vstorage path published.wallet` should return at least one child, like:
```yaml
children:
- agoric137z4uxjns44yllh6zfffzrp0zerldlqzxftg2k
pagination: null
```

## Platform Environment
- what OS are you using? macOS Sonoma 14.7.4
- what version of Node.js? v20.17.0
- is there anything special/unusual about your platform? nope
- what version of the Agoric-SDK are you using? `fast-usdc-beta-1-127-gd711f8fd3b`

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #11053

## Description

A catch-22 was introduced when `vats/init-core.js` and `inter-protocol/init-core.js` were separated into different coreProposal steps:
- `startWalletFactory` would not advance to the next step until `provisionPool` was instantiated with governance, but
- the governance needed by `provisionPool` was established in a later step.

Moving them to the same step was the expedient approach taken by #11058, but breaking the deadlock by decoupling the completion of `startWalletFactory` from the `provisionPool` governance seems cleaner, and less dependent upon subtle `@agoric/vm-config` steps.

Breaking the deadlock was crucial for solving #11053 , so that smart wallets can be properly provisioned even if `inter-protocol` governance occurs in a later step than `vats/init-core.js`.

Also in this PR:
- don't call `onReset` unless `producer.reset()` actually modified something
- add the key name to the rejection reason propagated to a nameHub's consumer caused by resetting a promise-space key.

### Security Considerations

n/a

### Scaling Considerations

No additional resource consumption.

### Documentation Considerations

n/a

### Testing Considerations

Comprehensive `cosmic-swinget/test/make.test.js` testing of wallet provisioning, including `scenario2.js` test library fixes.

To test this in a testnet, just boot it from genesis, and verify that smart wallets can be successfully provisioned via the faucet (don't forget to send some funds to the `provisionPool` or `uist` to the faucet account!).

### Upgrade Considerations

The bootstrap vat JS code is not upgradable for existing chains, so much of the changes in this PR will not affect those chains.  Besides that, the `agoricNames` vat and `provisioning` vat host nameHubs, so the `Value for ${key} has been deleted` diagnostic will continue to lack the `${key}` until they are upgraded.

Future chains booted from genesis will benefit the most from these changes.

### CODE REVIEW

File: packages/vats/src/core/promise-space.js [hunk 1]
```diff
@@ -50,10 +50,10 @@ export const makeStoreHooks = (store, log = noop) => {
       return;
     }
     if (store.has(name)) {
-      console.warn('cannot save duplicate:', name);
-      return;
+      store.set(name, value);
```
Comment (dckc) [inline packages/vats/src/core/promise-space.js:53]: how would this change get to mainnet?

"n/a" doesn't seem to suffice for upgrade considerations.

Comment (dckc) [reply packages/vats/src/core/promise-space.js:53]: How about adding a test in `test-promise-space.js` for this fix?

File: packages/vats/src/core/promise-space.js [hunk 2]
```diff
@@ -144,6 +144,9 @@ export const makePromiseSpace = (optsOrLog = {}) => {
     };
     const reset = (reason = undefined) => {
       onReset(name);
+      if (!nameToState.has(name)) {
+        return;
+      }
```
Comment (dckc) [inline packages/vats/src/core/promise-space.js:148]: How about adding a test in `test-promise-space.js` for this fix too?

File: packages/vats/src/core/startWalletFactory.js [hunk 3]
```diff
@@ -223,32 +225,60 @@ export const startWalletFactory = async (
     privateArgs: {
       storageNode: walletStorageNode,
       walletBridgeManager,
-      walletReviver: E(ppFacets.creatorFacet).getWalletReviver(),
+      walletReviver: E(E.get(ppFacetsP).creatorFacet).getWalletReviver(),
```
Comment (dckc) [inline packages/vats/src/core/startWalletFactory.js:229]: we pass a promise in `privateArgs`? I wonder how that works with upgrade... Do settled promises stay settled across upgrades?

File: packages/vats/src/core/startWalletFactory.js [hunk 4]
```diff
@@ -184,7 +184,11 @@ export const startWalletFactory = async (
 
   const marshaller = await E(board).getPublishingMarshaller();
   const poolBank = E(bankManager).getBankForAddress(poolAddr);
-  const ppFacets = await E(startGovernedUpgradable)({
+
+  // We cannot await the start of the provisionPool, since
```
Comment (dckc) [inline packages/vats/src/core/startWalletFactory.js:189]: We did `await` when we rebooted the VM in the vaults upgrade, right? Any idea what changed?

https://github.com/Agoric/agoric-sdk/blob/ba3b776444425bbcb275ce918794d9259f8e15da/packages/vats/src/core/startWalletFactory.js#L169

aka
https://github.com/Agoric/agoric-sdk/blob/mainnet1B-rc3/packages/vats/src/core/startWalletFactory.js#L169

File: packages/vats/src/core/startWalletFactory.js [hunk 5]
```diff
@@ -223,32 +225,60 @@ export const startWalletFactory = async (
...
+  const initAfterProvisionPool = async () => {
+    trace('initAfterProvisionPool awaiting provisionPoolFacets');
+    const ppFacets = await ppFacetsP;
+    trace('initAfterProvisionPool settled provisionPoolFacets');
+
+    provisionPoolStartResult.resolve(ppFacets);
+    instanceProduce.provisionPool.resolve(ppFacets.instance);
+
+    await Promise.all([
+      E(ppFacets.creatorFacet).addRevivableAddresses(oldAddresses),
```
Comment (dckc) [inline packages/vats/src/core/startWalletFactory.js:253]: I would dearly like to get rid of the whole reviving business.
someday...

File: packages/vats/src/core/utils.js [hunk 6]
```diff
@@ -212,19 +212,27 @@ const noop = harden(() => {});
...
-        void E.when(valueP, value => E(nameAdmin).update(name, value));
+        void E.when(valueP, value => E.sendOnly(nameAdmin).update(name, value));
       },
       onReset: name => {
-        void E(nameAdmin).delete(name);
+        void E(readonlyP)
+          .has(name)
+          .then(present => {
+            if (present) {
+              void E.sendOnly(nameAdmin).delete(name);
```
Comment (dckc) [inline packages/vats/src/core/utils.js]: seems worth a unit test in [test-name-hub-published.js](https://github.com/Agoric/agoric-sdk/blob/feefe9bab3ed25d7fa8700d63968228c46509da2/packages/vats/test/test-name-hub-published.js)

Comment (dckc) [reply packages/vats/src/core/utils.js]: but again... how do we deploy this change to mainnet?

Maybe the answer is "we don't" but that merits something explicit in upgrade considerations.

File: packages/vats/src/nameHub.js [hunk 7]
```diff
@@ -335,7 +335,7 @@ export const prepareNameHubKit = zone => {
             if (pmap.has(key)) {
               // Reject only if already exists.
               const old = NonNullish(pmap.get(key));
-              old.reject(Error(`Value has been deleted`));
+              old.reject(Error(`Value for ${key} has been deleted`));
```
Comment (dckc) [inline packages/vats/src/nameHub.js:338]: :1st_place_medal:

Comment (dckc) [reply packages/vats/src/nameHub.js:338]: Is the `agoricNames` vat being upgraded in u19?

Is `nameHub` used in any other vats? Oh yeah... provisioning holds namesByAddress. Are we upgrading that one?

**Review by dckc — COMMENTED** [review]
I think some unit tests are worthwhile for the fixes.

And I think there's more to say about **Upgrade Considerations**.

File: packages/vats/src/core/promise-space.js (hunk 1 above)
Comment (dckc) [reply packages/vats/src/core/promise-space.js:53]: "How do we validate this change in a testnet?" will eventually be asked. If the answer is "it's not cost-effective" then that should go in **Testing Considerations**.

File: packages/vats/src/core/startWalletFactory.js (hunk 3 above)
Comment (michaelfig) [reply packages/vats/src/core/startWalletFactory.js:229]: When a remote promise settles, the kernel is informed, and any vat that has subscribed to that promise will get the resulting data (or presence).  At that point, it is safe for either vat to upgrade, without the settled promise somehow interfering.

File: packages/vats/src/core/startWalletFactory.js (hunk 4 above)
Comment (michaelfig) [reply packages/vats/src/core/startWalletFactory.js:189]: The `decentral-devnet-config.json` introduced coreProposal steps, which will be useful for clearer separation of bootstrap dependencies.  That clearer separation revealed the fact that `startWalletFactory` would not resolve until `inter-protocol` established the governance committee for the `provisionPool`.  See my updates to the PR description above.

I don't know what completed the cycle from the inter-protocol side of things back to the wallet factory.

Since this runs at chain bootstrap time, all steps will complete before the first block commits, so the provisionPool-less walletFactory isn't exposed to any externally-submitted transactions.

File: packages/vats/src/core/startWalletFactory.js (hunk 5 above)
Comment (michaelfig) [reply packages/vats/src/core/startWalletFactory.js:253]: ... over a rainbow?

File: packages/vats/src/core/utils.js (hunk 6 above)
Comment (michaelfig) [reply packages/vats/src/core/utils.js]: This change is outdated since I simplified the `utils.js` change to just one line.

File: packages/vats/src/nameHub.js (hunk 7 above)
Comment (michaelfig) [reply packages/vats/src/nameHub.js:338]: I put notes in the Upgrade Considerations above.

**Comment by michaelfig** [comment]
@dckc, I still owe you a few little tests, but now that I've simplified the changes and adequately written up the PR description, I'd appreciate your rereview so I can address all the comments at once during the next push.

File: packages/vats/src/core/startWalletFactory.js (hunk 4 above)
Comment (dckc) [reply packages/vats/src/core/startWalletFactory.js:189]: ok

File: packages/vats/src/core/utils.js [hunk 8]
```diff
@@ -221,6 +221,7 @@ export const makePromiseSpaceForNameHub = (nameAdmin, log = noop) => {
         logHooks.onAddKey(name);
       },
       onResolve: (name, valueP) => {
+        void E(nameAdmin).reserve(name);
```
Comment (dckc) [inline packages/vats/src/core/utils.js]: interesting solution

**Review by dckc — APPROVED** [review]
upgrade considerations and such look good

I approve presuming the unit tests as discussed.

File: packages/vats/src/core/utils.js (hunk 8 above)
Comment (michaelfig) [reply packages/vats/src/core/utils.js]: I will add a test for this fix.

Comment (michaelfig) [reply packages/vats/src/core/utils.js]: Turns out it wasn't necessary... the `onAddKey` does a reserve before `onResolve` is called.
