### PR TITLE
fix(liveslots): allow new Kind upgrade to add new facets

### LINKED ISSUE #7437: defineDurableKindMulti can't add new facets during upgrade
## Describe the bug

@Chris-Hibbert asked me today about what, exactly, can be changed about a durable Kind when the vat/contract is upgraded. I told him:

* faceted-ness vs unfacetness must remain the same (either use `defineDurableKind` both times, or `defineDurableKindMulti` both times
* any existing facets (i.e. the facet name) must still exist
* new facets can be added (* caveat 1)
* the methods of each facet can be completely changed
* the state of the instances must have the same property names (* caveat 2)
* the optional `stateShape` constraint, if provided, must be the same (* caveat 2)

"Caveat 2" is that we have a plan (#7407) to allow a migration function that will let the state contents and/or `stateShape` be changed across upgrades.

"Caveat 1" is that I think I was wrong. We intended to allow new facets during upgrade, but our implementation sorts the facet names before assigning them integers, so the "does this facet still exist, and with the same integer index" check is working on the *sorted* names. The consequence is that you ~can only add facets if they sort alphabetically *later* than any existing facets~, which is clearly not useful.

EDIT: further investigation shows that you cannot add new facets at all, the check ensures that everything on the new list is also on the old list, which means that it incorrectly tolerates the removal of late-alphabet facets.

It looks like we have several *negative* tests, which assert than an upgrade fails if you change various aspects of the facet list. But we don't have any positive test which shows an upgrade *succeeding* when new facets are added.

## The Fix

When we examine the facet names of the new behavior record, and assign them integers, we should consult the old (recorded) list first, and use the same integer for any pre-existing facet. Then we should check that all old facets still exist. Then we should take all of the new names and assign them new integers.

We need to confirm that the reference counts and export status DB values are still compatible. The export status is a string of length `numFacets`, so the question is whether a short string will be correctly interpreted as having the new facets be unexported.

I don't remember how the refcount string is encoded, we need to check and make sure it is tolerant of new facets too.

## Priority

We don't strictly need to do this before the Vaults upgrade, since the first time it will be needed is during contract upgrades that happen post-Vaults, which will work as long as we upgrade the chain to use a new version of liveslots (with the new `defineDurableKindMulti`) by then. But if there's any problem with refcount/export-status data, we might want to get that fixed beforehand, so we don't run into any surprises later.

### PR DESCRIPTION
**Pull request by warner**
fix(liveslots): allow new Kind upgrade to add new facets

When a new vat's new incarnation is redefining all the existing
durable Kinds, it provides new behavior records, which might contain a
different set of facets than the previous incarnation was using.

Vats are not allowed to omit old facets: they are required to provide
definitions for every facet that the previous version defined. However
they *are* allowed to *add* facets. New calls to the maker will return
a larger cohort of Representatives than before. The new facets will be
created (during deserialization) of pre-existing objects too, however
the only way to access them will be through new behavior functions on
old facets (through e.g. `facets.newFacet`).

Previously, this new-facets compatibility check was broken. New facets
were never allowed, and even some old facets could be omitted without
causing `defineDurableKindMulti` to throw an error (although behavior
beyond that point was probably corrupt).

This commit changes the VOM to properly allow new facets, and to check
for any missing ones. This relies upon the recent change to
`setExportStatus()`, to tolerate old `vom.es.${baseRef}` records with
fewer facets than the current definition is tracking.

`checkAndUpdateFacetiousness()` is factored out into a separate file,
with extensive tests. New tests were added to test-kind-changes.js, as
well as higher-level tests in packages/SwingSet (test-upgrade.js was
rewritten to exercise the various combinations more directly).

closes #7437

### CODE REVIEW

File: packages/swingset-liveslots/src/facetiousness.js [hunk 1]
```diff
@@ -41,3 +43,43 @@ export function assessFacetiousness(obj) {
...
+      proposal.splice(proposedIdx, 1); // remove from proposal
+      newFacetNames.push(facet);
+    }
+
+    // new facets are appended in alphabetic order
+    proposal.sort();
+    desc.facets = newFacetNames.concat(proposal);
+  } else {
+    desc.unfaceted = true;
+  }
```
Comment (FUDCo) [inline packages/swingset-liveslots/src/facetiousness.js:85]: What is this `else` clause doing?  Isn't it redundant with the check on line 54?

**Review by FUDCo — APPROVED** [review]
Looks good.  Glad to get this cleaned up.

File: packages/swingset-liveslots/src/facetiousness.js (hunk 1 above)
Comment (warner) [reply packages/swingset-liveslots/src/facetiousness.js:85]: Line 81 is where `.unfaceted` is assigned in the first place. `checkAndUpdateFacetiousness` is called on both the first and the subsequent times. The first time it gets a descriptor with just `{ kindID, tag }`, and this function is responsible for adding `.unfaceted` or `.facets` (it mutates `desc` in place.. I should call that out in a comment). The subsequent times, it might update `.facets` (if new facets were added), redundantly re-assign `.facets` with the same names as before (if no new facets were added), or it might redundantly re-assign `.unfaceted = true`.

It seemed easier to have it always make an assignment, even if it's reassigning the same value, than to have a bunch of conditionals.

I'll add some comments.
