### PR TITLE
fix(zoe): assert that amountKeywordRecord is a copyRecord

### LINKED ISSUE #4061: Validate User-provided Keywords as Keywords
# Suggestion 1: Adhere to Keyword Standards

## Location

https://github.com/Agoric/agoric-sdk/blob/f6a87bab45bb6ac611f91e20a3c93baf1b180294/packages/zoe/src/contractFacet/zcfZygote.js#L151

https://github.com/Agoric/agoric-sdk/blob/f6a87bab45bb6ac611f91e20a3c93baf1b180294/packages/zoe/src/contractFacet/zcfZygote.js#L189

## Synopsis

Keywords follow a standard that is being asserted and enforced to prevent accidental conflicts with existing property names in some cases (i.e. instanceRecordStorage.js, cleanProposal.js) but not in all cases, as indicated in the aforementioned links in the location section.

## Suggested Mitigation
We recommend making all keywords adhere to the same standard.

## Planned Mitigation

Alter `assertAmountKeywordRecord` to actually assert that keywords are keywords. See `cleanProposal.js` for example code that can be used.

### PR DESCRIPTION
**Pull request by katelynsills**
BREAKING CHANGE: `amountKeywordRecord` must be hardened before passing to `zcfMint` and `zcfSeat` methods

Note: because this is a breaking change, we may want to wait to merge until we have other Zoe input validation complete, so there's only one breaking change to Zoe.

closes: #4061

## Description

This PR changes the code of `zcfMint.burnLosses`, `zcfMint.mintGains`, `zcfSeat.incrementBy`, and `zcfSeat.decrementBy` to assert that the user-defined `amountKeywordRecord` is actually a keyword record and coerce the amounts. This means checking that it is a copyRecord, among other things. The actual function used is `coerceAmountKeywordRecord` from `cleanProposal.js`.

`coerceAmountKeywordRecord` requires a hardened object, thus, this is a breaking change. Any `amountKeywordRecord` not hardened will cause the function to throw.

### Security Considerations

This is part of the input validation that we need to do for Zoe, but not the entirety of it. https://github.com/Agoric/agoric-sdk/issues/4068 is the input validation task covering all of Zoe.

### Documentation Considerations

This is a breaking change that will effect dapps. We should explain the need to `harden` in our documentation.

### Testing Considerations

No additional tests needed.

### CODE REVIEW

File: packages/zoe/src/contracts/loan/close.js [hunk 1]
```diff
@@ -43,14 +43,18 @@ export const makeCloseLoanInvitation = (zcf, config) => {
...
+          Collateral: collateralSeat.getAmountAllocated(
+            'Collateral',
+            collateralBrand,
+          ),
+        }),
+      ),
+    );
+    lenderSeat.incrementBy(
+      harden(repaySeat.decrementBy(harden({ Loan: debt }))),
     );
```
Comment (erights) [inline packages/zoe/src/contracts/loan/close.js]: Ideally the creator of an object is the one to harden the object before releasing it. The typical and best case, as in the remaining harden here, is on the object literal itself. Otherwise, things should only be passing hardened objects to each other. The receiver should be defensively checking and rejecting, as `incrementBy` already does. It should not be doing its own defensive hardening, as that masks bugs in the source of the object. For example, if `decrementBy` returned an unhardened object, the defensive harden would mask the bug. In this case it is fine because `decrementBy` is not buggy in this way.
```suggestion
    lenderSeat.incrementBy(repaySeat.decrementBy(harden({ Loan: debt })));
```
Please correct all places where this PR makes this error.

This will also cause some error messages to revert to what they were before this PR. IMO the old error messages were better anyway, so this is welcome.

File: packages/zoe/test/unitTests/zcf/test-reallocateForZCFMint.js [hunk 2]
```diff
@@ -9,7 +9,7 @@ import { setup } from '../setupBasicMints.js';
 
 import { setupZCFTest } from './setupZcfTest.js';
 
-// Test that `zcfSeat.incrementBy()` and `zcfSeat.decrementBy()` can
+// Test that `zcfSeat.incrementBy(harden()` and `zcfSeat.decrementBy(harden()))` can
```
Comment (erights) [inline packages/zoe/test/unitTests/zcf/test-reallocateForZCFMint.js]: A regexp-based transform gone wrong?
```suggestion
// Test that `zcfSeat.incrementBy()` and `zcfSeat.decrementBy()` can
```

**Review by erights — APPROVED** [review]
LGTM

File: packages/zoe/test/unitTests/zcf/test-reallocateForZCFMint.js (hunk 2 above)
Comment (katelynsills) [reply packages/zoe/test/unitTests/zcf/test-reallocateForZCFMint.js]: Oof, yes!

File: packages/zoe/src/contracts/loan/close.js (hunk 1 above)
Comment (katelynsills) [reply packages/zoe/src/contracts/loan/close.js]: Hmm, I'm not seeing how this will cause some error messages to revert. I would expect the effect to be the same.

But, I just removed all of the `harden` calls on outputs from `incrementBy` and `decrementBy`, since they are already hardened.
