### PR TITLE
Fix every assert!!  For great speediness!

### LINKED ISSUE #7271: Cleanup assert detail strings in the kernel and kernel adjacent packages
## What is the Problem Being Solved?

Testing has shown that an unreasonable amount of computation is being expended on runtime asserts, in particular on the construction of detail strings that will never be used.  We've developed new coding patterns to address these, and while these patterns are being used in new code they have not yet been systemically retrofitted on existing code.  The task here is to perform that retrofit with respect to the kernel and kernel-related packages (currently: `SwingSet`, `swing-store`, and `swingset-liveslots`).

## Description of the Design

Any assertion with a detail string where the detail string is anything other than a single string literal should be converted to the new `Fail` pattern:
 
That is, convert asserts such as
```
assert(expr, X`...`);
```
to
```
expr || Fail`...`;
```
or to
```
if (!expr) {
  throw Fail`...`;
}
```
if TypeScript's type inference engine gets confused by the simpler form and reports type errors.

Asserts of the form `assert(expr)` (i.e., no details) or `assert(expr, 'simple message')` (i.e., details consist of a single string literal) need not be converted.

The reference to `assert` here is for illustrative purposes. Other kinds of asserts such as `assert.equal(...)`should follow the same logic.  However, measurement has shown that type checking is faster inline, so `assert.typeof(....)` should always be converted to the `Fail` form regardless of details.  It may also make sense to always convert direct failures (`assert.fail(...)`) simply because it's cleaner and shorter.

## Security Considerations

None in particular.  Semantically this conversion should be no-op.

## Scaling Considerations

None as such, though obviously the point of the exercise is to improve performance, which will help with scaling.

### PR DESCRIPTION
**Pull request by FUDCo**
Closes #7271

I'm sure this will be some kind of performance improvement, but it's possible these changes won't provide as much benefit as we originally hoped -- there proved to be far fewer asserts that mandated adjusting than I think we anticipated, since a great fraction had either a constant detail string or no details at all.

There were several detail strings that were template strings with no values injected into them at all (i.e., no embedded `${foo}` expressions) but instead were simple string literals that happened to be delimited by back-ticks instead of quotes.  These have been changed to ordinary string literals.

### CODE REVIEW

File: packages/SwingSet/src/devices/plugin/device-plugin.js [hunk 1]
```diff
@@ -115,7 +115,7 @@ export function buildRootDeviceNode(tools) {
   function send(index, obj) {
     const mod = connectedMods[index];
     // console.info('send', index, obj, mod);
-    assert(mod, X`No module associated with ${index}`, TypeError);
+    mod || Fail`No module associated with ${index}`;
```
Comment (gibson042) [inline packages/SwingSet/src/devices/plugin/device-plugin.js:118]: We should probably maintain this and similar use of `assert`'s third argument so the PR doesn't affect input/output behavior.
```suggestion
    mod || assert.fail(X`No module associated with ${index}`, TypeError);
```

**Review by warner — APPROVED** [review]
Looks good! Sorry for the delay :(

File: packages/SwingSet/src/kernel/state/vatKeeper.js [hunk 2]
```diff
@@ -589,8 +590,7 @@ export function makeVatKeeper(
       const slot = k.slice(prefix.length);
       if (!slot.startsWith('k')) {
         const vatSlot = slot;
-        const kernelSlot =
-          kvStore.get(k) || assert.fail('getNextKey ensures get');
+        const kernelSlot = kvStore.get(k) || Fail`getNextKey ensures get`;
```
Comment (gibson042) [inline packages/SwingSet/src/kernel/state/vatKeeper.js:592]: We should make more use of this ``` foo = bar() || Fail`…` ``` fallible assignment expression pattern!

File: packages/SwingSet/src/vats/network/network.js [hunk 3]
```diff
@@ -277,7 +277,7 @@ export function makeNetworkProtocol(protocolHandler) {
       },
       async addListener(listenHandler) {
         !revoked || Fail`Port ${localAddr} is revoked`;
-        assert(listenHandler, X`listenHandler is not defined`, TypeError);
+        listenHandler || Fail`listenHandler is not defined`;
```
Comment (gibson042) [inline packages/SwingSet/src/vats/network/network.js:280]:
```suggestion
        listenHandler || assert.fail('listenHandler is not defined', TypeError);
```

File: packages/SwingSet/src/vats/network/router.js [hunk 4]
```diff
@@ -53,11 +53,8 @@ export default function makeRouter() {
       prefixToRoute.init(prefix, route);
     },
     unregister(prefix, route) {
-      assert(
-        prefixToRoute.get(prefix) === route,
-        X`Router is not registered at prefix ${prefix}`,
-        TypeError,
-      );
+      prefixToRoute.get(prefix) === route ||
+        Fail`Router is not registered at prefix ${prefix}`;
```
Comment (gibson042) [inline packages/SwingSet/src/vats/network/router.js:57]:
```suggestion
      prefixToRoute.get(prefix) === route ||
        assert.fail(X`Router is not registered at prefix ${prefix}`, TypeError);
```

File: packages/SwingSet/src/vats/network/router.js [hunk 5]
```diff
@@ -96,11 +93,8 @@ export function makeRouterProtocol(E = defaultE) {
   // Needs to account for multiple paths.
   function unregisterProtocolHandler(prefix, protocolHandler) {
     const ph = protocolHandlers.get(prefix);
-    assert(
-      ph === protocolHandler,
-      X`Protocol handler is not registered at prefix ${prefix}`,
-      TypeError,
-    );
+    ph === protocolHandler ||
+      Fail`Protocol handler is not registered at prefix ${prefix}`;
```
Comment (gibson042) [inline packages/SwingSet/src/vats/network/router.js:97]:
```suggestion
    ph === protocolHandler ||
      assert.fail(X`Protocol handler is not registered at prefix ${prefix}`, TypeError);
```

File: packages/SwingSet/src/vats/network/router.js [hunk 6]
```diff
@@ -109,11 +103,7 @@ export function makeRouterProtocol(E = defaultE) {
   /** @type {Protocol['bind']} */
   async function bind(localAddr) {
     const [route] = router.getRoutes(localAddr);
-    assert(
-      route !== undefined,
-      X`No registered router for ${localAddr}`,
-      TypeError,
-    );
+    route !== undefined || Fail`No registered router for ${localAddr}`;
```
Comment (gibson042) [inline packages/SwingSet/src/vats/network/router.js:106]:
```suggestion
    route !== undefined || assert.fail(X`No registered router for ${localAddr}`, TypeError);
```

File: packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js [hunk 7]
```diff
@@ -398,7 +391,7 @@ export function buildRootObject(vatPowers, _vatParameters, baggage) {
     // reject unknown options
     const unknown = Object.keys(rest).join(',');
     if (unknown) {
-      assert.fail(`CreateVatOptions: unknown options ${unknown}`);
+      Fail`CreateVatOptions: unknown options ${q(unknown)}`;
```
Comment (gibson042) [inline packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js:380]: I'm going to trust you on these `q(…)` introductions.

**Review by gibson042 — APPROVED** [review]
Is similar work needed in [endo](https://github.com/endojs/endo)?

File: packages/SwingSet/src/devices/plugin/device-plugin.js (hunk 1 above)
Comment (FUDCo) [reply packages/SwingSet/src/devices/plugin/device-plugin.js:118]: All those `TypeErrors` were historical baggage, and this just gets rid of them.

File: packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js (hunk 7 above)
Comment (FUDCo) [reply packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js:380]: I'm pretty sure @erights will dispute this (and it's not worth fighting about) but I'd change the default to not censor and instead have something like a c(...) function to censor.   IMHO the default censorship of strings has never provided much value and has cost a lot in terms of debugging.  Another minor thing that's disruptive is that `q` outputs its arg in quotation marks, which breaks tests and also inhibits one's ability to control the format of output (at some point it might be useful to add something that performs the uncensoring mission of `q` but doesn't insert the quote characters, but it's not the least bit pressing).
