### PR TITLE
fix npm registry flake

### LINKED ISSUE #9909: NPM Registry Flake
In CI, when running integration tests, the step that sets up a local NPM registry occasionally fails. This issue occurs during our integration tests, which utilize a matrix strategy to execute across `Yarn`, `npm`, and `npx`. Our packages are published using [`Verdaccio`](https://verdaccio.org/) with a `dist-tag` of `ci`. We use this `dist-tag` to set up `agoric-cli` with `npm`, `npx`, and `Yarn` before running the `yarn integration test` command.

The script that tends to fail, [`scripts/registry.sh`](https://github.com/Agoric/agoric-sdk/blob/bef1be9b4fd16286ae5ca59a7d8812a775f7c6fe/scripts/registry.sh), is mainly designed to set up and run a local npm registry using `Verdaccio`, configure `npm` and `Yarn` to use it. 

https://github.com/Agoric/agoric-sdk/actions/runs/10361707252/job/28682520908?pr=9253
https://github.com/Agoric/agoric-sdk/actions/runs/10361707252/job/28682521191?pr=9253

# Possible Solutions
To address this issue, we could consider the following options:

- **Run yarn cache clean before publishing a package.** 
This can help clear any potential cache issues that might be causing the failures. More details can be found [here](https://stackoverflow.com/questions/55323656/error-command-failed-with-exit-code-1-when-i-try-to-run-yarn).

- **Add a retry mechanism.**
Implementing a retry mechanism could help mitigate transient failures and is a relatively safe and easy-to-implement option.

- **Try bumping versions of Lerna.**
There have been discussions around similar issues with Lerna, and bumping the versions might resolve the problem. For more details, see the [Lerna GitHub issue](https://github.com/lerna/lerna/issues/3570).

Given that this issue occurs occasionally, I am currently opting for the retry mechanism because it seems like a safe bet.

### PR DESCRIPTION
**Pull request by rabi-siddique**
closes #9909

### CODE REVIEW

**Review by frazarshad — APPROVED** [review]

**Review by michaelfig — CHANGES_REQUESTED** [review]
See https://github.com/Agoric/agoric-sdk/issues/9909#issuecomment-2297078874 for an approach that I believe would converge more rapidly on a successful outcome.

File: scripts/registry.sh [hunk 1]
```diff
@@ -91,6 +90,18 @@ publish() {
       | (popd > /dev/null && git hash-object -w --stdin))
 
     git commit -am "chore: update versions"
+
+    while ! yarn lerna publish from-package \
+      --dist-tag="$DISTTAG" --no-git-reset --no-verify-access --yes; do
+      echo 1>&2 "Retrying publish..."
+      sleep 5
+    done
+
```
Comment (Muneeb147) [inline scripts/registry.sh:99]: @rabi-siddique Have we tested it with multiple re-triggering of job? Did we see any improvement?
Can check logs if we actually see `Retrying publish...` in stderr.

Comment (rabi-siddique) [reply scripts/registry.sh:99]: After implementing this change, I haven’t experienced any flakiness or failures in the `Start local NPM registry` step throughout all the testing I’ve done so far in the integration tests workflow.

I did encounter an instance of `Retrying publish...` during a workflow run, but the step did not fail, and `yarn lerna publish` was successfully executed again.

Comment (Muneeb147) [reply scripts/registry.sh:99]: Sounds good 👍

**Review by Muneeb147 — APPROVED** [review]

**Review by michaelfig — APPROVED** [review]
