### PR TITLE
fix(address-hooks): version robustness and hardening

### LINKED ISSUE #10681: Address Hooks are misclassified if versions don't match
The Address Hooks implementation should not pass through hooked addresses with a mismatched version nibble as if they were not hooked. Instead, such addresses should be rejected for using an unsupported version, allowing us to introduce such functionality in the future.

_Originally posted by @gibson042 in https://github.com/Agoric/agoric-sdk/pull/10613#pullrequestreview-2493921581_

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #10681

## Description

Be more robust for Address Hook version compatibility: return an error if the magic bytes match but the version number is unsupported.  If the magic bytes don't match, it is not an address hook, so pass through the specimen as the `baseAddress` with empty `hookData`.

Also, `harden` the exports and returned objects if running under HardenedJS.

### Security Considerations

Stronger Address Hook classification helps prevent accidental collisions.  Hardened return objects and exported functions have fewer mutability concerns.

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

Some unhappy-path testing has been added to verify at least these issues have been addressed.

### Upgrade Considerations

n/a

### CODE REVIEW

**Review by 0xpatrickdev — APPROVED** [review]
The hardening and null prototype changes LGTM. I'll let @gibson042 review the versioning changes.

If convenient, consider adding a @throws annotation to `decodeAddressHook` like https://github.com/Agoric/agoric-sdk/pull/10682/commits/b6d20f73fd7cf3fd99f0ffa688da332b0526927b. If not, I'll include it in a PR I'm updating to depend on this.

File: golang/cosmos/types/address_hooks.go [hunk 1]
```diff
@@ -25,7 +25,7 @@ const (
 
 // AddressHookMagic is a magic byte prefix that identifies a hooked address.
 // Chosen to make bech32 address hooks that look like "agoric10rch..."
-var AddressHookMagic = []byte{0x78, 0xf1, 0x70 | AddressHookVersion}
+var AddressHookMagic = []byte{0x78, 0xf1, 0x70 /* | AddressHookVersion */}
```
Comment (gibson042) [inline golang/cosmos/types/address_hooks.go]: Suggestion: rename to something AddressHookBytePrefix.

File: packages/cosmic-proto/src/address-hooks.js [hunk 2]
```diff
@@ -204,10 +222,21 @@ export const splitHookedAddressUnsafe = (
...
+      version = maybeMagicByte & 0x0f;
+      maybeMagicByte &= 0xf0;
     }
+    if (maybeMagicByte !== ADDRESS_HOOK_MAGIC[i]) {
+      return harden({ baseAddress: specimen, hookData: new Uint8Array() });
+    }
+  }
+
+  if (version !== ADDRESS_HOOK_VERSION) {
+    return `Unsupported address hook version ${version}`;
```
Comment (gibson042) [inline packages/cosmic-proto/src/address-hooks.js]: I didn't get to this function before, but it's bizarre for it to return strings rather than throw exceptions. Please document the reason (or just eliminate the need by e.g. merging it into `splitHookedAddress`).

...and even if it is important to return rather than throw, consider future-proofing by returning a composite `{ baseAddress, hookData } | { error }` record.

**Review by gibson042 — APPROVED** [review]
Thanks!

File: packages/cosmic-proto/src/address-hooks.js (hunk 2 above)
Comment (michaelfig) [reply packages/cosmic-proto/src/address-hooks.js]: > it's bizarre

Indeed.  It's the style that the `bech32` package was written in, and it rubbed off on me. :P  Time to clean up that muck.
