### PR TITLE
fix(vaultFactory): don't prevent repayment based on DebtLimit

### LINKED ISSUE #9837: Inter Protocol vaults should allow adjustments that don't increase debt when mint limit <= debt outstanding
## Describe the bug
Inter Protocol vaults have per-collateral global mint limits that prevent new IST from being minted beyond that threshold.

These mint limits can be adjusted by the Economic Committee, independent of the amount of IST that has been minted against that collateral already

In scenarios where the mint limit is adjusted to be *below* the debt outstanding (even to zero), users *should* be able to make adjustments to their vaults which do not increase debt outstanding.  For example, they should be able to repay debt, add collateral, and/or withdraw collateral (subject to collateralization ratio constraints for the last).

This is not occurring.  The EC recently reduced mint limits for stOSMO vaults below the IST debt outstanding, and now users with stOSMO vaults are prevented from adjusting them at all.  Users attempting to avoid liquidation are stuck.

## To Reproduce
1. Create a vault for a specific collateral type
2. Use EC powers to vote to reduce the mint limit below the currently minted IST debt for that specific collateral type
3. Attempt to adjust your vault (repay IST, add collateral, or any other type of adjustment)

Note that in production, you will not have control of #2 and therefore will need to have an existing stOSMO vault open.

## Expected behavior
When mint limit is <= current debt outstanding, Vault Manager should prevent *new* minting of IST but should allow all other vault adjustments

User should be able to:
* Repay debt
* Add collateral
* Withdraw collateral (subject to collateralization ratio constraints)

## Platform Environment
Mainnet 

## Additional context
Error found by user:
Offer failed: Error: Minting {"brand":"[Alleged: IST brand]","value":"[0n]"} past {"brand":"[Alleged: IST brand]","value":"[490607974495n]"} would hit total debt limit {"brand":"[Alleged: IST brand]","value":"[490000000000n]"}

### PR DESCRIPTION
**Pull request by dckc**
closes: #9837

## Description

DebtLimit should not impact a vault owner's ability to repay, so refine `checkDebtLimit` to succeed regardless of `debtLimit` if `toMint` is empty.

### Security / Scaling Considerations

none

### Testing Considerations

straightforward unit test that failed before the fix

### Upgrade / Documentation Considerations

Straightforward upgrade; no state changes. See:
 - #9887

This fix should be cited in release notes.

### CODE REVIEW

File: packages/inter-protocol/src/vaultFactory/vaultManager.js [hunk 1]
```diff
@@ -867,11 +867,13 @@ export const prepareVaultManagerKit = (
           const { state } = this;
           const { collateralBrand, totalDebt } = state;
 
-          checkDebtLimit(
-            factoryPowers.getGovernedParams(collateralBrand).getDebtLimit(),
-            totalDebt,
-            toMint,
-          );
+          if (!AmountMath.isEmpty(toMint)) {
```
Comment (turadg) [inline packages/inter-protocol/src/vaultFactory/vaultManager.js]: I think this is the job of `checkDebtLimit` itself. It's doc says,
```
 * @param {Amount<'nat'>} toMint
 * @throws if minting would exceed total debt
```
If toMint is empty then it shouldn't throw. 

So instead of this change I suggest updating that helper function and adding whatever docs would have helped to make that the clear solution. This will also require a change to `contractSupport.test.js`. That will unit test this logic, though it's certainly helpful to also have the integration test you make in `vault-collaterlization-test.js`.

**Review by turadg — APPROVED** [review]

**Review by Chris-Hibbert — APPROVED** [review]
