### PR TITLE
No fake baggage

### LINKED ISSUE #7578: Audit `makeScalarBigMapStore` usages for pseudo baggage
## What is the Problem Being Solved?

kind handles should be reachable from the root baggage so kinds can be redefined in vat upgrades (See https://github.com/Agoric/agoric-sdk/issues/7577). If a vat fails to redefine kinds , it will fail its upgrade. We should audit all usages of `makeScalarBigMapStore` to ensure these collections are not used to store kind handles, unless themselves added to a durable object reachable from baggage.

One particularly worrisome case is currently `makeIssuerKit`:
https://github.com/Agoric/agoric-sdk/blob/3a983388191ad2f157e79022ab48f2f86fc7e368/packages/ERTP/src/issuerKit.js#L185-L201

## Description of the Design

Manual audit until a more low level enforcement mechanism is added (#7577)

## Security Considerations

Must be sure these usages are sound to avoid future upgrade failures.

## Scaling Considerations

None

## Test Plan

If a case is found, understand why it wasn't detected by upgrade tests, and modify upgrade tests to increase coverage if applicable.

### LINKED ISSUE #7651: Zoe is not null-upgradable
## Describe the bug

While working on #7578 I refactored the tests using a `vat-zoe.js` to rely instead on the production Zoe vat. This uncovered an issue where the test exercising Zoe upgrade actually used a different implementation than the production one. The tested implementation is upgradable, but does not implement all the semantics of the production Zoe vat. The production Zoe vat however fails the null upgrade that the test performs, indicating it doesn't rewire the kinds correctly.

## To Reproduce
- Cherry pick https://github.com/Agoric/agoric-sdk/commit/bb3681d5f526f4999137f6852f05fc54d443451c or use the WIP branch for PR #7636
- Observe test now marked as failing: `cd packages/zoe && yarn test test/swingsetTests/zoe/test-zoe-upgrade.js`

## Expected behavior
Working Zoe upgrade test

## Additional context
In the production Zoe vat, `makeZoeKit` seem to be called only during `buildZoe` which is not called during upgrades, and thus fails to rewire kinds during `buildRootObject`.

However I couldn't easily fix the production Zoe vat since it seems the `makeZoeKit` args rely on data only available during `buildZoe`, in particular `feeIssuerConfig` and `zcfBundleName`.

## Screenshots
```
error during vat dispatch() of startVat,[object Object] (Error#1)
Error#1: defineDurableKind not called for tags: [ZDEFAULT brand,ZDEFAULT payment,ZDEFAULT Purse,ZDEFAULT issuer,ZDEFAULT mint,FeeMint,Zoe Invitation brand,Zoe Invitation payment,Zoe Invitation Purse,Zoe Invitation issuer,Zoe Invitation mint,InstanceAdmin,BundleIDInstallation,BundleInstallation,InstallationStorage,ZoeMint,InstanceStorageManager,InstanceRecord,ZoeStorageManager,InstanceHandle,zoe Seat publisher,ZoeSeatKit,SeatHandle,instanceAdmin,zoeInstanceAdmin,emptyCreatorFacet,emptyPublicFacet,adminFacet,ZoeService]
```

### PR DESCRIPTION
**Pull request by mhofman**
closes: #7578
closes: #7627
closes: #7651

Best reviewed commit-by-commit

## Description

This is the result of a manual audit to track down and remove places where a fake baggage is created, or at least to explicitly contain it to tests, tools and demo contracts

In particular this PR does the following:
- [refactor] Rename `makeBoard` to `makeFakeBoard`. I realized after the fact this was the same as #7627, but is slightly more complete and passes tests
- [refactor] Introduce a `makeDurableZoeKit` which required a baggage, and deprecate `makeZoeKit` (with the removed options to specify a baggage). I also introduced a new `makeZoeForTest` tool and wrote a shared `setupZoeForTest` tool that creates a fake baggage, reducing the uses of `makeDurableZoeKit` to this test helper and the production `vat-zoe`
- [refactor] Removed `vat-zoe` implementations used in tests and use the production one instead.
- [fix] Make Zoe vat upgradable by stashing `buildZoe` params in the baggage. Fixes #7651 
- [fix] Remove the `quoteMint` from priceAuthority's `privateArgs`, and unconditionally create a durable issuer kit for it.
- [chore] marked the remaining usages of `makeIssueKit` as not for production

### Security Considerations

None

### Scaling Considerations

None

### Documentation Considerations

None

### Testing Considerations

There is a new test tool for Zoe, which should be used instead of `makeZoeKit`, which is now deprecated.

Because of the `makeFakeBoard` rename, the following PR is required to land in documentation repo:
- https://github.com/Agoric/documentation/pull/800

```
#documentation-branch: mhofman/7578-fix-make-zoe
```

### CODE REVIEW

File: packages/deploy-script-support/test/unitTests/test-install.js [hunk 1]
```diff
@@ -9,10 +9,15 @@ import { resolve as importMetaResolve } from 'import-meta-resolve';
 
 import '../../exported.js';
 
+// eslint-disable-next-line import/no-extraneous-dependencies
```
Comment (turadg) [inline packages/deploy-script-support/test/unitTests/test-install.js]: if it's a dep please include it in package.json. but I don't think it needs to be a dep…

File: packages/deploy-script-support/test/unitTests/test-install.js [hunk 2]
```diff
@@ -9,10 +9,15 @@ import { resolve as importMetaResolve } from 'import-meta-resolve';
...
+import { makeScalarBigMapStore } from '@agoric/vat-data';
 import { makeInstall } from '../../src/install.js';
 
 test('install', async t => {
-  const { zoeService: zoe } = makeZoeKit(fakeVatAdmin);
+  const { zoeService: zoe } = makeZoeKit(
+    makeScalarBigMapStore('zoe baggage', { durable: true }),
+    fakeVatAdmin,
+  );
```
Comment (turadg) [inline packages/deploy-script-support/test/unitTests/test-install.js]: this is common enough that there should be a single function to do it. perhaps `makeZoeKitForTest` in a `tools` export. Then most of these changes would be four chars at the call site (and an extra import, but on a package that's already a dependency).

Moreover, Zoe's baggage should always be durable, so the caller shouldn't be allowed to pass in any MapStore.

File: packages/zoe/src/zoeService/installationStorage.js [hunk 3]
```diff
@@ -20,12 +19,9 @@ const { Fail, quote: q } = assert;
 
 /**
  * @param {GetBundleCapForID} getBundleCapForID
- * @param {Baggage} [zoeBaggage] optional only so it can be omitted in tests
```
Comment (turadg) [inline packages/zoe/src/zoeService/installationStorage.js:23]: +1 to `src` not encoding defaults for tests. maybe worth putting in our coding guidelines.

File: packages/zoe/src/contracts/priceAggregator.js [hunk 4]
```diff
@@ -62,8 +63,9 @@ const priceDescriptionFromQuote = quote => quote.quoteAmount.value[0];
  * quoteMint?: ERef<Mint<'set'>>,
  * storageNode: ERef<StorageNode>,
  * }} privateArgs
+ * @param {import('@agoric/vat-data').Baggage} baggage
  */
-const start = async (zcf, privateArgs) => {
+const start = async (zcf, privateArgs, baggage) => {
```
Comment (turadg) [inline packages/zoe/src/contracts/priceAggregator.js]: please leave this contract alone because it's just an example, not part of production
https://github.com/Agoric/agoric-sdk/blob/bb30947461eae614ff5e4fac3a9e21b927efe3f6/packages/zoe/src/contracts/priceAggregator.js#L47-L52

It is confusing that `zoe/src/contracts` has examples and production contracts. We have deferred cleaning up package factoring https://github.com/Agoric/agoric-sdk/issues/4645

File: packages/deploy-script-support/test/unitTests/test-install.js [hunk 5]
```diff
@@ -3,16 +3,21 @@ import { test } from '@agoric/zoe/tools/prepare-test-env-ava.js';
...
 import fakeVatAdmin from '@agoric/zoe/tools/fakeVatAdmin.js';
-import { makeBoard } from '@agoric/vats/src/lib-board.js';
+import { makeFakeBoard } from '@agoric/vats/tools/board-utils.js';
 import bundleSource from '@endo/bundle-source';
 import { resolve as importMetaResolve } from 'import-meta-resolve';
 
 import '../../exported.js';
 
+// eslint-disable-next-line import/no-extraneous-dependencies
+import { makeScalarBigMapStore } from '@agoric/vat-data';
```
Comment (gibson042) [inline packages/deploy-script-support/test/unitTests/test-install.js]: Why not add `@agoric/vat-data` to devDependencies?

File: packages/zoe/src/contracts/scaledPriceAuthority.js [hunk 6]
```diff
@@ -34,9 +33,11 @@ import { makePriceAuthorityTransform } from '../contractSupport/priceAuthorityTr
  */
 export const prepare = async (
   zcf,
-  { quoteMint = makeIssuerKit('quote', AssetKind.SET).mint } = {},
+  { quoteMint: providedQuoteMint } = {},
```
Comment (turadg) [inline packages/zoe/src/contracts/scaledPriceAuthority.js]: I don't see anywhere that this privateArg is provided. I think we're better off excising the privateArgs param. Please confirm @dckc .

File: packages/zoe/src/contractSupport/priceAuthorityQuoteMint.js [hunk 7]
```diff
@@ -0,0 +1,52 @@
...
+  prepareIssuerKit,
+} from '@agoric/ertp';
+import { makeScalarBigMapStore } from '@agoric/vat-data';
+
+/**
+ *
+ * @param {import('@agoric/vat-data').Baggage} baggage
+ * @param {ERef<Mint<'set'>>} [providedQuoteMint]
+ */
+export const prepareQuoteMint = (baggage, providedQuoteMint) => {
```
Comment (turadg) [inline packages/zoe/src/contractSupport/priceAuthorityQuoteMint.js]: when we drop the privateArg (see below) I think this will be better factored as a `provideQuoteMint`.

File: packages/vats/src/core/chain-behaviors.js [hunk 8]
```diff
@@ -460,6 +460,7 @@ export const publishAgoricNames = async (
   const marshaller = E(board).getPublishingMarshaller();
 
   // XXX will fail upon restart, but so would the makeStoredPublishKit this is replacing
+  // XXX is that ok?
```
Comment (turadg) [inline packages/vats/src/core/chain-behaviors.js]: yes, there's only one production use of `makeStoredPublishKit` which is  [vote outcomes](https://github.com/Agoric/agoric-sdk/blob/bb30947461eae614ff5e4fac3a9e21b927efe3f6/packages/governance/src/committee.js#L142-L147) and we've elected to defer durability of governance.

File: packages/zoe/src/contracts/mintAndSellNFT.js [hunk 9]
```diff
@@ -29,6 +29,7 @@ import { assert } from '@agoric/assert';
 const start = zcf => {
   const { tokenName = 'token' } = zcf.getTerms();
   // Create the internal token mint
+  // makeIssuerKit fails upgrade, safe because demo only?
```
Comment (turadg) [inline packages/zoe/src/contracts/mintAndSellNFT.js]: in this case yes

File: packages/vats/src/vat-mints.js [hunk 10]
```diff
@@ -39,6 +39,7 @@ export function buildRootObject() {
      * @param  {[AssetKind?, DisplayInfo?]} issuerArgs
      */
     makeMintAndIssuer: (issuerNameSingular, ...issuerArgs) => {
+      // makeIssuerKit fails upgrade, safe because demo only?
```
Comment (turadg) [inline packages/vats/src/vat-mints.js]: I'm not sure. I see this in demo and devnet configs but also https://github.com/Agoric/agoric-sdk/blob/bb30947461eae614ff5e4fac3a9e21b927efe3f6/packages/vats/decentral-core-config.json#L35-L38

@michaelfig ?

File: packages/inter-protocol/test/psm/setupPsm.js [hunk 11]
```diff
@@ -26,11 +26,16 @@ const charterRoot = './src/econCommitteeCharter.js'; // package relative
...
   const { makeFar } = makeLoopback('zoeTest');
   const { zoeService, feeMintAccess } = await makeFar(
-    makeZoeKit(makeFakeVatAdmin(() => {}).admin, undefined, {
-      name: Stable.symbol,
-      assetKind: Stable.assetKind,
-      displayInfo: Stable.displayInfo,
-    }),
+    makeZoeKit(
+      makeScalarBigMapStore('zoe baggage', { durable: true }),
+      makeFakeVatAdmin(() => {}).admin,
```
Comment (gibson042) [inline packages/inter-protocol/test/psm/setupPsm.js]: Nit: we could probably clarify the purpose of this empty function by naming it something like `ignoreTestContext` (and likewise in packages/smart-wallet/test/supports.js).

**Review by gibson042 — COMMENTED** [review]
These look like nice improvements!

File: packages/zoe/src/contracts/priceAggregator.js (hunk 4 above)
Comment (dckc) [reply packages/zoe/src/contracts/priceAggregator.js]: also:
 - #1656

File: packages/zoe/src/contracts/scaledPriceAuthority.js (hunk 6 above)
Comment (dckc) [reply packages/zoe/src/contracts/scaledPriceAuthority.js]: yes, if it were important we would/should have had a test.

@michaelfig if you know something we haven't considered, please let us know.

File: packages/vats/src/vat-mints.js (hunk 10 above)
Comment (michaelfig) [reply packages/vats/src/vat-mints.js]: `decentral-core-config.json` is also non-production.  See the `$comment` at the top.

Comment (dckc) [reply packages/vats/src/vat-mints.js]: vat-mints is very much demo-only. It has the poison pill that is enforced by static analysis in a test:

```
import { notForProductionUse } from '@agoric/internal/src/magic-cookie-test-only.js';
```

https://github.com/Agoric/agoric-sdk/blob/09b993a22a1618fc6c0e3bddb1d09b6fa4e78de5/packages/vats/test/test-boot-config.js#L143

File: packages/deploy-script-support/test/unitTests/test-install.js (hunk 2 above)
Comment (mhofman) [reply packages/deploy-script-support/test/unitTests/test-install.js]: I introduced a `makeZoeForTest`, `makeZoeKitForTest` and common `setupZoeForTest`, and refactored all the tests to use these new tools. Its was a big refactor, but I think it paid out!

File: packages/zoe/src/contracts/priceAggregator.js (hunk 4 above)
Comment (mhofman) [reply packages/zoe/src/contracts/priceAggregator.js]: Reverted, and annotated contract to be `notForProductionUse`

File: packages/zoe/src/contracts/scaledPriceAuthority.js (hunk 6 above)
Comment (mhofman) [reply packages/zoe/src/contracts/scaledPriceAuthority.js]: Removed

File: packages/vats/src/core/chain-behaviors.js (hunk 8 above)
Comment (mhofman) [reply packages/vats/src/core/chain-behaviors.js]: Updated with comment explaining why this is ok

File: packages/zoe/src/contracts/mintAndSellNFT.js (hunk 9 above)
Comment (mhofman) [reply packages/zoe/src/contracts/mintAndSellNFT.js]: marked contract as `notForProductionUse`

File: packages/vats/src/vat-mints.js (hunk 10 above)
Comment (mhofman) [reply packages/vats/src/vat-mints.js]: This `notForProductionUse` is pretty cool. I added it to the other zoe contracts with `makeIssuerKit` that are supposed to not end up in production.

File: packages/inter-protocol/test/psm/setupPsm.js (hunk 11 above)
Comment (mhofman) [reply packages/inter-protocol/test/psm/setupPsm.js]: The empty function was not needed in the first place. Gone in the refactor

**Comment by mhofman** [comment]
Once this is green, I will rebase and fix up the commits, and mark as ready for review.

**Comment by mhofman** [comment]
@turadg it looks like since I removed the optional `quoteMint` of the scaled price authority, the type of `privateArgs` becomes empty and allows assignment of an arg of type `string`. This would not be a problem except that your Zoe type tests use that contract to as an example, and the type checking of `privateArgs` now fails an expected error. This is likely a case where if we were running in strict type mode / no implicit any, it would be fine, but alas we're not. I'm not sure of the best way forward to fix that one. Is there another contract that can be used here in place?

```
Error: test/types.test-d.ts(50,5): error TS2578: Unused '@ts-expect-error' directive.
```

File: packages/deploy-script-support/test/unitTests/test-install.js (hunk 2 above)
Comment (turadg) [reply packages/deploy-script-support/test/unitTests/test-install.js]: Looks it to me!

**Comment by turadg** [comment]
> I'm not sure of the best way forward to fix that one.

It's there to test that the types are defined so we can just give a different invalid argument.
```js
  E(zoe).startInstance(
    scaledPriceInstallation,
    validIssuers,
    // @ts-expect-error includes an extra term
    { ...validTerms, extra: string },
  );
```

File: packages/vats/src/core/chain-behaviors.js [hunk 12]
```diff
@@ -460,6 +460,8 @@ export const publishAgoricNames = async (
   const marshaller = E(board).getPublishingMarshaller();
 
   // XXX will fail upon restart, but so would the makeStoredPublishKit this is replacing
+  // Since we expect the bootstrap vat to be replaced instead of upgraded this should be
```
Comment (turadg) [inline packages/vats/src/core/chain-behaviors.js:463]: ✏️

File: packages/zoe/src/contractSupport/priceAuthorityQuoteMint.js [hunk 13]
```diff
@@ -0,0 +1,34 @@
...
+import { makeScalarBigMapStore } from '@agoric/vat-data';
+
+/**
+ *
+ * @param {import('@agoric/vat-data').Baggage} baggage
+ */
+export const provideQuoteMint = baggage => {
+  /** @type {ERef<Mint<'set'>>} */
+  let baggageQuoteMint;
+  if (baggage.has(`quoteMintIssuerBaggage`)) {
```
Comment (turadg) [inline packages/zoe/src/contractSupport/priceAuthorityQuoteMint.js:15]: consider a const

**Review by turadg — APPROVED** [review]
LGTM. Thanks for the clean commits.

I left a separate comment on how to get types passing.

**Comment by mhofman** [comment]
> It's there to test that the types are defined so we can just give a different invalid argument.

That won't do because `privateArgs: object` now, which means it's equivalent to `any` in non strict TS mode....

**Review by turadg — APPROVED** [review]

**Review by Chris-Hibbert — APPROVED** [review]
LGTM
