### PR TITLE
7266 auction status

### LINKED ISSUE #7266: [CLI] Auction Status interface
## Describe the bug
As a bidding user, I want to list the remaining time left on an auction and the current price of the auction, so that I can best inform my bidding strategy.

## To Reproduce
1. Bid on some liquidating vaults
2. Unable to easily see other bids I'm competing with, or how long there is for an auction I have already bid on, or if my bid will currently win the auction at the end of the duration

## Expected behavior
A user can see if their bid is the current winning bid, the time remaining on the auction, and easily list in ranked order the other bids in competition

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #7266 

## Description

Write important data about the auction's status to chain storage.

### Security Considerations

None

### Scaling Considerations

Reduces load on the chain

### Documentation Considerations

Added Auction data to the README. (replacing obsolete AMM info)  I dunno where else it needs to be written up.

### Testing Considerations

New Tests.

### CODE REVIEW

File: packages/inter-protocol/src/auction/auctioneer.js [hunk 1]
```diff
@@ -384,10 +385,26 @@ export const start = async (zcf, privateArgs, baggage) => {
...
+  const makeAuctionPublishKit = prepareDurablePublishKit(
+    baggage,
+    'Auction publish kit',
+  );
+  /** @type {PublishKit<import('./scheduler.js').ScheduleNotification>} */
+  const { publisher: schedulePublisher, subscriber: scheduleSubscriber } =
+    makeAuctionPublishKit();
+
+  const scheduleNode = E(privateArgs.storageNode).makeChildNode('schedule');
+  pipeTopicToStorage(scheduleSubscriber, scheduleNode, privateArgs.marshaller);
```
Comment (turadg) [inline packages/inter-protocol/src/auction/auctioneer.js:408]: if there's a risk that this PR lands after https://github.com/Agoric/agoric-sdk/issues/7300 is done then please include a TODO comment here to remove `pipeTopicToStorage`

Comment (turadg) [inline packages/inter-protocol/src/auction/auctioneer.js:408]: if there's a risk that this PR lands after https://github.com/Agoric/agoric-sdk/issues/7300 is done then please include a TODO comment here to remove `pipeTopicToStorage`

File: packages/inter-protocol/src/auction/auctioneer.js [hunk 2]
```diff
@@ -499,8 +520,14 @@ export const start = async (zcf, privateArgs, baggage) => {
     },
   });
 
-  // @ts-expect-error types are correct. How to convince TS?
-  const scheduler = await makeScheduler(driver, timer, params, timerBrand);
+  const scheduler = await makeScheduler(
+    driver,
+    timer,
+    // @ts-expect-error types are correct. How to convince TS?
```
Comment (turadg) [inline packages/inter-protocol/src/auction/auctioneer.js:528]: glad to see the suppression more targeted. I'll take a look at this types after pushing this review.

File: packages/inter-protocol/src/auction/auctioneer.js [hunk 3]
```diff
@@ -569,6 +596,12 @@ export const start = async (zcf, privateArgs, baggage) => {
       getSchedules() {
         return E(scheduler).getSchedule();
       },
+      getScheduleUpdates() {
+        return scheduleSubscriber;
+      },
+      getBookDataUpdates(brand) {
+        return subscribers.get(brand);
+      },
```
Comment (turadg) [inline packages/inter-protocol/src/auction/auctioneer.js]: please use the `getPublicTopics` style which will aid documentation https://github.com/Agoric/agoric-sdk/blob/013fff8bdc7bb3e8fbecd6c06b59e065ed706e50/packages/inter-protocol/src/price/fluxAggregator.js#L312-L333

File: packages/inter-protocol/src/auction/scheduler.js [hunk 4]
```diff
@@ -116,17 +117,29 @@ export const computeRoundTiming = (params, baseTime) => {
...
  */
 
+/**
+ * @typedef {object} ScheduleNotification
+ *
+ * @property {Timestamp | undefined} activeStartTime start time of current
+ *    auction if auction is active
+ * @property {Timestamp | undefined} nextStartTime start time of next auction
+ * @property {Timestamp | undefined} nextDescendingStepTime if auction is
+ *    active we're not on the last step, when the next descending step will be
```
Comment (turadg) [inline packages/inter-protocol/src/auction/scheduler.js]: are there really 2^3 combinations of defined/undefined?   in particular, why can a notification be empty?

the possible values seem to depend on `auctionState` but not in a way that's clear to me. Please add some conditions or assertions in `publishSchedule` relating it to the state.

File: packages/inter-protocol/src/auction/scheduler.js [hunk 5]
```diff
@@ -182,65 +229,84 @@ export const makeScheduler = async (
...
+
+    if (schedule) {
+      publishSchedule(time);
+    }
   };
 
-  const scheduleRound = time => {
-    trace('nextRound', time);
+  // schedule the wakeups for the steps of this round
+  const scheduleSteps = now => {
```
Comment (turadg) [inline packages/inter-protocol/src/auction/scheduler.js]: thanks for making clear that the time passed in is "now" versus some future scheduled time.

please do the same for `clockTick = (time, schedule)` so that it can end with,
```js
    if (schedule) {
      publishSchedule(now);
    }
```

Comment (turadg) [reply packages/inter-protocol/src/auction/scheduler.js]: separately, passing around `now` feels like it leaves room for bugs. "now" is a shared truth.

WDYT of keeping `let now` in closure and just updating it whenever it changes? then each function can get its `now` from closure instead of params. If you do that, I think maybe the publishSchedule calls can get refactored to happen in fewer places.

File: packages/inter-protocol/src/auction/scheduler.js [hunk 6]
```diff
@@ -182,65 +229,84 @@ export const makeScheduler = async (
...
   // XXX manualTimer returns a bigint, not a timeRecord.
-  const now = TimeMath.toAbs(baseNow, timerBrand);
-  nextSchedule = computeRoundTiming(params, now);
-  scheduleNextRound(nextSchedule.startTime);
+  const baseNow = await E(timer).getCurrentTimestamp();
+  nextSchedule = computeRoundTiming(
+    params,
+    TimeMath.toAbs(baseNow, timerBrand),
+  );
+  const firstStart = TimeMath.subtractAbsRel(
```
Comment (turadg) [inline packages/inter-protocol/src/auction/scheduler.js:221]: this looks to be different from `baseNow`. why is `publishSchedule = now => {` taking an argument that isn't *now*?

File: packages/inter-protocol/test/auction/test-auctionBook.js [hunk 7]
```diff
@@ -85,7 +94,13 @@ test('simple addOffer', async t => {
   const initialPrice = makeRatioFromAmounts(moola(20n), simoleans(100n));
   const pa = buildManualPriceAuthority(initialPrice);
 
-  const book = await makeAuctionBook(moolaKit.brand, simoleanKit.brand, pa);
+  const publishKit = makePublishKit();
```
Comment (turadg) [inline packages/inter-protocol/test/auction/test-auctionBook.js]: that the whole kit is kept makes me look for how the subscriber is used, but it isn't. please take only what you need. POLA-ish.

```suggestion
  const { publisher }  = makePublishKit();
```

File: packages/inter-protocol/test/auction/test-auctionContract.js [hunk 8]
```diff
@@ -261,6 +270,16 @@ const makeAuctionDriver = async (t, customTerms, params = defaultParams) => {
     getTimerService() {
       return timerService;
     },
+    async getScheduleTracker(t) {
```
Comment (turadg) [inline packages/inter-protocol/test/auction/test-auctionContract.js]: glad the subscribtionTracker was usable here.

note: this function synchronously returns a promise so no need for `async`

File: packages/inter-protocol/src/auction/auctionBook.js [hunk 9]
```diff
@@ -89,6 +89,40 @@ export const makeBidSpecShape = (currencyBrand, collateralBrand) => {
 
 /** @typedef {import('@agoric/vat-data').Baggage} Baggage */
 
+/**
+ * @typedef {object} PriceLevel
```
Comment (turadg) [inline packages/inter-protocol/src/auction/auctionBook.js]: surprised we don't have this type already. closest is `PriceDescription` but that has more.

consider putting this in the `zoe/tools/types-ambient.js` since it makes sense outside of auctions

File: packages/inter-protocol/src/auction/auctionBook.js [hunk 10]
```diff
@@ -89,6 +89,40 @@ export const makeBidSpecShape = (currencyBrand, collateralBrand) => {
...
+ * @property {Amount<'nat'>} amountIn
+ * The amount supplied to a trade
+ * @property {Amount<'nat'>} amountOut
+ * The quoted result of trading `amountIn`
+ */
+
+/**
+ * @typedef {object} BookDataNotification
+ *
+ * @property {PriceQuote | null} startPrice identifies the priceAuthority and price
```
Comment (turadg) [inline packages/inter-protocol/src/auction/auctionBook.js]: a little hard to read. consider column aligning like https://github.com/Agoric/agoric-sdk/blob/c93516ed1f45452d2286dccc75b08befeef6e4de/packages/inter-protocol/src/vaultFactory/vaultManager.js#L78-L81

File: packages/inter-protocol/src/auction/auctionBook.js [hunk 11]
```diff
@@ -89,6 +89,40 @@ export const makeBidSpecShape = (currencyBrand, collateralBrand) => {
...
+ * @property {Amount<'nat'> | null} remainingProceedsGoal The remainder of the proceeds the sellers were targeting to raise
+ * @property {Amount<'nat'> | undefined} proceedsRaised The proceeds raised so far in the auction
+ * @property {Amount<'nat'>} startCollateral How much collateral was available
+ *    for sale at the start. (If more is deposited later, it'll be added in.)
+ * @property {Amount<'nat'> | undefined} collateralAvailable The amount of collateral remaining
+ */
+
+/*
+ * If stateVariable is unset, set it to amount, otherwise add amount
+ */
```
Comment (turadg) [inline packages/inter-protocol/src/auction/auctionBook.js]: `addAmountToState` sounds like it's adding a property to the state. this is _increasing_ an amount stored in state. The laziness of setting it if it isn't set seems unnecessarily dynamic. Why not set them to empty amounts during initState? 

Then you don't even need this function. The two places it's called can be like,
```js
state.remainingProceedsGoal = AmountMath.add(state.remainingProceedsGoal, incrementToGoal);
```
which is statically analyzable. If you really want to avoid repeating the state property we could have a helper like,
```js
increaseAmount(state, 'remainingProceedsGoal', incrementToGoal);
```
… and have the type checker verify that the second arg is a property in the first arg, but I think that still breaks things like "find all references".  

Kind of a general challenge with immutable data when you want to change it without repeating the name of the thing being changed.

File: packages/inter-protocol/src/auction/auctionBook.js [hunk 12]
```diff
@@ -528,14 +663,21 @@ export const prepareAuctionBook = (baggage, zcf) => {
...
           priceBook.exitAllSeats();
           scaledBidBook.exitAllSeats();
         },
+        endAuction() {
+          const { state } = this;
+
+          state.startCollateral = null;
+          state.lockedPriceForRound = null;
+          state.curAuctionPrice = null;
+          state.remainingProceedsGoal = null;
```
Comment (turadg) [inline packages/inter-protocol/src/auction/auctionBook.js]: that the nullness of these four values has to be synchronized worries me. if they're really non or not at the same time, wouldn't it be better to bundle them in an object? then "between auctions" that single object ref is null and otherwise it's populated in a verifiable "during auction" shape

File: packages/inter-protocol/src/auction/auctioneer.js (hunk 1 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/auctioneer.js:408]: done

File: packages/inter-protocol/src/auction/auctioneer.js (hunk 3 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/auctioneer.js]: How should this represent the sub-nodes for each book? They're retrievable with `getBookDataUpdates(brand)`.

File: packages/inter-protocol/src/auction/scheduler.js (hunk 4 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/scheduler.js]: I can initialize nextStartTime in its declaration, so only activeStartTime can be undefined.

File: packages/inter-protocol/src/auction/scheduler.js (hunk 5 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/scheduler.js]: Done.   I didn't see a way to reduce calls on `publishSchedule`.

File: packages/inter-protocol/src/auction/scheduler.js (hunk 6 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/scheduler.js:221]: After making `now` shared, `firstStart` is used for making the schedule, and publish doesn't need a parameter.

```
  scheduleNextRound(firstStart);
  publishSchedule();
```

File: packages/inter-protocol/test/auction/test-auctionBook.js (hunk 7 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/test/auction/test-auctionBook.js]: done

File: packages/inter-protocol/test/auction/test-auctionContract.js (hunk 8 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/test/auction/test-auctionContract.js]: done

File: packages/inter-protocol/src/auction/scheduler.js [hunk 13]
```diff
@@ -147,18 +147,33 @@ export const makeScheduler = async (
...
-   * Next should always be defined after initialization unless it's paused
-   *
-   * @type {Schedule | undefined}
-   */
-  let nextSchedule;
+
+  /** @returns {Promise<{now:Timestamp, nextSchedule: Schedule}>} */
+  const initializeNextSchedule = async () => {
+    return E.when(
+      // XXX manualTimer returns a bigint, not a timeRecord.
```
Comment (turadg) [inline packages/inter-protocol/src/auction/scheduler.js:77]: exploration into burning this debt https://github.com/Agoric/agoric-sdk/pull/7348

File: packages/inter-protocol/src/auction/scheduler.js [hunk 14]
```diff
@@ -147,18 +147,33 @@ export const makeScheduler = async (
...
+          params,
+          TimeMath.toAbs(now, timerBrand),
+        );
+        return { now, nextSchedule };
+      },
+    );
+  };
+  let { now, nextSchedule } = await initializeNextSchedule();
+  const setTimeMonotonically = time => {
+    TimeMath.compareAbs(time, now) >= 0 || Fail`Time only moves forward`;
```
Comment (turadg) [inline packages/inter-protocol/src/auction/scheduler.js:90]: bold claim!

File: packages/inter-protocol/src/auction/scheduler.js [hunk 15]
```diff
@@ -116,42 +117,103 @@ export const computeRoundTiming = (params, baseTime) => {
...
    */
   let liveSchedule;
-  /**
-   * Next should always be defined after initialization unless it's paused
-   *
-   * @type {Schedule | undefined}
-   */
-  let nextSchedule;
+
+  /** @returns {Promise<{now:Timestamp, nextSchedule: Schedule}>} */
```
Comment (turadg) [inline packages/inter-protocol/src/auction/scheduler.js]: nit: space around object members
```suggestion
  /** @returns {Promise<{ now: Timestamp, nextSchedule: Schedule }>} */
```

File: packages/inter-protocol/src/auction/scheduler.js [hunk 16]
```diff
@@ -116,42 +117,103 @@ export const computeRoundTiming = (params, baseTime) => {
...
+    now = time;
+  };
+
   const stepCancelToken = makeCancelToken();
 
   /** @type {typeof AuctionState[keyof typeof AuctionState]} */
   let auctionState = AuctionState.WAITING;
 
+  const publishSchedule = () => {
+    const calcNextStep = () => {
```
Comment (turadg) [inline packages/inter-protocol/src/auction/scheduler.js]: this function should move to the left so it's not redefined whenever `publicSchedule()`.

with less context it could help for the name to be more specific. e.g. `calcNextDescendingStepTime()`.

though consider moving it into another module as a function that takes `liveSchedule` and `nextSchedule`. Easier to test that way. Actually, _please_ move it out and have a unit test for it.

File: packages/inter-protocol/src/auction/scheduler.js (hunk 6 above)
Comment (turadg) [reply packages/inter-protocol/src/auction/scheduler.js:221]: Nice. So now `publishSchedule` is called three places:
1. end of `clockTick`
2. after this scheduleNextRound()
3. after wake's `startAuction` which is the one other call to `scheduleNextRound()`.

Looking through the cases I think this can be simplified to two sites:
1. end of `clockTick`
2. end of `scheduleNextRound`

That makes more sense to me. Documenting that on `publishSchedule` would help too:
"To be called whenever the clock ticks or a next round is scheduled"

File: packages/inter-protocol/src/auction/auctionBook.js (hunk 11 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/auctionBook.js]: A couple of these values distinguish between empty and null.

File: packages/inter-protocol/src/auction/auctionBook.js (hunk 9 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/auctionBook.js]: done

File: packages/inter-protocol/src/auction/scheduler.js (hunk 15 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/scheduler.js]: done

File: packages/inter-protocol/src/auction/scheduler.js (hunk 5 above)
Comment (turadg) [reply packages/inter-protocol/src/auction/scheduler.js]: GH had this comment hidden so I didn't it before writing https://github.com/Agoric/agoric-sdk/pull/7339#discussion_r1160279248

I'll resolve this thread.

File: packages/inter-protocol/src/auction/auctioneer.js (hunk 3 above)
Comment (turadg) [reply packages/inter-protocol/src/auction/auctioneer.js]: Hmm. They shouldn't be properties of this object because it's an open set. My first thought is to have an object for each book with `getPublicTopics` as a call on it, but it looks like "book" is a concept internal to the auctioneer. You could have `getPublicTopics` take an optional brand which would give you the topics for that brand book instead of the whole auctioneer.

It's worth considering though having a public facet on the AuctionBook exo and having an Auctioneer method to get one of those by brand.

Either way, I think the book's subscriber is a concern of the book and should be within its own Exo object. I.e. delete the `subscribers` map and get the entry from the book exo. That will also simplify upgrade.

File: packages/inter-protocol/src/auction/scheduler.js (hunk 16 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/scheduler.js]: renamed and moved with computeRoundTiming to new module.

File: packages/inter-protocol/src/auction/scheduler.js (hunk 6 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/scheduler.js:221]: done

File: packages/inter-protocol/src/auction/auctioneer.js (hunk 3 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/auctioneer.js]: Done. Thanks for the suggestion. That seems cleaner.

File: packages/inter-protocol/src/auction/auctionBook.js (hunk 12 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/auctionBook.js]: They're not as parallel as they looked. After looking more closely, 
 * startCollateral will never be null. it's reset to empty at the end of an auction, and increases when `addAssets()` is called
 * `startProceedsGoal` is reset at the end of an auction. it increases when `addAssets()` is called with a goal.
 * `lockedPriceForRound` is assigned a value to lock the price, and reset to null at the end of the auction.
 * `curAuctionPrice` is assigned a value at the beginning of each descending step, and reset at the end of the auction.
 * `remainingProceedsGoal` is assigned a value at the beginning of the auction (if there's a goal), reduced on every trade, and reset at the end of the auction.

File: packages/inter-protocol/src/auction/auctionBook.js (hunk 11 above)
Comment (Chris-Hibbert) [reply packages/inter-protocol/src/auction/auctionBook.js]: I removed the helper.  I considered renaming to `addToNullable()`, since state was the first arg anyway, but your comments about type checking and static analysis convinced me the function wasn't adding enough value.

**Review by turadg — APPROVED** [review]
Some outstanding concerns but all blockers addressed 👍
