### PR TITLE
fix(cosmos-vm): prevent some hangs and crashes in `agd`

### LINKED ISSUE #11395: Add lock around ClientCodec state
# What

Add mutexes around the cosmos vm client codec state, in particular the `outbound` and `replies` maps.

## Why

The maps can be modified by different threads (golang in `WriteRequest` and `ReadResponseBody`; js in `Receive`), and there is no guarantee there may not be multiple goroutines making requests in parallel, resulting in the request or response of one racing with the request or response of another.

### LINKED ISSUE #11396: handle panics in non-go threads
# What

Make sure that any call from a non-go thread to an exported go function has explicit panic handling

## Why

According to the [design doc](https://docs.google.com/document/d/1nr-TQHw_er6GOQRsF6T43GGhFDelrAP0NqSS_00RgZQ/preview?tab=t.0#heading=h.yrdoln2nfbej), when go code is used as a library (buildmode c-archive or c-shared) and called from non-go code, a panic should result in program termination. 

> If the Go code panics, and the panic is not recovered by Go code, the entire program will be terminated.  It would be nice to figure out some more friendly approach, but this is what we will start with.

However it seems this may actually be undefined behavior, and the termination of the process may not guaranteed. We believe in a thread running the node main event loop, it may not terminate other threads.

## How

`recover` panics in exported functions used by JS to invoke golang (`ReplyToGo` and `SendToGo`), and explicitly terminate the process through `os.Exit()`

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #11396, closes: #11395

## Description

- Introduce locks around `vm.ClientCodec` internal state.
- Explicitly `recover()` from Golang panics and propagate errors to the VM controller.

### Security Considerations

Provide better auditability if `agd` crashes.

### Scaling Considerations

Makes the `vm` package correct even with interleaving parallel operations.

### Documentation Considerations

n/a

### Testing Considerations

n/a

### Upgrade Considerations

n/a

### CODE REVIEW

File: golang/cosmos/vm/client.go [hunk 1]
```diff
@@ -34,12 +35,18 @@ var _ rpc.ClientCodec = (*ClientCodec)(nil)
...
+	inbound chan *rpc.Response
+
+	reqMutex sync.Mutex
+	outbound map[int]rpc.Request
+
+	// scratch space
 	replyToRead uint64
+
+	mutex   sync.Mutex
+	replies map[uint64]string
```
Comment (gibson042) [inline golang/cosmos/vm/client.go]: Documenting the scope of these Mutex-valued fields:
```suggestion
	// reqMutex protects outbound
	reqMutex sync.Mutex
	outbound map[int]rpc.Request

	// scratch space
	replyToRead uint64

	// mutex protects replies
	mutex   sync.Mutex
	replies map[uint64]string
```

File: golang/cosmos/vm/client.go [hunk 2]
```diff
@@ -86,25 +97,34 @@ func (cc *ClientCodec) ReadResponseHeader(r *rpc.Response) error {
 
 // ReadResponseBody decodes a response body (currently just string) from the VM.
```
Comment (gibson042) [inline golang/cosmos/vm/client.go:101]:
```suggestion
// ReadResponseBody decodes a response body (currently just string) from the VM,
// and must always be called immediately after ReadResponseHeader (cf.
// https://pkg.go.dev/net/rpc#ClientCodec ).
```

**Review by gibson042 — APPROVED** [review]
LGTM, just comment suggestions.

**Review by JeancarloBarrios — APPROVED** [review]

File: golang/cosmos/vm/client.go (hunk 1 above)
Comment (michaelfig) [reply golang/cosmos/vm/client.go]: Thanks!  Adopted and expanded.

File: golang/cosmos/vm/client.go (hunk 2 above)
Comment (michaelfig) [reply golang/cosmos/vm/client.go:101]: Done, but "must always be" with "will always be".

File: golang/cosmos/cmd/libdaemon/main.go [hunk 3]
```diff
@@ -92,6 +121,8 @@ func RunAgCosmosDaemon(nodePort C.int, toNode C.sendFunc, cosmosArgs []*C.char)
 	// fmt.Fprintln(os.Stderr, "Starting Cosmos", args)
 	os.Args = args
 	go func() {
+		defer handlePanic("daemon.RunWithController")
```
Comment (mhofman) [inline golang/cosmos/cmd/libdaemon/main.go:124]: Why do we need this `handlePanic`? Isn't it a goroutine in the first place?

**Review by mhofman — COMMENTED** [review]
Sorry for the late review. Looks good, just one question.

File: golang/cosmos/cmd/libdaemon/main.go (hunk 3 above)
Comment (michaelfig) [reply golang/cosmos/cmd/libdaemon/main.go:124]: My intent was to guarantee the exit of the program if this goroutine panics, but I may have been overly defensive.

So, it may not be strictly necessary, but shouldn't hurt.
