### PR TITLE
fix(vats): fix promise space reset() misbehavior

### LINKED ISSUE #7709: contract upgrade proposals fragile due to promiseSpace reset strange behavior
## Describe the bug

while working on upgrade testing (#6099) we ran into strange behavior that causes subtle failures in core eval proposals.

it seems to come down to a bug around the `reset()` method from `makePromiseSpace`.

## To Reproduce

```js
test('resolve after reset', async t => {
  /** @type {MapStore<string, string>} */
  const store = makeScalarBigMapStore('stuff', { durable: true });

  const { consume, produce } = makePromiseSpace({ store });
  {
    const { resolve, reset } = produce.foo;
    // const foo2 = consume.foo;
    reset();
    resolve(1);
    // t.is(await foo2, 1);
    t.is(await consume.foo, 1);
  }

  {
    const { resolve, reset } = produce.foo;
    reset();
    resolve(2);
    t.is(await consume.foo, 2);
  }
});
```

## Expected behavior

test above ^ passes. Perhaps some other design constraints need some thought.

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

cc @michaelfig @turadg @warner

### PR DESCRIPTION
**Pull request by warner**
Previously, the reset() feature misbehaved in a common use pattern, where both the `reset` and `resolve` facets were extracted at the same time. The state was nominally held in `nameToState.get(name)`, but was sometimes used by closed-over `state` and `pk` variables. Which one you got depended upon when the Proxy `get` trap was called. If `resolve` was fetched early and retained across a `reset()` call, then `resolve()` would resolve the *old* promise. Later, when `consume` was used, the space would create a new Promise to satisfy the request, which would never be resolved.

This changes the implementation to strictly keep/use the state in `nameToState`, and allow all resolve/reject/reset methods to work the same way no matter when they were retrieved (they close over `name` but not any state).

closes #7709

### CODE REVIEW

**Comment by warner** [comment]
@dckc please run your init/upgrade-proposal test against this branch and see if it behaves better. I think the symptom of the buggy promise-space should have been that the `consume.myInstance` promise would never resolve, so the new vat would never be upgraded. But I know some of the test runs had different symptoms: let's make sure those were artifacts of the test changes we were making and not some new/independent problem.

@michaelfig please make sure this matches your original intentions for how `reset()` should work.

@erights You mentioned that the Proxy could be safer, but it wasn't obvious to me what should be done.. let me know what should be changed.

Concerns:
* Is `remaining` cleared at the right time? Previously `reset()` would clear it, but the `.finally` did too, and I think a `produce.reset(reason); const { foo } = consume;` would incorrectly remove `foo` from `remaining` shortly after the `consume.foo` get trap re-added it. The new logic should not have that problem, but I might have managed to introduce a new one.
* Am I calling the hooks at the right time?
* I renamed one unit test (`makePromiseSpace backed by store`) to say "copied by store", as far as I can tell, the `store` is never read from. To be "backed by" I'd expect the data to be stored primarily in the `store`, which would mean that `makePromiseSpace(store)` would *read* pre-existing store contents (e.g. from an earlier space), and that would require something like a `for (const [k,v] of store.entries()) { produce[k].resolve(v); }`. Might be a neat feature, maybe for a future replacement vat-bootstrap, but not what we've got so far. @michaelfig does that seem accurate?

**Comment by dckc** [comment]
## destructure twice work-around: no joy

Before trying out this proposed fix, I thought this idea was worth a try:

> he could rewrite `init-proposal.js` to destructure produce twice, to work around the promise-space bug,

The rewrite is:
 - 2023-05-12 09:15 9810300d1 WIP: work around promiseSpace.reset()

I ran `scripts/start-local-chain.sh` from `packages/inter-protocol` as usual before running `AGORIC_NET=local ./test/upgrade-contract/contract-upgrade-smoketest.sh` from `packages/agoric-cli`.

<details><summary>Proposals 1 and 2 failed due to unrelated errors</summary>

My first smoke test attempt failed because I forgot to sufficiently fund the account that was supposed to upload the bundle. (The smoke test script seems to not handle this failure mode):

1. "2023-05-12T13:45:00.174512787Z","PROPOSAL_STATUS_PASSED"

```
2023-05-12T13:45:05.353Z SwingSet: xsnap: v10: Error: bundleID not yet installe
d: b1-2a3be684d00d708cbaf7503e0ad6a1894736946122f1fd2180d9b9c33ad93094bffe208db
0a8a13acfcc4c71810d143329da11eae8cf8d127578420842f758e6
```

The second one failed due to a typo: I wrote `instance.myInstance.reset()` where I meant `instance.produce.myInstance.reset()`:

2. "2023-05-12T13:46:50.476782586Z","PROPOSAL_STATUS_PASSED"]

```
2023-05-12T13:47:00.704Z SwingSet: xsnap: v10: RemoteError(error:liveSlots:v1#70002)#2: "myInstance" not permitted, only ["produce"]
```
</details> 

### init, upgrade proposals succeed on 1st smoke test

3. "2023-05-12T13:50:31.044262437Z","PROPOSAL_STATUS_PASSED"
4. "2023-05-12T13:51:36.203487803Z","PROPOSAL_STATUS_PASSED"

```
2023-05-12T13:51:42.302Z SwingSet: kernel: vat v46 upgraded from incarnation 0 
to 1 with source b1-f9b241fdac20a141e2946d863584ea78fce6b3b4b198f41bb7919b03790
48a6a0a90eb6cd98ca0529ce74b38fa2b425ebd216043fb5e6ea096b0e863c65ffefa
```

upgraded behavior seems to work. note `numWantsSatisfied: 1`, capitalized `Free Tokens!!!` with 3 !s

```
$ agops inter my make --from gov1
Object [Alleged: BoardRemoteInstanceHandle] { getBoardId: {} }
2023-05-12T13:54:31.790896575Z tx not in block 307 retrying...
2023-05-12T13:54:31.790896575Z tx not in block 307 retrying...
{"height":"308","txhash":"DD47D7EA68E4427BE640CDCF7959630552ED0730C1566444A4E5A07D77262C86"}
{"id":"my-1683899677507","invitationSpec":{"instance":{},"publicInvitationMaker":"makeInvitation","source":"contract"},"numWantsSatisfied":1,"proposal":{"want":{"Tokens":{"brand":{},"value":"32"}}},"result":"Congratulations, Free Tokens!!!"}
```

ps shows:
```
xsnap-worker v46:zcf-b1-1b57f-myContract -r @8:v46-14
```

Unfortunately, in an attempt to use `DEBUG=label-instances`, I suppressed all logging from vats in this run.
`cosmic-swingset/Makefile` shows `DEBUG ?= SwingSet:ls,SwingSet:vat`. I aim to try that next time.

### upgrade affects wrong vat on 2nd smoke test

I paused the smoke test script after `PROPOSAL_STATUS_VOTING_PERIOD` to let me interact with the "broken" contract before upgrading this time.

5. "2023-05-12T14:03:23.076929024Z","PROPOSAL_STATUS_PASSED"

as expected, broken contract behavior observed: no `numWantsSatisfied`, lowercase `free tokens!` with 1 !.

```
$ agops inter my make --from gov1
Object [Alleged: BoardRemoteInstanceHandle] { getBoardId: {} }
2023-05-12T14:04:43.415637069Z tx not in block 429 retrying...
{"height":"430","txhash":"064C2680487155A0F4211D4421B64964A0C9BDA91A9D9A4226D4AF708362BAFF"}
2023-05-12T14:04:48.429625996Z offer not in wallet at block 430 retrying...
{"id":"my-1683900293221","invitationSpec":{"instance":{},"publicInvitationMaker":"makeInvitation","source":"contract"},"numWantsSatisfied":0,"payouts":{"Tokens":{"brand":{},"value":"0"}},"proposal":{"want":{"Tokens":{"brand":{},"value":"32"}}},"result":"Congratulations, free tokens!"}
```

Then I let the smoke test resume upgrading:

6. "2023-05-12T14:06:58.677453841Z","PROPOSAL_STATUS_PASSED"]

but note that the upgrade affected v46, the vat from the 1st smoke test run:

```
2023-05-12T14:07:05.020Z SwingSet: kernel: vat v46 upgraded from incarnation 1 
to 2 with source b1-f9b241fdac20a141e2946d863584ea78fce6b3b4b198f41bb7919b03790
48a6a0a90eb6cd98ca0529ce74b38fa2b425ebd216043fb5e6ea096b0e863c65ffefa
```

ps shows

```
v46:zcf-b1-1b57f-myContract
v47:zcf-b1-1b57f-myContract -r @8:v47-4
```

**Comment by warner** [comment]
I don't understand the "Chain deployment test" failure. It feels like the client somehow halted around https://github.com/Agoric/agoric-sdk/actions/runs/4956832069/jobs/8867776209?pr=7710#step:10:6894 (maybe while trying to provision the wallet?) , since no progress seems to be made after that point, but I don't see any errors other than the "peer connection lost", and I'm not even sure the client would have been treated as a peer. I need to compare this output against a successful run, and see where they diverge.

**Comment by dckc** [comment]
> please run your init/upgrade-proposal test against this branch and see if it behaves better.

it does!

cherry-picking this fix into `mfig-contract-upgrade-e2e` gets us:

 - 2023-05-12 01:07 2a242bd8c fix(vats): fix promise space reset() misbehavior

repeating the experiment above, on the 2nd smoke test, we get the correct vat upgraded:

```
2023-05-12T15:22:01.057Z SwingSet: kernel: vat v47 upgraded from incarnation 0 to 1 with source b1-f9b241fdac20a141e2946d863584ea78fce6b3b4b198f41bb7919b0379048a6a0a90eb6cd98ca0529ce74b38fa2b425ebd216043fb5e6ea096b0e863c65ffefa
```

and correct upgraded contract behavior:

```
$ agops inter my make --from gov1
Object [Alleged: BoardRemoteInstanceHandle] { getBoardId: {} }
2023-05-12T15:25:15.527007001Z tx not in block 397 retrying...
2023-05-12T15:25:20.539637052Z tx not in block 398 retrying...
{"height":"398","txhash":"462721C3E27CEE5F0F31AB5F1BF91A68B044895AA660287EF727D300D1967ED2"}
{"id":"my-1683905122857","invitationSpec":{"instance":{},"publicInvitationMaker":"makeInvitation","source":"contract"},"numWantsSatisfied":1,"proposal":{"want":{"Tokens":{"brand":{},"value":"32"}}},"result":"Congratulations, Free Tokens!!!"}
```

p.s. running the smoke test a 3rd time works too:
gov-q:
```
["5","2023-05-12T15:36:01.975828598Z","PROPOSAL_STATUS_PASSED"]
["6","2023-05-12T15:41:22.717743466Z","PROPOSAL_STATUS_PASSED"]
```

chain log:

```
2023-05-12T15:41:28.840Z SwingSet: kernel: vat v48 upgraded from incarnation 0 to 1 with source b1-f9b241fdac20a141e2946d863584ea78fce6b3b4b198f41bb7919b0379048a6a0a90eb6cd98ca0529ce74b38fa2b425ebd216043fb5e6ea096b0e863c65ffefa
```

smart wallet interaction with upgraded contract:
```
$ agops inter my make --from gov1
Object [Alleged: BoardRemoteInstanceHandle] { getBoardId: {} }
2023-05-12T15:42:22.974407921Z tx not in block 602 retrying...
{"height":"603","txhash":"0FAD298B3CA295C9AC2921E4B89449C245705FE755B8F28709EA756DEEE64326"}
{"id":"my-1683906151298","invitationSpec":{"instance":{},"publicInvitationMaker":"makeInvitation","source":"contract"},"numWantsSatisfied":1,"proposal":{"want":{"Tokens":{"brand":{},"value":"32"}}},"result":"Congratulations, Free Tokens!!!"}
```

File: packages/vats/test/test-promise-space.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ test('makePromiseSpace', async t => {
   await checkAlice(reusedAlice, `Hi, I'm Alice 3!`);
 });
 
-test('makePromiseSpace backed by store', async t => {
+test('makePromiseSpace copied into store', async t => {
```
Comment (dckc) [inline packages/vats/test/test-promise-space.js:41]: :+1:

**Review by dckc — COMMENTED** [review]
the tests look good, including backed by -> copied into

**Review by dckc — APPROVED** [review]
the new implementation is... slightly less puzzling to me than the old one :)

That is: this should wait for review by @michaelfig . But if he's not available, I think it should land; I'm willing to help maintain it.

File: packages/vats/src/core/promise-space.js [hunk 2]
```diff
@@ -95,75 +96,69 @@ export const makePromiseSpace = (optsOrLog = {}) => {
...
-
       pk.promise
         .finally(() => {
-          remaining.delete(name);
           onSettled(name, remaining);
         })
         .catch(() => {});
+      nameToState.set(name, harden({ pk, isSettling: false }));
+    }
+    return nameToState.get(name) || Fail`provideState(${name})`;
```
Comment (gibson042) [inline packages/vats/src/core/promise-space.js]: Isn't this `Fail` unreachable? We might instead keep more of the old logic.
```js
let state = nameToState.get(name);
if (!state) {
  onAddKey(name);
  remaining.add(name);
  const pk = makePromiseKit();
  pk.promise
    .finally(() => {
      onSettled(name, remaining);
    });
    .catch(() => {});
  state = harden({ pk, isSettling: false });
  nameToState.set(name, state);
}
return state;
```

File: packages/vats/src/core/promise-space.js [hunk 3]
```diff
@@ -95,75 +96,69 @@ export const makePromiseSpace = (optsOrLog = {}) => {
...
-          }
-          reject(reason);
+  // we must tolerate these producer methods being retrieved both
+  // before and after the consumer is retrieved, and also both before
+  // and after reset() is invoked, so they only close over 'name' and
+  // not over any state variables
+
+  const makeProducer = name => {
+    const resolve = value => {
+      onResolve(name, value);
```
Comment (gibson042) [inline packages/vats/src/core/promise-space.js]: I know the old code worked like this too, but is it intentional for the `onResolve` callback to be invoked before actually resolving the promise?

File: packages/vats/src/core/promise-space.js [hunk 4]
```diff
@@ -95,75 +96,69 @@ export const makePromiseSpace = (optsOrLog = {}) => {
...
+      old.pk.reject(reason);
+      remaining.delete(name);
+    };
+    const reset = (reason = undefined) => {
+      onReset(name);
+      const old = provideState(name);
+      if (!old.isSettling) {
+        // we haven't produced a value yet, and there might be
+        // consumers still watching old.pk.promise
+        if (!reason) {
```
Comment (gibson042) [inline packages/vats/src/core/promise-space.js]: Is this too liberal? We might instead want `if (reason === undefined)` or even @erights's trick of `const reset = (...args) => { … }` and `if (args.length === 0)`.

**Review by gibson042 — APPROVED** [review]

File: packages/vats/src/core/promise-space.js (hunk 2 above)
Comment (warner) [reply packages/vats/src/core/promise-space.js]: It is indeed unreachable, but `tsc` didn't seem to know that.

I'll switch to your approach.

File: packages/vats/src/core/promise-space.js (hunk 3 above)
Comment (warner) [reply packages/vats/src/core/promise-space.js]: I wasn't able to figure that out. Given how resolvers work, I don't think anyone could observe a difference, so I stuck with the original order.

File: packages/vats/src/core/promise-space.js (hunk 4 above)
Comment (warner) [reply packages/vats/src/core/promise-space.js]: The only examples I've found of calling `reset` either did `reset()` or `reset('string')`. I'd like to keep it as simple as possible, so I think we'd be ok with `=== undefined`.

File: packages/vats/src/core/promise-space.js [hunk 5]
```diff
@@ -95,86 +95,81 @@ export const makePromiseSpace = (optsOrLog = {}) => {
...
+      remaining.delete(name);
+    };
+
+    return harden({ resolve, reject, reset });
+  };
+
   /** @type {PromiseSpaceOf<T>['consume']} */
   // @ts-expect-error cast
   const consume = new Proxy(
     {},
```
Comment (erights) [inline packages/vats/src/core/promise-space.js]:
```suggestion
    harden({}),
```
This prevents non-get operations from mutating the target and using it as a communications channel. Should be done for both proxies.

**Review by erights — CHANGES_REQUESTED** [review]

File: packages/vats/src/core/promise-space.js (hunk 5 above)
Comment (erights) [reply packages/vats/src/core/promise-space.js]: > @erights You mentioned that the Proxy could be safer, but it wasn't obvious to me what should be done.. let me know what should be changed.

That's what I had in mind.

Comment (erights) [reply packages/vats/src/core/promise-space.js]: Btw, I know it is strange that the proxy invariants allow `get` to pretend properties exist when the hardened target doesn't have them. That's because the proxy invariants are only strong on own-invariants and weak on inherited-only invariants. The proxy can hallucinate these properties only because they are absent as own properties on the target.

Ask me about the history here sometime if your curious. We landed in an ok but weirder than necessary place.

Comment (erights) [reply packages/vats/src/core/promise-space.js]: You need to `yarn format` and push again

**Review by erights — CHANGES_REQUESTED** [review]
On line 62-66
```js
      if (isPromise(valueP)) {
        void valueP.then(value => save(name, value));
      } else {
        save(name, valueP);
      }
```
is NOT reentrancy safe, because `isPromise` does not check that `valueP` is a safe promise. IOW, it may still have an own malicious `then` method. Could check for a safe promise (`passStyleOf(valueP) === 'promise'), but better to just do
```js
      if (isPromise(valueP)) {
        void E.when(valueP, value => save(name, value));
      } else {
        save(name, valueP);
      }
```
Even better in general would be
```js
      void E.when(valueP, value => save(name, value));
```
unless there's a reason you need the synchronous shortcut. Do you?

Icing on the cake is that `E.when` knows how to do deep stack turn tracking.

**Comment by warner** [comment]
> On line 62-66
> 
> ```js
>       if (isPromise(valueP)) {
>         void valueP.then(value => save(name, value));
>       } else {
>         save(name, valueP);
>       }
> ```
> 
> is NOT reentrancy safe, because `isPromise` does not check that `valueP` is a safe promise. IOW, it may still have an own malicious `then` method. Could check for a safe promise (`passStyleOf(valueP) === 'promise'), but better to just do
> 
> ```js
>       if (isPromise(valueP)) {
>         void E.when(valueP, value => save(name, value));
>       } else {
>         save(name, valueP);
>       }
> ```
> 
> Even better in general would be
> 
> ```js
>       void E.when(valueP, value => save(name, value));
> ```
> 
> unless there's a reason you need the synchronous shortcut. Do you?

I don't know. Given what I can glean from the code, callers (behavior functions) might `resolve()` with a real value (frequently a Presence or a record with Presences), or a Promise for such. If they use a Promise, then.. huh, it could hang out for an undetermined time before finally settling, which makes the removal of the name from `remaining` feel a bit premature. The original version only removed from `remaining` upon `.finally` (or `reset()`), and now I think that I shouldn't have changed that part (`remaining` is only used for debugging, but if someone does `produce.foo.resolve(new Promise(() => 0))`, it'll hang forever but not report `foo` as still being pending).

Ok, so I should really move the `remaining.delete` into the `.finally`, and I think the corresponding thing for the `onResolve` hook is to *not* need the synchronous shortcut, as you suggested. So I'll also change it to `E.when`.

@michaelfig I could really use your review on this, I want to make sure I didn't violate any of your other intentions like I did with `remaining`.


> 
> Icing on the cake is that `E.when` knows how to do deep stack turn tracking.

**Review by erights — COMMENTED** [review]
Minor note. Feel free to ignore this round, but capturing while I see it

The code on 90-94 is correct, but I'd rewrite it as
```js
  const { log = noop, store = undefined, hooks = undefined } = opts;
  const logHooks = store
    ? makeStoreHooks(store, log)
    : hooks || makeLogHooks(log);
  const { onAddKey, onSettled, onResolve, onReset } = logHooks;
```
except that TS complains about it in a way that makes no sense to me. Certainly not worth untangling the TS problem today, so ignore for now.

**Review by erights — APPROVED** [review]
LGTM, thanks!

For the record, I do not thoroughly understand the code yet, so I'm really approving to remove my "request changes" block, enabling you to act on your existing approvals.

Everything I understood looks good, and I see no red flags. But this is certainly a weird abstraction that I'd like to come back to later to thoroughly understand. It looks important!

File: packages/vats/src/core/promise-space.js (hunk 4 above)
Comment (erights) [reply packages/vats/src/core/promise-space.js]: Agree. In fact, I strongly prefer `param === undefined` over my arity trick in general. My arity trick is only for the rare cases that it is really compelling that we want to treat an explicit `undefined` as a valid input *and* we want to distinguish the omitted parameter case. We should generally try to avoid those, as it fights hard against JS's general stance on this.

File: packages/vats/package.json [hunk 6]
```diff
@@ -42,6 +42,7 @@
     "@agoric/vat-data": "^0.4.3",
     "@agoric/zoe": "^0.25.3",
     "@agoric/zone": "^0.1.0",
+    "@endo/eventual-send": "^0.17.2",
```
Comment (michaelfig) [inline packages/vats/package.json]: Please don't change.  `@endo/far` is where we find `E`.

```suggestion
```

File: packages/vats/src/core/promise-space.js [hunk 7]
```diff
@@ -1,7 +1,8 @@
 // @ts-check
+import { E } from '@endo/eventual-send';
```
Comment (michaelfig) [inline packages/vats/src/core/promise-space.js]:
```suggestion
import { E } from '@endo/far';
```

File: packages/vats/src/core/promise-space.js (hunk 3 above)
Comment (michaelfig) [reply packages/vats/src/core/promise-space.js]:
```suggestion
      const old = provideState(name);
      if (old.isSettling) {
        // First attempt to settle always wins.
        return;
      }
      onResolve(name, value);
```

File: packages/vats/src/core/promise-space.js [hunk 8]
```diff
@@ -95,102 +92,89 @@ export const makePromiseSpace = (optsOrLog = {}) => {
...
+
+  const makeProducer = name => {
+    const resolve = value => {
+      onResolve(name, value);
+      const old = provideState(name);
+      nameToState.set(name, harden({ ...old, isSettling: true }));
+      old.pk.resolve(value);
+    };
+    const reject = reason => {
+      const old = provideState(name);
```
Comment (michaelfig) [inline packages/vats/src/core/promise-space.js:138]:
```suggestion
      const old = provideState(name);
      if (old.isSettling) {
        // First attempt to settle always wins.
        return;
      }
```

**Review by michaelfig — CHANGES_REQUESTED** [review]

File: packages/vats/package.json (hunk 6 above)
Comment (warner) [reply packages/vats/package.json]: oops, thanks, I grepped and found a bunch of eventual-sends, and assumed that was canonical :)

**Review by michaelfig — APPROVED** [review]
