### PR TITLE
chore(golang): fix lint errors

### LINKED ISSUE #4842: fix miscellaneous lints
## Describe the bug
fix golang lints in test cases for golangci-linter

### PR DESCRIPTION
**Pull request by arirubinstein**
closes: #4842

## Description

Fixes the initial lints, except for
https://github.com/Agoric/agoric-sdk/issues/4791
```
golang/cosmos/x/swingset/types/types.go:91:16: ineffectual assignment to err (ineffassign)
		ret.Nums[i], err = Nat(numFloat)
		             ^
```
https://github.com/Agoric/agoric-sdk/issues/4794
```
golang/cosmos/x/vbank/module.go:191:16: Error return value of `am.PushAction` is not checked (errcheck)
		am.PushAction(ctx, action)
		             ^
```
https://github.com/Agoric/agoric-sdk/issues/4793
```
golang/cosmos/x/vbank/module.go:198:36: Error return value of `am.keeper.SendCoinsToFeeCollector` is not checked (errcheck)
		am.keeper.SendCoinsToFeeCollector(ctx, xfer)
		                                 ^
```

which have individual issues.

I'll modify the pr to include the initial lint errors

### CODE REVIEW

File: golang/cosmos/app/app.go [hunk 1]
```diff
@@ -745,7 +745,10 @@ func (app *GaiaApp) InitChainer(ctx sdk.Context, req abci.RequestInitChain) abci
 // Commit tells the controller that the block is commited
 func (app *GaiaApp) Commit() abci.ResponseCommit {
 	// Frontrun the BaseApp's Commit method
-	swingset.CommitBlock(app.SwingSetKeeper)
+	err := swingset.CommitBlock(app.SwingSetKeeper)
```
Comment (arirubinstein) [inline golang/cosmos/app/app.go:748]:
```
golang/cosmos/app/app.go:748:22: Error return value of `swingset.CommitBlock` is not checked (errcheck)
	swingset.CommitBlock(app.SwingSetKeeper)
```

File: golang/cosmos/daemon/cmd/testnet.go [hunk 2]
```diff
@@ -177,7 +178,7 @@ func InitTestnet(
 			return err
 		}
 
-		addr, secret, err := server.GenerateSaveCoinKey(kb, nodeDirName, true, algo)
+		addr, secret, err := testutil.GenerateSaveCoinKey(kb, nodeDirName, "", true, algo)
```
Comment (arirubinstein) [inline golang/cosmos/daemon/cmd/testnet.go:181]:
```
golang/cosmos/daemon/cmd/testnet.go:180:24: SA1019: server.GenerateSaveCoinKey is deprecated: GenerateSaveCoinKey generates a new key mnemonic with its addrress. If mnemonic is provided then it's used for key generation. The key is saved in the keyring. The function returns error if overwrite=true and the key already exists. Please use testutils.GenerateSaveCoinKey instead. (staticcheck)
		addr, secret, err := server.GenerateSaveCoinKey(kb, nodeDirName, true, algo)
```

File: golang/cosmos/vm/controller.go [hunk 3]
```diff
@@ -66,7 +65,7 @@ func UnregisterPortHandler(portNum int) error {
 func ReceiveFromController(portNum int, msg string) (string, error) {
 	handler := portToHandler[portNum]
 	if handler == nil {
-		return "", errors.New(fmt.Sprintf("Unregistered port %d", portNum))
+		return "", fmt.Errorf("Unregistered port %d", portNum)
```
Comment (arirubinstein) [inline golang/cosmos/vm/controller.go:68]:
```
golang/cosmos/vm/controller.go:69:14: S1028: should use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...)) (gosimple)
		return "", errors.New(fmt.Sprintf("Unregistered port %d", portNum))
```

File: golang/cosmos/x/lien/keeper/keeper_test.go [hunk 4]
```diff
@@ -126,7 +126,7 @@ func makeTestKit() testKit {
 	ms.MountStoreWithDB(bankStoreKey, sdk.StoreTypeIAVL, db)
 	ms.MountStoreWithDB(stakingStoreKey, sdk.StoreTypeIAVL, db)
 	ms.MountStoreWithDB(lienStoreKey, sdk.StoreTypeIAVL, db)
-	ms.LoadLatestVersion()
+	_ = ms.LoadLatestVersion()
```
Comment (arirubinstein) [inline golang/cosmos/x/lien/keeper/keeper_test.go]:
```
golang/cosmos/x/vbank/vbank_test.go:248:22: Error return value of `ms.LoadLatestVersion` is not checked (errcheck)
	ms.LoadLatestVersion()
```

File: golang/cosmos/x/lien/keeper/keeper_test.go [hunk 5]
```diff
@@ -540,7 +534,11 @@ func TestWrap(t *testing.T) {
 
 	tk.initAccount(t, addr1, addr2, types.AccountState{Total: ubld(33)})
 	acc := innerAk.GetAccount(ctx, addr2)
-	acc.SetAccountNumber(8)
+	err := acc.SetAccountNumber(8)
```
Comment (arirubinstein) [inline golang/cosmos/x/lien/keeper/keeper_test.go:551]:
```
golang/cosmos/x/lien/keeper/keeper_test.go:543:22: Error return value of `acc.SetAccountNumber` is not checked (errcheck)
	acc.SetAccountNumber(8)
```

File: golang/cosmos/x/lien/keeper/keeper_test.go [hunk 6]
```diff
@@ -549,7 +547,11 @@ func TestWrap(t *testing.T) {
 
 	tk.initAccount(t, addr1, addr3, types.AccountState{Total: ubld(10), Liened: ubld(8)})
 	acc = innerAk.GetAccount(ctx, addr3)
-	acc.SetAccountNumber(17)
+	err = acc.SetAccountNumber(17)
```
Comment (arirubinstein) [inline golang/cosmos/x/lien/keeper/keeper_test.go:564]:
```
golang/cosmos/x/lien/keeper/keeper_test.go:552:22: Error return value of `acc.SetAccountNumber` is not checked (errcheck)
	acc.SetAccountNumber(17)
```

File: golang/cosmos/x/swingset/handler.go [hunk 7]
```diff
@@ -35,11 +33,3 @@ func NewHandler(k Keeper) sdk.Handler {
 		}
 	}
 }
-
-func mailboxPeer(key string) (string, error) {
```
Comment (arirubinstein) [inline golang/cosmos/x/swingset/handler.go:39]:
```
golang/cosmos/x/swingset/handler.go:39:6: `mailboxPeer` is unused (deadcode)
func mailboxPeer(key string) (string, error) {
```

File: golang/cosmos/x/swingset/module.go [hunk 8]
```diff
@@ -29,7 +29,6 @@ var (
 
 // app module Basics object
 type AppModuleBasic struct {
-	cdc codec.Codec
```
Comment (arirubinstein) [inline golang/cosmos/x/swingset/module.go:32]:
```
golang/cosmos/x/swingset/module.go:32:2: `cdc` is unused (structcheck)
	cdc codec.Codec
```

File: golang/cosmos/x/swingset/module.go [hunk 9]
```diff
@@ -66,7 +65,7 @@ func (AppModuleBasic) RegisterRESTRoutes(ctx client.Context, rtr *mux.Router) {
 }
 
 func (AppModuleBasic) RegisterGRPCGatewayRoutes(clientCtx client.Context, mux *runtime.ServeMux) {
-	types.RegisterQueryHandlerClient(context.Background(), mux, types.NewQueryClient(clientCtx))
+	_ = types.RegisterQueryHandlerClient(context.Background(), mux, types.NewQueryClient(clientCtx))
```
Comment (arirubinstein) [inline golang/cosmos/x/swingset/module.go:68]:
```
golang/cosmos/x/swingset/module.go:69:34: Error return value of `types.RegisterQueryHandlerClient` is not checked (errcheck)
	types.RegisterQueryHandlerClient(context.Background(), mux, types.NewQueryClient(clientCtx))
	                                ^
```

File: golang/cosmos/x/vbank/keeper/keeper.go [hunk 10]
```diff
@@ -10,7 +10,6 @@ import (
 	vm "github.com/Agoric/agoric-sdk/golang/cosmos/vm"
 )
 
-const paramsKey string = "params"
```
Comment (arirubinstein) [inline golang/cosmos/x/vbank/keeper/keeper.go:13]:
```
golang/cosmos/x/vbank/keeper/keeper.go:13:7: `paramsKey` is unused (deadcode)
const paramsKey string = "params"
```

File: golang/cosmos/x/vbank/module.go [hunk 11]
```diff
@@ -57,7 +57,6 @@ func minCoins(a, b sdk.Coins) sdk.Coins {
 
 // app module Basics object
 type AppModuleBasic struct {
-	cdc codec.Codec
```
Comment (arirubinstein) [inline golang/cosmos/x/vbank/module.go:60]:
```
golang/cosmos/x/vbank/module.go:60:2: `cdc` is unused (structcheck)
	cdc codec.Codec
```

File: golang/cosmos/x/vbank/module.go [hunk 12]
```diff
@@ -92,7 +91,7 @@ func (AppModuleBasic) RegisterRESTRoutes(clientCtx client.Context, rtr *mux.Rout
 }
 
 func (AppModuleBasic) RegisterGRPCGatewayRoutes(clientCtx client.Context, mux *runtime.ServeMux) {
-	types.RegisterQueryHandlerClient(context.Background(), mux, types.NewQueryClient(clientCtx))
+	_ = types.RegisterQueryHandlerClient(context.Background(), mux, types.NewQueryClient(clientCtx))
```
Comment (arirubinstein) [inline golang/cosmos/x/vbank/module.go:94]:
```
golang/cosmos/x/vbank/module.go:95:34: Error return value of `types.RegisterQueryHandlerClient` is not checked (errcheck)
	types.RegisterQueryHandlerClient(context.Background(), mux, types.NewQueryClient(clientCtx))
```

File: golang/cosmos/x/vbank/vbank_test.go [hunk 13]
```diff
@@ -245,7 +245,7 @@ func makeTestKit(bank types.BankKeeper) (Keeper, sdk.Context) {
 	ms.MountStoreWithDB(vbankStoreKey, sdk.StoreTypeIAVL, db)
 	ms.MountStoreWithDB(paramsStoreKey, sdk.StoreTypeIAVL, db)
 	ms.MountStoreWithDB(paramsTStoreKey, sdk.StoreTypeTransient, db)
-	ms.LoadLatestVersion()
+	_ = ms.LoadLatestVersion()
```
Comment (arirubinstein) [inline golang/cosmos/x/vbank/vbank_test.go]:
```
golang/cosmos/x/vbank/vbank_test.go:248:22: Error return value of `ms.LoadLatestVersion` is not checked (errcheck)
	ms.LoadLatestVersion()
```

File: golang/cosmos/x/vibc/module.go [hunk 14]
```diff
@@ -29,7 +29,6 @@ var (
 
 // app module Basics object
 type AppModuleBasic struct {
-	cdc codec.Codec
```
Comment (arirubinstein) [inline golang/cosmos/x/vibc/module.go:32]:
```
golang/cosmos/x/vibc/module.go:32:2: `cdc` is unused (structcheck)
	cdc codec.Codec
```

File: golang/cosmos/x/lien/keeper/keeper_test.go (hunk 4 above)
Comment (JimLarson) [reply golang/cosmos/x/lien/keeper/keeper_test.go]: Might as well check that this error return is nil. It's fine to panic.

File: golang/cosmos/x/lien/keeper/keeper_test.go [hunk 15]
```diff
@@ -354,12 +354,6 @@ func TestAccountState(t *testing.T) {
 	if err != nil {
 		t.Fatalf("cannot undelegate: %v", err)
 	}
-	wantState = types.AccountState{
```
Comment (JimLarson) [inline golang/cosmos/x/lien/keeper/keeper_test.go:357]: Don't remove - looks like I forgot to `GetAccountState` and compare. See a few lines above.

File: golang/cosmos/x/vbank/vbank_test.go (hunk 13 above)
Comment (JimLarson) [reply golang/cosmos/x/vbank/vbank_test.go]: As with the lien test, check this and panic if not nil.

**Review by JimLarson — CHANGES_REQUESTED** [review]

File: golang/cosmos/x/lien/keeper/keeper_test.go (hunk 15 above)
Comment (arirubinstein) [reply golang/cosmos/x/lien/keeper/keeper_test.go:357]: fixed with a new getstate

**Review by JimLarson — APPROVED** [review]
