### PR TITLE
fix(psm): "mint" limits for IST rather than anchor

### LINKED ISSUE #6223: PSM minting limit should be wrt Minted brand
## Describe the bug
For PSM, the MintingLimit parameter was specified in terms of the anchor brand. That makes the MintingLimit incomparable with among minting sources, including other PSMs.

## Expected behavior
Minting limits are expressed in the minted currency, e.g., IST.

## Platform Environment
PSM

### PR DESCRIPTION
**Pull request by dtribble**
closes: #6223

## Description

The MintingLimit parameter was specified in terms of the anchor brand. That makes the MintingLimit incomparable with among minting sources, including other PSMs.

Incidentally reduce the default MINT_LIMIT to a small value for testing. Governance is required to raise it to a higher amount.

### Security Considerations

The minting limits are an important tool for managing risk in IST. While the minting limit using the anchor amounts coudl be managed, using different brands for different PSM or other minting sources would make it so that we were not minting against a standard limit.

### Documentation Considerations

Documenting minting limits as expressed in IST will be much clearer.

### Testing Considerations

A test was added to confirm that it mints against the minted brand rather than the anchor brand.

### CODE REVIEW

File: packages/inter-protocol/src/psm/psm.js [hunk 1]
```diff
@@ -143,17 +146,24 @@ export const start = async (zcf, privateArgs, baggage) => {
...
-  const assertUnderLimit = given => {
-    const anchorAfterTrade = AmountMath.add(
-      anchorPool.getAmountAllocated('Anchor', anchorBrand),
-      given,
-    );
-    AmountMath.isGTE(params.getMintLimit(), anchorAfterTrade) ||
+  const assertUnderLimit = toMint => {
+    const mintedAfter = AmountMath.add(mintedOutstanding, toMint);
+    AmountMath.isGTE(params.getMintLimit(), mintedAfter) ||
       assert.fail(X`Request would exceed mint limit`);
```
Comment (dckc) [inline packages/inter-protocol/src/psm/psm.js:157]: we don't have a `fail` template tag yet? darn.

File: packages/inter-protocol/test/psm/test-psm.js [hunk 2]
```diff
@@ -338,6 +338,27 @@ test('limit', async t => {
...
+  const anchorPerMinted = makeRatio(50n, anchor.brand, 100n, minted.brand);
+  const driver = await makePsmDriver(t, { anchorPerMinted });
+
+  trace('test going over limit');
+  const giveTooMuch = anchor.make(MINT_LIMIT);
+  const seat1 = await driver.swapAnchorForMintedSeat(giveTooMuch);
+  t.throwsAsync(() => E(seat1).getOfferResult(), {
+    message: 'Request would exceed mint limit',
+  });
+  trace('limit is enforced on the Minted rather than Anchor');
```
Comment (dckc) [inline packages/inter-protocol/test/psm/test-psm.js]: use ava's message arg instead of trace?

```suggestion
  t.throwsAsync(() => E(seat1).getOfferResult(), {
    message: 'Request would exceed mint limit',
  }, 'limit is enforced on the Minted rather than Anchor');
```

File: packages/inter-protocol/test/psm/test-psm.js [hunk 3]
```diff
@@ -338,6 +338,27 @@ test('limit', async t => {
...
+
+  trace('test right at limit');
+  const give = anchor.make(MINT_LIMIT / 2n);
+  const paymentPs = await driver.swapAnchorForMinted(give);
+  await paymentPs;
+  trace('test at minted limit works');
```
Comment (dckc) [inline packages/inter-protocol/test/psm/test-psm.js]:
```suggestion
  await t.notThrowsAsync(paymentPs, 'test that minted limit works');
```

at least spell out "that" :)

**Review by dckc — APPROVED** [review]
looks good.
a couple minor suggestions to consider. not critical.

File: packages/inter-protocol/src/psm/psm.js (hunk 1 above)
Comment (turadg) [reply packages/inter-protocol/src/psm/psm.js:157]: what would that do?

Incidentally, why is this a template at all when it's a simple string? While we're here, how about adding some feedback: (`X``Request would exceed mint limit ${mintLimit.value}`)

File: packages/inter-protocol/test/psm/test-psm.js (hunk 2 above)
Comment (turadg) [reply packages/inter-protocol/test/psm/test-psm.js]: +1

File: packages/inter-protocol/src/psm/psm.js [hunk 4]
```diff
@@ -118,6 +118,9 @@ export const start = async (zcf, privateArgs, baggage) => {
   const anchorPool = provideEmptyZcfSeat('anchorPoolSeat');
   const feePool = provideEmptyZcfSeat('feePoolSeat');
   const stage = provideEmptyZcfSeat('stageSeat');
+
+  let mintedOutstanding = AmountMath.makeEmpty(stableBrand);
```
Comment (turadg) [inline packages/inter-protocol/src/psm/psm.js:122]: not clear to me what this value is for. Making `burnLosses` throw an error if `toBurn` is greater than what we've yet minted?

Shouldn't `burnMinted` take the exact same amount as `mintMinted` ? 

As is, I'm not sure this value and those two new functions are in improvement.

File: packages/inter-protocol/test/psm/test-psm.js [hunk 5]
```diff
@@ -311,7 +311,7 @@ test('simple trades', async t => {
 });
 
 test('limit', async t => {
-  const { mintLimit, anchor } = t.context;
+  const { anchor } = t.context;
```
Comment (turadg) [inline packages/inter-protocol/test/psm/test-psm.js:316]: for the same reasons you stopped getting `mintLimit` from the context, it should be removed from the context maker https://github.com/Agoric/agoric-sdk/blob/a1dedeae72908fda45afcb6038d76f8359adc8de/packages/inter-protocol/test/psm/test-psm.js#L129

File: packages/inter-protocol/test/psm/test-psm.js [hunk 6]
```diff
@@ -338,6 +338,27 @@ test('limit', async t => {
   // t.throwsAsync(() => await E(seat1).getOfferResult());
```
Comment (turadg) [inline packages/inter-protocol/test/psm/test-psm.js:340]: Is "TODO Offer result should be an error" something we should have for PSO?

Same question for the other TODO in this test: https://github.com/Agoric/agoric-sdk/blob/a1dedeae72908fda45afcb6038d76f8359adc8de/packages/inter-protocol/test/psm/test-psm.js#L328

File: packages/inter-protocol/test/psm/test-psm.js (hunk 3 above)
Comment (turadg) [reply packages/inter-protocol/test/psm/test-psm.js]: I feel more strongly about this being an actual test statement so included it in my requested changes

**Review by turadg — CHANGES_REQUESTED** [review]

**Review by turadg — APPROVED** [review]
I pushed the changes I requested so I'm approving.

I had also Requested Changes on a question about `mintedOutstanding` but I figured it out while following the code in my IDE so I deleted the comment.

File: packages/inter-protocol/src/psm/psm.js (hunk 1 above)
Comment (dckc) [reply packages/inter-protocol/src/psm/psm.js:157]: The fall template tag would abbreviate assert.fail and X:

```js
x > 0 || fail`x too small: ${x}`
```

Comment (dckc) [reply packages/inter-protocol/src/psm/psm.js:157]: It was something I saw Dean say in chat somewhere.

Comment (turadg) [reply packages/inter-protocol/src/psm/psm.js:157]: nifty

File: packages/inter-protocol/test/psm/test-psm.js (hunk 2 above)
Comment (dtribble) [reply packages/inter-protocol/test/psm/test-psm.js]: `trace` here is wrapped around AVA's log (in tests). This provided consistent reporting along with any `trace` statements in the stuff being tested (which are using `console`)

File: packages/inter-protocol/test/psm/test-psm.js (hunk 6 above)
Comment (dtribble) [reply packages/inter-protocol/test/psm/test-psm.js:340]: that's pre-existing. I don't know what was intended here.

**Review by turadg — APPROVED** [review]
+1 changes since last review
