### PR TITLE
fix(cosmic-swingset): use BOOTSTRAP_BLOCK to avoid slog confusion

### LINKED ISSUE #3470: Off by one blockHeight in slog for genesis block
## Describe the bug
When starting a node with a genesis block at a specific `blockHeight`, the slog file contains 2 `cosmic-swingset-end-block` sections (`start` to `finish`) for the initial block (e.g. `15425` for the first restart of testnet phase 4).

It seems that first section contains the reactions to the vat replay, and the second has the first cosmos driven deliveries, so the first section should be numbered differently.

## To Reproduce
1. Create a genesis from an existing chain state.
2. Start a node from that genesis
3. Let the chain start producing blocks

## Expected behavior
No duplicate block numbers in slog files

## Platform Environment
N/A

## Additional context
Observed in all slogs for node starting at genesis collected during testnet 4.

## Screenshots
```
{"time":1624681768.567772,"type":"cosmic-swingset-end-block-finish","blockHeight":15425,"blockTime":1624734000}
{"time":1624734002.3602827,"type":"cosmic-swingset-begin-block","blockHeight":15425,"blockTime":1624734000}
{"time":1624734002.4302108,"type":"cosmic-swingset-end-block-start","blockHeight":15425,"blockTime":1624734000}
```

### PR DESCRIPTION
**Pull request by michaelfig**
Fixes #3470

This should clear up the slogging of the bootstrap work that is run before the chain starts producing blocks.

Rather than running this work under a fake `END_BLOCK` message, use `BOOTSTRAP_BLOCK` instead.

### CODE REVIEW

**Comment by michaelfig** [comment]
Tagging @mhofman and @JimLarson to review the parts that they understand.  The final decision is probably up to @warner.

File: golang/cosmos/x/swingset/genesis.go [hunk 1]
```diff
@@ -34,13 +42,25 @@ func InitGenesis(ctx sdk.Context, keeper Keeper, data *types.GenesisState) []abc
 	// Just run the SwingSet kernel to finish bootstrap and get ready to open for
 	// business.
 	stdlog.Println("Running SwingSet until bootstrap is ready")
-	bootstrapBlock := abci.RequestEndBlock{Height: ctx.BlockHeight()}
-	valUpdate, err := EndBlock(ctx, bootstrapBlock, keeper)
```
Comment (JimLarson) [inline golang/cosmos/x/swingset/genesis.go:38]: Just one thing to double-check. This call sets `endBlockHeight` and `endBlockTime` in `abci.go`. Assuming that `ctx.BlockHeight()` is zero, the behavior is unchanged, but the `endBlockTime` now remains uninitialized. I *think* that's fine, as there should be a (real) call to `EndBlock()` before the next call to `CommitBlock()`, which is the only thing that reads those fields, but please double-check to be sure.

**Review by JimLarson — APPROVED** [review]
The Go changes LGTM - with one thing to double-check.

File: golang/cosmos/x/swingset/genesis.go (hunk 1 above)
Comment (michaelfig) [reply golang/cosmos/x/swingset/genesis.go:38]: That understanding is correct.

File: packages/cosmic-swingset/src/launch-chain.js [hunk 2]
```diff
@@ -175,21 +175,27 @@ export async function launch(
...
+  async function bootstrapBlock(blockTime) {
+    controller.writeSlogObject({
+      type: 'cosmic-swingset-bootstrap-block-start',
+      blockTime,
+    });
+    // This is before the initial block, we need to finish processing the
+    // entire bootstrap before opening for business.
+    await crankScheduler(Infinity);
+    controller.writeSlogObject({
+      type: 'cosmic-swingset-bootstrap-block-end',
```
Comment (mhofman) [inline packages/cosmic-swingset/src/launch-chain.js]: Nit, to stay consistent with the `end-block-{start|finish}`
```suggestion
      type: 'cosmic-swingset-bootstrap-block-finish',
```

File: packages/solo/src/start.js [hunk 3]
```diff
@@ -444,8 +444,12 @@ export default async function start(basedir, argv) {
       if (err) {
         console.error(err);
       }
+      // eslint-disable-next-line no-use-before-define
+      process.off('exit', killDeployment);
     },
   );
+  const killDeployment = () => cp.kill('SIGINT');
+  process.on('exit', killDeployment);
```
Comment (mhofman) [inline packages/solo/src/start.js:452]: This seems unrelated to this issue.

**Review by mhofman — CHANGES_REQUESTED** [review]
Minor nits. Refactor around swingset bootstrap seems sane to me, but I'll let @warner confirm.

File: packages/solo/src/start.js (hunk 3 above)
Comment (michaelfig) [reply packages/solo/src/start.js:452]: It helped me debug problems while creating this PR.  Would you prefer I remove it?

Comment (mhofman) [reply packages/solo/src/start.js:452]: I think there is a more general issue with children management (e.g. the cli tends to leave its child behind too). I personally prefer keeping PRs focused, but I'll defer on best practices for now. If included, it should probably be its own commit tho.

**Review by mhofman — APPROVED** [review]

File: packages/cosmic-swingset/src/launch-chain.js [hunk 4]
```diff
@@ -175,21 +175,27 @@ export async function launch(
...
 
-  let bootstrapBlock;
+  async function bootstrapBlock(blockTime) {
+    controller.writeSlogObject({
+      type: 'cosmic-swingset-bootstrap-block-start',
+      blockTime,
+    });
+    // This is before the initial block, we need to finish processing the
+    // entire bootstrap before opening for business.
+    await crankScheduler(Infinity);
```
Comment (warner) [inline packages/cosmic-swingset/src/launch-chain.js:185]: @mhofman Be aware, here's another call site that wants a `runPolicy`, and this one wants a "give it as much time as it wants" option.

**Review by warner — APPROVED** [review]
Good, I like the simplicity.

File: packages/cosmic-swingset/src/launch-chain.js (hunk 4 above)
Comment (mhofman) [reply packages/cosmic-swingset/src/launch-chain.js:185]: Yup, makes it a lot more straightforward actually.
