### PR TITLE
fix: don't ever display a 404 for the wallet

### LINKED ISSUE #1878: Running `agoric open` fails to load the wallet during initialisation
**Describe the bug**
Running `agoric open` or `agoric open --repl` before the ag-solo has initialised doesn't give feedback, it just fails to load the wallet.

**To Reproduce**
1. Start `agoric start --reset`
2. As soon as the "listening" message appears, run `agoric open`
3. Note that the wallet does not appear, even if you wait until the initialisation is complete
4. Try reloading the page
5. Now the "null authorization" message appears in the `agoric start` terminal

Also retry the same, but for step 2, use `agoric open --repl`.

**Expected behavior**
The wallet panel should always appear, and display a loading message.  When initialisation is complete, the panel should reload with the actual wallet.  The user should be prevented from reloading the page (and causing the "null" error).

**Platform Environment**
n/a

**Additional context**
none.

**Screenshots**

Results of `agoric start` before wallet initialisation.  Note that the wallet just doesn't load.
Screen Shot 2020-10-16 at 9 21 16 AM

Results of `agoric start --repl` before wallet initialisation.  Notice there is no trace of the wallet.
Screen Shot 2020-10-16 at 9 22 01 AM

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #1878 

Move the symlinking of the wallet before we establish the HTTP listener.  That way, as soon as the browser loads, the wallet is available.

At least on Chromium-based browsers, calling `agoric open` before the HTTP server is set up will automatically detect that localhost:8000 is available and automatically reload (with the wallet) as soon as the listener is established.

This makes for a much more robust `agoric open`.

### CODE REVIEW

**Review by FUDCo — APPROVED** [review]
is ok

File: packages/cosmic-swingset/lib/ag-solo/start.js [hunk 1]
```diff
@@ -297,6 +297,26 @@ export default async function start(basedir, argv) {
     resetOutdatedState,
   } = d;
 
+  // Remove wallet traces.
+  await unlink('html/wallet').catch(_ => {});
+
+  const { wallet } = JSON.parse(fs.readFileSync('options.json', 'utf-8'));
```
Comment (kriskowal) [inline packages/cosmic-swingset/lib/ag-solo/start.js:303]: Is there sense in making this robust to the working directory, or are you comfortable with that being implied by the `yarn start` workflow driving?

**Review by kriskowal — APPROVED** [review]

File: packages/cosmic-swingset/lib/ag-solo/start.js (hunk 1 above)
Comment (michaelfig) [reply packages/cosmic-swingset/lib/ag-solo/start.js:303]: > Is there sense in making this robust to the working directory, or are you comfortable with that being implied by the `yarn start` workflow driving?

This command can only run after an `agoric init <dirname>; cd <dirname>` and it heuristically identifies when you're definitely not in such a directory.

But thanks for asking.
