### PR TITLE
fix(cosmos): ensure simulated transactions can't trigger SwingSet

### LINKED ISSUE #3739: consensus failure in testnet4.5 on RPC node peer-2 at block 9292
@michaelfig reported one of our testnet4.5 ("metering phase") RPC nodes halted with a consensus error at block 9292. With the new #3442 kernel activityhash in place, the node will stop just before it commits the non-conforming swingset state changes.

I looked at the slogfiles from the failed node and from one that continued to work. The difference is that the failed node was given an extra `cosmic-swingset-deliver-inbound` in block 9292. This is what swingset sees in response to a cosmos-level signed transaction coming from a solo node. The host calls `mailbox.deliverInbound(peer, msg)`, and the mailbox device pushes a delivery to vattp onto the run-queue. Then, when `controller.run()` is executed, this delivery is made. The specific delivery (as reported in the slogfile) was:
```json
{
  "type": "crank-start",
  "message": {
    "type": "send",
    "target": "ko33",
    "msg": {
      "method": "deliverInboundMessages",
      "args": {
        "body": "[\"agoric19ta405rhge63q4delmuy376azee3jsr4x85k67\",[[13,\"13:11:deliver:ro+51033:makeEmptyPurse:rp-50;[]\"]]]",
        "slots": []
      },
      "result": null
    }
  }
}
```

In the non-failing ("good") node, this same delivery appears in block 9294. The cosmos txn which provides this delivery also appears in block 9294 (according to `ag-chain-cosmos query block 9294` on a monitoring node that has not observed any problems).

I'm really puzzled as to how this message could be delivered two blocks *early*. If the failing node saw the message arrive *late*, then I might suspect a bug in the cosmic-swingset block-manager, causing a queued message to be missed, and delivered on the next block with any messages (note that 9293 was empty).

But for the failing node to see the delivery *earlier* than the succeeding/consensus nodes.. one weak hypothesis is that we've got a block-manager bug that fails far more often than not, and the "failing" node is actually the one validator which *didn't* see the delay. That seems really unlikely.

An even weaker hypothesis is that some block proposer suggested a 9292-A which includes the delivery, but the vote failed, but the "bad" RPC node thought it succeeded, and executed the block anyways.

The same thing seemed to happen to a second RPC node, at block 10200. In this case, the extra message was:
```json
{
  "type": "crank-start",
  "message": {
    "type": "send",
    "target": "ko33",
    "msg": {
      "method": "deliverInboundMessages",
      "args": {
        "body": "[\"agoric14pz3f6ae0jgqtxt484z2s4ezwk4r8lupu9d2c5\",[[2646,\"2646:2632:deliver:ro+45626:getPayout:rp-2332;[\\\"Collateral\\\"]\"],[2647,\"2647:2632:deliver:ro+45626:getPayout:rp-2333;[\\\"RUN\\\"]\"]]]",
        "slots": []
      },
      "result": null
    }
  }
}
```

in this case the monitoring node saw the corresponding cosmos txn in block 10202.

cc @michaelfig

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #3739

The former pattern of `vm.IsSimulation` was too brittle to handle
our migration to the GRPC-based transaction handlers.  Instead,
intercept the actual invocation of CallToController and prevent
it from running anything in SwingSet if in simulation mode.

Also, make sure our InfiniteGasMeter is only assigned once, so
that if we ever do Cosmos-level metering of SwingSet downcalls,
there is only one place to adjust.

### CODE REVIEW

**Review by dckc — COMMENTED** [review]
Wild.

I browsed the changes. If it's important to have this approved soon: Which are the key parts and which are just knock-on effects?

**Review by dckc — APPROVED** [review]
Thanks for testing it.

File: golang/cosmos/app/app.go [hunk 1]
```diff
@@ -358,7 +358,12 @@ func NewAgoricApp(
 	)
 
 	// This function is tricky to get right, so we build it ourselves.
-	callToController := func(ctx sdk.Context, str string) (string, error) {
+	callToController := func(ctx sdk.Context, str, simReturn string) (string, error) {
+		if vm.IsSimulation(ctx) {
+			// Just return the simReturn, since the message is being simulated.
+			return simReturn, nil
```
Comment (JimLarson) [inline golang/cosmos/app/app.go:364]: It sure looks like `simReturn` is always the empty string. If so, you can avoid the extra arg to `callToController` and avoid a lot of changes.
