### PR TITLE
7794 capture market price at auction start

### LINKED ISSUE #7794: Auction price level starts based on locked price not market price
## To Reproduce
1. Start a local chain with vaults
2. Wait for price lock period to start
3. Push new oracle price, verify in UI that price is updated
4. Wait for auction to start
5. Observe that `currentPriceLevel` starts at a multiple of the `startPrice` rather than the current market price that was last pushed.

## Expected behavior

At step 5, the `currentPriceLevel` should be a multiple of the market price that was last pushed.

## Additional context

[Gist ](https://gist.github.com/samsiegart/e449de6953afbc45f835448183444677) showing a sequence of events:
- Update the oracle price (lines 1-95), verified in UI that this succeeded
- Query the book (line 96), see that `startPrice` is around $12, and `currentPriceLevel` is null (auction hasn't started yet)
- Query the book again (line 100), see that `currentPriceLevel` is around $12, rather than the market price that was previously pushed

### LINKED ISSUE #7796: Liquidation never takes place following rebuild from master despite conditions conducive to it, vaults hung in liquidating state and bids never fill
## Describe the bug
After rebuilding docker from master to test @Chris-Hibbert's fix https://github.com/Agoric/agoric-sdk/issues/7784 - I setup test scenario for reconstitution, pushed price to trigger liquidations but liquidation never completes (even though auction continues to run).
Vaults are hung in 'liquidating' state'.

## To Reproduce
1. Rebuild docker against Master
2. Set Flow 2b liquidation scenario with price of 12.34, 3x vaults + 2 bids as per: 
3. Observe default 1hour auction schedule via 'agops inter action status', wait for 1-1.5 cycles for it to pick up testing default of 10min (600s start freq) and 5mins price lock period (300s).
4. Observe vaults go into 'liquidating' state in Vaults UI but never complete liquidation.
5. Observe no collateral on offer and no bids filled for outstanding debt despite bids in.
6. Observe 'liquidating' vaults stuck in loop.
7. Observe auctions start and complete in cycles but no collateral on offer or bids filled.

## Expected behavior
Expected auction schedule to have settled, liquidation to have occurred and auction complete with bids filled and 2x vaults reconstituted

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context
Tried changing auction params to see if it would refresh/wake-up liquidator but didn't have an effect.

## Screenshots
Pasted Graphic 6

Pasted Graphic 7

Pasted Graphic 8

### LINKED ISSUE #7798: Auction shouldn't  track locked price
## Describe the bug

The auction only tracks one lockedPrice, so it can't distinguish the price locked for the current round with one locked for the next round. The price is locked for the next round based on the priceLockTimePeriod.

If the priceLockPeriod occurs before the start of some steps of the auction, their prices will be based on the new locked price rather than the one the auction started with.

The current parameters in econ-behavior.js (which I think are the proposed parameters for the Vaults release) sidestep this issue because the auction will end before the priceLock for the next round.
```
    auctionParams = {
      StartFrequency: 3600n,
      ClockStep: 3n * 60n,
      StartingRate: 10500n,
      LowestRate: 6500n,
      DiscountStep: 500n,
      AuctionStartDelay: 2n,
      PriceLockPeriod: 30n * 60n, // half an hour
    }
```
This specifies 8 descending steps of 3 minutes each, which ends before the priceLock at the half hour.

## To Reproduce

Set up auction parameters where the priceLock would be before the start of the last step of the auction. (e.g. 10 descending steps of 5 minutes each, and a price lock period of 20 minutes.)  If the price changes between the lock point before the current round and the price lock for the next round, that should effect the price at which goods are sold in rounds that start after the price lock.

## Expected behavior

When the price is locked for the next round, that shouldn't affect prices charged in the current descending auction.

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #7798
closes: #7796 
closes: #7794 

## Description

I had named two things "lockedPrice", and it had confused me into scheduled the capture of the market price at the start of the auction to be at the priceLock time instead. The PR (separately) renames all lockPrice references in auction and scheduler to be variations on "capture" instead, and then corrects the timing of the capture.

### Security Considerations

Names are powerful

### Scaling Considerations

None

### Documentation Considerations

Captured price doesn't have a confusing name in the UI.

### Testing Considerations

Manual tests have exposed this issue, and the unit tests show that I have fixed the issue.

### CODE REVIEW

File: packages/inter-protocol/src/auction/scheduler.js [hunk 1]
```diff
@@ -209,9 +209,9 @@ export const makeScheduler = async (
   };
 
   // set wakeups for the steps of this round
-  const queueLiveSchedule = () => {
+  const scheduleDescendingSteps = () => {
```
Comment (turadg) [inline packages/inter-protocol/src/auction/scheduler.js:215]: this was renamed to "queue" to avoid the overloading of "schedule" (noun for a plan and verb for setting wakeups). ironic that the PR un-overloading "locked" re-overloaded "schedule".  also surprised to see it not mentioned in the commit message.

not a blocker

**Review by turadg — APPROVED** [review]
Aha! Much clearer with the refactor. Thanks for separating that out.

Testing plan looks good enough to put into the merge queue. While that's chugging through please also manually verify on chain that this fully fixes #7794.

**Comment by samsiegart** [comment]
Could you help me understand the implications this has on vstorage? Is `startPrice` now equal to `capturedPriceForRound` if it fixes https://github.com/Agoric/agoric-sdk/issues/7794? I would expect that to imply that:
1. `startPrice` is now `null` until auction starts, as opposed to having a value as soon as it enters the price lock period.
2. `startPrice` no longer represents the locked price during the price lock period. Is that price published anywhere now?

**Comment by Chris-Hibbert** [comment]
> Could you help me understand the implications this has on vstorage?

Auctions no longer track a price captured at the priceLock point. They incorrectly captured this price before this PR when what they actually wanted was the market price at the start of the auction. So that's no longer useful for the UI to show as the lock price.

Vaults are capturing the lockedPrice at the correct time, but they aren't publishing it. This could be added to the vaultManager metrics with one line of code. (Plus whatever it takes to process metrics and update types.)  It wouldn't affect vault or auction processing logic. It might affect the timing of updating the metrics, which could impact test output.
