### PR TITLE
fix(auction): recovering from late start

### LINKED ISSUE #7775: handling of auctions ending in the future is broken
## Describe the bug

Case 2 of the auction timing recovery fails.

## To Reproduce

Use branch https://github.com/Agoric/agoric-sdk/pull/7773
```sh
TARGET=agoric-upgrade-10 make build_test run
```

Wait for block 880.
```
2023-05-17T19:10:04.953Z block-manager: block 880 begin
2023-05-17T19:10:05.184Z SwingSet: vat: v39: ----- SCHED.8  2 startSchedulingFromScratch
2023-05-17T19:10:05.185Z SwingSet: vat: v39: ----- SCHED.8  3 nextRound { timerBrand: Object [Alleged: timerBrand] {}, absValue: 1_684_350_000n }
2023-05-17T19:10:05.186Z SwingSet: vat: v39: ----- SCHED.8  4 priceLock { timerBrand: Object [Alleged: timerBrand] {}, absValue: 1_684_348_202n }
2023-05-17T19:10:05.189Z SwingSet: vat: v39: ----- SCHED.8  5 received param update
2023-05-17T19:10:05.273Z SwingSet: vat: v39: ----- SCHED.8  6 received param update
2023-05-17T19:10:05.278Z SwingSet: vat: v39: ----- SCHED.8  7 START  { timerBrand: Object [Alleged: timerBrand] {}, absValue: 1_684_350_002n }
2023-05-17T19:10:05.279Z SwingSet: vat: v39: ----- SCHED.8  8 queueLiveSchedule repeating { absValue: 1_684_350_000n, timerBrand: Object [Alleged: timerBrand] {} } { timerBrand: Object [Alleged: timerBrand] {}, relValue: 2n } { timerBrand: Object [Alleged: timerBrand] {}, absValue: 1_684_350_002n }
2023-05-17T19:10:05.279Z SwingSet: vat: v39: ----- SCHED.8  9 nextRound { timerBrand: Object [Alleged: timerBrand] {}, absValue: 1_684_351_800n }
2023-05-17T19:10:05.280Z SwingSet: vat: v39: ----- SMath.7  2 calc { timerBrand: Object [Alleged: timerBrand] {}, absValue: 1_684_350_002n } { absValue: 1_684_350_000n, timerBrand: Object [Alleged: timerBrand] {} }
2023-05-17T19:10:05.281Z SwingSet: vat: v39: ----- SCHED.8  10 priceLock { timerBrand: Object [Alleged: timerBrand] {}, absValue: 1_684_351_502n }
2023-05-17T19:10:05.288Z SwingSet: vat: v39: ----- SCHED.8  11 wake step { absValue: 1_684_350_002n, timerBrand: Object [Alleged: timerBrand] {} }
2023-05-17T19:10:05.288Z SwingSet: vat: v39: ----- SCHED.8  12 clockTick { timerBrand: Object [Alleged: timerBrand] {}, absValue: 1_684_350_002n } { absValue: 1_684_350_002n, timerBrand: Object [Alleged: timerBrand] {} }
2023-05-17T19:10:05.289Z SwingSet: vat: v39: ----- Auction.9  2 startRound
2023-05-17T19:10:05.292Z SwingSet: vat: v39: (Error#1)
2023-05-17T19:10:05.292Z SwingSet: vat: v39: Error#1: Unable to start auction cleanly. skipping this auction round.
2023-05-17T19:10:05.292Z SwingSet: vat: v39: Error: Unable to start auction cleanly. skipping this auction round.
 at construct ()
 at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:56)
 at makeError (/bundled-source/.../node_modules/ses/src/error/assert.js:243)
 at advanceRound (.../inter-protocol/src/auction/scheduler.js:184)
 at clockTick (.../inter-protocol/src/auction/scheduler.js:199)
 at clockTick (.../inter-protocol/src/auction/scheduler.js:138)
 at wake (.../inter-protocol/src/auction/scheduler.js:240)
 at apply ()
 at apply ()
 at dispatchToHandler (/bundled-source/.../node_modules/@endo/eventual-send/src/handled-promise.js:163)
 at win (/bundled-source/.../node_modules/@endo/eventual-send/src/handled-promise.js:511)
 at ()

2023-05-17T19:10:05.292Z SwingSet: vat: v39: ----- Auction.9  3 finalize
2023-05-17T19:10:05.312Z SwingSet: vat: v39: ----- AucBook.6  2 BOOK notifier 12010000/1000000
2023-05-17T19:10:05.341Z SwingSet: vat: v42: ----- LIQ.5  8 SCHEDULE { clockStep: { relValue: 20n, timerBrand: Object [Alleged: timerBrand] {} }, endRate: 6_500n, endTime: { absValue: 1_684_350_762n, timerBrand: Object [Alleged: timerBrand] {} }, lockTime: { absValue: 1_684_350_302n, timerBrand: Object [Alleged: timerBrand] {} }, startDelay: { relValue: 2n, timerBrand: Object [Alleged: timerBrand] {} }, startTime: { absValue: 1_684_350_602n, timerBrand: Object [Alleged: timerBrand] {} }, steps: 8n }
2023-05-17T19:10:05.342Z SwingSet: vat: v42: ----- LIQ.5  9 CASE 2: endTime is in the future or now so reschedule waking
2023-05-17T19:10:05.396Z SwingSet: vat: v42: ----- LIQ.5  10 SCHEDULE { clockStep: { relValue: 20n, timerBrand: Object [Alleged: timerBrand] {} }, endRate: 6_500n, endTime: { absValue: 1_684_350_762n, timerBrand: Object [Alleged: timerBrand] {} }, lockTime: { absValue: 1_684_350_302n, timerBrand: Object [Alleged: timerBrand] {} }, startDelay: { relValue: 2n, timerBrand: Object [Alleged: timerBrand] {} }, startTime: { absValue: 1_684_350_602n, timerBrand: Object [Alleged: timerBrand] {} }, steps: 8n }
2023-05-17T19:10:05.397Z SwingSet: vat: v42: ----- LIQ.5  11 CASE 2: endTime is in the future or now so reschedule waking
2023-05-17T19:10:05.439Z SwingSet: vat: v42: ----- LIQ.5  12 SCHEDULE { clockStep: { relValue: 20n, timerBrand: Object [Alleged: timerBrand] {} }, endRate: 6_500n, endTime: { absValue: 1_684_350_762n, timerBrand: Object [Alleged: timerBrand] {} }, lockTime: { absValue: 1_684_350_302n, timerBrand: Object [Alleged: timerBrand] {} }, startDelay: { relValue: 2n, timerBrand: Object [Alleged: timerBrand] {} }, startTime: { absValue: 1_684_350_602n, timerBrand: Object [Alleged: timerBrand] {} }, steps: 8n }
2023-05-17T19:10:05.439Z SwingSet: vat: v42: ----- LIQ.5  13 CASE 2: endTime is in the future or now so reschedule waking
2023-05-17T19:10:06.019Z SwingSet: vat: v42: ----- LIQ.5  14 SCHEDULE { clockStep: { relValue: 20n, timerBrand: Object [Alleged: timerBrand] {} }, endRate: 6_500n, endTime: { absValue: 1_684_350_762n, timerBrand: Object [Alleged: timerBrand] {} }, lockTime: { absValue: 1_684_350_302n, timerBrand: Object [Alleged: timerBrand] {} }, startDelay: { relValue: 2n, timerBrand: Object [Alleged: timerBrand] {} }, startTime: { absValue: 1_684_350_602n, timerBrand: Object [Alleged: timerBrand] {} }, steps: 8n }
2023-05-17T19:10:06.020Z SwingSet: vat: v42: ----- LIQ.5  15 CASE 2: endTime is in the future or now so reschedule waking
2023-05-17T19:10:06.058Z SwingSet: vat: v42: ----- LIQ.5  16 SCHEDULE { clockStep: { relValue: 20n, timerBrand: Object [Alleged: timerBrand] {} }, endRate: 6_500n, endTime: { absValue: 1_684_350_762n, timerBrand: Object [Alleged: timerBrand] {} }, lockTime: { absValue: 1_684_350_302n, timerBrand: Object [Alleged: timerBrand] {} }, startDelay: { relValue: 2n, timerBrand: Object [Alleged: timerBrand] {} }, startTime: { absValue: 1_684_350_602n, timerBrand: Object [Alleged: timerBrand] {} }, steps: 8n }
2023-05-17T19:10:06.058Z SwingSet: vat: v42: ----- LIQ.5  17 CASE 2: endTime is in the future or now so reschedule waking
2023-05-17T19:10:06.097Z SwingSet: vat: v42: ----- LIQ.5  18 SCHEDULE { clockStep: { relValue: 20n, timerBrand: Object [Alleged: timerBrand] {} }, endRate: 6_500n, endTime: { absValue: 1_684_350_762n, timerBrand: Object [Alleged: timerBrand] {} }, lockTime: { absValue: 1_684_350_302n, timerBrand: Object [Alleged: timerBrand] {} }, startDelay: { relValue: 2n, timerBrand: Object [Alleged: timerBrand] {} }, startTime: { absValue: 1_684_350_602n, timerBrand: Object [Alleged: timerBrand] {} }, steps: 8n }
```

…ad infinitum.

## Expected behavior

Case 2 recovers without looping so rapidly.

Fix should have a test that covers case 2.

### PR DESCRIPTION
**Pull request by turadg**
closes: #7775

## Description

Case 2 of auction recovery didn't have test coverage. In Docker testing it was hit. The bug is that it was meant to reschedule to the "startTime" of the _next_ nextAuctionSchedule. This does that and tries to make the logic and naming more clear.

### Testing Considerations

I tried to include an integration test but it will take longer than we have. I tested in the Docker test by trying to repro 7775 and it's not. I'll keep investigating but I think we should land this because it does fix a bug and it may unblock liquidation testing.

### CODE REVIEW

File: packages/inter-protocol/src/auction/scheduler.js [hunk 1]
```diff
@@ -199,12 +196,12 @@ export const makeScheduler = async (
         advanceRound();
         break;
       case 'endExactly':
-        if (advanceRound()) {
-          finishAuctionRound();
-        }
+        // do both the "during" and "after" behaviors
```
Comment (ivanlei) [inline packages/inter-protocol/src/auction/scheduler.js:197]: _comment_:

With the context of this bug it makes so much sense. Of course we always wanna finish an auction after `endExactly`.

File: packages/inter-protocol/test/vaultFactory/test-auction.js [hunk 2]
```diff
@@ -81,3 +81,46 @@ test('reset auction params', async t => {
     { startTime: { absValue: schedule2.startTime.absValue + 5n * freq } },
   );
 });
+
+// FIXME get this to induce CASE 2 of auction scheduling
```
Comment (ivanlei) [inline packages/inter-protocol/test/vaultFactory/test-auction.js]: please file an issue for this.

**Review by ivanlei — APPROVED** [review]
LGTM. I think it's worth a @Chris-Hibbert review as well.

File: packages/inter-protocol/src/auction/scheduler.js [hunk 3]
```diff
@@ -200,7 +200,7 @@ export const makeScheduler = async (
         finishAuctionRound();
         break;
       case 'after':
-        await finishAuctionRound();
+        finishAuctionRound();
```
Comment (kriskowal) [inline packages/inter-protocol/src/auction/scheduler.js:202]: Is this better served by `void` or sinking the promise elsewhere? Is `finishAuctionRound` still returning a promise? Could the error, if it occurs, be communicated to whomever is best positioned to react some other way than awaiting?

Comment (turadg) [reply packages/inter-protocol/src/auction/scheduler.js:202]: the use of `await` at all was driven by signaling back a failure of timer `.cancel()`. But that's not necessary: https://github.com/Agoric/agoric-sdk/blob/7842f2dbcb810c25f5cacd99c56ecf03d7386c77/packages/inter-protocol/src/auction/scheduler.js#L168-L170

Without that, there's no reason for any of `clockTick` to be async.

**Review by Chris-Hibbert — APPROVED** [review]

File: packages/inter-protocol/src/auction/scheduler.js (hunk 3 above)
Comment (kriskowal) [reply packages/inter-protocol/src/auction/scheduler.js:202]: That makes sense. Is `finishAuctionRound` still async?

Comment (turadg) [reply packages/inter-protocol/src/auction/scheduler.js:202]: no
