### PR TITLE
fix(agoric-cli): Thread rpcAddresses for Cosmos publishBundle

### LINKED ISSUE #5601: connection refused when deploying dapp-fungible-faucet to devnet
## Describe the bug

Following the getting started instructions, we get as far as [Deploy the contract](https://agoric.com/documentation/getting-started/start-a-project.html#deploy-the-contract-and-api) but it fails with `connection refused`.

I suspect the `tx swingset install-bundle` support from #4975 isn't integrated with `agoric start testnet`.

## To Reproduce
1. check out agoricdev-13 ; yarn ; yarn build
2. `agoric init demo15; cd demo15; agoric install`
3. `agoric start --reset testnet 8000 https://devnet.agoric.net/network-config`
4. `agoric deploy ./contract/deploy.js ./api/deploy.js`

```
$ agoric deploy ./contract/deploy.js ./api/deploy.js
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /home/connolly/projects/agoric/demo15/contract/deploy.js
agoric: deploy: Deploy script will run with Node.js ESM
agoric: deploy: /home/connolly/projects/agoric/agoric-sdk/golang/cosmos/build/agd tx swingset install-bundle --gas auto --gas-adjustment 1.2 --home /home/connolly/projects/agoric/demo15/_agstate/agoric-servers/testnet-8000/ag-cosmos-helper-statedir --keyring-backend test --from ag-solo --chain-id agoricdev-13 --yes @/tmp/agoric-cli-bundle--2328033-OEV9okvXA6GG/bundle.json
Error: post failed: Post "http://localhost:26657": dial tcp 127.0.0.1:26657: connect: connection refused
Usage:
  agd tx swingset install-bundle <JSON>/@<FILE>/- [flags]
```

## Expected behavior
contract gets deployed

## Platform Environment
 - _what OS are you using?_ Ubuntu _what version of Node.js?_ v16.14.2
 - _is there anything special/unusual about your platform?_ trying to deploy to devnet
 - _what version of the Agoric-SDK are you using? (run `git describe --tags --always`)_ bb2451d

cc @michaelfig @kriskowal

### PR DESCRIPTION
**Pull request by kriskowal**
closes: #5601

## Description

This change fixes #5601 which manifested as a failure to connect to a remote chain when publishing a bundle. This addresses the specific problem that publishBundle did not thread the `rpcAddresses` from the connection spec down to `agd`. This solution will be replaced with a system based on casting in cosmjs, with retries and feedback about installation success and failure #5460, but this addresses the problem until then.

### CODE REVIEW

**Comment by dckc** [comment]
@vejmelkam would you please try this out? @ktomascz? @anilhelvaci?

File: packages/agoric-cli/src/publish.js [hunk 1]
```diff
@@ -42,6 +42,17 @@
...
 const { details: X, quote: q } = assert;
 
+/**
+ * @template T
+ * @param {Array<T>} array
+ * @returns {T}
+ */
+const choose = array => {
+  assert(array.length > 0);
+  const index = Math.floor(array.length * Math.random());
```
Comment (dckc) [inline packages/agoric-cli/src/publish.js]: grumble... ambient authority...

**Review by dckc — APPROVED** [review]
I haven't verified that it lets folks deploy to devnet, but it looks worthwhile in any case.

**Comment by kriskowal** [comment]
> @vejmelkam would you please try this out? @ktomascz? @anilhelvaci?

Issue #5601 should already be mitigated by https://github.com/Agoric/dapp-fungible-faucet/pull/48 on `agoric-sdk/master`. That is to say, you should not see connection errors on `agoric-sdk/master` even without this change, because `agoric init` will use `dapp-fungible-faucet/main` as a template, and the template does not use `publishBundle` at this time.

To manually validate that this PR addresses the underlying problem requires invoking `agoric init --dapp-branch 5660-repro dapp-test` to use a back-dated version of the template, one which still uses `publishBundle`. That version has remaining issues with deployment because `publishBundle` does not retry if it misses a link in the block chain, but at least should not fail with `connection-refused`.

When we’ve ironed out the remaining issues with `publishBundle`, we intend to revisit the dapp-template such that it uses `publishBundle` again. @michaelfig and I have decided to refactor the contract deploy script in terms of `@agoric/deploy-script-helpers/install.js`, and to integrate bundle publishing there.

File: packages/agoric-cli/src/publish.js (hunk 1 above)
Comment (kriskowal) [reply packages/agoric-cli/src/publish.js]: Fair, and I can change this such that `random` is a power needed by `makeBundlePublisher`.

**Comment by ktomascz** [comment]
@dckc @kriskowal 

Hi, I have tested with the  `--dapp-branch 5660-repro dapp-test` and it seems to be looking up the correct node but the address is assembled incorrectly: 

```
➜  dapp-test git:(master) agoric deploy contract/deploy.js api/deploy.js
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /home/vscode/dapp-test/contract/deploy.js
agoric: deploy: Deploy script will run with Node.js ESM
agoric: deploy: /home/vscode/agoric-sdk/golang/cosmos/build/agd tx swingset install-bundle --gas auto --gas-adjustment 1.2 --home /home/vscode/dapp-test/_agstate/agoric-servers/testnet-8000/ag-cosmos-helper-statedir --node http://https://devnet.rpc.agoric.net:443 --keyring-backend test --from ag-solo --chain-id agoricdev-13 --yes @/tmp/agoric-cli-bundle--17567-ti44y7BVuJpX/bundle.json

Error: post failed: Post "http://https//devnet.rpc.agoric.net:443": dial tcp: lookup https: no such host
Usage:
  agd tx swingset install-bundle <JSON>/@<FILE>/- [flags]
```
  
Note the POST endpoint address: **"http://https//devnet.rpc.agoric.net:443"**  

When I am testing this SDK branch with the default (main) dapp I am getting the same error as described in [https://github.com/Agoric/agoric-sdk/issues/5341](https://github.com/Agoric/agoric-sdk/issues/5341)
I am not sure these two issues are even related.

**Comment by kriskowal** [comment]
> Hi, I have tested with the `--dapp-branch 5660-repro dapp-test` and it seems to be looking up the correct node but the address is assembled incorrectly:

Thank you for the reproduction. I’ll look into making the code that produces the address more sophisticated, to handle both the bare address and full URL cases.
