### PR TITLE
fix: adopt `VTRANSFER_IBC_EVENT` as an action-type

### LINKED ISSUE #9670: Consensus failure `VTRANSFER_IBC_EVENT` not recognized
## Describe the bug

When running a local test chain, the following chain-halting error is displayed when receiving an IBC transfer (`ics20-1`) packet that is monitored by the `x/vtransfer` package and forwarded to the JS VM:

```
agoriclocal  | 2024-07-09T06:49:03.736Z block-manager: END_BLOCK error: (Error#1)
agoriclocal  | Error#1: VTRANSFER_IBC_EVENT not recognized
agoriclocal  | 
agoriclocal  |   at performAction (packages/cosmic-swingset/src/launch-chain.js:610:13)
agoriclocal  |   at processActions (packages/cosmic-swingset/src/launch-chain.js:629:13)
agoriclocal  |   at async runKernel (packages/cosmic-swingset/src/launch-chain.js:670:5)
agoriclocal  |   at async endBlock (packages/cosmic-swingset/src/launch-chain.js:692:5)
agoriclocal  | 
agoriclocal  | portHandler threw (Error#1)
agoriclocal  | 6:49AM ERR CONSENSUS FAILURE!!! err="Error: (a string) not recognized"
```

## To Reproduce
1. Get the `agoric1...` address for a localchain account (`lca`) with `await E(lca).getAddress()`;
2. Register a transfer tap with `E(lca).monitorTransfers(transferTap)`
3. Send an IBC `ics20-1` token transfer to the chain with the recipient set to the`agoric1...` address obtained in step 1.
4. The local chain halts with the above error.

## Expected behavior
The transfer tap is executed without error, the tokens are deposited, and the chain proceeds to execute.

## Platform Environment
 - software version: Using Docker image `ghcr.io/agoric/agoric-sdk:upgrade-16-dev` image ID `e20c98d152c7`
 - special considerations: running under Docker desktop for macOS
 - what version of the Agoric-SDK are you using? `@agoric/access-token@0.4.22-u16.0-1-g07b01308ea`

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #9670

## Description
Ensure that the `VTRANSFER_IBC_EVENT` messages are plumbed through the `cosmic-swingset` layer.

### Security Considerations
Prevents chain halt when the `x/vtransfer` facilities are used.

### Testing Considerations
This bug was overlooked because end-to-end testing of this facility was not completed until a late stage. Earlier unit testing used mocks of the bridge device that did not have the same problematic behaviour. More automated end-to-end IBC testing in a close-to-production setting is needed.

### Upgrade Considerations
Fixing this `cosmic-swingset` behaviour does not require upgrade of any other components.

### CODE REVIEW

**Review by toliaqat — APPROVED** [review]

**Review by iomekam — APPROVED** [review]

File: packages/internal/src/action-types.js [hunk 1]
```diff
@@ -15,3 +15,4 @@ export const VBANK_BALANCE_UPDATE = 'VBANK_BALANCE_UPDATE';
 export const WALLET_ACTION = 'WALLET_ACTION';
 export const WALLET_SPEND_ACTION = 'WALLET_SPEND_ACTION';
 export const INSTALL_BUNDLE = 'INSTALL_BUNDLE';
+export const VTRANSFER_IBC_EVENT = 'VTRANSFER_IBC_EVENT';
```
Comment (gibson042) [inline packages/internal/src/action-types.js:18]: I'd like to see a comment above declaration of `IBC_EVENT` that following exports describe internal events for which handling code is expected in packages/cosmic-swingset/src/launch-chain.js.

**Review by gibson042 — APPROVED** [review]

File: packages/internal/src/action-types.js (hunk 1 above)
Comment (mhofman) [reply packages/internal/src/action-types.js:18]: I'm not sure why this action needs a comment any more than any other of the actions above? I'd be ok restructuring to highlight which actions come through the queue and which come through the pipe.

File: packages/vats/src/proposals/transfer-proposal.js [hunk 2]
```diff
@@ -1,6 +1,7 @@
 // @ts-check
 import { E } from '@endo/far';
-import { BridgeId as BRIDGE_ID, VTRANSFER_IBC_EVENT } from '@agoric/internal';
+import { BridgeId as BRIDGE_ID } from '@agoric/internal';
+import { VTRANSFER_IBC_EVENT } from '@agoric/internal/src/action-types.js';
```
Comment (mhofman) [inline packages/vats/src/proposals/transfer-proposal.js:4]: I am really confused why the transfer vat needs to be aware of the action type in the first place. This seems like a layering violation. No other action type leaks past the cosmic-swingset layer.
