### PR TITLE
fix(zoe): add zoe.installBundleID

### LINKED ISSUE #4563: add zoe.installBundleID(bundleID)
## What is the Problem Being Solved?

As part of the path towards contract/vat upgrade, I need Zoe to treat contract source code as `bundlecap` handles, not (large) bundle objects. With #4372 we have the kernel support, but we need to change the way Zoe manages the "installations" table, as well as change the API.

Zoe distinguishes an "installation" (akin to a class) from an "instance". Each installation has a single contract code bundle. Each instance of that installation has its own vat. The vat is launched with the ZCF bundle, and then Zoe tells ZCF to evaluate the contract bundle.

The current API is: `E(zoe).install(bundle)`. I want to change that to `E(zoe).install(bundleID)`, where `bundleID` is a string that includes a hash of the bundle contents. Zoe uses `vatAdminService` to look up this ID and retrieve a `bundlecap`, and then stores just a bundlecap. When Zoe tells ZCF which contract to use, it sends the bundlecap. ZCF is responsible for retrieving the actual source code (using `bundle = D(bundlecap).getBundle()`) so it can do the `importBundle()`. By leaving the contract's identity as a bundlecap until the last possible moment, we can reduce the size of messages, and give us some wiggle room to get Endo more involved in the process (eventually `importBundle(bundlecap)` should be a service provided by the vat environment, and overlap somehow with JS's native dynamic `import` expression).

For that to work, you must install the bundle first, by talking to the kernel. That means the host application needs to be involved. For the chain, that will require a new cosmos transaction type (#4396), which calls `controller.validateAndInstallBundle`. The contract deployment process must change: the deploy script needs a way to sign and send this transaction first, learn the bundleID, then send the ID to `E(zoe).install` instead of the bundle.

I'm currently expecting that this will need a flag day, which is always horrible. If we were ok with `E(zoe).install(bundleOrID)`, we could avoid it, but that will complicate the necessary Zoe changes. 

Unit test code must be changed too. In looking at the Zoe unit tests, a common pattern is:
```js
  const fakeVatAdminSvc = makeFakeVatAdmin(setJig).admin;
  const { zoeService: zoe } = makeZoeKit(fakeVatAdminSvc);
  const bundle = await bundleSource(contractRoot);
  const installation = await E(zoe).install(bundle);
```

that changes to:
```js
  const { admin: fakeVatAdminSvc, vatAdminState } = makeFakeVatAdmin(setJig);
  const { zoeService: zoe } = makeZoeKit(fakeVatAdminSvc);
  const bundle = await bundleSource(contractRoot);
  vatAdminState.installBundle('b1-zcftester', bundle);
  const installation = await E(zoe).install('b1-atomicswap');
```

(the Bundle ID is normally `b1-` followed by a SHA512 hash of the bundle's compartment map, but the fake vatAdminService allows any string, so we use a made-up ID for the contracts used in the test)

### PR DESCRIPTION
**Pull request by warner**
fix(zoe): add zoe.installBundleID

To transition Zoe from full contract bundles to bundlecaps, this adds a new
install API. `E(zoe).install(bundle)` is unchanged, but the new preferred
approach is `E(zoe).installBundleID(bundleID)`. This requires the
corresponding bundle to be installed with the swingset kernel's
vatAdminService, either before or after `installBundleID()` (zoe will wait
forever for the bundle to be installed).

Zoe `Installation` objects retain their `getBundle()` method to accomodate
dapp tests that have not switched to the new approach, but it throws an error
if used on a new bundleID-based installation. A new method named
`E(zoe).getBundleIDFromInstallation(allegedInstallation)` can be used to both
validate the installation and get back the bundleID, but it throws on the old
bundle-based installations.

Internally, the installationStorage.unwrapInstallation now returns either 
`{ bundle, installation }` or `{ bundlecap, bundleID, installation }`. ZCF's
`evaluateContract()` method accepts either a bundlecap or a full bundle.

closes #4563

### CODE REVIEW

**Comment by warner** [comment]
This changes a handful of Zoe tests (to confirm that the new behavior works). It does not yet change the rest of the zoe tests, nor the tests elsewhere in agoric-sdk, nor the tests in dapps that live outside agoric-sdk. I need to change all of those before I can remove the old `E(zoe).install` API.

I also made a small swingset change to export a few types that are now part of the Zoe API (`BundleID` and a module type). This seems necessary to let `packages/vats/` pass typechecking.

File: packages/SwingSet/src/index.js [hunk 1]
```diff
@@ -12,3 +12,6 @@ export { buildTimer } from './devices/timer.js';
 export { buildBridge } from './devices/bridge.js';
 export { default as buildCommand } from './devices/command.js';
 export { buildPlugin } from './devices/plugin.js';
+
+/** @typedef { import('./types').BundleID } BundleID */
```
Comment (mhofman) [inline packages/SwingSet/src/index.js]: I'm gonna be stubborn, but I'd still prefer using extensions.
```suggestion
/** @typedef { import('./types.js').BundleID } BundleID */
```

File: packages/zoe/src/contractFacet/zcfZygote.js [hunk 2]
```diff
@@ -340,7 +340,15 @@ export const makeZCFZygote = (
    * @type {ZCFZygote}
    * */
   const zcfZygote = {
-    evaluateContract: bundle => {
+    evaluateContract: bundleOrBundlecap => {
+      let bundle;
+      if (passStyleOf(bundleOrBundlecap) === 'remotable') {
+        const bundlecap = bundleOrBundlecap;
+        // @ts-ignore powers is not typed correctly: https://github.com/Agoric/agoric-sdk/issues/3239s
```
Comment (erights) [inline packages/zoe/src/contractFacet/zcfZygote.js]: @turadg recommends that we prefer `@ts-expect-error` when that works as well. That way, if it stops being necessary, it'll let us know. Also, typo
```suggestion
        // @ts-ignore powers is not typed correctly: https://github.com/Agoric/agoric-sdk/issues/3239
```

File: packages/zoe/src/zoeService/installationStorage.js [hunk 3]
```diff
@@ -3,49 +3,82 @@
...
-    assert(
-      installations.has(installation),
-      X`${installation} was not a valid installation`,
-    );
+  /** @type {InstallBundleID} */
+  const installBundleID = async bundleID => {
+    assert.typeof(bundleID, 'string', `a bundle ID must be provided`);
+    // this waits until someone tells the host application to store the
+    // bundle into the kernel, with controller.validateAndInstallBundle()
+    const bundlecap = await getBundlecapForID(bundleID);
```
Comment (erights) [inline packages/zoe/src/zoeService/installationStorage.js]: I will here admit to an irrational bias, rather than requesting a change.

The idea of a long-term-by-design postponement being done with an `await`, rather than an explicit `E.when` makes me nervous. The callbacks of an `E.when` are distinct js function objects. The implicit callback of an `await` is the unreified continuation of the function. However, I don't see a concrete disadvantage of the long term `await`.
   * both are captured by snapshot with full fidelity.
   * both are reproduced by replay with full fidelity. Therefore
      * both are equally supportive of manchurian mischief
      * including upgrading to a new version of XS that can't read old snapshots
   * neither will ever need to be virtual, because promises can't
   * neither will ever need to survive a normal upgrade, because promises don't.

So, no change suggested.

Comment (erights) [reply packages/zoe/src/zoeService/installationStorage.js]: But please at least put the AWAIT comment after this line.

**Review by erights — APPROVED** [review]
Why `*Bundlecap` instead of `*BundleCap`? Since none of this has been merged yet, if we're going to rename it, now is the ideal time.

File: packages/zoe/src/contractFacet/zcfZygote.js (hunk 2 above)
Comment (turadg) [reply packages/zoe/src/contractFacet/zcfZygote.js]: 👍, modulo that as yet [sometimes the IDE and CLI/CI will disagree about the set of errors](https://github.com/Agoric/agoric-sdk/issues/4620). In those cases it's better to use ts-ignore than to have either of them complain. After that issue is resolved we could global replace ts-ignore with ts-expect-error and see which are gone.

In this particular case I think we're better off fixing the types: 1b043d284c13aa3679db05d6f1be42b43a2bafc3 I didn't push directly to this branch because I didn't know the norms here around that and I wasn't certain I got it right.

File: packages/SwingSet/src/index.js (hunk 1 above)
Comment (turadg) [reply packages/SwingSet/src/index.js]: Note that when VS Code offers to import, it does so without the `.js`, even with the `typescript.preferences.importModuleSpecifierEnding": "js"` setting.

Comment (mhofman) [reply packages/SwingSet/src/index.js]: Interesting, I swear it does for me. We should find what setting triggers this.

Comment (turadg) [reply packages/SwingSet/src/index.js]: Oh good! We shouldn't have to decide based on limits of tooling. Once we have a setting we agree on we can distribute with https://github.com/Agoric/agoric-sdk/pull/4418

Comment (mhofman) [reply packages/SwingSet/src/index.js]: Well apparently I must have muscle memory and add those automatically as I can't seem to reproduce anymore.

File: packages/zoe/src/zoeService/installationStorage.js (hunk 3 above)
Comment (warner) [reply packages/zoe/src/zoeService/installationStorage.js]: I'm happy to use `.then` here instead. Does your bias sort of feel that `await` is for things that will happen soon, whereas `.then` is for things that happen much later?

I don't think either form is better than the other w.r.t. upgrade or snapshots. Having a name for the second half helps to clarify its purpose, sometimes, but mostly when there might be another code path that leads into it (as in your comments in #4545 and the three different ways to obtain a promise for the ZCF bundle).

One style question: making both `installBundle` and `installBundleID` be `async` seems like a good idea to emphasize their parallelism (also they're both mostly invoked from remote vats, `E(zoe).install*`, so it's not like the caller gets a choice). Once `installBundleID` is `async`, then it seemed awkward to build up the `.then` and return a Promise instead of using `await` inline. If I change the `await` to `.then`, should I also change `installBundleID` to not be `async`? And then should I change `installBundle` to also not be async, and be ok with `installBundle` being actually-sync (and not returning a Promise) but `installBundleID` always returns a Promise? And, now they have different error behaviors if you e.g. pass in a bad argument (synchronous throw vs promise rejection).

File: packages/SwingSet/src/index.js (hunk 1 above)
Comment (warner) [reply packages/SwingSet/src/index.js]: Oh, I thought I got red squiggles from vscode when I did that. I prefer extensions too, I'll look into it.

File: packages/zoe/src/zoeService/installationStorage.js (hunk 3 above)
Comment (erights) [reply packages/zoe/src/zoeService/installationStorage.js]: Please do *not* use `.then`. It is not safe against reentrancy. And least `await` is safe, and so switching from `await` to `.then` is a decrease in robustness. When you would use `.then`, use `E.when` instead.

If `await` and `E.when` are otherwise tied, a tie breaker is that `E.when` gives us deep stacks on errors. We cannot reasonably make that happen for `.then` or `await` without changes to the underlying engine.

Comment (erights) [reply packages/zoe/src/zoeService/installationStorage.js]: I do not consider it awkward for an `async` function to use explicit promise logic rather than `await`. In fact, I think we should do exactly this more often. In the absence of `await`, as you note, the meaning of `async` is to promise-ify the outcome, turning both success and errors into promises.

I will admit that this particular combination is one that other developers may find surprising when they first see it. In this case, I don't think that's a big hurdle.

File: packages/zoe/src/contractFacet/zcfZygote.js (hunk 2 above)
Comment (erights) [reply packages/zoe/src/contractFacet/zcfZygote.js]: >  I didn't push directly to this branch because I didn't know the norms here around that and I wasn't certain I got it right.

I defer to @warner on such norms. But my take:

Don't push directly to someone else's branch. Create a PR based on their's, send it to them to review, and mention that PR in a review comment on their original PR. If they like it, they should feel free to merge it into their PR without further consulting you.

Comment (warner) [reply packages/zoe/src/contractFacet/zcfZygote.js]: yeah, either make a meta-PR, or use github's "suggested change" mechanism.. pushing to my branch would surprise/confuse my local workspace and/or workflow

Comment (turadg) [reply packages/zoe/src/contractFacet/zcfZygote.js]: 👌 no surprise pushing to PR branches

for something that's too small to make a new PR but too spread out to make a bunch of suggested changes, WDYT of sharing the commit as above? 1b043d284c13aa3679db05d6f1be42b43a2bafc3  Then you can just `git cherry-pick 1b043d2` if you want it.

File: packages/zoe/src/zoeService/installationStorage.js (hunk 3 above)
Comment (warner) [reply packages/zoe/src/zoeService/installationStorage.js]: Note to folks following along at home (because I had to ask too): the concern with `.then` is a hostile provider of the object that you assume behaves like a Promise. It might be a non-Promise with a `.then` method that does something synchronously. It might be a real Promise but with an overriden `.then` method. Using `await` and `E.when` protects against this malice.

In this case, `getBundleCapForID` is coming from the rest of Zoe, but I'm happy to stick with something that maintains caution in any situation.

I'll stick with `await`, add an `// AWAIT` comment, and leave both functions as `async`.

File: packages/zoe/src/contractFacet/zcfZygote.js (hunk 2 above)
Comment (turadg) [reply packages/zoe/src/contractFacet/zcfZygote.js]: @warner I notice TS failures in https://github.com/Agoric/agoric-sdk/runs/5300164567?check_suite_focus=true

If that's due to https://github.com/Agoric/agoric-sdk/commit/1b043d284c13aa3679db05d6f1be42b43a2bafc3 no objections here to punting that.

File: packages/zoe/src/zoeService/internal-types.js [hunk 4]
```diff
@@ -56,12 +56,14 @@
...
- * Assert the installation is known, and return the bundle and
+ * Assert the installation is known, and return the bundle/bundlecap and
  * installation
  *
  * @param {ERef<Installation>} installationP
  * @returns {Promise<{
- *   bundle: SourceBundle,
+ *   bundle?: SourceBundle,
+ *   bundleCap?: BundleCap,
+ *   bundleID?: BundleID,
```
Comment (turadg) [inline packages/zoe/src/zoeService/internal-types.js:66]: non-blocking but FYI, we can use unions to convey mutual exclusion. It has the advantage over optionals of guaranteeing to consumer that one of them is defined. E.g.,
```ts
type BundleOrBundleCap = {bundle: SourceBundle} | {bundleCap: BundleCap, bundleId: BundleID};
```
or in jsdoc,
```js
/** @typedef  { {bundle: SourceBundle} | {bundleCap: BundleCap: bundleId} } BundleOrBundleCap */
```

then intersection for the return type
```ts
Promise<BundleOrBundleCap & {installation: Installation}>
```

Comment (warner) [reply packages/zoe/src/zoeService/internal-types.js:66]: aye, thanks, will look into that later, there's another `BundleOrBundleCap` floating around which doesn't include the `bundleID` that I don't want to collide with

Comment (turadg) [reply packages/zoe/src/zoeService/internal-types.js:66]: > collide with 

Want to point out that the possibility of collisions is due to ambient types. Because TypeScript is structurally typed, there's usually little problem with redundant definitions. (Besides code maintenance/documentation.)
