### PR TITLE
only hold vaults that aren't settled

### LINKED ISSUE #5531: closing a vault doesn’t remove it from the vaultManager
## Describe the bug

Closing a vault leaves it in the vault manager. This prevents GC.

More significantly, because `liquidateAll()` iterates over all held vaults and a vault can't transition after being CLOSED, an exception is thrown if any vault has been closed:
```
Vault cannot transition from closed to liquidating
```

Related, it doesn't currently trigger the manager to `updateMetrics`.

## Expected behavior
`liquidateAll` does not depend on whether vaults have been closed.

Any vault in the CLOSED phase is not held by its old vault manager.

Moreover nothing is held in the vault manager that can't accrue interest. So LIQUIDATED is not held either. 

Design: vault manager only holds vaults that:
- can accrue interest
- can be liquidated

### PR DESCRIPTION
**Pull request by turadg**
closes: #5531

## Description

This introduces the concept of "settled", which means that they have no debts remaining. When vaults are liquidated, they are settled even though they may have had a shortfall, because the contract covered the shortfall using the reserve. Vaults can also be settled by closure.

Once a vault is settled, the manager has no more concern with it. Vault manager was removing vaults in the liquidation case and not the closure case. This makes it remove vaults upon settling.

### Security Considerations

`prioritizedVaults` adds a new `hasVaultByAttributes` lookup. This authority for information is subsumed by the extant `removeVaultByAttributes`.

### Documentation Considerations

Added a file comment for vaultManager explaining its scope and the invariant on what it retains.

### Testing Considerations

New tests. Updates to existing tests.

### CODE REVIEW

File: packages/run-protocol/src/vaultFactory/vaultDirector.js [hunk 1]
```diff
@@ -292,15 +293,16 @@ const machineBehavior = {
         debtMint.burnLosses(harden({ RUN: toMint }), mintSeat);
         throw e;
       } finally {
+        // Not that if this assertion may fail because of an error in the
```
Comment (Chris-Hibbert) [inline packages/run-protocol/src/vaultFactory/vaultDirector.js]: If this correction isn't right, please reword.
```suggestion
        // Note that if this assertion may fail because of an error in the
```

File: packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js [hunk 2]
```diff
@@ -33,7 +33,7 @@ import { makeTracer } from '../makeTracer.js';
 
 const { quote: q, details: X } = assert;
 
-const trace = makeTracer('XykAmm');
+const trace = makeTracer('XykAmm', false);
```
Comment (Chris-Hibbert) [inline packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js:36]: I'm approving these this time, but I'd prefer a separate tiny PR that just turns tracers off. I'll approve a PR that does that any time.

File: packages/run-protocol/src/vpool-xyk-amm/addPool.js [hunk 3]
```diff
@@ -47,15 +47,6 @@ export const makeAddIssuer = (
...
     await zcf.saveIssuer(secondaryIssuer, keyword);
-    const issuer = zcf.getIssuerForBrand(secondaryBrand);
-    console.log(
-      'Saved issuer',
-      secondaryIssuer,
-      'to keyword',
-      keyword,
-      'and got back',
-      issuer,
-    );
```
Comment (Chris-Hibbert) [inline packages/run-protocol/src/vpool-xyk-amm/addPool.js:58]: Please put this in a separate PR.

**Review by Chris-Hibbert — CHANGES_REQUESTED** [review]

File: packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js (hunk 2 above)
Comment (turadg) [reply packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js:36]: Is that a personal preference or a repo policy? I don't see anything about it in https://github.com/Agoric/agoric-sdk/blob/master/CONTRIBUTING.md

If the motivation is for the git history and blame attribution, I share that goal and that's why this PR has a separate tiny commit for the tracer changes. [d3a8dc9](https://github.com/Agoric/agoric-sdk/pull/5538/commits/d3a8dc9931d1551e08cf5c591a7212c48103c8ec)

If it's for a different reason, lemme know. I'll try to document it.

File: packages/run-protocol/src/vpool-xyk-amm/addPool.js (hunk 3 above)
Comment (turadg) [reply packages/run-protocol/src/vpool-xyk-amm/addPool.js:58]: Why? Same reason as https://github.com/Agoric/agoric-sdk/pull/5538#discussion_r895083300 ?

File: packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js (hunk 2 above)
Comment (Chris-Hibbert) [reply packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js:36]: Yes, the motivation is for the git history and blame attribution.  How does a separate commit make a difference? Were you planning to not squish when merging? There are 6 commits currently, so would that mean squishing everything else and leaving one commit separate? that doesn't seem sustainable for reviewers or PR authors. Wouldn't it be much simpler to have a separate tiny PR?

File: packages/run-protocol/src/vpool-xyk-amm/addPool.js (hunk 3 above)
Comment (Chris-Hibbert) [reply packages/run-protocol/src/vpool-xyk-amm/addPool.js:58]: Basically the same, but it's a more substantive change, and in the AMM. I don't think this is a trivial enough unrelated change to leave in a PR for vaults.

File: packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js (hunk 2 above)
Comment (turadg) [reply packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js:36]: > Were you planning to not squish when merging? 

Correct. That's why I've been careful to separate independent changes into different commits.

> Wouldn't it be much simpler to have a separate tiny PR?

It would be more work on top of what I've already done to separate the commits. It would be simpler in that we wouldn't have this debate on this PR but in the long run it means more work in general if we can't allow a PR to have multiple independent commits merged. It's worth getting aligned as an org on what is expected and allowed. (I say allowed because the request here was made as a blocking review, such that if someone else approves it the PR still can't be merged).

The CONTRIBUTING.md says,
> We favor "Squash and merge" (which requires the PR title to be a conventional commit) since it requires the least careful attention, especially when there are appended follow-up changes, but it's not the only tool in the toolbox.
> …
> We've also squashed follow-up commits manually (through an interactive rebase) after a PR had been approved and tests were passing, then landed the stack with "Rebase and merge" or "Create merge commit".

The latter is what I've done here.

File: packages/run-protocol/src/vaultFactory/vaultManager.js [hunk 4]
```diff
@@ -544,26 +556,54 @@ const managerBehavior = {
    * @param {NormalizedDebt} oldDebtNormalized
    * @param {Amount<'nat'>} oldCollateral
    * @param {VaultId} vaultId
+   * @param {import('./vault.js').VaultPhase} vaultPhase at the end of whatever change updatied balances
```
Comment (Chris-Hibbert) [inline packages/run-protocol/src/vaultFactory/vaultManager.js]:
```suggestion
   * @param {import('./vault.js').VaultPhase} vaultPhase at the end of whatever change updated balances
```

**Review by Chris-Hibbert — APPROVED** [review]
