### PR TITLE
fix(fast-usdc): consider encumberedBalance in withdrawCalc

### LINKED ISSUE #10856: withdraw calculations don't take encumbered balance into account
## Describe the bug

The justification here doesn't seem to take encumbered balance into account

https://github.com/Agoric/agoric-sdk/blob/44f449b7fa1c9b8051d98e567c350fce37e33f83/packages/fast-usdc/src/exos/liquidity-pool.js#L321-L322

## To Reproduce

This case is at least untested:

 1. Alice deposits 10 USDC for 10 FastLP
 2. Bob initiates an advance of 6, reducing the pool to 4
 3. Alice proposes to withdraw 7 USDC
 4. Bob's advance is settled

## Expected behavior

Alice's proposal to withdraw fails with a diagnostic that suggests trying again, as the pool should refill shortly.

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

### PR DESCRIPTION
**Pull request by dckc**
closes: #10856

## Description

 - [x] add contract test to confirm the bug
 - [x] fix pool-share-math; update tests
 - [x] update liquidity-pool exo

### Security Considerations

Prevents contract from becoming unavailable due to an inconsistent state.

### Scaling / Documentation Considerations

n/a

### Testing Considerations

 - added a contract test
 - added a pool-share-math unit test

### Upgrade Considerations

not yet deployed

### CODE REVIEW

File: packages/fast-usdc/src/pool-share-math.js [hunk 1]
```diff
@@ -112,6 +152,8 @@ export const withdrawCalc = (shareWorth, { give, want }) => {
   const { denominator: sharesOutstanding, numerator: poolBalance } = shareWorth;
   !isGTE(want.USDC, poolBalance) ||
     Fail`cannot withdraw ${q(want.USDC)}; only ${q(poolBalance)} in pool`;
+  isGTE(unencumberedBalance, want.USDC) ||
+    Fail`cannot withdraw ${q(want.USDC)}; ${q(encumberedBalance)} is in use; stand by for pool to return to ${q(poolBalance)}`;
```
Comment (samsiegart) [inline packages/fast-usdc/src/pool-share-math.js:156]: I'm not sure what to do about this but I'm pretty sure these Amounts show up as `[an Object]` or some such thing on the user level, which I assume this messaging is intended for, so maybe render the values instead?

File: packages/fast-usdc/test/fast-usdc.contract.test.ts [hunk 2]
```diff
@@ -780,6 +785,51 @@ test.serial('STORY05(cont): LPs withdraw all liquidity', async t => {
...
+  // 2. Bob initiates an advance of 6, reducing the pool to 4
+  const bob = makeCustomer('Bob', cctp, txPub.publisher, feeConfig);
+  const bridgePos = snapshot();
+  const sent = await bob.sendFast(t, 6_000_000n, 'osmo123bob5');
+  await eventLoopIteration();
+  bob.checkSent(t, since(bridgePos));
+
+  // 3. Alice proposes to withdraw 7 USDC
+  await t.throwsAsync(E(alice).withdraw(t, 0.7), {
+    message: /cannot withdraw .* in use; stand by/,
```
Comment (samsiegart) [inline packages/fast-usdc/test/fast-usdc.contract.test.ts]: Related to my comment above, possibly make this expected string more explicit

File: packages/fast-usdc/test/pool-share-math.test.ts [hunk 3]
```diff
@@ -72,7 +76,7 @@ test('withdrawal after deposit OK', t => {
   });
   mustMatch(proposal, shapes.withdraw);
 
-  const actual = withdrawCalc(state1, proposal);
+  const actual = withdrawCalc(state1, proposal, pDep.give);
```
Comment (samsiegart) [inline packages/fast-usdc/test/pool-share-math.test.ts:79]: I know this already existed but I'm not sure what `pDep` means... "proposal for deposit"? It's not immediately clear what the connection is between that and the pool allocation. Could we infer it from `shareWorth` instead?

File: packages/fast-usdc/src/pool-share-math.js (hunk 1 above)
Comment (dckc) [reply packages/fast-usdc/src/pool-share-math.js:156]: `q(...)` renders them. for [example](https://github.com/Agoric/agoric-sdk/actions/runs/12901768576/job/35974442069?pr=10870#step:14:1881):

```
RemoteError(error:captp:far-zoeTest#20001)#3: cannot withdraw ***"brand":"[Alleged: USDC brand]","value":"[7000000n]"***; ***"brand":"[Alleged: USDC brand]","value":"[5879999n]"*** is in use; stand by for pool to return to ***"brand":"[Alleged: USDC brand]","value":"[10000001n]"***
```

File: packages/fast-usdc/test/fast-usdc.contract.test.ts (hunk 2 above)
Comment (dckc) [reply packages/fast-usdc/test/fast-usdc.contract.test.ts]: OK.

I'm generally reluctant to commit to specific error messages in our API, but don't suppose I have a solid justification.

File: packages/fast-usdc/test/pool-share-math.test.ts (hunk 3 above)
Comment (dckc) [reply packages/fast-usdc/test/pool-share-math.test.ts:79]: > It's not immediately clear what the connection is between [proposal for deposit] and the pool allocation.

The connection is that `proposal.give` is what the deposit handler transfers into the pool:

https://github.com/Agoric/agoric-sdk/blob/3c74e530472f29d762b6252af5322ca8aba48a87/packages/fast-usdc/src/exos/liquidity-pool.js#L266-L269

> Could we infer it from `shareWorth` instead?

Not quite; `shareWorth.numerator` is off by 1E-6 USDC so that it never goes to zero. It's a bit of a design wart, but I haven't figured out a better way.

**Review by samsiegart — APPROVED** [review]
