### PR TITLE
fix(notifier): For durable `fail()`, persist the reason rather than a rejected promise

### LINKED ISSUE #7009: Durable publish kits cannot store failure reasons
## Describe the bug
As encountered in #6969, the `fail` method of a durable publish kit constructs a rejected promise that is not durable and therefore not accepted by `advanceDurablePublishKit`. This wasn't caught by testing because the fake virtual reference manager relaxes durability constraints: https://github.com/Agoric/agoric-sdk/blob/8beeeab33b815e39cf02581c5d3ec8ce417f0381/packages/swingset-liveslots/tools/fakeVirtualSupport.js#L256-L269

## To Reproduce
```js
const makeDurablePublishKit = prepareDurablePublishKit(baggage, 'DurablePublishKit');
const { publisher, subscriber } = makeDurablePublishKit();
publisher.fail('reason');
// => Error: Cannot accept non-durable rejection
```

## Expected behavior
"reason" becomes the terminal failure value.

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #7009

## Description

Send the `fail` reason directly to `advanceDurablePublishKit` so it can persist the value _before_ wrapping it in a rejected promise to resolve the outstanding tail promise.

### Security Considerations

None.

### Scaling Considerations

No change.

### Documentation Considerations

Not applicable.

### Testing Considerations

#6523 should make it possible to update the durable publish kit tests for realistic durability constraints.

### CODE REVIEW

File: packages/notifier/src/publish-kit.js [hunk 1]
```diff
@@ -316,20 +316,21 @@ const provideDurablePublishKitEphemeralData = (state, facets) => {
...
   const { valueDurability, status } = state;
   if (status !== 'live') {
     throw new Error('Cannot update state after termination.');
   }
-  if (done || valueDurability === 'mandatory') {
+  const done = targetStatus !== 'live';
+  if (targetStatus === 'failed') {
+    canBeDurable(value) ||
+      Fail`Cannot accept non-durable fail reason: ${value}`;
+  } else if (done || valueDurability === 'mandatory') {
```
Comment (gibson042) [inline packages/notifier/src/publish-kit.js:332]: I'm not sure it's worth keeping a distinct message for `fail(nonDurableReason)` vs. `finish(nonDurableFinalValue)` and `publish(nonDurableValue)`. If not, we could simplify this.
```suggestion
  if (done || valueDurability === 'mandatory') {
```

File: packages/notifier/src/publish-kit.js [hunk 2]
```diff
@@ -316,20 +316,21 @@ const provideDurablePublishKitEphemeralData = (state, facets) => {
...
     canBeDurable(value) || Fail`Cannot accept non-durable value: ${value}`;
```
Comment (gibson042) [inline packages/notifier/src/publish-kit.js]: I'm not sure it's worth keeping a distinct message for `fail(nonDurableReason)` vs. `finish(nonDurableFinalValue)` and `publish(nonDurableValue)`. If not, we could simplify this.
```suggestion
  if (done || valueDurability === 'mandatory') {
    canBeDurable(value) || Fail`Cannot accept non-durable value: ${value}`;
```

Comment (turadg) [reply packages/notifier/src/publish-kit.js]: The stack trace should show which case it was. The only value I can think of is for a test to be able to verify which failure, but it could do that by exercising both paths. So +1 to the simplification.

File: packages/notifier/src/publish-kit.js [hunk 3]
```diff
@@ -316,20 +316,21 @@ const provideDurablePublishKitEphemeralData = (state, facets) => {
  * Extends the sequence of results.
  *
  * @param {{state: DurablePublishKitState, facets: PublishKit<*>}} context
- * @param {boolean} done
  * @param {any} value
- * @param {any} [rejection]
+ * @param {DurablePublishKitState["status"]} [targetStatus]
```
Comment (turadg) [inline packages/notifier/src/publish-kit.js]: 🙌 types

**Review by turadg — APPROVED** [review]

File: packages/notifier/src/publish-kit.js (hunk 3 above)
Comment (erights) [reply packages/notifier/src/publish-kit.js]: This is a type syntax I have not seen before. What's the difference between
```js
DurablePublishKitState["status"]
```
vs
```js
DurablePublishKitState.status
```
or
```js
DurablePublishKitState['status']
```
?

Comment (turadg) [reply packages/notifier/src/publish-kit.js]: The two quotes are just stylistic. Our Prettier config is single quotes but it doesn't reach into jsdoc.

The `.` is reserved for referencing a namespace.

https://www.typescriptlang.org/play?#code/C4TwDgpgBAysCGxoF4oG8BQUoDMD2eAXFAHYCuAtgEYQBOANFlFfLcQM7C0CWJA5gG4MAXwwYAxnhKco7XnwA2EYnEQQA2gHJ8eTQF0oqAExDJ04FAAmeMlSUqESdQCIdzg8dNSZJeBQjsYPDiyrCOEAB0OoZQJhhAA
