### PR TITLE
fix: adding dup entries to virtual sets is OK

### LINKED ISSUE #7234: virtual/durable Sets throw when adding duplicate item, should ignore silently
## Describe the bug

In fixing #7231 and adding new tests, I noticed that our virtual/durable SetStore collections violate [our spec](https://github.com/Agoric/agoric-sdk/blob/34ed9a6b0e63988bfeda3558735062b1f99a0a9f/packages/store/src/types.js#L176-L180) and throw an error when you try to add the same item twice: 

```js
const s = makeScalarBigSetStore('label');
s.add(47);
s.add(47); // throws 
```

## Expected behavior

The second `add` should be silently ignored.

We should check both strong and weak Sets for this behavior.

### PR DESCRIPTION
**Pull request by FUDCo**
Fixes #7234

### CODE REVIEW

File: packages/swingset-liveslots/src/collectionManager.js [hunk 1]
```diff
@@ -348,6 +348,12 @@ export function makeCollectionManager(
       updateEntryCount(1);
     }
 
+    function addToSet(key) {
+      if (!has(key)) {
+        init(key, null);
```
Comment (warner) [inline packages/swingset-liveslots/src/collectionManager.js]: `init` starts with its own `has()` call, so duplicate adds will cause two DB reads before doing the write.

I don't think that's worth optimizing now (it would require adding a `alreadyChecked` option to `init`, or splitting `init` into `checkedInit` and `uncheckedInit`, or something), but if duplicate Set additions turn out to be a common thing, we could improve it in the future.

Maybe add a one-line comment, `// TODO: optimize out the duplicate has() call`, so we'll know where to look.

**Review by warner — APPROVED** [review]
looks good! glad it was as quick as we'd hoped.

File: packages/swingset-liveslots/src/collectionManager.js (hunk 1 above)
Comment (FUDCo) [reply packages/swingset-liveslots/src/collectionManager.js]: Yeah, this bugged me too, but other code paths already get stuck with extraneous `has` calls so I figured this actually wasn't as big a change as one might think.  It's one of the reasons I dislike the `init` vs. `set` convention.

I will add a suitable comment and then land the thing.

File: packages/swingset-liveslots/src/collectionManager.js [hunk 2]
```diff
@@ -348,6 +348,15 @@ export function makeCollectionManager(
       updateEntryCount(1);
     }
 
+    function addToSet(key) {
```
Comment (erights) [inline packages/swingset-liveslots/src/collectionManager.js]:
```suggestion
    const addToSet = key => {
```

**Review by erights — CHANGES_REQUESTED** [review]
Please don't write new functions as `function` functions without a reason.

File: packages/swingset-liveslots/src/collectionManager.js (hunk 2 above)
Comment (FUDCo) [reply packages/swingset-liveslots/src/collectionManager.js]: Please recheck.

Still grumpy that I can't write `const addToSet = (key) => {` without whining from prettier.  Being consistent about argument list delimiters would address much of my concern about the legibility of this style.

File: packages/swingset-liveslots/src/collectionManager.js (hunk 1 above)
Comment (FUDCo) [reply packages/swingset-liveslots/src/collectionManager.js]: Since I was already in there fixing MarkM's style whinge, I went ahead and fixed this too.

File: packages/swingset-liveslots/src/collectionManager.js (hunk 2 above)
Comment (erights) [reply packages/swingset-liveslots/src/collectionManager.js]: Yes, I am sympathetic to this issue. OTOH, there are too many times we write one-arg callbacks essentially as part of a repeated syntactic idiom like `.map(x => something)` or `E.when(p, f => something)`. For all these to pay the readability cost of more punctuation would be worse.

If there's a setting that lets the common idioms stay clean while allowing the others, that may be interesting. But last I looked there isn't.

**Review by erights — APPROVED** [review]
LGTM

File: packages/swingset-liveslots/src/collectionManager.js (hunk 2 above)
Comment (FUDCo) [reply packages/swingset-liveslots/src/collectionManager.js]: I'd say just allow the parens around a single arg to be optional.  When one is writing an inline function expression that's going be, e.g., passed as a parameter, it makes sense to be terse.  But when writing something that's intended to be a top-level function definition, I find the non-orthogonality to be aggravating.

Comment (erights) [reply packages/swingset-liveslots/src/collectionManager.js]: optional means it wont be normalized, and for the inline cases, some will and some won't, making readability even worse than normalizing on the wrong option.

Comment (FUDCo) [reply packages/swingset-liveslots/src/collectionManager.js]: I think I just don't weight that normalization nearly as highly as you do.  There are too many cases where the normalized form makes my eyes bleed.  I'll favor legibility over normalization any day of the week in cases where normalization makes the code harder to read (which it sometimes definitely does).  Consistency is good for legibility, and normalization _does_ ensure consistency, but consistency per se is insufficient. We could, for example, have a rule that that says to have one lexical token per line with no indentation, which would be consistent but also insane.  I fundamentally don't think it's a problem to have human aesthetic judgement driving some of how we use whitespace and punctuation for formatting.  We already use human aesthetic judgement with respect to countless other aspects of our code, such as the order that things are placed in a module, the names of functions, methods, and variables, which lines of code need comments vs. which can do without them, and much more, not to mention the design of APIs themselves.  There are even some uses of whitespace that prettier still allows you to use your own judgement on, such as where to insert blank lines to separate one bit of code from an adjacent, less related bit of code (code paragraphs?).  I'm actually pretty obsessive about formatting consistency myself -- my beef with prettier is often not so much that it's opinionated but that some of its opinions are just wrong -- but sometimes I'm following a rule that isn't easily captured by automation (such as, to return to where we started: Inline function expression with a single arg, leaving off the parens is more legible; definition of a top level function with a single arg, adding parens around the arg is more legible -- however, the determination as what falls into which category is subjective and so automation may not be feasible, but I trust the programmer on this, because it's really about expressing their intent anyway).
