### PR TITLE
test(ansible): Improve failure output

### LINKED ISSUE #9060: faucet-helper.sh does not provide enough information to diagnose failures
## Describe the bug
For #9041, [packages/deployment/scripts/integration-test.sh](https://github.com/Agoric/agoric-sdk/blob/master/packages/deployment/scripts/integration-test.sh) invocation of <code>SOLO_COINS=40000000000uist PATH="$thisdir/../bin:$SDK_SRC/bin:$PATH" "$AG_SETUP_COSMOS_HOME/**faucet-helper.sh**" add-egress loadgen "$SOLO_ADDR"</code> produced the following message which was not helpful in issue diagnosis: https://github.com/Agoric/agoric-sdk/actions/runs/8234823417/job/22517489901?pr=9041#step:10:2536
```
Error: EOF: tx parse error
Usage:
  agd tx broadcast [file_path] [flags]

Flags:
  -a, --account-number uint      The account number of the signing account (offline mode only)
      --aux                      Generate aux signer data instead of sending a tx
  -b, --broadcast-mode string    Transaction broadcasting mode (sync|async|block) (default "sync")
      --dry-run                  ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it (when enabled, the local Keybase is not accessible)
      --fee-granter string       Fee granter grants fees for the transaction
      --fee-payer string         Fee payer pays fees for the transaction instead of deducting from the signer
      --fees string              Fees to pay along with transaction; eg: 10uatom
      --from string              Name or address of private key with which to sign
      --gas string               gas limit to set per-transaction; set to "auto" to calculate sufficient gas automatically. Note: "auto" option doesn't always report accurate results. Set a valid coin value to adjust the result. Can be used instead of "fees". (default 200000)
      --gas-adjustment float     adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored  (default 1)
      --gas-prices string        Gas prices in decimal format to determine the transaction fee (e.g. 0.1uatom)
      --generate-only            Build an unsigned transaction and write it to STDOUT (when enabled, the local Keybase only accessed when providing a key name)
  -h, --help                     help for broadcast
      --keyring-backend string   Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
      --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
      --ledger                   Use a connected Ledger device
      --node string              <host>:<port> to tendermint rpc interface for this chain (default "tcp://localhost:26657")
      --note string              Note to add a description to the transaction (previously --memo)
      --offline                  Offline mode (does not allow any online functionality)
  -o, --output string            Output format (text|json) (default "json")
  -s, --sequence uint            The sequence number of the signing account (offline mode only)
      --sign-mode string         Choose sign mode (direct|amino-json|direct-aux), this is an advanced feature
      --timeout-height uint      Set a block timeout height to prevent the tx from being committed past a certain height
      --tip string               Tip is the amount that is going to be transferred to the fee payer on the target chain. This flag is only valid when used with --aux, and is ignored if the target chain didn't enable the TipDecorator
  -y, --yes                      Skip tx broadcasting prompt confirmation

Global Flags:
      --chain-id string     The network chain ID
      --home string         directory for config and data (default "/home/runner/.agoric")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors

Failed to append [
  {
    "@type": "/cosmos.bank.v1beta1.MsgSend",
    "from_address": "agoric1e4zr9xsxaqua05stzxlsd2c5eh70xlxl6u5l5a",
    "to_address": "agoric1gqxzwnc40yxxxsxd209n7pd89xyr9zljzmwwdp",
    "amount": [
      {
        "denom": "uist",
        "amount": "40000000000"
      }
    ]
  }
]
to {"body":{"messages":[{"@type":"/agoric.swingset.MsgProvision","nickname":"loadgen","address":"agoric1gqxzwnc40yxxxsxd209n7pd89xyr9zljzmwwdp","power_flags":[],"submitter":"agoric1e4zr9xsxaqua05stzxlsd2c5eh70xlxl6u5l5a"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"600000","payer":"","granter":""},"tip":null},"signatures":[]}
```

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #9060
Ref d13427ce59618b9dafcdd490a8d57db24df075e4

## Description

Improves the error output of packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh.

### Security Considerations

n/a

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

Further improvements may be warranted, but this covers the confusing failures we've seen so far.

### Upgrade Considerations

n/a

### CODE REVIEW

File: packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh [hunk 1]
```diff
@@ -78,14 +78,14 @@ while [[ ${#rpcAddrs[@]} -gt 0 ]]; do
         msg1='[]'
       fi
       txfile="/tmp/faucet.$$.json"
+      signedtxfile="/tmp/faucet.$$.signed.json"
       trap 'rm -f "$txfile"' EXIT
```
Comment (michaelfig) [inline packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh]: We should clean up the signed tx file on exit also.
```suggestion
      trap 'rm -f "$txfile" "$signedtxfile"' EXIT
```

**Review by michaelfig — APPROVED** [review]
Just one nit; a tiny tmpfile resource leak.  Otherwise, LGTM!
