### PR TITLE
7313 enforce min initial debt

### LINKED ISSUE #7313: the MinInitialDebt parameter is ignored
## Describe the bug

Opening a vault with less debt than MinInitialDebt does not fail.

## Expected behavior

If the vault opening offer doesn't create sufficient debt then the vault should not fail with an error message: "Below Minimum - You need to mint a minimum of X IST to create a vault" per @otoole-brendan 

## Additional context

There is a `MinInitialDebt` test in test-vaultFactory.js but it is testing _maximum_ debt: https://github.com/Agoric/agoric-sdk/blob/841a7012831166f6c29f00bdffc907f2b35a7b0c/packages/inter-protocol/test/vaultFactory/test-vaultFactory.js#L1563

### PR DESCRIPTION
**Pull request by turadg**
closes: #7313

## Description

Enforces `MinInitialDebt` in the vaultFactory contract.

This compares it to the _want_ rather than the post-fee debt. Please confirm that's acceptable @otoole-brendan .

### Security Considerations

--

### Scaling Considerations

--

### Documentation Considerations

EC may need some guide on what this parameter is used for and that it's checked against the _want_ rather than the actual initial debt. (Or if the code is changed to the latter, then documented as such.)

### Testing Considerations

CI

### CODE REVIEW

File: packages/inter-protocol/src/vaultFactory/vaultDirector.js [hunk 1]
```diff
@@ -366,10 +366,14 @@ export const prepareVaultDirector = (
           const factoryPowers = Far('vault factory powers', {
             getGovernedParams: () =>
               Far('vault manager param manager', {
+                // one param from director scope
```
Comment (samsiegart) [inline packages/inter-protocol/src/vaultFactory/vaultDirector.js:369]: I don't understand the significance of this, is there a hazard here?

**Review by samsiegart — APPROVED** [review]
I prefer having the `want` be a nice round number as is the case with what you have. Rather than post-fee debt being e.g. 5 IST and the minimum want being e.g. 4.9751... IST

File: packages/inter-protocol/src/vaultFactory/vaultDirector.js (hunk 1 above)
Comment (turadg) [reply packages/inter-protocol/src/vaultFactory/vaultDirector.js:369]: Not a runtime hazard but the Far says it's a "vault manager param manager" and while it has all the "vault manager" params it has exactly one param from the director scope.
