### PR TITLE
fix latest NPM packages

### LINKED ISSUE #8380: agoric-upgrade-11 NPM packages fail getting started steps
## Describe the bug

The new `latest` / `agoric-upgrade-11` NPM release missed backporting some fixes and uncovered new issues when testing Getting Started (card store version).

In particular, existing fixes:
- missing [fix to `@agoric/swingset-liveslots`](https://github.com/Agoric/agoric-sdk/commit/1ab049437bdbf196d110ed69c901313daae37ee6) from #7921
- missing [fix to `@agoric/eslint-config`](https://github.com/Agoric/agoric-sdk/commit/379277e777f6c69c1f23ed9aa7dc04d4c25a8b8d) from #7922
- #8322: The wallet factory does not actually support starting (just upgrading)

New uncovered issues
- https://github.com/babel/babel/issues/15995: New override mistakes with some `@babel` package versions entrained by `@endo/bundle-source`
- The wallet UI exposed by ag-solo (port 8000), fails to load because of a bad resolution (tries to lookup in `dapp-foo/node_modules/node_modules/@agoric/wallet-ui/build/index.html`)

## To Reproduce
Follow getting started with `npx agoric@latest install latest`

## Expected behavior
Can build / start UI and wallet

## Platform Environment
NPM `latest` / `agoric-upgrade-11`

### PR DESCRIPTION
**Pull request by mhofman**
Fixes #8380

## Description

Follow up to #8360 and #8374. The new NPM packages were not sufficient to get our partner to test a dapp as expected. This PR cherry picks a few more existing and new fixes that were needed. It was not 100% sufficient to run without an agoric-sdk checkout because of their reliance of a cosmos based testnet (see #8033), and makefile targets in `cosmic-swingset`, however that's a separate issue.

This PR is constructed with the following git-rebase-todo

```
# Pull Request #8322
pick 97cb7158f fix(walletFactory): move upgrading check before baggage is populated (#8322)

# Pull Request #8351
pick 9f89f97d4 feat: puppetGovernor pass the Issuerkeywordrecord through (#8351)

# Partial Pull Request #7921
pick 1ab049437 build: export tools from swingset-liveslots

# Partial Pull Request #7922
pick 379277e77 fix: export of eslint-config.cjs

# Branch Agoric-mhofman-fix-solo-wallet-ui
label base-Agoric-mhofman-fix-solo-wallet-ui
pick c57885107 fix(solo): correct lookup of wallet-ui
pick 1ac063e79 fix(wallet): don't assume node_modules layout
label Agoric-mhofman-fix-solo-wallet-ui
reset base-Agoric-mhofman-fix-solo-wallet-ui
merge -C bf2e680e7 Agoric-mhofman-fix-solo-wallet-ui # Merge pull request #8392 from Agoric/mhofman/fix-solo-wallet-ui

# Branch Agoric-mhofman-workaround-babel-override-mistake
label base-Agoric-mhofman-workaround-babel-override-mistake
pick 584ec6248 fix(solo): use alternative endo init
pick 877c1a13d fix(internal): severe override taming for bundle-source
label Agoric-mhofman-workaround-babel-override-mistake
reset base-Agoric-mhofman-workaround-babel-override-mistake
merge -C 1831bf3fd Agoric-mhofman-workaround-babel-override-mistake # Merge pull request #8391 from Agoric/mhofman/workaround-babel-override-mistake
```

### Security Considerations

This PR picks a change switching the override and error taming of the solo to a severe/unsafe mode respectively. This should be safe as only our trusted code should be impacted.

### Scaling Considerations

None

### Documentation Considerations

None

### Testing Considerations

Verified these changes applied as patches are sufficient to get KREAd working with their testing flow.

### Upgrade Considerations

Only a wallet factory change affects runtime code, however it's only to make it compatible with both a bootstrap and upgrade start, and safe to include even though not technically 100% matching of the code that was deployed in the core eval, but that's what the tag is for. No other contract code is affected.

### CODE REVIEW

File: packages/internal/src/node/createBundles.js [hunk 1]
```diff
@@ -29,7 +30,13 @@ export const createBundlesFromAbsolute = async sourceBundles => {
...
   for (const args of cacheToArgs.values()) {
     console.log(BUNDLE_SOURCE_PROGRAM, ...args);
-    const { status } = spawnSync(prog, args, { stdio: 'inherit' });
+    const env = /** @type {NodeJS.ProcessEnv} */ (
+      /** @type {unknown} */ ({
+        __proto__: process.env,
+        LOCKDOWN_OVERRIDE_TAMING: 'severe',
+      })
+    );
+    const { status } = spawnSync(prog, args, { stdio: 'inherit', env });
```
Comment (gibson042) [inline packages/internal/src/node/createBundles.js:39]: TIL that `spawnSync` etc. walk the prototype chain for `env`. A comment explaining the insertion of `LOCKDOWN_OVERRIDE_TAMING: 'severe'` would be nice, but I understand that this is cherry-picking.

**Review by gibson042 — APPROVED** [review]
The changes look reasonable, and I confirm that the claimed git-rebase-todo is able to produce the resulting commit history and file state.

```
# Pull Request #8322
pick 97cb7158f fix(walletFactory): move upgrading check before baggage is populated (#8322)

# Pull Request #8351
pick 9f89f97d4 feat: puppetGovernor pass the Issuerkeywordrecord through (#8351)

# Partial Pull Request #7921
pick 1ab049437 build: export tools from swingset-liveslots

# Partial Pull Request #7922
pick 379277e77 fix: export of eslint-config.cjs

# Branch Agoric-mhofman-fix-solo-wallet-ui
label base-Agoric-mhofman-fix-solo-wallet-ui
pick c57885107 fix(solo): correct lookup of wallet-ui
pick 1ac063e79 fix(wallet): don't assume node_modules layout
label Agoric-mhofman-fix-solo-wallet-ui
reset base-Agoric-mhofman-fix-solo-wallet-ui
merge -C bf2e680e7 Agoric-mhofman-fix-solo-wallet-ui # Merge pull request #8392 from Agoric/mhofman/fix-solo-wallet-ui

# Branch Agoric-mhofman-workaround-babel-override-mistake
label base-Agoric-mhofman-workaround-babel-override-mistake
pick 584ec6248 fix(solo): use alternative endo init
pick 877c1a13d fix(internal): severe override taming for bundle-source
label Agoric-mhofman-workaround-babel-override-mistake
reset base-Agoric-mhofman-workaround-babel-override-mistake
merge -C 1831bf3fd Agoric-mhofman-workaround-babel-override-mistake # Merge pull request #8391 from Agoric/mhofman/workaround-babel-override-mistake
```
