### PR TITLE
fix(cosmic-swingset)!: Extend and partition cosmos-sdk configuration for cosmic-swingset

### LINKED ISSUE #9946: Cosmos init action may contain non-consensus data
## What is the Problem Being Solved?

The cosmos init action is currently included as-is as the `bootMsg` passed in the bootstrap vat's parameters. As a message queued in swingset, it affects consensus.

However some fields in the init action (e.g. the ports) may not have determinism guarantees, and we're considering adding a `swingsetConfig` field to the init action to support #9386 and #9574

## Description of the Design

A clear separation in the init message between consensus data that should end up in `bootMsg` and non-consensus data that should not.

## Security Considerations

Maintain consensus

## Scaling Considerations

None

## Test Plan

Bootstrapping a multinode chain with different local swingset config or other locally decided fields

## Upgrade Considerations

None

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #9946

## Description
* Share runtime cosmos-sdk [viper] configuration with cosmic-swingset in the AG_COSMOS_INIT message
* Exclude non-consensus configuration from bootstrap vat arguments

### Security Considerations
I believe that cosmic-swingset should be considered as a peer of the Go parts of agd, and thus entitled to full runtime configuration. If we have reason to consider it otherwise, then filtering will be warranted.

### Scaling Considerations
This increases the size of AG_COSMOS_INIT messages by up to several KB (but those messages are one-per-process-start).

### Documentation Considerations
We'll want cross-referencing of any config values that are accessed by cosmic-swingset.

### Testing Considerations
TBD

### Upgrade Considerations
This changes the bootstrap vat arguments (which are subject to consensus) for any new chain instance to exclude the "port" settings. However, it should not affect any existing chain, and the bootstrap vat does not use that configuration.

### CODE REVIEW

File: golang/cosmos/app/app.go [hunk 1]
```diff
@@ -350,6 +361,10 @@ func NewAgoricApp(
 		tkeys:             tkeys,
 		memKeys:           memKeys,
 	}
+	// The VM is entitled to full awareness of runtime configuration.
```
Comment (michaelfig) [inline golang/cosmos/app/app.go]: Can you explain here what it means for `resolvedConfig` to be "subject to consensus" as described in `chain-main.js`?

IIUC, `appOpts` can contain outside-of-consensus validator configuration, just one example of which is `minimum-gas-prices`, as well as several others set by `agd start` command line flags or the files in `~/.agoric/config/*.toml`.

I think what this PR actually does is a good thing (by including more inside- and outside-of-consensus parameters for cosmic-swingset to act on); I am just confused by the comments that seem to be implying something stricter than what I see implemented.

**Review by michaelfig — APPROVED** [review]
I'd like to be sure this PR "does what it says on the tin", which I think would be solved by updating the comments describing it.

**Review by michaelfig — APPROVED** [review]
I'd like to be sure this PR "does what it says on the tin", which I think would be solved by updating the comments describing it.

Other than that minor detail, this LGTM!

**Review by siarhei-agoric — APPROVED** [review]
Ship it!

File: golang/cosmos/app/app.go (hunk 1 above)
Comment (gibson042) [reply golang/cosmos/app/app.go]: `resolvedConfig` should definitely *not* have been included in `bootMsg`, that was a bug on my part. Fixed now, which I hope resolves your misunderstanding.

File: packages/cosmic-swingset/src/launch-chain.js [hunk 2]
```diff
@@ -724,33 +731,16 @@ export async function launch({
...
+  function withErrorLogging(label, fn, onSettled) {
     const p = fn();
-    // Just attach some callbacks, but don't use the resulting neutered result
-    // promise.
-    void E.when(p, finish, e => {
-      // None of these must fail, and if they do, log them verbosely before
-      // returning to the chain.
-      blockManagerConsole.error(type, 'error:', e);
-      finish();
+    void E.when(p, onSettled, err => {
```
Comment (mhofman) [inline packages/cosmic-swingset/src/launch-chain.js:740]: I'm surprised that the previous `finish` took care of returning `res` just for getting `void`ed here. We probably should review the whole composition of this thing.

File: packages/cosmic-swingset/src/chain-main.js [hunk 3]
```diff
@@ -64,6 +64,35 @@ const toNumber = specimen => {
...
+    params,
+    supplyCoins,
+    upgradeDetails,
+  } = initAction;
+  return {
+    type,
+    blockTime,
+    blockHeight,
+    chainID,
+    isBootstrap,
```
Comment (mhofman) [inline packages/cosmic-swingset/src/chain-main.js]: I don't see a reason why `isBootstrap` would be useful in the `bootMsg`. We can likely can drop it.

File: packages/cosmic-swingset/src/chain-main.js [hunk 4]
```diff
@@ -64,6 +64,35 @@ const toNumber = specimen => {
...
+    params,
+    supplyCoins,
+    upgradeDetails,
```
Comment (mhofman) [inline packages/cosmic-swingset/src/chain-main.js]: I am wondering whether `upgradeDetails` should be included in `bootMsg`. While a chain upgrade may technically bootstrap swingset (hello psm and bulldozer), I'm not sure we have the wiring correct to run any core proposals from the `upgradeDetails` in that case. Regardless, I would not expect the bootstrap vat to take on the responsibility to parse the `upgradeDetails`.

File: golang/cosmos/app/app.go [hunk 5]
```diff
@@ -359,6 +361,10 @@ func NewAgoricApp(
...
+	if resolvedConfig, ok := appOpts.(*viper.Viper); ok {
+		app.resolvedConfig = resolvedConfig.AllSettings()
+	}
```
Comment (mhofman) [inline golang/cosmos/app/app.go]: I would strongly prefer to carve out a subsection of the app config, likely named "swingset" and only pass that section through. I agree that JS and golang can share that subsection, but I really don't see a reason to overexpose the full cosmos config to JS.

**Review by mhofman — COMMENTED** [review]
Some preliminary observations. I have a larger question as to the scope of this PR that I'll take offline.

File: golang/cosmos/app/app.go (hunk 5 above)
Comment (gibson042) [reply golang/cosmos/app/app.go]: I'm convinced. Updated.

**Comment by gibson042** [comment]
@mhofman @siarhei-agoric I've updated this to read and propagate a `[swingset]` config section, with the first supported entry being `slogfile` to validate that it actually works.

@siarhei-agoric For #9574, you'll want to update golang/cosmos/x/swingset/config.go and then read in the value from the `resolvedConfig` property of the `initAction` object passed to `launchAndInitializeSwingSet` (see the top of that function in this PR for a template).

File: golang/cosmos/daemon/cmd/root.go [hunk 6]
```diff
@@ -99,24 +119,30 @@ func initTendermintConfig() *tmcfg.Config {
...
+	// FIXME: We may want a non-zero min gas price.
+	// For now, we set it to zero to reduce friction (the default "" fails
+	// startup, forcing each validator to set their own value).
 	srvCfg.MinGasPrices = "0uist"
 
-	return serverconfig.DefaultConfigTemplate, *srvCfg
+	// CustomAppConfig extends the base config struct.
+	type CustomAppConfig struct {
+		serverconfig.Config `mapstructure:",squash"`
+		Swingset            *swingset.SwingsetConfig `mapstructure:"swingset"`
```
Comment (mhofman) [inline golang/cosmos/daemon/cmd/root.go]: Maybe add a comment this `"swingset"` here should match `swingset.ConfigPrefix` ?

File: golang/cosmos/daemon/cmd/root.go [hunk 7]
```diff
@@ -144,10 +170,27 @@ func initRootCmd(sender vm.Sender, rootCmd *cobra.Command, encodingConfig params
...
+				}
+				if err = baseConfig.ValidateBasic(); err != nil {
+					return err
+				}
+				if _, err = swingset.SwingsetConfigFromViper(viper); err != nil {
+					return err
+				}
+				return nil
+			}
+			appendToPreRunE(command, preRunE)
```
Comment (mhofman) [inline golang/cosmos/daemon/cmd/root.go:195]: I'm surprised there isn't a better way to hook to validate custom config. Why not parse / validate the config in the `appCreator` ? We already cast `appOpts` to the `Viper` instance anyway. I would also expect the swingset config to be parsed for other commands, like snapshot restores, since that involves cosmic-swingset as well.

File: golang/cosmos/x/swingset/config.go [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+	FlagSlogfile = "swingset.slogfile"
+)
+
+// DefaultConfigTemplate defines a default TOML configuration section for the SwingSet VM.
+// See https://github.com/cosmos/cosmos-sdk/issues/20097 for auto-synchronization ideas.
+const DefaultConfigTemplate = `
+
+	[swingset]
+	# slogfile is the absolute path at which a SwingSet log "slog" file should be written.
+	slogfile = ""
```
Comment (mhofman) [inline golang/cosmos/x/swingset/config.go]: Nit: an absolute file path is kinda weird, wondering if we could somehow resolve it relative to the home dir

File: golang/cosmos/app/app.go [hunk 9]
```diff
@@ -963,10 +978,16 @@ func (app *GaiaApp) initController(ctx sdk.Context, bootstrap bool) {
 	app.controllerInited = true
 
 	// Begin initializing the controller here.
+	var swingsetConfig map[string]any
+	if resolvedConfig, ok := app.resolvedConfig.(*viper.Viper); ok {
+		swingsetSection := resolvedConfig.AllSettings()[swingset.ConfigPrefix]
+		swingsetConfig, _ = swingsetSection.(map[string]any)
+	}
```
Comment (mhofman) [inline golang/cosmos/app/app.go]: Why is this not using `SwingsetConfigFromViper` in any way?

I don't see how any resolutions that may be performed would be carried here without it.

File: golang/cosmos/app/app.go [hunk 10]
```diff
@@ -929,9 +941,12 @@ type cosmosInitAction struct {
 	vm.ActionHeader `actionType:"AG_COSMOS_INIT"`
 	ChainID         string          `json:"chainID"`
 	IsBootstrap     bool            `json:"isBootstrap"`
-	UpgradeDetails  *upgradeDetails `json:"upgradeDetails,omitempty"`
 	Params          swingset.Params `json:"params"`
-	SupplyCoins     sdk.Coins       `json:"supplyCoins"`
+	// ResolvedConfig is the subset of complete config that is relevant to the VM.
+	// It is a superset of swingset.SwingsetConfig.
```
Comment (mhofman) [inline golang/cosmos/app/app.go]: How is it a superset?

File: golang/cosmos/x/swingset/config.go [hunk 11]
```diff
@@ -0,0 +1,45 @@
...
+const (
+	ConfigPrefix = "swingset"
+	FlagSlogfile = "swingset.slogfile"
+)
+
+// DefaultConfigTemplate defines a default TOML configuration section for the SwingSet VM.
+// See https://github.com/cosmos/cosmos-sdk/issues/20097 for auto-synchronization ideas.
+const DefaultConfigTemplate = `
+
+	[swingset]
```
Comment (mhofman) [inline golang/cosmos/x/swingset/config.go]: Is the indentation here expected?

**Review by mhofman — COMMENTED** [review]
I'm still thinking through the plumbing but overall I'm happy to see the narrower config approach. Given that I'm expecting to see some options being "resolved" from their raw value to a value directly usable by cosmic-swingset (e.g. default artifact pruning), I'm wondering how the current plumbing supports that.

> with the first supported entry being slogfile to validate that it actually works.

That's a great idea, and I think we should resolve this value as relative to the home folder if not absolute, showing how transform of raw values in the config might work.

Btw, I just realized another example candidate option might be a temp folder to use for the JS side of state-sync, but the plumbing of that might be more difficult (there is no affordance for this on the JS side currently). There is actually an open issue for that: #8629

File: golang/cosmos/app/app.go (hunk 10 above)
Comment (gibson042) [reply golang/cosmos/app/app.go]: Right now it's a superset only in the trivial sense, but we know that cosmic-swingset _will_ need data that's not under `[swingset]` (at which point it will be a strict superset), so I just documented that now.

File: golang/cosmos/app/app.go (hunk 9 above)
Comment (gibson042) [reply golang/cosmos/app/app.go]: This is trivial right now, but I'm expecting to replace it with use of a function that will probably be defined in config.go. But it won't be `SwingsetConfigFromViper`, because that function is limited to the `[swingset]` section whereas this future one will be consuming full configuration and emitting the superset.

File: golang/cosmos/daemon/cmd/root.go (hunk 7 above)
Comment (gibson042) [reply golang/cosmos/daemon/cmd/root.go:195]: `appCreator` would be great, but doesn't have an error return so we're limited to `panic` and `return nil`. But this pattern can also be applied to other commands if need be.

File: golang/cosmos/x/swingset/config.go (hunk 11 above)
Comment (gibson042) [reply golang/cosmos/x/swingset/config.go]: probably not, but https://github.com/rollchains/tiablob/blob/main/tiasync/config.go has it too. I'll drop it.

File: golang/cosmos/x/swingset/config.go (hunk 8 above)
Comment (gibson042) [reply golang/cosmos/x/swingset/config.go]: I'm not sure that's a great referent. And we can always relax this later.

Comment (mhofman) [reply golang/cosmos/x/swingset/config.go]: When I mentioned home dir, it's the cosmos home dir, aka `~/.agoric` by default. Why wouldn't that be a good referent?

File: golang/cosmos/app/app.go (hunk 10 above)
Comment (mhofman) [reply golang/cosmos/app/app.go]: I'm curious as to what "config" options would be purely generated instead of resolved.

File: golang/cosmos/x/swingset/config.go [hunk 12]
```diff
@@ -0,0 +1,45 @@
...
+	FlagSlogfile = "swingset.slogfile"
+)
+
+// DefaultConfigTemplate defines a default TOML configuration section for the SwingSet VM.
+// See https://github.com/cosmos/cosmos-sdk/issues/20097 for auto-synchronization ideas.
+const DefaultConfigTemplate = `
+
+[swingset]
+# slogfile is the absolute path at which a SwingSet log "slog" file should be written.
+slogfile = ""
```
Comment (mhofman) [inline golang/cosmos/x/swingset/config.go]: Why not use the template to apply the default value here? I don't expect it'll ever change but that'd be a good example for other configs

```suggestion
slogfile = "{{ .Swingset.SlogFile }}"
```

It does require more weird coupling between the naming in this file and the config in `root.go` however.

File: golang/cosmos/daemon/cmd/root.go [hunk 13]
```diff
@@ -99,24 +119,31 @@ func initTendermintConfig() *tmcfg.Config {
...
+	// For now, we set it to zero to reduce friction (the default "" fails
+	// startup, forcing each validator to set their own value).
 	srvCfg.MinGasPrices = "0uist"
 
-	return serverconfig.DefaultConfigTemplate, *srvCfg
+	// CustomAppConfig extends the base config struct.
+	type CustomAppConfig struct {
+		serverconfig.Config `mapstructure:",squash"`
+		// Swingset must use a mapstructure key matching swingset.ConfigPrefix.
+		Swingset            *swingset.SwingsetConfig `mapstructure:"swingset"`
```
Comment (mhofman) [inline golang/cosmos/daemon/cmd/root.go]: Out of curiosity, why use a pointer for the SwingsetConfig? It seems that all of the cosmos-sdk examples inline the struct.

File: golang/cosmos/x/swingset/config.go [hunk 14]
```diff
@@ -0,0 +1,45 @@
...
+type SwingsetConfig struct {
+	// SlogFile is the absolute path at which a SwingSet log "slog" file should be written.
+	SlogFile string `mapstructure:"slogfile"`
+}
+
+var DefaultSwingsetConfig = SwingsetConfig{
+	SlogFile: "",
+}
+
+func SwingsetConfigFromViper(viper *viper.Viper) (*SwingsetConfig, error) {
```
Comment (mhofman) [inline golang/cosmos/x/swingset/config.go]: I'm confused why this method returns a SwingsetConfig object if it isn't used anywhere.

Edit: I would also have thought it could use `v.Unmarshal` somehow.

File: golang/cosmos/daemon/cmd/root.go (hunk 7 above)
Comment (mhofman) [reply golang/cosmos/daemon/cmd/root.go:195]: Yeah it's really weird that `appCreator` doesn't get to return an error. Especially because the callers have an error returning path. It's unfortunate that it forces us to further intercept commands.

I'm wondering if it wouldn't be better to call this in our `PersistentPreRunE`, right after calling `server.InterceptConfigsPreRunHandler`, since that's what finishes all the config stuff, and looking at the internals of cobra, is called immediately before the intercepted `PreRunE` here.

Comment (gibson042) [reply golang/cosmos/daemon/cmd/root.go:195]: PersistentPreRunE also applies to client commands like `agd query`, for which it would be inappropriate to validate server config.

**Review by siarhei-agoric — APPROVED** [review]
Looks good to me!

File: golang/cosmos/x/swingset/config.go (hunk 8 above)
Comment (gibson042) [reply golang/cosmos/x/swingset/config.go]: > When I mentioned home dir, it's the cosmos home dir, aka ~/.agoric by default. Why wouldn't that be a good referent?

For starters, because I think we have multiple poorly-explained concepts of "home dir"—distinct from cosmos-sdk `FlagHome` [--home] but used to set its default value is our golang/cosmos/app/app.go `DefaultNodeHome` "_default home directories for the application daemon_", which is initialized to ~/.agoric but set to ~/.ag-chain-cosmos by `RunAgCosmosDaemon` for the goroutine that runs inside Node.js. Our app initialization uses `FlagHome` (including to set the default SwingStoreExportDir to ./config/swing-store underneath that), but most other code uses `DefaultNodeHome` (_including the syscall.Exec that replaces agd with Node.js ag-chain-cosmos, which I just realized is a bug because `agd --home=/path/to/dir start` → `ag-chain-cosmos --home ~/.agoric --home /path/to/dir start` ✔ but `AGD_HOME=/path/to/dir agd start` → `ag-chain-cosmos --home ~/.agoric start` ✘_).

But beyond that, because interpretation of relative paths in config files is just inherently confusing unless very well explained (and generally best when relative to the file itself). But I will add support for interpretation relative to current directory for values specified dynamically via e.g. environment variable.

File: golang/cosmos/app/app.go (hunk 10 above)
Comment (gibson042) [reply golang/cosmos/app/app.go]: I was thinking of global settings like `--moniker`, `--log_level`, and `--log_format`, but I guess even if we did want those they'd be communicated at invocation rather than in the AG_COSMOS_INIT message. I'll simplify.

File: golang/cosmos/x/swingset/config.go (hunk 8 above)
Comment (mhofman) [reply golang/cosmos/x/swingset/config.go]: Yeah the handling of the `home` env/flag could be improved, but besides that, it really seems that every relative path in the config is resolved from that folder. For example, take the `add_book_file`, `node_key_file`, `genesis_file` etc. from `config.toml`. They are all relative to the cosmos home dir. In `app.toml`, the `streamers.file.write_dir` is also resolved relative to the home dir: https://github.com/agoric-labs/cosmos-sdk/blob/2c7e4030ee73d926bb979460fcab1cd769d93bd9/store/streaming/constructor.go#L101-L104

File: golang/cosmos/daemon/cmd/root.go (hunk 7 above)
Comment (mhofman) [reply golang/cosmos/daemon/cmd/root.go:195]: Good call!

File: golang/cosmos/x/swingset/config.go (hunk 8 above)
Comment (gibson042) [reply golang/cosmos/x/swingset/config.go]: OK, that's persuasive. Done.

File: golang/cosmos/app/app.go (hunk 9 above)
Comment (gibson042) [reply golang/cosmos/app/app.go]: Update: It _is_ now `SwingsetConfigFromViper`.

File: golang/cosmos/x/swingset/config.go (hunk 12 above)
Comment (gibson042) [reply golang/cosmos/x/swingset/config.go]: Done.

File: golang/cosmos/daemon/cmd/root.go (hunk 13 above)
Comment (gibson042) [reply golang/cosmos/daemon/cmd/root.go]: Updated.

**Review by mhofman — APPROVED** [review]
Thanks for all these changes!

with the `SLOGFILE` env, this definitely ended up more complicated than I expected. There's probably some refactoring and tests that we could add for the config resolution function, but that can be done later.

**Comment by gibson042** [comment]
> with the `SLOGFILE` env, this definitely ended up more complicated than I expected. There's probably some refactoring and tests that we could add for the config resolution function, but that can be done later.

Yeah, likewise. I guess it was actually a really good starting point.

File: golang/cosmos/x/swingset/config.go [hunk 15]
```diff
@@ -0,0 +1,100 @@
...
+		if resolvedConfig.Get(flags.FlagHome) != nil {
+			return nil, fmt.Errorf("expected an instance of viper!")
+		}
+	}
+	if v == nil {
+		return nil, nil
+	}
+	v.MustBindEnv(FlagSlogfile, "SLOGFILE")
+	wrapper := struct{ Swingset SwingsetConfig }{}
+	v.Unmarshal(&wrapper)
```
Comment (mhofman) [inline golang/cosmos/x/swingset/config.go]: lint seems to be complaining about return value check
