### PR TITLE
Harmonise `core/boot-psm.js` with `core/boot.js`

### LINKED ISSUE #6490: how to get to PSM contract from repl / deploy script?
## Describe the bug

 @thisispalash is working on #5822 and he asked me how his code can talk to the PSM contract. I'm struggling to find a way.

## To Reproduce

1. check out the community-dev branch
2. agoric init; agoric start; agoric open --repl
3. try to look up the PSM and amm
4. find amm but no PSM:

```
command[16] E(home.agoricNames).lookup('instance', 'psm')
history[16] unresolved Promise
command[17] E(home.agoricNames).lookup('instance', 'amm')
history[17] [Object Alleged: InstanceHandle]{}
```

It looks like `decentral-demo-config.json` doesn't start the PSM.

## Expected behavior

PSM contract started in an environment where  @thisispalash can get at it.

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

```
$ git describe --tags --always
agoricxnet-7-412-g3482e0d98
```

## Additional context
community-dev branch

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #6490
#loadgen-branch: mfig-diagnostics

## Description

Merge the changes from the `core/boot-psm.js` mechanism used in the first Agoric VM deployment with the manifest-based `core/boot.js` system.

### Testing Considerations

The `devnet` configuration is now tested by the cosmic-swingset integration tests.

### CODE REVIEW

**Comment by dckc** [comment]
I tried the steps to reproduce from #6490 ; it doesn't look fixed.

```
command[9] E(home.agoricNames).lookup('instance', 'psm')
history[9] Promise.reject("Error: \"nameKey\" not found: (a string)")
```

**Comment by michaelfig** [comment]
> I tried the steps to reproduce from #6490 ; it doesn't look fixed.
> 
> ```
> command[9] E(home.agoricNames).lookup('instance', 'psm')
> history[9] Promise.reject("Error: \"nameKey\" not found: (a string)")
> ```

Ahh, yes.  That's because there's an instance per brand pair.  Try `E(E(home.agoricNames).lookup('instance')).entries()`

File: packages/cosmic-swingset/Makefile [hunk 1]
```diff
@@ -143,12 +143,9 @@ scenario2-run-chain-economy: t1/decentral-economy-config.json
...
 		$(MAKE) scenario2-run-chain
 
-scenario2-run-chain-psm: ../vats/decentral-psm-config.json
-	CHAIN_BOOTSTRAP_VAT_CONFIG="$$PWD/../vats/decentral-psm-config.json" \
-		$(MAKE) scenario2-run-chain
-
-scenario2-run-chain:
-	OTEL_EXPORTER_PROMETHEUS_PORT=$(OTEL_EXPORTER_PROMETHEUS_PORT) \
+scenario2-run-chain: ../vats/decentral-devnet-config.json
+	CHAIN_BOOTSTRAP_VAT_CONFIG="$$PWD/../vats/decentral-devnet-config.json" \
```
Comment (turadg) [inline packages/cosmic-swingset/Makefile]: a little surprising to have this default to devnet. consider a comment to call it out and say why

File: packages/inter-protocol/scripts/init-core.js [hunk 2]
```diff
@@ -71,15 +71,16 @@ const installKeyGroups = {
...
-  install: install0,
-  wrapInstall,
-}) => {
-  const { ROLE = 'chain' } = process.env;
+export const committeeProposalBuilder = async (
+  { publishRef, install: install0, wrapInstall },
+  options = {},
+  { env = process.env } = {},
+) => {
+  const { ROLE = env.ROLE || 'chain', econCommitteeOptions } = options;
```
Comment (turadg) [inline packages/inter-protocol/scripts/init-core.js]: better to pass `process.env` than rely on ambient authority, but why pass it at all if it can come in through `options.ROLE`? Multiple ways to express the same configuration makes the code harder to follow. It's not apparent without reading `committeeProposalBuilder` that `env.ROLE` is valid or takes precedence over `options.ROLE`.

File: packages/inter-protocol/scripts/init-core.js [hunk 3]
```diff
@@ -71,15 +71,16 @@ const installKeyGroups = {
  * @param {(m: string, b: string, opts?: any) => I} opts.install
  * @param {<T>(f: T) => T} [opts.wrapInstall]
  *
+ * @param options
```
Comment (turadg) [inline packages/inter-protocol/scripts/init-core.js]:
```suggestion
 * @param {{ ROLE: 'chain' | 'whatever else', econCommitteeOptions: ??? }} options
```

File: packages/inter-protocol/src/proposals/committee-proposal.js [hunk 4]
```diff
@@ -58,15 +60,19 @@ export const inviteCommitteeMembers = async (
...
-          E(votingAPI).makeNullInvitation(),
-        ]);
         await reserveThenDeposit(
           `econ committee member ${addr}`,
           namesByAddressAdmin,
           addr,
-          [voterInvitation, nullInvitation],
+          [
+            invitationP,
+            // TODO: This null invitation is used just to identify the
```
Comment (turadg) [inline packages/inter-protocol/src/proposals/committee-proposal.js]: TODO by when? Ticket?

File: packages/inter-protocol/src/proposals/startPSM.js [hunk 5]
```diff
@@ -448,21 +446,36 @@ export const PSM_MANIFEST = harden({
...
+      consume: { [Stable.symbol]: 'zoe' },
     },
   },
 });
 
+export const getManifestForPsmGovernance = (
+  { restoreRef },
+  { installKeys },
+) => {
+  const { [installGovAndPSMContracts.name]: _toss, ...manifest } =
```
Comment (turadg) [inline packages/inter-protocol/src/proposals/startPSM.js]: isn't simply `_` the convention here for ignoring a param?
```suggestion
  const { [installGovAndPSMContracts.name]: _, ...manifest } =
```

File: packages/inter-protocol/src/proposals/utils.js [hunk 6]
```diff
@@ -63,8 +63,16 @@ export const reserveThenDeposit = async (
     [addr, DEPOSIT_FACET],
   ]);
   console.info('depositing to', debugName);
-  await Promise.all(payments.map(payment => E(depositFacet).receive(payment)));
-  console.info('confirmed deposit for', debugName);
+  await Promise.allSettled(
+    payments.map(async (paymentP, i) => {
+      const payment = await paymentP;
+      await E(depositFacet).receive(payment);
+      console.info(
```
Comment (turadg) [inline packages/inter-protocol/src/proposals/utils.js:70]: nice diagnostic info

File: packages/smart-wallet/src/walletFactory.js [hunk 7]
```diff
@@ -36,9 +37,16 @@ export const publishDepositFacet = async (
   namesByAddressAdmin,
 ) => {
   const { nameHub, myAddressNameAdmin } = makeMyAddressNameAdminKit(address);
-  myAddressNameAdmin.update(WalletName.depositFacet, wallet.getDepositFacet());
+  myAddressNameAdmin.reserve(WalletName.depositFacet);
 
-  return E(namesByAddressAdmin).update(address, nameHub, myAddressNameAdmin);
+  // Don't clobber an existing myAddressNameAdmin or deposit facet.
```
Comment (turadg) [inline packages/smart-wallet/src/walletFactory.js]: this will silently fail if `publishDepositFacet` is called a second time and `wallet.getDepositFacet()` changes.

This does seem like an improvement to make it immutable, but shouldn't we error if something tries to change it? At least log?

File: packages/vats/scripts/init-core.js [hunk 8]
```diff
@@ -0,0 +1,30 @@
+import { makeHelpers } from '@agoric/deploy-script-support';
+
+export const defaultProposalBuilder = async ({ publishRef, install }) =>
```
Comment (turadg) [inline packages/vats/scripts/init-core.js:3]: is "default" here meant like "default export" or are there expected to be multiple proposal builders in a module like this?

File: packages/vats/src/core/chain-behaviors.js [hunk 9]
```diff
@@ -146,8 +147,22 @@ export const bridgeProvisioner = async ({
...
-          return E(provisioning)
-            .pleaseProvision(nickname, address, powerFlags)
+          let provisionP;
+          if (powerFlags.includes(PowerFlags.SMART_WALLET)) {
+            // Only provision a smart wallet.
+            provisionP = E(bridgeManager).toBridge(
+              BRIDGE_ID.PROVISION_SMART_WALLET,
+              obj,
+            );
+          } else {
```
Comment (turadg) [inline packages/vats/src/core/chain-behaviors.js:159]: this is assuming the if `SMART_WALLET` isn't in the powerFlags that it should do this. why not validate the contents? I'm thinking the final `else` should be an error for an undefined case

**Comment by dckc** [comment]
> Try `entries()`

I should have been clear: yes, I did that too. There are no PSMs

```
command[5] E(lookup('agoricNames', 'instance')).entries()
history[5] [...]

command[8] h[5].map(([n, _v]) => n)
history[8] ["economicCommittee","amm","ammGovernor","VaultFactory","feeDistributor","Treasury","VaultFactoryGovernor","stakeFactory","stakeFactoryGovernor","Pegasus","reserve","reserveGovernor","psmCharter","interchainPool","provisionPool","walletFactory"]
```

File: packages/smart-wallet/src/walletFactory.js (hunk 7 above)
Comment (dckc) [reply packages/smart-wallet/src/walletFactory.js]: More like it silently succeeds, yes?
This is saying "if there's already one there, leave it alone. Otherwise, use this one"

Comment (turadg) [reply packages/smart-wallet/src/walletFactory.js]: Success or failure depends on the intent ;-)

My point is: if what's already there doesn't match, isn't that a surprise? In what cases would you expect the existing value to be different than the new one?

Comment (dckc) [reply packages/smart-wallet/src/walletFactory.js]: > In what cases would you expect the existing value to be different than the new one?

In case an ag-solo already registered it.

> isn't that a surprise?

Not any longer, IIUC.

**Comment by dckc** [comment]
I see PSMs now:

```
command[0]
E(E(home.agoricNames).lookup('instance')).keys()
history[0]
["economicCommittee","amm","ammGovernor","VaultFactory","feeDistributor","Treasury","VaultFactoryGovernor","stakeFactory","stakeFactoryGovernor","Pegasus","reserve","reserveGovernor","psmCharter","interchainPool","provisionPool","walletFactory","psm-IST-USDC_axl","psm-IST-USDC_grv","psm-IST-USDT_axl","psm-IST-USDT_grv","psm-IST-AUSD"]
```

fyi, @thisispalash

File: packages/vats/src/core/chain-behaviors.js (hunk 9 above)
Comment (michaelfig) [reply packages/vats/src/core/chain-behaviors.js:159]: Can you please be more specific?  What kind of validation do you expect, since the Golang side of things already enforces that `powerFlags` is an array of strings?

File: packages/vats/scripts/init-core.js (hunk 8 above)
Comment (michaelfig) [reply packages/vats/scripts/init-core.js:3]: The `coreProposals` swingset config feature uses `defaultProposalBuilder` by default (i.e. if the config file does not specify a different entrypoint).

File: packages/smart-wallet/src/walletFactory.js (hunk 7 above)
Comment (michaelfig) [reply packages/smart-wallet/src/walletFactory.js]: I'll add documentation to this effect.

File: packages/inter-protocol/scripts/init-core.js (hunk 2 above)
Comment (michaelfig) [reply packages/inter-protocol/scripts/init-core.js]: Turns out `ROLE` was unnecessary.  Removed.

File: packages/inter-protocol/src/proposals/committee-proposal.js (hunk 4 above)
Comment (michaelfig) [reply packages/inter-protocol/src/proposals/committee-proposal.js]: #6598

File: packages/agoric-cli/src/start.js [hunk 10]
```diff
@@ -509,6 +509,30 @@ export default async function startMain(progname, rawArgs, powers, opts) {
         return exitStatus;
       }
     }
+
+    // Create the full economy chain config.
+    const coreConfigPath = path.resolve(
+      'node_modules/@agoric/vats/decentral-core-config.json',
```
Comment (dckc) [inline packages/agoric-cli/src/start.js]: This seems to assume that the current working directory has `node_modules` with the `@agoric/vats` package installed. That seems to be a new assumption. I suppose it's justified by the way `agoric install` works?

Elsewhere I've see a function that resolves paths like `@agoric/vats/decentral-core-config.json`. I'm not sure why we don't use it here.

But I don't feel strongly about it. The whole `agoric-cli` package seems to be a bit of a wild west w.r.t. ocap discipline.

File: packages/vats/decentral-devnet-config.json [hunk 11]
```diff
@@ -83,6 +125,18 @@
...
+    },
+    "network": {
+      "sourceSpec": "@agoric/vats/src/vat-network.js"
+    },
+    "priceAuthority": {
+      "sourceSpec": "@agoric/vats/src/vat-priceAuthority.js"
+    },
+    "provisioning": {
+      "sourceSpec": "@agoric/vats/src/vat-provisioning.js"
+    },
```
Comment (dckc) [inline packages/vats/decentral-devnet-config.json:142]: I suppose this calls for re-opening #5965 to think it over again.

File: packages/vats/decentral-devnet-config.json [hunk 12]
```diff
@@ -83,6 +125,18 @@
...
     },
+    "ibc": {
+      "sourceSpec": "@agoric/vats/src/vat-ibc.js"
+    },
+    "network": {
+      "sourceSpec": "@agoric/vats/src/vat-network.js"
+    },
+    "priceAuthority": {
+      "sourceSpec": "@agoric/vats/src/vat-priceAuthority.js"
+    },
```
Comment (dckc) [inline packages/vats/decentral-devnet-config.json:139]: why does `vat-priceAuthority.js` belong here rather than in a vaults proposal?
(semi-rhetorical; I suppose I could figure it out if I looked around.)

File: packages/vats/decentral-devnet-config.json [hunk 13]
```diff
@@ -83,6 +125,18 @@
     "board": {
       "sourceSpec": "@agoric/vats/src/vat-board.js"
     },
+    "ibc": {
+      "sourceSpec": "@agoric/vats/src/vat-ibc.js"
+    },
+    "network": {
+      "sourceSpec": "@agoric/vats/src/vat-network.js"
+    },
```
Comment (dckc) [inline packages/vats/decentral-devnet-config.json:136]: @ivanlei the [list of vats/contracts](https://github.com/Agoric/agoric-sdk/issues/5014#issuecomment-1309365804) that I put together Nov 9 for planning purposes didn't include these two (ibc, network). I suppose they should be added to the list of things to make upgradeable (#6553). Ah... we already have #5696 for the network vat. I don't know whether we included it in any plans.

File: packages/inter-protocol/scripts/init-core.js (hunk 2 above)
Comment (dckc) [reply packages/inter-protocol/scripts/init-core.js]: Seems to still be there as of 2a2b2881946288ad0c7191

File: packages/inter-protocol/src/proposals/startPSM.js (hunk 5 above)
Comment (dckc) [inline packages/inter-protocol/src/proposals/startPSM.js]: Why are we removing `installGovAndPSMContracts` from the manifest returned by `getManifestForPsmGovernance`? It seems particularly relevant.

File: packages/vats/src/core/startWalletFactory.js [hunk 14]
```diff
@@ -108,7 +108,8 @@ const startGovernedInstance = async (
  * }>} powers
  * @param {{
  *   options?: {
- *     perAccountInitialValue?: bigint
+ *     perAccountInitialValue?: bigint,
+ *     walletBridgeId?: string
```
Comment (dckc) [inline packages/vats/src/core/startWalletFactory.js]:
```suggestion
 *     walletBridgeId?: string,
```

**Review by dckc — APPROVED** [review]
In the interest of addressing #6490 , I'm ready to land this.

It relaxes some constraints that we introduced in `boot-psm.js`, so I re-opened #4165 and  #5965 to re-consider our approach to those.

File: packages/inter-protocol/scripts/init-core.js (hunk 2 above)
Comment (michaelfig) [reply packages/inter-protocol/scripts/init-core.js]: > Seems to still be there

I need to push.  I'll rerequest your review when I do.

File: packages/agoric-cli/src/start.js (hunk 10 above)
Comment (michaelfig) [reply packages/agoric-cli/src/start.js]: The dependency on `node_modules` was ugly and unnecessary, so I've now abstracted it behind `require.resolve`.

File: packages/inter-protocol/src/proposals/startPSM.js (hunk 5 above)
Comment (michaelfig) [reply packages/inter-protocol/src/proposals/startPSM.js]: The `installations` property below subsumes what `installGovAndPSMContracts` does.

File: packages/vats/decentral-devnet-config.json (hunk 12 above)
Comment (michaelfig) [reply packages/vats/decentral-devnet-config.json:139]: `vat-priceAuthority.js` is not a Zoe contract, so doesn't easily fit into the current way proposals are implemented.  But yes, ideally it would be part of a proposal, and we would make a separate decision whether to publish it to solo clients.

File: packages/vats/src/core/chain-behaviors.js [hunk 15]
```diff
@@ -146,9 +147,24 @@ export const bridgeProvisioner = async ({
     async fromBridge(_srcID, obj) {
       switch (obj.type) {
         case 'PLEASE_PROVISION': {
-          const { nickname, address, powerFlags } = obj;
-          return E(provisioning)
-            .pleaseProvision(nickname, address, powerFlags)
+          const { nickname, address, powerFlags: rawPowerFlags } = obj;
+          const powerFlags = rawPowerFlags || [];
```
Comment (dckc) [inline packages/vats/src/core/chain-behaviors.js:151]: don't we usually write it this way?

```suggestion
          const { nickname, address, powerFlags = [] } = obj;
```

File: packages/vats/src/core/chain-behaviors.js [hunk 16]
```diff
@@ -146,9 +147,24 @@ export const bridgeProvisioner = async ({
     async fromBridge(_srcID, obj) {
```
Comment (dckc) [inline packages/vats/src/core/chain-behaviors.js:147]: how does `fromBridge` here relate to the one in `provisionPool.js`? I'd like to see compare/contrast comments on each.

File: packages/vats/src/core/chain-behaviors.js (hunk 15 above)
Comment (dckc) [reply packages/vats/src/core/chain-behaviors.js:151]: - wish: unit test
 - wish: pattern-based dynamic type check on `obj`

File: packages/solo/src/chain-cosmos-sdk.js [hunk 17]
```diff
@@ -690,8 +690,7 @@ ${chainID} chain does not yet know of address ${clientAddr}${adviseEgress(
           console.debug(`helper said: ${stdout}`);
           const out = JSON.parse(stdout);
 
-          out.code ||
-            0 ||
+          out.code === 0 ||
```
Comment (dckc) [inline packages/solo/src/chain-cosmos-sdk.js:693]: yikes. that looks like it was hairy to track down.

wish: unit test

**Review by dckc — APPROVED** [review]
still looks good.

I have a few wishes...

File: packages/vats/src/core/chain-behaviors.js (hunk 15 above)
Comment (michaelfig) [reply packages/vats/src/core/chain-behaviors.js:151]: Turns out that `obj.powerFlags` can be `null`.  The destructuring default values only work if `obj.powerFlags` is `undefined`.

Yeah, the dynamic checks would be better with patterns.

File: packages/vats/src/core/chain-behaviors.js [hunk 18]
```diff
@@ -146,9 +147,24 @@ export const bridgeProvisioner = async ({
...
-          return E(provisioning)
-            .pleaseProvision(nickname, address, powerFlags)
+          const { nickname, address, powerFlags: rawPowerFlags } = obj;
+          const powerFlags = rawPowerFlags || [];
+          let provisionP;
+          if (powerFlags.includes(PowerFlags.SMART_WALLET)) {
+            // Only provision a smart wallet.
+            provisionP = E(bridgeManager).fromBridge(
+              BRIDGE_ID.PROVISION_SMART_WALLET,
+              obj,
```
Comment (mhofman) [inline packages/vats/src/core/chain-behaviors.js:157]: Where does this message actually end up? I do not see any bridge handler registered for it since `boot-psm` sets `walletBridgeId` to `BridgeId.PROVISION`.
